### ISSUE TITLE
Add API models unit tests

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#10008]
Our current unit tests do not include any coverage for the API models.

This issue aims to add new python unit tests for the API models located at [api/models](https://github.com/wazuh/wazuh/tree/master/api/api/models). The new unit tests should cover as much of the code as possible.

Lastly, the added tests should be included in the Jenkins package so the tests are automatically run in every pull request.

## Tasks:

- [x] /api/models/agent_added_model.py
- [x] /api/models/agent_inserted_model.py
- [x] /api/models/basic_info_model.py
- [x] /api/models/logtest_model.py
- [x] /api/models/security_token_response_model.py
- [x] /api/models/active_response_model.py
- [x] /api/models/configuration_model.py
- [x] /api/models/security_model.py
- [x] /api/models/group_added_model.py

**Comment by vicferpoy** [comment]
## Status update

Unit tests have been added and the coverage has improved.

### Before

```shellsession
Name                                      Stmts   Miss  Cover
-------------------------------------------------------------
models/__init__.py                            3      0   100%
models/active_response_model.py              36     36     0%
models/agent_added_model.py                  29     29     0%
models/agent_inserted_model.py               48     48     0%
models/base_model_.py                       104     21    80%
models/basic_info_model.py                   59     24    59%
models/configuration_model.py               212    212     0%
models/group_added_model.py                  15     15     0%
models/security_model.py                     72     72     0%
models/security_token_response_model.py      19      6    68%
-------------------------------------------------------------
TOTAL                                       597    463    22%
```

### After

```shellsession
Name                                      Stmts   Miss  Cover
-------------------------------------------------------------
models/__init__.py                            3      0   100%
models/active_response_model.py              36      0   100%
models/agent_added_model.py                  29      0   100%
models/agent_inserted_model.py               48      0   100%
models/base_model_.py                       104      0   100%
models/basic_info_model.py                   59      0   100%
models/configuration_model.py               212      0   100%
models/group_added_model.py                  15      0   100%
models/security_model.py                     72      0   100%
models/security_token_response_model.py      19      0   100%
-------------------------------------------------------------
TOTAL                                       597      0   100%
```

Regards,
Víctor
