### ISSUE TITLE
Linux support on PowerPC architectures

### ISSUE THREAD

**Issue by orsifacundo** [wazuh/wazuh#10043]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.x | All | Agent | -| Linux (PowerPC)|

Hi team,

It would be great to have support for Linux agents running on PowerPC architectures.

Regards.

## Description
Based on conversations, we found that the core requirement is intended to provide the precompiled ones, as well as the tests to verify that the operation is correct.

The packages tasks will be carried out in: https://github.com/wazuh/wazuh-packages/issues/914

## Tasks
- [x] Generate precompiled dependencies for ppc64le.
- [x] Upload dependencies to s3 
- [ ] Test in debian stretch
- [ ] Test in Centos 7

**Comment by Dwordcito** [comment]
It was compiled, installed and smoke tests were done without any inconvenience, it is understood that the greatest limitation for this case is the creation of packages to publish them on the page.

I understand that the wazuh-ci team is already looking to generate packages, based on daily feedback from members.

@orsifacundo You could specify if you found any limitations or if it is simply a matter of distributing packages for download.

@okynos for visibility.

**Comment by orsifacundo** [comment]
Hi @Dwordcito this request is simply for package distribution.

**Comment by havidarou** [comment]
Closed as per https://github.com/wazuh/wazuh-packages/issues/914
