### ISSUE TITLE
Define automatic labels

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#1004]
The agent labels are defined in the configuration and are included every label related to the agent in which they are included.

These labels are constant (key, value) pairs. We propose to create some automatic labels:
```xml
<labels>
  <label key="os">$(os.name) $(os.version)</label>
  <label key="address">$(network.ip)/$(network.mask)</label>
  <label key="connection">$(port)/$(protocol)</label>
</labels>
```

Please propose all the automatic labels that you need.

## Roadmap

- [x] Add timezone to the timestamp field on the DB.
- [x] Create a data structure to save the information.
- [ ] Design the parser to read the config file. (#2053)
- [x] Design the functionality to read the structure.
- [ ] Design the function that expect the syscollector message and fill the structure. (#2189)
- [x] Add the information to the alerts. (#2054)
- [x] Preload Syscollector data from Wazuh DB. (#2055)
- [ ] Write the documentation.

**Comment by jesuslinares** [comment]
It would be great to use automatic lables for the following ones:
```
<ossec_config>
 <labels>
  <label key="os.name">ubuntu</label>
  <label key="os.version">17.10</label>
  <label key="network.ipv4.primary">192.168.1.x</label>
  <label key="network.ipv4.others">192.168.1.y,192.168.1.z</label>
  <label key="network.ipv6.primary">fe80::xx...</label>
  <label key="network.ipv6.others">fe80::yy...,fe80::yy...</label>
  <label key="network.mac.primary">08:ff...</label>
  <label key="network.mac.others">08:ff..,08:zz..</label>
  <label key="timezone">+02</label>
  <label key="hostname">myhost</label>
 </labels>
</ossec_config>
```

**Comment by evilpete** [comment]
To be useful in a cloud environment information such as the instance ID would be required given that OS / IP addr / hostname are not sufficient identifiers when dealing with a distributed cloud architecture spanning  multiple regions and potentially multiple accounts

**Comment by vikman90** [comment]
@evilpete That's a good point. Currently, we are using the data collected by the Syscollector engine to enrich the alerts.

This means that we will need to extend Syscollector to pick up data about the instance from the AWS API, which seems very interesting.

We will do a little research about this. Thanks for your feedback!
Best regards.

**Comment by evilpete** [comment]
As I mentioned in #663, simply fetching data from the metadata URL http://169.254.169.254/latest/meta-data/ will have *all* the info you need without an AWS API call
