### ISSUE TITLE
Change Authd default options configuration values

### ISSUE THREAD

**Issue by TJOSERAFAEL** [wazuh/wazuh#1011]
We need to have activated by default the following options:

- `force_insert`
- `purge`
- `use_source_ip`

### Subtasks
- [x] Change the default values in the **ossec.conf** file. 
- [x] The options `-i`, `-F` and `-r` must be eliminated from the parameters
- [x] Show a deprecated message if any of the described options is used.  `WARN: Option X is deprecated. Set it in the configuration file`

This goes for Wazuh 3.5
