### ISSUE TITLE
Add new manager standalone API integration tests

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#10137]
Currently, our API integration tests are run under a virtualized cluster with 3 nodes, but we are not testing if all our endpoints work under a single manager, with the cluster disabled.

To test this, we should add a new mechanism to disable the cluster in the master node and thus simulate a standalone node. In addition, changes on the load balancer configuration are needed.

## Tasks
- [x] Add an option to choose between full cluster or standalone manager mode. **Ref:** https://github.com/wazuh/wazuh/issues/10591
- [x] Change nginx configuration depending on the environment mode. **Ref:** https://github.com/wazuh/wazuh/issues/10591
- [x] Assert that all previous tests work. **Ref:** https://github.com/wazuh/wazuh/issues/10592 and https://github.com/wazuh/wazuh/issues/10593
- [x] Open new issues for all unexpected encountered fails. **Ref:** https://github.com/wazuh/wazuh/issues/10593
- [x] Update the test mapping script and its output. 
- [x] Update the automated testing mechanism on higher levels to include these new integration tests. (Update `docker-compose` version)

---
**WORKING_BRANCH:** dev-add-standalone-ait
**TARGET_WAZUH_BRANCH:** master

Latest rebase of `dev-add-standalone-ait` (working) with master: JAN, 25 - 11:30 UTC

**Comment by mcarmona99** [comment]
## Issue update

Each test will be passed in the same environment with configuration changes, therefore, it will be passed twice. The test will be passed with a cluster configuration and with cluster disabled.
By default, pass each test twice. For some specific tests, only `standalone` or `cluster` configuration.


After the following lines in `api/test/integration/env/base/manager/entrypoint.sh`,

```
# Modify ossec.conf
for conf_file in /tmp/configuration_files/*.conf; do
  python3 /tools/xml_parser.py /var/ossec/etc/ossec.conf $conf_file
done
```

change cluster disabled `no` to `yes` if we are in standalone mode:

```
#!/usr/bin/env bash

sed -i -e "/<cluster>/,/<\/cluster>/ s|<disabled>[a-z]\+</disabled>|<disabled>yes</disabled>|g" /var/ossec/etc/ossec.conf
```


This line will be executed only if we are in `standalone` mode. When are we going to use standalone? That will be indicated in a mark in the API Integration Test. That mark will be used to change the `docker-compose` argument `MODE` that will indicate `STANDALONE`, `CLUSTER` or `BOTH`.

I keep investigating this possibility.
