### ISSUE TITLE
CloudWatch Logs raises ThrottlingException

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#10754]
|Wazuh version|Component|
|---|---|
| 4.2.4 | Wazuh AWS module |

# Description
We have been told that our AWS CloudWatch Logs implementation does not properly handle the `ThrottlingException` that is raised when more than 10 requests per second are made to the AWS API.

The request that seems to be raising this issue is `get_log_events`, as shown in the ossec.log output:
![image](https://user-images.githubusercontent.com/54286452/140538433-92008050-2298-4d05-853e-8838eabdf8bc.png)

# Tasks
- [x] Replicate the issue
- [x] Find the root cause and the solution for this issue
- [x] Test the fix

**Comment by CarlosRS9** [comment]
# Status update

Here is some of the information and conclusions found during our first attempt to understand what might be causing this issue:

## ThrottlingException

As explained [here](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/CommonErrors.html) and [here](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/), this exception is raised when a request was denied due to request throttling, which means that 10 or more requests per second per region were attempted.

This quota (10 requests per second) cannot be changed.





## Where is this exception being raised 


As shown in the ossec.log output the exception seems to be raised by the `get_log_events` here (pending confirmation):

https://github.com/wazuh/wazuh/blob/4.2/wodles/aws/aws_s3.py#L2555-L2556

One possible explanation for this may be that the response contains a `None` value for the `response['events']` so no events are sent to analysisd but the loop may continue trying to obtain more logs from `get_log_event` calls. We cannot confirm this yet as we were unable to replicate the issue. **We are still working on this.**

## Possible solutions

This issue happened to other external projects such as Metaflow. The common solution seems to be to expect that exception, catch it and continue attempting to perform the request to the AWS API until no exception is raised. However, **we cannot conclude this is a valid solution until we are able to correctly replicate this behaviour.**

**Comment by CarlosRS9** [comment]
# Status update


After investigating this issue and being able to test it in the client environment where this error was occurring, we have been able to verify the root cause and solution of this problem.


**The exception** is indeed being raised by the `get_log_events` function. However, it was not the module that was performing more than 10 calls per second. We have been able to verify that due to the bottleneck of the call itself, it is impossible to execute it 10 times per second even in a loop whose only purpose is that. However, it is possible for this to happen if other services, such as Kinesis or the AWS console itself, are making multiple calls to CloudWatchLogs while the module is running.

**The solution** is, as we indicated, is to check if this exception is being raised when making the API call and, if this happens, catch it and try again until the exception is raised no more or a given numer of attempts where performed.

### Conclusion

Although the module is not able to generate these 10 calls per second, it is possible that it has to suffer these exceptions in very congested environments, so our code must contemplate them and manage them correctly.
