### ISSUE TITLE
Use multiprocessing for Agent-info synchronization

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#10770]
|Component|
|---|
| Wazuh cluster |

## Description

Currently, the Wazuh cluster relies solely on asynchrony/concurrency to carry out all its tasks. While this is a good approach in all those I/O bound tasks, it is not so good in tasks where CPU usage is intensive since everything is blocked until they are finished.

To solve it, one option is to implement multiprocessing in the most problematic parts (CPU-bound). As part of this issue, we will try to perform the communication with wazuh-db for Agent-info synchronization in a new process. In particular, the following block should be executed in a different process than `wazuh-clusterd`:
https://github.com/wazuh/wazuh/blob/ddc752e027236c1bab2eaba3e8d72ae94a5105d0/framework/wazuh/core/cluster/master.py#L540-L550

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by Selutario** [comment]
## Issue update

I have created a new process that executes a class in charge of only sending chunks to wazuh-db. 
```PYTHON
    def send_data_to_wdb(self):
        wdb_conn = WazuhDBConnection()

        while True:
            data = self.agent_info_data.get()
            updated_chunks = 0
            
            for chunk in data['chunks']:
                try:
                    response = wdb_conn.send(f"{data['set_data_command']} {chunk}", raw=True)
                except Exception as e:
                    pass
```

As it can be seen above, I am using the `Queue` class of `multiprocessing.Manager` in order to receive the chunks from each worker instance (in the parent `wazuh-clusterd` process). 

This is working fine and the agent information is being updated on the master. However, I have not yet found an elegant and effective way to respond to the appropriate instance with the result. This way, the MasterHandler instance cannot notify to its worker if there has been any error in the process. In addition, loggers with the MasterHandler instance tag are not being used.

This approach has the advantage that there is no overhead creating and destroying processes since a single process is maintained that is continuously fed with the data provided by the MasterHandler instances of the parent process. The disadvantages are, however, those that we have mentioned above. I am researching to find the best solution.

**Comment by Selutario** [comment]
## Issue update

Below you can see the behavior of the cluster after the changes explained in the previous issue update:
![image](https://user-images.githubusercontent.com/23361101/140937587-3183655b-0d41-49ac-8bc8-f9326772adcd.png)

Each MasterHandler instance is adding chunks of data to the **Agent-info chunks (process 1)**. That is working fine and the information is being updated, however, it is not returning any response (if the task finished, if all chunks were correctly updated, etc). Therefore, I tried to add a new queue where said process would notify the original `wazuh-clusterd` (process 0) with the response (steps 2 and 3):
![image](https://user-images.githubusercontent.com/23361101/140938078-7cc9cccd-f59f-486b-8497-bb342922597e.png)

The problem is that the queue in process 0 is blocking all the processes while waiting for any response from process 1, so other tasks can't be run. There is no official tool or support in Python for combining Async and Manager().Queue(). Our own tools could be developed if necessary.

I am trying now a different approach where `ProcessPoolExecutor` is used and tasks are added as in the API, where response can be obtained:
https://github.com/wazuh/wazuh/blob/4cd3ebbc4d480c7e4b3a078f3ef31534e9ff8d46/framework/wazuh/core/cluster/dapi/dapi.py#L264-L267

In the DAPI we are not using multiprocessing right now, but an example was explained at https://github.com/wazuh/wazuh/issues/9060#issuecomment-873959125

This is, however, not working in my case. This is being run in each MasterHandler instance:
```PYTHON
        task = self.loop.run_in_executor(self.server.process_pool, partial(self.server.send_data_to_wdb, data))
        try:
            test = await asyncio.wait_for(task, timeout=20)
        except Exception as e:
            self.logger.info(f'ERROR: {e}')
```
but the following exception is being raised:
```
{TypeError} cannot pickle '_asyncio.Task' object
```

I need to research that better.

**Comment by Selutario** [comment]
## Issue update

The synchronization is correctly working after using ProcessPoolExecutor for this development:
```PYTHON
        try:
            task = self.loop.run_in_executor(self.server.agent_info_pool, self.send_data_to_wdb, logger, data)
            result = await asyncio.wait_for(task, timeout=20)
        except asyncio.TimeoutError:
            await self.send_request(command=b'syn_m_a_err', data=f"timeout processing agent-info chunks.".encode())
            raise exception.WazuhClusterError(3037)
        except Exception as e:
            await self.send_request(command=b'syn_m_a_err',
                                    data=f"error processing agent-info chunks in process pool: {str(e)}".encode())
            raise exception.WazuhClusterError(3038, extra_message=str(e))
```

The function `self.send_data_to_wdb` is executed in another process and the response is received from `await asyncio.wait_for(task, timeout=20)` when it is ready. 

I also tried using multiple workers in the ProcessPoolExecutor so `wazuh-db` is receives Agent-info chunks from multiple sources at the same time. This is working fine too.

## Errors

If the task running in the other process does not finish on time, a timeout exception is raised. However, the task is not cancelled, so more and more tasks are created and queue waiting for their turn. In order to stop the task, an `Event()` must be used:
```PYTHON
        timeout = self.server.manager.Event()
        try:
            task = self.loop.run_in_executor(self.server.agent_info_pool, self.send_data_to_wdb, logger, data, timeout)
            result = await asyncio.wait_for(task, timeout=20)
        except asyncio.TimeoutError:
            timeout.set()
            await self.send_request(command=b'syn_m_a_err', data=f"timeout processing agent-info chunks.".encode())
            raise exception.WazuhClusterError(3037)
        except Exception as e:
            await self.send_request(command=b'syn_m_a_err',
                                    data=f"error processing agent-info chunks in process pool: {str(e)}".encode())
            raise exception.WazuhClusterError(3038, extra_message=str(e))
```

In case that an asyncio.TimeoutError is raised, the `Event()` is set (`timeout.set()`). It stops the loop inside `self.send_data_to_wdb`:
```PYTHON
    @staticmethod
    def send_data_to_wdb(logger, data, timeout):
        result = {'updated_chunks': 0, 'error_messages': list()}
        wdb_conn = WazuhDBConnection()
        before = time()

        for i, chunk in enumerate(data['chunks']):
            if timeout.is_set():
                break
            ...

        logger.debug(f"{result['updated_chunks']}/{len(data['chunks'])} chunks updated in wazuh-db "
                     f"in {(time() - before):3f}s."
        return result
```

However, I found an strange behaviour in the logs:
```
2021/11/10 13:56:15 INFO: [Worker worker2] [Agent-info sync] Starting
2021/11/10 13:56:16 INFO: [Worker worker1] [Agent-info sync] CHUNK 1 - ok
2021/11/10 13:56:17 INFO: [Worker worker1] [Agent-info sync] CHUNK 2 - ok
2021/11/10 13:56:18 INFO: [Worker worker1] [Agent-info sync] CHUNK 3 - ok
2021/11/10 13:56:19 INFO: [Worker worker1] [Agent-info sync] CHUNK 4 - ok
2021/11/10 13:56:20 ERROR: [Worker worker1] [Main] Error 3037 - Timeout while waiting for response of Agent-info update in the process pool.
2021/11/10 13:56:20 DEBUG: [Worker worker1] [Agent-info sync] 5/64 chunks updated in wazuh-db in 5.069974s.
2021/11/10 13:56:20 ERROR: [Worker worker2] [Main] Error 3037 - Timeout while waiting for response of Agent-info update in the process pool.
2021/11/10 13:56:20 DEBUG: [Worker worker1] [Agent-info sync] 0/64 chunks updated in wazuh-db in 0.000758s.
```

As it can be seen above, the task is canceled when the timeout is exceeded, no more chunks are processed and this log (the last one inside `send_data_to_wdb`) is printed:
```
2021/11/10 13:56:20 DEBUG: [Worker worker1] [Agent-info sync] 5/64 chunks updated in wazuh-db in 5.069974s.
```

However, if there were more tasks waiting to be run and a timeout is raised also for them, the logger seems to be wrong (it shows the message under the `worker1` tag instead of `worker2`):
```
2021/11/10 13:56:20 ERROR: [Worker worker2] [Main] Error 3037 - Timeout while waiting for response of Agent-info update in the process pool.
2021/11/10 13:56:20 DEBUG: [Worker worker1] [Agent-info sync] 0/64 chunks updated in wazuh-db in 0.000758s.
```

**Comment by Selutario** [comment]
# Statistics comparison
These stats are comparing the status of the Wazuh cluster before and after the refactor carried out in this PR. The changes also include the refactor of the `Local Integrity` task, which was developed at #10765. 

The times obtained have been shorter after the changes, in a cluster of these characteristics:
- 10 workers nodes
- 50000 agents

# Tasks
## Stats in old cluster 
```PYTHON
{
    "setup_phase": {
        "integrity_check": {
            "time_spent(s)": {
                "workers": {
                    "mean": ("worker_3", 2.7357000000000005),
                    "max": ("worker_8", 12.387),
                },
                "master": {
                    "mean": ("master", 1.675761403508772),
                    "max": ("master", 9.852),
                },
            }
        },
        "integrity_sync": {
            "time_spent(s)": {
                "workers": {
                    "mean": ("worker_9", 0.7583269230769231),
                    "max": ("worker_9", 6.053),
                },
                "master": {
                    "mean": ("master", 3.8770406654343805),
                    "max": ("master", 23.984),
                },
            }
        },
        "agent-info_sync": {
            "time_spent(s)": {
                "workers": {
                    "mean": ("worker_8", 2.012596774193548),
                    "max": ("worker_8", 10.689),
                },
                "master": {
                    "mean": ("master", 0.42895733788395907),
                    "max": ("master", 5.03),
                },
            }
        },
    },
    "stable_phase": {
        "integrity_check": {
            "time_spent(s)": {
                "workers": {
                    "mean": ("worker_7", 2.105411111111111),
                    "max": ("worker_4", 3.324),
                },
                "master": {
                    "mean": ("master", 1.04997799779978),
                    "max": ("master", 2.335),
                },
            }
        },
        "agent-info_sync": {
            "time_spent(s)": {
                "workers": {
                    "mean": ("worker_4", 1.0482333333333334),
                    "max": ("worker_3", 2.356),
                },
                "master": {
                    "mean": ("master", 0.3596314631463146),
                    "max": ("master", 1.282),
                },
            }
        },
    },
}
```

## Stats after adding Multiprocessing
```PYTHON
{
    "setup_phase": {
        "integrity_check": {
            "time_spent(s)": {
                "workers": {
                    "mean": ("worker_1", 2.5858055555555555),
                    "max": ("worker_4", 8.461),
                },
                "master": {
                    "mean": ("master", 1.435443661971831),
                    "max": ("master", 6.992),
                },
            }
        },
        "integrity_sync": {
            "time_spent(s)": {
                "workers": {
                    "mean": ("worker_10", 0.6728970588235295),
                    "max": ("worker_9", 4.834),
                },
                "master": {
                    "mean": ("master", 2.444264705882353),
                    "max": ("master", 16.085),
                },
            }
        },
        "agent-info_sync": {
            "time_spent(s)": {
                "workers": {
                    "mean": ("worker_1", 2.163704225352113),
                    "max": ("worker_3", 8.917),
                },
                "master": {
                    "mean": ("master", 0.7589546783625731),
                    "max": ("master", 3.819),
                },
            }
        },
    },
    "stable_phase": {
        "integrity_check": {
            "time_spent(s)": {
                "workers": {
                    "mean": ("worker_2", 1.491635294117647),
                    "max": ("worker_2", 1.961),
                },
                "master": {
                    "mean": ("master", 0.6252827102803737),
                    "max": ("master", 1.02),
                },
            }
        },
        "agent-info_sync": {
            "time_spent(s)": {
                "workers": {
                    "mean": ("worker_9", 0.7740470588235295),
                    "max": ("worker_10", 1.689),
                },
                "master": {
                    "mean": ("master", 0.3331741176470588),
                    "max": ("master", 1.349),
                },
            }
        },
    },
}
```
