### ISSUE TITLE
Generate Cisco Umbrella, Inspector and Trusted Advisor sample logs for the AWS integration module

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#10841]
|Component|
|---|
| AWS module |

## Description
We need to generate sample logs for Cisco Umbrella, Inspector and Trusted Advisor to be able to test these integrations.

## Checks
- [x] Investigate what needs to be configured in order to be able to generate such logs
- [x] Generate Trusted Advisor logs
- [x] Generate Cisco Umbrella logs
- [x] Check collected logs in `archives.log`
- [x] Generate AWS Inspector logs
- [x] Apply for the required permissions and configure all the necessary settings in the DEV environment
- [x] Review and test the generated logs
- [x] Delete unnecessary services after the development

**Comment by noise-kngdm** [comment]
## Issue update
We have successfully configured our development environment to be able to generate Trusted Advisor logs, we will be working on Cisco Umbrella next.

**Comment by noise-kngdm** [comment]
## Issue update
We have been able to generate the necessary logs and we have uploaded to an S3 bucket a file with the following contents:
<details><summary>Trusted advisor sample logs</summary>

	{"aws": {"status": "ERROR", "source": "trustedadvisor", "uuid": "XXX06388-6dfa-4071-9f85-19f8cXXXXX", "resource_id": "arn:aws:ec2:us-east-1:XXXX:security-group/XX-0fa3f085deXXXXX", "log_info": {"s3bucket": "trustedadvisortesting", "aws_account_alias": "", "log_file": "trustedAdvisor2018/11/07/17/trustedadvisortesting"}, "check-item-detail": {"Status": "Red", "IP Range": "0.0.0.0/0", "Protocol": "tcp", "Security Group Name": "AccessBastion", "Region": "us-east-1", "Security Group ID": "sg-0fa3f085de7XXXX (vpc-c1XXXXba)", "Port": "22"}, "check-name": "Security Groups - Unrestricted Access"}, "integration": "aws"}
	{"aws": {"status": "WARN", "source": "trustedadvisor", "uuid": "6f1d64f7-de54-41af", "resource_id": "", "log_info": {"s3bucket": "trustedadvisortesting", "aws_account_alias": "", "log_file": "trustedAdvisor2018/11/08/16/trustedadvisortesting"}, "check-item-detail": {"Status": "Yellow", "Driver Status": "Newer version available", "Region": "us-east-1", "Timestamp": "2018-10-18 20:22:56", "Instance ID": "i-0dd8b9360d2XXXX"}, "check-name": "PV Driver Version for EC2 Windows Instances"}, "integration": "aws"}
	{"aws": {"status": "OK", "source": "trustedadvisor", "uuid": "XXXX4b2a-71XX-4df1-a1ae-73938XXXX", "resource_id": "", "log_info": {"s3bucket": "trustedadvisortesting", "aws_account_alias": "", "log_file": "trustedAdvisor2018/11/07/17/trustedadvisortesting"}, "check-item-detail": {"Hourly Instance Usage Max/Average/Min": "2/0/0", "Operating System": "Windows", "Recommended Additional 3-Year RIs": "+0", "Estimated Bill \n(Current RIs)": "$1.73", "Upfront Cost": "$0.00", "Instance Type": "t2.2xlarge", "Estimated Bill \n(Optimized RIs)": "$1.73", "Recommended Additional 1-Year RIs": "+0", "Estimated Monthly Savings": "$0.00", "Current RIs \n(1-Year and 3-Year)": "0", "Region / AZ": "us-east-1d"}, "check-name": "Amazon EC2 Reserved Instances Optimization"}, "integration": "aws"}

</details>

We are currently working on generating the Cisco Umbrella logs.

**Comment by noise-kngdm** [comment]
## Issue update
We have finally enabled the use of AWS Inspector and set up a test environment with Inspector events to use for testing. 

Running the integration module with the mentioned service shows the following output: 

```
root@d9d617150c26:/var/ossec/wodles/aws# ./aws-s3 -sr inspector -d2  -p dev -r us-east-1
DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Getting alerts from "us-east-1" region.
DEBUG: +++ Table does not exist; create
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
```

When running the module twice, no duplicate alerts are generated:
```
root@d9d617150c26:/var/ossec/wodles/aws# ./aws-s3 -sr inspector -d2  -p dev -r us-east-1
DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Getting alerts from "us-east-1" region.
DEBUG: +++ There are not new events from us-east-1 region
DEBUG: +++ There are not new events from us-east-1 region
DEBUG: +++ There are not new events from us-east-1 region
DEBUG: +++ There are not new events from us-east-1 region
DEBUG: +++ There are not new events from us-east-1 region
DEBUG: +++ There are not new events from us-east-1 region
DEBUG: +++ There are not new events from us-east-1 region
DEBUG: +++ There are not new events from us-east-1 region
DEBUG: +++ There are not new events from us-east-1 region
DEBUG: +++ There are not new events from us-east-1 region
DEBUG: +++ There are not new events from us-east-1 region
DEBUG: +++ There are not new events from us-east-1 region
DEBUG: +++ There are not new events from us-east-1 region
DEBUG: +++ There are not new events from us-east-1 region
DEBUG: +++ There are not new events from us-east-1 region
DEBUG: +++ There are not new events from us-east-1 region
```

The service is succesfully generating alerts from the collected events:
```
** Alert 1641228728.2611467: - amazon,aws,aws_inspector,
Rule: 80496 (level 10) -> 'AWS Inspector - Network assessment [2022-01-03T17:46:59Z]: 
```
## Conclusions
The service is working as expected and now we will be able to support it and make any changes to the integration when necessary.
