### ISSUE TITLE
find_account_ids returns every folder name present in the AWS bucket instead of just the account ID folders

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#10840]
|Component|
|---|
| AWS module |

## Description
The `find_account_ids` function is used to get the different account IDs available for the given bucket. This function works by just looking for the folders available, as different Account IDs will have different folders each one with its corresponding data. However, the current implementation does not differentiate between folders related to account IDs and any other folder inside the root. The implemented solution obtains a lists with every folder in the root directory (also taking into account the suffix and preffix value if applicable).

We must improve the function to ignore any folder that does not belong to an Account ID. These folders can be distinguished by their name, which is a string composed of 12 digits.

## Tasks
- [x] Investigate and design the best solution for this issue.
- [x] Update the `find_account_ids` function.
- [x] Test the module
- [x] Update the changelog (CHANGELOG.md)

**Comment by CarlosRS9** [comment]
# Status update

El módulo ha sido actualizado para solucionar este problema. La solución implementada pasa por verificar que los directorios que devuelve la función list_objects_v2 están compuestos únicamente por 12 dígitos antes de determinar que se trata de un Account ID.

Se ha probado el módulo tras aplicar este cambio para garantizar su correcto funcionamiento. Estos son los resultados:



<details>
  <summary>AWS Config before the fix</summary>

  ```
 	/var/ossec/wodles/aws/aws-s3 -p dev -b wazuh-aws-wodle-config -t config --region us-east-1 --debug 2 -s 2021-NOV-22
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Table does not exist; create
	DEBUG: +++ Working on 123456789000 - us-east-1
	DEBUG: +++ Marker: AWSLogs/123456789000/Config/us-east-1/2021/11/22
	DEBUG: ++ Found new log: AWSLogs/123456789000/Config/us-east-1/2021/11/22/123456789000_Config_us-east-1_ConfigHistory_AWS::Config::ResourceCompliance_20211122T004303Z_20211122T025123Z_1.json.gz
	DEBUG: +++ DB Maintenance
	DEBUG: +++ Marker: AWSLogs/123456789000/Config/us-east-1/2021/11/23
	DEBUG: +++ No logs to process in bucket: 123456789000/us-east-1
	DEBUG: +++ Marker: AWSLogs/123456789000/Config/us-east-1/2021/11/24
	DEBUG: ++ Found new log: AWSLogs/123456789000/Config/us-east-1/2021/11/24/123456789000_Config_us-east-1_ConfigHistory_AWS::Config::ResourceCompliance_20211124T004303Z_20211124T025123Z_1.json.gz
	DEBUG: +++ DB Maintenance
	DEBUG: +++ DB Maintenance
	DEBUG: +++ Working on test_empty - us-east-1
	DEBUG: +++ Marker: AWSLogs/test_empty/Config/us-east-1/2021/11/22
	DEBUG: +++ No logs to process in bucket: test_empty/us-east-1
	DEBUG: +++ Marker: AWSLogs/test_empty/Config/us-east-1/2021/11/23
	DEBUG: +++ No logs to process in bucket: test_empty/us-east-1
	DEBUG: +++ Marker: AWSLogs/test_empty/Config/us-east-1/2021/11/24
	DEBUG: +++ No logs to process in bucket: test_empty/us-east-1
	DEBUG: +++ DB Maintenance
	DEBUG: +++ Working on test_suffix - us-east-1
	DEBUG: +++ Marker: AWSLogs/test_suffix/Config/us-east-1/2021/11/22
	DEBUG: +++ No logs to process in bucket: test_suffix/us-east-1
	DEBUG: +++ Marker: AWSLogs/test_suffix/Config/us-east-1/2021/11/23
	DEBUG: +++ No logs to process in bucket: test_suffix/us-east-1
	DEBUG: +++ Marker: AWSLogs/test_suffix/Config/us-east-1/2021/11/24
	DEBUG: +++ No logs to process in bucket: test_suffix/us-east-1
	DEBUG: +++ DB Maintenance
  ```
</details>

The module assume the `test_empty` and `test_suffix` represent different account IDs, which is not true.

<details>
  <summary>AWS Config after the fix</summary>
  
  ```
	/var/ossec/wodles/aws/aws-s3 -p dev -b wazuh-aws-wodle-config -t config --region us-east-1 --debug 2 -s 2021-NOV-22
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Table does not exist; create
	DEBUG: +++ Working on 123456789000 - us-east-1
	DEBUG: +++ Marker: AWSLogs/123456789000/Config/us-east-1/2021/11/22
	DEBUG: ++ Found new log: AWSLogs/123456789000/Config/us-east-1/2021/11/22/123456789000_Config_us-east-1_ConfigHistory_AWS::Config::ResourceCompliance_20211122T004303Z_20211122T025123Z_1.json.gz
	DEBUG: +++ DB Maintenance
	DEBUG: +++ Marker: AWSLogs/123456789000/Config/us-east-1/2021/11/23
	DEBUG: +++ No logs to process in bucket: 123456789000/us-east-1
	DEBUG: +++ Marker: AWSLogs/123456789000/Config/us-east-1/2021/11/24
	DEBUG: ++ Found new log: AWSLogs/123456789000/Config/us-east-1/2021/11/24/123456789000_Config_us-east-1_ConfigHistory_AWS::Config::ResourceCompliance_20211124T004303Z_20211124T025123Z_1.json.gz
	DEBUG: +++ DB Maintenance
	DEBUG: +++ DB Maintenance
  ```
</details>

The module try to obtain logs from the only account ID available in the bucket. The other folders are being ignored.

<details>
  <summary>AWS Cloudtrail before the fix</summary>
  
  ```
	/var/ossec/wodles/aws/aws-s3 -p dev -b wazuh-aws-wodle-cloudtrail -t cloudtrail --region us-west-1 --debug 2 -s 2021-NOV-22
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Working on 123456789000 - us-west-1
	DEBUG: +++ Marker: AWSLogs/123456789000/CloudTrail/us-west-1/2021/11/22
	DEBUG: ++ Found new log: AWSLogs/123456789000/CloudTrail/us-west-1/2021/11/22/123456789000_CloudTrail_us-west-1_20211122T0000Z_rUQtGNUqmrPZMCnu.json.gz
	DEBUG: ++ Found new log: AWSLogs/123456789000/CloudTrail/us-west-1/2021/11/23/123456789000_CloudTrail_us-west-1_20211123T0000Z_rUQtGNUqmrPZMCnu.json.gz
	DEBUG: +++ DB Maintenance
	DEBUG: +++ DB Maintenance
	DEBUG: +++ Working on test_empty - us-west-1
	DEBUG: +++ Marker: AWSLogs/test_empty/CloudTrail/us-west-1/2021/11/22
	DEBUG: +++ No logs to process in bucket: test_empty/us-west-1
	DEBUG: +++ DB Maintenance
	DEBUG: +++ Working on test_suffix - us-west-1
	DEBUG: +++ Marker: AWSLogs/test_suffix/CloudTrail/us-west-1/2021/11/22
	DEBUG: +++ No logs to process in bucket: test_suffix/us-west-1
	DEBUG: +++ DB Maintenance
  ```
</details>

The module assume the `test_empty` and `test_suffix` represent different account IDs, which is not true.

<details>
  <summary>AWS Cloudtrail after the fix</summary>
  
  ```
	/var/ossec/wodles/aws/aws-s3 -p dev -b wazuh-aws-wodle-cloudtrail -t cloudtrail --debug 2 -s 2021-NOV-22       
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Table does not exist; create
	DEBUG: +++ Working on 123456789000 - us-west-1
	DEBUG: +++ Marker: AWSLogs/123456789000/CloudTrail/us-west-1/2021/11/22
	DEBUG: ++ Found new log: AWSLogs/123456789000/CloudTrail/us-west-1/2021/11/22/123456789000_CloudTrail_us-west-1_20211122T0000Z_rUQtGNUqmrPZMCnu.json.gz
	DEBUG: ++ Found new log: AWSLogs/123456789000/CloudTrail/us-west-1/2021/11/23/123456789000_CloudTrail_us-west-1_20211123T0000Z_rUQtGNUqmrPZMCnu.json.gz
	DEBUG: +++ DB Maintenance
	DEBUG: +++ DB Maintenance
  ```
</details>

The module try to obtain logs from the only account ID available in the bucket. The other folders are being ignored.

<details>
  <summary>AWS Cloudtrailg before the fix using a suffix</summary>

  ```
	/var/ossec/wodles/aws/aws-s3 -p dev -b wazuh-aws-wodle-cloudtrail -t cloudtrail --debug 2 -s 2021-NOV-22 -L test_suffix/
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Table does not exist; create
	DEBUG: +++ Working on 123456789000 - us-west-1
	DEBUG: +++ Marker: AWSLogs/test_suffix/123456789000/CloudTrail/us-west-1/2021/11/22
	DEBUG: ++ Found new log: AWSLogs/test_suffix/123456789000/CloudTrail/us-west-1/2021/11/22/123456789000_CloudTrail_us-west-1_20211122T0000Z_rUQtGNUqmrPZMCnu.json.gz
	DEBUG: +++ DB Maintenance
	DEBUG: +++ DB Maintenance
	DEBUG: +++ Working on invalid - us-west-1
	DEBUG: +++ Marker: AWSLogs/test_suffix/invalid/CloudTrail/us-west-1/2021/11/22
	DEBUG: +++ No logs to process in bucket: invalid/us-west-1
	DEBUG: +++ DB Maintenance
  ```
</details>

The module assume the `invalid` folder represent a different account ID, which is not true.

<details>
  <summary>AWS Cloudtrail after the fix using a suffix</summary>

  ```
	/var/ossec/wodles/aws/aws-s3 -p dev -b wazuh-aws-wodle-cloudtrail -t cloudtrail --debug 2 -s 2021-NOV-22 -L test_suffix/
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Table does not exist; create
	DEBUG: +++ Working on 123456789000 - us-west-1
	DEBUG: +++ Marker: AWSLogs/test_suffix/123456789000/CloudTrail/us-west-1/2021/11/22
	DEBUG: ++ Found new log: AWSLogs/test_suffix/123456789000/CloudTrail/us-west-1/2021/11/22/123456789000_CloudTrail_us-west-1_20211122T0000Z_rUQtGNUqmrPZMCnu.json.gz
	DEBUG: +++ DB Maintenance
	DEBUG: +++ DB Maintenance
  ```
</details>

The module try to obtain logs from the only account ID available in the bucket. The other folders are being ignored. The suffix is applied as intended.

Everything works as expected.

**Comment by CarlosRS9** [comment]
# Status update

The module has been updated to fix this bug. The solution implemented verifies that the directories returned by `list_objects_v2 `are composed of only 12 digits before determining it is a valid Account ID.

The module has been tested after applying this change to ensure its correct operation. Here are the results:




<details>
  <summary>AWS Config before the fix</summary>

  ```
 	/var/ossec/wodles/aws/aws-s3 -p dev -b wazuh-aws-wodle-config -t config --region us-east-1 --debug 2 -s 2021-NOV-22
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Table does not exist; create
	DEBUG: +++ Working on 123456789000 - us-east-1
	DEBUG: +++ Marker: AWSLogs/123456789000/Config/us-east-1/2021/11/22
	DEBUG: ++ Found new log: AWSLogs/123456789000/Config/us-east-1/2021/11/22/123456789000_Config_us-east-1_ConfigHistory_AWS::Config::ResourceCompliance_20211122T004303Z_20211122T025123Z_1.json.gz
	DEBUG: +++ DB Maintenance
	DEBUG: +++ Marker: AWSLogs/123456789000/Config/us-east-1/2021/11/23
	DEBUG: +++ No logs to process in bucket: 123456789000/us-east-1
	DEBUG: +++ Marker: AWSLogs/123456789000/Config/us-east-1/2021/11/24
	DEBUG: ++ Found new log: AWSLogs/123456789000/Config/us-east-1/2021/11/24/123456789000_Config_us-east-1_ConfigHistory_AWS::Config::ResourceCompliance_20211124T004303Z_20211124T025123Z_1.json.gz
	DEBUG: +++ DB Maintenance
	DEBUG: +++ DB Maintenance
	DEBUG: +++ Working on test_empty - us-east-1
	DEBUG: +++ Marker: AWSLogs/test_empty/Config/us-east-1/2021/11/22
	DEBUG: +++ No logs to process in bucket: test_empty/us-east-1
	DEBUG: +++ Marker: AWSLogs/test_empty/Config/us-east-1/2021/11/23
	DEBUG: +++ No logs to process in bucket: test_empty/us-east-1
	DEBUG: +++ Marker: AWSLogs/test_empty/Config/us-east-1/2021/11/24
	DEBUG: +++ No logs to process in bucket: test_empty/us-east-1
	DEBUG: +++ DB Maintenance
	DEBUG: +++ Working on test_suffix - us-east-1
	DEBUG: +++ Marker: AWSLogs/test_suffix/Config/us-east-1/2021/11/22
	DEBUG: +++ No logs to process in bucket: test_suffix/us-east-1
	DEBUG: +++ Marker: AWSLogs/test_suffix/Config/us-east-1/2021/11/23
	DEBUG: +++ No logs to process in bucket: test_suffix/us-east-1
	DEBUG: +++ Marker: AWSLogs/test_suffix/Config/us-east-1/2021/11/24
	DEBUG: +++ No logs to process in bucket: test_suffix/us-east-1
	DEBUG: +++ DB Maintenance
  ```
</details>

The module assume the `test_empty` and `test_suffix` represent different account IDs, which is not true.

<details>
  <summary>AWS Config after the fix</summary>
  
  ```
	/var/ossec/wodles/aws/aws-s3 -p dev -b wazuh-aws-wodle-config -t config --region us-east-1 --debug 2 -s 2021-NOV-22
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Table does not exist; create
	DEBUG: +++ Working on 123456789000 - us-east-1
	DEBUG: +++ Marker: AWSLogs/123456789000/Config/us-east-1/2021/11/22
	DEBUG: ++ Found new log: AWSLogs/123456789000/Config/us-east-1/2021/11/22/123456789000_Config_us-east-1_ConfigHistory_AWS::Config::ResourceCompliance_20211122T004303Z_20211122T025123Z_1.json.gz
	DEBUG: +++ DB Maintenance
	DEBUG: +++ Marker: AWSLogs/123456789000/Config/us-east-1/2021/11/23
	DEBUG: +++ No logs to process in bucket: 123456789000/us-east-1
	DEBUG: +++ Marker: AWSLogs/123456789000/Config/us-east-1/2021/11/24
	DEBUG: ++ Found new log: AWSLogs/123456789000/Config/us-east-1/2021/11/24/123456789000_Config_us-east-1_ConfigHistory_AWS::Config::ResourceCompliance_20211124T004303Z_20211124T025123Z_1.json.gz
	DEBUG: +++ DB Maintenance
	DEBUG: +++ DB Maintenance
  ```
</details>

The module try to obtain logs from the only account ID available in the bucket. The other folders are being ignored.

<details>
  <summary>AWS Cloudtrail before the fix</summary>
  
  ```
	/var/ossec/wodles/aws/aws-s3 -p dev -b wazuh-aws-wodle-cloudtrail -t cloudtrail --region us-west-1 --debug 2 -s 2021-NOV-22
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Working on 123456789000 - us-west-1
	DEBUG: +++ Marker: AWSLogs/123456789000/CloudTrail/us-west-1/2021/11/22
	DEBUG: ++ Found new log: AWSLogs/123456789000/CloudTrail/us-west-1/2021/11/22/123456789000_CloudTrail_us-west-1_20211122T0000Z_rUQtGNUqmrPZMCnu.json.gz
	DEBUG: ++ Found new log: AWSLogs/123456789000/CloudTrail/us-west-1/2021/11/23/123456789000_CloudTrail_us-west-1_20211123T0000Z_rUQtGNUqmrPZMCnu.json.gz
	DEBUG: +++ DB Maintenance
	DEBUG: +++ DB Maintenance
	DEBUG: +++ Working on test_empty - us-west-1
	DEBUG: +++ Marker: AWSLogs/test_empty/CloudTrail/us-west-1/2021/11/22
	DEBUG: +++ No logs to process in bucket: test_empty/us-west-1
	DEBUG: +++ DB Maintenance
	DEBUG: +++ Working on test_suffix - us-west-1
	DEBUG: +++ Marker: AWSLogs/test_suffix/CloudTrail/us-west-1/2021/11/22
	DEBUG: +++ No logs to process in bucket: test_suffix/us-west-1
	DEBUG: +++ DB Maintenance
  ```
</details>

The module assume the `test_empty` and `test_suffix` represent different account IDs, which is not true.

<details>
  <summary>AWS Cloudtrail after the fix</summary>
  
  ```
	/var/ossec/wodles/aws/aws-s3 -p dev -b wazuh-aws-wodle-cloudtrail -t cloudtrail --debug 2 -s 2021-NOV-22       
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Table does not exist; create
	DEBUG: +++ Working on 123456789000 - us-west-1
	DEBUG: +++ Marker: AWSLogs/123456789000/CloudTrail/us-west-1/2021/11/22
	DEBUG: ++ Found new log: AWSLogs/123456789000/CloudTrail/us-west-1/2021/11/22/123456789000_CloudTrail_us-west-1_20211122T0000Z_rUQtGNUqmrPZMCnu.json.gz
	DEBUG: ++ Found new log: AWSLogs/123456789000/CloudTrail/us-west-1/2021/11/23/123456789000_CloudTrail_us-west-1_20211123T0000Z_rUQtGNUqmrPZMCnu.json.gz
	DEBUG: +++ DB Maintenance
	DEBUG: +++ DB Maintenance
  ```
</details>

The module try to obtain logs from the only account ID available in the bucket. The other folders are being ignored.

<details>
  <summary>AWS Cloudtrailg before the fix using a suffix</summary>

  ```
	/var/ossec/wodles/aws/aws-s3 -p dev -b wazuh-aws-wodle-cloudtrail -t cloudtrail --debug 2 -s 2021-NOV-22 -L test_suffix/
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Table does not exist; create
	DEBUG: +++ Working on 123456789000 - us-west-1
	DEBUG: +++ Marker: AWSLogs/test_suffix/123456789000/CloudTrail/us-west-1/2021/11/22
	DEBUG: ++ Found new log: AWSLogs/test_suffix/123456789000/CloudTrail/us-west-1/2021/11/22/123456789000_CloudTrail_us-west-1_20211122T0000Z_rUQtGNUqmrPZMCnu.json.gz
	DEBUG: +++ DB Maintenance
	DEBUG: +++ DB Maintenance
	DEBUG: +++ Working on invalid - us-west-1
	DEBUG: +++ Marker: AWSLogs/test_suffix/invalid/CloudTrail/us-west-1/2021/11/22
	DEBUG: +++ No logs to process in bucket: invalid/us-west-1
	DEBUG: +++ DB Maintenance
  ```
</details>

The module assume the `invalid` folder represent a different account ID, which is not true.

<details>
  <summary>AWS Cloudtrail after the fix using a suffix</summary>

  ```
	/var/ossec/wodles/aws/aws-s3 -p dev -b wazuh-aws-wodle-cloudtrail -t cloudtrail --debug 2 -s 2021-NOV-22 -L test_suffix/
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Table does not exist; create
	DEBUG: +++ Working on 123456789000 - us-west-1
	DEBUG: +++ Marker: AWSLogs/test_suffix/123456789000/CloudTrail/us-west-1/2021/11/22
	DEBUG: ++ Found new log: AWSLogs/test_suffix/123456789000/CloudTrail/us-west-1/2021/11/22/123456789000_CloudTrail_us-west-1_20211122T0000Z_rUQtGNUqmrPZMCnu.json.gz
	DEBUG: +++ DB Maintenance
	DEBUG: +++ DB Maintenance
  ```
</details>

The module try to obtain logs from the only account ID available in the bucket. The other folders are being ignored. The suffix is applied as intended.

Everything works as expected.
