### ISSUE TITLE
Ruleset Testing: Epic Issue

### ISSUE THREAD

**Issue by jcruzlp** [wazuh/wazuh#10879]
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.3 | Rules/Decoders | Improve |

## Description

This issue aims to track the needed changes to ensure the quality of the ruleset and fix errors regarding granularity, typos, indexation...

We're waiting for the decision of which PRs will be kept for 4.3 and which ones will be discarded.

The branches used for this task will be:
- https://github.com/wazuh/wazuh/tree/decoders_review_17-11-2021 for decoders, tracked by @xrisbarney 
- https://github.com/wazuh/wazuh/tree/rules_review_17-11-2021 for rules, tracked by @Spades0 
- https://github.com/wazuh/wazuh/tree/19879-ruleset-fixes for implement changes listed below, tracked by @jcruzlp

This issue will be a nexus for all changes and issues.

## Necessary Issues
- Initial testing for 4.3 ruleset as it is: https://github.com/wazuh/wazuh/issues/10880
- Final testing of the ruleset with the desired fixes:

## Mandatory changes

- [ ] - As seen in the initial issue for 4.3 testing, we need to reimplement the PR https://github.com/wazuh/wazuh/pull/10768 in order to fix the issues with SSHD decoding. As the PR https://github.com/wazuh/wazuh/pull/10863 reverted these changes.
- [ ] - Also as @mikykeane reported, we use ID out of the official rule range from `1-99999`. We must track them and fix them.
- [x] - We have two files for Wazuh-api rules and decoders, we need to decide which one of them do we want to keep, or if both. Asked @davidjiglesias about it. We'll have to remove the old ones and keep the new implemented ones (If we keep them).
- [ ] - Changes are necessary for RHEL 8 SCA as requested by this issue from community https://github.com/wazuh/wazuh/issues/10886

**Comment by jcruzlp** [comment]
Wazuh API rules fixed, restored event for blocked API as requested by @santiago-bassett.
Removed old rules for wazuh API as discussed with @davidjiglesias they probably won't work anymore.
Added old rules to deprecated ruleset to avoid errors in the upgrade process.
Tested the changes to rules with `wazuh-logtest` as here:
```terminal
Starting wazuh-logtest v4.2.5
Type one log per line

2021/10/04 15:23:55 ERROR: Something bad happened

**Phase 1: Completed pre-decoding.
	full event: '2021/10/04 15:23:55 ERROR: Something bad happened'

**Phase 2: Completed decoding.
	name: 'wazuh-api-info'
	event-time: '2021/10/04 15:23:55'
	type: 'ERROR'

**Phase 3: Completed filtering (rules).
	id: '423'
	level: '8'
	description: 'Wazuh API Error event.'
	groups: '['wazuh-api']'
	firedtimes: '1'
	gpg13: '['3.3', '7.1', '4.12', '4.3']'
	hipaa: '['164.312.a.1']'
	mail: 'False'
	nist_800_53: '['AC.7', 'SC.5']'
	pci_dss: '['1.3.2', '6.5.10', '7.1', '8.1']'
	tsc: '['cc6.1']'
**Alert to be generated.

2021/10/04 15:23:55 WARNING: something wrong happened

**Phase 1: Completed pre-decoding.
	full event: '2021/10/04 15:23:55 WARNING: something wrong happened'

**Phase 2: Completed decoding.
	name: 'wazuh-api-info'
	event-time: '2021/10/04 15:23:55'
	type: 'WARNING'

**Phase 3: Completed filtering (rules).
	id: '422'
	level: '5'
	description: 'Wazuh API Warning event.'
	groups: '['wazuh-api']'
	firedtimes: '1'
	gpg13: '['3.3', '7.1', '4.12']'
	hipaa: '['164.312.a.1']'
	mail: 'False'
	nist_800_53: '['AC.7', 'SC.5']'
	pci_dss: '['1.3.2', '6.5.10', '7.1', '8.1']'
	tsc: '['cc6.1']'
**Alert to be generated.

2021/10/04 15:23:55 ERROR: IP blocked due to exceeded number of logins attempts: 172.18.0.1

**Phase 1: Completed pre-decoding.
	full event: '2021/10/04 15:23:55 ERROR: IP blocked due to exceeded number of logins attempts: 172.18.0.1'

**Phase 2: Completed decoding.
	name: 'wazuh-api-info'
	event-time: '2021/10/04 15:23:55'
	message: 'IP blocked due to exceeded number of logins attempts'
	srcip: '172.18.0.1'
	type: 'ERROR'

**Phase 3: Completed filtering (rules).
	id: '428'
	level: '10'
	description: 'Wazuh API: Warning event - IP: 172.18.0.1 blocked due to exceeded loging attemps.'
	groups: '['wazuh-api']'
	firedtimes: '1'
	gpg13: '['3.3']'
	hipaa: '['164.312.e.1']'
	mail: 'False'
	mitre.id: '['T1110']'
	mitre.tactic: '['Credential Access']'
	mitre.technique: '['Brute Force']'
	nist_800_53: '['AC.7']'
	pci_dss: '['8.2']'
**Alert to be generated.
```

**Comment by xrisbarney** [comment]
### Possible Decoder Issues
Manager version - 4.2.5
- [ruleset/decoders/0030-arpwatch_decoders.xml](https://github.com/wazuh/wazuh/blob/master/ruleset/decoders/0030-arpwatch_decoders.xml) did not decode the sample logs. It may require reworking.
- [ruleset/decoders/0050-checkpoint_decoders.xml](https://github.com/wazuh/wazuh/blob/master/ruleset/decoders/0050-checkpoint_decoders.xml) did not decode the sample logs. It may require reworking.
- [ruleset/decoders/0070-cisco-vpn_decoders.xml](https://github.com/wazuh/wazuh/blob/master/ruleset/decoders/0070-cisco-vpn_decoders.xml) did not decode the sample logs. It may require reworking.
- [ruleset/decoders/0145-mailscanner_decoders.xml](https://github.com/wazuh/wazuh/blob/master/ruleset/decoders/0145-mailscanner_decoders.xml) did not decode the sample logs. It may require reworking.
- [ruleset/decoders/0365-vpopmail_decoders.xml](https://github.com/wazuh/wazuh/blob/master/ruleset/decoders/0365-vpopmail_decoders.xml) logs did not match the decoder. Will need to retest and rework.
- [ruleset/decoders/0405-mongodb_decoders.xml](https://github.com/wazuh/wazuh/blob/master/ruleset/decoders/0405-mongodb_decoders.xml) logs did not match the decoder. Will need to retest and rework.

**Comment by Spades0** [comment]
**Rule Issues and Comments**

Manager version - 4.2.5

- [ruleset/rules/0240-ids_rules.xml](https://github.com/wazuh/wazuh/blob/master/ruleset/rules/0240-ids_rules.xml): Changed tag <if_fts></if_fts> to <if_fts />. Seems like the later is the new syntax.

- [ruleset/rules/0850-audit_rules.xml](https://github.com/wazuh/wazuh/blob/master/ruleset/rules/0850-audit_rules.xml): Changed on line 22, the characters --  to -/- in the sample log, It was causing an error that commented out the rest of the rules.
  
- [ruleset/rules/0017-wazuh-api_rules.xml](https://github.com/wazuh/wazuh/blob/master/ruleset/rules/0017-wazuh-api_rules.xml)
|./tests/api.ini          |    27    |    1     |    ❌     |
  Rule 427 fails cos it's log is being picked up by another rule - 410
 
- [ruleset/rules/0260-nginx_rules.xml](https://github.com/wazuh/wazuh/blob/master/ruleset/rules/0260-nginx_rules.xml): In rule 31317, it passes but in <match>failed (2: No such file or directory</match>, there should be a ")"
  just before </match> and also in the sample log in the ini file.

- [ruleset/rules/0095-sshd_rules.xml](https://github.com/wazuh/wazuh/blob/master/ruleset/rules/0095-sshd_rules.xml)
 |./tests/sshd.ini         |    27    |    16    |    ❌     |
 Some rules need to be looked at and worked on.
 Some rules are not working because no decoders are found for the logtest.
