### ISSUE TITLE
Adapt the cluster to the changes made in the `agent-groups` files

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#10919]
Based on the development of the Core team, we have to adapt the cluster code, the agent-groups files are going to disappear so we have to remove the synchronization part of them.

The information of these files will be in global.db and will be managed by wazuh-db so from the cluster, we will have to synchronize the changes in the DB as we do now.

### Tasks

- [ ] Remove the code in charge of the synchronization of the agent-groups files (extra-valid).
- [ ] Adapt the cluster unittests.
- [ ] Run integrated API tests related to the cluster (modify if necessary).
- [ ] Perform several performance tests (workload).
