### ISSUE TITLE
Add unit tests for log rotation 

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#10924]
### Description

The goal of this issue is to add unit tests for the updated _log rotation_ features, and those added in issue #3072. As the current `log rotation` does not have unit tests, the tests must be created completely from scratch, covering as many functions as possible.

### Tasks

**Tests**
- [ ] Create tests for updated functions.
- [ ] Create tests for new functions.
- [ ] Create the necessary mockups.

**Misc**
- [ ] Make sure to perform the tests in compliance with the style code.
- [ ] Ensure 100% coverage for each function.

**Comment by vikman90** [comment]
Closing this issue as it will be superseded by version 5.0.
