### ISSUE TITLE
Fix the use of the ``aws_account_id`` parameter in the AWS integration's Custom buckets

### ISSUE THREAD

**Issue by noise-kngdm** [wazuh/wazuh#10939]
|Component|
|---|
| External integration modules |

## Description
In the AWS integration module, all the AWS buckets that inherit from the `AWSCustomBucket` class are using the following method to register the processed logs:  
https://github.com/wazuh/wazuh/blob/7d201e611db0baa54a28e1efe31e91174fc8c365/wodles/aws/aws_s3.py#L1958-L1974

This method uses the `self.aws_account_id` parameter to insert the processed logs into the database, without taking into consideration the `aws_account_id` passed as a parameter. Also, the `iter_regions_and_accounts` method overloaded for `AWSCustomBucket` also discards that parameter, as can be seen below:
https://github.com/wazuh/wazuh/blob/7d201e611db0baa54a28e1efe31e91174fc8c365/wodles/aws/aws_s3.py#L1942-L1947  

This could be troublesome when trying to process logs pertaining to different accounts, and therefore the impact of this bug should be studied as part of this issue.
## Tasks
- [x] Study impact of the bug.
- [ ] Implement fix.
- [ ] Test changes.
- [ ] Update the documentation.
- [ ] Changelog (`CHANGELOG.md`).

**Comment by fdalmaup** [comment]
# Issue Update

## Initial analysis of the code 

The `mark_complete` method of the `AWSCustomBucket` has been modified at the PR https://github.com/wazuh/wazuh/pull/10838. 
Currently, the method calls the `AWSBucket` implementation passing `self.aws_account_id`
https://github.com/wazuh/wazuh/blob/011dbf0006dc3a30291484fa5c3a271d5924fd2c/wodles/aws/aws_s3.py#L2175-L2176

That parameter is passed like that because the `iter_regions_and_accounts` method overloaded for `AWSCustomBucket remains the same as described in the issue description, not sending the `account_id` and `regions` parameters received to the `iter_files_in_bucket` method. Therefore, the values for those parameters when being called by `AWSCustomBucket` child classes are `None`
https://github.com/wazuh/wazuh/blob/011dbf0006dc3a30291484fa5c3a271d5924fd2c/wodles/aws/aws_s3.py#L1008 

 When, inside this last method, the `mark_complete` method is called by an `AWSCustomBucket` instance
https://github.com/wazuh/wazuh/blob/011dbf0006dc3a30291484fa5c3a271d5924fd2c/wodles/aws/aws_s3.py#L1050
it sends the `self.aws_account_id` as described because the parameter `aws_account_id` is `None`.

**Comment by fdalmaup** [comment]
# Issue Update

The `iter_regions_and_accounts` method has been analyzed for the `AWSBucket` and `AWSCustomBucket` classes.
In the first case, if no `account_id` or `regions` parameters have been defined, the ones that exist in the specified bucket are searched, and then the `iter_files_in_bucket` is called with each one of their values. As described previously, in the second case the method `iter_files_in_bucket` is called without setting parameters without iterations for accounts_id or regions. Therefore, the `mark_complete` method for custom buckets registers in the DB file table the `aws_account_id` of the client who made the request which is set in: 
https://github.com/wazuh/wazuh/blob/011dbf0006dc3a30291484fa5c3a271d5924fd2c/wodles/aws/aws_s3.py#L1972-L1988

In the case of buckets that use the `AWSBucket` method, in the DB file table, the `aws_account_id` values are each of those found, unless it has been specified that only the logs of a particular account should be taken.

The described behavior may be because buckets of type `AWSCustomBucket`, like `KMS`, `Macie` and `Trusted Advisor`, or which inherit from it such as `GuardDuty` and `WAF`, do not have logs that are recorded according to the `aws_account_id` as is the case with ` CloudTrail` or `Config` which follow the `/AWSLogs/<account_id>/<service>/<region>/` pattern. Therefore, there is no need to look for different accounts to get the logs, but rather they are based only on the prefix that the user may enter. It is for this last reason that if a prefix is ​​not indicated, it will search according to the date regex which is the default behavior, and skip those that do not comply with the expected path, showing the `Skipping file with another prefix...` message. It's probably done this way to avoid unnecessary calls to the AWS service. If the user registers the logs with different accounts as a prefix, it should be indicated with the corresponding parameter, but it will continue to be registered in the DB with the account of the one who makes the request for the logs.

## Example with custom bucket `WAF`

For testing purposes, two folders with the `aws_account_id` format have been generated.
Command used to retrieve logs from any of the created folders representing different accounts:
`/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-waf -l aws_account_id_X_prefix -t custom -s 2021-Sep-17 -p dev -d2`

**Note that the `-l` flag is being used, which indicates the prefix to be searched.**
This was executed for each of the folders created because otherwise, it would not bring the logs of both prefixes.

When executing `sqlite3 s3_cloudtrail.db 'SELECT * FROM custom;'` to verify what has been stored in the DB file, the following results were found:
```
wazuh-aws-wodle-waf/<aws_account_id_A_prefix>/|<aws_account_id_request>|<aws_account_id_A_prefix>/2022/06/03/aws-waf-logs-delivery-stream-1-xxxxxxxxx|2022-09-22 18:48:07|20220603
wazuh-aws-wodle-waf/<aws_account_id_B_prefix>/|<aws_account_id_request>|<aws_account_id_B_prefix>/2022/06/03/aws-waf-logs-delivery-stream-1-xxxxxxxxx|2022-09-22 18:48:31|20220603
```

## Example with non-custom bucket `CloudTrail`

Command used:
`/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-cloudtrail -t cloudtrail -s 2021-Dec-01 -p dev -d2`

No `aws_account_id` was specified using the `-c` flag, therefore, the module searched for every account in the bucket and retrieved the logs of each one.

When executing `sqlite3 s3_cloudtrail.db 'SELECT * FROM cloudtrail;'` to verify what has been stored in the DB file, the following results were found:
```
wazuh-aws-wodle-cloudtrail/|<aws_account_id_A>|<region>|AWSLogs/<aws_account_id_A>/CloudTrail/region-1/2022/03/30/xxxxxxxxx.json.gz|2022-09-22 17:23:39|20220330
wazuh-aws-wodle-cloudtrail/|<aws_account_id_B>|<region>|AWSLogs/<aws_account_id_B>/CloudTrail/region-1/2021/12/23/xxxxxxxxx.json.gz|2022-09-22 17:23:39|20211223
```

## Conclusion

The application of a fix for this way of handling the parameter should be analyzed in case the way of storing the data in the DB should be modified.

**Comment by fdalmaup** [comment]
# Issue Update

It was found that the current use of the parameter `aws_account_id` in Custom Buckets is not generating problems related to the user experience and the fetching of the logs.  
The code and its quality could be improved, but the necessary changes are considered _breaking changes_ because they would require a redesign of how the module handles AWS account ids and prefixes, and the primal objective is to maintain compatibility with what the user already has.
