### ISSUE TITLE
Release 4.3.0 - Release Candidate 1 - Modules tests

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#10962]
The following issue aims to perform all the required testing for the current release candidate to ensure the modules (AWS, GCP and Azure) works as expected, report the results, and open new issues for any encountered errors.

## Modules tests information

|||
|--------------------------------------|------------------------------------------------|
| **Main release candidate issue**     | https://github.com/wazuh/wazuh/issues/10955    |
| **Version**                          | 4.3.0                                          |
| **Release candidate #**              | RC1                                            |
| **Tag**                              | https://github.com/wazuh/wazuh/tree/v4.3.0-rc1 |
| **Previous modules tests issue**      | -                                              |

## Test report procedure
All individual test checks must be marked as:

|||
|---------------------------------|--------------------------------------------|
| Pass | The test ran successfully. |
| Xfail | The test was expected to fail and it failed. It must be properly justified and reported in an issue.  |
| Skip | The test was not run. It must be properly justified and reported in an issue.  |
| Fail | The test failed. A new issue must be opened to evaluate and address the problem. |

All test results must have one the following statuses: 

|||
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed check. |
| :yellow_circle:  | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

The resulting logs for the tests must be included in the status report so it can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions
|||||
|----------------|-------------|-------------|---|
| **Module**    | **Testing issue** | **Status**  |**Notes**|
| AWS            |  #10964 | :red_circle: | #9993: Only_logs_after parameter implementation should be consistent between modules <br>#10663: CloudWatch Logs is missing the reparse parameter <br>#10840: The module misinterprets folders in root path as AWS account IDs <br>#10846 (`To be fixed in 4.4`): The module make unnecessary calls to the VPCFlow API <br>#11113: Reparse option is not working for the VPC Flow integration <br>#11138 (`To be fixed in 4.4`): GuardDuty is missing the discard_regex functionality <br>#11148 (`To be fixed in 4.4`): Unnecessary amount of Skipping file messages present <br>#11150: Server Access does not process certain old dates and displays the "Skipping file too old to process" message. <br>#11160 (`To be fixed in 4.4`): Unnecessary CloudWatch Logs debug messages <br>#11183: Cloudtrail and Custom buckets process duplicate logs.|
| GCP            |   #10965          |:red_circle: |#11149: The module doesn't properly filter folders by prefix.<br>https://github.com/wazuh/wazuh-documentation/issues/4644: The Python version that the documentation says is required is wrong.|
| Azure          |  #10966           |:red_circle: |#11096: The execution doesn't stop when wrong parameters were used with Storage.<br>#11116: Configuration parser treats as required optional fields.<br>#11147 (`To be fixed in 4.4`): The module should be able to filter logs depending on a prefix folder.|

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.
- [x] @davidjiglesias 
- [x] @CarlosRS9 
- [x] @noise-kngdm

**Comment by CarlosRS9** [comment]
# AWS Manual testing

The AWS module manual testing must include the following **supported services**:

- Cloudtrail
- VPC
- Config
- ALB
- CLB
- NLB
- KMS
- Macie
- Trusted Advisor
- GuardDuty
- WAF
- Inspector
- CloudWatch Logs
- Umbrella

The data available in our Wazuh-dev environment for each of these supported services will be used. Additional logs may be created if they are necessary or there is insufficient data for testing.

Every test must be performed both on a Manager and an Agent.

Every parameter available for the supported service must be tested. This includes `reparse`, `only_logs_after` and many others, regardless of if the parameter itself is common for every supported service or exclusive to a single one.

Each supported service must be tested at least once using the local configuration (`ossec.conf`) and running it manually from the command line.

# Tasks

- [ ] Test the AWS integration for Cloudtrail.
- [ ] Test the AWS integration for VPC.
- [ ] Test the AWS integration for Config.
- [ ] Test the AWS integration for ALB.
- [ ] Test the AWS integration for CLB.
- [ ] Test the AWS integration for NLB.
- [ ] Test the AWS integration for KMS.
- [ ] Test the AWS integration for Macie.
- [ ] Test the AWS integration for Trusted Advisor.
- [ ] Test the AWS integration for GuardDuty.
- [ ] Test the AWS integration for WAF.
- [ ] Test the AWS integration for Inspector.
- [ ] Test the AWS integration for CloudWatch Logs.
- [ ] Test the AWS integration for Umbrella.


# Results

**Comment by CarlosRS9** [comment]
# GCP Manual testing

The GCP module manual testing must include both `gcp-bucket` and `gcp-pubsub` integrations.


The data available in our Wazuh-dev environment will be used. Additional logs may be created if they are necessary or there is insufficient data for testing.

Every test must be performed both on a Manager and an Agent.

Every parameter available must be tested. This includes `reparse`, `only_logs_after` and many others, regardless of if the parameter itself is common for both integrations or exclusive to a single one.

Each integration must be tested at least once using the local configuration (`ossec.conf`) and running it manually from the command line.

# Tasks

- [ ] Test the GCP-Pubsub integration.
- [ ] Test the GCP-Buckets integration.

# Results

**Comment by CarlosRS9** [comment]
# Azure Manual testing


The Azure module manual testing must include `Graph`, `Log Analytics` and `Storage` integrations.


The data available in our Wazuh-dev environment will be used. Additional logs may be created if they are necessary or there is insufficient data for testing.

The tests will be performed on a Manager as this module is not compatible with agents yet.

Every parameter available must be tested. This includes `reparse`, `offset` and many others, regardless of if the parameter itself is common for every integrations or exclusive to a single one.

Each integration must be tested at least once using the local configuration (`ossec.conf`) and running it manually from the command line.

Logs from `azure-logs.log` should be included with the result report if available.

# Tasks

- [ ] Test Azure Graph integration.
- [ ] Test Azure Log Analytics integration.
- [ ] Test Azure Storage integration.

# Results
