### ISSUE TITLE
Cannot build Windows agent on MinGW 10-win32

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#11025]
|Version|Type|Platform|Compiler|
|---|---|---|---|
|4.3.0-rc1|Agent|Windows|MinGW 10-win32|

The build procedure is raising the following error:

```sh
make clean-deps clean
make TARGET=winagent deps
make TARGET=winagent
```
```
grep: /etc/redhat-release: No such file or directory
cp /usr/i686-w64-mingw32/lib/libwinpthread-1.dll win32/libwinpthread-1.dll
cp  win32/libgcc_s_sjlj-1.dll
cp: missing destination file operand after 'win32/libgcc_s_sjlj-1.dll'
Try 'cp --help' for more information.
make: *** [Makefile:777: win32/libgcc_s_sjlj-1.dll] Error 1
```

## Rationale

File `libgcc_s_sjlj-1.dll` won't exist on MinGW 10 library. It seems that MinGW 10 replaced SJLJ exceptions with DWARF2:

```sh
# i686-w64-mingw32-gcc -v
Target: i686-w64-mingw32
Configured with: (...) --disable-sjlj-exceptions --with-dwarf2
gcc version 10-win32 20210110 (GCC)
```

## Tasks

- [x] Replace `libgcc_s_sjlj-1.dll` with `libgcc_s_dw2-1.dll` at Makefile.
- [x] Replace `libgcc_s_sjlj-1.dll` with `libgcc_s_dw2-1.dll` at the NSIS installer.
- [x] Replace `libgcc_s_sjlj-1.dll` with `libgcc_s_dw2-1.dll` at the MSI installer.
- [x] Require MinGW 10 or newer to compile the agent for Windows.

## Possible dependencies

If we confirm that this has been a change by MinGW and DWARF2 exception handling works on every supported platform, we will need to update MinGW on the package building environments.
