### ISSUE TITLE
Fix bug in Azure storage when specifying an invalid bucket

### ISSUE THREAD

**Issue by noise-kngdm** [wazuh/wazuh#11098]
| Affected integration |
|---|
|  Azure|

## Description
While working on #10966 we realized that when executing the recently refactored Azure Storage module specifying a non-existent container, instead of finishing the execution and returning a plain error message the module will try to connect to it.

<details><summary>Execution with an invalid container</summary>

<p>

```
root@1b335b872bf4:/var/ossec/wodles/azure# /var/ossec/wodles/azure/azure-logs --storage --container invalid --storage_time_offset 10h --storage_auth_path /var/ossec/wodles/azure/credentials-storage -v
11/29/2021 05:08:07 PM INFO: AZURE Getting the data from /var/ossec/wodles/azure/last_dates.json.
11/29/2021 05:08:07 PM INFO: AZURE Azure Storage starting.
11/29/2021 05:08:07 PM INFO: AZURE Storage: Authenticating.
11/29/2021 05:08:07 PM INFO: AZURE Storage: Authenticated.
11/29/2021 05:08:07 PM INFO: AZURE Storage: Getting containers.
11/29/2021 05:08:07 PM INFO: AZURE Storage: Getting blobs.
11/29/2021 05:08:07 PM DEBUG: AZURE String_to_sign=GET











x-ms-client-request-id:8a80e799-512e-11ec-b71f-4ba46d91cb47
x-ms-date:Mon, 29 Nov 2021 16:08:07 GMT
x-ms-version:2019-02-02
/frameworkteststorage/invalid
comp:list
restype:container
11/29/2021 05:08:07 PM INFO: AZURE Client-Request-ID=8a80e799-512e-11ec-b71f-4ba46d91cb47 Outgoing request: Method=GET, Path=/invalid, Query={'restype': 'container', 'comp': 'list', 'prefix': None, 'delimiter': None, 'marker': None, 'maxresults': None, 'include': None, 'timeout': None}, Headers={'x-ms-version': '2019-02-02', 'User-Agent': 'Azure-Storage/2.1.0-2.1.0 (Python CPython 3.9.6; Linux 5.15.5-arch1-1)', 'x-ms-client-request-id': '8a80e799-512e-11ec-b71f-4ba46d91cb47', 'x-ms-date': 'Mon, 29 Nov 2021 16:08:07 GMT', 'Authorization': 'REDACTED'}.
11/29/2021 05:08:07 PM DEBUG: AZURE Starting new HTTPS connection (1): frameworkteststorage.blob.core.windows.net:443
11/29/2021 05:08:08 PM DEBUG: AZURE https://frameworkteststorage.blob.core.windows.net:443 "GET /invalid?restype=container&comp=list HTTP/1.1" 404 225
11/29/2021 05:08:08 PM INFO: AZURE Client-Request-ID=8a80e799-512e-11ec-b71f-4ba46d91cb47 Receiving Response: Server-Timestamp=Mon, 29 Nov 2021 16:08:07 GMT, Server-Request-ID=2d1fa308-601e-0008-3d3b-e5b2f8000000, HTTP Status Code=404, Message=The specified container does not exist., Headers={'content-length': '225', 'content-type': 'application/xml', 'server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': '2d1fa308-601e-0008-3d3b-e5b2f8000000', 'x-ms-client-request-id': '8a80e799-512e-11ec-b71f-4ba46d91cb47', 'x-ms-version': '2019-02-02', 'x-ms-error-code': 'ContainerNotFound', 'date': 'Mon, 29 Nov 2021 16:08:07 GMT'}.
11/29/2021 05:08:08 PM INFO: AZURE Client-Request-ID=8a80e799-512e-11ec-b71f-4ba46d91cb47 Operation failed: checking if the operation should be retried. Current retry count=0, Server-Timestamp=Mon, 29 Nov 2021 16:08:07 GMT, Server-Request-ID=2d1fa308-601e-0008-3d3b-e5b2f8000000, HTTP status code=404, Exception=The specified container does not exist. ErrorCode: ContainerNotFound<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerNotFound</Code><Message>The specified container does not exist.RequestId:2d1fa308-601e-0008-3d3b-e5b2f8000000Time:2021-11-29T16:08:08.0699843Z</Message></Error>.
11/29/2021 05:08:08 PM ERROR: AZURE Client-Request-ID=8a80e799-512e-11ec-b71f-4ba46d91cb47 Retry policy did not allow for a retry: Server-Timestamp=Mon, 29 Nov 2021 16:08:07 GMT, Server-Request-ID=2d1fa308-601e-0008-3d3b-e5b2f8000000, HTTP status code=404, Exception=The specified container does not exist. ErrorCode: ContainerNotFound<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerNotFound</Code><Message>The specified container does not exist.RequestId:2d1fa308-601e-0008-3d3b-e5b2f8000000Time:2021-11-29T16:08:08.0699843Z</Message></Error>.
11/29/2021 05:08:08 PM ERROR: AZURE Storage: Error getting blobs: 'The specified container does not exist. ErrorCode: ContainerNotFound
<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerNotFound</Code><Message>The specified container does not exist.
RequestId:2d1fa308-601e-0008-3d3b-e5b2f8000000
Time:2021-11-29T16:08:08.0699843Z</Message></Error>'.
11/29/2021 05:08:08 PM INFO: AZURE Updating /var/ossec/wodles/azure/last_dates.json file.
11/29/2021 05:08:08 PM INFO: AZURE Storage: End

```
</p>

</details>  

It will also save in the `last_dates.json` file an entry corresponding to the non-existent container when it shouldn't.
```
root@1b335b872bf4:/var/ossec/wodles/azure# cat last_dates.json ; echo
{"log_analytics": {}, "graph": {}, "storage": {"82e049b81fa6eb88ebf85f1677785f2b": {"min": "2021-11-29T06:05:26.092892Z", "max": "2021-11-29T06:05:26.092892Z"}}}
```

## Tasks
- [ ] Make the module abort the execution when an invalid container was specified
- [ ] Test in a manager
- [ ] Test in an agent
- [ ] Update the documentation if necessary
- [ ] Add entry to the changelog if necessary

**Comment by noise-kngdm** [comment]
We will fix this in #11096.
