### ISSUE TITLE
Fix bug in Azure Storage integration when using invalid parameters

### ISSUE THREAD

**Issue by noise-kngdm** [wazuh/wazuh#11096]
| Affected integration |
|---|
| Azure|

## Description
While working on #10966 we realized that there are some problems related with how the module deals with incorrect credentials.

### Using a wrong `account_name` or `account_key`
 Azure Storage module with invalid credentials, instead of finishing the execution and returning a plain error message the module keeps trying to connect with the wrong credentials for a long time.  

The output displayed when using the `-v` option is the following:

<details><summary>Execution with invalid credentials 1</summary>

<p>

```
root@1b335b872bf4:/var/ossec/wodles/azure# /var/ossec/wodles/azure/azure-logs --account_name invalid --account_key invalid --storage --container frameworktestcontainer --storage_time_offset 10h -v
11/29/2021 04:50:34 PM INFO: AZURE Getting the data from /var/ossec/wodles/azure/last_dates.json.
11/29/2021 04:50:34 PM INFO: AZURE Azure Storage starting.
11/29/2021 04:50:34 PM INFO: AZURE Storage: Authenticating.
11/29/2021 04:50:34 PM INFO: AZURE Storage: Authenticated.
11/29/2021 04:50:34 PM INFO: AZURE Storage: Getting containers.
11/29/2021 04:50:34 PM INFO: AZURE Storage: Getting blobs.
11/29/2021 04:50:34 PM INFO: AZURE Client-Request-ID=1691984e-512c-11ec-a9e6-d59d16a5d670 Unable to sign the request: Exception=Incorrect padding.
11/29/2021 04:50:34 PM ERROR: AZURE Storage: Error getting blobs: 'Incorrect padding'.
11/29/2021 04:50:34 PM INFO: AZURE Updating /var/ossec/wodles/azure/last_dates.json file.
11/29/2021 04:50:34 PM INFO: AZURE Storage: End
```

</p>

</details>

<details><summary>Execution with invalid credentials 2</summary>

<p>

```
root@1b335b872bf4:/var/ossec/wodles/azure# /var/ossec/wodles/azure/azure-logs --account_name invalido --account_key invalido --storage --container frameworktestcontainer --storage_time_offset 10h -v
11/29/2021 04:09:53 PM INFO: AZURE Getting the data from /var/ossec/wodles/azure/last_dates.json.
11/29/2021 04:09:53 PM INFO: AZURE Azure Storage starting.
11/29/2021 04:09:53 PM INFO: AZURE Storage: Authenticating.
11/29/2021 04:09:53 PM INFO: AZURE Storage: Authenticated.
11/29/2021 04:09:53 PM INFO: AZURE Storage: Getting containers.
11/29/2021 04:09:53 PM INFO: AZURE 276fdc115c93c665ecb3616a9bca2e65 was not found in /var/ossec/wodles/azure/last_dates.json for storage
11/29/2021 04:09:53 PM INFO: AZURE Storage: Getting blobs.
11/29/2021 04:09:53 PM DEBUG: AZURE String_to_sign=GET











x-ms-client-request-id:68093b56-5126-11ec-b835-79a1cba11dcc
x-ms-date:Mon, 29 Nov 2021 15:09:53 GMT
x-ms-version:2019-02-02
/invalido/frameworktestcontainer
comp:list
restype:container
11/29/2021 04:09:53 PM INFO: AZURE Client-Request-ID=68093b56-5126-11ec-b835-79a1cba11dcc Outgoing request: Method=GET, Path=/frameworktestcontainer, Query={'restype': 'container', 'comp': 'list', 'prefix': None, 'delimiter': None, 'marker': None, 'maxresults': None, 'include': None, 'timeout': None}, Headers={'x-ms-version': '2019-02-02', 'User-Agent': 'Azure-Storage/2.1.0-2.1.0 (Python CPython 3.9.6; Linux 5.15.5-arch1-1)', 'x-ms-client-request-id': '68093b56-5126-11ec-b835-79a1cba11dcc', 'x-ms-date': 'Mon, 29 Nov 2021 15:09:53 GMT', 'Authorization': 'REDACTED'}.
11/29/2021 04:09:53 PM DEBUG: AZURE Starting new HTTPS connection (1): invalido.blob.core.windows.net:443
11/29/2021 04:09:53 PM INFO: AZURE Client-Request-ID=68093b56-5126-11ec-b835-79a1cba11dcc Operation failed: checking if the operation should be retried. Current retry count=0, , HTTP status code=Unknown, Exception=HTTPSConnectionPool(host='invalido.blob.core.windows.net', port=443): Max retries exceeded with url: /frameworktestcontainer?restype=container&comp=list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3c215ddb80>: Failed to establish a new connection: [Errno -2] Name or service not known')).
11/29/2021 04:09:53 PM INFO: AZURE Client-Request-ID=68093b56-5126-11ec-b835-79a1cba11dcc Retry policy is allowing a retry: Retry count=1, Interval=15.34370803293641.
11/29/2021 04:10:09 PM DEBUG: AZURE String_to_sign=GET











x-ms-client-request-id:68093b56-5126-11ec-b835-79a1cba11dcc
x-ms-date:Mon, 29 Nov 2021 15:10:09 GMT
x-ms-version:2019-02-02
/invalido/frameworktestcontainer
comp:list
restype:container
11/29/2021 04:10:09 PM INFO: AZURE Client-Request-ID=68093b56-5126-11ec-b835-79a1cba11dcc Outgoing request: Method=GET, Path=/frameworktestcontainer, Query={'restype': 'container', 'comp': 'list', 'prefix': None, 'delimiter': None, 'marker': None, 'maxresults': None, 'include': None, 'timeout': None}, Headers={'x-ms-version': '2019-02-02', 'User-Agent': 'Azure-Storage/2.1.0-2.1.0 (Python CPython 3.9.6; Linux 5.15.5-arch1-1)', 'x-ms-client-request-id': '68093b56-5126-11ec-b835-79a1cba11dcc', 'x-ms-date': 'Mon, 29 Nov 2021 15:10:09 GMT', 'Authorization': 'REDACTED'}.
11/29/2021 04:10:09 PM DEBUG: AZURE Starting new HTTPS connection (2): invalido.blob.core.windows.net:443
11/29/2021 04:10:09 PM INFO: AZURE Client-Request-ID=68093b56-5126-11ec-b835-79a1cba11dcc Operation failed: checking if the operation should be retried. Current retry count=1, , HTTP status code=Unknown, Exception=HTTPSConnectionPool(host='invalido.blob.core.windows.net', port=443): Max retries exceeded with url: /frameworktestcontainer?restype=container&comp=list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3c215ddd60>: Failed to establish a new connection: [Errno -2] Name or service not known')).
11/29/2021 04:10:09 PM INFO: AZURE Client-Request-ID=68093b56-5126-11ec-b835-79a1cba11dcc Retry policy is allowing a retry: Retry count=2, Interval=16.0876123065821.
11/29/2021 04:10:25 PM DEBUG: AZURE String_to_sign=GET











x-ms-client-request-id:68093b56-5126-11ec-b835-79a1cba11dcc
x-ms-date:Mon, 29 Nov 2021 15:10:25 GMT
x-ms-version:2019-02-02
/invalido/frameworktestcontainer
comp:list
restype:container
11/29/2021 04:10:25 PM INFO: AZURE Client-Request-ID=68093b56-5126-11ec-b835-79a1cba11dcc Outgoing request: Method=GET, Path=/frameworktestcontainer, Query={'restype': 'container', 'comp': 'list', 'prefix': None, 'delimiter': None, 'marker': None, 'maxresults': None, 'include': None, 'timeout': None}, Headers={'x-ms-version': '2019-02-02', 'User-Agent': 'Azure-Storage/2.1.0-2.1.0 (Python CPython 3.9.6; Linux 5.15.5-arch1-1)', 'x-ms-client-request-id': '68093b56-5126-11ec-b835-79a1cba11dcc', 'x-ms-date': 'Mon, 29 Nov 2021 15:10:25 GMT', 'Authorization': 'REDACTED'}.
11/29/2021 04:10:25 PM DEBUG: AZURE Starting new HTTPS connection (3): invalido.blob.core.windows.net:443
11/29/2021 04:10:25 PM INFO: AZURE Client-Request-ID=68093b56-5126-11ec-b835-79a1cba11dcc Operation failed: checking if the operation should be retried. Current retry count=2, , HTTP status code=Unknown, Exception=HTTPSConnectionPool(host='invalido.blob.core.windows.net', port=443): Max retries exceeded with url: /frameworktestcontainer?restype=container&comp=list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3c215ddbb0>: Failed to establish a new connection: [Errno -2] Name or service not known')).
11/29/2021 04:10:25 PM INFO: AZURE Client-Request-ID=68093b56-5126-11ec-b835-79a1cba11dcc Retry policy is allowing a retry: Retry count=3, Interval=25.461412587286965.
11/29/2021 04:10:50 PM DEBUG: AZURE String_to_sign=GET











x-ms-client-request-id:68093b56-5126-11ec-b835-79a1cba11dcc
x-ms-date:Mon, 29 Nov 2021 15:10:50 GMT
x-ms-version:2019-02-02
/invalido/frameworktestcontainer
comp:list
restype:container
11/29/2021 04:10:50 PM INFO: AZURE Client-Request-ID=68093b56-5126-11ec-b835-79a1cba11dcc Outgoing request: Method=GET, Path=/frameworktestcontainer, Query={'restype': 'container', 'comp': 'list', 'prefix': None, 'delimiter': None, 'marker': None, 'maxresults': None, 'include': None, 'timeout': None}, Headers={'x-ms-version': '2019-02-02', 'User-Agent': 'Azure-Storage/2.1.0-2.1.0 (Python CPython 3.9.6; Linux 5.15.5-arch1-1)', 'x-ms-client-request-id': '68093b56-5126-11ec-b835-79a1cba11dcc', 'x-ms-date': 'Mon, 29 Nov 2021 15:10:50 GMT', 'Authorization': 'REDACTED'}.
11/29/2021 04:10:50 PM DEBUG: AZURE Starting new HTTPS connection (4): invalido.blob.core.windows.net:443
11/29/2021 04:10:50 PM INFO: AZURE Client-Request-ID=68093b56-5126-11ec-b835-79a1cba11dcc Operation failed: checking if the operation should be retried. Current retry count=3, , HTTP status code=Unknown, Exception=HTTPSConnectionPool(host='invalido.blob.core.windows.net', port=443): Max retries exceeded with url: /frameworktestcontainer?restype=container&comp=list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3c215ddee0>: Failed to establish a new connection: [Errno -2] Name or service not known')).
11/29/2021 04:10:50 PM ERROR: AZURE Client-Request-ID=68093b56-5126-11ec-b835-79a1cba11dcc Retry policy did not allow for a retry: , HTTP status code=Unknown, Exception=HTTPSConnectionPool(host='invalido.blob.core.windows.net', port=443): Max retries exceeded with url: /frameworktestcontainer?restype=container&comp=list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3c215ddee0>: Failed to establish a new connection: [Errno -2] Name or service not known')).
11/29/2021 04:10:50 PM ERROR: AZURE Storage: Error getting blobs: 'HTTPSConnectionPool(host='invalido.blob.core.windows.net', port=443): Max retries exceeded with url: /frameworktestcontainer?restype=container&comp=list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3c215ddee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))'.
11/29/2021 04:10:50 PM INFO: AZURE Updating /var/ossec/wodles/azure/last_dates.json file.
11/29/2021 04:10:50 PM INFO: AZURE Storage: End
```
</p>

</details>

The module keeps retrying for a long time with the invalid credentials as shown below:

```
root@1b335b872bf4:/var/ossec/wodles/azure# time /var/ossec/wodles/azure/azure-logs --account_name invalido --account_key invalido --storage --container frameworktestcontainer --storage_time_offset 10h   

real	0m57.571s
user	0m0.162s
sys	0m0.031s
```  

It also stores in the `last_dates.json` file information regarding the failed execution when it shouldn´t. 
```
root@1b335b872bf4:/var/ossec/wodles/azure# cat last_dates.json
{"log_analytics": {}, "graph": {}, "storage": {"276fdc115c93c665ecb3616a9bca2e65": {"min": "2021-11-29T05:31:59.017007Z", "max": "2021-11-29T05:31:59.017007Z"}}}
```

### Using a wrong `container` value
Instead of finishing the execution and returning a plain error message the module will try to connect to it.

<details><summary>Execution with an invalid container</summary>

<p>

```
root@1b335b872bf4:/var/ossec/wodles/azure# /var/ossec/wodles/azure/azure-logs --storage --container invalid --storage_time_offset 10h --storage_auth_path /var/ossec/wodles/azure/credentials-storage -v
11/29/2021 05:08:07 PM INFO: AZURE Getting the data from /var/ossec/wodles/azure/last_dates.json.
11/29/2021 05:08:07 PM INFO: AZURE Azure Storage starting.
11/29/2021 05:08:07 PM INFO: AZURE Storage: Authenticating.
11/29/2021 05:08:07 PM INFO: AZURE Storage: Authenticated.
11/29/2021 05:08:07 PM INFO: AZURE Storage: Getting containers.
11/29/2021 05:08:07 PM INFO: AZURE Storage: Getting blobs.
11/29/2021 05:08:07 PM DEBUG: AZURE String_to_sign=GET











x-ms-client-request-id:8a80e799-512e-11ec-b71f-4ba46d91cb47
x-ms-date:Mon, 29 Nov 2021 16:08:07 GMT
x-ms-version:2019-02-02
/frameworkteststorage/invalid
comp:list
restype:container
11/29/2021 05:08:07 PM INFO: AZURE Client-Request-ID=8a80e799-512e-11ec-b71f-4ba46d91cb47 Outgoing request: Method=GET, Path=/invalid, Query={'restype': 'container', 'comp': 'list', 'prefix': None, 'delimiter': None, 'marker': None, 'maxresults': None, 'include': None, 'timeout': None}, Headers={'x-ms-version': '2019-02-02', 'User-Agent': 'Azure-Storage/2.1.0-2.1.0 (Python CPython 3.9.6; Linux 5.15.5-arch1-1)', 'x-ms-client-request-id': '8a80e799-512e-11ec-b71f-4ba46d91cb47', 'x-ms-date': 'Mon, 29 Nov 2021 16:08:07 GMT', 'Authorization': 'REDACTED'}.
11/29/2021 05:08:07 PM DEBUG: AZURE Starting new HTTPS connection (1): frameworkteststorage.blob.core.windows.net:443
11/29/2021 05:08:08 PM DEBUG: AZURE https://frameworkteststorage.blob.core.windows.net:443 "GET /invalid?restype=container&comp=list HTTP/1.1" 404 225
11/29/2021 05:08:08 PM INFO: AZURE Client-Request-ID=8a80e799-512e-11ec-b71f-4ba46d91cb47 Receiving Response: Server-Timestamp=Mon, 29 Nov 2021 16:08:07 GMT, Server-Request-ID=2d1fa308-601e-0008-3d3b-e5b2f8000000, HTTP Status Code=404, Message=The specified container does not exist., Headers={'content-length': '225', 'content-type': 'application/xml', 'server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': '2d1fa308-601e-0008-3d3b-e5b2f8000000', 'x-ms-client-request-id': '8a80e799-512e-11ec-b71f-4ba46d91cb47', 'x-ms-version': '2019-02-02', 'x-ms-error-code': 'ContainerNotFound', 'date': 'Mon, 29 Nov 2021 16:08:07 GMT'}.
11/29/2021 05:08:08 PM INFO: AZURE Client-Request-ID=8a80e799-512e-11ec-b71f-4ba46d91cb47 Operation failed: checking if the operation should be retried. Current retry count=0, Server-Timestamp=Mon, 29 Nov 2021 16:08:07 GMT, Server-Request-ID=2d1fa308-601e-0008-3d3b-e5b2f8000000, HTTP status code=404, Exception=The specified container does not exist. ErrorCode: ContainerNotFound<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerNotFound</Code><Message>The specified container does not exist.RequestId:2d1fa308-601e-0008-3d3b-e5b2f8000000Time:2021-11-29T16:08:08.0699843Z</Message></Error>.
11/29/2021 05:08:08 PM ERROR: AZURE Client-Request-ID=8a80e799-512e-11ec-b71f-4ba46d91cb47 Retry policy did not allow for a retry: Server-Timestamp=Mon, 29 Nov 2021 16:08:07 GMT, Server-Request-ID=2d1fa308-601e-0008-3d3b-e5b2f8000000, HTTP status code=404, Exception=The specified container does not exist. ErrorCode: ContainerNotFound<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerNotFound</Code><Message>The specified container does not exist.RequestId:2d1fa308-601e-0008-3d3b-e5b2f8000000Time:2021-11-29T16:08:08.0699843Z</Message></Error>.
11/29/2021 05:08:08 PM ERROR: AZURE Storage: Error getting blobs: 'The specified container does not exist. ErrorCode: ContainerNotFound
<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerNotFound</Code><Message>The specified container does not exist.
RequestId:2d1fa308-601e-0008-3d3b-e5b2f8000000
Time:2021-11-29T16:08:08.0699843Z</Message></Error>'.
11/29/2021 05:08:08 PM INFO: AZURE Updating /var/ossec/wodles/azure/last_dates.json file.
11/29/2021 05:08:08 PM INFO: AZURE Storage: End

```
</p>

</details>  

It will also save in the `last_dates.json` file an entry corresponding to the non-existent container when it shouldn't.
```
root@1b335b872bf4:/var/ossec/wodles/azure# cat last_dates.json ; echo
{"log_analytics": {}, "graph": {}, "storage": {"82e049b81fa6eb88ebf85f1677785f2b": {"min": "2021-11-29T06:05:26.092892Z", "max": "2021-11-29T06:05:26.092892Z"}}}
```

## Tasks
- [x] Make the module abort the execution when invalid credentials were specified
- [x] Test in a manager
- [x] Test in an agent
- [x] Update the documentation if necessary
- [x] Add entry to the changelog if necessary

**Comment by CarlosRS9** [comment]
# Status Update


Both issues have been addressed and fixed. The Storage integration will now try to access the specified container to ensure the credentials allow it. If the credentials are not valid an error message will be shown.

The manual testing for this fix has not finished yet as we have detected a strange case where an "incorrect padding" error is shown. We are verifying that no further changes are necessary. We will attach the test results once we finish this investigation.

**Comment by CarlosRS9** [comment]
# Status update

The research, development and testing have been completed. Here is a list of the changes introduced.

## Changes

- A new check has been added to validate if the specified credentials provide access to the required container. In case the credentials are not valid an error will be displayed and the execution will be terminated, leaving the `last_dates.json` file untouched.
- The module has been modified so the credentials validation is only attempted once. If it fails, the default max retries (which was 3) will not be applied. For the rest of the API calls it will still be applied.
- The logging configuration has been modified to not show INFO or DEBUG messages corresponding to the Azure module and URLLIB3 in the `azure-logs-log` file. Such messages will still appear in the command output if executed manually with the `-v` option.

## Testing

### Using a wrong `account_name` or `account_key`
Azure Storage module with invalid credentials, instead of finishing the execution and returning a plain error message the module keeps trying to connect with the wrong credentials for a long time.  

The output displayed when using the `-v` option is the following:

<details><summary>Output from the command using -v</summary>

    12/10/2021 01:39:11 PM INFO: AZURE Getting the data from /var/ossec/wodles/azure/last_dates.json.
    12/10/2021 01:39:11 PM INFO: AZURE Azure Storage starting.
    12/10/2021 01:39:11 PM INFO: AZURE Storage: Authenticating.
    12/10/2021 01:39:11 PM DEBUG: AZURE String_to_sign=GET











    x-ms-client-request-id:8e92b168-59be-11ec-af37-f9ab4ef6288e
    x-ms-date:Fri, 10 Dec 2021 13:39:11 GMT
    x-ms-version:2019-02-02
    /invalido123445/frameworktestcontainer
    comp:list
    maxresults:1
    restype:container
    12/10/2021 01:39:11 PM INFO: AZURE Client-Request-ID=8e92b168-59be-11ec-af37-f9ab4ef6288e Outgoing request: Method=GET, Path=/frameworktestcontainer, Query={'restype': 'container', 'comp': 'list', 'prefix': None, 'delimiter': None, 'marker': None, 'maxresults': '1', 'include': None, 'timeout': None}, Headers={'x-ms-version': '2019-02-02', 'User-Agent': 'Azure-Storage/2.1.0-2.1.0 (Python CPython 3.9.6; Linux 5.15.6-200.fc35.x86_64)', 'x-ms-client-request-id': '8e92b168-59be-11ec-af37-f9ab4ef6288e', 'x-ms-date': 'Fri, 10 Dec 2021 13:39:11 GMT', 'Authorization': 'REDACTED'}.
    12/10/2021 01:39:11 PM DEBUG: AZURE Starting new HTTPS connection (1): invalido123445.blob.core.windows.net:443
    12/10/2021 01:39:11 PM INFO: AZURE Client-Request-ID=8e92b168-59be-11ec-af37-f9ab4ef6288e Operation failed: checking if the operation should be retried. Current retry count=0, , HTTP status code=Unknown, Exception=HTTPSConnectionPool(host='invalido123445.blob.core.windows.net', port=443): Max retries exceeded with url: /frameworktestcontainer?restype=container&comp=list&maxresults=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f613e84fe20>: Failed to establish a new connection: [Errno -2] Name or service not known')).
    12/10/2021 01:39:11 PM ERROR: AZURE Client-Request-ID=8e92b168-59be-11ec-af37-f9ab4ef6288e Retry policy did not allow for a retry: , HTTP status code=Unknown, Exception=HTTPSConnectionPool(host='invalido123445.blob.core.windows.net', port=443): Max retries exceeded with url: /frameworktestcontainer?restype=container&comp=list&maxresults=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f613e84fe20>: Failed to establish a new connection: [Errno -2] Name or service not known')).
    12/10/2021 01:39:11 PM ERROR: AZURE Storage: Invalid credentials for accessing the 'frameworktestcontainer' container.
</details>


<details><summary>Output from the azure-logs.log file</summary>

    12/10/2021 01:39:41 PM INFO: AZURE Getting the data from /var/ossec/wodles/azure/last_dates.json.
    12/10/2021 01:39:41 PM INFO: AZURE Azure Storage starting.
    12/10/2021 01:39:41 PM INFO: AZURE Storage: Authenticating.
    12/10/2021 01:39:41 PM ERROR: AZURE Client-Request-ID=a0d805fd-59be-11ec-b77f-49e5a3715d9f Retry policy did not allow for a retry: , HTTP status code=Unknown, Exception=HTTPSConnectionPool(host='invalido123445.blob.core.windows.net', port=443): Max retries exceeded with url: /frameworktestcontainer?restype=container&comp=list&maxresults=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f15f83c7e20>: Failed to establish a new connection: [Errno -2] Name or service not known')).
    12/10/2021 01:39:41 PM ERROR: AZURE Storage: Invalid credentials for accessing the 'frameworktestcontainer' container.
</details>

The module tried to validate the credentials without attempting it again as the validation failed. The new `Invalid credentials for accessing the 'frameworktestcontainer' container` message was shown. The `last_dates.json` file was not updated.



### Using a wrong `container` value


<details><summary>Output from the command using -v</summary>

    /var/ossec/wodles/azure/azure-logs --storage --container invalid --storage_time_offset 10h --storage_auth_path /var/ossec/wodles/azure/credentials-storage -v

    12/10/2021 01:45:39 PM INFO: AZURE Getting the data from /var/ossec/wodles/azure/last_dates.json.
    12/10/2021 01:45:39 PM INFO: AZURE Azure Storage starting.
    12/10/2021 01:45:39 PM INFO: AZURE Storage: Authenticating.
    12/10/2021 01:45:39 PM DEBUG: AZURE String_to_sign=GET











    x-ms-client-request-id:75cd91c5-59bf-11ec-bb22-f97968702198
    x-ms-date:Fri, 10 Dec 2021 13:45:39 GMT
    x-ms-version:2019-02-02
    /frameworkteststorage/invalid
    comp:list
    maxresults:1
    restype:container
    12/10/2021 01:45:39 PM INFO: AZURE Client-Request-ID=75cd91c5-59bf-11ec-bb22-f97968702198 Outgoing request: Method=GET, Path=/invalid, Query={'restype': 'container', 'comp': 'list', 'prefix': None, 'delimiter': None, 'marker': None, 'maxresults': '1', 'include': None, 'timeout': None}, Headers={'x-ms-version': '2019-02-02', 'User-Agent': 'Azure-Storage/2.1.0-2.1.0 (Python CPython 3.9.6; Linux 5.15.6-200.fc35.x86_64)', 'x-ms-client-request-id': '75cd91c5-59bf-11ec-bb22-f97968702198', 'x-ms-date': 'Fri, 10 Dec 2021 13:45:39 GMT', 'Authorization': 'REDACTED'}.
    12/10/2021 01:45:39 PM DEBUG: AZURE Starting new HTTPS connection (1): frameworkteststorage.blob.core.windows.net:443
    12/10/2021 01:45:39 PM DEBUG: AZURE https://frameworkteststorage.blob.core.windows.net:443 "GET /invalid?restype=container&comp=list&maxresults=1 HTTP/1.1" 404 225
    12/10/2021 01:45:39 PM INFO: AZURE Client-Request-ID=75cd91c5-59bf-11ec-bb22-f97968702198 Receiving Response: Server-Timestamp=Fri, 10 Dec 2021 13:45:38 GMT, Server-Request-ID=aa475fee-301e-0015-0dcc-edbf44000000, HTTP Status Code=404, Message=The specified container does not exist., Headers={'content-length': '225', 'content-type': 'application/xml', 'server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': 'aa475fee-301e-0015-0dcc-edbf44000000', 'x-ms-client-request-id': '75cd91c5-59bf-11ec-bb22-f97968702198', 'x-ms-version': '2019-02-02', 'x-ms-error-code': 'ContainerNotFound', 'date': 'Fri, 10 Dec 2021 13:45:38 GMT'}.
    12/10/2021 01:45:39 PM INFO: AZURE Client-Request-ID=75cd91c5-59bf-11ec-bb22-f97968702198 Operation failed: checking if the operation should be retried. Current retry count=0, Server-Timestamp=Fri, 10 Dec 2021 13:45:38 GMT, Server-Request-ID=aa475fee-301e-0015-0dcc-edbf44000000, HTTP status code=404, Exception=The specified container does not exist. ErrorCode: ContainerNotFound<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerNotFound</Code><Message>The specified container does not exist.RequestId:aa475fee-301e-0015-0dcc-edbf44000000Time:2021-12-10T13:45:39.5782296Z</Message></Error>.
    12/10/2021 01:45:39 PM ERROR: AZURE Client-Request-ID=75cd91c5-59bf-11ec-bb22-f97968702198 Retry policy did not allow for a retry: Server-Timestamp=Fri, 10 Dec 2021 13:45:38 GMT, Server-Request-ID=aa475fee-301e-0015-0dcc-edbf44000000, HTTP status code=404, Exception=The specified container does not exist. ErrorCode: ContainerNotFound<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerNotFound</Code><Message>The specified container does not exist.RequestId:aa475fee-301e-0015-0dcc-edbf44000000Time:2021-12-10T13:45:39.5782296Z</Message></Error>.
    12/10/2021 01:45:39 PM ERROR: AZURE Storage: Invalid credentials for accessing the 'invalid' container.
</details>


<details><summary>Output from the azure-logs.log file</summary>

    /var/ossec/wodles/azure/azure-logs --storage --container invalid --storage_time_offset 10h --storage_auth_path /var/ossec/wodles/azure/credentials-storage

    12/10/2021 01:45:46 PM INFO: AZURE Getting the data from /var/ossec/wodles/azure/last_dates.json.
    12/10/2021 01:45:46 PM INFO: AZURE Azure Storage starting.
    12/10/2021 01:45:46 PM INFO: AZURE Storage: Authenticating.
    12/10/2021 01:45:47 PM ERROR: AZURE Client-Request-ID=7a365279-59bf-11ec-b5f4-238ba45ab875 Retry policy did not allow for a retry: Server-Timestamp=Fri, 10 Dec 2021 13:45:46 GMT, Server-Request-ID=f4916d75-d01e-0032-52cc-eda880000000, HTTP status code=404, Exception=The specified container does not exist. ErrorCode: ContainerNotFound<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerNotFound</Code><Message>The specified container does not exist.RequestId:f4916d75-d01e-0032-52cc-eda880000000Time:2021-12-10T13:45:46.9743574Z</Message></Error>.
    12/10/2021 01:45:47 PM ERROR: AZURE Storage: Invalid credentials for accessing the 'invalid' container.
</details>

The module tried to validate the credentials without attempting it again as the validation failed. The new `Invalid credentials for accessing the 'invalid' container` message was shown. The `last_dates.json` file was not updated.
