### ISSUE TITLE
Fix Azure integration's configuration parsing

### ISSUE THREAD

**Issue by noise-kngdm** [wazuh/wazuh#11116]
| Affected integration |
|---|
|  Azure|

## Description
While working on #10966 we realized that the configuration of none of the Azure integrations is being correctly parsed.

### Graph
The following should be a valid configuration. According to the [Wazuh documentation](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-azure-logs.html#graph-request-time-offset), the `time_offset` tag has a default value, so it shouldn't be required in order to use the integration.
```
<wodle name="azure-logs">
  <disabled>no</disabled>
  <interval>10m</interval>
  <run_on_start>yes</run_on_start>

  <graph>
    <auth_path>/var/ossec/wodles/azure/credentials</auth_path>
    <tenantdomain>wazuh.onmicrosoft.com</tenantdomain>
    <request>
        <query>auditLogs/directoryAudits</query>
    </request>

    <request>
        <query>auditLogs/directoryAudits</query>
        <time_offset>2d</time_offset>
    </request>

    <request>
        <query>auditLogs/directoryAudits</query>
        <time_offset>3d</time_offset>
    </request>
  </graph>
</wodle>
```

Executing `service wazuh-manager restart` on a machine after adding this to the `ossec.conf` file shows the following error messages as part of the output:

```
2021/11/30 16:27:18 wazuh-modulesd: INFO: At module 'azure-logs': No request tag defined. Setting it randomly...
2021/11/30 16:27:18 wazuh-modulesd: ERROR: At module 'azure-logs': No time offset defined. Skipping request block...
2021/11/30 16:27:18 wazuh-modulesd: INFO: At module 'azure-logs': No request tag defined. Setting it randomly...
2021/11/30 16:27:18 wazuh-modulesd: INFO: At module 'azure-logs': No request tag defined. Setting it randomly...
```

<details><summary>Full command's output</summary>

<p>

```
root@9c9e87a51748:/var/ossec/wodles/azure# service wazuh-manager restart
Killing wazuh-clusterd...
Killing wazuh-modulesd...
Killing wazuh-monitord...
Killing wazuh-logcollector...
Killing wazuh-remoted...
Killing wazuh-syscheckd...
Killing wazuh-analysisd...
wazuh-maild not running...
Killing wazuh-execd...
Killing wazuh-db...
Killing wazuh-authd...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
Killing wazuh-apid...
Wazuh v4.3.0 Stopped
2021/11/30 16:27:09 wazuh-db[17474] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2021/11/30 16:27:09 wazuh-db[17474] main.c:101 at main(): DEBUG: Wazuh home directory: /var/ossec
2021/11/30 16:27:09 wazuh-remoted[17479] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2021/11/30 16:27:09 wazuh-remoted[17479] main.c:130 at main(): DEBUG: Wazuh home directory: /var/ossec
2021/11/30 16:27:09 wazuh-remoted[17479] main.c:148 at main(): DEBUG: This is not a worker
2021/11/30 16:27:09 wazuh-modulesd: INFO: At module 'azure-logs': No request tag defined. Setting it randomly...
2021/11/30 16:27:09 wazuh-modulesd: ERROR: At module 'azure-logs': No time offset defined. Skipping request block...
2021/11/30 16:27:09 wazuh-modulesd: INFO: At module 'azure-logs': No request tag defined. Setting it randomly...
2021/11/30 16:27:09 wazuh-modulesd: INFO: At module 'azure-logs': No request tag defined. Setting it randomly...
Starting Wazuh v4.3.0...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
2021/11/30 16:27:12 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
Started wazuh-integratord...
Started wazuh-agentlessd...
2021/11/30 16:27:12 wazuh-authd[17542] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2021/11/30 16:27:12 wazuh-authd[17542] config.c:20 at authd_read_config(): DEBUG: Reading configuration 'etc/ossec.conf'
2021/11/30 16:27:12 wazuh-authd[17542] main-server.c:372 at main(): DEBUG: Wazuh home directory: /var/ossec
Started wazuh-authd...
2021/11/30 16:27:13 wazuh-db[17558] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2021/11/30 16:27:13 wazuh-db[17558] main.c:101 at main(): DEBUG: Wazuh home directory: /var/ossec
Started wazuh-db...
Started wazuh-execd...
Started wazuh-analysisd...
Started wazuh-syscheckd...
2021/11/30 16:27:16 wazuh-remoted[17786] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2021/11/30 16:27:16 wazuh-remoted[17786] main.c:130 at main(): DEBUG: Wazuh home directory: /var/ossec
2021/11/30 16:27:16 wazuh-remoted[17786] main.c:148 at main(): DEBUG: This is not a worker
Started wazuh-remoted...
Started wazuh-logcollector...
Started wazuh-monitord...
2021/11/30 16:27:18 wazuh-modulesd: INFO: At module 'azure-logs': No request tag defined. Setting it randomly...
2021/11/30 16:27:18 wazuh-modulesd: ERROR: At module 'azure-logs': No time offset defined. Skipping request block...
2021/11/30 16:27:18 wazuh-modulesd: INFO: At module 'azure-logs': No request tag defined. Setting it randomly...
2021/11/30 16:27:18 wazuh-modulesd: INFO: At module 'azure-logs': No request tag defined. Setting it randomly...
Started wazuh-modulesd...
Started wazuh-clusterd...
Completed.

```

</p>

</details>

### Log Analytics
The following should be a valid configuration. According to the [Wazuh documentation](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-azure-logs.html#log-analytics-request-time-offset), the `time_offset` tag has a default value, so it shouldn't be required in order to use the integration.
```
<wodle name="azure-logs">
  <disabled>no</disabled>
  <interval>10m</interval>
  <run_on_start>yes</run_on_start>
   <log_analytics>
    <auth_path>/var/ossec/wodles/azure/credentials-analytics</auth_path>
    <tenantdomain>wazuh.onmicrosoft.com</tenantdomain>

     <request>
      <tag>azure-diagnostics</tag>
      <query>AzureDiagnostics</query>
      <workspace>bc8d21bd-b966-4a4f-8eed-9e0328720cbe</workspace>
    </request>

     <request>
      <tag>azure-activity</tag>
      <query>AzureActivity</query>
      <workspace>bc8d21bd-b966-4a4f-8eed-9e0328720cbe</workspace>
      <time_offset>14d</time_offset>
    </request>

     <request>
      <tag>azure-diagnostics</tag>
      <query>AzureDiagnostics</query>
      <workspace>bc8d21bd-b966-4a4f-8eed-9e0328720cbe</workspace>
      <time_offset>1d</time_offset>
    </request>

     <request>
      <tag>azure-diagnostics</tag>
      <query>AzureDiagnostics</query>
      <workspace>bc8d21bd-b966-4a4f-8eed-9e0328720cbe</workspace>
      <time_offset>30d</time_offset>
    </request>
   </log_analytics>
 </wodle>
```

Executing `service wazuh-manager restart` on a machine after adding this to the `ossec.conf` file shows the following error messages as part of the output:

```
2021/11/30 16:02:16 wazuh-modulesd: ERROR: At module 'azure-logs': No time offset defined. Skipping request block...
```

<details><summary>Full command's output</summary>

<p>

```
Killing wazuh-clusterd...
Killing wazuh-modulesd...
Killing wazuh-monitord...
Killing wazuh-logcollector...
Killing wazuh-remoted...
Killing wazuh-syscheckd...
Killing wazuh-analysisd...
wazuh-maild not running...
Killing wazuh-execd...
Killing wazuh-db...
Killing wazuh-authd...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
Killing wazuh-apid...
Wazuh v4.3.0 Stopped
2021/11/30 16:02:05 wazuh-db[14222] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2021/11/30 16:02:05 wazuh-db[14222] main.c:101 at main(): DEBUG: Wazuh home directory: /var/ossec
2021/11/30 16:02:05 wazuh-remoted[14227] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2021/11/30 16:02:05 wazuh-remoted[14227] main.c:130 at main(): DEBUG: Wazuh home directory: /var/ossec
2021/11/30 16:02:05 wazuh-remoted[14227] main.c:148 at main(): DEBUG: This is not a worker
2021/11/30 16:02:05 wazuh-modulesd: ERROR: At module 'azure-logs': No time offset defined. Skipping request block...
Starting Wazuh v4.3.0...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
2021/11/30 16:02:08 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
Started wazuh-integratord...
Started wazuh-agentlessd...
2021/11/30 16:02:08 wazuh-authd[14290] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2021/11/30 16:02:08 wazuh-authd[14290] config.c:20 at authd_read_config(): DEBUG: Reading configuration 'etc/ossec.conf'
2021/11/30 16:02:08 wazuh-authd[14290] main-server.c:372 at main(): DEBUG: Wazuh home directory: /var/ossec
Started wazuh-authd...
2021/11/30 16:02:09 wazuh-db[14306] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2021/11/30 16:02:09 wazuh-db[14306] main.c:101 at main(): DEBUG: Wazuh home directory: /var/ossec
Started wazuh-db...
Started wazuh-execd...
Started wazuh-analysisd...
Started wazuh-syscheckd...
2021/11/30 16:02:13 wazuh-remoted[14537] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2021/11/30 16:02:13 wazuh-remoted[14537] main.c:130 at main(): DEBUG: Wazuh home directory: /var/ossec
2021/11/30 16:02:13 wazuh-remoted[14537] main.c:148 at main(): DEBUG: This is not a worker
Started wazuh-remoted...
Started wazuh-logcollector...
Started wazuh-monitord...
2021/11/30 16:02:16 wazuh-modulesd: ERROR: At module 'azure-logs': No time offset defined. Skipping request block...
Started wazuh-modulesd...
Started wazuh-clusterd...
Completed.

```

</p>

</details>

### Storage
The following should be a valid configuration. The script is prepared to be executed without specifying any `blob`, `content_type`, or `time_offset`, as shown in **Storage's test 12** from #10966.
```
<wodle name="azure-logs">
  <disabled>no</disabled>
  <interval>10m</interval>
  <run_on_start>yes</run_on_start>

  <storage>
      <auth_path>/var/ossec/wodles/azure/credentials-storage</auth_path>
      <tag>azure-activity</tag>

      <container name="frameworktestcontainer">
          <content_type>json_inline</content_type>
          <time_offset>50d</time_offset>
      </container>

      <container name="frameworktestcontainer">
          <blobs>.txt</blobs>
          <time_offset>50d</time_offset>
      </container>

      <container name="frameworktestcontainer">
          <blobs>.txt</blobs>
          <content_type>json_inline</content_type>
      </container>

      <container name="frameworktestcontainer"></container>
  </storage>
</wodle>
```

Executing `service wazuh-manager restart` on a machine after adding this to the `ossec.conf` file shows the following error messages as part of the output:

```
2021/11/30 11:37:18 wazuh-modulesd: ERROR: At module 'azure-logs': No blobs defined. Skipping container block...
2021/11/30 11:37:18 wazuh-modulesd: ERROR: At module 'azure-logs': No content type defined. Skipping container block...
2021/11/30 11:37:18 wazuh-modulesd: ERROR: At module 'azure-logs': No time offset defined. Skipping container block...
2021/11/30 11:37:18 wazuh-modulesd: ERROR: (1230): Invalid element in the configuration: 'container'.
```

<details><summary>Full command's output</summary>

<p>

```
root@cf5d62c519fe:/var/ossec/wodles/azure# service wazuh-manager restart
Killing wazuh-clusterd...
Killing wazuh-modulesd...
Killing wazuh-monitord...
Killing wazuh-logcollector...
Killing wazuh-remoted...
Killing wazuh-syscheckd...
Killing wazuh-analysisd...
wazuh-maild not running...
Killing wazuh-execd...
Killing wazuh-db...
Killing wazuh-authd...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
Killing wazuh-apid...
Wazuh v4.3.0 Stopped
2021/11/30 11:36:29 wazuh-db[11655] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2021/11/30 11:36:29 wazuh-db[11655] main.c:101 at main(): DEBUG: Wazuh home directory: /var/ossec
2021/11/30 11:36:29 wazuh-remoted[11660] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2021/11/30 11:36:29 wazuh-remoted[11660] main.c:130 at main(): DEBUG: Wazuh home directory: /var/ossec
2021/11/30 11:36:29 wazuh-remoted[11660] main.c:148 at main(): DEBUG: This is not a worker
2021/11/30 11:36:29 wazuh-modulesd: ERROR: At module 'azure-logs': No blobs defined. Skipping container block...
2021/11/30 11:36:29 wazuh-modulesd: ERROR: At module 'azure-logs': No content type defined. Skipping container block...
2021/11/30 11:36:29 wazuh-modulesd: ERROR: At module 'azure-logs': No time offset defined. Skipping container block...
2021/11/30 11:36:29 wazuh-modulesd: ERROR: At module 'azure-logs': No container defined. Skipping block...
2021/11/30 11:36:29 wazuh-modulesd: ERROR: No such tag 'container' at module 'azure-logs'.
2021/11/30 11:36:29 wazuh-modulesd: ERROR: (1202): Configuration error at 'etc/ossec.conf'.
wazuh-modulesd: Configuration error. Exiting
root@cf5d62c519fe:/var/ossec/wodles/azure# vim ../../etc/ossec.conf 
root@cf5d62c519fe:/var/ossec/wodles/azure# service wazuh-manager restart
wazuh-clusterd not running...
wazuh-modulesd not running...
wazuh-monitord not running...
wazuh-logcollector not running...
wazuh-remoted not running...
wazuh-syscheckd not running...
wazuh-analysisd not running...
wazuh-maild not running...
wazuh-execd not running...
wazuh-db not running...
wazuh-authd not running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid not running...
Wazuh v4.3.0 Stopped
2021/11/30 11:37:08 wazuh-db[11739] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2021/11/30 11:37:08 wazuh-db[11739] main.c:101 at main(): DEBUG: Wazuh home directory: /var/ossec
2021/11/30 11:37:09 wazuh-remoted[11744] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2021/11/30 11:37:09 wazuh-remoted[11744] main.c:130 at main(): DEBUG: Wazuh home directory: /var/ossec
2021/11/30 11:37:09 wazuh-remoted[11744] main.c:148 at main(): DEBUG: This is not a worker
2021/11/30 11:37:09 wazuh-modulesd: ERROR: At module 'azure-logs': No blobs defined. Skipping container block...
2021/11/30 11:37:09 wazuh-modulesd: ERROR: At module 'azure-logs': No content type defined. Skipping container block...
2021/11/30 11:37:09 wazuh-modulesd: ERROR: At module 'azure-logs': No time offset defined. Skipping container block...
2021/11/30 11:37:09 wazuh-modulesd: ERROR: (1230): Invalid element in the configuration: 'container'.
Starting Wazuh v4.3.0...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
2021/11/30 11:37:12 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
Started wazuh-integratord...
Started wazuh-agentlessd...
2021/11/30 11:37:12 wazuh-authd[11807] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2021/11/30 11:37:12 wazuh-authd[11807] config.c:20 at authd_read_config(): DEBUG: Reading configuration 'etc/ossec.conf'
2021/11/30 11:37:12 wazuh-authd[11807] main-server.c:372 at main(): DEBUG: Wazuh home directory: /var/ossec
Started wazuh-authd...
2021/11/30 11:37:13 wazuh-db[11823] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2021/11/30 11:37:13 wazuh-db[11823] main.c:101 at main(): DEBUG: Wazuh home directory: /var/ossec
Started wazuh-db...
Started wazuh-execd...
Started wazuh-analysisd...
Started wazuh-syscheckd...
2021/11/30 11:37:17 wazuh-remoted[12054] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2021/11/30 11:37:17 wazuh-remoted[12054] main.c:130 at main(): DEBUG: Wazuh home directory: /var/ossec
2021/11/30 11:37:17 wazuh-remoted[12054] main.c:148 at main(): DEBUG: This is not a worker
Started wazuh-remoted...
Started wazuh-logcollector...
Started wazuh-monitord...
2021/11/30 11:37:18 wazuh-modulesd: ERROR: At module 'azure-logs': No blobs defined. Skipping container block...
2021/11/30 11:37:18 wazuh-modulesd: ERROR: At module 'azure-logs': No content type defined. Skipping container block...
2021/11/30 11:37:18 wazuh-modulesd: ERROR: At module 'azure-logs': No time offset defined. Skipping container block...
2021/11/30 11:37:18 wazuh-modulesd: ERROR: (1230): Invalid element in the configuration: 'container'.
Started wazuh-modulesd...
Started wazuh-clusterd...
Completed.

```

</p>

</details>

## Tasks
- [x] Fix Graph configuration
- [x] Fix Log Analytics configuration
- [x] Fix Storage configuration
- [x] Test in a manager
- [x] Update the documentation if necessary
- [x] Add entry to the changelog if necessary

**Comment by noise-kngdm** [comment]
## Issue update
We have successfully modified the Graph and Log Analytics configuration parser to avoid having to set a `time_offset` parameter, by removing the following check from `src/config/wmodules-azure.c`:

https://github.com/wazuh/wazuh/blob/d1a05b607f260d168d38088b13c1c703fa787908/src/config/wmodules-azure.c#L389-L392

We're currently working on the Storage configuration parser.

**Comment by noise-kngdm** [comment]
## Issue update
We have finished with the changes required to make those parameters optional, which are in this commit 97e4d61a1ee52aba040d8c867063c03ba0eabd71. Apart from the configuration parsing, we had to modify the way the arguments were generating by the `src/wazuh_modules/wm_azure.c` file before calling the `wazuh/wodles/azure/azure-logs.py` script

All the changes have been tested with several valid configurations and everything is working as expected, and now we're focusing on the unit tests.
