### ISSUE TITLE
Test Wazuh cluster performance at scale

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#11120]
As part of our continuous effort to improve the performance of Wazuh in loaded environments, we have been introducing several improvements and fixes to Wazuh cluster in recent versions (v4.1, v4.2 and v4.3). The majority of these improvements are related to `wazuh-clusterd` and `wazuh-apid` daemons performance, but there are others. We are working hard to ensure the product is able to scale well into big production environments.

The list of improvements includes but it is not limited to:
- Changed the cluster "local_integrity" task to run in a separate process to improve overall performance. (#10767)
- The cluster communication with the database for agent information synchronization runs in a parallel separate process. (#10807)
- The cluster processing of the extra-valid files in the master node is carried out in a parallel separate process. (#10920)
- Improved the cluster nodes integrity calculation process. It only calculates the MD5 of the files that have been modified since the last integrity check. (#8175)
- Changed the synchronization of agent information between cluster nodes to complete the synchronization in a single task for each worker. (#8182)
- Improved API requests processing time by applying cache to token RBAC permissions extraction. It will be invalidated if any resource related to the token is modified. (#8615)
- Increased to 100000 the maximum value accepted for limit API parameter, default value remains at 500. (#8841)
- Agent DB synchronization has been boosted by caching the last data checksum in Wazuh DB. (#9093)
- Improved Remoted performance with an agent TCP connection sending queue. (#10326)
- Changed request_slice calculation to improve efficiency when accessing wazuh-db data. (#8885)
- Fixed a bug that caused cluster agent-groups files to be synchronized multiple times unnecessarily. (#10866)
- Fixed an issue in Wazuh DB that compiled the SQL statements multiple times unnecessarily. (#10922)
- The manager's agent database has been fixed to prevent dangling entries from removed agents. (#10390)
- Prevented the manager from leaving dangling agent database files. (#8902)
- Changed thread pool executors for process pool executors to improve API availability. (#10916)
- Improved the performance of several API endpoints. This is specially appreciable in environments with a big number of agents. https://github.com/wazuh/wazuh/issues/8720

There are also some other improvements planned:
- https://github.com/wazuh/wazuh/issues/10980
- https://github.com/wazuh/wazuh/issues/10771
- https://github.com/wazuh/wazuh/issues/8251
- https://github.com/wazuh/wazuh/issues/10780
- https://github.com/wazuh/wazuh/issues/3072
- https://github.com/wazuh/wazuh/issues/11054
- [Migrate client.keys to wazuh-db](https://github.com/wazuh/wazuh/issues/83)
However, there are still some issues and doubts about the limits of a Wazuh cluster for a certain topology and hardware usage. We need to ensure the entire agent lifecycle runs smooth in a huge cluster, ensuring its registration and connectivity in a timely manner.
For example, issue #11094 reports some delays in the wazuh-db synchronization mechanism. Issue #11054 pretends to improve the efficiency of the groups and multigroups design, which has been proved to not scale well, etc.

Due to the aforementioned reasons we should test the performance of a Wazuh cluster at all different levels, including agent registration, agent connection, time it takes for an agent to be active, agent registration limits, agent connection limits, cluster load performance, wazuh-db load performance, etc. We know some limits are going to appear somewhere at some point, we just need to find where and when to approach it with a fix or improvement.

This issue aims to test the current performance of a Wazuh cluster from an end-to-end perspective (agent registration --> agent active) in environments that are big and as real as possible. 

To accomplish this goal we will need to complete the following tasks:
- [x] #11130
- [ ] Investigate and determine current testing environment limitations (Current cluster pipeline has a limit of registered agents, disk has a limited size for debug logs, limited # of workers, etc).
- [ ] Determine testing scenarios (#agents, #workers, #groups vs no-groups, #agent labels, etc).
- [ ] Determine testing use cases (N agents registration per minute, wazuh-db sync-req load simulation, etc).
- [ ] Perform tests and evaluate results.
