### ISSUE TITLE
Update AWS GuardDuty to make use of the discard_regex functionality

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#11138]
| Affected integration |
|---|
| AWS GuardDuty |

## Description

During the #10964 we found that the AWS GuardDuty integration does not correctly use the `discard_regex` functionality. This is because this integration overwrites the `iter_events` function with its own version, which lacks the logic required for `discard_regex` to work. It is necessary to determine why it overwrites the function instead of inheriting and finally udpate it to make use of `discard_regex`.

## Tasks
- [x] Fix the issue
- [x] Test in a manager
- [x] Test in an agent

**Comment by fdalmaup** [comment]
# Issue Update

I have been analyzing the code from `aws_s3.py`.  In addition to the lack of the discard_regex functionality, the main difference between the `iter_events` implementation in `AWSBucket` and the one in `AWSGuardDutyBucket` is that they use different implementations of the `reformat_msg` method. `AWSGuardDuty` defines a `reformat_msg` that yields an event message, therefore returning a generator object, and the `AWSBucket` implementation returns an event message. This is why `AWSGuardDutyBucket` overrides the `iter_events` function, to use the generator that `reformat_msg` creates and send several messages to the platform via `WazuhIntegration.send_msg`.

`AWSBucket.iter_events` 
https://github.com/wazuh/wazuh/blob/4739ec792a3d41fff621ba06e3b786e9b1ded79a/wodles/aws/aws_s3.py#L932-L967

`AWSGuardDutyBucket.iter_events` 
https://github.com/wazuh/wazuh/blob/4739ec792a3d41fff621ba06e3b786e9b1ded79a/wodles/aws/aws_s3.py#L2147-L2155

The code involving the `iter_events` method should be refactored to avoid code repetition and to mantain the `reformat_msg` functionality on `AWSGuardDutyBucket`.

**Comment by fdalmaup** [comment]
# Issue Update

The `iter_events` method from the `AWSBucket` class was refactored modifying the internal functions names `_check_recursive` and `_event_should_be_skipped` following the PEP8 convention for the considered internal components, and also generating a new method called `send_event` in the class. This method defines how the `refactor_msg` and the `send_msg` is used. The change corresponds to the difference between the `iter_events` from `AWSGuardDutyBucket` and `AWSBucket` and how they use the previously named methods as explained in previous updates of the issue.

Manual tests are being carried out to verify the correct operation of the modified and created methods.

**Comment by fdalmaup** [comment]
# ossec.conf tests

## Manager ossec.conf test
Add the following configuration to the ossec.conf of a manager:

<details>
    <summary>Configuration</summary>

  <wodle name="aws-s3">
    <disabled>no</disabled>
    <remove_from_bucket>no</remove_from_bucket>
    <interval>10m</interval>
    <run_on_start>yes</run_on_start>
    <skip_on_error>no</skip_on_error>

    <bucket type="guardduty">
        <aws_profile>dev</aws_profile>
        <name>wazuh-aws-wodle-guardduty</name>
        <discard_regex field="partition">aws</discard_regex>
        <only_logs_after>2021-JUN-18</only_logs_after>
    </bucket>
  </wodle>

</details>

<details>
    <summary>ossec.log</summary>

  2022/08/25 17:07:39 wazuh-modulesd:aws-s3[1713] wm_aws.c:59 at wm_aws_main(): INFO: Module AWS started
  2022/08/25 17:07:39 wazuh-modulesd:aws-s3[1713] wm_aws.c:81 at wm_aws_main(): INFO: Starting fetching of logs.
  2022/08/25 17:07:39 wazuh-modulesd:aws-s3[1713] wm_aws.c:133 at wm_aws_main(): INFO: Executing Bucket Analysis: (Bucket: wazuh-aws-wodle-guardduty, Type: guardduty, Profile: dev)
  2022/08/25 17:07:39 wazuh-modulesd:aws-s3[1713] wm_aws.c:328 at wm_aws_run_s3(): DEBUG: Create argument list
  2022/08/25 17:07:39 wazuh-modulesd:aws-s3[1713] wm_aws.c:443 at wm_aws_run_s3(): DEBUG: Launching S3 Command: wodles/aws/aws-s3 --bucket wazuh-aws-wodle-guardduty --aws_profile dev --only_logs_after 2021-JUN-18 --discard-field partition --discard-regex aws --type guardduty --debug 2
  2022/08/25 17:07:43 wazuh-modulesd:aws-s3[1713] wm_aws.c:483 at wm_aws_run_s3(): DEBUG: Bucket:  -  OUTPUT: DEBUG: +++ Debug mode on - Level: 2
  DEBUG: +++ The "aws" regex found a match in the "partition" field. The event will be skipped.
  DEBUG: +++ The "aws" regex found a match in the "partition" field. The event will be skipped.
  DEBUG: +++ The "aws" regex found a match in the "partition" field. The event will be skipped.
  DEBUG: +++ The "aws" regex found a match in the "partition" field. The event will be skipped.
  DEBUG: +++ The "aws" regex found a match in the "partition" field. The event will be skipped.
  2022/08/25 17:07:47 wazuh-modulesd:aws-s3[1713] wm_aws.c:173 at wm_aws_main(): INFO: Fetching logs finished.
  2022/08/25 17:07:47 wazuh-modulesd:aws-s3[1713] wm_aws.c:77 at wm_aws_main(): DEBUG: Sleeping until: 2022/08/25 17:17:39

</details>

### Conclusions

The integration is working fine, the events are not being sent to Analysisd due to the `discard_regex` option.


## Agent ossec.conf test
Deploy an agent and install the required dependencies described in the official Wazuh documentation, then run the module adding the following configuration to the ossec.conf:

<details>
    <summary>Configuration</summary>

  <wodle name="aws-s3">
    <disabled>no</disabled>
    <remove_from_bucket>no</remove_from_bucket>
    <interval>10m</interval>
    <run_on_start>yes</run_on_start>
    <skip_on_error>no</skip_on_error>

    <bucket type="guardduty">
        <aws_profile>dev</aws_profile>
        <name>wazuh-aws-wodle-guardduty</name>
        <discard_regex field="partition">aws</discard_regex>
        <only_logs_after>2021-JUN-18</only_logs_after>
    </bucket>
  </wodle>

</details>

<details>
    <summary>ossec.log</summary>

    2022/08/25 17:17:10 wazuh-modulesd:aws-s3[2994] wm_aws.c:59 at wm_aws_main(): INFO: Module AWS started
    2022/08/25 17:17:10 wazuh-modulesd:aws-s3[2994] wm_aws.c:81 at wm_aws_main(): INFO: Starting fetching of logs.
    2022/08/25 17:17:10 wazuh-modulesd:aws-s3[2994] wm_aws.c:133 at wm_aws_main(): INFO: Executing Bucket Analysis: (Bucket: wazuh-aws-wodle-guardduty, Type: guardduty, Profile: dev)
    2022/08/25 17:17:10 wazuh-modulesd:aws-s3[2994] wm_aws.c:328 at wm_aws_run_s3(): DEBUG: Create argument list
    2022/08/25 17:17:10 wazuh-modulesd:aws-s3[2994] wm_aws.c:443 at wm_aws_run_s3(): DEBUG: Launching S3 Command: wodles/aws/aws-s3 --bucket wazuh-aws-wodle-guardduty --aws_profile dev --only_logs_after 2021-JUN-18 --discard-field partition --discard-regex aws --type guardduty --debug 2
    2022/08/25 17:17:14 wazuh-modulesd:aws-s3[2994] wm_aws.c:483 at wm_aws_run_s3(): DEBUG: Bucket:  -  OUTPUT: DEBUG: +++ Debug mode on - Level: 2
    DEBUG: +++ The "aws" regex found a match in the "partition" field. The event will be skipped.
    DEBUG: +++ The "aws" regex found a match in the "partition" field. The event will be skipped.
    DEBUG: +++ The "aws" regex found a match in the "partition" field. The event will be skipped.
    DEBUG: +++ The "aws" regex found a match in the "partition" field. The event will be skipped.
    DEBUG: +++ The "aws" regex found a match in the "partition" field. The event will be skipped.
    2022/08/25 17:17:18 wazuh-modulesd:aws-s3[2994] wm_aws.c:173 at wm_aws_main(): INFO: Fetching logs finished.
    2022/08/25 17:17:18 wazuh-modulesd:aws-s3[2994] wm_aws.c:77 at wm_aws_main(): DEBUG: Sleeping until: 2022/08/25 17:27:10

</details>

### Conclusions
The integration is working fine with agents, no event is being processed in the manager.

**Comment by fdalmaup** [comment]
# AWS Wodle Unit Tests
## Test report
[aws_unit_tests.zip](https://github.com/wazuh/wazuh/files/9428024/aws_unit_tests.zip)

## Test results

---
| **Test name** | **Pass** | **XPass** | **Skip** | **XFail** | **Fail** | **Issues Ref.** | **Status** |
|--|--|--|--|--|--|--|--|
| aws/tests/test_aws.py | 38 | 0 | 0 | 0 | 0 |  | :green_circle: |
