### ISSUE TITLE
Add `-p/--prefix` parameter to the Azure Storage integration

### ISSUE THREAD

**Issue by noise-kngdm** [wazuh/wazuh#11147]
| Affected integration |
|---|
|  Azure Storage|

## Description
While working on #10966, we realized that the Azure module is lacking a feature that the rest of the external integrations have, the ability to filter folders inside a bucket depending on a prefix.  

I suggest adding a new parameter to the script, `-p/--prefix`. The new parameter indicates the folder where the logs that must be collected are located. If no prefix is set when executing the module, it should only fetch the log files inside the root directory and assume that the files in the rest of the folders have another prefix and shouldn't be parsed in this execution.  

Adding this parameter would let users have more versatile bucket configurations, instead of having to create a bucket for each service that should be monitored. 

## Tasks
- [x] Add `prefix` parameter to the module
- [x] Test in a manager
- [x] Update the documentation if necessary
- [x] Add entry to the changelog if necessary

**Comment by nico-stefani** [comment]
# Issue Update

## Container structure

In the container we have the next structure with 5 applicable files.

```
frameworktestcontainer
|___test_folder
    |___sample.inline
    |___sample.json
    |___sample.txt
|___test_prefix
    |___sample.inline
|___sample.inline
```

## Module Tests

### Test setting a prefix

Using the parameter `--prefix test_prefix` the module only must search inside `test_prefix` directory.


<details>
    <summary>Command Used</summary>

    /var/ossec/wodles/azure/azure-logs --storage --storage_time_offset 30d --container frameworktestcontainer --prefix test_prefix --storage_auth_path /var/ossec/wodles/azure/credentials -d2

</details>


<details>
    <summary>Command Output</summary>

    2022/08/26 05:22:46 azure: INFO: Checking database integrity
    2022/08/26 05:22:46 azure: INFO: Database integrity check finished
    2022/08/26 05:22:46 azure: INFO: Azure Storage starting.
    2022/08/26 05:22:46 azure: INFO: Storage: Authenticating.
    2022/08/26 05:22:46 azure: DEBUG: String_to_sign=GET











    x-ms-client-request-id:b3cf04f7-2563-11ed-b946-cba20158041f
    x-ms-date:Fri, 26 Aug 2022 17:22:46 GMT
    x-ms-version:2019-02-02
    /frameworkteststorage/frameworktestcontainer
    restype:container
    2022/08/26 05:22:46 azure: INFO: Client-Request-ID=b3cf04f7-2563-11ed-b946-cba20158041f Outgoing request: Method=GET, Path=/frameworktestcontainer, Query={'snapshot': None, 'timeout': None, 'restype': 'container'}, Headers={'x-ms-version': '2019-02-02', 'User-Agent': 'Azure-Storage/2.1.0-2.1.0 (Python CPython 3.9.9; Linux 5.19.0-76051900-generic)', 'x-ms-client-request-id': 'b3cf04f7-2563-11ed-b946-cba20158041f', 'x-ms-date': 'Fri, 26 Aug 2022 17:22:46 GMT', 'Authorization': 'REDACTED'}.
    2022/08/26 05:22:47 azure: INFO: Client-Request-ID=b3cf04f7-2563-11ed-b946-cba20158041f Receiving Response: Server-Timestamp=Fri, 26 Aug 2022 17:22:47 GMT, Server-Request-ID=bf270868-d01e-006f-6b70-b9a204000000, HTTP Status Code=200, Message=OK, Headers={'content-length': '0', 'last-modified': 'Wed, 20 Oct 2021 07:47:27 GMT', 'etag': '"0x8D9939DDD0A61EA"', 'server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': 'bf270868-d01e-006f-6b70-b9a204000000', 'x-ms-client-request-id': 'b3cf04f7-2563-11ed-b946-cba20158041f', 'x-ms-version': '2019-02-02', 'x-ms-lease-status': 'unlocked', 'x-ms-lease-state': 'available', 'x-ms-has-immutability-policy': 'false', 'x-ms-has-legal-hold': 'false', 'x-ms-default-encryption-scope': '$account-encryption-key', 'x-ms-deny-encryption-scope-override': 'false', 'date': 'Fri, 26 Aug 2022 17:22:47 GMT'}.
    2022/08/26 05:22:47 azure: INFO: Storage: Authenticated.
    2022/08/26 05:22:47 azure: INFO: 82e049b81fa6eb88ebf85f1677785f2b was not found in the database for storage. Adding it.
    2022/08/26 05:22:47 azure: DEBUG: Attempting to insert row object into storage with md5='82e049b81fa6eb88ebf85f1677785f2b', min_date='2022-07-27T17:22:47.862080Z', max_date='2022-07-27T17:22:47.862080Z'
    2022/08/26 05:22:47 azure: INFO: Storage: Getting blobs.
    2022/08/26 05:22:47 azure: DEBUG: String_to_sign=GET











    x-ms-client-request-id:b482f3b6-2563-11ed-baf7-cba20158041f
    x-ms-date:Fri, 26 Aug 2022 17:22:47 GMT
    x-ms-version:2019-02-02
    /frameworkteststorage/frameworktestcontainer
    comp:list
    prefix:test_prefix
    restype:container
    2022/08/26 05:22:47 azure: INFO: Client-Request-ID=b482f3b6-2563-11ed-baf7-cba20158041f Outgoing request: Method=GET, Path=/frameworktestcontainer, Query={'restype': 'container', 'comp': 'list', 'prefix': 'test_prefix', 'delimiter': None, 'marker': None, 'maxresults': None, 'include': None, 'timeout': None}, Headers={'x-ms-version': '2019-02-02', 'User-Agent': 'Azure-Storage/2.1.0-2.1.0 (Python CPython 3.9.9; Linux 5.19.0-76051900-generic)', 'x-ms-client-request-id': 'b482f3b6-2563-11ed-baf7-cba20158041f', 'x-ms-date': 'Fri, 26 Aug 2022 17:22:47 GMT', 'Authorization': 'REDACTED'}.
    2022/08/26 05:22:48 azure: INFO: Client-Request-ID=b482f3b6-2563-11ed-baf7-cba20158041f Receiving Response: Server-Timestamp=Fri, 26 Aug 2022 17:22:47 GMT, Server-Request-ID=bf2708ff-d01e-006f-7570-b9a204000000, HTTP Status Code=200, Message=OK, Headers={'transfer-encoding': 'chunked', 'content-type': 'application/xml', 'server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': 'bf2708ff-d01e-006f-7570-b9a204000000', 'x-ms-client-request-id': 'b482f3b6-2563-11ed-baf7-cba20158041f', 'x-ms-version': '2019-02-02', 'date': 'Fri, 26 Aug 2022 17:22:47 GMT'}.
    2022/08/26 05:22:48 azure: INFO: Storage: The search starts from the date: 2022-07-27 17:22:47.882192+00:00 for blobs in container: 'frameworktestcontainer' and prefix: 'test_prefix'
    2022/08/26 05:22:48 azure: DEBUG: String_to_sign=GET











    x-ms-client-request-id:b4afd6aa-2563-11ed-b36c-cba20158041f
    x-ms-date:Fri, 26 Aug 2022 17:22:48 GMT
    x-ms-range:bytes=0-33554431
    x-ms-version:2019-02-02
    /frameworkteststorage/frameworktestcontainer/test_prefix/sample.inline
    2022/08/26 05:22:48 azure: INFO: Client-Request-ID=b4afd6aa-2563-11ed-b36c-cba20158041f Outgoing request: Method=GET, Path=/frameworktestcontainer/test_prefix/sample.inline, Query={'snapshot': None, 'timeout': None}, Headers={'x-ms-lease-id': None, 'If-Modified-Since': None, 'If-Unmodified-Since': None, 'If-Match': None, 'If-None-Match': None, 'x-ms-range': 'bytes=0-33554431', 'x-ms-version': '2019-02-02', 'User-Agent': 'Azure-Storage/2.1.0-2.1.0 (Python CPython 3.9.9; Linux 5.19.0-76051900-generic)', 'x-ms-client-request-id': 'b4afd6aa-2563-11ed-b36c-cba20158041f', 'x-ms-date': 'Fri, 26 Aug 2022 17:22:48 GMT', 'Authorization': 'REDACTED'}.
    2022/08/26 05:22:48 azure: INFO: Client-Request-ID=b4afd6aa-2563-11ed-b36c-cba20158041f Receiving Response: Server-Timestamp=Fri, 26 Aug 2022 17:22:47 GMT, Server-Request-ID=bf2709a2-d01e-006f-0770-b9a204000000, HTTP Status Code=206, Message=Partial Content, Headers={'content-length': '233', 'content-type': 'application/octet-stream', 'content-range': 'bytes 0-232/233', 'last-modified': 'Thu, 25 Aug 2022 20:29:09 GMT', 'accept-ranges': 'bytes', 'etag': '"0x8DA86D876F88981"', 'server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': 'bf2709a2-d01e-006f-0770-b9a204000000', 'x-ms-client-request-id': 'b4afd6aa-2563-11ed-b36c-cba20158041f', 'x-ms-version': '2019-02-02', 'x-ms-creation-time': 'Thu, 25 Aug 2022 20:29:09 GMT', 'x-ms-blob-content-md5': 'f/8pRQEB20X6IAipRUn4UA==', 'x-ms-lease-status': 'unlocked', 'x-ms-lease-state': 'available', 'x-ms-blob-type': 'BlockBlob', 'x-ms-server-encrypted': 'true', 'date': 'Fri, 26 Aug 2022 17:22:47 GMT'}.
    2022/08/26 05:22:48 azure: INFO: Storage: Sending event by socket.
    2022/08/26 05:22:48 azure: INFO: Storage: Sending event by socket.
    2022/08/26 05:22:48 azure: INFO: Storage: Sending event by socket.
    2022/08/26 05:22:48 azure: DEBUG: Attempting to update a storage row object. MD5: '82e049b81fa6eb88ebf85f1677785f2b', min_date: '2022-07-27T17:22:47.862080Z', max_date: '2022-08-25T20:29:09.000000Z'
    2022/08/26 05:22:48 azure: INFO: Storage: End


</details>

Keep the `azure.db` file and run the same command again to ensure no duplicate logs have been processed.

<details>
    <summary>Command Output</summary>

    2022/08/26 06:54:04 azure: INFO: Checking database integrity
    2022/08/26 06:54:04 azure: INFO: Database integrity check finished
    2022/08/26 06:54:04 azure: INFO: Azure Storage starting.
    2022/08/26 06:54:04 azure: INFO: Storage: Authenticating.
    2022/08/26 06:54:04 azure: DEBUG: String_to_sign=GET











    x-ms-client-request-id:750dd12f-2570-11ed-9e1d-1df402552dc8
    x-ms-date:Fri, 26 Aug 2022 18:54:04 GMT
    x-ms-version:2019-02-02
    /frameworkteststorage/frameworktestcontainer
    restype:container
    2022/08/26 06:54:04 azure: INFO: Client-Request-ID=750dd12f-2570-11ed-9e1d-1df402552dc8 Outgoing request: Method=GET, Path=/frameworktestcontainer, Query={'snapshot': None, 'timeout': None, 'restype': 'container'}, Headers={'x-ms-version': '2019-02-02', 'User-Agent': 'Azure-Storage/2.1.0-2.1.0 (Python CPython 3.9.9; Linux 5.19.0-76051900-generic)', 'x-ms-client-request-id': '750dd12f-2570-11ed-9e1d-1df402552dc8', 'x-ms-date': 'Fri, 26 Aug 2022 18:54:04 GMT', 'Authorization': 'REDACTED'}.
    2022/08/26 06:54:06 azure: INFO: Client-Request-ID=750dd12f-2570-11ed-9e1d-1df402552dc8 Receiving Response: Server-Timestamp=Fri, 26 Aug 2022 18:54:05 GMT, Server-Request-ID=a11fc11b-401e-00a6-117d-b91fe9000000, HTTP Status Code=200, Message=OK, Headers={'content-length': '0', 'last-modified': 'Wed, 20 Oct 2021 07:47:27 GMT', 'etag': '"0x8D9939DDD0A61EA"', 'server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': 'a11fc11b-401e-00a6-117d-b91fe9000000', 'x-ms-client-request-id': '750dd12f-2570-11ed-9e1d-1df402552dc8', 'x-ms-version': '2019-02-02', 'x-ms-lease-status': 'unlocked', 'x-ms-lease-state': 'available', 'x-ms-has-immutability-policy': 'false', 'x-ms-has-legal-hold': 'false', 'x-ms-default-encryption-scope': '$account-encryption-key', 'x-ms-deny-encryption-scope-override': 'false', 'date': 'Fri, 26 Aug 2022 18:54:05 GMT'}.
    2022/08/26 06:54:06 azure: INFO: Storage: Authenticated.
    2022/08/26 06:54:06 azure: INFO: Storage: Getting blobs.
    2022/08/26 06:54:06 azure: DEBUG: String_to_sign=GET











    x-ms-client-request-id:76028948-2570-11ed-b2e5-1df402552dc8
    x-ms-date:Fri, 26 Aug 2022 18:54:06 GMT
    x-ms-version:2019-02-02
    /frameworkteststorage/frameworktestcontainer
    comp:list
    prefix:test_prefix
    restype:container
    2022/08/26 06:54:06 azure: INFO: Client-Request-ID=76028948-2570-11ed-b2e5-1df402552dc8 Outgoing request: Method=GET, Path=/frameworktestcontainer, Query={'restype': 'container', 'comp': 'list', 'prefix': 'test_prefix', 'delimiter': None, 'marker': None, 'maxresults': None, 'include': None, 'timeout': None}, Headers={'x-ms-version': '2019-02-02', 'User-Agent': 'Azure-Storage/2.1.0-2.1.0 (Python CPython 3.9.9; Linux 5.19.0-76051900-generic)', 'x-ms-client-request-id': '76028948-2570-11ed-b2e5-1df402552dc8', 'x-ms-date': 'Fri, 26 Aug 2022 18:54:06 GMT', 'Authorization': 'REDACTED'}.
    2022/08/26 06:54:06 azure: INFO: Client-Request-ID=76028948-2570-11ed-b2e5-1df402552dc8 Receiving Response: Server-Timestamp=Fri, 26 Aug 2022 18:54:06 GMT, Server-Request-ID=a11fc1a1-401e-00a6-0b7d-b91fe9000000, HTTP Status Code=200, Message=OK, Headers={'transfer-encoding': 'chunked', 'content-type': 'application/xml', 'server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': 'a11fc1a1-401e-00a6-0b7d-b91fe9000000', 'x-ms-client-request-id': '76028948-2570-11ed-b2e5-1df402552dc8', 'x-ms-version': '2019-02-02', 'date': 'Fri, 26 Aug 2022 18:54:06 GMT'}.
    2022/08/26 06:54:06 azure: INFO: Storage: The search starts from the date: 2022-07-27 18:54:06.479390+00:00 for blobs in container: 'frameworktestcontainer'
    2022/08/26 06:54:06 azure: INFO: Storage: End


</details>

#### Conclusions

The module worked as expected, only takes `test_prefix/sample.inline`.

### Test setting without a prefix

Without using the `--prefix` parameter the module only must search inside the root container and skip all files with any prefix.

<details>
    <summary>Command Used</summary>

    /var/ossec/wodles/azure/azure-logs --storage --storage_time_offset 30d --container frameworktestcontainer --storage_auth_path /var/ossec/wodles/azure/credentials -d2

</details>

<details>
    <summary>Command Output</summary>

    2022/08/26 05:31:10 azure: INFO: Checking database integrity
    2022/08/26 05:31:10 azure: INFO: Database integrity check finished
    2022/08/26 05:31:10 azure: INFO: Azure Storage starting.
    2022/08/26 05:31:10 azure: INFO: Storage: Authenticating.
    2022/08/26 05:31:10 azure: DEBUG: String_to_sign=GET











    x-ms-client-request-id:e0459a1f-2564-11ed-9d35-01832441b926
    x-ms-date:Fri, 26 Aug 2022 17:31:10 GMT
    x-ms-version:2019-02-02
    /frameworkteststorage/frameworktestcontainer
    restype:container
    2022/08/26 05:31:10 azure: INFO: Client-Request-ID=e0459a1f-2564-11ed-9d35-01832441b926 Outgoing request: Method=GET, Path=/frameworktestcontainer, Query={'snapshot': None, 'timeout': None, 'restype': 'container'}, Headers={'x-ms-version': '2019-02-02', 'User-Agent': 'Azure-Storage/2.1.0-2.1.0 (Python CPython 3.9.9; Linux 5.19.0-76051900-generic)', 'x-ms-client-request-id': 'e0459a1f-2564-11ed-9d35-01832441b926', 'x-ms-date': 'Fri, 26 Aug 2022 17:31:10 GMT', 'Authorization': 'REDACTED'}.
    2022/08/26 05:31:11 azure: INFO: Client-Request-ID=e0459a1f-2564-11ed-9d35-01832441b926 Receiving Response: Server-Timestamp=Fri, 26 Aug 2022 17:31:11 GMT, Server-Request-ID=346e017a-001e-001e-3971-b9442f000000, HTTP Status Code=200, Message=OK, Headers={'content-length': '0', 'last-modified': 'Wed, 20 Oct 2021 07:47:27 GMT', 'etag': '"0x8D9939DDD0A61EA"', 'server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': '346e017a-001e-001e-3971-b9442f000000', 'x-ms-client-request-id': 'e0459a1f-2564-11ed-9d35-01832441b926', 'x-ms-version': '2019-02-02', 'x-ms-lease-status': 'unlocked', 'x-ms-lease-state': 'available', 'x-ms-has-immutability-policy': 'false', 'x-ms-has-legal-hold': 'false', 'x-ms-default-encryption-scope': '$account-encryption-key', 'x-ms-deny-encryption-scope-override': 'false', 'date': 'Fri, 26 Aug 2022 17:31:11 GMT'}.
    2022/08/26 05:31:11 azure: INFO: Storage: Authenticated.
    2022/08/26 05:31:11 azure: INFO: Storage: Getting blobs.
    2022/08/26 05:31:11 azure: DEBUG: String_to_sign=GET











    x-ms-client-request-id:e0c31d1a-2564-11ed-8297-01832441b926
    x-ms-date:Fri, 26 Aug 2022 17:31:11 GMT
    x-ms-version:2019-02-02
    /frameworkteststorage/frameworktestcontainer
    comp:list
    restype:container
    2022/08/26 05:31:11 azure: INFO: Client-Request-ID=e0c31d1a-2564-11ed-8297-01832441b926 Outgoing request: Method=GET, Path=/frameworktestcontainer, Query={'restype': 'container', 'comp': 'list', 'prefix': None, 'delimiter': None, 'marker': None, 'maxresults': None, 'include': None, 'timeout': None}, Headers={'x-ms-version': '2019-02-02', 'User-Agent': 'Azure-Storage/2.1.0-2.1.0 (Python CPython 3.9.9; Linux 5.19.0-76051900-generic)', 'x-ms-client-request-id': 'e0c31d1a-2564-11ed-8297-01832441b926', 'x-ms-date': 'Fri, 26 Aug 2022 17:31:11 GMT', 'Authorization': 'REDACTED'}.
    2022/08/26 05:31:12 azure: INFO: Client-Request-ID=e0c31d1a-2564-11ed-8297-01832441b926 Receiving Response: Server-Timestamp=Fri, 26 Aug 2022 17:31:11 GMT, Server-Request-ID=346e0241-001e-001e-6871-b9442f000000, HTTP Status Code=200, Message=OK, Headers={'transfer-encoding': 'chunked', 'content-type': 'application/xml', 'server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': '346e0241-001e-001e-6871-b9442f000000', 'x-ms-client-request-id': 'e0c31d1a-2564-11ed-8297-01832441b926', 'x-ms-version': '2019-02-02', 'date': 'Fri, 26 Aug 2022 17:31:11 GMT'}.
    2022/08/26 05:31:12 azure: INFO: Storage: The search starts from the date: 2022-07-27 17:31:11.619211+00:00 for blobs in container: 'frameworktestcontainer'
    2022/08/26 05:31:12 azure: DEBUG: String_to_sign=GET











    x-ms-client-request-id:e1018247-2564-11ed-828a-01832441b926
    x-ms-date:Fri, 26 Aug 2022 17:31:12 GMT
    x-ms-range:bytes=0-33554431
    x-ms-version:2019-02-02
    /frameworkteststorage/frameworktestcontainer/sample.inline
    2022/08/26 05:31:12 azure: INFO: Client-Request-ID=e1018247-2564-11ed-828a-01832441b926 Outgoing request: Method=GET, Path=/frameworktestcontainer/sample.inline, Query={'snapshot': None, 'timeout': None}, Headers={'x-ms-lease-id': None, 'If-Modified-Since': None, 'If-Unmodified-Since': None, 'If-Match': None, 'If-None-Match': None, 'x-ms-range': 'bytes=0-33554431', 'x-ms-version': '2019-02-02', 'User-Agent': 'Azure-Storage/2.1.0-2.1.0 (Python CPython 3.9.9; Linux 5.19.0-76051900-generic)', 'x-ms-client-request-id': 'e1018247-2564-11ed-828a-01832441b926', 'x-ms-date': 'Fri, 26 Aug 2022 17:31:12 GMT', 'Authorization': 'REDACTED'}.
    2022/08/26 05:31:12 azure: INFO: Client-Request-ID=e1018247-2564-11ed-828a-01832441b926 Receiving Response: Server-Timestamp=Fri, 26 Aug 2022 17:31:12 GMT, Server-Request-ID=346e03b0-001e-001e-2971-b9442f000000, HTTP Status Code=206, Message=Partial Content, Headers={'content-length': '311', 'content-type': 'application/octet-stream', 'content-range': 'bytes 0-310/311', 'last-modified': 'Thu, 25 Aug 2022 21:11:56 GMT', 'accept-ranges': 'bytes', 'etag': '"0x8DA86DE711AEAD2"', 'server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': '346e03b0-001e-001e-2971-b9442f000000', 'x-ms-client-request-id': 'e1018247-2564-11ed-828a-01832441b926', 'x-ms-version': '2019-02-02', 'x-ms-creation-time': 'Wed, 20 Oct 2021 11:29:37 GMT', 'x-ms-blob-content-md5': 'I1jtjBGU7RWxmnoNzoHF9w==', 'x-ms-lease-status': 'unlocked', 'x-ms-lease-state': 'available', 'x-ms-blob-type': 'BlockBlob', 'x-ms-server-encrypted': 'true', 'date': 'Fri, 26 Aug 2022 17:31:12 GMT'}.
    2022/08/26 05:31:12 azure: INFO: Storage: Sending event by socket.
    2022/08/26 05:31:12 azure: INFO: Storage: Sending event by socket.
    2022/08/26 05:31:12 azure: INFO: Storage: Sending event by socket.
    2022/08/26 05:31:12 azure: INFO: Storage: Sending event by socket.
    2022/08/26 05:31:12 azure: DEBUG: Attempting to update a storage row object. MD5: '82e049b81fa6eb88ebf85f1677785f2b', min_date: '2022-07-27T17:22:47.862080Z', max_date: '2022-08-25T21:11:56.000000Z'
    2022/08/26 05:31:12 azure: DEBUG: Skipping test_folder/sample.inline
    2022/08/26 05:31:12 azure: DEBUG: Skipping test_folder/sample.json
    2022/08/26 05:31:12 azure: DEBUG: Skipping test_folder/sample.txt
    2022/08/26 05:31:12 azure: DEBUG: Skipping test_prefix/sample.inline
    2022/08/26 05:31:12 azure: INFO: Storage: End

</details>

Keep the `azure.db` file and run the same command again to ensure no duplicate logs have been processed.

<details>
    <summary>Command Output</summary>

    2022/08/26 06:55:19 azure: INFO: Checking database integrity
    2022/08/26 06:55:19 azure: INFO: Database integrity check finished
    2022/08/26 06:55:19 azure: INFO: Azure Storage starting.
    2022/08/26 06:55:19 azure: INFO: Storage: Authenticating.
    2022/08/26 06:55:19 azure: DEBUG: String_to_sign=GET











    x-ms-client-request-id:a19d2083-2570-11ed-8ddf-c35bff535f86
    x-ms-date:Fri, 26 Aug 2022 18:55:19 GMT
    x-ms-version:2019-02-02
    /frameworkteststorage/frameworktestcontainer
    restype:container
    2022/08/26 06:55:19 azure: INFO: Client-Request-ID=a19d2083-2570-11ed-8ddf-c35bff535f86 Outgoing request: Method=GET, Path=/frameworktestcontainer, Query={'snapshot': None, 'timeout': None, 'restype': 'container'}, Headers={'x-ms-version': '2019-02-02', 'User-Agent': 'Azure-Storage/2.1.0-2.1.0 (Python CPython 3.9.9; Linux 5.19.0-76051900-generic)', 'x-ms-client-request-id': 'a19d2083-2570-11ed-8ddf-c35bff535f86', 'x-ms-date': 'Fri, 26 Aug 2022 18:55:19 GMT', 'Authorization': 'REDACTED'}.
    2022/08/26 06:55:20 azure: INFO: Client-Request-ID=a19d2083-2570-11ed-8ddf-c35bff535f86 Receiving Response: Server-Timestamp=Fri, 26 Aug 2022 18:55:20 GMT, Server-Request-ID=96a7055e-e01e-005b-687d-b991cc000000, HTTP Status Code=200, Message=OK, Headers={'content-length': '0', 'last-modified': 'Wed, 20 Oct 2021 07:47:27 GMT', 'etag': '"0x8D9939DDD0A61EA"', 'server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': '96a7055e-e01e-005b-687d-b991cc000000', 'x-ms-client-request-id': 'a19d2083-2570-11ed-8ddf-c35bff535f86', 'x-ms-version': '2019-02-02', 'x-ms-lease-status': 'unlocked', 'x-ms-lease-state': 'available', 'x-ms-has-immutability-policy': 'false', 'x-ms-has-legal-hold': 'false', 'x-ms-default-encryption-scope': '$account-encryption-key', 'x-ms-deny-encryption-scope-override': 'false', 'date': 'Fri, 26 Aug 2022 18:55:20 GMT'}.
    2022/08/26 06:55:20 azure: INFO: Storage: Authenticated.
    2022/08/26 06:55:20 azure: INFO: Storage: Getting blobs.
    2022/08/26 06:55:20 azure: DEBUG: String_to_sign=GET











    x-ms-client-request-id:a25244fb-2570-11ed-af2f-c35bff535f86
    x-ms-date:Fri, 26 Aug 2022 18:55:20 GMT
    x-ms-version:2019-02-02
    /frameworkteststorage/frameworktestcontainer
    comp:list
    restype:container
    2022/08/26 06:55:20 azure: INFO: Client-Request-ID=a25244fb-2570-11ed-af2f-c35bff535f86 Outgoing request: Method=GET, Path=/frameworktestcontainer, Query={'restype': 'container', 'comp': 'list', 'prefix': None, 'delimiter': None, 'marker': None, 'maxresults': None, 'include': None, 'timeout': None}, Headers={'x-ms-version': '2019-02-02', 'User-Agent': 'Azure-Storage/2.1.0-2.1.0 (Python CPython 3.9.9; Linux 5.19.0-76051900-generic)', 'x-ms-client-request-id': 'a25244fb-2570-11ed-af2f-c35bff535f86', 'x-ms-date': 'Fri, 26 Aug 2022 18:55:20 GMT', 'Authorization': 'REDACTED'}.
    2022/08/26 06:55:21 azure: INFO: Client-Request-ID=a25244fb-2570-11ed-af2f-c35bff535f86 Receiving Response: Server-Timestamp=Fri, 26 Aug 2022 18:55:20 GMT, Server-Request-ID=96a705fb-e01e-005b-687d-b991cc000000, HTTP Status Code=200, Message=OK, Headers={'transfer-encoding': 'chunked', 'content-type': 'application/xml', 'server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': '96a705fb-e01e-005b-687d-b991cc000000', 'x-ms-client-request-id': 'a25244fb-2570-11ed-af2f-c35bff535f86', 'x-ms-version': '2019-02-02', 'date': 'Fri, 26 Aug 2022 18:55:20 GMT'}.
    2022/08/26 06:55:21 azure: INFO: Storage: The search starts from the date: 2022-07-27 18:55:20.821697+00:00 for blobs in container: 'frameworktestcontainer'
    2022/08/26 06:55:21 azure: DEBUG: Skipping test_folder/sample.inline
    2022/08/26 06:55:21 azure: DEBUG: Skipping test_folder/sample.json
    2022/08/26 06:55:21 azure: DEBUG: Skipping test_folder/sample.txt
    2022/08/26 06:55:21 azure: DEBUG: Skipping test_prefix/sample.inline
    2022/08/26 06:55:21 azure: INFO: Storage: End


</details>

#### Conclusions

The module worked as expected, only takes `sample.inline` in root container and skips files with prefix `test_prefix` and `test_folder`.

**Comment by nico-stefani** [comment]
# Issue Update

### Testing ossec.conf parser
#### Run the integration from the `ossec.conf` configuring multiple `container` blocks only one with `prefix`

Remove the `/var/ossec/wodles/azure/azure.db` file and run the module using the following configuration. Every blob available should be processed.

<details>
    <summary>Configuration used</summary>

    <wodle name="azure-logs">
    <disabled>no</disabled>
    <interval>10m</interval>
    <run_on_start>yes</run_on_start>

    <storage>
        <auth_path>/var/ossec/wodles/azure/credentials-storage</auth_path>
        <tag>azure-activity</tag>

        <container name="frameworktestcontainer">
            <content_type>json_inline</content_type>
            <time_offset>30d</time_offset>
        <prefix>test_prefix</prefix>
        </container>

        <container name="frameworktestcontainer">
            <blobs>.txt</blobs>
            <time_offset>150d</time_offset>
        </container>

        <container name="frameworktestcontainer">
            <blobs>.txt</blobs>
            <content_type>json_inline</content_type>
        </container>

        <container name="frameworktestcontainer">
            <blobs>.json</blobs>
            <content_type>json_inline</content_type>
            <time_offset>150d</time_offset>
        </container>

    </storage>
    </wodle>

</details>

<details>
    <summary>Command output</summary>

    2022/09/05 12:12:27 wazuh-modulesd:azure-logs[53639] wm_azure.c:439 at wm_azure_cleanup(): INFO: Module finished.
    2022/09/05 12:12:40 wazuh-modulesd:azure-logs[54821] wm_azure.c:53 at wm_azure_main(): INFO: Module started.
    2022/09/05 12:12:40 wazuh-modulesd:azure-logs[54821] wm_azure.c:73 at wm_azure_main(): INFO: Starting fetching of logs.
    2022/09/05 12:12:40 wazuh-modulesd:azure-logs[54821] wm_azure.c:91 at wm_azure_main(): INFO: Starting Storage log collection for 'azure-activity'.
    2022/09/05 12:12:40 wazuh-modulesd:azure-logs[54821] wm_azure.c:296 at wm_azure_storage(): DEBUG: Creating argument list.
    2022/09/05 12:12:40 wazuh-modulesd:azure-logs[54821] wm_azure.c:363 at wm_azure_storage(): DEBUG: Launching command: wodles/azure/azure-logs --storage --storage_auth_path /var/ossec/wodles/azure/credentials-storage --container "frameworktestcontainer" --blobs "*" --storage_tag azure-activity --json_inline --storage_time_offset 30d --prefix test_prefix --debug 2
    2022/09/05 12:12:43 wazuh-modulesd:azure-logs[54821] wm_azure.c:380 at wm_azure_storage(): INFO: Finished Storage log collection for container 'frameworktestcontainer'.
    2022/09/05 12:12:43 wazuh-modulesd:azure-logs[54821] wm_azure.c:296 at wm_azure_storage(): DEBUG: Creating argument list.
    2022/09/05 12:12:43 wazuh-modulesd:azure-logs[54821] wm_azure.c:363 at wm_azure_storage(): DEBUG: Launching command: wodles/azure/azure-logs --storage --storage_auth_path /var/ossec/wodles/azure/credentials-storage --container "frameworktestcontainer" --blobs ".txt" --storage_tag azure-activity --storage_time_offset 150d --debug 2
    2022/09/05 12:12:45 wazuh-modulesd:azure-logs[54821] wm_azure.c:380 at wm_azure_storage(): INFO: Finished Storage log collection for container 'frameworktestcontainer'.
    2022/09/05 12:12:45 wazuh-modulesd:azure-logs[54821] wm_azure.c:296 at wm_azure_storage(): DEBUG: Creating argument list.
    2022/09/05 12:12:45 wazuh-modulesd:azure-logs[54821] wm_azure.c:363 at wm_azure_storage(): DEBUG: Launching command: wodles/azure/azure-logs --storage --storage_auth_path /var/ossec/wodles/azure/credentials-storage --container "frameworktestcontainer" --blobs ".txt" --storage_tag azure-activity --json_inline --debug 2
    2022/09/05 12:12:47 wazuh-modulesd:azure-logs[54821] wm_azure.c:380 at wm_azure_storage(): INFO: Finished Storage log collection for container 'frameworktestcontainer'.
    2022/09/05 12:12:47 wazuh-modulesd:azure-logs[54821] wm_azure.c:296 at wm_azure_storage(): DEBUG: Creating argument list.
    2022/09/05 12:12:47 wazuh-modulesd:azure-logs[54821] wm_azure.c:363 at wm_azure_storage(): DEBUG: Launching command: wodles/azure/azure-logs --storage --storage_auth_path /var/ossec/wodles/azure/credentials-storage --container "frameworktestcontainer" --blobs ".json" --storage_tag azure-activity --json_inline --storage_time_offset 150d --debug 2
    2022/09/05 12:12:50 wazuh-modulesd:azure-logs[54821] wm_azure.c:380 at wm_azure_storage(): INFO: Finished Storage log collection for container 'frameworktestcontainer'.


</details>

##### Conclusions
The module worked as expected.

**Comment by nico-stefani** [comment]
# Issue Update

We decide rename the option to `path` in order to keep consistency with the other modules. 

```xml
<wodle name="azure-logs">
<disabled>no</disabled>
<interval>10m</interval>
<run_on_start>yes</run_on_start>

<storage>
    <auth_path>/var/ossec/wodles/azure/credentials-storage</auth_path>
    <tag>azure-activity</tag>

    <container name="frameworktestcontainer">
        <content_type>json_inline</content_type>
        <time_offset>30d</time_offset>
        <path>test_prefix</path>
    </container>
</storage>
</wodle>
```
