### ISSUE TITLE
Google Cloud Storage doesn't properly filter folders by prefix

### ISSUE THREAD

**Issue by noise-kngdm** [wazuh/wazuh#11149]
| Affected integration |
|---|
|  Google Cloud Storage|

## Description
While working on #10965 we realized that the `-P/--prefix` parameter isn't working as expected. When the module is executed without specifying any prefix, it will collect and process every log in the bucket, even if it's inside a folder -which marks that it has a prefix- and shouldn't be collected. This behavior would end up generating duplicate alerts, and it should be fixed as soon as possible.

The following example shows that the module has processed the `test_prefix/test_1.txt` when it shouldn't have.

```
root@a4d858f57579:/var/ossec/wodles/gcloud# /var/ossec/wodles/gcloud/gcloud -T access_logs -b framework-test-bucket -c credentials.json -l1 
gcloud_wodle - INFO - The creation time of test_22.txt is older than 2021-12-01 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - The creation time of test_3.txt is older than 2021-12-01 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - The creation time of test_4.txt is older than 2021-12-01 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - The creation time of test_5.txt is older than 2021-12-01 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - Processing test_6.txt
gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 6", "source": "gcp_bucket"}}'"
gcloud_wodle - INFO - Processing test_7.txt
gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 7", "source": "gcp_bucket"}}'"
gcloud_wodle - INFO - Processing test_8.txt
gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 8", "source": "gcp_bucket"}}'"
gcloud_wodle - INFO - Processing test_9.txt
gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 9", "source": "gcp_bucket"}}'"
gcloud_wodle - INFO - Processing test_prefix/test_1.txt
gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 1", "source": "gcp_bucket"}}'"
gcloud_wodle - INFO - Updating previously processed files.
gcloud_wodle - INFO - Received 5 messages
```

## Tasks
- [x] Fix the prefix parameter
- [x] Test in a manager
- [x] Test in an agent
- [x] Update the documentation if necessary
- [x] Add entry to the changelog if necessary

**Comment by noise-kngdm** [comment]
## Issue update
To fix this problem we only had to add a delimiter to the request to GCP to point that we just need the files under that folder, and not the files on its subfolders. The delimiter added can be seen in following code snippet:

https://github.com/wazuh/wazuh/blob/919f3f9ef5861f99a330dc5bed4f555cfacea535/wodles/gcloud/buckets/bucket.py#L214

We also added to the constructor the logic necessary to add a `/` at the end of the prefix if it's not present, since it's necessary to make a successful request to GCP.
https://github.com/wazuh/wazuh/blob/919f3f9ef5861f99a330dc5bed4f555cfacea535/wodles/gcloud/buckets/bucket.py#L56
