### ISSUE TITLE
Add python-json-logger dependency to our embedded python

### ISSUE THREAD

**Issue by Kondent** [wazuh/wazuh#11153]
## Description
During the development of JSON logs handling for the API, I made use of a new and necessary dependency.
And as we discussed with the team, this new dependency needs to be added to our embedded python.

* Related issue in which this dependency is needed: [#10867](https://github.com/wazuh/wazuh/issues/10867).
* Dependency @ pypi: [python-json-logger](https://pypi.org/project/python-json-logger/).
* Dependency @ github: [madzak/python-json-logger](https://github.com/madzak/python-json-logger).

## Tasks
- [x] Update sources package
- [x] Update compiled `amd64` package
- [x] Update compile `aarch64` package

**Comment by noise-kngdm** [comment]
## Issue update
Since the python-json-logger library is written in Python in its entirety, it is possible to directly use the wheels provided in its [PyPI site](https://pypi.org/project/python-json-logger/#files) with the different architectures and installation methods supported.

We have currently updated the package used to install the embedded Python interpreter from sources. To do that, we added the wheel to the `cpython/Dependencies` folder and then used the [pip2pi](https://github.com/wolever/pip2pi) `dir2pi` command to update the metadata.

### Test the package
To test the new package, we builded Wazuh and extracted the updated package into the `src/external/cpython` folder. After succesfully running the `install.sh` script, we made sure that the new dependency is available for the embedded interpreter:

```
root@0dff4846b97f:/wazuh# /var/ossec/framework/python/bin/python3
Python 3.9.9 (main, Mar  1 2022, 12:07:48) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pythonjsonlogger import jsonlogger
>>> 
root@0dff4846b97f:/wazuh# /var/ossec/framework/python/bin/python3 -m pip freeze | grep json-logger
python-json-logger==2.0.2
```

We are currently working on updating the compiled `amd64` package.

**Comment by noise-kngdm** [comment]
## Issue update
We have updated the pre-compiled `aarch64` and `amd64` packages. To test them, we set up a Centos 7 machine with Wazuh v4.1.5, then changed the `requirements.txt` file with the one from the `feature/10867-api-json-log` branch and, after installing all the compilation dependencies, ran `/wazuh/src/make deps`. Once the dependencies were build, we removed the `/wazuh/src/external/cpython` folder and extracted the one updated by us instead. Finally, we executed the `/wazuh/install.sh` script.

As a note, to be able to use an arm Centos7 container in our host we used the [qemu](https://hub.docker.com/r/multiarch/qemu-user-static) emulator.

Once the execution finished, we got the following results:

### amd64

```
[root@c82d367bd8db wazuh]# /var/ossec/framework/python/bin/python3
Python 3.9.9 (main, Mar  2 2022, 12:57:05) 
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from wazuh import *
>>> from pythonjsonlogger import jsonlogger
>>> 
[root@c82d367bd8db wazuh]# /var/ossec/framework/python/bin/python3 -m pip freeze | grep json-logger
python-json-logger==2.0.2
```

### aarch64
We have been facing compilation when trying to compile the Wazuh manager in a `arm` architecture. We will work on that to be able to later test the changes made to the arm embedded python interpreter.


### Conclusions
The `amd64` package is working fine, we just need to update the compiled ones using the pre-compiled.

**Comment by noise-kngdm** [comment]
## Issue update
We have updated the `aarch64` and `amd64` compiled Python packages. Then, we tested them using a fresh environment whose external dependencies include the ones updated. After installing Wazuh, we got the following results:

### amd64
The installation for amd64 processors is working as expected

```
root@f99dcc72066b:/var/ossec/framework/python/bin# ./python3
Python 3.9.9 (main, Mar  3 2022, 16:05:35) 
[GCC 5.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from wazuh import *
>>> from pythonjsonlogger import *
>>> 
root@f99dcc72066b:/var/ossec/framework/python/bin# ./pip3 freeze | grep python-json
python-json-logger==2.0.2
```

### aarch64
The installation for arm64 processors is working as expected. 
```
root@50dbeab70e32:/var/ossec/framework/python/bin# /var/ossec/framework/python/bin/python3
Python 3.9.9 (main, Mar  3 2022, 12:33:11) 
[GCC 5.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from wazuh import *
>>> from pythonjsonlogger import jsonlogger
>>> 
root@50dbeab70e32:/var/ossec/framework/python/bin# /var/ossec/framework/python/bin/python3 -m pip freeze | grep json-logger
python-json-logger==2.0.2
```

### sources
The installation from sources is working as expected.

```
root@336796223f1a:/var/ossec/bin# cd ../framework/python/bin/
root@336796223f1a:/var/ossec/framework/python/bin# ./python3
Python 3.9.9 (main, Mar  3 2022, 16:09:58) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pythonjsonlogger import *
>>> from wazuh import *
>>> 
root@336796223f1a:/var/ossec/framework/python/bin# ./pip3 freeze | grep python-json
python-json-logger==2.0.2
```

## Conclusions
The different installation methods have been correctly updated, to finish with this issue we just need to upload the new Python packages to the folder corresponding to the version 16 of the dependencies.

**Comment by mcarmona99** [comment]
The `python-json-logger` dependency has been removed from the embedded python. This issue is reopened to review why the dependency is not available and add it to our embedded python interpreter again.
