### ISSUE TITLE
Remove unnecessary CloudWatch Logs debug messages

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#11160]
| Affected integration |
|---|
| AWS CloudWatch Logs |

## Description

During the #10964 we found the CloudWatch Logs module is showing every event sent to analysisd if debug mode level 2 is used. This could result in too many messages present in the ossec.log. This kind of messages should be available if debug mode level 3 is used instead.

## Tasks
- [x] Replace the debug condition from level 2 to level 3
- [x] Test in a manager
- [x] Add entry to the changelog if necessary

**Comment by fdalmaup** [comment]
# Issue Update 

The modification of the debug level of the messages described in the issue's description has been carried out. The message `+++ Sending events to Analysisd...` is shown as the first message previous to sending each event to Analysisd and after that the message `+++ Sent X events to Analysisd`, being X the number of events processed, is shown. These messages require a debug level of 2.

**Comment by fdalmaup** [comment]
# Manual Test CloudWatch Logs

## Test details
The following tests have been done in a Wazuh Manager instance. Its version was 4.5 (master branch).

Before starting these tests, a series of Cloudwatch Logs test events in a period of 7 days in the past until today must be uploaded to the `4_5_test`'s `test_stream` log stream.

### Debug level 2
Remove the `/var/ossec/wodles/aws/aws_services.db` file and run the module using the following command to obtain every log from the Cloudwatch Logs log group for the given date.

Command
```
/var/ossec/wodles/aws/aws-s3 -sr cloudwatchlogs -g 4_5_test -d 2 -s 2022-JUL-29 -p dev -r us-east-1
```
<details><summary>Command output</summary>

    /var/ossec/wodles/aws/aws-s3 -sr cloudwatchlogs -g 4_5_test -d 2 -s 2022-JUL-29 -p dev -r us-east-1
    DEBUG: +++ Debug mode on - Level: 2
    DEBUG: +++ Getting alerts from "us-east-1" region.
    DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
    DEBUG: only logs: 1659052800000
    DEBUG: +++ Table does not exist; create
    DEBUG: Getting log streams for "4_5_test" log group
    DEBUG: Found "test_stream" log stream in 4_5_test
    DEBUG: Getting data from DB for log stream "test_stream" in log group "4_5_test"
    DEBUG: Token: "None", start_time: "None", end_time: "None"
    DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_5_test" using token "None", start_time "1659052800000" and end_time "None"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: +++ Sent 16 events to Analysisd
    DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_5_test" using token "f/37022632589172071573263438858639281121463877139200933888/s", start_time "1659052800000" and end_time "None"
    DEBUG: Saving data for log group "4_5_test" and log stream "test_stream".
    DEBUG: The saved values are "{'token': 'f/37022632589205522689054233858347788404597368857223462911/s', 'start_time': 1659052800000, 'end_time': 1660152262159}"
    DEBUG: Purging the BD
    DEBUG: Getting log streams for "4_5_test" log group
    DEBUG: Found "test_stream" log stream in 4_5_test
    DEBUG: committing changes and closing the DB
</details>

Keep the database file and run the same command again to ensure no duplicate logs are processed. Use the same `only_logs_after` parameter.

<details><summary>Command output</summary>

    /var/ossec/wodles/aws/aws-s3 -sr cloudwatchlogs -g 4_5_test -d 2 -s 2022-JUL-29 -p dev -r us-east-1
    DEBUG: +++ Debug mode on - Level: 2
    DEBUG: +++ Getting alerts from "us-east-1" region.
    DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
    DEBUG: only logs: 1659052800000
    DEBUG: Getting log streams for "4_5_test" log group
    DEBUG: Found "test_stream" log stream in 4_5_test
    DEBUG: Getting data from DB for log stream "test_stream" in log group "4_5_test"
    DEBUG: Token: "f/37022632589205522689054233858347788404597368857223462911/s", start_time: "1659052800000", end_time: "1660152262159"
    DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_5_test" using token "f/37022632589205522689054233858347788404597368857223462911/s", start_time "1660152262160" and end_time "None"
    DEBUG: Saving data for log group "4_5_test" and log stream "test_stream".
    DEBUG: The saved values are "{'token': 'f/37022632589205522689054233858347788404597368857223462911/s', 'start_time': 1659052800000, 'end_time': 1660152262160}"
    DEBUG: Some data already exists on DB for that key. Updating their values...
    DEBUG: Purging the BD
    DEBUG: Getting log streams for "4_5_test" log group
    DEBUG: Found "test_stream" log stream in 4_5_test
    DEBUG: committing changes and closing the DB

</details>

### Debug level 3
Remove the `/var/ossec/wodles/aws/aws_services.db` file and run the module using the following command to obtain every log from the Cloudwatch Logs log group for the given date.

Command
```
/var/ossec/wodles/aws/aws-s3 -sr cloudwatchlogs -g 4_5_test -d 3 -s 2022-JUL-29 -p dev -r us-east-1
```
<details><summary>Command output</summary>

    /var/ossec/wodles/aws/aws-s3 -sr cloudwatchlogs -g 4_5_test -d 3 -s 2022-JUL-29 -p dev -r us-east-1
    DEBUG: +++ Debug mode on - Level: 3
    DEBUG: +++ Getting alerts from "us-east-1" region.
    DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
    DEBUG: only logs: 1659052800000
    DEBUG: +++ Table does not exist; create
    DEBUG: Getting log streams for "4_5_test" log group
    DEBUG: Found "test_stream" log stream in 4_5_test
    DEBUG: Getting data from DB for log stream "test_stream" in log group "4_5_test"
    DEBUG: Token: "None", start_time: "None", end_time: "None"
    DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_5_test" using token "None", start_time "1659052800000" and end_time "None"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: The message is "Test log 0 - 2022-7-29"
    DEBUG: The message's timestamp is 1659100462660
    DEBUG: "Test log 0 - 2022-7-29"
    DEBUG: The message is "Test log 1 - 2022-7-29"
    DEBUG: The message's timestamp is 1659100472502
    DEBUG: "Test log 1 - 2022-7-29"
    DEBUG: The message is "Test log 2 - 2022-7-29"
    DEBUG: The message's timestamp is 1659100483581
    DEBUG: "Test log 2 - 2022-7-29"
    DEBUG: The message is "Test log 3 - 2022-7-29"
    DEBUG: The message's timestamp is 1659100492369
    DEBUG: "Test log 3 - 2022-7-29"
    DEBUG: The message is "Test log 4 - 2022-7-29"
    DEBUG: The message's timestamp is 1659100502933
    DEBUG: "Test log 4 - 2022-7-29"
    DEBUG: The message is "Test log 5 - 2022-7-29"
    DEBUG: The message's timestamp is 1659100512690
    DEBUG: "Test log 5 - 2022-7-29"
    DEBUG: The message is "Test log 6 - 2022-7-29"
    DEBUG: The message's timestamp is 1659100522240
    DEBUG: "Test log 6 - 2022-7-29"
    DEBUG: The message is "Test log 7 - 2022-7-29"
    DEBUG: The message's timestamp is 1659100531170
    DEBUG: "Test log 7 - 2022-7-29"
    DEBUG: The message is "Test log 8 - 2022-7-29"
    DEBUG: The message's timestamp is 1659100540310
    DEBUG: "Test log 8 - 2022-7-29"
    DEBUG: The message is "Test log 9 - 2022-7-29"
    DEBUG: The message's timestamp is 1659100550044
    DEBUG: "Test log 9 - 2022-7-29"
    DEBUG: The message is "Test log 10 - 2022-7-29"
    DEBUG: The message's timestamp is 1659100556663
    DEBUG: "Test log 10 - 2022-7-29"
    DEBUG: The message is "Test log 11 - 2022-7-29"
    DEBUG: The message's timestamp is 1659100566406
    DEBUG: "Test log 11 - 2022-7-29"
    DEBUG: The message is "Test log 12 - 2022-7-29"
    DEBUG: The message's timestamp is 1659100574840
    DEBUG: "Test log 12 - 2022-7-29"
    DEBUG: The message is "Test log 13 - 2022-8-1      1659355579"
    DEBUG: The message's timestamp is 1659355591835
    DEBUG: "Test log 13 - 2022-8-1      1659355579"
    DEBUG: The message is "Test log 14 - 2022-8-5   1659625348516"
    DEBUG: The message's timestamp is 1659625354421
    DEBUG: "Test log 14 - 2022-8-5   1659625348516"
    DEBUG: The message is "Test log 15 - 2022-8-10    1660152255717"
    DEBUG: The message's timestamp is 1660152262159
    DEBUG: "Test log 15 - 2022-8-10    1660152255717"
    DEBUG: +++ Sent 16 events to Analysisd
    DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_5_test" using token "f/37022632589172071573263438858639281121463877139200933888/s", start_time "1659052800000" and end_time "None"
    DEBUG: Saving data for log group "4_5_test" and log stream "test_stream".
    DEBUG: The saved values are "{'token': 'f/37022632589205522689054233858347788404597368857223462911/s', 'start_time': 1659052800000, 'end_time': 1660152262159}"
    DEBUG: Purging the BD
    DEBUG: Getting log streams for "4_5_test" log group
    DEBUG: Found "test_stream" log stream in 4_5_test
    DEBUG: committing changes and closing the DB
    
</details>

Keep the database file and run the same command again to ensure no duplicate logs are processed. Use the same `only_logs_after` parameter.

<details><summary>Command output</summary>

    /var/ossec/wodles/aws/aws-s3 -sr cloudwatchlogs -g 4_5_test -d 3 -s 2022-JUL-29 -p dev -r us-east-1
    DEBUG: +++ Debug mode on - Level: 3
    DEBUG: +++ Getting alerts from "us-east-1" region.
    DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
    DEBUG: only logs: 1659052800000
    DEBUG: Getting log streams for "4_5_test" log group
    DEBUG: Found "test_stream" log stream in 4_5_test
    DEBUG: Getting data from DB for log stream "test_stream" in log group "4_5_test"
    DEBUG: Token: "f/37022632589205522689054233858347788404597368857223462911/s", start_time: "1659052800000", end_time: "1660152262159"
    DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_5_test" using token "f/37022632589205522689054233858347788404597368857223462911/s", start_time "1660152262160" and end_time "None"
    DEBUG: Saving data for log group "4_5_test" and log stream "test_stream".
    DEBUG: The saved values are "{'token': 'f/37022632589205522689054233858347788404597368857223462911/s', 'start_time': 1659052800000, 'end_time': 1660152262160}"
    DEBUG: Some data already exists on DB for that key. Updating their values...
    DEBUG: Purging the BD
    DEBUG: Getting log streams for "4_5_test" log group
    DEBUG: Found "test_stream" log stream in 4_5_test
    DEBUG: committing changes and closing the DB

</details>

## Conclusions
The module is working as expected.

**Comment by fdalmaup** [comment]
# Test setting `ossec.conf`

Run the module adding the following configuration to the `ossec.conf` file
<details><summary>Configuration</summary>
    
    <wodle name="aws-s3">
      <disabled>no</disabled>
      <remove_from_bucket>no</remove_from_bucket>
      <interval>10m</interval>
      <run_on_start>yes</run_on_start>
      <skip_on_error>no</skip_on_error>
  
      <service type="cloudwatchlogs">
          <aws_profile>dev</aws_profile>
          <aws_log_groups>4_5_test</aws_log_groups>
          <only_logs_after>2021-AUG-20</only_logs_after>
          <regions>us-east-1</regions>
      </service>
    </wodle>

</details>

<details><summary>ossec.log</summary>

  2022/09/23 15:21:36 wazuh-modulesd:aws-s3[3817] wm_aws.c:59 at wm_aws_main(): INFO: Module AWS started
  2022/09/23 15:21:36 wazuh-modulesd:aws-s3[3817] wm_aws.c:81 at wm_aws_main(): INFO: Starting fetching of logs.
  2022/09/23 15:21:36 wazuh-modulesd:aws-s3[3817] wm_aws.c:168 at wm_aws_main(): INFO: Executing Service Analysis: (Service: cloudwatchlogs, Profile: dev)
  2022/09/23 15:21:36 wazuh-modulesd:aws-s3[3817] wm_aws.c:507 at wm_aws_run_service(): DEBUG: Create argument list
  2022/09/23 15:21:36 wazuh-modulesd:aws-s3[3817] wm_aws.c:611 at wm_aws_run_service(): DEBUG: Launching S3 Command: wodles/aws/aws-s3 --service cloudwatchlogs --aws_profile dev --only_logs_after 2021-AUG-20 --regions us-east-1 --aws_log_groups 4_5_test --debug 2
  2022/09/23 15:21:39 wazuh-modulesd:aws-s3[3817] wm_aws.c:652 at wm_aws_run_service(): DEBUG: Service: cloudwatchlogs  -  OUTPUT: DEBUG: +++ Debug mode on - Level: 2
  2022/09/23 15:21:40 wazuh-modulesd:aws-s3[3817] wm_aws.c:173 at wm_aws_main(): INFO: Fetching logs finished.
  2022/09/23 15:21:40 wazuh-modulesd:aws-s3[3817] wm_aws.c:77 at wm_aws_main(): DEBUG: Sleeping until: 2022/09/23 15:31:36

</details>


## Conclusions

The module is working as expected.
