### ISSUE TITLE
Rework issue 9056 - Add OracleDB 12c cluster ruleset

### ISSUE THREAD

**Issue by xrisbarney** [wazuh/wazuh#11272]
|Wazuh version|Component|Install type|Install method|Platform|Action type|
|---|---|---|---|---|---|
| 4.3.0 | Rules and Decoders | Manager | Packages | Any | Rework|

|Related issues|Related PR|
|---|---|
| #9056 | #9238  |

|Related PR|
|---|
| #11274  |

## Description
This issue is has been created as a rework of the rules in PR #9238 to close issue #9056. 
The aim of this issue is:
- To ensure the rules and decoders from the issue are reverted.
- To add tests.
- To fix issues regarding indentation, syntax, rule granularity, spellings and ensure the ruleset quality is standard.

## Original Issue
Type: Ruleset improvements. 

### Request from #9056
# Description
Ruleset for Oracle DB needs to be added.

Questionnaire summary:
```
What product is? Oracle DB - cluster
Any particular version? 12C
Is it paid? Yes - license is needed
  How we proceed to get that product installed for us? They will send us logs of 6 month
  What are the environment requirements to install the product? -
What are you needs? See security alerts, healthcheck, initdb logs provided by oracle (no additional information is needed)
What do you expect to see on Wazuh? -
Did you have any security issue that you expect to see? No
Exists documentation about the product? -
Do we need core team integration? Yes, maybe, we need to confirm
Expected date? 2/3 weeks
Expected Wazuh version? They want to install 4.2
Compliance or Mitre information? - 
```
## Logs
We have 2 types of logs, `.log` and `.aud` files.

Audit files contains logs of database operations and queries, they are multi-line, some examples:
```aud
Sat Dec 21 22:13:41 2019 +05:30
LENGTH : '4582'
ACTION :[4430] 'select /*+  no_parallel(t) no_parallel_index(t) dbms_stats cursor_sharing_exact use_weak_name_resl dynamic_sampling(0) no_monitoring xmlindex_sel_idx_tbl no_substrb_pad  */ substrb(dump("USER#",16,0,64),1,240) val, 
                      rowidtochar(rowid) rwid from "SYS"."USER$" t where rowid in (chartorowid('AAAAAKAABAAAADRAAA'),chartorowid('AAAAAKAABAAAADRAAB'),...) order by "USER#"'
DATABASE USER:[3] 'SYS'
PRIVILEGE :[4] 'NONE'
CLIENT USER:[0] ''
CLIENT TERMINAL:[7] 'UNKNOWN'
STATUS:[1] '0'
DBID:[10] '3320902093'

Sat Dec 21 22:13:41 2019 +05:30
LENGTH : '4582'
ACTION :[4430] 'select /*+  no_parallel(t) no_parallel_index(t) dbms_stats cursor_sharing_exact use_weak_name_resl dynamic_sampling(0) no_monitoring xmlindex_sel_idx_tbl no_substrb_pad  */ substrb(dump("USER#",16,0,64),1,240) val, 
                      rowidtochar(rowid) rwid from "SYS"."USER$" t where rowid in (chartorowid('AAAAAKAABAAAADRAAA'),chartorowid('AAAAAKAABAAAADRAAB'),chartorowid('AAAAAKAABAAAADRAAC'),chartorowid('AAAAAKAABAAAADRAAD'),chartorowid('AAAAAKAABAAAADRAAE'), ...) order by "USER#"'
DATABASE USER:[3] 'SYS'
PRIVILEGE :[4] 'NONE'
CLIENT USER:[0] ''
CLIENT TERMINAL:[7] 'UNKNOWN'
STATUS:[1] '0'
DBID:[10] '3320902093'
```

Log files are also multi-line and they contain general logging, some examples:
```log
Thu Feb 11 13:14:56 2021
Thread 1 advanced to log sequence 13060 (LGWR switch)
  Current log# 2 seq# 13060 mem# 0: +NPCDBDG/CDBTST93/ONLINELOG/group_2.384.1017127695
  Current log# 2 seq# 13060 mem# 1: +FLASHDG/CDBTST93/ONLINELOG/group_2.263.1017127695
Thu Feb 11 13:14:56 2021
Archived Log entry 13813 added for thread 1 sequence 13059 ID 0xc5f18acd dest 1:
Thu Feb 11 13:32:07 2021
skgxpvfynet: mtype: 61 process 38909 failed because of a resource problem in the OS. The OS has most likely run out of buffers (rval: 4)
Errors in file /opt/oracle/app/oracle/diag/rdbms/cdbtst93/CDBTST931/trace/CDBTST931_ora_38909.trc  (incident=346160):
ORA-00603: ORACLE server session terminated by fatal error
ORA-27504: IPC error creating OSD context
ORA-27300: OS system dependent operation:sendmsg failed with status: 105
ORA-27301: OS failure message: No buffer space available
ORA-27302: failure occurred at: sskgxpsnd2
Incident details in: /opt/oracle/app/oracle/diag/rdbms/cdbtst93/CDBTST931/incident/incdir_346160/CDBTST931_ora_38909_i346160.trc
opiodr aborting process unknown ospid (38909) as a result of ORA-603
Thu Feb 11 13:32:08 2021
Dumping diagnostic data in directory=[cdmp_20210211133208], requested by (instance=1, osid=38909), summary=[incident=346160].
```

## Tasks
- [x] Test multi-line functionality on Wazuh 4.2
- [x] Develop decoders
  - [x] Audit decoders
  - [x] General logging decoders
- [x] Develop generic rules
  - [x] Generic Audit rules
  - [x] Generic general logging rules
  - [x] Map applicable compliance 

## Branch to track changes
https://github.com/wazuh/wazuh/tree/9056_add_oracledb_12c_ruleset
