### ISSUE TITLE
Add API JSON log handling

### ISSUE THREAD

**Issue by Kondent** [wazuh/wazuh#11308]
This is an epic development regarding API JSON logs configuration and modifications in affected repositories.

Tasks:
- [x] Make API log format configurable (via its configuration file).
- [x] Handle the configured log format at our log related modules.
- [x] Review and verify if a new dependency is needed.
- [x] Open necessary issues in all the affected repositories and notify the affected teams.

* Working `wazuh/wazuh` branch: `dev-support-api-json-log`.
* Last rebase from `4.4`: 9 May 2022, 8:40 CET

> EDIT: `dev-support-api-json-log` already merged into `4.4` (https://github.com/wazuh/wazuh/pull/13197)

**Comment by mcarmona99** [comment]
No issue was opened in the [wazuh-ansible](https://github.com/wazuh/wazuh-ansible/) repository as the `api.yaml` used by the Ansible deployment is the default that comes with the wazuh-manager installation package.

Ref.: https://github.com/wazuh/wazuh-ansible/issues/691#issuecomment-999521420
