### ISSUE TITLE
Engine MVP

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#11334]
# Description

[Design document](https://docs.google.com/document/d/125d8tpj192MNdggLcNjk_R0tQWEuhjBEmtjONHbUkHo/edit#)
[User manual](https://docs.google.com/document/d/1N0p7pd7XszQwFU9HBjpB7txIw2DCcAsV-BKfEZSLixw/edit)
[Environment setup](https://docs.google.com/document/d/1FvBedeyAD1TniSl4yfgskT4aSaxhPs8eKi3ySKUpne8/edit#heading=h.k2r2a39mafs4)

Currently, the decoders and rules are based on a declarative XML syntax, which does not cover all the functionalities that we want to have in order to improve our threat intelligence offering. Also, currently, the way of developing rules and decoders may be confusing and overwhelming, given the excessive need of using regular expressions.
There are also considerations about scalability, usability, robustness and licensing which we want to address through this design process.
This proposal will then try to improve the user experience; potentiate the threat detection ability of the engine and help with the adoption of the Common Schema.

<img width="733" alt="image" src="https://user-images.githubusercontent.com/2181918/198263362-d943aca9-8e31-41bd-b70f-4647e728a980.png">

High-level component description:

- Store: in charge of managing the life cycle of schemas, decoders, rules, filters, and outputs. It manages the versioning automatically and persists the information in an appropriate storage. The catalog storage is only accessible through the API.
- Builder: transforms a description into appropriate executable code. It validates the description syntax and semantics, and generates operations ready to be executed. It will link the graph of execution, putting the built operations in the correct order. It links decoders, rules and outputs together, building the optimized engine dynamically.
- Codegen: takes the builder output and generated code which will be executed using one of the backend available. Currently, only the RXCPP backend is implemented.
- Server: receives Wazuh protocol events, extracts its payload and prepares it to be processed by the engine, then delivers the pre-processed event object to the router.
- API: Provides a standard interface to access all the features of the service. It also has an authentication mechanism to allow or deny access to the API.
- Metrics: Provides a standard interface to access all the monitoring data of the service. Any component should be able to register metrics.
- Router: Manages the running “sandboxes” or “environments”. Each sandbox routes events from the input in the protocol/server to an engine environment (production, staging, testing, etc.). Each environment is in charge of:

  - Decoding and normalization of events
  - Setting the threat level of relevant events
  - Deciding where each event should end after being processed, either in a configured output or filtered out and discarded

 # Plan

## Spike

This design will define the set of features our engine must support, without taking on implementation designs. It will be refined over time, as development progresses.
 - [x] #10681

## MVP design and implementation

Implement the minimum functionality which allow us to measure the performance of the main functionalities of the design with production-like workloads.
We will validate the design, identifying weak points and changing the design accordingly to improve them.

<details>
<summary>Issues</summary>

- [x] #11336 
- [x] #11335 
- [x] #11337 
- [x] #11339
- [x] #11340
- [x] #11765 
- [x] #11968
 
 </details>

## Feature complete implementation
Complete the features required for a production release. We will focus on creating the most used parsers, function helpers and CDB support.
The API must allow for the complete management of the service by the users. It should implement the authentication and authorization methods aligned with the external Wazuh API served by the framework.

<details>
<summary>Issues</summary>

  - [x] #12122 
  - [x] #12124 
  - [x] #12125 
  - [x] #12272
  - [x] #12481
  - [x] #12597 
  - [x] #13008 
  - [x] #13038 
  - [x] #13803
  - [x] #14737
  - [x] #14738
  - [x] #14792
  - [x] #15083 
  - [x] #15988
  - [x] #15939
  - New cases:
    - [x] #17980
    - [x] #18177
    - [x] #17609

 </details>

## Ensure the performance and robustness
Complete the testing framework for the service, including all integrated test and benchmarks. An extensive battery of tests should ensure the robustness of the service, so we will focus on fail scenarios, corner cases and long-term running benchmarks and stability.

<details>
<summary>Issues</summary>

- [x] #16087
- [x] #16156
- [x] #16013
- [x] #15963
- [x] #16385
- [x] #16358
- [x] #16614
- [x] #16677
- [x] #16695
- [ ] #16688
- [x] #16741
- [x] #16892
- [x] #16920
- [x] #16892
- [x] #17147
- [x] #16741
- [x] #17980
- [x] #17847
- [x] #18046
- [x] #17877
- [ ] #18019
- [x] #18527
- [x] #18523
- [x] #18524
- [x] #18525
- [x] #18989
- [x] #18990
- [x] #19459
- [x] #19761
- [x] #19998
- [x] #19863
- [x] #20090

 </details>

Generate all the relevant documentation
Polish the user documentation and training materials, so the users can start using the software features as intended.
  - [ ] [User manual](https://docs.google.com/document/d/1N0p7pd7XszQwFU9HBjpB7txIw2DCcAsV-BKfEZSLixw/)
  - [ ] [Tutorial](https://docs.google.com/document/d/1FvBedeyAD1TniSl4yfgskT4aSaxhPs8eKi3ySKUpne8/)
  - [ ] [Design document](https://docs.google.com/document/d/125d8tpj192MNdggLcNjk_R0tQWEuhjBEmtjONHbUkHo/)

## Integration

The new engine will be integrated with Wazuh and will be installed by default. All the new features will be available to users upon release.

<details>
<summary>Issues</summary>

- [x] #14738
- [x] #16307
- [x] #16457
- [x] #16497
- [x] #16754
- [x] #16685 
- [x] #18316
- [x] #18416

</details>

These efforts will produce [a testing environment in a convenient VM](https://github.com/wazuh/wazuh/blob/11334-dev-new-wazuh-engine/src/engine/test/scripts/Vagrantfile) which will deliver the latest builds to team members and users.

### Event acquisition

The new engine will support the current protocols to receive events from other components, and its design will support multiple protocols at the same time.
It will also deliver messages to wazuh-db, while allowing future evolutions when needed.

<details>
<summary>Issues</summary>

- [x] #16261
- [x] #16263
- [x] #16467
- [x] #17762
- [x] #18458
- [x] #18935
- [x] #19021
- [x] #20157
- [x] #20350 

 </details>

### Event processing
  We will work with @wazuh/threat-intel to create new rules and decoders, as per the new engine objectives. Also, we will provide a metrics module and an event congestion mechanism.

<details>
<summary>Issues</summary>

- [x] #15181
- [x] #16243
- [x] #16371
- [x] #15485
- [x] #15845
- [x] #18806
- [x] #19051
- [ ] decoders & rules documentation
</details>
   
We will have a new documentation section where all the details related to devices and formats supported, the fields extracted, and other metadata. We will work with @wazuh/content 

### Event indexation
  Initially, the engine will rely on the current architecture for event indexation, in future version this might change to simplify or improve the product.
  We will use a single index pattern and a daily log rotation, with the capability to implement roll-overs if necessary.

<details>
<summary>Issues</summary>

- [x] #16104

</details>

### Engine management and APIs
  The engine will provide a new set of APIs, enabling users more control over the engine. We will work with @wazuh/framework to deliver these APIs to the end users. We might opt to design new endpoints or to update the ones we already have.

<details>
<summary>Issues</summary>

- [x] Configuration API
- [x] Metrics API
- [x] Catalog API
- [x] Environments API
- [x] KVDB API
- [x] Router API
- [x] Testing API
- [x] Policy API
- [ ]  https://github.com/wazuh/wazuh/issues/17058
- [ ]  Building, packaging and delivery
    We will work with @wazuh/cicd to create the appropriate building and packaging pipelines. The engine will be a component of the wazuh-manager package.
    We will work with @wazuh/core to update the compilation process to fit wazuh standards.
    - [ ] Update wazuh manager packages
    - [ ] Update installation assistant
    - [ ] Update installation from sources documentation and scripts
    - [ ] Create default configurations
    - [ ] Update docker images, and 3rd party tooling like ansible and puppet scripts.

### Dashboards & indexer
  We will work with @wazuh/frontend to support these new changes. New features will appear over time once the engine
is delivered. The features we already have related to the current engine will be updated. We will work with @wazuh/design to improve the general UX of the new components.

    - [ ] New alerts index pattern wazuh-alerts-5.x
    - [ ] Enhance current queries to support new schema and indexed fields
    - [ ] Update and enhance current visualizations to support new and current indexes
    - [ ] Add support for new rules & decoders formats and APIs
    - [ ] Add support for new KVDB APIs

### Exhaustive testing
  We will define a testing plan for the whole product. Its focus will be to test the correct operation of the product as a whole with the new engine.
 - [ ] #18019

### Update product documentation
  General product documentation will be updated to reflect these changes. We will work with @wazuh/content to create the appropriate pages and updates.

### Training
  We might decide to organize webinars, articles, training sessions, etc. for Wazuh team and its community to ease the transition to the new engine.

### Related issues that might be tackled on this effort

- [ ] #15451

**Comment by zbalkan** [comment]
Will the new engine be able to install/apply new rules without a service restart?

**Comment by zbalkan** [comment]
May I suggest using [rqlite](https://github.com/rqlite/rqlite) for rules and configuration? Using a distributed local database might enable you to ignore master-worker separation by eliminating the tasks below thanks to raft algorithm for distribution.

- Receive and manage agent registration requests. (every worker can accept and write to database)
- Creating shared configuration groups. (Every worker can accept the settings and write to database)
- Updating custom rules, decoders and CDB lists. (Every worker can accept the rule, decoder, CDB list changes and write to database)
- Synchronizing all this information to the workers. (rqlite handles the synchronization)

It would also speed up to ruleset/config reloading by converting it just to a database query operation. This would eliminate the need to restart for some use cases.

With the elimination of master-worker node roles, the case for load balancing would not require a separate Nginx or HAProxy node, because a keepalived configuration on nodes with a single IP for cluster would solve that issue too.

**Comment by gdiazlo** [comment]
@zbalkan thanks for your suggestions. The changes you propose exceed the purpose of the engine. But that does not mean we aren't aware of the situations you comment on. That's why the design of the engine tries to:
* work and integrate with the Wazuh of today
* enable Wazuh to change and grow without the engine becoming a stopper.

There are other projects which will affect the rule-set life cycle and the cluster capabilities. The engine will need to be updated when those projects land.

**Comment by gdiazlo** [comment]
> Will the new engine be able to install/apply new rules without a service restart?

@zbalkan  yes, it will support dynamic updates.
