### ISSUE TITLE
Builder / linker component for the new engine

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh#11339]
| Epic | Branch | PR |
|-|-|-|
|#11334| [11339-builder-linker-engine](https://github.com/wazuh/wazuh/tree/11339-builder-linker-engine) | #11399 (Draft) |

## Description
The builder / linker will be in charge of building an environment from its definition in the catalog. It will generate the processing graph, asking the catalog to provide the relevant assets specified in the environment definition. In order to implement a modular and easy to expand functionality we are implementing the [builder pattern](https://en.wikipedia.org/wiki/Builder_pattern#:~:text=The%20builder%20pattern%20is%20a,Gang%20of%20Four%20design%20patterns.) to build the different components through this module.
## Tasks
 - [x] operations graph
Define the operations API and how to build an execution graph. We should leverage RxCpp library to implement these components. 
- [x]  decoders, rules and filters parsing
Convert assets definition into executable operations. The operations must be ordered following their precedence stated in the definition document.

- [ ] ~Convert logql expressions into executable operations.~
 - [x] output parsing
We should support only one type of output initially: file output, in the future we will need to support different types of outputs such as elastic search, active response, etc.
 - [ ] basic parsers and function helpers
  Support the following basic function helpers and parsers:

    Parser:
   - [ ] timestamp/format 
   - [ ] ip
   - [ ] cidr
   - [ ] hostname
 
   Function Helpers:
    - [ ] +gt / greater than
    - [ ] +lt / less than

### Concrete implementation tasks
- [x] Implement registry to store all builders
- [x] Implement Builder class
  - [x] Implement auto registration on Builder construction
- [x] Implement specialized Builder class for building operations
  - [x] Implement basic operations (instances of builders)
    - [x] Implement condition value operation
    - [x] Implement condition field exists operation
    - [x] Implement mapping value operation
    - [x] Implement mapping reference operation
- [x] Implement specialized Builder class for building ensembles (decoders, rules, filters...)
  - [x] Implement basic decoder operation (instance of builder)
- [x] Implement specialized Builder class for building engines (groups of ensembles)
  - [x] Implement basic graph operation for ensembles (instance of builder)
- [x] Implement interface to build environments (groups of engines) (used by router)

**Comment by JavierBejMen** [comment]
## Update
So far the following functionality has been implemented:
- Registry class to obtain Builders
- Builder class with registration on registry when constructor is called
- Builder error exception to handle unexpected situations when building objects
- JsonBuilder class that describes a builder which accepts a json as input
- MultiJsonBuilder class that describes a builder which accepts multiple jsons as input
- Operation condition value to check if fields present in the event contains specific value
- Auxiliary JsonPath class to split strings containing a json path
- Tests for all implemented classes

**Comment by JavierBejMen** [comment]
## Update
Quality and best practices refactor
- Renamed al *.h -> *.hpp
- Deleted all using namespace clauses from header files
- Updated cpp files to include correct headers
- Deleted unused includes
- Minor style corrections

Implemented:
- Function helper exists and not_exists
- Added `builder::syntax` namespace to define syntax anchors and other parser's elements
- Condition builder to choose between conditions and helpers
- Refactored builder/CMakelists.txt to make it cleaner
- Added very basic decoder builder with stage check
- Added tests for all new functionality

**Comment by gdiazlo** [comment]
Closed by #11399
