### ISSUE TITLE
Rework of issue #8501 - Merge macos-sshd ruleset into sshd ruleset

### ISSUE THREAD

**Issue by fabamatic** [wazuh/wazuh#11421]
|Wazuh version|Component|Action type|Install method|Platform|
|---|---|---|---|---|
| 4.3.0 | Rules and Decoders | Rework | Packages | Any |

### Description
|Related issue|Related PR|
|---|---|
| #8501| #10768|

The aim of this issue is:
- To ensure the rules and decoders from issue #8501 work correctly.
- To fix issues regarding indentation, syntax, rule granularity, spellings and ensure the ruleset quality is standard

------------------------------------------------------------------------------------------------------------------------------------------------
## Description
With the forecomming predecoder update to take macos-sshd timestamps, current ruleset for said service will be absorved by sshd ruleset, so we need to merge macos-sshd ruleset into sshd ruleset.

### Related issue
#8427

## Tasks
- [x] Add required decoders from macos-sshd to sshd
- [x] Add required rules from macos-sshd to sshd
- [ ] Delete macos-sshd rules/decoders/.ini
- [x] Adjust test file .ini to the new sshd ruleset
- [ ] Test solution
