### ISSUE TITLE
Fix the `--reparse` option in the AWS VPCFlow and Config integrations

### ISSUE THREAD

**Issue by noise-kngdm** [wazuh/wazuh#11473]
| Affected integration |
|---|
| AWS VPCFlow|

## Description

During the testing of #11428 we found a bug related to the VPCFlow reparse option that wasn't fixed in #11113. Once the database is populated, using the `--reparse` option and specifying an `only_logs_after` value should make the module reparse every log from the date specified by the `only_logs_after` parameter until the date of execution. Instead, the module only collects the logs starting from the date of the last log processed.

```
root@42453d0af7b0:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-vpcflow -t vpcflow -s 2021-NOV-09 --reparse -p dev -d2
DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Working on 166157441623 - us-east-1
DEBUG: +++ Marker: AWSLogs/166157441623/vpcflowlogs/us-east-1/2021/11/09
DEBUG: ++ File previously processed, but reparse flag set: AWSLogs/166157441623/vpcflowlogs/us-east-1/2021/12/23/166157441623_vpcflowlogs_us-east-1_fl-03fbf155728a27ded_20211223T0000Z_ce6176d8.log.gz
DEBUG: ++ Found new log: AWSLogs/166157441623/vpcflowlogs/us-east-1/2021/12/23/166157441623_vpcflowlogs_us-east-1_fl-03fbf155728a27ded_20211223T0000Z_ce6176d8.log.gz
DEBUG: +++ File already marked complete, but reparse flag set: AWSLogs/166157441623/vpcflowlogs/us-east-1/2021/12/23/166157441623_vpcflowlogs_us-east-1_fl-03fbf155728a27ded_20211223T0000Z_ce6176d8.log.gz
DEBUG: +++ DB Maintenance
```

This is because the VPCFlow's `get_date_last_log` method isn't considering the reparse parameter.
https://github.com/wazuh/wazuh/blob/f3d98710ff56e17052df872a936f7280a685b98c/wodles/aws/aws_s3.py#L1666-L1680

This should be fixed in order to standardize the way the different types of buckets work.

## Tasks
- [x] Fix the reparse functionality for VPCFlow
- [x] Fix the reparse functionality for Config
- [x] Test in a manager
- [ ] Add entry to the changelog if necessary

**Comment by noise-kngdm** [comment]
## Issue update
While working on the issue we realized that the `Config` module had the same problem. Since the fixes are very similar, we decided to include both fixes in the branch created for this issue. 

```
DEBUG: ++ Found new log: AWSLogs/166157441623/Config/us-east-1/2021/11/9/09/ConfigHistory/166157441623_Config_us-east-1_ConfigHistory_AWS::Config::ResourceCompliance_20211109T004303Z_20211109T025123Z_1.json.gz
DEBUG: +++ DB Maintenance
DEBUG: +++ Marker: AWSLogs/166157441623/Config/us-east-1/2021/11/9
DEBUG: +++ No logs to process in bucket: 166157441623/us-east-1
DEBUG: +++ Marker: AWSLogs/166157441623/Config/us-east-1/2021/11/9
DEBUG: +++ No logs to process in bucket: 166157441623/us-east-1
DEBUG: +++ Marker: AWSLogs/166157441623/Config/us-east-1/2021/11/9
.
.
.
DEBUG: +++ No logs to process in bucket: 166157441623/us-east-1
DEBUG: +++ Marker: AWSLogs/166157441623/Config/us-east-1/2021/11/9
DEBUG: +++ No logs to process in bucket: 166157441623/us-east-1
DEBUG: +++ DB Maintenance
```

### Fixing --reparse in VPCFlow
The problem with the `--reparse` option in the VPCFlow module was that the use of the reparse parameter wasn't being considered when creating the list of days that should be used to make the requests to AWS.
https://github.com/wazuh/wazuh/blob/5408c25220ba7b1ecbeb3872065c997b6e1d5f10/wodles/aws/aws_s3.py#L1666-L1680

Also, it was not using the date passed as parameter to generate the requests, and it was using the one set as `only_logs_after` instead. That works for most of the modules, but not for `VPCFlow` and `Config`, which have a different behavior.
https://github.com/wazuh/wazuh/blob/5408c25220ba7b1ecbeb3872065c997b6e1d5f10/wodles/aws/aws_s3.py#L1760-L1767

### Fixing --reparse in Config
With `Config`, the problem was only with the date that was being used to generate the requests.
https://github.com/wazuh/wazuh/blob/5408c25220ba7b1ecbeb3872065c997b6e1d5f10/wodles/aws/aws_s3.py#L1274-L1280
