### ISSUE TITLE
Fix `Psutil` error in CentOS6 (GLIBC) at the precompiled level

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#11514]
## Description

In this issue, we are going to try to fix the problem with `Psutil` on CentOS 6 with x86 architecture. The problem with this dependency is that it makes use of GLIBC in its 2.13 version, however, the images we use to generate our Python package do not have this dependency.

```
14:54:04  2021/11/18 17:54:04 wazuh-modulesd: WARNING: The <ignore_time> tag at module 'vulnerability-detector' is deprecated for version newer than 4.3.
14:54:04  Traceback (most recent call last):
14:54:04    File "/var/ossec/framework/scripts/wazuh-clusterd.py", line 13, in <module>
14:54:04      from psutil import Process
14:54:04    File "/var/ossec/framework/python/lib/python3.9/site-packages/psutil/__init__.py", line 101, in <module>
14:54:04      from . import _pslinux as _psplatform
14:54:04    File "/var/ossec/framework/python/lib/python3.9/site-packages/psutil/_pslinux.py", line 26, in <module>
14:54:04      from . import _psutil_linux as cext
14:54:04  ImportError: /lib64/libc.so.6: version `GLIBC_2.13' not found (required by /var/ossec/framework/python/lib/python3.9/site-packages/psutil/_psutil_linux.cpython-39-x86_64-linux-gnu.so)
```

It is possible that the solution to this error is to add this version to the `x86` image. The tests will be done on a CentOS 6 vanilla.

**Comment by AdriiiPRodri** [comment]
## Status update

We have discarded that the problem is in the images used to generate the Python package. We discarded both the local image and the image used by Jenkins. Both images give the same result when querying GLIBC:

```
[root@2c4eb0a937c4 /]# strings /lib64/libc.so.6 |grep GLIBC_
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_PRIVATE
```

Investigating the source code of Psutil in its version 5.7.0 we see the following piece of code:

https://github.com/giampaolo/psutil/blob/f2e0c98ec0348810afe0e12347991438123c86f1/psutil/_psutil_linux.c#L45-L49

Where version 2.13 onwards is explicitly verified. This piece of code disappears in version 5.8.0. So the next step will be to upgrade to 5.8.0 and check if the error persists.

**Comment by AdriiiPRodri** [comment]
## Status update

As we indicated in the previous comment, after doing several tests we have determined that the error does not occur with version 5.8.0 of Psutil.

We have also verified that after upgrading this dependency to 5.8.0, Wazuh continues to work as it should. The API and Cluster processes have not been affected:

```
[root@ca65682c1fd7 /]# /var/ossec/framework/python/bin/pip3 freeze | grep psutil
psutil==5.8.0

[root@ca65682c1fd7 /]# ps -edf ww
UID        PID  PPID  C STIME TTY      STAT   TIME CMD
root         1     0  0 10:37 pts/0    Ss     0:00 bash
wazuh     7771     1 82 10:52 ?        Sl     0:08 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
root      7811     1  1 10:52 ?        Sl     0:00 /var/ossec/bin/wazuh-authd
wazuh     7828     1  4 10:52 ?        Sl     0:00 /var/ossec/bin/wazuh-db
wazuh     7842  7771  0 10:52 ?        S      0:00 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh     7845  7771  0 10:52 ?        S      0:00 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
root      7858     1  0 10:52 ?        Sl     0:00 /var/ossec/bin/wazuh-execd
wazuh     7870     1 13 10:52 ?        Sl     0:00 /var/ossec/bin/wazuh-analysisd
root      7880     1 21 10:52 ?        SNl    0:01 /var/ossec/bin/wazuh-syscheckd
wazuh     7892     1  0 10:52 ?        Sl     0:00 /var/ossec/bin/wazuh-remoted
root      7936     1  0 10:52 ?        Sl     0:00 /var/ossec/bin/wazuh-logcollector
wazuh     7960     1  0 10:52 ?        S      0:00 /var/ossec/bin/wazuh-monitord
root      8044     1  8 10:52 ?        Sl     0:00 /var/ossec/bin/wazuh-modulesd
wazuh     8264     1  5 10:52 ?        Sl     0:00 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
wazuh     8284  8264  0 10:52 ?        S      0:00 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
wazuh     8287  8264  0 10:52 ?        S      0:00 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
root      8686     1  0 10:52 pts/0    R+     0:00 ps -edf ww
```

### TODO

- [ ] Upgrade Psutil from 5.7.0 to 5.8.0 for ARM.
- [ ] Upgrade Psutil from 5.7.0 to 5.8.0 for X86.
- [ ] Upgrade Psutil from 5.7.0 to 5.8.0 for sources.
