### ISSUE TITLE
Fix AWS integration's Cisco Umbrella module

### ISSUE THREAD

**Issue by noise-kngdm** [wazuh/wazuh#11523]
| Affected integration |
|---|
| AWS Umbrella |

## Description

During the testing of #11428 we found a bug related to the AWS Umbrella integration. Since the Cisco Umbrella logs aren't stored like most of the services, that is, using a folder structure like `bucket/prefix/YYYY/MM/DD`, but instead Cisco Umbrella uploads the logs following the `bucket/prefix/YYYY-MM-DD-HH-MM.sgv` format, the logs aren't properly collected by the integration.

```
root@ca67f50829f8:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l iplogs -t cisco_umbrella -p dev -d2 -s 2021-dec-01
DEBUG: +++ Debug mode on - Level: 2
ERROR: No files were found in 'wazuh-aws-wodle-umbrella/iplogs/'. No logs will be processed.
root@ca67f50829f8:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l iplogs -t cisco_umbrella -p dev -d2    
DEBUG: +++ Debug mode on - Level: 2
ERROR: No files were found in 'wazuh-aws-wodle-umbrella/iplogs/'. No logs will be processed.
```

This problem is due to not having example logs available until #10841 was started for recent developments, like the one made for #9993.

This should be fixed in order to be able to support the use of Cisco Umbrella data with the AWS integration.

## Tasks
- [x] Fix the Umbrella integration
- [x] Test in a manager
- [x] Test in an agent
- [x] Add entry to the changelog if necessary

**Comment by noise-kngdm** [comment]
## Issue update

We found that the problem was that the `CiscoUmbrella` class inherits from `AWSCustomBucket` which has the `check_prefix` attribute set to `True`. That's because most of the custom buckets doesn't have a folder structure like `YYYY/MM/DD` and instead they store their files having the upload date as part of the filename. That was troublesome because files with another prefix would get processed too when trying to collect files from the root folder. However, with the Umbrella buckets there is no such problem, since they store their files with a `prefix/YYYY-MM-DD/YYYY-MM-DD-HH-mm-abcd-svg` format, being abcd a four characters random string.  

To fix this, we only had to change the value of the `check_prefix` attribute to false in the `CiscoUmbrella` constructor, right after calling the parent's one.


## Tests performed
To check that everything was working smoothly after the changes, we performed the following tests.

| Test | Status |
|---|---|
| Test only_logs_after | :green_circle: |
| Using path            | :green_circle: |
| Using reparse         | :green_circle: |
| Using discard_regex   | :green_circle: |
| Test iplogs   | :green_circle: |
| Test dnslogs   | :green_circle: |
| Test proxylogs   | :green_circle: |

### Test details
#### Test only_logs_after
Since the three types of Cisco Umbrella buckets use the same underlying logic, we will only need to test that the `only_logs_after` parameter for one of them.

Remove the `/var/ossec/wodles/aws/s3_cloudtrail.db` file and run the module using the following command to obtain every log from the Umbrella bucket for the given date.

##### First execution without specifying an only_logs_after value
Upload one log file to the bucket with the date of execution. Then execute the command. It should use as marker an string with the date of execution and collect the uploaded log.

Use the command:
```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l 166157441623/iplogs -t cisco_umbrella -p dev -d2
```

<details>
    <summary>Command output</summary>

	root@9fb0b9d12c89:/var/ossec/wodles/azure# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l 166157441623/iplogs -t cisco_umbrella -p dev -d2
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Marker: 166157441623/iplogs/2021-12-24/2021-12-24-00-00-ixla.csv.gz
	DEBUG: ++ Found new log: 166157441623/iplogs/2021-12-29/2021-12-29-00-00-ixla.csv.gz
	DEBUG: +++ DB Maintenance
	DEBUG: +++ DB Maintenance

</details>

###### Conclusions
The module worked as expected.

##### First execution specifying an only_logs_after value set in the past
Remove the database file and run the command the using `2021-Dec-20` date as `only_logs_after`. 3 logs should be collected and sent to analysisd.

Use the command:
```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l 166157441623/iplogs -t cisco_umbrella -s 2021-Dec-20 -p dev -d2
```

<details>
    <summary>Command output</summary>

	root@9fb0b9d12c89:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l 166157441623/iplogs -t cisco_umbrella -s 2021-Dec-20 -p dev -d2
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Table does not exist; create
	DEBUG: +++ Marker: 166157441623/iplogs/2021-12-20
	DEBUG: ++ Found new log: 166157441623/iplogs/2021-12-20/2021-12-20-00-00-xoal.csv.gz
	DEBUG: ++ Found new log: 166157441623/iplogs/2021-12-24/2021-12-24-00-00-ixla.csv.gz
	DEBUG: ++ Found new log: 166157441623/iplogs/2021-12-29/2021-12-29-00-00-ixla.csv.gz
	DEBUG: +++ DB Maintenance
	DEBUG: +++ DB Maintenance

</details>

Keep the database file and run the same command again to ensure no duplicate logs have been processed.

Use the command:
```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l 166157441623/iplogs -t cisco_umbrella -s 2021-Dec-20 -p dev -d2
```

<details>
    <summary>Command output</summary>

	root@9fb0b9d12c89:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l 166157441623/iplogs -t cisco_umbrella -s 2021-Dec-20 -p dev -d2
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Marker: 166157441623/iplogs/2021-12-29/2021-12-29-00-00-ixla.csv.gz
	DEBUG: +++ No logs to process in bucket: None/None
	DEBUG: +++ DB Maintenance

</details>

###### Conclusions
The module worked as expected.

##### Execute the command again with an only_logs_after value set earlier in the past

Run the module again, keeping the database file, using the `2021-Dec-01` date as `only_logs_after`. It should use as marker an string with the date of execution and not consider the `only_logs_after` value.

Use the command:
```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l 166157441623/iplogs -t cisco_umbrella -s 2021-Dec-01 -p dev -d2
```

<details>
    <summary>Command output</summary>

	root@9fb0b9d12c89:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l 166157441623/iplogs -t cisco_umbrella -s 2021-Dec-01 -p dev -d2
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Marker: 166157441623/iplogs/2021-12-29/2021-12-29-00-00-ixla.csv.gz
	DEBUG: +++ No logs to process in bucket: None/None
	DEBUG: +++ DB Maintenance

</details>

###### Conclusions
The module worked as expected.

##### Execute the module having a last key set and no only_logs_after value
Without removing the database, execute `sqlite3 /var/ossec/wodles/aws/s3_cloudtrail.db 'delete from cisco_umbrella where created_date in (select max(created_date) from cisco_umbrella);'`. This command will remove the more recents logs. Then execute the module without specifying an `only_logs_after` value. It should only collect the previously uploaded log.

Use the command:
```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l 166157441623/iplogs -t cisco_umbrella -p dev -d2
```

<details>
    <summary>Command output</summary>

	root@9fb0b9d12c89:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l 166157441623/iplogs -t cisco_umbrella -p dev -d2
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Marker: 166157441623/iplogs/2021-12-24/2021-12-24-00-00-ixla.csv.gz
	DEBUG: ++ Found new log: 166157441623/iplogs/2021-12-29/2021-12-29-00-00-ixla.csv.gz
	DEBUG: +++ DB Maintenance
	DEBUG: +++ DB Maintenance

</details>

###### Conclusions
The module worked as expected.

##### Execute the module having an only_logs_after later than the last key
The module should only fetch the logs corresponding to the days set by the only_logs_after date onwards, and it should skip the logs in between. 1 log should be processed.
Keeping the database file, execute `sqlite3 /var/ossec/wodles/aws/s3_cloudtrail.db 'delete from cisco_umbrella where created_date not in (select min(created_date) from cisco_umbrella);'`. 

Use the command:
```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l 166157441623/iplogs -t cisco_umbrella -p dev -d2 -s YYYY-MMM-DD
```
Being `YYYY-MMM-DD` the data corresponding to the date of execution.

<details>
    <summary>Command output</summary>

	root@9fb0b9d12c89:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l 166157441623/iplogs -t cisco_umbrella -p dev -d2 -s 2021-dec-29
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Marker: 166157441623/iplogs/2021-12-29
	DEBUG: ++ Found new log: 166157441623/iplogs/2021-12-29/2021-12-29-00-00-ixla.csv.gz
	DEBUG: +++ DB Maintenance
	DEBUG: +++ DB Maintenance

</details>

###### Conclusions
The module worked as expected.

##### Execute the module having an only_logs_after earlier than the last key
Without removing the database, execute `sqlite3 /var/ossec/wodles/aws/s3_cloudtrail.db 'delete from cisco_umbrella where created_date not in (select min(created_date) from cisco_umbrella);'`. This command will remove all the logs but the older ones. The execution of the module must result in collecting the last 3 logs, using as marker the last key.

Use the command:
```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l 166157441623/iplogs -t cisco_umbrella -p dev -d2 -s 2021-Dec-01 
```

<details>
    <summary>Command output</summary>

	root@9fb0b9d12c89:/var/ossec/wodles/aws# sqlite3 ./s3_cloudtrail.db 'delete from cisco_umbrella where log_key != "166157441623/2021-12-15/2021-12-15-00-00-asge.csv.gz"'
	root@9fb0b9d12c89:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l 166157441623/iplogs -t cisco_umbrella -p dev -d2 -s 2021-Dec-01 
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Marker: 166157441623/iplogs/2021-12-15/2021-12-15-00-00-asge.csv.gz
	DEBUG: ++ Found new log: 166157441623/iplogs/2021-12-20/2021-12-20-00-00-xoal.csv.gz
	DEBUG: ++ Found new log: 166157441623/iplogs/2021-12-24/2021-12-24-00-00-ixla.csv.gz
	DEBUG: ++ Found new log: 166157441623/iplogs/2021-12-29/2021-12-29-00-00-ixla.csv.gz
	DEBUG: +++ DB Maintenance
	DEBUG: +++ DB Maintenance

</details>

###### Conclusions
After executing the sqlite query, we detected that the `created_date` field of the database wasn't being properly set. We updated #11560 with the new findings to fix that problem for the Umbrella buckets too. After modifying the SQLite query with the one that can be seen in the command output we ensured that the module collected the expected logs.

##### Conclusions of the only_logs_after tests
The module is working as expected.

#### Using path

Run the module providing a `path` value to ensure only logs present in that path are being processed.

Use the command:
```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l test_prefix/166157441623/iplogs -t cisco_umbrella -s 2021-Dec-15 -p dev -d2
```

<details>
    <summary>Command output</summary>

	root@9fb0b9d12c89:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l test_prefix/166157441623/iplogs -t cisco_umbrella -s 2021-Dec-15 -p dev -d2
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Marker: test_prefix/166157441623/iplogs/2021-12-15
	DEBUG: ++ Found new log: test_prefix/166157441623/iplogs/2021-12-15/2021-12-15-00-00-abcd.csv.gz
	DEBUG: +++ DB Maintenance
	DEBUG: +++ DB Maintenance

</details>

##### Conclusions
The module worked as expected.

#### Using reparse

Remove the `/var/ossec/wodles/aws/s3_cloudtrail.db` file and run the module using the following command to obtain every log from the Umbrella bucket for the given date.

Use the command:
```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l 166157441623/iplogs -t cisco_umbrella -s 2021-Dec-20 -p dev -d2
```

<details>
    <summary>Command output</summary>

	root@9fb0b9d12c89:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l 166157441623/iplogs -t cisco_umbrella -s 2021-Dec-20 -p dev -d2
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Table does not exist; create
	DEBUG: +++ Marker: 166157441623/iplogs/2021-12-20
	DEBUG: ++ Found new log: 166157441623/iplogs/2021-12-20/2021-12-20-00-00-xoal.csv.gz
	DEBUG: ++ Found new log: 166157441623/iplogs/2021-12-24/2021-12-24-00-00-ixla.csv.gz
	DEBUG: ++ Found new log: 166157441623/iplogs/2021-12-29/2021-12-29-00-00-ixla.csv.gz
	DEBUG: +++ DB Maintenance
	DEBUG: +++ DB Maintenance

</details>

Run the module again, keeping the database file, using the same `only_logs_after` value and the `reparse` option. The same logs should be processed again, resulting in duplicated events.

Use the command:
```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l 166157441623/iplogs -t cisco_umbrella -s 2021-Dec-20 --reparse -p dev -d2
```

<details>
    <summary>Command output</summary>

	root@9fb0b9d12c89:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l 166157441623/iplogs -t cisco_umbrella -s 2021-Dec-20 --reparse -p dev -d2
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Marker: 166157441623/iplogs/2021-12-20
	DEBUG: ++ File previously processed, but reparse flag set: 166157441623/iplogs/2021-12-20/2021-12-20-00-00-xoal.csv.gz
	DEBUG: ++ Found new log: 166157441623/iplogs/2021-12-20/2021-12-20-00-00-xoal.csv.gz
	DEBUG: +++ File already marked complete, but reparse flag set: 166157441623/iplogs/2021-12-20/2021-12-20-00-00-xoal.csv.gz
	DEBUG: ++ File previously processed, but reparse flag set: 166157441623/iplogs/2021-12-24/2021-12-24-00-00-ixla.csv.gz
	DEBUG: ++ Found new log: 166157441623/iplogs/2021-12-24/2021-12-24-00-00-ixla.csv.gz
	DEBUG: +++ File already marked complete, but reparse flag set: 166157441623/iplogs/2021-12-24/2021-12-24-00-00-ixla.csv.gz
	DEBUG: ++ File previously processed, but reparse flag set: 166157441623/iplogs/2021-12-29/2021-12-29-00-00-ixla.csv.gz
	DEBUG: ++ Found new log: 166157441623/iplogs/2021-12-29/2021-12-29-00-00-ixla.csv.gz
	DEBUG: +++ File already marked complete, but reparse flag set: 166157441623/iplogs/2021-12-29/2021-12-29-00-00-ixla.csv.gz
	DEBUG: +++ DB Maintenance
	DEBUG: +++ DB Maintenance

</details>

##### Conclusions
The module worked as expected.

#### Using discard_regex
The output should show that some events are being skipped depending on the `discard-field` and `discard-regex` used.
Remove the database file and then use the command:
```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l 166157441623/iplogs -t cisco_umbrella -s 2021-dec-01 --discard-field identity --discard-regex 'TheComputerName' -p dev -d2
```

<details>
    <summary>Command output</summary>

	root@9fb0b9d12c89:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l 166157441623/iplogs -t cisco_umbrella -s 2021-dec-01 --discard-field identity --discard-regex 'TheComputerName' -p dev -d2
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Table does not exist; create
	DEBUG: +++ Marker: 166157441623/iplogs/2021-12-01
	DEBUG: ++ Found new log: 166157441623/iplogs/2021-12-01/2021-12-01-00-00-xyzs.csv.gz
	DEBUG: +++ The "TheComputerName" regex found a match in the "identity" field. The event will be skipped.
	DEBUG: +++ The "TheComputerName" regex found a match in the "identity" field. The event will be skipped.
	DEBUG: ++ Found new log: 166157441623/iplogs/2021-12-15/2021-12-15-00-00-asge.csv.gz
	DEBUG: +++ The "TheComputerName" regex found a match in the "identity" field. The event will be skipped.
	DEBUG: +++ The "TheComputerName" regex found a match in the "identity" field. The event will be skipped.
	DEBUG: ++ Found new log: 166157441623/iplogs/2021-12-20/2021-12-20-00-00-xoal.csv.gz
	DEBUG: +++ The "TheComputerName" regex found a match in the "identity" field. The event will be skipped.
	DEBUG: +++ The "TheComputerName" regex found a match in the "identity" field. The event will be skipped.
	DEBUG: ++ Found new log: 166157441623/iplogs/2021-12-24/2021-12-24-00-00-ixla.csv.gz
	DEBUG: +++ The "TheComputerName" regex found a match in the "identity" field. The event will be skipped.
	DEBUG: +++ The "TheComputerName" regex found a match in the "identity" field. The event will be skipped.
	DEBUG: ++ Found new log: 166157441623/iplogs/2021-12-29/2021-12-29-00-00-ixla.csv.gz
	DEBUG: +++ The "TheComputerName" regex found a match in the "identity" field. The event will be skipped.
	DEBUG: +++ The "TheComputerName" regex found a match in the "identity" field. The event will be skipped.
	DEBUG: +++ DB Maintenance
	DEBUG: +++ DB Maintenance

</details>

##### Conclusions
The module worked as expected.

#### Test iplogs
This command should only fetch `iplogs`.
Use the command:
```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l 166157441623/iplogs -t cisco_umbrella -s 2021-Dec-20 -p dev -d2
```

<details>
    <summary>Command output</summary>

	root@9fb0b9d12c89:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l 166157441623/iplogs -t cisco_umbrella -s 2021-Dec-20 -p dev -d2

	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Table does not exist; create
	DEBUG: +++ Marker: 166157441623/iplogs/2021-12-20
	DEBUG: ++ Found new log: 166157441623/iplogs/2021-12-20/2021-12-20-00-00-xoal.csv.gz
	DEBUG: ++ Found new log: 166157441623/iplogs/2021-12-24/2021-12-24-00-00-ixla.csv.gz
	DEBUG: ++ Found new log: 166157441623/iplogs/2021-12-29/2021-12-29-00-00-ixla.csv.gz
	DEBUG: +++ DB Maintenance
	DEBUG: +++ DB Maintenance

</details>

##### Conclusions
The module worked as expected.

#### Test proxylogs
This command should only fetch `proxylogs`.
Use the command:
```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l 166157441623/proxylogs -t cisco_umbrella -s 2021-Dec-15 -p dev -d2
```

<details>
    <summary>Command output</summary>

	root@9fb0b9d12c89:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l 166157441623/proxylogs -t cisco_umbrella -s 2021-Dec-15 -p dev -d2
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Marker: 166157441623/proxylogs/2021-12-15
	DEBUG: ++ Found new log: 166157441623/proxylogs/2021-12-15/2021-12-15-00-00-xjia.csv.gz
	DEBUG: +++ DB Maintenance
	DEBUG: +++ DB Maintenance

</details>

##### Conclusions
The module worked as expected.

#### Test dnslogs
This command should only fetch `dnslogs`.
Use the command:
```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l 166157441623/dnslogs -t cisco_umbrella -s 2021-Dec-15 -p dev -d2
```

<details>
    <summary>Command output</summary>

	root@9fb0b9d12c89:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-umbrella -l 166157441623/dnslogs -t cisco_umbrella -s 2021-Dec-15 -p dev -d2
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Marker: 166157441623/dnslogs/2021-12-15
	DEBUG: ++ Found new log: 166157441623/dnslogs/2021-12-15/2021-12-15-00-00-ioxa.csv
	DEBUG: +++ DB Maintenance
	DEBUG: +++ DB Maintenance
</details>

##### Conclusions
The module worked as expected.
