### ISSUE TITLE
Remove unnecessary DB queries from the AWS integration

### ISSUE THREAD

**Issue by noise-kngdm** [wazuh/wazuh#11561]
## Description
During the testing of #11428 we discovered that the `ALB`, `CLB` and `NLB` modules doesn't show any message telling that the `--reparse` option is being used.

<details><summary>Using the reparse option with CLB</summary>

	root@42453d0af7b0:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-clb -t clb -s 2021-NOV-09 --reparse -p dev -d2
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Working on 166157441623 - us-west-1
	DEBUG: +++ Marker: AWSLogs/166157441623/elasticloadbalancing/us-west-1/2021/11/09
	DEBUG: ++ Found new log: AWSLogs/166157441623/elasticloadbalancing/us-west-1/2021/11/09/166157441623_elasticloadbalancing_us-west-1_fram-dev-APIClassi-TCDBB3LRKY97_20211109T1735Z_18.144.142.112_2helnha7.log
	DEBUG: ++ Found new log: AWSLogs/166157441623/elasticloadbalancing/us-west-1/2021/11/10/166157441623_elasticloadbalancing_us-west-1_fram-dev-APIClassi-TCDBB3LRKY97_20211110T1735Z_18.144.142.112_2helnha7.log
	DEBUG: ++ Found new log: AWSLogs/166157441623/elasticloadbalancing/us-west-1/2021/11/11/166157441623_elasticloadbalancing_us-west-1_fram-dev-APIClassi-TCDBB3LRKY97_20211111T1735Z_18.144.142.112_2helnha7.log
	DEBUG: ++ Found new log: AWSLogs/166157441623/elasticloadbalancing/us-west-1/2021/11/12/166157441623_elasticloadbalancing_us-west-1_fram-dev-APIClassi-TCDBB3LRKY97_20211112T1735Z_18.144.142.112_2helnha7.log
	DEBUG: ++ Found new log: AWSLogs/166157441623/elasticloadbalancing/us-west-1/2021/12/23/166157441623_elasticloadbalancing_us-west-1_fram-dev-APIClassi-TCDBB3LRKY97_20211223T1735Z_18.144.142.112_2helnha7.log
	DEBUG: +++ DB Maintenance
	DEBUG: +++ DB Maintenance

</details>

On the other hand, the rest of the modules that support the `--reparse` option, show an output similar to the following:

<details><summary>Using the reparse option with Cloudtrail</summary>

	root@42453d0af7b0:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-cloudtrail -t cloudtrail -s 2021-NOV-21 --reparse -p dev -d2
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Working on 166157441623 - us-west-1
	DEBUG: +++ Marker: AWSLogs/166157441623/CloudTrail/us-west-1/2021/11/21
	DEBUG: ++ File previously processed, but reparse flag set: AWSLogs/166157441623/CloudTrail/us-west-1/2021/11/21/166157441623_CloudTrail_us-west-1_20211121T0000Z_rUQtGNUqmrPZMCnu.json.gz
	DEBUG: ++ Found new log: AWSLogs/166157441623/CloudTrail/us-west-1/2021/11/21/166157441623_CloudTrail_us-west-1_20211121T0000Z_rUQtGNUqmrPZMCnu.json.gz
	DEBUG: +++ File already marked complete, but reparse flag set: AWSLogs/166157441623/CloudTrail/us-west-1/2021/11/21/166157441623_CloudTrail_us-west-1_20211121T0000Z_rUQtGNUqmrPZMCnu.json.gz
	DEBUG: ++ File previously processed, but reparse flag set: AWSLogs/166157441623/CloudTrail/us-west-1/2021/11/22/166157441623_CloudTrail_us-west-1_20211122T0000Z_rUQtGNUqmrPZMCnu.json.gz
	DEBUG: ++ Found new log: AWSLogs/166157441623/CloudTrail/us-west-1/2021/11/22/166157441623_CloudTrail_us-west-1_20211122T0000Z_rUQtGNUqmrPZMCnu.json.gz
	DEBUG: +++ File already marked complete, but reparse flag set: AWSLogs/166157441623/CloudTrail/us-west-1/2021/11/22/166157441623_CloudTrail_us-west-1_20211122T0000Z_rUQtGNUqmrPZMCnu.json.gz
	DEBUG: ++ File previously processed, but reparse flag set: AWSLogs/166157441623/CloudTrail/us-west-1/2021/11/23/166157441623_CloudTrail_us-west-1_20211123T0000Z_rUQtGNUqmrPZMCnu.json.gz
	DEBUG: ++ Found new log: AWSLogs/166157441623/CloudTrail/us-west-1/2021/11/23/166157441623_CloudTrail_us-west-1_20211123T0000Z_rUQtGNUqmrPZMCnu.json.gz

</details>

The problem with that message is that it's being generated after making a request to the database in the `already_processed` method to check if a file with the same primary key exists in the database, and this is being made for every file pulled.

https://github.com/wazuh/wazuh/blob/f4ab39d1f70cd92f18606e229cbc90aec46aa39c/wodles/aws/aws_s3.py#L566-L569

Since the files collected shouldn't be double-checked with the database -which by default doesn't store all files collected but only the last 500- and processing them or not should only depend on their date, we propose removing that check and adding a generic message like `++ Reparse mode on` when executing the module with the reparse option.

## Tasks
- [ ] Remove the DB request made for every file to check if it has been processed or not
- [ ] Add a message when using the `--reparse` option
- [ ] Test in a manager
- [ ] Test in an agent
- [ ] Add entry to the changelog if necessary
