### ISSUE TITLE
Fix how the AWS module sets the `created_date` field in LB and Umbrella buckets

### ISSUE THREAD

**Issue by noise-kngdm** [wazuh/wazuh#11560]
| Affected integration |
|---|
| AWS ALB, CLB, NLB |

## Description
During the testing of #11428 we found a bug related with how the `ALB`, `NLB` and `CLB` buckets insert the processed files into the `s3_cloudtrail.db` database. For example, when executing the module as in the following code snippet:

```
root@ce731622bbf1:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-clb -t clb -p dev -d2 -s 2021-nov-01 
DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Table does not exist; create
DEBUG: +++ Working on 166157441623 - us-west-1
DEBUG: +++ Marker: AWSLogs/166157441623/elasticloadbalancing/us-west-1/2021/11/01
DEBUG: ++ Found new log: AWSLogs/166157441623/elasticloadbalancing/us-west-1/2021/11/09/166157441623_elasticloadbalancing_us-west-1_fram-dev-APIClassi-TCDBB3LRKY97_20211109T1735Z_18.144.142.112_2helnha7.log
DEBUG: ++ Found new log: AWSLogs/166157441623/elasticloadbalancing/us-west-1/2021/11/10/166157441623_elasticloadbalancing_us-west-1_fram-dev-APIClassi-TCDBB3LRKY97_20211110T1735Z_18.144.142.112_2helnha7.log
DEBUG: ++ Found new log: AWSLogs/166157441623/elasticloadbalancing/us-west-1/2021/11/11/166157441623_elasticloadbalancing_us-west-1_fram-dev-APIClassi-TCDBB3LRKY97_20211111T1735Z_18.144.142.112_2helnha7.log
DEBUG: ++ Found new log: AWSLogs/166157441623/elasticloadbalancing/us-west-1/2021/11/12/166157441623_elasticloadbalancing_us-west-1_fram-dev-APIClassi-TCDBB3LRKY97_20211112T1735Z_18.144.142.112_2helnha7.log
DEBUG: ++ Found new log: AWSLogs/166157441623/elasticloadbalancing/us-west-1/2021/12/23/166157441623_elasticloadbalancing_us-west-1_fram-dev-APIClassi-TCDBB3LRKY97_20211223T1735Z_18.144.142.112_2helnha7.log
DEBUG: +++ DB Maintenance
DEBUG: +++ DB Maintenance
```

The `created_date` is being set wrong in the database.

```
root@ce731622bbf1:/var/ossec/wodles/aws# sqlite3 s3_cloudtrail.db 'select log_key, created_date from clb'
AWSLogs/166157441623/elasticloadbalancing/us-west-1/2021/11/09/166157441623_elasticloadbalancing_us-west-1_fram-dev-APIClassi-TCDBB3LRKY97_20211109T1735Z_18.144.142.112_2helnha7.log|20211111
AWSLogs/166157441623/elasticloadbalancing/us-west-1/2021/11/10/166157441623_elasticloadbalancing_us-west-1_fram-dev-APIClassi-TCDBB3LRKY97_20211110T1735Z_18.144.142.112_2helnha7.log|20211111
AWSLogs/166157441623/elasticloadbalancing/us-west-1/2021/11/11/166157441623_elasticloadbalancing_us-west-1_fram-dev-APIClassi-TCDBB3LRKY97_20211111T1735Z_18.144.142.112_2helnha7.log|20211111
AWSLogs/166157441623/elasticloadbalancing/us-west-1/2021/11/12/166157441623_elasticloadbalancing_us-west-1_fram-dev-APIClassi-TCDBB3LRKY97_20211112T1735Z_18.144.142.112_2helnha7.log|20211112
AWSLogs/166157441623/elasticloadbalancing/us-west-1/2021/12/23/166157441623_elasticloadbalancing_us-west-1_fram-dev-APIClassi-TCDBB3LRKY97_20211223T1735Z_18.144.142.112_2helnha7.log|20211223
```

We should investigate why this happens and how to fix it. After reviewing the code, we think that this bug has no impact, since this field is only being used by the `VPCFlow` and `Config` buckets.

UPDATE:
While working on #11523 we detected that the Umbrella buckets had a similar problem. That should be fixed here too.
```
root@9fb0b9d12c89:/var/ossec/wodles/aws# sqlite3 ./s3_cloudtrail.db 'select log_key, created_date from cisco_umbrella'
166157441623/iplogs/2021-12-01/2021-12-01-00-00-xyzs.csv.gz|20211224
166157441623/iplogs/2021-12-15/2021-12-15-00-00-asge.csv.gz|20211224
166157441623/iplogs/2021-12-20/2021-12-20-00-00-xoal.csv.gz|20211224
166157441623/iplogs/2021-12-24/2021-12-24-00-00-ixla.csv.gz|20211224
166157441623/iplogs/2021-12-29/2021-12-29-00-00-ixla.csv.gz|20211229
```

## Tasks
- [x] Fix the bug in LB
- [x] Fix the bug in Umbrella
- [x] Test in a manager
- [x] Test in an agent
- [x] Add entry to the changelog if necessary

**Comment by robertogp21** [comment]
## Issue update

We have found that the regular expression used in `get_creation_date()` function is not matching the keys of the logs, so that the value of `name_regex` is always None. Therefore, the date that is saved in the database is the last time the log was modified.

https://github.com/wazuh/wazuh/blob/341697e3c592085f37583f5c0cf274531a69b45d/wodles/aws/aws_s3.py#L2079-L2085
