### ISSUE TITLE
GCloud Pub/Sub module is sending malformed JSON strings to `analysisd`

### ISSUE THREAD

**Issue by noise-kngdm** [wazuh/wazuh#11647]
| Affected integration |
|---|
| GCP Pub/Sub|

## Description
After the [integration tests](https://github.com/wazuh/wazuh-qa/issues/1880) made for the first release candidate of `v4.3.0`, it has been reported that the GCP Pub/Sub module is not working as expected after the changes added in https://github.com/wazuh/wazuh/pull/9279.

Even though a message recieved from Pub/Sub is in bytes format, it is not being properly decoded before sending it to `analysisd` neither in the code block that loops through the messages nor in the `format_msg` method.
https://github.com/wazuh/wazuh/blob/218787c1487ddf7a3f43d8c4727bd643c456ca8e/wodles/gcloud/pubsub/subscriber.py#L112-L116
https://github.com/wazuh/wazuh/blob/218787c1487ddf7a3f43d8c4727bd643c456ca8e/wodles/gcloud/integration.py#L39-L53

That makes `analysisd` generate the following error message when trying to decode the message.
```
2021/12/31 13:39:16 wazuh-analysisd[4790] json_decoder.c:390 at JSON_Decoder_Exec(): DEBUG: Decoding JSON: '{"integration": "gcp", "gcp": b''
2021/12/31 13:39:16 wazuh-analysisd[4790] json_decoder.c:395 at JSON_Decoder_Exec(): DEBUG: Malformed JSON string '{"integration": "gcp", "gcp": b'{"integration": "gcp", "gcp": {"team": "framework", "message": "Test message at Fri Dec 31 09:31:10 2021"}}'}'
```

This should be fixed as soon as possible.

## Tasks
- [ ] Fix the error
- [ ] Test in a manager
- [ ] Test in an agent
- [ ] Add entry to the changelog if necessary

**Comment by noise-kngdm** [comment]
## Issue update
We fixed the error by decoding the string before formatting it in the `format_msg` method.

https://github.com/wazuh/wazuh/blob/7b7c3f8383e57be7c6f1ce28fecede0222c703a3/wodles/gcloud/pubsub/subscriber.py#L113

Now, after executing the module with a populated topic we can see in the `ossec.log` file that the messages are being decode by `analysisd` with no problem.

<details><summary>Execution of the Pub/Sub module</summary>

	root@ad0eb89e1411:/var/ossec/logs# /var/ossec/wodles/gcloud/gcloud -p wazuh-dev-258815 -s test_subscription -c /var/ossec/wodles/gcloud/credentials.json -T pubsub -m 10 -t 16 -l1
	gcloud_wodle - DEBUG - Setting 16 threads to pull 10 messages in total
	gcloud_wodle - DEBUG - Processing event: {"integration": "gcp", "gcp": {"team": "framework", "message": "Test message at Fri Dec 31 14:22:50 2021"}}
	gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"team": "framework", "message": "Test message at Fri Dec 31 14:22:50 2021"}}'"
	gcloud_wodle - DEBUG - Processing event: {"integration": "gcp", "gcp": {"team": "framework", "message": "Test message at Fri Dec 31 14:22:52 2021"}}
	gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"team": "framework", "message": "Test message at Fri Dec 31 14:22:52 2021"}}'"
	gcloud_wodle - DEBUG - Processing event: {"integration": "gcp", "gcp": {"team": "framework", "message": "Test message at Fri Dec 31 14:22:52 2021"}}
	gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"team": "framework", "message": "Test message at Fri Dec 31 14:22:52 2021"}}'"
	gcloud_wodle - DEBUG - Processing event: {"integration": "gcp", "gcp": {"team": "framework", "message": "Test message at Fri Dec 31 14:22:52 2021"}}
	gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"team": "framework", "message": "Test message at Fri Dec 31 14:22:52 2021"}}'"
	gcloud_wodle - DEBUG - Processing event: {"integration": "gcp", "gcp": {"team": "framework", "message": "Test message at Fri Dec 31 14:22:52 2021"}}
	gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"team": "framework", "message": "Test message at Fri Dec 31 14:22:52 2021"}}'"
	gcloud_wodle - DEBUG - Processing event: {"integration": "gcp", "gcp": {"team": "framework", "message": "Test message at Fri Dec 31 14:22:52 2021"}}
	gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"team": "framework", "message": "Test message at Fri Dec 31 14:22:52 2021"}}'"
	gcloud_wodle - DEBUG - Processing event: {"integration": "gcp", "gcp": {"team": "framework", "message": "Test message at Fri Dec 31 14:22:52 2021"}}
	gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"team": "framework", "message": "Test message at Fri Dec 31 14:22:52 2021"}}'"
	gcloud_wodle - DEBUG - Processing event: {"integration": "gcp", "gcp": {"team": "framework", "message": "Test message at Fri Dec 31 14:22:52 2021"}}
	gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"team": "framework", "message": "Test message at Fri Dec 31 14:22:52 2021"}}'"
	gcloud_wodle - DEBUG - Processing event: {"integration": "gcp", "gcp": {"team": "framework", "message": "Test message at Fri Dec 31 14:22:52 2021"}}
	gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"team": "framework", "message": "Test message at Fri Dec 31 14:22:52 2021"}}'"
	gcloud_wodle - DEBUG - Processing event: {"integration": "gcp", "gcp": {"team": "framework", "message": "Test message at Fri Dec 31 14:22:52 2021"}}
	gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"team": "framework", "message": "Test message at Fri Dec 31 14:22:52 2021"}}'"
	gcloud_wodle - INFO - Received and acknowledged 10 messages
</details>


```
2021/12/31 14:25:19 wazuh-remoted[8978] state.c:59 at rem_write_state(): DEBUG: Updating state file.
2021/12/31 14:25:19 wazuh-analysisd[8784] json_decoder.c:390 at JSON_Decoder_Exec(): DEBUG: Decoding JSON: '{"integration": "gcp", "gcp": {"'
2021/12/31 14:25:19 wazuh-analysisd[8784] json_decoder.c:390 at JSON_Decoder_Exec(): DEBUG: Decoding JSON: '{"integration": "gcp", "gcp": {"'
2021/12/31 14:25:19 wazuh-analysisd[8784] json_decoder.c:390 at JSON_Decoder_Exec(): DEBUG: Decoding JSON: '{"integration": "gcp", "gcp": {"'
2021/12/31 14:25:19 wazuh-analysisd[8784] json_decoder.c:390 at JSON_Decoder_Exec(): DEBUG: Decoding JSON: '{"integration": "gcp", "gcp": {"'
2021/12/31 14:25:19 wazuh-analysisd[8784] json_decoder.c:390 at JSON_Decoder_Exec(): DEBUG: Decoding JSON: '{"integration": "gcp", "gcp": {"'
2021/12/31 14:25:19 wazuh-analysisd[8784] json_decoder.c:390 at JSON_Decoder_Exec(): DEBUG: Decoding JSON: '{"integration": "gcp", "gcp": {"'
2021/12/31 14:25:19 wazuh-analysisd[8784] json_decoder.c:390 at JSON_Decoder_Exec(): DEBUG: Decoding JSON: '{"integration": "gcp", "gcp": {"'
2021/12/31 14:25:19 wazuh-analysisd[8784] json_decoder.c:390 at JSON_Decoder_Exec(): DEBUG: Decoding JSON: '{"integration": "gcp", "gcp": {"'
2021/12/31 14:25:19 wazuh-analysisd[8784] json_decoder.c:390 at JSON_Decoder_Exec(): DEBUG: Decoding JSON: '{"integration": "gcp", "gcp": {"'
2021/12/31 14:25:19 wazuh-analysisd[8784] json_decoder.c:390 at JSON_Decoder_Exec(): DEBUG: Decoding JSON: '{"integration": "gcp", "gcp": {"'
2021/12/31 14:25:19 wazuh-remoted[8978] manager.c:677 at c_files(): DEBUG: Updating shared files sums.

```

**Comment by snaow** [comment]
Identified and reported by QA Team at: https://github.com/wazuh/wazuh-qa/issues/2369
