### ISSUE TITLE
Engine component integration for MVP 

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh#11765]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0 | Engine | -  | - | - |

We need to integrate the engine components described in #11334 into a coherent program ready to run.

The initial version of the program will have command line arguments only as configuration. In future issues, we might address the configuration management needs of complex scenarios.

This program main purpose is to enable us testing the interaction between components and measuring resource usage related to the design choices made. 

All the options supported will be self documented using `-h | --help ` flags.

## Tasks
- [x] Command line argument parser
- [x] Integrate router/server
- [x] Integrate router/catalog
- [x] Integrate router/builder
- [x] Integrate builder/catalog
- [ ] QoL improvements to CMakelists
- [x] Add logging framework
