### ISSUE TITLE
DB maintenance method is not working in the AWS load balancer buckets

### ISSUE THREAD

**Issue by noise-kngdm** [wazuh/wazuh#11826]
| Component |
|--|
| AWS integration module |

## Description
While working on #10850, we realized that the DB maintenance isn't working as expected with the load balancer buckets -`NLB`, `ALB` and `CLB`-. The problem is that even though the load balancer buckets work in a very similar way to how the buckets that inherit from the `AWSLogsBucket` class work, the load balancer buckets were programmed to inherit from the `AWSCustomBucket` class, which is a sibling class with slightly different behavior.  

The problem that fact is causing is that the module is not removing old and unnecessary entries from the database, which is what the call to the `db_maintenance` method does. This means that the database of installations that work with the `ALB`, `NLB`, and `CLB` integrations will grow indefinitely when they shouldn't. That's because:
- The load balancer buckets store the filename of the processed logs in the database using the AWS account ID of the account where those logs are stored.
- The custom buckets store logs in the database using the AWS account ID of the client who executed the module. That account ID is stored in the `aws_account_id` attribute that can be seen in the following code snippet.
- When the load balancers call the `db_maintenance` method, they use the `aws_account_id` attribute to indicate the `aws_account_id` column, however, the account ID they should be using is the one passed as a parameter instead.
https://github.com/wazuh/wazuh/blob/0e2da8a7ed14c5f92889d54ea42a845a4b456f6b/wodles/aws/aws_s3.py#L2166-L2175  

The fix we suggest is overloading the `db_maintenance` method in the `AWSLBBucket` class using the one [defined in the `AWSBucket` class](https://github.com/wazuh/wazuh/blob/0e2da8a7ed14c5f92889d54ea42a845a4b456f6b/wodles/aws/aws_s3.py#L663-L681) as a reference.

## Tasks
- [x] Fix load balancers DB maintenance
- [x] Test fix in `ALB`
- [x] Test fix in `NLB`
- [x] Test fix in `CLB`
- [x] Add entry to the changelog
