### ISSUE TITLE
Standardize the use of `only_logs_after` in the AWS Inspector Classic integration

### ISSUE THREAD

**Issue by noise-kngdm** [wazuh/wazuh#11930]
| Affected integration |
|---|
| AWS Inspector |

## Description
During the testing of the AWS module made in #11775, we realized that the integration with AWS Inspector Classic is not working adequately. The module is not following the principles set for #9993, which state how the module works when using the `only_logs_after` parameter.

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">Behavior</th>
<th scope="col" class="org-left">Last key = None, only logs = None</th>
<th scope="col" class="org-left">Last key = None, only logs = 2021-01-01</th>
<th scope="col" class="org-left">Last key = 2021-01-01, only logs = 2021-05-01</th>
<th scope="col" class="org-left">Last key = 2021-05-01, only logs = None</th>
<th scope="col" class="org-left">Last key = 2021-05-01, only logs = 2021-01-01</th>

</tr>
</thead>

<tbody>

<tr>
<td class="org-left"><b><b>Inspector</b></b></td>
<td class="org-left">Process todays logs. :green_circle:</td>
<td class="org-left">Process from 2021-01-01 until today. :green_circle:</td>
<td class="org-left"><b>Starts from 2021-01-01.</b> :red_circle:</td>
<td class="org-left">Starts from 2021-05-01. :green_circle:</td>
<td class="org-left">Starts from 2021-05-01. :green_circle:</td>
</tr>

<tr>
<td class="org-left"><b><b>Desired</b></b></td>
<td class="org-left"><b><b>Process todays logs.</b></b></td>
<td class="org-left"><b><b>Process from 2021-01-01 until today.</b></b></td>
<td class="org-left"><b><b>Starts from 2021-05-01.</b></b></td>
<td class="org-left"><b><b>Starts from 2021-05-01.</b></b></td>
<td class="org-left"><b><b>Starts from 2021-05-01 or process every log that had not been processed yet after 2021-01-01, skip the rest.</b></b></td>
</tr>
</tbody>
</table>  

When executing the module having a last key set in the past and specifying an `only_logs_after` parameter later in time, instead of using the specified `only_logs_after` parameter, the module uses the last key's date, resulting in processing unwanted findings. Since the module is not very informative, we had to manually edit the script to print the date that was being passed to the AWS API to realize this is happening.
```
root@10eede02c138:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -sr inspector -d 2 -s 2022-jan-24 -p dev -r us-east-1
DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Getting alerts from "us-east-1" region.
2022-01-03 00:00:00
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
DEBUG: +++ Processing new events from us-east-1 region
```

This should be fixed, and the rest of the cases should be reviewed too.

## Tasks
- [x] Fix the problem.
- [x] Test in a manager.
- [x] Update the documentation if necessary.
- [x] Add entry to the changelog if necessary.

**Comment by noise-kngdm** [comment]
## Issue update
We have finished with the fix, but before submitting a PR we have decided to add new debug messages to the module in order to better test it in the next release candidates, since as of now the module doesn't shows any useful information in debug mode 2.
Once we are done with that we will test the changes and publish the PR.

**Comment by noise-kngdm** [comment]
## Issue update
We have already finished with the changes to the module, and we also tested that it is working fine after all the changes it underwent.

### Test performed

Remove the `/var/ossec/wodles/aws/aws_services.db` file and run the module using the following command to obtain every finding log group for the given date.

#### First execution without specifying an only_logs_after value

Use the command: 
```
/var/ossec/wodles/aws/aws-s3 -sr inspector -d 2 -p dev -r us-east-1

```

Unless a new assessment run was executed in the same date, no log should be collected.

<details>
    <summary>Command output</summary>

	root@5639afb74f6a:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -sr inspector -d 2 -p dev -r us-east-1
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Getting alerts from "us-east-1" region.
	DEBUG: +++ Table does not exist; create
	DEBUG: +++ Listing findings starting from 2022-01-26 00:00:00
	DEBUG: +++ 117 events collected and processed in us-east-1

</details>

##### Conclusions
Only findings from the execution date onwards were collected, so the module is working as expected.

#### First execution specifying an only_logs_after value set in the past
Remove the database file and run the command specifying the date of the second assessment run. All events from that date onwards should be collected.

Use the command:
```
/var/ossec/wodles/aws/aws-s3 -sr inspector -d 2 -s YYYY-MMM-DD -p dev -r us-east-1
```

<details>
    <summary>Command output</summary>

	root@5639afb74f6a:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -sr inspector -d 2 -s 2022-Jan-14 -p dev -r us-east-1
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Getting alerts from "us-east-1" region.
	DEBUG: +++ Table does not exist; create
	DEBUG: +++ Listing findings starting from 2022-01-14 00:00:00
	DEBUG: +++ 438 events collected and processed in us-east-1

</details>

Keep the database file and run the same command again to ensure no duplicate logs are processed. Use the same `only_logs_after` parameter.

Use the command 
```
/var/ossec/wodles/aws/aws-s3 -sr inspector -d 2 -s YYYY-MMM-DD -p dev -r us-east-1
```

<details>
    <summary>Command output</summary>

	root@5639afb74f6a:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -sr inspector -d 2 -s 2022-Jan-14 -p dev -r us-east-1
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Getting alerts from "us-east-1" region.
	DEBUG: +++ Listing findings starting from 2022-01-26 12:35:46.605239
	DEBUG: +++ There are no new events in the "us-east-1" region

</details>

##### Conclusions
The module worked as expected.

#### Execute the command again with an only_logs_after value set earlier in the past

Run the module again, keeping the database file, using the date set for the first assessment run registered. The module should process no new log.

Use the command 
```
/var/ossec/wodles/aws/aws-s3 -sr inspector -d 2 -s YYYY-MMM-DD -p dev -r us-east-1
```

<details>
    <summary>Command output</summary>

	root@5639afb74f6a:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -sr inspector -d 2 -s 2022-Jan-01 -p dev -r us-east-1
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Getting alerts from "us-east-1" region.
	DEBUG: +++ Listing findings starting from 2022-01-26 12:36:22.642894
	DEBUG: +++ There are no new events in the "us-east-1" region

</details>

##### Conclusions
The module worked as expected.

#### Execute the module having a last key set and no only_logs_after value
Remove the database and execute the command `/var/ossec/wodles/aws/aws-s3 -sr inspector -d 2 -p dev -r us-east-1 -s 2022-Jan-03`, which is the date of the first assessment run.
Then execute `sqlite3 ./aws_services.db 'update aws_services set scan_date = "2022-01-04 00:00:00.0" where scan_date not in (select min(scan_date) from aws_services)'`. This will simulate an environment which has only collected the logs corresponding to the first assessment run.

Use the command:
```
/var/ossec/wodles/aws/aws-s3 -sr inspector -d 2 -p dev -r us-east-1
```
The module should collect all the logs starting from the `2022-Jan-03` without processing duplicates.

<details>
    <summary>Command output</summary>

	root@5639afb74f6a:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -sr inspector -d 2 -p dev -r us-east-1
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Getting alerts from "us-east-1" region.
	DEBUG: +++ Listing findings starting from 2022-01-04 00:00:00
	DEBUG: +++ 438 events collected and processed in us-east-1

</details>

##### Conclusions
The module worked as expected.

#### Execute the module having an only_logs_after later than the last key
Keeping the database file, execute `sqlite3 ./aws_services.db 'update aws_services set scan_date = "2022-01-04 00:00:00.0" where scan_date not in (select min(scan_date) from aws_services)'`.

Use the command:
```
/var/ossec/wodles/aws/aws-s3 -sr inspector -d 2 -s YYYY-MMM-DD -p dev -r us-east-1
```
Being `YYYY-MMM-DD` the date corresponding to the day following the execution date. No log should be collected.

<details>
    <summary>Command output</summary>

	root@5639afb74f6a:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -sr inspector -d 2 -s 2022-Jan-26 -p dev -r us-east-1
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Getting alerts from "us-east-1" region.
	DEBUG: +++ Listing findings starting from 2022-01-26 00:00:00
	DEBUG: +++ 117 events collected and processed in us-east-1

</details>

##### Conclusions
The module worked as expected.

#### Execute the module having an only_logs_after earlier than the last key
Keeping the database file, execute `sqlite3 ./aws_services.db 'update aws_services set scan_date = "2022-01-04 00:00:00.0" where scan_date not in (select min(scan_date) from aws_services)'`.
e
Use the command:
```
/var/ossec/wodles/aws/aws-s3 -sr inspector -d 2 -s 2021-Dec-01 -p dev -r us-east-1
```

It should only collect the logs starting from the first assessment run without processing it again.

<details>
    <summary>Command output</summary>

	root@5639afb74f6a:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -sr inspector -d 2 -s 2021-Dec-01 -p dev -r us-east-1
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Getting alerts from "us-east-1" region.
	DEBUG: +++ Listing findings starting from 2022-01-04 00:00:00
	DEBUG: +++ 438 events collected and processed in us-east-1

</details>

##### Conclusions
The module worked as expected.

### Using reparse
Without removing the databases file, execute the following command:

```
/var/ossec/wodles/aws/aws-s3 -sr inspector -d 2 -s 2021-Jan-03 -p dev -r us-east-1 --reparse
```

<details>
    <summary>Command output</summary>

	root@5639afb74f6a:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -sr inspector -d 2 -s 2021-Jan-03 -p dev -r us-east-1 --reparse
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Getting alerts from "us-east-1" region.
	DEBUG: +++ Listing findings starting from 2021-01-03 00:00:00
	DEBUG: +++ 549 events collected and processed in us-east-1

</details>

#### Conclusions
The module worked as expected, even though it is not showing information about the `reparse` option being set. That will be addressed in #11561.
