### ISSUE TITLE
Generate Google Cloud DNS sample logs for the GCP module

### ISSUE THREAD

**Issue by noise-kngdm** [wazuh/wazuh#12003]
| Affected integration |
|---|
| Google Cloud |

## Description
While working on wazuh/wazuh-documentation#4672, we realized that there is no [Google Cloud DNS](https://console.cloud.google.com/net-services/dns) service configured in our development environment, and we neither have sample logs available.

It is necessary to have Google Cloud DNS logs available to test the *Pub/Sub* integration and update the documentation.

## Tasks
- [x] Configure Google Cloud DNS
- [x] Get sample Google Cloud DNS logs
- [x] Test DNS logs with the Pub/Sub integration

**Comment by noise-kngdm** [comment]
## Issue update
We have finished generating and testing the GCP DNS logs we detailed the process followed below.

### Test integration
To finish with this issue we created the following resources:
- The `wazuh-dns-test` subscription.
- The `wazuh-dns-topic` topic, pulls messages from the `wazuh-dns-test` subscription.
- The `framework-dns-log-sink` sink that ingests the results obtained with the `resource.type = "dns_query"` query into the wazuh-dns-test subscription.

After having a populated subscription and topic and enabling the `logall` option, we executed the Pub/Sub integration:


```
/var/ossec/wodles/gcloud/gcloud -p wazuh-dev-project -s wazuh-dns-test  -c /var/ossec/wodles/gcloud/credentials.json -l 1 -T pubsub -m 3
```

<details><summary>Command output</summary>

	root@fc4e39794fcc:/var/ossec/wodles/gcloud# /var/ossec/wodles/gcloud/gcloud -p wazuh-dev-project -s wazuh-dns-test -c /var/ossec/wodles/gcloud/credentials.json -l 1 -T pubsub -m 3
	gcloud_wodle - DEBUG - Setting 1 thread to pull 3 messages in total
	gcloud_wodle - DEBUG - Processing event: {"integration": "gcp", "gcp": {"insertId":"v2ty3if2l38sf","jsonPayload":{"authAnswer":true,"protocol":"UDP","queryName":"logging.googleapis.com.","queryType":"A","rdata":"logging.googleapis.com.\t300\tIN\ta\t173.173.211.93","responseCode":"NOERROR","serverLatency":2,"sourceIP":"10.0.2.12","sourceNetwork":"default","vmInstanceId":6.6083749317140378e+18,"vmInstanceIdString":"6608374931714037409","vmInstanceName":"769054035614.framework-issue-12008","vmProjectId":"wazuh-dev-project","vmZoneName":"us-west1-b"},"logName":"projects/wazuh-dev-project/logs/dns.googleapis.com%2Fdns_queries","receiveTimestamp":"2022-02-01T08:57:42.51560097Z","resource":{"labels":{"location":"us-west1","project_id":"wazuh-dev-project","source_type":"gce-vm","target_name":"","target_type":"external"},"type":"dns_query"},"severity":"INFO","timestamp":"2022-02-01T08:57:42.134623486Z"}}
	gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"insertId":"v2ty3if2l38sf","jsonPayload":{"authAnswer":true,"protocol":"UDP","queryName":"logging.googleapis.com.","queryType":"A","rdata":"logging.googleapis.com.\\t300\\tIN\\ta\\t173.173.211.93","responseCode":"NOERROR","serverLatency":2,"sourceIP":"10.0.2.12","sourceNetwork":"default","vmInstanceId":6.6083749317140378e+18,"vmInstanceIdString":"6608374931714037409","vmInstanceName":"769054035614.framework-issue-12008","vmProjectId":"wazuh-dev-project","vmZoneName":"us-west1-b"},"logName":"projects/wazuh-dev-project/logs/dns.googleapis.com%2Fdns_queries","receiveTimestamp":"2022-02-01T08:57:42.51560097Z","resource":{"labels":{"location":"us-west1","project_id":"wazuh-dev-project","source_type":"gce-vm","target_name":"","target_type":"external"},"type":"dns_query"},"severity":"INFO","timestamp":"2022-02-01T08:57:42.134623486Z"}}'"
	gcloud_wodle - DEBUG - Processing event: {"integration": "gcp", "gcp": {"insertId":"v2ty3if2y5i7v","jsonPayload":{"authAnswer":true,"protocol":"UDP","queryName":"ci.wazuh.co.","queryType":"A","rdata":"","responseCode":"NXDOMAIN","serverLatency":25,"sourceIP":"10.0.2.12","sourceNetwork":"default","vmInstanceId":6.6083749317140378e+18,"vmInstanceIdString":"6608374931714037409","vmInstanceName":"769054035614.framework-issue-12008","vmProjectId":"wazuh-dev-project","vmZoneName":"us-west1-b"},"logName":"projects/wazuh-dev-project/logs/dns.googleapis.com%2Fdns_queries","receiveTimestamp":"2022-02-01T08:40:07.628110254Z","resource":{"labels":{"location":"us-west1","project_id":"wazuh-dev-project","source_type":"gce-vm","target_name":"","target_type":"external"},"type":"dns_query"},"severity":"NOTICE","timestamp":"2022-02-01T08:40:07.159617058Z"}}
	gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"insertId":"v2ty3if2y5i7v","jsonPayload":{"authAnswer":true,"protocol":"UDP","queryName":"ci.wazuh.co.","queryType":"A","rdata":"","responseCode":"NXDOMAIN","serverLatency":25,"sourceIP":"10.0.2.12","sourceNetwork":"default","vmInstanceId":6.6083749317140378e+18,"vmInstanceIdString":"6608374931714037409","vmInstanceName":"769054035614.framework-issue-12008","vmProjectId":"wazuh-dev-project","vmZoneName":"us-west1-b"},"logName":"projects/wazuh-dev-project/logs/dns.googleapis.com%2Fdns_queries","receiveTimestamp":"2022-02-01T08:40:07.628110254Z","resource":{"labels":{"location":"us-west1","project_id":"wazuh-dev-project","source_type":"gce-vm","target_name":"","target_type":"external"},"type":"dns_query"},"severity":"NOTICE","timestamp":"2022-02-01T08:40:07.159617058Z"}}'"
	gcloud_wodle - DEBUG - Processing event: {"integration": "gcp", "gcp": {"insertId":"v2ty3if2y5i81","jsonPayload":{"authAnswer":true,"protocol":"UDP","queryName":"ci.wazuh.co.c.wazuh-dev-project.internal.","queryType":"AAAA","rdata":"","responseCode":"NXDOMAIN","serverLatency":1,"sourceIP":"10.0.2.12","sourceNetwork":"default","vmInstanceId":6.6083749317140378e+18,"vmInstanceIdString":"6608374931714037409","vmInstanceName":"769054035614.framework-issue-12008","vmProjectId":"wazuh-dev-project","vmZoneName":"us-west1-b"},"logName":"projects/wazuh-dev-project/logs/dns.googleapis.com%2Fdns_queries","receiveTimestamp":"2022-02-01T08:40:07.628110254Z","resource":{"labels":{"location":"us-west1","project_id":"wazuh-dev-project","source_type":"gce-vm","target_name":"","target_type":"external"},"type":"dns_query"},"severity":"NOTICE","timestamp":"2022-02-01T08:40:07.163711237Z"}}
	gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"insertId":"v2ty3if2y5i81","jsonPayload":{"authAnswer":true,"protocol":"UDP","queryName":"ci.wazuh.co.c.wazuh-dev-project.internal.","queryType":"AAAA","rdata":"","responseCode":"NXDOMAIN","serverLatency":1,"sourceIP":"10.0.2.12","sourceNetwork":"default","vmInstanceId":6.6083749317140378e+18,"vmInstanceIdString":"6608374931714037409","vmInstanceName":"769054035614.framework-issue-12008","vmProjectId":"wazuh-dev-project","vmZoneName":"us-west1-b"},"logName":"projects/wazuh-dev-project/logs/dns.googleapis.com%2Fdns_queries","receiveTimestamp":"2022-02-01T08:40:07.628110254Z","resource":{"labels":{"location":"us-west1","project_id":"wazuh-dev-project","source_type":"gce-vm","target_name":"","target_type":"external"},"type":"dns_query"},"severity":"NOTICE","timestamp":"2022-02-01T08:40:07.163711237Z"}}'"
	gcloud_wodle - INFO - Received and acknowledged 3 messages

</details>

If we examine the `archives.log` file searching for the collected events, we can see that they were indeed sent to analysisd.

<details><summary>Contents of archives.log</summary>

	2022 Feb 01 08:57:50 fc4e39794fcc->Wazuh-GCloud {"integration": "gcp", "gcp": {"insertId":"v2ty3if2l38sf","jsonPayload":{"authAnswer":true,"protocol":"UDP","queryName":"logging.googleapis.com.","queryType":"A","rdata":"logging.googleapis.com.\t300\tIN\ta\t173.173.211.93","responseCode":"NOERROR","serverLatency":2,"sourceIP":"10.0.2.12","sourceNetwork":"default","vmInstanceId":6.6083749317140378e+18,"vmInstanceIdString":"6608374931714037409","vmInstanceName":"769054035614.framework-issue-12008","vmProjectId":"wazuh-dev-project","vmZoneName":"us-west1-b"},"logName":"projects/wazuh-dev-project/logs/dns.googleapis.com%2Fdns_queries","receiveTimestamp":"2022-02-01T08:57:42.51560097Z","resource":{"labels":{"location":"us-west1","project_id":"wazuh-dev-project","source_type":"gce-vm","target_name":"","target_type":"external"},"type":"dns_query"},"severity":"INFO","timestamp":"2022-02-01T08:57:42.134623486Z"}}
	2022 Feb 01 08:57:51 fc4e39794fcc->Wazuh-GCloud {"integration": "gcp", "gcp": {"insertId":"v2ty3if2y5i7v","jsonPayload":{"authAnswer":true,"protocol":"UDP","queryName":"ci.wazuh.co.","queryType":"A","rdata":"","responseCode":"NXDOMAIN","serverLatency":25,"sourceIP":"10.0.2.12","sourceNetwork":"default","vmInstanceId":6.6083749317140378e+18,"vmInstanceIdString":"6608374931714037409","vmInstanceName":"769054035614.framework-issue-12008","vmProjectId":"wazuh-dev-project","vmZoneName":"us-west1-b"},"logName":"projects/wazuh-dev-project/logs/dns.googleapis.com%2Fdns_queries","receiveTimestamp":"2022-02-01T08:40:07.628110254Z","resource":{"labels":{"location":"us-west1","project_id":"wazuh-dev-project","source_type":"gce-vm","target_name":"","target_type":"external"},"type":"dns_query"},"severity":"NOTICE","timestamp":"2022-02-01T08:40:07.159617058Z"}}
	2022 Feb 01 08:57:51 fc4e39794fcc->Wazuh-GCloud {"integration": "gcp", "gcp": {"insertId":"v2ty3if2y5i81","jsonPayload":{"authAnswer":true,"protocol":"UDP","queryName":"ci.wazuh.co.c.wazuh-dev-project.internal.","queryType":"AAAA","rdata":"","responseCode":"NXDOMAIN","serverLatency":1,"sourceIP":"10.0.2.12","sourceNetwork":"default","vmInstanceId":6.6083749317140378e+18,"vmInstanceIdString":"6608374931714037409","vmInstanceName":"769054035614.framework-issue-12008","vmProjectId":"wazuh-dev-project","vmZoneName":"us-west1-b"},"logName":"projects/wazuh-dev-project/logs/dns.googleapis.com%2Fdns_queries","receiveTimestamp":"2022-02-01T08:40:07.628110254Z","resource":{"labels":{"location":"us-west1","project_id":"wazuh-dev-project","source_type":"gce-vm","target_name":"","target_type":"external"},"type":"dns_query"},"severity":"NOTICE","timestamp":"2022-02-01T08:40:07.163711237Z"}}

</details>


Testing one of those logs with the `wazuh-logtest` tool shows the following output.
<details><summary>wazuh-logtest output</summary>

	Starting wazuh-logtest v4.4.0
	Type one log per line

	{"integration": "gcp", "gcp": {"insertId":"v2ty3if2l38sf","jsonPayload":{"authAnswer":true,"protocol":"UDP","queryName":"logging.googleapis.com.","queryType":"A","rdata":"logging.googleapis.com.\t300\tIN\ta\t173.173.211.93","responseCode":"NOERROR","serverLatency":2,"sourceIP":"10.0.2.12","sourceNetwork":"default","vmInstanceId":6.6083749317140378e+18,"vmInstanceIdString":"6608374931714037409","vmInstanceName":"769054035614.framework-issue-12008","vmProjectId":"wazuh-dev-project","vmZoneName":"us-west1-b"},"logName":"projects/wazuh-dev-project/logs/dns.googleapis.com%2Fdns_queries","receiveTimestamp":"2022-02-01T08:57:42.51560097Z","resource":{"labels":{"location":"us-west1","project_id":"wazuh-dev-project","source_type":"gce-vm","target_name":"","target_type":"external"},"type":"dns_query"},"severity":"INFO","timestamp":"2022-02-01T08:57:42.134623486Z"}}

	**Phase 1: Completed pre-decoding.

	**Phase 2: Completed decoding.
		name: 'json'
		gcp.insertId: 'v2ty3if2l38sf'
		gcp.jsonPayload.authAnswer: 'true'
		gcp.jsonPayload.protocol: 'UDP'
		gcp.jsonPayload.queryName: 'logging.googleapis.com.'
		gcp.jsonPayload.queryType: 'A'
		gcp.jsonPayload.rdata: 'logging.googleapis.com.	300	IN	a	173.173.211.93'
		gcp.jsonPayload.responseCode: 'NOERROR'
		gcp.jsonPayload.serverLatency: '2'
		gcp.jsonPayload.sourceIP: '10.0.2.12'
		gcp.jsonPayload.sourceNetwork: 'default'
		gcp.jsonPayload.vmInstanceId: '6608374931714037760.000000'
		gcp.jsonPayload.vmInstanceIdString: '6608374931714037409'
		gcp.jsonPayload.vmInstanceName: '769054035614.framework-issue-12008'
		gcp.jsonPayload.vmProjectId: 'wazuh-dev-project'
		gcp.jsonPayload.vmZoneName: 'us-west1-b'
		gcp.logName: 'projects/wazuh-dev-project/logs/dns.googleapis.com%2Fdns_queries'
		gcp.receiveTimestamp: '2022-02-01T08:57:42.51560097Z'
		gcp.resource.labels.location: 'us-west1'
		gcp.resource.labels.project_id: 'wazuh-dev-project'
		gcp.resource.labels.source_type: 'gce-vm'
		gcp.resource.labels.target_type: 'external'
		gcp.resource.type: 'dns_query'
		gcp.severity: 'INFO'
		gcp.timestamp: '2022-02-01T08:57:42.134623486Z'
		integration: 'gcp'

	**Phase 3: Completed filtering (rules).
		id: '65011'
		level: '2'
		description: 'GCP info event from VM 769054035614.framework-issue-12008 with source IP 10.0.2.12 from us-west1 with response code NOERROR.'
		groups: '['gcp']'
		firedtimes: '1'
		mail: 'False'

</details>

### Conclusions
After the results of the analysis, we can say that the integration with GCP DNS queries is working as expected.
