### ISSUE TITLE
Review AWS integration and adapt it to Python3.6

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#12237]
| Affected integration |
|---|
| AWS |

## Description

Review the AWS integration code and remove any python features that are not compatible with Python 3.6, such as the `:=` operator or the `list[type]` docstrings.

## Tasks
- [ ] Review and adapt the code.
- [ ] Test in an agent or manager using python3.6.
- [ ] Unit tests without failures. Updated if there are any relevant changes.
- [ ] Update the documentation if necessary.
- [ ] Add entry to the changelog if necessary.

**Comment by CarlosRS9** [comment]
# Status update

The code was updated to remove the `:=` operators which was the only thing that prevented the AWS module from being compatible with python 3.6

The introduced changes affect the following functions:
- `find_account_ids` and `build_s3_filter_args` from `AWSBucket` class.
- `build_s3_filter_args` from `AWSVPCFlowBucket` class.
- `load_information_from_file` from `AWSServerAccess` class.
- `get_alerts` from `AWSInspector` class
- `get_log_streams` from `AWSCloudWatchLogs` class.

As the changes have a large impact we are testing the module in detail.

**Comment by CarlosRS9** [comment]
# Testing Server Access

Remove the database file and run the command the using 2021-NOV-12 date as only_logs_after. 4 logs should be collected and sent to analysisd.

Use the command 
```
/var/ossec/wodles/aws/aws-s3.py -b wazuh-aws-wodle-access -t server_access -s 2021-NOV-12 -p dev -d2 | grep -v 'Skipping file with'
```

<details>
    <summary>Command output</summary>

	/var/ossec/wodles/aws/aws-s3.py -b wazuh-aws-wodle-access -t server_access -s 2021-NOV-12 -p dev -d2 | grep -v 'Skipping file with'
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Table does not exist; create
	DEBUG: +++ Marker: 2021-11-12
	DEBUG: ++ Found new log: 2021-11-12-09-11-26-B9F9F891E8D0EB13
	DEBUG: ++ Found new log: 2021-11-12-13-11-26-B9F9F891E8D0EB13
	DEBUG: ++ Found new log: 2021-11-15-09-12-25-F92E1554CC549BEE
	DEBUG: ++ Found new log: 2021-12-27-09-12-23-F92E1554CC549BEA
	DEBUG: ++ Found new log: 2022-01-25-09-12-23-F92E1554CC549BEX
	DEBUG: ++ Found new log: 2022-02-11-09-12-25-H99KY554CC549BEE
	DEBUG: +++ DB Maintenance
	DEBUG: +++ DB Maintenance
</details>

##### Conclusions
The module worked as expected.

**Comment by CarlosRS9** [comment]
# Testing Inspector

## Test details

### Test only_logs_after

Remove the `/var/ossec/wodles/aws/aws_services.db` file and run the module using the following command to obtain every finding log group for the given date.

#### First execution specifying an only_logs_after value set in the past
Remove the database file and run the command specifying the date of the last assessment run. All events from that date onwards should be collected.

Use the command:
```
/var/ossec/wodles/aws/aws-s3.py -sr inspector -d 2 -s YYYY-MMM-DD -p dev -r us-east-1
```

<details>
    <summary>Command output</summary>

	/var/ossec/wodles/aws/aws-s3.py -sr inspector -d 2 -s 2022-jan-03 -p dev -r us-east-1
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Getting alerts from "us-east-1" region.
	DEBUG: +++ Table does not exist; create
	DEBUG: +++ Listing findings starting from 2022-01-03 00:00:00
	DEBUG: +++ 549 events collected and processed in us-east-1
</details>

Keep the database file and run the same command again to ensure no duplicate logs are processed. Use the same `only_logs_after` parameter.

Use the command 
```
/var/ossec/wodles/aws/aws-s3.py -sr inspector -d 2 -s YYYY-MMM-DD -p dev -r us-east-1
```

<details>
    <summary>Command output</summary>

	/var/ossec/wodles/aws/aws-s3.py -sr inspector -d 2 -s 2022-jan-03 -p dev -r us-east-1
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Getting alerts from "us-east-1" region.
	DEBUG: +++ Listing findings starting from 2022-02-14 17:14:51.412335
	DEBUG: +++ There are no new events in the "us-east-1" region
</details>

##### Conclusions
The module worked as expected.

#### Execute the command again with an only_logs_after value set earlier in the past

Run the module again, keeping the database file, using the date set for the first assessment run registered. The module should process no new log.

Use the command 
```
/var/ossec/wodles/aws/aws-s3.py -sr inspector -d 2 -s YYYY-MMM-DD -p dev -r us-east-1
```

<details>
    <summary>Command output</summary>

	/var/ossec/wodles/aws/aws-s3.py -sr inspector -d 2 -s 2022-jan-01 -p dev -r us-east-1
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Getting alerts from "us-east-1" region.
	DEBUG: +++ Listing findings starting from 2022-02-14 17:16:02.832374
	DEBUG: +++ There are no new events in the "us-east-1" region
</details>

##### Conclusions
The module worked as expected.

#### Execute the module having a last key set and no only_logs_after value
Remove the database and execute the command `/var/ossec/wodles/aws/aws-s3.py -sr inspector -d 2 -p dev -r us-east-1 -s 2022-Jan-03`, which is the date of the first assessment run.
Then execute `sqlite3 ./aws_services.db 'delete from aws_services where scan_date != (SELECT min(scan_date) from aws_services);'`. This will simulate an environment which has only collected the logs corresponding to the first assessment run.

Use the command:
```
/var/ossec/wodles/aws/aws-s3.py -sr inspector -d 2 -p dev -r us-east-1
```
The module should collect all the logs starting from the `2022-Jan-03` without processing duplicates.

<details>
    <summary>Command output</summary>

	sqlite3 /var/ossec/wodles/aws/aws_services.db 'select * from aws_services'
	inspector|567970947422|us-east-1|2022-01-03 00:00:00.0
	/var/ossec/wodles/aws/aws-s3.py -sr inspector -d 2 -p dev -r us-east-1
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Getting alerts from "us-east-1" region.
	DEBUG: +++ Listing findings starting from 2022-01-03 00:00:00
	DEBUG: +++ 549 events collected and processed in us-east-1
</details>

##### Conclusions
The module worked as expected.

**Comment by CarlosRS9** [comment]
# Testing CloudWatch Logs

## Test details
Before starting these tests, a series of Cloudwatch Logs test events in a period of 14 days in the past until today must be uploaded to the `4_3_test`'s `test_stream` log stream.

### Test only_logs_after

Remove the `/var/ossec/wodles/aws/aws_services.db` file and run the module using the following command to obtain every log from the Cloudwatch Logs log group for the given date.



#### First execution without specifying an only_logs_after value

Use the command 
```
/var/ossec/wodles/aws/aws-s3.py -sr cloudwatchlogs -g 4_3_test -d 2 -p dev -r us-east-1
```

<details>
    <summary>Command output</summary>

	/var/ossec/wodles/aws/aws-s3.py -sr cloudwatchlogs -g 4_3_test -d 2 -p dev -r us-east-1
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Getting alerts from "us-east-1" region.
	DEBUG: only logs: None
	DEBUG: +++ Table does not exist; create
	DEBUG: Getting log streams for "4_3_test" log group
	DEBUG: Found "test_stream" log stream in 4_3_test
	DEBUG: Getting data from DB for log stream "test_stream" in log group "4_3_test"
	DEBUG: Token: "None", start_time: "None", end_time: "None"
	DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_3_test" using token "None", start_time "1644796800000" and end_time "None"
	DEBUG: Saving data for log group "4_3_test" and log stream "test_stream".
	DEBUG: The saved values are "{'token': 'f/36680194340169684017803161812123715926506285965634404351/s', 'start_time': 1644796800000, 'end_time': 1644796800000}"
	DEBUG: Purging the BD
	DEBUG: Getting log streams for "4_3_test" log group
	DEBUG: Found "test_stream" log stream in 4_3_test
	DEBUG: committing changes and closing the DB
</details>


##### Conclusions
The module only collected the logs uploaded the date of execution so it is working as expected.


#### First execution specifying an only_logs_after value set in the past
Remove the database file and run the command specifying a date set 5 days earlier in the past. All the logs between the date set by the `only_logs_after` parameter and the present day must be collected.

Use the command 
```
/var/ossec/wodles/aws/aws-s3.py -sr cloudwatchlogs -g 4_3_test -d 2 -s YYYY-MMM-DD -p dev -r us-east-1
```

<details>
    <summary>Command output</summary>

	/var/ossec/wodles/aws/aws-s3.py -sr cloudwatchlogs -g 4_3_test -d 2 -s 2022-jan-16 -p dev -r us-east-1
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Getting alerts from "us-east-1" region.
	DEBUG: only logs: 1642291200000
	DEBUG: Getting log streams for "4_3_test" log group
	DEBUG: Found "test_stream" log stream in 4_3_test
	DEBUG: Getting data from DB for log stream "test_stream" in log group "4_3_test"
	DEBUG: Token: "f/36680194340169684017803161812123715926506285965634404351/s", start_time: "1644796800000", end_time: "1644796800000"
	DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_3_test" using token "None", start_time "1642291200000" and end_time "1644796800000"
	DEBUG: +++ Sending events to Analysisd...
	DEBUG: The message is "Test log 5 - 2022-1-17 - 1642419404426"
	DEBUG: +++ Sending events to Analysisd...
	DEBUG: The message is "Test log 6 - 2022-1-17 - 1642419404427"
	DEBUG: +++ Sending events to Analysisd...
	DEBUG: The message is "Test log 7 - 2022-1-21 - 1642765328448"
	DEBUG: +++ Sending events to Analysisd...
	DEBUG: The message is "Test log 8 - 2022-1-21 - 1642765328449"
	DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_3_test" using token "f/36634891010743919584474076488460266823645439445062647808/s", start_time "1642291200000" and end_time "1644796800000"
	DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_3_test" using token "f/36680194340169684017803161812123715926506285965634404351/s", start_time "1644796800001" and end_time "None"
	DEBUG: Saving data for log group "4_3_test" and log stream "test_stream".
	DEBUG: The saved values are "{'token': 'f/36680194340169684017803161812123715926506285965634404351/s', 'start_time': 1642291200000, 'end_time': 1644796800001}"
	DEBUG: Some data already exists on DB for that key. Updating their values...
	DEBUG: Purging the BD
	DEBUG: Getting log streams for "4_3_test" log group
	DEBUG: Found "test_stream" log stream in 4_3_test
	DEBUG: committing changes and closing the DB
</details>

Keep the database file and run the same command again to ensure no duplicate logs are processed. Use the same `only_logs_after` parameter.

Use the command:
```
/var/ossec/wodles/aws/aws-s3.py -sr cloudwatchlogs -g 4_3_test -d 2 -s YYYY-MMM-DD -p dev -r us-east-1
```

<details>
    <summary>Command output</summary>

	/var/ossec/wodles/aws/aws-s3.py -sr cloudwatchlogs -g 4_3_test -d 2 -s 2022-jan-16 -p dev -r us-east-1
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Getting alerts from "us-east-1" region.
	DEBUG: only logs: 1642291200000
	DEBUG: Getting log streams for "4_3_test" log group
	DEBUG: Found "test_stream" log stream in 4_3_test
	DEBUG: Getting data from DB for log stream "test_stream" in log group "4_3_test"
	DEBUG: Token: "f/36680194340169684017803161812123715926506285965634404351/s", start_time: "1642291200000", end_time: "1644796800001"
	DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_3_test" using token "f/36680194340169684017803161812123715926506285965634404351/s", start_time "1644796800002" and end_time "None"
	DEBUG: Saving data for log group "4_3_test" and log stream "test_stream".
	DEBUG: The saved values are "{'token': 'f/36680194340169684017803161812123715926506285965634404351/s', 'start_time': 1642291200000, 'end_time': 1644796800002}"
	DEBUG: Some data already exists on DB for that key. Updating their values...
	DEBUG: Purging the BD
	DEBUG: Getting log streams for "4_3_test" log group
	DEBUG: Found "test_stream" log stream in 4_3_test
	DEBUG: committing changes and closing the DB
</details>


##### Conclusions
The module is working as expected.



#### Execute the command again with an only_logs_after value set earlier in the past

Run the module again, keeping the database file, using the date set 14 days earlier in the past than the execution time. The module should collect all logs between that date and the first log collected and skip the rest to avoid processing duplicates.

Use the command 
```
/var/ossec/wodles/aws/aws-s3.py -sr cloudwatchlogs -g 4_3_test -d 2 -s YYYY-MMM-DD -p dev -r us-east-1
```

<details>
    <summary>Command output</summary>

	/var/ossec/wodles/aws/aws-s3.py -sr cloudwatchlogs -g 4_3_test -d 2 -s 2022-jan-07 -p dev -r us-east-1
	DEBUG: +++ Debug mode on - Level: 2
	DEBUG: +++ Getting alerts from "us-east-1" region.
	DEBUG: only logs: 1641513600000
	DEBUG: Getting log streams for "4_3_test" log group
	DEBUG: Found "test_stream" log stream in 4_3_test
	DEBUG: Getting data from DB for log stream "test_stream" in log group "4_3_test"
	DEBUG: Token: "f/36680194340169684017803161812123715926506285965634404351/s", start_time: "1642291200000", end_time: "1644796800002"
	DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_3_test" using token "None", start_time "1641513600000" and end_time "1642291200000"
	DEBUG: +++ Sending events to Analysisd...
	DEBUG: The message is "Test log 0 - 2022-1-14 - 1642158889249"
	DEBUG: +++ Sending events to Analysisd...
	DEBUG: The message is "Test log 1 - 2022-1-14 - 1642158889250"
	DEBUG: +++ Sending events to Analysisd...
	DEBUG: The message is "Test log 2 - 2022-1-14 - 1642158889251"
	DEBUG: +++ Sending events to Analysisd...
	DEBUG: The message is "Test log 3 - 2022-1-14 - 1642158889252"
	DEBUG: +++ Sending events to Analysisd...
	DEBUG: The message is "Test log 4 - 2022-1-14 - 1642158889253"
	DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_3_test" using token "f/36621366964755521812994011433827037582505456891659943936/s", start_time "1641513600000" and end_time "1642291200000"
	DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_3_test" using token "f/36680194340169684017803161812123715926506285965634404351/s", start_time "1644796800003" and end_time "None"
	DEBUG: Saving data for log group "4_3_test" and log stream "test_stream".
	DEBUG: The saved values are "{'token': 'f/36680194340169684017803161812123715926506285965634404351/s', 'start_time': 1641513600000, 'end_time': 1644796800003}"
	DEBUG: Some data already exists on DB for that key. Updating their values...
	DEBUG: Purging the BD
	DEBUG: Getting log streams for "4_3_test" log group
	DEBUG: Found "test_stream" log stream in 4_3_test
	DEBUG: committing changes and closing the DB
</details>

##### Conclusions
The module is working as expected.
