### ISSUE TITLE
Review Gcloud integration and adapt it to Python3.6

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#12238]
| Affected integration |
|---|
| Gcloud |

## Description

Review the Gcloud integration code and remove any python features that are not compatible with Python 3.6, such as the `:=` operator or the `list[type]` docstrings.

## Tasks
- [x] Review and adapt the code.
- [x] Test in an agent or manager using python3.6.
- [x] Unit tests without failures. Updated if there are any relevant changes.
- [x] Add entry to the changelog if necessary.

**Comment by noise-kngdm** [comment]
## Issue update
We have finished adding a CentOS 7 agent with all the required dependencies to our development environment. 

When we fixed the use of type hinting with generics mentioned in the last update, we executed both the `Pub/Sub` and the `Storage` modules to make sure that everything worked as expected. The `Pub/Sub` module is working flawlessly, but we encountered the following error when executing for the second time the `Storage` one:

```
[root@5c24deae2639 gcloud]# python3 /var/ossec/wodles/gcloud/gcloud -p wazuh-dev-258815 -c /var/ossec/wodles/gcloud/credentials.json -l 2 -T access_logs -b  framework-test-bucket  -o 2021-dec-20
gcloud_wodle - CRITICAL - An exception happened while running the wodle: time data '2021-12-23 11:50:04.395000+00:00' does not match format '%Y-%m-%d %H:%M:%S.%f%z'
```

We researched what could the problem be, and we concluded that's due to differences in the implementation of the `strptime` method added in `Python 3.7` and how the [`isoformat`](https://docs.python.org/3/library/datetime.html#datetime.date.isoformat) method of the datetime class works.

As stated by the [datetime documentation](https://docs.python.org/3/library/datetime.html#datetime.date.__str__), the `__str__` method returns the same as the `isoformat` method. That's the method that's being implicitly called when storing information about the processed files in the database:

https://github.com/wazuh/wazuh/blob/5a5866b56557d2b10383a1c286f58f2ecb27c7d4/wodles/gcloud/buckets/bucket.py#L153-L159

The `isoformat` method returns dates that specify the timezone information using colons to separate hours minutes, and seconds. However, as stated by the [datetime documentation](https://docs.python.org/3/library/datetime.html#technical-detail):
> Changed in version 3.7: When the %z directive is provided to the strptime() method, the UTC offsets can have a colon as a separator between hours, minutes and seconds. For example, '+01:00:00' will be parsed as an offset of one hour. In addition, providing 'Z' is identical to '+00:00'.

So for Python versions prior to `3.7`, the `strptime` method won't be able to parse dates in the format returned by the implicit call to `__str__`. 

We fixed this problem in 72e14cbe3f by explicitly transforming the datetime object into a string with a format compatible with `Python 3.6`.
https://github.com/wazuh/wazuh/blob/72e14cbe3fa48901b8f0f2d96067668fa3437452/wodles/gcloud/buckets/bucket.py#L154

### Tests performed
To make sure that the module works with `Python 3.6`, we executed both the Pub/Sub and the Storage modules after removing the mentioned type hinting with generics mentioned in the last update. The module is now working without problems in `Python 3.6`. We will soon open a PR to add this change.

#### Pub/Sub

##### One thread and one hundred messages
```
[root@5c24deae2639 gcloud]# python3 /var/ossec/wodles/gcloud/gcloud -p wazuh-dev-258815 -s wazuh-audit-logs -c /var/ossec/wodles/gcloud/credentials.json -l 2 -T pubsub
gcloud_wodle - INFO - Received and acknowledged 100 messages
```

##### Ten threads and five hundred messages
```
[root@5c24deae2639 gcloud]# python3 /var/ossec/wodles/gcloud/gcloud -p wazuh-dev-258815 -s wazuh-audit-logs -c /var/ossec/wodles/gcloud/credentials.json -l 2 -T pubsub -t 10 -m 500
gcloud_wodle - INFO - Received and acknowledged 500 messages
```

#### Storage

##### Specifying a `only_logs_after` date
```
[root@e22993148f2e gcloud]# python3 /var/ossec/wodles/gcloud/gcloud -b framework-test-bucket -l 2 -c /var/ossec/wodles/gcloud/credentials.json -T access_logs -o 2021-dec-20
gcloud_wodle - INFO - Processing test_1_new.txt
gcloud_wodle - INFO - The creation time of test_22.txt is older than 2021-12-20 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - Processing test_2_new.txt
gcloud_wodle - INFO - The creation time of test_3.txt is older than 2021-12-20 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - Processing test_3_new.txt
gcloud_wodle - INFO - The creation time of test_4.txt is older than 2021-12-20 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - The creation time of test_5.txt is older than 2021-12-20 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - Updating previously processed files.
gcloud_wodle - INFO - Received 3 messages
[root@e22993148f2e gcloud]# python3 /var/ossec/wodles/gcloud/gcloud -b framework-test-bucket -l 2 -c /var/ossec/wodles/gcloud/credentials.json -T access_logs -o 2021-dec-20
gcloud_wodle - INFO - Skipping previously processed file: test_1_new.txt
gcloud_wodle - INFO - The creation time of test_22.txt is older than 2021-12-20 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - Skipping previously processed file: test_2_new.txt
gcloud_wodle - INFO - The creation time of test_3.txt is older than 2021-12-20 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - Skipping previously processed file: test_3_new.txt
gcloud_wodle - INFO - The creation time of test_4.txt is older than 2021-12-20 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - The creation time of test_5.txt is older than 2021-12-20 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - Received 0 messages
```


##### Without specifying a `only_logs_after` and having no files for the execution date
```
[root@e22993148f2e gcloud]# python3 /var/ossec/wodles/gcloud/gcloud -b framework-test-bucket -l 2 -c /var/ossec/wodles/gcloud/credentials.json -T access_logs  
gcloud_wodle - INFO - The creation time of test_1_new.txt is older than 2022-02-15 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - The creation time of test_22.txt is older than 2022-02-15 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - The creation time of test_2_new.txt is older than 2022-02-15 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - The creation time of test_3.txt is older than 2022-02-15 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - The creation time of test_3_new.txt is older than 2022-02-15 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - The creation time of test_4.txt is older than 2022-02-15 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - The creation time of test_5.txt is older than 2022-02-15 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - Received 0 messages
```

##### Without specifying a `only_logs_after` having new files for the execution date
```
[root@e22993148f2e gcloud]# python3 /var/ossec/wodles/gcloud/gcloud -b framework-test-bucket -l 2 -c /var/ossec/wodles/gcloud/credentials.json -T access_logs
gcloud_wodle - INFO - The creation time of test_1_new.txt is older than 2022-02-15 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - The creation time of test_22.txt is older than 2022-02-15 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - The creation time of test_2_new.txt is older than 2022-02-15 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - The creation time of test_3.txt is older than 2022-02-15 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - The creation time of test_3_new.txt is older than 2022-02-15 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - The creation time of test_4.txt is older than 2022-02-15 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - The creation time of test_5.txt is older than 2022-02-15 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - Processing test_6.txt
gcloud_wodle - INFO - Updating previously processed files.
gcloud_wodle - INFO - Received 1 message
[root@e22993148f2e gcloud]# python3 /var/ossec/wodles/gcloud/gcloud -b framework-test-bucket -l 2 -c /var/ossec/wodles/gcloud/credentials.json -T access_logs
gcloud_wodle - INFO - The creation time of test_1_new.txt is older than 2022-02-15 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - The creation time of test_22.txt is older than 2022-02-15 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - The creation time of test_2_new.txt is older than 2022-02-15 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - The creation time of test_3.txt is older than 2022-02-15 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - The creation time of test_3_new.txt is older than 2022-02-15 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - The creation time of test_4.txt is older than 2022-02-15 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - The creation time of test_5.txt is older than 2022-02-15 00:00:00+00:00. Skipping it...
gcloud_wodle - INFO - Skipping previously processed file: test_6.txt
gcloud_wodle - INFO - Received 0 messages
```

##### Specifying a prefix
```
[root@e22993148f2e gcloud]# python3 /var/ossec/wodles/gcloud/gcloud -b framework-test-bucket -l 2 -c /var/ossec/wodles/gcloud/credentials.json -T access_logs -o 2021-jan-01 -P test_prefix
gcloud_wodle - INFO - Processing test_prefix/test_1.txt
gcloud_wodle - INFO - Updating previously processed files.
gcloud_wodle - INFO - Received 1 message
[root@e22993148f2e gcloud]# python3 /var/ossec/wodles/gcloud/gcloud -b framework-test-bucket -l 2 -c /var/ossec/wodles/gcloud/credentials.json -T access_logs -o 2021-jan-01 -P test_prefix
gcloud_wodle - INFO - Skipping previously processed file: test_prefix/test_1.txt
gcloud_wodle - INFO - Received 0 messages
```

##### Having an empty bucket
```
[root@e22993148f2e gcloud]# python3 /var/ossec/wodles/gcloud/gcloud -b framework-test-bucket -l 2 -c /var/ossec/wodles/gcloud/credentials.json -T access_logs -o 2021-jan-01 -P test_empty
gcloud_wodle - INFO - Received 0 messages
```

##### Using log level 1
```
[root@e22993148f2e gcloud]# python3 /var/ossec/wodles/gcloud/gcloud -b framework-test-bucket -l 1 -c /var/ossec/wodles/gcloud/credentials.json -T access_logs -o 2021-jan-01
gcloud_wodle - INFO - Processing test_1_new.txt
gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 1", "source": "gcp_bucket"}}'"
gcloud_wodle - INFO - Processing test_22.txt
gcloud_wodle - INFO - Processing test_2_new.txt
gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 2", "source": "gcp_bucket"}}'"
gcloud_wodle - INFO - Processing test_3.txt
gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 3", "source": "gcp_bucket"}}'"
gcloud_wodle - INFO - Processing test_3_new.txt
gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 3", "source": "gcp_bucket"}}'"
gcloud_wodle - INFO - Processing test_4.txt
gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 4", "source": "gcp_bucket"}}'"
gcloud_wodle - INFO - Processing test_5.txt
gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 5", "source": "gcp_bucket"}}'"
gcloud_wodle - INFO - Processing test_6.txt
gcloud_wodle - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 6", "source": "gcp_bucket"}}'"
gcloud_wodle - INFO - Updating previously processed files.
gcloud_wodle - INFO - Received 7 messages
```
