### ISSUE TITLE
Review Docker Listener integration and adapt it to Python3.6

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#12240]
| Affected integration |
|---|
| Docker Listener |

## Description

Review the Docker Listener integration code and remove any python features that are not compatible with Python 3.6, such as the `:=` operator or the `list[type]` docstrings.

## Tasks
- [x] Review and adapt the code.
- [x] Test in an agent or manager using python3.6.
- [x] Unit tests without failures. Updated if there are any relevant changes.
- [x] Add entry to the changelog if necessary.

**Comment by noise-kngdm** [comment]
## Issue update
To test if this module works with Python 3.6, we installed a Wazuh manager version `4.3.0` in a Ubuntu 18.04 virtual machine, installed docker, and finally installed the required dependencies. After that, we executed the `DockerListener.py` script, not with the Wazuh embedded Python interpreter but with the system one. Since Ubuntu 18.04 comes with Python 3.6 installed -or at least the [bento we used to set up the machine](https://app.vagrantup.com/bento/boxes/ubuntu-18.04)- we could use the module after having an up-and-running Wazuh manager.

### Execution of the module
```
root@ubuntu18LTS:/var/ossec/wodles/docker# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.3.0"
WAZUH_REVISION="40305"
WAZUH_TYPE="server"
root@ubuntu18LTS:/var/ossec/wodles/docker# python3 -V 
Python 3.6.9
root@ubuntu18LTS:/var/ossec/wodles/docker# python3 ./DockerListener.py 
{"integration": "docker", "docker": {"Wodle event": "Started"}}
Docker service was started.
{"integration": "docker", "docker": {"Wodle event": "Connected to Docker service"}}
{"integration": "docker", "docker": {"status": "create", "id": "96b312f72c6984967ed95890a6c79b5c4ce263902b5001ab9430536e10791cd9", "from": "alpine", "Type": "container", "Action": "create", "Actor": {"ID": "96b312f72c6984967ed95890a6c79b5c4ce263902b5001ab9430536e10791cd9", "Attributes": {"image": "alpine", "name": "gifted_lumiere"}}, "scope": "local", "time": 1645028297, "timeNano": 1645028297315717181}}
{"integration": "docker", "docker": {"status": "attach", "id": "96b312f72c6984967ed95890a6c79b5c4ce263902b5001ab9430536e10791cd9", "from": "alpine", "Type": "container", "Action": "attach", "Actor": {"ID": "96b312f72c6984967ed95890a6c79b5c4ce263902b5001ab9430536e10791cd9", "Attributes": {"image": "alpine", "name": "gifted_lumiere"}}, "scope": "local", "time": 1645028297, "timeNano": 1645028297318468059}}
{"integration": "docker", "docker": {"Type": "network", "Action": "connect", "Actor": {"ID": "779bd1ce337be45558d2239894800510fc165a8fc5d0d53bd92bc138d99671e6", "Attributes": {"container": "96b312f72c6984967ed95890a6c79b5c4ce263902b5001ab9430536e10791cd9", "name": "bridge", "type": "bridge"}}, "scope": "local", "time": 1645028297, "timeNano": 1645028297338717632}}
{"integration": "docker", "docker": {"status": "start", "id": "96b312f72c6984967ed95890a6c79b5c4ce263902b5001ab9430536e10791cd9", "from": "alpine", "Type": "container", "Action": "start", "Actor": {"ID": "96b312f72c6984967ed95890a6c79b5c4ce263902b5001ab9430536e10791cd9", "Attributes": {"image": "alpine", "name": "gifted_lumiere"}}, "scope": "local", "time": 1645028297, "timeNano": 1645028297861115836}}
{"integration": "docker", "docker": {"status": "resize", "id": "96b312f72c6984967ed95890a6c79b5c4ce263902b5001ab9430536e10791cd9", "from": "alpine", "Type": "container", "Action": "resize", "Actor": {"ID": "96b312f72c6984967ed95890a6c79b5c4ce263902b5001ab9430536e10791cd9", "Attributes": {"height": "26", "image": "alpine", "name": "gifted_lumiere", "width": "187"}}, "scope": "local", "time": 1645028297, "timeNano": 1645028297863746739}}
{"integration": "docker", "docker": {"status": "die", "id": "96b312f72c6984967ed95890a6c79b5c4ce263902b5001ab9430536e10791cd9", "from": "alpine", "Type": "container", "Action": "die", "Actor": {"ID": "96b312f72c6984967ed95890a6c79b5c4ce263902b5001ab9430536e10791cd9", "Attributes": {"exitCode": "0", "image": "alpine", "name": "gifted_lumiere"}}, "scope": "local", "time": 1645028333, "timeNano": 1645028333630500373}}
{"integration": "docker", "docker": {"Type": "network", "Action": "disconnect", "Actor": {"ID": "779bd1ce337be45558d2239894800510fc165a8fc5d0d53bd92bc138d99671e6", "Attributes": {"container": "96b312f72c6984967ed95890a6c79b5c4ce263902b5001ab9430536e10791cd9", "name": "bridge", "type": "bridge"}}, "scope": "local", "time": 1645028333, "timeNano": 1645028333788637742}}
```

### Conclusions
We can conclude that this module needs no further changes to make it compatible with Python 3.6 onwards.
