### ISSUE TITLE
Engine - Event trace debugging

### ISSUE THREAD

**Issue by JavierBejMen** [wazuh/wazuh#12613]
| Wazuh version | Component | Install type | Install method   | Platform   |
| ------------- | --------- | ------------ | ---------------- | ---------- |
| 5.0.0         | Engine    | Manager      | Packages/Sources | OS version |

In our design the operations applied through the processing pipeline are expected to operate correctly or fail. We need to implement a mechanism to allow the users to see on demand all the operations and stages an specific event goes through to see how it is being processed and detect undesired behavior on assets and operations. 

Initially in the python PoC all trace is appended to the event that flows through the entire graph, where setting up a variable in the asset definition would log said trace once the asset has processed the event. In the current engine implementation no trace is being recorded, so we need to implement it, though multiple alternatives exists:
- Instrumentalizing the event, as it is in the python PoC, appending the trace to the event. This will allow to see every detail of the operations applied to the event, but will require the event to traverse the entire graph in order to reach and output presumably.
- Instrumentalizing the processing pipeline at desired granularity, at asset (decoder, rule ...) granularity initially. This will allow to see debug information of all events at a given asset, but tracing an event will require extra effort on correlating multiple assets debugging information.

In any case the user should be able to turn this functionality on demand and define the outputs of this debugging trace, keeping in mind this will be used from our future API, or with the property `draft: true` in the asset definition.

**This trace do not contemplate logic or fatal errors derived from other processes, errors per se are treated on a different level and are not the aim of this issue.**
## Tasks
- [x] Research approaches
  - Instrumentalize event
  - Instrumentalize processing engine

### Instrumentalize processing engine (Assets scope)
- [x] Implement tracer.
- [x] Update asset builders to create and inject the tracer and handle debug yml tag.
- [x] Update operation builders to use the tracer.
- [x] Update Router/Enviroment classes to expose tracer outputs.

**Comment by JavierBejMen** [comment]
## Research update / Instrumentalize pipeline operations
One possible approach is to trace what is happening on a asset scope, this would mean to define a sink observable to emit all debug information on the operations done by said asset. The asset builder will define a `tracer` that would be injected on the subsequent builders, so the developer in charge of making the builders can use it.

Following this approach, all operation builders well need to update its signature from ```using OpBuilder = std::function<Lifter(const DocumentValue &)>;``` to ```using OpBuilder = std::function<Lifter(const DocumentValue &, tracer)>;```. Then, the tracer would be passed by value to the `lifter`.

condition value builder simple example:
```
types::Lifter opBuilderConditionValue(const types::DocumentValue & def, tracer tr)
{
    // Make deep copy of value
    // TODO Should separete document to be checked, in order of build the path before check teh value
    types::Document doc{def};

    // Return Lifter
    // Pass tracer by value too
    return [=](types::Observable o)
    {
        // Append rxcpp operation
        // Pass tracer by value too again
        return o.filter([=](types::Event e) { 
            if( e->check(doc)){
                return true;
            }else{
                tr("Filter failed");
                return false;
            }
        );
    };
}
```
The tracer is defined in the asset builder, and should be exposed or accessible by the `Router`, so it can be de/activated on demand. The tracer could be implemented as a subject, implementing the de/activation through un/subscribing.

simple tracer:
```
struct tr{
        subjects::subject<string> m_subj;
        auto getTrFn() -> tracer {
            return [m_s = this->m_subj.get_subscriber()](string msg){
                if(m_s.is_subscribed()){
                    m_s.on_next(msg);
                }
            };
        }
    } tracer;
    auto lifter = conditionValueBuilder(jsonValue, tracer.getTrFn());
    
    //Activation
    auto cs = tr.m_subj.get_observable.subscribe();
    // Deactivation
    cs.unsubscribe();
```

### Tasks
- Implement tracer.
- Update asset builders to create and inject the tracer and handle debug yml tag.
- Update operation builders to use the tracer.
- Update Router/Enviroment classes to expose tracer outputs.

**Comment by JavierBejMen** [comment]
## Update

Added Tracer and updated builders definitions
 - Added Tracer class in connectable.hpp and updated connectable.
 - Added TracerFn type to builderTypes.hpp.
 - Updated all AssetBuilders to create a Tracer.
 - Updated all OperationBuilders to receive a TracerFn, use of the actual
   tracer not implemented.
 - Updated all builder tests to use a fake tracer.
