### ISSUE TITLE
Add API log rotation depending on file size

### ISSUE THREAD

**Issue by Kondent** [wazuh/wazuh#12615]
## Description
Currently, our API log file is rotating at certain time (everyday at `midnight`).
We should investigate and evaluate the possibility of adding log rotation depending on the size of the log file.

Rotated logs are store into `/var/ossec/logs/api/<YEAR>/<MONTH>` as `api-<DAY>.log.gz`.

https://github.com/wazuh/wazuh/blob/341697e3c592085f37583f5c0cf274531a69b45d/framework/wazuh/core/wlogging.py#L56

A proper investigation is needed here, since we could have more than one file for each day if the `log size` is exceeded.

## Tasks
- [x] Implement log rotation support depending on file size.
- [x] Review/modify the filenames of rotated logs.
- [x] Investigate the possibility of adding a new parameter to our API configuration file to set a specific value regarding this size.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by vicferpoy** [comment]
# Issue update

## Configuration

For the API configuration, a new option has been added:

```yaml
logs:
  max_size: 0
```

It defaults to 0, disabling this feature. Any other value greater than 0 (bytes) will disable the time based rotation (at midnight) and will make the API log rotate depending on the file size.

> A minimum size limitation could be added later on to prevent file flooding.

## Rotated files

As there can be multiple rotated logs depending on the maximum size, I decided to label them using a suffix. For instance:

- _api.log-01_1_
- _api.log-01_2_
- _api.log-01_3_
- _api.log-01_4_

This will indicate that on day 1 of a certain year and month, a total of 4 log files were rotated.
