### ISSUE TITLE
Fix unit tests for AWS 

### ISSUE THREAD

**Issue by robertogp21** [wazuh/wazuh#12637]
| Affected integration |
|---|
| AWS |

# Description

While working on [this PR](https://github.com/wazuh/wazuh/pull/12630) we detected that some tests were not passing. The reason for the failure was that the unit test of the external integrations was trying to execute a binary that doesn't exist in the repository. The binary is `wazuh-control`, and the failure occurred when executing `test_config_format_created_date()` in `test_aws.py`

The output of the error is the following:

```
_____________ test_config_format_created_date[2021/1/19-20210119] ______________
utils.py:61: in call_wazuh_control
    proc = subprocess.Popen([wazuh_control, option], stdout=subprocess.PIPE)
/usr/local/lib/python3.9/subprocess.py:951: in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
/usr/local/lib/python3.9/subprocess.py:1823: in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
E   FileNotFoundError: [Errno 2] No such file or directory: '/tmp/build/wazuh/bin/wazuh-control'

During handling of the above exception, another exception occurred:
aws/tests/test_aws.py:325: in test_config_format_created_date
    bucket = aws_s3.AWSConfigBucket(**{'reparse': False, 'access_key': None, 'secret_key': None,
aws/aws_s3.py:1139: in __init__
    AWSLogsBucket.__init__(self, **kwargs)
aws/aws_s3.py:1043: in __init__
    AWSBucket.__init__(self, **kwargs)
aws/aws_s3.py:513: in __init__
    WazuhIntegration.__init__(self, access_key=access_key,
aws/aws_s3.py:150: in __init__
    self.wazuh_version = utils.get_wazuh_version()
utils.py:111: in get_wazuh_version
    return get_wazuh_info("WAZUH_VERSION")
utils.py:84: in get_wazuh_info
    wazuh_info = call_wazuh_control("info")
utils.py:66: in call_wazuh_control
    exit(1)
E   SystemExit: 1
----------------------------- Captured stdout call -----------------------------
ERROR: a problem occurred while executing /tmp/build/wazuh/bin/wazuh-control
```

## Tasks
- [x] Fix the test.
- [x] Test in a manager.
- [x] Test in an agent.
- [x] Unit tests without failures. Updated if there are any relevant changes.
- [x] API integration tests without failures. Updated if there are any relevant changes.
- [x] Update the documentation if necessary.
- [x] Add entry to the changelog if necessary.
