### ISSUE TITLE
Improve `decompress_file` exception handling

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#12649]
| Affected integration |
|---|
| AWS|

## Description

The `decompress_file` function present in the AWS module must be reviewed to improve its exception management, as it is currently not handling the possible exceptions that `gzip.open` could generate:

https://github.com/wazuh/wazuh/blob/341697e3c592085f37583f5c0cf274531a69b45d/wodles/aws/aws_s3.py#L841-L849

## Tasks
- [x] Determine which exceptions should be handled and modify the function to do so.
- [x] Test in a manager.
- [x] Test in an agent.
- [x] Unit tests without failures. Updated if there are any relevant changes.
- [x] Integration tests without failures. Updated if there are any relevant changes.
- [x] Update the documentation if necessary.
- [x] Add entry to the changelog if necessary.

**Comment by noise-kngdm** [comment]
## Issue update
We have researched with exceptions could be raised by the methods called by the `decompress_file` method. Those could be `zipfile.BadZipFile`, `gzip.BadGZipFile`, and `zlib.error`. We also refactored the `decompress_file` method to make it a wrapper method that calls the necessary decompression function.

We will make the necessary tests before opening a PR with the changes.

**Comment by noise-kngdm** [comment]
## Issue update
After implementing the necessary tests, we realized that the `gzip.open` method doesn't check that the file isn't corrupt. To fix that we decided to include a call to `gzip.read`, which will output a message if the file is corrupted.

To ensure that the check doesn't incur in an appreciable overhead, we wrote a test that would execute the `decompress_file` method with a 120B file and with a 1.76GiB file, and then would compute how much time was spent in the `decompress_file` method using `time.perf_counter`. The results are the following:

### Profiling results
Without calling `gzip.read`:
```
Delay: 0.0008279430003312882 
	 Size in bytes: 120
Delay: 0.0013236239974503405 
	 Size in bytes: 1894000020
```
Adding a call to `gzip.read`:
```
Delay: 0.0009675670007709414 
	 Size in bytes: 120
Delay: 0.0013778530010313261 
	 Size in bytes: 1894000020
```

As the tests show, adding a call to `gzip.read` doesn't incur in any appreciable overhead.


### Tests

#### Unit tests
The unit tests pass without any problems:

```
(wazuh-unit) ➜  wodles git:(master) ✗ pytest 
==================================== test session starts ====================================
platform linux -- Python 3.10.4, pytest-6.2.5, py-1.11.0, pluggy-0.13.1
rootdir: /home/gonzz/git/wazuh/wodles
plugins: asyncio-0.15.1
collected 55 items                                                                          

aws/tests/test_aws.py ......................................                          [ 69%]
gcloud/tests/test_access_logs.py .                                                    [ 70%]
gcloud/tests/test_bucket.py ...                                                       [ 76%]
gcloud/tests/test_gcloud.py .....                                                     [ 85%]
gcloud/tests/test_integration.py .....                                                [ 94%]
gcloud/tests/test_subscriber.py ...                                                   [100%]

===================================== warnings summary ======================================
aws/aws_s3.py:538
  /home/gonzz/git/wazuh/wodles/aws/aws_s3.py:538: DeprecationWarning: invalid escape sequence '\d'
    self.prefix_regex= re.compile("^\d{12}$")

../../../venv/wazuh-unit/lib/python3.10/site-packages/google/pubsub_v1/services/publisher/client.py:17
  /home/gonzz/venv/wazuh-unit/lib/python3.10/site-packages/google/pubsub_v1/services/publisher/client.py:17: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    from distutils import util

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================== 55 passed, 2 warnings in 0.49s ===============================
```

#### Other tests
We uploaded three different files to the `wazuh-aws-wodle-cloudtrail` bucket, two one of them compressed using the supported compression algorithms and one in plain text to ensure that the module works as expected after the changes. Executing it shows the following output:

##### Test in a 4.4 manager
```
root@8895de820dd8:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-cloudtrail -t cloudtrail -d2  -p dev 
DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Table does not exist; create
DEBUG: +++ Working on 166157441623 - us-west-1
DEBUG: +++ Marker: AWSLogs/166157441623/CloudTrail/us-west-1/2022/03/30
DEBUG: ++ Found new log: AWSLogs/166157441623/CloudTrail/us-west-1/2022/03/30/166157441623_CloudTrail_us-west-1_20220330T0000Z_HASDoKlxgfdNInHa.json.gz
DEBUG: ++ Found new log: AWSLogs/166157441623/CloudTrail/us-west-1/2022/03/30/166157441623_CloudTrail_us-west-1_20220330T0000Z_HASDoKlxgfdNInHa.json.zip
DEBUG: ++ Found new log: AWSLogs/166157441623/CloudTrail/us-west-1/2022/03/30/166157441623_CloudTrail_us-west-1_20220330T0000Z_HASDoKlxgfdkdIOa.json.txt
DEBUG: +++ DB Maintenance
DEBUG: +++ Working on XXXXXXXXXXXX - us-west-1
DEBUG: +++ Marker: AWSLogs/XXXXXXXXXXXX/CloudTrail/us-west-1/2022/03/30
DEBUG: +++ No logs to process in bucket: XXXXXXXXXXXX/us-west-1
DEBUG: +++ DB Maintenance
```
##### Test in a 4.4 agent with Python 3.6

```
[root@81223fab675c aws]# python3 ./aws-s3  -b wazuh-aws-wodle-cloudtrail -p dev -d 2
DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Table does not exist; create
DEBUG: +++ Working on 166157441623 - us-west-1
DEBUG: +++ Marker: AWSLogs/166157441623/CloudTrail/us-west-1/2022/03/30
DEBUG: ++ Found new log: AWSLogs/166157441623/CloudTrail/us-west-1/2022/03/30/166157441623_CloudTrail_us-west-1_20220330T0000Z_HASDoKlxgfdNInHa.json.gz
DEBUG: ++ Found new log: AWSLogs/166157441623/CloudTrail/us-west-1/2022/03/30/166157441623_CloudTrail_us-west-1_20220330T0000Z_HASDoKlxgfdNInHa.json.zip
DEBUG: ++ Found new log: AWSLogs/166157441623/CloudTrail/us-west-1/2022/03/30/166157441623_CloudTrail_us-west-1_20220330T0000Z_HASDoKlxgfdkdIOa.json.txt
DEBUG: +++ DB Maintenance
DEBUG: +++ Working on XXXXXXXXXXXX - us-west-1
DEBUG: +++ Marker: AWSLogs/XXXXXXXXXXXX/CloudTrail/us-west-1/2022/03/30
DEBUG: +++ No logs to process in bucket: XXXXXXXXXXXX/us-west-1
DEBUG: +++ DB Maintenance
[root@81223fab675c aws]# python3 --version
Python 3.6.8
```

### Conclusions
The module works as expected after the changes, so we will submit a PR with the changes as soon as possible.
