### ISSUE TITLE
Make the remove_from_bucket option configurable per bucket in AWS conf parser

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#12670]
| Affected integration |
|---|
| AWS |

## Description

The AWS module has a `remove_from_bucket` parameter available, which allows the user to decide whether logs should be removed from the bucket once they are consumed. However, our current implementation of this parameter implies that it must be set globally, i.e. within the `wodle` block. We should change this so that this parameter is set within the `bucket` tag. This way a user will be able to indicate specific buckets where logs should be deleted after comsuption, without this decision affecting the rest of the configured buckets.

Example of a valid configuration after applying the change:

```
<wodle name="aws-s3">
  <disabled>no</disabled>
  <interval>10m</interval>
  <run_on_start>yes</run_on_start>

  <!-- KMS, 'dev' profile -->
  <bucket type="custom">
    <name>wazuh-aws-wodle</name>
    <path>kms_compress_encrypted</path>
    <aws_profile>dev</aws_profile>
    <remove_from_bucket>yes</remove_from_bucket>
  </bucket>

  <bucket type="cloudtrail">
    <name>wazuh-cloudtrail</name>
    <aws_profile>dev</aws_profile>
  </bucket>

  <bucket type="cloudtrail">
    <name>wazuh-aws-wodle</name>
    <path>alternative-path</path>
    <aws_profile>dev</aws_profile>
    <remove_from_bucket>yes</remove_from_bucket>
  </bucket>
</wodle>
```

## Tasks
- [ ] Apply the required changes to ossec.conf parser
- [ ] Update Core Unit Tests
- [ ] Review and update aws-s3.py module if necessary
- [ ] Test in a manager.
- [ ] Test in an agent.
- [ ] Unit tests without failures. Updated if there are any relevant changes.
- [ ] Integration tests without failures. Updated if there are any relevant changes.
- [ ] Update the documentation if necessary.
- [ ] Add entry to the changelog if necessary.

**Comment by mateojames** [comment]
It seems the implementation has already been done previously, though no documentation seems to exist about it. We will be testing the current state of the functionality to then proceed with the process of documentation

**Comment by mateojames** [comment]
After testing the functionality, it seems the field <remove_from_bucket> only works when set at the bucket level and not at the aws module level. It appears this issue was solved and it was decided to erase the functionality for the `<wodle>`, but the Framework team has decided to keep that functionality. We will be working on adding it back and proceed with the process of documentation of the field `<remove_from_bucket>` in both cases.


### Case 1: `<remove_from_bucket>` set at bucket level

**Configuration used:**

```
<wodle name="aws-s3">
    <disabled>no</disabled>
    <interval>10m</interval>
    <run_on_start>yes</run_on_start>

    <bucket type="custom">
      <name>wazuh-aws-wodle</name>
      <aws_profile>dev</aws_profile>
      <remove_from_bucket>yes</remove_from_bucket>
    </bucket>

    <bucket type="cloudtrail">
      <name>wazuh-aws-cloudtrail</name>
      <aws_profile>dev</aws_profile>
      <remove_from_bucket>yes</remove_from_bucket>
    </bucket>
</wodle>

```

**Output:**

_Both logs were erased from the buckets_


### Case 2: `<remove_from_bucket>` set at wodle level

**Configuration used:**

```
<wodle name="aws-s3">
    <disabled>no</disabled>
    <interval>10m</interval>
    <run_on_start>yes</run_on_start>
    <remove_from_bucket>yes</remove_from_bucket>


    <bucket type="custom">
      <name>wazuh-aws-wodle</name>
      <aws_profile>dev</aws_profile>
    </bucket>

    <bucket type="cloudtrail">
      <name>wazuh-aws-cloudtrail</name>
      <aws_profile>dev</aws_profile>
    </bucket>
</wodle>
```

**Output:**

_None of the logs were erased from the buckets_

**Comment by mateojames** [comment]
The team has discussed about the actions to take after the new findings, to either add back the `remove_from_bucket` option to the wodle or to only correct the documentation that shows it is possible to configure it there, as this option has been eliminated a while ago. The decision will be made on the following days.

**Comment by mateojames** [comment]
After testing the field `<remove_from_bucket>` does no effect when configured in the wodle section, the team has opted to correct the documentation and specify this field is only configurable for each specific bucket, with the default option being No. The possibility to set the option in the wodle section hasn't been available for some time now, and this is not intended to change in the time being, so there is no need to make changes in the functionality of the application.
