### ISSUE TITLE
Change API login endpoint method to `POST`

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#12793]
Currently, our API login endpoint to retrieve a token is `GET /security/user/authenticate`. This is incorrect, as login endpoints should use the `POST` method.

## Tasks

- [x] Change method in API specification.
- [x] Update integration tests.
- [x] Update documentation references.
- [x] Notify all affected teams.
