### ISSUE TITLE
Review UTC timestamps calculation in the external integrations

### ISSUE THREAD

**Issue by noise-kngdm** [wazuh/wazuh#12833]
| Affected integration |
|---|
| AWS, Azure |

# Description
As reported in #12108, the timestamps weren't being correctly calculated in some parts of the framework. After running `grep` in the `wodles` folder looking for the `datetime.utcnow` string, we realized that in fact the timestamps aren't correct in the wodles folder either.
```
#  wazuh git:(master) ✗ grep -rl 'datetime.utcnow' wodles
wodles/aws/aws_s3.py
wodles/azure/azure-logs.py
```

The calculation of the timestamps must be reviewed to use the UTC time or a timezone-aware format. We advice using the solution suggested in #12108, that is, replacing those instances with:
```
datetime.utcnow().replace(tzinfo=timezone.utc).timestamp()
```

## Tasks
- [x] Review if timestamps are being calculated using other methods and if those should be changed too
- [x] Test in a manager.
- [x] Test in an agent.
- [x] Unit tests without failures. Updated if there are any relevant changes.
- [x] Integration tests without failures. Updated if there are any relevant changes.
- [x] Update the documentation if necessary.
- [x] Add entry to the changelog if necessary.

**Comment by fdalmaup** [comment]
# Issue Update

The aws_s3.py and azure-logs.py files are generating datetime objects without the proper tzinfo attribute set to timezone.utc, which would generate the error described in the description of the issue when converting to timestamp. 
The required changes have been made, tests will be carried out to verify that the normal behavior of the modules was not affected.

**Comment by fdalmaup** [comment]
# Azure Wodle Unit Tests
The modification in the `azure-logs.py` was made in the `offset_to_datetime` function. This function was already tested in the existing unit tests, therefore no new test was required.

## Test report
[azure_tests.zip](https://github.com/wazuh/wazuh/files/9302214/azure_tests.zip)


## Test results

---
| **Test name** | **Pass** | **XPass** | **Skip** | **XFail** | **Fail** | **Issues Ref.** | **Status** |
|--|--|--|--|--|--|--|--|
| azure/tests/test_azure.py | 115 | 0 | 0 | 0 | 0 |  | :green_circle: |
| azure/tests/test_orm.py | 23 | 0 | 0 | 0 | 0 |  | :green_circle: |

**Comment by fdalmaup** [comment]
# AWS Wodle Unit Tests

## Test report
[aws_tests.zip](https://github.com/wazuh/wazuh/files/9302237/aws_tests.zip)


## Test results

---
| **Test name** | **Pass** | **XPass** | **Skip** | **XFail** | **Fail** | **Issues Ref.** | **Status** |
|--|--|--|--|--|--|--|--|
| aws/tests/test_aws.py | 38 | 0 | 0 | 0 | 0 |  | :green_circle: |

**Comment by fdalmaup** [comment]
# Manual Test CloudWatch Logs 
The modification in the `aws_s3.py` file was made where the `timestamp()` function is used which is the case of the `default_date_millis` attribute in the `AWSCloudWatchLogs` class. 
The function generates a timestamp from the `default_date` attribute which is defined in the `WazuhIntegration` class (`self.default_date = datetime.utcnow().replace(hour=0, minute=0, second=0, microsecond=0)` and could lead to an error in the generated timestamp value as described in the Issue Description. Therefore, the definition was changed to `default_date = datetime.utcnow().replace(hour=0, minute=0, second=0, microsecond=0, tzinfo=timezone.utc)` and manual tests on the `AWSCloudWatchLogs` class needed to be made.
