### ISSUE TITLE
Change the location of the cluster configuration file

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#12832]
## Description

In this issue, we will modify the cluster behavior. Currently, the internal configuration of the cluster is defined in the `cluster.json` (https://github.com/wazuh/wazuh/blob/master/framework/wazuh/core/cluster/cluster.json) file. However, there are two files with this configuration:

```
root@wazuh-master:/# find -name cluster.json
./var/ossec/framework/wazuh/core/cluster/cluster.json
./var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.4.0-py3.9.egg/wazuh/core/cluster/cluster.json
```

This causes confusion when modifying the cluster settings. The file that actually reads the cluster is `/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.4.0-py3.9.egg/wazuh/core/cluster/cluster.json`, this depends on the version. Of course, at upgrade time the changes in the `cluster.json` file are removed.

Therefore, in this issue, we aim to be consistent with the other Wazuh configuration files, and therefore, the only configuration file for the cluster will be `/var/ossec/framework/wazuh/core/cluster/cluster.json`.

The main problem resides in the following cluster function, which as we can see, extracts the information from the wrong folder:

![image](https://user-images.githubusercontent.com/15522808/159736591-c6b24e5b-8f11-4f42-b739-a47324cd37a5.png)

It is not wrong to have two files because the one in the `/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.4.0-py3.9.egg/wazuh/core/cluster/cluster.json` folder is the original version file and can be useful to restore the configuration in case of error.

## TODO

- [ ] Modify the `get_cluster_items` function.
- [ ] Design a method to preserve/backup the changes applied to the cluster.json file in case of update.
- [ ] Review and fix possible errors in unit tests.
- [ ] Run all tests related to the cluster.

**Comment by davidjiglesias** [comment]
We are finally not approaching this change.
