### ISSUE TITLE
Wazuh Config Copy Module

### ISSUE THREAD

**Issue by stoksoz1** [wazuh/wazuh#12848]
| Config Copy Module |
|---|
| Copy important files to different location|

> wazuh config
> elasticsearch config
> kibana config
> filebeat config
> decoders
> rules
> 

## Tasks
- [ ] Daily copy selected files/folders 
- [ ] Show config changes on GUI
- [ ] Compare config files
