### ISSUE TITLE
Journald support in Logcollector

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#12862]
# Logcollector support for journald logs

| EPIC branch|
|--|
|12862-logcollector-journald-support|

## Description

*systemd* has a component called *journald* that handles logging for the services. It makes it easier for the services to record information about their status and actions. This information can be very valuable for the Wazuh users, so we need to develop a way to enable *Logcollector* to monitor these logs.

### Related issues

This task is similar to the support for macOS logs through the integration with the Unified Logging System:

- wazuh/wazuh#4572

## Functional requirements

1. The user will have a new option available in Logcollector to gather *journald* logs.
    - Local configuration: agent's *etc/ossec.conf*.
    - Shared configuration: manager's *etc/shared/\*/agent.conf*.
    - Shared configuration: user interface.
2. The user can define multiple `<localfile>` blocks for *journald*, all of which are valid.
3. Agents will include a basic journald configuration by default, on new installations, if the platform has *journald*.
4. Users will be provided with a predefined ruleset used to analyze journald events.
5. Users may extend such ruleset according to their needs.
6. The user will be able to find the alerts derived from the captured logs in the Wazuh Dashboard.

### New options

```xml
<localfile>
  <log_format>journald</log_format>
  <journald>
    <priority>
    <transport>
    <syslog_identifier>
    <syslog_facility>
```

### Compatible options

```xml
<localfile>
  <ignore>
  <restrict>
  <only-future-events>
```

## Non-functional requirements

1. Logcollector should check for new events in the journald API every `logcollector.loop_timeout` seconds.
2. If `logcollector.max_lines` is greater than 0, then a maximum of events corresponding to the option value will be read in each read phase.
3. If `<only-future-events>` is set to `no`, the agent shall position the read cursor over the event after the last one sent after a restart.
4. If either `<only-future-events>` is set to `yes`, or the agent has started for the first time, the agent should position the read cursor at the end of the log.
5. Options `<ignore>` and `<restrict>` shall execute the search on the content to be sent (*full log*).
6. The documentation shall include a new capabilities section explaining how to gather *journald* logs.

## Implementation restrictions

1. The content that the agent sends (*full_log*) must correspond to the output of `journalctl`.
2. This feature should be implemented via the journald API. Avoid calling `journalctl` whenever possible.
3. This feature will only be available on Linux, and depends on the distro being based on *systemd*.
4. Regarding functional requirement no. 2, there is no way to override or cancel a *journald* `<localfile>` block.

## Plan

- [x] **Stage 1**: [Make a PoC to pick up logs from *journald*](https://github.com/wazuh/wazuh/issues/22056). 
- [x] **Stage 2**: Implement the necessary changes to the agent.
  - [x] wazuh/wazuh#22322
  - [x] wazuh/wazuh#22411
  - [x] wazuh/wazuh#22606
- [x] **Stage 3**: Extend the Logcollector QA tests to check this feature. 
  - [x] #22654 
  - [x] https://github.com/wazuh/qa-integration-framework/issues/130
- [x] **Stage 4**: [Extend the reference documentation with the new options and values.](https://github.com/wazuh/wazuh-documentation/issues/7201)
- [x] **Stage 5**: [Validate Compatibility of Journald Log Collection with Existing Ruleset.](https://github.com/wazuh/wazuh/issues/22964)
- [x] **Stage 6**: [Verify that the new configuration can be pushed from the UI. A priori, no changes are required in the Dashboard.](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6564)
- [x] **Stage 7**: [Enable Framework to Parse and send journald Configuration as JSON.](https://github.com/wazuh/wazuh/issues/22949)

## Requirements Traceability Matrix (RTM)

|Requirement type|Responsible|Description|Plan part|
|--|--|--|--|
|Functional|@wazuh/core|New option in Logcollector.|Stages 2 & 4|
|Functional|@wazuh/core|Accept multiple settings.|Stage 2|
|Functional|@wazuh/core|Include a basic default configuration.|Stage 2|
|Functional|@wazuh/threat-intel|Define a default ruleset.|Stage 5|
|Functional|@wazuh/threat-intel|Accept ruleset extensions.|Stage 5|
|Functional|@wazuh/frontend|Ability to find alerts in the Dashboard.|Stage 6|
|Functional|@wazuh/framework|Parse and send journald Configuration as JSON.|Stage 7|
|Non-functional|@wazuh/core|Regularly pick events from *journald*.|Stage 2|
|Non-functional|@wazuh/core|Limit read to a maximum event count.|Stage 2|
|Non-functional|@wazuh/core|Set the read cursor in the previous position before restarting.|Stage 2|
|Non-functional|@wazuh/core|Set the read cursor at the end, according to the configuration.|Stage 2|
|Non-functional|@wazuh/core|Implement behavior for `<ignore>` and `<restrict>`.|Stage 2|
|Implementation restriction|@wazuh/core|The full log must match the *journald* output.|Stage 2|
|Implementation restriction|@wazuh/core|Use the *journald* API.|Stage 2|
|Implementation restriction|@wazuh/core|Availability restricted to Linux with *systemd*.|Stage 2|
|Implementation restriction|@wazuh/core|Do not support setting overriding or cancelation.|Stage 2|

## Reference

- [sd-journal (www.freedesktop.org)](https://www.freedesktop.org/software/systemd/man/latest/sd-journal.html#)
- [systemd.journal-fields (www.freedesktop.org)](https://www.freedesktop.org/software/systemd/man/latest/systemd.journal-fields.html)

## Approved by

- @vikman90

**Comment by sempervictus** [comment]
I did this for OSSEC a few years back - just haven't had the time/energy to port it over. I spoke with the devs in Slack about this and they said they were looking into doing the portage to Wazuh. If anyone else wants to rewrite a bunch of pointer syntax to convert the OSSEC modality to the way Wazuh modified the C code for the internal logreader pipeline, feel free to ping me for assistance.

**Comment by nnachefski** [comment]
I'm using a custom-built wazuh container that runs as a DaemonSet on OKD worker nodes (Fedora CoreOS).  Fedora uses a journald logging systems.  I need wazuh to be able to parse journald logs (instead of log files) for this to work.  Any idea on when this will enter the roadmap?  Journald has been around for some time already (10 years?!).

**Comment by branchnetconsulting** [comment]
I just had a client today asking me if Wazuh could logcollect directly from journald and I pointed him here.  If there there is more info available on this please do share.

**Comment by vikman90** [comment]
We agree to delay the task delivery to April 18th.

**Comment by V3ntus** [comment]
Echoing interest. The Nix community is progressively porting the Wazuh suite to NixOS and Nixpkgs, but this means Wazuh LogCollector on NixOS will not work without `journald` support (see [Logging in the NixOS manual](https://nlewo.github.io/nixos-manual-sphinx/administration/logging.xml.html))

**Comment by dlouzan** [comment]
@juliancnn @JcabreraC We've seen that this has been recently completed, targetting 4.9; is there any chance that it will be made available or backported on the current 4.8.x release? Missing journald support has been blocking us from properly parsing some relevant logs.

Otherwise, would it be feasible to start testing a 4.9 branch on the agents to verify the functionality with https://github.com/wazuh/wazuh-kubernetes? I know that the documentation states that the agent clients cannot be on a higher version than the server manager, but we'd like to start verifying the use case on our dev/staging systems, if possible at all 🙇  Based on the breaking changes between 4.7 and 4.8, I assume that running a dev version of 4.9 of the server would be more complicated, but perhaps just testing the agent would be "fine".

/cc @bufferoverflow @fh1ch @ercanucan @max-wittig

**Comment by V3ntus** [comment]
Also interested in backporting to 4.8, but it seems the current situation of 4.8 is a mess.

**Comment by bufferoverflow** [comment]
I just saw the MR https://github.com/wazuh/wazuh-kubernetes/pull/726/files which introduces `4.9.0-alpha1` I think offering the  `4.9.0-alpha1`  images on Docker Hub would help to test already.
