### ISSUE TITLE
Fix module import issues by turning the wodles folder into a Python package

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#12874]
| Affected integration |
|---|
| The entire wodle folder |

## Description

During #11940 a new module called `tools.py` was created for Azure integration. Since there is already a module in gcloud called `tools` python started to give problems when handling these imports.

As a solution to this and future problems, as well as to stop using `path.append` and `path.insert` as much as possible, this issue will convert the wodles folder, where all the modules are located, into a python package, so it can be installed in a similar way to what happens with the `wazuh` (framework) and `api` packages in the same repo. This solution will save us problems in the future, when the modules continue to grow.

## Tasks
- [ ] Apply the changes
- [ ] Test in a manager.
- [ ] Test in an agent.
- [ ] Unit tests without failures. Updated if there are any relevant changes.
- [ ] API integration tests without failures. Updated if there are any relevant changes.
- [ ] Update the documentation if necessary.
- [ ] Add entry to the changelog if necessary.

**Comment by CarlosRS9** [comment]
# Status update

To create a custom python package for wodles it would be necessary to move all the contents from the `wodles/` path to a sub folder, in the same way that we have the API package (`api/api/`) and the Framework package (`framework/wazuh/`) set up right now. This would involve moving all the files to a path to be determined, e.g. `wodles/wodles/`. This in turn would have an impact on installation from sources, installation from packages, automatic integration tests and some others. Due to the high impact of this change and the its low priority, we have decided to postpone this action indefinitely. Later, when it is fully critical to create this package, it will be done.

**Comment by davidjiglesias** [comment]
We do not plan to follow this approach.
