### ISSUE TITLE
Investigate about the `region` field

### ISSUE THREAD

**Issue by yanazaeva** [wazuh/wazuh#12937]
It was noticed that while configuring the ECR image scan if we set the `region` field in the `profile` setting, it will not work as expected. Instead of scanning only the mentioned region, it will scan all of them:
![image](https://user-images.githubusercontent.com/67015786/161022019-aaf78351-e9d7-4c4a-a5f1-d6373bff9464.png)

As we can see in the image, after scanning the mentioned region, and printing its vulnerabilities, it will start scanning other regions as well, printing the following message as it won't be able to find the desired log group:
```
{"timestamp":"2022-03-30T11:43:49.169+0000","agent":{"id":"000","name":"default"},"manager":{"name":"default"},"id":"1648640629.12190","full_log":"DEBUG: ++++ The specified \"/aws/ecr/image-scan-findings/framework-test-ecr-repository\" log group does not exist or insufficient privileges to access it.","decoder":{},"location":"aws-s3"}
```

We should investigate this in more detail and check the repercussion this might have. 

## Tasks
- [x] Test in a manager.
- [x] Unit tests without failures. Updated if there are any relevant changes.
- [x] Integration tests without failures. Updated if there are any relevant changes.
- [x] Update the documentation if necessary.
- [x] Add entry to the changelog if necessary.

**Comment by nico-stefani** [comment]
# Issue Update

## The problem

After some debugging of the module, i found that the `region` defined in the `profile` isn't taking account because every single element in

https://github.com/wazuh/wazuh/blob/011dbf0006dc3a30291484fa5c3a271d5924fd2c/wodles/aws/aws_s3.py#L3557-L3559

Is passed to the boto3 session and overrides the value that is declared in the profile.

https://github.com/wazuh/wazuh/blob/011dbf0006dc3a30291484fa5c3a271d5924fd2c/wodles/aws/aws_s3.py#L249-L250
https://github.com/wazuh/wazuh/blob/011dbf0006dc3a30291484fa5c3a271d5924fd2c/wodles/aws/aws_s3.py#L256

## Possible solution

A possible solution should be create the boto3 session before the list iteration and apply the next logic order:

1. Search region/s received through the parameters.
2. Search region/s defined in the profiles, this can be achieved instantiating `boto3.session(profile_name="test")`.
3. None of the above, search all regions.

By doing this, the behavior is equalized with the way that the module process buckets. 
Also this proposed change will be affect the other kind of service available, `inspector`.

**Comment by nico-stefani** [comment]
# Issue Update

After discuss the possible solution with the team we arrive to the conclusion:

To get the regions we follow the next priorities order:
1. Take the regions passed through the `-r` parameter.
2. If the regions wasn't received through parameter, we read the file `~/.aws/config` and get `regions` key taking account of the `profile`.
3. If none of the above are defined, use the default regions.
