### ISSUE TITLE
Add Subscription ID column to the Azure Log Analytics database

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#13051]
| Affected integration |
|---|
| Azure Log Analytics |

## Description

In the past we have had cases where a user wanted to obtain the logs resulting from the same Log Analytics query, but applied to more than one different subscription ID. With our current implementation this is not possible, as it would be an identical query and it's the query the value we use as the primary key in the database.

It doesn't seem possible to get this information at runtime unless the user has provided it using a tag in the `ossec.conf` configuration. We could consider adding a new `subscription_id` tag to the module configuration, to be able to use it in conjunction with the md5 as part of the primary key in the database. In this way it would be possible to run the same query for different subscriptions. It needs to be investigated whether the best option would be to create this additional parameter as well as the impact of such a field. Whether it is present or not, will have to be taken into account, as a bad design could generate duplicate event cases.

Currently a small workaround can be applied to achieve this, which is to have the subscriptionID added as part of the query. This causes the md5 value used as the primary key to differ, so it is possible to have different entries in the database depending on the subscriptionID:

```
    <log_analytics>

        <application_id>5....4</application_id>
        <application_key>0......E</application_key>
        <tenantdomain>wazuh.onmicrosoft.com</tenantdomain>

        <request>
            <tag>azure-activity</tag>
            <query>AzureActivity | where SubscriptionId == '<SubscriptionId-1>' </query>
            <workspace>bc.....be</workspace>
            <time_offset>36h</time_offset>
        </request>

        <request>
            <tag>azure-activity</tag>
            <query>AzureActivity | where SubscriptionId == '<SubscriptionId-2>' </query>
            <workspace>bc.....be</workspace>
            <time_offset>36h</time_offset>
        </request>
    </log_analytics>
```

## Tasks
- [ ] Investigate the best solution to fix this issue
- [ ] Test in a manager.
- [ ] Test in an agent.
- [ ] Unit tests without failures. Updated if there are any relevant changes.
- [ ] Integration tests without failures. Updated if there are any relevant changes.
- [ ] Update the documentation if necessary.
- [ ] Add entry to the changelog if necessary.
