### ISSUE TITLE
Review and update Azure unit tests

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#13390]
| Affected integration |
|---|
| Azure |

## Description

As part of #13387 we need to review the existing unit tests for the Azure module, expanding them to ensure we are close to the 100% coverage and adding new test if required. Currently we only have tests for the ORM.

## Tasks
- [ ] Review existing tests and update them if necessary.
- [ ] Add new tests for the missing coverage.
- [ ] Add entry to the changelog if necessary.

**Comment by CarlosRS9** [comment]
## Status update

The development is finished. The following changes have been applied:

- Added unit tests for `azure-logs.py` module. Current coverage is 97%.
- Small updates to improve existing UT for `orm.py` module and increase its coverage to 100%.
- Small code quality improvements in `azure-logs.py` and `orm.py`.
- A bug where the `azure-logs.db` file was being created when running the entire wodles test suit from the root path has been fixed.

This is the current coverage for the Azure module after the changes:
```
pytest azure  --cov azure --cov-report term-missing --disable-pytest-warnings
======================================= test session starts =======================================
platform linux -- Python 3.10.4, pytest-6.2.5, py-1.11.0, pluggy-0.13.1
rootdir: /home/carlos/GIT/wazuh/wodles
plugins: cov-3.0.0
collected 137 items                                                                               

azure/tests/test_azure.py ................................................................. [ 47%]
.................................................                                           [ 83%]
azure/tests/test_orm.py .......................                                             [100%]

---------- coverage: platform linux, python 3.10.4-final-0 -----------
Name                        Stmts   Miss  Cover   Missing
---------------------------------------------------------
azure/azure-logs.py           435     12    97%   853-867
azure/orm.py                  107      0   100%
azure/tests/test_azure.py     524      0   100%
azure/tests/test_orm.py       121      0   100%
---------------------------------------------------------
TOTAL                        1187     12    99%


======================================= 137 passed in 1.16s =======================================
```

We are finishing manual testing of the module to ensure none of the changes introduced have broken anything.

**Comment by CarlosRS9** [comment]
# Test results

## Graph integration test

Remove `last_dates.json` file and run the integration using `-graph_query 'auditLogs/directoryAudits'` and `--offset 2d`. Only 4 logs should be processed. The `last_dates.json` should be updated as expected.

<details><summary>Command used</summary>

    /var/ossec/wodles/azure/azure-logs --graph --graph_time_offset 2d --graph_query 'auditLogs/directoryAudits' --graph_auth_path /var/ossec/wodles/azure/credentials --graph_tenant_domain wazuh.onmicrosoft.com --graph_tag azure-active_directory -d 2
</details>

<details><summary>command output</summary>

    2022/07/01 12:16:43 azure: INFO: Checking database integrity
    2022/07/01 12:16:43 azure: INFO: Database integrity check finished
    2022/07/01 12:16:43 azure: INFO: Azure Graph starting.
    2022/07/01 12:16:43 azure: INFO: Graph: Getting authentication token.
    2022/07/01 12:16:43 azure: INFO: Graph: Building the url.
    2022/07/01 12:16:43 azure: INFO: 5956825a2e7b02dbebce74ec3c2ac5a5 was not found in the database for graph. Adding it.
    2022/07/01 12:16:43 azure: DEBUG: Attempting to insert row object into graph with md5='5956825a2e7b02dbebce74ec3c2ac5a5', min_date='2022-06-29T12:16:43.673099Z', max_date='2022-06-29T12:16:43.673099Z'
    2022/07/01 12:16:43 azure: INFO: Graph: The search starts for query: 'auditLogs/directoryAudits' using activityDateTime+ge+2022-06-29T12:16:43.706251Z
    2022/07/01 12:16:43 azure: INFO: Graph: The URL is 'https://graph.microsoft.com/v1.0/auditLogs/directoryAudits?&$filter=activityDateTime+ge+2022-06-29T12:16:43.706251Z'
    2022/07/01 12:16:43 azure: INFO: Graph: Pagination starts
    2022/07/01 12:16:44 azure: DEBUG: Attempting to update a graph row object. MD5: '5956825a2e7b02dbebce74ec3c2ac5a5', min_date: '2022-06-29T12:16:43.673099Z', max_date: '2022-07-01T08:50:12.0692661Z'
    2022/07/01 12:16:44 azure: INFO: Graph: Sending event by socket.
    2022/07/01 12:16:44 azure: INFO: Graph: Sending event by socket.
    2022/07/01 12:16:44 azure: INFO: Graph: Sending event by socket.
    2022/07/01 12:16:44 azure: INFO: Graph: Sending event by socket.
    2022/07/01 12:16:44 azure: INFO: Graph: End
</details>

Repeat the test to ensure there are no duplicates. Keep the `last_dates.json` file from the previous test and run the integration using `-graph_query 'auditLogs/directoryAudits` and `--offset 2d`. Same as before.

<details><summary>Command used</summary>

    /var/ossec/wodles/azure/azure-logs --graph --graph_time_offset 2d --graph_query 'auditLogs/directoryAudits' --graph_auth_path /var/ossec/wodles/azure/credentials --graph_tenant_domain wazuh.onmicrosoft.com --graph_tag azure-active_directory -d 2
</details>

<details><summary>command output</summary>

    2022/07/01 12:17:53 azure: INFO: Checking database integrity
    2022/07/01 12:17:53 azure: INFO: Database integrity check finished
    2022/07/01 12:17:53 azure: INFO: Azure Graph starting.
    2022/07/01 12:17:53 azure: INFO: Graph: Getting authentication token.
    2022/07/01 12:17:53 azure: INFO: Graph: Building the url.
    2022/07/01 12:17:53 azure: INFO: Graph: The search starts for query: 'auditLogs/directoryAudits' using activityDateTime+gt+2022-07-01T08:50:12.0692661Z
    2022/07/01 12:17:53 azure: INFO: Graph: The URL is 'https://graph.microsoft.com/v1.0/auditLogs/directoryAudits?&$filter=activityDateTime+gt+2022-07-01T08:50:12.0692661Z'
    2022/07/01 12:17:53 azure: INFO: Graph: Pagination starts
    2022/07/01 12:17:54 azure: INFO: Graph: There are no new results
    2022/07/01 12:17:54 azure: INFO: Graph: End
</details>


### Conclusions
The module worked as expected.



## Log Analytics integration test


Remove the `/var/ossec/wodles/azure/last_dates.json` file and run the command, using `--la_time_offset 30d`. 50 logs should be processed.

<details><summary>Command used</summary></summary>

    /var/ossec/wodles/azure/azure-logs --log_analytics --la_auth_path /var/ossec/wodles/azure/credentials-analytics --la_tenant_domain wazuh.onmicrosoft.com --la_tag azure-activity --la_query "AzureActivity" --workspace bc8d21bd-b966-4a4f-8eed-9e0328720cbe --la_time_offset 30d -d 2
</details>

<details><summary>Command output</summary></summary>

    2022/07/01 12:20:17 azure: INFO: Checking database integrity
    2022/07/01 12:20:17 azure: INFO: Database integrity check finished
    2022/07/01 12:20:17 azure: INFO: Azure Log Analytics starting.
    2022/07/01 12:20:17 azure: INFO: Log Analytics: Getting authentication token.
    2022/07/01 12:20:17 azure: INFO: f90c15b0327962c9e661142547368572 was not found in the database for log_analytics. Adding it.
    2022/07/01 12:20:17 azure: DEBUG: Attempting to insert row object into log_analytics with md5='f90c15b0327962c9e661142547368572', min_date='2022-06-01T12:20:17.818700Z', max_date='2022-06-01T12:20:17.818700Z'
    2022/07/01 12:20:17 azure: INFO: Log Analytics: The search starts for query: 'AzureActivity | order by TimeGenerated asc | where TimeGenerated >= datetime(2022-06-01T12:20:17.860684Z) '
    2022/07/01 12:20:17 azure: INFO: Log Analytics: Sending a request to the Log Analytics API.
    2022/07/01 12:20:22 azure: INFO: Log Analytics: Sending event by socket.
    2022/07/01 12:20:22 azure: INFO: Log Analytics: Sending event by socket.
    2022/07/01 12:20:22 azure: DEBUG: Attempting to update a log_analytics row object. MD5: 'f90c15b0327962c9e661142547368572', min_date: '2022-06-01T12:20:17.818700Z', max_date: '2022-06-03T14:05:13.004Z'
    2022/07/01 12:20:22 azure: INFO: Azure Log Analytics ending.
</details>


### Conclusions
The module worked as expected.





## Storage integration test

Remove `last_dates.json` file and run the integration using `--storage_time_offset 120d`.

Only the files contained in the `test_folder` path should be processed as the other ones have an older `last_modified` datetime.

  
<details>
    <summary>Command used</summary>

    /var/ossec/wodles/azure/azure-logs --storage --storage_time_offset 120d --container frameworktestcontainer --storage_auth_path /var/ossec/wodles/azure/credentials-storage -d 2
</details>

<details><summary>Command output</summary>

    2022/07/01 12:42:18 azure: INFO: Checking database integrity
    2022/07/01 12:42:18 azure: INFO: Database integrity check finished
    2022/07/01 12:42:18 azure: INFO: Azure Storage starting.
    2022/07/01 12:42:18 azure: INFO: Storage: Authenticating.
    2022/07/01 12:42:18 azure: DEBUG: String_to_sign=GET











    x-ms-client-request-id:3e18dd27-f93b-11ec-bfcd-dfb7eff0ce7c
    x-ms-date:Fri, 01 Jul 2022 12:42:18 GMT
    x-ms-version:2019-02-02
    /frameworkteststorage/frameworktestcontainer
    restype:container
    2022/07/01 12:42:18 azure: INFO: Client-Request-ID=3e18dd27-f93b-11ec-bfcd-dfb7eff0ce7c Outgoing request: Method=GET, Path=/frameworktestcontainer, Query={'snapshot': None, 'timeout': None, 'restype': 'container'}, Headers={'x-ms-version': '2019-02-02', 'User-Agent': 'Azure-Storage/2.1.0-2.1.0 (Python CPython 3.9.9; Linux 5.17.13-200.fc35.x86_64)', 'x-ms-client-request-id': '3e18dd27-f93b-11ec-bfcd-dfb7eff0ce7c', 'x-ms-date': 'Fri, 01 Jul 2022 12:42:18 GMT', 'Authorization': 'REDACTED'}.
    2022/07/01 12:42:18 azure: INFO: Client-Request-ID=3e18dd27-f93b-11ec-bfcd-dfb7eff0ce7c Receiving Response: Server-Timestamp=Fri, 01 Jul 2022 12:42:18 GMT, Server-Request-ID=fa1dc451-001e-0053-4448-8d8bc3000000, HTTP Status Code=200, Message=OK, Headers={'content-length': '0', 'last-modified': 'Wed, 20 Oct 2021 07:47:27 GMT', 'etag': '"0x8D9939DDD0A61EA"', 'server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': 'fa1dc451-001e-0053-4448-8d8bc3000000', 'x-ms-client-request-id': '3e18dd27-f93b-11ec-bfcd-dfb7eff0ce7c', 'x-ms-version': '2019-02-02', 'x-ms-lease-status': 'unlocked', 'x-ms-lease-state': 'available', 'x-ms-has-immutability-policy': 'false', 'x-ms-has-legal-hold': 'false', 'x-ms-default-encryption-scope': '$account-encryption-key', 'x-ms-deny-encryption-scope-override': 'false', 'date': 'Fri, 01 Jul 2022 12:42:18 GMT'}.
    2022/07/01 12:42:18 azure: INFO: Storage: Authenticated.
    2022/07/01 12:42:18 azure: INFO: 82e049b81fa6eb88ebf85f1677785f2b was not found in the database for storage. Adding it.
    2022/07/01 12:42:18 azure: DEBUG: Attempting to insert row object into storage with md5='82e049b81fa6eb88ebf85f1677785f2b', min_date='2022-03-03T12:42:18.867366Z', max_date='2022-03-03T12:42:18.867366Z'
    2022/07/01 12:42:18 azure: INFO: Storage: Getting blobs.
    2022/07/01 12:42:18 azure: DEBUG: String_to_sign=GET











    x-ms-client-request-id:3e865351-f93b-11ec-839a-dfb7eff0ce7c
    x-ms-date:Fri, 01 Jul 2022 12:42:18 GMT
    x-ms-version:2019-02-02
    /frameworkteststorage/frameworktestcontainer
    comp:list
    restype:container
    2022/07/01 12:42:18 azure: INFO: Client-Request-ID=3e865351-f93b-11ec-839a-dfb7eff0ce7c Outgoing request: Method=GET, Path=/frameworktestcontainer, Query={'restype': 'container', 'comp': 'list', 'prefix': None, 'delimiter': None, 'marker': None, 'maxresults': None, 'include': None, 'timeout': None}, Headers={'x-ms-version': '2019-02-02', 'User-Agent': 'Azure-Storage/2.1.0-2.1.0 (Python CPython 3.9.9; Linux 5.17.13-200.fc35.x86_64)', 'x-ms-client-request-id': '3e865351-f93b-11ec-839a-dfb7eff0ce7c', 'x-ms-date': 'Fri, 01 Jul 2022 12:42:18 GMT', 'Authorization': 'REDACTED'}.
    2022/07/01 12:42:19 azure: INFO: Client-Request-ID=3e865351-f93b-11ec-839a-dfb7eff0ce7c Receiving Response: Server-Timestamp=Fri, 01 Jul 2022 12:42:18 GMT, Server-Request-ID=fa1dc4ce-001e-0053-3048-8d8bc3000000, HTTP Status Code=200, Message=OK, Headers={'transfer-encoding': 'chunked', 'content-type': 'application/xml', 'server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': 'fa1dc4ce-001e-0053-3048-8d8bc3000000', 'x-ms-client-request-id': '3e865351-f93b-11ec-839a-dfb7eff0ce7c', 'x-ms-version': '2019-02-02', 'date': 'Fri, 01 Jul 2022 12:42:18 GMT'}.
    2022/07/01 12:42:19 azure: INFO: Storage: The search starts from the date: 2022-03-03 12:42:18.901545+00:00 for blobs in container: 'frameworktestcontainer' 
    2022/07/01 12:42:19 azure: INFO: Storage: End
</details>

Keep the `last_dates.json` file and run the same command again to ensure no duplicate logs have been processed.

<details><summary>Command used</summary>

    /var/ossec/wodles/azure/azure-logs --storage --storage_time_offset 120d --container frameworktestcontainer --storage_auth_path /var/ossec/wodles/azure/credentials-storage -d 2
</details>

<details><summary>Command output</summary>


    2022/07/01 12:43:44 azure: INFO: Checking database integrity
    2022/07/01 12:43:44 azure: INFO: Database integrity check finished
    2022/07/01 12:43:44 azure: INFO: Azure Storage starting.
    2022/07/01 12:43:44 azure: INFO: Storage: Authenticating.
    2022/07/01 12:43:44 azure: DEBUG: String_to_sign=GET











    x-ms-client-request-id:7150e6b1-f93b-11ec-8795-ff6e9de33696
    x-ms-date:Fri, 01 Jul 2022 12:43:44 GMT
    x-ms-version:2019-02-02
    /frameworkteststorage/frameworktestcontainer
    restype:container
    2022/07/01 12:43:44 azure: INFO: Client-Request-ID=7150e6b1-f93b-11ec-8795-ff6e9de33696 Outgoing request: Method=GET, Path=/frameworktestcontainer, Query={'snapshot': None, 'timeout': None, 'restype': 'container'}, Headers={'x-ms-version': '2019-02-02', 'User-Agent': 'Azure-Storage/2.1.0-2.1.0 (Python CPython 3.9.9; Linux 5.17.13-200.fc35.x86_64)', 'x-ms-client-request-id': '7150e6b1-f93b-11ec-8795-ff6e9de33696', 'x-ms-date': 'Fri, 01 Jul 2022 12:43:44 GMT', 'Authorization': 'REDACTED'}.
    2022/07/01 12:43:44 azure: INFO: Client-Request-ID=7150e6b1-f93b-11ec-8795-ff6e9de33696 Receiving Response: Server-Timestamp=Fri, 01 Jul 2022 12:43:44 GMT, Server-Request-ID=71fafd03-e01e-0029-7448-8d9683000000, HTTP Status Code=200, Message=OK, Headers={'content-length': '0', 'last-modified': 'Wed, 20 Oct 2021 07:47:27 GMT', 'etag': '"0x8D9939DDD0A61EA"', 'server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': '71fafd03-e01e-0029-7448-8d9683000000', 'x-ms-client-request-id': '7150e6b1-f93b-11ec-8795-ff6e9de33696', 'x-ms-version': '2019-02-02', 'x-ms-lease-status': 'unlocked', 'x-ms-lease-state': 'available', 'x-ms-has-immutability-policy': 'false', 'x-ms-has-legal-hold': 'false', 'x-ms-default-encryption-scope': '$account-encryption-key', 'x-ms-deny-encryption-scope-override': 'false', 'date': 'Fri, 01 Jul 2022 12:43:44 GMT'}.
    2022/07/01 12:43:44 azure: INFO: Storage: Authenticated.
    2022/07/01 12:43:44 azure: INFO: Storage: Getting blobs.
    2022/07/01 12:43:44 azure: DEBUG: String_to_sign=GET











    x-ms-client-request-id:71b7b61d-f93b-11ec-8fbc-ff6e9de33696
    x-ms-date:Fri, 01 Jul 2022 12:43:44 GMT
    x-ms-version:2019-02-02
    /frameworkteststorage/frameworktestcontainer
    comp:list
    restype:container
    2022/07/01 12:43:44 azure: INFO: Client-Request-ID=71b7b61d-f93b-11ec-8fbc-ff6e9de33696 Outgoing request: Method=GET, Path=/frameworktestcontainer, Query={'restype': 'container', 'comp': 'list', 'prefix': None, 'delimiter': None, 'marker': None, 'maxresults': None, 'include': None, 'timeout': None}, Headers={'x-ms-version': '2019-02-02', 'User-Agent': 'Azure-Storage/2.1.0-2.1.0 (Python CPython 3.9.9; Linux 5.17.13-200.fc35.x86_64)', 'x-ms-client-request-id': '71b7b61d-f93b-11ec-8fbc-ff6e9de33696', 'x-ms-date': 'Fri, 01 Jul 2022 12:43:44 GMT', 'Authorization': 'REDACTED'}.
    2022/07/01 12:43:45 azure: INFO: Client-Request-ID=71b7b61d-f93b-11ec-8fbc-ff6e9de33696 Receiving Response: Server-Timestamp=Fri, 01 Jul 2022 12:43:44 GMT, Server-Request-ID=71fafd5f-e01e-0029-4848-8d9683000000, HTTP Status Code=200, Message=OK, Headers={'transfer-encoding': 'chunked', 'content-type': 'application/xml', 'server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': '71fafd5f-e01e-0029-4848-8d9683000000', 'x-ms-client-request-id': '71b7b61d-f93b-11ec-8fbc-ff6e9de33696', 'x-ms-version': '2019-02-02', 'date': 'Fri, 01 Jul 2022 12:43:44 GMT'}.
    2022/07/01 12:43:45 azure: INFO: Storage: The search starts from the date: 2022-03-03 12:43:44.789029+00:00 for blobs in container: 'frameworktestcontainer' 
    2022/07/01 12:43:45 azure: INFO: Storage: End
</details>



##### Conclusions
The module worked as expected.
