### ISSUE TITLE
Add Docker Listener unit tests

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#13391]
| Affected integration |
|---|
| Docker Listener |

## Description

As part of #13387 we need to add unit tests for the Docker Listener module. These tests should have a coverage close to 100% if possible. 

## Tasks
- [x] Apply required changes to the code
- [x] Create the new unit tests
- [x] Add entry to the changelog if necessary

**Comment by CarlosRS9** [comment]
After reviewing the module for this issue we came to the conclusion that it will be necessary to update the code and improve or replace some parts. Due to the nature of these changes this will be done in another issue at a later date. Until then we have proceeded to create the UTs for the current version of this module.

This module did not have any unit tests so it has been necessary to create them from scratch. They are almost finished, except for extending the coverage with tests for the management of some exceptions. No major changes have been applied to the module, only small and very punctual changes.

**Comment by CarlosRS9** [comment]
The development is finished. We have completed the creation of the unit tests for the `DockerListener` module. The current coverage is at `94%`. These are the results:
```
pytest docker-listener  --cov docker-listener --cov-report term-missing --disable-pytest-warnings
====================================== test session starts ======================================
platform linux -- Python 3.10.5, pytest-6.2.5, py-1.11.0, pluggy-0.13.1
rootdir: /home/carlos/GIT/wazuh/wodles
plugins: cov-3.0.0
collected 19 items                                                                              

docker-listener/tests/test_docker_listener.py ...................                         [100%]

---------- coverage: platform linux, python 3.10.5-final-0 -----------
Name                                            Stmts   Miss  Cover   Missing
-----------------------------------------------------------------------------
docker-listener/DockerListener.py                  87      5    94%   19-21, 149-150
docker-listener/tests/test_docker_listener.py     142      0   100%
-----------------------------------------------------------------------------
TOTAL                                             229      5    98%
```

It has been necessary to apply some changes to facilitate the implementation of these tests. Specifically, the `__init__` function of the `DockerListener` class has been modified and the creation of the different threads has been moved to a new function called `start`, which in addition to this task will also be responsible for invoking the `connect` function. 

Finally, we have performed manual tests to ensure the correct functioning of the module after the changes introduced.

We are aware that the current implementation of the module can be improved in certain aspects, but the impact of the changes that the module requires are too big to undertake them in this issue, so issue #14176 has been opened to analyze and implement such improvements where appropriate.

**Comment by CarlosRS9** [comment]
## Tests results

Manual testing was performed to ensure everything works after the change. The tests were carried out using both a Wazuh manager and a Wazuh agent both using the following configuration:
```
<wodle name="docker-listener">
    <interval>30s</interval>
    <attempts>5</attempts>
    <run_on_start>yes</run_on_start>
    <disabled>no</disabled>
</wodle>
```

### Test docker listener using ossec.conf in a manager
Restart Wazuh and check ossec.log to verify the module is running


<details><summary>ossec.log output</summary>

2022/07/07 14:30:55 wazuh-modulesd:docker-listener: INFO: Module finished.
2022/07/07 14:31:07 wazuh-modulesd[3122] main.c:95 at main(): DEBUG: Created new thread for the 'docker-listener' module.
2022/07/07 14:31:07 wazuh-modulesd:docker-listener[3122] wm_docker.c:45 at wm_docker_main(): INFO: Module docker-listener started.
2022/07/07 14:31:07 wazuh-modulesd:docker-listener[3122] wm_docker.c:58 at wm_docker_main(): INFO: Starting to listening Docker events.
2022/07/07 14:31:07 wazuh-modulesd:docker-listener[3122] wm_docker.c:62 at wm_docker_main(): DEBUG: Launching command 'wodles/docker/DockerListener'

</details>



#### Conclusions

The module worked as expected. No errors were present.
