### ISSUE TITLE
Update MITRE DB to v11.2, resolve wrong mappings and include APT emulation rules.

### ISSUE THREAD

**Issue by fabamatic** [wazuh/wazuh#13555]
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.3 | Rules/Decoders | New/Improve |

## Description

Update Wazuh rules using content developed for Feed. Migrate ruleset files from the Feed repository that improve content quality in Wazuh:

### Bugfixes on Windows Rules 

- [x] #13579

#### PRs and Tasks 

- [x] #13622
- [x] #13567

#### Changes
- 0595-win-sysmon_rules.xml
  - [x] https://github.com/wazuh/wazuh/pull/13594
- 0800-sysmon_id_1.xml
  - [x] https://github.com/wazuh/wazuh/pull/13595
- 0810-sysmon_id_3.xml 
  - [x] https://github.com/wazuh/wazuh/pull/13596
- 0820-sysmon_id_7.xml
  - [x] https://github.com/wazuh/wazuh/pull/13630
- 0830-sysmon_id_11.xml
  - [x] https://github.com/wazuh/wazuh/pull/13631
- 0840-win_event_channel.xml
  - [x] https://github.com/wazuh/wazuh/pull/13633
- 0860-sysmon_id_13.xml
  - [x] https://github.com/wazuh/wazuh/pull/13636
- 0870-sysmon_id_8.xml
  - [x] https://github.com/wazuh/wazuh/pull/13637
- 0915-win-powershell_rules.xml
  - [x] https://github.com/wazuh/wazuh/pull/13638
- 0945-sysmon_id_10.xml
  - [x] https://github.com/wazuh/wazuh/pull/13639
- 0950-sysmon_id_20.xml
  - [x] https://github.com/wazuh/wazuh/pull/13673

### Improved testing

- [x] https://github.com/wazuh/wazuh/pull/13597
  - [x] Support for Windows  eventchannel tests
  - [x] Improved reporting
- [x] Update Windows rules .ini test files
