### ISSUE TITLE
Remove standalone option in API integration tests

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#13763]
## Description

The Wazuh cluster will always be enabled and running after the changes in https://github.com/wazuh/wazuh/issues/7108. As a consequence, the `standalone` option in the API integration tests should be removed. 

It is necessary to delete all the related code and check that the tests still work after that. For instance:
https://github.com/wazuh/wazuh/blob/4ad7e9cddfb31b5e0aea978332d2185f00d94f4c/api/test/integration/env/base/manager/entrypoint.sh#L11-L13

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)
