### ISSUE TITLE
Ownership and increased effectiveness for Wazuh Content

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#13760]
## Description
This epic aims to solve wazuh's content management.

It ranges from increasing the time-to-value for which not only a future implementation must be designed, but also a process to streamline the work of the content team to increase the efficiency and effectiveness of detection.

In this epic, the following requirements must be considered.

- [x] Recurrent migration from third party vendors dbs.
- [x] Definition of update processes and content loading.
- [ ] Definition and generalization of an update by date/id of a content in a common way.
- [ ] Definition of a common schema for remote queries on different topics based on event information (malicious image name? command line? vulnerable package? malicious IP?)
- [ ] Design based on these definitions, the solutions for the different actors involved.
- [ ] Implementation of both load tooling and product definitions.

**Comment by Dwordcito** [comment]
# Recurrent migration from third party vendors dbs.
The purpose of this requirement case is to explain the process by which, through different content formats, said information is translated into a common format, and through a normalization process they are separated by type and normalize their schema.


![CONTENT Migration ](https://user-images.githubusercontent.com/14300208/173735761-f2e6e202-bdec-4a52-976d-0b489b4eb80c.png)

#### Normalize
The idea of ​​the normalizer is to converge from different origins to a unified schema that through key fields that are an identifier to check increments, modifications or eliminations between two processes. At two different times.

#### Diff Engine
The next step is to find the increment of this origin, through this difference calculation engine.

#### Entry analysis test
This analysis must be checked by the person in charge of the migration process, to verify that the output is valid, that it has the expected format and is suitable both in its effectiveness and that it is capable of having a correct operation in the scanner engine or engine of analysis.

#### Content Database
Relational database engine, from which the contents are created to be distributed.

**Comment by Dwordcito** [comment]
# Definition of update processes and content loading
### Update processes
![Wazuh Content update process](https://user-images.githubusercontent.com/14300208/173742147-e12a0b78-063b-4e98-9e5d-70b98172a213.png)

### Content loading
TBD

**Comment by Dwordcito** [comment]
To be addressed in https://github.com/wazuh/wazuh/issues/14153
