### ISSUE TITLE
FIM whodata delays packages installation time

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh#13920]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.4 | Wazuh FIM | Manager/Agent | Packages | All |

Hello team,

I observed that the `whodata` option affects the installation and update time of the packages on a server. Here you may check an example:

1. Wazuh agent is up and running with the `whodata` configuration applied:

```
Installed products updated.

Reinstalled:
  selinux-policy-3.14.3-95.el8.noarch    selinux-policy-targeted-3.14.3-95.el8.noarch

Complete!

real    2m20.679s
user    1m37.496s
sys     0m6.213s
```

2. Wazuh agent is not running:

```
Installed products updated.

Reinstalled:
  selinux-policy-3.14.3-95.el8.noarch    selinux-policy-targeted-3.14.3-95.el8.noarch

Complete!

real    1m49.625s
user    1m34.526s
sys     0m5.491s
```

In this example, I used the `selinux` package. Still, I observed the same in other packages and it seems to be related to those agents whose configuration/process is in place in one of the monitored directories, but I could not confirm this.

**Details:**

- OS: RHEL7.9, RHEL8.4, RHEL8.6
```
NAME="Red Hat Enterprise Linux"
VERSION="8.6 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.6 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.6"
```
- Wazuh version: v4.1.4, v4.2.4 and v4.3.4
- Audit version: 2.8 in OS 7.9 and 3.0.7 in OS 8.4-8.6
- No relevant information in kernel, Wazuh, auditd service logs.
- When the agent is running, `wazuh-syscheck` process consumes more CPU than `yum` and the id% of the CPU is higher
![image](https://user-images.githubusercontent.com/23264276/174570909-1c876919-179e-4622-9ed8-59e8b4cebb3f.png)

- It doesn't occur when the agent is not running:
![image](https://user-images.githubusercontent.com/23264276/174571107-e831b66e-16cc-416a-ae76-2bb09a760c26.png)

**Configurations**
_**Internal**_

Regards,

Miguel Casares

## Final conclusions
Hello team, after much research, the audit developers have clarified that the correct use of the dispatcher is to never block the thread that receives the logs in the audit socket. To do this, I propose to create an internal buffer of syscheck that stores the received logs, and another thread is responsible for processing them. This way we can prevent audit from blocking other system processes and control more closely the maximum limit of logs that we will be able to process.

## Proposed solution
In the syscheck whodata code, file syscheck_audit.c, function [audit_read_events](https://github.com/wazuh/wazuh/blob/6cce5b8465ecdc8008950e6fc0a2bfd0ebb251c1/src/syscheckd/whodata/syscheck_audit.c#L507). Here we call the recv function, which receives the audit logs.
We must move the calls to the function audit_parse, which are the ones that process each log, parse it and generate the corresponding event in FIM. Then we need to adapt the code to work with an internal buffer.

## Subtasks

- [ ] https://github.com/wazuh/wazuh-documentation/issues/5941
- [x] https://github.com/wazuh/wazuh-qa/issues/3963
  - [ ] https://github.com/wazuh/wazuh-qa/pull/4485

**Comment by chemamartinez** [comment]
Hi team,

I reproduced the bug in a CentOS 8 agent with the following conditions:
- **OS:** CentOS 8 amd64
- **Wazuh version:** v4.3.6
- **Number of CPUs:** 1
- **RAM:** 1024MB

## Reproducing the bug

To force whodata reaching its limits and stuck other processes that generate a huge amount of audit logs such as `yum`, I added the following rules to `audit`:
```
[root@localhost ~]# auditctl -l
-w /root -p wa -k access
-w /root -p wa -k system-locale
-w /root -p wa -k time-change
-w /root -p wa -k identity
-w /root -p wa -k MAC-policy
-w /root -p wa -k logins
-w /root -p wa -k session
-w /root -p wa -k perm_mod
-w /root -p wa -k privileged
-w /etc -p wa -k access
-w /etc -p wa -k system-locale
-w /etc -p wa -k time-change
-w /etc -p wa -k identity
-w /etc -p wa -k MAC-policy
-w /etc -p wa -k logins
-w /etc -p wa -k session
-w /etc -p wa -k perm_mod
-w /etc -p wa -k privileged
-w /var/log -p wa -k access
-w /var/log -p wa -k system-locale
-w /var/log -p wa -k time-change
-w /var/log -p wa -k identity
-w /var/log -p wa -k MAC-policy
-w /var/log -p wa -k logins
-w /var/log -p wa -k session
-w /var/log -p wa -k perm_mod
-w /var/log -p wa -k privileged
-w /usr -p wa -k access
-w /usr -p wa -k system-locale
-w /usr -p wa -k time-change
-w /usr -p wa -k identity
-w /usr -p wa -k MAC-policy
-w /usr -p wa -k logins
-w /usr -p wa -k session
-w /usr -p wa -k perm_mod
-w /usr -p wa -k privileged
```

All these keys will be included to be read by whodata.

And the following configuration to FIM:
```xml
  <!-- File integrity monitoring -->
  <syscheck>
    ...
    <!-- Directories to check  (perform all possible verifications) -->
    <directories whodata="yes">/etc,/usr/bin,/usr/sbin</directories>
    <directories whodata="yes">/bin,/sbin,/boot</directories>
    <directories whodata="yes">/root</directories>
    ...
    <whodata>
      <audit_key>system-locale,time-change,identity,MAC-policy,logins,session,perm_mod,a$
    </whodata>
    ...
  </syscheck>
```

With that configuration, we exercise `yum` in the following conditions:

**Agent stopped**
```
[root@localhost ~]# time yum reinstall selinux-* -y
...
Reinstalled:
  selinux-policy-3.14.3-104.el8.noarch
  selinux-policy-devel-3.14.3-104.el8.noarch
  selinux-policy-targeted-3.14.3-104.el8.noarch

Complete!

real	1m26.472s
user	1m5.690s
sys	0m6.495s
```

The result is 1.26 minutes to complete the operation.

**Whodata running**
Once we run the agent, we wait until whodata starts to monitor:
```
2022/07/22 16:09:42 wazuh-syscheckd: INFO: (6019): File integrity monitoring real-time Whodata engine started.
```

Repeat the operation of reinstalling the package:
```
[root@localhost ~]# time yum reinstall selinux-* -y
Reinstalled:
  selinux-policy-3.14.3-104.el8.noarch
  selinux-policy-devel-3.14.3-104.el8.noarch
  selinux-policy-targeted-3.14.3-104.el8.noarch

Complete!

real	7m56.113s
user	2m49.951s
sys	0m36.013s
```

The same operation took 7.56 minutes when whodata is overloaded. During this time we can see that the CPU usage of `syscheckd` is high.

## Mitigation

Once the bug is reproduced, let's see if we can mitigate it with the available FIM configuration.

The first option is to apply `max_files_per_second` which was included in 4.2.0 to reduce the FIM footprint when monitoring a large number of files (#6830).

Adding the following configuration to the FIM block:
```
<max_files_per_second>100</max_files_per_second>
```

It speeds up the time of running the `yum` command to 4.48m in the same conditions:
```
time yum reinstall selinux-* -y

Reinstalled:
  selinux-policy-3.14.3-104.el8.noarch
  selinux-policy-devel-3.14.3-104.el8.noarch
  selinux-policy-targeted-3.14.3-104.el8.noarch

Complete!

real	4m48.087s
user	2m9.424s
sys	0m25.634s
```

However, it also makes the baseline scan much slower, we have to look for a coherent value depending on the FIM load.

We can also check [`rt_delay`](https://documentation.wazuh.com/current/user-manual/reference/internal-options.html#syscheck) which is an internal option to add a delay between real-time alerts in milliseconds. It is 5 seconds by default.

When repeating the test with `rt_delay` to its highest value `1000` the result is:
```
[root@localhost ~]# time yum reinstall selinux-* -y
Reinstalled:
  selinux-policy-3.14.3-104.el8.noarch
  selinux-policy-devel-3.14.3-104.el8.noarch
  selinux-policy-targeted-3.14.3-104.el8.noarch

Complete!

real	5m32.936s
user	1m55.942s
sys	0m13.437s
```

Any of these settings seem to mitigate the problem completely.

**Comment by jotacarma90** [comment]
# Issue update
Hi team, I have been investigating this situation thoroughly, I have been using CentOS 8 and Ubuntu 20, both with 2gb RAM and 2 cores, Wazuh agent 4.3.7. I should mention that the first tests were done with CentOS, and I was able to reproduce the problem. Then I managed to reproduce it also with Ubuntu, to rule out reasons.

## Configuration
- Audit rules (`/etc/audit/rules.d/audit.rules`):
```
-w /root -p wa -k access
-w /root -p wa -k system-locale
-w /root -p wa -k time-change
-w /root -p wa -k identity
-w /root -p wa -k MAC-policy
-w /root -p wa -k logins
-w /root -p wa -k session
-w /root -p wa -k perm_mod
-w /root -p wa -k privileged
-w /etc -p wa -k access
-w /etc -p wa -k system-locale
-w /etc -p wa -k time-change
-w /etc -p wa -k identity
-w /etc -p wa -k MAC-policy
-w /etc -p wa -k logins
-w /etc -p wa -k session
-w /etc -p wa -k perm_mod
-w /etc -p wa -k privileged
-w /var/log -p wa -k access
-w /var/log -p wa -k system-locale
-w /var/log -p wa -k time-change
-w /var/log -p wa -k identity
-w /var/log -p wa -k MAC-policy
-w /var/log -p wa -k logins
-w /var/log -p wa -k session
-w /var/log -p wa -k perm_mod
-w /var/log -p wa -k privileged
-w /usr -p wa -k access
-w /usr -p wa -k system-locale
-w /usr -p wa -k time-change
-w /usr -p wa -k identity
-w /usr -p wa -k MAC-policy
-w /usr -p wa -k logins
-w /usr -p wa -k session
-w /usr -p wa -k perm_mod
-w /usr -p wa -k privileged
```
- ossec.conf:
```xml
  <directories whodata="yes">/etc,/usr/bin,/usr/sbin</directories>
  <directories whodata="yes">/bin,/sbin,/boot</directories>
  <directories whodata="yes">/root</directories>

  <whodata>
    <audit_key>access,system-locale,time-change,identity,MAC-policy,logins,session,perm_mod,privileged,access,system-locale,time-change,identity,MAC-policy,logins,session,perm_mod,privileged,access,system-locale,time-change,identity,MAC-policy,logins,session,perm_mod,privileged,access,system-locale,time-change,identity,MAC-policy,logins,session,perm_mod,privileged</audit_key>
  </whodata>
```


## Test result

- Command executed for the test (after researching a lot of packages reinstallation):
`time apt --reinstall install -y gnome*`

- Agent off
```
real	1m6.823s
user	0m38.123s
sys	0m22.216s
```
- Agent on (basic test configuration mentioned)
```
real	2m35.864s
user	0m35.974s
sys	0m29.988s
```
- Agent on, `max_files_per_second` = 50
```
real	2m30.848s
user	0m34.823s
sys	0m30.781s
```
- Agent on, `rt_delay` = 500
```
real	2m23.253s
user	0m35.023s
sys	0m30.260s
```
- Agent on, `max_files_per_second` = 50 and `rt_delay` = 500
```
real	2m11.420s
user	0m35.040s
sys	0m30.413s
```

## Extra

I have tried multiple configurations to better narrow down the problem, but this behavior only appears when using a large number of custom audit keys. For example:
- By removing the `audit_key` block from the configuration, the package reinstallation times return to normal (as with the agent off). 
- I have also tried to saturate syscheck in several ways, monitoring the whole disk with whodata, even adding 60k files so that syscheck does not stop processing, and then use some command that requires a lot of CPU, such as dd (`time dd if=/dev/urandom of=/test/testfile bs=1M count=3000`). But the issue has not been reproduced this way.
- I have added some debug messages along the audit related code (`audit_read_events` and `audit_parse` functions), and I have seen that, for example, in the case of `rt_delay` or `max_files_per_second`, the sleep is done once an event is going to be processed, but with the custom audit keys not all events will be processed, some are filtered out before, which may make these settings not at all helpful.\
- Also checked that the `process_priority` setting of syscheck and the `priority_boost` of auditd have no effect on this issue.
- I have tried to modify the setting q_depth of the audisp configuration file: /etc/audisp/audispd.conf, but it doesn't affect either.
- Throughout all the tests, I have seen a few occasions where the process of reinstalling packages slowed down excessively, even spending more than an hour. These cases appeared when

## Conclusions

After testing, it is confirmed that there seems to be a relationship between the cpu usage of syscheck and the slowdown of package reinstallation. However, even increasing to the maximum the proposed settings does not seem that we can completely eliminate this error, analyzing the code, it is possible that these settings only reduce the processing of some events, since in the case of the audit_keys, syscheck has to read a multitude of logs that then will not be processed.

**Comment by jotacarma90** [comment]
# Issue update 2

I have continued to research, and have found that the audit version is very relevant to this issue. All my previous analysis was done on an Ubuntu 20, which has a version of audit 2.8. On a CentOS 8, the audit version is 3.0.

As of version 3.0 of audit, the auditd and audisp code has been merged, and among other things, the `disp_qos` option has been deprecated. Therefore, for these cases, I have been looking for an alternative to reduce processing times.
I have seen a clear improvement by increasing the internal buffer size of auditd, `backlog_limit` from `/etc/audit/rules.d/audit.rules` (default value 8192). This setting corresponds to the size of the internal auditd queue.

## Test
For this test, I have used the same configuration related to whodata as in the previous test.

- Command executed for the test:
`time yum reinstall -y kernel*`

- Agent off
```
real	1m2.293s
user	0m48.042s
sys	0m17.081s
```
- Agent on, `backlog_limit` default value = 8192
```
real	5m36.130s
user	0m46.740s
sys	0m16.789s
```
- Agent on, `backlog_limit` = 32768
```
real	5m37.339s
user	0m47.395s
sys	0m15.267s
```
- Agent on, `backlog_limit` = 65536
```
real	5m10.840s
user	0m47.341s
sys	0m16.043s
```
- Agent on, `backlog_limit` = 131072
```
real	5m4.738s
user	0m47.552s
sys	0m17.333s
```
- Agent on, `backlog_limit` = 262144
```
real	4m13.215s
user	0m47.770s
sys	0m16.602s
```
- Agent on, `backlog_limit` = 524288
```
real	2m7.544s
user	0m48.645s
sys	0m17.603s
```
- Agent on, `backlog_limit` = 1048576
```
real	1m7.916s
user	0m46.512s
sys	0m16.636s
```

**Comment by jotacarma90** [comment]
# Issue update 3 - Python script

Hello team, 
To finish with the investigation of this issue, I have created a python script to receive the audit messages in the same way as wazuh. I have managed to reproduce the issue in this way.
I created an issue in the audit repository with all the info and specifying how to reproduce the bug this way:
https://github.com/linux-audit/audit-kernel/issues/139

After discussion of a possible workaround we have ruled it out pending a comment from the audit team, because as we can see the blocking in the yum trace happens when the client socket is slower reading logs than audit sends them.

**Comment by MiguelCasaresRobles** [comment]
Just for the record, I tried to use the following option to limit the number of events read with the audit configuration and the issue still persisted:
```
  <max_eps>50</max_eps>
```

**Comment by jotacarma90** [comment]
Delayed the ETA of this issue due to a blockage waiting for the merge of the IT testing issue, by the QA team:
- Issue QA: https://github.com/wazuh/wazuh-qa/issues/3963
- PR QA: https://github.com/wazuh/wazuh-qa/pull/4485

**Comment by uhlhosting** [comment]
@jotacarma90 please consider also this when using disp_qos in future; https://access.redhat.com/solutions/6053441 . It seems to be deprecated in RHEL8. Working fully only in RHEL 7. So that cannot be a solution not even a workaround.

I have the very same issue with Wazuh and FIM, so I had to shutdown FIM, to avoid breaking my wordpress sites durring upgrades. 

In most of the cases, the upgrades could not even complete, were completely destroying the wordpress install. I had to always run manual upgrades from server and remove old plugins. I was about to report this issue when I found this post. I anyone wants more detail to help with debug let me know, on my server its happening at every wordpress upgrade I have when FIM is on.

this is my auditctl -l


```
-w /etc/rc.local -p wa -k possible_rcscript_attack
-a always,exit -F arch=b32 -S execve -F uid=48 -F key=webshell_command_exec
-a always,exit -F arch=b64 -S execve -F uid=48 -F key=webshell_command_exec
-a always,exit -F arch=b64 -S socket -F a0=0xA -F euid=48 -F key=webshell_net_connect
-a always,exit -F arch=b64 -S socket -F a0=0x2 -F euid=48 -F key=webshell_net_connect
-a always,exit -F arch=b32 -S socket -F a0=0xA -F euid=48 -F key=webshell_net_connect
-a always,exit -F arch=b32 -S socket -F a0=0x2 -F euid=48 -F key=webshell_net_connect
-w /etc/ld.so.preload -p wa -k possible_preload_hijack
-w /home/virtual/site1/fst/var/www/html -p wa -k wazuh_fim
-w /home/virtual/site10/fst/var/www/html -p wa -k wazuh_fim
-w /home/virtual/site11/fst/var/www/html -p wa -k wazuh_fim
-w /home/virtual/site12/fst/var/www/html -p wa -k wazuh_fim
-w /home/virtual/site13/fst/var/www/html -p wa -k wazuh_fim
-w /home/virtual/site14/fst/var/www/html -p wa -k wazuh_fim
-w /home/virtual/site15/fst/var/www/html -p wa -k wazuh_fim
-w /home/virtual/site16/fst/var/www/html -p wa -k wazuh_fim
-w /home/virtual/site17/fst/var/www/html -p wa -k wazuh_fim
-w /home/virtual/site18/fst/var/www/html -p wa -k wazuh_fim
-w /home/virtual/site19/fst/var/www/html -p wa -k wazuh_fim
-w /home/virtual/site2/fst/var/www/html -p wa -k wazuh_fim
-w /home/virtual/site20/fst/var/www/html -p wa -k wazuh_fim
-w /home/virtual/site21/fst/var/www/html -p wa -k wazuh_fim
-w /home/virtual/site22/fst/var/www/html -p wa -k wazuh_fim
-w /home/virtual/site23/fst/var/www/html -p wa -k wazuh_fim
-w /home/virtual/site24/fst/var/www/html -p wa -k wazuh_fim
-w /home/virtual/site25/fst/var/www/html -p wa -k wazuh_fim
-w /home/virtual/site26/fst/var/www/html -p wa -k wazuh_fim
-w /home/virtual/site27/fst/var/www/html -p wa -k wazuh_fim
-w /home/virtual/site28/fst/var/www/html -p wa -k wazuh_fim
-w /home/virtual/site29/fst/var/www/html -p wa -k wazuh_fim
-w /home/virtual/site3/fst/var/www/html -p wa -k wazuh_fim
-w /home/virtual/site30/fst/var/www/html -p wa -k wazuh_fim
-w /home/virtual/site4/fst/var/www/html -p wa -k wazuh_fim
-w /home/virtual/site5/fst/var/www/html -p wa -k wazuh_fim
-w /home/virtual/site6/fst/var/www/html -p wa -k wazuh_fim
-w /home/virtual/site7/fst/var/www/html -p wa -k wazuh_fim
-w /home/virtual/site8/fst/var/www/html -p wa -k wazuh_fim
-w /home/virtual/site9/fst/var/www/html -p wa -k wazuh_fim
```

**Comment by jotacarma90** [comment]
Hello @uhlhosting 

Thank you very much for the advice, I will take it into account. It is true that this setting is deprecated, if I remember correctly for the versions of audit 3.0 and higher.
The solution we have finally found is to modify the Wazuh FIM code, implementing an internal queue to handle the audit events, this way the upgrade threads or the system itself will not be blocked. You can see in the PR linked to this issue:
https://github.com/wazuh/wazuh/pull/16200

Thank you,
best regards

**Comment by uhlhosting** [comment]
Will check the solution. Since at this moment. Thus old issue is clearly not fixed. Since it blocking our wordpress upgrades every time they occur.

**Comment by jotacarma90** [comment]
Blocked due to some PR checks failing:
https://github.com/wazuh/wazuh-jenkins/issues/5716

**Comment by jotacarma90** [comment]
Found new problems in build PR checks, it is solved with this PR:
https://github.com/wazuh/wazuh-packages/pull/2533

But we have to wait until the cascade merge brings these changes into master branch
ETA delayed 1 week more.

**Comment by uhlhosting** [comment]
Hi

Seems this issue was very detrimental. I found out that the syscheckd service part of wazuh. Was active even when the wazuh agent was manually stopped. 

I had to uninstall the wazuh agent. To stop it from interfering with out plugin download process on our hosting platform.
