### ISSUE TITLE
Adapt FIM DB to use new setting thread_pool

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#14056]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| [9103-replace-fim-db-dbsync](https://github.com/wazuh/wazuh/tree/9103-replace-fim-db-dbsync) | FIM | All | Sources | All |

# Description

Hello team,
This issue is to implement in FIM the `thread_pool` setting, this functionality is being worked in the issue:
https://github.com/wazuh/wazuh/issues/14025

It is a variable to indicate the number of threads to be used by rsync in the synchronization. We must parse the setting in the configuration and use the rsync constructor to use it. Here is the code used to create rsync handle, line 43:

https://github.com/wazuh/wazuh/blob/3a53012eaf9a8ba8257aee25ce8184aa6a7e5a8f/src/syscheckd/src/db/src/db.cpp#L26-L55

## Configuration example

```xml
  <syscheck>
   
   [...]
   
   <synchronization>
      <enabled>yes</enabled>
      <interval>5m</interval>
      <thread_pool>1</thread_pool>
      <max_eps>10</max_eps>
    </synchronization>
  </syscheck>
```

## Task list

- [x] Parse the setting in the configuration
- [x] Implement in fim_db what is needed to use thread_pool when creating the rsync handle.
- [x] Add/modify the necessary tests
