### ISSUE TITLE
Implement new setting max_interval in FIM synchronization

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#14075]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| [9103-replace-fim-db-dbsync](https://github.com/wazuh/wazuh/tree/9103-replace-fim-db-dbsync) | FIM | All | Sources | All |

# Description

Hello team,
This issue is to implement in FIM the `max_interval` setting. It is linked to the `response_timeout`, which is being worked on in the issue:
https://github.com/wazuh/wazuh/issues/14069

`response_timeout` is responsible for verifying that enough time has passed since the last sync message received. If it is not enough, we skip the next synchronization, and the `interval` configured for this one is duplicated.
Consequently, the new setting `max_interval`, indicates the maximum value that can be assigned to this interval. In addition, when a successful synchronization is performed, the interval will return to its original value.

## Task list

- [ ] Parse the setting in the configuration
- [ ] Implementation of the mechanism
- [ ] Add/modify the necessary tests
