### ISSUE TITLE
Review and improve AWS find_account_ids error management

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#14087]
| Affected integration |
|---|
| AWS |

## Description

During the investigation carried out in https://github.com/wazuh/wazuh/issues/14079 we concluded that we should review and improve the error handling for the `find_account_ids` AWS function in order to show useful information for the user when an exception is caught.

As an example, if we attempt to process ALB logs that are stored inside a custom folder in the bucket but we don't specify the required prefix value as part of the Wazuh configuration then the integration will fail showing the following error message:
```
Invalid type of bucket. The bucket was set up as 'alb' type and this bucket does not contain log files from this type. Try with other type: {'guardduty', 'custom', 'waf', 'vpcflow', 'cloudtrail', 'config'}
```
This generic message does not tell us that the real reason for the failure is that the `bucket/AWSLogs/` path does not exist and that we should check our log path.

## Tasks
- [x] Determine which exceptions should be handled by the function.
- [x] Determine the best solution to handle these kind of exceptions.
- [x] Implement the solution.
- [x] Test in a manager.
- [x] Test in an agent.
- [x] Unit tests without failures. Updated if there are any relevant changes.
- [x] Integration tests without failures. Updated if there are any relevant changes.
- [x] Update the documentation if necessary.
- [x] Add entry to the changelog if necessary.

**Comment by fdalmaup** [comment]
# Issue Update

I have been analyzing the aws-s3.py code in order to determine the exception to be thrown for the case raised. The find_account_ids is not executed in every type of bucket, we should define if the exception should be for all of the types or just the ones that don't describe the failure correctly.

**Comment by fdalmaup** [comment]
# Issue update

I have made a change in the error message printed when the base prefix is not found in the bucket. The error message involving the bucket type has been removed.
The changes have been committed to the `feature/14087-aws-find-account-ids-error-management` branch. Manual tests and Unit tests will be carried out.

**Comment by fdalmaup** [comment]
# AWS Wodle Unit Tests

## Test report
[aws_unit_test.zip](https://github.com/wazuh/wazuh/files/9291713/aws_unit_test.zip)

## Test results

---
| **Test name** | **Pass** | **XPass** | **Skip** | **XFail** | **Fail** | **Issues Ref.** | **Status** |
|--|--|--|--|--|--|--|--|
| aws/tests/test_aws.py | 38 | 0 | 0 | 0 | 0 |  | :green_circle: |

**Comment by fdalmaup** [comment]
# Issue Update

The error message now provides more detail related to the prefix given or not and the type of bucket has been added.

The branch [feature/14087-aws-find-account-ids-error-management](https://github.com/wazuh/wazuh/compare/feature/14087-aws-find-account-ids-error-management) was created to make this modification.
The relevant tests were carried out giving successful results.
