### ISSUE TITLE
Add rules for the RBAC database migration logs

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#14120]
After the development done in the epic https://github.com/wazuh/wazuh/issues/13109, new logs can appear in the `api.log` file due to the RBAC DB migration process.

For instance, for a fresh installation where no migration is needed:

```
2022/05/17 09:53:33 INFO: Checking RBAC database integrity...
2022/05/17 09:53:33 INFO: RBAC database not found. Initializing
2022/05/17 09:53:38 INFO: /var/ossec/api/configuration/security/rbac.db database created successfully
2022/05/17 09:53:38 INFO: RBAC database integrity check finished successfully
```

No migration required (database already created):

```
...
2022/05/23 10:50:42 INFO: /var/ossec/api/configuration/security/rbac.db file was detected
...
```

When a migration is required (no important changes):

```
...
2022/05/23 10:50:07 INFO: /var/ossec/api/configuration/security/rbac.db file was detected
2022/05/23 10:50:07 INFO: RBAC database migration required. Current version is 0 but it should be 1. Upgrading RBAC database to version 1
2022/05/23 10:50:11 INFO: /var/ossec/api/configuration/security/rbac.db database upgraded successfully
...
```

When a migration is required and a resource changes. These logs can appear:

For users:

```
2022/05/23 11:04:45 WARNING: User 102 (example) is part of the new default users. Renaming it to 'example_user'
```

For roles:

```
2022/05/23 11:04:45 WARNING: Role 102 (example) is part of the new default roles. Renaming it to 'example_user'
```

For rules:

```
2022/05/23 11:04:45 WARNING: Rule 102 (example) is part of the new default rules. Attempting to migrate relationships
2022/05/23 11:04:45 INFO: All relationships were migrated to the new rule 36
```

For policies:

```
2022/05/23 11:04:45 WARNING: Policy 102 (example) is part of the new default policies. Attempting to migrate relationships
2022/05/23 11:04:45 INFO: All relationships were migrated to the new policy 36
```

Migration required and a default resource was deleted:

For users and roles:

```
2022/05/23 11:10:05 WARNING: User 5 (example) no longer exists. Removing affected user-role relationships
...
2022/05/23 11:10:05 WARNING: Role 5 (example) no longer exists. Removing affected user-role relationships
```

For roles and policies:

```
2022/05/23 11:10:05 WARNING: Role 5 (example) no longer exists. Removing affected role-policy relationships
...
2022/05/23 11:10:05 WARNING: Policy 5 (example) no longer exists. Removing affected role-policy relationships
```

For roles and rules:

```
2022/05/23 11:10:05 WARNING: Role 5 (example) no longer exists. Removing affected role-rule relationships
...
2022/05/23 11:10:05 WARNING: Rule 5 (example) no longer exists. Removing affected role-rule relationships
```

Errors in the migration process:

```
2022/05/23 11:57:39 ERROR: Error during the database migration. Restoring the previous database file
2022/05/23 11:57:39 ERROR: Error details: [Errno 1] Operation not permitted: '/var/ossec/api/configuration/security/rbac.db'
Error when trying to start the Wazuh API. 2011 - Error while attempting to check RBAC database integrity: [Errno 1] Operation not permitted: '/var/ossec/api/configuration/security/rbac.db'.
```

```
2022/05/23 11:57:39 ERROR: Error retrieving the current Wazuh RBAC database version. Aborting database integrity check
```

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by davidjiglesias** [comment]
Current ruleset already detects this kind of logs:

```
root@wazuh-master:/# /var/ossec/bin/wazuh-logtest
Starting wazuh-logtest v4.3.0
Type one log per line

2022/05/23 11:04:45 WARNING: Policy 102 (example) is part of the new default policies. Attempting to migrate relationships

**Phase 1: Completed pre-decoding.
	full event: '2022/05/23 11:04:45 WARNING: Policy 102 (example) is part of the new default policies. Attempting to migrate relationships'

**Phase 2: Completed decoding.
	name: 'wazuh-api-info'
	event-time: '2022/05/23 11:04:45'
	message: 'Policy 102 (example) is part of the new default policies. Attempting to migrate relationships'
	type: 'WARNING'

**Phase 3: Completed filtering (rules).
	id: '422'
	level: '5'
	description: 'Wazuh API Warning event.'
	groups: '['wazuh_api']'
	firedtimes: '1'
	gpg13: '['3.3', '4.12', '7.1']'
	hipaa: '['164.312.a.1']'
	mail: 'False'
	nist_800_53: '['AC.7', 'SC.5']'
	pci_dss: '['1.3.2', '6.5.10', '7.1', '8.1']'
	tsc: '['cc6.1']'
**Alert to be generated.
```
