### ISSUE TITLE
Vulnerability scanner module

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#14156]
|Part of Epic|
|---|
|#14153|

## Description
Today we have the need to orient the scanning service to events, this is necessary since it is the best way to improve usability to have practically real-time results, this is because having vulnerable applications is at the top of attacker vectors.
Avoiding through early detection that we are vulnerable in the most efficient and effective way is the commitment of this initiative.

## Goals
* Expose interface to capture new packages installed, updated, or removed events.
* Expose interface to capture new hotfixes installed or removed events.
* Expose interfaces to capture feed update events.
* Match between the events described above.
* Distribution of results events.

## Non functional requirements
* Performance
It must have the capacity to be multi-threaded, to make its scan more efficient.
* Footprint
Scan with an origin in memory as many times as possible, and make use of a threshold for it, when opting to disk is exceeded. Maintain a scanning cache for recurring packets.

![image](https://user-images.githubusercontent.com/14300208/177797539-d1dcbaf2-1df1-44f8-9b89-ae8299b4dd5f.png)

### User Stories

1. As a security analyst, I want a vulnerability scanner module that can orchestrate the scanning process.
2. As a system administrator, I want a database feed manager that can efficiently manage the vulnerability feed and keep them up to date.
3. As a security team lead, I want a vulnerability-detector inventory that can store and track identified vulnerabilities, along with relevant details.
4. As a developer, I want the scanner module to support different scanning techniques and provide customizable scanning configurations.
5. As a tester, I want to ensure that the scanner module and its sub-components undergo rigorous testing to guarantee their reliability, accuracy, and performance.

### Proposed Solution

The proposed solution is to develop a vulnerability scanner module with the following three main sub-components:

1. Scanner Orchestrator: This component will handle the orchestration of scanning tasks.

2. Database Feed Manager: This component will be responsible for managing, and updating the vulnerability feed of Wazuh.

3. Vulnerability Detected Inventory: This component will store and track identified vulnerabilities, including relevant details such as vulnerability IDs, severity levels, affected systems, and remediation steps. It will provide an interface for querying and managing the inventory of detected vulnerabilities. This has to be compliant with the fields arranged in the elastic common schema.

## Development issues
  - ### Common tasks
    - #### Design
      - [ ] #17915
    - #### Development
      - [x] #17914
      - [ ] Integrate with the Scanner Orchestrator and Vulnerability Detected Inventory
  - ### Scan orchestrator
    - #### Design
       - [ ] #17901
       - [ ] #17902
       - [ ] #17903
       
    - #### Development
       - [x] #17899
       - [x] #17900
       - [ ] #17916
       - [ ] Develop logic to identify unscanned packages/systems
      
  - ### Database feed manager
    - #### Design
       - [ ] #17904
       - [x] #17905
       - [x] #17906
    - #### Development
       - [x] https://github.com/wazuh/wazuh/issues/17874
       - [x] #17912
       - [x] #17913
       - [x] #19042
       - [x] #19043
       - [x] #19044
       - [x] #19045
       - [x] #19046
       - [x] #19047
       - [x] #19828
       - [x] #19885
    
  - ### VD Inventory
    - #### Design
      - [x] #17907
      - [ ] #17911
    - #### Development
      - [x] #17917
    
  - ### Configuration management
    - #### Design
      - [x] #17910
    - #### Development
      - [x] #18577
      - [x] #18578
      - [x] #19781
      
  - ### Installer
    - #### Development

  - ### QA/Automation
      - [x] #17952 
      - [x] #18042 
      - [x] #18327
      - [x] #18328
      - [x] #18425
      - [x] #18431

- First E2E issues:
   - [x] #20496
   - [x] #20497
   - [x] #20498
   - [x] #20501
   - [x] #20504
   - [x] #20502
   - [x] #20503

**Comment by hitman28594** [comment]
It would be nice if wazuh actually had a vulnerability scanning module or integration. 

The vulnerability detector module is requires an agent to work and leaves wazuh blind to the vulnerabilities on all other non-agent devices. 

It would be nice if wazuh could:
1) run it’s own additional scans against infrastructure and feed the results into vulnerability-detector or syscollector. 
2) ingest Nessus/openvas/qualys reports and feed that into vulnerability-detector.
