### ISSUE TITLE
Review and update DockerListener implementation

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#14176]
| Affected integration |
|---|
| DockerListener |

## Description

During the creation of the unit tests for the DockerListener module in #13391 we have realized it is necessary to review the entire module and make some changes to the implementation, especially with the management of threads. We must make sure that the resources are used correctly and that the possible exceptions that could occur are handled properly.

## Tasks
- [ ] Review the code and determine which changes are required.
- [ ] Apply the changes.
- [ ] Test in a manager.
- [ ] Test in an agent.
- [ ] Update the unit tests to acomodate the new changes.
- [ ] Unit tests without failures.
- [ ] Integration tests without failures. Updated if there are any relevant changes.
- [ ] Update the documentation if necessary.
- [ ] Add entry to the changelog if necessary.

**Comment by fdalmaup** [comment]
# Issue Update

I have been analyzing the code. Some methods could be refactored, like `check_docker_service()` because it verifies the status of the Docker daemon and also assigns the Docker client to fetch the events.
I didn't get the reason why there are two threads and why they are managed the way they do. I`ll continue investigating for a better way to manage them since it is the core of the issue.

**Comment by fdalmaup** [comment]
# Issue Update

After some tests in a dev environment, it was found that the use of the two threads is to have at minimum one of them listening to the events from the Docker service. There is no mechanism (such as `Lock`) to synchronize the threads when accessing the Docker client events.

The DockerListener.py implementation could be carried out based on the Producer-Consumer problem. The consumer in this case would be the `DockerListener` class, in charge of taking docker events and sending them to Wazuh, and the producer would be the Docker service itself, which could be encapsulated in a `DockerService` class.
