### ISSUE TITLE
Test: Ruleset

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#1422]
# Ruleset test

| Version | Revision | Branch |
| --- | --- | --- |
| 3.7.0 | 3701 | 3.7 |

## Unit tests

- [ ] Run unit tests.

## *update_ruleset*

- [ ] Check *major.minor.x*.
- [ ] From specific branch.
- [ ] Every argument.

## JSON plugin decoder

- [ ] Add a static field to the rule description. (https://github.com/wazuh/wazuh/pull/397)
- [ ] Check the offset option to the plugin decoders. (https://github.com/wazuh/wazuh/pull/512)
- [ ] Check the treatment of null fields from events with the option `json_null_field`. (https://github.com/wazuh/wazuh/pull/677)
- [ ] Mix two decoders trying to extend a regex extracting a specific field. (https://github.com/wazuh/wazuh/pull/602)

**Comment by vikman90** [comment]
The ruleset unit test have failed:
```
- [ File = ./tests/cisco_ios.ini ] ---------
------------------------------------------------------------
Failed: Exit code = -11
        Alert     = 8
        Rule      = 20100
        Decoder   = cisco-ios
        Section   = cisco ios ids: sig
        line name = log 1 pass
 
2018/09/24 16:49:52 ossec-testrule: INFO: Started (pid: 3564).
ossec-testrule: Type one log per line.
**Phase 1: Completed pre-decoding.
       full event: 'Sep  1 10:25:29 10.10.10.1 %IPS-4-SIGNATURE: Sig:3051 Subsig:1 Sev:4 TCP Connection Window Size DoS [192.168.100.11:51654 -> 10.10.10.10:4444]'
       timestamp: 'Sep  1 10:25:29'
       hostname: '10.10.10.1'
       program_name: '(null)'
       log: '%IPS-4-SIGNATURE: Sig:3051 Subsig:1 Sev:4 TCP Connection Window Size DoS [192.168.100.11:51654 -> 10.10.10.10:4444]'
**Phase 2: Completed decoding.
       decoder: 'cisco-ios'
       id: '3051'
       srcip: '192.168.100.11'
       srcport: '51654'
       dstip: '10.10.10.10'
       dstport: '4444'
------------------------------------------------------------
Failed: Exit code = -11
        Alert     = 8
        Rule      = 20100
        Decoder   = cisco-ios
        Section   = cisco ios ids: sig
        line name = log 2 pass
 
2018/09/24 16:49:52 ossec-testrule: INFO: Started (pid: 3602).
ossec-testrule: Type one log per line.
**Phase 1: Completed pre-decoding.
       full event: 'Sep  1 10:25:29 10.10.10.1 %IPS-4-SIGNATURE: Sig:3051 Subsig:1 Sev:4 TCP Connection Window Size DoS [192.168.100.11:60797 -> 10.10.10.10:80]'
       timestamp: 'Sep  1 10:25:29'
       hostname: '10.10.10.1'
       program_name: '(null)'
       log: '%IPS-4-SIGNATURE: Sig:3051 Subsig:1 Sev:4 TCP Connection Window Size DoS [192.168.100.11:60797 -> 10.10.10.10:80]'
**Phase 2: Completed decoding.
       decoder: 'cisco-ios'
       id: '3051'
       srcip: '192.168.100.11'
       srcport: '60797'
       dstip: '10.10.10.10'
       dstport: '80'
------------------------------------------------------------
Failed: Exit code = -11
        Alert     = 8
        Rule      = 20100
        Decoder   = cisco-ios
        Section   = cisco ios ids: sig
        line name = log 3 pass
 
2018/09/24 16:49:52 ossec-testrule: INFO: Started (pid: 3603).
ossec-testrule: Type one log per line.
**Phase 1: Completed pre-decoding.
       full event: 'Sep  1 10:25:29 10.10.10.1 %IPS-4-SIGNATURE: Sig:5123 Subsig:2 Sev:5 WWW IIS Internet Printing Overflow [192.168.100.11:60797 -> 10.10.10.10:80]'
       timestamp: 'Sep  1 10:25:29'
       hostname: '10.10.10.1'
       program_name: '(null)'
       log: '%IPS-4-SIGNATURE: Sig:5123 Subsig:2 Sev:5 WWW IIS Internet Printing Overflow [192.168.100.11:60797 -> 10.10.10.10:80]'
**Phase 2: Completed decoding.
       decoder: 'cisco-ios'
       id: '5123'
       srcip: '192.168.100.11'
       srcport: '60797'
       dstip: '10.10.10.10'
       dstport: '80'
..
- [ File = ./tests/proftpd.ini ] ---------
.......
- [ File = ./tests/oscap.ini ] ---------
................................
- [ File = ./tests/modsecurity.ini ] ---------
......
- [ File = ./tests/cimserver.ini ] ---------
..
- [ File = ./tests/vsftpd.ini ] ---------
....
- [ File = ./tests/apache.ini ] ---------
............
- [ File = ./tests/doas.ini ] ---------
....
- [ File = ./tests/dovecot.ini ] ---------
...............
- [ File = ./tests/pam.ini ] ---------
.....
- [ File = ./tests/opensmtpd.ini ] ---------
.......
- [ File = ./tests/nginx.ini ] ---------
............
- [ File = ./tests/sudo.ini ] ---------
------------------------------------------------------------
Failed: Exit code = -11
        Alert     = 4
        Rule      = 5403
        Decoder   = sudo
        Section   = sudo: all
        line name = log 1 pass
 
2018/09/24 16:50:23 ossec-testrule: INFO: Started (pid: 4049).
ossec-testrule: Type one log per line.
**Phase 1: Completed pre-decoding.
       full event: 'Apr 27 15:22:23 niban sudo:     dcid : TTY=pts/4'
       timestamp: 'Apr 27 15:22:23'
       hostname: 'niban'
       program_name: 'sudo'
       log: '    dcid : TTY=pts/4'
**Phase 2: Completed decoding.
       decoder: 'sudo'
       srcuser: 'dcid'
       tty: 'pts/4'
------------------------------------------------------------
Failed: Exit code = -11
        Alert     = 4
        Rule      = 5403
        Decoder   = sudo
        Section   = sudo: all
        line name = log 2 pass
 
2018/09/24 16:50:24 ossec-testrule: INFO: Started (pid: 4050).
ossec-testrule: Type one log per line.
**Phase 1: Completed pre-decoding.
       full event: 'Apr 14 10:59:01 enigma sudo:     dcid : TTY=ttyp3'
       timestamp: 'Apr 14 10:59:01'
       hostname: 'enigma'
       program_name: 'sudo'
       log: '    dcid : TTY=ttyp3'
**Phase 2: Completed decoding.
       decoder: 'sudo'
       srcuser: 'dcid'
       tty: 'ttyp3'
------------------------------------------------------------
Failed: Exit code = -11
        Alert     = 4
        Rule      = 5403
        Decoder   = sudo
        Section   = sudo: all
        line name = log 3 pass
 
2018/09/24 16:50:24 ossec-testrule: INFO: Started (pid: 4051).
ossec-testrule: Type one log per line.
**Phase 1: Completed pre-decoding.
       full event: 'Apr 19 14:52:02 enigma sudo:     dcid : TTY=ttyp3'
       timestamp: 'Apr 19 14:52:02'
       hostname: 'enigma'
       program_name: 'sudo'
       log: '    dcid : TTY=ttyp3'
**Phase 2: Completed decoding.
       decoder: 'sudo'
       srcuser: 'dcid'
       tty: 'ttyp3'
------------------------------------------------------------
Failed: Exit code = -11
        Alert     = 4
        Rule      = 5403
        Decoder   = sudo
        Section   = sudo: all
        line name = log 4 pass
 
2018/09/24 16:50:24 ossec-testrule: INFO: Started (pid: 4052).
ossec-testrule: Type one log per line.
**Phase 1: Completed pre-decoding.
       full event: 'Dec 30 19:36:11 rheltest sudo: cplummer : TTY=pts/2'
       timestamp: 'Dec 30 19:36:11'
       hostname: 'rheltest'
       program_name: 'sudo'
       log: 'cplummer : TTY=pts/2'
**Phase 2: Completed decoding.
       decoder: 'sudo'
       srcuser: 'cplummer'
       tty: 'pts/2'
.
------------------------------------------------------------
Failed: Exit code = -11
        Alert     = 4
        Rule      = 5403
        Decoder   = sudo
        Section   = First time user executed sudo
        line name = log 1 pass
 
2018/09/24 16:50:24 ossec-testrule: INFO: Started (pid: 4056).
ossec-testrule: Type one log per line.
**Phase 1: Completed pre-decoding.
       full event: 'Jun 25 15:48:21 precise32 sudo:  mike : TTY=pts/0'
       timestamp: 'Jun 25 15:48:21'
       hostname: 'precise32'
       program_name: 'sudo'
       log: ' mike : TTY=pts/0'
**Phase 2: Completed decoding.
       decoder: 'sudo'
       srcuser: 'mike'
       tty: 'pts/0'
..
- [ File = ./tests/exim.ini ] ---------
.....
- [ File = ./tests/samba.ini ] ---------
....
- [ File = ./tests/firewalld.ini ] ---------
..
- [ File = ./tests/netscreen.ini ] ---------
....
- [ File = ./tests/web_rules.ini ] ---------
.....
- [ File = ./tests/ossec.ini ] ---------
.....
- [ File = ./tests/syslog.ini ] ---------
.....
- [ File = ./tests/apparmor.ini ] ---------
.....
- [ File = ./tests/cpanel.ini ] ---------
.......
- [ File = ./tests/systemd.ini ] ---------
.
- [ File = ./tests/unbound.ini ] ---------
- [ File = ./tests/named.ini ] ---------
.....
- [ File = ./tests/postfix.ini ] ---------
..
- [ File = ./tests/web_appsec.ini ] ---------
...............................
- [ File = ./tests/rsh.ini ] ---------
..
- [ File = ./tests/su.ini ] ---------
....
------------------------------------------------------------
Failed: Exit code = -11
        Alert     = 4
        Rule      = 5305
        Decoder   = su
        Section   = su: work fts
        line name = log 1 pass
 
2018/09/24 16:50:41 ossec-testrule: INFO: Started (pid: 4157).
ossec-testrule: Type one log per line.
**Phase 1: Completed pre-decoding.
       full event: 'Apr 22 17:51:51 enigma su: dcid to root on /dev/ttyp1'
       timestamp: 'Apr 22 17:51:51'
       hostname: 'enigma'
       program_name: 'su'
       log: 'dcid to root on /dev/ttyp1'
**Phase 2: Completed decoding.
       decoder: 'su'
       srcuser: 'dcid'
       dstuser: 'root'
- [ File = ./tests/sysmon.ini ] ---------
...
- [ File = ./tests/mailscanner.ini ] ---------
.
- [ File = ./tests/sshd.ini ] ---------
...........................
```

Thanks @BraulioV

**Comment by BraulioV** [comment]
Hi guys,

it's a segmentation fault. Here you can see the error after running `ossec-logtest`:

```
# /var/ossec/bin/ossec-logtest
2018/09/24 17:07:34 ossec-testrule: INFO: Started (pid: 2872).
ossec-testrule: Type one log per line.

Sep  1 10:25:29 10.10.10.1 %IPS-4-SIGNATURE: Sig:3051 Subsig:1 Sev:4 TCP Connection Window Size DoS [192.168.100.11:51654 -> 10.10.10.10:4444]


**Phase 1: Completed pre-decoding.
       full event: 'Sep  1 10:25:29 10.10.10.1 %IPS-4-SIGNATURE: Sig:3051 Subsig:1 Sev:4 TCP Connection Window Size DoS [192.168.100.11:51654 -> 10.10.10.10:4444]'
       timestamp: 'Sep  1 10:25:29'
       hostname: '10.10.10.1'
       program_name: '(null)'
       log: '%IPS-4-SIGNATURE: Sig:3051 Subsig:1 Sev:4 TCP Connection Window Size DoS [192.168.100.11:51654 -> 10.10.10.10:4444]'

**Phase 2: Completed decoding.
       decoder: 'cisco-ios'
       id: '3051'
       srcip: '192.168.100.11'
       srcport: '51654'
       dstip: '10.10.10.10'
       dstport: '4444'
Segmentation fault
```

**Comment by adri9valle** [comment]
Updated ruleset from a specific branch issue => ([#215](https://github.com/wazuh/wazuh-ruleset/issues/215))

**Comment by adri9valle** [comment]
### Unit tests  

##### Run unit tests.  
```
[root@manager rules-testing]# pwd
/home/vagrant/wazuh-ruleset/tools/rules-testing
[root@manager rules-testing]# ./runtests.py 
- [ File = ./tests/syslog.ini ] ---------
.....
- [ File = ./tests/su.ini ] ---------
.....
- [ File = ./tests/netscreen.ini ] ---------
....
- [ File = ./tests/postfix.ini ] ---------
..
- [ File = ./tests/firewalld.ini ] ---------
..
- [ File = ./tests/web_rules.ini ] ---------
.....
- [ File = ./tests/sudo.ini ] ---------
........
- [ File = ./tests/vsftpd.ini ] ---------
....
- [ File = ./tests/proftpd.ini ] ---------
.......
- [ File = ./tests/sshd.ini ] ---------
...........................
- [ File = ./tests/nginx.ini ] ---------
............
- [ File = ./tests/cpanel.ini ] ---------
.......
- [ File = ./tests/modsecurity.ini ] ---------
......
- [ File = ./tests/web_appsec.ini ] ---------
...............................
- [ File = ./tests/exim.ini ] ---------
.....
- [ File = ./tests/sysmon.ini ] ---------
...
- [ File = ./tests/named.ini ] ---------
.....
- [ File = ./tests/unbound.ini ] ---------

- [ File = ./tests/apache.ini ] ---------
............
- [ File = ./tests/opensmtpd.ini ] ---------
.......
- [ File = ./tests/doas.ini ] ---------
....
- [ File = ./tests/samba.ini ] ---------
....
- [ File = ./tests/pam.ini ] ---------
.....
- [ File = ./tests/cimserver.ini ] ---------
..
- [ File = ./tests/ossec.ini ] ---------
.....
- [ File = ./tests/oscap.ini ] ---------
................................
- [ File = ./tests/mailscanner.ini ] ---------
.
- [ File = ./tests/rsh.ini ] ---------
..
- [ File = ./tests/cisco_ios.ini ] ---------
.....
- [ File = ./tests/dovecot.ini ] ---------
...............
- [ File = ./tests/apparmor.ini ] ---------
.....
- [ File = ./tests/systemd.ini ] ---------
.
[root@manager rules-testing]# 
```

### update_ruleset  

**issue [#215](https://github.com/wazuh/wazuh-ruleset/issues/215)**

##### Check major.minor.x.  

```
[root@manager decoders]# /var/ossec/bin/update_ruleset -n '3.6'
### Wazuh ruleset ###
ERROR: Upgrade aborted: Unexpected version in the new ruleset. Expected version v3.7.x. Found version v3.6.2
```

##### From specific branch.  

```
[root@manager decoders]# /var/ossec/bin/update_ruleset -n '3.7'
### Wazuh ruleset ###

The following rules will be updated:
	0180-pure-ftpd_rules.xml
	0235-vmware_rules.xml
	0500-owncloud_rules.xml
	0525-openvas_rules.xml
You already have the latest version of rootchecks.

The following decoders will be updated:
	0065-cisco-ios_decoders.xml

OSSEC requires a restart to apply changes.
Do you want to restart OSSEC now? [y/N]: y
wazuh-clusterd not running...
Killing wazuh-modulesd...
Killing ossec-monitord...
Killing ossec-logcollector...
Killing ossec-remoted...
Killing ossec-syscheckd...
Killing ossec-analysisd...
ossec-maild not running...
Killing ossec-execd...
Killing wazuh-db...
Wazuh v3.7.0 Stopped
Starting Wazuh v3.7.0 (maintained by Wazuh Inc.)...
Started wazuh-db...
Started ossec-execd...
Started ossec-analysisd...
Started ossec-syscheckd...
Started ossec-remoted...
Started ossec-logcollector...
Started ossec-monitord...
Started wazuh-modulesd...
Completed.

Ruleset v3.7.0 updated to v3.7.0 successfully
[root@manager decoders]#
```

##### Every argument.  

**`-s` y  `-j`**

```
[root@manager decoders]# /var/ossec/bin/update_ruleset -s wazuh-ruleset-3.7/ -j
{"data": {"new_version": "v3.7.0", "success": true, "restarted": false, "old_version": "v3.7.0", "restart_required": false, "msg": "\nYou already have the latest version of ruleset."}, "error": 0}
```



**`-f`, `-d` y `-n`**

```
[root@manager decoders]# /var/ossec/bin/update_ruleset -f -d -n '3.7'
DEBUG: Arguments: {'source': 'download', 'json': False, 'ossec_path': '/var/ossec', 'force': True, 'url': False, 'branch-name': '3.7', 'debug': True, 'backups': False, 'restart': 'ask'}
### Wazuh ruleset ###
DEBUG: Downloading ruleset from https://github.com/wazuh/wazuh-ruleset/archive/3.7.zip.

The following rules will be updated:
	0010-rules_config.xml
	0015-ossec_rules.xml
	0016-wazuh_rules.xml
	0020-syslog_rules.xml
	0025-sendmail_rules.xml
	0030-postfix_rules.xml
...
...
...

OSSEC requires a restart to apply changes.
Do you want to restart OSSEC now? [y/N]: Do not forget to restart OSSEC to apply changes.

```


#### JSON plugin decoder  

###### Add a static field to the rule description. (#397)  

*local_decoder.xml*  

```xml
<decoder name="demo">
  <prematch>^demo: </prematch>
  <program_name>myapp</program_name>
  <regex offset="after_prematch">^(\S+) (\S+) (\S+) (\S+) (\S+)</regex>
  <order>srcip,action,item,url,arg</order>
</decoder>

```

*local_rules.xml*  
```xml
<decoder name="demo">
  <prematch>^demo: </prematch>
  <program_name>myapp</program_name>
  <regex offset="after_prematch">^(\S+) (\S+) (\S+) (\S+) (\S+)</regex>
  <order>srcip,action,item,url,arg</order>
</decoder>
```  

```xml
<rule id="100001" level="5">
  <decoded_as>demo</decoded_as>
  <description>srcip=$(srcip), action=$(action), item=$(item), url=$(url), dstip=$(dstip), fz=$(fz), k=$k</description>
</rule>

```  

```
[root@manager rules]# /var/ossec/bin/ossec-logtest
2018/10/15 13:00:16 ossec-testrule: INFO: Started (pid: 23640).
ossec-testrule: Type one log per line.

Feb 16 14:00:00 localhost myapp: demo: 1.2.3.4 insert tuple http://example.com 2.3.4.5


**Phase 1: Completed pre-decoding.
       full event: 'Feb 16 14:00:00 localhost myapp: demo: 1.2.3.4 insert tuple http://example.com 2.3.4.5'
       timestamp: 'Feb 16 14:00:00'
       hostname: 'localhost'
       program_name: 'myapp'
       log: 'demo: 1.2.3.4 insert tuple http://example.com 2.3.4.5'

**Phase 2: Completed decoding.
       decoder: 'demo'
       srcip: '1.2.3.4'
       action: 'insert'
       item: 'tuple'
       url: 'http://example.com'
       arg: '2.3.4.5'

**Phase 3: Completed filtering (rules).
       Rule id: '100001'
       Level: '5'
       Description: 'srcip=1.2.3.4, action=insert, item=tuple, url=http://example.com, dstip=, fz=, k=$k'
**Alert to be generated.

```

##### Check the offset option to the plugin decoders. (#512)  

**After pregmatch**  

*local_decoder.xml*  

```
<decoder name="raw_json">
    <program_name>nba_program</program_name>
    <prematch>player_information: "</prematch>
    <plugin_decoder offset="after_prematch">JSON_Decoder</plugin_decoder>
</decoder>
```

*local_rules.xml*  

```
<rule id="100002" level="5">
    <decoded_as>raw_json</decoded_as>
    <description>Raw JSON event</description>
</rule>
```

```
[root@manager rules]# /var/ossec/bin/ossec-logtest
2018/10/15 13:19:14 ossec-testrule: INFO: Started (pid: 24680).
ossec-testrule: Type one log per line.

2018 Apr 04 13:11:52 nba_program: this_is_an_example: " player_information: "{ "name": "Stephen", "surname": "Curry", "team": "Golden State Warriors", "number": 30, "position": "point guard"}


**Phase 1: Completed pre-decoding.
       full event: '2018 Apr 04 13:11:52 nba_program: this_is_an_example: " player_information: "{ "name": "Stephen", "surname": "Curry", "team": "Golden State Warriors", "number": 30, "position": "point guard"}'
       timestamp: '2018 Apr 04 13:11:52'
       hostname: 'manager'
       program_name: 'nba_program'
       log: 'this_is_an_example: " player_information: "{ "name": "Stephen", "surname": "Curry", "team": "Golden State Warriors", "number": 30, "position": "point guard"}'

**Phase 2: Completed decoding.
       decoder: 'raw_json'
       name: 'Stephen'
       surname: 'Curry'
       team: 'Golden State Warriors'
       number: '30'
       position: 'point guard'

**Phase 3: Completed filtering (rules).
       Rule id: '100002'
       Level: '5'
       Description: 'Raw JSON event'
**Alert to be generated.

```

##### Check the treatment of null fields from events with the option json_null_field. (#677) 

*local_decoder.xml*  

```
<decoder name="testdecoder">
  <program_name>^test_program$</program_name>
  <prematch>^{\s*"</prematch>
  <plugin_decoder>JSON_Decoder</plugin_decoder>
  <json_null_field>discard</json_null_field>
</decoder>
```
We can change the field value `json_null_field` to `empty` or `string` for change the null value for a `empty` value or change the null value for the `string` value 'null'.

- `<json_null_field>discard</json_null_field>`
- `<json_null_field>empty</json_null_field>`
- `<json_null_field>string</json_null_field>`


*local_rules.xml*  

```
<rule id="100003" level="5">
    <decoded_as>testdecoder</decoded_as>
    <description>Test json null fields</description>
</rule>
```


- **Discard:**

```
May 25 00:00:00 hostname test_program[0001]: {"date":"2018-05-25","field1":null,"field2":"string"}


**Phase 1: Completed pre-decoding.
       full event: 'May 25 00:00:00 hostname test_program[0001]: {"date":"2018-05-25","field1":null,"field2":"string"}'
       timestamp: 'May 25 00:00:00'
       hostname: 'hostname'
       program_name: 'test_program'
       log: '{"date":"2018-05-25","field1":null,"field2":"string"}'

**Phase 2: Completed decoding.
       decoder: 'testdecoder'
       date: '2018-05-25'
       field2: 'string'

**Phase 3: Completed filtering (rules).
       Rule id: '100003'
       Level: '5'
       Description: 'Test json null fields'
**Alert to be generated.
```

- **Empty:**

```
**Phase 2: Completed decoding.
       decoder: 'testdecoder'
       date: '2018-05-25'
       field1: ''
       field2: 'string'
```

- **String:**

```
**Phase 2: Completed decoding.
       decoder: 'testdecoder'
       date: '2018-05-25'
       field1: 'null'
       field2: 'string'
```

##### Mix two decoders trying to extend a regex extracting a specific field. (#602)  


```
<decoder name="json">
  <prematch>^{\s*"</prematch>
</decoder>

<decoder name="json_child">
  <parent>json</parent>
  <prematch>^{\s*"</prematch>
  <plugin_decoder>JSON_Decoder</plugin_decoder>
</decoder>

<decoder name="json_child">
  <parent>json</parent>
  <regex>@(\S+)"</regex>
  <order>user.email.domain</order>
</decoder>

```

*local_rules.xml*  

```
<rule id="100004" level="5">
    <decoded_as>json</decoded_as>
    <description>Test regex json</description>
</rule>

```

```
[root@manager decoders]# /var/ossec/bin/ossec-logtest 
2018/10/15 14:09:16 ossec-testrule: INFO: Started (pid: 29056).
ossec-testrule: Type one log per line.

{"user": {"name": "John","surname": "Smith","email":"john.smith@example.com"}}


**Phase 1: Completed pre-decoding.
       full event: '{"user": {"name": "John","surname": "Smith","email":"john.smith@example.com"}}'
       timestamp: '(null)'
       hostname: 'manager'
       program_name: '(null)'
       log: '{"user": {"name": "John","surname": "Smith","email":"john.smith@example.com"}}'

**Phase 2: Completed decoding.
       decoder: 'json'
       user.name: 'John'
       user.surname: 'Smith'
       user.email: 'john.smith@example.com'
       user.email.domain: 'example.com'

**Phase 3: Completed filtering (rules).
       Rule id: '100004'
       Level: '5'
       Description: 'Test regex json'
**Alert to be generated.
```

**Comment by adri9valle** [comment]
update rulset => ([#215](https://github.com/wazuh/wazuh-ruleset/issues/215))
