### ISSUE TITLE
Debian Stretch vulnerabilities are no longer available

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#14354]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| All | Vulnerability Detector | Manager | All | Debian Stretch |

### Description

The end of support for Debian 9 Stretch was reached past June, 30th.

![image](https://user-images.githubusercontent.com/29475387/179743933-4a1fd9a5-c109-4062-aab7-c375958df6df.png)

Unfortunately, that means they don't provide the affected packages for Debian Stretch in the [Security tracker feed](https://security-tracker.debian.org/tracker/data/json), which Vulnerability Detector needs to scan Debian agents looking for vulnerabilities in the package inventory.

From the Wazuh side, it is needed to deprecate the support of Debian Stretch in Vulnerability Detector. [Here](https://github.com/wazuh/wazuh/pull/5660) we can see the same task performed for Debian Jessie two years ago.

This has been reported by the community in [this thread](https://groups.google.com/g/wazuh/c/UMAiMpzYUjc) of Google groups.

### DoD

- [x] Avoid indexing the Debian Stretch OVAL feed, used for the CVE metadata
- [x] Remove Debian Stretch from the Vulnerability Detector configuration templates
- [x] Avoid scanning Debian Stretch agents in Vulnerability Detector
- [x] Include a warning message when detected a Debian Stretch agent is being scanned
- [x] Remove integration tests related to Debian Stretch in Vulnerability Detector (https://github.com/wazuh/wazuh-qa/issues/3167)
- [x] Deprecate Debian Stretch in the Wazuh documentation (https://github.com/wazuh/wazuh-documentation/issues/5515)

**Comment by niko2** [comment]
Hi,
Why not keeping these vulnerabilities by downloading oval file and use it locally (offline update with local path) ?
This could be useful for the machines that have not been migrated yet.

**Comment by MarcelKemp** [comment]
Hi @niko2,

We don't maintain vulnerabilities by downloading the OVAL, because on Debian the OVAL is the one that gives us the metadata of the CVEs and the JSON is the one that really tells us if a vulnerability affects a target.

This means that without the `Stretch` target in the JSON, we don't have any vulnerability for that target, so we can't detect if it is vulnerable or not with the data extracted from the OVAL.

So my only recommendation is to upgrade your OS ASAP.

Sorry for the inconvenience!
