### ISSUE TITLE
Improve the ThrottlingException handling in the AWS module

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#14754]
| Affected integration |
|---|
| AWS |

## Description
We need to review the AWS module to determine which parts of its code could be affected by a unhandled `ThrottlingException` in a similar way to what we need in https://github.com/wazuh/wazuh/issues/10754. It seems this affects to the CloudWath Logs implementation only, but we need to confirm it.

Regarding CloudWatchLogs, during https://github.com/wazuh/wazuh/issues/14718 we discovered that the `DescribeLogStreams` can raise `ThrottlingException` too and because of that we should update our module to expect and catch these exceptions.

## Tasks
- [x] Investigate whether this affects only cloudwatch logs or the whole AWS module
- [x] Add the Throttling exception handling to the `DescribeLogStreams` and any other affected function.
- [x] Unit tests without failures. Updated if there are any relevant changes.
- [x] Integration tests without failures. Updated if there are any relevant changes.
- [x] Update the documentation if necessary.
- [x] Add entry to the changelog if necessary.

**Comment by fdalmaup** [comment]
# Issue Update

I have made some changes to the code, specifically in the `get_log_streams` method which is the one that uses `DescribeLogStreams` and raises the `ThrottlingException`. Manual tests have been carried out to verify it works as expected:
```
/var/ossec/wodles/aws/aws-s3 -sr cloudwatchlogs -g 4_4_test -d 2 -p dev -r us-east-1
DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Getting alerts from "us-east-1" region.
DEBUG: only logs: None
DEBUG: Getting log streams for "4_4_test" log group
DEBUG: WARNING: The "describe_log_streams" request was denied due to request throttling. Attempting again.
DEBUG: Found "test_stream" log stream in 4_4_test
DEBUG: Getting data from DB for log stream "test_stream" in log group "4_4_test"
DEBUG: Token: "f/37060011712092978178900541551456153760331542018780004351/s", start_time: "1661828400000", end_time: "1661828400000"
DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_4_test" using token "f/37060011712092978178900541551456153760331542018780004351/s", start_time "1661828400001" and end_time "None"
DEBUG: Saving data for log group "4_4_test" and log stream "test_stream".
DEBUG: The saved values are "{'token': 'f/37060011712092978178900541551456153760331542018780004351/s', 'start_time': 1661828400000, 'end_time': 1661828400001}"
DEBUG: Some data already exists on DB for that key. Updating their values...
DEBUG: Purging the BD
DEBUG: Getting log streams for "4_4_test" log group
DEBUG: Found "test_stream" log stream in 4_4_test
DEBUG: committing changes and closing the DB
```

Any request to the AWS API through the module client could receive a `ThrottlingException` inside a `botocore.exceptions.ClientError` exception. Therefore, every section of code that takes into account this last type of exceptions, like the ones made by `get_log_streams` and  `get_alerts_within_range`, needs to handle the exception.
The methods that could generate this AWS service exceptions are:
- AWSBucket.check_bucket
- AWSServerAccess.check_bucket
- WazuhIntegration.get_client

**Comment by fdalmaup** [comment]
# Issue Update

After discussing with the team, we came to the conclusion that it would be best to update the module so that the retry connections due to `ThrottlingException` are handled by Boto3 and not manually by the wodle. The following link related to this topic [Retries](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html) will be investigated and used as a base for the possible update

**Comment by fdalmaup** [comment]
# Issue Update

The code has been modified so the Boto3 session, when getting the client for the connection, defines the `retry` configurations with `max_attempts` and `mode` values. The default values are 10 and `standard`. The former, as explained in the link attached in the previous update, defines which retry mode to use being `legacy` and `adaptive` the other two.

For the manual tests, a `max_attempts` value of 2 was used. The results were:
```
/var/ossec/wodles/aws/aws-s3 -sr cloudwatchlogs -g 4_4_test -d 2 -p dev -r us-east-1
DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Getting alerts from "us-east-1" region.
DEBUG: only logs: None
DEBUG: Getting log streams for "4_4_test" log group
DEBUG: ERROR: The "get_log_streams" request failed: An error occurred (ThrottlingException) when calling the DescribeLogStreams operation (reached max retries: 2): Rate exceeded
DEBUG: committing changes and closing the DB
```

After the `retry` configurations base test, two parameters have been added to the script. These are -rM /--retry_mode and -rm/--retry_max_attempts and didn't affect the correct functioning of the module:
<details><summary>Results</summary>

    /var/ossec/wodles/aws/aws-s3 -rM standard -rm 3 -sr cloudwatchlogs -g 4_4_test -d 2 -p dev -r us-east-1
    DEBUG: +++ Debug mode on - Level: 2
    DEBUG: +++ Getting alerts from "us-east-1" region.
    DEBUG: only logs: None
    DEBUG: Getting log streams for "4_4_test" log group
    DEBUG: Found "test_stream" log stream in 4_4_test
    DEBUG: Getting data from DB for log stream "test_stream" in log group "4_4_test"
    DEBUG: Token: "None", start_time: "1661914800000", end_time: "1661914800002"
    DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_4_test" using token "None", start_time "1661914800003" and end_time "None"
    DEBUG: Saving data for log group "4_4_test" and log stream "test_stream".
    DEBUG: The saved values are "{'token': None, 'start_time': 1661914800000, 'end_time': 1661914800003}"
    DEBUG: Some data already exists on DB for that key. Updating their values...
    DEBUG: Purging the BD
    DEBUG: Getting log streams for "4_4_test" log group
    DEBUG: Found "test_stream" log stream in 4_4_test
    DEBUG: committing changes and closing the DB

</details>

Results when no parameters are indicated and no `~/.aws/config` overrides them:
<details><summary>Results</summary>

    /var/ossec/wodles/aws/aws-s3 -sr cloudwatchlogs -g 4_4_test -d 2 -p dev -r us-east-1
    DEBUG: +++ Debug mode on - Level: 2
    DEBUG: +++ Getting alerts from "us-east-1" region.
    DEBUG: only logs: None
    DEBUG: +++ Table does not exist; create
    DEBUG: Getting log streams for "4_4_test" log group
    DEBUG: ERROR: The "get_log_streams" request failed: An error occurred (ThrottlingException) when calling the DescribeLogStreams operation (reached max retries: 4): Rate exceeded
    DEBUG: committing changes and closing the DB

</details>

Results writing the `~/.aws/config` file:
<details><summary>config</summary>

    [profile dev]
    region=us-east-1
    max_attempts=2
    retry_mode=standard

</details>

<details><summary>Results</summary>

      /var/ossec/wodles/aws/aws-s3 -sr cloudwatchlogs -g 4_4_test -d 2 -p dev -r us-east-1
      DEBUG: +++ Debug mode on - Level: 2
      DEBUG: +++ Getting alerts from "us-east-1" region.
      DEBUG: only logs: None
      DEBUG: Getting log streams for "4_4_test" log group
      DEBUG: ERROR: The "get_log_streams" request failed: An error occurred (ThrottlingException) when calling the DescribeLogStreams operation (reached max retries: 1): Rate exceeded
      DEBUG: committing changes and closing the DB

</details>

**Comment by fdalmaup** [comment]
# Issue Update

The previously developed parameters for the script have been removed because those parameters were not going to be configured in the wodle section of  `ossec.conf` file and we should avoid new parameters unless it is strictly needed.

The code now verifies if the `~/.aws/config` file exists. If it does, then it uses the `mode` and `max_attempts` values defined inside of it. In case it does not exist, then the default values are defined as `max_attempts` = 10 and `mode` equal `standard`.
Results when no `config` file is defined:
```
/var/ossec/wodles/aws/aws-s3 -sr cloudwatchlogs -g 4_4_test -d 2 -p dev -r us-east-1
DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Getting alerts from "us-east-1" region.
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: only logs: None
DEBUG: Getting log streams for "4_4_test" log group
DEBUG: Found "test_stream" log stream in 4_4_test
DEBUG: Getting data from DB for log stream "test_stream" in log group "4_4_test"
DEBUG: Token: "None", start_time: "1662001200000", end_time: "1662001200007"
DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_4_test" using token "None", start_time "1662001200008" and end_time "None"
DEBUG: Saving data for log group "4_4_test" and log stream "test_stream".
DEBUG: The saved values are "{'token': None, 'start_time': 1662001200000, 'end_time': 1662001200008}"
DEBUG: Some data already exists on DB for that key. Updating their values...
DEBUG: Purging the BD
DEBUG: Getting log streams for "4_4_test" log group
DEBUG: Found "test_stream" log stream in 4_4_test
DEBUG: committing changes and closing the DB
```

Results when `config` file exists:
```
/var/ossec/wodles/aws/aws-s3 -sr cloudwatchlogs -g 4_4_test -d 2 -p dev -r us-east-1
DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Getting alerts from "us-east-1" region.
DEBUG: Found configuration for connection retries in ~/.aws/config
DEBUG: only logs: None
DEBUG: Getting log streams for "4_4_test" log group
DEBUG: Found "test_stream" log stream in 4_4_test
DEBUG: Getting data from DB for log stream "test_stream" in log group "4_4_test"
DEBUG: Token: "None", start_time: "1662001200000", end_time: "1662001200006"
DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_4_test" using token "None", start_time "1662001200007" and end_time "None"
```
Results when `config` file exists and a `ThrottlingException` is triggered:
```
/var/ossec/wodles/aws/aws-s3 -sr cloudwatchlogs -g 4_4_test -d 2 -p dev -r us-east-1
DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Getting alerts from "us-east-1" region.
DEBUG: Found configuration for connection retries in ~/.aws/config
DEBUG: only logs: None
DEBUG: Getting log streams for "4_4_test" log group
DEBUG: ERROR: The "get_log_streams" request failed: An error occurred (ThrottlingException) when calling the DescribeLogStreams operation (reached max retries: 1): Rate exceeded
DEBUG: committing changes and closing the DB
```


Unit tests and Manual tests will be carried out to check the correct operation of the module.
The documentation will be updated to explain the user how to define this values.

**Comment by fdalmaup** [comment]
# AWS Wodle Unit Tests
## Test report
[aws_unit_tests.zip](https://github.com/wazuh/wazuh/files/9471411/aws_unit_tests.zip)

## Test results

---
| **Test name** | **Pass** | **XPass** | **Skip** | **XFail** | **Fail** | **Issues Ref.** | **Status** |
|--|--|--|--|--|--|--|--|
| aws/tests/test_aws.py | 38 | 0 | 0 | 0 | 0 |  | :green_circle: |

**Comment by fdalmaup** [comment]
# Module Manual Testing

A test is considered valid if the following conditions are met:

- The expected result described in the test itself is met.
- The expected amount of events were sent to `analysisd`.
- The expected output was present in the `{wazuh_path}/logs/ossec.log` file.

The data available in our Wazuh-dev environment for each of these supported services will be used. Additional logs may be created if they are necessary or there is insufficient data for testing.

To be able to replicate the `ThrottlingException` we created a custom script that sends request to AWS, so more that 10 requests per second were made. Having both this custom script and the Wazuh AWS module at the same time results in the expected ThrottlingException being raised. 

## CloudWatch Logs

### Test without specifying a `~/.aws/config` file
Remove the `/var/ossec/wodles/aws/aws_services.db` file and run the module using the following command to obtain every log from the Cloudwatch Logs log group for the given date.

Use the command
```
/var/ossec/wodles/aws/aws-s3 -sr cloudwatchlogs -g 4_4_test -d 2 -s 2022-JUL-27 -p dev -r us-east-1
```
<details><summary>Command output</summary>

    /var/ossec/wodles/aws/aws-s3 -sr cloudwatchlogs -g 4_4_test -d 2 -s 2022-JUN-26 -p dev -r us-east-1
    DEBUG: +++ Debug mode on - Level: 2
    DEBUG: +++ Getting alerts from "us-east-1" region.
    DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
    DEBUG: only logs: 1656201600000
    DEBUG: +++ Table does not exist; create
    DEBUG: Getting log streams for "4_4_test" log group
    DEBUG: Found "test_stream" log stream in 4_4_test
    DEBUG: Getting data from DB for log stream "test_stream" in log group "4_4_test"
    DEBUG: Token: "None", start_time: "None", end_time: "None"
    DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_4_test" using token "None", start_time "1656201600000" and end_time "None"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: The message is "test log 01"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: The message is "test log 02"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: The message is "test log 03"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: The message is "test log 04"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: The message is "test log 05"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: The message is "test log 06"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: The message is "test log 07"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: The message is "test log 08"
    DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_4_test" using token "f/37005045211641564753592332036677569118654559889967742976/s", start_time "1656201600000" and end_time "None"
    DEBUG: Saving data for log group "4_4_test" and log stream "test_stream".
    DEBUG: The saved values are "{'token': 'f/37005045211675015869384080449614511648105350264348704767/s', 'start_time': 1656201600000, 'end_time': 1659363616875}"
    DEBUG: Purging the BD
    DEBUG: Getting log streams for "4_4_test" log group
    DEBUG: Found "test_stream" log stream in 4_4_test
    DEBUG: committing changes and closing the DB

</details>

Keep the database file and run the same command again to ensure no duplicate logs are processed. Use the same only_logs_after parameter.
<details><summary>Command output</summary>

    /var/ossec/wodles/aws/aws-s3 -sr cloudwatchlogs -g 4_4_test -d 2 -s 2022-JUN-26 -p dev -r us-east-1
    DEBUG: +++ Debug mode on - Level: 2
    DEBUG: +++ Getting alerts from "us-east-1" region.
    DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
    DEBUG: only logs: 1656201600000
    DEBUG: Getting log streams for "4_4_test" log group
    DEBUG: Found "test_stream" log stream in 4_4_test
    DEBUG: Getting data from DB for log stream "test_stream" in log group "4_4_test"
    DEBUG: Token: "f/37005045211675015869384080449614511648105350264348704767/s", start_time: "1656201600000", end_time: "1659363616875"
    DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_4_test" using token "f/37005045211675015869384080449614511648105350264348704767/s", start_time "1659363616876" and end_time "None"
    DEBUG: Saving data for log group "4_4_test" and log stream "test_stream".
    DEBUG: The saved values are "{'token': 'f/37005045211675015869384080449614511648105350264348704767/s', 'start_time': 1656201600000, 'end_time': 1659363616876}"
    DEBUG: Some data already exists on DB for that key. Updating their values...
    DEBUG: Purging the BD
    DEBUG: Getting log streams for "4_4_test" log group
    DEBUG: Found "test_stream" log stream in 4_4_test
    DEBUG: committing changes and closing the DB

</details>


### Test specifying a `~/.aws/config` file

Remove the `/var/ossec/wodles/aws/aws_services.db` file and define `mode=standard` and `max_attempts=2` in the `~/.aws/config` file. 

<details><summary>~/.aws/config</summary>

    [profile dev]
    region=us-east-1
    max_attempts=2
    retry_mode=standard

</details>

Then run the module using the following command for each scenario: not having and having the `ThrottlingException`

Use the command
```
/var/ossec/wodles/aws/aws-s3 -sr cloudwatchlogs -g 4_4_test -d 2 -s 2022-JUL-27 -p dev -r us-east-1
```

#### No throttling generated

<details><summary>Command output</summary>

    /var/ossec/wodles/aws/aws-s3 -sr cloudwatchlogs -g 4_4_test -d 2 -s 2022-JUN-26 -p dev -r us-east-1
    DEBUG: +++ Debug mode on - Level: 2
    DEBUG: +++ Getting alerts from "us-east-1" region.
    DEBUG: Found configuration for connection retries in ~/.aws/config
    DEBUG: only logs: 1656201600000
    DEBUG: +++ Table does not exist; create
    DEBUG: Getting log streams for "4_4_test" log group
    DEBUG: Found "test_stream" log stream in 4_4_test
    DEBUG: Getting data from DB for log stream "test_stream" in log group "4_4_test"
    DEBUG: Token: "None", start_time: "None", end_time: "None"
    DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_4_test" using token "None", start_time "1656201600000" and end_time "None"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: The message is "test log 01"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: The message is "test log 02"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: The message is "test log 03"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: The message is "test log 04"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: The message is "test log 05"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: The message is "test log 06"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: The message is "test log 07"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: The message is "test log 08"
    DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_4_test" using token "f/37005045211641564753592332036677569118654559889967742976/s", start_time "1656201600000" and end_time "None"
    DEBUG: Saving data for log group "4_4_test" and log stream "test_stream".
    DEBUG: The saved values are "{'token': 'f/37005045211675015869384080449614511648105350264348704767/s', 'start_time': 1656201600000, 'end_time': 1659363616875}"
    DEBUG: Purging the BD
    DEBUG: Getting log streams for "4_4_test" log group
    DEBUG: Found "test_stream" log stream in 4_4_test
    DEBUG: committing changes and closing the DB

</details>


#### Throttling generated

<details><summary>Command output</summary>

    /var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -sr cloudwatchlogs -g 4_4_test -d 2 -s 2022-JUN-26 -p dev -r us-east-1
    DEBUG: +++ Debug mode on - Level: 2
    DEBUG: +++ Getting alerts from "us-east-1" region.
    DEBUG: Found configuration for connection retries in ~/.aws/config
    DEBUG: only logs: 1656201600000
    DEBUG: Getting log streams for "4_4_test" log group
    DEBUG: ERROR: The "get_log_streams" request failed: An error occurred (ThrottlingException) when calling the DescribeLogStreams operation (reached max retries: 1): Rate exceeded
    DEBUG: committing changes and closing the DB

</details>

**Comment by fdalmaup** [comment]
# Test the module in an agent

Deploy an agent and install the required dependencies described in the official Wazuh documentation, then run the module adding the following configuration to the ossec.conf:

<details>
    <summary>Configuration</summary>

    <wodle name="aws-s3">
        <disabled>no</disabled>
        <remove_from_bucket>no</remove_from_bucket>
        <interval>10m</interval>
        <run_on_start>yes</run_on_start>
        <skip_on_error>no</skip_on_error>

        <bucket type="cloudtrail">
           <aws_profile>dev</aws_profile>
           <name>wazuh-aws-wodle-cloudtrail</name>
           <only_logs_after>2021-NOV-21</only_logs_after>
        </bucket>
        
        <service type="cloudwatchlogs">
            <aws_profile>dev</aws_profile>
            <aws_log_groups>4_4_test</aws_log_groups>
            <only_logs_after>2022-JUL-20</only_logs_after>
            <regions>us-east-1</regions>
        </service>
    </wodle>
</details>

## Test without specifying a ~/.aws/config file

<details><summary>Output</summary>

  2022/09/01 17:54:51 wazuh-modulesd:aws-s3[6670] wm_aws.c:59 at wm_aws_main(): INFO: Module AWS started
  2022/09/01 17:54:51 wazuh-modulesd:aws-s3[6670] wm_aws.c:81 at wm_aws_main(): INFO: Starting fetching of logs.
  2022/09/01 17:54:51 wazuh-modulesd:aws-s3[6670] wm_aws.c:133 at wm_aws_main(): INFO: Executing Bucket Analysis: (Bucket: wazuh-aws-wodle-cloudtrail, Type: cloudtrail, Profile: dev)
  2022/09/01 17:54:51 wazuh-modulesd:aws-s3[6670] wm_aws.c:328 at wm_aws_run_s3(): DEBUG: Create argument list
  2022/09/01 17:54:51 wazuh-modulesd:aws-s3[6670] wm_aws.c:443 at wm_aws_run_s3(): DEBUG: Launching S3 Command: wodles/aws/aws-s3 --bucket wazuh-aws-wodle-cloudtrail --aws_profile dev --only_logs_after 2021-NOV-21 --type cloudtrail --debug 2
  2022/09/01 17:54:57 wazuh-modulesd:aws-s3[6670] wm_aws.c:483 at wm_aws_run_s3(): DEBUG: Bucket:  -  OUTPUT: DEBUG: +++ Debug mode on - Level: 2
  DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
  2022/09/01 17:54:57 wazuh-modulesd:aws-s3[6670] wm_aws.c:168 at wm_aws_main(): INFO: Executing Service Analysis: (Service: cloudwatchlogs, Profile: dev)
  2022/09/01 17:54:57 wazuh-modulesd:aws-s3[6670] wm_aws.c:507 at wm_aws_run_service(): DEBUG: Create argument list
  2022/09/01 17:54:57 wazuh-modulesd:aws-s3[6670] wm_aws.c:611 at wm_aws_run_service(): DEBUG: Launching S3 Command: wodles/aws/aws-s3 --service cloudwatchlogs --aws_profile dev --only_logs_after 2022-JUL-20 --regions us-east-1 --aws_log_groups 4_4_test --debug 2
  2022/09/01 17:55:00 wazuh-modulesd:aws-s3[6670] wm_aws.c:652 at wm_aws_run_service(): DEBUG: Service: cloudwatchlogs  -  OUTPUT: DEBUG: +++ Debug mode on - Level: 2
  DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
  2022/09/01 17:55:00 wazuh-modulesd:aws-s3[6670] wm_aws.c:173 at wm_aws_main(): INFO: Fetching logs finished.
  2022/09/01 17:55:00 wazuh-modulesd:aws-s3[6670] wm_aws.c:77 at wm_aws_main(): DEBUG: Sleeping until: 2022/09/01 18:04:51

</details>


## Test specifying a ~/.aws/config file

<details><summary>~/.aws/config</summary>
    [profile dev]
    region=us-east-1
    max_attempts=2
    retry_mode=standard
</details>

<details><summary>Output</summary>

    2022/09/01 17:46:42 wazuh-modulesd:aws-s3[5263] wm_aws.c:59 at wm_aws_main(): INFO: Module AWS started
    2022/09/01 17:46:42 wazuh-modulesd:aws-s3[5263] wm_aws.c:81 at wm_aws_main(): INFO: Starting fetching of logs.
    2022/09/01 17:46:42 wazuh-modulesd:aws-s3[5263] wm_aws.c:133 at wm_aws_main(): INFO: Executing Bucket Analysis: (Bucket: wazuh-aws-wodle-cloudtrail, Type: cloudtrail, Profile: dev)
    2022/09/01 17:46:42 wazuh-modulesd:aws-s3[5263] wm_aws.c:328 at wm_aws_run_s3(): DEBUG: Create argument list
    2022/09/01 17:46:42 wazuh-modulesd:aws-s3[5263] wm_aws.c:443 at wm_aws_run_s3(): DEBUG: Launching S3 Command: wodles/aws/aws-s3 --bucket wazuh-aws-wodle-cloudtrail --aws_profile dev --only_logs_after 2021-NOV-21 --type cloudtrail --debug 2
    2022/09/01 17:46:48 wazuh-modulesd:aws-s3[5263] wm_aws.c:483 at wm_aws_run_s3(): DEBUG: Bucket:  -  OUTPUT: DEBUG: +++ Debug mode on - Level: 2
    DEBUG: Found configuration for connection retries in ~/.aws/config
    2022/09/01 17:46:48 wazuh-modulesd:aws-s3[5263] wm_aws.c:168 at wm_aws_main(): INFO: Executing Service Analysis: (Service: cloudwatchlogs, Profile: dev)
    2022/09/01 17:46:48 wazuh-modulesd:aws-s3[5263] wm_aws.c:507 at wm_aws_run_service(): DEBUG: Create argument list
    2022/09/01 17:46:48 wazuh-modulesd:aws-s3[5263] wm_aws.c:611 at wm_aws_run_service(): DEBUG: Launching S3 Command: wodles/aws/aws-s3 --service cloudwatchlogs --aws_profile dev --only_logs_after 2022-JUL-20 --regions us-east-1 --aws_log_groups 4_4_test --debug 2
    2022/09/01 17:46:50 wazuh-modulesd:aws-s3[5263] wm_aws.c:652 at wm_aws_run_service(): DEBUG: Service: cloudwatchlogs  -  OUTPUT: DEBUG: +++ Debug mode on - Level: 2
    DEBUG: Found configuration for connection retries in ~/.aws/config
    2022/09/01 17:46:51 wazuh-modulesd:aws-s3[5263] wm_aws.c:173 at wm_aws_main(): INFO: Fetching logs finished.
    2022/09/01 17:46:51 wazuh-modulesd:aws-s3[5263] wm_aws.c:77 at wm_aws_main(): DEBUG: Sleeping until: 2022/09/01 17:56:42

</details>

## Conclusions

The module worked as expected. The events were sent to the analysis engine with no duplicates.

**Comment by fdalmaup** [comment]
# Issue Update

The `ThrottlingException` is an AWS service exception, which is not directly generated by the Boto3 client. As defined in the [documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/error-handling.html#botocore-exceptions) Boto3 classifies all AWS service errors and exceptions as `ClientError` exceptions. This is a general exception when an error response is provided by an AWS service to the Boto3 client’s request. Therefore, the management of these exceptions was added to the code to raise descriptive messages to the user when needed.
The exception rising was only tested in the `CloudWatch` logs case because it was not possible to saturate the environment in the case of the other services. This may be due the amount of calls needed by the `AWSCloudWatchLogs` class.
