### ISSUE TITLE
Normalize WAZUH_MANAGER variable separator in Windows and Linux

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#14844]
Hello all,

## Description

We come from https://github.com/wazuh/wazuh-packages/issues/1491
We have detected a difference between separator `;` and `,` in Windows and Linux deployment variable `WAZUH_MANAGER`.
This problem is already solved in previous PRs but we have detected that it is not included in the last releases 4.4+

## Tasks
- [ ] Manage if we will support both separators or we will change directly to `,` in Windows
- [ ] Include the specified modification inside install and register script
- [ ] Build and test package

## Validation

- [ ] Build the package
- [ ] Install the package without auto deploy variables
- [ ] Install the package using `WAZUH_MANAGER` variable with only one address
- [ ] Install the package using `WAZUH_MANAGER` variable with multiple addresses split by `,`
- [ ] Install the package using `WAZUH_MANAGER` variable with multiple addresses split by `;` (Should not work)
- [ ] Install the package using multiple auto deploy variables including `WAZUH_MANAGER`
- [ ] Remove the package and reinstall using mentioned variable (Multiple addresses)

## Resolution

The research and conclusion of this issue is in https://github.com/wazuh/wazuh/issues/14844#issuecomment-1468271270

**Comment by davidcr01** [comment]
# Update Report

## Research

I have been investigating the separators of the list of the WAZUH_MANAGER values, and I concluded that this development has been done.

In 4.5.0:
- Linux (uses the comma, and only the comma): https://github.com/wazuh/wazuh/blob/251e799b17a8f8d1b81786f627392ba28bdf35fb/src/init/register_configure_agent.sh#L336. 
- Windows (uses the comma, and only the comma): https://github.com/wazuh/wazuh/blob/251e799b17a8f8d1b81786f627392ba28bdf35fb/src/win32/InstallerScripts.vbs#L85

In 4.4.0
- Linux (uses the comma, and only the comma): https://github.com/wazuh/wazuh/blob/f7cbac49a9fd04633ade3a9caeb287d09d59b19f/src/init/register_configure_agent.sh#L336
- Windows (uses the comma, and only the comma): https://github.com/wazuh/wazuh/blob/f7cbac49a9fd04633ade3a9caeb287d09d59b19f/src/win32/InstallerScripts.vbs#L85

This change was made in the following issues:
- In Windows: https://github.com/wazuh/wazuh/pull/14113
- In Linux: https://github.com/wazuh/wazuh/pull/15038

## Conclusion

With this, I can conclude that the separator of the values of the variable WAZUH_MANAGER is normalized, specifically to the comma character.
