### ISSUE TITLE
Review and refactor db queries in AWS module

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#14914]
| Affected integration |
|---|
| AWS |

## Description

The AWS module defines the different sql queries it uses to access, create and delete resources from the sqlite db inside the `__init__` method of each class. This means that the queries can only be made when a particular object is instantiated, requiring that functionalities which use queries such as `sql_get_metadata_version` to be tested only instantiating an object. 

https://github.com/wazuh/wazuh/blob/1270b56bcda5fde39c31cae95c1cd12aad73a5b2/wodles/aws/aws_s3.py#L92-L121

The declared queries should be reviewed and refactored to have a more generic and simpler code test.

## Tasks
- [ ] Review the code and determine the required changes to enhance the code and its testing.
- [ ] Test in a manager.
- [ ] Test in an agent.
- [ ] Unit tests without failures. Updated if there are any relevant changes.
- [ ] Integration tests without failures. Updated if there are any relevant changes.
- [ ] Update the documentation if necessary.
- [ ] Add entry to the changelog if necessary.
