### ISSUE TITLE
AWS Server Access check_bucket bug

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#15016]
| Affected integration |
|---|
| AWS Server Access|

## Description
Wazuh version: `v4.3.7`
Fails in: `Manager - Agent`

It was found that the `AWSServerAccess` integration is not processing logs found in the root folder of the bucket unless it contains folders inside of it. The result is the following message `ERROR: No files were found in 'bucket'. No logs will be processed.` even if the bucket has logs inside

The problem is caused by the following section of the code
https://github.com/wazuh/wazuh/blob/e2b514bef3d148acd4bcae1a1c7fa8783b82ca3a/wodles/aws/aws_s3.py#L2580-L2585

<details><summary>ServerAccess logs</summary>

<p>

```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-access -t server_access -s 2021-NOV-12 -p dev -d2
DEBUG: +++ Debug mode on - Level: 2
ERROR: No files were found in 'wazuh-aws-wodle-access/'. No logs will be processed.
```
</p>

</details>

When adding an empty folder, the module brings every log present in the root folder of the bucket:

<details><summary>ServerAccess logs</summary>

<p>

```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-access -t server_access -s 2021-NOV-12 -p dev -d2
DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Table does not exist; create
DEBUG: +++ Marker: 2021-11-12
DEBUG: ++ Found new log: 2021-11-12-09-11-26-B9F9F891E8D0EB13
DEBUG: ++ Found new log: 2021-11-12-13-11-26-B9F9F891E8D0EB13
DEBUG: ++ Found new log: 2021-11-15-09-12-25-F92E1554CC549BEE
DEBUG: ++ Found new log: 2021-12-27-09-12-23-F92E1554CC549BEA
DEBUG: ++ Found new log: 2022-01-25-09-12-23-F92E1554CC549BEX
DEBUG: ++ Found new log: 2022-02-11-09-12-25-H99KY554CC549BEE
DEBUG: +++ DB Maintenance

```
</p>

</details>

The condition to raise the ERROR message inside the `check_bucket` method should be reviewed and modified to correctly verify that the bucket is not empty.

## Tasks
- [x] Test in a manager.
- [x] Test in an agent.
- [x] Unit tests without failures. Updated if there are any relevant changes.
- [x] Integration tests without failures. Updated if there are any relevant changes.
- [x] Update the documentation if necessary.
- [x] Add entry to the changelog if necessary.

**Comment by fdalmaup** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wazuh---Framework-5d8b5184022c8d0001c05f4d/issues/wazuh/wazuh/15016?planning-poker) with Zenhub @CarlosRS9 @davidjiglesias @nico-stefani

**Comment by EduLeon12** [comment]
Con @nico-stefani se concluyo que no es necesario realizar nuevos tests.

**Comment by EduLeon12** [comment]
I was able to set up testing environment to test the s3 bucket.

The next steps will be to access the bucket using a different version of wazuh to check if the problem persists throughout versions:
- [ ] Test on v4.3.7 on a manager.
- [ ] Test on v.4.5 on a manager.
If needed:
- [ ] Test on v.4.5 on an agent.

**Comment by EduLeon12** [comment]
I was able to set up a testing environment to test the s3 bucket.

The following steps will be to access the bucket using a different version of wazuh to check if the problem persists throughout versions:
- [ ] Test on v4.3.7 on a manager.
- [ ] Test on v.4.5 on a manager.
If needed:
- [ ] Test on v.4.5 on an agent.

**Comment by EduLeon12** [comment]
The result shown in images will be commands one after the other.
The first result is with a s3 bucket with an empty folder in it and the second with a s3 bucket without an empty folder on the root.

- Bucket with Folder on root 
![Bucket with Folder on root ](https://user-images.githubusercontent.com/60372646/214403060-6e4c634b-ddd9-40b7-9f4f-61c92120bee7.png)

- Bucket without folder on root
![Bucket without folder on root](https://user-images.githubusercontent.com/60372646/214403454-6b8ca96c-ee5f-41ab-a9e1-a1df5b2fafd0.png)


Testing Results:
 - Wodle Manager v4.3.7:
![Wodle Manager v4.3.7](https://user-images.githubusercontent.com/60372646/214403890-2da269ab-1998-4614-8498-ae72a122e545.png)

- Wodle Manager v4.5 (master): 
![Wodle Manager v4.5 (master) ](https://user-images.githubusercontent.com/60372646/214404157-5f3b3356-b354-4519-b313-66c3ebb3b38b.png)

- Wodle Agent v4.5 (master): 
![Wodle Agent v4.5 (master) ](https://user-images.githubusercontent.com/60372646/214404370-abd819d1-c5da-425b-92d9-857a3d7a39cc.png)

As shown in the images bug persists in v4.5 (master) since no logs are found when the folder does not exist in root.

Next steps:
- [ ] Develop a solution in module check_bucket
https://github.com/wazuh/wazuh/blob/e2b514bef3d148acd4bcae1a1c7fa8783b82ca3a/wodles/aws/aws_s3.py#L2580-L2585

**Comment by EduLeon12** [comment]
After investigating and testing this issue further with the help of the [AWS S3 API].(https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html#API_ListObjectsV2_ResponseElements) 

The Delimiter causes keys that contain the same string between the prefix and the first occurrence of the delimiter to be rolled up into a single result element in the "CommonPrefixes" list, since the default delimiter is  "/" only folders will be stored.

Every other file match based on Prefix will be stored in "Contents" List. 

- Response with Delimiter = "/":
`{
	'Contents': [{
		'Key': '2021-04-29-09-14-48-5273CCCAE2158DCE',
		'LastModified': datetime.datetime(2023, 1, 24, 18, 34, 12, tzinfo = tzutc()),
		'ETag': '"a2d6bf32d38ef09a2db25c2b0e4d8e5e"',
		'Size': 624,
		'StorageClass': 'STANDARD'
	}],
	'Name': 'wazuh-aws-wodle-access-test',
	'Prefix': '2021-04-29',
	'Delimiter': '/',
	'MaxKeys': 1000,
	'CommonPrefixes': [{
		'Prefix': '2021-04-29-test/'
	}],
}`


- Response without delimiter:
`{
	'Contents': [{
		'Key': '2021-04-29-09-14-48-5273CCCAE2158DCE',
		'LastModified': datetime.datetime(2023, 1, 24, 18, 34, 12, tzinfo = tzutc()),
		'ETag': '"a2d6bf32d38ef09a2db25c2b0e4d8e5e"',
		'Size': 624,
		'StorageClass': 'STANDARD'
	}, {
		'Key': '2021-04-29-test/',
		'LastModified': datetime.datetime(2023, 1, 25, 19, 51, 54, tzinfo = tzutc()),
		'ETag': '"d41d8cd98f00b204e9800998ecf8427e"',
		'Size': 0,
		'StorageClass': 'STANDARD'
	}],
	'Name': 'wazuh-aws-wodle-access-test',
	'Prefix': '2021-04-29',
	'MaxKeys': 1000,
	'EncodingType': 'url',
	'KeyCount': 2
}`

Possible Solutions:
- Create a conditional to validate "Content" list content and existence on the response.
or 
- Remove Delimiter and create a filter to separate Files from folders inside "Content" List.

**Comment by EduLeon12** [comment]
After Developing and testing the solution we got the results:

```
root@wazuh-master:/var/ossec/wodles/aws# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-access-test -t server_access -s 2021-APR-29 -p dev -d2
DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Marker: 2021-04-29
DEBUG: ++ Found new log: 2021-04-29-09-13-06-338835093EADA3C1
DEBUG: ++ Found new log: 2021-04-29-09-14-05-B61AAAC9147C7F9F
DEBUG: ++ Skipping previously processed file: 2021-04-29-09-14-48-5273CCCAE2158DCE
DEBUG: +++ DB Maintenance
```
On Bucket without folder root on it.

S3 Bucket Image:
![Screenshot from 2023-01-27 16-36-30](https://user-images.githubusercontent.com/60372646/215181695-29bfce93-b2b7-45a6-8d10-69ced4844d31.png)
