### ISSUE TITLE
Shuffle integration

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#15034]
|Wazuh version|
|---|
| 4.4.0 |

## Description

Currently, Shuffle has developed a [custom integration](https://github.com/Shuffle/Shuffle/blob/launch/functions/extensions/wazuh/custom-shuffle.py) to forward alerts into their platform. The objective of this issue is to make it a native integration within Wazuh itself, like the ones for Slack or VirusTotal.

## Tasks

- [x] Review the code, test it and add it to Wazuh as a native integration.
- [x] Develop unit tests
- [x] Modify related Integratord files and unit tests to contemplate the new integration.
- [x] Verify the correct functioning of the integration when installing and updating Wazuh
- [x] Changelog.
- [x] Update the documentation.

**Comment by fdalmaup** [comment]
# Issue Update

`shuffle` script added to `wazuh/integrations` and modified sections of the code related to exception handling. Modifications should be done to `wazuh/src/os_integrator/integrator.c` in order to add verifications regarding the integration section in `ossec.conf`. 
Also, when installing a Wazuh manager, I couldn't get to have the script inside `/var/ossec/integrations`. I assume that modifications to the Makefile or the `install.sh` script are required.

In a local environment, I have installed the Shuffle platform to test the integration once I achieve the expected Wazuh installation. 

Unit tests to check the expected behavior of the script's functions will be developed.

**Comment by fdalmaup** [comment]
# Issue Update

After modifying `/src/init/inst-functions.sh` and adding the corresponding instructions to add the wrappers of the `shuffle` script, a manual installation was successfully carried out.
<img src="https://user-images.githubusercontent.com/26691145/193035042-ef22ebc4-8ed1-45f0-b0bb-3ef9f7f02756.png" width=50% height=50%>

**Comment by fdalmaup** [comment]
# Unit tests

## Test report
[shuffle_tests.zip](https://github.com/wazuh/wazuh/files/9684656/shuffle_tests.zip)

## Test results

---
| **Test name** | **Pass** | **XPass** | **Skip** | **XFail** | **Fail** | **Issues Ref.** | **Status** |
|--|--|--|--|--|--|--|--|
| integrations/tests/test_shuffle.py | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |

**Comment by fdalmaup** [comment]
# Manual test 
`ossec.conf` configuration
```
 <integration>
     <name>shuffle</name>
     <hook_url>http://<IP>:3001/api/v1/hooks/<HOOK_ID></hook_url>
     <level>3</level>
     <alert_format>json</alert_format>
 </integration>
```
Results in `/var/ossec/logs/integrations.log `
```
Fri Sep 30 15:30:00 UTC 2022: # Starting
Fri Sep 30 15:30:00 UTC 2022: # Webhook
Fri Sep 30 15:30:00 UTC 2022: http://<IP>:3001/api/v1/hooks/<HOOK_ID>
Fri Sep 30 15:30:00 UTC 2022: # File location
Fri Sep 30 15:30:00 UTC 2022: /tmp/shuffle-XXXXXX.alert
Fri Sep 30 15:30:00 UTC 2022: # Processing alert
Fri Sep 30 15:30:00 UTC 2022: {'timestamp': 'year-month-dayThours:minuts:seconds+0000', 'rule': {'level': 0, 'description': 'alert description', 'id': 'rule-id', 'firedtimes': 1}, 'id': 'alert_id', 'full_log': 'full log.', 'decoder': {'name': 'decoder-name'}, 'location': 'wazuh-X'}
Fri Sep 30 15:30:00 UTC 2022: # Generating message
Fri Sep 30 15:30:00 UTC 2022: {"severity": 1, "pretext": "WAZUH Alert", "title": "alert description", "text": "full log.", "rule_id": "rule-id", "timestamp": "year-month-dayThours:minuts:seconds+0000", "id": "alert_id", "all_fields": {"timestamp": "year-month-dayThours:minuts:seconds+0000", "rule": {"level": 0, "description": "alert description", "id": "rule-id", "firedtimes": 1}, "id": "alert_id", "full_log": "full log.", "decoder": {"name": "decoder-name"}, "location": "wazuh-X"}}
Fri Sep 30 15:30:00 UTC 2022: # Sending message
Fri Sep 30 15:30:00 UTC 2022: # In send msg
Fri Sep 30 15:30:00 UTC 2022: # After send msg: <Response [200]>
```

**Comment by frikky** [comment]
:fire:
