### ISSUE TITLE
Release 4.3.9 - Post release

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#15161]
The following issue aims to perform required post-release checks to ensure a well-published release procedure.

## Main information
|||
| :-- | :-- |
| **Version** | 4.3.9 |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.3.9 |
| **Release issue** |  #15088 |
| **Previous post release issue** | --- |

### Release notes
- [x] wazuh/wazuh release notes (tag)
- [x] ~wazuh/wazuh-feed release notes (tag)~
- [x] wazuh/wazuh-packages release notes (tag)
- [x] wazuh/wazuh-kibana-app release notes (tag)
- [x] wazuh/wazuh-splunk release notes (tag)
- [x] wazuh/wazuh-qa release notes (tag)
- [x] wazuh/wazuh-ansible release notes (tag)
- [x] wazuh/wazuh-docker release notes (tag)
- [x] wazuh/wazuh-kubernetes release notes (tag)
- [x] wazuh/wazuh-puppet release notes (tag)

### Repository
- [x] Live installation test
- [x] Live upgrade test
- [x] WPK versions check
- [x] WPK upgrade test
- [x] Post-release check (files)
- [x] AMI published
- [x] Cache invalidated
- [x] Build release containers
- [x] Build and push Docker Hub images
- [x] Build and release debug packages
- [x] Publish puppet forge module

### Documentation
- [x] Documentation updated
- [x] Documentation published
- [x] Cache invalidated

## Validation

The following auditors must give the green light to this release.

- [x] @davidjiglesias 
- [x] @okynos

**Comment by okynos** [comment]
## Summary
#### Install
🟢  https://ci.wazuh.info/view/Tests/job/Test_install/106023 CentOS 7
🟢  https://ci.wazuh.info/view/Tests/job/Test_install/106024 Ubuntu Focal

#### Upgrade
🟢 https://ci.wazuh.info/view/Tests/job/Test_upgrade/105603/ CentOS 7
🟢 https://ci.wazuh.info/view/Tests/job/Test_upgrade/105604/ Ubuntu Focal

#### WPK versions check


#### WPK upgrade test


#### Post-release check


#### Release containers
🟡  https://ci.wazuh.info/view/Procedures/job/Procedure_docker_testing_image_generation/205/

**Comment by fcaffieri** [comment]
## WPK upgrade test

### Summary

| System | Upgrade status | 
| -- | -- |
| Agent Linux | green_circle |
| Agent Windows | green_circle |

### Install manager 4.3.9

```
[root@manager-wpk vagrant]# curl -o wazuh-manager-4.3.9-1.x86_64.rpm https://packages.wazuh.com/4.x/yum/wazuh-manager-4.3.9-1.x86_64.rpm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  114M  100  114M    0     0  52.2M      0  0:00:02  0:00:02 --:--:-- 52.2M
[root@manager-wpk vagrant]# yum install wazuh-manager-4.3.9-1.x86_64.rpm -y
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror
Examining wazuh-manager-4.3.9-1.x86_64.rpm: wazuh-manager-4.3.9-1.x86_64
Marking wazuh-manager-4.3.9-1.x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package wazuh-manager.x86_64 0:4.3.9-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================================================================================================================
 Package                                  Arch                              Version                              Repository                                                Size
================================================================================================================================================================================
Installing:
 wazuh-manager                            x86_64                            4.3.9-1                              /wazuh-manager-4.3.9-1.x86_64                            438 M

Transaction Summary
================================================================================================================================================================================
Install  1 Package

Total size: 438 M
Installed size: 438 M
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : wazuh-manager-4.3.9-1.x86_64                                                                                                                                 1/1 
  Verifying  : wazuh-manager-4.3.9-1.x86_64                                                                                                                                 1/1 

Installed:
  wazuh-manager.x86_64 0:4.3.9-1                                                                                                                                                

Complete!
[root@manager-wpk vagrant]#

[root@manager-wpk vagrant]# /var/ossec/bin/wazuh-control info 
WAZUH_VERSION="v4.3.9"
WAZUH_REVISION="40322"
WAZUH_TYPE="server"
[root@manager-wpk vagrant]#
```

### Install and configure agent 4.3.8 in Linux

```
[root@agent-wpk vagrant]# curl -o wazuh-agent-4.3.8-1.x86_64.rpm https://packages.wazuh.com/4.x/yum/wazuh-agent-4.3.8-1.x86_64.rpm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 8760k  100 8760k    0     0  16.8M      0 --:--:-- --:--:-- --:--:-- 16.8M
[root@agent-wpk vagrant]# ls -la
total 8776
drwx------. 3 vagrant vagrant     112 Oct 13 20:28 .
drwxr-xr-x. 3 root    root         21 Apr 30  2020 ..
-rw-r--r--. 1 vagrant vagrant      18 Apr  1  2020 .bash_logout
-rw-r--r--. 1 vagrant vagrant     193 Apr  1  2020 .bash_profile
-rw-r--r--. 1 vagrant vagrant     231 Apr  1  2020 .bashrc
drwx------. 2 vagrant vagrant      29 Oct 13 20:27 .ssh
-rw-r--r--. 1 root    root    8970855 Oct 13 20:28 wazuh-agent-4.3.8-1.x86_64.rpm
[root@agent-wpk vagrant]# 
[root@agent-wpk vagrant]# 
[root@agent-wpk vagrant]# yum install wazuh-agent-4.3.8-1.x86_64.rpm -y
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror
Examining wazuh-agent-4.3.8-1.x86_64.rpm: wazuh-agent-4.3.8-1.x86_64
Marking wazuh-agent-4.3.8-1.x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package wazuh-agent.x86_64 0:4.3.8-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================================================================================================================
 Package                                 Arch                               Version                               Repository                                               Size
================================================================================================================================================================================
Installing:
 wazuh-agent                             x86_64                             4.3.8-1                               /wazuh-agent-4.3.8-1.x86_64                              25 M

Transaction Summary
================================================================================================================================================================================
Install  1 Package

Total size: 25 M
Installed size: 25 M
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : wazuh-agent-4.3.8-1.x86_64                                                                                                                                   1/1 
  Verifying  : wazuh-agent-4.3.8-1.x86_64                                                                                                                                   1/1 

Installed:
  wazuh-agent.x86_64 0:4.3.8-1                                                                                                                                                  

Complete!
[root@agent-wpk vagrant]# /var/ossec/bin/wazuh-control info 
WAZUH_VERSION="v4.3.8"
WAZUH_REVISION="40321"
WAZUH_TYPE="agent"
[root@agent-wpk vagrant]# vi /var/ossec/etc/ossec.conf
[root@agent-wpk vagrant]# systemctl start wazuh-agent
[root@agent-wpk vagrant]# cat  /var/ossec/etc/ossec.conf  | grep address
      <address>172.16.1.10</address>
[root@agent-wpk vagrant]#
```

### Upgrade agent Linux via WPK

```
[root@manager-wpk vagrant]# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: manager-wpk (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: agent-wpk, IP: any, Active

List of agentless devices:

[root@manager-wpk vagrant]# curl -so wazuh_agent_v4.3.9_linux_x86_64.wpk https://packages.wazuh.com/4.x/wpk/linux/x86_64/wazuh_agent_v4.3.9_linux_x86_64.wpk
[root@manager-wpk vagrant]# ls -la
total 136844
drwx------. 3 vagrant vagrant       157 Oct 13 20:32 .
drwxr-xr-x. 3 root    root           21 Apr 30  2020 ..
-rw-r--r--. 1 vagrant vagrant        18 Apr  1  2020 .bash_logout
-rw-r--r--. 1 vagrant vagrant       193 Apr  1  2020 .bash_profile
-rw-r--r--. 1 vagrant vagrant       231 Apr  1  2020 .bashrc
drwx------. 2 vagrant vagrant        29 Oct 13 20:26 .ssh
-rw-r--r--. 1 root    root    120109988 Oct 13 20:28 wazuh-manager-4.3.9-1.x86_64.rpm
-rw-r--r--. 1 root    root     20001047 Oct 13 20:32 wazuh_agent_v4.3.9_linux_x86_64.wpk
[root@manager-wpk vagrant]# /var/ossec/bin/agent_upgrade -a 001 -f /home/vagrant/wazuh_agent_v4.3.9_linux_x86_64.wpk -x upgrade.sh

Upgrading...

Upgraded agents:
	Agent 001 upgraded: Wazuh v4.3.8 -> Wazuh v4.3.9
[root@manager-wpk vagrant]#
```

#### Agent:

```
[root@agent-wpk vagrant]# /var/ossec/bin/wazuh-control info 
WAZUH_VERSION="v4.3.9"
WAZUH_REVISION="40322"
WAZUH_TYPE="agent"
[root@agent-wpk vagrant]#
```

### Install and configure agent 4.3.8 in Windows

```
C:\Users\Administrator>wazuh-agent-4.3.9-1.msi /q WAZUH_MANAGER="172.16.1.10"

C:\Users\Administrator>cd Downloads

C:\Users\Administrator\Downloads>dir
 Volume in drive C is Windows 2016
 Volume Serial Number is 26DF-55D2

 Directory of C:\Users\Administrator\Downloads

10/13/2022  08:34 PM    <DIR>          .
10/13/2022  08:34 PM    <DIR>          ..
10/13/2022  08:34 PM         5,885,952 wazuh-agent-4.3.8-1.msi
               1 File(s)      5,885,952 bytes
               2 Dir(s)  47,737,597,952 bytes free

C:\Users\Administrator\Downloads>wazuh-agent-4.3.8-1.msi /q WAZUH_MANAGER="172.16.1.10"

C:\Users\Administrator\Downloads>NET START WazuhSvc
The Wazuh service is starting.
The Wazuh service was started successfully.


C:\Users\Administrator\Downloads>
```

![image](https://user-images.githubusercontent.com/89791732/195706085-bd026e3f-9df4-49de-91f3-8ed73c88ad40.png)

### Upgrade agent Windows via wpk:

```
root@manager-wpk vagrant]# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: manager-wpk (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: agent-wpk, IP: any, Active
   ID: 002, Name: agent-win-wpk, IP: any, Active

List of agentless devices:

[root@manager-wpk vagrant]# curl -so wazuh_agent_v4.3.9_windows.wpk https://packages.wazuh.com/4.x/wpk/windows/wazuh_agent_v4.3.9_windows.wpk
[root@manager-wpk vagrant]# ls -la
total 142288
drwx------. 3 vagrant vagrant       195 Oct 13 20:41 .
drwxr-xr-x. 3 root    root           21 Apr 30  2020 ..
-rw-r--r--. 1 vagrant vagrant        18 Apr  1  2020 .bash_logout
-rw-r--r--. 1 vagrant vagrant       193 Apr  1  2020 .bash_profile
-rw-r--r--. 1 vagrant vagrant       231 Apr  1  2020 .bashrc
drwx------. 2 vagrant vagrant        29 Oct 13 20:26 .ssh
-rw-r--r--. 1 root    root    120109988 Oct 13 20:28 wazuh-manager-4.3.9-1.x86_64.rpm
-rw-r--r--. 1 root    root     20001047 Oct 13 20:32 wazuh_agent_v4.3.9_linux_x86_64.wpk
-rw-r--r--. 1 root    root      5572593 Oct 13 20:41 wazuh_agent_v4.3.9_windows.wpk
[root@manager-wpk vagrant]# /var/ossec/bin/agent_upgrade -a 002 -f /home/vagrant/wazuh_agent_v4.3.9_windows.wpk -x upgrade.bat -F

Upgrading...

Upgraded agents:
	Agent 002 upgraded: Wazuh v4.3.8 -> Wazuh v4.3.9
[root@manager-wpk vagrant]# 

```

#### Agent:

![image](https://user-images.githubusercontent.com/89791732/195706650-6a11afd3-6c44-4f37-a6d4-3668e6570856.png)

**Comment by fcaffieri** [comment]
## Debug packages:
### RPM:
https://devel.ci.wazuh.info/job/Package_builder_fcaffieri/367
https://devel.ci.wazuh.info/job/Package_builder_fcaffieri/368
https://devel.ci.wazuh.info/job/Package_builder_fcaffieri/364
https://devel.ci.wazuh.info/job/Package_builder_fcaffieri/369
https://devel.ci.wazuh.info/job/Package_builder_fcaffieri/370
https://devel.ci.wazuh.info/job/Package_builder_fcaffieri/371
https://devel.ci.wazuh.info/job/Package_builder_fcaffieri/372

### DEB:
https://devel.ci.wazuh.info/job/Package_builder_fcaffieri/373
https://devel.ci.wazuh.info/job/Package_builder_fcaffieri/374
https://devel.ci.wazuh.info/job/Package_builder_fcaffieri/375
https://devel.ci.wazuh.info/job/Package_builder_fcaffieri/376
https://devel.ci.wazuh.info/job/Package_builder_fcaffieri/377
https://devel.ci.wazuh.info/job/Package_builder_fcaffieri/378
https://devel.ci.wazuh.info/job/Package_builder_fcaffieri/379

## Publish warehouse:
https://devel.ci.wazuh.info/job/Publish_releas_fcaffieri/65

![image](https://user-images.githubusercontent.com/89791732/195727076-50165f35-8891-4d0b-8a28-b921e7c6c34a.png)
![image](https://user-images.githubusercontent.com/89791732/195727094-2fe11f1b-6918-479c-9667-f2d82575530c.png)


## Publish packages.wazuh.com:
https://devel.ci.wazuh.info/job/Publish_releas_fcaffieri/66

![image](https://user-images.githubusercontent.com/89791732/195727532-8c44d352-9a90-4ec4-9f2b-2b84c82ae6ec.png)
![image](https://user-images.githubusercontent.com/89791732/195727557-f22a4dd6-6cee-4223-a66f-0ad62489ef93.png)
