### ISSUE TITLE
Engine | New ruleset development

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh#15181]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0 | engine | - | - | - |

The engine has reached the maturity point to allow us to start the development of its ruleset. 

This ruleset's primary goals are:
 * embrace the common schema
 * increase the number of devices and formats supported
 * revamp and update the alert rules
 * define the best practices to develop the ruleset 

We will have a development environment #14738 and a user manual developed  #13815. We have developed some examples  #13803  used to test the capabilities of the engine, and not necessarily a description of the best practices to adopt.

To do:

- [x] Create supported sources  inventory 
        We need an inventory of all the devices and log formats we want to support, ordered by priority, to parallelize the decoder development and testing. https://github.com/wazuh/wazuh-threatintel/issues/31

- [x] Create an agent simulator 
        We want to create an agent simulator to ease the ruleset development. This agent must generate events in the same format a real agent would do, and send them directly to the engine. The engine has also testing features that might need some adaptation to integrate this new simulator.

- [ ] For each device to support:
    - acquire source events to use with the simulator
    - develop the decoder
    - generate tests
    - develop device-specific rules

    - Issues:
      - [ ] Support for device XXX  

 - [ ] Create generic security rules inventory
         For each rule, determine if it can be implemented in the engine, or should be implemented in the indexer. We want to leverage the engine as much as possible.

 - [ ] For each rule to support:
     - acquire events to use with the simulator
     - develop the rule
     - generate tests  

- [ ] All events generated must comply with the common schema
- [ ] We need to develop vendor extensions for the schema

**Comment by davidjiglesias** [comment]
To be continued in the future as part of the new engine.
