### ISSUE TITLE
AWS Integration: Improvements

### ISSUE THREAD

**Issue by mgmacias95** [wazuh/wazuh#1522]
Hello team,

Below there's a summary of all feedback and requests we have received for the AWS integration:

#### New features
- [x] Support for AWS config (https://github.com/wazuh/wazuh/issues/1777)
- [x] Support for AWS Trusted Advisor (https://github.com/wazuh/wazuh/issues/922)
- [x] Support for AWS KMS (Key Management Service) (https://github.com/wazuh/wazuh/pull/1919)
- [x] Support for AWS inspector (network) (https://github.com/wazuh/wazuh/issues/1899)
- [x] Support for all AWS GuardDuty sample findings (https://github.com/wazuh/wazuh/issues/1263)
- [x] AWS GuardDuty improve rules (https://github.com/wazuh/wazuh/issues/1907)

### Documentation

- [x] Read encrypted buckets (Asked [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/wazuh/2iYrFX2onZ4/jLLlTcvgAQAJ;context-place=forum/wazuh)) (https://github.com/wazuh/wazuh-documentation/pull/606)
- [x] Support for roles to access buckets (instead of hardcoded secret keys) (https://github.com/wazuh/wazuh/issues/1901)
- [x] Fix AWS documentation (section storing logs in S3): Clicking on "add target" is not needed (https://github.com/wazuh/wazuh-documentation/pull/598)

#### Fixes
- [x] Fix mapping template for AWS GuardDuty (https://github.com/wazuh/wazuh/pull/1761)
- [x] Update script to allow new VPC Flow directory structure. We only support VPC Flow logs generated by a lambda function right now. (https://github.com/wazuh/wazuh/issues/1516 and https://github.com/sonofagl1tch/AWSDetonationLab/pull/21).
- [x] remove_from_bucket argument in AWS wodle no functioning as expected (https://github.com/wazuh/wazuh/issues/1618).
- [x] Fix bug when too many logs are generated in the same day (https://github.com/wazuh/wazuh/issues/1367).
- [x] Increase qty of aws.eventNames; remove usage of aws.eventSources (https://github.com/wazuh/wazuh/pull/1698)
- [x] Review pulling of VPC logs (https://github.com/wazuh/wazuh/issues/2065)
- [x] Create/review databases (https://github.com/wazuh/wazuh/issues/2066)

Best regards,
Marta

**Comment by UranusBytes** [comment]
@mgmacias95 
Hi Marta - I'm excited to so much great progress planned for the AWS integration with Wazuh!

A couple comments to throw in:

> Read encrypted buckets 

FWIW, I did testing this morning and didn't have problems with encrypted logs.  But I could replicate the issue when the user defined to get the logs from S3 had insufficient access to the KMS key.  I replied to the referenced email thread with verbose details on what permissions are required, so maybe this is just a slight update/tweak to the documentation.  

> Support for roles to access buckets (instead of hardcoded secret keys)

This should already work, unless I'm misunderstanding the goal.  At least I'm currently using IAM roles for accessing the S3 buckets.  Below is an example of my baseline config for a bucket, and this works without issue.
```
<bucket type="cloudtrail">
      <aws_account_alias>myTestAccount</aws_account_alias>
      <name>s3-bucket-myTestAccount</name>
      <aws_account_id>123412341234</aws_account_id>
      <iam_role_arn>arn:aws:iam::123412341234:role/Wazuh-Log-Parser</iam_role_arn>
      <only_logs_after>2018-SEP-15</only_logs_after>
</bucket>
```
Thanks!

Jeremy

**Comment by mgmacias95** [comment]
Hi @UranusBytes,

All defined tasks are taken from feedback directly received from users. If a user has thought Wazuh doesn't support IAM roles, our documentation must be reviewed and improved. The same with bucket encryption.

Thank you so much for all your help and support 😄 !!!

Best regards,
Marta

**Comment by UranusBytes** [comment]
@mgmacias95 Please see #1618 and consider adding to this upcoming release

**Comment by mgmacias95** [comment]
Hi @UranusBytes,

Thank you so much for reporting this and helping in the original issue at the wazuh mailing list. I have added that issue to this roadmap 😄.

Best regards,
Marta
