### ISSUE TITLE
Engine - KVDB API and client

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh#15274]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0 | Engine | - | - | - |

We need to implement the KVDB management API to enable users to manage any DB in runtime.

We need to implement the following command in our engine client:

- [x] **list**: prints all databases currently available. We might want to implement filters/queries later.
- [x] **create**: creates a database and optionally initializes it from a file. To use stdin as a file, we can use - as the file name.   If the database already exists or can’t be created, it returns an error.
- [x] **dump**: dumps the contents of db-id as an array of JSON object like [{“key”: string, “value”, value},....]
- [x] **delete**: removes a database, erasing all values from the store. If the database does not exist or can’t be deleted, it returns an error. If it is in use, we cannot delete it and should indicate the user with an appropriate message.
- [x] **get**: gets the value of a key for a database, identified with its db-id. If the database or the key does not exist, return an error.
- [x] **insert**: insert or updates the value of a key in db-id. If the value already exists, it is updated. If the database does not exist or the key value can’t be created or updated, it returns an error.
- [x] **remove**: removes a key from the db-id. If the key does not exist, or it can’t be removed, returns an error.

We need to implement this in the same way we did with the catalog.

## Tasks
- [x] Implement functionality
- [x] Update Documentation
- [ ] QA validate https://github.com/wazuh/wazuh-qa/issues/3663

**Comment by LucioDonda** [comment]
Commands added

- create
example:
```
 ╰─# ./build/main kvdb -a /tmp/api_socket -k /tmp/kvdbTest create -n TEST_KVDB -p /tmp/filepath                                     
 KVDB name:TEST_KVDB created.
```

Being filepath content
```
╰─# cat /tmp/filepath 
key_1:val_1
key_2:val_2
key_3:val_3
key_4:val_4
key_5:val_5
key_6:val_6
key_7:val_7
key_8:val_8

```

-  dump
```
╰─# ./build/main kvdb -a /tmp/api_socket -k /tmp/kvdbTest dump -n TEST_KVDB                   
KVDB content:
[{"key":"key_1","value":"val_1"},{"key":"key_2","value":"val_2"},{"key":"key_3","value":"val_3"},{"key":"key_4","value":"val_4"},{"key":"key_5","value":"val_5"},{"key":"key_6","value":"val_6"},{"key":"key_7","value":"val_7"},{"key":"key_8","value":"val_8"}]

```
prettified:
```
[
    {
        "key": "key_1",
        "value": "val_1"
    },
    {
        "key": "key_2",
        "value": "val_2"
    },
    {
        "key": "key_3",
        "value": "val_3"
    },
    {
        "key": "key_4",
        "value": "val_4"
    },
    {
        "key": "key_5",
        "value": "val_5"
    },
    {
        "key": "key_6",
        "value": "val_6"
    },
    {
        "key": "key_7",
        "value": "val_7"
    },
    {
        "key": "key_8",
        "value": "val_8"
    }
]
```

-  list
example:

```
╰─# ./build/main kvdb -a /tmp/api_socket -k /tmp/kvdbTest list                        
2 KVDBs available
1/2 name: ANOTHER_TEST_KVDB
2/2 name: TEST_KVDB
```
or filtered:
```
╰─# ./build/main kvdb -a /tmp/api_socket -k /tmp/kvdbTest list -n TEST
1 KVDB available
1/1 name: TEST_KVDB
```

- delete

```
╰─# ./build/main kvdb -a /tmp/api_socket -k /tmp/kvdbTest delete -n ANOTHER_TEST_KVDB
 KVDB name:ANOTHER_TEST_KVDB deleted.
╰─# ./build/main kvdb -a /tmp/api_socket -k /tmp/kvdbTest list                       
1 KVDB available
1/1 name: TEST_KVDB
```


- get
 
```
╰─# ./build/main kvdb -a /tmp/api_socket -k /tmp/kvdbTest get -n TEST_KVDB -k key_7                                                                                                                          106 ↵
Value [val_7] on key [key_7] from DB [TEST_KVDB]
```
 
 - insert

```
 ╰─# ./build/main kvdb -a /tmp/api_socket -k /tmp/kvdbTest insert -n TEST_KVDB -k key_10 -v value_10
Key value [key_10,value_10] inserted on [TEST_KVDB]
╰─# ./build/main kvdb -a /tmp/api_socket -k /tmp/kvdbTest dump -n TEST_KVDB                        
KVDB content:
[{"key":"key_1","value":"val_1"},{"key":"key_10","value":"value_10"},{"key":"key_2","value":"val_2"},{"key":"key_3","value":"val_3"},{"key":"key_4","value":"val_4"},{"key":"key_5","value":"val_5"},{"key":"key_6","value":"val_6"},{"key":"key_7","value":"val_7"},{"key":"key_8","value":"val_8"}]
```
 - remove
```
 ╰─# ./build/main kvdb -a /tmp/api_socket -k /tmp/kvdbTest remove -n TEST_KVDB -k key_1                                                                                                                       130 ↵
Key [key_1] deleted on [TEST_KVDB]
╰─# ./build/main kvdb -a /tmp/api_socket -k /tmp/kvdbTest dump -n TEST_KVDB            
KVDB content:
[{"key":"key_10","value":"value_10"},{"key":"key_2","value":"val_2"},{"key":"key_3","value":"val_3"},{"key":"key_4","value":"val_4"},{"key":"key_5","value":"val_5"},{"key":"key_6","value":"val_6"},{"key":"key_7","value":"val_7"},{"key":"key_8","value":"val_8"}]
```
