### ISSUE TITLE
Invalid entries in `last_dates.json`

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh#15282]
|Wazuh version|Component|Install type|
|---|---|---|
| 4.3.8 | Azure module | Manager |

We need to investigate a problem when the `last_dates.json` contains invalid entries into `log_analytics` key, by example.

```json
{
  "log_analytics": {
    "2a78ed76450c3cb42320882b3e055b31": {
      "min": "2021-05-14T15:10:53.211Z",
      "max": "2021-05-14T15:10:53.211Z"
    },
    "f90c15b0327962c9e661142547368572": {
      "min": "2021-06-25T12:40:08.124Z",
      "max": "2021-06-25T12:40:08.124Z"
    },
    "cd04c1dc0a79a7e105bbab939e223238": {
      "min": "0",
      "max": "0"
    },
    "d4ba655672d8e58526585143485fb6d1": {
      "min": "0",
      "max": "0"
    },
    "c64518704ce0c0d5501a45763f464276": {
      "min": "2022-07-26T18:00:00Z",
      "max": "2022-11-02T13:00:00Z"
    },
    "0c5ade473eccec326a57c90eafd47b5a": {
      "min": "2022-07-24T12:00:46.5292647Z",
      "max": "2022-07-24T12:00:46.5292647Z"
    },
    "3bf20def2914066463a097b381def719": {
      "min": "2022-07-26T18:44:45.3670697Z",
      "max": "2022-11-02T14:15:51.6742391Z"
    },
    "aa43c558bb8c804f6aa3289c7b149626": {
      "min": "2022-07-26T18:36:10.0361692Z",
      "max": "2022-11-02T14:15:46.040368Z"
    },
    "885e7821375c1bcc250055b6831db89e": {
      "min": "2022-07-26T18:38:52.8580229Z",
      "max": "2022-11-02T14:15:48.4880595Z"
    },
    "de3f6d56d657fb4ca310533dc2dd9928": {
      "min": "2022-07-26T18:42:34.249475Z",
      "max": "2022-11-02T14:15:38.8428819Z"
    },
    "63daf76c0c6951a249570d1a0c0a2201": {
      "min": "2022-07-26T18:36:53.8334155Z",
      "max": "2022-11-02T13:55:19.4648023Z"
    }
  },
  "graph": {},
  "storage": {}
}
```
This causes an error because the module tries to parse the `0` value to a datetime.

```bash
[root@wazuh-manager-master-0 /]# /var/ossec/wodles/azure/azure-logs --log_analytics --la_auth_path /var/ossec/etc/graph_auth.txt --la_tenant_domain XXXXXX --la_tag app-service-http-logs --la_query "AppServiceHTTPLogs" --workspace XXXXXX --la_time_offset 2h
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/dateutil/parser/_parser.py", line 655, in parse
    ret = self._build_naive(res, default)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/dateutil/parser/_parser.py", line 1241, in _build_naive
    naive = default.replace(**repl)
ValueError: day is out of range for month

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/ossec/wodles/azure/azure-logs.py", line 863, in <module>
    start_log_analytics()
  File "/var/ossec/wodles/azure/azure-logs.py", line 317, in start_log_analytics
    body = build_log_analytics_query(offset=args.la_time_offset, md5_hash=md5_hash)
  File "/var/ossec/wodles/azure/azure-logs.py", line 346, in build_log_analytics_query
    min_datetime = parse(min_str, fuzzy=True)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/dateutil/parser/_parser.py", line 657, in parse
    six.raise_from(ParserError(e.args[0] + ": %s", timestr), e)
  File "<string>", line 3, in raise_from
dateutil.parser._parser.ParserError: day is out of range for month: 0
```
## Tasks
- [x] Try to replicate the generation of invalid entries
- [x] Propose a solution

**Comment by RamosFe** [comment]
## Update

The issue is encountered when trying to parse the contents of `last_dates.json` with invalid `min, max` date values. The exception is raised when building the Query for the API Request to the Azure Logs Service as shown below:

https://github.com/wazuh/wazuh/blob/88bf15d2cbb2040e197e34a94dda0f71f607afad/wodles/azure/azure-logs.py#L328-L347

The min and max value is obtained from the JSON file using the following function:

https://github.com/wazuh/wazuh/blob/88bf15d2cbb2040e197e34a94dda0f71f607afad/wodles/azure/azure-logs.py#L194-L225

The solution that I propose is to add date validations in the `get_min_max` function and treat the different error cases in the following way:

- **Case 1: Invalid min value and valid max value**: The min value is replaced with the max value.  In this way, we ensure that the Query Builder behaves as expected.
- **Case 2: Valid min value and invalid max value**: The max value is replaced with the min value. In this way, we ensure that the Query Builder behaves as expected.
- **Case 3: Invalid min value and invalid max value**: Both values are replaced with the `desired_datetime` (Calculated using the offset and the execution date). This is the same way as is treated a new md5 value:
https://github.com/wazuh/wazuh/blob/88bf15d2cbb2040e197e34a94dda0f71f607afad/wodles/azure/azure-logs.py#L214-L224

Before developing these changes, we should add unit tests for the `get_min_max` function so that we have a safety net and avoid adding new bugs when changing the function functionality.

- [ ] Add tests for the existing functionality of the `get_min_max` function.
- [ ] Add tests for the invalid min and max scenarios.
- [ ] Development of the solution

**Comment by RamosFe** [comment]
## Update

Added tests for the `get_min_max` function for the already existing functionality
https://github.com/wazuh/wazuh/blob/3de45ad5a38332af11e885ddc335bb4ff25d2594/wodles/azure/tests/test_azure_logs.py#L28-L58

**Comment by RamosFe** [comment]
## Update

The issue is encountered when trying to parse the contents of last_dates.json with invalid min and max date values. The exception is raised when building the Query for the API Request to the Azure Logs Service as shown below:

https://github.com/wazuh/wazuh/blob/251e799b17a8f8d1b81786f627392ba28bdf35fb/wodles/azure/azure-logs.py#L346-L349

The file last_dates.json was used as a way to persist the data of the requests. Now, the Azure Wodle uses a database to persist the data. When the script starts, it searches for last_dates.json, and if it finds this file, it persists the data into the database and erases it.

The solution that I propose is to add date validations to the function in charge of the migration of the data from the JSON to the database and treat the different error cases in the following way:

### Actual Format
* **Case 1**: Invalid min value and valid max value: The min value is replaced with the max value. In this way, we ensure that the Query Builder behaves as expected.
* **Case 2:** Valid min value and invalid max value: The max value is replaced with the min value. In this way, we ensure that the Query Builder behaves as expected.
* **Case 3**: Invalid min value and invalid max value: Both values are replaced with the actual date.

### Legacy format 
In the old format of the `last_dates.json` file, there is only one value. If this value is invalid this is replaced with the actual date.

## Tasks

- [ ] Add tests for the existing functionality of valid values.
- [ ] Add tests for the invalid min and max scenarios.
- [ ] Add new `last_dates.json` files with the invalid min and max scenarios and add them to the existing tests.
- [ ] Development of the solution

**Comment by RamosFe** [comment]
## Update

Added tests for the new validation function:
https://github.com/wazuh/wazuh/blob/3b14c2817ad5dd06981d49d8a7da9cdde0766731/wodles/azure/tests/test_orm.py#L221-L264

Added new test cases taking into account the new invalid scenarios:
https://github.com/wazuh/wazuh/blob/3b14c2817ad5dd06981d49d8a7da9cdde0766731/wodles/azure/tests/test_orm.py#L128-L129

**Comment by RamosFe** [comment]
Integration tests were made using Azure Storage and Azure Log Analytics passed using invalid fields in the `last_dates.json` file. The Azure Wodle script executed without problems.
