### ISSUE TITLE
External socket output are null terminated

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#1530]
|Version detected|Affected component|Working branch|
|---|---|---|
|3.6.1|Logcollector|[3.6-fix-logcollector-socket](https://github.com/wazuh/wazuh/compare/stable...3.6-fix-logcollector-socket)|

## Bug description

Logcollector is appending a null termination into external socket messages.

For instance, when connecting Logcollector to Fluent Bit via socket:
```xml
<!-- ossec.conf -->
<socket>
  <name>fluentbit</name>
  <mode>udp</mode>
  <location>/var/run/fluent-bit.sock</location>
  <prefix>\<13\></prefix>
</socket>

<localfile>
  <location>/root/test.log</location>
  <log_format>syslog</log_format>
  <target>fluentbit</target>
</localfile>
```

This input in Logcollector:
```
Oct  2 10:10:10 centos chronyd[554]: Received KoD RATE from 37.139.121.60
```
Produces this output by Fluent Bit:
```
syslog.0: [1538475010.000000, {"pri":"13", "time":"Oct  2 10:10:10", "ident":"centos", "pid":"", "message":"Received KoD RATE from 37.139.121.60\u0000"}]
```

## Reason

The bug is produced by this line: [mq_op.c:180](https://github.com/wazuh/wazuh/blob/v3.6.1/src/shared/mq_op.c#L180)
```c
OS_SendUnix(sock, string, length);
```

We are using this call form:
```c
OS_SendUnix(sock, string, 0);
```

When `length = 0`, this sending function calculates the string length and adds 1 ([os_net.c:447](https://github.com/wazuh/wazuh/blob/v3.6.1/src/os_net/os_net.c#L447-L449)):
```c
if (size == 0) {
    size = strlen(msg) + 1;
}
```
This code lets include the null terminator for _ossec-analysisd_ and _ossec-agentd_. They will get rid of this byte.

However, external sockets may accept that extra terminator as string input.

## Proposed fix

Replace:
```c
OS_SendUnix(sock, string, 0);
```
with:
```c
OS_SendUnix(sock, string, strlen(string));
```

## Subtasks

- [x] Implement fix. 5b94130
- [x] Test that output message towards _ossec-agentd_ is not affected.
- [x] Test output towards Fluent Bit.
- [x] Test raw socket output.
- [x] Merge into the development branch. #1547
