### ISSUE TITLE
Update GCP Bucket implementation

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#15347]
| Affected integration |
|---|
| GCloud |

Our current GCP implementation requires the `integration_type` parameter to be used to indicate when a given configuration should trigger the `PubSub` or `Storage` integration. When configuring PubSub, the user does not need to indicate any type, as the parser itself when detecting the `gcp_pubsub` tag will invoke the script providing the required `--integration_type pubsub` parameter. However, this is not the case for Storage. 

Storage works similarly to Pubsub, with the exception that the parser expects to find a `type` attribute inside the `bucket` tag:
```
<gcp-bucket>
   <bucket type="access_logs">
       <name>wazuh-test-bucket</name>
       <credentials_file>credentials.json</credentials_file>
   </bucket>
</gcp-bucket>
```

This was implemented this way for the following reasons:

1. To be consistent with the AWS S3 integration, which uses the type parameter to determine whether the logs to be processed come from CloudTrail, Guarduty or other services. This is necessary because AWS expects to receive a different format depending on the type of service that originated the logs.
1. Having the type attribute allow us to add support for different types of logs for Bucket integration in the future, just like with AWS.
1. Originally this implementation was made exclusively for processing `access_logs` logs.

However, we shouldn't require users to have to specify the attribute `type` in the `bucket` tag for the following reasons:
1. We officially support `access_logs` logs only, since Wazuh does not incorporate default rules for other types of logs. Since we only support one log type, it makes no sense to make it mandatory to specify `type="access_logs"`. In case a different value for the type is applied, the integration will fail as `access_logs` is the only supported value. Therefore, even if we wanted to limit ourselves exclusively to processing access_logs records, this parameter would be completely unnecessary.
1. Our current GCP Pubsub implementation is not limited exclusively to `access logs`. This limitation is only imposed by the fact that Wazuh only incorporates rules for them. However, the module is fully compatible and able to process any log stored in Storage, as long as its format is comma delimited csv. That is, our integration is with CSV format, not with access_logs.
1. Users can process any log from Storage with our current implementation, as long as those logs comply with the `csv` format and users create their own custom rules in case they are not `access logs`. Still, the user is forced to indicate that the type is `access_logs`, when it is not true.

### Proposed change

- Remove any reference to `access_logs` in our code and benefit from the fact that our integration is already compatible with any log as long as it is in CSV format. 
- Update the `gcloud.py` module so that the value it expects to receive is not `arguments.integration_type == "access_logs"` but rather `arguments.integration_type == "csv"`.
- Update the `access_logs.py` module so that it is now called `bucket_csv.py` and the `GCSAccessLogs` class is renamed to `CSVLogs`. No further changes are needed. The current logic already takes care of reading the first line of the log to determine which fields are expected to be processed.
- Update the `gcp.c` parser so that it is not necessary to read the `type` attribute inside the `bucket` tag. We could simply ignore it to maintain backwards compatibility with previous configurations.
- Update the `gcp.c` parser to automatically invoke the script always using the `--integration_type csv` parameter if we are using bucket integration.
- Update the documentation to make it clear to users that the module is compatible with any csv logs, as long as they create their own rules or they are `--access_logs` logs.

### Advantages of implementing this change:
1. Simplified configuration for users
1. Avoid confusions, as we currently support any log in `csv` format. The user will not think that he is limited to `access_logs` only.
1. Possibility to easily extend the module in the future to process logs in `json`, `jsonl` or plain text format. It will simply be necessary to add a new `if` to the `gcloud.py` module indicating `arguments.integration_type == "csv"` or `arguments.integration_type == "json"`, as well as to create a new `JSONLogs` class that inherits from `bucket` and implements the necessary `load_information_from_file` function. This was already kept in mind when designing and implementing the current version of Storage.
1. Users would not be affected by the simplified configuration, as the `type` attribute could be ignored by the parser.

### Impact of the changes

Implementing these changes would require the following:
- Perform manual testing.
- Updating the Core unit tests for GCP. These are simple changes.
- Update python module unit tests.
- Update the integration tests.
- Update documentation.

## Tasks
- [ ] Apply the changes
- [ ] Test in a manager.
- [ ] Test in an agent.
- [ ] Update Core tests.
- [ ] Update unit tests.
- [ ] Update Integration tests.
- [ ] Unit tests without failures. Updated if there are any relevant changes.
- [ ] Integration tests without failures. Updated if there are any relevant changes.
- [ ] Update the documentation.
- [ ] Add entry to the changelog.
