### ISSUE TITLE
Update GCP parser for the credentials_file option

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#15346]
| Affected integration |
|---|
| GCloud |

## Description

The `credentials_file` parameter is common to both pubsub and Storage integrations. It's also a required parameter in our `get_script_arguments` configuration in `tools.py`.

Since this parameter is required by the `ArgumentParser` itself, the module does not perform any checking or error handling if it is not present. If this parameter is not provided, the argument parser fails and displays its generic error.

Is in the core parser (`gcp.c`) side where we should make sure this parameter is provided. We have to update the parser to show us an error if it is not applied, in the same way that happens with the `integration_type` option.

## Tasks
- [ ] Update the core parser
- [ ] Test in a manager.
- [ ] Test in an agent.
- [ ] Unit tests without failures. Updated if there are any relevant changes.
- [ ] Add entry to the changelog if necessary.

**Comment by RamosFe** [comment]
## Update  GCP Bucket

Tested if the `parser` raises an error when using the following configuration in `ossec.conf`:

```
<gcp-bucket>
    <run_on_start>yes</run_on_start>
    <interval>1m</interval>
    <logging>debug</logging>
    <bucket type="access_logs">
        <name>framework-test-bucket</name>
        <!-- <credentials_file>/var/ossec/wodles/gcloud/credentials.json</credentials_file> !-->
        <only_logs_after>2021-Nov-01</only_logs_after>
        <remove_from_bucket>no</remove_from_bucket>
    </bucket>
</gcp-bucket>
```
After making these changes to the configuration and restarting Wazuh the following error was raised:

```
2023/05/04 16:23:31 wazuh-db[30281] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2023/05/04 16:23:31 wazuh-db[30281] main.c:119 at main(): DEBUG: Wazuh home directory: /var/ossec
2023/05/04 16:23:36 wazuh-remoted[30299] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2023/05/04 16:23:35 wazuh-remoted[30299] main.c:130 at main(): DEBUG: Wazuh home directory: /var/ossec
2023/05/04 16:23:36 wazuh-remoted[30299] main.c:148 at main(): DEBUG: This is not a worker
2023/05/04 16:23:36 wazuh-modulesd: ERROR: No value defined for tag 'credentials_file' in module 'gcp-bucket'.
2023/05/04 16:23:36 wazuh-modulesd: ERROR: (1202): Configuration error at 'etc/ossec.conf'.
wazuh-modulesd: Configuration error. Exiting
```

Checking the parser for `gcp bucket`, the validation for the `credentials_file` option exists:

https://github.com/wazuh/wazuh/blob/e958b3c818a25ad1405db11bd17032f8970e1881/src/config/wmodules-gcp.c#L400-L403

**Comment by RamosFe** [comment]
## Conclusion

The `gcp` parser raises an error when the option `credentials_file` is missing for `GCP Sub/Pub` and `GCP Bucket` so there is no need to add another validation to the already existing code.
