### ISSUE TITLE
Engine - Enable HLP as function helpers

### ISSUE THREAD

**Issue by JavierBejMen** [wazuh/wazuh#15421]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|5.0.0 | Engine | Manager | Packages/Sources | OS version |

## Description
The engine must allow the use of HLP parsers through function helpers and the use of the logpar block in the normalize stage. Also, we need to implement all requirements stated in the design.

## Tasks
- [x] Function helpers to parse and extract for each parser (mappings).
- [x] Function helpers to parse and check for each parser (conditionals).
- [x] Block logpar inside normalize's blocks.
- [x] Update implementation to fit the requirements.
- [ ] Update user manual.
- [ ] QA validation
