### ISSUE TITLE
Build a manager for AIX

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#15502]
|Base version|Target platform|Architecture|
|---|---|---|
|3.1.0|AIX 7.1 - 7.3|POWER7 - Power10|

This task aims to provide a manager running on AIX 7.1+ to monitor itself locally and send alerts via Syslog.

## Phase 1: Build a manager in local mode

- Build a manager for the following architectures:
    - POWER7.
    - POWER8.
    - POWER9.
    - Power10.

### Deliverable

- Native packages for Wazuh Manager for the mentioned architectures.

We will include the packages in folder `aix` at [https://packages-dev.wazuh.com/custom](https://packages-dev.wazuh.com).

**Results:**
[POWER7 installer](https://packages-dev.wazuh.com/custom/aix/wazuh-local-3.1.0-1.aix7.1.power7.ppc.rpm). 
[POWER8 installer](https://packages-dev.wazuh.com/custom/aix/wazuh-local-3.1.0-1.aix7.1.power8.ppc.rpm).
[POWER9 installer](https://packages-dev.wazuh.com/custom/aix/wazuh-local-3.1.0-1.aix7.1.power9.ppc.rpm).
Power10 installer.

### Subtask
- [X] https://github.com/wazuh/wazuh-packages/issues/1978

## Phase 2: Build a manager with restricted capabilities

- Build a manager on AIX, optimized for the different PowerPC architectures.
- Be able to disable the compilation of:
    - wazuh-remoted
    - wazuh-apid
    - wazuh-clusterd
- Provide a manager package that has these components disabled by default:
    - Remote incoming connections.
    - RESTful API.
    - Cluster.
    - Vulnerability Detector.

### Deliverable

1. Development branch with the following changes:
    - Makefile: remove `TARGET=local` and add `BUILD_REMOTED=y|n`
    - Select which components to include in the sources installer.
2. Native packages for Wazuh Manager for:
    - POWER7.
    - POWER8.
    - POWER9.
    - Power10.

### Subtask

- [x] https://github.com/wazuh/wazuh/issues/15971

## Phase 3: Test the manager

- Functional tests on the following capabilities:
    - File integrity monitoring (scheduled scan).
    - Log collector.
- Performance tests for each architecture.
- Footprint tests:
    - Disk.
    - Memory.
    - CPU usage.
    - Resource usage (file descriptors).

### Deliverable

- An issue with the test results.

### Subtask

- [x] https://github.com/wazuh/wazuh-qa/issues/3676

## Phase 4: Update manager to 4.3.0 with restricted capabilities

- Rebase the local mode deprecation (phase 2) to branch 4.3.
- Build the manager skipping Remoted, API, and Clusterd for AIX.

### Subtask

- [x] https://github.com/wazuh/wazuh/issues/16392

## Phase 5: Extend the capabilities of the manager for AIX

The following capabilities are not currently available on AIX. We desire to add them to this manager:

- Vulnerability detection:
    - Package inventory.
    - Feed of vulnerabilities affecting packages on AIX.
- File integrity monitoring:
    - Real-time engine.
    - Who-data engine.
- Security configuration assessment:
    - SCA policy for IBM AIX.

**Comment by MarcelKemp** [comment]
## Phase 2: Build a manager with restricted capabilities

|Development branch|
|---|
|[15502-build-restricted-AIX-manager](https://github.com/wazuh/wazuh/tree/15502-build-restricted-AIX-manager)|

### Development

In this development phase, we have started working from the _`v3.1.0`_ branch, where we have modified the code to include the option to disable compilation for some modules in their respective Makefile:
- Remote incoming connections. This module would prevent the compilation of `ossec-remoted` and `ossec-authd`.
- Cluster. This would prevent the compilation of `wazuh-clusterd` and `wazuh-internal-clusterd`.
- RESTful API. For _v3.1.0_ no changes have been made, as it is an additional installation of the [wazuh-api](https://github.com/wazuh/wazuh-api) repository, which has to be done manually.
- Vulnerability detector. In _v3.1.0_ it is not yet included as a module, so it does not have any compilation.

In addition, the following changes requested in the deliverable section have been included:
- Remove `TARGET=local` and add new `BUILD_REMOTED` parameter, which has largely replaced the conditions for local installation.
- Changes to the installation script (`install.sh`) so that the user can enable or disable the installation (including compilation) of these modules.

### Tasks
- [x] Analysis of deliverable for `v3.1.0`
- [x] Remove `TARGET=local`
- Disable component compilation:
  - [x] Add `BUILD_REMOTED`
  - [ ] Add `BUILD_CLUSTERD`
- [ ] Testing in an _AIX_ environment

**Comment by DFolchA** [comment]
## Update 

Build and test packages with the requested changes:

### POWER 8
```
bash-4.4# rpm -ihv output/wazuh-local-4.3.11-1.aix7.1.power8.ppc.rpm 
Preparing...                          ################################# [100%]
Updating / installing...
   1:wazuh-local-4.3.11-1             ################################# [100%]
rpm_share: 0645-024 Unable to access directory /var/ossec/queue/vulnerabilities
rpm_share: 0645-007 ATTENTION: update_dir() returned an unexpected result.
rpm_share: 0645-007 ATTENTION: update_inst_root() returned an unexpected result.
bash-4.4# /var/ossec/bin/wazuh-control start
Starting Wazuh v4.3.11...

Started wazuh-csyslogd...
Started wazuh-dbd...
2023/07/26 08:24:07 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
Started wazuh-integratord...
Started wazuh-agentlessd...
Started wazuh-db...
Started wazuh-execd...
2023/07/26 08:24:07 wazuh-maild: INFO: E-Mail notification disabled. Clean Exit.
Started wazuh-maild...
Started wazuh-analysisd...
Started wazuh-syscheckd...
Started wazuh-logcollector...
Started wazuh-monitord...
Started wazuh-modulesd...
Completed.
bash-4.4# cat /var/ossec/etc/internal_options.conf |grep wazuh.thread_stack_size
wazuh.thread_stack_size=2048
bash-4.4# tail -n 8 /var/ossec/etc/ossec.conf 
<ossec_config>
  <syslog_output>
    <server>server.com</server>
    <format>json</format>
    <use_fqdn>yes</use_fqdn>
  </syslog_output>
</ossec_config>

bash-4.4# 
```

### POWER 9
```
bash-4.4# rpm -ihv output/wazuh-local-4.3.11-1.aix7.1.power9.ppc.rpm 
Preparing...                          ################################# [100%]
Updating / installing...
   1:wazuh-local-4.3.11-1             ################################# [100%]
rpm_share: 0645-024 Unable to access directory /var/ossec/queue/vulnerabilities
rpm_share: 0645-007 ATTENTION: update_dir() returned an unexpected result.
rpm_share: 0645-007 ATTENTION: update_inst_root() returned an unexpected result.
bash-4.4# /var/ossec/bin/wazuh-control start
Starting Wazuh v4.3.11...

Started wazuh-csyslogd...
Started wazuh-dbd...
2023/07/26 08:24:01 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
Started wazuh-integratord...
Started wazuh-agentlessd...
Started wazuh-db...
Started wazuh-execd...
2023/07/26 08:24:01 wazuh-maild: INFO: E-Mail notification disabled. Clean Exit.
Started wazuh-maild...
Started wazuh-analysisd...
Started wazuh-syscheckd...
Started wazuh-logcollector...
Started wazuh-monitord...
Started wazuh-modulesd...
Completed.
bash-4.4# 
bash-4.4# cat /var/ossec/etc/internal_options.conf |grep wazuh.thread_stack_size
wazuh.thread_stack_size=2048
bash-4.4# tail -n 8 /var/ossec/etc/ossec.conf 
<ossec_config>
  <syslog_output>
    <server>server.com</server>
    <format>json</format>
    <use_fqdn>yes</use_fqdn>
  </syslog_output>
</ossec_config>

bash-4.4# 

```

**Comment by vikman90** [comment]
Let's block this issue by management as the customer is not responding.
