### ISSUE TITLE
Engine - Store host information to enrich events

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#15500]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0| Engine| Manager| Packages/Sources | OS version |

In order to enrich the events with the information of the system where they have been collected, we want to create a decoder that takes advantage of the information of Syscollector.

The initial approach is to store the system information as an [ECS host object](https://www.elastic.co/guide/en/ecs/current/ecs-host.html) in a KVDB.

Then, we have to create another decoder that for all ingested events adds the host information from the KVDB to the event to be processed.

For all this, it is also necessary to add new helper functions for KVDB: one for writing and one for deleting.

## Tasks
- [x] Implement functionality
  - [x] Function helper `+kvdb_set`
  - [x] Function helper `+kvdb_delete`
  - [x] Change of the function helper `+s_append` by `+ef_append` to consider arrays and objects
  - [x] Decoder to save Syscollector information
  - [x] Decoder to enrich host information.
- [ ] Update Documentation
- [ ] QA validate

**Comment by JcabreraC** [comment]
## Host Fields
| ECS field | Value (_Dbsync_ / _Syscollector_ / _other_) | Wazuh field | Reason |
| ---- | ----- | ---- | ---- |
| host.architecture | data.attributes.architecture / data.architecture | host.architecture | |
| host.boot.id | null | | Not available in dbsync/syscollector events |
| host.cpu.usage | null | | Not available in dbsync/syscollector events |
| host.disk.read.bytes | null | | Not available in dbsync/syscollector events | 
| host.disk.write.bytes | null | | Not available in dbsync/syscollector events |
| host.domain | null | | Not available in dbsync/syscollector events | 
| host.hostname | data.attributes.hostname / data.hostname | host.hostname | |
| host.id | agent.id | host.id | |
| host.ip | data.attributes.address / data.address | host.ip | |
| host.mac | data.attributes.mac / data.mac | host.mac | |
| host.name | data.attributes.hostname / data.hostname | host.name | | 
| host.network.egress.bytes | null | | At the moment it is not possible to process such information, given how the data is received from the agents |
| host.network.egress.packets | null | | At the moment it is not possible to process such information, given how the data is received from the agents | 
| host.network.ingress.bytes | null | | At the moment it is not possible to process such information, given how the data is received from the agents | 
| host.network.ingress.packets | null | | At the moment it is not possible to process such information, given how the data is received from the agents | 
| host.pid_ns_ino | null | | Not available in dbsync/syscollector events | 
| host.type | null | | Not available in dbsync/syscollector events |
| host.uptime | null | | Not available in dbsync/syscollector events |
| host.os.family | null | | Not available in dbsync/syscollector events |
| host.os.full | null | | Not available in dbsync/syscollector events |
| host.os.kernel | data.attributes.release / data.release | host.os.kernel | |
| host.os.name | data.attributes.os_name / data.os_name | host.os.name | |
| host.os.platform | data.attributes.os_platform / data.os_platform | host.os.platform | |
| host.os.type | data.attributes.sysname / data.sysname / windows | host.os.type | |
| host.os.version | data.attributes.os_version / data.os_version | host.os.version | |
