### ISSUE TITLE
New decoders and rules for macOS 13 Ventura and olders

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh#15567]
|Wazuh version| Component | Action type |
|---|---|---|
|4.x.x| Ruleset |Improvement |

Improve the current Ruleset to add the decoder/rules to manage and alert from analyzing the logs collected from macOS 13.0 Ventura systems. 

- [x] Analyze currently collected logs.
- [x] Verify backward compatibility with previous macOS versions.
- [x] Propose ossec.conf modification as needed to ensure default log collection on MacOS environments.
- [x] Review possible conflicts with the current decoder based on standard Linux services like Syslog, auth.log, and others.
- [x] Create decoders and rules for version 4.x.x ruleset.
- [x] Use IDs from 89600 to 89699

Blocked by
https://github.com/wazuh/wazuh/issues/16751

**Comment by ooniagbi** [comment]
We discovered a time zone issue with the pre-decoder for macOS logs and opened this issue: https://github.com/wazuh/wazuh/issues/15669

**Comment by ooniagbi** [comment]
We are currently investigating how this [comment](https://github.com/wazuh/wazuh/issues/15555#issuecomment-1335440269) affects our work and if there are any workarounds.

**Comment by ooniagbi** [comment]
We have used the following queries to generate logs for `sshd`, `sudo`, and `tccd` processes in macOS:

<localfile>
  <location>macos</location>
  <log_format>macos</log_format>
  <query type="trace,log,activity" level="info">process == "sshd"</query>
</localfile>

<localfile>
  <location>macos</location>
  <log_format>macos</log_format>
  <query type="trace,log,activity" level="info">process == "sudo"</query>
</localfile>

<localfile>
  <location>macos</location>
  <log_format>macos</log_format>
  <query type="trace,log,activity" level="info">process == "tccd"</query>
</localfile>

We have confirmed that the current ruleset for` sshd` and `sudo` events are applicable for macOS logs obtained using the query. Examples:

```
{
   "timestamp":"2022-12-19T14:43:55.304+0200",
   "rule":{
      "level":5,
      "description":"sshd: Attempt to login using a non-existent user",
      "id":"5710",
      "mitre":{
         "id":[
            "T1110.001",
            "T1021.004",
            "T1078"
         ],
         "tactic":[
            "Credential Access",
            "Lateral Movement",
            "Defense Evasion",
            "Persistence",
            "Privilege Escalation",
            "Initial Access"
         ],
         "technique":[
            "Password Guessing",
            "SSH",
            "Valid Accounts"
         ]
      },
      "firedtimes":11,
      "mail":false,
      "groups":[
         "syslog",
         "sshd",
         "authentication_failed",
         "invalid_login"
      ],
      "gdpr":[
         "IV_35.7.d",
         "IV_32.2"
      ],
      "gpg13":[
         "7.1"
      ],
      "hipaa":[
         "164.312.b"
      ],
      "nist_800_53":[
         "AU.14",
         "AC.7",
         "AU.6"
      ],
      "pci_dss":[
         "10.2.4",
         "10.2.5",
         "10.6.1"
      ],
      "tsc":[
         "CC6.1",
         "CC6.8",
         "CC7.2",
         "CC7.3"
      ]
   },
   "agent":{
      "id":"013",
      "name":"MacOS",
      "ip":"10.0.2.15"
   },
   "manager":{
      "name":"localhost.localdomain"
   },
   "id":"1671453835.2926619",
   "full_log":"2022-12-19 06:43:52.342632-0600  localhost sshd[2902]: Failed password for invalid user hacker from 192.168.56.1 port 58225 ssh2",
   "predecoder":{
      "program_name":"sshd",
      "timestamp":"2022-12-19 06:43:52.342632-0600"
   },
   "decoder":{
      "parent":"sshd",
      "name":"sshd"
   },
   "data":{
      "srcip":"192.168.56.1",
      "srcuser":"hacker"
   },
   "location":"macos"
}
```
```
{
   "timestamp":"2022-12-19T14:41:45.661+0200",
   "rule":{
      "level":3,
      "description":"Successful sudo to ROOT executed.",
      "id":"5402",
      "mitre":{
         "id":[
            "T1548.003"
         ],
         "tactic":[
            "Privilege Escalation",
            "Defense Evasion"
         ],
         "technique":[
            "Sudo and Sudo Caching"
         ]
      },
      "firedtimes":1,
      "mail":false,
      "groups":[
         "syslog",
         "sudo"
      ],
      "pci_dss":[
         "10.2.5",
         "10.2.2"
      ],
      "gpg13":[
         "7.6",
         "7.8",
         "7.13"
      ],
      "gdpr":[
         "IV_32.2"
      ],
      "hipaa":[
         "164.312.b"
      ],
      "nist_800_53":[
         "AU.14",
         "AC.7",
         "AC.6"
      ],
      "tsc":[
         "CC6.8",
         "CC7.2",
         "CC7.3"
      ]
   },
   "agent":{
      "id":"013",
      "name":"MacOS",
      "ip":"10.0.2.15"
   },
   "manager":{
      "name":"localhost.localdomain"
   },
   "id":"1671453705.2901972",
   "full_log":"2022-12-19 06:41:39.441045-0600  localhost sudo[1242]:    macos : TTY=ttys000 ; PWD=/Users/macos ; USER=root ; COMMAND=/usr/bin/cd /Library/Ossec/",
   "predecoder":{
      "program_name":"sudo",
      "timestamp":"2022-12-19 06:41:39.441045-0600"
   },
   "decoder":{
      "parent":"sudo",
      "name":"sudo",
      "ftscomment":"First time user executed the sudo command"
   },
   "data":{
      "srcuser":"macos",
      "dstuser":"root",
      "tty":"ttys000",
      "pwd":"/Users/macos",
      "command":"/usr/bin/cd /Library/Ossec/"
   },
   "location":"macos"
}
```

**Comment by ooniagbi** [comment]
tccd decoders have been added: https://github.com/wazuh/wazuh/blob/02bf9d1766939c433bddfc37e66f1fec4408e57e/ruleset/decoders/macos_decoders

**Comment by ooniagbi** [comment]
tccd rules have been added: https://github.com/wazuh/wazuh/blob/b1546cc3559d4e2344cdda7cce27f7af9685f750/ruleset/rules/macos_rules

**Comment by ooniagbi** [comment]
`tccd` decoders and rules logtest results:
```
**Messages:
	WARNING: (7003): '61dfad42' token expires
	INFO: (7202): Session initialized with token 'e9913a51'

**Phase 1: Completed pre-decoding.
	full event: '2022-12-15 12:50:32.169646-0800  localhost tccd[642]: [com.apple.TCC:access] Update Access Record: kTCCServiceSystemPolicyDesktopFolder for com.apple.Terminal to Allowed at 1671137432 (2022-12-15 20:50:32 +0000)'
	timestamp: '2022-12-15 12:50:32.169646-0800'
	program_name: 'tccd'

**Phase 2: Completed decoding.
	name: 'macOS_tcc_process'
	application: 'com.apple.Terminal'
	service: 'kTCCServiceSystemPolicyDesktopFolder'
	time_access_granted: '20:50:32'

**Phase 3: Completed filtering (rules).
	id: '100020'
	level: '5'
	description: 'com.apple.Terminal has been granted permission to kTCCServiceSystemPolicyDesktopFolder at 20:50:32'
	groups: '["macOS","tccd_process"]'
	firedtimes: '1'
	mail: 'false'
**Alert to be generated.
```
```
**Messages:
	WARNING: (7003): '61dfad42' token expires
	INFO: (7202): Session initialized with token 'f8a6e025'

**Phase 1: Completed pre-decoding.
	full event: '2022-12-18 04:39:18.563903-0100  localhost tccd[1162]: [com.apple.TCC:access] Update Access Record: kTCCServiceMicrophone for us.zoom.xos to Denied at 1671334758 (2022-12-18 03:39:18 +0000)'
	timestamp: '2022-12-18 04:39:18.563903-0100'
	program_name: 'tccd'

**Phase 2: Completed decoding.
	name: 'macOS_tcc_process'
	application: 'us.zoom.xos'
	service: 'kTCCServiceMicrophone'
	time_access_denied: '03:39:18'

**Phase 3: Completed filtering (rules).
	id: '100021'
	level: '5'
	description: 'us.zoom.xos has been denied permission to kTCCServiceMicrophone at 03:39:18'
	groups: '["macOS","tccd_process"]'
	firedtimes: '1'
	mail: 'false'
**Alert to be generated.
```

**Comment by ooniagbi** [comment]
We created the following query for screensharing events on macOS:
```
<localfile>
  <location>macos</location>
  <log_format>macos</log_format>
  <query type="trace,log,activity" level="info">process == "screensharingd" AND message CONTAINS "Authentication:"</query>
</localfile>
```
We're working on creating rules/decoders for these events.

**Comment by ooniagbi** [comment]
Added new rules and decoders for `loginwindow` events (login, logoff, screen lock/unlock), and `screensharingd` events (failure, success).

https://github.com/wazuh/wazuh/commit/b45c3c4b18a814aa246d89fa3a65b7e1b976c564

https://github.com/wazuh/wazuh/commit/dee53b5d2834f4b01f09d7827f92e1ed78600cca

**Comment by ooniagbi** [comment]
We have been collecting and analyzing logs for the following queries:

```
process == “kextd” && sender == “IOKit”	Captures successful and failed attempts to add kernel extensions

<localfile>
  <location>macos</location>
  <log_format>macos</log_format>
  <query type="trace,log,activity" level="info">process == “kextd” AND sender == “IOKit”</query>
</localfile>

process == “securityd” && eventMessage CONTAINS “Session ” && subsystem == “com.apple.securityd” 	Captures session creation and destruction events

<localfile>
  <location>macos</location>
  <log_format>macos</log_format>
  <query type="trace,log,activity" level="info">process == “securityd” AND eventMessage CONTAINS “Session ” AND subsystem == “com.apple.securityd”</query>
</localfile>

process == “loginwindow” && sender == “Security”	Captures keychain.db unlock events

<localfile>
  <location>macos</location>
  <log_format>macos</log_format>
  <query type="trace,log,activity" level="info">process == “loginwindow” AND sender == “Security”</query>
</localfile>
```

**Comment by ooniagbi** [comment]
We have tested and confirmed that a query with multiple processes is possible. 

> We are currently investigating how this [comment](https://github.com/wazuh/wazuh/issues/15555#issuecomment-1335440269) affects our work and if there are any workarounds.

We have tested and confirmed that a query with multiple processes is possible. This means we can create a single query to circumvent this issue. Further testing will confirm this.

**Comment by ooniagbi** [comment]
We are investigating how macOS handles malware events and what the complete list of processes for macOS is.

**Comment by ooniagbi** [comment]
Siumulated events for kextd:

```
2023-01-11 09:02:17.961672-0800 0x1ec      Error       0x0                  92     0    kextd: (IOKit) [com.apple.kext:kextlog] Kext rejected due to system policy: <OSKext 0x600003d7b780 [0x7fff888eccc0]> { URL = "file:///Library/StagedExtensions/Library/Filesystems/lucidfs/lucidfs.fs/Contents/Resources/[mount_lucidfs.app/Contents/Extensions/10.12/lucidfs.kext/](http://mount_lucidfs.app/Contents/Extensions/10.12/lucidfs.kext/)", ID = "com.lucidlink.lucidfs.filesystems.lucidfs" }

2023-01-11 09:02:17.961711-0800 0x1ec      Error       0x0                  92     0    kextd: (IOKit) [com.apple.kext:kextlog] com.lucidlink.lucidfs.filesystems.lucidfs failed security checks; failing.

2023-01-11 09:03:19.151737-0800 0x1ec      Error       0x0                  92     0    kextd: (IOKit) [com.apple.kext:kextlog] Kext rejected due to system policy: <OSKext 0x600003d78ae0 [0x7fff888eccc0]> { URL = "file:///Library/StagedExtensions/Library/Filesystems/lucidfs/lucidfs.fs/Contents/Resources/[mount_lucidfs.app/Contents/Extensions/10.12/lucidfs.kext/](http://mount_lucidfs.app/Contents/Extensions/10.12/lucidfs.kext/)", ID = "com.lucidlink.lucidfs.filesystems.lucidfs" }

2023-01-11 09:03:19.151815-0800 0x1ec      Error       0x0                  92     0    kextd: (IOKit) [com.apple.kext:kextlog] com.lucidlink.lucidfs.filesystems.lucidfs failed security checks; failing.
```
We have created some rules for securityd events also. They will be updated this Friday.

**Comment by ooniagbi** [comment]
Added decoders for `securityd`: https://github.com/wazuh/wazuh/commit/734f76a4ac08c7696730ee57acf8e1bd4006dc34

**Comment by ooniagbi** [comment]
Added new rules for `securityd`: https://github.com/wazuh/wazuh/commit/2f259f47669566148b0ba71c8bee694d7772fb88

**Comment by ooniagbi** [comment]
Full list of queries we are writing rules and decoders for:

<html>
<body>
<ul dir="auto" style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box;">Gatekeeper events</li><li style="box-sizing: border-box; margin-top: 0.25em;">Xprotect events</li><li style="box-sizing: border-box; margin-top: 0.25em;">Apple script events</li><li style="box-sizing: border-box; margin-top: 0.25em;">sudo, logons, opendirectory events</li></ul><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Some other interesting events (from<span> </span><a href="https://www.crowdstrike.com/blog/how-to-leverage-apple-unified-log-for-incident-response/" rel="nofollow" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">https://www.crowdstrike.com/blog/how-to-leverage-apple-unified-log-for-incident-response/</a>):</p>

Predicate | Description
-- | --
process == “sudo” | Captures command line activity run with elevated privileges
process == “logind” | Captures user login events
process == “tccd” | Captures events that indicate permissions and access violations
process == “sshd” | Captures successful, failed and general ssh activity
process == “kextd” && sender == “IOKit” | Captures successful and failed attempts to add kernel extensions
process == “screensharingd \|\| process == “ScreensharingAgent”’ | Captures events that indicate successful or failed authentication via screen sharing
process == “loginwindow” && sender == “Security” | Captures keychain.db unlock events
process == “securityd” && eventMessage CONTAINS “Session ” && subsystem == “com.apple.securityd” | Captures session creation and destruction events


</body>
</html>

**Comment by ooniagbi** [comment]
Project summary/status at at 16/01/2023

- [ ] sudo events - We have confirmed that the current rules work for macOS sudo events.
- [ ] logind events - In progress.
- [ ] tccd events - We have created new decoders and rules for tccd events.
- [ ] sshd events - We have confirmed that the current rules work for macOS sshd events.
- [ ] kextd events - In progress.
- [ ] screensharingd events - We have created new decoders and rules for screensharingd events.
- [ ] keychain.db unlock events - We have had issues simulating these events. For now, they only occur when the OS is turned on.
- [ ] session creation and destruction events - We have created new decoders and rules for these events.
- [ ] Gatekeeper events - not started.
- [ ] Xprotect events - not started.
- [ ] Apple script events - not started.
- [ ] logons, opendirectory events - rules and decoders for login events have been added. opendirectory events - not started.

**Comment by ooniagbi** [comment]
According to [this](https://www.maketecheasier.com/add-remove-kexts-from-macos/) kext has been deprecated for macOS Big Sur and later. This explains why we were having issues simulating some events. We will ignore that query.

**Comment by ooniagbi** [comment]
Wazuh query for macOS events covered so far:

```
<localfile>
  <location>macos</location>
  <log_format>macos</log_format>
  <query type="trace,log,activity" level="info">(process == "sudo") or (process == "sshd") or (process == "tccd") or (message contains "SessionAgentNotificationCenter") or (process == "screensharingd" and message contains "Authentication") or (process == "securityd" and eventMessage contains "Session" and subsystem == "com.apple.securityd")</query>
</localfile>
```

**Comment by ooniagbi** [comment]
Running tests:

- [ ] sudo
- [ ] sshd
- [ ] login, logout, screenlock, screen unlock
