### ISSUE TITLE
Fix GCP Wodle error messages

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#15569]
| Affected integration |
|---|
| GCloud |

## Description

During #15536 it was found that in case of providing erroneous `project_id` or `subscription_name` fields, the displayed messages do not accurately indicate the affected field.

Wrong project returns subscription ERROR message
```
./gcloud --integration_type pubsub --project wazuh-dev-error --subscription_id wazuh-framework-subscription --credentials_file /var/ossec/wodles/gcloud/credentials.json --max_messages 50 --num_threads 4 --log_level 2
:gcloud_wodle: - DEBUG - Setting 4 threads to pull 50 messages in total
:gcloud_wodle: - ERROR - An exception happened while running the wodle: GCloudPubSubSubscriptionError: The 'wazuh-dev-error' subscription is incorrect or the user credentials are not valid
```

Wrong subscription returns project ERROR message
```
./gcloud --integration_type pubsub --project wazuh-dev-123456 --subscription_id wazuh-error --credentials_file /var/ossec/wodles/gcloud/credentials.json --max_messages 50 --num_threads 4 --log_level 2
:gcloud_wodle: - DEBUG - Setting 4 threads to pull 50 messages in total
:gcloud_wodle: - ERROR - An exception happened while running the wodle: GCloudPubSubProjectError: The 'wazuh-error' project ID is incorrect or the user does not have permissions to access to it
```

## Tasks
- [ ] Modify the code in order to show the correct messages.
- [ ] Test in a manager.
- [ ] Test in an agent.
- [ ] Unit tests without failures. Updated if there are any relevant changes.
- [ ] Update the documentation if necessary.
- [ ] Add entry to the changelog if necessary.

**Comment by fdalmaup** [comment]
# Issue Update

The `GCloudError` instances created when a `google.api_core.exceptions` was raised were mixed. The code has been modified and now the error messages shown are now correct.

Incorrect `project_id`
```
./gcloud --integration_type pubsub --project wazuh-dev-error --subscription_id wazuh-framework-subscription --credentials_file /var/ossec/wodles/gcloud/credentials.json --max_messages 50 --num_threads 4 --log_level 2
:gcloud_wodle: - DEBUG - Setting 4 threads to pull 50 messages in total
:gcloud_wodle: - ERROR - An exception happened while running the wodle: GCloudPubSubProjectError: The 'wazuh-dev-error' project ID is incorrect or the user does not have permissions to access to it
```

Incorrect `subscription_id`
```
./gcloud --integration_type pubsub --project wazuh-dev-123456 --subscription_id wazuh-error-sub --credentials_file /var/ossec/wodles/gcloud/credentials.json --max_messages 50 --num_threads 4 --log_level 2
:gcloud_wodle: - DEBUG - Setting 4 threads to pull 50 messages in total
:gcloud_wodle: - ERROR - An exception happened while running the wodle: GCloudPubSubSubscriptionError: The 'wazuh-error-sub' subscription is incorrect or the user credentials are not valid
```

Incorrect `project_id` and `subscription_id` shows 
```
./gcloud --integration_type pubsub --project wazuh-dev-error --subscription_id wazuh-error-sub --credentials_file /var/ossec/wodles/gcloud/credentials.json --max_messages 50 --num_threads 4 --log_level 2
:gcloud_wodle: - DEBUG - Setting 4 threads to pull 50 messages in total
:gcloud_wodle: - ERROR - An exception happened while running the wodle: GCloudPubSubProjectError: The 'wazuh-dev-error' project ID is incorrect or the user does not have permissions to access to it
```

## Test using ossec.conf in a manager with Python 3.9
Pending

## Test using ossec.conf in an agent with Python 3.6
Pending



## Unit tests
### Test report
[gcloud_test.zip](https://github.com/wazuh/wazuh/files/10142603/gcloud_test.zip)

### Test results

---
| **Test name** | **Pass** | **XPass** | **Skip** | **XFail** | **Fail** | **Issues Ref.** | **Status** |
|--|--|--|--|--|--|--|--|
| wodles/gcloud/tests/test_access_logs.py | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| wodles/gcloud/tests/test_bucket.py | 3 | 0 | 0 | 0 | 0 |  | :green_circle: |
| wodles/gcloud/tests/test_gcloud.py | 5 | 0 | 0 | 0 | 0 |  | :green_circle: |
| wodles/gcloud/tests/test_integration.py | 5 | 0 | 0 | 0 | 0 |  | :green_circle: |
| wodles/gcloud/tests/test_subscriber.py | 3 | 0 | 0 | 0 | 0 |  | :green_circle: |
