### ISSUE TITLE
Syscollector alerts after the first scan can be lost if the agent changes of worker

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#15639]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4 | syscollector wodle - analysisd| Agent and Manager| Any | Any |

Working branch: [15639-syscollector-deltas-on-worker-change](https://github.com/wazuh/wazuh/tree/15639-syscollector-deltas-on-worker-change)

# Description

## Introduction

Currently, syscollector has two mechanisms of synchronization with the manager: rsync and deltas. Both works together using the next flow
1. First scan is synchronized using rsync
2. Second scan is synchronized using deltas, and rsync after.
3. ...

A delta is a diff between the current scan and the last one, leading to 3 types of them: insertion, modification or delete.

- Insertion delta: contain all the information since is new and must be synchronized
- Modification delta: contains only the changed values and an entity identifier (primary key)
- Delete delta: contains only the entity identifier (primary key)

Deltas advantages were
- Low bandwith usage
- Reduce rsync interaction because they were explicitly changed by deltas
- Allow the creation of rules, and therefore, alerts

##  The problem

In a Wazuh Cluster, agents could freely change from worker to worker depending on the load balancer policy/availability, but the fact that deltas do not always contain all the information is not allowed to create alerts on those workers that do not have a previous information to modify/delete
 
### Steps
1. Agent starts. First syscollector scan is sync with Worker A using rsync
2. Agent changes (on the fly) from worker A to Worker B
3. Agent executes second syscollector scan and sync the results using deltas
4. Agente sync the second scan using rsync
### Expected
3. Worker B generate alerts  related to the second scan
4. Rsync between Worker B and the agent have only sync the left information that was not synced on the deltas sync
### Current
3. Worker B does not generate any alerts  related to the second scan
4. Rsync between Worker B and the agent have to recreate the full information in this worker

# DoD
- [x] Dbsync changes @Dwordcito 
  - [x] Allow dbsync to report all the information of deltas (i.e porting #12385 )
  - [x] Dbsync test (unit, smoke,interface,testtool)
- [x] Analysisd changes @Dwordcito
  - [x] Change syscollector decoder to support deltas containing all the payload
  - [x] Cleanup unused code
  - [x] Unit tests
  - [x] Integration tests update -> https://github.com/wazuh/wazuh-qa/issues/3673
- [x] Wazuh-db changes @jnasselle 
  - [x] Adapt wazuh-db syscollector deltas handling mechanism. NOTE: agent's inventory database should be created when the first alert arrives
  - [x] Cleanup unused code
  - [x] Unit tests update
  - [x] Integration tests  -> https://github.com/wazuh/wazuh-qa/issues/3673 @jnasselle 
- [x] Manual test
  - [x] https://github.com/wazuh/wazuh-qa/issues/3672
  - [x] https://github.com/wazuh/wazuh-qa/issues/3732
- [ ] Exploratory session https://github.com/wazuh/wazuh/issues/15824
