### ISSUE TITLE
Engine - Improve engine performance

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#15713]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|5.0.0 | Engine | Manager | Packages/Sources | OS version |

## Description
Some points in the engine that can be optimized to improve engine performance have been identified through benchmarks.

The changes to be made to improve performance are:
- Reduce the copy of JSON objects when doing a merge.
- Improve the algorithm that looks for the end token in a logical expression.
- Ensure only move semantics are used on Results/Traces.

## Tasks
- [x] Implement and ensure only move semantics are used on Results/Traces
- [ ] Implement merge improvement
- [ ] Implement end token algorithm improvement
- [ ] Update user manual.
- [ ] QA validation
