### ISSUE TITLE
Engine - Migration of test decoders to ruleset

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#15723]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|5.0.0 | Engine | Manager | Packages/Sources | OS version |

## Description
It is necessary to migrate the decoders used for engine testing to the current ruleset. These decoders have to adapt to the new parser and function helper that has been implemented.

With this, we will not only extend the ruleset but also identify if it is necessary to create or modify some tools to improve the writing of the decoders.

## Tasks
- [x] Migrate Ciscat decoder
- [x] Migrate Nginx error decoder
- [x] Migrate Nginx access decoder
- [x] Migrate postgress (csv) decoder
- [x] Migrate audit decoders
- [x] Migrate AWS decoders
- [x] Update Documentation
- [x] QA validate

**Comment by LucioDonda** [comment]
Auditd Fields Mapping

| ECS field                   | value                                                          | wazuh field                 | reason                                        |
| --------------------------- | -------------------------------------------------------------- | --------------------------- | --------------------------------------------- |
| auditd.log.data       |       | auditd.log.data   |       |
| auditd.log.denied_mask        |       | auditd.log.denied_mask    |       |
| auditd.log.device     |       | auditd.log.device |       |
| auditd.log.dir        |       | auditd.log.dir    |       |
| auditd.log.file       |       | auditd.log.file   |       |
| auditd.log.grp        |       | auditd.log.grp    |       |
| auditd.log.info       |       | auditd.log.info   |       |
| auditd.log.invalid_context        |       | auditd.log.invalid_context    
| auditd.log.name       |       | auditd.log.name   |       |
| auditd.log.new-chardev        |       | auditd.log.new-chardev    |       |
| auditd.log.new-disk       |       | auditd.log.new-disk   |       |
| auditd.log.new-fs     |       | auditd.log.new-fs |       |
| auditd.log.new-net        |       | auditd.log.new-net    |       |
| auditd.log.new-rng        |       | auditd.log.new-rng    |       |
| auditd.log.new_group      |       | auditd.log.new_group  |       |
| auditd.log.ocomm      |       | auditd.log.ocomm  |       |
| auditd.log.old-auid       |"auditd.log.old_auid"| auditd.log.old-auid   |       |
| auditd.log.old-chardev        |       | auditd.log.old-chardev    |       |
| auditd.log.old-disk       |       | auditd.log.old-disk   |       |
| auditd.log.old-fs     |       | auditd.log.old-fs |       |
| auditd.log.old-net        |       | auditd.log.old-net    |       |
| auditd.log.old-rng        |       | auditd.log.old-rng    |       |
| auditd.log.old-ses        |"auditd.log.old_ses"| auditd.log.old-ses    |       |
| auditd.log.operation      |       | auditd.log.operation  |       |
| auditd.log.path       |       | auditd.log.path   |       |
| auditd.log.proctitle      |       | auditd.log.proctitle  |       |
| auditd.log.profile        |       | auditd.log.profile    |       |
| auditd.log.record_type        |test_group| auditd.log.record_type    |       |
| auditd.log.requested_mask     |       | auditd.log.requested_mask |       |
| auditd.log.root_dir       |       | auditd.log.root_dir   |       |
| auditd.log.se | 14     |auditd.log.ses    | |
| auditd.log.sequence | 555     |auditd.log.sequence    | |
| auditd.log.src        | 127.0.0.1| auditd.log.src    |       |
| auditd.log.success        |       | auditd.log.success    |       |
| auditd.log.sw     |       | auditd.log.sw |       |
| auditd.log.vm     |       | auditd.log.vm |       |
| auditd.log.watch      |       | auditd.log.watch  |       |
| container.name        |       | container.name    |       |
| container.runtime     |       | container.runtime |       |
| event.action      | test_group | event.action  |       |
| event.category        |       | event.category    |       |
| event.kind        | event | event.kind    |       |
| event.module      | auditd | event.module  |       |
| event.outcome     | success | event.outcome |       |
| event.type        |       | event.type    |       |
| fileset.name      |       | fileset.name  |       |
| host.architecture     | x_86_64| host.architecture |       |
| message       |       | message   |       |
| network.direction     |ingress| network.direction |       |
| process.args      |       | process.args  |       |
| process.args_count        |       | process.args_count    |       |
| process.executable        |"/usr/sbin/groupadd"| process.executable    |       |
| process.exit_code     |       | process.exit_code |       |
| process.name      |       | process.name  |       |
| process.parent.pid        |       | process.parent.pid    |       |
| process.pid       | 2940| process.pid   |       |
| process.working_directory     |       | process.working_directory |       |
| source.address        | 127.0.0.1    | source.address    |       |
| source.as.number      |       | source.as.number  |       |
| source.as.organization.name       |       | source.as.organization.name   |       |
| timestamp     |"1610903123.444"| timestamp |       |
| user.audit.group.id       |       | user.audit.group.id   |       |
| user.audit.id     |    4294967295   | user.audit.id |       |
| user.effective.group.id       |       | user.effective.group.id   |       |
| user.effective.id     |       | user.effective.id |       |
| user.filesystem.group.id      |       | user.filesystem.group.id  |       |
| user.filesystem.id        |       | user.filesystem.id    |       |
| user.group.id     |       | user.group.id |       |
| user.id       |    0   | user.id   |       |
| user.name     |"charlie"| user.name |       |
| user.owner.group.id       |       | user.owner.group.id   |       |
| user.owner.id     |       | user.owner.id |       |
| user.saved.group.id       |       | user.saved.group.id   |       |
| user.saved.id     |       | user.saved.id |       |
| user.terminal     |   "pts/2"    | user.terminal |       |

**Comment by LucioDonda** [comment]
AWS S3 Fields Mapping:
| ecs field                   | value                                                          | wazuh field                 | reason                                        |
| --------------------------- | -------------------------------------------------------------- | --------------------------- | --------------------------------------------- |
| aws.s3access.authentication_type  |   | aws.s3access.authentication_type   | 
| aws.s3access.bucket_owner  |   | aws.s3access.bucket_owner   | 
| aws.s3access.bucket  |   | aws.s3access.bucket   | 
| aws.s3access.bytes_sent  |   | aws.s3access.bytes_sent   | 
| aws.s3access.cipher_suite  |   | aws.s3access.cipher_suite   | 
| aws.s3access.error_code  |   | aws.s3access.error_code   | 
| aws.s3access.host_header  |   | aws.s3access.host_header   | 
| aws.s3access.host_id  |   | aws.s3access.host_id   | 
| aws.s3access.http_status  |   | aws.s3access.http_status   | 
| aws.s3access.key  |   | aws.s3access.key   | 
| aws.s3access.object_size  |   | aws.s3access.object_size   | 
| aws.s3access.operation  |   | aws.s3access.operation   | 
| aws.s3access.referrer  |   | aws.s3access.referrer   | 
| aws.s3access.remote_ip  |   | aws.s3access.remote_ip   | 
| aws.s3access.request_id  |   | aws.s3access.request_id   | 
| aws.s3access.request_uri  |   | aws.s3access.request_uri   | 
| aws.s3access.requester  |   | aws.s3access.requester   | 
| aws.s3access.signature_version  |   | aws.s3access.signature_version   | 
| aws.s3access.tls_version  |   | aws.s3access.tls_version   | 
| aws.s3access.total_time  |   | aws.s3access.total_time   | 
| aws.s3access.turn_around_time  |   | aws.s3access.turn_around_time   | 
| aws.s3access.user_agent  |   | aws.s3access.user_agent   | 
| aws.s3access.version_id  |   | aws.s3access.version_id   | 
| client.address  |   | client.address   | 
| client.ip  |   | client.ip   | 
| client.user.id  |   | client.user.id   | 
| cloud.provider  |   | cloud.provider   | 
| event.action  |   | event.action   | 
| event.category  |   | event.category   | 
| event.code  |   | event.code   | 
| event.duration  |   | event.duration   | 
| event.id  |   | event.id   | 
| event.kind  |   | event.kind   | 
| event.type  |   | event.type   | 
| http.request.referrer  |   | http.request.referrer   | 
| http.response.body.bytes  |   | http.response.body.bytes   | 
| http.response.status_code  |   | http.response.status_code   | 
| related.ip  |   | related.ip   | 
| related.user  |   | related.user   | 
| timestamp  |   | timestamp   | 
| tls.cipher  |   | tls.cipher   |

**Comment by LucioDonda** [comment]
AWS S3 Fields Mapping:
| ECS field                   | Value                                                          | Wazuh Field                 | Reason                                        |
| --------------------------- | -------------------------------------------------------------- | --------------------------- | --------------------------------------------- |
| aws.cloudtrail.additional_eventdata | | aws.cloudtrail.additional_eventdata | | 
| aws.cloudtrail.api_version | | aws.cloudtrail.api_version | | 
| aws.cloudtrail.digest.end_time | | aws.cloudtrail.digest.end_time | | 
| aws.cloudtrail.digest.log_files | | aws.cloudtrail.digest.log_files | | 
| aws.cloudtrail.digest.newest_event_time | | aws.cloudtrail.digest.newest_event_time | | 
| aws.cloudtrail.digest.oldest_event_time | | aws.cloudtrail.digest.oldest_event_time | | 
| aws.cloudtrail.digest.previous_hash_algorithm | | aws.cloudtrail.digest.previous_hash_algorithm | | 
| aws.cloudtrail.digest.previous_s3_bucket | | aws.cloudtrail.digest.previous_s3_bucket | | 
| aws.cloudtrail.digest.public_key_fingerprint | | aws.cloudtrail.digest.public_key_fingerprint | | 
| aws.cloudtrail.digest.s3_bucket | | aws.cloudtrail.digest.s3_bucket | | 
| aws.cloudtrail.digest.signature_algorithm | | aws.cloudtrail.digest.signature_algorithm | | 
| aws.cloudtrail.digest.start_time | | aws.cloudtrail.digest.start_time | | 
| aws.cloudtrail.error_code | | aws.cloudtrail.error_code | | 
| aws.cloudtrail.error_message | | aws.cloudtrail.error_message | | 
| aws.cloudtrail.event_category | | aws.cloudtrail.event_category | | 
| aws.cloudtrail.event_type | | aws.cloudtrail.event_type | | 
| aws.cloudtrail.event_version | | aws.cloudtrail.event_version | | 
| aws.cloudtrail.insight_details | | aws.cloudtrail.insight_details | | 
| aws.cloudtrail.management_event | | aws.cloudtrail.management_event | | 
| aws.cloudtrail.read_only | | aws.cloudtrail.read_only | | 
| aws.cloudtrail.recipient_account_id | | aws.cloudtrail.recipient_account_id | | 
| aws.cloudtrail.request_id | | aws.cloudtrail.request_id | | 
| aws.cloudtrail.request_parameters | | aws.cloudtrail.request_parameters | | 
| aws.cloudtrail.resources.account_id | | aws.cloudtrail.resources.account_id | | 
| aws.cloudtrail.resources.arn | | aws.cloudtrail.resources.arn | | 
| aws.cloudtrail.resources.type | | aws.cloudtrail.resources.type | | 
| aws.cloudtrail.response_elements | | aws.cloudtrail.response_elements | | 
| aws.cloudtrail.service_event_details | | aws.cloudtrail.service_event_details | | 
| aws.cloudtrail.shared_event_id | | aws.cloudtrail.shared_event_id | | 
| aws.cloudtrail.user_identity.access_key_id | | aws.cloudtrail.user_identity.access_key_id | | 
| aws.cloudtrail.user_identity.arn | | aws.cloudtrail.user_identity.arn | | 
| aws.cloudtrail.user_identity.invoked_by | | aws.cloudtrail.user_identity.invoked_by | | 
| aws.cloudtrail.user_identity.session_context.creation_date | | aws.cloudtrail.user_identity.session_context.creation_date | | 
| aws.cloudtrail.user_identity.session_context.mfa_authenticated | | aws.cloudtrail.user_identity.session_context.mfa_authenticated | | 
| aws.cloudtrail.user_identity.session_context.session_issuer.account_id | | aws.cloudtrail.user_identity.session_context.session_issuer.account_id | | 
| aws.cloudtrail.user_identity.session_context.session_issuer.arn | | aws.cloudtrail.user_identity.session_context.session_issuer.arn | | 
| aws.cloudtrail.user_identity.session_context.session_issuer.principal_id | | aws.cloudtrail.user_identity.session_context.session_issuer.principal_id | | 
| aws.cloudtrail.user_identity.session_context.session_issuer.type | | aws.cloudtrail.user_identity.session_context.session_issuer.type | | 
| aws.cloudtrail.user_identity.type | | aws.cloudtrail.user_identity.type | | 
| aws.cloudtrail.vpc_endpoint_id | | aws.cloudtrail.vpc_endpoint_id | | 
| cloud.region | | cloud.region | | 
| event.action | | event.action | | 
| event.id | | event.id | | 
| event.provider | | event.provider | | 
| event.outcome | | event.outcome | | 
| file.path | | file.path | | 
| related.hash | | related.hash | | 
| related.user | | related.user | | 
| related.user | | related.user | | 
| related.user | | related.user | | 
| related.user | | related.user | | 
| source.address | | source.address | | 
| source.ip | | source.ip | | 
| timestamp | | timestamp | | 
| user_agent | | user_agent | | 
| user_agent.original | | user_agent.original | | 
| user.id | | user.id | |

**Comment by LucioDonda** [comment]
ELB fields Mapping:
| ECS field                   | Value                                                          | Wazuh field                 | Reason                                        |
| --------------------------- | -------------------------------------------------------------- | --------------------------- | --------------------------------------------- |
| aws.elb.action_executed | | aws.elb.action_executed | 
| aws.elb.backend.http.response.status_code | | aws.elb.backend.http.response.status_code | 
| aws.elb.backend.ip | | aws.elb.backend.ip | 
| aws.elb.backend.port | | aws.elb.backend.port | 
| aws.elb.backend_processing_time.sec | | aws.elb.backend_processing_time.sec | 
| aws.elb.chosen_cert.arn | | aws.elb.chosen_cert.arn | 
| aws.elb.chosen_cert.serial | | aws.elb.chosen_cert.serial | 
| aws.elb.classification | | aws.elb.classification | 
| aws.elb.classification_reason | | aws.elb.classification_reason | 
| aws.elb.connection_time.ms | | aws.elb.connection_time.ms | 
| aws.elb.error.reason | | aws.elb.error.reason | 
| aws.elb.incoming_tls_alert | | aws.elb.incoming_tls_alert | 
| aws.elb.listener | | aws.elb.listener | 
| aws.elb.matched_rule_priority | | aws.elb.matched_rule_priority | 
| aws.elb.name | | aws.elb.name | 
| aws.elb.protocol | | aws.elb.protocol | 
| aws.elb.redirect_url | | aws.elb.redirect_url | 
| aws.elb.request_processing_time.sec | | aws.elb.request_processing_time.sec | 
| aws.elb.response_processing_time.sec | | aws.elb.response_processing_time.sec | 
| aws.elb.ssl_cipher | | aws.elb.ssl_cipher | 
| aws.elb.ssl_named_group | | aws.elb.ssl_named_group | 
| aws.elb.ssl_protocol | | aws.elb.ssl_protocol | 
| aws.elb.target_group.arn | | aws.elb.target_group.arn | 
| aws.elb.target_port | | aws.elb.target_port | 
| aws.elb.target_status_code | | aws.elb.target_status_code | 
| aws.elb.tls_handshake_time.ms | | aws.elb.tls_handshake_time.ms | 
| aws.elb.trace_id | | aws.elb.trace_id | 
| aws.elb.type | | aws.elb.type | 
| cloud.provider | | cloud.provider | 
| event.category | | event.category | 
| event.dataset | | event.dataset | 
| event.end | | event.end | 
| event.kind | | event.kind | 
| event.module | | event.module | 
| event.outcome | | event.outcome | 
| http.request.body.bytes | | http.request.body.bytes | 
| http.request.method | | http.request.method | 
| http.response.body.bytes | | http.response.body.bytes | 
| http.response.status_code | | http.response.status_code | 
| http.version | | http.version | 
| service.type | | service.type | 
| tls.cipher | | tls.cipher | 
| tls.version | | tls.version | 
| tls.version_protocol | | tls.version_protocol | 
| trace.id | | trace.id | 
| url | | url |

**Comment by LucioDonda** [comment]
POSTGRESQL fields Mapping:
| ECS field                   | Value                                                          | Wazuh field                 | Reason                                        |
| --------------------------- | -------------------------------------------------------------- | --------------------------- | --------------------------------------------- |
| event.category | | event.category |
| event.dataset | | event.dataset |
| event.kind | | event.kind |
| event.module | | event.module |
| fileset.name | | fileset.name |
| input.type | | input.type |
| log.level | | log.level |
| postgresql.internal_query | | postgresql.internal_query |
| postgresql.log.application_name | | postgresql.log.application_name |
| postgresql.log.backend_type | | postgresql.log.backend_type |
| postgresql.log.command_tag | | postgresql.log.command_tag |
| postgresql.log.context | | postgresql.log.context |
| postgresql.log.database | | postgresql.log.database |
| postgresql.log.detail | | postgresql.log.detail |
| postgresql.log.hint | | postgresql.log.hint |
| postgresql.log.location | | postgresql.log.location |
| postgresql.log.query | | postgresql.log.query |
| postgresql.log.session_id | | postgresql.log.session_id |
| postgresql.log.session_line_num | | postgresql.log.session_line_num |
| postgresql.log.session_start_time | | postgresql.log.session_start_time |
| postgresql.log.sql_state_code | | postgresql.log.sql_state_code |
| postgresql.log.timestamp | | postgresql.log.timestamp |
| postgresql.log.transaction_id | | postgresql.log.transaction_id |
| postgresql.log.virtual_transaction_id | | postgresql.log.virtual_transaction_id |
| process.pid | | process.pid |
| service.type | | service.type |
| timestamp | | timestamp |
| user.name | | user.name |

**Comment by LucioDonda** [comment]
NGINX fields Mapping:
| ECS field                   | Value                                                          | Wazuh field                 | Reason                                        |
| --------------------------- | -------------------------------------------------------------- | --------------------------- | --------------------------------------------- |
| @timestamp | | @timestamp | |
| destination.domain | | destination.domain | |
| destination.ip | | destination.ip | |
| destination.port | | destination.port | |
| event.category | | event.category | |
| event.kind | | event.kind | |
| event.module | | event.module | |
| event.outcome | | event.outcome | |
| event.start | | event.start | |
| event.type | | event.type | |
| http.request.method  | | http.request.method  | |
| http.request.referrer | | http.request.referrer | |
| http.response.body.bytes | | http.response.body.bytes | |
| http.response.status_code | | http.response.status_code | |
| http.version  | | http.version  | |
| log.level | | log.level | |
| nginx.access.remote_ip_list | | nginx.access.remote_ip_list | |
| process.pid | | process.pid | |
| process.thread.id | | process.thread.id | |
| related.ip | | related.ip | |
| related.user | | related.user | |
| service.type | | service.type | |
| source.address | | source.address | |
| url.domain | | url.domain | |
| url.original  | | url.original  | |
| user_agent.original | | user_agent.original | |
