### ISSUE TITLE
Syslog timestamp with milliseconds granularity is not correctly decoded

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#15730]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.3.10 | Analysisd | Manager | N/A | N/A |

## Description

Syslog events are predecoded at [`cleanevent.c`](https://github.com/wazuh/wazuh/blob/70b03fb6c9f4184c14c14be004608842e1efb297/src/analysisd/cleanevent.c#L85). In this predecoding stage, the following syslog formats are contemplated:
- `2007-06-14T15:48:55-04:00`
- `2009-05-22T09:36:46.214994-07:00`

However, regarding the [Syslog-ng reference](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.37/administration-guide/75#TOPIC-1829200), we are missing a format when the fraction of seconds contains 3 digits instead of 6.

> Note that syslog-ng can produce fractions of a second (for example, milliseconds) in the timestamp by using the frac-digits() global or per-destination option.
> NOTE: As syslog-ng OSE is precise up to the microsecond, when the frac-digits() option is set to a value higher than 6, syslog-ng OSE will truncate the fraction seconds in the timestamps after 6 digits.

This issue has been reported by a community user.

## Steps to reproduce

Run Wazuh Logtest and try to decode the following sample log:
```
2022-12-20T15:02:53.288+00:00 INFO program[123]: this is a test
```

This is the output from `wazuh-logtest`:
```
# wazuh-logtest
Starting wazuh-logtest v4.4.0
Type one log per line

2022-12-20T15:02:53.288+00:00 INFO program[123]: this is a test

**Phase 1: Completed pre-decoding.
	full event: '2022-12-20T15:02:53.288+00:00 INFO program[123]: this is a test'
	timestamp: '2022-12-20T15:02:53.288+00:00 I'
	program_name: 'program'

**Phase 2: Completed decoding.
	No decoder matched.
```

As we can see, the timestamp includes two extra characters, which breaks the rest of the decoding phases.

## DoD

- [x] Fix the predecoder to support the missing syslog format
- [x] Add unit tests for the new cases
- [x] Verify nothing else is affected by the changes

**Comment by chemamartinez** [comment]
Branch https://github.com/wazuh/wazuh/tree/15730-fix-syslog-timestamp
