### ISSUE TITLE
VPC integration broke with inexistent region

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh#15763]
| Affected integration |
|---|
| AWS|

## Description

During the development of the integration tests for VPC(wazuh/wazuh-qa#3336), we found that when an inexistent region is provided the module broke with an unexpected error.

<details><summary>Used command</summary>

  ```bash
  /var/ossec/wodles/aws/aws-s3 --bucket wazuh-vpcflow-integration-tests --aws_profile qa --only_logs_after 2022-NOV-20 --regions us-fake-1 --type vpcflow --debug 2
  ```
</details>

<details><summary>Command output</summary>

  ```python
  DEBUG: +++ Debug mode on - Level: 2
  DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
  DEBUG: +++ Table does not exist; create
  DEBUG: +++ Working on XXXXXXXXXX - us-fake-1
  DEBUG: +++ Error: Could not connect to the endpoint URL: "https://ec2.us-fake-1.amazonaws.com/"
  Unknown error: Could not connect to the endpoint URL: "https://ec2.us-fake-1.amazonaws.com/"
  Traceback (most recent call last):
    File "/var/ossec/framework/python/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
      conn = connection.create_connection(
    File "/var/ossec/framework/python/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
      for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
    File "/var/ossec/framework/python/lib/python3.9/socket.py", line 954, in getaddrinfo
      for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
  socket.gaierror: [Errno -2] Name or service not known

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/var/ossec/framework/python/lib/python3.9/site-packages/botocore/httpsession.py", line 323, in send
      urllib_response = conn.urlopen(
    File "/var/ossec/framework/python/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
      retries = retries.increment(
    File "/var/ossec/framework/python/lib/python3.9/site-packages/urllib3/util/retry.py", line 507, in increment
      raise six.reraise(type(error), error, _stacktrace)
    File "/var/ossec/framework/python/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
      raise value
    File "/var/ossec/framework/python/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
      httplib_response = self._make_request(
    File "/var/ossec/framework/python/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
      self._validate_conn(conn)
    File "/var/ossec/framework/python/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
      conn.connect()
    File "/var/ossec/framework/python/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
      conn = self._new_conn()
    File "/var/ossec/framework/python/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
      raise NewConnectionError(
  urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x7f0173176b80>: Failed to establish a new connection: [Errno -2] Name or service not known

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/var/ossec/wodles/aws/aws-s3.py", line 3655, in <module>
      main(sys.argv[1:])
    File "/var/ossec/wodles/aws/aws-s3.py", line 3602, in main
      bucket.iter_bucket(options.aws_account_id, options.regions)
    File "/var/ossec/wodles/aws/aws-s3.py", line 959, in iter_bucket
      self.iter_regions_and_accounts(account_id, regions)
    File "/var/ossec/wodles/aws/aws-s3.py", line 1812, in iter_regions_and_accounts
      flow_logs_ids = self.get_flow_logs_ids(self.access_key,
    File "/var/ossec/wodles/aws/aws-s3.py", line 1751, in get_flow_logs_ids
      flow_logs_ids = list(map(operator.itemgetter('FlowLogId'), ec2_client.describe_flow_logs()['FlowLogs']))
    File "/var/ossec/framework/python/lib/python3.9/site-packages/botocore/client.py", line 386, in _api_call
      return self._make_api_call(operation_name, kwargs)
    File "/var/ossec/framework/python/lib/python3.9/site-packages/botocore/client.py", line 691, in _make_api_call
      http, parsed_response = self._make_request(
    File "/var/ossec/framework/python/lib/python3.9/site-packages/botocore/client.py", line 711, in _make_request
      return self._endpoint.make_request(operation_model, request_dict)
    File "/var/ossec/framework/python/lib/python3.9/site-packages/botocore/endpoint.py", line 102, in make_request
      return self._send_request(request_dict, operation_model)
    File "/var/ossec/framework/python/lib/python3.9/site-packages/botocore/endpoint.py", line 156, in _send_request
      raise exception
    File "/var/ossec/framework/python/lib/python3.9/site-packages/botocore/endpoint.py", line 200, in _do_get_response
      http_response = self._send(request)
    File "/var/ossec/framework/python/lib/python3.9/site-packages/botocore/endpoint.py", line 269, in _send
      return self.http_session.send(request)
    File "/var/ossec/framework/python/lib/python3.9/site-packages/botocore/httpsession.py", line 352, in send
      raise EndpointConnectionError(endpoint_url=request.url, error=e)
  botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://ec2.us-fake-1.amazonaws.com/"
  ```
</details>

Is needed to catch this exception and show a correct message explaining that the region provided is an invalid one.

## Tasks
- [x] Test in a manager.
- [x] Test in an agent.
- [x] Unit tests without failures. Updated if there are any relevant changes.
- [x] Update integration tests.
- [x] Update the documentation if necessary.
- [x] Add entry to the changelog if necessary.
