### ISSUE TITLE
Investigate about a problem with `--remove` for ALB, CLB and NLB integrations

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh#15804]
| Affected integration |
|---|
| AWS|

## Description

During the development of the integration tests for ALB, CLB, and NLB (wazuh/wazuh-qa#3338), we found a possible bug with the parameter `--remove`.  What happens is the module deletes older logs from another region.

The issue occurs when the module is called from modulesd with the parameters:
`wodles/aws/aws-s3 --bucket wazuh-alb-integration-tests --remove --aws_profile qa --type alb --debug 2`

<details><summary>Command output</summary>

```
Launching S3 Command: wodles/aws/aws-s3 --bucket wazuh-alb-integration-tests --remove --aws_profile qa --type alb --debug 2

DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: +++ Table does not exist; create
DEBUG: +++ Working on 819751203818 - us-east-1
DEBUG: +++ Marker: AWSLogs/819751203818/elasticloadbalancing/us-east-1/2022/12/26
DEBUG: ++ Found new log: AWSLogs/819751203818/elasticloadbalancing/us-east-1/2022/12/26/819751203818_elasticloadbalancing_us-east-1__app.ALB-qatests_20221226T1216Z_1394216562005043570_84.228.145.47_pczeay_.log
DEBUG: +++ Remove file from S3 Bucket:AWSLogs/819751203818/elasticloadbalancing/us-east-1/2022/12/26/819751203818_elasticloadbalancing_us-east-1__app.ALB-qatests_20221226T1216Z_1394216562005043570_84.228.145.47_pczeay_.log
DEBUG: +++ DB Maintenance
DEBUG: +++ Working on 819751203818 - us-east-2
DEBUG: +++ Marker: AWSLogs/819751203818/elasticloadbalancing/us-east-1/2022/12/26/819751203818_elasticloadbalancing_us-east-1__app.ALB-qatests_20221226T1216Z_1394216562005043570_84.228.145.47_pczeay_.log
DEBUG: ++ Found new log: AWSLogs/819751203818/elasticloadbalancing/us-east-2/2022/11/21/819751203818_elasticloadbalancing_us-east-2_app.ALB-qatests_20221121T1828Z_527708974255532716_231.4.174.11_pczeay_.log
DEBUG: +++ Remove file from S3 Bucket:AWSLogs/819751203818/elasticloadbalancing/us-east-2/2022/11/21/819751203818_elasticloadbalancing_us-east-2_app.ALB-qatests_20221121T1828Z_527708974255532716_231.4.174.11_pczeay_.log
DEBUG: ++ Found new log: AWSLogs/819751203818/elasticloadbalancing/us-east-2/2022/11/26/819751203818_elasticloadbalancing_us-east-2_app.ALB-qatests_20221126T1828Z_527708974255532716_231.4.174.11_pczeay_.log
DEBUG: +++ Remove file from S3 Bucket:AWSLogs/819751203818/elasticloadbalancing/us-east-2/2022/11/26/819751203818_elasticloadbalancing_us-east-2_app.ALB-qatests_20221126T1828Z_527708974255532716_231.4.174.11_pczeay_.log
DEBUG: +++ DB Maintenance
```

</details>

But, when the command is called directly the module works as expected.

 <details><summary>Command output</summary>

```
DEBUG: +++ Debug mode on - Level: 2
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: +++ Working on 819751203818 - us-east-1
DEBUG: +++ Marker: AWSLogs/819751203818/elasticloadbalancing/us-east-1/2022/12/27
DEBUG: +++ No logs to process in bucket: 819751203818/us-east-1
DEBUG: +++ DB Maintenance
DEBUG: +++ Working on 819751203818 - us-east-2
DEBUG: +++ Marker: AWSLogs/819751203818/elasticloadbalancing/us-east-2/2022/12/27
DEBUG: +++ No logs to process in bucket: 819751203818/us-east-2
DEBUG: +++ DB Maintenance
```

</details>

## Tasks
- [ ] Test in a manager.
- [ ] Test in an agent.
- [ ] Unit tests without failures. Updated if there are any relevant changes.
- [ ] Integration tests without failures. Updated if there are any relevant changes.
- [ ] Update the documentation if necessary.
- [ ] Add entry to the changelog if necessary.

**Comment by nico-stefani** [comment]
# Issue Update

Doing some research I found the possible cause of the problem.

Currently, the [A,C,N]LB integrations inherit from the `AWSLBBucket` class which in turn inherits from `AWSCustomBucket`.
The problem comes when `AWSLBBucket` overrides the ` iter_regions_and_accounts` method:

https://github.com/wazuh/wazuh/blob/78bbd9f8e923c1a588b198ce2d0fe530659973dd/wodles/aws/aws_s3.py#L2411-L2412

Because in the `AWSCustomBucket.iter_regions_and_accounts` the region isn't used to process logs but in `AWSBucket.iter_regions_and_accounts` it's contemplated.

* `AWSCustomBucket.iter_regions_and_accounts`

https://github.com/wazuh/wazuh/blob/78bbd9f8e923c1a588b198ce2d0fe530659973dd/wodles/aws/aws_s3.py#L2174-L2179

* `AWSBucket.iter_regions_and_accounts`

https://github.com/wazuh/wazuh/blob/78bbd9f8e923c1a588b198ce2d0fe530659973dd/wodles/aws/aws_s3.py#L951-L964

And this is reflected in the DB structure and the query to get the last key:

* AWSBucket

https://github.com/wazuh/wazuh/blob/78bbd9f8e923c1a588b198ce2d0fe530659973dd/wodles/aws/aws_s3.py#L464-L472

https://github.com/wazuh/wazuh/blob/78bbd9f8e923c1a588b198ce2d0fe530659973dd/wodles/aws/aws_s3.py#L487-L499

* AWSCustomBucket

https://github.com/wazuh/wazuh/blob/78bbd9f8e923c1a588b198ce2d0fe530659973dd/wodles/aws/aws_s3.py#L2028-L2035

https://github.com/wazuh/wazuh/blob/78bbd9f8e923c1a588b198ce2d0fe530659973dd/wodles/aws/aws_s3.py#L2049-L2060

## Conclusion

The proposed solution is to try using the DB structure defined in AWSBucket, maybe changing the father class.  
But this brings a problem when changing the structure of the DB that should be contemplated.

I will do some tests in order to validate the proposed solution.

**Comment by nico-stefani** [comment]
# Issue Update

After doing some validations in be6ee2dba79cb2e33f82d2f017184df59d63d59d, I conclude that is possible to make the changes and match with the behavior of other integrations like `cloudtrail`.

But, we need to decide how to handle a data migration for ALB, CLB, and NLB integrations,  if we choose to continue with the proposal.

- [ ] Discuss with the team.
