### ISSUE TITLE
Release 4.4.0 - Beta 1 - E2E UX tests - Wazuh Dashboard

### ISSUE THREAD

**Issue by hector222arroyo** [wazuh/wazuh#15942]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.
## Modules test information

|||
|----------------------------------|------ |
| **Main release candidate issue** |   https://github.com/wazuh/wazuh/issues/15893  |
| **Main E2E UX test issue** |   https://github.com/wazuh/wazuh/issues/15519  |
| **Version**                      | 4.4.0 |
| **Release candidate #**          | Beta 1   |
| **Tag**                          | https://github.com/wazuh/wazuh/tree/v4.4.0-beta1 |
| **Previous modules tests issue** | https://github.com/wazuh/wazuh/issues/15551 |

## Installation procedure
- Wazuh Indexer
  - [Step by Step](https://documentation-dev.wazuh.com/v4.4.0-beta1/installation-guide/wazuh-indexer/step-by-step.html)
- Wazuh Server
  - [Step by Step](https://documentation-dev.wazuh.com/v4.4.0-beta1/installation-guide/wazuh-server/step-by-step.html)
- Wazuh Dashboard
  - [Step by Step](https://documentation-dev.wazuh.com/v4.4.0-beta1/installation-guide/wazuh-dashboard/step-by-step.html)
- Wazuh Agent
  - Wazuh WUI one-liner deploy IP GROUP (created beforehand)

## Test description

The best effort is to test Wazuh dashboard package. Think critically and at least review/test:

 - [x] Wazuh dashboard package specs
 - [x] Dashboard package size
 - [x] Dashboard package metadata
 - [x] Dashboard package digital signature
 - [x] Installed files location, size, and permissions
 - [x] Installation footprint (check that no unnecessary files are modified/broken in the file system. For example that operating system files do keep their right owner/permissions and that the installer did not break the system.)
 - [x] Installed service (check that it works correctly)
 - [x] Wazuh Dashboard logs when installed
 - [x] Wazuh Dashboard configuration (Try to find anomalies compared with 4.3.10)
 - [x] Wazuh Dashboard (including the Wazuh WUI) communication with Wazuh manager API and Wazuh indexer
 - [x] Register Wazuh Agents
 - [x] Basic browsing through the WUI
 - [x] Basic experience with WUI performance.
 - [x] Anything else that could have been overlooked when creating the new package

## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| 🟢 | All checks passed. |
| 🔴 | There is at least one failed result. |
| 🟡 | There is at least one expected failure or skipped test and no failures. |

Any failing test must be documented with a new issue, detailing the error and the possible cause. 

An extended test results report can be attached as a ZIP or TXT file. Please attach any documents, screenshots, or tables to the issue update with the results. The auditors can use this report to dig deeper into possible failures and details.

## Conclusions

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| 🟢   | Wazuh dashboard package specs | - | [Comment](https://github.com/wazuh/wazuh/issues/15942#issuecomment-1385605535)  |
| 🟢  | Dashboard package size  | - | [Comment](https://github.com/wazuh/wazuh/issues/15942#issuecomment-1385607328) |
| 🟢  | Dashboard package metadata (description) | - | [Comment](https://github.com/wazuh/wazuh/issues/15942#issuecomment-1385608510) |
| 🟢  | Dashboard package digital signature | - | [Comment](https://github.com/wazuh/wazuh/issues/15942#issuecomment-1385610088) |
| 🟢  | Installed files location, size, and permissions  | - | [Comment](https://github.com/wazuh/wazuh/issues/15942#issuecomment-1385642369) |
| 🟢  | Installation footprint  | - | [Comment](https://github.com/wazuh/wazuh/issues/15942#issuecomment-1384215180) |
| 🟢  | Installed service | - | [Comment](https://github.com/wazuh/wazuh/issues/15942#issuecomment-1384215180) |
| 🟢 | Wazuh Dashboard logs when installed  | - | [Comment](https://github.com/wazuh/wazuh/issues/15942#issuecomment-1384215180) |
| 🟢 | Wazuh Dashboard configuration  | - | [Comment](https://github.com/wazuh/wazuh/issues/15942#issuecomment-1385986105)  |
| 🟢 | Communication between dashboard, indexer & manager | - | [Comment](https://github.com/wazuh/wazuh/issues/15942#issuecomment-1386241336)  |
| 🟢 | Register Wazuh Agents  | - | [Comment](https://github.com/wazuh/wazuh/issues/15942#issuecomment-1387090868) |
| 🟢  | Basic browsing through the WUI | - | [Comment](https://github.com/wazuh/wazuh/issues/15942#issuecomment-1387277793)  |
| 🟢 | Basic experience with WUI performance | - | [Comment](https://github.com/wazuh/wazuh/issues/15942#issuecomment-1387277793)  |
| 🟢 | Wazuh server installation | - | [Comment](https://github.com/wazuh/wazuh/issues/15942#issuecomment-1384215180)  |

## Auditors' validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @davidjiglesias 
- [x] @wazuh/frontend

**Comment by hector222arroyo** [comment]
# Installation logs 🟢 

<details><summary>indexer </summary>

```console
[root@G15-LAPTOP ~]# curl -sO https://packages-dev.wazuh.com/4.4/wazuh-certs-tool.sh
[root@G15-LAPTOP ~]# curl -sO https://packages-dev.wazuh.com/4.4/config.yml
[root@G15-LAPTOP ~]# ls -lac
total 84
dr-xr-x---  3 root root  4096 Jan 16 11:15 .
dr-xr-xr-x 18 root root  4096 Jan 16 08:59 ..
-rw-------  1 root root  6880 Jan 16 08:58 anaconda-ks.cfg
-rw-r--r--  1 root root    18 Jan 16 08:58 .bash_logout
-rw-r--r--  1 root root   176 Jan 16 08:58 .bash_profile
-rw-r--r--  1 root root   176 Jan 16 08:58 .bashrc
-rw-r--r--  1 root root   622 Jan 16 11:15 config.yml
-rw-r--r--  1 root root   100 Jan 16 08:58 .cshrc
-rw-------  1 root root  6587 Jan 16 08:58 original-ks.cfg
drwxr-----  3 root root  4096 Jan 16 11:15 .pki
-rw-r--r--  1 root root   129 Jan 16 08:58 .tcshrc
-rw-r--r--  1 root root 31519 Jan 16 11:15 wazuh-certs-tool.sh
[root@G15-LAPTOP ~]#

[root@G15-LAPTOP ~]# nano config.yml
```

```console
[root@G15-LAPTOP ~]# bash ./wazuh-certs-tool.sh -A
16/01/2023 11:19:13 INFO: Admin certificates created.
16/01/2023 11:19:13 INFO: Wazuh indexer certificates created.
16/01/2023 11:19:13 INFO: Wazuh server certificates created.
16/01/2023 11:19:13 INFO: Wazuh dashboard certificates created.
[root@G15-LAPTOP ~]# tar -cvf ./wazuh-certificates.tar -C ./wazuh-certificates/ .
./
./node-1.pem
./root-ca.key
./dashboard-key.pem
./dashboard.pem
./admin-key.pem
./wazuh-1.pem
./admin.pem
./wazuh-1-key.pem
./node-1-key.pem
./root-ca.pem
[root@G15-LAPTOP ~]# rm -rf ./wazuh-certificates
```

```console
[root@G15-LAPTOP ~]# yum install coreutils
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.unimagdalena.edu.co
 * extras: mirror.genesisadaptive.com
 * updates: mirror.dal.nexril.net
Package coreutils-8.22-24.el7_9.2.x86_64 already installed and latest version
Nothing to do
[root@G15-LAPTOP ~]# rpm --import https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH
[root@G15-LAPTOP ~]#
[root@G15-LAPTOP ~]# echo -e '[wazuh]\ngpgcheck=1\ngpgkey=https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH\nenabled=1\nname=EL-$releasever - Wazuh\nbaseurl=https://packages-dev.wazuh.com/pre-release/yum/\nprotect=1' | tee /etc/yum.repos.d/wazuh.repo
[wazuh]
gpgcheck=1
gpgkey=https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH
enabled=1
name=EL-$releasever - Wazuh
baseurl=https://packages-dev.wazuh.com/pre-release/yum/
protect=1
[root@G15-LAPTOP ~]#

```

```console
[root@G15-LAPTOP ~]# yum -y install wazuh-indexer
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.mirrors.hoobly.com
 * extras: mirrors.advancedhosters.com
 * updates: nyc.mirrors.clouvider.net
base                                                                                                              | 3.6 kB  00:00:00
extras                                                                                                            | 2.9 kB  00:00:00
updates                                                                                                           | 2.9 kB  00:00:00
wazuh                                                                                                             | 3.4 kB  00:00:00
wazuh/primary_db                                                                                                  | 278 kB  00:00:00
Resolving Dependencies
--> Running transaction check
---> Package wazuh-indexer.x86_64 0:4.4.0-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=========================================================================================================================================
 Package                              Arch                          Version                           Repository                    Size
=========================================================================================================================================
Installing:
 wazuh-indexer                        x86_64                        4.4.0-1                           wazuh                        497 M

Transaction Summary
=========================================================================================================================================
Install  1 Package

Total download size: 497 M
Installed size: 747 M
Downloading packages:
wazuh-indexer-4.4.0-1.x86_64.rpm                                                                                  | 497 MB  00:03:10
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : wazuh-indexer-4.4.0-1.x86_64                                                                                          1/1
Created opensearch keystore in /etc/wazuh-indexer/opensearch.keystore
  Verifying  : wazuh-indexer-4.4.0-1.x86_64                                                                                          1/1

Installed:
  wazuh-indexer.x86_64 0:4.4.0-1

Complete!
[root@G15-LAPTOP ~]#
```

</details>

**Comment by hector222arroyo** [comment]
# Wazuh Dashboard Package specs 🟢
```yaml
[root@ip-172-31-82-186 centos]# yum info wazuh-dashboard
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: download.cf.centos.org
 * extras: download.cf.centos.org
 * updates: download.cf.centos.org
Installed Packages
Name        : wazuh-dashboard
Arch        : x86_64
Version     : 4.4.0
Release     : 1
Size        : 1.1 G
Repo        : installed
From repo   : wazuh
Summary     : Wazuh dashboard is a user interface and visualization tool for security-related data. Documentation can be found at
            : https://documentation.wazuh.com/current/getting-started/components/wazuh-dashboard.html
URL         : https://www.wazuh.com/
License     : GPL
Description : Wazuh dashboard is a user interface and visualization tool for security-related data. This Wazuh central component enables exploring,
            : visualizing, and analyzing the stored security alerts generated by the Wazuh server. Wazuh dashboard enables inspecting the status
            : and managing the configurations of the Wazuh cluster and agents as well as creating and managing users and roles. In addition, it
            : allows testing the ruleset and making calls to the Wazuh API. Documentation can be found at
            : https://documentation.wazuh.com/current/getting-started/components/wazuh-dashboard.html

```

```yaml
[root@ip-172-31-82-186 centos]# rpm -qi $(rpm -qa | awk '/dashboard/ {print $0}')
Name        : wazuh-dashboard
Version     : 4.4.0
Release     : 1
Architecture: x86_64
Install Date: Mon 16 Jan 2023 10:08:03 PM UTC
Group       : System Environment/Daemons
Size        : 1200966876
License     : GPL
Signature   : RSA/SHA256, Fri 13 Jan 2023 06:50:32 PM UTC, Key ID 96b3ee5f29111145
Source RPM  : wazuh-dashboard-4.4.0-1.src.rpm
Build Date  : Fri 13 Jan 2023 05:28:05 PM UTC
Build Host  : ip-172-31-63-239.ec2.internal
Relocations : (not relocatable)
Packager    : Wazuh, Inc <info@wazuh.com>
Vendor      : Wazuh, Inc <info@wazuh.com>
URL         : https://www.wazuh.com/
Summary     : Wazuh dashboard is a user interface and visualization tool for security-related data. Documentation can be found at https://documentation.wazuh.com/current/getting-started/components/wazuh-dashboard.html
Description :
Wazuh dashboard is a user interface and visualization tool for security-related data. This Wazuh central component enables exploring, visualizing, and analyzing the stored security alerts generated by the Wazuh server. Wazuh dashboard enables inspecting the status and managing the configurations of the Wazuh cluster and agents as well as creating and managing users and roles. In addition, it allows testing the ruleset and making calls to the Wazuh API. Documentation can be found at https://documentation.wazuh.com/current/getting-started/components/wazuh-dashboard.html

```

**Comment by hector222arroyo** [comment]
# Dashboard Package Size 🟢
```yaml
[root@ip-172-31-82-186 centos]# rpm --qf '%{SIZE}\n' -q wazuh-dashboard | awk '{print $1/(1024*1024)"MiB"}'
1145.33MiB

```

**Comment by hector222arroyo** [comment]
# Dashboard package metadata (description) 🟢
```yaml
[root@ip-172-31-82-186 centos]# yum -C search wazuh-dashboard
Loaded plugins: fastestmirror
========================================================== N/S matched: wazuh-dashboard ===========================================================
wazuh-dashboard.x86_64 : Wazuh dashboard is a user interface and visualization tool for security-related data. Documentation can be found at
                       : https://documentation.wazuh.com/current/getting-started/components/wazuh-dashboard.html

  Name and summary matches only, use "search all" for everything.

```

**Comment by hector222arroyo** [comment]
# Dashboard package digital signature 🟢
```yaml
[root@ip-172-31-82-186 centos]# rpm -qi $(rpm -qa  | awk '/dashboard/ {print $0}') | awk '/Name|Install|Signature/ {print $0}'
Name        : wazuh-dashboard
Install Date: Mon 16 Jan 2023 10:08:03 PM UTC
Signature   : RSA/SHA256, Fri 13 Jan 2023 06:50:32 PM UTC, Key ID 96b3ee5f29111145
[root@ip-172-31-82-186 centos]#
[root@ip-172-31-82-186 centos]# rpm -q gpg-pubkey --qf '%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n'
gpg-pubkey-f4a80eb5-53a7ff4b    gpg(CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>)
gpg-pubkey-29111145-591cd381    gpg(Wazuh.com (Wazuh Signing Key) <support@wazuh.com>)
[root@ip-172-31-82-186 centos]#

```

**Comment by hector222arroyo** [comment]
# Installed files location, size and permissions 🟢
``` /usr/share/wazuh-dashboard ```
```yaml
[root@ip-172-31-82-186 centos]# ls -lac /usr/share/wazuh-dashboard
total 1468
drwxr-x---.   9 wazuh-dashboard wazuh-dashboard     211 Jan 16 22:07 .
drwxr-xr-x.  71 root            root               4096 Jan 16 22:06 ..
drwxr-x---.   2 wazuh-dashboard wazuh-dashboard     109 Jan 16 22:06 bin
drwxr-x---.   2 wazuh-dashboard wazuh-dashboard      44 Jan 16 22:08 config
drwxr-x---.   3 wazuh-dashboard wazuh-dashboard      31 Jan 16 22:30 data
-rw-r-----.   1 wazuh-dashboard wazuh-dashboard   11358 Jan 16 22:06 LICENSE.txt
-rw-r-----.   1 wazuh-dashboard wazuh-dashboard    5369 Jan 16 22:06 manifest.yml
drwxr-x---.   6 wazuh-dashboard wazuh-dashboard     108 Jan 16 22:06 node
drwxr-x---. 708 wazuh-dashboard wazuh-dashboard   20480 Jan 16 22:06 node_modules
-rw-r-----.   1 wazuh-dashboard wazuh-dashboard 1426715 Jan 16 22:06 NOTICE.txt
-rw-r-----.   1 wazuh-dashboard wazuh-dashboard     829 Jan 16 22:06 package.json
drwxr-x---.  10 wazuh-dashboard wazuh-dashboard     221 Jan 16 22:07 plugins
-rw-r-----.   1 wazuh-dashboard wazuh-dashboard    1933 Jan 16 22:06 README.txt
drwxr-x---.  11 wazuh-dashboard wazuh-dashboard     160 Jan 16 22:08 src
-r--r-----.   1 wazuh-dashboard wazuh-dashboard       6 Jan 16 22:06 VERSION

```

**Comment by hector222arroyo** [comment]
# Wazuh dashboard configuration 🟢

<details><summary>Config 4.4.0</summary>

```yaml
[root@ip-172-31-82-186 centos]# cat /usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml
---
```
</details>

**Comment by hector222arroyo** [comment]
# Wazuh Dashboard (included the Wazuh WUI) communication with Wazuh manager API and Wazuh indexer 🟢

**Comment by hector222arroyo** [comment]
# Register Wazuh Agent 🟢 

![image](https://user-images.githubusercontent.com/68483100/213185438-f37c1bbd-e519-40df-bbad-0cb1bbeff073.png)


```yaml
root@ip-172-31-92-151:/home/ubuntu# curl -so wazuh-agent.deb https://packages-dev.wazuh.com/pre-release/apt/pool/main/w/wazuh-agent/wazuh-agent_4.4.0-1_amd64.deb && sudo WAZUH_MANAGER='54.174.92.217' WAZUH_AGENT_GROUP='default' WAZUH_AGENT_NAME='my-server-test01' dpkg -i ./wazuh-agent.deb
Selecting previously unselected package wazuh-agent.
(Reading database ... 112520 files and directories currently installed.)
Preparing to unpack ./wazuh-agent.deb ...
Unpacking wazuh-agent (4.4.0-1) ...
Setting up wazuh-agent (4.4.0-1) ...
root@ip-172-31-92-151:/home/ubuntu#
root@ip-172-31-92-151:/home/ubuntu# sudo systemctl daemon-reload
root@ip-172-31-92-151:/home/ubuntu#
root@ip-172-31-92-151:/home/ubuntu# sudo systemctl enable wazuh-agent
Synchronizing state of wazuh-agent.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable wazuh-agent
Created symlink /etc/systemd/system/multi-user.target.wants/wazuh-agent.service → /lib/systemd/system/wazuh-agent.service.
root@ip-172-31-92-151:/home/ubuntu#
root@ip-172-31-92-151:/home/ubuntu# sudo systemctl start wazuh-agent
root@ip-172-31-92-151:/home/ubuntu#

```


![image](https://user-images.githubusercontent.com/68483100/213186199-4b698956-d0e1-40e8-9d57-05d13e6eabd1.png)

**Comment by hector222arroyo** [comment]
# Basic experience with WUI performance and Basic experience with WUI performance 🟢

![image](https://user-images.githubusercontent.com/68483100/213191539-1deacacd-c7f1-447e-bbfb-ea68f4d7879b.png)

![image](https://user-images.githubusercontent.com/68483100/213191660-1b05bb15-0534-4cfa-8048-ed01541a7f7b.png)


![image](https://user-images.githubusercontent.com/68483100/213191770-99d5f45b-69e2-4d92-b6bf-6ff5b061b085.png)

![image](https://user-images.githubusercontent.com/68483100/213197533-5f154529-ff22-4e22-ab3e-1d6ea17b00ae.png)

![image](https://user-images.githubusercontent.com/68483100/213197680-21d95248-5cbc-40b5-b0b1-122da06d89a1.png)


![image](https://user-images.githubusercontent.com/68483100/213197789-495b3814-2bb2-41f2-a743-61e5021bd6af.png)
