### ISSUE TITLE
Build a manager for AIX with restricted capabilities

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#15971]
|Base version|Target platform|Architecture|
|---|---|---|
|3.1.0|AIX 7.1 - 7.3|POWER7 - Power10|

This task aims to provide a manager running on AIX 7.1+ to monitor itself locally and send alerts via Syslog.

### Description

- Build a manager on AIX, optimized for the different PowerPC architectures.
- Be able to disable the compilation of:
    - wazuh-remoted
    - wazuh-apid
    - wazuh-clusterd
- Provide a manager package that has these components disabled by default:
    - Remote incoming connections.
    - RESTful API.
    - Cluster.
    - Vulnerability Detector.

### Deliverable

1. Development branch with the following changes:
    - Makefile: remove `TARGET=local` and add `BUILD_REMOTED=y|n`
    - Select which components to include in the sources installer.

### Development

|Development branch|
|---|
|[15502-build-restricted-AIX-manager](https://github.com/wazuh/wazuh/tree/15502-build-restricted-AIX-manager)|

In this development phase, we have started working from the _`v3.1.0`_ branch, where we have modified the code to include the option to disable compilation for some modules in their respective Makefile:
- Remote incoming connections. This module would prevent the compilation of `ossec-remoted` and `ossec-authd`.
- Cluster. This would prevent the compilation of `wazuh-clusterd` and `wazuh-internal-clusterd`.
- RESTful API. For _v3.1.0_ no changes have been made, as it is an additional installation of the [wazuh-api](https://github.com/wazuh/wazuh-api) repository, which has to be done manually.
- Vulnerability detector. In _v3.1.0_ it is not yet included as a module, so it does not have any compilation.

In addition, the following changes requested in the deliverable section have been included:
- Remove `TARGET=local` and add new `BUILD_REMOTED` parameter, which has largely replaced the conditions for local installation.
- Changes to the installation script (`install.sh`) so that the user can enable or disable the installation (including compilation) of these modules.

### Tasks
- [x] Analysis of deliverable for `v3.1.0`
- [x] Remove `TARGET=local`
- Disable component compilation:
  - [x] Add `BUILD_REMOTED`
  - [x] Add `BUILD_CLUSTERD`
- [x] Testing in an _AIX_ environment

**Comment by MarcelKemp** [comment]
Although development is complete, due to issues that appeared in testing, it was decided to move to the next phase, supporting version 4.3.
