### ISSUE TITLE
Develop API webhook for security events

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#16067]
| Branch |
|--------|
| [feature/16067-security-events-webhook](https://github.com/wazuh/wazuh/tree/feature/16067-security-events-webhook) | 

## Description

A new API endpoint has been requested to ingest security events to `analysisd`.

The suggested endpoint is `POST /events` and will have its own customizable limits.

## Tasks

- [x] #15325
- [x] #16068
- [x] #16077
- [ ] wazuh/wazuh-documentation#5903
- [x] wazuh/wazuh-qa#3886
- [x] #17709

## Checks

- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by nico-stefani** [comment]
# Update

Blocked because of a re-opened issue #11957, related to framework UT fails.

**Comment by Selutario** [comment]
**ETA postponed. Reason:**
- [Fix to AITs in 4.5.0](https://github.com/wazuh/wazuh/issues/17690) has not been ported to other branches yet.
