### ISSUE TITLE
Config aws log collector meeting a error

### ISSUE THREAD

**Issue by godt21** [wazuh/wazuh#16093]
| Affected integration |
|---|
| AWS, GCloud, Azure...|
AWS

## Tasks
- [ ] Test in a manager.
- [x] Test in an agent.
- [ ] Unit tests without failures. Updated if there are any relevant changes.
- [ ] Integration tests without failures. Updated if there are any relevant changes.
- [ ] Update the documentation if necessary.
- [ ] Add entry to the changelog if necessary.

**Comment by godt21** [comment]
all right. I comment it but not show. I am using the wodle for fetch aws log. but I only can see the error log as the below.
2023/02/06 16:46:54 wazuh-modulesd:aws-s3: INFO: Fetching logs finished.
2023/02/06 16:47:54 wazuh-modulesd:aws-s3: INFO: Starting fetching of logs.
2023/02/06 16:47:54 wazuh-modulesd:aws-s3: INFO: Executing Bucket Analysis: (Bucket: log-xxxx-xxxx Path: cloudTrail, Type: cloudtrail, Profile: cloudtrail-dev)
2023/02/06 16:47:54 wazuh-modulesd:aws-s3: WARNING: Bucket:  -  Returned exit code 1
2023/02/06 16:47:54 wazuh-modulesd:aws-s3: WARNING: Bucket:  -  Unknown error.
2023/02/06 16:47:54 wazuh-modulesd:aws-s3: INFO: Fetching logs finished.

**Comment by godt21** [comment]
hi @davidjiglesias 
      If I can test wodle aws script manul? and if there is any log for wodle?
regards,

**Comment by davidjiglesias** [comment]
Hello @godt21,

Please enable wazuh-modulesd in debug 2, and then restart the service, let's see if we can extract some more information about the error.

To activate this debug mode, open the file `/var/ossec/etc/local_internal_options.conf` and add the line `wazuh_modules.debug = 2` (or use the next command: `echo "wazuh_modules.debug=2" >> /var/ossec/etc/local_internal_options.conf`

Paste the log after the changes.

**Comment by davidjiglesias** [comment]
The issue does not meet Quality standards
