### ISSUE TITLE
Engine - Review CSV and KVmap

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#16155]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|5.0.0 | Engine | Manager | Packages/Sources | OS version |

## Description
It is necessary to check the kvmap and csv in the engine, as there are cases where it does not work correctly.

Once the functionality is checked, we need to make new test cases for these and correct the not expected behaviors. To do this, we will review feedback from other users who have been using the engine in recent months.

## Tasks
- [x] Check kvmap performance
- [x] Create new test corner cases for kvmap
- [x] Fix issues in kvmap
- [x] Check csv performance
- [x] Create new test corner cases for csv
- [x] Fix issues in csv
- [x] Update Documentation
- [ ] QA validate
