### ISSUE TITLE
Show an explicit message when there aren't logs to process

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh#16290]
| Affected integration |
|---|
| AWS |

## Description

Currently, some AWS integrations aren't showing an explicit message when aren't logs to process. 
This behavior must be fixed in order to make it homogeneous with the rest of the integrations.

Affected integrations

* [x] WAF
* [x] Server Access

The message to display when the available logs for process should be for :

https://github.com/wazuh/wazuh/blob/49bfe3385dd2d559f0587b6e8a4c6d6aa478d3d1/wodles/aws/aws_s3.py#L1016

And when a bucket is empty:

https://github.com/wazuh/wazuh/blob/251e799b17a8f8d1b81786f627392ba28bdf35fb/wodles/aws/aws_s3.py#L1085

## Tasks
- [x] Test in a manager.
- [x] Test in an agent.
- [x] Unit tests without failures. Updated if there are any relevant changes.
- [x] Integration tests without failures. Updated if there are any relevant changes.
- [x] Update the documentation if necessary.
- [x] Add entry to the changelog if necessary.

**Comment by nico-stefani** [comment]
# Issue update

After the changes, I got the next test results.

## Tier 0

```python
root@ubuntu-jammy:/home/vagrant/qa/tests/integration/test_aws# pytest -k 'waf or server_access' --disable-warnings --tier 0
================================================================================================ test session starts ================================================================================================
platform linux -- Python 3.10.6, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/vagrant/qa/tests/integration, configfile: pytest.ini
plugins: metadata-2.0.2, html-3.1.1, testinfra-5.0.0
collected 195 items / 179 deselected / 16 selected

test_basic.py ..                                                                                                                                                                                              [ 12%]
test_discard_regex.py ..                                                                                                                                                                                      [ 25%]
test_only_logs_after.py ....                                                                                                                                                                                  [ 50%]
test_path.py ......                                                                                                                                                                                           [ 87%]
test_remove_from_bucket.py ..                                                                                                                                                                                 [100%]

============================================================================ 16 passed, 179 deselected, 2 warnings in 331.63s (0:05:31) =============================================================================
```

## Tier 1

```python
root@ubuntu-jammy:/home/vagrant/qa/tests/integration/test_aws# pytest -k 'waf or server_access' --disable-warnings --tier 1 --tb=no
================================================================================================ test session starts ================================================================================================
platform linux -- Python 3.10.6, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/vagrant/qa/tests/integration, configfile: pytest.ini
plugins: metadata-2.0.2, html-3.1.1, testinfra-5.0.0
collected 195 items / 193 deselected / 2 selected

test_only_logs_after.py FF                                                                                                                                                                                    [100%]

============================================================================================== short test summary info ==============================================================================================
FAILED test_only_logs_after.py::test_bucket_multiple_calls[waf_only_logs_after_multiple_calls] - wazuh_testing.modules.aws.cli_utils.OutputAnalysisError: The AWS module did not use the correct marker
FAILED test_only_logs_after.py::test_bucket_multiple_calls[server_access_only_logs_after_multiple_calls] - wazuh_testing.modules.aws.cli_utils.OutputAnalysisError: The AWS module did not use the correct marker
============================================================================= 2 failed, 193 deselected, 3 warnings in 67.56s (0:01:07) ==============================================================================
```

Because the tier 1 tests continued with their execution, I found new fails in the next steps of the test. This should be handled in a specific issue (TBC)
