### ISSUE TITLE
Show an explicit message when an invalid region is passed

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh#16301]
| Affected integration |
|---|
| AWS |

## Description

Currently, the AWS service integrations (cloudwatch, inspector) aren't showing an explicit message when an invalid region name is passed.

The message to display should be:

`DEBUG: +++ The region <region_name> is not a valid one.`

## Affected Integrations

- [x] Inspector
- [x] CloudWatch

## Tasks
- [x] Test in a manager.
- [x] Test in an agent.
- [x] Unit tests without failures. Updated if there are any relevant changes.
- [x] Integration tests without failures. Updated if there are any relevant changes.
- [x] Update the documentation if necessary.
- [x] Add entry to the changelog if necessary.

**Comment by nico-stefani** [comment]
# Issue Update

Reading the code I found the cause of the problems.

* Inspector:

https://github.com/wazuh/wazuh/blob/745cb8657a2df0ec4e8d539b87b069f3fe58e3d8/wodles/aws/aws_s3.py#L2900

* CloudWatch

https://github.com/wazuh/wazuh/blob/745cb8657a2df0ec4e8d539b87b069f3fe58e3d8/wodles/aws/aws_s3.py#L3358

There isn't any validation of the regions before calling these methods. Which generate requests to inexistent endpoints, like `https://inspector.us-fake-1.amazonaws.com/`.

I will add some validation in order to prevent this behavior.
