### ISSUE TITLE
Investigate and enhance external modules logging messages

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#16314]
| Affected integration |
|---|
| AWS, GCloud, Azure |

## Description
As mentioned in #14535, the debug mode (`wazuh_modules.debug=2`) is disabled by default, therefore when not enabled, the logging of the different modules does not give enough information if there are warning or error messages, making harder the troubleshooting.

For example, in case of a `Throttling Exception` in the AWS module, the user would only see the debug message if the debug level is 2 due to the following section of code:
https://github.com/wazuh/wazuh/blob/78bbd9f8e923c1a588b198ce2d0fe530659973dd/wodles/aws/aws_s3.py#L1059-L1064

Those types of errors are difficult to reproduce because they depend on several variables such as environment congestion, number of requests to the service, etc.

Another example is regarding the different allowed regions for the AWS module. In some AWS services, in case a non-existent region is used in the module's execution, there is no warning message:
<details><summary>Fake region defined in Config bucket</summary>

    /var/ossec/wodles/aws/aws-s3 --bucket wazuh-aws-wodle-config --aws_profile dev --only_logs_after 2022-NOV-20 --type config --debug 2 --region us-fake
    DEBUG: +++ Debug mode on - Level: 2
    DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
    DEBUG: +++ Table does not exist; create
    DEBUG: +++ Working on 123456789123 - us-fake
    DEBUG: +++ Marker: AWSLogs/123456789123/Config/us-fake/2022/11/20
    DEBUG: +++ No logs to process in bucket: 123456789123/us-fake
    DEBUG: +++ DB Maintenance

</details>

We should review the different messages and debug levels used in order to make error troubleshooting simpler so that the solution can be carried out quickly. As well, if it is a module error itself, its reproduction should be easier to carry out.

## Tasks
- [ ] Investigate and determine the minimum necessary logging for the modules' troubleshooting.
- [ ] Test in a manager.
- [ ] Test in an agent.
- [ ] Unit tests without failures. Updated if there are any relevant changes.
- [ ] Integration tests without failures. Updated if there are any relevant changes.
- [ ] Update the documentation if necessary.
- [ ] Add entry to the changelog if necessary.

**Comment by RamosFe** [comment]
## Update

Started to read Azure `wodle` and [Azure SDK](https://learn.microsoft.com/en-us/python/api/overview/azure/?view=azure-python) for checking which errors are not warned by the logging.

**Comment by RamosFe** [comment]
# Update - Azure Wodle

## Azure Log Analytics

### Error handling

- Errors related to configuration credentials are already handled:
  https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/azure/azure-logs.py#L294-L302

- Errors related to tokens are already handled:
  https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/azure/azure-logs.py#L799-L814

- There should be logged the contents of the error response before the `raise_for_status`:
  https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/azure/azure-logs.py#L413

  Minimum fields to be logged: 
    - Status Code (code field) 
    - Error msg (message field) 
    - Details (details field)
  Documentation: https://learn.microsoft.com/en-us/rest/api/loganalytics/dataaccess/query/get?source=recommendations&tabs=HTTP#errorinfo

### Debug

- The information of the query should only be logged if the debug flag is activated:
  https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/azure/azure-logs.py#L370
- The URL, header and body content should be logged if the debug flag is activated:
  https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/azure/azure-logs.py#L393-L394
- The information send to the socket should be logged if the debug flag is activated:
  https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/azure/azure-logs.py#L456-L459

## Azure Graph

### Error handling

- Errors related to configuration credentials are already handled:
  https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/azure/azure-logs.py#L470-L479

- Errors related to tokens are already handled:
  https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/azure/azure-logs.py#L799-L814

- There should be logged the contents of the error response before the `raise_for_status`:
    https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/azure/azure-logs.py#L590-L594

    Minimum fields to be logged: 
     - Status Code (code field) 
     - Error msg (message field) 
     - Details (details field)
    Documentation: https://learn.microsoft.com/en-us/rest/api/loganalytics/dataaccess/query/get?source=recommendations&tabs=HTTP#errorinfo

### Debug
- The URL and headers should be logged if the debug flag is activated:
https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/azure/azure-logs.py#L566

- The response of the request should be logged if the debug flag is activated:
https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/azure/azure-logs.py#L566

- There should be logged when it iterates to the next resource using the field `next_url`:
https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/azure/azure-logs.py#L588

## Azure Storage

### Error handling

- Errors related to configuration credentials are already handled:
https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/azure/azure-logs.py#L603-L613

- Errors related to tokens are already handled:
  https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/azure/azure-logs.py#L799-L814
  
- Errors related to container existence/permission handled but it should be logged the `msg` property from `AzureException`:
https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/azure/azure-logs.py#L622-L640

- Errors related to reading from a blob handled:
https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/azure/azure-logs.py#L724-L725

### Debug
- It should log the containers if the debug flag is activated:
https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/azure/azure-logs.py#L634

- It should log the data send to the socket if the debug flag is activated:
https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/azure/azure-logs.py#L745-L746

- There should be logged when it iterates to the next resource using the field `next_marker`:
https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/azure/azure-logs.py#L767

**Comment by RamosFe** [comment]
# Update

## AWS Wodle

### Info

- Should be `info`:
  https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/aws/aws_s3.py#L3659
  https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/aws/aws_s3.py#L3665
  https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/aws/aws_s3.py#L2912-L2915

### Debug

- Should log the initialized class if the debug option is set:
  https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/aws/aws_s3.py#L3595-L3618
- Should log the initialized class if the debug option is set:
  https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/aws/aws_s3.py#L3643-L3647

### Error Handling

- Should log the passed `LogBucket` option:
  https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/aws/aws_s3.py#L3619-L3620
- Should log the `error code` of the request:
  https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/aws/aws_s3.py#L1088-L1107
- Should log and raise an error if an invalid region is passed:
  https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/aws/aws_s3.py#L950-L963
- There should not be `debug` and should be `error` (It should be logged even if the debug flag is not activated):
  https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/aws/aws_s3.py#L1058-L1074
- Should log the passed `service` option:
  https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/aws/aws_s3.py#L3643-L3649

### Logging Format:

- Debug:
  Is printed with `print` and uses the function `debug`:
  https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/aws/aws_s3.py#L3427-L3429

  The format of a debug msg is `DEBUG: +++ Debug mode on - Level: 1` (example of use).

- Error:
  Sometimes it uses the function `debug` and other times it uses `print`.
  The format of an error msg is:
  - `DEBUG: ERROR: The "get_log_streams" request failed: Code 404'` (example of msg with debug).
  - `ERROR: Access error: 404` (Example of msg with print).
- Info:
  There is no `info` level, which is replaced by debug.

**Comment by RamosFe** [comment]
## Update

Started developing the changes mentioned above, starting with the AWS Wodle.

**Comment by RamosFe** [comment]
# Update
## Google Cloud
### Error Handling
For handling errors the wodle uses a`Base Exception class` that defines the format of the logs
https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/gcloud/exceptions.py#L16-L44

All the subclasses handle the multiple error cases the API could give, so there is no improvement to make in the structure of how the errors are handled.

### Log Format
The format of the logs is the same for all the errors, as shown below:
https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/wodles/gcloud/gcloud.py#L92-L107

**Comment by RamosFe** [comment]
# Update

Added more logs for the logging level `info`. The list of events that are now logged is shown below:
## Azure
### Azure Analytics
- When it uses the auth file for authentication.
- When it uses the key and domain for authentication.
- Time intervals of the Analytics request query.
- When it requests the API.

### Azure Graph
- When it uses the auth file for authentication.
- When it uses the key and domain for authentication.
- Time intervals of the Graph request filter.
- When it requests the API.
- When it iterates to the next page.

### Azure Storage
- When it uses the auth file for authentication.
- When it uses the key and account name for authentication.
- When it gets all the containers of the account.
- When it gets the specified containers of the account.
- When it requests data for a container.
- When it requests data for a blob.
- When it skips a blob due to a specific
condition (Prefix not set, not expected format, empty blob).

**Comment by RamosFe** [comment]
# Update

## AWS
- What type of service is working with.
- What type of bucket is working with.
- When the account id is not specified and the id is searched in the bucket.
- When the region is not specified and the regions of the account are searched in the account data.
- Region in which the bucket is being processed.
- File from which information is being obtained.

## Google Cloud
- When it checks the credentials before starting.
- When it works with Pub/Sub or Access Logs.

**Comment by RamosFe** [comment]
# Update

The Issue is blocked until the 3 Issues mentioned [here](https://github.com/wazuh/wazuh/issues/16717) related to the design of the log are completed. After these issues are completed, we need to adapt the logs created in this Issue to the new format.

**Comment by RamosFe** [comment]
## Update

After multiple changes in the external modules, especially `azure` and `aws`, it was decided that it was best to create a new branch and add the changes to this new branch than rebasing the existing one with `4.9.0`. The PR https://github.com/wazuh/wazuh/pull/16748 was replaced with PR https://github.com/wazuh/wazuh/pull/23790.
