### ISSUE TITLE
Add support for Microsoft Graph security API

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#16312]
## Description
The [Microsoft Graph security API](https://learn.microsoft.com/en-us/graph/api/resources/security-api-overview) provides a unified interface and schema to integrate with security solutions from Microsoft and ecosystem partners. This empowers customers to streamline security operations and better defend against increasing cyber threats. As part of Wazuh's continuous effort to integrate with principal security solutions, we propose designing and developing a new module to integrate logs from the Microsoft Graph Security API.

## Design requirements
To meet the necessary requirements of this module, we propose the following design:

- The solution will be written in C, similar to the current Office 365 module.
- The solution will provide the necessary code structure and layout to develop future integrations and logs with any other Microsoft Graph API endpoints, beyond security.
 ![image](https://user-images.githubusercontent.com/48716145/222389088-634a94c2-c44e-49f5-87f8-a0cb11fdead3.png)
- The solution will incorporate the same standard options and settings as the other [Wazuh Cloud security modules](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-s3.html#options), including [AWS](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-s3.html#options), [Azure](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-azure-logs.html), or [GCP](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/gcp-pubsub.html#options).
- The solution will incorporate full coverage and support to ingest logs from current security endpoints, as illustrated in the diagram below: 
![image](https://user-images.githubusercontent.com/48716145/222391191-09702b8d-ff64-439f-a333-eec228a14f88.png)
- The solution will provide a full set of decoders and rules for Microsoft Graph security API logs.
- The solution will have unit tests with full coverage.
- The solution will incorporate a suite of integration tests, similar to [AWS](https://github.com/wazuh/wazuh-qa/issues/3333).
- The solution will include appropriate [documentation](https://documentation.wazuh.com/current/index.html) to help users understand how to configure and use the module.

## Impact
By adding support for Microsoft Graph Security API logs to the Wazuh platform, users will be able to easily monitor and analyze their security data in a more centralized and streamlined manner. This will help organizations detect and respond to threats faster, leading to a more secure environment for everyone involved.

## Additional Context
We believe that adding support for Microsoft Graph Security API logs to the Wazuh platform is a crucial step in improving the security posture of our users. With this module, Wazuh will be able to provide even more comprehensive coverage of security data across multiple endpoints, helping users better understand their security risks and take appropriate action.

## EPIC details
Epic branch: [feature/16312-microsoft-graph-security-API](https://github.com/wazuh/wazuh/tree/feature/16312-microsoft-graph-security-API)
Last rebase with master: March 2nd 2023 10:03 UTC

**Comment by Dwordcito** [comment]
Based on the contribution of a community member, we are going to define certain tasks to make the merge commit possible, to meet the definition of done of an issue to be incorporated into a wazuh branch.

### DoD / Subtasks
- [ ] Scan build report possible memory leak in MS Graph contribution
- [ ] Unit tests compilation error in MS Graph contribution
- [ ] Add integration test for Microsoft graph integration
- [ ] Coverity execution in Microsoft graph contribution
