### ISSUE TITLE
Incorporate delay load mechanism and explicit preload verification for libraries in the Windows Agent

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#16319]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.x rev | Wazuh component | Manager/Agent | Packages | Windows |

## Description

This issue aims to incorporate a "delay load" mechanism for libraries to avoid the implicit loading of libraries that Wazuh distributes. In addition, signature verification before explicit library load.

Implicitly loading a library can be problematic because it can result in unintended behavior and potential security risks, especially if the library being loaded is a third-party library.

To avoid these risks, a "delay load" mechanism will be incorporated to ensure that libraries are only loaded explicitly when needed. Additionally, signature verification will be added to ensure that the libraries being loaded are trusted and have not been tampered with.

The main goal of this issue is to prevent third-party libraries from being loaded when signed binaries are copied to another directory to use custom libraries with potentially malicious uses. By using a custom implementation of `LoadLibrary` in the Windows agent's main, we can ensure that libraries are only loaded explicitly when needed and that signature verification is performed to ensure that they are trusted.

## Expected

After this issue is completed, we should expect the following:
- A "delay load" mechanism should be implemented to avoid the implicit loading of libraries that Wazuh distributes.
- Signature verification should be added to ensure that the libraries are explicitly loaded.
- In the Windows agent's main, custom implementation of `LoadLibrary` should be used to delay the loading of libraries.

## DoD

- [x] Incorporate a "delay load" mechanism to avoid the implicit loading of libraries that Wazuh distributes.
- [x] Add signature verification to ensure that the libraries are explicitly loaded.
- [x] Use a custom implementation of `LoadLibrary` in the Windows agent's main to delay the loading of libraries.
- [x] Test thoroughly to ensure that the changes do not affect the behavior of the code.
- [ ] Update any relevant documentation to reflect the changes made.

**Comment by pereyra-m** [comment]
## Update

Working branch: https://github.com/wazuh/wazuh/tree/dev-16319-delay-load .

The first step of the issue is in progress. 
It consists in adding a 'delay load' to `libwinpthread-1.dll` and `libwazuhext.dll` so the `.exe` files stop looking for these libraries in the current folder before the main method begins.

**Tasks completed**:

- After trying different approaches, the small library `libwinpthread-1.dll` was compiled statically. This avoids depending on the library.
- The delay load for MinGW isn't supported with a simple flag. This repository was taken as an example of a workaround https://github.com/AustinWise/delay-load-mingw/ . The `dlltool` is used to generate an intermediate `.lib` import library to link against. The `libwazuhext.lib` was successfully created and almost all the executable of the Wazuh windows agent compile successfully.

**Current state**:

- Just three active response `.exe` files have trouble finding the symbols of an external dependency through the intermediate `libwazuhext.lib` library. Here we have the error messages

<details>

<summary>
win32/restart-wazuh.exe error messages
</summary>

``` bash
make[1]: Entering directory '/home/vagrant/wazuh_win/wazuh/src'
i686-w64-mingw32-gcc -DARGV0=\"restart-wazuh\" -Wl,-Bstatic,--whole-archive -lwinpthread -Wl,--no-whole-archive -Wl,-Bdynamic -O2  libwazuhshared.dll libwazuhext.lib active-response/restart-wazuh.o active-response/active_responses.o -s -o win32/restart-wazuh.exe
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0xdc): undefined reference to `cJSON_ParseWithOpts@12'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0xf9): undefined reference to `cJSON_GetObjectItem@8'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x104): undefined reference to `cJSON_IsNumber@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x11b): undefined reference to `cJSON_GetObjectItem@8'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x126): undefined reference to `cJSON_IsObject@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x13d): undefined reference to `cJSON_GetObjectItem@8'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x148): undefined reference to `cJSON_IsString@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x15f): undefined reference to `cJSON_GetObjectItem@8'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x16a): undefined reference to `cJSON_IsObject@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x186): undefined reference to `cJSON_Delete@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x23c): undefined reference to `cJSON_GetObjectItem@8'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x249): undefined reference to `cJSON_IsString@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x2d7): undefined reference to `cJSON_Delete@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x375): undefined reference to `cJSON_CreateObject@0'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x38d): undefined reference to `cJSON_AddNumberToObject@16'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x395): undefined reference to `cJSON_CreateObject@0'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x3ab): undefined reference to `cJSON_AddItemToObject@12'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x3cc): undefined reference to `cJSON_AddStringToObject@12'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x3e7): undefined reference to `cJSON_AddStringToObject@12'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x402): undefined reference to `cJSON_AddStringToObject@12'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x40a): undefined reference to `cJSON_CreateObject@0'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x420): undefined reference to `cJSON_AddItemToObject@12'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x428): undefined reference to `cJSON_CreateArray@0'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x43e): undefined reference to `cJSON_AddItemToObject@12'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x464): undefined reference to `cJSON_CreateString@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x473): undefined reference to `cJSON_AddItemToArray@8'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x487): undefined reference to `cJSON_PrintUnformatted@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x494): undefined reference to `cJSON_Delete@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x558): undefined reference to `cJSON_GetObjectItem@8'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x565): undefined reference to `cJSON_IsString@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x5a0): undefined reference to `cJSON_Delete@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x644): undefined reference to `cJSON_Delete@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x664): undefined reference to `cJSON_GetObjectItem@8'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x671): undefined reference to `cJSON_IsString@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x6a4): undefined reference to `cJSON_GetObjectItem@8'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x6b1): undefined reference to `cJSON_IsObject@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x6c8): undefined reference to `cJSON_GetObjectItem@8'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x6d5): undefined reference to `cJSON_IsObject@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x716): undefined reference to `cJSON_GetObjectItem@8'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x723): undefined reference to `cJSON_IsObject@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x73e): undefined reference to `cJSON_GetObjectItem@8'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x74b): undefined reference to `cJSON_IsObject@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x766): undefined reference to `cJSON_GetObjectItem@8'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x773): undefined reference to `cJSON_IsObject@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x78e): undefined reference to `cJSON_GetObjectItem@8'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x79b): undefined reference to `cJSON_IsObject@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x7b2): undefined reference to `cJSON_GetObjectItem@8'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x7bf): undefined reference to `cJSON_IsObject@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x7d6): undefined reference to `cJSON_GetObjectItem@8'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x7e3): undefined reference to `cJSON_IsString@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x7fa): undefined reference to `cJSON_GetObjectItem@8'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x807): undefined reference to `cJSON_IsString@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x81e): undefined reference to `cJSON_IsString@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x854): undefined reference to `cJSON_GetObjectItem@8'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x861): undefined reference to `cJSON_IsString@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x894): undefined reference to `cJSON_GetObjectItem@8'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x8a1): undefined reference to `cJSON_IsObject@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x8b8): undefined reference to `cJSON_GetObjectItem@8'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x8c5): undefined reference to `cJSON_IsObject@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x8dc): undefined reference to `cJSON_GetObjectItem@8'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x8e9): undefined reference to `cJSON_IsObject@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x900): undefined reference to `cJSON_GetObjectItem@8'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x90d): undefined reference to `cJSON_IsString@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x953): undefined reference to `cJSON_GetObjectItem@8'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x960): undefined reference to `cJSON_IsObject@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x97b): undefined reference to `cJSON_GetObjectItem@8'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x988): undefined reference to `cJSON_IsArray@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x9cc): undefined reference to `cJSON_GetArraySize@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x9df): undefined reference to `cJSON_GetArrayItem@8'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0x9ec): undefined reference to `cJSON_IsString@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0xac3): undefined reference to `cJSON_GetObjectItem@8'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0xad0): undefined reference to `cJSON_IsObject@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0xaeb): undefined reference to `cJSON_GetObjectItem@8'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0xaf8): undefined reference to `cJSON_IsArray@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0xb28): undefined reference to `cJSON_GetArrayItem@8'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0xb35): undefined reference to `cJSON_IsString@4'
/usr/bin/i686-w64-mingw32-ld: active-response/active_responses.o:active_respons:(.text+0xb8a): undefined reference to `cJSON_GetArraySize@4'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:2411: win32/restart-wazuh.exe] Error 1
make[1]: Leaving directory '/home/vagrant/wazuh_win/wazuh/src'
make: *** [Makefile:786: winagent] Error 2
```

</details>

The compilation of cJSON is being analyzed to determine where the symbol definition issue is.

**Comment by pereyra-m** [comment]
## Update 

Working branch: https://github.com/wazuh/wazuh/tree/dev-16319-delay-load.

**Tasks completed**:

- The first was completed, adding a delay load to `libwazuhshared.dll` in the same way as `libwazuhext.dll`.
- The compilation errors of the active response binaries were solved.

**Current state:**

- The second step is in progress: these delay loaded libraries now have to be explicitly loaded and verified.
- All the Wazuh agent binaries can be executed without the initial load of the non-system libraries `libwazuhext.dll`, `libwazuhshared.dll` and `libwinpthread-1.dll`. Here we have the example with `wazuh-agent.exe`, comparing the binary with and without the changes

![dependecy_walker](https://user-images.githubusercontent.com/65046601/224328939-60a45496-cd0b-4152-86bf-3ed69475554c.png)

![proc_mon2](https://user-images.githubusercontent.com/65046601/224328963-e62bbda5-e11a-49f1-b5fc-f22982721668.png)

![proc_mon1](https://user-images.githubusercontent.com/65046601/224328980-5a7e17ab-1e20-4db7-9488-d1320805ad81.png)

**Comment by pereyra-m** [comment]
## Update

Working branch: https://github.com/wazuh/wazuh/tree/dev-16319-delay-load.

The second step of the issue was delayed because more libraries were being tried to be opened like `wsock32.dll` and `msasn1.dll`. The possibility of a delay load was analyzed but it was much simpler to embed an XML manifest in the executable  to:
- Force the system libraries to be searched in the System folders as required
- Avoid a [DotLocal (.local) Dll Redirection](https://learn.microsoft.com/en-us/archive/blogs/junfeng/dotlocal-local-dll-redirection)

**Tasks completed**: 
- A manifest was added to all the executables that didn't have one. Also, many libraries were explicitly configured to be loaded from the System folder.

![2023-03-13_18-57](https://user-images.githubusercontent.com/65046601/224841261-92227f09-6273-469c-945d-f205db1a5881.png)

**Comment by pereyra-m** [comment]
## Update

Working branch: https://github.com/wazuh/wazuh/tree/dev-16319-delay-load.


**Current state:**

- Some Windows executables that are being compiled with the delayed load libraries are having crashes that are under research. Some initialization code (before the `main()` method) is looking for manager methods and crashing. This behavior isn't logical, because these Wazuh methods are compiled under `libwazuh.a`, and this library wasn't added to the delay load libraries.

![2023-03-17_11-00](https://user-images.githubusercontent.com/65046601/226342794-96dbb0f2-35e2-4cb1-926b-cd9a5b0f9a0f.png)
![2023-03-16_18-48](https://user-images.githubusercontent.com/65046601/226342802-c949acae-4aa8-43b6-a6ee-aac4b1cf817c.png)
![2023-03-16_18-46](https://user-images.githubusercontent.com/65046601/226342811-3ba252a3-cd16-4f63-b7d7-ec8c846abba9.png)

**Comment by pereyra-m** [comment]
### Update

Working branch: https://github.com/wazuh/wazuh/tree/dev-16319-delay-load.

The executable were crashing due to https://www.sourceware.org/bugzilla/show_bug.cgi?id=22676.
The workaround in https://www.sourceware.org/bugzilla/show_bug.cgi?id=14339 was applied: it consists in omitting the `__declspec(dllimport)` from every external library in `libwazuhext.dll` (using compilation defines). Also, the `-D` option was added to `dlltool` to set the right name and the compilation flag `--add-stdcall-alias` was added to properly resolve the cJSON symbols.

A dummy program was created to validate that all the external libraries symbols are properly resolved by the delay load mechanism.

<details>
<summary>
Test program output
</summary>

```
Hello World!
I'm in dliStartProcessing for externalMethods.dll, external_method
I'm in dliNotePreLoadLibrary for externalMethods.dll, external_method
DllMain in externalMethod DLL_PROCESS_ATTACH
I'm in dliNotePreGetProcAddress for externalMethods.dll, external_method
I'm in dliNoteEndProcessing for externalMethods.dll, external_method
100
**
I'm in dliStartProcessing for libwazuhext.dll, cJSON_CreateObject
I'm in dliNotePreLoadLibrary for libwazuhext.dll, cJSON_CreateObject
I'm in dliNotePreGetProcAddress for libwazuhext.dll, cJSON_CreateObject
I'm in dliNoteEndProcessing for libwazuhext.dll, cJSON_CreateObject
I'm in dliStartProcessing for libwazuhext.dll, cJSON_AddStringToObject
I'm in dliNotePreGetProcAddress for libwazuhext.dll, cJSON_AddStringToObject
I'm in dliNoteEndProcessing for libwazuhext.dll, cJSON_AddStringToObject
I'm in dliStartProcessing for libwazuhext.dll, cJSON_Print
I'm in dliNotePreGetProcAddress for libwazuhext.dll, cJSON_Print
I'm in dliNoteEndProcessing for libwazuhext.dll, cJSON_Print
{
        "name": "value"
}
I'm in dliStartProcessing for libwazuhext.dll, cJSON_Delete
I'm in dliNotePreGetProcAddress for libwazuhext.dll, cJSON_Delete
I'm in dliNoteEndProcessing for libwazuhext.dll, cJSON_Delete
I'm in dliStartProcessing for libwazuhext.dll, external_method_2
I'm in dliNotePreGetProcAddress for libwazuhext.dll, external_method_2
I'm in dliNoteEndProcessing for libwazuhext.dll, external_method_2
200
**
I'm in dliStartProcessing for libwazuhext.dll, pcre2_compile_8
I'm in dliNotePreGetProcAddress for libwazuhext.dll, pcre2_compile_8
I'm in dliNoteEndProcessing for libwazuhext.dll, pcre2_compile_8
1
**
I'm in dliStartProcessing for libwazuhext.dll, zlibVersion
I'm in dliNotePreGetProcAddress for libwazuhext.dll, zlibVersion
I'm in dliNoteEndProcessing for libwazuhext.dll, zlibVersion
1.2.11
**
I'm in dliStartProcessing for libwazuhext.dll, EVP_MD_CTX_new
I'm in dliNotePreGetProcAddress for libwazuhext.dll, EVP_MD_CTX_new
I'm in dliNoteEndProcessing for libwazuhext.dll, EVP_MD_CTX_new
I'm in dliStartProcessing for libwazuhext.dll, EVP_sha1
I'm in dliNotePreGetProcAddress for libwazuhext.dll, EVP_sha1
I'm in dliNoteEndProcessing for libwazuhext.dll, EVP_sha1
I'm in dliStartProcessing for libwazuhext.dll, EVP_DigestInit
I'm in dliNotePreGetProcAddress for libwazuhext.dll, EVP_DigestInit
I'm in dliNoteEndProcessing for libwazuhext.dll, EVP_DigestInit
1
I'm in dliStartProcessing for libwazuhext.dll, OPENSSL_init_ssl
I'm in dliNotePreGetProcAddress for libwazuhext.dll, OPENSSL_init_ssl
I'm in dliNoteEndProcessing for libwazuhext.dll, OPENSSL_init_ssl
1
1
I'm in dliStartProcessing for libwazuhext.dll, OPENSSL_init_crypto
I'm in dliNotePreGetProcAddress for libwazuhext.dll, OPENSSL_init_crypto
I'm in dliNoteEndProcessing for libwazuhext.dll, OPENSSL_init_crypto
1
**
I'm in dliStartProcessing for libwazuhext.dll, sqlite3_open
I'm in dliNotePreGetProcAddress for libwazuhext.dll, sqlite3_open
I'm in dliNoteEndProcessing for libwazuhext.dll, sqlite3_open
0
**
I'm in dliStartProcessing for libwazuhext.dll, yaml_parser_initialize
I'm in dliNotePreGetProcAddress for libwazuhext.dll, yaml_parser_initialize
I'm in dliNoteEndProcessing for libwazuhext.dll, yaml_parser_initialize
1
I'm in dliStartProcessing for libwazuhext.dll, yaml_parser_delete
I'm in dliNotePreGetProcAddress for libwazuhext.dll, yaml_parser_delete
I'm in dliNoteEndProcessing for libwazuhext.dll, yaml_parser_delete
**
I'm in dliStartProcessing for libwazuhext.dll, curl_global_init
I'm in dliNotePreGetProcAddress for libwazuhext.dll, curl_global_init
I'm in dliNoteEndProcessing for libwazuhext.dll, curl_global_init
0
DllMain in externalMethod DLL_PROCESS_DETACH
```

</details>

**Comment by pereyra-m** [comment]
## Update

A PR was created to test the new Github action test.
A python test was created to run all the Wazuh executables and inspect them with Process monitor to find any missing library that could be used to inject malicious code.

After several adjustments, the test is working as expected

![2023-04-05_17-31](https://user-images.githubusercontent.com/65046601/230204557-41eff3b2-75e4-455d-a5b6-a560577b3ed6.png)

Now, some issues are being solved:
- The unit tests in Windows are failing
- Some integration tests are failing because the `WazuhSvc` can't be started properly.

**Comment by pereyra-m** [comment]
## Update

The PR https://github.com/wazuh/wazuh/pull/16607 is under review.
