### ISSUE TITLE
Review and test tool alternatives for implementation to fulfill task requirements

### ISSUE THREAD

**Issue by mateojames** [wazuh/wazuh#16349]
As part of the [integration of Wazuh as a subscriber in Amazon Security Lake](https://github.com/wazuh/wazuh/issues/16326), we will be testing different tools to send parquet files to s3 instances, retrieve parquet files from an s3, handle those accordingly taking into account the Open Cybersecurity Schema Framework (OCSF). This also includes the compression and decompression of files with the extension `.gz.parquet`.

The principal tools to be reviewed for use are the following:

- [OCSF Parquet Data Validation](https://github.com/aws-samples/amazon-security-lake/tree/main/validate_1.0.0-rc.2)
- [AWS SDK for pandas (awswrangler)](https://github.com/aws/aws-sdk-pandas)

## Tasks

- [x] :green_circle: Send parquet files to an S3 successfully with AWSWrangler
- [x] :green_circle: Retrieve parquet files to an S3 successfully with AWSWrangler
- [x] <del> Handle the files with `.gz.parquet` via decompression and parquet reading</del>
- [x] :red_circle: Test the validation of OCSF Parquet Data with AWSWrangler
- [x] Read Parquet data and map it to a compatible JSON for later analysis with AWSWrangler

**Comment by mateojames** [comment]
## UPDATE

The sample script provided on the OCSF validator was tested and ir runs successfully, validating a sample parquet provided by the tool.
<details><summary>Sample Test OCSF Parquet Validator 🟢 </summary>
python sample.py

Validating Against Event Class: api_activity (3005)...

----------------------------------------FILE DATA----------------------------------------
{
      "activity_id": 2,
      "activity_name": "Read",
      "api": {
            "operation": "PutObject",
            "request": {
                  "uid": "AAAAA1111BBBB222"
            },
            "service": {
                  "name": "s3.amazonaws.com"
            }
      },
      "actor": {
            "invoked_by": "asus incidents china",
            "process": {
                  "cmd_line": "soft continues aerial",
                  "file": {
                        "fingerprints": [
                              {
                                    "algorithm": "CTPH",
                                    "algorithm_id": 5,
                                    "value": "50A8F9A63714AB82F79F8E79E82A9EB60A13507D5E9CCC85221814039F6BCC69B16F6CCF2096B836B2702D7B15AE804DEEF1EBCB6C92818A5157387DC29E49E7"
                              }
                        ],
                        "is_system": true,
                        "modifier": {
                              "account_uid": "521e652a-a8c2-11ed-ba25-0242ac110002",
                              "domain": "filed sand antigua",
                              "name": "Lessons",
                              "org_uid": "521e6ad4-a8c2-11ed-a3b1-0242ac110002",
                              "uid": "521e6e8a-a8c2-11ed-9ba5-0242ac110002"
                        },
                        "name": "taste.cgi",
                        "parent_folder": "/practitioner/rendering/collectors/connecticut/cases/jul.swift",
                        "path": "/practitioner/rendering/collectors/connecticut/cases/jul.swift/taste.cgi",
                        "product": {
                              "name": "induction targets seats",
                              "uid": "521e75e2-a8c2-11ed-838c-0242ac110002",
                              "vendor_name": "uniprotkb peripherals items",
                              "version": "1.0.0-rc.2"
                        },
                        "security_descriptor": "satisfy interesting susan",
                        "type": "Unknown",
                        "type_id": 0,
                        "version": "1.0.0-rc.2"
                  },
                  "loaded_modules": [
                        "/mentioned/edmonton/kind/pal/thirty.sh",
                        "/appointments/jc/contrast/isle/scenarios.msg"
                  ],
                  "name": "Since",
                  "parent_process": {
                        "created_time": 1675978807320480,
                        "file": {
                              "attributes": 68,
                              "company_name": "Junita Priscilla",
                              "confidentiality": "Confidential",
                              "confidentiality_id": 2,
                              "desc": "chosen phi mpg",
                              "fingerprints": [
                                    {
                                          "algorithm": "SHA-256",
                                          "algorithm_id": 3,
                                          "value": "7896A617A785DD968B580C61A2B418AE7EA28ECB713A3650178971519C566C4E"
                                    }
                              ],
                              "mime_type": "wolf/handed",
                              "modifier": {
                                    "account_type": "disorders clark queue",
                                    "credential_uid": "521e959a-a8c2-11ed-889d-0242ac110002",
                                    "groups": [
                                          {
                                                "name": "nights testament inspired",
                                                "uid": "521ea1c0-a8c2-11ed-b122-0242ac110002"
                                          },
                                          {
                                                "name": "phenomenon networks immunology"
                                          }
                                    ],
                                    "name": "Reasons",
                                    "uid": "521ea756-a8c2-11ed-89d4-0242ac110002"
                              },
                              "name": "candidate.vcxproj",
                              "parent_folder": "/classic/navigation/geographic/petroleum/assessment/apparel.prf",
                              "path": "/classic/navigation/geographic/petroleum/assessment/apparel.prf/candidate.vcxproj",
                              "signature": {
                                    "company_name": "Raven Angella",
                                    "created_time": 1675978807321659,
                                    "fingerprints": [
                                          {
                                                "algorithm": "CTPH",
                                                "algorithm_id": 5,
                                                "value": "69561CBDD2FB0112CA594C9DAA9704C2B932BEBE8D51ED7299CB0C0B3279C227EC1514C60E30E8C8F599F571F1DA5E3EDF64E64DE1305630F34D43F9BCF3518C"
                                          }
                                    ]
                              },
                              "size": 2061303196,
                              "type": "richard",
                              "type_id": 99
                        },
                        "loaded_modules": [
                              "/cams/gains/harris/tp/mats.rm"
                        ],
                        "name": "Survive",
                        "parent_process": {
                              "cmd_line": "brunswick acceptable born",
                              "created_time": 1675978807321834,
                              "file": {
                                    "confidentiality": "Confidential",
                                    "confidentiality_id": 2,
                                    "fingerprints": [
                                          {
                                                "algorithm": "Unknown",
                                                "algorithm_id": 0,
                                                "value": "C2E430150A9DC86ABC74A1173C224D579F595A553B4F37C7022AF0835A80945B71BC5738FD1E0F1F1067E6DD5F38FFD8853231A746721B640ED03659F27F960B"
                                          },
                                          {
                                                "algorithm": "SHA-512",
                                                "algorithm_id": 4,
                                                "value": "FEEC6E2C86C50E5C01E4FECF2077470B20EAD3510927B11477321B340265F24CA13BED9553A698B1D42D26157DCF7A75B4ED5097D082522CA6995F3C2D80D090"
                                          }
                                    ],
                                    "is_system": false,
                                    "modifier": {
                                          "domain": "towns nice bug",
                                          "name": "Supervisors",
                                          "type": "dsc ya disposition",
                                          "uid": "521ebf02-a8c2-11ed-8c35-0242ac110002"
                                    },
                                    "name": "ultimate.fnt",
                                    "parent_folder": "/coaching/deeper/photographers/stroke/half/information.js",
                                    "path": "/coaching/deeper/photographers/stroke/half/information.js/ultimate.fnt",
                                    "product": {
                                          "name": "funny prison bangkok",
                                          "uid": "521ecbfa-a8c2-11ed-b75b-0242ac110002",
                                          "vendor_name": "unity admit strange",
                                          "version": "1.0.0-rc.2"
                                    },
                                    "type": "Character Device",
                                    "type_id": 3
                              },
                              "integrity": "stores ts actively",
                              "loaded_modules": [
                                    "/continually/pregnancy/rank/michigan/james.js"
                              ],
                              "name": "Inquiry",
                              "parent_process": {
                                    "created_time": 1675978807322722,
                                    "file": {
                                          "confidentiality": "ms associate metabolism",
                                          "fingerprints": [
                                                {
                                                      "algorithm": "SHA-1",
                                                      "algorithm_id": 2,
                                                      "value": "73FDDEF46CBCF6B91B2A2DA18643439A9B666F4F"
                                                },
                                                {
                                                      "algorithm": "SHA-512",
                                                      "algorithm_id": 4,
                                                      "value": "CF57C835C3C3228D710D63528B9D59BA04BA0CB2EE9ADD0319C181BE126713CDDCBC12836A3BDF9484E6B81DB304167CABC20CBE192A5533893650FC4C082EC5"
                                                }
                                          ],
                                          "name": "monitors.b",
                                          "type": "Character Device",
                                          "type_id": 3
                                    },
                                    "name": "Humidity",
                                    "parent_process": {
                                          "cmd_line": "fast acc anyway",
                                          "created_time": 1675978807325390,
                                          "integrity": "bleeding loving blast",
                                          "name": "Carlo",
                                          "pid": 47,
                                          "uid": "521f421a-a8c2-11ed-91bf-0242ac110002",
                                          "user": {
                                                "account_type": "AWS IAM User",
                                                "account_type_id": 3,
                                                "domain": "mind statewide abuse",
                                                "email_addr": "Irma@william.org",
                                                "name": "Investigations",
                                                "uid": "521f4a4e-a8c2-11ed-a108-0242ac110002"
                                          }
                                    },
                                    "pid": 61,
                                    "session": {
                                          "created_time": 1675978807325806,
                                          "issuer": "assumption realtor in",
                                          "uid": "521f50ca-a8c2-11ed-81d5-0242ac110002"
                                    },
                                    "uid": "521f546c-a8c2-11ed-848e-0242ac110002",
                                    "user": {
                                          "account_type": "magnet a nelson",
                                          "name": "Dependent",
                                          "org_uid": "521f5b9c-a8c2-11ed-9e0a-0242ac110002",
                                          "uid": "521f5f0c-a8c2-11ed-9f4d-0242ac110002"
                                    }
                              },
                              "pid": 22,
                              "terminated_time": 1675978807326322,
                              "user": {
                                    "account_type": "Windows Account",
                                    "account_type_id": 2,
                                    "name": "Prediction"
                              }
                        },
                        "pid": 58,
                        "sandbox": "cached howard bt",
                        "terminated_time": 1675978807326450,
                        "uid": "521f6a88-a8c2-11ed-9a67-0242ac110002",
                        "user": {
                              "name": "Difference",
                              "org_uid": "521f7168-a8c2-11ed-82c4-0242ac110002",
                              "uid": "521f74e2-a8c2-11ed-8097-0242ac110002",
                              "uuid": "521f7898-a8c2-11ed-8eb8-0242ac110002"
                        }
                  },
                  "pid": 12,
                  "session": {
                        "created_time": 1675978807327041,
                        "expiration_time": 1675978807327047,
                        "issuer": "mitsubishi organisms higher",
                        "uid": "521f80d6-a8c2-11ed-b192-0242ac110002"
                  },
                  "uid": "521f840a-a8c2-11ed-b1c4-0242ac110002",
                  "user": {
                        "name": "Automatically",
                        "uid": "521f8aa4-a8c2-11ed-84d2-0242ac110002"
                  }
            },
            "user": {
                  "name": "Minerals",
                  "org_uid": "521f9044-a8c2-11ed-96ac-0242ac110002",
                  "type": "Admin",
                  "type_id": 2,
                  "uid": "521f9418-a8c2-11ed-bd21-0242ac110002"
            }
      },
      "category_name": "Audit Activity",
      "category_uid": 3,
      "class_name": "API Activity",
      "class_uid": 3005,
      "dst_endpoint": {
            "domain": "terrorism line enables",
            "hostname": "rapidly.gov",
            "instance_uid": "521e0e5e-a8c2-11ed-a604-0242ac110002",
            "interface_name": "constitution accused assisted",
            "interface_uid": "521e1836-a8c2-11ed-9d6c-0242ac110002",
            "ip": "161.181.96.23",
            "name": "a division ai",
            "port": 39762,
            "subnet_uid": "521e1e80-a8c2-11ed-97d7-0242ac110002",
            "svc_name": "wn deployment pirates",
            "uid": "521e23e4-a8c2-11ed-9404-0242ac110002"
      },
      "duration": 45,
      "message": "printing experts coins",
      "metadata": {
            "original_time": "global situated bobby",
            "processed_time": 1675978807318380,
            "product": {
                  "lang": "en",
                  "name": "fatty official french",
                  "uid": "521e35aa-a8c2-11ed-874e-0242ac110002",
                  "vendor_name": "metabolism worlds coin"
            },
            "profiles": [],
            "uid": "521e3afa-a8c2-11ed-9313-0242ac110002",
            "version": "1.0.0-rc.2"
      },
      "resources": [
            {
                  "account_uid": "521fb042-a8c2-11ed-9f90-0242ac110002",
                  "details": "fruits bonds masters",
                  "group_name": "attribute mag dancing",
                  "name": "rain lease gulf",
                  "owner": {
                        "name": "Viewing",
                        "type": "models",
                        "type_id": 99.0,
                        "uid": "521fb736-a8c2-11ed-8702-0242ac110002"
                  },
                  "uid": "521fbcfe-a8c2-11ed-9a6a-0242ac110002"
            },
            {
                  "criticality": "partnership damages consultancy",
                  "group_name": "cancer beijing float",
                  "name": "airline provides prescription",
                  "owner": {
                        "account_type": "Windows Account",
                        "account_type_id": 2.0,
                        "name": "Employment",
                        "uid": "521fc492-a8c2-11ed-a341-0242ac110002"
                  },
                  "uid": "521fcabe-a8c2-11ed-a606-0242ac110002"
            }
      ],
      "severity": "Critical",
      "severity_id": 5,
      "src_endpoint": {
            "hostname": "desire.com",
            "instance_uid": "521fa23c-a8c2-11ed-98f4-0242ac110002",
            "interface_name": "reporting others maritime",
            "interface_uid": "521fa638-a8c2-11ed-a7ee-0242ac110002",
            "ip": "108.158.95.134",
            "mac": "B1:40:CD:D7:A4:ED:1A:B6",
            "port": 8589,
            "svc_name": "photoshop protection referred",
            "uid": "521faa66-a8c2-11ed-a279-0242ac110002"
      },
      "time": 1675978807317245,
      "timezone_offset": 12,
      "type_name": "API Activity: Read",
      "type_uid": 300502
}

-------------------------------------------------------------------------------------

VALID OCSF.
</details>

However, when tested against a parquet directly downloaded from a S3 instance, the validator finds the format invalid.
<details><summary>Test OCSF Parquet Validator with a Parquet generated by us 🔴  </summary>
python validate.py -i "/path/to/the/parquet/directory"  -version ocsf_schema_1.0.0-rc.2
{'version': 'ocsf_schema_1.0.0-rc.2', 'path': '/Users/mateo/Laburo/Wazuh/SecurityLake'}

Validating Against Event Class: inventory_info (5001)...

-----------------------------------FILE DATA-----------------------------------
{
      "metadata": {
            "product": {
                  "version": "1.08",
                  "name": "CloudTrail",
                  "feature": {
                        "name": "Management, Data, and Insights"
                  },
                  "vendor_name": "AWS"
            },
            "profiles": [
                  "cloud"
            ],
            "version": "0.26.1"
      },
      "time": 1678121018000,
      "cloud": {
            "region": "eu-west-1",
            "provider": "AWS"
      },
      "api": {
            "response": {},
            "operation": "PutObject",
            "request": {
                  "uid": "Q49GNBSKJD9DQV09"
            },
            "service": {
                  "name": "s3.amazonaws.com"
            }
      },
      "ref_event_uid": "06c80536-37c3-4df7-a40e-573ccdee6ecf",
      "src_endpoint": {
            "uid": "vpce-088a843e1626bec10",
            "domain": "securitylake.amazonaws.com"
      },
      "resources": [
            {
                  "uid": "arn:aws:s3:::aws-security-data-lake-eu-west-1-bt0t8tsmsv9l9j7zueyfr3lbndhydf/aws/CLOUD_TRAIL/region=eu-west-1/accountId=567970947422/eventHour=2023030616/9ec35be7307d1d5c750711c1e11c0bb4.gz.parquet",
                  "type": "AWS::S3::Object"
            },
            {
                  "uid": "arn:aws:s3:::aws-security-data-lake-eu-west-1-bt0t8tsmsv9l9j7zueyfr3lbndhydf",
                  "account_uid": "567970947422",
                  "type": "AWS::S3::Bucket"
            }
      ],
      "identity": {
            "user": {
                  "type": "AWSService"
            },
            "session": {},
            "invoked_by": "securitylake.amazonaws.com",
            "idp": {}
      },
      "http_request": {
            "user_agent": "securitylake.amazonaws.com"
      },
      "class_name": "Cloud API",
      "class_uid": 5001,
      "category_name": "Cloud Activity",
      "category_uid": 5,
      "severity_id": 0,
      "severity": "Unknown",
      "activity_name": "Operational",
      "activity_id": 3,
      "type_uid": 500103,
      "type_name": "Cloud API: Operational",
      "unmapped": [
            [
                  "eventCategory",
                  "Data"
            ],
            [
                  "sharedEventID",
                  "34675fc3-0550-4c03-99dd-382f83094643"
            ],
            [
                  "responseElements",
                  "{\"x-amz-server-side-encryption\":\"AES256\"}"
            ],
            [
                  "requestParameters",
                  "{\"bucketName\":\"aws-security-data-lake-eu-west-1-bt0t8tsmsv9l9j7zueyfr3lbndhydf\",\"Host\":\"aws-security-data-lake-eu-west-1-bt0t8tsmsv9l9j7zueyfr3lbndhydf.s3.eu-west-1.amazonaws.com\",\"x-amz-acl\":\"bucket-owner-full-control\",\"key\":\"aws/CLOUD_TRAIL/region=eu-west-1/accountId=567970947422/eventHour=2023030616/9ec35be7307d1d5c750711c1e11c0bb4.gz.parquet\"}"
            ],
            [
                  "recipientAccountId",
                  "567970947422"
            ],
            [
                  "readOnly",
                  "false"
            ],
            [
                  "eventType",
                  "AwsApiCall"
            ],
            [
                  "managementEvent",
                  "false"
            ],
            [
                  "additionalEventData",
                  "{\"SignatureVersion\":\"SigV4\",\"CipherSuite\":\"ECDHE-RSA-AES128-GCM-SHA256\",\"bytesTransferredIn\":20562,\"SSEApplied\":\"Default_SSE_S3\",\"AuthenticationMethod\":\"AuthHeader\",\"x-amz-id-2\":\"xQtyXYjgoKQC/YnRHZ8doJMY/By/xO7vlqTYY6TAp1Skq0FyEoJLuJQkkEsjMCDjQbUc2bFYinFm1+lbDIDvkQ==\",\"bytesTransferredOut\":0}"
            ]
      ]
}

---------------------------------------------------------------------------

INVALID OCSF.

3 is not one of [0, 1, 99]

Failed validating 'enum' in schema['properties']['activity_id']:
    {'enum': [0, 1, 99], 'title': 'Activity ID', 'type': 'integer'}

On instance['activity_id']:
    3
500103 is not one of [500100, 500101, 500199]

Failed validating 'enum' in schema['properties']['type_uid']:
    {'enum': [500100, 500101, 500199],
     'title': 'Type ID',
     'type': 'integer'}

On instance['type_uid']:
    500103
[['eventCategory', 'Data'], ['sharedEventID', '34675fc3-0550-4c03-99dd-382f83094643'], ['responseElements', '{"x-amz-server-side-encryption":"AES256"}'], ['requestParameters', '{"bucketName":"aws-security-data-lake-eu-west-1-bt0t8tsmsv9l9j7zueyfr3lbndhydf","Host":"aws-security-data-lake-eu-west-1-bt0t8tsmsv9l9j7zueyfr3lbndhydf.s3.eu-west-1.amazonaws.com","x-amz-acl":"bucket-owner-full-control","key":"aws/CLOUD_TRAIL/region=eu-west-1/accountId=567970947422/eventHour=2023030616/9ec35be7307d1d5c750711c1e11c0bb4.gz.parquet"}'], ['recipientAccountId', '567970947422'], ['readOnly', 'false'], ['eventType', 'AwsApiCall'], ['managementEvent', 'false'], ['additionalEventData', '{"SignatureVersion":"SigV4","CipherSuite":"ECDHE-RSA-AES128-GCM-SHA256","bytesTransferredIn":20562,"SSEApplied":"Default_SSE_S3","AuthenticationMethod":"AuthHeader","x-amz-id-2":"xQtyXYjgoKQC/YnRHZ8doJMY/By/xO7vlqTYY6TAp1Skq0FyEoJLuJQkkEsjMCDjQbUc2bFYinFm1+lbDIDvkQ==","bytesTransferredOut":0}']] is not of type 'object'

Failed validating 'type' in schema['properties']['unmapped']:
    {'additionalProperties': True,
     'properties': {},
     'title': 'Object',
     'type': 'object'}

On instance['unmapped']:
    [['eventCategory', 'Data'],
     ['sharedEventID', '34675fc3-0550-4c03-99dd-382f83094643'],
     ['responseElements', '{"x-amz-server-side-encryption":"AES256"}'],
     ['requestParameters',
      '{"bucketName":"aws-security-data-lake-eu-west-1-bt0t8tsmsv9l9j7zueyfr3lbndhydf","Host":"aws-security-data-lake-eu-west-1-bt0t8tsmsv9l9j7zueyfr3lbndhydf.s3.eu-west-1.amazonaws.com","x-amz-acl":"bucket-owner-full-control","key":"aws/CLOUD_TRAIL/region=eu-west-1/accountId=567970947422/eventHour=2023030616/9ec35be7307d1d5c750711c1e11c0bb4.gz.parquet"}'],
     ['recipientAccountId', '567970947422'],
     ['readOnly', 'false'],
     ['eventType', 'AwsApiCall'],
     ['managementEvent', 'false'],
     ['additionalEventData',
      '{"SignatureVersion":"SigV4","CipherSuite":"ECDHE-RSA-AES128-GCM-SHA256","bytesTransferredIn":20562,"SSEApplied":"Default_SSE_S3","AuthenticationMethod":"AuthHeader","x-amz-id-2":"xQtyXYjgoKQC/YnRHZ8doJMY/By/xO7vlqTYY6TAp1Skq0FyEoJLuJQkkEsjMCDjQbUc2bFYinFm1+lbDIDvkQ==","bytesTransferredOut":0}']]
</details>

There is a couple of interesting observations. For one, the validator seems to be able to read the file in the directory without a problem, showing its contents correctly. However, this file is in a `.gz.parquet` format, not in a `.parquet` format as the sample file was. This could be the origin of the problem of the test. Further testing is required.

**Comment by mateojames** [comment]
## UPDATE

Using the AWSWrangler tool, we were able to successfully download and upload parquet files with no issues in few lines.

### Download Parquet file from S3 🟢 
```
import awswrangler as wr
wr.s3.download(path=s3_path, local_file=local_file)
```
The file is saved successfully.

### Upload Parquet file to S3 🟢 
```
import awswrangler as wr
wr.s3.upload(local_file,path=s3_directory+"test.gz.parquet")
```
The file was uploaded successfully

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/64434083/224047576-3f19fea4-c21c-4373-9473-1bd394d9dc70.png">

**Comment by mhamra** [comment]
### UPDATE
Using pandas package, it is straightforward to convert parquet files into Json format row by row, but pandas package requires pyarrow package to read parquet files

```
import pandas as pd

df = pd.read_parquet('path_to_sample_parquet.parquet')
for row in df.iloc:
    print(row.to_json())

```
