### ISSUE TITLE
Show descriptive messages when parsing AWS configuration

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh#16383]
| Affected integration |
|---|
| AWS |

## Description

Currently, in some cases, the AWS configuration parser isn't showing messages.

- [x] Bucket empty values (only_logs_after, regions, path, path_suffix)
- [x] Service empty values (log_groups, only_logs_after, regions)
- [x] Bucket invalid values (name, regions, path, path_suffix)
- [x] Service invalid values (log_groups, only_logs_after, regions)

For empty values the message should be:

https://github.com/wazuh/wazuh/blob/dacf07da9930c4445ea55b1e5cdf6c7baea9a8d6/src/config/wmodules-command.c#L74

And for invalid values:

https://github.com/wazuh/wazuh/blob/dacf07da9930c4445ea55b1e5cdf6c7baea9a8d6/src/config/wmodules-command.c#L69

## Tasks
- [x] Test in a manager.
- [x] Test in an agent.
- [x] Unit tests without failures. Updated if there are any relevant changes.
- [x] Integration tests without failures. Updated if there are any relevant changes.
- [x] Update the documentation if necessary.
- [x] Add entry to the changelog if necessary.

**Comment by nico-stefani** [comment]
# Issue Update

I was trying to understand the C code that parses the `ossec.conf` configuration. I will continue investigating in order to reach the cause of the problem.

**Comment by nico-stefani** [comment]
I was working on the validation for empty values in 004ac54fc82499ae7f5bce689fb27c8836260a1a.
