### ISSUE TITLE
Build a v4.3.0 manager for AIX with restricted capabilities

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#16392]
|Base version|Target platform|Architecture|
|---|---|---|
|4.3|AIX 7.1 - 7.3|POWER7 - POWER9|

This task aims to provide a manager running on AIX 7.1+ to monitor itself locally and send alerts via Syslog.

This is _Phase 4_ of the epic issue: https://github.com/wazuh/wazuh/issues/15502

### Description

- Build a v4.3 manager on AIX, optimized for the different PowerPC architectures.
  - Fix compilation problems. First of all, the problem with the compilation of wazuh-DB.
- Rebase the local mode deprecation (phase 2) to branch 4.3.
  - Deprecate the installation in `local` mode. 
  - Be able to disable the compilation of: `Remoted`, `API` and `Clusterd`.

### Deliverable

1. Development branch with the following changes:
  - Compile and install a v4.3 manager on AIX.
  - Makefile: remove `TARGET=local` and add `BUILD_REMOTED=y|n`
  - Select which components to include in the sources' installer.

### Tasks
- [x] Compiling and installing a manager `4.3` on AIX.
  - [x] Fix compilation issue in `wazuh-DB`. `poll` implementation.
  - [x] Fix some definitions. Ex: `LOGALL` and `regex`
  - [x] Manual compilation and installation of `cmake`.
  - [x] Fix `strcasestr` definition for AIX.
  - [x] Fix function definition by library linking with `libwazuhext`: `BZ2`, `curl` and `zlib` (compress2).
- [ ] Rebase the local mode deprecation (phase 2) to branch `4.3`.
  - [ ] Remove `TARGET=local`
  - [ ] Disable components compilation.
- [x] Adding the feature of forwarding alerts to Fluentd: https://github.com/wazuh/wazuh/issues/16351
- [x] Testing in an _AIX_ environment
  - [x] AIX 6
  - [x] AIX 7.1

**Comment by MarcelKemp** [comment]
## Compilation and installation problems
- _Lack of `nofity` implementation to compile Wazuh-DB._
In this case, there was no specific implementation for AIX, so we had to implement all the functions using `pollset`.
  - Commits: https://github.com/wazuh/wazuh/commit/aaca8da92dc95c014f654eacd4117e38c3f81d5e & https://github.com/wazuh/wazuh/commit/f18276a9647c68b237c566318b8893f035225c3f
- _System variables and definitions that conflicted with code variables and definitions._
To fix this, it has been necessary to rename the variables in the code and in all its uses, so that it allows to compile without conflict and without losing any functionality. Variables affected: `regex` and `LOGALL`.
  - Commits: https://github.com/wazuh/wazuh/commit/a5f9b032a48c1fb0663f1fa018e4933d19b51963 & https://github.com/wazuh/wazuh/commit/3566aa6fd5a8e919ae047c27ff0cbf8692319a65
- _In AIX there is no `strcasestr` function, so it is necessary to define it and create a similar function in case AIX is detected.
It has simply been necessary to implement a `strcasestr` function that works similarly to the original one by using other functions, such as: `tolower`, `strncasecmp`, etc._
  - Commits: https://github.com/wazuh/wazuh/commit/a5f9b032a48c1fb0663f1fa018e4933d19b51963 & https://github.com/wazuh/wazuh/commit/9cdaeebcb497d6ee7906bf87397d9b4cf4b02eef
- _For AIX 7.1, a bug was found in the compilation of `cmake`, which did not allow it to be installed and caused errors in the compilation that made use of `cmake`._
This problem is fixed by manually running the `[build_cmake](https://github.com/wazuh/wazuh-packages/blob/daeeaa51b6d7f1c60d30ccbd69e413e414fca7b0/aix/generate_wazuh_packages.sh#L72-L83)` function found in the [wazuh-packages](https://github.com/wazuh/wazuh-packages/blob/master/aix/generate_wazuh_packages.sh) repository, and adding two new commands that allow linking and limiting the size of TOC in order to compile `cmake`. 
```sh
sed ' 1 s/.*/&-Wl,-bbigtoc/' Source/CMakeFiles/cmake.dir/link.txt | tee Source/CMakeFiles/cmake.dir/link.txt
sed ' 1 s/.*/&-Wl,-bbigtoc/' Tests/CMakeServerLib/CMakeFiles/CMakeServerLibTests.dir/link.txt | tee Tests/CMakeServerLib/CMakeFiles/CMakeServerLibTests.dir/link.txt
```

      Once compiled, it simply installs and compiles the `cmake` code correctly in Wazuh.
- _Undefined errors of functions used in the code due to the lack of linking of some libraries, not allowing to advance in the compilation of the code._
For AIX 6, the issue was solved by manually compiling the libraries and linking them to `libwazuhext.so`. In addition, it was necessary to manually rename and add `compress2`, because the `zlib` and `BZ2` libraries were overwritten. Affected libraries: `BZ2`, `curl` and `zlib` (compress2).
  - Commits: https://github.com/wazuh/wazuh/commit/211823cc1312c27e5c76fe08f2fb58424cb741c2 & https://github.com/wazuh/wazuh/commit/121d4cdecb0de684aab99b2fc380f7e6ae549681

  For AIX 7, the previous fix did not work for the `curl` library, so it has been necessary to apply another fix, where we have hardcoded the library that has the `curl_easy` functions defined, allowing us to find the defined functions and install the manager.
  - Commit: https://github.com/wazuh/wazuh/commit/3566aa6fd5a8e919ae047c27ff0cbf8692319a65

**Comment by mateocervilla** [comment]
## Functionality issues
- _Error at `wnotify_add`_
The `pollset_create()` function is different from its equivalent in `epoll` and `kevent` in terms of its argument. In this case, it is the maximum number of file descriptors that can belong to the pollset. When it has a value of -1, it is bound by `OPEN_MAX` as defined in `<sys/limits.h>` 
  - Commit: https://github.com/wazuh/wazuh/commit/6066ccf4fd0053e1a1094e688c530a00a450df28

- _`get_nproc()`: Unimplemented._
This function needed to be implemented for `AIX`. There, the `unistd.h` includes a system variable `_SC_NPROCESSORS_ONLN` for the `sysconf()` function that allows to get the number of processors online.
  - Commit: https://github.com/wazuh/wazuh/commit/8f93bb77c384fdc432625b73713c268d58691bcb

**Comment by mateocervilla** [comment]
## Current Errors

We are currently facing and working on some of the following errors:

- `wazuh-db: ERROR: Can't open SQLite database 'var/db/mitre.db': unable to open database file`

- `wazuh-analysisd: ERROR: Bad response from wazuh-db: Couldn't open DB mitre`
  - `wazuh-analysisd: ERROR: Response from the Mitre database cannot be parsed.`
  - `wazuh-analysisd: ERROR: Mitre matrix information could not be loaded.`

- `wazuh-analysisd: ERROR: (1109): Unable to create new pthread. Resource temporarily unavailable (11)`
  - `wazuh-analysisd: CRITICAL: (1109): Unable to create new pthread.`

- `wazuh-syscheckd: ERROR: socketerr (not available).`
  - `wazuh-syscheckd: ERROR: (1224): Error sending message to queue.`
- `wazuh-logcollector: ERROR: socketerr (not available).`
  - `wazuh-logcollector: ERROR: Unable to send message to 'queue/sockets/queue' (wazuh-analysisd might be down). Attempting to reconnect.`

**Comment by mateocervilla** [comment]
## Functionality issues
- _`wazuh-analysisd: ERROR: (1109): Unable to create new pthread. Resource temporarily unavailable (11)`_
The AIX machine we are working on seems to have some limitation related to the stack size of the threads. When the default value of 8192 KiB is assigned for the stack size, the `wazuh-analysisd` module reaches 30 threads and crashes. If the size is reduced to 2048, the execution seems to work OK. We are currently working with this size but also researching if this is a case of a system limitation or just a system parameter that can be adjusted.
The value of the stack size can be set in the parameter `wazuh.thread_stack_size` at the file `internal_options.conf`

When execution proceeds, it hits the following error

- _`wazuh-analysisd[11600040] rules.c:3138 at OS_CheckIfRuleMatch(): CRITICAL: At pthread_mutex_lock(): Invalid argument`_
To solve this error it was necessary to initialize the mutex to prevent it from crashing.
  - Commit: https://github.com/wazuh/wazuh/commit/dd1da6e87b63a703669c50ed418146d63e96cd30

- _`CRITICAL: (1102): Could not acquire memory due to [(0)-(Error 0)].`_
The program fails in the following `os_calloc`, and does not throw an error message (the only one that can throw is a lack of memory), it simply cuts because it receives NULL and that's how it is defined:
```
os_calloc(lf->nfields, sizeof(DynamicField), lf_cpy->fields);

    for (i = 0; i < lf->nfields; i++) {
        w_strdup(lf->fields[i].value, lf_cpy->fields[i].value);
        w_strdup(lf->fields[i].key, lf_cpy->fields[i].key);
    }

#define os_calloc(x,y,z) ((z = (__typeof__(z)) calloc(x,y)))?(void)1:merror_exit(MEM_ERROR, errno, strerror(errno))
```
We can see it wants to allocate some amount `lf->nfields` of memory that it is used in a for loop. In case it is 0, it never enters.
Since in AIX allocating a size 0 always returns NULL, the program thinks it fails but it doesn't. With the _LINUX_SOURCE_COMPAT flag we allow it to work as in Linux, that is, a valid pointer of size 0 is returned instead of NULL.
More info [here](https://www.ibm.com/docs/en/aix/7.1?topic=m-malloc-free-realloc-calloc-mallopt-mallinfo-mallinfo-heap-alloca-valloc-posix-memalign-subroutine#malloc__basetrf1-gen2267).
  - Commit: https://github.com/wazuh/wazuh/commit/59213c1cd1fdb7d820e21a8b63cb64ef99dc1fea


Since analysisd no longer crashes, the following errors no longer occur:
  - `wazuh-syscheckd: ERROR: socketerr (not available).`
  - `wazuh-logcollector: ERROR: socketerr (not available).`

**Comment by mateocervilla** [comment]
> * _`wazuh-analysisd: ERROR: (1109): Unable to create new pthread. Resource temporarily unavailable (11)`_
>   The AIX machine we are working on seems to have some limitation related to the stack size of the threads. When the default value of 8192 KiB is assigned for the stack size, the `wazuh-analysisd` module reaches 30 threads and crashes. If the size is reduced to 2048, the execution seems to work OK. We are currently working with this size but also researching if this is a case of a system limitation or just a system parameter that can be adjusted.
>   The value of the stack size can be set in the parameter `wazuh.thread_stack_size` at the file `internal_options.conf`

We found that by default, on AIX systems the memory limit of a 32 bit process is `256 MB`. In our case, the 30 threads + 1 main of 8 MB each gives a total of 248 MB and when a new 8 MB thread is created, the limit is reached and the program crashes.
This memory limit can be increased to a maximum of 2 GB using the environment variable `LDR_CNTRL`.

Executing the following command:
- `export LDR_CNTRL=MAXDATA=0x80000000` (Value 8 stands for 8x256MB (max. value) = 2 GB)

Then, we can execute in the current shell session a process up to 2 GB of memory.
In order to apply this to compile time, we can use the `Xlinker` gcc option to pass the `-bmaxdata:0x80000000` as an option to the linker. This will raise up the maximum memory available for allocation to the program.

This limit only exist because it seems that by default, the program is compiled as a 32-bit program. This can be changed with the `-maix64` option. Now, as it is a 64-bit program, the said memory limit does not exist anymore.

**Comment by mateocervilla** [comment]
> `wazuh-db: ERROR: Can't open SQLite database 'var/db/mitre.db': unable to open database file`
> `wazuh-analysisd: ERROR: Bad response from wazuh-db: Couldn't open DB mitre`

This error is caused by the lack of a proper compilation of cypthon, 
which is in charge of creating said missing file. An alternative is to download an already created `mitre.db` file.



> `wazuh-analysisd: ERROR: Response from the Mitre database cannot be parsed.`
> `wazuh-analysisd: ERROR: Mitre matrix information could not be loaded.`

This error occurs when parsing the `mitre.db` file. At some point, `wazuh-db` crashes and parsing is aborted. We notice that when compiling with `DEBUG=1` this does not happen, which indicates that it may be a race condition situation.

**Comment by tdrauncieal** [comment]
## AIX VM on linux x86 [success]

During testing an issue related to fluentd, I initially chose to use an AIX VM for said task and although I ultimately ended up using a Linux VM, during this process I was able to successfully create an AIX 7.2 VM.
specifically I used `quemu-system-ppc64` and followed this [tutorial](https://kwakousys.wordpress.com/2020/09/06/run-aix-7-2-on-x86-with-qemu/)

here a some output to see:
```shell
Last login: Sat Oct  7 08:18:04 CDT 2023 on /dev/pts/0 from 192.168.100.2                                                                                                                                          
*******************************************************************************                                                                                                                                    
*                                                                             *                                                                                                                                    
*                                                                             *                                                                                                                                    
*  Welcome to AIX Version 7.2!                                                *                                                                                                                                    
*                                                                             *                                                                                                                                    
*                                                                             *                                                                                                                                    
*  Please see the README file in /usr/lpp/bos for information pertinent to    *                                                                                                                                    
*  this release of the AIX Operating System.                                  *                                                                                                                                    
*                                                                             *                                                                                                                                    
*                                                                             *                                                                                                                                    
*******************************************************************************                                                                                                                                    
# shutdown                                                                                                                                                                                                         
                                                                                                                                                                                                                   
SHUTDOWN PROGRAM                                                                                                                                                                                                   
Sat Oct  7 08:18:45 CDT 2023                                                                                                                                                                                       

``` 

Another [tutorial](https://aix4admins.blogspot.com/2020/04/qemu-aix-on-x86-qemu-quick-emulator-is.html) that may be useful

**Comment by MarcelKemp** [comment]
I will keep the branch `16392-aix-build-fix` in the repository in case any other customer needs a manager for AIX.
