### ISSUE TITLE
Engine - Adapting the ruleset to the integration model

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#16457]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|5.0.0 | Engine | Manager | Packages/Sources | OS version |

## Description
Following our investigation of the issue https://github.com/wazuh/wazuh/issues/16261, we need to modify the engine ruleset to accommodate the new integration method.

To implement the changes proposed in the research problem, we must restructure the ruleset accordingly. In addition, we will need to develop several scripts that facilitate the creation of these integrations.

## Tasks
- Change the ruleset according to the proposed method of integration.
  - [x] Reorganized ruleset
  - [x] Update wazuh-internal integrations and wazuh-core integration 
- [x] Create a set of scripts to help in the creation of these integrations.
- [x] Create integrations endpoint
- [x] Rename environment to policy in code
- [x] Adapt OSSEC event parsing only to extract the fields specified by the protocol
- [x] Update and test the Vagrant 
- [ ] Update Documentation
- [ ] QA validate
