### ISSUE TITLE
Engine - Researching the replacement of rapidjson by nlohmann

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#16498]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|5.0.0 | Engine | Manager | Packages/Sources | OS version |

## Description
We need to conduct a study on changing the rapidjson library used in our engine to nlohmann, which is already used in other modules of Wazuh. We initially chose rapidjson for its speed and JSON validation, but we now believe that validation is unnecessary and want to perform performance tests to compare both libraries.

To make a fair evaluation, benchmarks will be conducted to measure the performance and features of both rapidjson and nlohmann. If nlohmann proves to be a better option in terms of performance and efficiency, we will switch to this library in our engine.

## Tasks
- [x] Study the incorporation of nlohmann
- [x] Create bechmarks to confront rapidjson with nlohmann
- [x] Replace the library if necessary
- [x] Update documentation

**Comment by nmkoremblum** [comment]
We were evaluating the possibility of replacing the JSON C++ library "Rapidjson" in the Wazuh Engine, as it has not had an official release for several years. Various sources were consulted, including:

- https://arxiv.org/pdf/1902.08318.pdf
- https://github.com/danielaparker/json_benchmarks/blob/master/report/performance.md
- https://github.com/simdjson/simdjson#performance-results
- https://github.com/miloyip/nativejson-benchmark
- https://github.com/mloskot/json_benchmark
- https://chadaustin.me/2013/01/json-parser-benchmarking/
  
In almost all cases, the Rapidjson library proved to be the fastest, except in some cases, such as string parsing, where "simdjson" performed much better. However, this library did not offer all the features required for use in the Engine. Although all the data indicated that there is no replacement that offers the same performance and features as Rapidjson, we decided to compare it with the JSON library Nlohmann, which is being used in other Wazuh modules. Nlohmann has the advantage of being actively maintained and easy to use for code development, although its design was not oriented towards performance, as its creator himself indicates in the following link: https://www.reddit.com/r/cpp/comments/9ss87p/comment/e8s1ixj. Despite this, some benchmarks of specific functionalities were performed, and as expected, it was observed that operations performed with Nlohmann took much longer than with Rapidjson, as seen in the following test result:

```
-----------------------------------------------------------------------------------
Benchmark                                         Time             CPU   Iterations
-----------------------------------------------------------------------------------
rapidjson_parse_minimal_bench                   261 ns          260 ns      2091370
nlohmann_parse_minimal_bench                   1749 ns         1742 ns       352595
rapidjson_parse_large_bench                  181926 ns       181678 ns         3410
nlohmann_parse_large_bench                  1889160 ns      1889137 ns          329
rapidjson_stringify_minimal_bench               258 ns          258 ns      2903055
nlohmann_stringify_minimal_bench                611 ns          611 ns      1113075
rapidjson_stringify_large_bench              139352 ns       139345 ns         4000
nlohmann_stringify_large_bench               386697 ns       386645 ns         1743
rapidjson_prettify_minimal_bench                264 ns          264 ns      2522254
nlohmann_prettify_minimal_bench                 680 ns          679 ns       965197
rapidjson_prettify_large_bench               190160 ns       190151 ns         2887
nlohmann_prettify_large_bench                493131 ns       493065 ns         1377
rapidjson_field_modifying_minimal_bench        21.5 ns         21.5 ns     28125768
nlohmann_field_modifying_minimal_bench          205 ns          205 ns      3191063
rapidjson_field_modifying_large_bench          29.4 ns         29.4 ns     23188504
nlohmann_field_modifying_large_bench            236 ns          236 ns      2844097
rapidjson_get_string_field_minimal_bench       22.6 ns         22.6 ns     25208958
nlohmann_get_string_field_minimal_bench         226 ns          226 ns      2802426
rapidjson_get_string_field_large_bench         24.8 ns         24.8 ns     25239268
nlohmann_get_string_field_large_bench           263 ns          263 ns      2566024
rapidjson_erase_field_minimal_bench            1.92 ns         1.92 ns    348935532
nlohmann_erase_field_minimal_bench             10.2 ns         10.2 ns     69704415
rapidjson_erase_field_large_bench              6.16 ns         6.15 ns    106881172
nlohmann_erase_field_large_bench               63.0 ns         63.0 ns     11508931
rapidjson_add_kv_pair_minimal_bench            82.2 ns         82.2 ns     11971698
nlohmann_add_kv_pair_minimal_bench              271 ns          253 ns      2196654
rapidjson_add_kv_pair_large_bench              55.8 ns         55.8 ns     11419844
nlohmann_add_kv_pair_large_bench                285 ns          285 ns      2561266
```

The fact that individual operations differed significantly in their execution time did not necessarily mean that their contribution was significant in the total end-to-end operations of the Engine. Because estimating their contribution was too complex, we decided to completely replace one library with the other and compare the number of events that each implementation was capable of processing. The following was obtained:

Glossary:
- `KVDB empty`: The database has no information from any agents.
- `KVDB full`: The database has information from logging agents (it has more registered agents than reporting agents).
- `Remote`: Logs without agent ID.
- `Agent`: Logs with agent ID.
- `Dummy`: Logs that are not accepted by any decoder (except the most primitive ones).
- `Enrich`: Events that fill the database with information from agents.

|RAPIDJSON| | | | | | | | | |
|:----|:----|:----|:----|:----|:----|:----|:----|:----|:----|
|KVDB state|KVDB empty|KVDB empty|KVDB empty|KVDB empty|KVDB full|KVDB full|KVDB full|KVDB full||
|Logs|Remote|Agent|Dummy|Enrich|Remote|Agent|Dummy|Enrich|SUMMARY|
|Events sent|313000|321000|829465|1380276|316000|311000|806225|1355271|5632237|
|Events lost|0|0|0|272|0|0|0|267|539|
|Events processed|313000|321000|829465|1380004|316000|311000|806225|1355004|5631698|
|Elapsed time (s)|120.99|120.96|120.03|120.94|120.35|121.02|120.05|121.08|965.420369|
|EPS|2587|2654|6910|11411|2626|2570|6716|11191|5833|
|Relative difference|18%|19%|13%|69%|18%|18%|19%|67%|40%|

|NLOHMANN| | | | | | | | | |
|:----|:----|:----|:----|:----|:----|:----|:----|:----|:----|
|KVDB state|KVDB empty|KVDB empty|KVDB empty|KVDB empty|KVDB full|KVDB full|KVDB full|KVDB full||
|Logs|Remote|Agent|Dummy|Enrich|Remote|Agent|Dummy|Enrich|SUMMARY|
|Events sent|266000|269000|734300|610122|269000|263000|678265|815163|3904850|
|Events lost|0|0|0|119|0|0|0|159|278|
|Events processed|266000|269000|734300|610003|269000|263000|678265|815004|3904572|
|Elapsed time (s)|120.98|120.58|120.05|90.60|120.89|121.20|120.08|121.59|935.970389|
|EPS|2199|2231|6116|6733|2225|2170|5648|6703|4172|
|Relative difference|-15%|-16%|-11%|-41%|-15%|-16%|-16%|-40%|-28%|

It can be observed that, in general, performance is degraded by approximately 30% when using the Nlohmann library.

Given this, for now, we have decided to continue using the Rapidjson library.

**Comment by JcabreraC** [comment]
Since the performance of `nlohmann` is not as expected, we will keep the `rapidjson` library in the engine.

**Comment by Ben137KBC** [comment]
We also used RapidJSON and its speed it amazing, the best for sure. However, it is no longer maintained, no updates for years, and no CVE's are getting addressed. So we ended up switching to nlohmann json. It is slower, but the code migration can be done correctly by AI, and it is actively maintained.

**Comment by nische** [comment]
In our new Core Codebase we use "glaze". We use it because of some cool Features for json-schema but it should be quit fast too. 
Did anybody has experiance with Glaze?
