### ISSUE TITLE
Refactor NVD feeds to use NVD API 2.0 feeds

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#16555]
|Wazuh version|Component|Install type|Platform|
|---|---|---|---|
| All | Vulnerability Detector | Manager | All |

## Description

Due to the notice issued by NIST about the deprecation and retirement of all its legacy feeds in the NVD by September 2023, it is necessary to apply changes to the Vulnerability Detector module to make use of the NVD API, and to remove the current feeds to avoid future problems.

> In the following link, you can find more information about the notice: https://nvd.nist.gov/vuln/data-feeds

As there is a difference between the JSON schema of the legacy feeds and the NVD API 2.0 feeds, changes to the Vulnerability Detector code are required to make it work correctly.

## NVD API 2.0 Considerations

We have to take into account that there is a rate limit for the number of requests that can be made to the API. So there are two limits depending on whether we have an API key or not:
- Rate limit without an API key: 5 requests in a rolling 30-second window.
- Rate limit with an API key: 50 requests in a rolling 30-second window.
> NIST recomendation: Application need to sleeps for several seconds between requests so that legitimate requests are not denied, and all requests are responded to in sequence.

Knowing these rate limits, we also have to take into account that for the vulnerability feed download, the maximum number of results (CVEs) that can be requested is 2000 (and currently the full feed has ~211000 results), so the first download of the full NVD feed without API key (which would happen if we add it in the VDT code so that the module downloads the feeds through the API), could take around 53 minutes.
However, to update the feed data, according to NIST, it would only be necessary to make a request every 2h, so it would never reach the API rate limit.
> More info: https://nvd.nist.gov/developers/start-here#

Below, I share the link to obtain an API key:
- https://nvd.nist.gov/developers/request-an-api-key

## Procedure

1. Research about the changes needed in the module to make use of the new NVD API 2.0 feed.
   - Managing the download of the new feeds via the API. Decide whether to add API calls in the code or generate a feed that we update (automatically if possible) and provide the link for direct download.
   - Comparison between legacy feeds vs NVD API 2.0 feeds (CVEs and CPEs).
   - Analysis of the current NVD Vulnerability Detector code.

2. Develop the necessary changes to support NVD API 2.0 feeds.
   - Modify the NVD feed download code + configuration, according to the decision made above. Download feeds via API + management in Vulnerability Detector. 
   - Adapt the NVD parser for the new feed. Modify current tags, add new tags if important (or necessary) and remove deprecated tags.
   - Insert the parsed data into the DB and check that the content is similar or better than what we used for the legacy feeds.
   - Review and deprecate code that is unusable due to the switch of feed.

3. Testing to verify that Vulnerability Detector is working correctly.
   - Check that all supported OSes work correctly with the change.
   - Compare results between legacy feeds (before changes) and NVD API 2.0 feeds.
   - Add or modify custom feeds for NVD.
   - Check that there are no memory issues or bugs.

Extra considerations: Documentation, ITs, UTs, Jenkins, other repository configurations...

### List of issues:
- [x] https://github.com/wazuh/wazuh/issues/16661
- [x] https://github.com/wazuh/wazuh-tools/issues/224
- [x] https://github.com/wazuh/wazuh/issues/17055
- [x] https://github.com/wazuh/wazuh/issues/17308 (+ insert feeds)
- [x] Manual testing: https://github.com/wazuh/wazuh/issues/17746
- [x] ITs: https://github.com/wazuh/wazuh-qa/issues/4275
---
- [x] Jenkins: https://github.com/wazuh/wazuh-jenkins/issues/5219
- [x] Documentation: https://github.com/wazuh/wazuh-documentation/issues/6218
- [ ] Other repository configurations: 
  - [ ] https://github.com/wazuh/wazuh-qa/issues/4302
  - [x] https://github.com/wazuh/wazuh-puppet/issues/706
  - [ ] https://github.com/wazuh/wazuh/issues/17983
---
- Performance issue: 
  - [x] https://github.com/wazuh/wazuh/issues/17968

**Comment by vikman90** [comment]
Due to the taking over of the https://github.com/wazuh/wazuh-jenkins/issues/5219 responsibility, we need to extend the ETA by one week.
