### ISSUE TITLE
`wazuh-syscheckd` generates an error of mount files of snapd 

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh#16611]
## Description

Apparently, a new error has been found in the testing for Release 4.4.1-RC1 related to `wazuh-syscheckd`, in the Ubuntu agent of the stress test: https://github.com/wazuh/wazuh/issues/16577

The error is:
```
19:55:45 wazuh-syscheckd: ERROR: (6704): Couldn't get path of '/etc/systemd/system/multi-user.target.wants/snap-snapd-14295.mount'
19:55:48 wazuh-syscheckd: ERROR: (6704): Couldn't get path of '/etc/systemd/system/snap-snapd-14295.mount'
```

This error is displayed only once.

## Task

It's necessary to determine if this error is generated by the behavior of the stress test or not.

- [ ] Investigate the error.
- [ ] Fix the error.
- [ ] Validate the fix.

## Validation

- [ ] The error is not displayed anymore, in case it is not an error of the stress test.

**Comment by vikman90** [comment]
Hi! This issue seems to be a bug, but it cannot have been introduced in 4.4.1 since no agent code has been changed.

So, I'm marking this issue as a bug to be fixed soon.
