### ISSUE TITLE
Review Logging package to test integration to be used as the logging method of external integrations

### ISSUE THREAD

**Issue by EduLeon12** [wazuh/wazuh#16619]
| Affected integration |
|---|
| All External Integrations|

## Description

 As described in #14535, An improvement in the way that cloud integration outputs the data to the ossecs log needs to be done.

 Logging package provides all necessary tools to improve the way the output is being shown and to divide all output into the necessary levels to provide the most information possible.

 This package needs to be tested to analyze possible integration to standardize the way output is being handled through all cloud integration.

 This test consists of trying the package and testing how the core part behaves when the integration module logs data using this package.

## Tasks
- [x] Test in a manager.
- [x] Test in an agent.
- [x] Unit tests without failures. Updated if there are any relevant changes.
- [x] Integration tests without failures. Updated if there are any relevant changes.
- [x] Update the documentation if necessary.
- [x] Add entry to the changelog if necessary.

**Comment by EduLeon12** [comment]
## Issue Update

After discussing with the team and unifying issues that have the same impact and same main problem, therefore, same solutions we conclude that 3 different integration modules will be tested and log format will be used to conclude how the package affects current integration and how will it need to be changed to comply to every logging level.


- [x] External integration test #16624.
- [ ] Cloud integration #16314. 

2 possible solutions are being analyzed at the current moment.
- One Minor 
- One Mayor

Once we have the logs of the mentioned integrations they will be proposed to the team.

**Comment by EduLeon12** [comment]
# Issue Update 

## GCP 

- Ossec conf used 

```
  <gcp-pubsub>
     <pull_on_start>yes</pull_on_start>
     <interval>1m</interval>
     <project_id>********</project_id>
     <subscription_name>************</subscription_name>
     <num_threads>4</num_threads>
     <max_messages>50</max_messages>
     <credentials_file>/var/ossec/wodles/gcloud/credentials.json</credentials_file>
 </gcp-pubsub>

```

### Current behavior
 
No logs are shown in ossec.log since the current debug level is 0

Output:

```
2023/04/11 20:09:08 wazuh-modulesd:gcp-pubsub: INFO: Module started.
```

- When debug level is set to 2:

```
2023/04/11 20:21:36 wazuh-modulesd:gcp-pubsub[217701] wm_gcp.c:346 at wm_gcp_parse_output(): DEBUG: Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"insertId":"fth19if13l9t5","logName":"projects/wazuh-dev-258815/logs/cloudaudit.googleapis.com%2Fdata_access","protoPayload":{"@type":"type.googleapis.com/google.cloud.audit.AuditLog","authenticationInfo":{"principalEmail":"facundo.dalmau@wazuh.com","principalSubject":"user:facundo.dalmau@wazuh.com"},"authorizationInfo":[{"granted":true,"permission":"monitoring.timeSeries.list","resource":"769054035614","resourceAttributes":{}}],"methodName":"google.monitoring.v3.QueryService.QueryTimeSeries","numResponseItems":"8","request":{"@type":"type.googleapis.com/google.monitoring.v3.QueryTimeSeriesRequest","name":"projects/wazuh-dev-258815","query":"\\nfetch pubsub_topic\\n| metric \'pubsub.googleapis.com/topic/send_request_count\'\\n| filter resource.project_id == \'wazuh-dev-258815\'\\n| align rate(1m)\\n| every 1m\\n| group_by 1m,\\n[value_send_request_count_sum: sum(value.send_request_count)]"},"requestMetadata":{"callerIp":"181.47.46.56","callerSuppliedUserAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36,gzip(gfe)","destinationAttributes":{},"requestAttributes":{"auth":{},"time":"2023-04-11T20:20:59.168175168Z"}},"resourceName":"projects/wazuh-dev-258815","serviceName":"monitoring.googleapis.com"},"receiveTimestamp":"2023-04-11T20:21:00.414223972Z","resource":{"labels":{"method":"google.monitoring.v3.QueryService.QueryTimeSeries","project_id":"wazuh-dev-258815","service":"monitoring.googleapis.com"},"type":"audited_resource"},"severity":"INFO","timestamp":"2023-04-11T20:20:59.158646349Z"}}'"
2023/04/11 20:21:36 wazuh-modulesd:gcp-pubsub[217701] wm_gcp.c:352 at wm_gcp_parse_output(): INFO: Received and acknowledged 3 messages
2023/04/11 20:21:36 wazuh-modulesd:gcp-pubsub[217701] wm_gcp.c:151 at wm_gcp_pubsub_main(): DEBUG: Fetching logs finished.
2023/04/11 20:21:36 wazuh-modulesd:gcp-pubsub[217701] wm_gcp.c:143 at wm_gcp_pubsub_main(): DEBUG: Sleeping until: 2023/04/11 20:22:15
```

### Logging package

Currently trying to see the logs on the ossec.log after integrating the logging package

Next steps: 
- [ ] Troubleshoot module.

**Comment by EduLeon12** [comment]
# Update 

### Logging package integrated

- ossec.log:

```
2023/04/12 14:30:56 wazuh-modulesd:gcp-pubsub[217701] wm_gcp.c:352 at wm_gcp_parse_output(): INFO: This is a info message on the ossec.log
```

**Comment by EduLeon12** [comment]
## AWS

- ossec.conf used:


```
  <wodle name="aws-s3">
    <disabled>no</disabled>
    <remove_from_bucket>no</remove_from_bucket>
    <interval>10m</interval>
    <run_on_start>yes</run_on_start>
    <skip_on_error>no</skip_on_error>


    <bucket type="cloudtrail">
        <aws_profile>dev</aws_profile>
        <name>wazuh-aws-wodle-cloudtrail</name>
        <only_logs_after>2022-MAR-21</only_logs_after>
    </bucket>


    <bucket type="custom">
        <aws_profile>dev</aws_profile>
        <name>wazuh-aws-wodle-macie</name>
        <only_logs_after>2022-JAN-01</only_logs_after>
    </bucket>

</wodle>

```

### Current behavior

Not much information is shown to understand the error since debug level is not 2

Output:

```
root@wazuh-master:/var/ossec# cat logs/ossec.log | grep 'aws'
2023/04/12 14:51:15 wazuh-modulesd:aws-s3: INFO: Module AWS started
2023/04/12 14:51:15 wazuh-modulesd:aws-s3: INFO: Starting fetching of logs.
2023/04/12 14:51:15 wazuh-modulesd:aws-s3: INFO: Executing Bucket Analysis: (Bucket: wazuh-aws-wodle-cloudtrail, Type: cloudtrail, Profile: dev)
2023/04/12 14:51:15 wazuh-modulesd:aws-s3: WARNING: Bucket:  -  Returned exit code 12
```


- Debug level set to 2

```
2023/04/12 15:44:05 wazuh-modulesd:aws-s3[585275] wm_aws.c:444 at wm_aws_run_s3(): DEBUG: Launching S3 Command: wodles/aws/aws-s3 --bucket wazuh-aws-wodle-macie --aws_profile dev --only_logs_after 2022-JAN-01 --type custom --debug 2
2023/04/12 15:44:05 wazuh-modulesd:aws-s3[585275] wm_aws.c:458 at wm_aws_run_s3(): WARNING: Bucket:  -  Returned exit code 1
2023/04/12 15:44:05 wazuh-modulesd:aws-s3[585275] wm_aws.c:462 at wm_aws_run_s3(): WARNING: Bucket:  -  Unknown error.
2023/04/12 15:44:05 wazuh-modulesd:aws-s3[585275] wm_aws.c:482 at wm_aws_run_s3(): DEBUG: Bucket:  -  OUTPUT:   File "/var/ossec/wodles/aws/aws-s3.py", line 308
2023/04/12 15:44:05 wazuh-modulesd:aws-s3[585275] wm_aws.c:174 at wm_aws_main(): INFO: Fetching logs finished.
2023/04/12 15:44:05 wazuh-modulesd:aws-s3[585275] wm_aws.c:78 at wm_aws_main(): DEBUG: Sleeping until: 2023/04/12 15:54:05
```

### Logging package integrated

-

**Comment by EduLeon12** [comment]
# Conclusion

Based on the Logging behavior described in #14535 and the test performed in this issue, a new issue  [#16717
](https://github.com/wazuh/wazuh/issues/16717) has been opened.

Logging package is possible to integrate since some modules already logs data using them, the issue was opened to see possibility to adapt all integrations to a single logging method following the same format.

**Comment by GGP1** [comment]
## Review

Although there is not much information about the investigation in this issue, the analysis and solutions proposed in the ones related, improve significantly the current logging state of external integrations. 

A presentation has taken place to explain the solution and discuss with the team, concluding that we could start the minor stage of the development, while the major depending on external factors and potentially not taking place.

I consider that the investigation has been successful and the objective of the issue has been met. LGTM
