### ISSUE TITLE
Research NVD API 2.0 feeds

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#16661]
## Description

Research about the changes needed in the module to make use of the new NVD API 2.0 feed.
- Managing the download of the new feeds via the API. Decide whether to add API calls in the code or generate a feed that we update (automatically if possible) and provide the link for direct download.
- Comparison between legacy feeds vs NVD API 2.0 feeds (CVEs and CPEs).
- Analysis of the current NVD Vulnerability Detector code.

### Tasks:
- [ ] Find the best alternative for fetching feeds with VD.
- [ ] Legacy feeds vs NVD API 2.0 feeds.
- [ ] Check for new variables in the feed and see if they need to be added to the code.
- [ ] Check all NVD feed functions in VD and determine whether they need to be changed.

**Comment by MarcelKemp** [comment]
### Fetch NVD feeds
To avoid problems of limitations in the first download of the feed, we intend to do the following:
- First, we are going to create a script to generate a first complete feed of the NVD (one feed for the CVEs and another for the CPEs) that will be uploaded to our URL: https://feed.wazuh.com/vulnerability-detector/
- It will be necessary to create the Jenkins pipeline to automatically update both feeds, using the generated script.
- Once we have the complete feed, we will modify the Vulnerability Detector code to download the feeds and start parsing them.

**Comment by MarcelKemp** [comment]
### Feeds comparison
A comparison has been made between the legacy feeds vs. the new, NVD API 2.0 feeds:

<details><summary>

### CVE feeds comparison</summary>

<details open><summary>

#### Mapping
</summary>

```
CVE_Items.cve.data_type     -> NULL
CVE_Items.cve.data_format       -> NULL
CVE_Items.cve.data_version       -> NULL
CVE_Items.cve.CVE_data_meta.ID      -> vulnerabilities.cve.id
CVE_Items.cve.CVE_data_meta.ASSIGNER        -> vulnerabilities.cve.weaknesses.source
CVE_Items.cve.problemtype.problemtype_data.description.lang     ->  vulnerabilities.cve.descriptions.lang
CVE_Items.cve.problemtype.problemtype_data.description.value        -> vulnerabilities.cve.descriptions.value
CVE_Items.cve.references        -> vulnerabilities.cve.references
CVE_Items.cve.references.reference_data.url     -> vulnerabilities.cve.references.url
CVE_Items.cve.references.reference_data.name        -> NULL
CVE_Items.cve.references.reference_data.refsource       -> vulnerabilities.cve.references.source
CVE_Items.cve.references.reference_data.tags        -> vulnerabilities.cve.references.tags
CVE_Items.cve.description       -> vulnerabilities.cve.descriptions
CVE_Items.cve.description.description_data      -> NULL
CVE_Items.cve.description.description_data.lang     -> vulnerabilities.cve.descriptions.lang
CVE_Items.cve.description.description_data.value        -> vulnerabilities.cve.descriptions.value
CVE_Items.cve.configurations        -> vulnerabilities.cve.configurations
CVE_Items.cve.configurations.CVE_data_version       -> NULL
CVE_Items.cve.configurations.nodes      -> vulnerabilities.cve.configurations.nodes
CVE_Items.cve.configurations.nodes.operator     -> vulnerabilities.cve.configurations.nodes.operator
CVE_Items.cve.configurations.nodes.children     -> NULL
CVE_Items.cve.configurations.nodes.cpe_match        -> vulnerabilities.cve.configurations.nodes.cpeMatch
CVE_Items.cve.configurations.nodes.cpe_match.vulnerable     -> vulnerabilities.cve.configurations.nodes.cpeMatch.vulnerable
CVE_Items.cve.configurations.nodes.cpe_match.cpe23Uri       -> vulnerabilities.cve.configurations.nodes.cpeMatch.criteria
CVE_Items.cve.configurations.nodes.cpe_match.cpe_name       -> NULL
CVE_Items.cve.impact -> vulnerabilities.cve.metrics
CVE_Items.cve.impact.baseMetricVX       -> vulnerabilities.cve.metrics.cvssMetricVX
CVE_Items.cve.impact.baseMetricVX.cvssVX        -> vulnerabilities.cve.metrics.cvssMetricVX.cvssData
CVE_Items.cve.impact.baseMetricVX.cvssVX.version        ->  vulnerabilities.cve.metrics.cvssMetricVX.cvssData.version
CVE_Items.cve.impact.baseMetricVX.cvssVX.vectorString       ->  vulnerabilities.cve.metrics.cvssMetricVX.cvssData.vectorString
CVE_Items.cve.impact.baseMetricVX.cvssVX.attackVector       ->  vulnerabilities.cve.metrics.cvssMetricVX.cvssData.attackVector
CVE_Items.cve.impact.baseMetricVX.cvssVX.attackComplexity       ->  vulnerabilities.cve.metrics.cvssMetricVX.cvssData.attackComplexity
CVE_Items.cve.impact.baseMetricVX.cvssVX.privilegesRequired     -> vulnerabilities.cve.metrics.cvssMetricVX.cvssData.privilegesRequired
CVE_Items.cve.impact.baseMetricVX.cvssVX.userInteraction        -> vulnerabilities.cve.metrics.cvssMetricVX.cvssData.userInteraction
CVE_Items.cve.impact.baseMetricVX.cvssVX.scope      -> vulnerabilities.cve.metrics.cvssMetricVX.cvssData.scope
CVE_Items.cve.impact.baseMetricVX.cvssVX.confidentialityImpact      -> vulnerabilities.cve.metrics.cvssMetricVX.cvssData.confidentialityImpact
CVE_Items.cve.impact.baseMetricVX.cvssVX.integrityImpact        -> vulnerabilities.cve.metrics.cvssMetricVX.cvssData.integrityImpact
CVE_Items.cve.impact.baseMetricVX.cvssVX.availabilityImpact     -> vulnerabilities.cve.metrics.cvssMetricVX.cvssData.availabilityImpact
CVE_Items.cve.impact.baseMetricVX.cvssVX.baseScore      -> vulnerabilities.cve.metrics.cvssMetricVX.cvssData.baseScore
CVE_Items.cve.impact.baseMetricVX.cvssVX.baseSeverity       -> vulnerabilities.cve.metrics.cvssMetricVX.cvssData.baseSeverity
CVE_Items.cve.impact.baseMetricVX.exploitabilityScore       -> vulnerabilities.cve.metrics.cvssMetricVX.exploitabilityScore
CVE_Items.cve.impact.baseMetricVX.impactScore       -> vulnerabilities.cve.metrics.cvssMetricVX.impactScore
CVE_Items.cve.impact.baseMetricVX.impactScore  -> NULL
CVE_Items.cve.impact.baseMetricVX.severity -> NULL
CVE_Items.cve.impact.baseMetricVX.exploitabilityScore  -> vulnerabilities.cve.metrics.cvssMetricVX.exploitabilityScore
CVE_Items.cve.impact.baseMetricVX.impactScore  -> vulnerabilities.cve.metrics.cvssMetricVX.impactScore
CVE_Items.cve.impact.baseMetricVX.acInsufInfo  -> NULL
CVE_Items.cve.impact.baseMetricVX.obtainAllPrivilege  -> NULL
CVE_Items.cve.impact.baseMetricVX.obtainUserPrivilege  -> NULL
CVE_Items.cve.impact.baseMetricVX.obtainOtherPrivilege  -> NULL
CVE_Items.cve.impact.baseMetricVX.userInteractionRequired  -> NULL
CVE_Items.cve.impact.publishedDate      -> vulnerabilities.cve.published
CVE_Items.cve.impact.lastModifiedDate       -> vulnerabilities.cve.lastModified
```
</details>

<details><summary>

#### Legacy CVE feed
</summary>

```
CVE_Items.cve.data_type
CVE_Items.cve.data_format
CVE_Items.cve.data_version
CVE_Items.cve.CVE_data_meta
CVE_Items.cve.CVE_data_meta.ID
CVE_Items.cve.CVE_data_meta.ASSIGNER
CVE_Items.cve.problemtype
CVE_Items.cve.problemtype.problemtype_data
CVE_Items.cve.problemtype.problemtype_data.description
CVE_Items.cve.problemtype.problemtype_data.description.lang
CVE_Items.cve.problemtype.problemtype_data.description.value
CVE_Items.cve.references
CVE_Items.cve.references.reference_data
CVE_Items.cve.references.reference_data.url
CVE_Items.cve.references.reference_data.name
CVE_Items.cve.references.reference_data.refsource
CVE_Items.cve.references.reference_data.tags
CVE_Items.cve.description
CVE_Items.cve.description.description_data
CVE_Items.cve.description.description_data.lang
CVE_Items.cve.description.description_data.value
CVE_Items.cve.configurations
CVE_Items.cve.configurations.CVE_data_version
CVE_Items.cve.configurations.nodes
CVE_Items.cve.configurations.nodes.operator
CVE_Items.cve.configurations.nodes.children
CVE_Items.cve.configurations.nodes.cpe_match
CVE_Items.cve.configurations.nodes.cpe_match.vulnerable
CVE_Items.cve.configurations.nodes.cpe_match.cpe23Uri
CVE_Items.cve.configurations.nodes.cpe_match.cpe_name
CVE_Items.cve.impact
CVE_Items.cve.impact.baseMetricVX
CVE_Items.cve.impact.baseMetricVX.cvssVX
CVE_Items.cve.impact.baseMetricVX.cvssVX.version
CVE_Items.cve.impact.baseMetricVX.cvssVX.vectorString
CVE_Items.cve.impact.baseMetricVX.cvssVX.attackVector
CVE_Items.cve.impact.baseMetricVX.cvssVX.attackComplexity
CVE_Items.cve.impact.baseMetricVX.cvssVX.privilegesRequired
CVE_Items.cve.impact.baseMetricVX.cvssVX.userInteraction
CVE_Items.cve.impact.baseMetricVX.cvssVX.scope
CVE_Items.cve.impact.baseMetricVX.cvssVX.confidentialityImpact
CVE_Items.cve.impact.baseMetricVX.cvssVX.integrityImpact
CVE_Items.cve.impact.baseMetricVX.cvssVX.availabilityImpact
CVE_Items.cve.impact.baseMetricVX.cvssVX.baseScore
CVE_Items.cve.impact.baseMetricVX.cvssVX.baseSeverity
CVE_Items.cve.impact.baseMetricVX.exploitabilityScore
CVE_Items.cve.impact.baseMetricVX.impactScore
CVE_Items.cve.impact.baseMetricVX.severity
CVE_Items.cve.impact.baseMetricVX.exploitabilityScore
CVE_Items.cve.impact.baseMetricVX.impactScore
CVE_Items.cve.impact.baseMetricVX.acInsufInfo
CVE_Items.cve.impact.baseMetricVX.obtainAllPrivilege
CVE_Items.cve.impact.baseMetricVX.obtainUserPrivilege
CVE_Items.cve.impact.baseMetricVX.obtainOtherPrivilege
CVE_Items.cve.impact.baseMetricVX.userInteractionRequired
CVE_Items.cve.impact.publishedDate
CVE_Items.cve.impact.lastModifiedDate
```
</details>

<details><summary>

#### NVD API 2.0 CVE feed
</summary>

```
vulnerabilities.cve
vulnerabilities.cve.id
vulnerabilities.cve.sourceIdentifier
vulnerabilities.cve.published
vulnerabilities.cve.lastModified
vulnerabilities.cve.vulnStatus
vulnerabilities.cve.descriptions
vulnerabilities.cve.descriptions.lang
vulnerabilities.cve.descriptions.value
vulnerabilities.cve.metrics
vulnerabilities.cve.metrics.cvssMetricVX
vulnerabilities.cve.metrics.cvssMetricVX.source
vulnerabilities.cve.metrics.cvssMetricVX.type
vulnerabilities.cve.metrics.cvssMetricVX.cvssData
vulnerabilities.cve.metrics.cvssMetricVX.cvssData.version
vulnerabilities.cve.metrics.cvssMetricVX.cvssData.vectorString
vulnerabilities.cve.metrics.cvssMetricVX.cvssData.attackVector
vulnerabilities.cve.metrics.cvssMetricVX.cvssData.attackComplexity
vulnerabilities.cve.metrics.cvssMetricVX.cvssData.privilegesRequired
vulnerabilities.cve.metrics.cvssMetricVX.cvssData.userInteraction
vulnerabilities.cve.metrics.cvssMetricVX.cvssData.scope
vulnerabilities.cve.metrics.cvssMetricVX.cvssData.confidentialityImpact
vulnerabilities.cve.metrics.cvssMetricVX.cvssData.integrityImpact
vulnerabilities.cve.metrics.cvssMetricVX.cvssData.availabilityImpact
vulnerabilities.cve.metrics.cvssMetricVX.cvssData.baseScore
vulnerabilities.cve.metrics.cvssMetricVX.cvssData.baseSeverity
vulnerabilities.cve.metrics.cvssMetricVX.exploitabilityScore
vulnerabilities.cve.metrics.cvssMetricVX.impactScore
vulnerabilities.cve.weaknesses
vulnerabilities.cve.weaknesses.source
vulnerabilities.cve.weaknesses.type
vulnerabilities.cve.weaknesses.description
vulnerabilities.cve.weaknesses.description.lang
vulnerabilities.cve.weaknesses.description.value
vulnerabilities.cve.configurations
vulnerabilities.cve.configurations.nodes
vulnerabilities.cve.configurations.nodes.operator
vulnerabilities.cve.configurations.nodes.negate
vulnerabilities.cve.configurations.nodes.cpeMatch
vulnerabilities.cve.configurations.nodes.cpeMatch.vulnerable
vulnerabilities.cve.configurations.nodes.cpeMatch.criteria
vulnerabilities.cve.configurations.nodes.cpeMatch.matchCriteriaId
vulnerabilities.cve.references
vulnerabilities.cve.references.url
vulnerabilities.cve.references.source
vulnerabilities.cve.references.tags
```
</details>

</details>

<details><summary>

### CPE feeds comparison</summary>

<details open><summary>

#### Mapping
</summary>

```
cpe-list -> products
cpe-item.name -> products.cpe.cpeName
title -> products.cpe.titles.title
references.reference -> NULL
cpe-23:cpe23-item.name -> products.cpe.cpeName
```
</details>

<details><summary>

#### Legacy CVE feed
</summary>

```
cpe-list
cpe-item.name
title
references.reference
cpe-23:cpe23-item.name
```
</details>

<details><summary>

#### NVD API 2.0 CVE feed
</summary>

```
products
products.cpe
products.cpe.deprecated
products.cpe.cpeName
products.cpe.cpeNameId
products.cpe.lastModified
products.cpe.created
products.cpe.titles
products.cpe.titles.title
products.cpe.titles.lang
```
</details>

</details>

**Comment by mateocervilla** [comment]
## Fetch NVD CPE feeds

Investigating about the CPE feeds, we found that the hardcoded URL is used only within the `wm_vuldet_fetch_nvd_cpe()` function.


https://github.com/wazuh/wazuh/blob/1f5418d59a6c27a7a8dd534d4ccc2a3f2fb239eb/src/wazuh_modules/vulnerability_detector/wm_vuln_detector.h#L71

https://github.com/wazuh/wazuh/blob/1f5418d59a6c27a7a8dd534d4ccc2a3f2fb239eb/src/wazuh_modules/vulnerability_detector/wm_vuln_detector_nvd.c#L837-L840


And said function is only called when `update->dist_ref` equals to `FEED_CPED`

https://github.com/wazuh/wazuh/blob/1f5418d59a6c27a7a8dd534d4ccc2a3f2fb239eb/src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c#L5191-L5195

This macro was only used before as can be seen here:

https://github.com/wazuh/wazuh/blob/f44ad56ac3250b404e885df7ad54d1149a7856f2/src/config/wmodules-vuln-detector.c#L176-L180

But it was deprecated (commented) in commit https://github.com/wazuh/wazuh/commit/07de520096e1171719bc0a50e17db02aa3bea3b1 and later deleted in commit https://github.com/wazuh/wazuh/commit/a20fcbdbd3886d797141196071378bf6c61bdfa5

In conclusion, the re-implementation for the CPE dictionary of the NVD API 2.0 will not be required, since the necessary related information is taken from the CVE feed and the CPE helper.
