### ISSUE TITLE
Engine - Automate PR tests with Github Actions

### ISSUE THREAD

**Issue by nbertoldo** [wazuh/wazuh#16685]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0.0 | Engine| Manager | Packages/Sources | OS version |

## Description
In order to improve quality and speed up the engine development process, it is required to automate unit tests in the PRs by leveraging the advantages of GitHub Actions.

## Tasks
- [ ] Investigate how to automate tests with GitHub Actions
- [ ] Create a GitHub Actions workflow and test it in a test repository
- [ ] Replicate workflow in the engine repository
- [ ] Update Documentation
