### ISSUE TITLE
Update changelog and bump version

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#16693]
The goals are:
- [X] Fix a typo in the changelog.
- [X] Update the latest versions' date.
- [X] Bump version to 4.4.2.
- [X] Merge 4.4.2 into 4.4.
- [x] Change the base branch in PRs pointing to 4.4.2.
- [x] Delete branch 4.4.2.
- [ ] Merge branches 4.4 → 4.5 → master.
- [x] Bump external dependencies versions.
- [x] Bump external dependencies versions in AWS.

### Subtasks

- https://github.com/wazuh/wazuh-qa/issues/4089
- https://github.com/wazuh/wazuh-packages/issues/2157

**Comment by davidjiglesias** [comment]
The merge from 4.5 to master could not be completed because there are some failing checks in PR_wazuh that are currently being worked on. We will attempt again and update the current branch in the next update issue.
