### ISSUE TITLE
Engine - Develop an agent simulator script 

### ISSUE THREAD

**Issue by LucioDonda** [wazuh/wazuh#16695]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0.0 | Engine | Manager | Packages/Sources | OS version |

## Description
We need to develop a script that allows us to recreate all the available types of messages received by the engine. It must be able to be connected to the already available script (**write_message.go**) to send it through the proper socket in order to feed the engine itself.

The user will be able to define the sources and type of messages to send, define the base of the event and any additional field that the event requires.

## Tasks
- [ ] List all the available events sources and types.
- [ ] Create script, output must be accepted by engine as valid event.
- [ ] Test several cases adding template of base events.
- [ ] Document usage.

**Comment by LucioDonda** [comment]
Basic execution on first approach:
╰─# python3 agent_simulator.py -h                                                                                                                                                    
```
usage: agent_simulator.py [-h] [-m MODULE] [-s SOURCE] [-i AGENT_ID] [-n AGENT_NAME] [-a AGENT_IP] [-p FILE_PATH] [-l LABELS] {create_and_send,create_event} ...

positional arguments:
  {create_and_send,create_event}

optional arguments:
  -h, --help            show this help message and exit
  -m MODULE, --module MODULE
                        Module of events
  -s SOURCE, --source SOURCE
                        Source of events
  -i AGENT_ID, --agent-id AGENT_ID
                        Agent ID for event filling
  -n AGENT_NAME, --agent-name AGENT_NAME
                        Agent name for events filling
  -a AGENT_IP, --agent-ip AGENT_IP
                        Agent ip address for events filling
  -p FILE_PATH, --file_path FILE_PATH
                        filepath for localfile
  -l LABELS, --labels LABELS
                        labels added to localfile event

```

Generating logcollector syslog:
```
╰─# python3 agent_simulator.py -s "logcollector" -m "syslog" -i "123" -n "centosVM" -a "192.168.1.2"   create_and_send                                                                                         1 ↵
1:[123] (centosVM) 192.168.1.2->syslog:Apr 17 15:54:17 centosVM systemd[1]: cgroup compatibility translation between legacy and unified hierarchy settings
1:[123] (centosVM) 192.168.1.2->syslog:Apr 14 17:05:01 centosVM CRON[7628]: pam_unix(cron:session): session opened for user root by (uid=0)
not yet implemented, meanwhile saving it to file

```

**Comment by LucioDonda** [comment]
<b style="font-weight:normal;" id="docs-internal-guid-9d93291b-7fff-89f1-ec9f-391ccf4fa931"><div dir="ltr" style="margin-left:0pt;" align="left">

Module | sources | arguments | queue | example
-- | -- | -- | -- | --
logcollector | localfile | Format, label | 49 |  
| | | | command |   |   |  
| | macos |   |   |  
wodles | Github |   | WIP |  
| | Office 365 |   | WIP |  
| | AWS-s3 |   | 49 |  
| | OpenSCAP |   | WIP |  
| | Cis-cat |   | WIP |  
| | Osquery |   | WIP |  
| | Virustotal |   | WIP |  
| | Docker-listener |   | WIP |  
| | Azure |   | WIP |  
Internal modules | DB sync |   | 53 |  
| | hostinfo |   | 51 |  
| | rootcheck |   | 57 |  
| | sca |   | 112 |  
| | syscheck |   | 56 |  
| | syscollector |   | 100 |  
| | upgrade |   | 117 |  
Remote syslog |   |   |   |  

</div></b>

**Comment by LucioDonda** [comment]
Basic description:
```
╰─# python3 agent_simulator.py -h                                                                   
usage: agent_simulator.py [-h] [-m MODULE] [-s SOURCE] [-i AGENT_ID] [-n AGENT_NAME] [-a AGENT_IP] [-L LOCATION] [-l LABELS] {send_event,save_event} ...

positional arguments:
  {send_event,save_event}

optional arguments:
  -h, --help            show this help message and exit
  -m MODULE, --module MODULE
                        Module of events
  -s SOURCE, --source SOURCE
                        Source of events
  -i AGENT_ID, --agent-id AGENT_ID
                        Agent ID for event filling
  -n AGENT_NAME, --agent-name AGENT_NAME
                        Agent name for events filling
  -a AGENT_IP, --agent-ip AGENT_IP
                        Agent ip address for events filling
  -L LOCATION, --location LOCATION
                        logcollector location wether file path or command
  -l LABELS, --labels LABELS
                        json object added to logcollector json event

```

save event: creates and saves an event in the output file

```
╰─# python3 agent_simulator.py save_event -h
usage: agent_simulator.py save_event [-h] [-O OUTPUT]

optional arguments:
  -h, --help            show this help message and exit
  -O OUTPUT, --Output OUTPUT
                        File where to store created events

```

send event: create and sends event to the specified socket
```

╰─# python3 agent_simulator.py send_event -h
usage: agent_simulator.py send_event [-h] [-e ENGINE-SOCKET]

optional arguments:
  -h, --help            show this help message and exit
  -e ENGINE-SOCKET, --engine-socket ENGINE-SOCKET
                        Where the engine is listening to events

```

**Comment by LucioDonda** [comment]
Basic usage:


```
╰─# python3 agent_simulator.py -s "logcollector" -m "syslog" save_event                           
test_logs_base.txt
1:[001] (agent-001) any->syslog:Apr 17 15:54:17 agent-001 systemd[1]: cgroup compatibility translation between legacy and unified hierarchy settings
1:[001] (agent-001) any->syslog:Apr 14 17:05:01 agent-001 CRON[7628]: pam_unix(cron:session): session opened for user root by (uid=0)
1:[001] (agent-001) any->syslog:Apr 20 11:54:38 agent-001 dnf[3422]: CentOS Linux 8 - AppStream                      5.7 kB/s | 4.3 kB     00:00
1:[001] (agent-001) any->syslog:Apr 20 12:13:33 agent-001 env[4477]: 2023/04/20 12:13:33 wazuh-logcollector[4542] agent_op.c:237 at os_read_agent_profile(): DEBUG: os_read_agent_profile() = [centos, centos8, centos8.3]
1:[001] (agent-001) any->syslog:Apr 20 12:13:33 agent-001 env[4477]: 2023/04/20 12:13:33 wazuh-logcollector[4542] config.c:407 at ReadConfig(): DEBUG: agent_config element does not have any attributes.
1:[001] (agent-001) any->syslog:Apr 20 12:13:33 agent-001 env[4477]: 2023/04/20 12:13:33 wazuh-logcollector[4542] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
1:[001] (agent-001) any->syslog:Apr 20 12:13:33 agent-001 env[4477]: 2023/04/20 12:13:33 wazuh-logcollector[4542] main.c:126 at main(): DEBUG: Wazuh home directory: /var/ossec
1:[001] (agent-001) any->syslog:Apr 20 12:13:33 agent-001 env[4477]: Started wazuh-syscheckd...
1:[001] (agent-001) any->syslog:Apr 20 12:13:37 agent-001 env[4477]: Completed.
1:[001] (agent-001) any->syslog:Apr 20 12:13:37 agent-001 systemd[1]: Started Wazuh agent.
1:[001] (agent-001) any->syslog:Apr 20 12:41:01 agent-001 rsyslogd[733]: [origin software="rsyslogd" swVersion="8.1911.0-6.el8" x-pid="733" x-info="https://www.rsyslog.com"] rsyslogd was HUPed
1:[001] (agent-001) any->syslog:Apr 20 12:55:37 agent-001 dnf[4675]: Metadata cache refreshed recently.
1:[001] (agent-001) any->syslog:Apr 20 12:55:37 agent-001 systemd[1]: dnf-makecache.service: Succeeded.
1:[001] (agent-001) any->syslog:Apr 20 12:55:37 agent-001 systemd[1]: Started dnf makecache.
1:[001] (agent-001) any->syslog:Apr 20 13:32:43 agent-001 systemd[1]: Removed slice User Slice of UID 1000.
1:[001] (agent-001) any->syslog:Apr 20 13:32:43 agent-001 systemd[1]: session-4.scope: Succeeded.
1:[001] (agent-001) any->syslog:Apr 20 13:32:43 agent-001 systemd[1]: Stopping /run/user/1000 mount wrapper...

```

```
╰─# python3 agent_simulator.py -s "logcollector" -m "command" save_event
test_logs_base.txt
1:[001] (agent-001) any->command:ossec: output: 'command': tmpfs              1012220   16764    995456       2% /run
1:[001] (agent-001) any->command:ossec: output: 'command': Filesystem     1024-blocks    Used Available Capacity Mounted on
1:[001] (agent-001) any->command:ossec: output: 'command': tmpfs              1012220       0   1012220       0% /sys/fs/cgroup
1:[001] (agent-001) any->command:ossec: output: 'df -P': tmpfs              1012220       0   1012220       0% /dev/shm
1:[001] (agent-001) any->command:ossec: output: 'df -P': devtmpfs            993776       0    993776       0% /dev
1:[001] (agent-001) any->command:ossec: output: 'df -P': tmpfs              1012220   16748    995472       2% /run
1:[001] (agent-001) any->command:ossec: output: 'df -P': /dev/sda1         10474496 5820552   4653944      56% /
```

```
╰─# python3 agent_simulator.py -s "logcollector" -m "eventchannel" save_event
test_logs_base.txt
f:[001] (agent-001) any->eventchannel:{"Message":"The Software Protection service entered the running state.","Event":"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Service Control Manager' Guid='{555908d1-a6d7-4695-8e1e-26931d2012f4}' EventSourceName='Service Control Manager'/><EventID Qualifiers='16384'>7036</EventID><Version>0</Version><Level>4</Level><Task>0</Task><Opcode>0</Opcode><Keywords>0x8080000000000000</Keywords><TimeCreated SystemTime='2023-04-20T14:44:44.856325900Z'/><EventRecordID>3897</EventRecordID><Correlation/><Execution ProcessID='480' ThreadID='660'/><Channel>System</Channel><Computer>agent-001</Computer><Security/></System><EventData><Data Name='param1'>Software Protection</Data><Data Name='param2'>running</Data><Binary>7300700070007300760063002F0034000000</Binary></EventData></Event>"}
f:[001] (agent-001) any->eventchannel:{"Message":"The Software Protection service has started.\r\n6.3.9600.17809","Event":"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-SPP' Guid='{E23B33B0-C8C9-472C-A5F9-F2BDFEA0F156}' EventSourceName='Software Protection Platform Service'/><EventID Qualifiers='16384'>902</EventID><Version>0</Version><Level>0</Level><Task>0</Task><Opcode>0</Opcode><Keywords>0x80000000000000</Keywords><TimeCreated SystemTime='2023-04-20T14:44:44.000000000Z'/><EventRecordID>1785</EventRecordID><Correlation/><Execution ProcessID='0' ThreadID='0'/><Channel>Application</Channel><Computer>agent-001</Computer><Security/></System><EventData><Data>6.3.9600.17809</Data></EventData></Event>"}

```

**Comment by LucioDonda** [comment]
Rework on usage, removes the list of sources and gets event from the stdin:

help:
```

╰─#  python3 agent_simulator.py -h                                                                                                                   
usage: agent_simulator.py [-h] [-i AGENT_ID] [-n AGENT_NAME] [-a AGENT_IP] [--dry-run] [-e ENGINE_SOCKET] [-o OUTPUT_FILE] {logcollector,remote-syslog} ...

positional arguments:
  {logcollector,remote-syslog}

optional arguments:
  -h, --help            show this help message and exit
  -i AGENT_ID, --agent-id AGENT_ID
                        Agent ID for event filling
  -n AGENT_NAME, --agent-name AGENT_NAME
                        Agent name for events filling
  -a AGENT_IP, --agent-ip AGENT_IP
                        Agent ip address for events filling
  --dry-run             events wont be sent to the engine socket
  -e ENGINE_SOCKET, --engine-socket ENGINE_SOCKET
                        Where the engine is listening to events
  -o OUTPUT_FILE, --output OUTPUT_FILE
                        Output file where the events will be stored, if empty events wont be saved

```

audit default:

```
╰─# echo 'type=CRED_DISP msg=audit(1681997462.455:741): pid=3926 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023' |  python3 agent_simulator.py logcollector -L "/tmp/audit.log"  audit           130 ↵
1:[001] (agent-001) any->/tmp/audit.log:type=CRED_DISP msg=audit(1681997462.455:741): pid=3926 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023

```

syslog with non-default agent settings:

```
╰─# echo 'Apr 20 12:13:37 centos8 systemd[1]: Started Wazuh agent.' |  python3 agent_simulator.py logcollector -L "systemd"  syslog                                                           
1:[001] (agent-001) any->systemd:Apr 20 12:13:37 centos8 systemd[1]: Started Wazuh agent.


```

json with labels and escaped IPV6:

```
╰─# echo '{"event": {"example":"something"}}' | python3 agent_simulator.py -a "02:42:62:87:73:85" logcollector -L "/root/file/algo.json"  json -l '{"field":"value","label":1}'                                     1 ↵
1:[001] (agent-001) 02|:42|:62|:87|:73|:85->/root/file/algo.json:{"event": {"example": "something", "field": "value", "label": 1}}
```

not sending events:

```
╰─# echo 'just an event' | python3 agent_simulator.py --dry-run -a "192.168.10.1" logcollector  eventchannel                                                              
f:[001] (agent-001) 192.168.10.1->eventchannel:just an event


```
