### ISSUE TITLE
Refactor Azure module to use Logger tool and log relevant information

### ISSUE THREAD

**Issue by EduLeon12** [wazuh/wazuh#16739]
| Affected integration |
|---|
| Azure|

## Description

As described in #16717, To standardize the logging a refactor in this cloud module needs to be done to integrate the logging tool developed in the mentioned issue.

Logging refactor on the module should be done to log relevant information about the process.

Unit tests should be reviewed as well to adapt to the new logging method.

## Tasks
- [x] Test in a manager.
- [x] Test in an agent.
- [x] Unit tests without failures. Updated if there are any relevant changes.
- [x] Integration tests without failures. Updated if there are any relevant changes.
- [x] Update the documentation if necessary.
- [x] Add entry to the changelog if necessary.

**Comment by EduLeon12** [comment]
Logger implemented following the current behavior. It was found it follows the same issue as the aws_logger, meaning it depends on developing a parser to log the output.

A discussion was opened to confirm how to proceed.

**Comment by EduLeon12** [comment]
## Issue Update

Logger implemented and parser tested. Test messages can be seen in the `ossec.log`  

```
2023/10/04 17:34:40 wazuh-modulesd:azure-logs[9536] wm_parser.c:76 at wm_parse_output(): INFO: This is an INFO test Message
2023/10/04 17:34:40 wazuh-modulesd:azure-logs[9536] wm_parser.c:82 at wm_parse_output(): WARNING: This is a WARNING test Message
2023/10/04 17:34:40 wazuh-modulesd:azure-logs[9536] wm_parser.c:80 at wm_parse_output(): ERROR: This is an ERROR test Message

```

After running the unit test for the Azure wodle the results are very negative but expected. 

```
============================ 54 failed, 94 passed, 55 warnings in 4.18s ============================
```

Next steps:
- [ ] Fix unit test.
- [ ] Do a full testing in agents for python version (3.9 and 3.7)

**Comment by EduLeon12** [comment]
## Issue Update

All changes to the module have been made according to the implemented logger and parser.

### Testing

<details> <summary> Manager logs </summary>

The testing was made by adding a testing message for every level with the `debug` level set to 2.

```
root@wazuh-master:/var/ossec# cat etc/local_internal_options.conf
wazuh_modules.debug=2
```

- `ossec.log`

```
2023/10/05 19:28:42 wazuh-modulesd:azure-logs[5927] wm_parser.c:76 at wm_parse_output(): INFO: This is an INFO test Message
2023/10/05 19:28:42 wazuh-modulesd:azure-logs[5927] wm_parser.c:82 at wm_parse_output(): WARNING: This is a WARNING test Message
2023/10/05 19:28:42 wazuh-modulesd:azure-logs[5927] wm_parser.c:80 at wm_parse_output(): ERROR: This is an ERROR test Message
2023/10/05 19:28:42 wazuh-modulesd:azure-logs[5927] wm_parser.c:80 at wm_parse_output(): ERROR: This is an ERROR test Message, with more info


```

And the module was functioning properly for the azure storage integration.

```
2023/10/05 19:28:42 wazuh-modulesd:azure-logs[5927] wm_parser.c:76 at wm_parse_output(): INFO: Azure Storage starting.
2023/10/05 19:28:42 wazuh-modulesd:azure-logs[5927] wm_parser.c:76 at wm_parse_output(): INFO: Storage: Authenticating.
2023/10/05 19:28:42 wazuh-modulesd:azure-logs[5927] wm_parser.c:76 at wm_parse_output(): INFO: Storage: Authenticated.
2023/10/05 19:28:42 wazuh-modulesd:azure-logs[5927] wm_parser.c:76 at wm_parse_output(): INFO: Storage: Getting blobs.
2023/10/05 19:28:42 wazuh-modulesd:azure-logs[5927] wm_parser.c:76 at wm_parse_output(): INFO: Storage: The search starts from the date: 2023-10-04 19:28:42.218033+00:00 for blobs in container: 'null-json-blob' and prefix: '/'
2023/10/05 19:28:42 wazuh-modulesd:azure-logs[5927] wm_parser.c:76 at wm_parse_output(): INFO: Storage: End
2023/10/05 19:28:42 wazuh-modulesd:azure-logs[5927] wm_azure.c:369 at wm_azure_storage(): INFO: Finished Storage log collection for container 'null-json-blob'.
2023/10/05 19:28:42 wazuh-modulesd:azure-logs[5927] wm_azure.c:94 at wm_azure_main(): INFO: Finished Storage log collection for 'storage_53336128'.
2023/10/05 19:28:42 wazuh-modulesd:azure-logs[5927] wm_azure.c:100 at wm_azure_main(): DEBUG: Fetching logs finished.
2023/10/05 19:28:42 wazuh-modulesd:azure-logs[5927] wm_azure.c:70 at wm_azure_main(): DEBUG: Sleeping until: 2023/10/06 19:28:41


```

</details> 

<details> <summary> Agent logs with `Python 3.9`</summary>

- `ossec.log`

```

```

With the module working properly

```


```

</details> 

<details> <summary> Agent logs with `Python 3.7`</summary>

- `ossec.log`

```


```

With the module working properly
```


```

</details>

<details> <summary> Azure unit test </summary>

```
(unit-test) eduardoleon@pop-os:~/git/wazuh/wodles(16739-refactor-azure-logs)$ pytest --disable-warnings azure/tests/
============================== test session starts ==============================
platform linux -- Python 3.9.16, pytest-7.4.2, pluggy-0.13.1
rootdir: /home/eduardoleon/git/wazuh/wodles
plugins: anyio-3.6.2, aiohttp-1.0.4, trio-0.7.0, html-3.0.0, asyncio-0.18.1, cov-3.0.0, metadata-2.0.2
asyncio: mode=auto
collected 144 items

azure/tests/test_azure.py ............................................... [ 32%]
..................................................................        [ 78%]
azure/tests/test_orm.py ...............................                   [100%]

======================== 144 passed, 1 warning in 0.44s =========================
```

</details>

**Comment by EduLeon12** [comment]
## Issue Update

Currently trying to fix an issue where the parser is not printing the logs in the `ossec.log` when executed on agents. But, when testing the module manually it works without problems.

**Comment by EduLeon12** [comment]
## Issue update

After rebasing the branch to contain the latest changes the test message can be seen in the ossec.log using the wm_parse_output method as expected.
Concluding that the module is working as expected as well as the modulesd parsing of the logs. 

```command
2023/12/20 17:11:05 wazuh-modulesd:azure-logs[47159] wm_azure.c:356 at wm_azure_storage(): DEBUG: Launching command: wodles/azure/azure-logs --storage --storage_auth_path /var/ossec/wodles/wodles_credentials/azure_storage_credentials --container "frameworktestcontainer" --blobs "*" --storage_tag azure-activity --storage_time_offset 30d --debug 2
2023/12/20 17:11:08 wazuh-modulesd:azure-logs[47159] wm_parser.c:76 at wm_parse_output(): INFO: Azure Storage starting.
2023/12/20 17:11:08 wazuh-modulesd:azure-logs[47159] wm_parser.c:76 at wm_parse_output(): INFO: TEST MESSAGE: INFO
2023/12/20 17:11:08 wazuh-modulesd:azure-logs[47159] wm_parser.c:82 at wm_parse_output(): WARNING: TEST MESSAGE: WARNING
2023/12/20 17:11:08 wazuh-modulesd:azure-logs[47159] wm_parser.c:80 at wm_parse_output(): ERROR: TEST MESSAGE: ERROR
2023/12/20 17:11:08 wazuh-modulesd:azure-logs[47159] wm_parser.c:76 at wm_parse_output(): INFO: Storage: Authenticating.
2023/12/20 17:11:08 wazuh-modulesd:azure-logs[47159] wm_parser.c:76 at wm_parse_output(): INFO: Storage: Authenticated.
2023/12/20 17:11:08 wazuh-modulesd:azure-logs[47159] wm_parser.c:76 at wm_parse_output(): INFO: Storage: Getting blobs.
2023/12/20 17:11:08 wazuh-modulesd:azure-logs[47159] wm_parser.c:76 at wm_parse_output(): INFO: Storage: The search starts from the date: 2023-11-20 17:11:08.081019+00:00 for blobs in container: 'frameworktestcontainer' and prefix: '/'
2023/12/20 17:11:08 wazuh-modulesd:azure-logs[47159] wm_parser.c:76 at wm_parse_output(): INFO: Storage: End
2023/12/20 17:11:08 wazuh-modulesd:azure-logs[47159] wm_azure.c:369 at wm_azure_storage(): INFO: Finished Storage log collection for container 'frameworktestcontainer'.
2023/12/20 17:11:08 wazuh-modulesd:azure-logs[47159] wm_azure.c:94 at wm_azure_main(): INFO: Finished Storage log collection for 'azure-activity'.
2023/12/20 17:11:08 wazuh-modulesd:azure-logs[47159] wm_azure.c:100 at wm_azure_main(): DEBUG: Fetching logs finished.
2023/12/20 17:11:08 wazuh-modulesd:azure-logs[47159] wm_azure.c:70 at wm_azure_main(): DEBUG: Sleeping until: 2023/12/20 17:21:05
```
