### ISSUE TITLE
Refactor AWS module to use Logger tool and log relevant information

### ISSUE THREAD

**Issue by EduLeon12** [wazuh/wazuh#16737]
| Affected integration |
|---|
| AWS|

## Description

As described in #16717, To standardize the logging a refactor in this cloud module needs to be done to integrate the logging tool developed in the mentioned issue.

Logging refactor on the module should be done to log relevant information about the process.

Unit tests should be reviewed as well to adapt to the new logging method.

Note: Current behavior of the core prevents this module to be integrated, the core part should be reviewed to adapt to the logger tool. 

## Tasks
- [x] Test in a manager.
- [x] Test in an agent.
- [x] Unit tests without failures. Updated if there are any relevant changes.
- [x] Integration tests without failures. Updated if there are any relevant changes.
- [x] Update the documentation if necessary.
- [x] Add entry to the changelog if necessary.

**Comment by EduLeon12** [comment]
## Issue Update

I'm trying different scenarios for the implementation of the AWS strategy. 

- One solution is to make a few changes on the C part of the integration to standardize the logs.
- One solution is to adapt the concrete AWS strategy to current behavior.

I will keep testing the first scenario if it's possibly done without any major change if I don't see it possible an issue for the core team will be created and the second solution can be implemented.

**Comment by EduLeon12** [comment]
Tests are still being performed since adapting the current behavior to the strategy would make not using the pattern at all.

I will seek help with the team to seek the best way to approach this issue.

**Comment by EduLeon12** [comment]
I was able to change the methods of the AWS concrete strategy to be able to print any information without changing the C part of the code.

- Ossec.log
-  
```
root@wazuh-master:/var/ossec/logs# cat ossec.log | grep 'This is a test '
:aws-s3 - DEBUG - This is a test DEBUG message
:aws-s3 - INFO - This is a test INFO message
:aws-s3 - WARNING - This is a test WARNING message
:aws-s3 - ERROR - This is a test ERROR message
```

The last adjustment should be to edit the messages to comply with the current format. 

After that print statement needs to be changed to its corresponding logging level statement.

Ex:
```
print("Error: Invalid AWS credentials.")
```
To
 
```
logging.error("Invalid AWS credentials.")

```

**Comment by EduLeon12** [comment]
With the help of a team member, a aws_parser following the behavior of the [gcp_parser](https://github.com/wazuh/wazuh/blob/e958b3c818a25ad1405db11bd17032f8970e1881/src/wazuh_modules/wm_gcp.c#LL321C36-L321C36) was tried to be developed, with no success.

A discussion has been opened with the team to plan the next step.

**Comment by EduLeon12** [comment]
I was able to test two loggers after developing the parser, using two different Log tags or token declared in [here](https://github.com/wazuh/wazuh/blob/enhancement/16737-refactor-aws-logs/src/wazuh_modules/wm_aws.h).  


- Logger = ':aws_wodle:'. Created by me.
 ```
2023/05/08 20:24:57 :aws_wodle:[5438] wm_aws.c:704 at wm_aws_parse_output(): INFO: New format Info Test Message
2023/05/08 20:24:57 :aws_wodle:[5438] wm_aws.c:698 at wm_aws_parse_output(): DEBUG: New format Debug Test Message
2023/05/08 20:24:57 :aws_wodle:[5438] wm_aws.c:718 at wm_aws_parse_output(): WARNING: New format Warning Test Message
2023/05/08 20:24:57 :aws_wodle:[5438] wm_aws.c:714 at wm_aws_parse_output(): ERROR: New format Error Test Message
:aws_wodle: - INFO - New format Info Test Message
:aws_wodle: - DEBUG - New format Debug Test Message
:aws_wodle: - WARNING - New format Warning Test Message
:aws_wodle: - ERROR - New format Error Test Message
:aws_wodle: - INFO - New format Info Test Message
:aws_wodle: - DEBUG - New format Debug Test Message
:aws_wodle: - WARNING - New format Warning Test Message
:aws_wodle: - ERROR - New format Error Test Message
```

- Logger = ':aws-s3'.  This Tag was already present.
```
root@wazuh-master:/var/ossec# grep 'wm_aws_parse_output' logs/ossec.log 
root@wazuh-master:/var/ossec# grep 'New format' logs/ossec.log 
:aws-s3 - INFO - New format Info Test Message
:aws-s3 - DEBUG - New format Debug Test Message
:aws-s3 - WARNING - New format Warning Test Message
:aws-s3 - ERROR - New format Error Test Message
```
As we can see from the results the parser uses a new constant as a logger tag and the parser the logs are displayed using the default format except for the 'wazuh-modulesd' tag. 

This will be discuss with team leader in order to plan how to proceed.

**Comment by EduLeon12** [comment]
## Issue Update

Logger refactor has been made and multiple services and buckets have been tested.

```command
root@wazuh-master:/var/ossec# wodles/aws/aws-s3 --bucket wazuh-aws-wodle-##### --aws_profile dev --only_logs_after 2022-NOV-01 --type config --debug 2
:aws_wodle: - DEBUG - No retries configuration found in profile config. Generating default configuration for retries: mode: standard - max_attempts: 10
:aws_wodle: - DEBUG - Created Config object using profile: 'dev' configuration
:aws_wodle: - DEBUG - +++ Working on ######### - us-east-1
:aws_wodle: - DEBUG - +++ Marker: AWSLogs/#########/Config/us-east-1/2022/8/22/#########3_Config_us-east-1_ConfigHistory_AWS Config ResourceCompliance_20220216T004303Z_#########Z_1.json.gz
:aws_wodle: - DEBUG - +++ No logs to process in bucket: #########/us-east-1
:aws_wodle: - DEBUG - +++ DB Maintenance

root@wazuh-master:/var/ossec# wodles/aws/aws-s3 --bucket wazuh-aws-wodle-cloudtrail --aws_profile dev --only_logs_after 2022-JAN-01 --type cloudtrail --debug 2
:aws_wodle: - DEBUG - No retries configuration found in profile config. Generating default configuration for retries: mode: standard - max_attempts: 10
:aws_wodle: - DEBUG - Created Config object using profile: 'dev' configuration
:aws_wodle: - DEBUG - +++ Working on ######### - us-west-1
:aws_wodle: - DEBUG - +++ Marker: AWSLogs/#########/CloudTrail/us-west-1/2023/09/06/#########-west-1_20230906T1755Z_2CqtXDyI0zFiYm1J.json
:aws_wodle: - DEBUG - +++ No logs to process in bucket: #########/us-west-1
:aws_wodle: - DEBUG - +++ DB Maintenance
:aws_wodle: - DEBUG - +++ Working on ######### - us-west-1
:aws_wodle: - DEBUG - +++ Marker: AWSLogs/#########/CloudTrail/us-west-1/2022/01/01
:aws_wodle: - DEBUG - +++ No logs to process in bucket: #########/us-west-1
:aws_wodle: - DEBUG - +++ DB Maintenance
:aws_wodle: - DEBUG - +++ Working on ######### - us-west-1
:aws_wodle: - DEBUG - +++ Marker: AWSLogs/#########/CloudTrail/us-west-1/2023/01/25/166157#########3_CloudTrail_us-west-1_20211223T0000Z_HASDOtJxxxxxxxxx.json.gz
:aws_wodle: - DEBUG - +++ No logs to process in bucket: #########/us-west-1
:aws_wodle: - DEBUG - +++ DB Maintenance

root@wazuh-master:/var/ossec# wodles/aws/aws-s3 --bucket wazuh-aws-wodle-guardduty-native --aws_profile dev --only_logs_after 2022-AUG-01 --type guardduty --debug 2
:aws_wodle: - DEBUG - No retries configuration found in profile config. Generating default configuration for retries: mode: standard - max_attempts: 10
:aws_wodle: - DEBUG - Created Config object using profile: 'dev' configuration
:aws_wodle: - DEBUG - +++ Working on ######### - us-east-1
:aws_wodle: - DEBUG - +++ Marker: AWSLogs/#########/GuardDuty/us-east-1/2022/10/21/ec7b0b8c-5ec8-32ec-8e77-c738515b4f6f.jsonl.gz
:aws_wodle: - DEBUG - +++ No logs to process in bucket: #########/us-east-1
:aws_wodle: - DEBUG - +++ DB Maintenance

root@wazuh-master:/var/ossec# wodles/aws/aws-s3 --service cloudwatchlogs --aws_profile dev --only_logs_after 2023-JAN-01 --regions us-east-1 --aws_log_groups 4_6_test --debug 2
:aws_wodle: - DEBUG - Getting alerts from "us-east-1" region.
:aws_wodle: - DEBUG - No retries configuration found in profile config. Generating default configuration for retries: mode: standard - max_attempts: 10
:aws_wodle: - DEBUG - Created Config object using profile: 'dev' configuration
:aws_wodle: - DEBUG - only logs: #########
:aws_wodle: - DEBUG - Getting log streams for "4_6_test" log group
:aws_wodle: - DEBUG - Found "test_stream" log stream in 4_6_test
:aws_wodle: - DEBUG - Getting data from DB for log stream "test_stream" in log group "4_6_test"
:aws_wodle: - DEBUG - Token: "f/####################################/s", start_time: "1672531200000", end_time: "1697034353275"
:aws_wodle: - DEBUG - Getting CloudWatch logs from log stream "test_stream" in log group "4_6_test" using token "f/####################################/s", start_time "1697034353276" and end_time "None"
:aws_wodle: - DEBUG - +++ There are no new events in the "4_6_test" group
:aws_wodle: - DEBUG - Saving data for log group "4_6_test" and log stream "test_stream".
:aws_wodle: - DEBUG - The saved values are "{'token': 'f/#############################################/s', 'start_time': 1672531200000, 'end_time': 1697034353276}"
:aws_wodle: - DEBUG - Some data already exists on DB for that key. Updating their values...
:aws_wodle: - DEBUG - Purging the Database
:aws_wodle: - DEBUG - Getting log streams for "4_6_test" log group
:aws_wodle: - DEBUG - Found "test_stream" log stream in 4_6_test
:aws_wodle: - DEBUG - committing changes and closing the DB

root@wazuh-master:/var/ossec# wodles/aws/aws-s3 --subscriber security_lake --queue AmazonSecurityLake-#########-#########-#########-#########-#########-Main-Queue --external_id wazuh-external-id --iam_role_arn arn:aws:iam::#########:role/AmazonSecurityLake-######### --debug 2
:aws_wodle: - DEBUG - No retries configuration found in profile config. Generating default configuration for retries: mode: standard - max_attempts: 10
:aws_wodle: - DEBUG - Created Config object using profile: 'default' configuration
:aws_wodle: - DEBUG - 8 events sent to Analysisd
:aws_wodle: - DEBUG - Message deleted from queue: AmazonSecurityLake-#########-Main-Queue
```

Remaining task:

- [ ] Fix failing unit tests that currently use the old logger to assert test results. 

```python
====================== 403 failed, 214 passed, 403 warnings in 22.09s =======================
```

- [ ]  Successful AWS ITs burst launch

**Comment by EduLeon12** [comment]
## Issue Update

```python 
(unit-test) eduardoleon@pop-os:~/git/wazuh/wodles/aws(16737-refactor-aws-logs)$ pytest tests/
============================= test session starts =============================
platform linux -- Python 3.9.16, pytest-7.4.2, pluggy-0.13.1
rootdir: /home/eduardoleon/git/wazuh/wodles/aws/tests
configfile: pytest.ini
plugins: anyio-3.6.2, aiohttp-1.0.4, trio-0.7.0, html-3.0.0, asyncio-0.18.1, cov-3.0.0, metadata-2.0.2
asyncio: mode=auto
collected 614 items

tests/test_aws_bucket.py .............................................. [  7%]
....................................................................... [ 19%]
....................................................................... [ 30%]
.....................                                                   [ 34%]
tests/test_aws_s3.py ..................                                 [ 36%]
tests/test_aws_service.py ....                                          [ 37%]
tests/test_cloudtrail.py ..                                             [ 37%]
tests/test_cloudwatchlogs.py .......................................... [ 44%]
...........                                                             [ 46%]
tests/test_config.py .................................................. [ 54%]
............................                                            [ 59%]
tests/test_guardduty.py .................                               [ 62%]
tests/test_inspector.py ......                                          [ 63%]
tests/test_load_balancers.py ............                               [ 64%]
tests/test_s3_log_handler.py ....                                       [ 65%]
tests/test_server_access.py .................................           [ 71%]
tests/test_sqs_queue.py .......                                         [ 72%]
tests/test_tools.py ............................                        [ 76%]
tests/test_umbrella.py ......                                           [ 77%]
tests/test_vpcflow.py ............................                      [ 82%]
tests/test_waf.py .......                                               [ 83%]
tests/test_wazuh_integration.py ....................................... [ 89%]
...............................................................         [100%]

============================= 614 passed in 1.85s =============================
```

All Unit tests have been successfully adapted to the new logger.

The only remaining task is to successfully launch the AWS ITs.

**Comment by EduLeon12** [comment]
## Issue Update

After running the AWS ITs the results were the following

```python
root@ip-172-31-85-239:/wazuh-qa/tests/integration# pytest test_aws/
=========================== test session starts ============================
platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-1.2.0
rootdir: /wazuh-qa/tests/integration, configfile: pytest.ini
plugins: testinfra-5.0.0, html-3.1.1, metadata-3.0.0
collected 198 items

test_aws/test_basic.py ................                              [  8%]
test_aws/test_discard_regex.py .................                     [ 16%]
test_aws/test_log_groups.py F.                                       [ 17%]
test_aws/test_only_logs_after.py ..............F..............FFFFFF [ 35%]
FFFFFFFFFFxFE                                                        [ 41%]
test_aws/test_parser.py ..........................                   [ 54%]
test_aws/test_path.py .FF.F.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FFF     [ 75%]
test_aws/test_path_suffix.py .........                               [ 80%]
test_aws/test_regions.py ..F......FFF..F..FFFFFFF                    [ 92%]
test_aws/test_remove_from_bucket.py ...sss.........                  [100%]

========================= short test summary info ==========================
FAILED test_aws/test_log_groups.py::test_log_groups[cloudwatchlogs_log_groups_with_data]
FAILED test_aws/test_only_logs_after.py::test_service_without_only_logs_after[cloudwatchlogs_without_only_logs_after]
FAILED test_aws/test_only_logs_after.py::test_cloudwatch_with_only_logs_after[cloudwatchlogs_with_only_logs_after]
FAILED test_aws/test_only_logs_after.py::test_inspector_with_only_logs_after[inspector_with_only_logs_after]
FAILED test_aws/test_only_logs_after.py::test_bucket_multiple_calls[cloudtrail_only_logs_after_multiple_calls]
FAILED test_aws/test_only_logs_after.py::test_bucket_multiple_calls[vpc_only_logs_after_multiple_calls]
FAILED test_aws/test_only_logs_after.py::test_bucket_multiple_calls[config_only_logs_after_multiple_calls]
FAILED test_aws/test_only_logs_after.py::test_bucket_multiple_calls[alb_only_logs_after_multiple_calls]
FAILED test_aws/test_only_logs_after.py::test_bucket_multiple_calls[clb_only_logs_after_multiple_calls]
FAILED test_aws/test_only_logs_after.py::test_bucket_multiple_calls[nlb_only_logs_after_multiple_calls]
FAILED test_aws/test_only_logs_after.py::test_bucket_multiple_calls[kms_only_logs_after_multiple_calls]
FAILED test_aws/test_only_logs_after.py::test_bucket_multiple_calls[macie_only_logs_after_multiple_calls]
FAILED test_aws/test_only_logs_after.py::test_bucket_multiple_calls[trusted_advisor_only_logs_after_multiple_calls]
FAILED test_aws/test_only_logs_after.py::test_bucket_multiple_calls[guardduty_only_logs_after_multiple_calls]
FAILED test_aws/test_only_logs_after.py::test_bucket_multiple_calls[native_guardduty_only_logs_after_multiple_calls]
FAILED test_aws/test_only_logs_after.py::test_bucket_multiple_calls[waf_only_logs_after_multiple_calls]
FAILED test_aws/test_only_logs_after.py::test_bucket_multiple_calls[server_access_only_logs_after_multiple_calls]
FAILED test_aws/test_only_logs_after.py::test_bucket_multiple_calls[cisco_umbrella_only_logs_after_multiple_calls]
FAILED test_aws/test_only_logs_after.py::test_cloudwatch_multiple_calls[cloudwatchlogs_only_logs_after_multiple_calls]
FAILED test_aws/test_path.py::test_path[cloudtrail_path_without_data] - T...
FAILED test_aws/test_path.py::test_path[cloudtrail_inexistent_path] - Tim...
FAILED test_aws/test_path.py::test_path[vpc_path_without_data] - TimeoutE...
FAILED test_aws/test_path.py::test_path[cisco_umbrella_path_without_data]
FAILED test_aws/test_path.py::test_path[vpc_inexistent_path] - TimeoutErr...
FAILED test_aws/test_path.py::test_path[config_path_without_data] - Timeo...
FAILED test_aws/test_path.py::test_path[config_inexistent_path] - Timeout...
FAILED test_aws/test_path.py::test_path[alb_path_without_data] - TimeoutE...
FAILED test_aws/test_path.py::test_path[alb_inexistent_path] - TimeoutErr...
FAILED test_aws/test_path.py::test_path[clb_path_without_data] - TimeoutE...
FAILED test_aws/test_path.py::test_path[clb_inexistent_path] - TimeoutErr...
FAILED test_aws/test_path.py::test_path[nlb_path_without_data] - TimeoutE...
FAILED test_aws/test_path.py::test_path[nlb_inexistent_path] - TimeoutErr...
FAILED test_aws/test_path.py::test_path[kms_path_without_data] - TimeoutE...
FAILED test_aws/test_path.py::test_path[kms_inexistent_path] - TimeoutErr...
FAILED test_aws/test_path.py::test_path[macie_path_without_data] - Timeou...
FAILED test_aws/test_path.py::test_path[macie_inexistent_path] - TimeoutE...
FAILED test_aws/test_path.py::test_path[trusted_advisor_path_without_data]
FAILED test_aws/test_path.py::test_path[trusted_advisor_inexistent_path]
FAILED test_aws/test_path.py::test_path[guardduty_path_without_data] - Ti...
FAILED test_aws/test_path.py::test_path[guardduty_inexistent_path] - Time...
FAILED test_aws/test_path.py::test_path[native_guardduty_path_without_data]
FAILED test_aws/test_path.py::test_path[native_guardduty_inexistent_path]
FAILED test_aws/test_path.py::test_path[waf_path_without_data] - TimeoutE...
FAILED test_aws/test_path.py::test_path[waf_inexistent_path] - TimeoutErr...
FAILED test_aws/test_path.py::test_path[server_access_path_without_data]
FAILED test_aws/test_path.py::test_path[server_access_inexistent_path] - ...
FAILED test_aws/test_path.py::test_path[cisco_umbrella_inexistent_path]
FAILED test_aws/test_regions.py::test_regions[cloudtrail_inexistent_region]
FAILED test_aws/test_regions.py::test_regions[vpc_inexistent_region] - Ti...
FAILED test_aws/test_regions.py::test_regions[config_inexistent_region]
FAILED test_aws/test_regions.py::test_regions[alb_inexistent_region] - Ti...
FAILED test_aws/test_regions.py::test_regions[clb_inexistent_region] - Ti...
FAILED test_aws/test_regions.py::test_regions[nlb_inexistent_region] - Ti...
FAILED test_aws/test_regions.py::test_cloudwatch_regions[cloudwatchlogs_region_with_data]
FAILED test_aws/test_regions.py::test_cloudwatch_regions[cloudwatchlogs_regions_with_data]
FAILED test_aws/test_regions.py::test_cloudwatch_regions[cloudwatchlogs_inexistent_region]
FAILED test_aws/test_regions.py::test_inspector_regions[inspector_region_with_data]
FAILED test_aws/test_regions.py::test_inspector_regions[inspector_regions_with_data]
FAILED test_aws/test_regions.py::test_inspector_regions[inspector_inexistent_region]
ERROR test_aws/test_only_logs_after.py::test_cloudwatch_multiple_calls[cloudwatchlogs_only_logs_after_multiple_calls]
= 59 failed, 135 passed, 3 skipped, 1 xfailed, 1 error in 4509.22s (1:15:09) =

```

The failed test will be reviewed to understand if the change on the logger is the actual cause of the failure.

**Comment by EduLeon12** [comment]
> [!IMPORTANT]  
> During https://github.com/wazuh/wazuh-qa/issues/4714 development it was found that an Error is displayed when a bucket is empty and after discussing it with the team it was decided to change it to a warning since it's not a product issue.
This should be changed is this issue.

**Comment by EduLeon12** [comment]
## Issue Update

The only remaining task of this issue when resumed should be to change the `patterns.py` file of the testing framework (qa-integration-framework). located in path `src/wazuh_testing/modules/aws/patterns.py` to ensure the AWS Integration tests pass.

This has not been done since the epic blocking this issue is in charge of the migration of the AWS module to the testing framework.

Ex:
```python
# From

PARSER_ERROR = ".*wm_aws_read\(\): ERROR:.*"
EMPTY_CONTENT_WARNING = ".*WARNING: Empty content for tag '\w+' at module 'aws-s3'."
SERVICE_ANALYSIS = ".*INFO: Executing Service Analysis:*"
NO_LOG_PROCESSED = ".*DEBUG: \+\+\+ No logs to process for .*"

# To

PARSER_ERROR = ".*wm_aws_read\(\): .*"
EMPTY_CONTENT_WARNING = ".*Empty content for tag '\w+' at module 'aws-s3'."
SERVICE_ANALYSIS = ".*Executing Service Analysis:*"
NO_LOG_PROCESSED = ".* \+\+\+ No logs to process for .*"
```

This needs to be confirmed with the output of the `ossec.log` since the logger also prints the level configured for said log.

**Comment by Selutario** [comment]
Included in https://github.com/wazuh/wazuh/pull/23448
