### ISSUE TITLE
Engine - Optimize High-Level Parser Performance by Splitting Parsing Process

### ISSUE THREAD

**Issue by juliancnn** [wazuh/wazuh#16741]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|5.0.0 | Engine | Manager | Packages/Sources | OS version |

## Description
An opportunity has been identified to significantly improve the performance of our High-Level Parser (HLP). It is proposed to split the parsing process into two separate stages: one for semantic analysis and one for result construction.

Currently, in most cases, the 'Logpar' parser fails, but it is possible for some individual component parsers to succeed. Generating the result mapped to the event is a costly process in terms of time and resources. Therefore, it is proposed to split the process into two stages:

1. quick semantic analysis: perform a quick semantic analysis to determine if all individual parsers in 'Logpar' are successful.
2. Construction and validation of the result: if all individual parsers are successful, proceed to construct the result and validate its content.

This division will allow optimizing HLP performance by avoiding unnecessary result construction and validation when not all individual parsers are successful. In addition, this strategy can reduce processing time and improve overall system efficiency.
## Tasks
- [x] Study Parser combinators
- [x] Study Logpar 
- [x] Propose an Implementation
- [x] Benchmarks (HLP vs HLP3) and (HLP2 vs HLP3)
- [ ] Implement new parser, trace and result
- [ ] Implement new combinators
- [ ] Implement new builders of logpar
- [ ] Implement old parsers with new semantic
- [ ] Combinators Test
- [ ] Parser, trace and result test
- [ ] Parser test
- [ ] Apply RTR corrections
- [ ] Update Documentation
- [ ] QA validate
