### ISSUE TITLE
Ability to trace crashes in K8s environments

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#16747]
The goal of this issue is to prove that we're able to trace crashes that may occur in K8s environments. So, we need to provide packages with debugging data, run a testing environment, cause a crash and check the resulting core dump.

## Subtasks

- https://github.com/wazuh/wazuh-packages/issues/2161
  - [x] Create RPM packages for CentOS 7 having debugging data:
- Build and run a testing environment with debugging symbols
  - [x] Install the package in a K8s environment.
  - [x] Run a testing environment.
  - [x] Manually cause a crash (`kill -SIGSEGV` or similar) in _wazuh-db_ on that environment.
  - [x] Get a core dump.
- [x] Trace the core dump with GDB.

**Comment by teddytpc1** [comment]
The RPM package with debug symbols was created:
- [RPM](https://packages-dev.wazuh.com/warehouse/debug/4.3/rpm/wazuh-manager-4.3.10-0.debug.wp2161.x86_64.rpm)

**Comment by vikman90** [comment]
Thank you @teddytpc1.

I confirm that the package is correct and contains the debugging symbols.

## Cheks

<details><summary><h3>🟢 Installation on CentOS 7</h3></summary>

```shell
wget https://packages-dev.wazuh.com/warehouse/debug/4.3/rpm/wazuh-manager-4.3.10-0.debug.wp2161.x86_64.rpm
rpm -i wazuh-manager-4.3.10-0.debug.wp2161.x86_64.rpm
```

</details>

<details><summary><h3>🟢 wazuh-db size</h3></summary>

_wazuh-db_ binary must be larger than 1 MB, since the non-debug version is 578 KB.

```shell
ls -lh /var/ossec/bin/wazuh-db
```
```
-rwxr-x---. 1 root root 1.1M Apr 17 21:52 /var/ossec/bin/wazuh-db
```

</details>

<details><summary><h3>🟢 Run and kill wazuh-db</h3></summary>

```shell
/var/ossec/bin/wazuh-db
kill -SIGSEGV `pidof wazuh-db`
```

</details>

<details><summary><h3>🟢 Read the core dump</h3></summary>

```shell
gdb /var/ossec/bin/wazuh-db /var/crash/core.wazuh-db.*
```

```
(gdb) bt
#0  0x00007f0228fa8017 in pthread_join () from /lib64/libpthread.so.0
#1  0x00000000004057f4 in main (argc=2, argv=0x7ffdb9399478) at wazuh_db/main.c:213
(gdb) info thread
  Id   Target Id         Frame
  11   Thread 0x7f02269b9700 (LWP 6437) 0x00007f0228fad54d in __lll_lock_wait ()
   from /lib64/libpthread.so.0
  10   Thread 0x7f02271ba700 (LWP 6436) 0x00007f0228fad54d in __lll_lock_wait ()
   from /lib64/libpthread.so.0
  9    Thread 0x7f02249b5700 (LWP 6441) 0x00007f0228fad54d in __lll_lock_wait ()
   from /lib64/libpthread.so.0
  8    Thread 0x7f02261b8700 (LWP 6438) 0x00007f0228fad54d in __lll_lock_wait ()
   from /lib64/libpthread.so.0
  7    Thread 0x7f02241b4700 (LWP 6442) 0x00007f0228c969fd in nanosleep ()
   from /lib64/libc.so.6
  6    Thread 0x7f02281bc700 (LWP 6434) 0x00007f0228cd00e3 in epoll_wait ()
   from /lib64/libc.so.6
  5    Thread 0x7f02289bd700 (LWP 6433) 0x00007f0228cc6b43 in select ()
   from /lib64/libc.so.6
  4    Thread 0x7f02259b7700 (LWP 6439) 0x00007f0228fad54d in __lll_lock_wait ()
   from /lib64/libpthread.so.0
  3    Thread 0x7f02251b6700 (LWP 6440) 0x00007f0228fad54d in __lll_lock_wait ()
   from /lib64/libpthread.so.0
  2    Thread 0x7f02279bb700 (LWP 6435) 0x00007f0228fad54d in __lll_lock_wait ()
   from /lib64/libpthread.so.0
* 1    Thread 0x7f022a5ff740 (LWP 6432) 0x00007f0228fa8017 in pthread_join ()
   from /lib64/libpthread.so.0
```

</details>

## Conclusion

The package is ready to be installed on a containerized environment.

**Comment by vikman90** [comment]
## 🟢 Checking the core dump

```shell
gdb /var/ossec/bin/wazuh-db wazuh-db.core
```
```
(gdb) bt
#0  0x00007f3036b96017 in pthread_join () from /lib64/libpthread.so.0
#1  0x00000000004057f4 in main (argc=1, argv=0x7ffcf4b97368) at wazuh_db/main.c:213
(gdb) info thread
  Id   Target Id         Frame
  11   Thread 0x7f3030ba2700 (LWP 369) 0x00007f30368849fd in nanosleep () from /lib64/libc.so.6
  10   Thread 0x7f30315a3700 (LWP 368) 0x00007f3036b9b54d in __lll_lock_wait () from /lib64/libpthread.so.0
  9    Thread 0x7f30329a5700 (LWP 366) 0x00007f3036b9b54d in __lll_lock_wait () from /lib64/libpthread.so.0
  8    Thread 0x7f3031fa4700 (LWP 367) 0x00007f3036b9b54d in __lll_lock_wait () from /lib64/libpthread.so.0
  7    Thread 0x7f30333a6700 (LWP 365) 0x00007f3036b9b54d in __lll_lock_wait () from /lib64/libpthread.so.0
  6    Thread 0x7f30365ab700 (LWP 360) 0x00007f30368b4b43 in select () from /lib64/libc.so.6
  5    Thread 0x7f3035baa700 (LWP 361) 0x00007f3036b9b54d in __lll_lock_wait () from /lib64/libpthread.so.0
  4    Thread 0x7f3033da7700 (LWP 364) 0x00007f3036b9b54d in __lll_lock_wait () from /lib64/libpthread.so.0
  3    Thread 0x7f30351a9700 (LWP 362) 0x00007f3036b9b54d in __lll_lock_wait () from /lib64/libpthread.so.0
  2    Thread 0x7f30347a8700 (LWP 363) 0x00007f30368be0e3 in epoll_wait () from /lib64/libc.so.6
* 1    Thread 0x7f30381ef740 (LWP 357) 0x00007f3036b96017 in pthread_join () from /lib64/libpthread.so.0
(gdb) thread 6
[Switching to thread 6 (Thread 0x7f30365ab700 (LWP 360))]
#0  0x00007f30368b4b43 in select () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f30368b4b43 in select () from /lib64/libc.so.6
#1  0x0000000000405a2c in run_dealer (args=0x0) at wazuh_db/main.c:259
#2  0x00007f3036b94ea5 in start_thread () from /lib64/libpthread.so.0
#3  0x00007f30368bdb0d in clone () from /lib64/libc.so.6
```
