### ISSUE TITLE
Engine Framework API - Design

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#16868]
## Description

The aim of this issue is to define the design of the new API endpoints that will communicate with the new Wazuh Engine.

New Engine epic issue: https://github.com/wazuh/wazuh/issues/11334
Engine development branch: [11334-dev-new-wazuh-engine](https://github.com/wazuh/wazuh/tree/11334-dev-new-wazuh-engine)

> This is work in progress and the information provided below is subtle to changes.

### New endpoints design

The following endpoins have to be created in order for the framework API consumers to query and send instructions to the new Engine

<table>
    <thead>
        <tr>
            <th>Module</th>
            <th>Endpoint</th>
			<th>Description</th>
            <th>Engine command(s)</th>
        </tr>
    </thead>
    <tbody>
		
        <tr>
            <td rowspan=5>Catalog</td>
            <td><code>GET /engine/catalog/resource</td>
			<td>Get a resource from the catalog</td>
                        <td><code>catalog.resource/get</td>
        </tr>
        <tr>
            <td><code>POST /engine/catalog/resource</td>
			<td>Add a resource to the catalog</td>
                        <td><code>catalog.resource/post</td></td>
        </tr>
		<tr>
			<td><code>DELETE /engine/catalog/resource</td>
			<td>Remove a resource from the catalog</td>
                        <td><code>catalog.resource/delete</td></td>
		</tr>
		<tr>
			<td><code>PUT /engine/catalog/resource</td>
			<td>Update a resource from the catalog</td>
                        <td><code>catalog.resource/put</td></td>
		</tr>
		<tr>
			<td><code>GET /engine/catalog/resource/validate</td>
			<td>Validate a resource from the catalog</td>
                        <td><code>catalog.resource/validate</td></td>
		</tr>
		
	<tr>
            <td rowspan=2>Config</td>
                        <td><code>GET /engine/config/runtime</td>
			<td>Get the runtime configuration of the manager</td>
                        <td><code>config.runtime/get</td>
        </tr>
		<tr>
			<td><code>PUT /engine/config/runtime</td>
			<td>Update the runtime configuration of the manager</td>
                       <td><code>config.runtime/put, config.runtime/save</td></td>
		</tr>
        
        <tr>
            <td rowspan=1>Graph</td>
            <td><code>GET /engine/graph/resource</td>
			<td>Get a resource from the graph</td>
                        <td><code>graph.resource/get</td>
        </tr>
	
        <tr>
            <td rowspan=2>Integration</td>
                       <td><code>POST /engine/integration/policy</td>
			<td>Add an integration to a policy in the catalog</td>
                        <td><code>integration.policy/add_to</td>
        </tr>
		<tr>
			<td><code>DELETE /engine/integration/policy</td>
			<td>Remove an integration from a policy in the catalog</td>
                        <td><code>integration.policy/remove_from</td>
		</tr>
	
	<tr>
            <td rowspan=6>KVDB</td>
	    <td><code>GET /engine/kvdb</td>
	    <td>List all databases</td>
            <td><code>kvdb.manager/get</td>
	</tr>
		<tr>
			<td><code>POST /engine/kvdb</td>
			<td>Create a new database</td>
                        <td><code>kvdb.manager/post</td>
		</tr>
		<tr>
			<td><code>DELETE /engine/kvdb</td>
			<td>Delete a database</td>
                        <td><code>kvdb.manager/delete</td>
            <tr>
                        <td><code>GET /engine/kvdb/entries</td>
			<td>Get all entries or a list of them</td>
                        <td><code>kvdb.db/get, kvdb.manager/dump</td>
            </tr>
		<tr>
			<td><code>DELETE /engine/kvdb/entries</td>
			<td>Delete an entry or a list of them</td>
                        <td><code>kvdb.db/delete</td>
		</tr>
		<tr>
			<td><code>POST /engine/kvdb/entries</td>
			<td>Insert a new entry</td>
                        <td><code>kvdb.db/put</td>
		</tr>
		
		<tr>
            <td rowspan=4>Metrics</td>
                        <td><code>GET /engine/metrics</td>
			<td>Print a list of metrics or all of them as json</td>
                        <td><code>metrics/dump, metrics/get</td>
        </tr>
        <tr>
                        <td><code>GET /engine/instruments</td>
			<td>List all instruments showing its name, status and type</td>
                        <td><code>metrics/list</td>
        </tr>
		<tr>
			<td><code>PUT /engine/instruments/enable</td>
			<td>Enable or disable a specific instrument</td>
                        <td><code>metrics/enable</td>
		</tr>
		<tr>
			<td><code>GET /engine/metrics/test</td>
			<td>Generate dummy metrics for testing</td>
                        <td><code>metrics/test</td>
		</tr>
		
		<tr>
            <td rowspan=6>Router</td>
                        <td><code>GET /engine/routes</td>
			<td>Get a route from the router</td>
                        <td><code>router.route/get</td>
        </tr>
		<tr>
			<td><code>POST /engine/routes</td>
			<td>Create a route to the router</td>
                        <td><code>router.route/post</td>
		</tr>
		<tr>
			<td><code>PATCH /engine/routes</td>
			<td>Patch a route to the router</td>
                        <td><code>router.route/patch</td>
		</tr>
		<tr>
			<td><code>DELETE /engine/routes</td>
			<td>Delete a route to the router</td>
                        <td><code>router.route/delete</td>
		</tr>
		<tr>
			<td><code>GET /engine/routes/table</td>
			<td>Get the table of routes from the router</td>
                        <td><code>router.table/get</td>
		</tr>
		<tr>
			<td><code>POST /engine/routes/queue</td>
			<td>Send a event to queue of the router</td>
                        <td><code>router.queue/post</td>
		</tr>
    </tbody>
</table>

#### Requests

The new Engine takes a command's arguments from the JSON body it receives in the request, we could get those parameters from the URL (just like we do right now) and then build the Engine request accordingly.

For example, the user sends the request:
```
GET /router/route?name=SampleName
```

and we will build the following object and send it to the Engine:

```json
{
  "version": 1,
  "origin": {
	"name": "Origin component",
	"module": "component of module"
  },
  "command": "router.route/get",
  "parameters": {
	"name": "SampleName"
  }
}
```

#### Responses

The Engine responses follow the same format the current API uses, so we could just return the response, or wrap it with our standard object.

Sample response:
```json
{
  "error": 0,
  "data": {
    "status": "OK",
    "route": {
      	"name": "SampleName",
      	"filter": "filter/allow-all/0",
      	"policy": "environment/default/0",
      	"priority": 255
    }
  }
}
```

### Project

- [ ] https://github.com/wazuh/wazuh/issues/17058
    - [x] https://github.com/wazuh/wazuh/issues/17343
    - [ ] https://github.com/wazuh/wazuh/issues/17059
    - [ ] https://github.com/wazuh/wazuh/issues/17060
    - [x] https://github.com/wazuh/wazuh/issues/17742
    - [ ] https://github.com/wazuh/wazuh/issues/17061
    - [ ] https://github.com/wazuh/wazuh/issues/17065
    - [ ] https://github.com/wazuh/wazuh/issues/17066
    - [ ] https://github.com/wazuh/wazuh/issues/17067
  
- [ ] https://github.com/wazuh/wazuh/issues/17070
- [ ] https://github.com/wazuh/wazuh/issues/17062
    - [ ] https://github.com/wazuh/wazuh/issues/17063
    - [ ] https://github.com/wazuh/wazuh/issues/17068
    - [ ] https://github.com/wazuh/wazuh/issues/17069

**Comment by GGP1** [comment]
## Update

- Onboarded Fede to the project
- Merged `PUT /config/runtime` and `PUT /config/runtime/save`
- Added two notes
- Started developing the new specification so we can develop it collaboratively and visualize the end result

**Comment by GGP1** [comment]
## Update

Created a document with a structure we could use to organize the project's tasks and subtasks, features the API should have and other information related to the Engine development. We also made a meeting with Fede to share some thoughts on it.

**Comment by GGP1** [comment]
## Update

Created a document with a structure we could use to organize the project's tasks and subtasks, features the API should have and other information related to the Engine development. We also made a meeting with Fede to share some thoughts on it.

We are planning to have a meeting on the next Tuesday to define and start creating the issues for the next steps.

**Comment by GGP1** [comment]
## Update



- Changed `/config/runtime` to `/manager/configuration`
- Changed `/kvdb` to `/db` and `/kvdb/manager` to just `/db`
- Changed `/router/route` to `/routes`
- Modified the notes section

### Features

The API should support the following features:

- Pagination (currently using **offset/limit**)
- Field selection (currently using **select**)
- Sorting (currently using **sort**)
- Filtering (currently using **q**, **search**, **older_than**)
- Some kind of previous validation? Like request body size. Main one should be delegated to the Engine
- Versioning?
- Stream files from the user to the engine (phase 2)

### Project tasks structure proposal

The Framework API for the new Engine is a large project and should be divided into separate issues. Here is a structure we could follow

```yaml
Wazuh Engine API Framework
    - Design (this)
    - New endpoints implementation and old endpoints updates. Including unit and integration tests. Divided by module.
   	 - Catalog
   	 - Config
   	 - Integration
   	 - KVDB
   	 - Metrics
   	 - Router
    - New RBACs implementations
   	 - Sub-divide by module/group
    - Delete deprecated endpoints
   	 - Decoders
   	 - Lists
   	 - Rules
   	 - SCA
    - Specification update
```

### Changes unrelated to the Engine

Given that the new API will be incompatible with the current one, it might be beneficial to do some changes along with the project:

- Move `/overview/agents` to `/agents/overview`
- Move `/ciscat/[agent_id]/result` to `/agents/[agent_id]/ciscat`
- Delete deprecated endpoints
    - `GET /agents/[agent_id]/groups/is_sync`
    - `GET /cluster/[node_id]/stats/analysisd`
    - `GET /cluster/[node_id]/stats/remoted`
    - `GET /manager/stats/analysisd`
    - `GET /manager/stats/remoted`
    - `GET /security/user/authenticate`

**Comment by GGP1** [comment]
## Update

We did a meeting and defined the project's final structure as well as some changes in the design of the endpoints. 

I applied the discussed design changes to this issue's description and created the following issues to start with the development:

- https://github.com/wazuh/wazuh/issues/17058
    - https://github.com/wazuh/wazuh/issues/17059
    - https://github.com/wazuh/wazuh/issues/17060
    - https://github.com/wazuh/wazuh/issues/17061
- https://github.com/wazuh/wazuh/issues/17062
    - https://github.com/wazuh/wazuh/issues/17063
    - https://github.com/wazuh/wazuh/issues/17068
    - https://github.com/wazuh/wazuh/issues/17069

**Comment by RamosFe** [comment]
## Update

Changed the design of the Metrics module endpoints:
-  Created a new endpoint `GET instruments`.
- Grouped `metrics/dump`, `metrics/get` commands into the endpoint `GET metrics`  and `metrics/list`in `GET instruments` because each group of commands represents a different resource(https://github.com/wazuh/wazuh/pull/16364)

**Comment by fdalmaup** [comment]
Wazuh 5.0 has been redefined and will follow a different approach related to the current Wazuh API. More information:
- https://github.com/wazuh/wazuh/issues/22888
- https://github.com/wazuh/wazuh/issues/22677
- https://github.com/wazuh/wazuh/issues/22887
- https://github.com/wazuh/wazuh/issues/23577
- https://github.com/wazuh/wazuh-dashboard/issues/164
