### ISSUE TITLE
Engine - Adapt graph command to be used through the API

### ISSUE THREAD

**Issue by nmkoremblum** [wazuh/wazuh#16877]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|5.0.0 | Engine | Manager | Packages/Sources | OS version |

## Description

The "graph" command of the Wazuh Engine generates a graphical representation of the relationships between the elements that compose an operations chain. There are two different kinds of graphs that can be obtained: the security policy graph composed of decoders, rules, etc., and the expression graph, which is composed of the low-level operations which implement those policies. Currently, the command runs as a separate program. 

To improve the accessibility and usability of the "graph" command, it has been decided to turn it into a server endpoint and allow its use through the API. This way, users can interact with the command through a client.

This process will require expanding the existing API to handle the "graph" module and adapting its code accordingly.

## Tasks

- [x] Refactor the existing code of the "graph" command to adapt it to the new API model.
- [x] Implement the server endpoint.
- [x] Develop a client that allows users to interact with the API and generate the corresponding graphs.
- [x] Perform integration tests and ensure that the API works correctly.

## DoD
 - [x] All tasks completed. 
 - [x] Unit test run and tested.
 - [x] Clang format checked.
 - [x] Documentation updated.

**Comment by NahuFigueroa97** [comment]
![Captura desde 2023-05-11 14-47-47](https://github.com/wazuh/wazuh/assets/63238635/7db38a0d-8119-40ed-89d8-f126d17c107f)
