### ISSUE TITLE
Maintain production and numbered branches

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#16901]
The goals are:
- [x] Update the latest released versions' date.
- [x] Merge 4.3 into 4.4.
- [x] Merge 4.4 into 4.5.
- [x] Update Python from deps 20 to 21 in AWS
- [ ] Merge 4.5 into master.
- [ ] Update Python from deps 21 to 22 in AWS

### Subtasks

- [wazuh-qa](https://github.com/wazuh/wazuh-qa/issues/4135)
- [wazuh-packages](https://github.com/wazuh/wazuh-packages/issues/2183)
- [wazuh-jenkins](https://github.com/wazuh/wazuh-jenkins/issues/5052)
- [wazuh-docker](https://github.com/wazuh/wazuh-docker/issues/830) **Done**.
- wazuh-frontend

**Comment by teddytpc1** [comment]
`wazuh-docker`: https://github.com/wazuh/wazuh-docker/issues/830. Done
