### ISSUE TITLE
Engine - Test - Get the trace and output from the router api

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh#16920]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|5.0.0 | Engine | Manager | Packages/Sources | OS version |

## Description

The "test" command of the Wazuh Engine helps you test the items you’re developing. Including decoders, rules, outputs, and filters.

To improve the accessibility and usability of the "test" command, it has been decided to turn it into a server endpoint and allow its use through the API. This way, users can interact with the command through a client.

This process will require expanding the existing API to handle the "test" command and adapting its code accordingly.

### Requirements
-  The test command must use the API Router module to process the event.
-  The event goes through the entire router and applies the appropriate filter.
-  Mark the event that entered by test, to match with the Session router filter.
-  In case the parameter is not included try with the default route.
- The test command will not raise or create any policy environment, it will only use the ones that are created/raised indicating which one the event will go through.
- In case the policy/environment indicated in the command is not created/updated, the error is reported in the response.

## Tasks

- [x] Refactor the existing code of the "test" command to adapt it to the new API model.
- [x] Develop a client that allows users to interact with the API and generate the corresponding test.
- [x] Refactor the router module to return the trace and output through the API.

## DoD
 - [x] All tasks completed. 
 - [x] Unit test run and tested.
 - [x] Clang format checked.
 - [x] Documentation updated.
