### ISSUE TITLE
Release 4.4.2 - Post release

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#16957]
The following issue aims to perform required post-release checks to ensure a well-published release procedure.

## Main information
|||
| :--                             | :--                                                |
| **Version**                     | WAZUH_VERSION                                      |
| **Tag**                         | https://github.com/wazuh/wazuh/tree/vWAZUH_VERSION |
| **Release issue**               |  RELEASE_ISSUE                                     |
| **Previous post release issue** | PREVIOUS_POST                                      |

---

### Release notes and tags
- [ ] wazuh/wazuh
- [ ] wazuh/wazuh-packages
- [ ] wazuh/wazuh-kibana-app
- [ ] wazuh/wazuh-splunk
- [ ] wazuh/wazuh-qa
- [ ] wazuh/wazuh-ansible
- [ ] wazuh/wazuh-docker
- [ ] wazuh/wazuh-kubernetes
- [ ] wazuh/wazuh-puppet

### Repository
- [ ] Live installation test
- [ ] Live upgrade test
- [ ] WPK versions check
- [ ] WPK upgrade test
- [ ] Post-release check (files)
- [ ] AMI published
- [ ] Cache invalidated
- [ ] Build release containers
- [ ] Build and push Docker Hub images
- [ ] Build and release debug packages
- [ ] Publish puppet forge module
- [ ] Update upgrade template in wazuh-jenkins repository with the last version

### Documentation
- [ ] Documentation updated
- [ ] Documentation published
- [ ] Cache invalidated

### Marketing
- [ ] Community announcement (Need the rest of the checks ready)

---

## Validation

The following auditors must give the green light to this release.

- [ ] @davidjiglesias 
- [ ] @snaow

---

**Comment by c-bordon** [comment]
## Update report

- Install  tests: https://ci.wazuh.info/view/Tests/job/Test_install_tier/587/console
- Update tests: https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/2074/console

**Comment by c-bordon** [comment]
---

### WPK upgrade test

<details><summary>Linux WPK upgrade</summary>

```console
[root@centos7-1 ~]# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.4.2"
WAZUH_REVISION="40408"
WAZUH_TYPE="server"
[root@centos7-1 ~]# /var/ossec/bin/agent_control -i 001

Wazuh agent_control. Agent information:
   Agent ID:   001
   Agent Name: ab663cb5cc95
   IP address: any
   Status:     Active

   Operating system:    Linux |ab663cb5cc95 |5.19.0-41-generic |#42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 |x86_64
   Client version:      Wazuh v4.4.1
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1684412040

   Syscheck last started at:  Thu May 18 12:13:57 2023
   Syscheck last ended at:    Thu May 18 12:13:57 2023

[root@centos7-1 ~]# /var/ossec/bin/agent_upgrade -a 001

Upgrading...

Upgraded agents:
        Agent 001 upgraded: Wazuh v4.4.1 -> Wazuh v4.4.2
[root@centos7-1 ~]# /var/ossec/bin/agent_control -i 001

Wazuh agent_control. Agent information:
   Agent ID:   001
   Agent Name: ab663cb5cc95
   IP address: any
   Status:     Active

   Operating system:    Linux |ab663cb5cc95 |5.19.0-41-generic |#42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 |x86_64
   Client version:      Wazuh v4.4.2
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1684412189

   Syscheck last started at:  Thu May 18 12:15:50 2023
   Syscheck last ended at:    Thu May 18 12:15:51 2023
```

```console
root@ab663cb5cc95:/# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.4.1"
WAZUH_REVISION="40406"
WAZUH_TYPE="agent"
root@ab663cb5cc95:/# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.4.2"
WAZUH_REVISION="40408"
WAZUH_TYPE="agent"
root@ab663cb5cc95:/# cat /var/ossec/logs/upgrade.log
2023/05/18 12:15:44 - Generating Backup.
tar: ./var/ossec/queue/alerts/execq: socket ignored
tar: ./var/ossec/queue/alerts/cfgaq: socket ignored
tar: ./var/ossec/queue/sockets/wmodules: socket ignored
tar: ./var/ossec/queue/sockets/queue: socket ignored
tar: ./var/ossec/queue/sockets/logcollector: socket ignored
tar: ./var/ossec/queue/sockets/com: socket ignored
tar: ./var/ossec/queue/sockets/upgrade: socket ignored
tar: ./var/ossec/queue/sockets/syscheck: socket ignored
tar: ./var/ossec/queue/sockets/control: socket ignored
2023/05/18 12:15:45 - Upgrade started.

 Wazuh v4.4.2 (Rev. 40408) Installation Script - https://www.wazuh.com

 You are about to start the installation process of Wazuh.
 You must have a C compiler pre-installed in your system.

  - System: Linux ab663cb5cc95 5.19.0-41-generic (ubuntu 20.04)
  - User: root
  - Host: ab663cb5cc95


  -- Press ENTER to continue or Ctrl-C to abort. --

 - You already have Wazuh installed. Do you want to update it? (y/n): 
    - Installation will be made at  /var/ossec .

4- Installing the system

DIR="/var/ossec"
 - Running the Makefile

Stopping Wazuh...
agent
Wait for success...
success
Removing old SCA policies...
Installing SCA policies...


 - System is Debian (Ubuntu or derivative).
 - Init script modified to start Wazuh during boot.
Wait for success...
success
Starting Wazuh...
Starting Wazuh v4.4.2...
Started wazuh-execd...
Started wazuh-agentd...
Started wazuh-syscheckd...
Started wazuh-logcollector...
Started wazuh-modulesd...
Completed.

 - Configuration finished properly.

 - To start Wazuh:
      /var/ossec/bin/wazuh-control start

 - To stop Wazuh:
      /var/ossec/bin/wazuh-control stop

 - The configuration can be viewed or modified at /var/ossec/etc/ossec.conf


   Thanks for using Wazuh.
   Please don't hesitate to contact us if you need help or find
   any bugs.

   Use our public Mailing List at:
          https://groups.google.com/forum/#!forum/wazuh

   More information can be found at:
          - http://www.wazuh.com

    ---  Press ENTER to finish (maybe more information below). ---

 - Update completed.

2023/05/18 12:15:55 - Installation result = 0
2023/05/18 12:15:56 - Waiting connection... Status = connected. Remaining attempts: 29.
2023/05/18 12:15:56 - Connected to manager.
2023/05/18 12:15:56 - Upgrade finished successfully.
```
</details>

**Comment by rauldpm** [comment]
## Update report - Wazuh installation assistant

```
[root@centos7 vagrant]# curl -sO https://packages.wazuh.com/4.4/wazuh-install.sh && sudo bash ./wazuh-install.sh -a
18/05/2023 12:11:23 INFO: Starting Wazuh installation assistant. Wazuh version: 4.4.2
18/05/2023 12:11:23 INFO: Verbose logging redirected to /var/log/wazuh-install.log
18/05/2023 12:11:27 INFO: --- Dependencies ---
18/05/2023 12:11:27 INFO: Installing lsof.
18/05/2023 12:11:33 INFO: Wazuh repository added.
18/05/2023 12:11:33 INFO: --- Configuration files ---
18/05/2023 12:11:33 INFO: Generating configuration files.
18/05/2023 12:11:34 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
18/05/2023 12:11:34 INFO: --- Wazuh indexer ---
18/05/2023 12:11:34 INFO: Starting Wazuh indexer installation.
18/05/2023 12:12:39 INFO: Wazuh indexer installation finished.
18/05/2023 12:12:39 INFO: Wazuh indexer post-install configuration finished.
18/05/2023 12:12:39 INFO: Starting service wazuh-indexer.
18/05/2023 12:12:46 INFO: wazuh-indexer service started.
18/05/2023 12:12:46 INFO: Initializing Wazuh indexer cluster security settings.
18/05/2023 12:12:56 INFO: Wazuh indexer cluster initialized.
18/05/2023 12:12:56 INFO: --- Wazuh server ---
18/05/2023 12:12:56 INFO: Starting the Wazuh manager installation.
18/05/2023 12:13:25 INFO: Wazuh manager installation finished.
18/05/2023 12:13:25 INFO: Starting service wazuh-manager.
18/05/2023 12:13:36 INFO: wazuh-manager service started.
18/05/2023 12:13:36 INFO: Starting Filebeat installation.
18/05/2023 12:13:41 INFO: Filebeat installation finished.
18/05/2023 12:13:42 INFO: Filebeat post-install configuration finished.
18/05/2023 12:13:42 INFO: Starting service filebeat.
18/05/2023 12:13:42 INFO: filebeat service started.
18/05/2023 12:13:42 INFO: --- Wazuh dashboard ---
18/05/2023 12:13:42 INFO: Starting Wazuh dashboard installation.
18/05/2023 12:14:31 INFO: Wazuh dashboard installation finished.
18/05/2023 12:14:31 INFO: Wazuh dashboard post-install configuration finished.
18/05/2023 12:14:31 INFO: Starting service wazuh-dashboard.
18/05/2023 12:14:31 INFO: wazuh-dashboard service started.
18/05/2023 12:14:45 INFO: Initializing Wazuh dashboard web application.
18/05/2023 12:14:45 INFO: Wazuh dashboard web application initialized.
18/05/2023 12:14:45 INFO: --- Summary ---
18/05/2023 12:14:45 INFO: You can access the web interface https://<wazuh-dashboard-ip>
    User: admin
    Password: Mew3L2Tba9byR?stKa3PnhiUw6XWvWo3
18/05/2023 12:14:45 INFO: Installation finished.
```

**Comment by rauldpm** [comment]
## Update report - WPK Version files

- Linux

```
v4.4.2 92db4ada86760174a74630c670ed719f2d27f617
v4.4.1 88deb4d3211cb6f113d5fd91b750cd9dcb9a9dfd
v4.4.0 f9570187c20c410dc04f08bb968fac0efb243ac8
v4.3.11 40da76db3169eef483050539f87f46fd94dbb285
v4.3.10 ded48b7eb476dcb05f148d5faac15f2b795f13b3
v4.3.9 2f65f0491f413c6e40825b8f8044201802d4056b
v4.3.8 4568b9ef6984b0f7dc2d780e7dfad1a4ff71c74d
v4.3.7 050b06f42d09707cd60a4eefdaffa67cb8f8671d
v4.3.6 72b3e10095e3f6e0625968807ef58caca9fdb4cf
v4.3.5 b25b48ae20ef0527e922724a0eacc2973250e668
v4.3.4 e8fff13882137dddda16d24135f456928131a0ac
v4.3.3 5a57745cad4a8b90411059af8a26aa4763ddaf57
v4.3.2 c2cb4e25e59197b93ad23745cb8184e137e4b961
v4.3.1 6f102a985225e268f2277c5fedf7457f92ca4889
v4.3.0 3e851f9ec354d7f8df630c7cbb2c21bb7bfdf346
v4.2.7 33a5310828fa7190906a67d9a7d94d0ebeda1958
v4.2.6 c58b3425ac302c1ac752d7b67730e0483f4f3839
v4.2.5 c4c6083b0078bce19486e616139a9a41d63a8260
v4.2.4 e351c222c86baa0c5b165dd23a3ffd316872173f
v4.2.3 2b28ce23343c7eac2b33f1e2a7de2d2fdb6a069a
v4.2.2 dcce345d62f3197a875ca2c0905a9c58b8116eb9
v4.2.1 1329eb0414a358a6047d4875b073775c2fe876ee
v4.2.0 615b8a22b866d5dc3cfeee390ed3b1c937fa88a2
v4.1.5 43b45da34cf836647e9e43b718924e8b9989085e
v4.1.4 ad22231e9007d9db5f6faec2ec2c45b761060f34
v4.1.3 0c26544e7cfcefec95010ec67a72fcafffb362db
v4.1.2 bd8d85b1bb34302f4d9e839b4da7a74380fd208b
v4.1.1 874b9e9f32c1206ea7f7dc457b8070021560fc11
v4.1.0 a32c029440f288c3560e4f13cceee59623831457
v4.0.4 66a3d4e0b23cdc9a878a0d4e0b18cd43c2e956dd
v4.0.3 c0f5087cfe73811d7fd7d974f5bac534b9a865eb
v4.0.2 a7c32338cd09adbfa4831b1aaa1cf3c0db6b4fb8
v4.0.1 2fbf933f521fcd39982ad0ef20fb5a365c69bc76
v4.0.0 45e7cb448f9b220e1583d29ee3775fdade4fd40d
```

- macOS

```
v4.4.2 c388486ca63a9f951190f734130b2ff0d30e5462
v4.4.1 a8f04cf057e2ebfc8bd5a8d51a9c95f196ac23e7
v4.4.0 168a4dfed93c0f18bd422567797d1f5efb946633
v4.3.11 5d6585a8e2338963f41ba170d3961d34f7c385f0
v4.3.10 6f68bb0ef5c7b464225a2dc1cf155a8a6c07c3a6
v4.3.9 fd64867f777da0fb673998470939469ecc83c9d8
v4.3.8 51d6a2433e7d4a11781e2903724ad0715cdec900
v4.3.7 422936482d1a7e98a1f1a783e5f037c04bb27b02
v4.3.6 c78b4011b36b6897f5a4f60b43d63bfbc81d5393
v4.3.5 43bc0e1e89ee79e43577fcc6bea06cd736f3c837
v4.3.4 bfbe86c7200a451642f1bf48315cf8b6e28961ee
v4.3.3 417b1bfa355cb35c96e559c5ca7c824db4f4b82c
v4.3.2 d730841f1541fd0b2d1291a3c87694177ccea884
v4.3.1 b8c56018705f650bc20e0a74febcdf7ff30f76b2
v4.3.0 c0c2dc25f10bd9ad6fbc2d39f15573e108fd9b05
```

- Windows

```
v4.4.2 3c42dd4f29fffc8727c63eb4b3f8b8b1bb3bd700
v4.4.1 3bdfcaf5b0b53d413c7ad03c92f6b90dbfe247e4
v4.4.0 eaaabeec9378774be938b517ccdc6972b930554b
v4.3.11 e9ce2d15c40e06b0b80d6291b2d8808012dc7dfc
v4.3.10 22f90bb723bba3a8e07e218a8e2516c52d0fadb1
v4.3.9 2153ed12c34bc5bb111058e8bd2e4332c251cc62
v4.3.8 9144503b82882326e323d01209248fd83c90635e
v4.3.7 6209017b4a736bd9b1c15d8eae8fe2c4b2525b6c
v4.3.6 7cd2c6f3d36c2ca78913cd5bf7f1d11fd58cdae7
v4.3.5 d861d705486dafb7864e019dda5e48ff40dcbd39
v4.3.4 6fd757d5287d70cecdc02eca01e9104d38b19b5f
v4.3.3 9ffed615c93a6998c5ef2b537ab9bd8409ba4cfc
v4.3.2 ad2d315b9a40d323fca0855cdd23b5149104d5d6
v4.3.1 5474300682f0988289ad609d068f8de356dbe7d7
v4.3.0 707cd325afc9e0cdd1f9c28f1b807e86186ba78a
v4.2.7 0f9c3ee6dc686c7e546495f13869e87c6f477504
v4.2.6 7cd929524a7256f775ab03c04cc1cc74502441f9
v4.2.5 ab6fdaa12e31e2bfc3edc7a1e25c7c09d7c86ab9
v4.2.4 9dec2c6f2b95e492a87b6340a6884d39a32c9080
v4.2.3 2ca6c1d01099535f63f09a93a365033d78d171e2
v4.2.2 3f3531aa08fc5fb9f56d20e5040a16f6f79a6762
v4.2.1 d729bc67d3053721c921023b4c13f48fdd7fdaf8
v4.2.0 372788087117ae780c91f1529a0d88ebed112454
v4.1.5 93ca6375d60c73abfdba6aa18a7c3da6c70dd836
v4.1.4 bb6ffaab5b7ec8775aeca44412c76a957064ddd8
v4.1.3 56332e947df418fba5a75804575597a24f01164f
v4.1.2 66045f901a5cac64d03f745839438a8e7e4df13a
v4.1.1 c49cef08a275dec3bb601e6f537bdf61f8a41c15
v4.1.0 dbe7903835251e2aff242184d72342f94062dd38
v4.0.4 140c62494c1c93ae8f21459f3343bd0566a0af09
v4.0.3 b39b4806cc91b686412a0503f4443cb9bb995e47
v4.0.2 eef30470b1e3317471614756f9743a3b115aad84
v4.0.1 4041e9b2dd213ab253be84d6facb8e4f9d9067d5
v4.0.0 0937e27e8dbfb8146db153a4de25d7a93ee93fac
```

**Comment by rauldpm** [comment]
## Update report - Docker Hub

- https://hub.docker.com/layers/wazuh/wazuh-manager/4.4.2/images/sha256-a11bff08f8f27ae53d9a24c012315985fbc8a4ccad05e353009d85589cfbb708?context=explore
- https://hub.docker.com/layers/wazuh/wazuh-dashboard/4.4.2/images/sha256-80db5e3b5a195f04ab207f17bbcd4ff67226a67fe1a6c842abd38a66afc2f5dd?context=explore
- https://hub.docker.com/layers/wazuh/wazuh-indexer/4.4.2/images/sha256-72dcb45ae892fb538c45f2b733b05fb425409435be693144175391de187276b1?context=explore
