### ISSUE TITLE
Release 4.4.2 - RC 1 - E2E UX tests - Demo environment

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#16968]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           |Demo environment|
| **Category**            |Wazuh App|
| **Deployment option**   |Demo environment|
| **Previous testing issue**  |       None                          |
| **Main release issue**  |       https://github.com/wazuh/wazuh/issues/16966                  |
| **Main E2E UX test issue** |https://github.com/wazuh/wazuh/issues/16965|
| **Release candidate #** |                RC 1                          |

## Test description

- [x]  (**T1**): - No errors or warnings found in logs
- [x]  (**T2**): - The daemons are running with the correct user
- [x]  (**T3**): - The status of the Wazuh Indexer clusters is as expected.
- [x]  (**T4**): - No errors in the browser's developer console when browsing the App
- [x]  (**T5**): - Alerts are being generated for each of the modules configured for this purpose
- [x]  (**T6**): - No warning symbols in Discover when expanding a document
- [x]  (**T7**): - Alert generated
- [x] (**T8**): - Search works without specifying a field and using `*`

## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed result. |
| :yellow_circle:  | There is at least one expected failure or skipped test and no failures. |

## Conclusions

**Detected and previously reported issues:**
- https://github.com/wazuh/wazuh/issues/16981
- https://github.com/wazuh/wazuh-kibana-app/issues/4092
- https://github.com/wazuh/wazuh-kibana-app/issues/4108
- https://github.com/wazuh/wazuh-kibana-app/issues/4074
- https://github.com/wazuh/wazuh-kibana-app/issues/4232

**Detected and opened issues:**

- https://github.com/wazuh/wazuh-kibana-app/issues/5418
- https://github.com/wazuh/wazuh-automation/issues/1113

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| 🔴    | No errors or warnings found in logs |  Windows agent |   |
| 🟢   | The daemons are running with the correct user  |  |   |
| 🟢   | The status of the Wazuh Indexer clusters is as expected  | |   |
| 🟡  | No errors in the browser's developer console when browsing the App |  |   |
| 🟡 | Alerts are being generated for each of the modules configured for this purpose | |  |
| 🟢  | No warning symbols in Discover when expanding a document |  ||
| 🟢 | Generate an alert and check it in the web UI | |   |
| 🟢  | Search works without specifying a field and using `*` |  |  |

## Auditors' validation

The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @juliamagan 
- [x] @teddytpc1 
- [x] @davidjiglesias

**Comment by BelenValdivia** [comment]
## Task 1: No errors or warnings found in logs

**Comment by BelenValdivia** [comment]
### Task 2: The daemons are running with the correct user

**Comment by BelenValdivia** [comment]
### The status of the Wazuh Indexer clusters is as expected 🟢 

```
$ curl -k -u USER:PASS https://IP:9200/_cat/nodes?v
ip         heap.percent ram.percent cpu load_1m load_5m load_15m node.role node.roles                                        cluster_manager name
10.0.2.138           52          63   0    0.06    0.05     0.01 dimr      cluster_manager,data,ingest,remote_cluster_client -               node-1
10.0.2.121            9          66   1    0.06    0.03     0.00 dimr      cluster_manager,data,ingest,remote_cluster_client *               node-2
10.0.0.34            54          51   1    0.08    0.02     0.01 dimr      cluster_manager,data,ingest,remote_cluster_client -               node-7
10.0.2.101           29          64   0    0.00    0.00     0.00 dimr      cluster_manager,data,ingest,remote_cluster_client -               node-3

```

**Comment by BelenValdivia** [comment]
### Task 4: No errors in the browser's developer console when browsing the App 🔴 

- [Uncaught TypeError: bounds is null](https://github.com/wazuh/wazuh-kibana-app/issues/5418)

**Comment by BelenValdivia** [comment]
## Alerts are being generated for each of the modules configured for this purpose

**Comment by BelenValdivia** [comment]
### Task 6: No warning symbols in Discover when expanding a document 🟢 

After performing several tests both in Discover and in different modules, we have not been able to find any warning.

**Comment by BelenValdivia** [comment]
## Task 7: Generate an alert and check it in the web UI 🟢 

1. Generate alert
```
ssh invalid-user@centos.wazuh.info
invalid-user@centos.wazuh.info's password: 
Permission denied, please try again.
invalid-user@centos.wazuh.info's password: 
Permission denied, please try again.
invalid-user@centos.wazuh.info's password: 
invalid-user@centos.wazuh.info: Permission denied 
```
2. Check if the alerts are in the Dashboard
![brute force centos task 7](https://user-images.githubusercontent.com/26927338/236196374-e78d1217-5a2b-4a9c-baf0-d4f24c8a48d3.png)

<details><summary>Alert info</summary>

  ```
  {
    "_index": "wazuh-alerts-4.x-env-1-2023.05.03",
    "_id": "FQzE44cBLtBEmgIeAwRH",
    "_version": 1,
    "_score": null,
    "_source": {
      "predecoder": {
        "hostname": "ip-10-0-1-15",
        "program_name": "sshd",
        "timestamp": "May  3 22:38:03"
      },
      "cluster": {
        "node": "master",
        "name": "wazuh1"
      },
      "agent": {
        "ip": "10.0.1.15",
        "name": "Centos",
        "id": "002"
      },
      "previous_output": "May  3 22:38:02 ip-10-0-1-15 sshd[10711]: Failed password for invalid user invalid-user from 52.52.161.198 port 33688 ssh2\nMay  3 22:38:02 ip-10-0-1-15 sshd[10711]: Failed none for invalid user invalid-user from 52.52.161.198 port 33688 ssh2\nMay  3 22:38:01 ip-10-0-1-15 sshd[10711]: Invalid user invalid-user from 52.52.161.198 port 33688\nMay  3 22:37:59 ip-10-0-1-15 sshd[10709]: Failed password for invalid user invalid-user from 52.52.161.198 port 33686 ssh2\nMay  3 22:37:58 ip-10-0-1-15 sshd[10709]: Failed password for invalid user invalid-user from 52.52.161.198 port 33686 ssh2\nMay  3 22:37:55 ip-10-0-1-15 sshd[10709]: Failed none for invalid user invalid-user from 52.52.161.198 port 33686 ssh2\nMay  3 22:37:54 ip-10-0-1-15 sshd[10709]: Invalid user invalid-user from 52.52.161.198 port 33686",
      "data": {
        "srcuser": "invalid-user",
        "srcip": "52.52.161.198"
      },
      "manager": {
        "name": "wazuh-manager-master-0"
      },
      "rule": {
        "mail": false,
        "level": 10,
        "hipaa": [
          "164.312.b"
        ],
        "pci_dss": [
          "11.4",
          "10.2.4",
          "10.2.5"
        ],
        "tsc": [
          "CC6.1",
          "CC6.8",
          "CC7.2",
          "CC7.3"
        ],
        "description": "sshd: brute force trying to get access to the system. Non existent user.",
        "groups": [
          "syslog",
          "sshd",
          "authentication_failures"
        ],
        "nist_800_53": [
          "SI.4",
          "AU.14",
          "AC.7"
        ],
        "frequency": 8,
        "gdpr": [
          "IV_35.7.d",
          "IV_32.2"
        ],
        "firedtimes": 6,
        "mitre": {
          "technique": [
            "Brute Force"
          ],
          "id": [
            "T1110"
          ],
          "tactic": [
            "Credential Access"
          ]
        },
        "id": "5712"
      },
      "decoder": {
        "parent": "sshd",
        "name": "sshd"
      },
      "full_log": "May  3 22:38:03 ip-10-0-1-15 sshd[10711]: Failed password for invalid user invalid-user from 52.52.161.198 port 33688 ssh2",
      "input": {
        "type": "log"
      },
      "location": "/var/log/secure",
      "id": "1683153484.1965107952",
      "GeoLocation": {
        "city_name": "San Jose",
        "country_name": "United States",
        "region_name": "California",
        "location": {
          "lon": -121.8914,
          "lat": 37.3388
        }
      },
      "timestamp": "2023-05-03T22:38:04.458+0000"
    },
    "fields": {
      "timestamp": [
        "2023-05-03T22:38:04.458Z"
      ]
    },
    "highlight": {
      "cluster.name": [
        "@opensearch-dashboards-highlighted-field@wazuh1@/opensearch-dashboards-highlighted-field@"
      ],
      "agent.id": [
        "@opensearch-dashboards-highlighted-field@002@/opensearch-dashboards-highlighted-field@"
      ]
    },
    "sort": [
      1683153484458
    ]
  }
  ```
</details>

**Comment by BelenValdivia** [comment]
## Task 8: Search works without specifying a field and using `*` 🟢 

1. `*`

![task 8 with ast 1](https://user-images.githubusercontent.com/26927338/236224001-4af4e196-7b36-49f5-b27a-569f107fc3c3.png)

2. `osq*`

![task 8 with ast 2](https://user-images.githubusercontent.com/26927338/236224329-633ae27e-d587-41be-a2ab-aaf144c79b85.png)

3. `*ery*`

![task 8 with ast 3](https://user-images.githubusercontent.com/26927338/236224638-3d76b008-0cc4-42d4-b5c0-1da92907bf58.png)

4. `*ocker`

![task 8 with ast 4](https://user-images.githubusercontent.com/26927338/236224763-c6b72a18-5184-4a8c-818a-bc9f21b1c963.png)


![task 8 with ast 5](https://user-images.githubusercontent.com/26927338/236224805-abcef664-1990-4cc6-ad1f-4a219a2a6247.png)
