### ISSUE TITLE
 Change primary interface lookup to report IP used to connect to the Wazuh manager

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#16985]
## Description
Currently, the Wazuh agent uses a mechanism to find the primary interface, which can be problematic in some environments. This issue aims to change the behavior to report the IP used by the agent to connect to the manager instead. 

As this is a change in definition, it's important to note that users who need to obtain a complete list of available interfaces/IPs/etc. in an environment can use the information collected by syscollector.

## Task List
- [x] Update the agent code to report the IP used to connect to the manager.
- [x] Update documentation to reflect the new behavior if necessary
- [x] Test the changes in different environments to ensure compatibility
- [x] Add Unit tests.
- [x] ~~Add component tests.~~ Legacy code.
- [ ] Add Integration tests.

## Expected Result
After these changes are implemented, the Wazuh agent will report the IP used to connect to the manager in the agent list.

## Additional Notes
Required feature approvals.
- [x] @santiago-bassett 
- [x] @havidarou

**Comment by Dwordcito** [comment]
## Development notes.

- [ ] Get the source address of agt->sock in run_notify()
- [ ] Replace the call of get_agent_ip() in run_notify function with the new way to get the connection IP address.
- [ ] NO REMOVE the wm_control (IPC) and the windows implementation, because log collector currently uses this mechanism in host_ip field https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/localfile.html#out-format

**Comment by Dwordcito** [comment]
@tdrauncieal move the PR to 4.5.0.


CC @havidarou and @santiago-bassett
