### ISSUE TITLE
Fetch NVD API feeds (CVEs & CPEs)

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#17055]
## Description

To change the feeds that are going to be deprecated by the new ones of the API 2.0 in the NVD, it is necessary to generate a new feed that allows us not to be limited by the API rate limit, and for that we will generate a feed for the CVEs and another one for the CPEs, which contain all the available information and that we simply have to download from the Wazuh's manager to insert it in the vulnerability databases.  

The feeds offered by the NVD are distributed from the API 2.0 in JSON format:
- CVE: `https://services.nvd.nist.gov/rest/json/cves/2.0` ([documentation](https://nvd.nist.gov/developers/vulnerabilities))
- CPE: `https://services.nvd.nist.gov/rest/json/cpes/2.0` ([documentation](https://nvd.nist.gov/developers/products))

However, the results of the number of objects returned by the API is limited to 2000 for CVEs and 10000 for CPEs, so it is necessary to make several requests and merge the results into a single feed for each case. So we will get feeds that will have a list of JSON objects with the following schemas:

<details><summary>CVE API Schema</summary>

```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "JSON Schema for NVD Vulnerability Data API version 2.0",
	"definitions": {
		"def_cve_item": {
			"properties": {
				"cve": {"$ref": "#/definitions/cve_item"}
			},
			"required": ["cve"],
			"additionalProperties": false
		},
		"cve_item": {
			"type": "object",
			"properties": {
				"id": { "$ref": "#/definitions/cve_id" },
				"sourceIdentifier": { "type": "string" },
				"vulnStatus": { "type": "string" },
				"published": {"type": "string", "format": "date-time"},
				"lastModified": {"type": "string", "format": "date-time"},
				"evaluatorComment": {"type": "string"},
				"evaluatorSolution": {"type": "string"},
				"evaluatorImpact": {"type": "string"},
				"cisaExploitAdd": {"type": "string", "format": "date"},
				"cisaActionDue": {"type": "string", "format": "date"},
				"cisaRequiredAction": {"type": "string"},
				"cisaVulnerabilityName": {"type": "string"},
				"descriptions": {
				  "type": "array",
				  "minItems": 1,
				  "items": {"$ref": "#/definitions/lang_string"}
				},
				"references": {
				  "type": "array",
				  "items": { "$ref": "#/definitions/reference" },
				  "maxItems": 500,
				  "minItems": 0
				},
				"metrics": {
					"description": "Metric scores for a vulnerability as found on NVD.",
					"type": "object",
					"properties": {
						"cvssMetricV31": {
							"description": "CVSS V3.1 score.",
							"type": "array",
							"items": {"$ref": "#/definitions/cvss-v31"}
						},
						"cvssMetricV30": {
							"description": "CVSS V3.0 score.",
							"type": "array",
							"items": {"$ref": "#/definitions/cvss-v30"}
						},
						"cvssMetricV2": {
							"description": "CVSS V2.0 score.",
							"type": "array",
							"items": {"$ref": "#/definitions/cvss-v2"}
						}
					},
					"additionalProperties": false
				},
				"weaknesses": {
				  "type": "array",
				  "items": { "$ref": "#/definitions/weakness" }
				},
				"configurations": {
				  "type": "array",
				  "items": { "$ref": "#/definitions/config" }
				},
				"vendorComments": {
					"type": "array",
					"items": { "$ref": "#/definitions/vendorComment" }
				}
			},
			"required": [ "id", "published", "lastModified", "references", "descriptions" ],
			"additionalProperties": false
		},
		
		"cvss-v2": {
			"properties": {
				"source": {"type": "string"},
				"type": {"enum": ["Primary", "Secondary"]},
				"cvssData": {"$ref": "//csrc.nist.gov/schema/nvd/api/2.0/external/cvss-v2.0.json" },
				"baseSeverity": {"type": "string"},
				"exploitabilityScore": {"$ref": "#/definitions/def_subscore"},
				"impactScore": {"$ref": "#/definitions/def_subscore"},
				"acInsufInfo": {"type": "boolean"},
				"obtainAllPrivilege": {"type": "boolean"},
				"obtainUserPrivilege": {"type": "boolean"},
				"obtainOtherPrivilege": {"type": "boolean"},
				"userInteractionRequired": {"type": "boolean"}
			},
			"required": [ "source", "type", "cvssData" ],
			"additionalProperties": false
		},
				
		"cvss-v30": {
			"properties": {
				"source": {"type": "string"},
				"type": {"enum": ["Primary", "Secondary"]},
				"cvssData": {"$ref": "//csrc.nist.gov/schema/nvd/api/2.0/external/cvss-v3.0.json" },
				"exploitabilityScore": { "$ref": "#/definitions/def_subscore" },
				"impactScore": { "$ref": "#/definitions/def_subscore" }
			},
			"required": [ "source", "type", "cvssData" ],
			"additionalProperties": false
		},
		
		"cvss-v31": {
			"properties": {
				"source": {"type": "string"},
				"type": {"enum": ["Primary", "Secondary"]},
				"cvssData": {"$ref": "//csrc.nist.gov/schema/nvd/api/2.0/external/cvss-v3.1.json" },
				"exploitabilityScore": { "$ref": "#/definitions/def_subscore" },
				"impactScore": { "$ref": "#/definitions/def_subscore" }
			},
			"required": [ "source", "type", "cvssData" ],
			"additionalProperties": false
		},
				
		"cve_id": {
		  "type": "string",
		  "pattern": "^CVE-[0-9]{4}-[0-9]{4,}$"
		},
		"lang_string": {
		  "type": "object",
		  "properties": {
			"lang": { "type": "string" },
			"value": { "type": "string", "maxLength": 4096 }
		  },
		  "required": [ "lang", "value" ],
		  "additionalProperties": false
		},
		"reference": {
		  "type": "object",
		  "properties": {
			"url": {
			  "maxLength": 500,
			  "type": "string",
			  "pattern": "^(ftp|http)s?://\\S+$"
			},
			"source": {"type": "string"},
			"tags":{
				"type": "array", 
				"items": {"type": "string"}
			}
		  },
		  "required": [ "url" ],
		  "additionalProperties": false
		},
		"vendorComment": {
			"type": "object",
			"properties": {
				"organization": {"type": "string"},
				"comment": {"type": "string"},
				"lastModified": {"type": "string", "format": "date-time"}
			},
			"required": [ "organization", "comment", "lastModified" ],
			"additionalProperties": false
		},
		"weakness": {
			"properties": {
				"source": {"type": "string"},
				"type": {"type": "string"},
				"description": {
					"type": "array",
					"minItems": 0,
					"items": { "$ref": "#/definitions/lang_string" }
				}
			},
			"required": [ "source", "type", "description" ],
			"additionalProperties": false
		},
		"config": {
			"properties": {
				"operator": {"type": "string", "enum": [ "AND", "OR"] },
				"negate": {"type": "boolean"},
				"nodes": { "type": "array", "items": {"$ref": "#/definitions/node"}}
			},
			"required": ["nodes"],
			"additionalProperties": false
		},
		"node": {
			"description": "Defines a configuration node in an NVD applicability statement.",
			"properties": {
				"operator": {"type": "string", "enum": [ "AND", "OR"] },
				"negate": {"type": "boolean"},
				"cpeMatch": {
					"type": "array",
					"items": {"$ref": "#/definitions/cpe_match"}
				}
			},
			"required": ["operator", "cpeMatch"],
			"additionalProperties": false
		},
		"cpe_match": {
			"description": "CPE match string or range",
			"type": "object",
			"properties": {
				"vulnerable": {"type": "boolean"},
				"criteria": {"type": "string"},
				"matchCriteriaId": {"type": "string", "format": "uuid"},
				"versionStartExcluding": {"type": "string"},
				"versionStartIncluding": {"type": "string"},
				"versionEndExcluding": {"type": "string"},
				"versionEndIncluding": {"type": "string"}
			},
			"required": ["vulnerable", "criteria", "matchCriteriaId"],
			"additionalProperties": false
		},
		"def_subscore": {
            "description": "CVSS subscore.",
            "type": "number",
            "minimum": 0,
            "maximum": 10
        }
	},
	
    "type": "object",
    "properties": {
		"resultsPerPage": {"type": "integer"},
		"startIndex": {"type": "integer"},
		"totalResults": {"type": "integer"},
        "format": {"type": "string"},
        "version": {"type": "string"},
        "timestamp": {"type": "string", "format": "date-time"},
        "vulnerabilities": {
            "description": "NVD feed array of CVE",
            "type": "array",
            "items": {"$ref": "#/definitions/def_cve_item"}
        }
    },
    "required": [
        "resultsPerPage",
		"startIndex",
		"totalResults",
		"format",
		"version",
		"timestamp",
        "vulnerabilities"
    ],
	"additionalProperties":false
}
```
</details>

<details><summary>CPE API Schema</summary>

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "JSON Schema for NVD Common Product Enumeration (CPE) API version 2.0",
  "$id": "https://csrc.nist.gov/schema/nvd/api/2.0/cpe_api_json_2.0.schema",
  "definitions": {
    "defTitle": {
      "description": "Human readable title for CPE",
      "type": "object",
      "properties": {
        "title": {"type": "string"},
        "lang": {"type": "string"}
      },
      "required": ["title", "lang"],
	  "additionalProperties": false
    },
    "defReference": {
      "description": "Internet resource for CPE",
      "type": "object",
      "properties": {
		"ref": {
          "type": "string",
          "pattern": "^([A-Za-z][A-Za-z0-9+.-]+):(\\/\\/([^@]+@)?([A-Za-z0-9.\\-_~]+)(:\\d+)?)?((?:[A-Za-z0-9-._~]|%[A-Fa-f0-9]|[!$&'\\[\\]()*+,;=:@])+(?:\\/(?:[A-Za-z0-9-._~]|%[A-Fa-f0-9]|[!$&'\\[\\]()*+,;=:@])*)*|(?:\\/(?:[A-Za-z0-9-._~]|%[A-Fa-f0-9]|[!$&'()*+,;=:@])+)*)?(\\?(?:[A-Za-z0-9-._~]|%[A-Fa-f0-9]|[!$&'\\[\\]()*+,;=:@]|[/?])*)?(\\#(?:[A-Za-z0-9-._~]|%[A-Fa-f0-9]|[!$&'\\[\\]()*+,;=:@]|[/?])*)?$"
        },
        "type": {
          "type": "string",
          "enum": [
            "Advisory",
            "Change Log",
            "Product",
            "Project",
            "Vendor",
            "Version"
          ]
        }
      },
      "required": ["ref"],
	  "additionalProperties": false
    },
	
	"defCpe": {
		"type": "object",
		"properties": {
			"cpe": {
			  "type": "object",
			  "properties": {
				"deprecated" : {"type" : "boolean"},
				"cpeName": {"type": "string"},
				"cpeNameId": {"type": "string", "format": "uuid"},
				"created": {"type": "string", "format": "date-time"},
				"lastModified": {"type": "string", "format": "date-time"},
				"titles": {
				  "type": "array",
				  "items": {"$ref": "#/definitions/defTitle"}
				},
				"refs": {
				  "type": "array",
				  "items": {"$ref": "#/definitions/defReference"}
				},
				"deprecatedBy": {
				  "type": "array",
				  "items": {
					"type": "object",
					"properties": {
						"cpeName": {"type": "string"},
						"cpeNameId": {"type": "string", "format": "uuid"}
					}
				  }
				},
				"deprecates": {
				  "type": "array",
				  "items": {
					"type": "object",
					"properties": {
						"cpeName": {"type": "string"},
						"cpeNameId": {"type": "string", "format": "uuid"}
					}
				  }
				}
			  },
			  "required": ["cpeName", "cpeNameId", "deprecated", "lastModified", "created"],
			  "additionalProperties": false
			}
		},
		"required": ["cpe"],
		"additionalProperties": false
	}

  },
  "type": "object",
  "properties": {
	"resultsPerPage": {"type": "integer"},
	"startIndex": {"type": "integer"},
	"totalResults": {"type": "integer"},
    "format": {"type": "string"},
    "version": {"type": "string"},
    "timestamp": {"type": "string", "format": "date-time"},
    "products": {
      "description": "NVD feed array of CPE",
      "type": "array",
      "items": {"$ref": "#/definitions/defCpe"}
    }
  },
  "required": [
	"resultsPerPage",
	"startIndex",
	"totalResults",
    "format",
    "version",
	"timestamp",
    "products"
  ],
  "additionalProperties": false
}
```
</details>

So, it will be necessary a first collection of all the CVEs and CPEs, to have both feeds with all the current information, and from this point, we will have to make requests every X hours to know the changes that have been made in the feeds in that time interval. The results that appear in this request will be added (new) or overwritten (already existing) in the feeds.

Finally, to avoid that all this information is collected at runtime, we are going to create these feeds using scripts and then store them in feed.wazuh.com.

To avoid problems of limitations in the first download of the feed, we intend to do the following:
- First, we are going to create a script to generate a first complete feed of the NVD (one feed for the CVEs and another for the CPEs) that will be uploaded to our URL: https://feed.wazuh.com/vulnerability-detector/
- It will be necessary to create the Jenkins pipeline to automatically update both feeds, using the generated script.
- Once we have the complete feed, we will modify the Vulnerability Detector code to download the feeds and start parsing them.

### Tasks

- [x] Get an API key
- [x] Create NVD feed generation script
- [x] The new feed must contain all the CVEs and CPEs available in the API
- [x] The script must be able to either generate the feed from 0, or if you add an existing feed by parameter, it must be able to get the last timestamp and update it with the new information
- [x] The output feeds should be uploaded to feed.wazuh.com in GZIP format
- [x] A metadata file should be created including the following information of the feed
```
lastModifiedDate:2021-04-16T16:31:41+00:00
size:67988152
gzSize:1431315
sha256:86e248c6246e4e5d12384230f633ca025f9e224438280c99161bf833a1c75da7
version:1
```

**Comment by vikman90** [comment]
This issue is blocked by https://github.com/wazuh/wazuh-jenkins/issues/5219.
