### ISSUE TITLE
Release 4.4.2 - RC 2 - E2E UX tests - Demo environment

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh#17129]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           |Demo environment|
| **Category**            |Wazuh App|
| **Deployment option**   |Demo environment|
| **Previous testing issue**  |       None                          |
| **Main release issue**  |      https://github.com/wazuh/wazuh/issues/17004 |
| **Main E2E UX test issue** |https://github.com/wazuh/wazuh/issues/17005|
| **Release candidate #** |                RC 2                         |

## Test description

- [x]  (**T1**): - No errors or warnings found in logs
- [x]  (**T2**): - The daemons are running with the correct user
- [x]  (**T3**): - The status of the Wazuh Indexer clusters is as expected.
- [x]  (**T4**): - No errors in the browser's developer console when browsing the App
- [x]  (**T5**): - Alerts are being generated for each of the modules configured for this purpose
- [x]  (**T6**): - No warning symbols in Discover when expanding a document
- [x]  (**T7**): - Alert generated
- [x] (**T8**): - Search works without specifying a field and using `*`

## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed result. |
| :yellow_circle:  | There is at least one expected failure or skipped test and no failures. |

## Conclusions

**Detected and previously reported issues:**

- https://github.com/wazuh/wazuh-kibana-app/issues/4092
- https://github.com/wazuh/wazuh-kibana-app/issues/4108
- https://github.com/wazuh/wazuh-kibana-app/issues/4074
- https://github.com/wazuh/wazuh-kibana-app/issues/4232
- https://github.com/wazuh/wazuh-automation/issues/1113
- https://github.com/wazuh/wazuh-kibana-app/issues/4232

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| 🟡   | No errors or warnings found in logs |   |   |
|  🟢   | The daemons are running with the correct user  |  |   |
|  🟢   | The status of the Wazuh Indexer clusters is as expected  | |   |
|  🟡   | No errors in the browser's developer console when browsing the App |  |   |
|  🟡  | Alerts are being generated for each of the modules configured for this purpose | |  |
|  🟢  | No warning symbols in Discover when expanding a document |  ||
|  🟢  | Generate an alert and check it in the web UI | |   |
| 🟢   | Search works without specifying a field and using `*` |  |  |

## Auditors' validation

The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @damarisg 
- [x] @teddytpc1 
- [x] @davidjiglesias

**Comment by BelenValdivia** [comment]
## Task 1: No errors or warnings found in logs - WIP 

### Agents

<details>
<summary>Amazon Linux :green_circle:  </summary>

- `journalctl -xe -u wazuh-agent.service`:

    ```
    -- Unit wazuh-agent.service has finished shutting down.
    -- Reboot --
    may 16 12:06:17 ip-x.x.x.x.us-west-1.compute.internal systemd[1]: Starting Wazuh agent...
    -- Subject: Unit wazuh-agent.service has begun start-up
    -- Defined-By: systemd
    -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
    -- 
    -- Unit wazuh-agent.service has begun starting up.
    may 16 12:06:17 ip-x.x.x.x.us-west-1.compute.internal env[2415]: Starting Wazuh v4.4.2...
    may 16 12:06:18 ip-x.x.x.x.us-west-1.compute.internal env[2415]: Started wazuh-execd...
    may 16 12:06:21 ip-x.x.x.x.us-west-1.compute.internal env[2415]: Started wazuh-agentd...
    may 16 12:06:22 ip-x.x.x.x.us-west-1.compute.internal env[2415]: Started wazuh-syscheckd...
    may 16 12:06:23 ip-x.x.x.x.us-west-1.compute.internal env[2415]: Started wazuh-logcollector...
    may 16 12:06:24 ip-x.x.x.x.us-west-1.compute.internal env[2415]: Started wazuh-modulesd...
    may 16 12:06:24 ip-x.x.x.x.us-west-1.compute.internal crontab[2667]: (root) LIST (root)
    may 16 12:06:26 ip-x.x.x.x.us-west-1.compute.internal env[2415]: Completed.
    may 16 12:06:26 ip-x.x.x.x.us-west-1.compute.internal systemd[1]: Started Wazuh agent.
    -- Subject: Unit wazuh-agent.service has finished start-up
    -- Defined-By: systemd
    -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
    -- 
    -- Unit wazuh-agent.service has finished starting up.
    -- 
    -- The start-up result is done.
    
    ```

    
- `egrep -i "ERROR|WARNING" /var/ossec/logs/ossec.log`:

    ```
    ```

- `systemctl status wazuh-agent -l`:

    ```
     ● wazuh-agent.service - Wazuh agent
       Loaded: loaded (/usr/lib/systemd/system/wazuh-agent.service; enabled; vendor preset: disabled)
       Active: active (running) since mar 2023-05-16 12:06:26 UTC; 15min ago
      Process: 2415 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/SUCCESS)
       CGroup: /system.slice/wazuh-agent.service
               ├─2486 /var/ossec/bin/wazuh-execd
               ├─2530 /var/ossec/bin/wazuh-agentd
               ├─2545 /var/ossec/bin/wazuh-syscheckd
               ├─2559 /var/ossec/bin/wazuh-logcollector
               └─2577 /var/ossec/bin/wazuh-modulesd
    
    may 16 12:06:17 ip-x.x.x.x.us-west-1.compute.internal systemd[1]: Starting Wazuh agent...
    may 16 12:06:17 ip-x.x.x.x.us-west-1.compute.internal env[2415]: Starting Wazuh v4.4.2...
    may 16 12:06:18 ip-x.x.x.x.us-west-1.compute.internal env[2415]: Started wazuh-execd...
    may 16 12:06:21 ip-x.x.x.x.us-west-1.compute.internal env[2415]: Started wazuh-agentd...
    may 16 12:06:22 ip-x.x.x.x.us-west-1.compute.internal env[2415]: Started wazuh-syscheckd...
    may 16 12:06:23 ip-x.x.x.x.us-west-1.compute.internal env[2415]: Started wazuh-logcollector...
    may 16 12:06:24 ip-x.x.x.x.us-west-1.compute.internal env[2415]: Started wazuh-modulesd...
    may 16 12:06:24 ip-x.x.x.x.us-west-1.compute.internal crontab[2667]: (root) LIST (root)
    may 16 12:06:26 ip-x.x.x.x.us-west-1.compute.internal env[2415]: Completed.
    may 16 12:06:26 ip-x.x.x.x.us-west-1.compute.internal systemd[1]: Started Wazuh agent.
    ```   
- `/var/ossec/bin/wazuh-control status`:

    ```
    wazuh-modulesd is running...
    wazuh-logcollector is running...
    wazuh-syscheckd is running...
    wazuh-agentd is running...
    wazuh-execd is running...
    ```

</details>

<details>
<summary>RHEL :green_circle:</summary>

- `journalctl -xe -u wazuh-agent.service`:

    ```
    -- Logs begin at mar 2023-05-16 12:31:11 UTC, end at mar 2023-05-16 12:32:24 UTC. --
    may 16 12:31:23 ip-10-0-1-240.us-west-1.compute.internal systemd[1]: Starting Wazuh agent...
    -- Subject: Unit wazuh-agent.service has begun start-up
    -- Defined-By: systemd
    -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
    -- 
    -- Unit wazuh-agent.service has begun starting up.
    may 16 12:31:23 ip-10-0-1-240.us-west-1.compute.internal env[1173]: Starting Wazuh v4.4.2...
    may 16 12:31:24 ip-10-0-1-240.us-west-1.compute.internal env[1173]: Started wazuh-execd...
    may 16 12:31:27 ip-10-0-1-240.us-west-1.compute.internal env[1173]: Started wazuh-agentd...
    may 16 12:31:28 ip-10-0-1-240.us-west-1.compute.internal env[1173]: Started wazuh-syscheckd...
    may 16 12:31:29 ip-10-0-1-240.us-west-1.compute.internal env[1173]: Started wazuh-logcollector...
    may 16 12:31:30 ip-10-0-1-240.us-west-1.compute.internal osqueryd[1722]: osqueryd started [version=4.4.0]
    may 16 12:31:31 ip-10-0-1-240.us-west-1.compute.internal env[1173]: Started wazuh-modulesd...
    may 16 12:31:32 ip-10-0-1-240.us-west-1.compute.internal crontab[1815]: (root) LIST (root)
    may 16 12:31:33 ip-10-0-1-240.us-west-1.compute.internal env[1173]: Completed.
    may 16 12:31:33 ip-10-0-1-240.us-west-1.compute.internal systemd[1]: Started Wazuh agent.
    -- Subject: Unit wazuh-agent.service has finished start-up
    -- Defined-By: systemd
    -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
    -- 
    -- Unit wazuh-agent.service has finished starting up.
    -- 
    -- The start-up result is done.
    ```

- `egrep -i "ERROR|WARNING" /var/ossec/logs/ossec.log`:

    ```
    ```

- `systemctl status wazuh-agent -l`:

    ```
    ● wazuh-agent.service - Wazuh agent
       Loaded: loaded (/usr/lib/systemd/system/wazuh-agent.service; enabled; vendor preset: disabled)
       Active: active (running) since mar 2023-05-16 12:33:49 UTC; 1min 45s ago
      Process: 2921 ExecStop=/usr/bin/env /var/ossec/bin/wazuh-control stop (code=exited, status=0/SUCCESS)
      Process: 3008 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/SUCCESS)
        Tasks: 52
       Memory: 1019.6M
       CGroup: /system.slice/wazuh-agent.service
               ├─3035 /var/ossec/bin/wazuh-execd
               ├─3047 /var/ossec/bin/wazuh-agentd
               ├─3062 /var/ossec/bin/wazuh-syscheckd
               ├─3075 /var/ossec/bin/wazuh-logcollector
               ├─3099 /var/ossec/bin/wazuh-modulesd
               ├─3109 python3 wodles/docker/DockerListener
               ├─3112 /usr/bin/osqueryd --config_path=/etc/osquery/osquery.conf
               └─3119 /usr/bin/osqueryd                                        
    
    may 16 12:33:41 ip-10-0-1-240.us-west-1.compute.internal systemd[1]: Starting Wazuh agent...
    may 16 12:33:41 ip-10-0-1-240.us-west-1.compute.internal env[3008]: Starting Wazuh v4.4.2...
    may 16 12:33:43 ip-10-0-1-240.us-west-1.compute.internal env[3008]: Started wazuh-execd...
    may 16 12:33:44 ip-10-0-1-240.us-west-1.compute.internal env[3008]: Started wazuh-agentd...
    may 16 12:33:45 ip-10-0-1-240.us-west-1.compute.internal env[3008]: Started wazuh-syscheckd...
    may 16 12:33:46 ip-10-0-1-240.us-west-1.compute.internal env[3008]: Started wazuh-logcollector...
    may 16 12:33:46 ip-10-0-1-240.us-west-1.compute.internal osqueryd[3112]: osqueryd started [version=4.4.0]
    may 16 12:33:47 ip-10-0-1-240.us-west-1.compute.internal env[3008]: Started wazuh-modulesd...
    may 16 12:33:49 ip-10-0-1-240.us-west-1.compute.internal env[3008]: Completed.
    ```
 
- `/var/ossec/bin/wazuh-control status`:

    ```
    wazuh-modulesd is running...
    wazuh-logcollector is running...
    wazuh-syscheckd is running...
    wazuh-agentd is running...
    wazuh-execd is running...
    ```
</details>

**Comment by BelenValdivia** [comment]
## Task 3: The status of the Wazuh Indexer clusters is as expected 🟢 

```
$ curl -k -u USER:PASS https://IP:9200/_cat/nodes?v
ip         heap.percent ram.percent cpu load_1m load_5m load_15m node.role node.roles                                        cluster_manager name
x.x.x.x           40          63   0    0.06    0.05     0.01 dimr      cluster_manager,data,ingest,remote_cluster_client -               node-1
x.x.x.x            7          66   1    0.06    0.03     0.00 dimr      cluster_manager,data,ingest,remote_cluster_client *               node-2
x.x.x.x            9          51   1    0.08    0.02     0.01 dimr      cluster_manager,data,ingest,remote_cluster_client -               node-7
x.x.x.x           9          64   0    0.00    0.00     0.00 dimr      cluster_manager,data,ingest,remote_cluster_client -               node-3

```

**Comment by BelenValdivia** [comment]
## Task 4: No errors in the browser's developer console when browsing the App

**Some errors or warnings have been found that have been reported previously:**

- [Multiple unexpected warning during Wazuh app session ](https://github.com/wazuh/wazuh-kibana-app/issues/4092)
- [Warnings and errors when logging out of the app](https://github.com/wazuh/wazuh-kibana-app/issues/4108)
- [Disabled plugins shouldn't appear in More menu ](https://github.com/wazuh/wazuh-kibana-app/issues/4074)
-  [Uncaught TypeError: bounds is null](https://github.com/wazuh/wazuh-kibana-app/issues/4232)

**Comment by BelenValdivia** [comment]
### Task 5: Alerts are being generated for each of the modules configured for this purpose

**Comment by BelenValdivia** [comment]
### Task 6: No warning symbols in Discover when expanding a document

**Comment by BelenValdivia** [comment]
### Task 7: Generate an alert and check it in the web UI

**Comment by BelenValdivia** [comment]
## Task 8: Search works without specifying a field and using `*`
