### ISSUE TITLE
Maintain production and numbered branches

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#17186]
The goals are:
- [x] Merge 4.4 into 4.5.
- [x] Update Python from deps 20 to 21 in AWS
- [x] Merge 4.5 into master.
- [ ] Update Python from deps 21 to 22 in AWS

### Subtasks

- [wazuh-qa](https://github.com/wazuh/wazuh-qa/issues/4192)
- [wazuh-packages](https://github.com/wazuh/wazuh-packages/issues/2214)
- [wazuh-jenkins](https://github.com/wazuh/wazuh-jenkins/issues/5176)
- wazuh-docker
- [wazuh-frontend/kibana](https://github.com/wazuh/wazuh-kibana-app/issues/5404)
- [wazuh-frontend/splunk](https://github.com/wazuh/wazuh-splunk/issues/1400)
