### ISSUE TITLE
Parser NVD API feeds (CVEs & CPEs)

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#17308]
## Description

The aim of this issue is to adapt the NVD parser to support the new feeds we get from the NVD API 2.0.

To do this, we will need to start modifying the current tags used as conditions to check if data exists, and if so, get the values and store them in the NVD structure variables.

This change has to be done carefully, making sure that it correctly traverses the entire feed and that we store all the content in the structure without overwriting it at any point.

Tags that have been deprecated in this new feed will be removed to avoid unusable code.

For this task, we will rely on the comparison of the feeds that was done in the research:
- https://github.com/wazuh/wazuh/issues/16661#issuecomment-1540011228

### Tasks

- [x] Analyse the code and adapt the conditions to the new feeds.
- [x] Add the new tags needed to traverse the feeds.
- [x] Remove the conditions and tags that have been deprecated.
- [x] Check that all the information is correctly stored in the variables without losses or overwrites.
- [x] Check both CVEs and CPEs feeds.
- [x] Check memory management to ensure that there are no memory leaks or bugs.

**Comment by mateocervilla** [comment]
## High RAM usage issue

As previously noted in the [comment](https://github.com/wazuh/wazuh/issues/17308#issuecomment-1610012400), the recent update significantly improved the parsing process speed. However, there was an issue of excessive RAM usage that still persisted.

Due to loading a file of approximately 1 GB and parsing it while saving it into a cJSON structure, along with storing the extracted information in various other variables, the total memory usage reached almost 6 GB.

For this reason, the decision was made to revert to the previously used method, which involved searching for 'cve' objects and parsing them. However, this time, the approach involved breaking the string at each match, parsing only a small portion at a time. As a result, the memory usage was successfully reduced to slightly over 2 GB.

https://github.com/wazuh/wazuh/blob/182e6fc5db758fad8d969e1a74715cce2480eea8/src/wazuh_modules/vulnerability_detector/wm_vuln_detector_nvd.c#L1063-L1072

This change can be seen here: https://github.com/wazuh/wazuh/pull/17710/commits/182e6fc5db758fad8d969e1a74715cce2480eea8

Later on, for a better outcome, we chose to reduce the string as we iterated, discarding already parsed parts. We decided to do this every an intermediate number of iterations since doing it too frequently slowed down the process excessively, and doing it after too many iterations didn't provide significant memory usage reduction.

Finally, the memory usage was reduced to around 1.3 GB. This amount is due to, as mentioned before, the file size of approximately 1 GB and the variables that gradually store the information.

https://github.com/wazuh/wazuh/blob/b462287dd74964d33ed8c45206520f0b198e679c/src/wazuh_modules/vulnerability_detector/wm_vuln_detector_nvd.c#L1077-L1082

This change can be seen here: https://github.com/wazuh/wazuh/pull/17710/commits/b462287dd74964d33ed8c45206520f0b198e679c
