### ISSUE TITLE
Week 22 - Update Wazuh feeds

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#17367]
|Week|Feeds|Previous issue|
|---|---|---|
|22|MSU/ALAS|https://github.com/wazuh/wazuh/issues/17223|

## Description

The following issue aims to check the weekly update of Wazuh feeds, where they will be checked, and it will be decided whether to update them according to the results obtained.

All feed results must have one of the following statuses: 
| | |
|---------------------------------|--------------------------------------------|
| :green_circle: | The feed has been successfully updated |
| :red_circle:  | The feed could not be updated due to failures |
| :yellow_circle:  | The feed has been updated, but a failure has occurred |
| :black_circle:  | The feed has not been updated because it is not needed |

Any failed feed should be reported, detailing the error and possible cause.

In the results, the differences between the current feed and the new feed that will overwrite the current feed should be detailed.

### Current Wazuh feeds
- MSU: https://feed.wazuh.com/vulnerability-detector/windows/msu-updates.json.gz
- ALAS:
  - ALAS 1: https://feed.wazuh.com/vulnerability-detector/ALAS/1/alas.json.gz
  - ALAS 2: https://feed.wazuh.com/vulnerability-detector/ALAS/2/alas2.json.gz
  - ALAS 2022: https://feed.wazuh.com/vulnerability-detector/ALAS/2022/alas2022.json.gz

### Tasks
- [x] Check that feeds have been generated correctly.
- [x] Analyse the difference between the current feed and the new feed.
- [x] Update the current feed with the new feed.

**Comment by MarcelKemp** [comment]
## Update Wazuh feeds

### New feeds vs Current feeds

#### MSU

|MSU|Hotfixes|CVEs|
|---|---|---|
| MSU | +3 | = |

- Hotfixes:
```
KB5025182
KB5025367
KB5026372
```



#### ALAS

| ALAS | Vulnerabilities |
|---|---|
| ALAS 1 | = |
| ALAS 2 | = |
| ALAS 2022 | = |







### Release

| Feeds | Status | SHA256 |
|---|:-:|---|
| MSU | :green_circle: | `e8507d87a5f15ecfd5ba3a180db7cab915c0c367517b61343ad4581d8318dbe3` |
| ALAS 1 | :black_circle: | `2c5c00c3142818da8f5962ee43174d96282bfbc9f24e9c5f573af9e48302d226` |
| ALAS 2 | :black_circle: | `d3bcea972d4e03239b511be7574bd4dd6cb48a3a2d0d4939f5f6acf90b6f9d84` |
| ALAS 2022 | :black_circle: | `7685603c8b224db8c3232ed93755021f478743acb93a972fd17829594626a6f2` |

#### Comments

No vulnerability has been added to the ALAS feeds, so there is no need to update them.
