### ISSUE TITLE
Update AWS Services to make use of the discard_regex functionality

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#17388]
| Affected integration |
|---|
| AWS |

## Description

We have found that the current implementation of the AWS Services integrations (Inspector and CloudWatch Logs) do not make use of the `discard_regex` functionality although an example of a configuration using it can be found in the [documentation](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-s3.html#example-of-configuration). The integrations take the value of the parameter when instantiated but they do not use it to filter the events it fetches because they lack the logic required for `discard_regex` to work. We should make the necessary changes to make the proper use of the field available.

## Tasks
- [ ] Implement the `discard_regex` feature for the services integrations.
- [ ] Test in a manager.
- [ ] Test in an agent.
- [ ] Unit tests without failures. Updated if there are any relevant changes.
- [ ] Integration tests without failures. Updated if there are any relevant changes.
- [ ] Update the documentation if necessary.
- [ ] Add entry to the changelog if necessary.

**Comment by fdalmaup** [comment]
# Issue Update

Found that the methods used in the `AWSBucket.iter_events` method to apply the discard functionality can be refactored and added to the `WazuhIntegration` class in order to be inherited by `AWSService, thus reusing the code for buckets and services.

I have made the necessary modifications so the `AWSInspector` and `AWSCloudWatchLogs` classes implement the functionality. Currently in the process of making manual tests for code adjustments.

**Comment by fdalmaup** [comment]
# Issue Update

Following the modifications previously mentioned, the `AWSInspector` class behavior did not present any inconveniences as the logs are JSON objects, and the discard logic is directly applied.

Respecting how the `AWSCloudWatchLogs` class will work is influenced by the format of the logs that are received. As the received string by the module is sent directly to Analysisd, for cases in which there are JSON-type objects in the log stream, the code was modified so that the `discard-field` and `discard-regex` values are searched for if applicable. Otherwise, it looks for the `discard-regex` pattern in the string and the `discard-field` parameter is not required.

The `DEBUG` level required to show certain messages was also modified from 2 to 3 due to the number of logs that are generated with them.

> Between executions of the module, the `aws_services.db` file was removed to get logs always.

## Inspector


<details><summary>Command output Debug level 2</summary>

    /var/ossec/wodles/aws/aws-s3 -sr inspector -d 2 -s 2022-JAN-26 -p dev -r us-east-1 --discard-field assetAttributes.agentId --discard-regex "i-instance"
    DEBUG: +++ Debug mode on - Level: 2
    DEBUG: +++ Getting alerts from "us-east-1" region.
    DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
    DEBUG: +++ Table does not exist; create
    DEBUG: +++ Listing findings starting from 2022-01-26 00:00:00
    DEBUG: +++ There are no new events in the "us-east-1" region

</details>

<details><summary>Command output Debug level 3</summary>

    /var/ossec/wodles/aws/aws-s3 -sr inspector -d 3 -s 2022-JAN-26 -p dev -r us-east-1 --discard-field assetAttributes.agentId --discard-regex "i-instance"
    DEBUG: +++ Debug mode on - Level: 3
    DEBUG: +++ Getting alerts from "us-east-1" region.
    DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
    DEBUG: +++ Table does not exist; create
    DEBUG: +++ Listing findings starting from 2022-01-26 00:00:00
    DEBUG: +++ Processing 4 events
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ Processing 4 events
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ Processing 9 events
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ Processing 8 events
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ Processing 5 events
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ Processing 4 events
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ Processing 11 events
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ Processing 8 events
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ Processing 8 events
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ Processing 11 events
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ Processing 4 events
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ Processing 11 events
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ Processing 6 events
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ Processing 12 events
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ Processing 8 events
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ Processing 4 events
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ The "i-instance" regex found a match in the "assetAttributes.agentId" field. The event will be skipped.
    DEBUG: +++ There are no new events in the "us-east-1" region


</details>


## CloudWatch Logs

### Discard simple text log

<details><summary>Command output Debug level 2</summary>
    
    /var/ossec/wodles/aws/aws-s3 -sr cloudwatchlogs -g 4_5_test -d 2 -s 2021-JUN-20 -p dev -r us-east-1 --discard-regex TestDEBUG: +++ Debug mode on - Level: 2
    DEBUG: +++ Getting alerts from "us-east-1" region.
    DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
    DEBUG: only logs: 1624147200000
    DEBUG: +++ Table does not exist; create
    DEBUG: Getting log streams for "4_5_test" log group
    DEBUG: Found "test_stream" log stream in 4_5_test
    DEBUG: Getting data from DB for log stream "test_stream" in log group "4_5_test"
    DEBUG: Token: "None", start_time: "None", end_time: "None"
    DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_5_test" using token "None", start_time "1624147200000" and end_time "None"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: +++ There are no new events in the "4_5_test" group
    DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_5_test" using token "f/37592581196964608882919025805905778821310252234493460480/s", start_time "1624147200000" and end_time "None"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: +++ Sent 1 events to Analysisd
    DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_5_test" using token "f/37645180366972094805396383782547622777891308846091272192/s", start_time "1624147200000" and end_time "None"
    DEBUG: Saving data for log group "4_5_test" and log stream "test_stream".
    DEBUG: The saved values are "{'token': 'f/37645185496176941583196752952502274031084618732661604351/s', 'start_time': 1624147200000, 'end_time': 1688068269999}"
    DEBUG: Purging the BD
    DEBUG: Getting log streams for "4_5_test" log group
    DEBUG: Found "test_stream" log stream in 4_5_test
    DEBUG: committing changes and closing the DB



</details>

<details><summary>Command output Debug level 3</summary>

    /var/ossec/wodles/aws/aws-s3 -sr cloudwatchlogs -g 4_5_test -d 3 -s 2021-JUN-20 -p dev -r us-east-1 --discard-regex TestDEBUG: +++ Debug mode on - Level: 3
    DEBUG: +++ Getting alerts from "us-east-1" region.
    DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
    DEBUG: only logs: 1624147200000
    DEBUG: +++ Table does not exist; create
    DEBUG: Getting log streams for "4_5_test" log group
    DEBUG: Found "test_stream" log stream in 4_5_test
    DEBUG: Getting data from DB for log stream "test_stream" in log group "4_5_test"
    DEBUG: Token: "None", start_time: "None", end_time: "None"
    DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_5_test" using token "None", start_time "1624147200000" and end_time "None"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: +++ Retrieved log event is not a JSON object.
    DEBUG: +++ The "Test" regex found a match. The event will be skipped.
    DEBUG: +++ Retrieved log event is not a JSON object.
    DEBUG: +++ The "Test" regex found a match. The event will be skipped.
    DEBUG: +++ Retrieved log event is not a JSON object.
    DEBUG: +++ The "Test" regex found a match. The event will be skipped.
    DEBUG: +++ Retrieved log event is not a JSON object.
    DEBUG: +++ The "Test" regex found a match. The event will be skipped.
    DEBUG: +++ Retrieved log event is not a JSON object.
    DEBUG: +++ The "Test" regex found a match. The event will be skipped.
    DEBUG: +++ Retrieved log event is not a JSON object.
    DEBUG: +++ The "Test" regex found a match. The event will be skipped.
    DEBUG: +++ Retrieved log event is not a JSON object.
    DEBUG: +++ The "Test" regex found a match. The event will be skipped.
    DEBUG: +++ Retrieved log event is not a JSON object.
    DEBUG: +++ The "Test" regex found a match. The event will be skipped.
    DEBUG: +++ Retrieved log event is not a JSON object.
    DEBUG: +++ The "Test" regex found a match. The event will be skipped.
    DEBUG: +++ Retrieved log event is not a JSON object.
    DEBUG: +++ The "Test" regex found a match. The event will be skipped.
    DEBUG: +++ Retrieved log event is not a JSON object.
    DEBUG: +++ The "Test" regex found a match. The event will be skipped.
    DEBUG: +++ Retrieved log event is not a JSON object.
    DEBUG: +++ The "Test" regex found a match. The event will be skipped.
    DEBUG: +++ Retrieved log event is not a JSON object.
    DEBUG: +++ The "Test" regex found a match. The event will be skipped.
    DEBUG: +++ Retrieved log event is not a JSON object.
    DEBUG: +++ The "Test" regex found a match. The event will be skipped.
    DEBUG: +++ Retrieved log event is not a JSON object.
    DEBUG: +++ The "Test" regex found a match. The event will be skipped.
    DEBUG: +++ Retrieved log event is not a JSON object.
    DEBUG: +++ The "Test" regex found a match. The event will be skipped.
    DEBUG: +++ Retrieved log event is not a JSON object.
    DEBUG: +++ The "Test" regex found a match. The event will be skipped.
    DEBUG: +++ Retrieved log event is not a JSON object.
    DEBUG: +++ The "Test" regex found a match. The event will be skipped.
    DEBUG: +++ There are no new events in the "4_5_test" group
    DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_5_test" using token "f/37592581196964608882919025805905778821310252234493460480/s", start_time "1624147200000" and end_time "None"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: The message is "{     "networkInterfaces": [         {             "networkInterfaceId": "eni-networkInterfaceId",             "subnetId": "subnet-subnetId",             "vpcId": "vpc-vpcId",             "privateDnsName": "ip-0-0-0-0.ec2.internal",             "privateIpAddress": "0.0.0.0",             "privateIpAddresses": [                 {                     "privateDnsName": "ip-0-0-0-0.ec2.internal",                     "privateIpAddress": "0.0.0.0"                 }             ],             "publicDnsName": "ec2-0-0-0-0.compute-1.amazonaws.com",             "publicIp": "0.0.0.0",             "ipv6Addresses": [],             "securityGroups": [                 {                     "groupName": "groupName0",                     "groupId": "sg-groupId0"                 },                 {                     "groupName": "groupName1",                     "groupId": "sg-groupID1"                 }             ]         }     ] }"
    DEBUG: The message's timestamp is 1688068269999
    DEBUG: "{     \"networkInterfaces\": [         {             \"networkInterfaceId\": \"eni-networkInterfaceId\",             \"subnetId\": \"subnet-subnetId\",             \"vpcId\": \"vpc-vpcId\",             \"privateDnsName\": \"ip-0-0-0-0.ec2.internal\",             \"privateIpAddress\": \"0.0.0.0\",             \"privateIpAddresses\": [                 {                     \"privateDnsName\": \"ip-0-0-0-0.ec2.internal\",                     \"privateIpAddress\": \"0.0.0.0\"                 }             ],             \"publicDnsName\": \"ec2-0-0-0-0.compute-1.amazonaws.com\",             \"publicIp\": \"0.0.0.0\",             \"ipv6Addresses\": [],             \"securityGroups\": [                 {                     \"groupName\": \"groupName0\",                     \"groupId\": \"sg-groupId0\"                 },                 {                     \"groupName\": \"groupName1\",                     \"groupId\": \"sg-groupID1\"                 }             ]         }     ] }"
    DEBUG: +++ Sent 1 events to Analysisd
    DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_5_test" using token "f/37645180366972094805396383782547622777891308846091272192/s", start_time "1624147200000" and end_time "None"
    DEBUG: Saving data for log group "4_5_test" and log stream "test_stream".
    DEBUG: The saved values are "{'token': 'f/37645185496176941583196752952502274031084618732661604351/s', 'start_time': 1624147200000, 'end_time': 1688068269999}"
    DEBUG: Purging the BD
    DEBUG: Getting log streams for "4_5_test" log group
    DEBUG: Found "test_stream" log stream in 4_5_test
    DEBUG: committing changes and closing the DB

</details>



### Discard JSON log


<details><summary>Command output Debug level 2</summary>

    /var/ossec/wodles/aws/aws-s3 -sr cloudwatchlogs -g 4_5_test -d 2 -s 2023-JUN-20 -p dev -r us-east-1 --discard-field networkInterfaces.networkInterfaceId --discard-regex eni-networkInterfaceId
    DEBUG: +++ Debug mode on - Level: 2
    DEBUG: +++ Getting alerts from "us-east-1" region.
    DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
    DEBUG: only logs: 1687219200000
    DEBUG: +++ Table does not exist; create
    DEBUG: Getting log streams for "4_5_test" log group
    DEBUG: Found "test_stream" log stream in 4_5_test
    DEBUG: Getting data from DB for log stream "test_stream" in log group "4_5_test"
    DEBUG: Token: "None", start_time: "None", end_time: "None"
    DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_5_test" using token "None", start_time "1687219200000" and end_time "None"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: +++ There are no new events in the "4_5_test" group
    DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_5_test" using token "f/37645180366972094805396383782547622777891308846091272192/s", start_time "1687219200000" and end_time "None"
    DEBUG: Saving data for log group "4_5_test" and log stream "test_stream".
    DEBUG: The saved values are "{'token': 'f/37645185496176941583196752952502274031084618732661604351/s', 'start_time': 1687219200000, 'end_time': 1687219200000}"
    DEBUG: Purging the BD
    DEBUG: Getting log streams for "4_5_test" log group
    DEBUG: Found "test_stream" log stream in 4_5_test
    DEBUG: committing changes and closing the DB


</details>

<details><summary>Command output Debug level 3</summary>

    /var/ossec/wodles/aws/aws-s3 -sr cloudwatchlogs -g 4_5_test -d 3 -s 2023-JUN-20 -p dev -r us-east-1 --discard-field networkInterfaces.networkInterfaceId --discard-regex eni-networkInterfaceId
    DEBUG: +++ Debug mode on - Level: 3
    DEBUG: +++ Getting alerts from "us-east-1" region.
    DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
    DEBUG: only logs: 1687219200000
    DEBUG: +++ Table does not exist; create
    DEBUG: Getting log streams for "4_5_test" log group
    DEBUG: Found "test_stream" log stream in 4_5_test
    DEBUG: Getting data from DB for log stream "test_stream" in log group "4_5_test"
    DEBUG: Token: "None", start_time: "None", end_time: "None"
    DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_5_test" using token "None", start_time "1687219200000" and end_time "None"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: +++ The "eni-networkInterfaceId" regex found a match in the "networkInterfaces.networkInterfaceId" field. The event will be skipped.
    DEBUG: +++ There are no new events in the "4_5_test" group
    DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_5_test" using token "f/37645180366972094805396383782547622777891308846091272192/s", start_time "1687219200000" and end_time "None"
    DEBUG: Saving data for log group "4_5_test" and log stream "test_stream".
    DEBUG: The saved values are "{'token': 'f/37645185496176941583196752952502274031084618732661604351/s', 'start_time': 1687219200000, 'end_time': 1687219200000}"
    DEBUG: Purging the BD
    DEBUG: Getting log streams for "4_5_test" log group
    DEBUG: Found "test_stream" log stream in 4_5_test
    DEBUG: committing changes and closing the DB


</details>


## Conclusion

The manual testing passed, what remains to be done is executing the module's integration tests and updating them accordingly.

**Comment by fdalmaup** [comment]
# Issue Update

The AWS ITs have passed successfully:
```
/wazuh-qa/tests/integration/test_aws# pytest -x .
====================================================================== test session starts ======================================================================
platform linux -- Python 3.10.6, pytest-7.1.2, pluggy-1.0.0
rootdir: /wazuh-qa/tests/integration, configfile: pytest.ini
plugins: testinfra-5.0.0, html-3.1.1, metadata-3.0.0
collected 195 items                                                                                                                                             

test_basic.py ................                                                                                                                            [  8%]
test_discard_regex.py ..............                                                                                                                      [ 15%]
test_log_groups.py ..                                                                                                                                     [ 16%]
test_only_logs_after.py .............................................x.                                                                                   [ 40%]
test_parser.py ..........................                                                                                                                 [ 53%]
test_path.py ..........................................                                                                                                   [ 75%]
test_path_suffix.py .........                                                                                                                             [ 80%]
test_regions.py ........................                                                                                                                  [ 92%]
test_remove_from_bucket.py ...sss.........                                                                                                                [100%]

==================================================== 191 passed, 3 skipped, 1 xfailed in 3893.63s (1:04:53) =====================================================
```
Nevertheless, there are no cases to check the discard functionality for the `AWSServices` (`Inspector` and `CloudWatchLogs`). These should be developed in order to maintain the ITs updated.

**Comment by fdalmaup** [comment]
# Issue Update

The team has decided to modify the current behavior of the module. Currently, when the `<discard_regex>` parameter did not have the `field` parameter or if it was empty, the module showed a Warning when restarting the central components of the Wazuh manager. We are changing this in order to break the restart process and show an error message when no `field` value is present, except for when the type is `cloudwatchlogs` since it admits `<discard_regex>` when expecting text logs. For this last case, no warning is shown, assuming the user is aware of this use of the parameter having read the documentation (WIP)

The ITs for `discard_regex` are done:
```
pytest -vv wazuh-qa/tests/integration/test_aws/test_discard_regex.py
====================================================================== test session starts ======================================================================
platform linux -- Python 3.10.6, pytest-7.1.2, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.10.6', 'Platform': 'Linux-5.19.0-1025-aws-x86_64-with-glibc2.35', 'Packages': {'pytest': '7.1.2', 'pluggy': '1.0.0'}, 'Plugins': {'testinfra': '5.0.0', 'html': '3.1.1', 'metadata': '3.0.0'}}
rootdir: /wazuh-qa/tests/integration, configfile: pytest.ini
plugins: testinfra-5.0.0, html-3.1.1, metadata-3.0.0
collected 17 items                                                                                                                                              

wazuh-qa/tests/integration/test_aws/test_discard_regex.py::test_bucket_discard_regex[cloudtrail_discard_regex] PASSED                                     [  5%]
wazuh-qa/tests/integration/test_aws/test_discard_regex.py::test_bucket_discard_regex[vpc_discard_regex] PASSED                                            [ 11%]
wazuh-qa/tests/integration/test_aws/test_discard_regex.py::test_bucket_discard_regex[config_discard_regex] PASSED                                         [ 17%]
wazuh-qa/tests/integration/test_aws/test_discard_regex.py::test_bucket_discard_regex[alb_discard_regex] PASSED                                            [ 23%]
wazuh-qa/tests/integration/test_aws/test_discard_regex.py::test_bucket_discard_regex[clb_discard_regex] PASSED                                            [ 29%]
wazuh-qa/tests/integration/test_aws/test_discard_regex.py::test_bucket_discard_regex[nlb_discard_regex] PASSED                                            [ 35%]
wazuh-qa/tests/integration/test_aws/test_discard_regex.py::test_bucket_discard_regex[kms_discard_regex] PASSED                                            [ 41%]
wazuh-qa/tests/integration/test_aws/test_discard_regex.py::test_bucket_discard_regex[macie_discard_regex] PASSED                                          [ 47%]
wazuh-qa/tests/integration/test_aws/test_discard_regex.py::test_bucket_discard_regex[trusted_advisor_discard_regex] PASSED                                [ 52%]
wazuh-qa/tests/integration/test_aws/test_discard_regex.py::test_bucket_discard_regex[guardduty_discard_regex] PASSED                                      [ 58%]
wazuh-qa/tests/integration/test_aws/test_discard_regex.py::test_bucket_discard_regex[native_guardduty_discard_regex] PASSED                               [ 64%]
wazuh-qa/tests/integration/test_aws/test_discard_regex.py::test_bucket_discard_regex[waf_discard_regex] PASSED                                            [ 70%]
wazuh-qa/tests/integration/test_aws/test_discard_regex.py::test_bucket_discard_regex[server_access_discard_regex] PASSED                                  [ 76%]
wazuh-qa/tests/integration/test_aws/test_discard_regex.py::test_bucket_discard_regex[cisco_umbrella_discard_regex] PASSED                                 [ 82%]
wazuh-qa/tests/integration/test_aws/test_discard_regex.py::test_cloudwatch_discard_regex_json[cloudwatch_discard_regex_json] PASSED                       [ 88%]
wazuh-qa/tests/integration/test_aws/test_discard_regex.py::test_cloudwatch_discard_regex_simple_text[cloudwatch_discard_regex_simple_text] PASSED         [ 94%]
wazuh-qa/tests/integration/test_aws/test_discard_regex.py::test_inspector_discard_regex[inspector_discard_regex] PASSED                                   [100%]

================================================================ 17 passed in 336.47s (0:05:36) =================================================================
```

**Comment by fdalmaup** [comment]
# Issue Update

The feature is required for the upcoming `4.5.1` release, therefore a rebase to the corresponding branch was required. This release does not have the latest changes on which the module integration tests were based. 
The IT modifications carried out in https://github.com/wazuh/wazuh-qa/pull/4278 will stay pointing to the branch with the latest changes, but the development needs to be manually tested.
