### ISSUE TITLE
Refactor and migrate active response integration tests from QA repository to Core repository

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh#17426]
| Target version | Related Epic   |
|--------------------|-----------------------|
|           4.6         |  wazuh/wazuh#17427             |

## Description 

As part of wazuh/wazuh#17427, we need to refactor and migrate all legacy integration tests from the QA repository to the Core repository.

This specific issue aims to migrate the Active Response integration tests. 
The actual state of the AR tests is the following:
```vim
test_active_response/
├── test_analysisd
│   ├── data
│   │   ├── configuration_template
│   │   │   └── configuration_overwritten_rules.yaml
│   │   ├── rules
│   │   │   ├── 0270-web_appsec_rules_edit.xml
│   │   │   └── local_rules.xml
│   │   ├── scripts
│   │   │   └── custom-ar.sh
│   │   ├── test_cases
│   │   │   └── cases_overwritten_rules.yaml
│   │   └── wazuh_conf.yaml
│   ├── test_os_exec.py
│   └── test_overwritten_rules_ar.py
└── test_execd
    ├── conftest.py
    ├── data
    │   └── wazuh_conf.yaml
    ├── test_execd_firewall_drop.py
    └── test_execd_restart.py

8 directories, 12 files
```

### Tasks
- [x] Migrate `test_execd_firewall_drop`
- [x] Migrate `test_execd_restart`
- [x] Migrate `test_overwritten_rules_ar`
- [x] Migrate `test_os_exec`

**Comment by QU3B1M** [comment]
### Update 08/06/2023

- Migrated Active Response's `set_active_response_configuration` fixture
- Initial test migration, now migrating the framework required dependencies

**Comment by QU3B1M** [comment]
- Add **`authd_simulator`** and **`remoted_simulator`** fixtures

**Comment by QU3B1M** [comment]
This issue depends on wazuh/qa-integration-framework#2 to be finished. For now, it is on hold until the correspondent framework code is migrated.

**Comment by QU3B1M** [comment]
- Add fixtures to execd `conftest.py`

**Comment by QU3B1M** [comment]
- Add assertions to `test_execd_firewall_drop.py`
- Add local fixture `send_execd_message`
- Execute both cases successfully.

**Comment by QU3B1M** [comment]
- Add new cases to `test_execd_firewall_drop` and improve its docstrings
- Remove unused fixtures
- Add `test_execd_restart` scenario and its cases
- Validate all tests are working correctly

**Comment by QU3B1M** [comment]
- Moved `execd_firewall_drop` and `test_execd_restart` execd tests to a subfolder.
- Add `test_override_rules` _scenario_, _cases_ and its data.
- Create fixtures to make the `test_override_rules` scenario cleaner.
- Only docstrings are pending.
