### ISSUE TITLE
Release 4.4.4 - Post release

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#17537]
The following issue aims to perform required post-release checks to ensure a well-published release procedure.

## Main information
|||
| :--                             | :--                                                |
| **Version**                     | 4.4.4                                      |
| **Tag**                         | https://github.com/wazuh/wazuh/tree/v4.4.4 |
| **Release issue**               |  #17408                                     |
| **Previous post release issue** | #17244                                      |

---

### Release notes and tags
- [x] wazuh/wazuh
- [x] wazuh/wazuh-packages
- [x] wazuh/wazuh-kibana-app
- [x] wazuh/wazuh-splunk
- [x] wazuh/wazuh-qa
- [x] wazuh/wazuh-ansible
- [x] wazuh/wazuh-docker
- [x] wazuh/wazuh-kubernetes
- [x] wazuh/wazuh-puppet

### Repository
- [x] Live installation test 
- [x] Live upgrade test
- [x] WPK versions check
- [x] WPK upgrade test
- [x] Post-release check (files)
- [x] AMI published
- [x] Cache invalidated
- [x] Build release containers
- [x] Build and push Docker Hub images
- [x] Build and release debug packages
- [x] Publish puppet forge module
- [x] Update upgrade template in wazuh-jenkins repository with the last version 
- [x] Wazuh installation assistant uses v4.4.4
- [x] Complete https://github.com/wazuh/wazuh/issues/17420
- [x] Launch 2d stress tests v4.4.4 (live)

### Documentation
- [x] Documentation updated
- [x] Documentation published
- [x] Cache invalidated

### Marketing
- [x] Community announcement (Need the rest of the checks ready)

## Validation

The following auditors must give the green light to this release.

- [x] @davidjiglesias 

---

**Comment by rauldpm** [comment]
- Test install tier (AMD64) https://ci.wazuh.info/job/Test_install_tier/607/
- Test upgrade tier (AMD64) https://ci.wazuh.info/job/Test_upgrade_tier/2082/

**Comment by rauldpm** [comment]
### Tags and release notes

- wazuh/wazuh
  - https://github.com/wazuh/wazuh/tree/v4.4.4
  - https://github.com/wazuh/wazuh/releases/tag/v4.4.4 (Set as Pre-release)
- wazuh/wazuh-packages
  - https://github.com/wazuh/wazuh-packages/tree/v4.4.4
  -  https://github.com/wazuh/wazuh-packages/releases/tag/v4.4.4
- wazuh/wazuh-kibana-app
  - https://github.com/wazuh/wazuh-kibana-app/tree/v4.4.4-7.17.9
  - https://github.com/wazuh/wazuh-kibana-app/tree/v4.4.4-7.17.8
  - https://github.com/wazuh/wazuh-kibana-app/tree/v4.4.4-7.17.7
  - https://github.com/wazuh/wazuh-kibana-app/tree/v4.4.4-7.17.6
  - https://github.com/wazuh/wazuh-kibana-app/tree/v4.4.4-7.17.5
  - https://github.com/wazuh/wazuh-kibana-app/tree/v4.4.4-7.17.4
  - https://github.com/wazuh/wazuh-kibana-app/tree/v4.4.4-7.17.3
  - https://github.com/wazuh/wazuh-kibana-app/tree/v4.4.4-7.17.2
  - https://github.com/wazuh/wazuh-kibana-app/tree/v4.4.4-7.17.1
  - https://github.com/wazuh/wazuh-kibana-app/tree/v4.4.4-7.17.0
  - https://github.com/wazuh/wazuh-kibana-app/tree/v4.4.4-7.16.3
  - https://github.com/wazuh/wazuh-kibana-app/tree/v4.4.4-7.16.2
  - https://github.com/wazuh/wazuh-kibana-app/tree/v4.4.4-7.16.1
  - https://github.com/wazuh/wazuh-kibana-app/tree/v4.4.4-7.16.0
  - https://github.com/wazuh/wazuh-kibana-app/tree/v4.4.4-7.10.2
  - https://github.com/wazuh/wazuh-kibana-app/tree/v4.4.4-2.6.0
  - No release notes found
- wazuh/wazuh-splunk
  - https://github.com/wazuh/wazuh-splunk/tree/v4.4.4-8.2
  -  https://github.com/wazuh/wazuh-splunk/tree/v4.4.4-8.1
  - No release notes found
- wazuh/wazuh-qa
  - https://github.com/wazuh/wazuh-qa/tree/v4.4.4
  -  No release notes found
- wazuh/wazuh-ansible
  - https://github.com/wazuh/wazuh-ansible/tree/v4.4.4
  -  https://github.com/wazuh/wazuh-ansible/releases/tag/v4.4.4
- wazuh/wazuh-docker
  - https://github.com/wazuh/wazuh-docker/tree/v4.4.4
  -  https://github.com/wazuh/wazuh-docker/releases/tag/v4.4.4
- wazuh/wazuh-kubernetes
  - https://github.com/wazuh/wazuh-kubernetes/tree/v4.4.4
  -  https://github.com/wazuh/wazuh-kubernetes/releases/tag/v4.4.4
- wazuh/wazuh-puppet
  - https://github.com/wazuh/wazuh-puppet/tree/v4.4.4
  -  https://github.com/wazuh/wazuh-puppet/releases/tag/v4.4.4
