### ISSUE TITLE
Add support for Amazon Linux 2023 in Vulnerability Detector

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#17617]
|Component|Install type|Platform|
|---|---|---|
| _Vulnerability Detector_ | Manager | [Amazon Linux 2023](https://aws.amazon.com/es/linux/amazon-linux-2023/) |

## Description

The aim of this issue is to add native support for vulnerability scans to Amazon Linux 2023.

Amazon Linux 2023 offers its own OVAL feed (ALAS 2023): https://alas.aws.amazon.com/AL2023/alas.rss

We currently support older versions of Amazon Linux (1 and 2). We should incorporate this new OVAL that has just been released.

## Configuration

The configuration block for this new distribution will be like the one we have for the previous versions:

```xml
<vulnerability-detector>
    ...
    <!-- Amazon Linux OS vulnerabilities -->
    <provider name="alas">
      <enabled>yes</enabled>
      <os>amazon-linux-2023</os>
      <update_interval>1h</update_interval>
    </provider>
    ...
</vulnerability-detector>
```

## Tasks
- [x] #18511
- [x] https://github.com/wazuh/wazuh/issues/18526
- [x] https://github.com/wazuh/wazuh-documentation/issues/6366
- [x] https://github.com/wazuh/wazuh-qa/issues/4440
- [x] https://github.com/wazuh/wazuh-jenkins/issues/5547
- [x] Search in the other repositories where there is ALAS configuration and open an issue to request the specific team to make the necessary changes.

**Comment by shurex** [comment]
Any chance I can run the support if the 2023 feed before this is released in 4.7.0 ?
