### ISSUE TITLE
Support new Wazuh development version `4.5.1`

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh#17627]
## Description

The goal is to track the generation of issues, projects and numbered branches to fully support the new Wazuh version `4.5.1`. This is a bit of a special process since we have to move current 4.5 and 4.6(master) versions forward to what will be 4.6 and 4.7 (current dates for the releases remain unchanged).

## Tasks

- [x] Open `v4.5.1` release issue in wazuh/releases https://github.com/wazuh/releases/issues/7 
- [x] Create `Release 4.5.1` project in wazuh https://github.com/orgs/wazuh/projects/56
- [ ] Create numbered branches for `4.5.1`
  - [ ] New branch `4.5.1` on wazuh-jenkins repository 
  - [ ] New branch `4.5.1` on wazuh-qa repository
  - [ ] New branch `4.5.1` on wazuh-packages repository
  - [ ] New branch `4.5.1` on wazuh repository

**Comment by davidjiglesias** [comment]
To be done in https://github.com/wazuh/wazuh/issues/17639
