### ISSUE TITLE
Bump current minor numbered branches (4.5+)

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#17639]
## Description

This issue attempts to bump current 4.5 and master(4.6) to 4.6.0 and master(4.7.0) respectively. The reasoning behind it is to create a space to introduce 4.5.0 with the NVD API 2.0 development.

# CRITICAL NOTICE
Each step from below must be thoroughly completed before the next one can be tackled

## Tasks (For all repositories)

- [X] Bump version in master branch to version 4.7.0 and add a changelog entry

  - [X] https://github.com/wazuh/wazuh @wazuh/core @wazuh/framework @wazuh/threat-intel 
  - [x] https://github.com/wazuh/wazuh-packages @wazuh/core @wazuh/framework @wazuh/threat-intel @wazuh/frontend
       - Build and push testing images for GitHub actions in wazuh-packages
  - [x] https://github.com/wazuh/wazuh-automation @wazuh/qa 
  - [x] https://github.com/wazuh/wazuh-qa @wazuh/qa
  - [x] https://github.com/wazuh/wazuh-jenkins @wazuh/qa
  - [x] https://github.com/wazuh/wazuh-docker @wazuh/cicd 
  - [x] https://github.com/wazuh/wazuh-puppet @wazuh/cicd
  - [x] https://github.com/wazuh/wazuh-ansible @wazuh/cicd
  - [x] https://github.com/wazuh/wazuh-kubernetes @wazuh/cicd
  - [x] https://github.com/wazuh/wazuh-security-dashboards-plugin @wazuh/frontend
  - [x] https://github.com/wazuh/wazuh-dashboard @wazuh/frontend
  - [x] https://github.com/wazuh/wazuh-kibana-app @wazuh/frontend
  - [x] https://github.com/wazuh/wazuh-splunk @wazuh/frontend
  - [x] https://github.com/wazuh/wazuh-documentation @wazuh/documentation 

</details>

- [x] Use a script to rename version in release field in the team projects from 4.6.0 to 4.7.0

- [x] Ensure all issues from 4.6.0 are already in 4.7.0 and included in the new release project (4.7.0)

---
- [x] Rename branch 4.5 to 4.6.0

  - [x] https://github.com/wazuh/wazuh @wazuh/core @wazuh/framework @wazuh/threat-intel 
  - [x] https://github.com/wazuh/wazuh-packages @wazuh/core @wazuh/framework @wazuh/threat-intel @wazuh/frontend
  - [x] https://github.com/wazuh/wazuh-automation @wazuh/qa 
  - [x] https://github.com/wazuh/wazuh-qa @wazuh/qa
  - [x] https://github.com/wazuh/wazuh-jenkins @wazuh/qa
   The jenkins rename failed and we cannot delete the 4.5 branch.
  - [x] https://github.com/wazuh/wazuh-docker @wazuh/cicd 
  - [x] https://github.com/wazuh/wazuh-puppet @wazuh/cicd
  - [x] https://github.com/wazuh/wazuh-ansible @wazuh/cicd
  - [x] https://github.com/wazuh/wazuh-kubernetes @wazuh/cicd
  - [x] https://github.com/wazuh/wazuh-security-dashboards-plugin @wazuh/frontend
  - [x] https://github.com/wazuh/wazuh-dashboard @wazuh/frontend
  - [x] https://github.com/wazuh/wazuh-kibana-app @wazuh/frontend
  - [x] https://github.com/wazuh/wazuh-splunk @wazuh/frontend
  - [x] https://github.com/wazuh/wazuh-documentation @wazuh/documentation 

- [x] Bump version in 4.5 branch version to 4.6.0 and add a changelog entry

  - [x] https://github.com/wazuh/wazuh @wazuh/core @wazuh/framework @wazuh/threat-intel 
  - [x] https://github.com/wazuh/wazuh-packages @wazuh/core @wazuh/framework @wazuh/threat-intel @wazuh/frontend
  - [x] https://github.com/wazuh/wazuh-automation @wazuh/qa 
  - [x] https://github.com/wazuh/wazuh-qa @wazuh/qa
  - [x] https://github.com/wazuh/wazuh-jenkins @wazuh/qa
  - [x] https://github.com/wazuh/wazuh-docker @wazuh/cicd 
  - [x] https://github.com/wazuh/wazuh-puppet @wazuh/cicd
  - [x] https://github.com/wazuh/wazuh-ansible @wazuh/cicd
  - [x] https://github.com/wazuh/wazuh-kubernetes @wazuh/cicd
  - [x] https://github.com/wazuh/wazuh-security-dashboards-plugin @wazuh/frontend
  - [x] https://github.com/wazuh/wazuh-dashboard @wazuh/frontend
  - [x] https://github.com/wazuh/wazuh-kibana-app @wazuh/frontend
  - [x] https://github.com/wazuh/wazuh-splunk @wazuh/frontend
  - [x] https://github.com/wazuh/wazuh-documentation @wazuh/documentation 

- [x] Use a script to rename version in release field in the team projects from 4.5.0 to 4.6.0

- [x] Ensure all issues from 4.5.0 are already in 4.6.0 and included in the new release project (4.6.0)

- [x] Create branch 4.5.0 using tag v4.4.4 as base

  - [x] https://github.com/wazuh/wazuh @wazuh/core @wazuh/framework @wazuh/threat-intel 
  - [x] https://github.com/wazuh/wazuh-packages @wazuh/core @wazuh/framework @wazuh/threat-intel @wazuh/frontend
  - [x] https://github.com/wazuh/wazuh-automation @wazuh/qa 
  - [x] https://github.com/wazuh/wazuh-qa @wazuh/qa
  - [x] https://github.com/wazuh/wazuh-jenkins @wazuh/qa
  - [x] https://github.com/wazuh/wazuh-docker @wazuh/cicd 
  - [x] https://github.com/wazuh/wazuh-puppet @wazuh/cicd
  - [x] https://github.com/wazuh/wazuh-ansible @wazuh/cicd
  - [x] https://github.com/wazuh/wazuh-kubernetes @wazuh/cicd
  - [x] https://github.com/wazuh/wazuh-security-dashboards-plugin @wazuh/frontend
  - [x] https://github.com/wazuh/wazuh-dashboard @wazuh/frontend
  - [x] https://github.com/wazuh/wazuh-kibana-app @wazuh/frontend
  - [x] https://github.com/wazuh/wazuh-splunk @wazuh/frontend
  - [x] https://github.com/wazuh/wazuh-documentation @wazuh/documentation 

- [x] Bump version in 4.5.0 branch to version 4.5.0 and add a changelog entry

  - [x] https://github.com/wazuh/wazuh @wazuh/core @wazuh/framework @wazuh/threat-intel 
  - [x] https://github.com/wazuh/wazuh-packages @wazuh/core @wazuh/framework @wazuh/threat-intel @wazuh/frontend
  - [x] https://github.com/wazuh/wazuh-automation @wazuh/qa 
  - [x] https://github.com/wazuh/wazuh-qa @wazuh/qa
  - [x] https://github.com/wazuh/wazuh-jenkins @wazuh/qa
  - [x] https://github.com/wazuh/wazuh-docker @wazuh/cicd 
  - [x] https://github.com/wazuh/wazuh-puppet @wazuh/cicd
  - [x] https://github.com/wazuh/wazuh-ansible @wazuh/cicd
  - [x] https://github.com/wazuh/wazuh-kubernetes @wazuh/cicd
  - [x] https://github.com/wazuh/wazuh-security-dashboards-plugin @wazuh/frontend
  - [x] https://github.com/wazuh/wazuh-dashboard @wazuh/frontend
  - [x] https://github.com/wazuh/wazuh-kibana-app @wazuh/frontend
  - [x] https://github.com/wazuh/wazuh-splunk @wazuh/frontend
  - [x] https://github.com/wazuh/wazuh-documentation @wazuh/documentation 

- [x] Open v4.5.1 release issue in wazuh/releases https://github.com/wazuh/releases/issues/7
- [x] Create Release 4.5.1 project in wazuh https://github.com/orgs/wazuh/projects/56
- [x] Rename 4.4.5 to 4.5.1, if your repository does not currently have 4.4.5 or any development for that version, create 4.5.1 branch from 4.5.0. Bump version in 4.5.1 branch to version 4.5.1 and add a changelog entry.
  - [x] https://github.com/wazuh/wazuh @wazuh/core @wazuh/framework @wazuh/threat-intel 
  - [x] https://github.com/wazuh/wazuh-packages @wazuh/core @wazuh/framework @wazuh/threat-intel @wazuh/frontend
  - [x] https://github.com/wazuh/wazuh-automation @wazuh/qa 
  - [x] https://github.com/wazuh/wazuh-qa @wazuh/qa
  - [x] https://github.com/wazuh/wazuh-jenkins @wazuh/qa
  - [x] https://github.com/wazuh/wazuh-docker @wazuh/cicd 
  - [x] https://github.com/wazuh/wazuh-puppet @wazuh/cicd
  - [x] https://github.com/wazuh/wazuh-ansible @wazuh/cicd
  - [x] https://github.com/wazuh/wazuh-kubernetes @wazuh/cicd
  - [x] https://github.com/wazuh/wazuh-security-dashboards-plugin @wazuh/frontend
  - [x] https://github.com/wazuh/wazuh-dashboard @wazuh/frontend
  - [x] https://github.com/wazuh/wazuh-kibana-app @wazuh/frontend
  - [x] https://github.com/wazuh/wazuh-splunk @wazuh/frontend
  - [x] https://github.com/wazuh/wazuh-documentation @wazuh/documentation 

 - [x] Use a script to rename version in release field in the team projects from 4.4.5 to 4.5.1

 - [x] Ensure all issues from 4.4.5 are already in 4.5.1 and included in the new release project (4.5.1)

- [x]  All AWS resources should be regenerated using the `Procedure_ecs_task_tier` pipeline on branches that have been modified/bumped
  - [x] 4.5.0: https://ci.wazuh.info/job/Procedure_ecs_task_tier/15
  - [x] 4.5.1: https://ci.wazuh.info/job/Procedure_ecs_task_tier/21/
  - [x] 4.6.0: https://ci.wazuh.info/job/Procedure_ecs_task_tier/16
  - [x] 4.7.0 (master) : https://ci.wazuh.info/job/Procedure_ecs_task_tier/17/
