### ISSUE TITLE
Week 26 - Update Wazuh feeds

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#17682]
|Week|Feeds|Previous issue|
|---|---|---|
|26|MSU/ALAS|https://github.com/wazuh/wazuh/issues/17616|

## Description

The following issue aims to check the weekly update of Wazuh feeds, where they will be checked, and it will be decided whether to update them according to the results obtained.

All feed results must have one of the following statuses: 
| | |
|---------------------------------|--------------------------------------------|
| :green_circle: | The feed has been successfully updated |
| :red_circle:  | The feed could not be updated due to failures |
| :yellow_circle:  | The feed has been updated, but a failure has occurred |
| :black_circle:  | The feed has not been updated because it is not needed |

Any failed feed should be reported, detailing the error and possible cause.

In the results, the differences between the current feed and the new feed that will overwrite the current feed should be detailed.

### Current Wazuh feeds
- MSU: https://feed.wazuh.com/vulnerability-detector/windows/msu-updates.json.gz
- ALAS:
  - ALAS 1: https://feed.wazuh.com/vulnerability-detector/ALAS/1/alas.json.gz
  - ALAS 2: https://feed.wazuh.com/vulnerability-detector/ALAS/2/alas2.json.gz
  - ALAS 2022: https://feed.wazuh.com/vulnerability-detector/ALAS/2022/alas2022.json.gz

### Tasks
- [x] Check that feeds have been generated correctly.
- [x] Analyse the difference between the current feed and the new feed.
- [x] Update the current feed with the new feed.

**Comment by MarcelKemp** [comment]
## Update Wazuh feeds

### New feeds vs Current feeds

#### MSU

|MSU|Hotfixes|CVEs|
|---|---|---|
| MSU | +3 | = |


- Hotfixes:
```
KB5027215
KB5027219
KB5027230
```



#### ALAS

| ALAS | Vulnerabilities |
|---|---|
| ALAS 1 | = |
| ALAS 2 | = |
| ALAS 2022 | = |







### Release

| Feeds | Status | SHA256 |
|---|:-:|---|
| MSU | 🟢 | `b7de90620db54ec1f1a7c5984309887d5c6cf8eb738239aa9e04fad869454cd6` |
| ALAS 1 | :black_circle: | `4db73c4b05eb468006c4705c3bf83e7aebc84e00c64bb40b16a8257bec25d476` |
| ALAS 2 | :black_circle: | `49b5a75928ec3dd41c0f21c5488ea8517bcfa7170925f422435ea7a35bcebec9` |
| ALAS 2022 | :black_circle: | `3d5e6a99d5f4c1fd777e5f4ddc1c3721aa2c6d85f4c56578ca88c8496bef724b` |


#### Comments

The MSU generator has been rerun, due to the following error, causing a loss of 71 vulnerabilities: 
- `ERROR: TimeoutError()`

The newly generated MSU no longer had any bugs and its results were correct.
