### ISSUE TITLE
Refactor and migrate agentd integration tests from QA repository to Core repository

### ISSUE THREAD

**Issue by mjcr99** [wazuh/wazuh#17696]
## Description

As part of wazuh/wazuh#17427, we need to refactor and migrate all legacy integration tests from the QA repository to the Core repository.

This issue aims to do this with the agentd tests. The following files are involved:

```
test_agentd/
   ├── conftest.py
   ├── __init__.py
   └── test_agentd_multi_server
    │                   ├──── data
    |                   |        └── config_templates
    │                   │        │           └── wazuh_conf.yaml
    |                   |        └── test_cases
    │                   │                    └── wazuh_state_tests.yaml
    │                   └── test_agentd_multi_server.py
    └── test_agentd_reconnection
    │                   ├──── data
    |                   |        └── config_templates
    │                   │        │           └── wazuh_conf.yaml
    |                   |        └── test_cases
    │                   │                    └── wazuh_state_tests.yaml
    │                   └── test_agentd_reconnection.py
    └── test_agentd_state
    │                   ├──── data
    |                   |        └── config_templates
    │                   │        │           └── wazuh_conf.yaml
    |                   |        └── test_cases
    │                   │                    └── wazuh_state_tests.yaml
    │                   └── test_agentd_state.py
    └── test_agentd_state_config
    │                     ├──── data
    │                     |       └── config_templates
    │                     │       │           └── wazuh_conf.yaml
    │                     |       └── test_cases
    │                     │                   └── wazuh_state_tests.yaml
    │                     └── test_agentd_state_config.py
    └── test_agentd_state_reconnection
                       ├──── data
                       |        └── config_templates
                       │        │           └── wazuh_conf.yaml
                       |        └── test_cases
                       │                    └── wazuh_state_tests.yaml
                       │
                       └── test_agentd_connection_retries_pre_enrollment.py
                       │
                       └── test_agentd_initial_enrollment_retries.py
                       │
                       └── test_agentd_reconection_enrollment_no_keys_file.py
                       │
                       └── test_agentd_reconection_enrollment_no_keys.py
                       │
                       └── test_agentd_reconection_enrollment_with_keys.py
```

### Current status:
- [x] https://github.com/wazuh/wazuh/issues/19004 - BLOCKED
In the implementation of this test, the fixture configure_local_internal_options, has been changed as discussed in this [thread](https://wazuh-team.slack.com/archives/C05LD04A1EE/p1691163200267009). Due to this modification, we should change this fixture call in other tests, to reduce the number of executions of it.
- [x] https://github.com/wazuh/wazuh/issues/19005 - BLOCKED
- [x] https://github.com/wazuh/wazuh/issues/19094 - BLOCKED - All test are running but UDP protocol test cases do not work due to RemotedSimulator issue.
- [x] https://github.com/wazuh/wazuh/issues/19329 - BLOCKED
- [x] https://github.com/wazuh/wazuh/issues/19951 - BLOCKED

The subtask are affected by: https://github.com/wazuh/wazuh/issues/17696#issuecomment-1784578288

**Comment by mjcr99** [comment]
Hi team, 
during the development of this integration test, we found a problem with the new [qa-integration-framework](https://github.com/wazuh/qa-integration-framework),
specifically with the RemotedSimulator, that it's not mocking UDP connections properly.
 
This problem is reported in this issue: https://github.com/wazuh/qa-integration-framework/issues/41.
 
While the development of these tests is possible without the fix, all the test cases can not pass due to this UDP connection simulation problem. To fully complete this issue, is mandatory to solve it previously.

**Comment by mjcr99** [comment]
## Issue updates
**(13/12/2023)** - Reviewing all test documentation and format, fixing found problems.
