### ISSUE TITLE
Refactor and migrate rootcheck integration tests from QA repository to Core repository

### ISSUE THREAD

**Issue by lchico** [wazuh/wazuh#17700]
## Description

As part of wazuh/wazuh#17427, we need to refactor and migrate all legacy integration tests from the QA repository to the Core repository.

This issue aims to do this with the rootcheck tests. The following files are involved:

```
test_rootcheck/
|-- test_configuration
|   |-- data
|   |   |-- config_templates
|   |   |   `-- config_template.yaml
|   |   `-- test_cases
|   |       `-- cases_configuration.yaml
|   |-- __init__.py
|   `-- test_rootcheck.py
`-- conftest.py
```
### Tasks:

- [x] Apply new format to tests.
- [x] Ensure that each test configures all it needs (ie: internal options).
- [x] Move everything related to the test environment configuration to fixtures.
- [x] Make sure tests clean up the environment after execution.
- [x] Place fixtures in `conftest.py` files.
- [x] Use generic functions of the new QA framework.
- [x] Make sure there is no duplicate code.
- [ ]   Update the branch to main in the workflows once PR wazuh/qa-integration-framework#33 is merged
