### ISSUE TITLE
Add support for processing and testing raw Windows Event Channel messages 

### ISSUE THREAD

**Issue by tdrauncieal** [wazuh/wazuh#17762]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0.0 | Wazuh component | Manager/Agent | Packages/Sources | Linux |

## Description
It is intended to allow the user to evaluate Windows events in a transparent manner and at the same time to be able to easily identify them between `Windows Event Viewer` and when they are reported by the `Dashboard` e.g.

This issue is supported by the previous research requested:
- https://github.com/wazuh/internal-devel-requests/issues/7

## Tasks
- [ ] Strip message wrapping for EventChannel messages (agent side)
- [ ] Make a decoder to process XML data
- [ ] Change the way how to Engine process the raw XML message (a.k.a `analysisd`)
- [ ] Add/Update related unit tests
