### ISSUE TITLE
Support new version `4.4.5`

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#17772]
## Description

This issue attempts to support a new version 4.4.5 for the Wazuh system.

# CRITICAL NOTICE
Each step from below must be thoroughly completed before the next one can be tackled

## Tasks 

- [x] Create a GitHub issue for the release in the [Releases repository](https://github.com/wazuh/releases)
- [x] Create `Release 4.4.5` project in the wazuh project organization: https://github.com/orgs/wazuh/projects/50

## Tasks (For all repositories)

- [x] Create a 4.4.5 branch from the 4.4 branch
- [x] Bump version in the 4.4.5 branch from 4.4.4 to 4.4.5 and add a changelog entry. A pull request must be created to perform this action.

### Repositories

- [x] https://github.com/wazuh/wazuh/issues/17776 https://github.com/wazuh/wazuh-packages/issues/2255 @wazuh/core
  - [x] https://github.com/wazuh/wazuh
  - [x] https://github.com/wazuh/wazuh-packages
  - [ ] Build and push testing images for GitHub actions in wazuh-packages
- [x] https://github.com/wazuh/wazuh-qa/issues/4289 @wazuh/qa 
  - [x] https://github.com/wazuh/wazuh-automation
  - [x] https://github.com/wazuh/wazuh-qa
  - [x] https://github.com/wazuh/wazuh-jenkins
- [x] https://github.com/wazuh/wazuh-automation/issues/1161 @wazuh/cicd
  - [x] https://github.com/wazuh/wazuh-docker
  - [x] https://github.com/wazuh/wazuh-puppet
  - [x] https://github.com/wazuh/wazuh-ansible
  - [x] https://github.com/wazuh/wazuh-kubernetes
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/5638 https://github.com/wazuh/wazuh-splunk/issues/1414 @wazuh/frontend 
  - [x] https://github.com/wazuh/wazuh-security-dashboards-plugin
  - [x] https://github.com/wazuh/wazuh-dashboard
  - [x] https://github.com/wazuh/wazuh-kibana-app
  - [x] https://github.com/wazuh/wazuh-splunk
- [x] https://github.com/wazuh/wazuh-documentation/issues/6214 @wazuh/documentation 
  - [x] https://github.com/wazuh/wazuh-documentation
---

- [x]  All AWS resources should be generated using the `Procedure_ecs_task_tier` pipeline using the 4.4.5 branch
  - [x] 4.4.5: https://ci.wazuh.info/job/Procedure_ecs_task_tier/22/

**Comment by jnasselle** [comment]
- Created https://github.com/wazuh/wazuh-qa/pull/4288

**Comment by jnasselle** [comment]
- Created https://github.com/wazuh/wazuh-automation/pull/1160

**Comment by jnasselle** [comment]
- Jenkins branch bump was already handled here https://github.com/wazuh/wazuh-jenkins/pull/5296
