### ISSUE TITLE
Support new stage RC 1 for 4.4.5

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#17783]
## Description

This issue attempts to support a new stage RC1 for 4.4.5 in the Wazuh system.

## Tasks

- [ ] Testing tag v4.4.5-rc1 is created in all repositories. 
   - [x] @wazuh/core 
      - [x] https://github.com/wazuh/wazuh
      - [x] https://github.com/wazuh/wazuh-packages
  - [ ] @wazuh/qa 
    - [x] https://github.com/wazuh/wazuh-automation
    - [x] https://github.com/wazuh/wazuh-qa
    - [ ] https://github.com/wazuh/wazuh-jenkins
  - [x] @wazuh/cicd
    - [x] https://github.com/wazuh/wazuh-docker
    - [x] https://github.com/wazuh/wazuh-puppet
    - [x] https://github.com/wazuh/wazuh-ansible
    - [x] https://github.com/wazuh/wazuh-kubernetes
  - [x] @wazuh/frontend 
    - [x] https://github.com/wazuh/wazuh-security-dashboards-plugin
    - [x] https://github.com/wazuh/wazuh-dashboard
    - [x] https://github.com/wazuh/wazuh-kibana-app
    - [x] https://github.com/wazuh/wazuh-splunk
  - [x] @wazuh/documentation 
    - [x] https://github.com/wazuh/wazuh-documentation
- [x] Packages are created for v4.4.5-rc1. @wazuh/qa   
- [x] Pre-release 4.4.5 RC 1 is created in wazuh/wazuh. @wazuh/qa  
- [x] Testing issues for the release (if applicable) and RC 1 are created and assigned.  @wazuh/qa

**Comment by jnasselle** [comment]
- @wazuh/cicd related repos tags were checked and are approved

**Comment by jnasselle** [comment]
- @wazuh/frontend related repos tags were checked and are approved

**Comment by jnasselle** [comment]
- @wazuh/core  related repos tags were checked and are approved

**Comment by rauldpm** [comment]
## Packages

- Wazuh dashboard app: https://ci.wazuh.info/job/Packages_builder_tier/3007/

**Comment by jnasselle** [comment]
# Packages creation

Due to some Pipeline safety mechanism that avoid using pre-release repo on some targets (macOS, Solaris 10/11, Windows and OVA), a new tier with this targets were executed successfully

https://ci.wazuh.info/job/Packages_builder_tier/3030/

**Comment by rauldpm** [comment]
The wazuh-jenkins tag will be created at the end of the testing process
