### ISSUE TITLE
Support new stage RC 2 for 4.4.5

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#17841]
## Description

This issue attempts to support a new stage RC2 for 4.4.5 in the Wazuh system.

## Tasks

- [x] Testing tag `v4.4.5-rc2` is created in all repositories. 
   - [x] @wazuh/core 
      - [x] https://github.com/wazuh/wazuh
      - [x] https://github.com/wazuh/wazuh-packages
  - [x] @wazuh/qa 
    - [x] ~https://github.com/wazuh/wazuh-automation~
    - [x] https://github.com/wazuh/wazuh-qa
    - [x] ~https://github.com/wazuh/wazuh-jenkins~
  - [x] @wazuh/cicd
    - [x] https://github.com/wazuh/wazuh-docker
    - [x] https://github.com/wazuh/wazuh-puppet
    - [x] https://github.com/wazuh/wazuh-ansible
    - [x] https://github.com/wazuh/wazuh-kubernetes
  - [x] @wazuh/frontend 
    - [x] https://github.com/wazuh/wazuh-security-dashboards-plugin
    - [x] https://github.com/wazuh/wazuh-dashboard
    - [x] https://github.com/wazuh/wazuh-kibana-app
    - [x] https://github.com/wazuh/wazuh-splunk
  - [x] @wazuh/documentation 
    - [x] https://github.com/wazuh/wazuh-documentation
- [x] Packages are created for v4.4.5-rc2. @wazuh/qa   
- [x] Pre-release 4.4.5 RC 2 is created in wazuh/wazuh. @wazuh/core
- [x] Testing issues for the release (if applicable) and RC 2 are created and assigned.  @wazuh/core

**Comment by jnasselle** [comment]
- @wazuh/qa related repos:
  - wazuh/wazuh-automation does not have a reference to revision change. Skipping bump and tag was created
  - wazuh/wazuh-jenkins does not have a reference to revision change. Skipping bump and tag was created
  - wazuh/wazuh-qa https://github.com/wazuh/wazuh-qa/pull/4300. Tag was created

**Comment by jnasselle** [comment]
- @wazuh/cicd related repos:
  - wazuh/wazuh-docker https://github.com/wazuh/wazuh-docker/pull/879 and tag created https://github.com/wazuh/wazuh-docker/tree/v4.4.5-rc2
  - wazuh/wazuh-kubernetes https://github.com/wazuh/wazuh-kubernetes/pull/390 and tag created https://github.com/wazuh/wazuh-kubernetes/tree/v4.4.5-rc2
  - wazuh/wazuh-puppet  https://github.com/wazuh/wazuh-puppet/pull/696 and tag created https://github.com/wazuh/wazuh-puppet/tree/v4.4.5-rc2
  - wazuh/wazuh-ansible  https://github.com/wazuh/wazuh-ansible/pull/945 and tag created https://github.com/wazuh/wazuh-ansible/tree/v4.4.5-rc2

**Comment by AlexRuiz7** [comment]
- @wazuh/frontend repos ready:
  - wazuh/wazuh-kibana-app https://github.com/wazuh/wazuh/issues/17841
  - wazuh/wazuh-splunk Tags for RC2 created from RC1 ones
