### ISSUE TITLE
Research Windows ITs not working without being connected to a manager

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh#17878]
|Related Epic   |
|-----------------------|
|  wazuh/wazuh#17427             |

## Description 
Currently the Windows tests that runs on the `wazuh-qa` repo requires to be connected to a manager to work properly. The idea of this issue is to research why is that and how to avoid it as the Integration tests should not use any other component than the tested one.

This is necessary for the migration to continue, as we can't migrate an Integration test that depends on other component to work (that would be classified as System test). 

### Tasks

- [x] Find why the windows IT needs the agent to be connected to the manager.
- [x] Check if that is because of a `winagent` specific behavior or is an issue with the tests.
- [x] Apply the fix where it corresponds to.

**Comment by QU3B1M** [comment]
- It was found that the ITs depends on the _winagent_ to be connected to a _manager_ because in windows wazuh only works with 1 process, instead of multiple processes handling one component each, so no component (`fim`, `logcollector` nor `modulesd`) is started before `agentd` connects to a `wazuh-server`. The branch `fix_start_windows` has the corresponding modification for the _winagent_ to work just like the _Linux agent_.
- Tests were executed on the `fix_start_windows` branch proving that there several tests are working correctly without a manager connected (not all of the cases are passing, but its an improvement)

**Comment by QU3B1M** [comment]
- After some further testing on the branch `fix_start_windows` it was checked that those changes let the components to run without being connected to a `manager`, anyway the `wazuh-qa` ITs are behaving flaky in that branch, it looks like it has something to do with the way it sets the configuration and restart the service on windows.
- This will be continued on issue https://github.com/wazuh/wazuh/issues/17881 using the branch `fix_start_windows` as base for the tests

**Comment by QU3B1M** [comment]
- Several ITs are passing correctly on branch [`fix_start_windows`](https://github.com/wazuh/wazuh/tree/fix_start_windows) except the `agentd` tests scenarios.
- Research what is wrong in those cases, the results seem to be due to timeouts, but deeper research is required

**Comment by QU3B1M** [comment]
- Research failing ITs it was found that the specific failing scenario is `test_agentd_parametrized_reconnections`, as the `agentd` ITs leak of proper `teardown` and `setup` when one IT fail, the rest is likely to also fail.
- Some changes were made to the ITs on the branch [`test_windows_fix`](https://github.com/wazuh/wazuh-qa/tree/test_windows_fix) trying to debug what is happening. But nothing was found yet
- Manually the tests are ok, the failure has something to do with the `start/stop` of the wazuh service on windows. 
- Tests on Linux are failing because `Retries to slow` or `Retries to quick` that depends on time to time, more like a flaky tests

**Comment by QU3B1M** [comment]
After several modifications on the current `agentd` scenarios I wasn't able to find what is causing the errors
> the windows cases keep failing when they try to **restart** the winagent. Doing the same manually, everything seems to be ok. 

#### But we may have a clue:
When we run the cases on the [`17881_fim_dependencies_and_tests`](https://github.com/wazuh/wazuh/tree/17881_fim_dependencies_and_tests) everything runs ok! And **THIS BRANCH IS A CHILD OF [`fix_start_windows`](https://github.com/wazuh/wazuh/tree/fix_start_windows)**, so the error appeared after this branch was created, it is easier to track when the error was introduced.

**Comment by QU3B1M** [comment]
### Blocked

As the main priority right now is the **Release** and this issue needs deeper research in both sides _(`core`/`wazuh-qa`)_ it will remain blocked until the release is finished.  For now, as this also **blocks** the _Windows github action workflows_ only the Linux ITs will be migrated.

**Comment by QU3B1M** [comment]
### New progress 🚀 
During the work on #17881 it was found that adding a `pytest fixture` to setup the required simulators to make the tested `wazuh-agent` think it's being connected to an actual `wazuh-manager` could be the solution to this problem.

The fixture was added in the general `conftest.py` and configured to auto-start `AuthdSimulator` and `RemotedSimulator` in every `wazuh-agent` execution where the simulators are not started manually.

```python
@pytest.fixture(autouse=True)
def autostart_simulators(request: pytest.FixtureRequest) -> None:
    create_authd = 'authd_simulator' not in request.fixturenames
    create_remoted = 'remoted_simulator' not in request.fixturenames

    if services.get_service() is not WAZUH_MANAGER:
        authd = AuthdSimulator() if create_authd else None
        remoted = RemotedSimulator() if create_remoted else None

        authd.start() if create_authd else None
        remoted.start() if create_remoted else None

    yield

    if services.get_service() is not WAZUH_MANAGER:
        authd.shutdown() if create_authd else None
        remoted.shutdown() if create_remoted else None
```
This fix was tested on all the currently migrated Linux and Windows ITs and it was successful 🟢
