### ISSUE TITLE
Define user configuration and default values for the vulnerability detector module

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#17910]
## Description

This issue aims to define the user configuration options and default values for the vulnerability detector module. The vulnerability detector module is responsible for detecting vulnerabilities in the system and providing relevant information to the users. In order to make the module more flexible and customizable, it is necessary to define the configuration parameters that users can modify to suit their specific needs.

## Expected

After completing this issue, the following outcomes are expected:

- A well-defined set of configuration options for the vulnerability detector module.
- Default values assigned to each configuration option, providing a sensible starting point for users.
- Validation mechanisms in place to ensure that user-provided configuration values are within acceptable ranges or formats.

## DoD (Definition of Done)

- [x] Identify the necessary configuration options for the vulnerability detector module.
- [x] Define the purpose, usage, and acceptable values for each configuration parameter.
- [x] Assign default values to the configuration options, considering best practices and common use cases.

**Comment by Dwordcito** [comment]
The given XML configuration snippet seems to be defining settings for a system that includes both a vulnerability detection module and an indexing module that interacts with Elasticsearch.

```
<vulnerability-detector>
    <enabled>yes</enabled>
    <states-indexation>yes/no</states-indexation>
    <enabled>yes</enabled>
    <feed-interval-update>yes</feed-interval-update>
    <offline-path> </offline-path> or <offline-url> </offline-url> 
</vulnerability-detector>
```

The <vulnerability-detector> block controls the configuration for the vulnerability detection module. 
The <enabled> tag with 'yes' signifies that this module is activated.

<states-indexation></states-indexation> tag is likely used to specify parameters related to the indexation of vulnerability states. While not clearly defined in this example, its value could be a path or a URL.
<offline-path> </offline-path> or <offline-url> </offline-url> tags are probably used to specify the offline source (a path to a local file or a URL) from where vulnerability data can be fetched when online sources are not available or not desired. These fields are left empty in the given example.

--------
```
<indexer>
    <enabled>yes</enabled>
    <hosts>
        <host>http://10.2.20.2:9200</host>
        <host>https://10.2.20.42:9200</host>
    </hosts>

    <username>user</username>
    <password>pwd</password>
    <api_key></api_key>

    <ssl>
      <certificate_authorities>
           <ca> /var/ossec/</ca>
      </certificate_authorities>
      <certificate>cert</certificate>
      <key></key>
    </ssl>
</indexer>
```

The <indexer> block represents the settings for an indexing module, which appears to be configured to connect to an Elasticsearch cluster.

The <enabled> tag with 'yes' denotes that this indexing module is enabled.
<hosts> tag contains the addresses of the Elasticsearch nodes the module will connect to. Here, it seems to connect to nodes with IP addresses '10.2.20.2' and '10.2.20.42' on port '9200'.
The <username> and <password> tags store the credentials needed to authenticate the module's connection to the Elasticsearch cluster.
<api_key></api_key> tag is likely for storing an API key that could also be used for authentication, though it is left blank in this example.

The <ssl> block deals with Secure Socket Layer (SSL) settings for secure connections.

`<certificate_authorities>` specifies the Certificate Authorities (CA) that the module trusts. In this case, the path '/var/ossec/' is given, which could contain a CA certificate file.
`<certificate>` and `<key>` are tags meant for storing the SSL certificate and the corresponding private key for the module, used for mutual SSL authentication. The exact certificate and key are not specified in the example.

**Comment by GabrielEValenzuela** [comment]
# **Update report**
--------------------------

## **Introduction**

This report provides an update on this issue, detailing the tasks that were performed and outlining the default values defined in the design. The purpose of this report is to communicate the progress made on the issue and ensure all stakeholders are informed about the latest developments.

## **Tasks Performed**

The following PRs has been created in order to close as complete this issue:

- #18888 : This PR has for objective, read and load the configuration management to the vulnerability detection module.
It also adds configuration management for the indexer section.

- #18902 : This PR has for objective, introduce essential logic for validating the configuration JSON object passed to the vulnerability detection module. The validation process ensures that the configuration adheres to predefined criteria and handles potential errors throwing the necessary exceptions.

The exceptions raised due to an invalid configuration are `std::runtime`, which can be changed in the future to a custom exception. Additionally, some changes in the JSON object have been performed to make the configuration more readable. The new version is described below

```json
{
        "enabled":      "yes",
        "index-status": "no",
        "feed-update-interval": "60m",
        "offline-url":  "file:///var/algo.tar.gz"
},
{
        "enabled":      "yes",
        "hosts":      ["http://10.2.20.2:9200/", "https://10.2.20.42:9200/"],
        "username":     "user",
        "password":     "pwd",
        "api_key":      "",
        "ssl":  {
                "certificate_authorities":      [  "/var/ossec/" ],
                "certificate":  "cert",
                "key":  ""
        }
}
```  


## **Default Values**

In accordance with the design specifications, the following default values have been defined:

For vulnerabilty detection:
- **enabled:** [N/A]
- **index-status:** [N/A]
- **feed-update-interval:** [300s]
- **offline-url:** [""]

For indexer-status:
- **enabled:** [N/A]
- **hosts:** [N/A]
- **username** [""]
- **api_key:** [""]
- **certificate_authorities:** [""]
- **certificate:** [""]
- **key:** [""]

These default values ensure that the system operates efficiently and consistently, while also providing flexibility for future customization.

## **Conclusion**

This report highlights the progress made on  #17910 and summarizes the tasks performed to address the issue. It also outlines the default values established in the design to maintain system integrity. Further updates and testing will continue until the issue is resolved satisfactorily.

For any inquiries or additional information, please contact  the team.
