### ISSUE TITLE
Support new Wazuh version 4.8.0

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#17925]
# Description

This issue attempts to support a new version 4.8.0 in the Wazuh system. It includes tracking the generation of issues, projects, and numbered branches across all repositories.

# Tasks
Each task must be completed sequentially based on numbering. Tasks within the same subsection might be parallelized.

## 1. Open release tracking project  -> @davidjiglesias 
- [x] Release 4.8.0

### Wazuh-qa -> @wazuh/qa 

- [x] 1. Create numbered branch for current master version (4.7.0) using master branch on wazuh-qa repository
- [x] 2. Bump master branch to 4.8.0 (including changelog) on wazuh-qa repository

### Wazuh-jenkins -> @wazuh/qa 

- [x] 1. Create numbered branch for current master version (4.7.0) using master branch on wazuh-jenkins repository
- [x] 2. Bump master branch to 4.8.0 (including changelog) on wazuh-jenkins repository

### Wazuh-automation -> @wazuh/qa 

- [x] 1. Create numbered branch for current master version (4.7.0) using master branch on wazuh-automation repository
- [x] 2. Bump master branch to 4.8.0 (including changelog) on wazuh-automation repository

### Wazuh-packages -> @wazuh/core

- [x] 1. Create numbered branch for current master version (4.7.0) using master branch on wazuh-packages repository
- [x] 2. Bump master branch to 4.8.0 (including changelog) on wazuh-packages repository
- [x] 3. Build and push testing images for GitHub actions

### Wazuh -> @wazuh/core

- [x] 1. Create numbered branch for current master version (4.7.0) using master branch on wazuh repository
- [x] 2. Bump master branch to 4.8.0 (including changelog) on wazuh repository

### Wazuh-ansible -> @wazuh/cicd

- [x] 1. Create numbered branch for current master version (4.7.0) using master branch on wazuh-ansible repository
- [x] 2. Bump master branch to 4.8.0 (including changelog) on wazuh-ansible repository

### Wazuh-docker -> @wazuh/cicd

- [x] 1. Create numbered branch for current master version (4.7.0) using master branch on wazuh-docker repository
- [x] 2. Bump master branch to 4.8.0 (including changelog) on wazuh-docker repository

### Wazuh-puppet -> @wazuh/cicd

- [x] 1. Create numbered branch for current master version (4.7.0) using master branch on wazuh-puppet repository
- [x] 2. Bump master branch to 4.8.0 (including changelog) on wazuh-puppet repository

### Wazuh-kubernetes -> @wazuh/cicd

- [x] 1. Create numbered branch for current master version (4.7.0) using master branch on wazuh-kubernetes repository
- [x] 2. Bump master branch to 4.8.0 (including changelog) on wazuh-kubernetes repository

### Wazuh-kibana-app -> @wazuh/frontend

- [x] 1. Create numbered branch for current master version (4.7.0) using master branch on wazuh-kibana-app repository
- [x] 2. Bump master branch to 4.8.0 (including changelog) on wazuh-kibana-app repository

### Wazuh-splunk -> @wazuh/frontend

- [x] 1. Create numbered branch for current master version (4.7.0) using master branch on wazuh-splunk repository
- [x] 2. Bump master branch to 4.8.0 (including changelog) on wazuh-splunk repository

### Wazuh-documentation -> @wazuh/documentation

- [x] 1. Create numbered branch for current master version (4.7.0) using master branch on wazuh-documentation repository
- [x] 2. Bump master branch to 4.8.0 (including changelog) on wazuh-documentation repository

### 3. Create AWS resources  -> @wazuh/qa 

- [x] All AWS resources should be regenerated using the Procedure_ecs_task_tier pipeline on branches that have been modified/bumped
  - [x] 4.7.0
  - [x] 4.8.0 (master)
