### ISSUE TITLE
Memory problem when parsing the refactored NVD feed

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#17968]
## Description

Changes need to be made in the development of the NVD feed refactor, because it does not allow the memory increase according to the consumption it used before the development.

#### Comparison of memory and CPU performance
| | Max CPU | Average CPU | Max memory | Average memory |
|-|-|-|-|-|
| **Legacy NVD** | 84% | 72% | **346MB** | 124MB |
| **NVD 2.0**  | 113% | 90% | **1366MB** | 650MB |

- In the table we can see how at the **_maximum memory peak_**, the increase is **+295%**, so it is necessary to apply some fix to the problem.

#### Runtime comparison

| | Fetch | Parse | Insert | Total |
|-|-|-|-|-|
| **Legacy NVD** | 0:55 min | 3:50 min | 1:07 min | **5:52 min** |
| **NVD 2.0**  | 0:12 min | 0:11 min | 1:01 min | **1:24 min** |

### Tasks:
- [x] Analyse, plan and design the best possible solution.
- [x] Develop the proposed solution.
- [x] Check that the development does not affect the functioning of Vulnerability Detector.
- [x] Analyse the new performance results.
- [x] Adding UTs of new functions and fixing already developed UTs.
