### ISSUE TITLE
Support new stage Alpha 1 for 4.5.1 in wazuh repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#18229]
## Description

This issue attempts to support a new stage Alpha 1 for 4.5.1 in the wazuh repository.

## Tasks

- [ ] Ensure changelog is updated for 4.5.1
- [ ] Create tag v4.5.1-alpha1 from branch 4.5.1 on wazuh repository.
- [ ] Create a pre-release: https://github.com/wazuh//releases/tag/v4.5.1-alpha1
- [ ] Create pre-release v4.5.1 Alpha 1 on https://github.com/wazuh/wazuh/releases.
