### ISSUE TITLE
Support new stage Alpha 1 for 4.5.1 in wazuh repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#18230]
## Description

This issue attempts to support a new stage Alpha 1 for 4.5.1 in the wazuh repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.1
- [x] Create tag v4.5.1-alpha1 from branch 4.5.1 on wazuh repository.
- [x] Create a pre-release: https://github.com/wazuh/wazuh/releases/tag/v4.5.1-alpha1

**Comment by vikman90** [comment]
This issue is **blocked** by https://github.com/wazuh/wazuh/pull/18170.
