### ISSUE TITLE
Support new stage RC 1 for 4.5.0 in wazuh repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#18232]
## Description

This issue attempts to support a new stage RC 1 for 4.5.0 in the wazuh repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.0
- [x] Create tag v4.5.0-rc1 from branch 4.5.0 on wazuh repository.
- [x] Create a pre-release: https://github.com/wazuh/wazuh/releases/tag/v4.5.0-rc1
- [x] Create pre-release v4.5.0 RC 1 on https://github.com/wazuh/wazuh/releases.
