### ISSUE TITLE
Support TCP and UDP for remoted at the same time

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh#1838]
The migration from UDP to TCP agents must be progressive in a production environment. So, we need to support both protocols at the same time.

**Comment by juergenc** [comment]
Very good idea, I also stumbled over this obstacle. Migrating from single manager system to a clustered one could be a pain in the a** if you deal with many agents.

**Comment by JcabreraC** [comment]
Hi team,

This issue is to implement support for TCP and/or UDP protocols in the following features:

- Manager active check (`#Ping`  `#Pong`).
- Agent connection and logs sending
- Active Response 
- API requests-related interaction between manager and agents
- Shared files
- Centralized configuration (Agents can be configured remotely by using the **agent.conf** file.)
- Get configuration in JSON format

## Configuration
This feature adds support for TCP and UDP configuration load on secure connection.
The configuration block will allow for the `<connection>secure</connection>` tag to define the protocol used, between UDP, TCP, or both (separated by commas):

| Default values |Allowed values|
|---|---|
| tcp | tcp, udp |

Example:
```xml
<remote>
  <connection>secure</connection>
  <port>1514</port>
  <protocol>udp,tcp</protocol>
  <queue_size>16384</queue_size>
</remote>
```

It also changes the return of the configuration request through the API.
Now the return of the protocol field will be an array, that can have as values "tcp", "udp" or both

```
go run ./wazuh_sock.go -f /var/ossec/queue/ossec/request -m "getconfig remote"
```
```json
Response: ok {"remote":[{"connection":"secure","ipv6":"no","protocol":["TCP"],"port":"1514","queue_size":"131072"},{"connection":"syslog","ipv6":"no","protocol":["UDP"],"port":"514","allowed-ips":["any"]}]}
```

### IPv6: Bad config

This PR also includes the fix for IPv6 detection in the secure connection. 
For example, the following configuration block:
```xml
  <remote>
    <connection>secure</connection>
    <port>1514</port>
    <protocol>TCP, udp</protocol>
    <ipv6>yes</ipv6>
    <queue_size>131072</queue_size>
  </remote>
```
Show the following warning:

```
2021/02/23 20:38:46 wazuh-remoted: WARNING: (9003): Secure connection does not support IPv6. IPv4 will be used instead.
```
Then, it forces the use of IPv4.


## Feature Tests

### Feature Tests: With TCP protocol 

`<protocol>tcp</protocol>`

- [x] `#Ping`  `#Pong` (i.e. `go run ./wazuh_sock.go -s 192.168.0.35:1514 -p tcp `)
- [x] Agent connect and send logs
- [x] Active Response 
- [x] Remote API requeset (i.e.  `go run ./wazuh_sock.go -f /var/ossec/queue/ossec/request -m "019 logcollector getstate"`)
- [ ] API correct visualization of setting:
   - [ ] Static conf: `GET /manager/configuration?section=remote`
   - [x] Active conf: `GET /manager/configuration/request/remote`
- [x] Shared files
- [x] Centralized configuration (Agents can be configured remotely by using the **agent.conf** file.)
- [x]  Get configuration in JSON format (`go run ./wazuh_sock.go -f /var/ossec/queue/ossec/request -m "getconfig remote"`)
- [x] WPK
- [x] Syslog UDP
- [x] Syslog TCP

### Feature Tests: With UDP protocol 

`<protocol>udp</protocol>`

- [x] `#Ping`  `#Pong` (i.e `go run ./wazuh_sock.go -s 192.168.0.35:1514 -p udp -h=false`)
- [x] Agent connect and send logs
- [x] Active Response 
- [x] Remote API requeset (i.e.  `go run ./wazuh_sock.go -f /var/ossec/queue/ossec/request -m "019 logcollector getstate"`)
- [ ] API correct visualization of setting:
   - [ ] Static conf: `GET /manager/configuration?section=remote`
   - [x] Active conf: `GET /manager/configuration/request/remote`
- [x] Shared files
- [x] Centralized configuration (Agents can be configured remotely by using the **agent.conf** file.)
- [x]  Get configuration in JSON format (`go run ./wazuh_sock.go -f /var/ossec/queue/ossec/request -m "getconfig remote"`)
- [x] WPK
- [x] Syslog UDP
- [x] Syslog TCP

### Feature Tests: With TCP + UDP

`<protocol>udp, tcp</protocol>`

- [x] `#Ping`  `#Pong`
- [x] Agent connect and send logs
- [x] Active Response 
- [x] Remote API requeset (i.e.  `go run ./wazuh_sock.go -f /var/ossec/queue/ossec/request -m "019 logcollector getstate"`)
- [ ] API correct visualization of setting:
   - [ ] Static conf: `GET /manager/configuration?section=remote`
   - [x] Active conf: `GET /manager/configuration/request/remote`
- [x] Shared files
- [x] Centralized configuration (Agents can be configured remotely by using the **agent.conf** file.)
- [x]  Get configuration in JSON format (`go run ./wazuh_sock.go -f /var/ossec/queue/ossec/request -m "getconfig remote"`)
- [x] WPK
  - [x] Agent UDP
  - [X] Agent TCP
- [x] Syslog UDP
- [x] Syslog TCP
