### ISSUE TITLE
Release 4.5.1 - RC 1 - E2E UX tests - Demo environment 

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh#18412]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           |Demo environment|
| **Category**            |Wazuh App|
| **Deployment option**   |Demo environment|
| **Previous testing issue**  |       None                          |
| **Main release issue**  |   https://github.com/wazuh/wazuh/issues/18366 |
| **Main E2E UX test issue** | https://github.com/wazuh/wazuh/issues/18365|
| **Release candidate #** |                Alpha 1                          |

## Test description

- [x]  (**T1**): - No errors or warnings found in logs
- [x]  (**T2**): - The daemons are running with the correct user
- [x]  (**T3**): - The status of the Wazuh Indexer clusters is as expected.
- [x]  (**T4**): - No errors in the browser's developer console when browsing the App
- [x]  (**T5**): - Alerts are being generated for each of the modules configured for this purpose
- [x]  (**T6**): - No warning symbols in Discover when expanding a document
- [x]  (**T7**): - Alert generated
- [x] (**T8**): - Search works without specifying a field and using `*`

## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed result. |
| :yellow_circle:  | There is at least one expected failure or one warning found or one test skipped and no failures. |

## Conclusions

<table class="default">
  <tr>
    <td>Status</td>
    <td>Test</td>
    <td>Notes</td>
    <td>Issues detected </td>    
  </tr>
  <tr>
    <td>🟡</td>
    <td>No errors or warnings found in logs</td>
    <td> Found some known issues in the indexers.</td>
    <td>Comment about issues found:
    <ol>
        <li>https://github.com/wazuh/wazuh-packages/issues/2046#issuecomment-1383909709</li>
        <li>https://github.com/wazuh/wazuh-packages/issues/1511#issuecomment-1308329094 </li>
      </ol>
    </td>
  </tr>
  <tr>
    <td>🟢</td>
    <td>The daemons are running with the correct user</td>
    <td> </td>
    <td> </td>    
  </tr>
  <tr>
    <td>🟢</td>
    <td>The status of the Wazuh Indexer clusters is as expected</td>
    <td> </td>
    <td> </td>    
  </tr>
  <tr>
    <td> 🟡 </td>
    <td>No errors in the browser's developer console when browsing the App </td>
    <td>There are known issues reported.  Not stopper for the Release</td>
    <td>     
         Known issues:
        <ol>
        <li>https://github.com/wazuh/wazuh-kibana-app/issues/4108</li>
        <li>https://github.com/wazuh/wazuh-kibana-app/issues/4074</li>
        <li>https://github.com/wazuh/wazuh-kibana-app/issues/4092</li>
        <li>https://github.com/wazuh/wazuh-kibana-app/issues/5745</li>
      </ol>
    </td>    
  </tr>
    <tr>
    <td> 🟢 </td>
    <td>Alerts are being generated for each of the modules configured for this purpose</td>
    <td>Some modules do not generate alerts, but it is known to happen from previous versions. </td>
    <td>Comment about this issue:
        <ol>
        <li>https://github.com/wazuh/wazuh/issues/18065#issuecomment-1660475563 </li>
        </ol>
   </td>    
  </tr>
    <tr>
    <td>🟢</td>
    <td>No warning symbols in Discover when expanding a document</td>
    <td> </td>
    <td> </td>    
  </tr>
    <tr>
    <td>🟢</td>
    <td>Generate an alert and check it in the web UI</td>
    <td> </td>
    <td> </td>    
  </tr>
  <tr>
    <td>🟢</td>
    <td>Search works without specifying a field and using `*`</td>
    <td>The general search works. </td>
    <td>Known issue:
       <ol>
        <li>https://github.com/wazuh/wazuh-kibana-app/issues/5750 </li>
        </ol>
   </td>       
  </tr>
  
</table>

## Auditors' validation

The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ] @teddytpc1 
- [ ] @damarisg / @fcaffieri

**Comment by BelenValdivia** [comment]
## The daemons are running with the correct user 

### Agents

<details>
<summary>Amazon Linux 2 </summary>

1. Check the user: `ps -aux | grep wazuh` 🟢

```

```
</details>

**Comment by BelenValdivia** [comment]
## The status of the Wazuh Indexer clusters is as expected

<details>
<summary>wazuh-indexer</summary>

1. Check nodes: `curl -k -u ADMIN_USER:PASS https://dashboard_IP:9200/_cat/nodes?v` 🟢

```
```

</details>

**Comment by BelenValdivia** [comment]
# T4 - No errors in the browser's developer console when browsing the App

**Comment by BelenValdivia** [comment]
## T5 - Alerts are being generated for each of the modules configured for this purpose

**Comment by BelenValdivia** [comment]
### T6: No warning symbols in Discover when expanding a document 🟢 
After performing several tests both in Discover and in different modules, we have not been able to find any warning.

**Comment by BelenValdivia** [comment]
### Task 7: Generate an alert and check it in the web UI 🟢 

1. Generate alert
```
ssh invalid-user@centos.wazuh.info
invalid-user@centos.wazuh.info's password: 
Permission denied, please try again.
invalid-user@centos.wazuh.info's password: 
Permission denied, please try again.
invalid-user@centos.wazuh.info's password: 
invalid-user@centos.wazuh.info: Permission denied 
```
2. Check if the alerts are in the Dashboard

    ![image](https://github.com/wazuh/wazuh/assets/26927338/3a8c3e7a-0e0c-4c9d-a15f-60bafe2fc5f2)


<details>
<summary>Alert information</summary>

```
{
  "_index": "wazuh-alerts-4.x-env-1-2023.08.15",
  "_id": "Rixb-okB13hRgakkfPmP",
  "_version": 1,
  "_score": null,
  "_source": {
    "predecoder": {
      "hostname": "ip-1x.x.x.x",
      "program_name": "sshd",
      "timestamp": "Aug 15 18:00:45"
    },
    "cluster": {
      "node": "master",
      "name": "wazuh1"
    },
    "agent": {
      "ip": "x.x.x.x",
      "name": "Centos",
      "id": "003"
    },
    "previous_output": "Aug 15 18:00:40 ip-x.x.x.x sshd[8146]: Failed password for root from Y.Y.Y.Y port 40030 ssh2\nAug 15 18:00:35 ip-10-0-1-214 sshd[8143]: Failed password for root from 196.12.203.248 port 40020 ssh2\nAug 15 18:00:30 ip-10X.X.X.X  sshd[8140]: Failed password for root from 196.12.203.248 port 49270 ssh2\nAug 15 18:00:27 ip-X.X.X.X sshd[8137]: Failed password for root from Y.Y.Y.Y port 49268 ssh2\nAug 15 18:00:22 ip-X.X.X.X sshd[8134]: Failed password for root from Y.Y.Y.Y port 49246 ssh2\nAug 15 18:00:17 ip-10-0-1-214 sshd[8131]: Failed password for root from Y.Y.Y.Y port 54956 ssh2\nAug 15 18:00:12 ip-X.X.X.X sshd[8128]: Failed password for root from Y.Y.Y.Y port 54928 ssh2",
    "data": {
      "srcip": "Y.Y.Y.Y",
      "dstuser": "root",
      "srcport": "37462"
    },
    "manager": {
      "name": "wazuh-manager-master-0"
    },
    "rule": {
      "mail": false,
      "level": 10,
      "hipaa": [
        "164.312.b"
      ],
      "pci_dss": [
        "11.4",
        "10.2.4",
        "10.2.5"
      ],
      "tsc": [
        "CC6.1",
        "CC6.8",
        "CC7.2",
        "CC7.3"
      ],
      "description": "sshd: brute force trying to get access to the system. Authentication failed.",
      "groups": [
        "syslog",
        "sshd",
        "authentication_failures"
      ],
      "nist_800_53": [
        "SI.4",
        "AU.14",
        "AC.7"
      ],
      "frequency": 8,
      "gdpr": [
        "IV_35.7.d",
        "IV_32.2"
      ],
      "firedtimes": 4,
      "mitre": {
        "technique": [
          "Brute Force"
        ],
        "id": [
          "T1110"
        ],
        "tactic": [
          "Credential Access"
        ]
      },
      "id": "5763"
    },
    "decoder": {
      "parent": "sshd",
      "name": "sshd"
    },
    "full_log": "Aug 15 18:00:45 ip-X.X.X.X sshd[8149]: Failed password for root from Y.Y.Y.Y port 37462 ssh2",
    "input": {
      "type": "log"
    },
    "location": "/var/log/secure",
    "id": "1692122445.1309221263",
    "GeoLocation": {
      "city_name": "Meknes",
      "country_name": "Morocco",
      "region_name": "Meknes",
      "location": {
        "lon": -5.5396,
        "lat": 33.8916
      }
    },
    "timestamp": "2023-08-15T18:00:45.552+0000"
  },
  "fields": {
    "timestamp": [
      "2023-08-15T18:00:45.552Z"
    ]
  },
  "highlight": {
    "cluster.name": [
      "@opensearch-dashboards-highlighted-field@wazuh1@/opensearch-dashboards-highlighted-field@"
    ],
    "agent.id": [
      "@opensearch-dashboards-highlighted-field@003@/opensearch-dashboards-highlighted-field@"
    ]
  },
  "sort": [
    1692122445552
  ]
}
```
</details>

**Comment by BelenValdivia** [comment]
## Task 8: Search works without specifying a field and using `*`  🟢 

1. `*`

![image](https://github.com/wazuh/wazuh/assets/26927338/a1cab207-a29d-4c16-8e9d-870077083de5)


2. `osq*`


![image](https://github.com/wazuh/wazuh/assets/26927338/60c44f74-4cb2-4351-a83c-5914c356a869)



3. `*ery*`

![image](https://github.com/wazuh/wazuh/assets/26927338/f08f3a0a-8db2-49d8-86b7-bb3c6e4d2558)


4. `*ocker`

    ![image](https://github.com/wazuh/wazuh/assets/26927338/75581b29-91d6-4e79-bd68-4b258d87d35d)

    ![image](https://github.com/wazuh/wazuh/assets/26927338/722ecae6-e1f1-4986-badd-44b62d568f71)

**Comment by davidcr01** [comment]
LGTM
