### ISSUE TITLE
Add debug messages for when AWS logs do not contain the defined discard field

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#18424]
| Affected integration |
|---|
| AWS |

## Description

The AWS module defines the `discard_regex` parameter in order to discard logs according to a given regex that can be found in a determined `field`. When this field is found in the logs and the value matches the declared regex, the module displays a debug message that the log is being discarded. Nevertheless, when the parameter is declared and the field is not present in the log or no match is found for the regex, no message is displayed and every available log is processed. If a user makes a mistake when declaring these parameters, it would not notice any related information in the logs only the ones related to the normal processing of the module.

## Proposed solution 

The module should display a warning message when the declared `discard_field` does not find a match in the logs and a level 3 debug message when the declared regex does not match the value found for that field.

## Tasks
- [ ] Add appropriate debug messages for the defined case.
- [ ] Unit tests without failures. Updated if there are any relevant changes.
- [ ] Integration tests without failures. Updated if there are any relevant changes.
- [ ] Update the documentation if necessary.
- [ ] Add entry to the changelog if necessary.

**Comment by mauromalara** [comment]
Improvement found here: https://github.com/wazuh/wazuh-qa/pull/4278

**Comment by javiersanchz** [comment]
## Update 

- I was analyzing code related to Wazuh modules and testing adding warning messages

**Comment by javiersanchz** [comment]
## Update

- Changes made, but the debug logs for the PR still need to be displayed.

**Comment by javiersanchz** [comment]
## Update

- I had to restructure the issue after the AWS modularization, I have been launching the AWS integration tests as well.

**Comment by javiersanchz** [comment]
## Update

   - I was modifying some implementations of the code and testing to launch it with the parameters to show the DEBUG and warning added.
