### ISSUE TITLE
Improve whodata

### ISSUE THREAD

**Issue by albertomn86** [wazuh/wazuh#1848]
1. Whodata is not working in Amazon Linux due to the default configuration in audit.rules. The _rule -a never,task_ is included by default and blocks the output.

2. Audit 3.0 changed _audispd_ behavior and whodata needs to be upgraded.

## Tasks
- [x] Add the _af_wazuh_ plugin in the correct folder (Audit 2/Audit 3)
- [x] Add folder events: https://github.com/wazuh/wazuh/issues/1771
- [x] Include fix in whodata with recursive operations: https://github.com/wazuh/wazuh/pull/1762
- [x] Auto reload audit rules each 30 seconds. #2056
  - Reload audit rules only if necessary to avoid flooding by Logcollector.
- [x] Automatic reload whodata rules and continue working if auditd is restarted.
- [x] Check audit blocking rules before starting whodata thread.
- [x] Fix whodata compatibility with Audit 3. (Pending fix in Audit)
- [x] Initial healthcheck to ensure that everything is working. #2057

**Comment by albertomn86** [comment]
Related https://github.com/wazuh/wazuh/pull/1762
