### ISSUE TITLE
AL2023 support: Add, detect and scan Amazon Linux 2023 agents with Vulnerability Detector

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#18526]
### Description

The aim of this issue is to be able to detect and scan Amazon Linux 2023 agents by _Vulnerability Detector_, once the feed have been correctly indexed in the Vulnerability database.

### Tasks / Requirements

-  [x] Add configuration block for Amazon Linux 2023 agents
-  [x] Amazon Linux 2023 agents should be recognized by the detector and assigned the proper target feed
-  [x] Scan agent via OVAL and NVD 
-  [x] Evaluate if matching the source or binaries packages based on the information coming from the agents' inventory
-  [x] Cover new cases in unit tests
