### ISSUE TITLE
Engine - Use the agent simulator in test CLI command

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#18527]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0 | Engine | Manager| - | - |

## Description

Currently, the engine has an agent simulator for testing on it. Reference: [#6695](https://github.com/wazuh/wazuh/issues/16695)

It is necessary to integrate the agent simulator with the test command, so that the end user can send an event, just as it takes it from the source (windows event, for example), without having to know all the necessary parameters of the test command of the engine.

### Considerations

The user who uses the agent simulator will be able to:

- Use of events in the original format of the source (example, eventlog, eventchannel)

- Being able to enter a multiline event

## Tasks

- [x] Research of events
- [x] Adapt the agent simulator to the requirements
- [x] Try different types of events
- [ ] Update documentation

**Comment by soynof** [comment]
## List of sources

<b style="font-weight:normal;" id="docs-internal-guid-9d93291b-7fff-89f1-ec9f-391ccf4fa931"><div dir="ltr" style="margin-left:0pt;" align="left">

Module | sources | arguments | queue | example
-- | -- | -- | -- | --
logcollector | audit | Format, label | 49 |  
| | command  |   | 49 |  
| | djb-multilog | | 49 |
| | eventchannel | | 102 |
| | eventlog | | 49 |
| | full_command | | 49 |
| | iis | | 49 |
| | json | | 49 |
| | macos | | 49 |
| | multi-line-regex | | 49 |
| | multi-line | | 49 |
| | mysql_log | | 49 |
| | nmapg | | 49 |
| | postgresql_log | | 49 |
| | snort-full | | 49 |
| | squid | | 49 |
| | syslog | | 49 |
wodles | Github |   | WIP |  
| | Office 365 |   | WIP |  
| | AWS-s3 |   | 49 |  
| | OpenSCAP |   | WIP |  
| | Cis-cat |   | WIP |  
| | Osquery |   | WIP |  
| | Virustotal |   | WIP |  
| | Docker-listener |   | WIP |  
| | Azure |   | WIP |  
Internal modules | DB sync |   | 53 |  
| | hostinfo |   | 51 |  
| | rootcheck |   | 57 |  
| | sca |   | 112 |  
| | syscheck |   | 56 |  
| | syscollector |   | 100 |  
| | upgrade |   | 117 |  
Remote syslog |   |   |   |  

</div></b>

**Comment by soynof** [comment]
### Actual use of agent simulator:

```
root@wazuh-engine:~/repos/wazuh/src/engine/tools# python3 agent_simulator.py -h
usage: agent_simulator.py [-h] [-i AGENT_ID] [-n AGENT_NAME] [-a AGENT_IP] [--dry-run] [-e ENGINE_SOCKET] [-o OUTPUT_FILE] {logcollector,remote-syslog} ...

positional arguments:
  {logcollector,remote-syslog}

optional arguments:
  -h, --help            show this help message and exit
  -i AGENT_ID, --agent-id AGENT_ID
                        Agent ID for event filling
  -n AGENT_NAME, --agent-name AGENT_NAME
                        Agent name for events filling
  -a AGENT_IP, --agent-ip AGENT_IP
                        Agent ip address for events filling
  --dry-run             events wont be sent to the engine socket
  -e ENGINE_SOCKET, --engine-socket ENGINE_SOCKET
                        Where the engine is listening to events
  -o OUTPUT_FILE, --output OUTPUT_FILE
                        Output file where the events will be stored, if empty events wont be saved

```

**Comment by soynof** [comment]
## Audit example:

### Event
`type=CRED_DISP msg=audit(1681997462.455:741): pid=3926 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023`

### Call

`python3 agent_simulator.py logcollector -L "/tmp/audit.log" audi`

**Comment by soynof** [comment]
### Syslog example:

#### Event
`Apr 20 12:13:37 centos8 systemd[1]: Started Wazuh agent.`

#### Call

`python3 agent_simulator.py logcollector -L "systemd" syslog`

#### Result

`1:[001] (agent-001) any->systemd:Apr 20 12:13:37 centos8 systemd[1]: Started Wazuh agent.`

**Comment by soynof** [comment]
### Json example:

#### Event
`{"event": {"example":"something"}}`

#### Call

`python3 agent_simulator.py logcollector -L "/root/source.json" json`

#### Result

`1:[001] (agent-001) any->/root/source.json:{"event": {"example":"something"}}`

**Comment by soynof** [comment]
## Events examples

## logcollector

<details><summary>Audit</summary></details>
<details><summary>Command</summary></details>
<details><summary>djb-multilog</summary></details>
<details><summary>eventchannel</summary></details>
<details><summary>eventlog</summary></details>
<details><summary>full_command</summary></details>
<details><summary>iis</summary></details>
<details><summary>json</summary></details>
<details><summary>macos</summary></details>
<details><summary>multi-line</summary></details>
<details><summary>multi-line-regex</summary></details>
<details><summary>mysql_log</summary></details>
<details><summary>nmapg</summary></details>
<details><summary>postgresql_log</summary></details>
<details><summary>snort-full</summary></details>
<details><summary>squid</summary></details>
<details><summary>syslog</summary></details>

## wodles

<details><summary>Github</summary></details>
<details><summary>Office 365</summary></details>
<details><summary>AWS-s3</summary></details>
<details><summary>OpenSCAP</summary></details>
<details><summary>Cis-cat</summary></details>
<details><summary>Osquery</summary></details>
<details><summary>Virustotal</summary></details>
<details><summary>Docker-listener</summary></details>
<details><summary>Azure</summary></details>

## Internal modules

<details><summary>DB sync</summary></details>
<details><summary>hostinfo</summary></details>
<details><summary>rootcheck</summary></details>
<details><summary>sca</summary></details>
<details><summary>syscheck</summary></details>
<details><summary>syscollector</summary></details>
<details><summary>upgrade</summary></details>

## Remote syslog

**Comment by soynof** [comment]
### References:

[Eventlog](https://learn.microsoft.com/en-us/windows/win32/eventlog/event-logging)

[Eventchannel](https://learn.microsoft.com/en-us/windows/win32/wes/windows-event-log)
