### ISSUE TITLE
GCP Pub/Sub integration tests

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#18552]
|Objective  | Epic issue | 
|--------------|-----------------------------|
|https://github.com/wazuh/wazuh/issues/22732| https://github.com/wazuh/wazuh/issues/18551 |

## Description

As part of https://github.com/wazuh/wazuh/issues/18551, we need to Implement the integration test cases related to `GCP Pub/Sub` while meeting some [requirements](https://github.com/wazuh/wazuh/issues/22732). The development can be broken down into the following tasks.

### Tasks
- [x] https://github.com/wazuh/wazuh/issues/23671
- [x] https://github.com/wazuh/wazuh/issues/23676
- [x] https://github.com/wazuh/wazuh/issues/23674

**Comment by fdalmaup** [comment]
Due to the changes planned for version 5.0, the analysis that is being carried out regarding the External integrations modules, the team's efforts for improvements will be directed to the mentioned version.
