### ISSUE TITLE
Develop a configuration management system for the vulnerability detector module

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#18577]
### Description
This issue aims to implement the functionality that reads configuration settings from the `ossec.conf` file and passes them to a new module named "Vulnerability Detection." The configuration settings will be read from an XML format within the `ossec.conf` file and then converted into a cJSON struct that the Vulnerability Detector module can use.

In the absence of a tag, the JSON field should not have a default value and vulnerability detection should be called without those values

### Configuration example
```
<vulnerability-detection>
    <enabled>yes</enabled>
    <index-status>yes/no</index-status>
    <feed-update-interval>60m</feed-update-interval>
    <offline-url> file:///var/algo.tar.gz</offline-url> or <offline-url>HTTP://url.com/feed.tar.gz</offline-url>
</vulnerability-detection>
<indexer>
    <enabled>yes</enabled>
    <hosts>
        <host>http://10.2.20.2:9200</host>
        <host>https://10.2.20.42:9200</host>
    </hosts>

    <username>user</username>
    <password>pwd</password>
    <api_key></api_key>

    <ssl>
      <certificate_authorities>
           <ca>/var/ossec/</ca>
      </certificate_authorities>
      <certificate>cert</certificate>
      <key></key>
    </ssl>
</indexer>
```

### Expected JSON format
```
{
  "vulnerability-detection": {
    "enabled": "yes",
    "index-status": "yes/no",
    "feed-update-interval": "60m",
    "offline-url": "file:///var/algo.tar.gz"
  },
  "indexer": {
    "enabled": "yes",
    "hosts": ["http://10.2.20.2:9200", "https://10.2.20.42:9200"],
    "username": "user",
    "password": "pwd",
    "api_key": "",
    "ssl": {
      "certificate_authorities": ["/var/ossec/"],
      "certificate": "cert",
      "key": ""
    }
  }
}
```

### Tasks

- [x] Review the provided example configuration format and understand its structure and purpose.
- [x] Identify the appropriate location within the codebase to implement the reading of the `ossec.conf` configuration.
- [x] Extend the current parser to read the XML configuration within the `ossec.conf` file.
- [x] Convert the parsed XML configuration into a cJSON object for easy integration with the Vulnerability Detector module.
- [x] Test the reading and parsing of the configuration settings using example configurations and edge cases.
- [x] Validate that the cJSON object contains the expected values from the XML configuration.
- [x] Ensure error handling mechanisms are in place to handle cases where configuration settings are missing or in an invalid format.
- [x] Document the changes made, including the methods used for reading and parsing the configuration.
ate the issue status to "Closed" in the project management tool once the implementation is verified and complete.

### Definition of Done

- The `ossec.conf` configuration settings have been successfully read and parsed into a cJSON object.
- The Vulnerability Detector module has been updated to use the extracted configuration settings.
- Thorough testing has been conducted to verify the functionality of reading and passing configuration settings.
- Error handling mechanisms are in place to handle missing or invalid configuration settings.
- Documentation has been updated to reflect the changes made to support the new configuration settings.
