### ISSUE TITLE
integration of alb with aws not showing in the ui 

### ISSUE THREAD

**Issue by 00xSayDoo** [wazuh/wazuh#18572]
| Affected integration | wazuh version
|---|---|
| AWS|4.5.0-4.4.5|

## Description

The CloudTrail integration with Wazuh was set up without issues, but the ALB integration did not work. Many different methods were attempted to resolve the issue, but none were successful. The flow log integration was then tried and worked fine, which suggests that the issue may be with the UI.

<details><summary><SERVICE> logs</summary>
running this command to check if i can get the result '/var/ossec/wodles/aws/aws-s3 --bucket wazuh-xxx-xxx-xxxx\ --aws_profile default --reparse --type alb --debug 5' which i can get all the previous result from the bucket . 
<p>

```
DEBUG: ++ Reformat message
DEBUG: {"integration": "aws", "aws": {"log_info": {"aws_account_alias": "", "log_file": "AWSLogs/04990xxxx/elasticloadbalancing/us-east-1/2023/08/24/04990xxxx_elasticloadbalancing_us-east-1_app.NewELb.69bc159d685791ee_20230824T0625Z_52.22.223.197_4nbp7jfs.log.gz", "s3bucket": "wazuh-load-xxxx-xxxx"}, "type": "http", "time": "2023-08-24T06:24:55.513835Z", "elb": "app/NewELb/69bc159d685791ee", "client_port": "57814", "target_port": "80", "request_processing_time": "0.002", "target_processing_time": "0.001", "response_processing_time": "0.000", "elb_status_code": "200", "target_status_code": "200", "received_bytes": "552", "sent_bytes": "370", "request": "GET http://newelb-58xxx.us-east-1.elb.amazonaws.com:80/ HTTP/1.1", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.5845.97 Safari/537.36", "ssl_cipher": "-", "ssl_protocol": "-", "target_group_arn": "arn:aws:elasticloadbalancing:us-east-1:04990xxxx:targetgroup/Ec2TG/d0e31bf0c9183de1", "trace_id": "Root=1-64e6f7b7-58182a7d2f59f26447edc472", "domain_name": "-", "chosen_cert_arn": "-", "matched_rule_priority": "0", "request_creation_time": "2023-08-24T06:24:55.511000Z", "action_executed": "waf,forward", "redirect_url": "-", "error_reason": "-", "target_port_list": "80", "target_status_code_list": "200", "classification": "-", "classification_reason": "-", "source": "alb", "client_ip": "zz.zz.zz.zz", "target_ip": "xx.xx.xx.xx", "target_ip_list": "xx.31.xx.xx"}}
DEBUG: ++ Reformat message
DEBUG: {"integration": "aws", "aws": {"log_info": {"aws_account_alias": "", "log_file": "AWSLogs/04990xxxx/elasticloadbalancing/us-east-1/2023/08/24/04990xxxx_elasticloadbalancing_us-east-1_app.NewELb.69bc159d685791ee_20230824T0625Z_52.22.223.197_4nbp7jfs.log.gz", "s3bucket": "wazuh-xxx-xxxx-xxx"}, "type": "http", "time": "2023-08-24T06:25:00.515913Z", "elb": "app/NewELb/69bc159d685791ee", "client_port": "57814", "target_port": "80", "request_processing_time": "0.002", "target_processing_time": "0.001", "response_processing_time": "0.000", "elb_status_code": "200", "target_status_code": "200", "received_bytes": "551", "sent_bytes": "370", "request": "GET http://newelb-58xxxx.us-east-1.elb.amazonaws.com:80/ HTTP/1.1", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.5845.97 Safari/537.36", "ssl_cipher": "-", "ssl_protocol": "-", "target_group_arn": "arn:aws:elasticloadbalancing:us-east-1:04990xxxx:targetgroup/Ec2TG/d0e31bf0c9183de1", "trace_id": "Root=1-64e6f7bc-06fc6b33057fdf491f68020c", "domain_name": "-", "chosen_cert_arn": "-", "matched_rule_priority": "0", "request_creation_time": "2023-08-24T06:25:00.513000Z", "action_executed": "waf,forward", "redirect_url": "-", "error_reason": "-", "target_port_list": "80", "target_status_code_list": "200", "classification": "-", "classification_reason": "-", "source": "alb", "client_ip": "zz.zz.zz.zz", "target_ip": "xx.xx.xx.xx", "target_ip_list": "xx.xx.xx.xx"}}
DEBUG: +++ DB Maintenance
```
</p>

</details>

then test it with rule tester 

![image](https://github.com/wazuh/wazuh/assets/108477129/66273982-47fb-45a6-9092-5a41a52cc7c3)

here is without re-parse 
```

root@143-xxx-xx-122:/var/ossec/logs# /var/ossec/wodles/aws/aws-s3 --bucket wazuh-xx-xx-xxx --aws_profile default  --type alb --debug 5
DEBUG: +++ Debug mode on - Level: 5
DEBUG: Found configuration for connection retries in /root/.aws/config
DEBUG: +++ Working on 0499xxxxx - us-east-1
DEBUG: +++ Marker: AWSLogs/04990xxxxxx/elasticloadbalancing/us-east-1/2023/08/24/049909184539_elasticloadbalancing_us-east-1_app.NewELb.69bc15zzzzzzzzz_20230824T0635Z_52.22.223.197_3q1wdvcx.log.gz
DEBUG: +++ No logs to process in bucket: 04990xxxxxx/us-east-1
DEBUG: +++ DB Maintenance
```

here is the aws-s3 configure 
```
  <wodle name="aws-s3">
    <disabled>no</disabled>
    <interval>5m</interval>
    <run_on_start>yes</run_on_start>
    <skip_on_error>yes</skip_on_error>
    <bucket type="cloudtrail">
      <name>aws-cloudtrail-logs-0499xxxxx-27b051ea</name>
      <iam_role_arn>arn:aws:iam::04990xxxx:role/wazuh-role</iam_role_arn>
      <aws_account_id>0499xxxxxx39</aws_account_id>
      <aws_profile>default</aws_profile>
      <regions>us-east-1</regions>
    </bucket>
    <bucket type="alb">
      <name>wazuh-xxx-xxx-xxx</name>
      <aws_profile>default</aws_profile>
    </bucket>
    <bucket type="vpcflow">
      <name>ec2-to-xxx-xx-xxx</name>
      <aws_profile>default</aws_profile>
    </bucket>
  </wodle>
```
## Tasks
- [x] Test in a manager.
- [ ] Test in an agent.
- [ ] Unit tests without failures. Updated if there are any relevant changes.
- [ ] Integration tests without failures. Updated if there are any relevant changes.
- [ ] Update the documentation if necessary.
- [ ] Add entry to the changelog if necessary.

**Comment by 00xSayDoo** [comment]
If your logs will not generate any alert you will not get any alb alert in the dashboard, from what i see form the default rules only logs reporting a status error wilt trigger an alert.https://github.com/wazuh/wazuh/blob/38cfe7e537d611243a4128ce5dfd948359e505cc/ruleset/rules/0350-amazon_rules.xml#L161-L194
to solve it 
https://documentation.wazuh.com/current/user-manual/ruleset/custom.html#changing-an-existing-ruleAlso you could generate child rules from 80325  so you get alerts from logs you want to monitor, check this to learn how to generate new child rules:
https://documentation.wazuh.com/current/user-manual/ruleset/custom.html





thank for [Wazuh] Daniel Folch
