### ISSUE TITLE
Implement configuration validation and error handling for the vulnerability detector module

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#18578]
## Description
This issue aims to implement the functionality to interpret the configuration provided using the `nlohmann::json` library. The configuration settings will be extracted from the XML format within the `ossec.conf` file and converted into a `json` object. Additionally, this issue will handle default values and raise exceptions for any invalid configurations.

JSON format.
```
{
  "vulnerability-detection": {
    "enabled": "yes",
    "index-status": "yes/no",
    "feed-update-interval": "60m",
    "offline-url": "file:///var/algo.tar.gz"
  },
  "indexer": {
    "enabled": "yes",
    "hosts": ["http://10.2.20.2:9200", "https://10.2.20.42:9200"],
    "username": "user",
    "password": "pwd",
    "api_key": "",
    "ssl": {
      "certificate_authorities": ["/var/ossec/"],
      "certificate": "cert",
      "key": ""
    }
  }
}

```
#### Validations

1.   `<vulnerability-detection>`

        index-status: This can be either "yes" or "no".
        offline-url: This should be an array of URLs, both starting with "file://" and "http://" or "https://". OPTIONAL

2.  `<indexer>`
        api_key: <OPTIONAL>
            certificate_authorities:
                ca: This can be a file path or directory path.
            certificate: This is optional and can be left empty. OPTIONAL
            key: This is optional and can be left empty. OPTIONAL
            
### Tasks

- [x] Review the provided example configuration and understand its structure and values.
- [x] Implement mechanisms to handle default values for configuration settings that are not specified.
- [x] Ensure that required configuration settings are present and have valid values; otherwise, raise exceptions.
- [x] Validate that the resulting `json` object contains the expected values from the XML configuration.
- [x] Handle cases where the configuration is missing or has invalid values by raising appropriate exceptions.

### Definition of Done

- The `nlohmann::json` library has been used to handle the interpretation and conversion process.
- Default values are applied to configuration settings if not specified.
- Mechanisms are in place to raise exceptions for missing or invalid configuration settings.
- Code changes have been reviewed and approved by the development team.
