### ISSUE TITLE
Allow remoted to connect to external DB for retrieving client key

### ISSUE THREAD

**Issue by TJOSERAFAEL** [wazuh/wazuh#1859]
## Feature request

|Compatibility|Components involved|Branch|Due date
|---|---|---|---|
|Manager|Remoted and Authd|[dev-remoted-sql](https://github.com/wazuh/wazuh/compare/3.8...dev-remoted-sql)|12/04/2018|

## Description

We need to implement the feature so that when **remoted** reads and invalid key, it can retrieve it from an external database server and store it to the **client.keys** file.

## Subasks 

- Implement a dedicated Wazuh module for handling external key requests
  - [x] Listen to the dedicated socket
  - [x] Handle key retrieving request
  - [x] Call external script
  - [x] Retrieve results with correct format 
  - [x] Store the key in the client.keys file with an expiration date
  - [x] Query module configuration on demand
  - [x] Multi-thread the whole process
  - [x] Performance tunning
  - [ ] Test all use cases
  - [x] Documentation

- Make remoted daemon send the request to the key request module if the key is wrong
  - [x] Send to the dedicated key requests module socket the request
  - [x] Throw a warning/info message about this

- Implement a generic external script for retrieving keys from an external database
  - [x] Implementation of the script with the chosen language
  - [x] Make the script connect to an external database
  - [x] Format the output of the script

- Implement and define some  ossec.conf  parameters for disabling and configuring this feature
  - [x] Add new options labels
  - [x] Read the configuration labels
  - [x] Prepare errors information
  - [x] Test all use cases

### Involved functions

- auth_add_agent
- auth_remove_agent
- ReadSecMSG
- run_local_server

This is only valid for a master manager, a worker node should not do this.

**Comment by TJOSERAFAEL** [comment]
### Implementation and Design

This feature must follow the Wazuh cluster philosophy , workers cant take decisions by the own, the master has to take them and sync the files accordingly. 

A wodle called KeyRequest will be created and only activated on the master node. If a worker receives a request for a new key, it will be forwarded to the master node of the cluster being this the responsible of adding the key and sync the new **client.keys** file to the worker.

### Flow Diagram

![master woker](https://user-images.githubusercontent.com/16609513/48412514-3273a700-e745-11e8-9294-435b4d2fb815.png)

### Client keys file structure

As we want that each worker node has it own client.keys file with only the keys that will be used in that node, we need to tag each line of the **client.keys** file with the worker node that it will belong to.

![client keys](https://user-images.githubusercontent.com/16609513/48413297-9ac38800-e747-11e8-9c41-9b1bc84a39f8.png)

This allows to not have repeated keys in different workers.

### Some scenarios

 - An agent behind a load balancer configured incorrectly can cause many key requests if it changes the worker node often. If the time of syncing the clients.keys is high, the agent buffer will be full, causing it to loose events.

![loadbalancer](https://user-images.githubusercontent.com/16609513/48418200-f8120600-e754-11e8-9b01-7fd52efdac62.png)

- The worker node must wait for the client.keys to synchronize, speed is critical to avoid an agent buffer filling.

**Comment by vikman90** [comment]
## Integration protocol

### Find by agent ID

The manager will query an agent key by ID when the agent informed its ID. This happens when the agent was registered with a non-unique IP address, for instance, "10.0.0.0/24" or "any".

Example of call:
```sh
./agent_key_pull.py id 001
```

### Find by agent IP

When an agent is set up with a unique IP, it does not report its ID. In this case, Remoted will query an agent key by IP.

Example of call:
```sh
./agent_key_pull.py ip 192.168.22.31
```

### Expected output

The AgentKeyPulling module will always expect a JSON object in the script's standard output.

On success, we propose this format:

- `error`: it must be 0.
- `data`:
  - `id`: string containing the agent's ID, as it appears in the first word of any entry of the file _/var/ossec/etc/client.keys_.
  - `name`: the name of the agent, as it appears in the second word of _client.keys_.
  - `ip`: allowed IP range (CIDR), or `any` (third word of _client.keys_). Examples: `192.168.1.2`, `10.0.0.0/24`, `any`.
  - `key`: the agent's password, as it appears in the fourth word of _client.keys_.

Example:
```json
{
  "error": 0,
  "data": {
    "id": "001",
    "name": "agent-db-server1",
    "ip": "any",
    "key": "aa14db19dc2d41f206d545e1ed37883d054067cd629189cf3c80e6df96b90df9"
  }
}
```

On error condition, we propose this format:

- `error`: a number other than 0.
- `message`: string describing the error. The module will print this message in the manager's log (_ossec.log_).

Example:
```json
{
  "error": 104,
  "message": "External database address unreachable."
}
```

This format is according to the Wazuh API, as well as some internal APIs, like the local Authd server.

**Comment by TJOSERAFAEL** [comment]
### Enhancement 
In order to speed up the performance we can implement an optional enhancement as follows:

### Tasks

- Prepare N threads to open the external script only one time
- Make the scripts read from the `STDIN`
- Make each thread read the output from `STDOUT`

This will improve the performance by not launching the script every time a new key polling is requested.
