### ISSUE TITLE
Add AWS Custom Logs Buckets Unit Tests

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#18595]
| Affected integration |
|---|
| AWS |

## Description

During the development of #13388, a total coverage of 88% was obtained although the objective was 95% or higher. One of the untested code sections is the one involved in the AWS Custom Logs Buckets development (#13577) which was not included in the unit tests, only its modularization as it can be seen [here](https://github.com/wazuh/wazuh/issues/13388#issuecomment-1682910575). 
We should review the used feature-related classes and the code present in `aws_s3.py` in order to cover the untested code.

## Tasks
- [ ] Update unit tests and achieve a coverage higher than 95% for the AWS Custom Logs Buckets related code.
- [ ] Update the documentation if necessary.
- [ ] Add entry to the changelog if necessary.

**Comment by RamosFe** [comment]
## Update

After adding unit tests for the AWS Custom Logs Buckets functionality:

```
Name                                                                  Stmts   Miss  Cover
-----------------------------------------------------------------------------------------
__init__.py                                                               0      0   100%
aws_s3.py                                                                91     18    80%
aws_tools.py                                                            141     20    86%
buckets_s3/__init__.py                                                   10      0   100%
buckets_s3/aws_bucket.py                                                423     17    96%
buckets_s3/cloudtrail.py                                                 26      3    88%
buckets_s3/config.py                                                     91      7    92%
buckets_s3/guardduty.py                                                  64      1    98%
buckets_s3/load_balancers.py                                             69      0   100%
buckets_s3/server_access.py                                             135     13    90%
buckets_s3/umbrella.py                                                   22      0   100%
buckets_s3/vpcflow.py                                                   103     11    89%
buckets_s3/waf.py                                                        38      0   100%
services/__init__.py                                                      4      0   100%
services/aws_service.py                                                  44      0   100%
services/cloudwatchlogs.py                                              189      6    97%
services/inspector.py                                                    51      6    88%
subscribers/__init__.py                                                   4      0   100%
subscribers/s3_log_handler.py                                           110     46    58%
subscribers/sqs_message_processor.py                                     34      1    97%
subscribers/sqs_queue.py                                                 60      7    88%
tests/__init__.py                                                         0      0   100%
tests/aws_utils.py                                                      115      0   100%
tests/conftest.py                                                        10      0   100%
tests/test_aws_bucket.py                                                598      1    99%
tests/test_aws_s3.py                                                     41      0   100%
tests/test_aws_service.py                                                52      0   100%
tests/test_cloudtrail.py                                                 31      0   100%
tests/test_cloudwatchlogs.py                                            194      0   100%
tests/test_config.py                                                     66      0   100%
tests/test_guardduty.py                                                 117      0   100%
tests/test_inspector.py                                                  51      0   100%
tests/test_load_balancers.py                                             87      0   100%
tests/test_s3_log_handler.py                                             72      0   100%
tests/test_server_access.py                                             112      1    99%
tests/test_sqs_message_processor.py                                      19      0   100%
tests/test_sqs_queue.py                                                  83      0   100%
tests/test_tools.py                                                      88      0   100%
tests/test_umbrella.py                                                   38      0   100%
tests/test_vpcflow.py                                                   160      0   100%
tests/test_waf.py                                                        39      0   100%
tests/test_wazuh_integration.py                                         288      1    99%
wazuh_integration.py                                                    245     21    91%
-----------------------------------------------------------------------------------------
TOTAL                                                                  4272    207    95%

```
