### ISSUE TITLE
Add missing unit tests to the AWS module

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#18596]
| Affected integration |
|---|
| AWS |

## Description
As described in #18595, some code sections of the AWS module were not covered or modified in the unit tests before the merge. This issue aims to 
cover each feature and related code that has not been taken into account in the aforementioned issue, which is:
- AWS Services and subclasses discard_regex feature (#13577)
- `default_config` method modification (#14978)

The modifications of the UTs in the present issue should not only consider these two features but also the code that is not part of #18595, trying to reach a total coverage of 95% or higher. 

## Tasks
- [ ] Unit tests without failures and related coverage reports.
- [ ] Update the documentation if necessary.
- [ ] Add entry to the changelog if necessary.

**Comment by javiersanchz** [comment]
## Update 

 - I started to develop the requested unit tests and I was also looking for other tests that could be created to cover the 95% of the requested tests.

**Comment by javiersanchz** [comment]
## Update

- I continued with the unit_test of aws, I was testing to launch them and correcting error in the new test for default_cofig.

**Comment by javiersanchz** [comment]
## Update

- I went back to the issue, made some changes and tried launching the tests to see if they passed.

**Comment by javiersanchz** [comment]
## Update

- I fixed some bugs and added some more tests.

**Comment by javiersanchz** [comment]
## Update

- I've been implementing some more tests and correcting errors that I got when running them,

**Comment by javiersanchz** [comment]
## Update 

 - I'm working on the requested changes, launching Coverage and covering the AWS module methods with low percentages.

**Comment by javiersanchz** [comment]
## Update

   - I'm covering the get_logs and process_file functions of s3_log_handler.py (I've been investigating because I can't get them to run properly).
