### ISSUE TITLE
Support new stage RC 1 for 4.5.2 in wazuh repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#18606]
## Description

This issue attempts to support a new stage RC 1 for 4.5.2 in the wazuh repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.2
- [x] Create tag v4.5.2-rc1 from branch 4.5.2 on wazuh repository.
- [x] Create a pre-release: https://github.com/wazuh/wazuh/releases/tag/v4.5.2-rc1
