### ISSUE TITLE
Make FIM follow attribute and permission changes in Windows agent

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#1861]
FIM is able to follow the file mode, this allows it to detect changes in file permissions on UNIX systems.

However, FIM can't report changes in file attributes or permissions on Windows agents. Please add this capacity to monitor the Windows file attributes and the permission matrix.

## Subtasks

- [x] Read file attributes.
- [x] Read file permissions and produce a matrix.
- [x] Apply this feature in the scheduled scans.
- [x] Apply this feature in the real-time engine: let Windows poll system monitor changes in attributes.
- [x] Apply this feature in the audit engine: capture who-data for attribute and permission changes.
- [x] Show the Windows permissions in alerts.log.

Working on [dev-win-fim-attrs](https://github.com/wazuh/wazuh/tree/dev-win-fim-attrs).

**Comment by crolopez** [comment]
## Attributes field example

### alerts.json

``` JSON
"syscheck":{
    "path":"c:\\users\\administrator\\desktop\\test\\attrs\\file1.txt",
    "size_after":"322",
    "uid_after":"S-1-5-32-544",
    "md5_after":"136058061be1133269fee9c666b345f8",
    "sha1_after":"db3d49f4381c732132f2bd297246944a63c2b01b",
    "sha256_after":"ae6e8aac4a7e5d53aca6fd2ca011894490ecf43a90d09f167660491bfbce3572",
    "attrs_before":[
        "ARCHIVE",
        "COMPRESSED",
        "HIDDEN"
    ],
    "attrs_after":[
        "ARCHIVE",
        "COMPRESSED",
        "HIDDEN",
        "READONLY"
    ],
    "uname_after":"Administrators",
    "mtime_after":"2018-11-13T16:38:58",
    "event":"modified",
    "audit":{
        "process":{
            "id":""
        }
    }
}
```
### alerts.log
```
** Alert 1542129655.319723: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,
2018 Nov 13 17:20:55 (winagent) any->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
File 'c:\users\administrator\desktop\test\attrs\file1.txt' checksum changed.
Old attributes were: 'ARCHIVE,COMPRESSED,HIDDEN'
Now they are 'ARCHIVE,COMPRESSED,HIDDEN,READONLY'

Attributes:
 - Size: 322
 - Date: Tue Nov 13 16:38:58 2018
 - User: Administrators (S-1-5-32-544)
 - MD5: 136058061be1133269fee9c666b345f8
 - SHA1: db3d49f4381c732132f2bd297246944a63c2b01b
 - SHA256: ae6e8aac4a7e5d53aca6fd2ca011894490ecf43a90d09f167660491bfbce3572
 - File attributes: 
  + ARCHIVE
  + COMPRESSED
  + HIDDEN
  + READONLY
```

**Comment by crolopez** [comment]
## New permissions field example

### alerts.json

``` JSON
    "syscheck":{
        "path":"c:\\users\\administrator\\desktop\\test\\attrs\\file1.txt",
        "size_after":"32",
        "win_perm_before":[
            {
                "name":"standar_user",
                "denied":[
                    "FILE_READ_DATA",
                    "FILE_WRITE_DATA",
                    "FILE_APPEND_DATA",
                    "FILE_READ_EA",
                    "FILE_WRITE_EA",
                    "FILE_EXECUTE",
                    "FILE_READ_ATTRIBUTES",
                    "FILE_WRITE_ATTRIBUTES",
                    "READ_CONTROL"
                ],
                "allowed":[
                    "FILE_READ_DATA",
                    "FILE_WRITE_DATA",
                    "FILE_APPEND_DATA",
                    "FILE_READ_EA",
                    "FILE_WRITE_EA",
                    "FILE_READ_ATTRIBUTES",
                    "FILE_WRITE_ATTRIBUTES",
                    "READ_CONTROL",
                    "SYNCHRONIZE"
                ]
            },
            {
                "name":"SYSTEM",
                "allowed":[
                    "FILE_READ_DATA",
                    "FILE_WRITE_DATA",
                    "FILE_APPEND_DATA",
                    "FILE_READ_EA",
                    "FILE_WRITE_EA",
                    "FILE_EXECUTE",
                    "FILE_READ_ATTRIBUTES",
                    "FILE_WRITE_ATTRIBUTES",
                    "FILE_DELETE",
                    "DELETE",
                    "READ_CONTROL",
                    "WRITE_DAC",
                    "WRITE_OWNER",
                    "SYNCHRONIZE"
                ]
            },
            {
                "name":"Administrators",
                "allowed":[
                    "FILE_READ_DATA",
                    "FILE_WRITE_DATA",
                    "FILE_APPEND_DATA",
                    "FILE_READ_EA",
                    "FILE_WRITE_EA",
                    "FILE_EXECUTE",
                    "FILE_READ_ATTRIBUTES",
                    "FILE_WRITE_ATTRIBUTES",
                    "FILE_DELETE",
                    "DELETE",
                    "READ_CONTROL",
                    "WRITE_DAC",
                    "WRITE_OWNER",
                    "SYNCHRONIZE"
                ]
            },
            {
                "name":"Administrator",
                "allowed":[
                    "FILE_READ_DATA",
                    "FILE_WRITE_DATA",
                    "FILE_APPEND_DATA",
                    "FILE_READ_EA",
                    "FILE_WRITE_EA",
                    "FILE_EXECUTE",
                    "FILE_READ_ATTRIBUTES",
                    "FILE_WRITE_ATTRIBUTES",
                    "FILE_DELETE",
                    "DELETE",
                    "READ_CONTROL",
                    "WRITE_DAC",
                    "WRITE_OWNER",
                    "SYNCHRONIZE"
                ]
            },
            {
                "name":"jacinto",
                "allowed":[
                    "FILE_READ_DATA",
                    "FILE_WRITE_DATA",
                    "FILE_APPEND_DATA",
                    "FILE_READ_EA",
                    "FILE_WRITE_EA",
                    "FILE_EXECUTE",
                    "FILE_READ_ATTRIBUTES",
                    "FILE_WRITE_ATTRIBUTES",
                    "FILE_DELETE",
                    "DELETE",
                    "READ_CONTROL",
                    "WRITE_DAC",
                    "WRITE_OWNER",
                    "SYNCHRONIZE"
                ]
            }
        ],
        "win_perm_after":[
            {
                "name":"standar_user",
                "denied":[
                    "FILE_READ_DATA",
                    "FILE_WRITE_DATA",
                    "FILE_READ_EA",
                    "FILE_WRITE_EA",
                    "FILE_EXECUTE",
                    "FILE_READ_ATTRIBUTES",
                    "FILE_WRITE_ATTRIBUTES",
                    "READ_CONTROL"
                ],
                "allowed":[
                    "FILE_READ_DATA",
                    "FILE_WRITE_DATA",
                    "FILE_APPEND_DATA",
                    "FILE_READ_EA",
                    "FILE_WRITE_EA",
                    "FILE_READ_ATTRIBUTES",
                    "FILE_WRITE_ATTRIBUTES",
                    "READ_CONTROL",
                    "SYNCHRONIZE"
                ]
            },
            {
                "name":"SYSTEM",
                "allowed":[
                    "FILE_READ_DATA",
                    "FILE_WRITE_DATA",
                    "FILE_APPEND_DATA",
                    "FILE_READ_EA",
                    "FILE_WRITE_EA",
                    "FILE_EXECUTE",
                    "FILE_READ_ATTRIBUTES",
                    "FILE_WRITE_ATTRIBUTES",
                    "FILE_DELETE",
                    "DELETE",
                    "READ_CONTROL",
                    "WRITE_DAC",
                    "WRITE_OWNER",
                    "SYNCHRONIZE"
                ]
            },
            {
                "name":"Administrators",
                "allowed":[
                    "FILE_READ_DATA",
                    "FILE_WRITE_DATA",
                    "FILE_APPEND_DATA",
                    "FILE_READ_EA",
                    "FILE_WRITE_EA",
                    "FILE_EXECUTE",
                    "FILE_READ_ATTRIBUTES",
                    "FILE_WRITE_ATTRIBUTES",
                    "FILE_DELETE",
                    "DELETE",
                    "READ_CONTROL",
                    "WRITE_DAC",
                    "WRITE_OWNER",
                    "SYNCHRONIZE"
                ]
            },
            {
                "name":"Administrator",
                "allowed":[
                    "FILE_READ_DATA",
                    "FILE_WRITE_DATA",
                    "FILE_APPEND_DATA",
                    "FILE_READ_EA",
                    "FILE_WRITE_EA",
                    "FILE_EXECUTE",
                    "FILE_READ_ATTRIBUTES",
                    "FILE_WRITE_ATTRIBUTES",
                    "FILE_DELETE",
                    "DELETE",
                    "READ_CONTROL",
                    "WRITE_DAC",
                    "WRITE_OWNER",
                    "SYNCHRONIZE"
                ]
            },
            {
                "name":"jacinto",
                "allowed":[
                    "FILE_READ_DATA",
                    "FILE_WRITE_DATA",
                    "FILE_APPEND_DATA",
                    "FILE_READ_EA",
                    "FILE_WRITE_EA",
                    "FILE_EXECUTE",
                    "FILE_READ_ATTRIBUTES",
                    "FILE_WRITE_ATTRIBUTES",
                    "FILE_DELETE",
                    "DELETE",
                    "READ_CONTROL",
                    "WRITE_DAC",
                    "WRITE_OWNER",
                    "SYNCHRONIZE"
                ]
            }
        ],
        "uid_after":"S-1-5-32-544",
        "md5_after":"48f8e753943113e4befe4930b8bd8622",
        "sha1_after":"9997792c49c1e0323b4b24acb25045957be6af24",
        "sha256_after":"3f31098469d275c307c605e34a6b37ecd675b1bd4315f3a524bf7bce8147dd7e",
        "attrs_after":[
            "ARCHIVE",
            "HIDDEN",
            "NOT_CONTENT_INDEXED"
        ],
        "uname_after":"Administrators",
        "mtime_after":"2018-11-19T15:04:02",
        "event":"modified",
        "audit":{
            "process":{
                "id":""
            }
        }
    }
```
### alerts.log
```** Alert 1542707371.43980: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,
2018 Nov 20 09:49:31 (agewin) any->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
File 'c:\users\administrator\desktop\test\attrs\file1.txt' checksum changed.
Permissions changed.

Attributes:
 - Size: 32
 - Permissions: 
  [standar_user]  (DENIED)
  + FILE_READ_DATA
  + FILE_WRITE_DATA
  + FILE_READ_EA
  + FILE_WRITE_EA
  + FILE_EXECUTE
  + FILE_READ_ATTRIBUTES
  + FILE_WRITE_ATTRIBUTES
  + READ_CONTROL
  [standar_user]  (ALLOWED)
  + FILE_READ_DATA
  + FILE_WRITE_DATA
  + FILE_APPEND_DATA
  + FILE_READ_EA
  + FILE_WRITE_EA
  + FILE_READ_ATTRIBUTES
  + FILE_WRITE_ATTRIBUTES
  + READ_CONTROL
  + SYNCHRONIZE
  [SYSTEM]  (ALLOWED)
  + FILE_READ_DATA
  + FILE_WRITE_DATA
  + FILE_APPEND_DATA
  + FILE_READ_EA
  + FILE_WRITE_EA
  + FILE_EXECUTE
  + FILE_READ_ATTRIBUTES
  + FILE_WRITE_ATTRIBUTES
  + FILE_DELETE
  + DELETE
  + READ_CONTROL
  + WRITE_DAC
  + WRITE_OWNER
  + SYNCHRONIZE
  [Administrators]  (ALLOWED)
  + FILE_READ_DATA
  + FILE_WRITE_DATA
  + FILE_APPEND_DATA
  + FILE_READ_EA
  + FILE_WRITE_EA
  + FILE_EXECUTE
  + FILE_READ_ATTRIBUTES
  + FILE_WRITE_ATTRIBUTES
  + FILE_DELETE
  + DELETE
  + READ_CONTROL
  + WRITE_DAC
  + WRITE_OWNER
  + SYNCHRONIZE
  [Administrator]  (ALLOWED)
  + FILE_READ_DATA
  + FILE_WRITE_DATA
  + FILE_APPEND_DATA
  + FILE_READ_EA
  + FILE_WRITE_EA
  + FILE_EXECUTE
  + FILE_READ_ATTRIBUTES
  + FILE_WRITE_ATTRIBUTES
  + FILE_DELETE
  + DELETE
  + READ_CONTROL
  + WRITE_DAC
  + WRITE_OWNER
  + SYNCHRONIZE
  [jacinto]  (ALLOWED)
  + FILE_READ_DATA
  + FILE_WRITE_DATA
  + FILE_APPEND_DATA
  + FILE_READ_EA
  + FILE_WRITE_EA
  + FILE_EXECUTE
  + FILE_READ_ATTRIBUTES
  + FILE_WRITE_ATTRIBUTES
  + FILE_DELETE
  + DELETE
  + READ_CONTROL
  + WRITE_DAC
  + WRITE_OWNER
  + SYNCHRONIZE
 - Date: Mon Nov 19 15:04:02 2018
 - User: Administrators (S-1-5-32-544)
 - MD5: 48f8e753943113e4befe4930b8bd8622
 - SHA1: 9997792c49c1e0323b4b24acb25045957be6af24
 - SHA256: 3f31098469d275c307c605e34a6b37ecd675b1bd4315f3a524bf7bce8147dd7e
 - File attributes: 
  + ARCHIVE
  + HIDDEN
  + NOT_CONTENT_INDEXED
```

**Comment by crolopez** [comment]
### New alerts.log format

```
** Alert 1542724703.187623: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,
2018 Nov 20 14:38:23 (agewin) any->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
File 'c:\users\administrator\desktop\test\attrs\file1.txt' checksum changed.
Old attributes were: 'ARCHIVE, COMPRESSED, NOT_CONTENT_INDEXED'
Now they are 'ARCHIVE, COMPRESSED, HIDDEN, NOT_CONTENT_INDEXED'
Permissions changed.

Attributes:
 - Size: 60
 - Date: Tue Nov 20 14:20:31 2018
 - User: Administrators (S-1-5-32-544)
 - MD5: 011033d08de6d3d286db4ec882a4a952
 - SHA1: e075e23ee52478da4b69199669dac0801be617c8
 - SHA256: d0b126632043c4934a7dff0406c467238bb806e48a75fdee8f91bd06e85b477c
 - File attributes: ARCHIVE, COMPRESSED, HIDDEN, NOT_CONTENT_INDEXED
 - Permissions: 
   standar_user  (DENIED) - FILE_READ_DATA, FILE_WRITE_DATA, FILE_APPEND_DATA, FILE_READ_EA, FILE_WRITE_EA, FILE_EXECUTE, FILE_READ_ATTRIBUTES, FILE_WRITE_ATTRIBUTES, READ_CONTROL
   standar_user  (ALLOWED) - FILE_READ_DATA, FILE_WRITE_DATA, FILE_APPEND_DATA, FILE_READ_EA, FILE_WRITE_EA, FILE_READ_ATTRIBUTES, FILE_WRITE_ATTRIBUTES, READ_CONTROL, SYNCHRONIZE
   SYSTEM  (ALLOWED) - FILE_READ_DATA, FILE_WRITE_DATA, FILE_APPEND_DATA, FILE_READ_EA, FILE_WRITE_EA, FILE_EXECUTE, FILE_READ_ATTRIBUTES, FILE_WRITE_ATTRIBUTES, FILE_DELETE, DELETE, READ_CONTROL, WRITE_DAC, WRITE_OWNER, SYNCHRONIZE
   Administrators  (ALLOWED) - FILE_READ_DATA, FILE_WRITE_DATA, FILE_APPEND_DATA, FILE_READ_EA, FILE_WRITE_EA, FILE_EXECUTE, FILE_READ_ATTRIBUTES, FILE_WRITE_ATTRIBUTES, FILE_DELETE, DELETE, READ_CONTROL, WRITE_DAC, WRITE_OWNER, SYNCHRONIZE
   Administrator  (ALLOWED) - FILE_READ_DATA, FILE_WRITE_DATA, FILE_APPEND_DATA, FILE_READ_EA, FILE_WRITE_EA, FILE_EXECUTE, FILE_READ_ATTRIBUTES, FILE_WRITE_ATTRIBUTES, FILE_DELETE, DELETE, READ_CONTROL, WRITE_DAC, WRITE_OWNER, SYNCHRONIZE
   jacinto  (ALLOWED) - FILE_READ_DATA, FILE_WRITE_DATA, FILE_APPEND_DATA, FILE_READ_EA, FILE_WRITE_EA, FILE_EXECUTE, FILE_READ_ATTRIBUTES, FILE_WRITE_ATTRIBUTES, FILE_DELETE, DELETE, READ_CONTROL, WRITE_DAC, WRITE_OWNER, SYNCHRONIZE

```
