### ISSUE TITLE
Release 4.5.2 - RC 1 - Indexer/Dashboard packages

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh#18621]
# Packages tests metrics information
|||
| :--                              | :--                                                             |
| **Main release candidate issue** | https://github.com/wazuh/wazuh/issues/18618 |
| **Main packages metrics issue**  | https://github.com/wazuh/wazuh/issues/18620 |
| **Version**                      | 4.5.2                                                   |
| **Release candidate**            | RC1                                                      |
| **Tag**                          | [v4.5.2-rc1](https://github.com/wazuh/wazuh/tree/v4.5.2-rc1)  |

---
# Packages information
|||
| :--                              | :--                                                             |
| Repository | `packages-dev.wazuh.com`
| Package path | `pre-release`
| Package revision | `1`

--- 
# Tasks

- [x] Launch [build](https://ci.wazuh.info/job/Test_stack_tier) without checkfiles.
     - [72](https://ci.wazuh.info/job/Test_stack_tier/72/)
- [x] Validate each system.
- [x] Validate that include traces of each test in plain text

## Checks
System         | Install | Upgrade | Remove | Purge | Service | Systemd | Working (Curl) | Dashboard/Indexer VERSION file |
:--            | :--:    | :--:    | :--:   | :--:  | :--:    | :--:    | :--:           | :--:                           |
CentOS 7| :green_circle:   | :green_circle:      | :green_circle:     | :white_circle:    | :green_circle:      | :green_circle:      | :green_circle:             | :green_circle:                             |
CentOS 8       | :green_circle:   | :green_circle:      | :green_circle:     | :white_circle:    | :green_circle:      | :green_circle:      | :green_circle:             | :green_circle:                             |
Red Hat 7      | :green_circle:   | :green_circle:      | :green_circle:     | :white_circle:    | :green_circle:      | :green_circle:      | :green_circle:             | :green_circle:                             |
Red Hat 8      | :green_circle:   | :green_circle:      | :green_circle:     | :white_circle:    | :green_circle:      | :green_circle:      | :green_circle:             | :green_circle:                             |
Red Hat 9      | :green_circle:   | :green_circle:      | :green_circle:     | :white_circle:    | :green_circle:      | :green_circle:      | :green_circle:             | :green_circle:                             |
Amazon Linux 2 |:green_circle:   | :green_circle:      | :green_circle:     | :white_circle:    | :green_circle:      | :green_circle:      | :green_circle:             | :green_circle:                             |
Ubuntu 16.04   | :green_circle:   | :green_circle:      | :green_circle:     | :green_circle:    | :green_circle:      | :green_circle:      | :green_circle:             | :green_circle:                             |
Ubuntu 18.04   | :green_circle:   | :green_circle:      | :green_circle:     | :green_circle:    | :green_circle:      | :green_circle:      | :green_circle:             | :green_circle:                             |
Ubuntu 20.04   | :green_circle:   | :green_circle:      | :green_circle:     | :green_circle:    | :green_circle:      | :green_circle:      | :green_circle:             | :green_circle:                             |
Ubuntu 22.04   | :green_circle:   | :green_circle:      | :green_circle:     | :green_circle:    | :green_circle:      | :green_circle:      | :green_circle:             | :green_circle:                             |

---

> :black_circle: Not Started: The tasks didn't start yet.
> :yellow_circle: In progress: The team is already working on it.
> :green_circle: Ready to review: The auditors must validate the results.
> :white_circle: Skipped: The task has been deemed not necessary for this stage.
> :brown_circle:  Partially skipped:  Some parts of the task are skipped._
> :purple_circle: Completed: Task finished. Nothing to do here.
> :red_circle: Completed with failures: Some issues were raised here.

---

## Conclusion 

It works successfully without errors.

---

## Auditor's validation

In order to close and proceed with the release or the next candidate version, the following auditors must give the green light to this RC.

- [x] @davidjiglesias / @mauromalara 

---

**Comment by damarisg** [comment]
## Dashboard

<details>
<summary>Ubuntu Jammy 🟢 </summary>

### Results 1 
> 20:20:50  ================== test session starts =====================
> 20:20:50  platform linux -- Python 3.10.12, pytest-7.4.0, pluggy-1.2.0 -- /usr/bin/python3
> 20:20:50  cachedir: .pytest_cache
> 20:20:50  rootdir: /stack_test
> 20:20:50  collecting ... collected 13 items
> 20:20:50  
> 20:20:50  pytest_dashboard.py::test_upgrade SKIPPED (Skipping upgrage it will ...) [  7%]
> 20:20:50  pytest_dashboard.py::test_check_process_dashboards PASSED                [ 15%]
> 20:20:50  pytest_dashboard.py::test_check_dashboards_log_errors SKIPPED (The L...) [ 23%]
> 20:20:50  pytest_dashboard.py::test_check_dashboards_keystore PASSED               [ 30%]
> 20:20:50  pytest_dashboard.py::test_check_dashboards_api PASSED                    [ 38%]
> 20:20:50  pytest_dashboard.py::test_working_dashboard PASSED                       [ 46%]
> 20:20:50  pytest_dashboard.py::test_check_version_file PASSED                      [ 53%]
> 20:20:50  pytest_dashboard.py::test_sysv[start] PASSED                             [ 61%]
> 20:20:50  pytest_dashboard.py::test_sysv[stop] PASSED                              [ 69%]
> 20:20:50  pytest_dashboard.py::test_systemd[start] PASSED                          [ 76%]
> 20:20:50  pytest_dashboard.py::test_systemd[stop] PASSED                           [ 84%]
> 20:20:50  pytest_dashboard.py::test_remove PASSED                                  [ 92%]
> 20:20:50  pytest_dashboard.py::test_purge PASSED                                   [100%]
> 20:20:50  
> 20:20:50  =========== 11 passed, 2 skipped in 162.62s (0:02:42) ===================

### Results 2 

> 20:27:10  ==================== test session starts ==============================
> 20:27:10  platform linux -- Python 3.10.12, pytest-7.4.0, pluggy-1.2.0 -- /usr/bin/python3
> 20:27:10  cachedir: .pytest_cache
> 20:27:10  rootdir: /stack_test
> 20:27:10  collecting ... collected 13 items
> 20:27:10  
> 20:27:10  pytest_dashboard.py::test_upgrade PASSED                                 [  7%]
> 20:27:10  pytest_dashboard.py::test_check_process_dashboards PASSED                [ 15%]
> 20:27:10  pytest_dashboard.py::test_check_dashboards_log_errors SKIPPED (The L...) [ 23%]
> 20:27:10  pytest_dashboard.py::test_check_dashboards_keystore PASSED               [ 30%]
> 20:27:10  pytest_dashboard.py::test_check_dashboards_api SKIPPED (Skipping tes...) [ 38%]
> 20:27:10  pytest_dashboard.py::test_working_dashboard SKIPPED (Skipping test h...) [ 46%]
> 20:27:10  pytest_dashboard.py::test_check_version_file PASSED                      [ 53%]
> 20:27:10  pytest_dashboard.py::test_sysv[start] PASSED                             [ 61%]
> 20:27:10  pytest_dashboard.py::test_sysv[stop] PASSED                              [ 69%]
> 20:27:10  pytest_dashboard.py::test_systemd[start] PASSED                          [ 76%]
> 20:27:10  pytest_dashboard.py::test_systemd[stop] PASSED                           [ 84%]
> 20:27:10  pytest_dashboard.py::test_remove PASSED                                  [ 92%]
> 20:27:10  pytest_dashboard.py::test_purge PASSED                                   [100%]
> 20:27:10  
> 20:27:10  ============= 10 passed, 3 skipped in 94.06s (0:01:34) ===================

</details>

<details>
<summary>Ubuntu Bionic 🟢</summary>

### Results 1 

> 20:18:08  ============== test session starts ==============================
> 20:18:08  platform linux -- Python 3.6.9, pytest-5.3.5, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python3
> 20:18:08  cachedir: .pytest_cache
> 20:18:08  metadata: {'Python': '3.6.9', 'Platform': 'Linux-4.15.0-1060-aws-x86_64-with-Ubuntu-18.04-bionic', 'Packages': {'pytest': '5.3.5', 'py': '1.8.1', 'pluggy': '0.13.1'}, 'Plugins': {'metadata': '1.8.0', 'html': '2.0.1'}}
> 20:18:08  rootdir: /stack_test
> 20:18:08  plugins: metadata-1.8.0, html-2.0.1
> 20:18:08  collecting ... collected 13 items
> 20:18:08  
> 20:18:08  pytest_dashboard.py::test_upgrade SKIPPED                                [  7%]
> 20:18:08  pytest_dashboard.py::test_check_process_dashboards PASSED                [ 15%]
> 20:18:08  pytest_dashboard.py::test_check_dashboards_log_errors SKIPPED            [ 23%]
> 20:18:08  pytest_dashboard.py::test_check_dashboards_keystore PASSED               [ 30%]
> 20:18:08  pytest_dashboard.py::test_check_dashboards_api PASSED                    [ 38%]
> 20:18:08  pytest_dashboard.py::test_working_dashboard PASSED                       [ 46%]
> 20:18:08  pytest_dashboard.py::test_check_version_file PASSED                      [ 53%]
> 20:18:08  pytest_dashboard.py::test_sysv[start] PASSED                             [ 61%]
> 20:18:08  pytest_dashboard.py::test_sysv[stop] PASSED                              [ 69%]
> 20:18:08  pytest_dashboard.py::test_systemd[start] PASSED                          [ 76%]
> 20:18:08  pytest_dashboard.py::test_systemd[stop] PASSED                           [ 84%]
> 20:18:08  pytest_dashboard.py::test_remove PASSED                                  [ 92%]
> 20:18:08  pytest_dashboard.py::test_purge PASSED                                   [100%]
> 20:18:08  
> 20:18:08  ============ 11 passed, 2 skipped in 20.33s ========================

### Results 2 

> 20:24:22  =================== test session starts ==============================
> 20:24:22  platform linux -- Python 3.6.9, pytest-5.3.5, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python3
> 20:24:22  cachedir: .pytest_cache
> 20:24:22  metadata: {'Python': '3.6.9', 'Platform': 'Linux-4.15.0-1060-aws-x86_64-with-Ubuntu-18.04-bionic', 'Packages': {'pytest': '5.3.5', 'py': '1.8.1', 'pluggy': '0.13.1'}, 'Plugins': {'metadata': '1.8.0', 'html': '2.0.1'}}
> 20:24:22  rootdir: /stack_test
> 20:24:22  plugins: metadata-1.8.0, html-2.0.1
> 20:24:22  collecting ... collected 13 items
> 20:24:22  
> 20:24:22  pytest_dashboard.py::test_upgrade PASSED                                 [  7%]
> 20:24:22  pytest_dashboard.py::test_check_process_dashboards PASSED                [ 15%]
> 20:24:22  pytest_dashboard.py::test_check_dashboards_log_errors SKIPPED            [ 23%]
> 20:24:22  pytest_dashboard.py::test_check_dashboards_keystore PASSED               [ 30%]
> 20:24:22  pytest_dashboard.py::test_check_dashboards_api SKIPPED                   [ 38%]
> 20:24:22  pytest_dashboard.py::test_working_dashboard SKIPPED                      [ 46%]
> 20:24:22  pytest_dashboard.py::test_check_version_file PASSED                      [ 53%]
> 20:24:22  pytest_dashboard.py::test_sysv[start] PASSED                             [ 61%]
> 20:24:22  pytest_dashboard.py::test_sysv[stop] PASSED                              [ 69%]
> 20:24:22  pytest_dashboard.py::test_systemd[start] PASSED                          [ 76%]
> 20:24:22  pytest_dashboard.py::test_systemd[stop] PASSED                           [ 84%]
> 20:24:22  pytest_dashboard.py::test_remove PASSED                                  [ 92%]
> 20:24:22  pytest_dashboard.py::test_purge PASSED                                   [100%]
> 20:24:22  
> 20:24:22  ============= 10 passed, 3 skipped in 60.42s (0:01:00) ===================
> 

</details>

<details>
<summary></summary>

</details>


<details>
<summary></summary>

</details>


<details>
<summary></summary>

</details>

**Comment by damarisg** [comment]
## Indexer

<details>
<summary>Ubuntu Jammy 🟢 </summary>

### Results 1 
> 20:21:45  ====================== test session starts ==========================
> 20:21:45  platform linux -- Python 3.10.12, pytest-7.4.0, pluggy-1.2.0 -- /usr/bin/python3
> 20:21:45  cachedir: .pytest_cache
> 20:21:45  rootdir: /stack_test
> 20:21:45  collecting ... collected 19 items
> 20:21:45  
> 20:21:45  pytest_indexer.py::test_upgrade SKIPPED (Skipping upgrage it will
> 20:21:45  execute with previuos version)                                           [  5%]
> 20:21:45  pytest_indexer.py::test_check_process_indexer PASSED                     [ 10%]
> 20:21:45  pytest_indexer.py::test_check_indexer_log_errors PASSED                  [ 15%]
> 20:21:45  pytest_indexer.py::test_index_status[.opendistro_security] PASSED        [ 21%]
> 20:21:45  pytest_indexer.py::test_check_indexer_internal_users[admin] PASSED       [ 26%]
> 20:21:45  pytest_indexer.py::test_check_indexer_internal_users[kibanaserver] PASSED [ 31%]
> 20:21:45  pytest_indexer.py::test_check_indexer_internal_users[kibanaro] PASSED    [ 36%]
> 20:21:45  pytest_indexer.py::test_check_indexer_internal_users[logstash] PASSED    [ 42%]
> 20:21:45  pytest_indexer.py::test_check_indexer_internal_users[readall] PASSED     [ 47%]
> 20:21:45  pytest_indexer.py::test_check_indexer_internal_users[snapshotrestore] PASSED [ 52%]
> 20:21:45  pytest_indexer.py::test_indexer_cluster_health PASSED                    [ 57%]
> 20:21:45  pytest_indexer.py::test_check_working_indexer PASSED                     [ 63%]
> 20:21:45  pytest_indexer.py::test_check_version_file PASSED                        [ 68%]
> 20:21:45  pytest_indexer.py::test_sysv[start] PASSED                               [ 73%]
> 20:21:45  pytest_indexer.py::test_sysv[stop] PASSED                                [ 78%]
> 20:21:45  pytest_indexer.py::test_systemd[start] PASSED                            [ 84%]
> 20:21:45  pytest_indexer.py::test_systemd[stop] PASSED                             [ 89%]
> 20:21:45  pytest_indexer.py::test_remove PASSED                                    [ 94%]
> 20:21:45  pytest_indexer.py::test_purge PASSED                                     [100%]
> 20:21:45  
> 20:21:45  ================= 18 passed, 1 skipped in 47.71s ===================


### Results 2 

> 20:29:39  ===================== test session starts ===========================
> 20:29:39  platform linux -- Python 3.10.12, pytest-7.4.0, pluggy-1.2.0 -- /usr/bin/python3
> 20:29:39  cachedir: .pytest_cache
> 20:29:39  rootdir: /stack_test
> 20:29:39  collecting ... collected 19 items
> 20:29:39  
> 20:29:39  pytest_indexer.py::test_upgrade PASSED                                   [  5%]
> 20:29:39  pytest_indexer.py::test_check_process_indexer PASSED                     [ 10%]
> 20:29:39  pytest_indexer.py::test_check_indexer_log_errors PASSED                  [ 15%]
> 20:29:39  pytest_indexer.py::test_index_status[.opendistro_security] SKIPPED       [ 21%]
> 20:29:39  pytest_indexer.py::test_check_indexer_internal_users[admin] PASSED       [ 26%]
> 20:29:39  pytest_indexer.py::test_check_indexer_internal_users[kibanaserver] PASSED [ 31%]
> 20:29:39  pytest_indexer.py::test_check_indexer_internal_users[kibanaro] PASSED    [ 36%]
> 20:29:39  pytest_indexer.py::test_check_indexer_internal_users[logstash] PASSED    [ 42%]
> 20:29:39  pytest_indexer.py::test_check_indexer_internal_users[readall] PASSED     [ 47%]
> 20:29:39  pytest_indexer.py::test_check_indexer_internal_users[snapshotrestore] PASSED [ 52%]
> 20:29:39  pytest_indexer.py::test_indexer_cluster_health SKIPPED (Skipping test
> 20:29:39  has already been tested)                                                 [ 57%]
> 20:29:39  pytest_indexer.py::test_check_working_indexer SKIPPED (Skipping test has
> 20:29:39  already been tested)                                                     [ 63%]
> 20:29:39  pytest_indexer.py::test_check_version_file PASSED                        [ 68%]
> 20:29:39  pytest_indexer.py::test_sysv[start] PASSED                               [ 73%]
> 20:29:39  pytest_indexer.py::test_sysv[stop] PASSED                                [ 78%]
> 20:29:39  pytest_indexer.py::test_systemd[start] PASSED                            [ 84%]
> 20:29:39  pytest_indexer.py::test_systemd[stop] PASSED                             [ 89%]
> 20:29:39  pytest_indexer.py::test_remove PASSED                                    [ 94%]
> 20:29:39  pytest_indexer.py::test_purge PASSED                                     [100%]
> 20:29:39  
> 20:29:39  ============== 16 passed, 3 skipped in 142.60s (0:02:22) ===================

</details>

<details>
<summary>Ubuntu Bionic 🟢</summary>

### Results 1 

> 
> 20:19:06  ==================== test session starts ==============================
> 20:19:06  platform linux -- Python 3.6.9, pytest-5.3.5, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python3
> 20:19:06  cachedir: .pytest_cache
> 20:19:06  metadata: {'Python': '3.6.9', 'Platform': 'Linux-4.15.0-1060-aws-x86_64-with-Ubuntu-18.04-bionic', 'Packages': {'pytest': '5.3.5', 'py': '1.8.1', 'pluggy': '0.13.1'}, 'Plugins': {'metadata': '1.8.0', 'html': '2.0.1'}}
> 20:19:06  rootdir: /stack_test
> 20:19:06  plugins: metadata-1.8.0, html-2.0.1
> 20:19:06  collecting ... collected 19 items
> 20:19:06  
> 20:19:06  pytest_indexer.py::test_upgrade SKIPPED                                  [  5%]
> 20:19:06  pytest_indexer.py::test_check_process_indexer PASSED                     [ 10%]
> 20:19:06  pytest_indexer.py::test_check_indexer_log_errors PASSED                  [ 15%]
> 20:19:06  pytest_indexer.py::test_index_status[.opendistro_security] PASSED        [ 21%]
> 20:19:06  pytest_indexer.py::test_check_indexer_internal_users[admin] PASSED       [ 26%]
> 20:19:06  pytest_indexer.py::test_check_indexer_internal_users[kibanaserver] PASSED [ 31%]
> 20:19:06  pytest_indexer.py::test_check_indexer_internal_users[kibanaro] PASSED    [ 36%]
> 20:19:06  pytest_indexer.py::test_check_indexer_internal_users[logstash] PASSED    [ 42%]
> 20:19:06  pytest_indexer.py::test_check_indexer_internal_users[readall] PASSED     [ 47%]
> 20:19:06  pytest_indexer.py::test_check_indexer_internal_users[snapshotrestore] PASSED [ 52%]
> 20:19:06  pytest_indexer.py::test_indexer_cluster_health PASSED                    [ 57%]
> 20:19:06  pytest_indexer.py::test_check_working_indexer PASSED                     [ 63%]
> 20:19:06  pytest_indexer.py::test_check_version_file PASSED                        [ 68%]
> 20:19:06  pytest_indexer.py::test_sysv[start] PASSED                               [ 73%]
> 20:19:06  pytest_indexer.py::test_sysv[stop] PASSED                                [ 78%]
> 20:19:06  pytest_indexer.py::test_systemd[start] PASSED                            [ 84%]
> 20:19:06  pytest_indexer.py::test_systemd[stop] PASSED                             [ 89%]
> 20:19:06  pytest_indexer.py::test_remove PASSED                                    [ 94%]
> 20:19:06  pytest_indexer.py::test_purge PASSED                                     [100%]
> 20:19:06  
> 20:19:06  ============== 18 passed, 1 skipped in 37.54s ========================

### Results 2 

> 20:26:56  =================== test session starts ==============================
> 20:26:56  platform linux -- Python 3.6.9, pytest-5.3.5, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python3
> 20:26:56  cachedir: .pytest_cache
> 20:26:56  metadata: {'Python': '3.6.9', 'Platform': 'Linux-4.15.0-1060-aws-x86_64-with-Ubuntu-18.04-bionic', 'Packages': {'pytest': '5.3.5', 'py': '1.8.1', 'pluggy': '0.13.1'}, 'Plugins': {'metadata': '1.8.0', 'html': '2.0.1'}}
> 20:26:56  rootdir: /stack_test
> 20:26:56  plugins: metadata-1.8.0, html-2.0.1
> 20:26:56  collecting ... collected 19 items
> 20:26:56  
> 20:26:56  pytest_indexer.py::test_upgrade PASSED                                   [  5%]
> 20:26:56  pytest_indexer.py::test_check_process_indexer PASSED                     [ 10%]
> 20:26:56  pytest_indexer.py::test_check_indexer_log_errors PASSED                  [ 15%]
> 20:26:56  pytest_indexer.py::test_index_status[.opendistro_security] SKIPPED       [ 21%]
> 20:26:56  pytest_indexer.py::test_check_indexer_internal_users[admin] PASSED       [ 26%]
> 20:26:56  pytest_indexer.py::test_check_indexer_internal_users[kibanaserver] PASSED [ 31%]
> 20:26:56  pytest_indexer.py::test_check_indexer_internal_users[kibanaro] PASSED    [ 36%]
> 20:26:56  pytest_indexer.py::test_check_indexer_internal_users[logstash] PASSED    [ 42%]
> 20:26:56  pytest_indexer.py::test_check_indexer_internal_users[readall] PASSED     [ 47%]
> 20:26:56  pytest_indexer.py::test_check_indexer_internal_users[snapshotrestore] PASSED [ 52%]
> 20:26:56  pytest_indexer.py::test_indexer_cluster_health SKIPPED                   [ 57%]
> 20:26:56  pytest_indexer.py::test_check_working_indexer SKIPPED                    [ 63%]
> 20:26:56  pytest_indexer.py::test_check_version_file PASSED                        [ 68%]
> 20:26:56  pytest_indexer.py::test_sysv[start] PASSED                               [ 73%]
> 20:26:56  pytest_indexer.py::test_sysv[stop] PASSED                                [ 78%]
> 20:26:56  pytest_indexer.py::test_systemd[start] PASSED                            [ 84%]
> 20:26:56  pytest_indexer.py::test_systemd[stop] PASSED                             [ 89%]
> 20:26:56  pytest_indexer.py::test_remove PASSED                                    [ 94%]
> 20:26:56  pytest_indexer.py::test_purge PASSED                                     [100%]
> 20:26:56  
> 20:26:56 ============ 16 passed, 3 skipped in 134.82s (0:02:14) ===================
</details>

**Comment by mauromalara** [comment]
LGTM!
