### ISSUE TITLE
Multigroups inconsistency 

### ISSUE THREAD

**Issue by Cerv1** [wazuh/wazuh#1863]
## Steps to reproduce

Environment: 2 agents connected to one manager.

_Agent 1_ is assigned to `group1` and `group2`.
_Agent 2_ is assigned to `group1` and `group2`.

1. Stop the _Agent 1_. 
2. Delete the ` /var/ossec/etc/shared/group1` folder. The _Agent 2_ should delete `group1` from `agent.conf`.
3. Re-register the _Agent 1_ with the same name to the same manager. It should belongs only to the default group.
4. Create the `group1` again in the manager. 

After this last step, the _Agent 2_ is assigned to the `group1` group automatically.

## Current behaviour
-  If we create a group named `test` and add 2 agents to this group the **MD5** of `var/multigroups` changes for both.
- If we delete the `test` group both agents restart and lose this group of their configuration. The **MD5** of `var/multigroups` and the `.metadata` file **does not change**.
- If we create again the `test` group both agents are added automatically. The **MD5** of `var/multigroups` and the `.metadata` file **does not change**.
- If we retry to add them because we've deleted the group (theoretically) we got the following message: `Agent 'XXX' already belongs to group 'test'.` However, the group appears **empty** when we list with `agent_groups -l` even though both agents have the configuration of that group.

**Comment by Cerv1** [comment]
## Solution overview
To prevent the previous scenario we're going to create `var/groups`. This folder will store all the information related to the groups and the content of `etc/shared` will be a symbolic link to this new folder. Now, If the user accidentally deletes a group from `etc/shared` it won't delete the database information related to this groups. We've decided to make it this way because we think the user can modify the content of the `etc` folder.

## Tasks
- [ ] Create the new folder where the information of the groups will be stored (`var/groups`) in the installation script.
- [ ] Migrate the information of the groups from `etc/shared` to `var/groups` in the installation script.
- [ ] Move all the group information to the new folder and create a symbolic link in the previous one.
- [ ] Error management in `ossec-remoted` and `wazuh-api` when retrieving information from `etc/shared`.
- [ ] Modify `python` scripts to write the information in the new folder when the groups are modified, created, deleted... etc.

**Comment by Cerv1** [comment]
## Inconsistency in ossec-remoted when deleting agents
If  `ossec-authd` is running and we delete an agent with `manage_agents -r ID`, sometimes the file `queue/agent-groups/ID` is recreated by `ossec-remoted`.

Example:

```
# manage_agents -l
Available agents: 
   ID: 007, Name: CNTS, IP: 10.0.0.41
   ID: 035, Name: BNT, IP: 10.0.0.40

# agent_control -l
Wazuh agent_control. List of available agents:
   ID: 000, Name: workstation (server), IP: 127.0.0.1, Active/Local
   ID: 007, Name: CNTS, IP: 10.0.0.41, Active
   ID: 035, Name: BNT, IP: 10.0.0.40, Active


# cat /var/ossec/etc/client.keys 
007 CNTS 10.0.0.41 975593c5e4554e18dd46664c1ea8231c0107806b46d0806df2ff0ff513cbc63b
035 BNT 10.0.0.40 33121f69318950c136e98d345a9dc4e470aaaadc09d3ac7cdf0d724e4eedb2aa
# ls -l /var/ossec/queue/agent-groups/
total 68
-rw-rw---- 1 ossecr ossec  8 dic  7 09:26 001
-rw-rw---- 1 ossec  ossec  0 dic  5 16:28 004
-rw-rw---- 1 ossecr ossec  8 dic  7 09:28 007
-rw-rw---- 1 ossecr ossec  8 dic  7 10:43 010
-rw-rw---- 1 ossecr ossec  8 dic  7 12:03 013
-rw-rw---- 1 ossecr ossec  8 dic  7 12:12 015
-rw-rw---- 1 ossecr ossec 14 dic  7 12:17 018
-rw-rw---- 1 ossecr ossec 14 dic  7 12:21 020
-rw-rw---- 1 ossecr ossec  8 dic  7 12:22 021
-rw-rw---- 1 ossecr ossec  8 dic  7 12:27 022
-rw-rw---- 1 ossecr ossec 14 dic  7 12:48 023
-rw-rw---- 1 ossecr ossec 14 dic  7 12:52 024
-rw-rw---- 1 ossecr ossec  8 dic  7 13:02 026
-rw-rw---- 1 ossecr ossec 20 dic  7 13:27 029
-rw-rw---- 1 ossecr ossec  8 dic  7 15:02 030
-rw-rw---- 1 ossecr ossec  8 dic  7 15:41 033
-rw-rw---- 1 ossecr ossec  8 dic  7 15:47 034
-rw-rw---- 1 ossecr ossec  8 dic  7 16:13 035

**Comment by chemamartinez** [comment]
Done at #1985.
Documentation done at [#714](https://github.com/wazuh/wazuh-documentation/pull/714).
