### ISSUE TITLE
Release 4.5.2 - Post release

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#18641]
The following issue aims to perform required post-release checks to ensure a well-published release procedure.

## Main information
|||
| :--                             | :--                                                |
| **Version**                     | 4.5.2                                      |
| **Tag**                         | https://github.com/wazuh/wazuh/tree/v4.5.2 |
| **Release issue**               |  #18617                                     |
| **Previous post release issue** | https://github.com/wazuh/wazuh/issues/18491 |

---

### Release notes and tags
- [x] wazuh/wazuh
- [x] wazuh/wazuh-packages
- [x] wazuh/wazuh-kibana-app
- [x] wazuh/wazuh-splunk
- [x] wazuh/wazuh-qa
- [x] wazuh/wazuh-ansible
- [x] wazuh/wazuh-docker
- [x] wazuh/wazuh-kubernetes
- [x] wazuh/wazuh-puppet

### Publish Release
- [x] Launch pipeline: https://ci.wazuh.info/job/Publish_release/362/
  - [x] Check if `procedure_check_release` was launched correctly
  - [x] Relaunch `publish_unnattended` with last_tag changed to the previous version (`4.5.1`) to skip the validation due to parallel releases: https://ci.wazuh.info/job/publish_unattended/150/
  - [x] Check if the script of Wazuh Installation Assistant makes reference to the last version (`4.5.2`) internally
- [x] Relaunched for puppet only due to failure in `publish_unattended` https://ci.wazuh.info/job/Publish_release/366/ (replayed and script changed)

### Repository
- [x] Live installation test @mauromalara 
  - [x] AMD64: https://ci.wazuh.info/job/Test_install_tier/691/
    - [x] Replayed OracleLinux 8 https://ci.wazuh.info/job/Test_install/139905/ (unexpectedly stopped)
  - [x] ARM64 (macOS only): https://ci.wazuh.info/job/Test_install_tier/692/
- [x] Live upgrade test @pro-akim @damarisg 
  - [x] https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/2109/
- [x] WPK versions check @mauromalara
- [x] WPK upgrade test
  - [x] Linux @mauromalara
  - [x] MacOS Intel @BelenValdivia 
  - [x] MacOS Apple Silicon @BelenValdivia 
  - [x] Windows @pro-akim
- [x] Post-release check (files)
- [x] AMI published
- [x] Cache invalidated
- [x] Update Jenkins pipelines configurations according to new version
  - [x] https://ci.wazuh.info/job/Procedure_docker_testing_image_generation/
  - [x] https://ci.wazuh.info/job/Test_upgrade_tier
- [x] Build release containers @jnasselle https://ci.wazuh.info/job/Procedure_docker_testing_image_generation/436/
- [x] Build and push Docker Hub images
  - [x] https://ci.wazuh.info/job/procedure_push_docker_images/81/
- [x] Build and release debug packages
- [x] Publish puppet forge module
- [x] Update upgrade template in wazuh-jenkins repository with the last version
### Documentation
- [x] Documentation updated
- [x] Documentation published
- [x] Cache invalidated

### Marketing
- [x] Community announcement (Need the rest of the checks ready)

---

## Validation

The following auditors must give the green light to this release.

- [ ] @davidjiglesias 
- [ ] @teddytpc1

---

**Comment by mauromalara** [comment]
## WPK upgrade: Linux ⚫ @mauromalara

**Comment by mauromalara** [comment]
## WPK upgrade: macOS Appel Silicon ⚫ @BelenValdivia

**Comment by pro-akim** [comment]
## WPK upgrade test - Windows WIP 
### From Wazuh-Agent v4.5.1- WIP

####  UPGRADE OK: WIP

- [ ] Message Upgrade finished successfully. is shown in upgrade.log file.
- [ ]  Wazuh service is started and the agent is connected to the manager.
- [ ]  The version shown in the control panel is 4.5.1
- [ ]  The new SCA policy is added and executed

**Upgrade report**
[Download 4.5.1to4.5.2 Windows11 reports.zip]()



### From Wazuh-Agent v4.5.2 - WIP



####  UPGRADE OK: WIP

- [ ] Message Upgrade finished successfully. is shown in upgrade.log file.
- [ ]  Wazuh service is started and the agent is connected to the manager.
- [ ]  The version shown in the control panel is 4.5.1
- [ ]  The new SCA policy is added and executed

**Upgrade report**
[Download 4.5.2to4.5.2 Windows11 reports.zip]()


## Note
No error messages were found during the update process.

**Comment by rauldpm** [comment]
LGTM but we should add a check to test the Wazuh installation assistant

**Comment by davidjiglesias** [comment]
LGTM!
