### ISSUE TITLE
Support new stage Alpha 1 for 4.6.0 in wazuh repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#18697]
## Description

This issue attempts to support a new stage Alpha 1 for 4.6.0 in the wazuh repository.

## Tasks

- [x] Ensure changelog is updated for 4.6.0 (if applicable).
- [x] Create tag v4.6.0-alpha1 from branch 4.6.0 on wazuh repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh/releases/tag/v4.6.0-alpha1.

**Comment by Dwordcito** [comment]
https://github.com/wazuh/wazuh/releases/tag/v4.6.0-alpha1
