### ISSUE TITLE
`wazuh` and `wazuh-wui` user passwords are reset after upgrading the Wazuh manager to 4.6.0

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#18771]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0 | API | Manager | Packages | -- |

## Description

- During the bump of Wazuh indexer and Wazuh dashboard from 2.6.0 to 2.8.0, unwanted behavior was found regarding `wazuh` and `wazuh-wui` users.
- Apparently, when upgrading the Wazuh manager, the passwords of these users are restored by default, this is a security risk that must be fixed.

<details><summary>Output</summary>

```
root@debian10:/home/vagrant# TOKEN=$(curl -u wazuh-wui:1EFtqmyAHTkGfFZf.iDa2YuO8cCPEB6E -k -X POST "https://localhost:55000/security/user/authenticate?raw=true")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   404  100   404    0     0   1458      0 --:--:-- --:--:-- --:--:--  1458
root@debian10:/home/vagrant# echo $TOKEN
eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjkzODQ4NjY3LCJleHAiOjE2OTM4NDk1NjcsInN1YiI6IndhenVoLXd1aSIsInJ1bl9hcyI6ZmFsc2UsInJiYWNfcm9sZXMiOlsxXSwicmJhY19tb2RlIjoid2hpdGUifQ.ABY4AcuI0rTRhli28nlqFWUinoVJDzW02vt9tYemtgdpk7QBBFqkHZ922W1fWkuQNSSQ9JibB4YajWNnrkUU26fXAWReAlvVg95X_EbWKYmA-mf1ydDRPOQRZ4QBkiNgajbxRUypnE-1Tr-tsKUkX0udTsqOGcDxNdFlgBkKei9HzWkq
root@debian10:/home/vagrant# curl -k -u admin:Nyng?mdLBW?KpthB1R8y2xvAbS?0dYJA https://localhost:9200/_cat/nodes?v
ip        heap.percent ram.percent cpu load_1m load_5m load_15m node.role node.roles                                        cluster_manager name
127.0.0.1           61          93   4    0.17    0.29     0.14 dimr      cluster_manager,data,ingest,remote_cluster_client *               node-1
root@debian10:/home/vagrant# wget https://packages-dev.wazuh.com/staging/apt/pool/main/w/wazuh-manager/wazuh-manager_4.6.0-wp.2392_amd64.deb
--2023-09-04 17:32:11--  https://packages-dev.wazuh.com/staging/apt/pool/main/w/wazuh-manager/wazuh-manager_4.6.0-wp.2392_amd64.deb
Resolving packages-dev.wazuh.com (packages-dev.wazuh.com)... 143.204.231.78, 143.204.231.67, 143.204.231.122, ...
Connecting to packages-dev.wazuh.com (packages-dev.wazuh.com)|143.204.231.78|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 171353850 (163M) [binary/octet-stream]
Saving to: 'wazuh-manager_4.6.0-wp.2392_amd64.deb'

wazuh-manager_4.6.0-wp.2392_amd64.deb                100%[=====================================================================================================================>] 163.42M  72.5MB/s    in 2.3s    

2023-09-04 17:32:19 (72.5 MB/s) - 'wazuh-manager_4.6.0-wp.2392_amd64.deb' saved [171353850/171353850]

root@debian10:/home/vagrant# yum install ./wazuh-manager_4.6.0-wp.2392_amd64.deb 
bash: yum: command not found
root@debian10:/home/vagrant# apt install ./wazuh-manager_4.6.0-wp.2392_amd64.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'wazuh-manager' instead of './wazuh-manager_4.6.0-wp.2392_amd64.deb'
Suggested packages:
  expect
The following packages will be upgraded:
  wazuh-manager
1 upgraded, 0 newly installed, 0 to remove and 55 not upgraded.
Need to get 0 B/171 MB of archives.
After this operation, 1,731 kB of additional disk space will be used.
Get:1 /home/vagrant/wazuh-manager_4.6.0-wp.2392_amd64.deb wazuh-manager amd64 4.6.0-wp.2392 [171 MB]
Reading changelogs... Done        
(Reading database ... 183385 files and directories currently installed.)
Preparing to unpack .../wazuh-manager_4.6.0-wp.2392_amd64.deb ...
Unpacking wazuh-manager (4.6.0-wp.2392) over (4.5.1-1) ...
Setting up wazuh-manager (4.6.0-wp.2392) ...
Processing triggers for systemd (241-7~deb10u8) ...
root@debian10:/home/vagrant# curl -s https://packages.wazuh.com/4.x/filebeat/wazuh-filebeat-0.2.tar.gz | sudo tar -xvz -C /usr/share/filebeat/module
wazuh/alerts/
wazuh/alerts/config/
wazuh/alerts/config/alerts.yml
wazuh/alerts/manifest.yml
wazuh/alerts/ingest/
wazuh/alerts/ingest/pipeline.json
wazuh/archives/
wazuh/archives/config/
wazuh/archives/config/archives.yml
wazuh/archives/manifest.yml
wazuh/archives/ingest/
wazuh/archives/ingest/pipeline.json
wazuh/module.yml
root@debian10:/home/vagrant# curl -so /etc/filebeat/wazuh-template.json https://raw.githubusercontent.com/wazuh/wazuh/4.6.0/extensions/elasticsearch/7.x/wazuh-template.j
root@debian10:/home/vagrant# chmod go+r /etc/filebeat/wazuh-template.json
root@debian10:/home/vagrant# systemctl daemon-reload
root@debian10:/home/vagrant# systemctl enable filebeat
Synchronizing state of filebeat.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable filebeat
root@debian10:/home/vagrant# systemctl start filebeat
root@debian10:/home/vagrant# TOKEN=$(curl -u wazuh-wui:1EFtqmyAHTkGfFZf.iDa2YuO8cCPEB6E -k -X POST "https://localhost:55000/security/user/authenticate?raw=true")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    59  100    59    0     0    165      0 --:--:-- --:--:-- --:--:--   165
root@debian10:/home/vagrant# echo $TOKEN
{"title": "Unauthorized", "detail": "Invalid credentials"}
root@debian10:/home/vagrant# TOKEN=$(curl -u wazuh-wui:wazuh-wui -k -X POST "https://localhost:55000/security/user/authenticate?raw=true")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   404  100   404    0     0   1103      0 --:--:-- --:--:-- --:--:--  1103
root@debian10:/home/vagrant# echo $TOKEN
eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjkzODQ4OTU1LCJleHAiOjE2OTM4NDk4NTUsInN1YiI6IndhenVoLXd1aSIsInJ1bl9hcyI6ZmFsc2UsInJiYWNfcm9sZXMiOlsxXSwicmJhY19tb2RlIjoid2hpdGUifQ.AGvgPKVPqDIj5BgK0GAt-LVBJk5nUzK8GmBDtDjica47LlFBddhSjWrlJTWewbojIxNwR7kAENQjy-V8ONqL9mpjAU_ynqxlqz-GpV-oyMgEAy542-rzb9ShgTAVHdPoxAxfvMu4QtL7qnT_tbdjkW0nZjqagArpFD4gHJucfU42DPrd
```

</details>

## Tasks

- [x] The installation of a new version of the Wazuh manager, maintains the passwords of the `wazuh` and `wazuh-wui` users

## Validation

- [x] The passwords of the `wazuh` and `wazuh-wui` users do not change after the update

**Comment by EduLeon12** [comment]
## Issue Update 

After following the same update process, the bug was confirmed. The process followed was:

- Install a manager, indexer and dashboard for version 4.5.1:

```
root@vagrant:/# bash wazuh-install.sh --generate-config-files
04/09/2023 17:41:04 INFO: Starting Wazuh installation assistant. Wazuh version: 4.5.1
04/09/2023 17:41:04 INFO: Verbose logging redirected to /var/log/wazuh-install.log
04/09/2023 17:41:13 INFO: --- Configuration files ---
04/09/2023 17:41:13 INFO: Generating configuration files.
04/09/2023 17:41:14 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
root@vagrant:/# curl -sO https://packages.wazuh.com/4.5/wazuh-install.sh
root@vagrant:/# bash wazuh-install.sh --wazuh-indexer node-1
04/09/2023 17:41:37 INFO: Starting Wazuh installation assistant. Wazuh version: 4.5.1
04/09/2023 17:41:37 INFO: Verbose logging redirected to /var/log/wazuh-install.log
04/09/2023 17:41:43 INFO: --- Dependencies ----
04/09/2023 17:41:43 INFO: Installing apt-transport-https.
04/09/2023 17:41:46 INFO: Wazuh repository added.
04/09/2023 17:41:46 INFO: --- Wazuh indexer ---
04/09/2023 17:41:46 INFO: Starting Wazuh indexer installation.
04/09/2023 17:42:37 INFO: Wazuh indexer installation finished.
04/09/2023 17:42:37 INFO: Wazuh indexer post-install configuration finished.
04/09/2023 17:42:37 INFO: Starting service wazuh-indexer.
04/09/2023 17:42:46 INFO: wazuh-indexer service started.
04/09/2023 17:42:46 INFO: Initializing Wazuh indexer cluster security settings.
04/09/2023 17:42:47 INFO: Wazuh indexer cluster initialized.
04/09/2023 17:42:47 INFO: Installation finished.
root@vagrant:/# ^C
root@vagrant:/#
root@vagrant:/# bash wazuh-install.sh --start-cluster
04/09/2023 17:44:10 INFO: Starting Wazuh installation assistant. Wazuh version: 4.5.1
04/09/2023 17:44:10 INFO: Verbose logging redirected to /var/log/wazuh-install.log
04/09/2023 17:44:16 INFO: Wazuh indexer cluster security configuration initialized.
04/09/2023 17:44:22 INFO: Wazuh indexer cluster started.
root@vagrant:/# tar -axf wazuh-install-files.tar wazuh-install-files/wazuh-passwords.txt -O | grep -P "\'admin\'" -A 1
  indexer_username: 'admin'
  indexer_password: 'B8eo74acm7h?vq*bKhOV4re6Y7oU6u?Z'
root@vagrant:/# curl -k -u admin:<ADMIN_PASSWORD> https://<WAZUH_INDEXER_IP>:9200
bash: ADMIN_PASSWORD: No such file or directory
root@vagrant:/# curl -k -u admin:B8eo74acm7h?vq*bKhOV4re6Y7oU6u?Z https://0.0.0.0:9200
{
  "name" : "node-1",
  "cluster_name" : "wazuh-indexer-cluster",
  "cluster_uuid" : "A75xDckiTD-wOwcB6RINqg",
  "version" : {
    "number" : "7.10.2",
    "build_type" : "rpm",
    "build_hash" : "7203a5af21a8a009aece1474446b437a3c674db6",
    "build_date" : "2023-02-24T18:57:04.388618985Z",
    "build_snapshot" : false,
    "lucene_version" : "9.5.0",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
root@vagrant:/# bash wazuh-install.sh --wazuh-server wazuh-1
04/09/2023 17:45:28 INFO: Starting Wazuh installation assistant. Wazuh version: 4.5.1
04/09/2023 17:45:28 INFO: Verbose logging redirected to /var/log/wazuh-install.log
04/09/2023 17:45:33 INFO: Wazuh repository added.
04/09/2023 17:45:33 INFO: --- Wazuh server ---
04/09/2023 17:45:33 INFO: Starting the Wazuh manager installation.
04/09/2023 17:46:01 INFO: Wazuh manager installation finished.
04/09/2023 17:46:01 INFO: Starting service wazuh-manager.
04/09/2023 17:46:16 INFO: wazuh-manager service started.
04/09/2023 17:46:16 INFO: Starting Filebeat installation.
04/09/2023 17:46:21 INFO: Filebeat installation finished.
04/09/2023 17:46:21 INFO: Filebeat post-install configuration finished.
04/09/2023 17:46:24 INFO: Starting service filebeat.
04/09/2023 17:46:25 INFO: filebeat service started.
04/09/2023 17:46:25 INFO: Installation finished.
root@vagrant:/# bash wazuh-install.sh --wazuh-dashboard dashboard
04/09/2023 17:46:26 INFO: Starting Wazuh installation assistant. Wazuh version: 4.5.1
04/09/2023 17:46:26 INFO: Verbose logging redirected to /var/log/wazuh-install.log
04/09/2023 17:46:32 INFO: Wazuh repository added.
dashboard
04/09/2023 17:46:32 INFO: --- Wazuh dashboard ----
04/09/2023 17:46:32 INFO: Starting Wazuh dashboard installation.
04/09/2023 17:47:02 INFO: Wazuh dashboard installation finished.
04/09/2023 17:47:02 INFO: Wazuh dashboard post-install configuration finished.
04/09/2023 17:47:02 INFO: Starting service wazuh-dashboard.
04/09/2023 17:47:02 INFO: wazuh-dashboard service started.
04/09/2023 17:47:14 INFO: Initializing Wazuh dashboard web application.
04/09/2023 17:47:15 INFO: Wazuh dashboard web application initialized.
04/09/2023 17:47:15 INFO: --- Summary ---
04/09/2023 17:47:15 INFO: You can access the web interface https://0.0.0.0
    User: admin
    Password: B8eo74acm7h?vq*bKhOV4re6Y7oU6u?Z
04/09/2023 17:47:15 INFO: Installation finished.

root@vagrant:/var/ossec# ./bin/wazuh-control restart
wazuh-clusterd not running...
Killing wazuh-modulesd...
Killing wazuh-monitord...
Killing wazuh-logcollector...
Killing wazuh-remoted...
Killing wazuh-syscheckd...
Killing wazuh-analysisd...
wazuh-maild not running...
Killing wazuh-execd...
Killing wazuh-db...
Killing wazuh-authd...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
Killing wazuh-apid...
Wazuh v4.5.1 Stopped
Starting Wazuh v4.5.1...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...

```

- Change wazuh-wui password:

```
root@vagrant:/usr/share/wazuh-dashboard/data# curl -H 'Content-Type: application/json' -H "Authorization: Bearer $TOKEN" -d '{"password":"My_password_01"}'  -k -X PUT "https://0.0.0.0:55000/security/users/2"                                                                                                                                             
{"data": {"affected_items": [{"id": 2, "username": "wazuh-wui", "allow_run_as": true, "roles": [1]}], "total_affected_items": 1, "total_failed_items": 0, "failed_items": []}, "message": "User was successfully updated", "error": 0}
```

- Upgrade to wazuh 4.6.0

```
root@vagrant:/# apt install ./wazuh-manager_4.6.0-wp.2392_amd64.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'wazuh-manager' instead of './wazuh-manager_4.6.0-wp.2392_amd64.deb'
Suggested packages:
  expect
The following packages will be upgraded:
  wazuh-manager
1 upgraded, 0 newly installed, 0 to remove and 124 not upgraded.
Need to get 0 B/171 MB of archives.
After this operation, 1,731 kB of additional disk space will be used.
Get:1 /wazuh-manager_4.6.0-wp.2392_amd64.deb wazuh-manager amd64 4.6.0-wp.2392 [171 MB]
(Reading database ... 161624 files and directories currently installed.)
Preparing to unpack .../wazuh-manager_4.6.0-wp.2392_amd64.deb ...
Unpacking wazuh-manager (4.6.0-wp.2392) over (4.5.1-1) ...
Setting up wazuh-manager (4.6.0-wp.2392) ...
Scanning processes...
Scanning linux images...

Running kernel seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
root@vagrant:/# cd /var/ossec/bin/
root@vagrant:/var/ossec/bin# ./wazuh-control restart
wazuh-clusterd not running...
Killing wazuh-modulesd...
Killing wazuh-monitord...
Killing wazuh-logcollector...
Killing wazuh-remoted...
Killing wazuh-syscheckd...
Killing wazuh-analysisd...
wazuh-maild not running...
Killing wazuh-execd...
Killing wazuh-db...
Killing wazuh-authd...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
Killing wazuh-apid...
Wazuh v4.6.0 Stopped
Starting Wazuh v4.6.0...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
2023/09/04 18:28:37 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
Started wazuh-integratord...
Started wazuh-agentlessd...
Started wazuh-authd...
Started wazuh-db...
Started wazuh-execd...
Started wazuh-analysisd...
Started wazuh-syscheckd...
Started wazuh-remoted...
Started wazuh-logcollector...
Started wazuh-monitord...
Started wazuh-modulesd...
Completed.

```
 
- Test User authentication endpoint

```

root@vagrant:/var/ossec/bin# TOKEN=$(curl -u wazuh-wui:My_password_01 -k -X POST "https://0.0.0.0:55000/security/user/authenticate?raw=true")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    59  100    59    0     0    244      0 --:--:-- --:--:-- --:--:--   244
root@vagrant:/var/ossec/bin# echo $TOKEN
{"title": "Unauthorized", "detail": "Invalid credentials"}
root@vagrant:/var/ossec/bin# TOKEN=$(curl -u wazuh-wui:wazuh-wui -k -X POST "https://0.0.0.0:55000/security/user/authenticate?raw=true")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   404  100   404    0     0   1454      0 --:--:-- --:--:-- --:--:--  1453
root@vagrant:/var/ossec/bin#
root@vagrant:/var/ossec/bin# echo $TOKEN
eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjkzODUyNDAyLCJleHAiOjE2OTM4NTMzMDIsInN1YiI6IndhenVoLXd1aSIsInJ1bl9hcyI6ZmFsc2UsInJiYWNfcm9sZXMiOlsxXSwicmJhY19tb2RlIjoid2hpdGUifQ.AGzVca7TdyewOSSwTQRk8AJbRveDVwRo4zUK4X7YPnRJmAwLpyFrRb5IflvphH_VBBryxM-3c1Rmx00BKVvXFj03AUTogi1YZtr33PFpRAq0Pxxx6kN3JppcZfqu0LIuT0I4gYOo-Spa-SeaWtJUPkUlK-0suD8FLOw-sGWGlkxm13HD
```

The migration is done unsuccessfully by overwriting the user config with the default behavior.

To fix this behavior a debug is required in the [DatabaseManager](https://github.com/wazuh/wazuh/blob/88f03b2c6eac9dd2c80cb2d020d4b3fe7784f25d/framework/wazuh/rbac/orm.py#L2625) class and more specifically in the [migrate_data](https://github.com/wazuh/wazuh/blob/88f03b2c6eac9dd2c80cb2d020d4b3fe7784f25d/framework/wazuh/rbac/orm.py#L2775C9-L2775C21) method.

A recommendation debuggin method is:

- [ ] Debug the [get_data](https://github.com/wazuh/wazuh/blob/88f03b2c6eac9dd2c80cb2d020d4b3fe7784f25d/framework/wazuh/rbac/orm.py#L2826) to confirm old user information is being handled correctly.
- [ ] Debug  [add_user](https://github.com/wazuh/wazuh/blob/88f03b2c6eac9dd2c80cb2d020d4b3fe7784f25d/framework/wazuh/rbac/orm.py#L2829C1-L2829C1)  method to confirm data is being migrated successfully to new database.
- [ ] Check if the hashed passwords for the users are the same in both DB before the DB replacement.

**Comment by fdalmaup** [comment]
# Issue Update

The main problem is that both `wazuh` and `wazuh-wui` users' passwords are not being updated inside the `check_database_integrity()` method `framework/wazuh/rbac/orm.py` because their IDs (1 and 2) are not being taken into account to make a call to `migrate_data()`:
https://github.com/wazuh/wazuh/blob/4685040b5588948489d7fb044bff769d5373be10/framework/wazuh/rbac/orm.py#L3086-L3089

Adding the call for those IDs (check #18772) does not solve the problem instantly since the method tries to insert the users and since they already exist, it creates new ones. Something similar happens with roles, rules, and policies:
```
2023/09/04 20:29:14 WARNING: User 1 (wazuh) is part of the new default users. Renaming it to 'wazuh_user'
2023/09/04 20:29:14 WARNING: User 2 (wazuh-wui) is part of the new default users. Renaming it to 'wazuh-wui_user'
2023/09/04 20:29:14 WARNING: Role 1 (administrator) is part of the new default roles. Renaming it to 'administrator_user'
2023/09/04 20:29:14 WARNING: Role 2 (readonly) is part of the new default roles. Renaming it to 'readonly_user'
2023/09/04 20:29:14 WARNING: Rule 1 (wui_elastic_admin) is part of the new default rules. Attempting to migrate relationships
2023/09/04 20:29:14 INFO: All relationships were migrated to the new rule 1
2023/09/04 20:29:14 WARNING: Rule 2 (wui_opendistro_admin) is part of the new default rules. Attempting to migrate relationships
2023/09/04 20:29:14 INFO: All relationships were migrated to the new rule 2
2023/09/04 20:29:14 WARNING: Policy 1 (agents_all_resourceless) is part of the new default policies. Attempting to migrate relationships
2023/09/04 20:29:14 INFO: All relationships were migrated to the new policy 1
2023/09/04 20:29:14 WARNING: Policy 2 (agents_all_agents) is part of the new default policies. Attempting to migrate relationships
2023/09/04 20:29:14 INFO: All relationships were migrated to the new policy 2
2023/09/04 20:29:15 WARNING: Rule 2 (wui_opendistro_admin) no longer exists. Removing affected role-rule relationships
```

The method `AuthenticationManager.update_user()` might aid in achieving the desired result, although we should consider and discuss if the current behavior (i.e., maintaining the default values for those users) is the desired and expected one decided when developing the migration method or if the latter should include the update of the passwords.

**Comment by EduLeon12** [comment]
## Issue Update

After testing the proposed solution, the migration of the default user passwords 'wazuh' and 'wazuh-wui' was successful

<details> <summary>Testing Process </summary>

- Wazuh 4.5.1 installation output: 

```
root@vagrant:/var/ossec# ./bin/wazuh-control restart
wazuh-clusterd not running...
Killing wazuh-modulesd...
Killing wazuh-monitord...
Killing wazuh-logcollector...
Killing wazuh-remoted...
Killing wazuh-syscheckd...
Killing wazuh-analysisd...
wazuh-maild not running...
Killing wazuh-execd...
Killing wazuh-db...
Killing wazuh-authd...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
Killing wazuh-apid...
Wazuh v4.5.1 Stopped
Starting Wazuh v4.5.1...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
2023/09/04 18:13:35 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
Started wazuh-integratord...
Started wazuh-agentlessd...
Started wazuh-authd...
Started wazuh-db...
Started wazuh-execd...
Started wazuh-analysisd...
Started wazuh-syscheckd...
Started wazuh-remoted...
Started wazuh-logcollector...
Started wazuh-monitord...
Started wazuh-modulesd...
Completed.
```

- Password change for user `wazuh-wui`:

```
root@vagrant:/var/ossec# curl -k -X PUT "https://0.0.0.0:55000/security/users/2" -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" -d '{"password":"My_password_01"}'
```

- Version Update to branch with fix:

```
root@vagrant:git clone -b fix/18771-add-default-users-migration https://github.com/wazuh/wazuh.git

root@vagrant:/wazuh# ./install.sh

#########################
#########################

Starting Wazuh...

 - Configuration finished properly.

 - To start Wazuh:
      /var/ossec/bin/wazuh-control start

 - To stop Wazuh:
      /var/ossec/bin/wazuh-control stop

 - The configuration can be viewed or modified at /var/ossec/etc/ossec.conf


   Thanks for using Wazuh.
   Please don't hesitate to contact us if you need help or find
   any bugs.

   Use our public Mailing List at:
          https://groups.google.com/forum/#!forum/wazuh

   More information can be found at:
          - http://www.wazuh.com/

    ---  Press ENTER to finish (maybe more information below). ---

 - Update completed.

root@iI:/var/ossec# ./bin/wazuh-control restart
wazuh-clusterd not running...
Killing wazuh-modulesd...
Killing wazuh-monitord...
Killing wazuh-logcollector...
Killing wazuh-remoted...
Killing wazuh-syscheckd...
Killing wazuh-analysisd...
wazuh-maild not running...
Killing wazuh-execd...
Killing wazuh-db...
Killing wazuh-authd...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
Killing wazuh-apid...
Wazuh v4.6.0 Stopped
Starting Wazuh v4.6.0...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
2023/09/05 14:51:36 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
Started wazuh-integratord...
Started wazuh-agentlessd...
Started wazuh-authd...
Started wazuh-db...
Started wazuh-execd...
Started wazuh-analysisd...
Started wazuh-syscheckd...
Started wazuh-remoted...
Started wazuh-logcollector...
Started wazuh-monitord...
Started wazuh-modulesd...
Completed.
```

- Test User authentication:

```
root@vagrant:/wazuh# TOKEN=$(curl -u wazuh-wui:wazuh-wui -k -X POST "https://0.0.0.0:55000/security/user/authenticate?raw=true")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    59  100    59    0     0    329      0 --:--:-- --:--:-- --:--:--   331
2023/09/05 14:22:13 INFO: wazuh-wui 127.0.0.1 "POST /security/user/authenticate" with parameters {"raw": "true"} and body {} done in 0.173s: 401

root@vagrant:/wazuh# TOKEN=$(curl -u wazuh-wui:My_password_01 -k -X POST "https://0.0.0.0:55000/security/user/authenticate?raw=true")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   404  100   404    0     0   1744      0 --:--:-- --:--:-- --:--:--  1741
2023/09/05 14:15:16 INFO: wazuh-wui 127.0.0.1 "POST /security/user/authenticate" with parameters {"raw": "true"} and body {} done in 0.227s: 200
root@vagrant:/wazuh# echo $TOKEN
eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjkzOTIzMzE2LCJleHAiOjE2OTM5MjQyMTYsInN1YiI6IndhenVoLXd1aSIsInJ1bl9hcyI6ZmFsc2UsInJiYWNfcm9sZXMiOlsxXSwicmJhY19tb2RlIjoid2hpdGUifQ.AMRWaY4OCyKs2PCWX7cMosdSO7eHKWLaXo6EDQxONAEkTYGZMKc5hEW-46_8XW8SW8qcn5KgTUKM0YTIGNKdta3WAeobod03oDQKjnzQkfeDPqYUkadV55ldb_6r8kei7oRAaUVgjKeQd16QsywZMuoMDsplVVzXrGc--VxgtoF4GXM3
```

</details>

**Comment by davidjiglesias** [comment]
LGTM!
