### ISSUE TITLE
Scheduled upward merges for numbered branches in wazuh repository - Fortnight #17

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#18797]
## Description

The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.5.2-into-4.5.3`.

## Tasks

- [ ]

### 4.5.2
- [ ] Update changelog.
- [ ] Merge branch `4.5.2` into branch `4.5.3`.
### 4.5.3
- [ ] Update changelog.
- [ ] Merge branch `4.5.3` into branch `4.6.0`.
### 4.6.0
- [ ] Update changelog.
- [ ] Merge branch `4.6.0` into branch `4.7.0`.
### 4.7.0
- [ ] Update changelog.
- [ ] Merge branch `4.7.0` into branch `master`.
