### ISSUE TITLE
Maintain production and numbered branches post release 4.5.2 in wazuh repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#18813]
## Description

The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.5.2-into-4.5.3`.

## Tasks

- [x] Merge branch `4.5.2` into branch `4.5.3`.
- [x] Merge branch `4.5.3` into branch `4.6.0`.
- [x] Merge branch `4.6.0` into branch `4.7.0`.
- [ ] Merge branch `4.7.0` into branch `master`.
- [x] Delete all stage pre-releases for 4.5.2 (https://github.com/wazuh/wazuh/releases).
- [x] Delete all stage tags for v4.5.2. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.5.2-rc1, 4.5.2-alpha1, etc.
- [x] Delete branch `4.5.2`.
