### ISSUE TITLE
Improve vulnerability-detector 

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh#1887]
This issue contains the roadmap designed to improve different aspects of this module, as well as solve some invalid behaviors. 

### Priority tasks

- [x] **(3.8)** Design a modularized parser for Red Hat, with a view to expanding it to other operating systems, which combines its OVAL with the Security Data API for an optimal result. Related to https://github.com/wazuh/wazuh/issues/1265. 
- [x] **(3.8)** Implement the new parser.
- [ ] Extend compatibility with new systems such as Oracle Linux, which has its own feed.
- [x] **(3.8)** Option patch and url with new feed.
- [ ] Add custom decoder in Analisysd to decode string arrays.

### Lower priority tasks

- [ ] Study the improvement of the current database update process. To do this, the efficiency of the current updating method will be compared with the single insertion method based on hash tables.
- [ ] Apply the modularized parser to the rest of compatible feeds.

These tasks will probably be modified and expanded.

Working on [this branch](https://github.com/wazuh/wazuh/tree/dev-vuln-rh-feed).

**Comment by chemamartinez** [comment]
This issue is outdated.
