### ISSUE TITLE
Engine - Update windows decoders

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#18935]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|5.0.0 | Engine | Manager | Packages/Sources | OS version |

### Description

The objective of this issue is to enhance the `windows-security.yml` decoder in the Wazuh engine to align it more closely with the established syntax and improve overall decoding consistency. This update will not only make the decoder more complete but also serve as a reference for creating other decoders.

### Tasks

- [x] **Remove Parent Decoder References**
   - In `windows-event.yml`, remove the following lines:
     ```
     parents:
       - decoder/integrations/0
     ```

- [x] **Change Variable Name**
   - In `windows-event.yml`, change the variable name `_MapWindowsLevelToLogLevel` to `_win_log_level`.

- [x] **Unify Formatting for Multi-line Checks**
   - Ensure that all multi-line checks in decoders use the `>-` format for consistency.

- [x] **Include Empty Line**
   - In `windows-security.yml`, include an empty line before `# Generic fields comment` to improve readability.

- [x] **Remove Unnecessary Single Quotes**
   - Review and remove unnecessary single quotes from the `windows-security.yml` decoder.

- [x] **Create Helper Function for User Account Control Attributes**
   - Create a helper function in the `windows-security.yml` decoder to set User Account Control Attributes.

- [x] **Create Helper Function for Kerberos Ticket Options**
   - Create a helper function in the `windows-security.yml` decoder to set Kerberos Ticket Options.

- [x] **Update Variable Name `kerberos_encryption`**
   - Replace `kerberos_encryption` with `_kerberos_encryption` in `windows-security.yml` (two occurrences).

- [x] **Fix Variables in Set Audit Information**
   - Ensure that `subcategory_guid` and `audit_information_array` are treated as variables in `windows-security.yml`.

- [x] **Fix Variable `failure_code`**
    - Treat `failure_code` as a variable in `windows-security.yml`.

- [x] **Fix Variable `policy_changes`**
    - Treat `policy_changes` as a variable in `windows-security.yml`.

- [x] **Fix Variable `access_list`**
    - Treat `access_list` as a variable in `windows-security.yml`.

- [x] **Implement Helper Function for Array of Values**
    - Implement a helper function in `windows-security.yml` to return an array of values.

- [x] **Create Helper Function for Access Mask Descriptions**
    - Create a helper function in `windows-security.yml` to set Access Mask Descriptions.

- [x] **Avoid Duplicating Elements in Related Arrays**
    - Implement a mechanism to avoid duplicate elements in arrays, such as `related.user` and `related.ip`.

- [x] **Define Variable `member_name_parts`**
    - Treat `member_name_parts` as a variable in `windows-security.yml`.

- [x] **Define Variable `group_domain`**
    - Treat `group_domain` as a variable in `windows-security.yml`.

- [x] **Define Variable `process_parts`**
    - Treat `process_parts` as a variable in `windows-security.yml`.

- [x] **Define Variables `process_parts` and `parent_process_parts`**
    - Treat `process_parts` and `parent_process_parts` as variables in `windows-security.yml`.

- [x] **Define Variables `file_parts` and `file_parts.ext`**
    - Treat `file_parts` and `file_parts.ext` as variables in `windows-security.yml`.
    - 
- [x] **Create Helper Functions for Object Policy Change and SidListDesc**
    - In `windows-security.yml`, examine the code in the range of lines 3093 to 3459, which handles Object Policy Change and SidListDesc. Determine if it requires custom helper functions for these Windows events or if generic helper functions can be utilized.

- [x] **Eliminate Extra Spaces**
    - Remove extra spaces in the decoder check stage.
