### ISSUE TITLE
`wazuh-analysisd` is stopped for no apparent reason in the demo environment

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#18946]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0 | wazuh-analysisd | Manager | Packages | Amazon Linux 2 |

## Description

During the analysis of the issue https://github.com/wazuh/wazuh/issues/18843, a problem was found with the AWS wodle reported in https://github.com/wazuh/wazuh/issues/18901, after the weekend, when accessing the environment, an error was encountered while accessing the WUI showing an API error message

![image](https://github.com/wazuh/wazuh/assets/14913942/97ea8a77-1ead-45c2-b6cf-ebb62969fb9f)

<details><summary>WUI error</summary>

```
INFO: Current API id [env-2]
INFO: Checking current API id [env-2]...
INFO: Current API id [env-2] has some problem: 3002 - Request failed with status code 400
INFO: Getting API hosts...
INFO: API hosts found: 2
INFO: Checking API host id [env-1]...
INFO: Could not connect to API id [env-1]: 3099 - ERROR3099 - Some Wazuh daemons are not ready yet in node "master" (wazuh-analysisd->stopped)
INFO: Checking API host id [env-2]...
INFO: Could not connect to API id [env-2]: 3099 - ERROR3099 - Some Wazuh daemons are not ready yet in node "master" (wazuh-analysisd->stopped)
INFO: Removed [navigate] cookie
ERROR: No API available to connect
```

</details>

When observing the Wazuh manager environments (env-1 and env-2), an irregular state of the service has been found regarding `wazuh-analysisd`, being stopped on both nodes, but on one of them the service is marked as `active (existed)` with living processes while the other is `active (running)`

<details><summary>env-1 node</summary>

```
[root@wazuh-manager-master-0 wazuh-user]# systemctl status wazuh-manager.service 
● wazuh-manager.service - Wazuh manager
   Loaded: loaded (/usr/lib/systemd/system/wazuh-manager.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2023-09-08 19:27:13 UTC; 2 days ago
  Process: 16250 ExecStop=/usr/bin/env /var/ossec/bin/wazuh-control stop (code=exited, status=0/SUCCESS)
  Process: 16413 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/wazuh-manager.service
           ├─16478 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
           ├─16479 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
           ├─16482 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
           ├─16485 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
           ├─16513 /var/ossec/bin/wazuh-integratord
           ├─16532 /var/ossec/bin/wazuh-authd
           ├─16550 /var/ossec/bin/wazuh-db
           ├─16576 /var/ossec/bin/wazuh-execd
           ├─16606 /var/ossec/bin/wazuh-syscheckd
           ├─16628 /var/ossec/bin/wazuh-remoted
           ├─16661 /var/ossec/bin/wazuh-logcollector
           ├─16682 /var/ossec/bin/wazuh-monitord
           ├─16732 /var/ossec/bin/wazuh-modulesd
           ├─16869 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh_clusterd.py
           ├─16898 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh_clusterd.py
           └─16899 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh_clusterd.py
[root@wazuh-manager-master-0 wazuh-user]# /var/ossec/bin/wazuh-control status
wazuh-clusterd is running...
wazuh-modulesd is running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd not running...
wazuh-maild not running...
wazuh-execd is running...
wazuh-db is running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord is running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid is running...
[root@wazuh-manager-master-0 wazuh-user]# ps -ef | grep wazuh 
root     14656 12357  0 12:01 ?        00:00:00 sshd: wazuh-user [priv]
wazuh-u+ 14679 14656  0 12:01 ?        00:00:00 sshd: wazuh-user@pts/0
wazuh-u+ 14680 14679  0 12:01 pts/0    00:00:00 -bash
wazuh    16478     1  0 Sep08 ?        00:01:16 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh    16479 16478  0 Sep08 ?        00:00:02 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh    16482 16478  0 Sep08 ?        00:01:30 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh    16485 16478  0 Sep08 ?        00:00:00 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh    16513     1  0 Sep08 ?        00:01:30 /var/ossec/bin/wazuh-integratord
root     16532     1  0 Sep08 ?        00:09:52 /var/ossec/bin/wazuh-authd
wazuh    16550     1  0 Sep08 ?        00:05:50 /var/ossec/bin/wazuh-db
root     16576     1  0 Sep08 ?        00:00:05 /var/ossec/bin/wazuh-execd
root     16606     1  0 Sep08 ?        00:00:46 /var/ossec/bin/wazuh-syscheckd
wazuh    16628     1  0 Sep08 ?        00:06:06 /var/ossec/bin/wazuh-remoted
root     16661     1  0 Sep08 ?        00:00:28 /var/ossec/bin/wazuh-logcollector
wazuh    16682     1  0 Sep08 ?        00:06:22 /var/ossec/bin/wazuh-monitord
root     16732     1  1 Sep08 ?        00:50:13 /var/ossec/bin/wazuh-modulesd
wazuh    16869     1  0 Sep08 ?        00:08:33 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh_clusterd.py
wazuh    16898 16869  0 Sep08 ?        00:01:04 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh_clusterd.py
wazuh    16899 16869  0 Sep08 ?        00:01:05 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh_clusterd.py
root     17870 12357  0 12:49 ?        00:00:00 sshd: wazuh-user [priv]
wazuh-u+ 17876 17870  0 12:49 ?        00:00:00 sshd: wazuh-user@pts/1
wazuh-u+ 17877 17876  0 12:49 pts/1    00:00:00 -bash
root     18122 18019  0 12:51 pts/1    00:00:00 grep --color=auto wazuh

```

</details>

<details><summary>env-2 node</summary>

```
[root@wazuh-manager-master-0 wazuh-user]# systemctl status wazuh-manager.service 
● wazuh-manager.service - Wazuh manager
   Loaded: loaded (/usr/lib/systemd/system/wazuh-manager.service; enabled; vendor preset: disabled)
   Active: active (exited) since Thu 2023-09-07 13:26:14 UTC; 3 days ago
  Process: 17922 ExecStop=/usr/bin/env /var/ossec/bin/wazuh-control stop (code=exited, status=0/SUCCESS)
  Process: 18081 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/SUCCESS)

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
[root@wazuh-manager-master-0 wazuh-user]# /var/ossec/bin/wazuh-control status
wazuh-clusterd is running...
wazuh-modulesd is running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd not running...
wazuh-maild not running...
wazuh-execd is running...
wazuh-db is running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord is running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid is running...
[root@wazuh-manager-master-0 wazuh-user]# ps -ef | grep wazuh
root      8381 12350  0 12:49 ?        00:00:00 sshd: wazuh-user [priv]
wazuh-u+  8383  8381  0 12:49 ?        00:00:00 sshd: wazuh-user@pts/0
wazuh-u+  8384  8383  0 12:49 pts/0    00:00:00 -bash
root      8520  8429  0 12:51 pts/0    00:00:00 grep --color=auto wazuh
wazuh    25111     1  0 Sep07 ?        00:01:57 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh    25112 25111  0 Sep07 ?        00:00:18 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh    25115 25111  0 Sep07 ?        00:03:20 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh    25118 25111  0 Sep07 ?        00:00:00 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh    25146     1  0 Sep07 ?        00:03:04 /var/ossec/bin/wazuh-integratord
root     25165     1  0 Sep07 ?        00:14:24 /var/ossec/bin/wazuh-authd
wazuh    25182     1  0 Sep07 ?        00:06:00 /var/ossec/bin/wazuh-db
root     25207     1  0 Sep07 ?        00:00:08 /var/ossec/bin/wazuh-execd
root     25234     1  0 Sep07 ?        00:01:21 /var/ossec/bin/wazuh-syscheckd
wazuh    25255     1  0 Sep07 ?        00:07:56 /var/ossec/bin/wazuh-remoted
root     25289     1  0 Sep07 ?        00:00:42 /var/ossec/bin/wazuh-logcollector
wazuh    25309     1  0 Sep07 ?        00:10:53 /var/ossec/bin/wazuh-monitord
root     25358     1  2 Sep07 ?        02:27:17 /var/ossec/bin/wazuh-modulesd
wazuh    25485     1  0 Sep07 ?        00:02:13 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh_clusterd.py
wazuh    25491 25485  0 Sep07 ?        00:01:19 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh_clusterd.py
wazuh    25492 25485  0 Sep07 ?        00:01:20 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh_clusterd.py
```

</details>

## Tasks

- [ ] It is necessary to investigate and determine the following questions
   - Why wazuh-analysisd is stopped and the rest of the processes are still alive?
   - Why the Wazuh manager service is in an `active (exited)` state but there are live processes in the system?
   - Is there a relationship with the issue https://github.com/wazuh/wazuh/issues/18901?
- [ ] Find the cause of the error
- [ ] Apply the necessary fixes so that this behavior does not reproduce (if applicable)

## Maybe related

- https://github.com/wazuh/wazuh/issues/18901

**Comment by JorgeMarinoDev** [comment]
@rauldpm We were taking a look at this. 

We also understand the possible relation between analysis-d being dropped with the [aws wodle issue](https://github.com/wazuh/wazuh/issues/18901)

To proceed we need the entire logs (actual files) of master env1, env2 and the agent with the wodle. To cover [this point in time](https://github.com/wazuh/wazuh/issues/18843#issuecomment-1713834568)

Also if it's possible , to create a zip file for each. Containing /var/ossec etc, config, and so on to get a good idea of the environments. (similar to the footprint tests attached files)

Regards

**Comment by rauldpm** [comment]
The environment must be deployed and accessible, please contact @wazuh/cicd team to get the access credentials to the Wazuh manager master/worker nodes, where you can obtain the required files

**Comment by JorgeMarinoDev** [comment]
**Status Update**

* Requested and granted access to demo env. env1 and env2.

First Observation

* No logs archives found in both envs for Sept 8. (empty files)

![Screenshot from 2023-09-14 10-18-12](https://github.com/wazuh/wazuh/assets/117848458/3951db34-df6c-4c15-a5cf-fe28fcb59023)

![Screenshot from 2023-09-14 10-19-47](https://github.com/wazuh/wazuh/assets/117848458/9261c5dd-5c41-4a69-92d1-3965f43d0701)

In env2, we found some anomalies in Sept 09 log. (attached)

[ossec-09.log](https://github.com/wazuh/wazuh/files/12609966/ossec-09.log)

In the next screenshot we can see how logs are corrupted. 
![image](https://github.com/wazuh/wazuh/assets/117848458/b27ed4fb-2be2-47e0-8828-250f7eaf9322)

In the next screenshot we can see how Sept 9 at 03:33:56 it was the last time a log line was written. And the last thing logged was related to aws-s3 module. Should we correlate this info with any service restart? 

![image](https://github.com/wazuh/wazuh/assets/117848458/ca622447-46ce-4714-b97f-bea09a83db36)

**Comment by JorgeMarinoDev** [comment]
#### Issue : wazuh-analysisd is stopped for no apparent reason in the demo environment

After initial research these facts were found:

1. There is evidence that between September 7th and 8th the environments ran out of disk space due to the amount of alerts coming from aws module. 
   1. During this abnormal case, even some log lines are corrupted due to buffer corruptions. 
   2. Archive logs for Sept 8 were lost. System was not able to perform the compression.
   3. Alert log lines from aws were corrupted, superimposed json messages.
2. This behavior was confirmed in both envs.

```
wazuh-user@master-env2.wazuh.info
wazuh-user@master-env1.wazuh.info
```

3. After the disk issue, several operations were performed in the environments, and the final state was lost. 
4. The systemctl status of manager reported in this issue were taken 2 days after everything happened.
5. Many logs refer: `wazuh-modulesd: ERROR: (1278): Unable to reconnect to 'queue/sockets/queue': Connection refused (111).` After full disk.



**The next research stage was focused in finding :**

1. Out of Memory warnings.

2. SegFault evidence.

3. Core Dumps.

4. Abnormal sequence in the history of services. `journalctl` (attached)
[journalctl-env1.txt](https://github.com/wazuh/wazuh/files/12621361/journalctl-env1.txt)

5. Checking archived logs

   `/var/ossec/logs/wazuh/2023/Sep/tmp/ossec-07.log`
   `/var/ossec/logs/wazuh/2023/Sep/tmp/ossec-09.log`
   `/var/ossec/logs/wazuh/2023/Sep/tmp/ossec-10.log`
   `/var/ossec/logs/wazuh/2023/Sep/tmp/ossec-11.log`
   `/var/ossec/logs/wazuh/2023/Sep/tmp/ossec-12.log`
   `/var/ossec/logs/wazuh/2023/Sep/tmp/ossec-13.log`

6. Checking /var/log/messages
   `messages`
   `messages-20230910`
7. Checking .pid of daemons in `/var/ossec/var/run`.
8. Dmesg.
9. Kernel level messages.

After all of this no significant evidence was found, other than corrupted logs, or missing files.
No core dumps, no segfault, no OOM.



**Some hypothesis**

1. IPC sockets flooded.
2. var/run files and states failed relying on disk.
3. Processing corrupted events or logs caused abnormal behavior on **analysisd**.
4. Problem of direct feeding from aws integrator module bypassing monitord (please confirm architecture or disregard).



**Future improvements**

* If any issue similar to this, try to preserve the status and inform immediately. Do not conduct any operation further, because evidence will be lost.
* Conduct an experiment with low disk and try to reproduce.

**Comment by JorgeMarinoDev** [comment]
**A brief update on this**

1. Research results were analyzed and we agreed on keep monitoring the DEMO ENVIRONMENT until Sept 20th. 
2. We confirmed that this abnormal behavior was caused by full disk consequences.
3. The original [AWS wodle issue](https://github.com/wazuh/wazuh/issues/18901) was fixed and merged into 4.6.0 in [19002](https://github.com/wazuh/wazuh/pull/19002)
4. New version with fix is not deployed on DEMO (verified by checking date of fix compared to service start date)
5. We suggest resetting DEMO ENVIRONMENT after Sept 20th WITH deploy of new 4.6.0 with fix.

**September 19th Check**
![Screenshot from 2023-09-19 15-18-51](https://github.com/wazuh/wazuh/assets/117848458/daeb8881-d5d9-4458-96f0-590c3f757042)
![Screenshot from 2023-09-19 15-41-54](https://github.com/wazuh/wazuh/assets/117848458/d86b311f-f8cb-4039-a2be-0b6d4534652e)
![image](https://github.com/wazuh/wazuh/assets/117848458/1673d1b2-1ca0-49e2-a991-1517b59a8dfd)

Observations:
1. Service still on **active (exited)** state and processes running,
2. No relevant log info found.
3. kernel dmesg logs still show journal issues due to low disk.
