### ISSUE TITLE
Week 37 - Update Wazuh feeds

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#18993]
|Week|Feeds|Previous issue|
|---|---|---|
|37|MSU/ALAS|https://github.com/wazuh/wazuh/issues/18801|

## Description

The following issue aims to check the weekly update of Wazuh feeds, where they will be checked, and it will be decided whether to update them according to the results obtained.

All feed results must have one of the following statuses: 
| | |
|---------------------------------|--------------------------------------------|
| :green_circle: | The feed has been successfully updated |
| :red_circle:  | The feed could not be updated due to failures |
| :yellow_circle:  | The feed has been updated, but a failure has occurred |
| :black_circle:  | The feed has not been updated because it is not needed |

Any failed feed should be reported, detailing the error and possible cause.

In the results, the differences between the current feed and the new feed that will overwrite the current feed should be detailed.

### Current Wazuh feeds
- MSU: https://feed.wazuh.com/vulnerability-detector/windows/msu-updates.json.gz
- ALAS:
  - ALAS 1: https://feed.wazuh.com/vulnerability-detector/ALAS/1/alas.json.gz
  - ALAS 2: https://feed.wazuh.com/vulnerability-detector/ALAS/2/alas2.json.gz
  - ALAS 2022: https://feed.wazuh.com/vulnerability-detector/ALAS/2022/alas2022.json.gz
  - ALAS 2023: https://feed.wazuh.com/vulnerability-detector/ALAS/2023/alas2023.json.gz

### Tasks
- [x] Check that feeds have been generated correctly.
- [x] Analyse the difference between the current feed and the new feed.
- [ ] Update the current feed with the new feed.
------
- [ ] In addition, check the [EoL dates](https://endoflife.date/) of the OSes we [officially support with Vulnerability Detector](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/how-it-works.html#compatibility-matrix).
- [ ] Check if there is any news related to feed deprecations on the pages of official providers, and if so, report it.

**Comment by MarcelKemp** [comment]
## Update Wazuh feeds

### New feeds vs Current feeds

#### MSU

|MSU|Hotfixes|CVEs|
|---|---|---|
| MSU | +38 | +41 |

- Hotfixes:
```
KB4486670
KB5002398
KB5002419
KB5002435
KB5002436
KB5002437
KB5002439
KB5002445
KB5002451
KB5002453
KB5002459
KB5002463
KB5002464
KB5002465
KB5023788
KB5028948
KB5028952
KB5029242
KB5029243
KB5029247
KB5029250
KB5029259
KB5029295
KB5029296
KB5029312
KB5029318
KB5029332
KB5029351
KB5029646
KB5029647
KB5029648
KB5029651
KB5029652
KB5029653
KB5029654
KB5029655
KB5029847
KB5029848
```

- CVEs:
```
CVE-2023-35355
CVE-2023-36744
CVE-2023-36745
CVE-2023-36756
CVE-2023-36757
CVE-2023-36761
CVE-2023-36762
CVE-2023-36763
CVE-2023-36764
CVE-2023-36766
CVE-2023-36767
CVE-2023-36777
CVE-2023-36788
CVE-2023-36792
CVE-2023-36793
CVE-2023-36794
CVE-2023-36796
CVE-2023-36799
CVE-2023-36801
CVE-2023-36802
CVE-2023-36803
CVE-2023-36804
CVE-2023-36805
CVE-2023-36886
CVE-2023-38139
CVE-2023-38140
CVE-2023-38141
CVE-2023-38142
CVE-2023-38143
CVE-2023-38144
CVE-2023-38146
CVE-2023-38147
CVE-2023-38148
CVE-2023-38149
CVE-2023-38150
CVE-2023-38152
CVE-2023-38160
CVE-2023-38161
CVE-2023-38162
CVE-2023-38164
CVE-2023-41764
```


#### ALAS

| ALAS | Vulnerabilities |
|---|---|
| ALAS 1 | +9 |
| ALAS 2 | +22 |
| ALAS 2022 | = |
| ALAS 2023 | +25 |


- ALAS 1 vulns:
```
ALAS-2023-1816
ALAS-2023-1817
ALAS-2023-1818
ALAS-2023-1819
ALAS-2023-1820
ALAS-2023-1821
ALAS-2023-1823
ALAS-2023-1824
ALAS-2023-1825
```


- ALAS 2 vulns:
```
ALAS-2023-2222
ALAS-2023-2223
ALAS-2023-2224
ALAS-2023-2225
ALAS-2023-2226
ALAS-2023-2227
ALAS-2023-2228
ALAS-2023-2229
ALAS-2023-2230
ALAS-2023-2231
ALAS-2023-2232
ALAS-2023-2233
ALAS-2023-2234
ALAS-2023-2235
ALAS-2023-2236
ALAS-2023-2237
ALAS-2023-2238
ALAS-2023-2239
ALAS-2023-2240
ALAS-2023-2241
ALAS-2023-2242
ALAS-2023-2243
```



- ALAS 2023 vulns:
```
ALAS-2023-317
ALAS-2023-318
ALAS-2023-319
ALAS-2023-320
ALAS-2023-321
ALAS-2023-322
ALAS-2023-323
ALAS-2023-324
ALAS-2023-325
ALAS-2023-326
ALAS-2023-327
ALAS-2023-328
ALAS-2023-329
ALAS-2023-330
ALAS-2023-331
ALAS-2023-332
ALAS-2023-333
ALAS-2023-334
ALAS-2023-335
ALAS-2023-336
ALAS-2023-337
ALAS-2023-338
ALAS-2023-339
ALAS-2023-340
ALAS-2023-341
```

### Release

| Feeds | Status | SHA256 |
|---|:-:|---|
| MSU | :green_circle:  | `ad36f96d5189cbca5dfb85d85be75c03ab9a7f91fdaf80d5321e69df7d20131d` |
| ALAS 1 | :green_circle: | `51b3eb500659869e1c2bdd85ccab1cec4325bd688d3da151f374add979c0152a` |
| ALAS 2 | :green_circle: | `4728923554335e03815cf19fb5472981905511c5fc7b705869d86026f0ae197a` |
| ALAS 2022 | :green_circle: | `c800c6cd5b42565316a210374caad1e2b51950cb4181eb42f39f261cc081a371` |
| ALAS 2023 | :green_circle: | `64407c141ee2155273343bff0f31f5a2cca406f9f7cb16e9e5834c6ee8337d0e` |

**Comment by MarcelKemp** [comment]
## EoL dates
| Distribution/Provider | Versions | Maintenance Support | Extended Life Cycle Support | Comment |
|---|---|---|---|---|
|  | 5 | 31 Mar 2017 🔴 | 30 Nov 2020 🔴 | Archived ⚫ |
|  | 6 | 30 Nov 2020 🔴 | 30 Jun 2024 🟡 ||
| [**Red Hat**](https://endoflife.date/rhel) | 7 | 30 Jun 2024 🟡 | 30 Jun 2028 🟢 ||
|  | 8 | 31 May 2029 🟢 | 31 May 2032 🟢 ||
|  | 9 | 31 May 2032 🟢 | 31 May 2035 🟢 ||
|  | trusty / 14 | 02 Apr 2019 🔴 | 02 Apr 2024 🟡 ||
|  | xenial / 16 | 02 Apr 2021 🔴 | 02 Apr 2026 🟢 ||
| [**Ubuntu**](https://endoflife.date/ubuntu) | bionic / 18 | 31 May 2023 🔴 | 01 Apr 2028 🟢 ||
|  | focal / 20 | 02 Apr 2025 🟢 | 02 Apr 2030 🟢 ||
|  | jammy / 22 | 01 Apr 2027 🟢 | 09 Apr 2032 🟢 ||
|  | buster / 10 | 10 Sep 2022 🔴 | 30 Jun 2024 🟡 ||
| [**Debian**](https://endoflife.date/debian) | bullseye / 11 | 01 Jul 2024 🟡 | 30 Jun 2026 🟢 ||
|  | bookworm / 12 | 10 Jun 2026 🟢 | 10 Jun 2028 🟢 | Supported in `(v4.6)` - https://github.com/wazuh/wazuh/issues/18516 🟡 |
|  | AL 1 | 31 Dec 2020 🔴 | 31 Dec 2023 :orange_circle: | [Amazon announcement](https://aws.amazon.com/es/blogs/aws/update-on-amazon-linux-ami-end-of-life/) |
| [**Amazon Linux**](https://endoflife.date/amazon-linux) | AL 2 | 30 Jun 2025 🟢 | 30 Jun 2025 🟢 ||
|  | AL 2022 | - | - | Archived ⚫ |
|  | AL 2023 | 15 Mar 2025 🟢 | 15 Mar 2028 🟢 | Not yet supported - https://github.com/wazuh/wazuh/issues/17617 :warning: |
| **Arch Linux** | Rolling release | - | - | 🟢 |
|  | SLES 11 & SLED 11 | 31 Mar 2019 🔴 | 31 Mar 2022 🔴 ||
| [**SUSE**](https://endoflife.date/sles) | SLES 12 & SLED 12 | 31 Oct 2024 🟢 | 31 Oct 2027 🟢 ||
|  | SLES 15 & SLED 15 | 31 Jul 2028 🟢 | 31 Jul 2031 🟢 ||
| [**AlmaLinux**](https://endoflife.date/almalinux) | 8 | 01 May 2024 🟡 | 01 Mar 2029 🟢 | Supported in `(v4.6)` - https://github.com/wazuh/wazuh/pull/16343 🟡 |
|  | 9 | 31 May 2027 🟢 | 31 May 2032 🟢 | Supported in `(v4.6)` - https://github.com/wazuh/wazuh/pull/16343 🟡 |
| [**Windows**](https://endoflife.date/windows) | - |  |  ||
| [**Windows Server**](https://endoflife.date/windows-server) | - |  |  ||
| [**macOS**](https://endoflife.date/macos) | - |  |  ||
