### ISSUE TITLE
Refactor and migrate remoted and rids integration tests from QA repository to Core repository

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#19081]
## Description

As part of wazuh/wazuh#17427, we need to refactor and migrate all legacy integration tests from the QA repository to the Core repository.

This issue aims to do this with the remoted tests. The following files are involved:

```
test_remoted/
├── conftest.py
├── test_active_response
│   ├── data
│   │   └── wazuh_test_active_response.yaml
│   └── test_active_response_send_ar.py
├── test_agent_communication
│   ├── data
│   │   ├── wazuh_agent_pending_status.yaml
│   │   ├── wazuh_agents_reconnection.yaml
│   │   ├── wazuh_agent_version_shared_configuration_startup_message.yaml
│   │   ├── wazuh_invalid_protocol_communication.yaml
│   │   ├── wazuh_multi_agent_protocols_communication.yaml
│   │   ├── wazuh_multi_agent_status.yaml
│   │   ├── wazuh_protocols_communication.yaml
│   │   ├── wazuh_request_agent_info.yaml
│   │   └── wazuh_shared_configuration.yaml
│   ├── test_agent_pending_status.py
│   ├── test_agents_switching_protocols.py
│   ├── test_agent_version_shared_configuration_startup_message.py
│   ├── test_invalid_protocol_communication.py
│   ├── test_multi_agent_protocols_communication.py
│   ├── test_multi_agent_status.py
│   ├── test_protocols_communication.py
│   ├── test_request_agent_info.py
│   └── test_shared_configuration.py
├── test_configuration
│   ├── data
│   │   └── wazuh_basic_configuration.yaml
│   ├── test_basic_configuration_connection_invalid_connection.py
│   ├── test_basic_configuration_connection_invalid_port.py
│   ├── test_basic_configuration_connection_invalid_protocol.py
│   ├── test_basic_configuration_connection_valid.py
│   ├── test_basic_configuration_local_ip_invalid.py
│   ├── test_basic_configuration_local_ip_valid.py
│   ├── test_basic_configuration_queue_size_syslog.py
│   ├── test_basic_configuration_queue_size_too_big.py
│   ├── test_basic_configuration_queue_size_valid.py
│   ├── test_basic_configuration_rids_closing_time_invalid.py
│   ├── test_basic_configuration_rids_closing_time_valid.py
│   ├── test_basic_configuration_syslog_allowed_denied_ips_valid.py
│   ├── test_basic_configuration_syslog_allowed_ips_invalid.py
│   ├── test_basic_configuration_syslog_denied_ips_invalid.py
│   ├── test_basic_configuration_syslog_denied_ips.py
│   └── test_basic_configuration_syslog_no_allowed_ips.py
├── test_manager_messages
│   ├── data
│   │   └── wazuh_manager_ack.yaml
│   └── test_manager_ack.py
├── test_multi_groups
│   ├── data
│   │   └── test_cases
│   │       └── case_file_actions.yaml
│   └── test_merged_mg_file_content.py
└── test_socket_communication
    ├── data
    │   ├── configuration_template
    │   │   └── configuration_syslog_message_parser.yaml
    │   ├── test_cases
    │   │   └── cases_syslog_message_parser.yaml
    │   ├── wazuh_socket_communication.yaml
    │   └── wazuh_syslog.yaml
    ├── test_ping_pong_message.py
    ├── test_syslog_message_parser.py
    └── test_syslog_message.py
```

Also, rids tests should be part of remoted suite:

```
test_rids/
├── data
│   └── wazuh_manager_conf.yaml
├── test_rids_conf.py
└── test_rids.py
```

### Considerations:

- Apply new format to tests.
- Ensure that each test configures all it needs (ie: internal options).
- Move everything related to the test environment configuration to fixtures.
- Make sure tests clean up the environment after execution.
- Place fixtures in `conftest.py` files.
- Use generic functions of the new QA framework.
- Make sure there is no duplicate code.

### Tasks:

- [x] Migrate test_active_response suite.
- [x] Migrate test_agent_communication suite.
- [x] Migrate test_configuration suite.
- [x] Migrate test_rids suite.
- [x] Migrate test_manager_messages suite.
- [x] Migrate test_multi_groups suite.
- [x] Migrate test_socket_communication suite.

Tests branch: [enhancement/19081-remoted-tests](https://github.com/wazuh/wazuh/tree/enhancement/19081-remoted-tests)
Framework branch: [enhancement/19081-remoted-tests](https://github.com/wazuh/qa-integration-framework/tree/enhancement/19081-remoted-tests)

**Comment by thejbte** [comment]
I'm working on `test_socket_connection`, I'm having some problems with generate_callback, because it doesn't match the regex.

**Comment by thejbte** [comment]
I am working on `test_socket_connection`, there is a problem with reading the archive json file in file monitor, it is resolved by archives log file for ipv4 test.

**Comment by thejbte** [comment]
I am working on `test_socket_communication` -> `test_syslog_message`

**Comment by thejbte** [comment]
I am working on `test_socket_communication` -> `test_syslog_message` yet

**Comment by thejbte** [comment]
I'm working on `test_manager_ack`, I created PR . Checks fails on github actions about the framework.

**Comment by thejbte** [comment]
I'm working on `test_manager_ack`, I changed branch base becaue checks fails on github actions. Ready to merge.

**Comment by thejbte** [comment]
I was  working on `test_active_response`,  i created PR, it is ready to be merge.

**Comment by thejbte** [comment]
I'm working on test_agent_communication, I have some errors about "Bad file descriptor". I'm try fix it

**Comment by thejbte** [comment]
I'm working on `test_agent_communication`, I've finished `test_agent_pending_test`. 
I created PR to check test from github actions.

**Comment by thejbte** [comment]
I'm working on `test_agent_communication`. the test from github actions did not pass ,  I thinkit is the `agent_simulator` beacuase in some cases it doesn't receive the `pending` even if  `start_up` had already been sent.

**Comment by thejbte** [comment]
I am working on test_agent_communication. The github actions test failed again, with the possible fix breaking other tests. There are some problems with agent_simulator.

**Comment by thejbte** [comment]
I am working on test_agent_communication. the test_agent_pending_status keeps failing, so I reverted the changes and will continue with another test, in the end I have to fix the agent_simulator without breaking another test.

**Comment by thejbte** [comment]
I am working on test_agent_communication. I finish the test_agents protocols and fixed test_rids.
There is a problem with agent_simulator because a different test failed.

**Comment by thejbte** [comment]
I am working on test_agent_communication. when i pushed to fix test_rids again github actions failed on test_active response.
I'm looking for a solution to agent_simulator. Also I started the test_protocol_communication.

**Comment by thejbte** [comment]
I am working on `test_agent_communication`. I added tries to agent_simulator and I fixed `mitm`,  Also I finished the `test_protocol_communication`.

**Comment by thejbte** [comment]
I am working on `test_agent_communication`. I finished the `test_request_agent_info` and `test_multi_agent_status`.

**Comment by thejbte** [comment]
I  am working on test_agent_communication. I finished the  `test_agent_pending`,` multi_agent_protocols`,` multi_agent_status`, `test_invalid_protocol_communication`, I fixed bug on `agent_simulator`

**Comment by thejbte** [comment]
I am working on test_agent_communication. I finished the `test_shared_configuration` this test passed on GitHub action but failed all test linked with API, however these test doesn't use the API, when I skip all test of `test_agent_communication` the test failed too. maybe daemon API is down. I'm research what is the problem.

**Comment by thejbte** [comment]
I am working on test_agent_communication, I finished the test, i fix the problem with API. in this moment I'm  solving the request from review.
