### ISSUE TITLE
Optimize network performance in Remoted

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#1908]
|Due date| Branch|
|---|---|
|11/27/2018|[dev-remoted-netbuffer](https://github.com/wazuh/wazuh/compare/3.9...dev-remoted-netbuffer)|

Remoted uses a dedicated thread for networking. The goal of this issue is that the bottleneck of this thread should be the network itself.

The `epoll` system call notifies when a socket is available to receive data. When operating in TCP mode, Remoted gets a notification when at less one byte is available, then it tries to receive the entire message. This may produce a delay if the message is not completely in the kernel.

## Approach

Use one buffer per socket. When `epoll` notifies that some data is available, try to get at most data as possible. Then, find complete messages and dispatch them. Store the remaining data —part of the nest message— in the buffer. The next `receive` operation may append the data in the buffer.

## Subtasks

- [x] Make a PoC for network reception.
- [x] Study the maximum memory load.
- [x] Create a toolbox to abstract this feature.
- [x] Implement this feature in Remoted. ad23ab71b
- [x] Add a receive byte count to the statistics. a664bfc72
- [x] Set up these options, if needed. 42a805a17
  - Receive chunk size.
  - Buffer deallocating.
- [x] Prevent race condition between network handler and message dispatcher. a8b71d1d1
- [x] Implement timeout in agents through the select system call. 55c7af8ff
- [x] Let the agent send the startup message on every attempt in TCP mode. 14c8ab1fd
- [x] Test feature.
- [x] Documentation.

**Comment by vikman90** [comment]
## Proof of concept

These are the results obtained with a proof of concept connecting 6 clients to a server. This code has not yet implemented in Remoted.

### Throughput measurement

|Bytes / event|Gbps|Meps|
|---|---|---|
|8|0.472|30.744|
|16|0.679|22.256|
|32|1.033|10.640|
|64|1.568|5.397|
|128|2.742|3.105|
|256|3.392|1.828|
|512|9.038|2.248|
|1024|13.712|1.667|
|2048|13.271|0.809|
|4096|13.174|0.398|
|8192|13.481|0.205|
|16384|13.273|0.101|
|32768|13.408|0.051192|
|65536|14.436|0.027560|

![throughput](https://user-images.githubusercontent.com/10536251/49009970-330f3300-f172-11e8-8201-ac37a2374d11.png)

### Performance measurement

|Bytes / event|Gbps|Meps|
|---|---|---|
|8|0.29979|3.123|
|16|0.337768|2.111|
|32|0.361868|1.256|
|64|0.388227|0.713654|
|128|0.397512|0.376432|
|256|0.409292|0.196775|
|512|0.39917|0.096699|
|1024|0.404405|0.049174|
|2048|0.409132|0.024922|
|4096|0.413214|0.012598|
|8192|0.415498|0.006337|
|16384|0.412286|0.003145|
|32768|0.410422|0.001565|
|65536|0.410107|0.000782377|

![performance](https://user-images.githubusercontent.com/10536251/49009988-41f5e580-f172-11e8-9eff-0b0a5a652a7c.png)

## Expected memory usage

### Proposed data structure

```c
typedef struct sockbuffer_t {
    char * data;
    unsigned long data_size;
    unsigned long data_len;
} sockbuffer_t;

typedef struct netbuffer_t {
    int max_fd;
    sockbuffer_t * buffers;
} netbuffer_t;
```

`netbuffer_t` is an aggregation of `sockbuffer_t`. `netbuffer_t` is 16-byte long, and `sockbuffer_t` is 24-byte long. 

We will analyze the memory usage with 14.000 connected agents. In the worst case, each buffer will take the string limit (64 KiB) plus the reception chunk (4 KiB)

_netbuffer_t + (sockbuffer_t + string_limit + reception_chunk) * max_agents = 16 + (24 + 65536 + 4096) * 14000 = 975184016 bytes = **930.008 MiB**_

**Comment by vikman90** [comment]
## New options

### Internal options

|Option|Range|Default|Description|
|---|---|---|---|
|`remoted.receive_chunk`|`1024`..`16384`|`4096`|Receiving chunk size for TCP. We suggest using powers of two.|
|`remoted.buffer_relax`|`0` and `1`|`1`|Deallocate network buffers after usage, for memory saving.|

**Comment by vikman90** [comment]
## Problem

There is a **race condition** between:
- `HandleSecure()`: Network handling thread.
- `HandleSecureMessage()`: message handler, decryptor and demultiplexer.

If the message handler rejects an agent while it is sending data or while a new agent connects using the same socket number, it may free the network buffer at the same time that the network handler is receiving data.

## Possible solutions 

### Plan A

**Do not close the connection**. Leave the connection opened when Remoted rejects a message. 

- Implementation is simple.
- We rely on the receiving timeout to let the agent retry a connection. This delay is implemented as of Wazuh 3.0.0, and the default value is 60 seconds.

Agents below v3.0.0 and agents running on Solaris 10 don't implement a timeout, so they would wait indefinitely until the manager gets disconnected or restarted.

### Plan B

Remoted should still be closing connections for rejected agents, but the network handler thread should do that. We would implement a rejection list to pass messages between the message handler and the network handler.

### Plan C

Let Remoted send a rejection message to the agent. This would unlock the agent and let it know that it was rejected.

**Comment by vikman90** [comment]
I think that the Plan A has the most advantages:

- Simple implementation.
- Same behavior in both UDP and TCP mode.
- It's according to the drop policy (just like the UDP mode implementation).

In order to deal properly with Solaris 10 —that does not support socket timeout—, we propose:
- Let Remoted drop messages from unauthorized clients.
- Implement timeout in agents through the `select` system call.

**Comment by vikman90** [comment]
## Connection and buffer filling test

|Platform|CPU|RAM memory|
|---|---|---|
|Raspberry Pi 3 Model B|4× ARM Cortex-A53, 1.2GHz|1GB LPDDR2 (900 MHz)|

### Test purpose

1. Remoted supports a large number of concurrent connections on a low resource system.
2. Assess the impact of buffering network data in the worst case.
3. Check the stability of Remoted.
4. Check that no memory leaks are produced in the new implementation.

### Testing resources

[remoted-test.py](https://github.com/wazuh/wazuh/files/2824962/remoted-test.txt)

### Test results

|Connections|Buffered data per connection|RAM usage|
|---|---|---|
|8000|32 KB|273.1 MB|
|10000|64 KB|651.5 MB|

- No stability issues.
- No memory leaks detected.

**Comment by jesusgn90** [comment]
Merged https://github.com/wazuh/wazuh-documentation/pull/905

**Comment by vikman90** [comment]
> Merged [wazuh/wazuh-documentation#905](https://github.com/wazuh/wazuh-documentation/pull/905)

@jesusgn90 Thank you.
