### ISSUE TITLE
Integrate Wazuh with OpenVPN CloudConnexa

### ISSUE THREAD

**Issue by yuriy-chapran-openvpn** [wazuh/wazuh#19098]
| Affected integration |
|---|
| AWS, CloudConnexa|

## Description
As an Administrator, I want to receive logs from OpenVPN CloudConnexa, so that I could monitor my account and take actions in the case of issues. 

## Notes
Wazuh changes are going to be introduced by OpenVPN with details on log messages and rules in the pull request.

## Tasks (to be reviewed during pull request merge)
- [ ] Test in a manager.
- [ ] Test in an agent.
- [ ] Unit tests without failures. Updated if there are any relevant changes.
- [ ] Integration tests without failures. Updated if there are any relevant changes.
- [ ] Update the documentation if necessary.
- [ ] Add entry to the changelog.
