### ISSUE TITLE
Scheduled upward merges for numbered branches - Fortnight #18

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#19121]
# Description

The goal of this is to track the completion of the following tasks so the development branches are up to date in every repository, ensuring a clean environment for our development teams.

# Tasks

### wazuh-qa -> @wazuh/qa
- https://github.com/wazuh/wazuh-qa/issues/4540
### wazuh-jenkins -> @wazuh/qa
- https://github.com/wazuh/wazuh-jenkins/issues/5678
### wazuh-automation -> @wazuh/cicd
- https://github.com/wazuh/wazuh-automation/issues/1309
### wazuh-packages -> @wazuh/core
- https://github.com/wazuh/wazuh-packages/issues/2472
### wazuh -> @wazuh/core
- https://github.com/wazuh/wazuh/issues/19120
### wazuh-ansible -> @wazuh/cicd
- https://github.com/wazuh/wazuh-ansible/issues/1040
### wazuh-docker -> @wazuh/cicd
- https://github.com/wazuh/wazuh-docker/issues/1007
### wazuh-puppet -> @wazuh/cicd
- https://github.com/wazuh/wazuh-puppet/issues/776
### wazuh-kubernetes -> @wazuh/cicd
- https://github.com/wazuh/wazuh-kubernetes/issues/463
### wazuh-kibana-app -> @wazuh/frontend
- https://github.com/wazuh/wazuh-kibana-app/issues/5914
### wazuh-documentation -> @wazuh/documentation
- https://github.com/wazuh/wazuh-documentation/issues/6539

## 2. Create AWS resources  -> @wazuh/qa

- [x] Regenerate AWS resources using the Procedure_ecs_task_tier pipeline on branches that have been modified/bumped.
  - [x] 4.6.0: https://ci.wazuh.info/job/Procedure_ecs_task_tier/51/
  - [x] 4.7.0: https://ci.wazuh.info/job/Procedure_ecs_task_tier/52/
  - [x] 4.7.1: https://ci.wazuh.info/job/Procedure_ecs_task_tier/53/
  - [x] master: https://ci.wazuh.info/job/Procedure_ecs_task_tier/54/

**Comment by juliamagan** [comment]
Known issues:
  - `test_compilation-ubuntu-20.10` failed, reported at https://github.com/wazuh/wazuh-jenkins/issues/3961
  - `framework_python-arm64v8`  failed, reported at https://github.com/wazuh/wazuh-jenkins/issues/5421
