### ISSUE TITLE
Cluster: New features

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh#1913]
- [ ] Multiple masters (https://github.com/wazuh/wazuh/issues/811)
- [ ] Rename cluster configuration: <nodes> to <master_nodes> (https://github.com/wazuh/wazuh/issues/1276)
- [ ] Synchronize custom AR scripts (https://github.com/wazuh/wazuh/issues/1305)
- [ ] Add $hostname as node name and $node_type as node type in cluster (https://github.com/wazuh/wazuh/issues/1329)
