### ISSUE TITLE
Support new stage Beta 1 for 4.6.0 in wazuh repository

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#19142]
## Description

This issue attempts to support a new stage Beta 1 for 4.6.0 in the wazuh repository.

## Tasks

- [x] Ensure changelog is updated for 4.6.0 (if applicable).
- [x] Bump revision for branch 4.6.0 on wazuh repository.
- [x] Create tag v4.6.0-beta1 from branch 4.6.0 on wazuh repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh/releases/tag/v4.6.0-beta1.
