### ISSUE TITLE
macOS agent can not be installed after an uninstallation

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh#19406]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.2 | Wazuh agent | Agent | Packages | macOS 12.01 (Monterey) Intel |

When developing the [extension of the Wazuh macOS agent endpoint using Ansible](https://github.com/wazuh/wazuh-ansible/issues/768), an issue has been found. The problem is that the macOS agent can not be installed after an uninstallation of the same agent.
- The problem has been found in macOS 12 (Monterey), but this behavior could be reproduced in other OS and in ARM architecture.
- The same behavior has been found installing other Wazuh versions, for example, `4.4.5` version.
## Steps to reproduce

To reproduce the behavior:

1. Download the macOS package.
```console
vagrant@macos-1201-testing-ansible ~ % curl -so wazuh-agent-4.5.2-1.intel64.pkg https://packages.wazuh.com/4.x/macos/wazuh-agent-4.5.2-1.intel64.pkg
```

2. Install it.
```console
sh-3.2# installer -pkg wazuh-agent-4.5.2-1.intel64.pkg -target /
installer: Package name is Wazuh Agent
installer: Installing at base path /
installer: The install was successful.
```

3. Uninstall it. Following the [related documentation](https://documentation.wazuh.com/4.4/installation-guide/wazuh-agent/wazuh-agent-package-macos.html#uninstall-a-wazuh-agent).

```console
sh-3.2# /Library/Ossec/bin/wazuh-control stop
wazuh-modulesd not running...
wazuh-logcollector not running...
wazuh-syscheckd not running...
wazuh-agentd not running...
wazuh-execd not running...
Wazuh v4.5.2 Stopped

sh-3.2# /bin/rm -r /Library/Ossec
sh-3.2# /bin/launchctl unload /Library/LaunchDaemons/com.wazuh.agent.plist
sh-3.2# /bin/rm -f /Library/LaunchDaemons/com.wazuh.agent.plist
sh-3.2# /bin/rm -rf /Library/StartupItems/WAZUH
sh-3.2# /usr/bin/dscl . -delete "/Users/wazuh"
sh-3.2# /usr/bin/dscl . -delete "/Groups/wazuh"
sh-3.2# /usr/sbin/pkgutil --forget com.wazuh.pkg.wazuh-agent
Forgot package 'com.wazuh.pkg.wazuh-agent' on '/'.
```

4. Try to install it again. The installer does not finish the installation.
```console
sh-3.2# installer -pkg wazuh-agent-4.5.2-1.intel64.pkg -target /
installer: Package name is Wazuh Agent
installer: Installing at base path /
```

In some of the tests, restarting the machine is enough to solve the problem.

## Tasks

- [ ] Investigate the problem
- [ ] Investigate a fix
- [ ] Apply the fix
- [ ] Change the documentation if the fix is not applicable and a restart is necessary to re-install the agent again.

**Comment by JorgeMarinoDev** [comment]
This is a duplicate of #18598  (**WPK Upgrade on macOS Intel failed due to timeout and the process is freeze**)

Some notes:
1. @davidcr01 mentions this was detected while development of this [extension](https://github.com/wazuh/wazuh-ansible/issues/768). (tagged 4.8.0) . This behavior is not linked to the new extension.
2. The problem has been found in macOS 12 (Monterey), but this behavior could be reproduced in other OS and in ARM architecture.
3. The same behavior has been found installing other Wazuh versions, for example, 4.4.5 version.

Conclusion: Although detected while developing a new extension, this is not related or includes any new information to the already known bug #18598 that is external and depends on macOs. As mentioned [here](https://github.com/wazuh/wazuh/issues/18598#issuecomment-1724917225)
