### ISSUE TITLE
Migrate Azure wodle to the Microsoft Graph API

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#19563]
| Affected integration | Epic |
|---|---|
| Azure | https://github.com/wazuh/wazuh/issues/19395 |

## Description

The Azure Active Directory (Azure AD) Graph is deprecated since June 30 2023 and will be replaced with Microsoft Graph.

This issue aims to develop the changes necessary to migrate to the new API.

Microsoft provides a migration [guide](https://learn.microsoft.com/en-us/graph/migrate-azure-ad-graph-overview) and explains the differences between both of them [here](https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/compare).

## Tasks
- [ ] Replace existing calls to the Azure AD Graph API with Microsoft Graph.
- [ ] Test in a manager.
- [ ] Test in an agent.
- [ ] Unit tests without failures. Updated if there are any relevant changes.

**Comment by RamosFe** [comment]
## Update

Started reading the migration guide and analyzing which changes should be made to the Azure Wodle code.

**Comment by RamosFe** [comment]
## Update

Started documenting the request made to Azure and the return schema to have a registry of which schemas are changing and where they affect the code.
