### ISSUE TITLE
Refactor Azure cloud module project structure.

### ISSUE THREAD

**Issue by EduLeon12** [wazuh/wazuh#19576]
| Affected integration | Epic |
|---|---|
| Azure | https://github.com/wazuh/wazuh/issues/19395 |

## Description

Due to the changes on the Azure directory being performed in #19395, This issue aims to refactor the current Azure wodle structure. 

The structure architecture should follow the same guidelines follow in other cloud modules such as current [AWS module](https://github.com/wazuh/wazuh/tree/master/wodles/aws) and [GCloud module](https://github.com/wazuh/wazuh/tree/master/wodles/gcloud). 

A proposal for the structure is:

```
azure/
│
├── wazuh_integration.py
│
├── utils.py
│
├── analytics/
│   └── analytics.py
│
├── graphs/
│   └── graph.py
│
├── storage/
│   └── storage.py
│
├── database/
│   ├── orm.py
│   └── db_utils.py
│
└── tests/
    ├── test_tools.py
    ├── test_analytics.py
    ├── test_graphs.py
    ├── test_storage.py
    ├── test_orm.py
    └── test_db_utils.py

```

## Tasks
- [x] Test in a manager.
- [x] Test in an agent.
- [x] Unit tests without failures. Updated if there are any relevant changes.
- [x] Integration tests without failures. Updated if there are any relevant changes.
- [x] Update the documentation if necessary.
- [x] Add entry to the changelog if necessary.

## Related issues
- [x] https://github.com/wazuh/wazuh-jenkins/issues/6068
- [x] https://github.com/wazuh/wazuh-packages/issues/2689

**Comment by nico-stefani** [comment]
# Update

I've been designing the structure

```bash
wodles/azure
├── azure.py
├── azure_utils.py
├── db
│   ├── __init__.py
│   ├── orm.py
│   └── utils.py
├── graph.py
├── log_analytics.py
├── storage.py
└── tests
    ├── data
    ├── test_azure.py
    ├── test_log_analytics.py
    ├── test_graph.py
    ├── test_storage.py
    ├── test_utils.py
    └── test_orm.py
```

* The entry point `azure-logs.py` is renamed to `azure.py`
* There are separate modules for each type of service(`log_analytics.py`, `graph.py`, `storage.py`). Because for this integration we only have functions, I don't consider it necessary to use packages.
* The `azure_utils.py` we'll contain general utilities shared with the different modules.
* Also we have a package `db` containing the `orm.py` and `utils.py` for general db functions.

**Comment by nico-stefani** [comment]
# Update

All the code was migrated to the new module's structure.

```bash
(framework) ➜  wazuh git:(19576-refactor-azure-structure) pytest --disable-warnings wodles/azure/tests/
================================================================================================ test session starts ================================================================================================
platform linux -- Python 3.9.9, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/nstefani/git/wazuh/wodles, configfile: pytest.ini
plugins: aiohttp-1.0.4, asyncio-0.18.1, tavern-1.23.5, html-3.1.1, trio-0.7.0, cov-2.12.0, metadata-2.0.4
asyncio: mode=auto
collected 148 items

wodles/azure/tests/test_azure_utils.py ...................................................                                                                                                                    [ 34%]
wodles/azure/tests/db/test_db_utils.py .........                                                                                                                                                              [ 40%]
wodles/azure/tests/db/test_orm.py ...............................                                                                                                                                             [ 61%]
wodles/azure/tests/services/test_analytics.py ..................                                                                                                                                              [ 73%]
wodles/azure/tests/services/test_graph.py ............                                                                                                                                                        [ 81%]
wodles/azure/tests/services/test_storage.py ...........................                                                                                                                                       [100%]

================================================================================================ 148 passed in 0.88s ================================================================================================
```

**Comment by nico-stefani** [comment]
# Update

After doing some tests finally, I can run the module with the new structure

<details><summary>OSSEC conf</summary>
<p>

```xml
<wodle name="azure-logs">
        <disabled>no</disabled>
        <interval>10m</interval>
        <run_on_start>yes</run_on_start>

        <graph>
            <auth_path>/var/ossec/wodles/azure/graph.credentials</auth_path>
            <tenantdomain>wazuh.onmicrosoft.com</tenantdomain>
            <request>
                <query>auditLogs/directoryaudits</query>
                <time_offset>30d</time_offset>
            </request>

            <request>
                <query>auditLogs/signIns</query>
                <time_offset>30d</time_offset>
            </request>

            <request>
                <query>auditLogs/provisioning</query>
                <time_offset>30d</time_offset>
            </request>
        </graph>

        <log_analytics>
            <auth_path>/var/ossec/wodles/azure/loganalytics.credentials</auth_path>
            <tenantdomain>wazuh.onmicrosoft.com</tenantdomain>

            <request>
                <workspace>xxx</workspace>
                <query>AuditLogs</query>
                <time_offset>30d</time_offset>
            </request>
        </log_analytics>

        <storage>
            <auth_path>/var/ossec/wodles/azure/storage.credentials</auth_path>
            <tag>azure-activity</tag>

            <container name="frameworktestcontainer">
                <time_offset>30d</time_offset>
            </container>
        </storage>
</wodle>
```

</p>
</details> 

Module output

```
root@255ad66dbaf2:/var/ossec# cat logs/ossec.log | grep wazuh-modulesd:azure-logs
2023/12/04 19:52:38 wazuh-modulesd:azure-logs[251443] wm_azure.c:54 at wm_azure_main(): INFO: Module started.
2023/12/04 19:52:38 wazuh-modulesd:azure-logs[251443] wm_azure.c:74 at wm_azure_main(): INFO: Starting fetching of logs.
2023/12/04 19:52:38 wazuh-modulesd:azure-logs[251443] wm_azure.c:85 at wm_azure_main(): INFO: Starting Graphs log collection for the domain 'wazuh.onmicrosoft.com'.
2023/12/04 19:52:38 wazuh-modulesd:azure-logs[251443] wm_azure.c:209 at wm_azure_graphs(): DEBUG: Creating argument list.
2023/12/04 19:52:38 wazuh-modulesd:azure-logs[251443] wm_azure.c:259 at wm_azure_graphs(): DEBUG: Launching command: wodles/azure/azure-logs --graph --graph_auth_path /var/ossec/wodles/azure/graph.credentials --graph_tenant_domain wazuh.onmicrosoft.com --graph_tag request_829166026 --graph_query 'auditLogs/directoryaudits' --graph_time_offset 30d --debug 2
2023/12/04 19:52:43 wazuh-modulesd:azure-logs[251443] wm_azure.c:276 at wm_azure_graphs(): INFO: Finished Graphs log collection for request 'request_829166026'.
2023/12/04 19:52:43 wazuh-modulesd:azure-logs[251443] wm_azure.c:209 at wm_azure_graphs(): DEBUG: Creating argument list.
2023/12/04 19:52:43 wazuh-modulesd:azure-logs[251443] wm_azure.c:259 at wm_azure_graphs(): DEBUG: Launching command: wodles/azure/azure-logs --graph --graph_auth_path /var/ossec/wodles/azure/graph.credentials --graph_tenant_domain wazuh.onmicrosoft.com --graph_tag request_506657365 --graph_query 'auditLogs/signIns' --graph_time_offset 30d --debug 2
2023/12/04 19:52:47 wazuh-modulesd:azure-logs[251443] wm_azure.c:276 at wm_azure_graphs(): INFO: Finished Graphs log collection for request 'request_506657365'.
2023/12/04 19:52:47 wazuh-modulesd:azure-logs[251443] wm_azure.c:209 at wm_azure_graphs(): DEBUG: Creating argument list.
2023/12/04 19:52:47 wazuh-modulesd:azure-logs[251443] wm_azure.c:259 at wm_azure_graphs(): DEBUG: Launching command: wodles/azure/azure-logs --graph --graph_auth_path /var/ossec/wodles/azure/graph.credentials --graph_tenant_domain wazuh.onmicrosoft.com --graph_tag request_528941821 --graph_query 'auditLogs/provisioning' --graph_time_offset 30d --debug 2
2023/12/04 19:52:51 wazuh-modulesd:azure-logs[251443] wm_azure.c:276 at wm_azure_graphs(): INFO: Finished Graphs log collection for request 'request_528941821'.
2023/12/04 19:52:51 wazuh-modulesd:azure-logs[251443] wm_azure.c:87 at wm_azure_main(): INFO: Finished Graphs log collection for the domain 'wazuh.onmicrosoft.com'.
2023/12/04 19:52:51 wazuh-modulesd:azure-logs[251443] wm_azure.c:81 at wm_azure_main(): INFO: Starting Log Analytics collection for the domain 'wazuh.onmicrosoft.com'.
2023/12/04 19:52:51 wazuh-modulesd:azure-logs[251443] wm_azure.c:120 at wm_azure_log_analytics(): DEBUG: Creating argument list.
2023/12/04 19:52:51 wazuh-modulesd:azure-logs[251443] wm_azure.c:172 at wm_azure_log_analytics(): DEBUG: Launching command: wodles/azure/azure-logs --log_analytics --la_auth_path /var/ossec/wodles/azure/loganalytics.credentials --la_tenant_domain wazuh.onmicrosoft.com --la_tag request_607367744 --la_query "AuditLogs" --workspace xxx --la_time_offset 30d --debug 2
2023/12/04 19:52:56 wazuh-modulesd:azure-logs[251443] wm_azure.c:189 at wm_azure_log_analytics(): INFO: Finished Log Analytics collection for request 'request_607367744'.
2023/12/04 19:52:56 wazuh-modulesd:azure-logs[251443] wm_azure.c:83 at wm_azure_main(): INFO: Finished Log Analytics collection for the domain 'wazuh.onmicrosoft.com'.
2023/12/04 19:52:56 wazuh-modulesd:azure-logs[251443] wm_azure.c:92 at wm_azure_main(): INFO: Starting Storage log collection for 'azure-activity'.
2023/12/04 19:52:56 wazuh-modulesd:azure-logs[251443] wm_azure.c:297 at wm_azure_storage(): DEBUG: Creating argument list.
2023/12/04 19:52:56 wazuh-modulesd:azure-logs[251443] wm_azure.c:364 at wm_azure_storage(): DEBUG: Launching command: wodles/azure/azure-logs --storage --storage_auth_path /var/ossec/wodles/azure/storage.credentials --container "frameworktestcontainer" --blobs "*" --storage_tag azure-activity --storage_time_offset 30d --debug 2
2023/12/04 19:52:59 wazuh-modulesd:azure-logs[251443] wm_azure.c:381 at wm_azure_storage(): INFO: Finished Storage log collection for container 'frameworktestcontainer'.
2023/12/04 19:52:59 wazuh-modulesd:azure-logs[251443] wm_azure.c:94 at wm_azure_main(): INFO: Finished Storage log collection for 'azure-activity'.
2023/12/04 19:52:59 wazuh-modulesd:azure-logs[251443] wm_azure.c:100 at wm_azure_main(): DEBUG: Fetching logs finished.
2023/12/04 19:52:59 wazuh-modulesd:azure-logs[251443] wm_azure.c:70 at wm_azure_main(): DEBUG: Sleeping until: 2023/12/04 20:02:38
```
