### ISSUE TITLE
Post release tasks for 4.5.3

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#19588]
## Description
This issue attempts to track steps necessary to complete post-release maintenance tasks for 4.5.3.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.5.3-into-4.6.0`.

## Tasks

- [x] ~Merge branch `4.5.3` into branch `4.6.0`.~
- [x] Merge branch `4.6.0` into branch `4.7.0`.
- [x] Merge branch `4.7.0` into branch `4.7.1`.
- [x] Merge branch `4.7.1` into branch `master`.
- [x] Publish GitHub release as latest.
- [x] Delete all stage pre-releases for 4.5.3 (https://github.com/wazuh/wazuh/releases).
- [x] Delete all stage tags for v4.5.3. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.5.3-rc1, 4.5.3-alpha1, etc.
- [x] Delete branch `4.5.3`.

**Comment by JcabreraC** [comment]
4.6.0 has already been populated with latest 4.5.3 changes.
