### ISSUE TITLE
Support new Wazuh version 4.9.0

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#19625]
# Description

This issue attempts to support a new version 4.9.0 in the Wazuh system. It includes tracking the generation of issues, projects, and numbered branches across all repositories.

# Tasks
Each task must be completed sequentially based on numbering. Tasks within the same subsection might be parallelized.

## 1. Open release tracking project  -> @davidjiglesias
- [x] Release 4.9.0

### wazuh-qa -> @wazuh/qa
- https://github.com/wazuh/wazuh-qa/issues/4620
### wazuh-jenkins -> @wazuh/qa
- https://github.com/wazuh/wazuh-jenkins/issues/5801
### wazuh-automation -> @wazuh/cicd
- https://github.com/wazuh/wazuh-automation/issues/1365
### wazuh-packages -> @wazuh/core
- https://github.com/wazuh/wazuh-packages/issues/2526
### wazuh -> @wazuh/core
- https://github.com/wazuh/wazuh/issues/19624
### wazuh-ansible -> @wazuh/cicd
- https://github.com/wazuh/wazuh-ansible/issues/1078
### wazuh-docker -> @wazuh/cicd
- https://github.com/wazuh/wazuh-docker/issues/1052
### wazuh-puppet -> @wazuh/cicd
- https://github.com/wazuh/wazuh-puppet/issues/799
### wazuh-kubernetes -> @wazuh/cicd
- https://github.com/wazuh/wazuh-kubernetes/issues/484
### wazuh-dashboard-plugins -> @wazuh/frontend
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6003
### wazuh-documentation -> @wazuh/documentation
- https://github.com/wazuh/wazuh-documentation/issues/6633

## 3. Create AWS resources  -> @wazuh/qa

- [x] Regenerate AWS resources using the Procedure_ecs_task_tier pipeline on branches that have been modified/bumped.
  - [x] 4.8.0 - https://ci.wazuh.info/job/Procedure_ecs_task_tier/62/
  - [x] 4.9.0 (master) - https://ci.wazuh.info/job/Procedure_ecs_task_tier/64/

## 4. Create unattended resources  -> @wazuh/cicd
- [x] Create repositories for 4.9.0 in packages-dev to support unattended installer. [Reference](https://github.com/wazuh/wazuh-jenkins/issues/5417#issuecomment-1648346363)

**Comment by Rebits** [comment]
Waiting AWS resources creation:
- **4.8.0**: https://ci.wazuh.info/job/Procedure_ecs_task_tier/62/
- **4.9.0**: https://ci.wazuh.info/job/Procedure_ecs_task_tier/63/

**Comment by davidjiglesias** [comment]
LGTM!
