### ISSUE TITLE
Support new stage Alpha 1 for 4.5.4 in wazuh repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#19735]
## Description

This issue attempts to support a new stage Alpha 1 for 4.5.4 in the wazuh repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.4 (if applicable).
- [x] Bump revision for branch 4.5.4 on wazuh repository.
- [x] Create tag v4.5.4-alpha1 from branch 4.5.4 on wazuh repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh/releases/tag/v4.5.4-alpha1.
