### ISSUE TITLE
macOS (Monterey intel64) agent can not be upgraded

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#19741]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.0-alpha1 | Wazuh agent | Agent | Packages | macOS 12.01 (Monterey) Intel |

The problem is that the macOS agent can not be upgraded using the Local and WPK upgrade method
- The problem has been found in macOS 12 (Monterey).
- It seems related to: https://github.com/wazuh/wazuh/issues/19406

## Steps to reproduce

To reproduce the behavior:

1. Download the macOS package.
```console
sh-3.2# curl -sO https://packages.wazuh.com/4.x/macos/wazuh-agent-4.5.3-1.intel64.pkg
```

2. Install it.
```console
sh-3.2# echo "WAZUH_MANAGER='x.x.x.x'" > /tmp/wazuh_envs && installer -pkg wazuh-agent-4.5.3-1.intel64.pkg -target /
installer: Package name is Wazuh Agent
installer: Installing at base path /
installer: The install was successful.
sh-3.2# /Library/Ossec/bin/wazuh-control start
Starting Wazuh v4.5.3...
Started wazuh-execd...
Started wazuh-agentd...
Started wazuh-syscheckd...
Started wazuh-logcollector...
Started wazuh-modulesd...
Completed.
```

3.A Upgrade it (Local). 

```console
sh-3.2# curl -sO https://packages-dev.wazuh.com/pre-release/macos/wazuh-agent-4.7.0-1.intel64.pkg
# installer -pkg wazuh-agent-4.7.0-1.intel64.pkg -target /
installer: Package name is Wazuh Agent
installer: Upgrading at base path /
```
The upgrade process is blocked at this point.

3.B Upgrade it (WPK). 

from the Manager

Download the package
```console
[root@wazuh-server wazuh-user]# curl -LO https://packages-dev.wazuh.com/pre-release/wpk/macos/x86_64/pkg/wazuh_agent_v4.7.0_macos_x86_64.wpk
```

Upgrade it

```shellsession
[root@wazuh-server wazuh-user]# /var/ossec/bin/agent_upgrade -a 004 -f /home/wazuh-user/wazuh_agent_v4.7.0_macos_x86_64.wpk

Upgrading...

Failed upgrades:
  Agent 004 status: Timeout reached while waiting for the response from the agent
```
The system is throwing a timeout message.

## Tasks

- [ ] Investigate the problem
- [ ] Investigate a fix
- [ ] Apply the fix
- [ ] Change the documentation if the fix is not applicable and a restart is necessary to re-install the agent again.

**Comment by mauromalara** [comment]
@pro-akim could you add the output of the `upgrade.log` file?

**Comment by TomasTurina** [comment]
Duplicated of https://github.com/wazuh/wazuh/issues/18598

This is a known issue under investigation.
