### ISSUE TITLE
Post release tasks for 4.5.4

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#19802]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.5.4.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.5.4-into-4.6.0`.

## Tasks

- [x] Merge branch `4.5.4` into branch `4.6.0`.
- [ ] Merge branch `4.6.0` into branch `4.7.0`.
- [ ] Merge branch `4.7.0` into branch `4.7.1`.
- [ ] Merge branch `4.7.1` into branch `4.8.0`.
- [ ] Merge branch `4.8.0` into branch `master`.
- [x] Publish GitHub release as latest.
- [x] Delete all stage pre-releases for 4.5.4 (https://github.com/wazuh/wazuh/releases).
- [x] Delete all stage tags for v4.5.4. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.5.4-rc1, 4.5.4-alpha1, etc.
- [x] Fast-forward definitive tag v4.5.4 to `4.5.4` branch
- [x] Delete branch `4.5.4`.
