### ISSUE TITLE
Post release tasks for 4.6.0

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#19954]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.6.0.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.6.0-into-4.7.0`.

## Tasks

- [x] https://github.com/wazuh/wazuh/pull/19980
- [x] https://github.com/wazuh/wazuh/pull/20000
- [x] https://github.com/wazuh/wazuh/pull/20005
- [ ] https://github.com/wazuh/wazuh/pull/20030
- [ ] Publish GitHub release as latest.
- [ ] Delete all stage pre-releases for 4.6.0 (https://github.com/wazuh/wazuh/releases).
- [ ] Delete all stage tags for v4.6.0. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.6.0-rc1, 4.6.0-alpha1, etc.
- [ ] Fast-forward definitive tag v4.6.0 to `4.6.0` branch
- [ ] Delete branch `4.6.0`.

**Comment by TomasTurina** [comment]
https://github.com/wazuh/wazuh/pull/19980#issuecomment-1789682988

**Comment by TomasTurina** [comment]
Blocked by https://github.com/wazuh/wazuh-qa/pull/4671 and https://github.com/wazuh/wazuh-jenkins/issues/5911
