### ISSUE TITLE
Support new stage RC 1 for 4.7.0

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#20196]
# Description

This issue attempts to support a new stage RC 1 for 4.7.0 in the Wazuh system.

# Tasks

Each task must be completed sequentially based on numbering. Tasks within the same subsection might be parallelized.

### wazuh-qa -> @wazuh/qa
- https://github.com/wazuh/wazuh-qa/issues/4689
### wazuh-jenkins -> @wazuh/qa
- https://github.com/wazuh/wazuh-jenkins/issues/5959
### wazuh-automation -> @wazuh/cicd
- https://github.com/wazuh/wazuh-automation/issues/1406
### wazuh-packages -> @wazuh/core
- https://github.com/wazuh/wazuh-packages/issues/2595
### wazuh -> @wazuh/core
- https://github.com/wazuh/wazuh/issues/20195
### wazuh-ansible -> @wazuh/cicd
- https://github.com/wazuh/wazuh-ansible/issues/1119
### wazuh-docker -> @wazuh/cicd
- https://github.com/wazuh/wazuh-docker/issues/1104
### wazuh-puppet -> @wazuh/cicd
- https://github.com/wazuh/wazuh-puppet/issues/835
### wazuh-kubernetes -> @wazuh/cicd
- https://github.com/wazuh/wazuh-kubernetes/issues/514
### wazuh-dashboard-plugins -> @wazuh/frontend
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6112
### wazuh-documentation -> @wazuh/documentation
- https://github.com/wazuh/wazuh-documentation/issues/6747

## 2. Create pre-release packages for v4.7.0-rc1 using tags from task 1. -> @wazuh/qa
- [x] https://github.com/wazuh/wazuh-jenkins/issues/5962
  -  [x] Complete https://github.com/wazuh/wazuh-jenkins/issues/5962#issuecomment-1810719507
- [x] Upload updated filebeat module
  - https://github.com/wazuh/internal-devel-requests/issues/477#issuecomment-1810411427 

## 3. Create and assign testing issues for 4.7.0 RC 1. -> @davidjiglesias
- [x] Create issues

## 4.Set up demo environment for 4.7.0 RC 1. -> @wazuh/cicd

- https://github.com/wazuh/wazuh-automation/issues/1407
