### ISSUE TITLE
SCA false positive for Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by JackThird** [wazuh/wazuh#20231]
|Wazuh version|Component|Install type|Install method|Platform|
| --- | --- | --- | --- | --- |
|4.6.0|Manager/Agent|Manager|Packages|Ubuntu server 22.04 LTS|

I'm trying to resolve SCA 'Failed' checks on a server (Ubuntu server 22.04 LTS) where I installed Wazuh agent v4.6.0 but there are a lot of false positive, for example this check:

```
File: /var/ossec/ruleset/sca/cis_ubuntu22-04.yml
Rule id: 28528
Description: 1.4.2 Ensure permissions on bootloader config are configured (Automated)
rule: c:stat /boot/grub/grub.cfg -> r:Access: (0400/-r--------) && r:Uid:\s+\(\s*\t*0/\s*\t*root\)\s*\t*Gid:\s+\t*\(\s*\t*0/\s*\t*root\)
```

The file /boot/grub/grub.cfg has this stat result:
```
  File: /boot/grub/grub.cfg
  Size: 9724      	Blocks: 24         IO Block: 4096   regular file
Device: fd00h/64768d	Inode: 1048589     Links: 1
Access: (0400/-r--------)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-11-14 11:58:47.246387448 +0100
Modify: 2023-11-14 09:54:32.718403885 +0100
Change: 2023-11-14 10:45:56.124265278 +0100
 Birth: 2022-12-02 12:41:43.744000000 +0100
```

I have same issues on other checks like:
```
28529 | Ensure authentication required for single user mode.
f:/etc/shadow -> r:^root:\$\d+
```

```
28531 | Ensure Automatic Error Reporting is not enabled.
c:systemctl is-enabled apport.service -> r:disabled
not c:systemctl is-active apport.service -> r:active
not f:/etc/default/apport -> n:enabled=(\d+) compare != 0
```

etc.

Please could you check it? Is this module reliable?

Thanks.

**Comment by JackThird** [comment]
the fix:

before
`- 'c:stat /boot/grub/grub.cfg -> r:Access: (0400/-r--------) && r:Uid:\s+\(\s*\t*0/\s*\t*root\)\s*\t*Gid:\s+\t*\(\s*\t*0/\s*\t*root\)'`

after
`- 'c:stat /boot/grub/grub.cfg -> r:Access: \(0400/-r--------\) && r:Uid:\s+\(\s*\t*0/\s*\t*root\)\s*\t*Gid:\s+\t*\(\s*\t*0/\s*\t*root\)'`

**Comment by Grayfoox** [comment]
same issue here, bumping for visibility.

**Comment by Johnng007** [comment]
Errors confirmed for 
S/N | ID
-- | --
1 | 28528
2 | 28529
3 | 28531
4 | 28534
5 | 28653

**Comment by Johnng007** [comment]
**05-04-2024**

- checking linux based SCAs for similar issues - Ongoing

**Comment by Johnng007** [comment]
- [ ] Setup Debian 10, 11 and 12 testing labs labs

**Comment by Johnng007** [comment]
update: 19/04/2024
The debian SCAs are affected by the "Ensure permissions on bootloader config are configured." check.
The debian SCAs has the check as:
```
  # 1.5.1 Ensure permissions on bootloader config are configured (Automated)
  - id: 33030
    title: "Ensure permissions on bootloader config are configured."
    description: "The grub configuration file contains information on boot settings and passwords for unlocking boot options. Notes: - This recommendation is designed around the grub bootloader, if LILO or another bootloader is in use in your environment enact equivalent settings. - Replace /boot/grub/grub.cfg with the appropriate grub configuration file for your environment."
    rationale: "Setting the permissions to read and write for root only prevents non-root users from seeing the boot parameters or changing them. Non-root users who read the boot parameters may be able to identify weaknesses in security upon boot and be able to exploit them."
    remediation: "Run the following commands to set permissions on your grub configuration: # chown root:root /boot/grub/grub.cfg # chmod og-rwx /boot/grub/grub.cfg."
    compliance:
      - cis: ["1.5.1"]
      - cis_csc_v7: ["5.1"]
      - cmmc_v2.0: ["AC.1.002", "CM.2.061", "SC.3.180"]
      - iso_27001-2013: ["A.8.1.3", "A.14.2.5"]
      - mitre_techniques: ["T1110", "T1003", "T1081", "T1097", "T1178", "T1072", "T1067", "T1495", "T1019", "T1177", "T1485", "T1486", "T1491", "T1488", "T1487", "T1490", "T1146", "T1148", "T1015", "T1133", "T1200", "T1076", "T1051", "T1176", "T1501", "T1087", "T1098", "T1139", "T1197", "T1092", "T1136", "T1011", "T1147", "T1130", "T1174", "T1053", "T1166", "T1206", "T1503", "T1214", "T1187", "T1208", "T1142", "T1075", "T1201", "T1145", "T1184", "T1537", "T1078", "T1077", "T1134", "T1017", "T1088", "T1175", "T1190", "T1210", "T1525", "T1215", "T1086", "T1055", "T1505", "T1035", "T1218", "T1169", "T1100", "T1047", "T1084", "T1028", "T1156", "T1196", "T1530", "T1089", "T1073", "T1157", "T1054", "T1070", "T1037", "T1036", "T1096", "T1034", "T1150", "T1504", "T1494", "T1489", "T1198", "T1165", "T1492", "T1080", "T1209", "T1112", "T1058", "T1173", "T1137", "T1539", "T1535", "T1506", "T1138", "T1044", "T1199"]
      - nist_sp_800-53: ["AU-2", "CM-1", "CM-2", "CM-6", "CM-7", "IA-5", "IA-6", "SC-20", "SC-21"]
      - pci_dss_v3.2.1: ["2.2"]
    condition: all
    rules:
      - 'c:stat /boot/grub/grub.cfg -> r:Access:\s*\(0400/-r--------\)\s*Uid:\s*\(\s*\t*0/\s*\t*root\)\s*\t*Gid:\s*\(\s*\t*0/\s*\t*root\)'
```

The rule associated with it is wrong because the rationale explains that the permission should be set as read write for the root user. Also this is reflected in the remediation `chown root:root /boot/grub/grub.cfg` # `chmod og-rwx /boot/grub/grub.cfg`. 
applying the remediation the stats result will then differ from the rule checked.

![image](https://github.com/wazuh/wazuh/assets/30580457/79873f51-b4f3-445d-ad36-1233afe81442)

As expected the check fails for the debian agent.
![image](https://github.com/wazuh/wazuh/assets/30580457/8d271a7e-bf4b-4ab5-abe3-fe110f8b3dd8)

The check was fixed by modifying the rule to comply with the CIS rationale and recommendation.

```
    condition: all
    rules:
      - 'c:stat /boot/grub/grub.cfg -> r:Access: \(0600/-rw-------\) && r:Uid:\s+\(\s*\t*0/\s*\t*root\)\s*\t*Gid:\s+\t*\(\s*\t*0/\s*\t*root\)'
```
And as expected after the changes the rule passed.
![image](https://github.com/wazuh/wazuh/assets/30580457/b7a9ff39-8a75-4bba-8059-f47ec95e985b)

This issue applies to Debian 10 and 11 as well.

**Comment by Johnng007** [comment]
**Update 19/04/2024**

- [ ] Issue created for Debian 12 - https://github.com/wazuh/wazuh/issues/23012
- [ ] Issue created for Ubuntu 18.04 - https://github.com/wazuh/wazuh/issues/23013
- [ ] Issue created for Ubuntu 22.04 - https://github.com/wazuh/wazuh/issues/23015

**Comment by Johnng007** [comment]
**Update 22/04/2024**

- [ ] Branch created and issue fixed for Ubuntu 20.04

**Comment by IsExec** [comment]
# Ubuntu 22.04 SCA Retesting Report
**Condition**: The new SCA (rework) was benchmarked against the previous Ubuntu 22.04 SCA.  

## Agent running on old SCA (Ubuntu 22.04 old SCA)

###  Endpoint spec

<details>
<summary>CPU</summary>

````console
root@agentb:/home/vagrant/sca_footprint# lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         39 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  2
  On-line CPU(s) list:   0,1
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    CPU family:          6
    Model:               142
    Thread(s) per core:  1
    Core(s) per socket:  2
    Socket(s):           1
    Stepping:            10
    BogoMIPS:            4223.99
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm c
                         onstant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 movbe popc
                         nt aes rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase bmi1 bmi2 invpcid rdseed clflushopt md_clear
                          flush_l1d arch_capabilities
Virtualization features:
  Hypervisor vendor:     KVM
  Virtualization type:   full
Caches (sum of all):
  L1d:                   64 KiB (2 instances)
  L1i:                   64 KiB (2 instances)
  L2:                    512 KiB (2 instances)
  L3:                    16 MiB (2 instances)
NUMA:
  NUMA node(s):          1
  NUMA node0 CPU(s):     0,1
````

</details>

<details>
<summary>RAM</summary>

````console
root@agentb:/home/vagrant/sca_footprint# free -g -h -t
               total        used        free      shared  buff/cache   available
Mem:           3.8Gi       227Mi       1.8Gi       0.0Ki       1.7Gi       3.3Gi
Swap:          2.0Gi          0B       2.0Gi
Total:         5.8Gi       227Mi       3.8Gi
````

</details>

<details>
<summary>Disk</summary>

````console
root@agentb:/home/vagrant/sca_footprint# df -h
Filesystem                         Size  Used Avail Use% Mounted on
tmpfs                              385M  968K  384M   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv   62G  5.9G   53G  10% /
tmpfs                              1.9G     0  1.9G   0% /dev/shm
tmpfs                              5.0M     0  5.0M   0% /run/lock
/dev/sda2                          2.0G  234M  1.6G  13% /boot
tmpfs                              385M  4.0K  385M   1% /run/user/1000
````
</details>


### Footprint test results
<details>
<summary>Metrics</summary>

![cpu_percent_plot](https://github.com/user-attachments/assets/f64ff6b3-632b-488c-8ad3-894ec49b88e4)
![disk_percent_plot](https://github.com/user-attachments/assets/9eaa21cf-4504-4b7a-bbe2-ca516d5bbe97)
![disk_used_(mb)_plot](https://github.com/user-attachments/assets/721cc8d3-b570-40fb-b099-627ebd0fdeff)
![memory_percent_plot](https://github.com/user-attachments/assets/8d00a70d-e83d-4283-ad45-d14c6cd07448)
![memory_used_(mb)_plot](https://github.com/user-attachments/assets/f7603ffc-d12b-4432-b73a-6a8c7db230d7)
![ProcessesCPU](https://github.com/user-attachments/assets/85a2b765-b633-41dd-a0e8-e460350a1517)
![ProcessesCPU_Change_Point](https://github.com/user-attachments/assets/1d38a99c-0171-4ca7-b1d9-7b76c906ad32)
![ProcessesCPUlegend](https://github.com/user-attachments/assets/c31a1a1f-7353-41df-a3a0-f1ce329c3fb9)
![ProcessesRAM](https://github.com/user-attachments/assets/e1ce976e-9acc-43ef-a42c-1528223df154)
![ProcessesRAM_Change_Point](https://github.com/user-attachments/assets/e67a7c67-30d9-40b6-9c3e-2848cf4b2753)
![ProcessesRAMlegend](https://github.com/user-attachments/assets/75aad03c-12e7-4144-b981-d76354d0a3ae)
![swap_percent_plot](https://github.com/user-attachments/assets/02e3b8e8-692f-4e25-9b36-b6c0825303ce)
![swap_used_(mb)_plot](https://github.com/user-attachments/assets/444180d3-400f-4251-8edb-3de07dc13431)
</details>

<details>
<summary>SCA logs</summary>

````console
root@agentb:/home/vagrant/sca_footprint# tail /var/ossec/logs/ossec.log
2024/07/22 01:37:28 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_ubuntu22-04.yml'
2024/07/22 01:37:28 sca: INFO: Security Configuration Assessment scan finished. Duration: 5 seconds.
2024/07/22 01:42:23 sca: INFO: Starting Security Configuration Assessment scan.
2024/07/22 01:42:23 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/cis_ubuntu22-04.yml'
2024/07/22 01:42:28 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_ubuntu22-04.yml'
2024/07/22 01:42:28 sca: INFO: Security Configuration Assessment scan finished. Duration: 5 seconds.
2024/07/22 01:47:30 sca: INFO: Starting Security Configuration Assessment scan.
2024/07/22 01:47:30 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/cis_ubuntu22-04.yml'
2024/07/22 01:47:35 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_ubuntu22-04.yml'
2024/07/22 01:47:35 sca: INFO: Security Configuration Assessment scan finished. Duration: 5 seconds.
````

</details>

[metrics.zip](https://github.com/user-attachments/files/16327397/metrics.zip)

## Agent running on new SCA (Ubuntu 22.04 rework)

### Endpoint spec
<details>
<summary>CPU</summary>

````console
root@agenta:/home/vagrant/sca_footprint# lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         39 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  2
  On-line CPU(s) list:   0,1
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    CPU family:          6
    Model:               142
    Thread(s) per core:  1
    Core(s) per socket:  2
    Socket(s):           1
    Stepping:            10
    BogoMIPS:            4223.99
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm c
                         onstant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 movbe popc
                         nt aes rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase bmi1 bmi2 invpcid rdseed clflushopt md_clear
                          flush_l1d arch_capabilities
Virtualization features:
  Hypervisor vendor:     KVM
  Virtualization type:   full
Caches (sum of all):
  L1d:                   64 KiB (2 instances)
  L1i:                   64 KiB (2 instances)
  L2:                    512 KiB (2 instances)
  L3:                    16 MiB (2 instances)
NUMA:
  NUMA node(s):          1
  NUMA node0 CPU(s):     0,1
````

</details>

<details>
<summary>RAM</summary>

````console
root@agenta:/home/vagrant/sca_footprint# free -g -h -t
               total        used        free      shared  buff/cache   available
Mem:           3.8Gi       225Mi       1.9Gi       0.0Ki       1.6Gi       3.3Gi
Swap:          2.0Gi          0B       2.0Gi
Total:         5.8Gi       225Mi       3.9Gi
````

</details>

<details>
<summary>Disk</summary>

````console
root@agenta:/home/vagrant/sca_footprint# df -h
Filesystem                         Size  Used Avail Use% Mounted on
tmpfs                              385M  964K  384M   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv   62G  5.8G   53G  10% /
tmpfs                              1.9G     0  1.9G   0% /dev/shm
tmpfs                              5.0M     0  5.0M   0% /run/lock
/dev/sda2                          2.0G  234M  1.6G  13% /boot
tmpfs                              385M  4.0K  385M   1% /run/user/1000
````
</details>


### Footprint test results
<details>
<summary>Metrics</summary>

![cpu_percent_plot](https://github.com/user-attachments/assets/eae3adbc-4640-474d-b669-ac4d3940909b)
![disk_percent_plot](https://github.com/user-attachments/assets/1f7be35c-7ea8-44c9-9a4a-980c02112883)
![disk_used_(mb)_plot](https://github.com/user-attachments/assets/c209eb50-74c8-4fd3-b1ab-7a02e75a436c)
![memory_percent_plot](https://github.com/user-attachments/assets/7dd0b96e-b161-4859-b808-8f48d1ec7028)
![memory_used_(mb)_plot](https://github.com/user-attachments/assets/b079876b-9bbc-4a7c-91bb-e68b6e22ddd8)
![ProcessesCPU](https://github.com/user-attachments/assets/dcc661c7-b468-48ce-9929-35b2762c5b7d)
![ProcessesCPU_Change_Point](https://github.com/user-attachments/assets/3ee01ff0-1af9-4dd5-ba68-7768e000ab13)
![ProcessesCPUlegend](https://github.com/user-attachments/assets/bb681540-b542-448a-aa20-8d592dfaec41)
![ProcessesRAM](https://github.com/user-attachments/assets/406ac925-bc4a-4292-93b2-3dbcf3c9a244)
![ProcessesRAM_Change_Point](https://github.com/user-attachments/assets/32fd0a5d-41a4-4318-ab41-237a727b39af)
![ProcessesRAMlegend](https://github.com/user-attachments/assets/431bfe6e-b5ee-4724-b597-b1c5d526495d)
![swap_percent_plot](https://github.com/user-attachments/assets/54daada0-67a1-425c-b1cf-2ad912558718)
![swap_used_(mb)_plot](https://github.com/user-attachments/assets/589462a4-968e-420b-8c3a-c85d56c29fbf)
</details>

<details>
<summary>SCA logs</summary>

````console
root@agenta:/home/vagrant/sca_footprint# tail /var/ossec/logs/ossec.log
2024/07/22 03:12:13 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_ubuntu22-04.yml'
2024/07/22 03:12:13 sca: INFO: Security Configuration Assessment scan finished. Duration: 5 seconds.
2024/07/22 03:17:08 sca: INFO: Starting Security Configuration Assessment scan.
2024/07/22 03:17:08 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/cis_ubuntu22-04.yml'
2024/07/22 03:17:13 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_ubuntu22-04.yml'
2024/07/22 03:17:13 sca: INFO: Security Configuration Assessment scan finished. Duration: 5 seconds.
2024/07/22 03:22:08 sca: INFO: Starting Security Configuration Assessment scan.
2024/07/22 03:22:08 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/cis_ubuntu22-04.yml'
2024/07/22 03:22:13 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_ubuntu22-04.yml'
2024/07/22 03:22:13 sca: INFO: Security Configuration Assessment scan finished. Duration: 5 seconds.
````

</details>

[metrics.zip](https://github.com/user-attachments/files/16327582/metrics.zip)


## Analysis


  | Benchmark   (Ubuntu 22.04 old SCA) | New SCA (Ubuntu   22.04 rework) | Difference
-- | -- | -- | --
CPU |   |   |  
`wazuh-modulesd` average   CPU percent | 1.6 | 1.5 | -0.1
Overall   average CPU percent | 6.6 | 8.65 | 2.05
Overall peak   CPU percent | 18.9 | 17.1 | -1.8
Memory |   |   |  
`wazuh-modulesd` average   memory (MB) | 0.02 | 0.01 | -0.01
Overall   average memory used (MB) | 266.33 | 224.4 | -41.93
Overall peak   memory used peak (MB) | 267.97 | 225.27 | -42.7
Disk |   |   |  
Overall   average disk used (MB) | 5939.12 | 5899.97 | -39.15
Overall peak   disk used (MB) | 5939.13 | 5899.97 | -39.16
Overall   average disk read bytes | 1229.34 | 1154.94 | -74.4
Overall peak   disk read bytes | 1229.34 | 1154.94 | -74.4
Overall   average disk write bytes | 2550.8 | 2410.46 | -140.34
Overall peak   disk write bytes | 2550.92 | 2410.57 | -140.35

**Comment by ooniagbi** [comment]
LGTM!

**Comment by ooniagbi** [comment]
Merged to 4.10.0.
