### ISSUE TITLE
Engine - Implement Schema Type Validation in Builder Operations

### ISSUE THREAD

**Issue by JavierBejMen** [wazuh/wazuh#20340]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|5.0.0 | Engine | Manager | Packages/Sources | OS version |

Epic: #16688

## Description
To improve our system's robustness and integrity, we're introducing schema-type validation for all operations. This feature will ensure that each operation conforms to our predefined schema specifications. We aim to provide build-time validation for standard operations and implement runtime checks for more complex ones, which depend on external, non-schema references. This enhancement will be integrated seamlessly, requiring no additional coding from the users.

## Tasks
- [x] Make builders wrappable, allowing for schema validation integration.
- [x] Update the schema module to include schema types instead of just JSON types.
- [x] Implement a build-time wrapper to enforce schema validation during the build phase.
- [x] Implement a runtime wrapper to ensure ongoing schema compliance for complex 
- [x] Update the schema module to obtain a runtime validator for schema fields
operations.

**Comment by JavierBejMen** [comment]
- Added stage builders:
  - normalize
  - map
  - check
  - parse
- Updated helperParser to return arguments as references or values instead of strings (TODO update tests)
- QoL
- Basic wrappers for built type and runtime type validations implemented

**Comment by JavierBejMen** [comment]
- Added runtime validator functions to schemval
- Added build time validation for references and values (In progress)
- Traces messages are returned on result only when runtime state tracing is active
- QoL on traces and exception messages

**Comment by JavierBejMen** [comment]
- Updatedoutputs and fileOutput stage builders
- Added helperParser tests
- QoL and documentation in policy and builders current files and classes

**Comment by JavierBejMen** [comment]
- QoL on validation functionality
- Added arrays validation
- Updated helpers:
  - exists, not_exists
  - starts_with
  - array_append
 - Working on string cmp helpers

**Comment by JcabreraC** [comment]
ETA expanded. Some technical debt related to this module was more extensive than estimated.

**Comment by JavierBejMen** [comment]
- Updated basic filter and map helpers
- Updated kvdb helpers
- Updated builder validate integration functionality
- Updated HLP helpers

**Comment by JavierBejMen** [comment]
- Fixed decoders and minor bugs
