### ISSUE TITLE
Support new Wazuh version 4.8.1

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#20369]
# Description

This issue attempts to support a new version 4.8.1 in the Wazuh system. It includes tracking the generation of issues, projects, and numbered branches across all repositories.

# Tasks
Each task must be completed sequentially based on numbering. Tasks within the same subsection might be parallelized.

## 1. Open release tracking project  -> @davidjiglesias
- [x] Release 4.8.1 https://github.com/orgs/wazuh/projects/74

### wazuh-qa -> @wazuh/qa
- https://github.com/wazuh/wazuh-qa/issues/4704
### wazuh-jenkins -> @wazuh/qa
- https://github.com/wazuh/wazuh-jenkins/issues/5973
### wazuh-automation -> @wazuh/cicd
- https://github.com/wazuh/wazuh-automation/issues/1418
### wazuh-packages -> @wazuh/core
- https://github.com/wazuh/wazuh-packages/issues/2623
### wazuh -> @wazuh/core
- https://github.com/wazuh/wazuh/issues/20368
### wazuh-ansible -> @wazuh/cicd
- https://github.com/wazuh/wazuh-ansible/issues/1134
### wazuh-docker -> @wazuh/cicd
- https://github.com/wazuh/wazuh-docker/issues/1126
### wazuh-puppet -> @wazuh/cicd
- https://github.com/wazuh/wazuh-puppet/issues/845
### wazuh-kubernetes -> @wazuh/cicd
- https://github.com/wazuh/wazuh-kubernetes/issues/522
### wazuh-dashboard-plugins -> @wazuh/frontend
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6139
### wazuh-documentation -> @wazuh/documentation
- https://github.com/wazuh/wazuh-documentation/issues/6777

## 3. Create AWS resources  -> @wazuh/qa

- [x] All AWS resources should be regenerated using the Procedure_ecs_task_tier pipeline on branches that have been modified/bumped.
  - [x] 4.8.1 https://ci.wazuh.info/job/Procedure_ecs_task_tier/87/
