### ISSUE TITLE
Post release tasks for 4.7.0

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#20432]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.7.0.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.7.0-into-4.7.1`.

## Tasks

- [x] Merge branch `4.7.0` into branch `4.7.1`.
- https://github.com/wazuh/wazuh/pull/20449
- #20483
- https://github.com/wazuh/wazuh/pull/20495
- #20514
- [x] Publish GitHub release as latest.
- [x] Delete all stage pre-releases for 4.7.0 (https://github.com/wazuh/wazuh/releases).
- [x] Delete all stage tags for v4.7.0. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.7.0-rc1, 4.7.0-alpha1, etc.
- [x] Fast-forward definitive tag v4.7.0 to `4.7.0` branch
- [x] Delete branch `4.7.0`.

**Comment by vikman90** [comment]
4.7.0 → 4.7.1 already merged

```
*   60744ec686 (HEAD -> merge-4.7.0-into-4.7.1, origin/4.7.1, 4.7.1) Merge pull request #20415 from wazuh/merge-4.7.0-into-4.7.1
|\
| * d71ac8700b Merge branch '4.7.0' into '4.7.1'
|/|
| *   eb29da47d7 (tag: v4.7.0-rc2, tag: v4.7.0, origin/4.7.0, 4.7.0) Merge pull request #20385 from wazuh/change/20383-changelog-4.7.0
```
