### ISSUE TITLE
Primary key miss from the item id calculation for syscollector packages

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#20499]
## Description

It was found that after the changes in #17052, the way **syscollector** calculates the item ID for the packages table was modified.
This affects the way DBSync/RSync synces the DBs and this change must be reverted.

To be more specific, the file `src/wazuh_modules/syscollector/src/syscollectorImp.cpp` should have the `version` field again in `PACKAGES_ITEM_ID_FIELDS`.

## DoD

- [x] Revert the requested changes
- [x] Perform some manual tests to verify the correct behavior
- [x] Add UTs if required
- [x] CI Pass

## SubTask.

- [x] Development, manual tests. ETA -> 01/12/2023 
- [x] Testing/Review. ETA -> 01/12/2023
