### ISSUE TITLE
Implement dynamic labels parser

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#2053]
|Main task|Component|
|---|---|
|#1004|Analysisd|

Implement a language and a parser to model the dynamic labels configuration. These settings will be in the manager and the cluster will synchronize them. We need that this language lets configure filters for agent id and name. It should also allow defining which data the manager should produce for each agent.

## Proposed language

```yaml
dynamic_labels:
  - agent_id: ['000', '001', '002']
    keys:
      - os.name
      - os.version
      - ipv4.primary
  - agent_name: ^server-
    keys: [ipv4.primary, ipv4.netmask, ipv6.primary]
```

## Roadmap

- [x] Parse the configuration file.
- [ ] Replace the agent_name for the agent_id to introduce it in the Hash table
- [x] Unify all the keys for the same agent when it is specified in some configuration blocks.
- [x] Add the information to the Hash table
