### ISSUE TITLE
Implement dynamic label composer in Analysisd

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#2054]
|Main task|Component|
|---|---|
|#1004|Analysisd|

Issue #1004 described the task to implement dynamic agent labels. In this case, the label values come from Syscollector.

The writer component in Analysisd will call a procedure to enrich the alerts with dynamic labels. This subtask consists on implementing such procedure.

## Subtasks

- [x] View the information in the _alerts.log_.
- [x] View the information in the _alerts.json_.
- [x] View the information in the _archives.json_.
- [x] View the information in Kibana.
- [x] View the information in Splunk.

**Comment by Skeptor** [comment]
The task is complete.
The `archives.log` isn't marked as check cause this information doesn't have to appear in the `archives.log`
The commit where the structure is created and the dynamic label is composed is this one: https://github.com/wazuh/wazuh/commit/ad42e55f16fa4f6ea5fee5410da451cdf2d37368
