### ISSUE TITLE
Missing `version` information on Windows

### ISSUE THREAD

**Issue by GabrielEValenzuela** [wazuh/wazuh#20592]
## Description
Currently, on Windows systems, the version information is not being reported. This absence hinders proper system identification and version tracking. The proposed solution is to include the full human-readable kernel version as a substitute for the missing version information.

### User Story 1: Identify Missing Version Information
**As a** developer,
**I want** to identify and confirm the absence of version information on Windows systems,
**So that** I can address the issue accurately.

### User Story 2: Include Full Human-Readable Kernel Version
**As a** developer,
**I want** to implement a solution that includes the full human-readable kernel version,
**So that** proper system identification and version tracking can be maintained on Windows.

## DoD
- [ ] Confirm that version information is indeed missing on Windows systems.
- [ ] Implement the fix in the codebase.

## Subtasks
- [ ] Development ->TBD
- [ ] Tests/review -> TBD

**Comment by Darioortegaleyva** [comment]
## Verification

Verified on a real Windows 11 host (build 26200.8875, 25H2) by running the actual 5.0 OS-info code path (`SysOsInfoProviderWindows` + `SysOsInfo::setOsInfo`).

The `version` field (`host.os.kernel.version`) is not emitted on Windows (the key is absent from the `osinfo` output):

```sql
os_kernel_version (host.os.kernel.version): <absent>
```

On Linux/macOS this field comes from `uname` (the human-readable kernel banner, e.g. `#1 SMP Fri Mar 29 ...`). Windows has no native equivalent, so there is no real source to populate it without synthesizing a value.

This is the same rationale used to close the sibling `sysname` issue (#20596), and changing these OS kernel fields also impacts Vulnerability Detector (#24392).

Proposing to close, in line with #20596.
