### ISSUE TITLE
`os_version` information incomplete on Solaris

### ISSUE THREAD

**Issue by GabrielEValenzuela** [wazuh/wazuh#20595]
## Description
On Solaris systems, the `os_version` field in the version (kernel version) information is incomplete, hindering accurate system identification. The proposed solution is to include the full human-readable kernel version in the `os_version` field.

The following table makes a summary of the fields and their meaning:

| Field name   | Description |
|--------------|-------------|
| **scand_id** |   Identifier for the last syscollector scan  |
| **scan_time** |   Scan date (YYYY/MM/DD HH:mm:ss)  |
| **hostname** |   Hostname of the machine  |
| **architecture** |   Architecture of the machine  |
| **os_name** |   OS name of the machine  |
| **os_version** |   OS version of the machine  |
| **os_codename** |   OS version codename of the machine (macOS)  |
| **os_major** |   Major release version  |
| **os_minor** |   Minor release version  |
| **os_patch** |   Patch release version  |
| **os_build** |   Optional build-specific  |
| **os_release** |   Release ID (Windows)  |
| **os_display_version** |   Display version (Windows)  |
| **os_platform** |   OS platform of the machine  |
| **sysname** |   Kernel System name  |
| **release** |   Kernel Release name  |
| **version** |   Kernel Release version (human-readable)  |
| **checksum** |   Integrity synchronization value  |
| **item_id** |   Unified primary key  |

### User Story 1: Identify Incomplete OS Version Information
**As a** developer,
**I want** to identify and confirm the incompleteness of the `os_version` field on Solaris systems,
**So that** I can address the issue accurately.

### User Story 2: Include Full Human-Readable Kernel Version in os_version
**As a** developer,
**I want** to implement a solution that includes the full human-readable kernel version in the `os_version` field,
**So that** accurate system identification can be maintained on Solaris.

## DoD
- [ ] Confirm that version information is indeed missing on Solaris systems.
- [ ] Implement the fix in the codebase.

## Subtasks
- [ ] Development ->TBD
- [ ] Tests/review -> TBD
