### ISSUE TITLE
Missing `release` information on Windows

### ISSUE THREAD

**Issue by GabrielEValenzuela** [wazuh/wazuh#20591]
## Description
Currently, on Windows systems, the release information is not being reported. This absence hinders proper system identification and version tracking. The proposed solution is to use the kernel version with the format `NT-VERSION` as a substitute for the missing release information.

### User Story 1: Identify Missing Release Information
**As a** developer,
**I want** to identify and confirm the absence of release information on Windows systems,
**So that** I can address the issue accurately.

### User Story 2: Substitute Release Information with Kernel Version
**As a** developer,
**I want** to implement a solution that substitutes the missing release information with the kernel version in the format `NT-VERSION`,
**So that** proper system identification and version tracking can be maintained on Windows.

## DoD
- [ ] Confirm that release information is indeed missing on Windows systems.
- [ ] Implement the fix in the codebase.

## Subtasks
- [ ] Development ->TBD
- [ ] Tests/review -> TBD

**Comment by Darioortegaleyva** [comment]
## Verification

Verified on a real Windows 11 host (build 26200.8875, 25H2) by running the actual 5.0 OS-info code path (`SysOsInfoProviderWindows` + `SysOsInfo::setOsInfo`, the same functions the agent uses in `SysInfo::getOsInfo()`).

Emitted `osinfo` JSON:

```sql
{
  "architecture": "x86_64",
  "hostname": "ZENBOOK",
  "os_build": "26200.8875",
  "os_distribution_release": "2009",
  "os_full": "25H2",
  "os_kernel_release": "10.0.26200.8875",
  "os_major": "10",
  "os_minor": "0",
  "os_name": "Microsoft Windows 11 Home",
  "os_platform": "windows",
  "os_type": "windows",
  "os_version": "10.0.26200.8875"
}
```

The `release` field (`host.os.kernel.release`) is already populated with the kernel version on Windows (`10.0.26200.8875`). This was implemented for 5.0 (kernel version included in the release field for Windows).

The originally proposed `NT-VERSION` format was not adopted; the plain kernel version string is reported instead.

Nothing left to do here. Proposing to close as already resolved in 5.0.

**Comment by MarcelKemp** [comment]
LGTM.
