### ISSUE TITLE
Review and create new AWS S3 services events

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#20697]
| Affected integration |
|---|
| AWS |

## Description
In #20623, the AWS Macie rules from `ruleset/rules/0350-amazon_rules.xml` are being reviewed since these do not generate the proper description when alerts are triggered. The main reason is the format difference between some of the fetched AWS Macie events. For example, in the following events, it can be noted that the `severity` level is found inside different keys, among other differences:
<details><summary>Critical severity event</summary>

```json
{
    "integration": "aws",
    "aws": {
        "log_info": {
            "aws_account_alias": "",
            "log_file": "2021/01/01/00/firehose_macie-1-2021-01-01-00-20-42-eb1f80bc-5d9d-426b-a0a1-e0ad8d3ef656",
            "s3bucket": "test-aws-wodle-macie"
        },
        "notification-type": "ALERT_CREATED",
        "tags": {
            "value": [
                "Open Permissions",
                "Basic Alert"
            ]
        },
        "name": "S3 Bucket IAM policy grants global read rights",
        "severity": "CRITICAL",
        "url": "https://mt.region.macie.aws.amazon.com/posts/arn%3Aaws%3Amacie%3Aregion%3AACCOUNT-ID%3Atrigger%2Fb731d9ffb1fe61508d4a478c92efa666%2Falert%2F8f8845fe3b28f25fb13b0d074044f3fc",
        "alert-arn": "arn:aws:macie:region:ACCOUNT-ID:trigger/b731d9ffb1fe61508d4a478c92efa666/alert/8f8845fe3b28f25fb13b0d074044f3fc",
        "risk-score": 9,
        "created-at": "2021-01-01T00:20:42.364509",
        "actor": "resources.test.com",
        "summary": {
            "Description": "S3 Bucket uses IAM policy to grant read rights to Everyone. Your IAM policy contains a clause that effectively grants read access to any user. Please audit this bucket, and data contained within and confirm that this is intentional. If intentional, please use the alert whitelist feature to prevent future alerts",
            "Bucket": [
                "resources.test.com"
            ],
            "Record Count": 1,
            "ACL": {
                "resources.test.com": {
                    "Owner": {
                        "DisplayName": "test",
                        "ID": "3ab1235e25ea9e94ff9b7e4e379ba6b0c872cd36c096e1ac8cce7df433b47101"
                    },
                    "Grants": [
                        {
                            "Grantee": {
                                "Type": "CanonicalUser",
                                "DisplayName": "test",
                                "ID": "3ab1235e25ea9e94ff9b7e4e379ba6b0c872cd36c096e1ac8cce7df433b47101"
                            },
                            "Permission": "FULL_CONTROL"
                        },
                        {
                            "Grantee": {
                                "Type": "Group",
                                "URI": "http://acs.amazonaws.com/groups/global/AllUsers"
                            },
                            "Permission": "READ"
                        }
                    ]
                }
            },
            "Event Count": 1,
            "Timestamps": [
                "2021-01-01T00:11:49.171020Z"
            ],
            "recipientAccountId": [
                "ACCOUNT-ID"
            ]
        },
        "source": "macie"
    }
}
```

</details>
<details><summary>High severity event</summary>

```json
{
    "integration": "aws",
    "aws": {
        "log_info": {
            "aws_account_alias": "",
            "log_file": "2021/05/04/00/firehose_macie-1-2021-12-01-00-40-40-e269348f-0b8e-4f61-a4e9-995424ftest1",
            "s3bucket": "wazuh-aws-wodle-macie"
        },
        "schemaVersion": "1.0",
        "id": "4fe51676-xxxxxxxxxxxx",
        "accountId": "5555564",
        "partition": "aws",
        "region": "us-east-1",
        "type": "Policy:IAMUser/S3BucketSharedEx",
        "title": "The S3 bucket is shared with an external AWS account.",
        "description": "The access control list (ACL) or bucket policy for the Amazon S3 bucket allows the bucket to be shared with an AWS account that isn\u2019t part of your Amazon Macie organization.",
        "severity": {
            "score": 3,
            "description": "High"
        },
        "createdAt": "2021-03-12T18:47:20.834Z",
        "updatedAt": "2021-04-22T21:10:17.764Z",
        "count": 59,
        "resourcesAffected": {
            "s3Bucket": {
                "arn": "arn:aws:s3:::em-xxxx-app-us-east-1-ss",
                "name": "em-xxxxxx-app-us-east-1-qa",
                "createdAt": "2018-04-05T23:53:47.000Z",
                "owner": {
                    "displayName": "em-aws-xxxx",
                    "id": "79xxxxxxxx"
                },
                "tags": [],
                "defaultServerSideEncryption": {
                    "encryptionType": "NONE"
                },
                "publicAccess": {
                    "permissionConfiguration": {
                        "bucketLevelPermissions": {
                            "accessControlList": {
                                "allowsPublicReadAccess": false,
                                "allowsPublicWriteAccess": false
                            },
                            "bucketPolicy": {
                                "allowsPublicReadAccess": true,
                                "allowsPublicWriteAccess": false
                            },
                            "blockPublicAccess": {
                                "ignorePublicAcls": false,
                                "restrictPublicBuckets": false,
                                "blockPublicAcls": false,
                                "blockPublicPolicy": false
                            }
                        },
                        "accountLevelPermissions": {
                            "blockPublicAccess": {
                                "ignorePublicAcls": false,
                                "restrictPublicBuckets": false,
                                "blockPublicAcls": false,
                                "blockPublicPolicy": false
                            }
                        }
                    },
                    "effectivePermission": "PUBLIC"
                },
                "allowsUnencryptedObjectUploads": "TRUE"
            }
        },
        "category": "POLICY",
        "policyDetails": {
            "action": {
                "actionType": "AWS_API_CALL",
                "apiCallDetails": {
                    "api": "PutBucketPolicy",
                    "apiServiceName": "s3.amazonaws.com",
                    "firstSeen": "2021-03-12T18:31:09.000Z",
                    "lastSeen": "2021-04-22T21:01:18.000Z"
                }
            },
            "actor": {
                "userIdentity": {
                    "type": "IAMUser",
                    "iamUser": {
                        "principalId": "AIxxxxxxxxxxx",
                        "arn": "arn:aws:iam::180000000:user/bots/svc_ccteam_jenkins",
                        "accountId": "180000000000",
                        "userName": "svc_cxxx"
                    }
                },
                "ipAddressDetails": {
                    "ipAddressV4": "144.5.12.0",
                    "ipOwner": {
                        "asn": "5000",
                        "asnOrg": "00",
                        "isp": "xxxxx",
                        "org": "xxxx"
                    },
                    "ipCountry": {
                        "code": "xx",
                        "name": "xxx xxx"
                    },
                    "ipCity": {
                        "name": "xxxx"
                    },
                    "ipGeoLocation": {
                        "lat": 0.0,
                        "lon": -0.0
                    }
                }
            }
        },
        "sample": false,
        "archived": false,
        "source": "macie"
    }
}
```

</details>

We should review the stored events by the oldest [supported AWS Services](https://documentation.wazuh.com/current/cloud-security/amazon/services/supported-services/index.html) since AWS Macie might not be the only case, create new events, remove the outdated ones from our dev environment, and modify the associated rules and logic (if needed) to keep the module up to date.

## Tasks
- [ ] Test in a manager (AWS Integration Tests).
- [ ] Test in an agent.
- [ ] Unit tests without failures. Updated if there are any relevant changes.
- [ ] Integration tests without failures. Updated if there are any relevant changes.
- [ ] Update the documentation if necessary.
- [ ] Add entry to the changelog if necessary.

**Comment by issabayevmk** [comment]
Hi @fdalmaup. Can you please assign this issue to me. I would like to contribute. I have experience with creating rules for AWS. I created a number of rules in Panther SIEM.
