### ISSUE TITLE
Add Connexion 3.0 and Uvicorn support in Wazuh-API

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh#20748]
|Wazuh version|Component|Epic branch|
|---|---|--|
| 4.9 | API |[epic/20748-upgrade-to-connexion-3](https://github.com/wazuh/wazuh/tree/epic/20748-upgrade-to-connexion-3)|

## Description
The objective of this EPIC is to add support for the Connexion package 3.0 and the Uvicorn ASGI server.

### Steps for the upgrade:
- Migrate the current version of Connexion 2.0 to version 3.0 with minimum impact on the current functionality.
- Define the Python packages that the upgrade will include and remove.
- Create a new version of Wazuh packages, including the defined Python packages.
- Perform unit, integration, and system tests.
- Perform performance tests.
- Update documentation if needed.

#### Stage 1
- [x] #16504 
- [x] #21651
- [x] #21935
- [x] #20245
- [x] https://github.com/wazuh/wazuh/issues/22735
- [x] https://github.com/wazuh/wazuh/issues/22742
- [x] https://github.com/wazuh/wazuh/issues/22743
- [x] https://github.com/wazuh/wazuh/issues/22744
- [x] https://github.com/wazuh/wazuh/issues/22962
- [x] https://github.com/wazuh/wazuh/issues/22846
- [x] https://github.com/wazuh/wazuh/issues/22890
- [x] https://github.com/wazuh/wazuh/issues/22951
- [x] #22329
- [x] https://github.com/wazuh/wazuh/issues/22372
- [x] https://github.com/wazuh/wazuh/issues/22478
- [x] https://github.com/wazuh/wazuh/issues/21228
- [x] https://github.com/wazuh/wazuh/issues/23219

#### Stage 2
- [x] #22131
- [x] https://github.com/wazuh/wazuh/issues/22427

#### Stage 3
- [x] #20795
- [x] #20602
- [x] https://github.com/wazuh/wazuh/issues/23136

#### Final fixes
- [x] https://github.com/wazuh/wazuh/issues/23525
- [x] https://github.com/wazuh/wazuh/issues/23389
- [x] https://github.com/wazuh/wazuh/issues/23728
