### ISSUE TITLE
Vulnerability detector refactor performance tests

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#20776]
## Description

This issue outlines the steps to perform scalability and performance tests on the vulnerability detector module that is being refactored in https://github.com/wazuh/wazuh/issues/14153.

The testing should include:

- A deployment with indexer nodes.
- Benchmarking 4.7.x to compare the performance with the module before the refactor.
- Environment and processes footprints during the tests including CPU, RAM and file descriptors.
- Workload benchmark metrics executions with 10 workers and 10,000 agents, and 25 workers and 50,000 agents.

## Related issues

- [x] https://github.com/wazuh/wazuh/issues/20777
- [x] https://github.com/wazuh/wazuh/issues/20779
- [x] https://github.com/wazuh/wazuh-qa/issues/4781
- [x] https://github.com/wazuh/wazuh-qa/issues/4890
- [x] https://github.com/wazuh/wazuh-jenkins/issues/6182
- [x] https://github.com/wazuh/wazuh-jenkins/issues/6080
- [x] https://github.com/wazuh/wazuh-jenkins/issues/6207
- [x] https://github.com/wazuh/wazuh-jenkins/issues/6208
- [x] https://github.com/wazuh/wazuh/issues/20781

**Comment by santipadilla** [comment]
LGTM
