### ISSUE TITLE
Migrate and adapt HAProxy helper to run in the manager

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#20887]
| Epic branch |
|--|
|[epic-20887-migrate-haproxy-helper](https://github.com/wazuh/wazuh/tree/epic-20887-migrate-haproxy-helper)|

## Description

Some months ago, a tool was developed to improve how agents are distributed in a Wazuh cluster. This tool communicates with both the master node API and a HAProxy balancer to perform these two main tasks:
- Balance TCP sessions through agent reconnections so that all managers serve a similar number of clients.
- Add or remove managers from the HAProxy backend automatically.

Now it has been decided that, for maintenance reasons, the tool should be included in the manager. More specifically, in the framework's cluster folder. 

## Issues
- [x] https://github.com/wazuh/wazuh-tools/issues/268
- [x] https://github.com/wazuh/wazuh/issues/20937
- [x] https://github.com/wazuh/wazuh/issues/20938
- [x] https://github.com/wazuh/wazuh/issues/20936
- [x] https://github.com/wazuh/wazuh/issues/21552
- [x] https://github.com/wazuh/wazuh/issues/20939
- [x] https://github.com/wazuh/wazuh/issues/20940
- [x] https://github.com/wazuh/wazuh/issues/22905
- [x] https://github.com/wazuh/wazuh/issues/20941
- [x] https://github.com/wazuh/wazuh-jenkins/issues/6395
- [x] #23471
- [x] #23531

**Comment by nico-stefani** [comment]
# Update

I've been internalizing the coordinator code and setting up the project.

**Comment by nico-stefani** [comment]
# Update

I've been reading about the HAProxy architecture that currently we have.
