### ISSUE TITLE
Convert `HAProxy helper` configuration to XML and integrate it in ossec.conf

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#20939]
| Epic | 
|--|
|https://github.com/wazuh/wazuh/issues/20887|

## Description

We need to integrate the `HAProxy helper` configuration in the `ossec.conf`. This is the proposal:
```XML
<cluster>
    <name>wazuh</name>
    <node_name>master-node</node_name>
    <key>c98b62a9b6169ac5f67dae55ae4a9088</key>
    <node_type>master</node_type>
    <port>1516</port>
    <bind_addr>0.0.0.0</bind_addr>
    <nodes>
        <node>master</node>
    </nodes>
    <hidden>no</hidden>
    <disabled>no</disabled>

    <haproxy_helper>
      <disabled>yes</disabled>
      <frequency>60</frequency>
      <haproxy_address></haproxy_address>
      <haproxy_port></haproxy_port>
      <haproxy_user></haproxy_user>
      <haproxy_password></haproxy_password>
      <excluded_nodes>
        <node>master</node>
      </excluded_nodes>
      <agent_chunk_size>100</agent_chunk_size>
      <agent_reconnection_time>5</agent_reconnection_time>
      <imbalance_tolerance>10</imbalance_tolerance>
      <remove_disconnected_node_after>60</remove_disconnected_node_after>
    </haproxy_helper>
</cluster>
```

## Tasks
- [ ] Adapt core to accept the new options.
- [ ] Do not include these new options in the default configuration (in other words, a newly installed manager should not contain haproxy_helper configuration block). _This decision may change in the future_.
- [ ] Adapt the `HAProxy helper` to read and use the configuration from `ossec.conf`.
- [ ] Do manual tests by starting and stopping the manager (`service wazuh-manager restart`) with different combinations of cluster and haproxy_helper configuration. Report the results.
- [ ] If necessary after what was seen in the previous step, adapt the `wazuh-control` script (`/var/ossec/bin/wazuh-control`, [link](https://github.com/wazuh/wazuh/blob/master/src/init/wazuh-server.sh)).

**Comment by Selutario** [comment]
Something related was made here:
- https://github.com/wazuh/wazuh/issues/14293

**Comment by nico-stefani** [comment]
# Update

I've added the new validations in the `cluster-config.c` to parse the `ossec.conf` with the new parameters.

**Comment by nico-stefani** [comment]
# Update

I've been improving the validations in  `cluster-config.c` and getting the configurations from the `ossec.conf` on the helper side.

I got an error building the server even in 4.9, so I can't start testing yet.

```bash
make[2]: Entering directory '/wazuh/src/external/libarchive'
  CC       tar/bsdtar-bsdtar.o
  CC       tar/bsdtar-cmdline.o
  CC       tar/bsdtar-creation_set.o
  CC       tar/bsdtar-read.o
  CC       tar/bsdtar-subst.o
  CC       tar/bsdtar-util.o
  CC       tar/bsdtar-write.o
tar/write.c:37:10: fatal error: attr/xattr.h: No such file or directory
   37 | #include <attr/xattr.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:8174: tar/bsdtar-write.o] Error 1
make[2]: Leaving directory '/wazuh/src/external/libarchive'
make[1]: *** [Makefile:4031: all] Error 2
make[1]: Leaving directory '/wazuh/src/external/libarchive'
make: *** [Makefile:1185: external/libarchive/.libs/libarchive.a] Error 2
make: Leaving directory '/wazuh/src'
root@e07f0e0cae4a:/wazuh# git status
On branch 4.9.0
Your branch is up to date with 'origin/4.9.0'.
```

**Comment by nico-stefani** [comment]
# Update

I was able to build Wazuh with the introduced changes correctly. I need to continue working on better validations for the new fields.

**Comment by nico-stefani** [comment]
# Update

I've been working on the content validations and default values.

**Comment by nico-stefani** [comment]
# Update

I started the helper reading the configuration from the `ossec.conf`. 
I found a problem in the C parser that I must review and fix. Also, I need to check if the configuration API endpoint works correctly.
