### ISSUE TITLE
Integrate Wrapper API in the `HAProxy helper` or remove it

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#20936]
| Epic | 
|--|
|https://github.com/wazuh/wazuh/issues/20887|

## Description
As it was described in https://github.com/wazuh/wazuh/issues/20887, we are migrating the HAProxy helper (old coordinator) to the manager (`wazuh` repository). This is the current shape of the `HAProxy helper` - `HAProxy balancer` architecture:

![image](https://github.com/wazuh/wazuh/assets/23361101/6bcc1986-825c-4a2c-8be7-85b786c09813)

We need to review the `Wrapper API` code and integrate it inside the `HAProxy helper` (coordinator), or simply refactor the HAProxy Helper to skip it. This way, it will communicate with the Dataplane API straight forward. 

> [!IMPORTANT]
> The execution of this issue will depend on the results of the investigation done in https://github.com/wazuh/wazuh-tools/issues/268.

## Tasks
- [x] Review Wrapper API code
- [x] Review Coordinator code used to communicate with the Wrapper API
- [x] Refactor the Coordinator to work without the Wrapper API (communicating with Dataplane API instead)
- [x] Do basic testing to make sure that everything keeps working after this.

**Comment by nico-stefani** [comment]
# Update

I've been working in:
* Creating an environment without the WrapperAPI
* Migrating all the requests to the Dataplane API and removing the deprecated ones from the WrapperAPI

**Comment by nico-stefani** [comment]
# Update

I've been doing tests with the parameter `hard-stop-after` and seeing how the helper behaves.
Also, developing functionalities to obtain and validate the configuration from the proxy.

**Comment by nico-stefani** [comment]
# Update

I've been integrating the `hard-stop-afer` into the flow of the helper.

**Comment by nico-stefani** [comment]
# Update

I've been working on the functionality to update the configuration when the proxy didn't have the `hard-stop-after` on it.

**Comment by nico-stefani** [comment]
# Update

I having some trouble to reconnect agents aftert set the `hard-stop-after` in order to keep only once HAProxy process.

```python
2024/03/14 19:25:49 ERROR: [Local 948921] [Main] Internal error processing request 'b'dapi_fwd'': Error 3022 - Unknown node ID
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/common.py", line 819, in dispatch
    command, payload = self.process_request(command, payload)
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/local_server.py", line 269, in process_request
    raise WazuhClusterError(3022)
wazuh.core.exception.WazuhClusterError: Error 3022 - Unknown node ID
2024/03/14 19:25:49 ERROR: [Local 234451] [Main] Internal error processing request 'b'dapi_fwd'': Error 3022 - Unknown node ID
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/common.py", line 819, in dispatch
    command, payload = self.process_request(command, payload)
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/local_server.py", line 269, in process_request
    raise WazuhClusterError(3022)
wazuh.core.exception.WazuhClusterError: Error 3022 - Unknown node ID
```

I will continue investigating.

**Comment by nico-stefani** [comment]
# Update

I've been doing some manual testing to validate the correct behavior of the helper.

<details><summary> :green_circle: Check 0: Set the `hard-stop-after` for the first time.</summary>
<p>

This time, the environment has only three nodes: master, worker0 and worker1 and 4 agents each without the `hard-stop-after` setted.

Before agents connections:

![image](https://github.com/wazuh/wazuh/assets/7127104/b57a5f1c-3c15-4ec3-a02b-6ea568144cff)

```bash
➜  wazuh-coordinator-dev git:(dev-wazuh-coordinator) ✗ docker-compose exec wazuh-proxy ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0   4364  3072 ?        SNs  18:21   0:00 bash /scripts/entrypoint.sh wazuh-maste
syslog        19  0.0  0.0 292076  3404 ?        SNsl 18:21   0:00 rsyslogd
root          56  0.2  0.3 1263412 79168 ?       SNl  18:21   0:00 dataplaneapi -f /etc/haproxy/dataplanea
root          57  0.0  0.0   2824  1536 ?        SN   18:21   0:00 tail -f /dev/null
haproxy      257  1.2  0.1 273836 28540 ?        SNsl 18:24   0:02 /usr/sbin/haproxy -f /etc/haproxy/conf.
root         273  0.0  0.0   7064  2816 pts/0    RNs+ 18:27   0:00 ps aux
```

If we restart the master node simulating a upgrade:

```bash
2024/03/15 18:28:52 INFO: [HAPHelper] [Main] Proxy was initialized
2024/03/15 18:28:52 DEBUG2: [HAPHelper] [Proxy] Obtained proxy backends
2024/03/15 18:28:52 DEBUG2: [HAPHelper] [Proxy] Obtained proxy frontends
2024/03/15 18:28:52 INFO: [HAPHelper] [Main] Setting a value for `hard-stop-after` configuration.
2024/03/15 18:28:52 DEBUG: [HAPHelper] [D API] Receiving parameters {'select': ['node_name', 'version'], 'sort': {'fields': ['version', 'id'], 'order': 'desc'}, 'filters': {'status': 'active'}, 'q': 'id!=000', 'limit': 100000}
2024/03/15 18:28:52 DEBUG: [HAPHelper] [D API] Starting to execute request locally
2024/03/15 18:28:52 DEBUG: [HAPHelper] [D API] Finished executing request locally
2024/03/15 18:28:52 DEBUG: [HAPHelper] [D API] Time calculating request result: 0.015s
2024/03/15 18:28:52 DEBUG: [HAPHelper] [Main] Waiting for workers connections 12s...
2024/03/15 18:28:52 INFO: [HAPHelper] [Proxy] Setted `hard-stop-after` with 5 seconds.
2024/03/15 18:29:04 INFO: [HAPHelper] [Main] Reconnecting 13 agents.
2024/03/15 18:29:04 DEBUG: [HAPHelper] [Main] Reconnecting agents
2024/03/15 18:29:04 DEBUG: [HAPHelper] [Main] Agent reconnection chunk size is set to 120. Total iterations: 1
2024/03/15 18:29:04 DEBUG: [HAPHelper] [D API] Receiving parameters {'agent_list': ['013', '011', '009', '008', '012', '007', '006', '003', '010', '005', '004', '002', '001']}
2024/03/15 18:29:04 DEBUG: [HAPHelper] [D API] Receiving parameters {'agent_list': ['001', '002', '004', '005', '010']}
2024/03/15 18:29:04 DEBUG: [HAPHelper] [D API] Starting to execute request locally
2024/03/15 18:29:04 DEBUG: [HAPHelper] [D API] Finished executing request locally
2024/03/15 18:29:04 DEBUG: [HAPHelper] [D API] Time calculating request result: 0.013s
2024/03/15 18:29:04 DEBUG: [HAPHelper] [Main] Delay between agent reconnections. Sleeping 5s...
2024/03/15 18:29:09 INFO: [HAPHelper] [Main] Starting HAProxy Helper
2024/03/15 18:29:09 DEBUG2: [HAPHelper] [Proxy] Obtained proxy servers
2024/03/15 18:29:09 DEBUG: [HAPHelper] [D API] Receiving parameters {}
2024/03/15 18:29:09 DEBUG2: [HAPHelper] [Proxy] Obtained proxy servers
2024/03/15 18:29:09 INFO: [HAPHelper] [Main] Load balancer backend is up to date
2024/03/15 18:29:09 DEBUG2: [HAPHelper] [Proxy] Obtained server 'master-node' stats
2024/03/15 18:29:09 DEBUG2: [HAPHelper] [Proxy] Obtained server 'worker1' stats
2024/03/15 18:29:09 DEBUG2: [HAPHelper] [Proxy] Obtained server 'worker2' stats
2024/03/15 18:29:09 DEBUG: [HAPHelper] [Main] Checking for agent balance. Current connections distribution: {'master-node': 4, 'worker1': 4, 'worker2': 4}
2024/03/15 18:29:09 DEBUG: [HAPHelper] [Main] Current balance is under tolerance
2024/03/15 18:29:09 DEBUG2: [HAPHelper] [Proxy] Obtained server 'master-node' stats
2024/03/15 18:29:09 DEBUG2: [HAPHelper] [Proxy] Obtained server 'worker1' stats
2024/03/15 18:29:09 DEBUG2: [HAPHelper] [Proxy] Obtained server 'worker2' stats
2024/03/15 18:29:09 DEBUG: [HAPHelper] [Main] Current backend stats: {'master-node': 4, 'worker1': 4, 'worker2': 4}
2024/03/15 18:29:09 INFO: [HAPHelper] [Main] Load balancer backend is balanced
2024/03/15 18:29:09 DEBUG: [HAPHelper] [Main] Sleeping 60s...
```

During the startup the HAProxy has duplicated processes.

```bash
➜  wazuh-coordinator-dev git:(dev-wazuh-coordinator) ✗ docker-compose exec wazuh-proxy ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0   4364  3072 ?        SNs  18:21   0:00 bash /scripts/entrypoint.sh wazuh-maste
syslog        19  0.0  0.0 292076  3404 ?        SNsl 18:21   0:00 rsyslogd
root          56  0.2  0.3 1263412 79296 ?       SNl  18:21   0:01 dataplaneapi -f /etc/haproxy/dataplanea
root          57  0.0  0.0   2824  1536 ?        SN   18:21   0:00 tail -f /dev/null
haproxy      257  1.0  0.1 273836 29308 ?        SNsl 18:24   0:03 /usr/sbin/haproxy -f /etc/haproxy/conf.
haproxy      294  1.0  0.1 273836 26368 ?        SNsl 18:28   0:00 /usr/sbin/haproxy -f /etc/haproxy/conf.
root         310  0.0  0.0   7064  2816 pts/0    RNs+ 18:28   0:00 ps aux
```

After the restart the cluster is stabilized again and the `hard-stop-after` was setted.

![image](https://github.com/wazuh/wazuh/assets/7127104/29677d97-8d77-43cf-bfbf-1ab35257450c)

```bash
➜  wazuh-coordinator-dev git:(dev-wazuh-coordinator) ✗ docker-compose exec wazuh-proxy ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0   4364  3072 ?        SNs  18:21   0:00 bash /scripts/entrypoint.sh wazuh-maste
syslog        19  0.0  0.0 292076  3404 ?        SNsl 18:21   0:00 rsyslogd
root          56  0.2  0.3 1263412 81344 ?       SNl  18:21   0:01 dataplaneapi -f /etc/haproxy/dataplanea
root          57  0.0  0.0   2824  1536 ?        SN   18:21   0:00 tail -f /dev/null
haproxy      294  0.3  0.1 273836 27776 ?        SNsl 18:28   0:00 /usr/sbin/haproxy -f /etc/haproxy/conf.
root         316  0.0  0.0   7064  2944 pts/0    RNs+ 18:29   0:00 ps aux
```

```bash
➜  wazuh-coordinator-dev git:(dev-wazuh-coordinator) ✗ curl -k --silent -u haproxy:haproxy http://localhost:5555/v2/services/haproxy/configuration/global | jq
{
  "_version": 8,
  "data": {
    "runtime_apis": [
      {
        "level": "admin",
        "address": "/var/lib/haproxy/stats"
      }
    ],
    "chroot": "/var/lib/haproxy",
    "device_atlas_options": {},
    "fifty_one_degrees_options": {},
    "group": "haproxy",
    "hard_stop_after": 5000,
    "pidfile": "/var/run/haproxy.pid",
    "tune_options": {},
    "user": "haproxy",
    "wurfl_options": {}
  }
}
```


</p>
</details>


<details><summary> :green_circle: Check 1: Restart the helper with the `hard-stop-after` setted.</summary>
<p>

Before restart the helper

![image](https://github.com/wazuh/wazuh/assets/7127104/c381d0b4-c9b0-479d-bd15-3c691a575c8e)


```bash
➜  wazuh-coordinator-dev git:(dev-wazuh-coordinator) ✗ curl -k --silent -u haproxy:haproxy http://localhost:5555/v2/services/haproxy/configuration/global | jq
{
  "_version": 8,
  "data": {
    "runtime_apis": [
      {
        "level": "admin",
        "address": "/var/lib/haproxy/stats"
      }
    ],
    "chroot": "/var/lib/haproxy",
    "device_atlas_options": {},
    "fifty_one_degrees_options": {},
    "group": "haproxy",
    "hard_stop_after": 5000,
    "pidfile": "/var/run/haproxy.pid",
    "tune_options": {},
    "user": "haproxy",
    "wurfl_options": {}
  }
}
```

```bash
➜  wazuh-coordinator-dev git:(dev-wazuh-coordinator) ✗ docker-compose exec wazuh-proxy ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0   4364  3072 ?        SNs  18:21   0:00 bash /scripts/entrypoint.sh wazuh-maste
syslog        19  0.0  0.0 292076  3404 ?        SNsl 18:21   0:00 rsyslogd
root          56  0.1  0.3 1263412 78084 ?       SNl  18:21   0:01 dataplaneapi -f /etc/haproxy/dataplanea
root          57  0.0  0.0   2824  1536 ?        SN   18:21   0:00 tail -f /dev/null
haproxy      380  0.1  0.1 273836 28416 ?        SNsl 18:38   0:00 /usr/sbin/haproxy -f /etc/haproxy/conf.
root         396  0.0  0.0   7064  2816 pts/0    RNs+ 18:42   0:00 ps aux
```

When the helper start take the `hard-stop-after` and sleep until start the main loop.

```bash
2024/03/15 18:41:01 INFO: [HAPHelper] [Main] Proxy was initialized
2024/03/15 18:41:01 INFO: [HAPHelper] [Main] Ensuring only exists one HAProxy process. Sleeping 5.0s before start...
2024/03/15 18:41:06 DEBUG2: [HAPHelper] [Proxy] Obtained proxy backends
2024/03/15 18:41:06 DEBUG2: [HAPHelper] [Proxy] Obtained proxy frontends
2024/03/15 18:41:06 INFO: [HAPHelper] [Main] Starting HAProxy Helper
2024/03/15 18:41:06 DEBUG2: [HAPHelper] [Proxy] Obtained proxy servers
2024/03/15 18:41:06 DEBUG: [HAPHelper] [D API] Receiving parameters {}
2024/03/15 18:41:06 DEBUG2: [HAPHelper] [Proxy] Obtained proxy servers
2024/03/15 18:41:06 INFO: [HAPHelper] [Main] Load balancer backend is up to date
2024/03/15 18:41:06 DEBUG2: [HAPHelper] [Proxy] Obtained server 'master-node' stats
2024/03/15 18:41:06 DEBUG2: [HAPHelper] [Proxy] Obtained server 'worker1' stats
2024/03/15 18:41:06 DEBUG2: [HAPHelper] [Proxy] Obtained server 'worker2' stats
2024/03/15 18:41:06 DEBUG: [HAPHelper] [Main] Checking for agent balance. Current connections distribution: {'master-node': 4, 'worker1': 4, 'worker2': 4}
2024/03/15 18:41:06 DEBUG: [HAPHelper] [Main] Current balance is under tolerance
2024/03/15 18:41:06 DEBUG2: [HAPHelper] [Proxy] Obtained server 'master-node' stats
2024/03/15 18:41:06 DEBUG2: [HAPHelper] [Proxy] Obtained server 'worker1' stats
2024/03/15 18:41:07 DEBUG2: [HAPHelper] [Proxy] Obtained server 'worker2' stats
2024/03/15 18:41:07 DEBUG: [HAPHelper] [Main] Current backend stats: {'master-node': 4, 'worker1': 4, 'worker2': 4}
2024/03/15 18:41:07 INFO: [HAPHelper] [Main] Load balancer backend is balanced
2024/03/15 18:41:07 DEBUG: [HAPHelper] [Main] Sleeping 60s...
```

</p>
</details>

<details><summary> :green_circle: Check 2: Start the helper for the first time.</summary>
<p>

Before starting the helper

![image](https://github.com/wazuh/wazuh/assets/7127104/d2df5d2d-68c2-4eae-abbb-386df67c3389)

```bash
➜  wazuh-coordinator-dev git:(dev-wazuh-coordinator) ✗ docker-compose exec wazuh-proxy ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0   4364  3072 ?        SNs  18:56   0:00 bash /scripts/entrypoint.sh wazuh-maste
syslog        19  0.3  0.0 292076  3276 ?        SNsl 18:56   0:00 rsyslogd
haproxy       40  0.8  0.1 279980 27220 ?        SNsl 18:56   0:00 /usr/sbin/haproxy -f /etc/haproxy/conf.
root          56  0.8  0.3 1263092 71808 ?       SNl  18:56   0:00 dataplaneapi -f /etc/haproxy/dataplanea
root          57  0.0  0.0   2824  1408 ?        SN   18:56   0:00 tail -f /dev/null
root          79  0.0  0.0   7064  2816 pts/0    RNs+ 18:57   0:00 ps aux
```

```bash
2024/03/15 19:23:22 INFO: [HAPHelper] [Main] Proxy was initialized
2024/03/15 19:23:22 DEBUG2: [HAPHelper] [Proxy] Obtained proxy backends
2024/03/15 19:23:22 INFO: [HAPHelper] [Main] Could not find Wazuh backend 'wazuh_cluster'
2024/03/15 19:23:22 DEBUG2: [HAPHelper] [Proxy] Added new proxy backend: 'wazuh_cluster'
2024/03/15 19:23:22 INFO: [HAPHelper] [Main] Added Wazuh backend
2024/03/15 19:23:22 DEBUG2: [HAPHelper] [Proxy] Obtained proxy frontends
2024/03/15 19:23:22 INFO: [HAPHelper] [Main] Could not find Wazuh frontend 'wazuh_cluster_front'
2024/03/15 19:23:22 DEBUG2: [HAPHelper] [Proxy] Added new proxy frontend: 'wazuh_cluster_front'
2024/03/15 19:23:22 INFO: [HAPHelper] [Main] Added Wazuh frontend
2024/03/15 19:23:22 DEBUG: [HAPHelper] [Main] Waiting for workers connections 12s...
2024/03/15 19:23:34 INFO: [HAPHelper] [Main] Setting a value for `hard-stop-after` configuration.
2024/03/15 19:23:34 DEBUG: [HAPHelper] [D API] Receiving parameters {'select': ['node_name', 'version'], 'sort': {'fields': ['version', 'id'], 'order': 'desc'}, 'filters': {'status': 'active'}, 'q': 'id!=000', 'limit': 100000}
2024/03/15 19:23:34 DEBUG: [HAPHelper] [D API] Starting to execute request locally
2024/03/15 19:23:34 DEBUG: [HAPHelper] [D API] Finished executing request locally
2024/03/15 19:23:34 DEBUG: [HAPHelper] [D API] Time calculating request result: 0.019s
2024/03/15 19:23:34 INFO: [HAPHelper] [Proxy] Setted `hard-stop-after` with 5 seconds.
2024/03/15 19:23:34 INFO: [HAPHelper] [Main] Starting HAProxy Helper
2024/03/15 19:23:34 DEBUG2: [HAPHelper] [Proxy] Obtained proxy servers
2024/03/15 19:23:34 DEBUG: [HAPHelper] [D API] Receiving parameters {}
2024/03/15 19:23:34 DEBUG2: [HAPHelper] [Proxy] Obtained proxy servers
2024/03/15 19:23:34 INFO: [HAPHelper] [Main] Detected changes in Wazuh cluster nodes. Current cluster: {'master-node': 'wazuh-master', 'worker1': '172.26.0.3', 'worker2': '172.26.0.5'}
2024/03/15 19:23:34 INFO: [HAPHelper] [Main] Attempting to update proxy backend
2024/03/15 19:23:34 DEBUG2: [HAPHelper] [Proxy] Added new server 'master-node' wazuh-master:1514 to backend 'wazuh_cluster'
2024/03/15 19:23:35 DEBUG2: [HAPHelper] [Proxy] Added new server 'worker1' 172.26.0.3:1514 to backend 'wazuh_cluster'
2024/03/15 19:23:35 DEBUG2: [HAPHelper] [Proxy] Added new server 'worker2' 172.26.0.5:1514 to backend 'wazuh_cluster'
2024/03/15 19:23:35 DEBUG: [HAPHelper] [Main] Waiting for new servers to go UP
2024/03/15 19:23:36 DEBUG2: [HAPHelper] [Proxy] Obtained server 'master-node' stats
2024/03/15 19:23:36 DEBUG2: [HAPHelper] [Proxy] Obtained server 'worker1' stats
2024/03/15 19:23:36 DEBUG2: [HAPHelper] [Proxy] Obtained server 'worker2' stats
2024/03/15 19:23:36 DEBUG: [HAPHelper] [Main] All new servers are UP
2024/03/15 19:23:36 DEBUG: [HAPHelper] [D API] Receiving parameters {'select': ['node_name', 'version'], 'sort': {'fields': ['version', 'id'], 'order': 'desc'}, 'filters': {'status': 'active'}, 'q': 'id!=000', 'limit': 100000}
2024/03/15 19:23:36 DEBUG: [HAPHelper] [D API] Starting to execute request locally
2024/03/15 19:23:36 DEBUG: [HAPHelper] [D API] Finished executing request locally
2024/03/15 19:23:36 DEBUG: [HAPHelper] [D API] Time calculating request result: 0.005s
2024/03/15 19:23:36 DEBUG2: [HAPHelper] [Proxy] Obtained server 'master-node' stats
2024/03/15 19:23:36 DEBUG2: [HAPHelper] [Proxy] Obtained server 'worker1' stats
2024/03/15 19:23:36 DEBUG2: [HAPHelper] [Proxy] Obtained server 'worker2' stats
2024/03/15 19:23:36 DEBUG: [HAPHelper] [Main] Checking for agent balance. Current connections distribution: {'master-node': 0, 'worker1': 0, 'worker2': 0}
2024/03/15 19:23:36 DEBUG: [HAPHelper] [Main] Current balance is under tolerance
2024/03/15 19:23:36 INFO: [HAPHelper] [Main] Waiting for agent connections stability
2024/03/15 19:23:36 DEBUG: [HAPHelper] [Main] Sleeping 60s...
```

After the start only exists one HAProxy process and the `hard-stop-after` was setted.

![image](https://github.com/wazuh/wazuh/assets/7127104/19755382-6f81-4653-9281-2c0b3e2dc0a0)

```bash
➜  wazuh-coordinator-dev git:(dev-wazuh-coordinator) ✗ docker-compose exec wazuh-proxy ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0   4364  3072 ?        SNs  18:56   0:00 bash /scripts/entrypoint.sh wazuh-maste
syslog        19  0.1  0.0 292076  3276 ?        SNsl 18:56   0:00 rsyslogd
root          56  0.3  0.3 1263156 75136 ?       SNl  18:56   0:00 dataplaneapi -f /etc/haproxy/dataplanea
root          57  0.0  0.0   2824  1408 ?        SN   18:56   0:00 tail -f /dev/null
haproxy      292  0.4  0.1 273836 27528 ?        SNsl 18:59   0:00 /usr/sbin/haproxy -f /etc/haproxy/conf.
root         308  0.0  0.0   7064  2816 pts/0    RNs+ 19:00   0:00 ps aux
```

```bash
➜  wazuh-coordinator-dev git:(dev-wazuh-coordinator) ✗ curl -k --silent -u haproxy:haproxy http://localhost:5555/v2/services/haproxy/configuration/global | jq
{
  "_version": 8,
  "data": {
    "runtime_apis": [
      {
        "level": "admin",
        "address": "/var/lib/haproxy/stats"
      }
    ],
    "chroot": "/var/lib/haproxy",
    "device_atlas_options": {},
    "fifty_one_degrees_options": {},
    "group": "haproxy",
    "hard_stop_after": 5000,
    "pidfile": "/var/run/haproxy.pid",
    "tune_options": {},
    "user": "haproxy",
    "wurfl_options": {}
  }
}
```

</p>
</details>

**Comment by nico-stefani** [comment]
I've been working on the last improvements. Still, I need to validate the correct function.
