### ISSUE TITLE
Post release tasks for 4.7.1

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#20933]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.7.1.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.7.1-into-4.7.2`.

## Tasks

- [x] Merge branch `4.7.1` into branch `4.7.2`. - https://github.com/wazuh/wazuh/pull/20993
- [x] Merge branch `4.7.2` into branch `4.8.0`. - https://github.com/wazuh/wazuh/pull/21005
- [x] Merge branch `4.8.0` into branch `4.8.1`. - https://github.com/wazuh/wazuh/pull/21019
- [x] Merge branch `4.8.1` into branch `master`. - https://github.com/wazuh/wazuh/pull/21024
- [x] Publish GitHub release as latest.
- [x] Delete all stage pre-releases for 4.7.1 (https://github.com/wazuh/wazuh/releases).
- [x] Delete all stage tags for v4.7.1. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.7.1-rc1, 4.7.1-alpha1, etc.
- [x] Fast-forward definitive tag v4.7.1 to `4.7` branch.
- [x] Delete branch `4.7.1`.

**Comment by vikman90** [comment]
## Blocked

- https://github.com/wazuh/wazuh-qa/issues/4778

**Comment by vikman90** [comment]
## Deleting branch

Deleting _4.7.1_, it has no new commits:

```
5a0abd9df (HEAD -> 4.7.1, tag: v4.7.1-rc3, tag: v4.7.1, origin/4.7.1) Merge pull request #20886 from wazuh/change/20884-bump-revision
```

**Comment by jotacarma90** [comment]
Pending to merge last PR:
Merge branch 4.8.1 into branch master. - https://github.com/wazuh/wazuh/pull/21024

The checks that fail are known, as mentioned in the comment: https://github.com/wazuh/wazuh/pull/21024#issuecomment-1867734605

**Comment by MarcelKemp** [comment]
- Fast-forward definitive tag v4.7.1 to 4.7 branch.
The branch is protected, so I have opened the following PR to perform the merge:
  - 21095

**Comment by MarcelKemp** [comment]
Done.
