### ISSUE TITLE
Wazuh modulesd output parser not logging debug level  for the Azure wodle

### ISSUE THREAD

**Issue by EduLeon12** [wazuh/wazuh#20983]
| Affected integration |
|---|
| Azure|

## Description

During the development of #16739  it was found that the developed `wm_parse_output` is not printing the debug level messages in the `ossec.log` when debug level is 2.

As seen on the logs when executing the wodle manually and the printing of the debug level it can be confirmed that the debug level argument is being parsed correctly but for unknown reasons, the parser is not printing that level specifically.  

```command
root@8e346f14c305:/var/ossec# wodles/azure/azure-logs --storage --storage_auth_path /var/ossec/wodles/wodles_credentials/azure_storage_credentials --container "Test-container" --blobs "*" --storage_tag azure-activity --storage_time_offset 30d --debug 2

debug level is: 2
``` 
 
All other levels are being printed into the `ossec.log` correctly

```command
2023/12/20 18:19:20 wazuh-modulesd:azure-logs[3669] wm_parser.c:76 at wm_parse_output(): INFO: Test_message: INFO
2023/12/20 18:19:20 wazuh-modulesd:azure-logs[3669] wm_parser.c:82 at wm_parse_output(): WARNING: Test_message: WARNING
2023/12/20 18:19:20 wazuh-modulesd:azure-logs[3669] wm_parser.c:80 at wm_parse_output(): ERROR: Test_message: ERROR
```

This was tested by adding the following code block on the Azure wodle  `/var/ossec/wodles/azure/azure-logs.py`.

```python
    azure_logger.info("Test_message: INFO")
    azure_logger.debug("Test_message: DEBUg")
    azure_logger.warning("Test_message: WARNING")
    azure_logger.error("Test_message: ERROR")
```  

To replicate this issue the code line `azure_logger.debug("Test Message DEBUG")` can be added anywhere on the azure code for example at the bottom of the `azure-logs.py` file:

```python
if __name__ == "__main__":
    args = get_script_arguments()

    azure_logger.info("Test_message: INFO")
    azure_logger.debug("Test_message: DEBUB")
    azure_logger.warning("Test_message: WARNING")
    azure_logger.error("Test_message: ERROR")

   # Rest of code block

```

This issue should tend to fix the parser output of the Azure wodle to ensure the debug level messages are printed correctly and seen in the `ossec.log`

## Tasks
- [ ] Test in a manager.
- [ ] Test in an agent.
- [ ] Unit tests without failures. Updated if there are any relevant changes.

**Comment by EduLeon12** [comment]
Will be closed since it was found it was not an issue with the parser but the configuration of the woddle
