### ISSUE TITLE
Office 2016 hotfix cannot be installed on the system

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#21126]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.1 | Vulnerability Detector | Manager | All | Windows |

## Description

Environments have been found where Vulnerability Detector indicates that a Windows agent is vulnerable because the _Office 2016_ package does not have a hotfix (or any of its supersedences), causing them to be reported. Example:

- `CVE-2023-41764`: https://msrc.microsoft.com/update-guide/vulnerability/CVE-2023-41764 (the following hotfixes fix it):
  - `KB5002457`: https://www.catalog.update.microsoft.com/Search.aspx?q=KB5002457
  - `KB5002498`: https://www.catalog.update.microsoft.com/Search.aspx?q=KB5002498
  - `KB5002100`: https://www.catalog.update.microsoft.com/Search.aspx?q=KB5002100

This information is correct, as it is obtained from the MSU (which has the official Microsoft information from the [MSRC](https://msrc.microsoft.com/update-guide/vulnerability) and [Catalog](https://www.catalog.update.microsoft.com/home.aspx)), however, there are times when these hotfixes that fix the vulnerability cannot be installed, because the system appears to be already updated.

The problem is that if it really is up-to-date, we are not getting the hotfix and its supersedence, which causes a vulnerability to be reported that cannot be fixed.

So it is necessary to research how the installation of the hotfix itself verifies that the system is up-to-date and not vulnerable, and therefore indicates that the hotfix is not possible.

### Tasks
- [ ] Replicate the problem (you can try again to install a hotfix that has just been installed, so you will always get the message "`The hotfix is already installed on the system`").
  - [ ] Debug the Windows installation tool to check the logs and files it accesses to verify that the hotfix is installed (you can use the _Windows process monitor_).
- [ ] Once the registry or file used to verify it is found, modify the current code to obtain the hotfixes or mitigate these vulnerabilities.

**Comment by lsayanes** [comment]
### Looking for patch KB5002457 on disk

I have taken the `KB5002457` update as an example by downloading the executable file `riched202016-kb5002058-fullfile-x64-glb.exe` to install it.
Using "Windows process monitor" at the time of running the installation I discovered that it generated the logs: **opatchinstall(2).log** & **riched20-x-none_MSPLOG.LOG**
In the last one I found the `PatchId={786E845F-3515-4ACE-9BAF-A42AD1A6FFFF}` I have been looking for both **kb5002058** and **PatchId** in the system and registry.

I have also used the wuapi `search` function:
- https://learn.microsoft.com/en-us/windows/win32/api/wuapi/nf-wuapi-iupdatesearcher-search

and `PowerShell` script of type, to list installed patches:

```
$session = New-Object -ComObject "Microsoft.Update.Session"
$updatesearcher = $session.CreateUpdateSearcher()
$count = $updatesearcher.GetTotalHistoryCount()
$updates = $updatesearcher.QueryHistory(0, $count)

foreach ($update in $updates) {
  $out = New-Object -Type PSObject -Prop @{
    ‘KB’ = [regex]::match($update.Title,’KB(\d+)’)
    ‘Title’ = $update.Title
    ‘Description’ = $update.Description
    ‘Id’ = $update.UpdateIdentity.UpdateId
    ‘RevisionNumber’ = $update.UpdateIdentity.RevisionNumber
  }
  Write-Output $out
}

```
The specific update KB5002457 may not appear in update search results because the update is considered a cumulative update and individual updates within cumulative updates may not appear explicitly when you perform a search.

```
This is in msu-updates.json:
    ],
          "KB4011036": [
               "KB5002458",
               "KB4011569",
               "KB4461476",
               "KB5002058",
               "KB4011669"
```


Finally I found it using a PowerShell find:
`Get-ChildItem -Path C:\ -File -Recurse -Filter "*KB5002058*"`

![Captura de pantalla 2024-01-08 a la(s) 17 06 56](https://github.com/wazuh/wazuh/assets/68856625/278d4ffd-e2c0-43e5-b543-325d0fb8e19d)


The file "**_RICHED202016-KB5002058-FULLFI-709B9C07.pf_**" that I found in the _C:\Windows\Prefetch_ folder is a prefetch file. The Windows operating system uses prefetch files to speed up the startup of frequently used applications and services. They store information about the application, such as its execution time, and can help the system load the application more quickly when necessary.

In the context of the security patch "**_riched202016-kb5002058-fullfile-x64-glb.exe_**", the corresponding prefetch file is created when the patch is installed. This allows the system to load the patch more quickly when needed for updates or other purposes.
It is generally safe to leave prefetch files in place, as they help improve overall system performance. However, if you have problems or conflicts related to this specific file, you can try removing it and reinstalling the security patch using the same executable file provided.

**Comment by lsayanes** [comment]
I have not been able to reproduce the error because, in the specific case of the `KB5002457` patch that I installed, it has been detected by syscollector, in the DB of the Agent.
I also found it in the Windows registry, where Wazuh would look for it: 
`constexpr auto WIN_REG_PRODUCT_HOTFIX {"SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Installer\\UserData\\S-1-5-18\\Products"};
`
![2457](https://github.com/wazuh/wazuh/assets/68856625/152cfd2a-fc56-4cef-9c2d-3493eb9a2a21)

and it would be possible to uninstall it according to the uninstallation key:

![uninstall 2457](https://github.com/wazuh/wazuh/assets/68856625/7043e8c3-9e38-4c3f-9c69-4c05403ff142)


`"C:\Program Files\Common Files\Microsoft Shared\OFFICE16\Oarpmany.exe" /removereleaseinpatch "{90160000-0011-0000-1000-0000000FF1CE}" "{0F8DF4D9-BD4C-4CB7-9A98-7DF926577F15}" "3082" "0"`

**Comment by Leoquicenoz** [comment]
Once we were able to obtain the machine that has the replicated issue, we started to search by different methods for the hotfix installation location (We are still looking for `KB5002457`).

We used search methods such as: `Process Monitor`, `Event Viewer`, search in temporary folders, search in installation `logs`, we used third party software such as `InstalledPackagesView`, but we could not find the way in which Windows determines that the hotfix is already installed.

<details>

<summary>Screenshots</summary>

![Screenshot from 2024-01-22 21-09-03](https://github.com/wazuh/wazuh/assets/106568370/beab15e7-6b3e-4059-8538-e46955bb6ce5)

![Screenshot from 2024-01-22 21-40-00](https://github.com/wazuh/wazuh/assets/106568370/51137404-47e0-4496-b9a0-d089e09cb154)

![Screenshot from 2024-01-23 22-15-26](https://github.com/wazuh/wazuh/assets/106568370/8e626cc3-c867-4db1-b8e0-19747332ced4)

</details>

As I could not identify the path by any way, I was reading Windows documentation and in the popup window that appears when downloading the hotfix, some data is shown that I found interesting: 
1) **UpdateID**: I also performed searches on the machine with this ID and found nothing.
2) **Package Details**: Here you can see which hotfix replaces it. 

![image](https://github.com/wazuh/wazuh/assets/106568370/5c3bb55e-f401-4d0a-a667-51951b2fddbd)

When looking for the hotfix that replaces it (`KB5002521`), this if it finds it the Wazuh Manager and the path where it is is the normal `{"SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Installer\\UserData\\S-1-5-18\\Products"}`, I decide to make a test that is to uninstall this hotfix, that I imagine that when detecting that it is installed it does not allow to install the old ones since it replaces them and after making this, to try again to install the `KB5002457`.

Once uninstalled the hotfix `KB5002521` I try to install the `KB5002457` (that before I had not been able to do it because it said that it was already installed) and if it can be installed without problem, it is also in the normal path.

![Screenshot from 2024-01-22 21-43-38](https://github.com/wazuh/wazuh/assets/106568370/374d0b1f-0151-4a8a-984a-77e5efd53de7)

![Screenshot from 2024-01-22 21-44-49](https://github.com/wazuh/wazuh/assets/106568370/8df51692-9a1c-49ad-88b5-a67e9207d1d1)

**Comment by ncvicchi** [comment]
Changed ETA for higher priority issues

**Comment by Leoquicenoz** [comment]
## Update

I have not advanced much more, I am still looking for alternatives that I have not already used to search for the path in which the `KB` can be saved, but I have not been able to identify it,

**Comment by Leoquicenoz** [comment]
Changed ETA because no further progress has been made, pending further instruction or assistance.

**Comment by Leoquicenoz** [comment]
## Update

1. Obtain the `.json` file with the modifications in the `CVE-2023-41764`, adding the KBs to the list in the `"anyOf"` tag.
2. Wazuh manager `4.8.0` is installed to be able to test with this modification.
3. In the test environment that had been shared with me in which the issue was present, for some strange reason I could not reproduce it again so I am not sure if with the modifications made in the CVE, the issue has been solved.

**Comment by Leoquicenoz** [comment]
## Update

1. I tried to replicate the issue with the different vulnerabilities that were evidenced in the manager concerning `Microsoft Office 2016`, but none of the hotfix that patches these vulnerabilities can be installed as the following message is displayed: 

![image](https://github.com/wazuh/wazuh/assets/106568370/2dfbdd00-1c4f-40ae-a6df-977e1b2d9a2f)
 
But in the manager the following vulnerability is evidenced: 
```
Microsoft Office Professional Plus 2016|16.0.4266.1001|x64|CVE-2021-42293|1707255940|Medium|5.0|6.5|85def04ee3bd489a8baf328df0e5bb3a0dc3916a|PACKAGE|VALID|["https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2021-42293","https://nvd.nist.gov/vuln/detail/CVE-2021-42293"]|KB5002099 patch is not installed|CVE-2021-42293 affects Microsoft Office Professional Plus 2016|2021-12-15|2022-07-12
``` 
This same was tried with the different vulnerabilities that are obtained.

```
Microsoft Office Professional Plus 2016|16.0.4266.1001|x64|CVE-2021-42293|1707255940|Medium|5.0|6.5|85def04ee3bd489a8baf328df0e5bb3a0dc3916a|PACKAGE|VALID|["https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2021-42293","https://nvd.nist.gov/vuln/detail/CVE-2021-42293"]|KB5002099 patch is not installed|CVE-2021-42293 affects Microsoft Office Professional Plus 2016|2021-12-15|2022-07-12
Microsoft Office Professional Plus 2016|16.0.4266.1001|x64|CVE-2021-1711|1707255940|High|9.3|7.8|85def04ee3bd489a8baf328df0e5bb3a0dc3916a|PACKAGE|VALID|["https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2021-1711","https://nvd.nist.gov/vuln/detail/CVE-2021-1711"]|KB4486755 patch is not installed|CVE-2021-1711 affects Microsoft Office Professional Plus 2016|2021-01-12|2023-12-29
Microsoft Office Professional Plus 2016|16.0.4266.1001|x64|CVE-2021-28455|1707255940|High|6.5|8.8|85def04ee3bd489a8baf328df0e5bb3a0dc3916a|PACKAGE|VALID|["https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2021-28455","https://nvd.nist.gov/vuln/detail/CVE-2021-28455"]|KB4493197 patch is not installed|CVE-2021-28455 affects Microsoft Office Professional Plus 2016|2021-05-11|2023-12-29
Microsoft Office Professional Plus 2016|16.0.4266.1001|x64|CVE-2020-0991|1707255940|High|9.3|7.8|85def04ee3bd489a8baf328df0e5bb3a0dc3916a|PACKAGE|VALID|["https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2020-0991","https://nvd.nist.gov/vuln/detail/CVE-2020-0991"]|KB4484287 patch is not installed|CVE-2020-0991 affects Microsoft Office Professional Plus 2016|2020-04-15|2021-07-21
Microsoft Office Professional Plus 2016|16.0.4266.1001|x64|CVE-2020-0961|1707255940|High|9.3|7.8|85def04ee3bd489a8baf328df0e5bb3a0dc3916a|PACKAGE|VALID|["https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2020-0961","https://nvd.nist.gov/vuln/detail/CVE-2020-0961"]|KB4484287 patch is not installed|CVE-2020-0961 affects Microsoft Office Professional Plus 2016|2020-04-15|2021-07-21
Microsoft Office Professional Plus 2016|16.0.4266.1001|x64|CVE-2019-1463|1707255940|Medium|2.1|5.5|85def04ee3bd489a8baf328df0e5bb3a0dc3916a|PACKAGE|VALID|["https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2019-1463","https://nvd.nist.gov/vuln/detail/CVE-2019-1463"]|KB4484180 patch is not installed|CVE-2019-1463 affects Microsoft Office Professional Plus 2016|2019-12-10|2019-12-16
Microsoft Office Professional Plus 2016|16.0.4266.1001|x64|CVE-2019-1400|1707255940|Medium|2.1|5.5|85def04ee3bd489a8baf328df0e5bb3a0dc3916a|PACKAGE|VALID|["https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2019-1400","https://nvd.nist.gov/vuln/detail/CVE-2019-1400"]|KB4484180 patch is not installed|CVE-2019-1400 affects Microsoft Office Professional Plus 2016|2019-12-10|2019-12-13
Microsoft Office Professional Plus 2016|16.0.4266.1001|x64|CVE-2019-1402|1707255940|Medium|2.1|5.5|85def04ee3bd489a8baf328df0e5bb3a0dc3916a|PACKAGE|VALID|["https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2019-1402","https://nvd.nist.gov/vuln/detail/CVE-2019-1402"]|KB4484113 patch is not installed|CVE-2019-1402 affects Microsoft Office Professional Plus 2016|2019-11-12|2019-11-14
Microsoft Office Professional Plus 2016|16.0.4266.1001|x64|CVE-2019-1246|1707255940|High|9.3|7.8|85def04ee3bd489a8baf328df0e5bb3a0dc3916a|PACKAGE|VALID|["https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2019-1246","https://nvd.nist.gov/vuln/detail/CVE-2019-1246"]|KB4475591 patch is not installed|CVE-2019-1246 affects Microsoft Office Professional Plus 2016|2019-09-11|2020-08-24
Microsoft Office Professional Plus 2016|16.0.4266.1001|x64|CVE-2019-1155|1707255940|High|9.3|7.8|85def04ee3bd489a8baf328df0e5bb3a0dc3916a|PACKAGE|VALID|["https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2019-1155","https://nvd.nist.gov/vuln/detail/CVE-2019-1155"]|KB4475538 patch is not installed|CVE-2019-1155 affects Microsoft Office Professional Plus 2016|2019-08-14|2020-08-24
Microsoft Office Professional Plus 2016|16.0.4266.1001|x64|CVE-2019-0946|1707255940|High|9.3|7.8|85def04ee3bd489a8baf328df0e5bb3a0dc3916a|PACKAGE|VALID|["https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2019-0946","https://nvd.nist.gov/vuln/detail/CVE-2019-0946"]|KB4464551 patch is not installed|CVE-2019-0946 affects Microsoft Office Professional Plus 2016|2019-05-16|2019-05-17
Microsoft Office Professional Plus 2016|16.0.4266.1001|x64|CVE-2019-0945|1707255940|High|9.3|7.8|85def04ee3bd489a8baf328df0e5bb3a0dc3916a|PACKAGE|VALID|["https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2019-0945","https://nvd.nist.gov/vuln/detail/CVE-2019-0945"]|KB4464551 patch is not installed|CVE-2019-0945 affects Microsoft Office Professional Plus 2016|2019-05-16|2019-05-17
Microsoft Office Professional Plus 2016|16.0.4266.1001|x64|CVE-2019-0827|1707255940|High|6.8|7.8|85def04ee3bd489a8baf328df0e5bb3a0dc3916a|PACKAGE|VALID|["https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2019-0827","https://nvd.nist.gov/vuln/detail/CVE-2019-0827"]|KB4462213 patch is not installed|CVE-2019-0827 affects Microsoft Office Professional Plus 2016|2019-04-09|2020-08-24
Microsoft Office Professional Plus 2016|16.0.4266.1001|x64|CVE-2019-0826|1707255940|High|6.8|7.8|85def04ee3bd489a8baf328df0e5bb3a0dc3916a|PACKAGE|VALID|["https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2019-0826","https://nvd.nist.gov/vuln/detail/CVE-2019-0826"]|KB4462213 patch is not installed|CVE-2019-0826 affects Microsoft Office Professional Plus 2016|2019-04-09|2020-08-24
Microsoft Office Professional Plus 2016|16.0.4266.1001|x64|CVE-2019-0825|1707255940|High|6.8|7.8|85def04ee3bd489a8baf328df0e5bb3a0dc3916a|PACKAGE|VALID|["https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2019-0825","https://nvd.nist.gov/vuln/detail/CVE-2019-0825"]|KB4462213 patch is not installed|CVE-2019-0825 affects Microsoft Office Professional Plus 2016|2019-04-09|2020-08-24
Microsoft Office Professional Plus 2016|16.0.4266.1001|x64|CVE-2019-0824|1707255940|High|6.8|7.8|85def04ee3bd489a8baf328df0e5bb3a0dc3916a|PACKAGE|VALID|["https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2019-0824","https://nvd.nist.gov/vuln/detail/CVE-2019-0824"]|KB4462213 patch is not installed|CVE-2019-0824 affects Microsoft Office Professional Plus 2016|2019-04-09|2020-08-24
Microsoft Office Professional Plus 2016|16.0.4266.1001|x64|CVE-2019-0674|1707255940|High|9.3|7.8|85def04ee3bd489a8baf328df0e5bb3a0dc3916a|PACKAGE|VALID|["http://www.securityfocus.com/bid/106931","https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2019-0674","https://nvd.nist.gov/vuln/detail/CVE-2019-0674"]|KB4018294 patch is not installed|CVE-2019-0674 affects Microsoft Office Professional Plus 2016|2019-03-05|2020-08-24
Microsoft Office Professional Plus 2016|16.0.4266.1001|x64|CVE-2019-0673|1707255940|High|9.3|7.8|85def04ee3bd489a8baf328df0e5bb3a0dc3916a|PACKAGE|VALID|["http://www.securityfocus.com/bid/106930","https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2019-0673","https://nvd.nist.gov/vuln/detail/CVE-2019-0673"]|KB4018294 patch is not installed|CVE-2019-0673 affects Microsoft Office Professional Plus 2016|2019-03-05|2020-08-24
Microsoft Office Professional Plus 2016|16.0.4266.1001|x64|CVE-2019-0672|1707255940|High|9.3|7.8|85def04ee3bd489a8baf328df0e5bb3a0dc3916a|PACKAGE|VALID|["http://www.securityfocus.com/bid/106929","https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2019-0672","https://nvd.nist.gov/vuln/detail/CVE-2019-0672"]|KB4018294 patch is not installed|CVE-2019-0672 affects Microsoft Office Professional Plus 2016|2019-03-05|2020-08-24
Microsoft Office Professional Plus 2016|16.0.4266.1001|x64|CVE-2019-0671|1707255940|High|9.3|7.8|85def04ee3bd489a8baf328df0e5bb3a0dc3916a|PACKAGE|VALID|["http://www.securityfocus.com/bid/106928","https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2019-0671","https://nvd.nist.gov/vuln/detail/CVE-2019-0671"]|KB4018294 patch is not installed|CVE-2019-0671 affects Microsoft Office Professional Plus 2016|2019-03-05|2020-08-24
Microsoft Office Professional Plus 2016|16.0.4266.1001|x64|CVE-2019-0582|1707255940|High|9.3|7.8|85def04ee3bd489a8baf328df0e5bb3a0dc3916a|PACKAGE|VALID|["http://www.securityfocus.com/bid/106433","https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2019-0582","https://nvd.nist.gov/vuln/detail/CVE-2019-0582"]|KB4018294 patch is not installed|CVE-2019-0582 affects Microsoft Office Professional Plus 2016|2019-01-08|2023-03-31
Microsoft Office Professional Plus 2016|16.0.4266.1001|x64|CVE-2018-1030|1707255940|High|9.3|8.8|85def04ee3bd489a8baf328df0e5bb3a0dc3916a|PACKAGE|VALID|["http://www.securityfocus.com/bid/103620","http://www.securitytracker.com/id/1040654","https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2018-1030","https://nvd.nist.gov/vuln/detail/CVE-2018-1030"]|KB4018319 patch is not installed|CVE-2018-1030 affects Microsoft Office Professional Plus 2016|2018-04-12|2019-10-03
Microsoft Office Professional Plus 2016|16.0.4266.1001|x64|CVE-2018-1026|1707255940|High|9.3|8.8|85def04ee3bd489a8baf328df0e5bb3a0dc3916a|PACKAGE|VALID|["http://www.securityfocus.com/bid/103613","http://www.securitytracker.com/id/1040654","https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2018-1026","https://nvd.nist.gov/vuln/detail/CVE-2018-1026"]|KB4018319 patch is not installed|CVE-2018-1026 affects Microsoft Office Professional Plus 2016|2018-04-12|2019-10-03
Microsoft Office Professional Plus 2016|16.0.4266.1001|x64|CVE-2018-0853|1707255940|Low|4.3|3.3|85def04ee3bd489a8baf328df0e5bb3a0dc3916a|PACKAGE|VALID|["http://www.securityfocus.com/bid/102868","http://www.securitytracker.com/id/1040381","https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2018-0853","https://nvd.nist.gov/vuln/detail/CVE-2018-0853"]|KB4011143 patch is not installed|CVE-2018-0853 affects Microsoft Office Professional Plus 2016|2018-02-15|2020-08-24
Microsoft Office Professional Plus 2016|16.0.4266.1001|x64|CVE-2017-11934|1707255940|Medium|4.3|5.5|85def04ee3bd489a8baf328df0e5bb3a0dc3916a|PACKAGE|VALID|["http://www.securityfocus.com/bid/102064","http://www.securitytracker.com/id/1039998","https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2017-11934","https://nvd.nist.gov/vuln/detail/CVE-2017-11934"]|KB4011095 patch is not installed|CVE-2017-11934 affects Microsoft Office Professional Plus 2016|2017-12-12|2018-10-30
Microsoft Office Professional Plus 2016|16.0.4266.1001|x64|CVE-2016-0025|1707255940|High|9.3|7.3|85def04ee3bd489a8baf328df0e5bb3a0dc3916a|PACKAGE|VALID|["http://www.securitytracker.com/id/1036093","https://docs.microsoft.com/en-us/security-updates/securitybulletins/2016/ms16-070","https://nvd.nist.gov/vuln/detail/CVE-2016-0025"]|KB3115144 patch is not installed|CVE-2016-0025 affects Microsoft Office Professional Plus 2016|2016-06-16|2018-10-12
``` 
![Screenshot from 2024-02-07 18-39-53](https://github.com/wazuh/wazuh/assets/106568370/507f42ea-5b9e-4628-844c-07c07f9966bc)

2. I also tried to eliminate these vulnerabilities by adding the list of these `KBs` to the vulnerability file copied from `CTI`, in the `x_remediations` section and connecting the agent to a manager `4.8.0`, but it was not possible either.

**Comment by Leoquicenoz** [comment]
## Update

1. I tried to test by connecting the agent to the manager 4.8.0, but the manager did not show any vulnerability.

![Screenshot from 2024-02-08 11-45-39](https://github.com/wazuh/wazuh/assets/106568370/68d16340-dac0-47be-a6b8-987a1bc6111e)

2. A guide on how to make the modifications in the KB of the CVEs in its `x_remedations` section, this thinking that the proposed solution can give good results, so far the solution has not been fully tested because I have not been able to detect vulnerabilities in the agent with the manager `4.8.0`.

**Comment by Leoquicenoz** [comment]
## Update

After an intense search in the environment provided in which the issue is replicated, I find that:

The last KB installed in the environment was: `KB4493197`, this is determined based on the `opatchinstall(23).log` file, which shows the installation log of this hotfix and is the most recent installation log (the other `opatchinstall.log` files show the log of the other KBs).

![Screenshot from 2024-02-09 14-04-27](https://github.com/wazuh/wazuh/assets/106568370/55abd88c-8c98-4b6d-839d-6840ba39d0bd)

![Screenshot from 2024-02-09 14-04-56](https://github.com/wazuh/wazuh/assets/106568370/6a5a54e1-c34b-4aa9-9fa3-14f991793ec6)

In the Microsoft [description page](https://support.microsoft.com/en-us/topic/description-of-the-security-update-for-office-2016-may-11-2021-kb4493197-83afd3ad-e3b3-6b11-0639-57e727a8160d) of `KB4493197`, it is shown which files are installed when upgrading to this hotfix

![Screenshot from 2024-02-09 14-06-30](https://github.com/wazuh/wazuh/assets/106568370/7d42882e-6a17-44b2-9ca8-6dacc7e38c28)

You can see that this file is present in the paths: 

![Screenshot from 2024-02-09 14-08-04](https://github.com/wazuh/wazuh/assets/106568370/9010d86d-f419-4326-ab2f-944dab1372f5)

In the path of version `16.0.4266`, the installation files of the KBs are found, including those with a higher version as is the case of `KB5002100` (with file name `mso99lres.dll` and version `16.0.4666.1000`). This information can be seen [here](https://support.microsoft.com/en-us/topic/description-of-the-security-update-for-office-2016-september-12-2023-kb5002100-2965dcfd-8ecd-4104-8265-9ccff9a91d60)

![image](https://github.com/wazuh/wazuh/assets/106568370/a14b4afc-4607-433a-957c-50ebc328e1ac)

## External reference
Investigating also I found some similar cases in which the version `16.0.4266` presented inconveniences to be updated or to be able to install the most updated hotfixes:
1. https://www.reddit.com/r/sysadmin/comments/y2bfo7/outlook_2016_msi_version_wont_update_past_1604266/
2. https://www.reddit.com/r/sysadmin/comments/q6qvwr/can_one_still_upgrade_office_2016_vl_build/

## Conclusion

After so much time invested in this issue, researching a lot and looking for solutions everywhere, I must conclude that this behavior is due to a Windows error rather than a bug in Wazuh, since the behavior that is occurring is as expected, if the manager fails to detect the hotfix that solves a vulnerability, it will show that the OS is vulnerable to that specific package, the problem occurs when the operating system does not allow to install this KB.

**Comment by ncvicchi** [comment]
LGTM. This seems to be an issue that exceeds Wazuh to solve since it's a misbehavior of Windows. I recommended to close this issue since no further action is available.
