### ISSUE TITLE
Vulnerability format change for Windows Server 2022 (23H2)

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#21127]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.1 | Vulnerability Detector | Manager | All | Windows Server 2022 |

## Description

Wazuh detects the vulnerability `CVE-2023-36046` for all _Windows Server 2022_. Apparently, `KB5032202` should be installed on those servers to prevent this CVE, however, when consulting the hotfix, it says that it is only applicable for _`Windows Server 2022 version 23H2`_, not for _`Windows Server 2022 version 21H2`_:
- https://support.microsoft.com/help/5032202

This problem is caused by the fact that Windows Server 2022 agents previously did not have any specific versioning (such as **`23H2`**), as can be seen in other older vulnerabilities:
- `CVE-2023-38254`: https://msrc.microsoft.com/update-guide/vulnerability/CVE-2023-38254
```Windows Server 2022 (Server Core installation)```
- `CVE-2023-36046`: https://msrc.microsoft.com/update-guide/vulnerability/CVE-2023-36046
```Windows Server 2022, 23H2 Edition (Server Core installation)```

Such a distinction is currently not found in the NVD either, so it matches all versions of Windows Server 2022:
- CPE: **`cpe:2.3:o:microsoft:windows_server_2022:-:*:*:*:*:*:*:*`**
- NVD - CVE-2023-36046: https://nvd.nist.gov/vuln/detail/CVE-2023-36046#match-10047729

As from now on, it is possible that the format will change, adding this new versioning, it is necessary to carry out an investigation and modify the code to avoid false positives.

### Tasks
- [ ] Research the problem, search for all new cases and analyse the format.
- [ ] Modify the code so that new cases are only reported for their corresponding version.
- [ ] Check if the new format changes only in the MSU or if they also plan to change it in the NVD's CPE.

**Comment by mateocervilla** [comment]
## Update

- Installed a Windows Server 2022 21H2 VM
- Bug successfully reproduced
- Code research

**Comment by mateocervilla** [comment]
## Update
Tried to fill the `CHECK_TYPE` field of the affected vulnerabilities. This correctly filters out cases of the issue but also does so with all `Windows Server 2022` cases.
Now, we are investigating a way to avoid this.

We also observed that after applying the fix, false positive vulnerabilities are still present in the agent database unless they are manually removed. We are working on it too

**Comment by mateocervilla** [comment]
## Update
Continuing with the investigation, after several tests it seems that the solution ends up being in the request made to the database. With some modifications it looks like the vulnerabilities are shown correctly in each version.

**Comment by mateocervilla** [comment]
## Update
We are still investigating part of the code where the `check_type` of each vulnerability is assigned, something may need to be fixed there.
Meanwhile, we installed and tested in a VM with `WS2022 23H2`, since apparently, patches for product: `Windows Server 2022` do not include `23H2` versions unless specified (product: `Windows Server 2022, 23H2`) and this must be contemplated in the code.

**Comment by mateocervilla** [comment]
## Update
Still working on a correct request and code modification for Windows Server 2022 cases.
Testing for vulnerabilities in different Windows versions.

**Comment by mateocervilla** [comment]
## Update
The fix is now complete and tested, pushed in the branch [21127-ws22-vulndet-fix](https://github.com/wazuh/wazuh/tree/21127-ws22-vulndet-fix) with its respective Pull Request https://github.com/wazuh/wazuh/pull/21227

**Comment by MarcelKemp** [comment]
## Update
Researching the new CPE cases for `23h2` in the NVD and raising the fix for https://github.com/wazuh/intelligence-data/issues/30:
-  `cpe:2.3:o:microsoft:windows_server_2022_23h2:-:*:*:*:*:*:x64:*` - [NVD link](https://nvd.nist.gov/products/cpe/detail/738D9857-AC2B-40A3-953F-B8870525291E?namingFormat=2.3&orderBy=CPEURI&keyword=Windows+Server+2022&status=FINAL)
