### ISSUE TITLE
Scheduled upward merges for numbered branches in wazuh repository - Fortnight #1

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#21192]
## Description

The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.7.2-into-4.8.0`.

### 4.7.2
- [x] Update changelog.
- [x] Merge branch `4.7.2` into branch `4.8.0`. #21199
### 4.8.0
- [x] Update changelog. #21219
- [x] Merge branch `4.8.0` into branch `4.8.1`. #21220
### 4.8.1
- [x] Update changelog.
 - #17669 - Talked with framework team, they take care of it.
- [x] Merge branch `4.8.1` into branch `4.8.2`. #21223
### 4.8.2
- [x] Update changelog.
- [x] Merge branch `4.8.2` into branch `master`. #21286
### 4.9.0 (master)
- [x] Update changelog. #21289

### Extra
-  https://github.com/wazuh/wazuh/pull/21281
