### ISSUE TITLE
Maintain production and numbered branches post release  in wazuh repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#21191]
## Description

The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.7.2-into-4.8.0`.

## Tasks

- [ ] Merge branch `4.7.2` into branch `4.8.0`.
- [ ] Merge branch `4.8.0` into branch `4.8.1`.
- [ ] Merge branch `4.8.1` into branch `4.8.2`.
- [ ] Merge branch `4.8.2` into branch `master`.
- [ ] Delete all stage pre-releases for  (https://github.com/wazuh/wazuh/releases).
- [ ] Delete all stage tags for v. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v-rc1, -alpha1, etc.
- [ ] Delete branch ``.
