### ISSUE TITLE
Integrate Wazuh with AWS Security Hub

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#21209]
| Epic branch |
|--|
| [epic-21209-aws-security-hub-integration](https://github.com/wazuh/wazuh/tree/epic-21209-aws-security-hub-integration) |

## Description

We aim to integrate Wazuh with AWS Security Hub, which is a service used to manage the Cloud Security Posture Management within AWS. This service runs checks against security controls and generates control findings to help the user assess compliance against security best practices.

Given the specificity of the Security Hub findings, we need to incorporate this service as one of the supported by our AWS module.

## Issues
- [x] https://github.com/wazuh/wazuh/issues/21165
- [x] https://github.com/wazuh/wazuh/issues/21166
- [x] https://github.com/wazuh/wazuh-documentation/issues/6900
- [x] https://github.com/wazuh/wazuh/issues/22641
- [x] https://github.com/wazuh/wazuh/issues/22505
- [x] ~https://github.com/wazuh/wazuh/issues/21167~ (to be done in https://github.com/wazuh/wazuh/issues/22732)
