### ISSUE TITLE
Support new stage Alpha 2 for 4.8.0

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#21300]
# Description

This issue attempts to support a new stage Alpha 2 for 4.8.0 in the Wazuh system.

# Tasks

Each task must be completed sequentially based on numbering. Tasks within the same subsection might be parallelized.

### wazuh-qa -> @wazuh/qa
- https://github.com/wazuh/wazuh-qa/issues/4823
### wazuh-jenkins -> @wazuh/qa
- https://github.com/wazuh/wazuh-jenkins/issues/6143
### wazuh-automation -> @wazuh/cicd
- https://github.com/wazuh/wazuh-automation/issues/1520
### wazuh-packages -> @wazuh/core
- https://github.com/wazuh/wazuh-packages/issues/2754
### wazuh -> @wazuh/core
- https://github.com/wazuh/wazuh/issues/21299
### wazuh-ansible -> @wazuh/cicd
- https://github.com/wazuh/wazuh-ansible/issues/1189
### wazuh-docker -> @wazuh/cicd
- https://github.com/wazuh/wazuh-docker/issues/1180
### wazuh-puppet -> @wazuh/cicd
- https://github.com/wazuh/wazuh-puppet/issues/889
### wazuh-kubernetes -> @wazuh/cicd
- https://github.com/wazuh/wazuh-kubernetes/issues/566
### wazuh-dashboard-plugins -> @wazuh/frontend
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6283
### qa-integration-framework -> @wazuh/framework
- https://github.com/wazuh/qa-integration-framework/issues/83
### wazuh-documentation -> @wazuh/documentation
- https://github.com/wazuh/wazuh-documentation/issues/6923

## 2. Create pre-release packages for v4.8.0-alpha2 using tags from task 1. -> @wazuh/qa
- [x] https://github.com/wazuh/wazuh-jenkins/issues/6147
- [x] https://github.com/wazuh/wazuh-jenkins/issues/6164

## 3. Create and assign testing issues for 4.8.0 Alpha 2. -> @davidjiglesias
- [x] Create issues https://ci.wazuh.info/view/Procedures/job/Procedure_cicd_release_issues/140/

## 4.Set up demo environment for 4.8.0 Alpha 2. -> @wazuh/cicd

- https://github.com/wazuh/wazuh-automation/issues/1521
