### ISSUE TITLE
Post release tasks for 4.7.2

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#21317]
## Description

This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.7.2.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.7.2-into-4.8.0`.

## Tasks

- [x] Merge branch `4.7.2` into branch `4.8.0`. #21329
- [x] Merge branch `4.8.0` into branch `4.8.1`. #21341
- [x] Merge branch `4.8.1` into branch `4.8.2`. #21347
- [ ] Merge branch `4.8.2` into branch `master`. #21397
- [ ] Publish GitHub release as latest.
- [ ] Delete all stage pre-releases for 4.7.2 (https://github.com/wazuh/wazuh/releases).
- [ ] Delete all stage tags for v4.7.2. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.7.2-rc1, 4.7.2-alpha1, etc.
- [ ] Fast-forward definitive tag v4.7.2 to `4.7` branch.
- [ ] Delete branch `4.7.2`.
