### ISSUE TITLE
AWS CloudTrail integration, Agent don't show alerts on dashboard, of logs stored in a AWS Bucket

### ISSUE THREAD

**Issue by tdrauncieal** [wazuh/wazuh#21474]
| Affected integration | Issue related |
|---|---|
| AWS | #21372 |

## Description
After following the steps described in the [this guide](https://documentation-dev.wazuh.com/v4.7.0-alpha1/cloud-security/amazon/services/prerequisites/dependencies.html) to configure and test the integration between `AWS Cloudtrail` and the `wazuh agent`, I verify that the `dashboard` does not show events, however, I can verify that there are no connection errors and others reported by the manager and also I check that the bucket supplied for the test contains logs, which should be reported.

wazuh agent configuration (`/var/ossec/etc/ossec.conf`)
```html
  <wodle name="aws-s3">
    <disabled>no</disabled>
    <interval>10m</interval>
    <run_on_start>yes</run_on_start>
    <skip_on_error>no</skip_on_error>

    <bucket type="cloudtrail">
      <name>aws-cloudtrail-logs-966237403726-09245154</name>
      <aws_profile>default</aws_profile>
    </bucket>
  </wodle>

``` 
wazuh agent credentials (`~/.aws/credentials`)
```
[default]
aws_access_key_id=AK...KI
aws_secret_access_key=Nt....Rf
region=us-east-1

``` 
<details><summary>dashboard screenshot</summary>
<p>

![image](https://github.com/wazuh/wazuh/assets/93778492/224c9290-1e59-410d-80b2-8d855f9bcab9)

</p>

</details> 
<details><summary>bucket showing logs</summary>
<p>

![image](https://github.com/wazuh/wazuh/assets/93778492/783e5321-b072-456b-ae53-bfb6ac4d705d)

</p>
</details> 

<details><summary>manager logs</summary>
<p>

```shell
2024/01/16 15:20:46 wazuh-modulesd:aws-s3: INFO: Executing Bucket Analysis: (Bucket: aws-cloudtrail-logs-966237403726-09245154, Type: cloudtrail, Profile: default)
2024/01/16 15:20:51 wazuh-modulesd:aws-s3: INFO: Fetching logs finished.
2024/01/16 15:30:46 wazuh-modulesd:aws-s3: INFO: Starting fetching of logs.
2024/01/16 15:30:46 wazuh-modulesd:aws-s3: INFO: Executing Bucket Analysis: (Bucket: aws-cloudtrail-logs-966237403726-09245154, Type: cloudtrail, Profile: default)
2024/01/16 15:30:50 wazuh-modulesd:aws-s3: INFO: Fetching logs finished.
2024/01/16 15:40:46 wazuh-modulesd:aws-s3: INFO: Starting fetching of logs.
2024/01/16 15:40:46 wazuh-modulesd:aws-s3: INFO: Executing Bucket Analysis: (Bucket: aws-cloudtrail-logs-966237403726-09245154, Type: cloudtrail, Profile: default)
2024/01/16 15:40:51 wazuh-modulesd:aws-s3: INFO: Fetching logs finished.

``` 

</p>
</details> 

## Tasks
- [ ] Test in a manager.
- [X] Test in an agent.
- [ ] Unit tests without failures. Updated if there are any relevant changes.
- [X] Integration tests without failures. Updated if there are any relevant changes.
- [ ] Update the documentation if necessary.
- [ ] Add entry to the changelog if necessary.

**Comment by Selutario** [comment]
The AWS CloudTrail integration code is the same in managers and agents, so this troubleshooting can be carried out in:
- https://github.com/wazuh/wazuh/issues/21472
