### ISSUE TITLE
Add support for inspector service v2

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#21532]
## Description

During the investigation in https://github.com/wazuh/wazuh/issues/21419, we found that the [Amazon Inspector Classic service](https://docs.aws.amazon.com/inspector/v1/userguide/inspector_introduction.html) is available only in a limited set of [regions](https://docs.aws.amazon.com/general/latest/gr/inspector.html#inspector_region).

AWS has since launched a rearchitected and redesigned version of the service called [Amazon Inspector (v2)](https://docs.aws.amazon.com/inspector/latest/user/what-is-inspector.html), which offers broader regional coverage ([see regions](https://docs.aws.amazon.com/general/latest/gr/inspector2.html#inspector2_region)) along with enhanced features and integrations.

This issue aims to add support for the new Amazon Inspector v2 service **while maintaining compatibility with the current Inspector Classic (v1)**. The implementation must ensure that users can continue to receive and process findings from both versions of the service based on Wazuh configuration.

> [!Note]
> The [Moving to the new Amazon Inspector](https://docs.aws.amazon.com/inspector/v1/userguide/inspector-migration.html) guide might be useful.

## Tasks

- [x] Investigate the differences between v1 and v2 APIs and event formats.
- [x] Design a compatibility layer or detection mechanism to support both versions based on user configuration.
- [x] Implement support for ingesting and parsing events from Amazon Inspector v2.
- [x] Add appropriate configuration options if necessary (e.g., to enable/disable one version).
- [x] Update documentation to reflect dual-version support.

**Comment by Selutario** [comment]
We need to open an issue to show a deprecation warning when using the integration (and probably in documentation too)

**Comment by javiersanchz** [comment]
## Update

### Comparison of AWS Inspector Classic (v1) vs Inspector v2

| Region Name                | Region Code       | Inspector v1 | Inspector v2 |
|---------------------------|-------------------|--------------|--------------|
| US East (N. Virginia)     | us-east-1         | ✅           | ✅           |
| US East (Ohio)            | us-east-2         | ✅           | ✅           |
| US West (N. California)   | us-west-1         | ✅           | ✅           |
| US West (Oregon)          | us-west-2         | ✅           | ✅           |
| Canada (Central)          | ca-central-1      | ❌           | ✅           |
| Canada West (Calgary)     | ca-west-1         | ❌           | ✅           |
| South America (São Paulo) | sa-east-1         | ❌           | ✅           |
| Europe (Ireland)          | eu-west-1         | ✅           | ✅           |
| Europe (London)           | eu-west-2         | ✅           | ✅           |
| Europe (Paris)            | eu-west-3         | ❌           | ✅           |
| Europe (Frankfurt)        | eu-central-1      | ✅           | ✅           |
| Europe (Zürich)           | eu-central-2      | ❌           | ✅           |
| Europe (Milan)            | eu-south-1        | ❌           | ✅           |
| Europe (Spain)            | eu-south-2        | ❌           | ✅           |
| Europe (Stockholm)        | eu-north-1        | ✅           | ✅           |
| Israel (Tel Aviv)         | il-central-1      | ❌           | ✅           |
| Middle East (Bahrain)     | me-south-1        | ✅           | ✅           |
| Middle East (UAE)         | me-central-1      | ❌           | ✅           |
| Africa (Cape Town)        | af-south-1        | ❌           | ✅           |
| Asia Pacific (Tokyo)      | ap-northeast-1    | ✅           | ✅           |
| Asia Pacific (Seoul)      | ap-northeast-2    | ✅           | ✅           |
| Asia Pacific (Osaka)      | ap-northeast-3    | ❌           | ✅           |
| Asia Pacific (Singapore)  | ap-southeast-1    | ❌           | ✅           |
| Asia Pacific (Sydney)     | ap-southeast-2    | ✅           | ✅           |
| Asia Pacific (Jakarta)    | ap-southeast-3    | ❌           | ✅           |
| Asia Pacific (Melbourne)  | ap-southeast-4    | ❌           | ✅           |
| Asia Pacific (Malaysia)   | ap-southeast-5    | ❌           | ✅           |
| Asia Pacific (Thailand)   | ap-southeast-7    | ❌           | ✅           |
| Asia Pacific (Mumbai)     | ap-south-1        | ✅           | ✅           |
| Asia Pacific (Hyderabad)  | ap-south-2        | ❌           | ✅           |
| Asia Pacific (Hong Kong)  | ap-east-1         | ❌           | ✅           |
| Mexico (Central)          | mx-central-1      | ❌           | ✅           |


I've been reviewing how the AWS module currently retrieves logs from Amazon Inspector Classic (`v1`), using `boto3.client('inspector') `along with `list_findings()` and `describe_findings()`. From there, I started looking into the differences with Inspector `v2`, the possibility of integrating it (by switching to `boto3.client('inspector2'`)), and comparing the structure of the findings, which in `v2` are more detailed and enriched. Now I'm checking how to fetch logs from `v2` to see how they could fit into the current logic.

**Comment by javiersanchz** [comment]
## Update
After discussing with the team, the following decision has been made:

If the region supports both Inspector v1 and v2 → collect events from both versions.

If the region supports only Inspector v2 → collect only v2 events.

I’m still working on implementing the changes to process v2 events, as they’re not being collected yet. I need to investigate whether this is due to a lack of generated Inspector v2 events in AWS (in which case I’ll need to generate them), or if the implemented changes are not working as expected.

For now, I’m putting this task `on hold` to prioritize the release of version `4.13.0 RC1`.

**Comment by javiersanchz** [comment]
## Update

I was generating events from Inspector v2.

I conducted tests to see how to process these events and fix errors:


```console
root@wazuh-master:/# /var/ossec/wodles/aws/aws-s3 -sr inspector -s 2022-JAN-26 -r us-east-1 -d 2
DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Getting alerts from "us-east-1" region.
DEBUG: +++ Region 'us-east-1' added to the configuration
DEBUG: No retries configuration found in profile config. Generating default configuration for retries: mode: standard - max_attempts: 10
DEBUG: Created Config object using profile: 'default' configuration
DEBUG: +++ Table does not exist; create
DEBUG: +++ [v1] Listing findings from 2022-01-26 00:00:00
DEBUG: +++ [v2] Listing findings from 2022-01-26 00:00:00
DEBUG: +++ [v2] Error getting findings: Parameter validation failed:
Unknown parameter in filterCriteria: "creationTime", must be one of: awsAccountId, codeVulnerabilityDetectorName, codeVulnerabilityDetectorTags, codeVulnerabilityFilePath, componentId, componentType, ec2InstanceImageId, ec2InstanceSubnetId, ec2InstanceVpcId, ecrImageArchitecture, ecrImageHash, ecrImagePushedAt, ecrImageRegistry, ecrImageRepositoryName, ecrImageTags, epssScore, exploitAvailable, findingArn, findingStatus, findingType, firstObservedAt, fixAvailable, inspectorScore, lambdaFunctionExecutionRoleArn, lambdaFunctionLastModifiedAt, lambdaFunctionLayers, lambdaFunctionName, lambdaFunctionRuntime, lastObservedAt, networkProtocol, portRange, relatedVulnerabilities, resourceId, resourceTags, resourceType, severity, title, updatedAt, vendorSeverity, vulnerabilityId, vulnerabilitySource, vulnerablePackages
DEBUG: +++ 128 events collected and processed in us-east-1
```
It happens because  Inspector v2 does not support creationTime as a filter, unlike Inspector Classic (v1), where you can filter findings by `creationTime`.

I was also encountering other errors such as:

```console
...
DEBUG: +++ [v2] Listing findings from 2022-01-26 00:00:00
DEBUG: +++ [v2] Error getting findings: An error occurred (ValidationException) when calling the BatchGetFindingDetails operation: 1 validation error detected: Value at 'findingArns' failed to satisfy constraint: Member must have length less than or equal to 10
DEBUG: +++ 128 events collected and processed in us-east-1
```

This error is related to a limitation of the` Inspector v2 API`. The method `batch_get_finding_details` only accepts up to `10 ARNs `per call, so the findingArns should be split into `chunks` of `10`. This limit is officially documented by AWS.


```console
DEBUG: +++ [v2] Processing 0 findings in chunk 1
DEBUG: +++ [v2] Error retrieving finding arn:aws:inspector2:us-east-1:xxxxxx:finding/7xxxxxxfd: Corresponding finding details not found
DEBUG: +++ [v2] Error retrieving finding arn:aws:inspector2:us-east-1:xxxxxxx:finding/5xxxxxxxx6: Corresponding finding details not found
DEBUG: +++ There are no new events in the "us-east-1" region
```

Once those errors were fixed, ARNs of findings in Inspector v2 were found. However, when attempting to retrieve their details, the API returned that they do not exist or are not available. I need to access CloudTrail event history to check if these events are malformed, if I’m iterating over them incorrectly, or if there’s another cause.

I opened the issue https://github.com/wazuh/internal-devel-requests/issues/2712 to request permissions for CloudTrail event history.

**Comment by javiersanchz** [comment]
## Update

I’ve been making changes, but the same error still appears when trying to fetch `v2` events. I still don’t have the necessary permissions to view these events in `CloudTrail`. Blocking the issue until I receive those permissions.

**Comment by javiersanchz** [comment]
## Update

I was reviewing the events in `CloudTrail`.

I was conducting more tests by adding debug to verify that events from `v1` and `v2` are being retrieved, and that both are functioning correctly:

```console
root@wazuh-master:/# /var/ossec/wodles/aws/aws-s3 -sr inspector -s 2025-JUL-28 --reparse -r us-east-1 -d 2
DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Getting alerts from "us-east-1" region.
DEBUG: +++ No 'region' found in profile 'default'
DEBUG: No retries configuration found in profile config. Generating default configuration for retries: mode: standard - max_attempts: 10
DEBUG: Created Config object using profile: 'default' configuration
DEBUG: +++ [v1] Listing findings from 2025-07-28 00:00:00
DEBUG: +++ [v2] Listing findings from 2025-07-28 00:00:00
DEBUG: [v2] Getting details for chunk: ['arn:aws:inspector2:us-east-1:xxxxxx:finding/xxxxxxx', 'arn:aws:inspector2:us-east-1:xxxxx:finding/xxxxxx', 'arn:aws:inspector2:us-east-1:xxxxx:finding/xxxx', 'arn:aws:inspector2:us-east-1:xxxxx:finding/xxxxx', 'arn:aws:inspector2:us-east-1:xxxxx:finding/xxxxx', 'arn:aws:inspector2:us-east-1:xxxxxx:finding/xxxxx', 'arn:aws:inspector2:us-east-1:xxxxxx:finding/xxxxxx', ...
...
```

```console
DEBUG: {"integration": "aws", "aws": {"cwes": [], "epssScore": 0.00014, "evidences": [], "exploitObserved": {}, "findingArn": "arn:aws:inspector2:us-east-1:xxxxxx:finding/xxxxx", "referenceUrls": ["https://git.kernel.org/stable/c/xxxxxx", "https://git.kernel.org/stable/c/xxxxxx", "https://git.kernel.org/stable/c/xxxxx", "https://nvd.nist.gov/vuln/detail/xxxxx", "https://git.kernel.org/stable/c/xxxxx", "https://git.kernel.org/stable/c/xxxxx", "https://git.kernel.org/stable/c/xxxxx"]}}
```

```console
root@wazuh-master:/# /var/ossec/wodles/aws/aws-s3 -sr inspector -d 2 -s 2022-JAN-26 -r us-east-1 --reparse
DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Getting alerts from "us-east-1" region.
DEBUG: +++ No 'region' found in profile 'default'
DEBUG: No retries configuration found in profile config. Generating default configuration for retries: mode: standard - max_attempts: 10
DEBUG: Created Config object using profile: 'default' configuration
DEBUG: +++ Listing findings from 2022-01-26 00:00:00
DEBUG: +++ [v1] Processing 6 events
DEBUG: +++ [v1] Processing 4 events
...
DEBUG: +++ [v1] Processing 13 events
DEBUG: +++ [v1] Processing 8 events
DEBUG: +++ [v1] Processing 4 events
DEBUG: +++ [v2] Processing 100 events
DEBUG: +++ [v2] Processing 100 events
DEBUG: +++ [v2] Processing 100 events
...
```

I am still looking into generating alerts for v2 events, for now, I am only receiving v1 events.

**Comment by javiersanchz** [comment]
## Update

- I finish with some remaining changes.
- I create and modify new unit tests.
- Documentation of tests is pending, and I need to create a PR.

**Comment by javiersanchz** [comment]
## Update

- Tests were conducted on the functionality of Inspector v1 and v2.

- The unit tests were updated.

- The documentation team should be informed to update the documentation related to Inspector: https://documentation.wazuh.com/current/cloud-security/amazon/services/supported-services/inspector.html

- Regarding the AWS Integration Tests, I believe the issue https://github.com/wazuh/wazuh/issues/30046 should be reopened to address the necessary permissions in the AWS account.

On the other hand, as discussed, the following was implemented:

- If the region supports both Inspector v1 and v2 → collect events from both versions.

- If the region supports only Inspector v2 → collect only v2 events.

However, Inspector v2 generates significantly more events than v1 because it is designed to perform continuous and automatic scans across multiple resources (`EC2`, `ECR`, `Lambda`, etc.), unlike v1, which relies on manual scans. Additionally, v2 reports more granular and repeated findings across different contexts, which greatly increases the volume of events.

As a result, when processing Inspector events, the vast majority come from v2.

It was decided to leave it as is, bringing all events generated from v2, although it could be filtered by events, perhaps based on a certain `severity` level or a minimum `riskScore`, since there are simpler and more straightforward events such as:


```console
DEBUG: {"integration": "aws", "aws": {"cwes": [], "epssScore": 0.00017, "evidences": [], "exploitObserved": {}, "findingArn": "arn:aws:inspector2:us-east-1:xxxxx:finding/xxxxxx", "referenceUrls": ["https://git.kernel.org/stable/c/xxxxxx", "https://git.kernel.org/stable/c/xxxxxx", "https://git.kernel.org/stable/c/xxxxxx", "https://nvd.nist.gov/vuln/detail/CVE-2025-38360"], "source": "inspector2"}}
```

and more important events with more information, such as:

```console
DEBUG: {"integration": "aws", "aws": {"cwes": ["CWE-330"], "epssScore": 0.00024, "evidences": [{"evidenceDetail": "4 sightings on 2 sources: Telegram - Other Channels, Lore Kernel - Linux CVE Announce. 2 related malware families: Rootkit, Kernel. Most recent link (Jul 28, 2025): https://t.me/darkwebinformercvealerts/22748", "evidenceRule": "Recently Linked to Malware", "severity": "Medium"}, {"evidenceDetail": "1 sighting on 1 source: Recorded Future Vulnerability Analysis. CVSS v4 Score (5.9) calculated using CVSS Base Score (5.9) and Recorded Future Threat Metrics. Most recent link (Jul 25, 2025): https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2025-38458", "evidenceRule": "Vendor Severity: Medium", "severity": "Medium"}], "exploitObserved": {"lastSeen": "2025-07-29 01:16:36+00:00"}, "findingArn": "arn:aws:inspector2:us-east-1:xxxxxx:finding/xxxxxxx", "referenceUrls": ["https://nvd.nist.gov/vuln/detail/CVE-2025-38458", "https://git.kernel.org/stable/c/xxxxxxxxx", "https://git.kernel.org/stable/c/xxxxxxxxx", "https://git.kernel.org/stable/c/xxxxxx", "https://git.kernel.org/stable/c/xxxxxx", "https://git.kernel.org/stable/c/xxxxxx", "https://git.kernel.org/stable/c/xxxxxx", "https://git.kernel.org/stable/c/xxxxx", "https://git.kernel.org/stable/c/xxxxxx"], "riskScore": 35, "tools": ["Kernel"], "ttps": ["T1588.001"], "source": "inspector2"}}
```

**Comment by javiersanchz** [comment]
## Update

- The requested changes to the Inspector script were added.
- Issue [Modify and expand AWS integration tests related to Inspector #31262](https://github.com/wazuh/wazuh/issues/31262) was created to fix the previously failing tests and expand the related test coverage.

> Note : https://github.com/wazuh/wazuh/actions/runs/16800782094/job/47581468252?pr=31163

**Comment by jnasselle** [comment]
During https://github.com/wazuh/wazuh/issues/31262, it was found that the current implementation does not work on the following aspects:

- The Inspector v2 endpoint/action (batch_get_finding_details), which is used to fetch the information, does not provide complete and useful data.
  - While `batch_get_finding_details` retrieves vague information, the `list_findings` retrieves more accurate information and is the one shown by AWS Console 
  - Just using `list_findings` will improve performance because it will list and retrieve findings information simultaneously 
- The current rules in the Wazuh default ruleset (https://github.com/wazuh/wazuh/blob/4.14.0/ruleset/rules/0350-amazon_rules.xml#L540-L581) rely on `aws.severity` information that is not compatible with `batch_get_finding_details`, but with `list_findings`. This means that the current Inspector v2 implementation does not trigger any rule.

Reopening this issue

**Comment by javiersanchz** [comment]
## Update

- Changed the log retrieval method from `batch_get_finding_details` to `list_findings`.
- Verified the received events, the generated alerts, and the related Inspector rules.
- Updated the corresponding unit tests.

**Comment by javiersanchz** [comment]
## Update

Replaced `firstObservedAt` with `updatedAt` in `Inspector v2`.
Unlike `v1` (immutable findings with `createdAt`), `v2` findings are dynamic and can change. Using `updatedAt` ensures both new and updated findings are collected, preventing important changes from being missed.

Revised again:
- Event processing, alert generation, and rule triggering from them
- Unit tests
