### ISSUE TITLE
Transition to Wazuh Keystore for Indexer Configuration

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#21573]
### Description

This epic focuses on transitioning from the existing approach of storing user and password configuration on the indexer tag directly in the `ossec.conf` file to a more secure and manageable method using a dedicated Wazuh keystore. By implementing this change, we aim to enhance security and improve the management of sensitive configuration information.

### User Stories

- As a security-conscious user, I want my configuration information to be stored securely and not exposed in plain text within the `ossec.conf` file.
- As a system administrator, I want a more efficient and secure way to manage sensitive configuration data, such as passwords, for the indexer.
- As a developer, I want to implement a keystore solution that allows for easy retrieval and management of configuration data within the Wazuh ecosystem.

### Proposed Solution

The proposed solution involves the following key steps:

1. **Keystore Implementation:**
   - Develop a Wazuh-specific keystore where sensitive configuration data, including user credentials for the indexer, can be securely stored.

2. **Refactor Indexer credentials loading:**
   - Modify the Wazuh indexer to load configuration data from the new keystore.

3. **Documentation and User Guidance:**
   - Update documentation to guide users and administrators on how to use the Wazuh keystore for storing sensitive configuration data.

4. **Installation:**
   - Update the installation process to execute a tool to write the indexer connector credentials.

### Issue dependency
```mermaid
---
title: Issue dependency
---
stateDiagram-v2
    [*] --> Documentation#6984
    Documentation#6984 --> [*]

    [*] --> Wazuh#21574
    Wazuh#21574 --> [*]

    [*] --> Wazuh#21575
    Wazuh#21575 --> Wazuh#21576
    Wazuh#21575 --> Wazuh#21577

    [*] --> Wazuh#21606
    Wazuh#21606 --> Wazuh#21576
    Wazuh#21606 --> Wazuh#21577

    Wazuh#21577--> [*]
    Wazuh#21576--> [*]

    [*] --> InternalDevelRequest#707
    InternalDevelRequest#707 --> [*]

    [*] --> Wazuhpackages#2791
    Wazuhpackages#2791 --> [*]

 ```   
#### Subtasks and User Stories
- [x] wazuh/wazuh#21574
- [x] wazuh/wazuh#21575
- [x] wazuh/wazuh#21606
- [x] wazuh/wazuh#21576
- [x] wazuh/wazuh#21577
- [x] wazuh/wazuh-packages#2791
- [x] #21668
- [x] wazuh/wazuh-documentation#6984
- [x] wazuh/internal-devel-requests#707

### Definition of Done

- The Wazuh-specific keystore has been developed and integrated into the Wazuh manager.
- Configuration loading from the new keystore is functional and has been tested thoroughly.
- Documentation and user guidance for using the keystore have been updated.
- Installation success in all wazuh common ways.

### DRI
@Dwordcito

**Comment by ncvicchi** [comment]
Changed ETA waiting for several PRs to be merged

**Comment by Dwordcito** [comment]
Waiting issue assigned to CICD(https://github.com/wazuh/internal-devel-requests/issues/707) to close this issue.
