### ISSUE TITLE
Support new stage Beta 1 for 4.8.0 in wazuh repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#21724]
## Description

This issue attempts to support a new stage Beta 1 for 4.8.0 in the wazuh repository.

## Tasks

- [x] Ensure changelog is updated for 4.8.0 (if applicable).
- [x] Bump revision for branch 4.8.0 on wazuh repository.
- [x] Create tag v4.8.0-beta1 from branch 4.8.0 on wazuh repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh/releases/tag/v4.8.0-beta1.

**Comment by vikman90** [comment]
## Status update

This issue is **blocked** until @wazuh/data-pirates fixes these problems:

```
2024/02/05 08:20:23 indexer-connector: WARNING: No username and password found in the keystore, using default values.
```
```
2024/02/05 08:20:23 indexer-connector: WARNING: Error initializing IndexerConnector: Couldn't connect to server, we will try again after 2 seconds.
```
```
2024/02/05 08:20:24 wazuh-modulesd:vulnerability-scanner: ERROR: VulnerabilityScannerFacade::start: Couldn't find column family: 'vendor_map'
```
