### ISSUE TITLE
Support new stage Beta 1 for 4.8.0

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#21725]
# Description

This issue attempts to support a new stage Beta 1 for 4.8.0 in the Wazuh system.

# Tasks

Each task must be completed sequentially based on numbering. Tasks within the same subsection might be parallelized.

### wazuh-qa -> @wazuh/qa
- https://github.com/wazuh/wazuh-qa/issues/4911
### wazuh-jenkins -> @wazuh/qa
- https://github.com/wazuh/wazuh-jenkins/issues/6229
### wazuh-automation -> @wazuh/cicd
- https://github.com/wazuh/wazuh-automation/issues/1543
### wazuh-packages -> @wazuh/core
- https://github.com/wazuh/wazuh-packages/issues/2810
### wazuh -> @wazuh/core
- https://github.com/wazuh/wazuh/issues/21724
### wazuh-ansible -> @wazuh/cicd
- https://github.com/wazuh/wazuh-ansible/issues/1202
### wazuh-docker -> @wazuh/cicd
- https://github.com/wazuh/wazuh-docker/issues/1199
### wazuh-puppet -> @wazuh/cicd
- https://github.com/wazuh/wazuh-puppet/issues/915
### wazuh-kubernetes -> @wazuh/cicd
- https://github.com/wazuh/wazuh-kubernetes/issues/579
### wazuh-dashboard-plugins -> @wazuh/frontend
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6382
### qa-integration-framework -> @wazuh/framework
- https://github.com/wazuh/qa-integration-framework/issues/90
### wazuh-documentation -> @wazuh/documentation
- https://github.com/wazuh/wazuh-documentation/issues/7008

## 2. Create pre-release packages for v4.8.0-beta1 using tags from task 1. -> @wazuh/qa
- [x] https://github.com/wazuh/wazuh-jenkins/issues/6236
- [x]  https://github.com/wazuh/wazuh-jenkins/issues/6235

## 3. Create and assign testing issues for 4.8.0 Beta 1. -> @davidjiglesias
- [x] Create E2E issues
- [x] Create release testing issues

## 4.Set up demo environment for 4.8.0 Beta 1. -> @wazuh/cicd

- https://github.com/wazuh/wazuh-automation/issues/1544

**Comment by rauldpm** [comment]
All tasks have been completed
