### ISSUE TITLE
Set up an automated process to upload generated debug symbols to a designated storage location.

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#21736]
|Related issue|
|-|
|[#187](https://github.com/wazuh/internal-devel-requests/issues/187)|
|https://github.com/wazuh/wazuh/issues/22080|
|https://github.com/wazuh/wazuh-jenkins/issues/6200|

## Description

This issue aims to automate the upload process to a designated location (development/wazuh/x.y/main/packages, see https://github.com/wazuh/wazuh-jenkins/issues/6200#issuecomment-1977510703)** of the debug symbols generated on the package generation process of DEB, RPM, Windows, and macOS platforms, both for the agent and for the manager packages (when applicable).

It must also be considered auto-deletion policies for packages to be applied to debug symbols.

## Goals
For every platform, these goals must be achieved:
- Modify the package upload process workflows to accommodate the upload of its related debug symbols to the designated location (development/wazuh/x.y/main/packages, see https://github.com/wazuh/wazuh-jenkins/issues/6200#issuecomment-1977510703).
- Uploaded symbols should be securely stored and easily accessible for debugging purposes.
- Analyze and modify accordingly the auto-deletion process to comply with auto-deletion policies **_(TBD by management)_**
- Test & verify that these behaviors are satisfied

## Plan:

- [x] [Set up an automated process to upload generated debug symbols to a designated storage location (RPM)](https://github.com/wazuh/wazuh/issues/22942)
- [x] [Set up an automated process to upload generated debug symbols to a designated storage location (DEB)](https://github.com/wazuh/wazuh/issues/22944)
- [ ] [Set up an automated process to upload generated debug symbols to a designated storage location (Windows)](https://github.com/wazuh/wazuh/issues/22947)
- [x] [Set up an automated process to upload generated debug symbols to a designated storage location (macOS)](https://github.com/wazuh/wazuh/issues/22946)

### DoD
For every platform (RPM, DEB, Windows & macOS):
- Debug symbols associated with their corresponding binary are automatically uploaded to their designated location.
- Auto-deletion policies are considered and implemented
- Verification of proper behavior is performed

Approval
DRI Name: @ncvicchi 
Objective: Generate debug symbols

**Comment by ncvicchi** [comment]
This issue will stay blocked unit managment informs which should be the storage location for every debug symbol associated to a package.

**Comment by ncvicchi** [comment]
> [@ncvicchi](https://github.com/ncvicchi) check the notes for the definition.

I will update the description with them. Thanks!

**Comment by ncvicchi** [comment]
Blocked by #22947

**Comment by ncvicchi** [comment]
Moved ETA to 08/05 based on [Adapt agent package generation workflows with VPN and allocator module](https://github.com/wazuh/wazuh/issues/22839#top) ETA
