### ISSUE TITLE
SPIKE - Research external software to manage dependencies

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#21759]
## Description
This issue aims to investigate existing dependency managers to see if it would be possible to integrate any of them with Wazuh, avoiding having to manually manage dependencies as we currently do.

On the one hand, it is necessary to verify that the dependency manager allows making use of custom packages or repositories, as well as to verify how to manage special OSes that need specific dependencies (such as AIX or HP-UX).

In addition to this, it would be a good idea to find out about all the options it offers, and the requirements needed to add it to the project.

Once you have done your research, reflect on the pros and cons of the dependency manager and decide whether to integrate it into the next issue:
- https://github.com/wazuh/wazuh/issues/16882

The main dependency manager to be investigated is: [vcpkg](https://vcpkg.io/en/). Although the possibility of researching and using another one is not ruled out.

## Tasks
- [x] Investigate dependency managers.
- [ ] Document, adapt and test `vcpkg`.
- [ ] Summarise all the information obtained from the tool and reflect it in a comment.

**Comment by mjcr99** [comment]
## Issue update:
**(08/02/2024)** Researching vcpkg capabilities and available dependencies. Running small POC to fully understand required changes and possible impact.
