### ISSUE TITLE
Engine - Research and Development of an Automatic DB Update System for MaxMind Integration

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#21833]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| Latest | Wazuh Engine | Manager | Packages/Sources | All |
### Description

This issue focuses on the research and development of an automatic update system for MaxMind databases within the Wazuh-Engine. Given that MaxMind updates its GeoIP and ASN databases twice a week, it's crucial to have an automated system in place to ensure the Wazuh-Engine always utilizes the most current data for event enrichment.

### Objectives

- **Research Best Practices**: Investigate existing methods and best practices for automating database updates, specifically for MaxMind's GeoIP and ASN databases.
- **Authentication and Configuration**: Develop a system that can handle authentication with MaxMind's servers, requiring configuration options for the user's license key and account ID.
- **Automatic Download and Update**: Create a mechanism within the Wazuh-Engine that automatically downloads and updates the MaxMind databases at the specified update frequency.
- **Error Handling and Logging**: Ensure robust error handling and logging mechanisms are in place for the update process to notify administrators of any issues.

### Tasks

- [x] Conduct thorough research on automated update systems for databases, focusing on authentication methods and secure data transfer.
- [x] Implement the API to download the database from a specified URL
- [x] Implements download validation through hashing
- [x] Implement db replacement at runtime without destroying the policy
- [x] Develop error handling and logging functionalities to manage and report any issues encountered during the update process.
- [x] Test the update system to ensure reliability and efficiency, adjusting for any identified improvements.

### Additional Considerations

- **Security**: Ensure that the update process is secure, protecting the license key and account ID, and verifying the integrity of downloaded databases.
- **Performance Impact**: Assess the impact of the update process on the Wazuh-Engine's performance, optimizing to minimize disruption.
- **Documentation**: Document the update system's implementation, configuration, and operation within the Wazuh-Engine documentation.

### Acceptance Criteria

- A fully functional automatic update system for MaxMind databases is integrated into the Wazuh-Engine.
- Users can easily configure their MaxMind license and account ID within the Wazuh-Engine.
- The Wazuh-Engine can automatically download and update MaxMind databases twice a week without manual intervention.
- Comprehensive documentation is available to guide users through configuring and troubleshooting the update system.

**Comment by dlouzan** [comment]
@JcabreraC I have just bumped into these new issues for tracking MaxMind's GeoIP2 support after posting in https://github.com/wazuh/wazuh/issues/4496#issuecomment-1938587470 🙇 

Just adding my two cents (because we already integrate the MaxMind DB download system into our own servers): it'd be an option to avoid wazuh itself from configuring this, and just rely on the users' having to set it up on their servers, providing ofc documentation, configuration settings and options.

In our case, we have a common ansible role for servers that need GeoIP data, which sets up https://github.com/maxmind/geoipupdate, and sets up a systemd server and timer that takes care of running the updater. The only input needed are the MaxMind account id and license key.

If wazuh provided settings for configuring the location of the downloaded db files, that'd be enough. I think this would even be supported properly on k8s deployments, by documenting how to mount the DB directory into the wazuh-manager STS.

**Comment by juliancnn** [comment]
Hello @dlouzan ,

Thank you for your engagement and valuable suggestion regarding the MaxMind DB update process.

It's worth noting that this particular issue pertains to the Wazuh-Engine, which is in development as a future replacement for Wazuh-Analysisd. Our goal with the Wazuh-Engine is to create a more streamlined and user-friendly experience that reduces the need for manual intervention and simplifies maintenance.

We're designing the Wazuh-Engine to handle updates automatically, as opposed to the current process with wazuh-analysisd that requires user-initiated steps. We envision a system that not only meets current needs but also adapts to future improvements with ease.

For more context on the development and overarching goals of the Wazuh-Engine, you can refer to the epic issue on GitHub: [Wazuh-Engine Development Epic](https://github.com/wazuh/wazuh/issues/11334).

We greatly appreciate your contribution to this discussion and will keep in mind your insights as we continue to develop and refine the update mechanism.

**Comment by juliancnn** [comment]
UPDATE:

New branch `21833-engine-geoip-update`  (PR Pending..). 
[Added (temporary) modification](https://github.com/wazuh/wazuh/commit/4faaf6363719c53c670bdcc16e395b7cb2097b13), to automatically download and configure maxmind databases in wazuh-engine, only configuring the license in env var:

```bash
MM_LICENCE_KEY=XXX vagrant up 
```

**Comment by gdiazlo** [comment]
We will download the database from a Wazuh managed URL for now. We might revisit this in the future, but I believe this strategy adds to the flexibility we need now.

**Comment by dlouzan** [comment]
@gdiazlo Honest question: are you even legally able to host them yourselves? I thought that the GeoIP2 and GeoLite2 database files licensing require an account and license keys, even if free. Otherwise I think you need to enter a redistribution agreement with them e.g. <https://www.maxmind.com/en/geolite2-commercial-redistribution> 🙇

**Comment by gdiazlo** [comment]
I believe that's a commercial redistribution, but we won't redistribute it commercially. We will charge nothing for it. Also, we won't take any credit, furthermore as per the license, we must state that the database comes from MaxMind in our documentation and any marketing material. I've contacted MaxMind already about this. Just in case, I'll contact them again.

**Comment by JavierBejMen** [comment]
## Update
- Added method to update the geoip database from an URL with checksum verification
- Added tests
- Working on user API

**Comment by JavierBejMen** [comment]
## Update
Working on simplification of module classes and synchronization mechanisms

**Comment by JavierBejMen** [comment]
## Update
- Finished geo API
- Updated vagrantfile 
- Updated mmdb helper and tests
- Working on geo component tests

**Comment by JavierBejMen** [comment]
## Update
- Added component tests
- Fixed health tests and threadsanitizer errors
- Live review
