### ISSUE TITLE
Support new Wazuh version 5.0.0

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#21891]
# Description

This issue attempts to support a new version 5.0.0 in the Wazuh system. It includes tracking the generation of issues, projects, and numbered branches across all repositories.

# Tasks
Each task must be completed sequentially based on numbering. Tasks within the same subsection might be parallelized.

## 1. Open release tracking project  -> @davidjiglesias
- [x] Release 5.0.0

### wazuh-qa -> @wazuh/qa
- https://github.com/wazuh/wazuh-qa/issues/4955
### wazuh-jenkins -> @wazuh/qa
- https://github.com/wazuh/wazuh-jenkins/issues/6263
### wazuh-automation -> @wazuh/cicd
- https://github.com/wazuh/wazuh-automation/issues/1552
### wazuh-packages -> @wazuh/core
- https://github.com/wazuh/wazuh-packages/issues/2823
### wazuh -> @wazuh/core
- https://github.com/wazuh/wazuh/issues/21890
### wazuh-ansible -> @wazuh/cicd
- https://github.com/wazuh/wazuh-ansible/issues/1208
### wazuh-docker -> @wazuh/cicd
- https://github.com/wazuh/wazuh-docker/issues/1206
### wazuh-puppet -> @wazuh/cicd
- https://github.com/wazuh/wazuh-puppet/issues/921
### wazuh-kubernetes -> @wazuh/cicd
- https://github.com/wazuh/wazuh-kubernetes/issues/587
### wazuh-dashboard-plugins -> @wazuh/frontend
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6401
### wazuh-documentation -> @wazuh/documentation
- https://github.com/wazuh/wazuh-documentation/issues/7030
### qa-integration-framework -> @wazuh/framework
- https://github.com/wazuh/qa-integration-framework/issues/96
### wazuh-dashboard -> @wazuh/frontend
- https://github.com/wazuh/wazuh-dashboard/issues/145
### wazuh-security-dashboards-plugin -> @wazuh/frontend
- https://github.com/wazuh/wazuh-security-dashboards-plugin/issues/37
### wazuh-indexer -> @wazuh/indexer 
- https://github.com/wazuh/wazuh-indexer/issues/153

## 3. Create AWS resources -> @wazuh/qa

- [x] Regenerate AWS resources using the Procedure_ecs_task_tier pipeline on branches that have been modified/bumped.
  - [x] 4.9.0: https://ci.wazuh.info/job/Procedure_ecs_task_tier/126/
  - [x] 5.0.0 (master): https://ci.wazuh.info/job/Procedure_ecs_task_tier/127/

## 4. Create unattended resources  -> @wazuh/cicd
- [x] Create repositories for 5.0.0 in packages-dev to support unattended installer. [Reference](https://github.com/wazuh/wazuh-jenkins/issues/5417#issuecomment-1648346363)

**Comment by davidcr01** [comment]
A new folder `5.0` was created and the following files were copied:
![image](https://github.com/wazuh/wazuh/assets/72193239/9daa0830-25b5-41cb-95b7-1d5a1d08e36a)

**Comment by damarisg** [comment]
I moved it to "**On hold**" state because an incorrect change was applied to [plugins/main/common/api-info/endpoints.json](https://github.com/wazuh/wazuh-dashboard-plugins/pull/6402/files). The Framework team will reopen the issue and resolve the error.

Additionally, the QA team worked on the "`Create AWS Resources`" task and launched two pipelines that failed. We know about the error, but we need to add a comment to the issue to clarify what happened and whether or not there is a problem to fix.

**Comment by Desvelao** [comment]
Hi @damarisg , the file [plugins/main/common/api-info/endpoints.json](https://github.com/wazuh/wazuh-dashboard-plugins/pull/6402/files) is generated through a script that processes an API spec file of the target version. At the moment of the creation of the bump, the `wazuh/wazuh` repository was not bumped to 5.0.0, so we took a previous version to process the API spec file temporarily. The changes to this file were applied in the previous bumps too, for example https://github.com/wazuh/wazuh-dashboard-plugins/pull/6428.

This process will be done in another moment previous to the creation of the tags.

For more information, there are 2 files in the `wazuh/wazuh-dashboard.plugins` repository that is generated from the API information. This creates a dependency of `wazuh/wazuh` to complete these tasks. We could wait until the bump in `wazuh/wazuh` is completed, or take as base a previous API spec replacing the version to the bumped one, but this will contain data of another version, that gives the same result in the usage of the plugin. As I said previously, this file is updated later or at least in the process of the creation of the tags, ensuring the information is updated to the more recent changes. Note there is the same dependency problem when we create the tags too.

**Comment by davidjiglesias** [comment]
After talking with @damarisg and @Desvelao we are currently going to continue as it is.
