### ISSUE TITLE
Test wazuh-db concurrency problems

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#21918]
|Related issue|
|--|
|#17737|

This task aims to define and run a series of tests that will check how _wazuh-db_ works in multiple scenarios.

## Subtasks

- [x] Define a series of tests.
- [ ] Implement the test cases.
- [ ] Report the results for different versions:
  - [x] 4.7.2
  - [x] Fix branch: [fix/17737-wazuh-db-pool](https://github.com/wazuh/wazuh/compare/v4.7.2...fix/17737-wazuh-db-pool)
  - [x] 4.7.3

**Comment by LucioDonda** [comment]
Changed approach after discussion with @vikman90 :
* Query should be changed to execute a sleep on the DB, or any other non-OS dependant command.
Process:
* Script modified to get basic answer time to several queries.
* Not able to execute sleep through wdb:
- sqlite3 enables usleep(xx); execution
- error while trying to do it in wdb -> '(' char or non avaiblable method.
Workaround:
- adding sleep method directly in wdb.c, still in proccess.

c.c. @cborla

**Comment by LucioDonda** [comment]
Created basic modification for enabling sleep command on db, tested and working. 

` bash
root@jammy:/home/vagrant# ./wdb-base.py "agent 001 sleep 5"
`
``` log
2024/02/16 22:28:30 wazuh-db[28862] wdb_parser.c:263 at wdb_parse(): DEBUG: Agent 001 query: sleep 5
2024/02/16 22:28:30 wazuh-db[28862] wdb_parser.c:763 at wdb_parse(): DEBUG: DB(001) Sleep command called for 5.
2024/02/16 22:28:35 wazuh-db[28862] wdb_parser.c:766 at wdb_parse(): DEBUG: DB(001) Sleep result 5000.

```
Pending work:
* check concurrence issue (call sleep on X different agents) 
* issue after calling sleep (it doesn't answer)

**Comment by LucioDonda** [comment]
Conclusions:
The amount of time that the sleep query takes in each case does not vary significantly:

- with worker_pool_size=8

| case\version | 4.5.4 | 4.7.2 | FixBranch| 
| -- | -- | -- | -- | 
| Single Agent | 8.4214 | 8.609 | 8.4655 | 
| Multiple agents | 1.043 | 1.072 | 1.072 | 

- with worker_pool_size=4

| case\version | 4.5.4 | 4.7.2 |  
| -- | -- | -- |  
| Single Agent | 8.5737 | 8.4309 | 
| Multiple agents | 2.591 | 2.066 |

**Comment by cborla** [comment]
# Blocking test by concurrency 

The main goal is blocking wazuhdb by concurrency.

## Environment:

### Manager 

- Disable FIM for manager: ` vi /var/ossec/etc/ossec.conf `

```
<syscheck>
  <disabled>yes</disabled>
```
 
- Enable debug 2 in analysisd and wazuhdb :  `vi /var/ossec/etc/internal_options.conf`

```
# Analysisd (server or local)
analysisd.debug=2

# Wazuh DB debug level
wazuh_db.debug=2
```

### Agent
  - Enable FIM for agent and reduce sync interval:

```
	 <syscheck>
	    <disabled>no</disabled>
	    .
	    .
	    .
	    <synchronization>
	      <enabled>yes</enabled>
	      <interval>1m</interval>
	      <max_eps>10</max_eps>
	    </synchronization>
	  </syscheck>

```

## Steps to reproduce it:

Stop Agent. 
  - `pkill -f remoted ; pkill -f analysisd`, or
  - Windows agent by UI

Stop wazuhdb (Manager):
  - `pkill -f wazuh-db` 

Check that wazuh-db is not running:

```
# /var/ossec/bin/wazuh-control status
wazuh-clusterd not running...
wazuh-modulesd is running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd is running...
wazuh-maild not running...
wazuh-execd is running...
wazuh-db not running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord is running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid is running...

```

Change the checksum from fim_entry value. (Agent 006 in this case)

```
sqlite3 /var/ossec/queue/db/006.db

sqlite> update fim_entry set checksum='?';

sqlite> select checksum from fim_entry;
?
?
?
?
?
.
.
.
```

Run wazuh db
```
/var/ossec/bin/wazuh-db &
2024/02/22 23:13:45 wazuh-db[47318] main.c:119 at main(): DEBUG: Wazuh home directory: /var/ossec
[12]   Done                    /var/ossec/bin/wazuh-db
```

Check that wazuh-db is running:

```
# /var/ossec/bin/wazuh-control status

wazuh-clusterd not running...
wazuh-modulesd is running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd is running...
wazuh-maild not running...
wazuh-execd is running...
wazuh-db is running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord is running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid is running...

```

After restarting the agent, check the log values, at this point it is also advisable to stop the manager and delete the ossec.log file, to reset the counters to zero.

```
# grep save2 /var/ossec/logs/ossec.log | grep "Agent 006" | wc -l
0

# grep integrity_check /var/ossec/logs/ossec.log | grep "Agent 006" | wc -l
0

# grep registry_key /var/ossec/logs/ossec.log | grep -Eo "Time:.* ms \." | sort

# grep registry_value /var/ossec/logs/ossec.log | grep -Eo "Time:.* ms \." | sort
```

Check that the agent database is OK, ownership, group and permissions.

```
# ls -l /var/ossec/queue/db/
total 11328
-rw-r----- 1 wazuh wazuh 4845568 feb 22 23:10 000.db
-rw-r----- 1 wazuh wazuh 1138688 feb 22 23:07 006.db
-rw-r----- 1 wazuh wazuh   86016 feb 22 23:10 global.db
srw-rw---- 1 wazuh wazuh       0 feb 22 23:13 wdb

```

No agent connected

```
# /var/ossec/bin/agent_control -lc
Wazuh agent_control. List of available agents:
   ID: 000, Name: chb-VBox (server), IP: 127.0.0.1, Active/Local

```
Run Windows Agent

```
# /var/ossec/bin/agent_control -lc
Wazuh agent_control. List of available agents:
   ID: 000, Name: chb-VBox (server), IP: 127.0.0.1, Active/Local
   ID: 006, Name: DESKTOP, IP: any, Active

```

Look for following message types.

```
# grep save2 /var/ossec/logs/ossec.log | grep "Agent 006" | wc -l
10959

# grep integrity_check /var/ossec/logs/ossec.log | grep "Agent 006" | wc -l
38

# grep registry_key /var/ossec/logs/ossec.log | grep -Eo "Time:.* ms \." | sort

# grep registry_value /var/ossec/logs/ossec.log | grep -Eo "Time:.* ms \." | sort

```
At this point, we can only force the synchronization of the agent's database with the manager's database.

**Comment by cborla** [comment]
# Blocking test by concurrency 

The main goal is blocking wazuhdb by concurrency.

## Environment:

### Manager branch fix/17737-wazuh-db-pool (4.7.3)

```
# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.7.3"
WAZUH_REVISION="40712"
WAZUH_TYPE="server"
```

- Disable FIM for manager: ` vi /var/ossec/etc/ossec.conf `

```
<syscheck>
  <disabled>yes</disabled>
```
 
- Enable debug 2 in analysisd and wazuhdb :  `vi /var/ossec/etc/internal_options.conf`

```
# Analysisd (server or local)
analysisd.debug=2

# Wazuh DB debug level
wazuh_db.debug=2
```

### Agent
  - Enable FIM for agent and reduce sync interval:

```
	 <syscheck>
	    <disabled>no</disabled>
	    .
	    .
	    .
	    <synchronization>
	      <enabled>yes</enabled>
	      <interval>5m</interval>
	      <max_eps>10</max_eps>
	    </synchronization>
	  </syscheck>

```

## Steps to reproduce it:

Stop Agent. 
  - `pkill -f remoted ; pkill -f analysisd`, in manager side, or
  - Windows agent by UI

Stop wazuhdb (Manager):
  - `pkill -f wazuh-db` 

Check that wazuh-db is not running:

```
# /var/ossec/bin/wazuh-control status
wazuh-clusterd not running...
wazuh-modulesd is running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd is running...
wazuh-maild not running...
wazuh-execd is running...
wazuh-db not running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord is running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid is running...
```

Change the checksum from fim_entry value. (Agent 006 in this case)

```
sqlite3 /var/ossec/queue/db/006.db

sqlite> update fim_entry set checksum='?';

sqlite> select checksum from fim_entry;
?
?
?
?
?
.
.
.
```

Run wazuh db
```
/var/ossec/bin/wazuh-db &
2024/02/22 23:13:45 wazuh-db[47318] main.c:119 at main(): DEBUG: Wazuh home directory: /var/ossec
[12]   Done                    /var/ossec/bin/wazuh-db
```

Check that wazuh-db is running:

```
# /var/ossec/bin/wazuh-control status

wazuh-clusterd not running...
wazuh-modulesd is running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd is running...
wazuh-maild not running...
wazuh-execd is running...
wazuh-db is running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord is running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid is running...

```

After restarting the agent, check the log values, at this point it is also advisable to stop the manager and delete the ossec.log file, to reset the counters to zero.

```
# grep save2 /var/ossec/logs/ossec.log | grep "Agent 006" | wc -l
0

# grep integrity_check /var/ossec/logs/ossec.log | grep "Agent 006" | wc -l
0

# grep registry_key /var/ossec/logs/ossec.log | grep -Eo "Time:.* ms\." | sort

# grep registry_value /var/ossec/logs/ossec.log | grep -Eo "Time:.* ms\." | sort
```

Check that the agent database is OK, ownership, group and permissions.

```

# ls -l /var/ossec/queue/db/
total 40728
-rw-r----- 1 wazuh wazuh  4845568 feb 23 22:30 000.db
-rw-r----- 1 wazuh wazuh 31240192 feb 23 22:34 006.db
-rw-r----- 1 wazuh wazuh    86016 feb 23 22:29 global.db
srw-rw---- 1 wazuh wazuh        0 feb 23 22:35 wdb
```

No agent connected

```
# /var/ossec/bin/agent_control -lc
Wazuh agent_control. List of available agents:
   ID: 000, Name: VBox (server), IP: 127.0.0.1, Active/Local

```
Run Windows Agent

```
# /var/ossec/bin/agent_control -lc
Wazuh agent_control. List of available agents:
   ID: 000, Name: VBox (server), IP: 127.0.0.1, Active/Local
   ID: 006, Name: DESKTOP, IP: any, Active

```

Look for following message types.

```
# grep save2 /var/ossec/logs/ossec.log | grep "Agent 006" | wc -l
3545

# grep integrity_check /var/ossec/logs/ossec.log | grep "Agent 006" | wc -l
13789
```

Top `fim_registry_key` range checksum delay
```
# grep registry_key /var/ossec/logs/ossec.log | grep -Eo "Time:.* ms \." | sort

Time: 28.778 ms.
Time: 15.059 ms.
Time: 13.225 ms.
Time: 11.343 ms.
Time: 11.118 ms.
Time: 7.792 ms.
Time: 7.593 ms.
Time: 7.004 ms.
Time: 6.804 ms.
Time: 6.371 ms.
Time: 6.097 ms.
Time: 5.226 ms.
Time: 4.632 ms.
Time: 4.264 ms.
Time: 4.031 ms.
Time: 3.629 ms.
Time: 3.338 ms.
Time: 3.130 ms.
Time: 3.097 ms.
Time: 2.524 ms.
```

Top `fim_registry_value` range checksum delay
```
# grep registry_value /var/ossec/logs/ossec.log | grep -Eo "Time:.* ms\."

Time: 33.561 ms.
Time: 19.947 ms.
Time: 16.250 ms.
Time: 6.870 ms.
Time: 8.384 ms.
Time: 10.448 ms.
Time: 10.488 ms.
Time: 5.698 ms.
Time: 4.365 ms.
Time: 4.693 ms.
Time: 3.632 ms.
Time: 5.223 ms.
Time: 4.786 ms.
Time: 6.519 ms.
Time: 6.069 ms.
Time: 3.101 ms.
Time: 2.659 ms.
Time: 2.922 ms.
Time: 2.795 ms.
Time: 3.081 ms.
Time: 2.272 ms.
Time: 2.785 ms.
Time: 1.815 ms.
```


At this point, we can only force the synchronization of the agent's database with the manager's database.

**Comment by cborla** [comment]
Moved to on hold until we complete the stress test 4.8.0 analysis.

**Comment by cborla** [comment]
# Blocking test by concurrency 

The main goal is blocking wazuhdb by concurrency.

## Environment:

### Manager 4.7.3

```
# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.7.3"
WAZUH_REVISION="40714"
WAZUH_TYPE="server"
```

- Disable FIM for manager: ` vi /var/ossec/etc/ossec.conf `

```
<syscheck>
  <disabled>yes</disabled>
```
 
- Enable debug 2 in analysisd and wazuhdb :  `vi /var/ossec/etc/internal_options.conf`

```
# Analysisd (server or local)
analysisd.debug=2

# Wazuh DB debug level
wazuh_db.debug=2
```

### Agent
  - Enable FIM for agent and reduce sync interval:

```
	 <syscheck>
	    <disabled>no</disabled>
	    .
	    .
	    .
	    <synchronization>
	      <enabled>yes</enabled>
	      <interval>5m</interval>
	      <max_eps>10</max_eps>
	    </synchronization>
	  </syscheck>

```

## Steps to reproduce it:

Stop Agent. 
  - `pkill -f remoted ; pkill -f analysisd`, in manager side, or
  - Windows agent by UI

Stop wazuhdb (Manager):
  - `pkill -f wazuh-db` 

Check that wazuh-db is not running:

```
# /var/ossec/bin/wazuh-control status
wazuh-clusterd not running...
wazuh-modulesd is running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd is running...
wazuh-maild not running...
wazuh-execd is running...
wazuh-db not running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord is running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid is running...
```

Change the checksum from fim_entry value. (Agent 006 in this case)

```
sqlite3 /var/ossec/queue/db/006.db

sqlite> update fim_entry set checksum='?';

sqlite> select checksum from fim_entry;
?
?
?
?
?
.
.
.
```

Run wazuh db
```
/var/ossec/bin/wazuh-db &
2024/02/22 23:13:45 wazuh-db[47318] main.c:119 at main(): DEBUG: Wazuh home directory: /var/ossec
[12]   Done                    /var/ossec/bin/wazuh-db
```

Check that wazuh-db is running:

```
# /var/ossec/bin/wazuh-control status

wazuh-clusterd not running...
wazuh-modulesd is running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd is running...
wazuh-maild not running...
wazuh-execd is running...
wazuh-db is running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord is running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid is running...

```

After restarting the agent, check the log values, at this point it is also advisable to stop the manager and delete the ossec.log file, to reset the counters to zero.

```
# grep save2 /var/ossec/logs/ossec.log | grep "Agent 006" | wc -l
0

# grep integrity_check /var/ossec/logs/ossec.log | grep "Agent 006" | wc -l
0

# grep registry_key /var/ossec/logs/ossec.log | grep -Eo "Time:.* ms\." | sort

# grep registry_value /var/ossec/logs/ossec.log | grep -Eo "Time:.* ms\." | sort
```

Check that the agent database is OK, ownership, group and permissions.

```

# ls -l /var/ossec/queue/db/
total 40728
-rw-r----- 1 wazuh wazuh  4845568 feb 23 22:30 000.db
-rw-r----- 1 wazuh wazuh 31240192 feb 23 22:34 006.db
-rw-r----- 1 wazuh wazuh    86016 feb 23 22:29 global.db
srw-rw---- 1 wazuh wazuh        0 feb 23 22:35 wdb
```

No agent connected

```
# /var/ossec/bin/agent_control -lc
Wazuh agent_control. List of available agents:
   ID: 000, Name: VBox (server), IP: 127.0.0.1, Active/Local

```
Run Windows Agent

```
# /var/ossec/bin/agent_control -lc
Wazuh agent_control. List of available agents:
   ID: 000, Name: VBox (server), IP: 127.0.0.1, Active/Local
   ID: 006, Name: DESKTOP, IP: any, Active

```

Look for following message types.

```
# grep save2 /var/ossec/logs/ossec.log | grep "Agent 006" | wc -l
3545

# grep integrity_check /var/ossec/logs/ossec.log | grep "Agent 006" | wc -l
13789
```

Top `fim_registry_key` range checksum delay
```
# grep registry_key /var/ossec/logs/ossec.log | grep -Eo "Time:.* ms\." | sort

Time: 4.110 ms.
Time: 3.649 ms.
Time: 1.287 ms.
Time: 0.731 ms.
Time: 0.650 ms.
Time: 0.579 ms.
Time: 0.571 ms.
Time: 0.567 ms.
Time: 0.404 ms.
Time: 0.395 ms.
Time: 0.369 ms.
Time: 0.316 ms.
Time: 0.303 ms.
Time: 0.294 ms.
Time: 0.293 ms.
Time: 0.279 ms.
Time: 0.272 ms.
Time: 0.254 ms.
Time: 0.248 ms.
Time: 0.235 ms.
```

Top `fim_registry_value` range checksum delay
```
# grep registry_value /var/ossec/logs/ossec.log | grep -Eo "Time:.* ms\."

Time: 9.268 ms.
Time: 4.955 ms.
Time: 5.098 ms.
Time: 2.751 ms.
Time: 2.716 ms.
Time: 2.171 ms.
Time: 2.312 ms.
Time: 1.601 ms.
Time: 1.370 ms.
Time: 1.441 ms.
Time: 1.377 ms.
Time: 1.545 ms.
Time: 1.560 ms.
Time: 1.453 ms.
Time: 1.330 ms.
Time: 0.788 ms.
Time: 0.844 ms.
Time: 0.664 ms.
Time: 0.638 ms.
Time: 0.748 ms.
```

**Comment by vikman90** [comment]
Closing this issue as it was partially tested, and it is not on a current objective.
