### ISSUE TITLE
Week 7 - Update Wazuh feeds

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#21920]
|Week|Feeds|Previous issue|
|---|---|---|
|7/2024|MSU/ALAS|https://github.com/wazuh/wazuh/issues/21810|

## Description

The following issue aims to check the weekly update of Wazuh feeds, where they will be checked, and it will be decided whether to update them according to the results obtained.

All feed results must have one of the following statuses: 
| | |
|---------------------------------|--------------------------------------------|
| :green_circle: | The feed has been successfully updated |
| :red_circle:  | The feed could not be updated due to failures |
| :yellow_circle:  | The feed has been updated, but a failure has occurred |
| :black_circle:  | The feed has not been updated because it is not needed |

Any failed feed should be reported, detailing the error and possible cause.

In the results, the differences between the current feed and the new feed that will overwrite the current feed should be detailed.

### Current Wazuh feeds
- MSU: https://feed.wazuh.com/vulnerability-detector/windows/msu-updates.json.gz
- ALAS:
  - ALAS 1: https://feed.wazuh.com/vulnerability-detector/ALAS/1/alas.json.gz
  - ALAS 2: https://feed.wazuh.com/vulnerability-detector/ALAS/2/alas2.json.gz
  - ALAS 2022: https://feed.wazuh.com/vulnerability-detector/ALAS/2022/alas2022.json.gz
  - ALAS 2023: https://feed.wazuh.com/vulnerability-detector/ALAS/2023/alas2023.json.gz

### Tasks
- [x] Check that feeds have been generated correctly.
- [ ] Analyse the difference between the current feed and the new feed.
- [ ] Update the current feed with the new feed.
------
- [ ] In addition, check the [EoL dates](https://endoflife.date/) of the OSes we [officially support with Vulnerability Detector](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/how-it-works.html#compatibility-matrix).
- [ ] Check if there is any news related to feed deprecations on the pages of official providers, and if so, report it.

**Comment by MarcelKemp** [comment]
## Update Wazuh feeds

### New feeds vs Current feeds

#### MSU

|MSU|Hotfixes|CVEs|
|---|---|---|
| MSU | +24 | +61 |

- Hotfixes:
```
KB5002026
KB5002100
KB5002117
KB5002307
KB5002418
KB5002462
KB5002498
KB5002502
KB5002518
KB5002520
KB5002521
KB5002529
KB5032391
KB5034119
KB5034121
KB5034127
KB5034129
KB5034130
KB5034134
KB5034169
KB5034171
KB5034173
KB5034184
KB5034203
```


- CVEs:
```
CVE-2023-50387
CVE-2024-20673
CVE-2024-20684
CVE-2024-21304
CVE-2024-21315
CVE-2024-21327
CVE-2024-21328
CVE-2024-21338
CVE-2024-21339
CVE-2024-21340
CVE-2024-21341
CVE-2024-21342
CVE-2024-21343
CVE-2024-21344
CVE-2024-21345
CVE-2024-21346
CVE-2024-21347
CVE-2024-21348
CVE-2024-21349
CVE-2024-21350
CVE-2024-21351
CVE-2024-21352
CVE-2024-21353
CVE-2024-21354
CVE-2024-21355
CVE-2024-21356
CVE-2024-21357
CVE-2024-21358
CVE-2024-21359
CVE-2024-21360
CVE-2024-21361
CVE-2024-21362
CVE-2024-21363
CVE-2024-21364
CVE-2024-21365
CVE-2024-21366
CVE-2024-21367
CVE-2024-21368
CVE-2024-21369
CVE-2024-21370
CVE-2024-21371
CVE-2024-21372
CVE-2024-21375
CVE-2024-21377
CVE-2024-21378
CVE-2024-21379
CVE-2024-21380
CVE-2024-21389
CVE-2024-21391
CVE-2024-21393
CVE-2024-21394
CVE-2024-21395
CVE-2024-21396
CVE-2024-21397
CVE-2024-21404
CVE-2024-21405
CVE-2024-21406
CVE-2024-21410
CVE-2024-21412
CVE-2024-21413
CVE-2024-21420
```


#### ALAS

| ALAS | Vulnerabilities |
|---|---|
| ALAS 1 | = |
| ALAS 2 | +18 |
| ALAS 2022 | = |
| ALAS 2023 | +14 |



- ALAS 2 vulns:
```
ALAS-2024-2433
ALAS-2024-2434
ALAS-2024-2435
ALAS-2024-2436
ALAS-2024-2437
ALAS-2024-2438
ALAS-2024-2439
ALAS-2024-2440
ALAS-2024-2441
ALAS-2024-2442
ALAS-2024-2443
ALAS-2024-2444
ALAS-2024-2445
ALAS-2024-2446
ALAS-2024-2447
ALAS-2024-2448
ALAS-2024-2449
ALAS-2024-2450
```



- ALAS 2023 vulns:
```
ALAS-2024-502
ALAS-2024-503
ALAS-2024-504
ALAS-2024-505
ALAS-2024-507
ALAS-2024-508
ALAS-2024-509
ALAS-2024-510
ALAS-2024-511
ALAS-2024-512
ALAS-2024-513
ALAS-2024-514
ALAS-2024-515
ALAS-2024-516
```


### Release

| Feeds | Status | SHA256 |
|---|:-:|---|
| MSU | 🟢 | `2dbb44d95366358951988ec428c68c2e8c8561e777ad444617d18569a36b9397` |
| ALAS 1 | 🟢 | `5fd9e431f0ab874bfda958057899bd9a2f61c324c3a2cb1728de2782bba1b2d0` |
| ALAS 2 | 🟢 | `8467b3784cbe72dee064e3e4f22e4af5764b317e057dec5e805ff85258aa3ec4` |
| ALAS 2022 | 🟢 | `f2eb92d8532824d34ae11679752badedcbf4110b1f8c5f0b37d4cc2c767ad0cd` |
| ALAS 2023 | 🟢 | `beb85ad26fa1c8e48e1969c8adb7d755191aad6314cabcd1bba79c2f56d9e96f` |

**Comment by MarcelKemp** [comment]
## EoL dates
| Distribution/Provider | Versions | Maintenance Support | Extended Life Cycle Support | Comment |
|---|---|---|---|---|
|  | 5 | 31 Mar 2017 🔴 | 30 Nov 2020 🔴 | Archived ⚫ |
|  | 6 | 30 Nov 2020 🔴 | 30 Jun 2024 🟡 ||
| [**Red Hat**](https://endoflife.date/rhel) | 7 | 30 Jun 2024 🟡 | 30 Jun 2028 🟢 ||
|  | 8 | 31 May 2029 🟢 | 31 May 2032 🟢 ||
|  | 9 | 31 May 2032 🟢 | 31 May 2035 🟢 ||
|  | trusty / 14 | 02 Apr 2019 🔴 | 02 Apr 2024 🟠 ||
|  | xenial / 16 | 02 Apr 2021 🔴 | 02 Apr 2026 🟢 ||
| [**Ubuntu**](https://endoflife.date/ubuntu) | bionic / 18 | 31 May 2023 🔴 | 01 Apr 2028 🟢 ||
|  | focal / 20 | 02 Apr 2025 🟢 | 02 Apr 2030 🟢 ||
|  | jammy / 22 | 01 Apr 2027 🟢 | 09 Apr 2032 🟢 ||
|  | buster / 10 | 10 Sep 2022 🔴 | 30 Jun 2024 🟡 ||
| [**Debian**](https://endoflife.date/debian) | bullseye / 11 | 01 Jul 2024 🟡 | 30 Jun 2026 🟢 ||
|  | bookworm / 12 | 10 Jun 2026 🟢 | 10 Jun 2028 🟢 ||
|  | AL 1 | 31 Dec 2020 🔴 | 31 Dec 2023 🔴 | [Amazon announcement](https://aws.amazon.com/es/blogs/aws/update-on-amazon-linux-ami-end-of-life/) |
| [**Amazon Linux**](https://endoflife.date/amazon-linux) | AL 2 | 30 Jun 2025 🟢 | 30 Jun 2025 🟢 ||
|  | AL 2022 | - | - | Archived ⚫ |
|  | AL 2023 | 15 Mar 2025 🟢 | 15 Mar 2028 🟢 ||
| **Arch Linux** | Rolling release | - | - | 🟢 |
|  | SLES 11 & SLED 11 | 31 Mar 2019 🔴 | 31 Mar 2022 🔴 ||
| [**SUSE**](https://endoflife.date/sles) | SLES 12 & SLED 12 | 31 Oct 2024 🟡 | 31 Oct 2027 🟢 ||
|  | SLES 15 & SLED 15 | 31 Jul 2028 🟢 | 31 Jul 2031 🟢 ||
| [**AlmaLinux**](https://endoflife.date/almalinux) | 8 | 01 May 2024 🟠 | 01 Mar 2029 🟢 ||
|  | 9 | 31 May 2027 🟢 | 31 May 2032 🟢 ||
| [**Windows**](https://endoflife.date/windows) | - |  |  |  |
| [**Windows Server**](https://endoflife.date/windows-server) | - |  |  ||
| [**macOS**](https://endoflife.date/macos) | - |  |  ||
