### ISSUE TITLE
Show the agent's primary IP in the alerts

### ISSUE THREAD

**Issue by Skeptor** [wazuh/wazuh#2199]
|Branch|
|---|
|`new_wm_control` ([Compare](https://github.com/wazuh/wazuh/compare/3.9...new_wm_control))|

We're going to show the agent's primary IP in the alerts as the reporting_ip. This way the alerts can show the current agent's IP and make a difference with the Registration IP.

The agent daemon will use the Syscollector algorithm to get the network information and determine the primary IP address by filtering by the default gateway and metrics of the route.

The agent will include the desired IP address as a label in the agent-info file (`#"ip_address":172.16.143.12`) so each keepalive sent by the agent the IP address will be refreshed.

On the manager side, the analysis daemon has to read that label and include it in alerts for that agent as the same way as current labels are read.

Update
-----------
The design is going to have a refactor:
Instead of the agent daemon the IP is going to be extracted in a new module called `control`. It will be implemented on the agent side.
This module won't have the `Chroot()` function so the Syscollector algorithm can obtain the primary IP at any moment. Also, if there are two or more interfaces with a valid gateway the default interface will be chosen based on the Metric.
This module refresh the IP each hour, but it would be set in an option of the internal options of the agent.

After that, the module will comunicate with `agentd` to send it the IP. Once `agentd` receive the IP it will introduce it in the keepalive message in order to store the IP in the agent-info.

When the manager stores the agent-info it will store the IP in the `global.db` and `analysisd` will parse the `agent-info` to obtain the IP and replace the register IP in the alerts.

## Tasks

- [x] Create a new module (`control`) on the agent to get the primary IP address of an agent.
   - [x] Windows
   - [x] Linux
- [x] Create the communication between `agentd` and `control`
- [x] Send the IP from agentd to the manager in the keep-alive to store in the agent-info file.
- [x] Store `reporting_ip` in the global.db as ip.
- [x] Makes `analysisd` to read the ip and insert it on alerts replacing the actual ip.

### Remaining tasks

- [x] System labels start with `_` and don't allow user labels to start with that character.
   - [x] Code implemented.
   - [x] Documentation.
- [x] Syscollector DB migration to support new field. (https://github.com/wazuh/wazuh/commit/b9f4138173da3dca39ead7f9de9ef4466a50d12f)
- [x] When the manager don't have agent IP, let the field empty for that agent in the `global.db`.
- [x] Testing issue. https://github.com/wazuh/wazuh/issues/2558

**Comment by Skeptor** [comment]
I'm currently working on this branch: https://github.com/wazuh/wazuh/tree/get_report_ip
The `global.db` now contains a field to store the `reporting_ip` of the agent. The next steps is extract the primary IP of the agent from the Syscollector network scan.
To do this, the scan function is going to be splitted on two functions:
  - The function that makes the scan and store it in a JSON object.
  - The function that receive the JSON object and send it to the manager.

This way we can extract the IP from the scan when the keep-alive message is being built.

**Comment by Skeptor** [comment]
Issue updating the IP in real time:
At the moment, the Reporting IP is extracted using the Syscollector algorithm.
This algorithm extracts the network information from `getifaddrs()` which doesn't give the entire information after executing the `Chroot()` of `agentd.c`.
First, I'm going to develop all the tasks in the issue to have the functionality working and after that I will return on the problem of refreshing the IP in real time.

**Comment by Skeptor** [comment]
After the design update I will be working on this branch: https://github.com/wazuh/wazuh/tree/new_wm_control
The commit https://github.com/wazuh/wazuh/commit/1392cce34fa1b5d511a9af1bedb63c2edd3e41cc contains a subtask of the first task of the Roadmap, create the module that extract the IP in Linux systems. It also contains the split of the `Syscollector` functionality to obtain the network inventory in order to use the algorithm to obtain network information.
The next step in the Roadmap is send the information to `agentd` when `agentd` query the module. This will be each time `agentd` is going to send a keep-alive.

**Comment by Skeptor** [comment]
The communication between the new module and the agent is done.
The module creates a socket and a thread that listen that socket to receive the message from agentd when it is writting the keep-alive and send the IP of the agent.
The IP is included in the keep-alive to store it in the agent-info of the manager.
The next step is add the IP to the global db and replace the actual IP in the alerts with this IP

**Comment by Skeptor** [comment]
New commit: https://github.com/wazuh/wazuh/commit/efdc5474c2c0fae35e2ba5257401bd5dbe65e9e9
The commit changes the way the agent IP is added to the JSON alerts. Now instead of using the registration IP, analysisd parse the agent-info of the agent to get the Reporting IP.
Also it adds a mutex to the control module's threads and changes the keep alive message depending on the reporting ip value.

Alert example of an agent registered with any as IP: 

`client.keys`
![image](https://user-images.githubusercontent.com/9034923/52353859-a87b6780-2a2f-11e9-8e0d-9764bdec8e49.png)

`Kibana alert`
![image](https://user-images.githubusercontent.com/9034923/52353985-e1b3d780-2a2f-11e9-978d-baedcff0f7c3.png)

**Comment by Skeptor** [comment]
New commit: https://github.com/wazuh/wazuh/commit/9a1551888a450924e21beeeb92354fce0cadc711
Now the reporting IP is stored and updated in the global.db from the agent-info when the keep alive is received.
It also changes the call `SQL_FIND_AGENT` to preserve the comparison with the register_ip instead of the reporting_ip.

**Comment by Skeptor** [comment]
We added a new type of labels: `System labels` and the agent IP now behaves as a label. They are included in order to use invisible labels that send to the manager needed information.

In the Windows agent the IPv4 is obtained but atm the IP sent in the keep alive is the first valid IP. The next step is to use the metric of the interface (as it is done is Linux) to choose the default interface connected to the network.

Also the field metric has been add to the syscollector scan in order to use it to obtain the default gateway. At the moment it is done in Linux.
The field metric is going to be add in Windows syscollector message and the DB will has a mechanism to be migrated.

The commits for those changes are:
https://github.com/wazuh/wazuh/commit/f99b6eab99dfe346f0ffa908b6f3925a74dbf9e2 
https://github.com/wazuh/wazuh/commit/9ee4a3c4947fe95a25bcd55e6cb2237ea944dff6
https://github.com/wazuh/wazuh/commit/b84da46ba5d58401d0e80ccb83773d7a0dca316c
