### ISSUE TITLE
Engine - Prevent Heterogeneous Array Construction in `array_append`

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#21998]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0.0 | Engine | Manager | Packages/Sources | OS version |

**Description:**
The `array_append` helper function now allows the creation of heterogeneous arrays, a deviation from its intended functionality where arguments were always strings.

**Objective:**
- Modify the `array_append` function to enforce homogeneous array construction, maintaining consistency in array element types.

**Tasks:**
- [ ] Review the `array_append` function to understand the current behavior allowing heterogeneous arrays.
- [ ] Implement checks to validate the homogeneity of elements being appended to an array.
- [ ] Update documentation to clearly state the function's behavior regarding array element types.
- [ ] Add unit tests to validate the enforcement of homogeneous arrays.

**Acceptance Criteria:**
- The `array_append` function prevents the construction of heterogeneous arrays, ensuring all elements share the same type.
- Documentation and unit tests reflect and support this enforced behavior.

**Comment by JcabreraC** [comment]
After careful consideration, it has been decided that the array_append function will support heterogeneous arrays, but only for fields defined in the schema. This approach aligns with our intended functionality, as detailed and resolved in the following issue: [#20340](https://github.com/wazuh/wazuh/issues/20340) and its corresponding PR: [#20917](https://github.com/wazuh/wazuh/pull/20917).

Furthermore, the necessary tests validating this behavior have been completed, as documented in issue [#21537](https://github.com/wazuh/wazuh/issues/21537) and PR: [#21646](https://github.com/wazuh/wazuh/pull/21646).

To confirm the correct functionality, the following tests have been successfully executed:
```bash
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_0 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_0 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_1 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_1 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_2 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_2 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_3 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_3 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_4 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_4 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_5 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_5 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_6 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_6 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_7 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_7 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_8 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_8 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_9 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_9 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_10 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_10 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_11 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_11 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_12 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_12 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_13 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_13 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_14 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_14 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_15 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_15 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_16 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_16 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_17 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_17 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_18 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_18 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_19 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_19 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_20 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_20 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_21 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_21 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_22 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_22 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_23 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_23 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_24 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_24 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_25 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_25 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_26 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_26 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_27 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_27 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_28 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_28 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_29 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_29 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_30 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_30 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_31 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_31 (0 ms)
$3│ 
$3│ [ RUN      ] Builders/TransformOperationTest.Operates/ArrayAppend_32 @ ./source/builder/test/src/unit/builders/baseBuilders_test.cpp:238
$3│ [       OK ] Builders/TransformOperationTest.Operates/ArrayAppend_32 (0 ms)
```

Given this resolution and the accompanying tests, this issue is now closed.
