### ISSUE TITLE
Engine - Enhancement of Schema Validity Checks for Field Types in Wazuh-Engine

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#21995]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0.0 | Engine | Manager | Packages/Sources | OS version |

### Description

The Wazuh-Engine currently employs a runtime validator to ensure that fields being mapped correspond to predefined schema types. However, the existing design overlooks the fact that field types are not mutually exclusive, leading to potential validation inaccuracies. For example, a byte (unsigned 8-bit integer) also qualifies as an integer and, by extension, a long. Similarly, floats and doubles, or IPs and text/keywords, share overlapping categorizations. This issue aims to refine our validation mechanisms to acknowledge and accommodate the overlapping nature of these field types.

### Objectives

- **Refine Validation Logic**: Update the runtime validator to recognize and correctly handle field types that fall into multiple categories.
- **Schema Adaptation**: Adjust the schema definitions to reflect the non-mutually exclusive nature of field types, ensuring more accurate validation.
- **Enhance Field Type Handling**: Implement a more nuanced approach to field type validation that acknowledges the hierarchical and overlapping relationships between types.

### Tasks

- [ ] Conduct a thorough review of the current schema validation logic to identify limitations in handling non-mutually exclusive field types.
- [ ] Develop a revised validation approach that accurately reflects the relationships between field types, such as the inclusion of byte within integer and long categories.
- [ ] Update schema definitions to accommodate the refined validation logic, ensuring that field types are correctly categorized and validated.
- [ ] Implement changes to the runtime validator to enhance its ability to accurately validate fields against the updated schema definitions.
- [ ] Test the updated validation mechanism extensively to ensure it correctly identifies and validates fields according to the new logic.
- [ ] Document the changes made to the schema validation process, including the rationale behind the updated approach and guidance for future schema development.

### Additional Considerations

- **Backward Compatibility**: Assess the impact of these changes on existing schemas and data processing to ensure backward compatibility is maintained.
- **Performance Impact**: Evaluate the performance implications of the enhanced validation logic to ensure that it does not introduce significant overhead.
- **Documentation and Training**: Update the Wazuh-Engine documentation to reflect the new validation approach and provide training materials for developers on handling schema definitions.

### Acceptance Criteria

- The schema validation logic accurately recognizes and validates fields that fall into multiple type categories.
- Schema definitions are updated to align with the enhanced validation approach, ensuring accurate and reliable data processing.
- Documentation is revised to accurately describe the updated schema validation process and field type handling.

**Comment by JavierBejMen** [comment]
## Update

Here is the initial redesign of the schemval module and relations of the schemf module:
![image](https://github.com/wazuh/wazuh/assets/32262972/44b1bf20-bab1-4df9-ac17-f49b30eeb451)

The idea is to be able to validate the different cases about what a helper knows of the type needed/returned by the operation it performs (the ValidationToken class). The build time validation will return a ValidationResult, if succeeded it will contain also if a runtime validation needs to be done.

The builder is responsible for determining if an operation needs runtime validation at all, e.g. filter operations do never need runtime validation as no assignation on any field is performed.

The validation function exposed by the schemval has the following form:
```c++
ValidationResult(const Reference& targetField, const ValidationToken& valToken);
````
As it is now the builder's registry will hold the validation token associated for each helper builder and the SchemValidator class will query the schema instance to obtain the SchemType.

The SchemValidator class maintains a map of SchemType -> ValidationInfo, that associates each SchemType with its compatible JSON type, and compatbles SchemTypes.

A compatible SchemType may need additional validations, e.g. keyword type is compatible with the ip type only if it contains an ip address, this requirement is met by the presence of a ValueValidator in said relation.

### Dynamic validation
Some helper's ValidationToken depends on the arguments provided to the helper's builder, for such cases we can specify multiple helpers, effectively erasing the dynamic component, or define a Dynamic ValidationToken that will return the concrete ValidataionToken from the arguments passed to the helper's builder.


### Note
End design and names will be updated as the implementation advances.

**Comment by JcabreraC** [comment]
ETA has been extended due to deeper test coverage.
