### ISSUE TITLE
Support new stage Beta 2 for 4.8.0

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#22063]
# Description

This issue attempts to support a new stage Beta 2 for 4.8.0 in the Wazuh system.

# Tasks

Each task must be completed sequentially based on numbering. Tasks within the same subsection might be parallelized.

### wazuh-qa -> @wazuh/qa
- https://github.com/wazuh/wazuh-qa/issues/5017
### wazuh-jenkins -> @wazuh/qa
- https://github.com/wazuh/wazuh-jenkins/issues/6296
### wazuh-automation -> @wazuh/devops
- https://github.com/wazuh/wazuh-automation/issues/1570
### wazuh-packages -> @wazuh/core
- https://github.com/wazuh/wazuh-packages/issues/2852
### wazuh -> @wazuh/core
- https://github.com/wazuh/wazuh/issues/22062
### wazuh-ansible -> @wazuh/devops
- https://github.com/wazuh/wazuh-ansible/issues/1220
### wazuh-docker -> @wazuh/devops
- https://github.com/wazuh/wazuh-docker/issues/1229
### wazuh-puppet -> @wazuh/devops
- https://github.com/wazuh/wazuh-puppet/issues/935
### wazuh-kubernetes -> @wazuh/devops
- https://github.com/wazuh/wazuh-kubernetes/issues/601
### wazuh-dashboard-plugins -> @wazuh/dashboard
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6444
### qa-integration-framework -> @wazuh/framework
- https://github.com/wazuh/qa-integration-framework/issues/106
### wazuh-documentation -> @wazuh/qa
- https://github.com/wazuh/wazuh-documentation/issues/7065

## 2. Create pre-release packages for v4.8.0-beta2 using tags from task 1. -> @wazuh/qa
- [x] https://github.com/wazuh/wazuh-jenkins/issues/6301
- [x] ~Upload updated filebeat module~ 

## 3. Create and assign testing issues for 4.8.0 Beta 2. -> @davidjiglesias
- [x] Create issues
  - [x] E2E: --
  - [x] CI: https://ci.wazuh.info/job/Procedure_cicd_release_issues/145/ 

## 4.Set up demo environment for 4.8.0 Beta 2. -> @wazuh/cicd

- https://github.com/wazuh/wazuh-automation/issues/1571
