### ISSUE TITLE
Support new stage RC 2 for 4.7.3

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh#22198]
# Description

This issue attempts to support a new stage RC 2 for 4.7.3 in the Wazuh system.

# Tasks

Each task must be completed sequentially based on numbering. Tasks within the same subsection might be parallelized.

### wazuh-qa -> @wazuh/qa
- https://github.com/wazuh/wazuh-qa/issues/5045
### wazuh-jenkins -> @wazuh/qa
- https://github.com/wazuh/wazuh-jenkins/issues/6307
### wazuh-automation -> @wazuh/devops
- https://github.com/wazuh/wazuh-automation/issues/1573
### wazuh-packages -> @wazuh/core
- https://github.com/wazuh/wazuh-packages/issues/2855
### wazuh -> @wazuh/core
- https://github.com/wazuh/wazuh/issues/22196
### wazuh-ansible -> @wazuh/devops
- https://github.com/wazuh/wazuh-ansible/issues/1222
### wazuh-docker -> @wazuh/devops
- https://github.com/wazuh/wazuh-docker/issues/1232
### wazuh-puppet -> @wazuh/devops
- https://github.com/wazuh/wazuh-puppet/issues/941
### wazuh-kubernetes -> @wazuh/devops
- https://github.com/wazuh/wazuh-kubernetes/issues/603
### wazuh-dashboard-plugins -> @wazuh/dashboard
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6449
### qa-integration-framework -> @wazuh/framework
- https://github.com/wazuh/qa-integration-framework/issues/107
### wazuh-documentation -> @wazuh/qa
- https://github.com/wazuh/wazuh-documentation/issues/7073

## 2. Create pre-release packages for v4.7.3-rc2 using tags from task 1. -> @wazuh/qa
- [x] Create packages: https://github.com/wazuh/wazuh-jenkins/issues/6308
- [x] ~Upload updated filebeat module~

## 3. Create and assign testing issues for 4.7.3 RC 2. -> @davidjiglesias
- [x] Create issues
  - [x] E2E: Skipped
  - [x] CI: https://ci.wazuh.info/job/Procedure_cicd_release_issues/146/console

## 4.Set up demo environment for 4.7.3 RC 2. -> @wazuh/cicd

- https://github.com/wazuh/wazuh-automation/issues/1574
