### ISSUE TITLE
Scheduled upward merges for numbered branches - Fortnight #5

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#22265]
# Description

The goal of this is to track the completion of the following tasks so the development branches are up to date in every repository, ensuring a clean environment for our development teams.

# Tasks

### wazuh-qa -> @wazuh/qa
- https://github.com/wazuh/wazuh-qa/issues/5050
### wazuh-jenkins -> @wazuh/qa
- https://github.com/wazuh/wazuh-jenkins/issues/6314
### wazuh-automation -> @wazuh/devops
- https://github.com/wazuh/wazuh-automation/issues/1575
### wazuh-packages -> @wazuh/core
- https://github.com/wazuh/wazuh-packages/issues/2856
### wazuh -> @wazuh/core
- https://github.com/wazuh/wazuh/issues/22266
### wazuh-ansible -> @wazuh/devops
- https://github.com/wazuh/wazuh-ansible/issues/1224
### wazuh-docker -> @wazuh/devops
- https://github.com/wazuh/wazuh-docker/issues/1235
### wazuh-puppet -> @wazuh/devops
- https://github.com/wazuh/wazuh-puppet/issues/943
### wazuh-kubernetes -> @wazuh/devops
- https://github.com/wazuh/wazuh-kubernetes/issues/607
### wazuh-dashboard-plugins -> @wazuh/dashboard
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6465
### wazuh-documentation -> @wazuh/qa
- https://github.com/wazuh/wazuh-documentation/issues/7077
### qa-integration-framework -> @wazuh/framework
- https://github.com/wazuh/qa-integration-framework/issues/108
### wazuh-security-dashboards-plugin -> @wazuh/dashboard
- https://github.com/wazuh/wazuh-security-dashboards-plugin/issues/40
### wazuh-indexer -> @wazuh/indexer
- https://github.com/wazuh/wazuh-indexer/issues/172
### wazuh-dashboard ->@wazuh/dashboard
- https://github.com/wazuh/wazuh-dashboard/issues/150

## 2. Upload installation assistant in packages-dev -> @wazuh/qa

- [ ] Upload installation assistant in packages-dev using `Publish_unattended` pipeline. **BE CAREFUL NOT TO UPLOAD IT TO PRODUCTION**
  - [x] 4.8.0 will be skipped as will be done in v4.8.0-beta3 stage
  - [x] 4.8.1 and 4.8.2 will not be worked 
  - [ ] 4.9.0
  - [ ] master 

## 3. Create AWS resources  -> @wazuh/qa

- [ ] Regenerate AWS resources using the Procedure_ecs_task_tier pipeline on branches that have been modified/bumped.

**Comment by rauldpm** [comment]
Closed as completed in https://github.com/wazuh/wazuh/issues/22318
