### ISSUE TITLE
Support new stage Beta 3 for 4.8.0

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#22269]
# Description

This issue attempts to support a new stage Beta 3 for 4.8.0 in the Wazuh system.

# Tasks

Each task must be completed sequentially based on numbering. Tasks within the same subsection might be parallelized.

### wazuh-qa -> @wazuh/qa
- https://github.com/wazuh/wazuh-qa/issues/5052
### wazuh-jenkins -> @wazuh/qa
- https://github.com/wazuh/wazuh-jenkins/issues/6317
### wazuh-automation -> @wazuh/cicd
- https://github.com/wazuh/wazuh-automation/issues/1576
### wazuh-packages -> @wazuh/core
- https://github.com/wazuh/wazuh-packages/issues/2857
### wazuh -> @wazuh/core
- https://github.com/wazuh/wazuh/issues/22271
### wazuh-ansible -> @wazuh/cicd
- https://github.com/wazuh/wazuh-ansible/issues/1226
### wazuh-docker -> @wazuh/cicd
- https://github.com/wazuh/wazuh-docker/issues/1237
### wazuh-puppet -> @wazuh/cicd
- https://github.com/wazuh/wazuh-puppet/issues/945
### wazuh-kubernetes -> @wazuh/cicd
- https://github.com/wazuh/wazuh-kubernetes/issues/610
### wazuh-dashboard-plugins -> @wazuh/frontend
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6467
### qa-integration-framework -> @wazuh/framework
- https://github.com/wazuh/qa-integration-framework/issues/109
### wazuh-documentation -> @wazuh/documentation
- https://github.com/wazuh/wazuh-documentation/issues/7079

## 2. Validate that the Wazuh manager feed is updated. -> @wazuh/core
- [x] Check that the feed is updated
- [x] Update the feed if needed

## 3. Create pre-release packages for v4.8.0-beta3 using tags from task 1. -> @wazuh/qa
- [x] ~Upload Filebeat module if needed~
- [x] [Create v4.8.0-beta3 packages](https://github.com/wazuh/wazuh-jenkins/issues/6318)

## 4. Create and assign testing issues for 4.8.0 Beta 3. -> @davidjiglesias
- [x] Create E2E issues
- [x] Create release testing issues

## 4.Set up demo environment for 4.8.0 Beta 3. -> @wazuh/devel-devops 

- .https://github.com/wazuh/wazuh-automation/issues/1585
