### ISSUE TITLE
Post release tasks for 4.7.3

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#22317]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.7.3.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.7.3-into-4.8.0`.

## Tasks

- [x] Merge branch `4.7.3` into branch `4.8.0`.
- [x] [Merge branch `4.8.0` into branch `4.8.1`.](https://github.com/wazuh/wazuh/pull/22340)
- [x] [Merge branch `4.8.1` into branch `4.8.2`.](https://github.com/wazuh/wazuh/pull/22358)
- [x] [Merge branch `4.8.2` into branch `4.9.0`.](https://github.com/wazuh/wazuh/pull/22376)
- [x] [Merge branch `4.9.0` into branch `master`.](https://github.com/wazuh/wazuh/pull/22410)
- [x] Publish GitHub release as latest.
- [x] Delete all stage pre-releases for 4.7.3 (https://github.com/wazuh/wazuh/releases).
- [x] Delete all stage tags for v4.7.3. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.7.3-rc1, 4.7.3-alpha1, etc.
- [x] Fast-forward definitive tag v4.7.3 to `4.7.3` branch
- [x] Delete branch `4.7.3`.
