### ISSUE TITLE
Migrate and adapt the Wazuh manager subsystem

### ISSUE THREAD

**Issue by mjcr99** [wazuh/wazuh#22320]
| Related Issue|
|---|
| [Wazuh packages redesign tier 1 - Stage 2 - Migrate and adapt Wazuh subsystem repositories](https://github.com/wazuh/wazuh/issues/21755) |

 Migrate and adapt the Wazuh manager subsystem (debs, rpms)
Based on the research [issue 21777](https://github.com/wazuh/wazuh/issues/21777) the folder structure:
`/[os]/[arch]/[manager|agent]/Dockerfile`

**Goals:**
* First we want to bring all the code. Then adapt it for the Wazuh repository and perform tests locally to ensure it works well. According to these tests, if possible, we can even generate scripts (or use existing ones) to perform tests locally, which we will then use for GitHub Actions. 

* The subsystem's version and revision will be extracted from its metadata. The Dockerfiles must extract that data and make it accessible within the container.

* The building of the packages must be done through the use of Docker containers.

* Generate README.md

## Tasks

- [x] Research and set ETA for the parent issue (notify @rauldpm)
- [x] Migrate code - Manual package generation
- [x] Package creation through CI
  - Packages that require a sign during the build phase must implement this functionality (for example Windows and macOS)
- [x] Add CI testing
- [x] Upload packages to S3 through CI. This must be done after the testing phase

**Comment by mjcr99** [comment]
### Comment Update:
(04/03/2024): Migrating `debs` managers' Dockerfiles and modifying the main script to deal with the manager option.

**Comment by rauldpm** [comment]
After a meeting with the teams involved, it has been decided the following:

- Wazuh manager/agent for PPC systems will be worked on in the tier 2

**Comment by MarcelKemp** [comment]
The ETA is delayed because we are blocked due to lack of ARM provisioning.
- https://github.com/wazuh/internal-devel-requests/issues/1005

**Comment by rauldpm** [comment]
@MarcelKemp keep in mind that that issue is a VPN request, it is not a request for ARM resources

ARM resources are not currently available as GitHub Runner, but they will be soon, there is a private Beta stage that provides access to ARM
- https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/
- https://resources.github.com/devops/accelerate-your-cicd-with-arm-and-gpu-runners-in-github-actions/

If you require EC2 resources please open a dedicated issue, we will need to request the ARM AMIs needed and provision them, we will also need to update the CI user permissions to use EC2

**Comment by mjcr99** [comment]
The ARM-related workflows are waiting for the allocator module.

- https://github.com/wazuh/wazuh-qa/issues/4855

**Comment by rauldpm** [comment]
Please check https://github.com/wazuh/wazuh/issues/21755#issuecomment-2034819851

**Comment by lchico** [comment]
# Update 05-04-2024

* Updated how we check the Wazuh Manager installation.
* I successfully tested the package installation using the builder image.
* Rebased the branch and ran a couple of tests. [Link](https://github.com/wazuh/wazuh/actions/runs/8575607105/job/23504965425)

![image](https://github.com/wazuh/wazuh/assets/21695385/2a4416e5-9609-4e0f-be2c-2b986cb49f82)

**Comment by rauldpm** [comment]
After asking @havidarou, @davidjiglesias, and @gdiazlo, it has been confirmed that the ARM Wazuh manager will not be developed while we do not have Wazuh indexer and Wazuh dashboard for ARM systems
