### ISSUE TITLE
Migrate and adapt WPK tools from wazuh-packages to wazuh/wazuh repository

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#22321]
| Related Issue|
|---|
| [Wazuh packages redesign tier 1 - Stage 2 - Migrate and adapt Wazuh subsystem repositories](https://github.com/wazuh/wazuh/issues/21755) |

# Description

Hello team,

This issue is part of the project to migrate all the package tools from the wazuh-packages repository to the wazuh/wazuh repository.
In this issue, we are going to make all the necessary modifications to move the WPK generation part and everything that depends on it. Directory structure:

```
WAZUH-PACKAGES\WPK
│   generate_wpk_package.sh
│   README.md
│   run.sh
│   wpkpack.py
│
├───common
│       Dockerfile
│
└───linux
    ├───aarch64
    │       Dockerfile
    │
    ├───armv7hl
    │       build_deps.sh
    │       Dockerfile
    │       entrypoint.sh
    │
    └───x86_64
            CentOS-Base.repo
            Dockerfile
```

## Tasks

- [x] Research and set ETA for the parent issue (notify @rauldpm)
- [x] Migrate code - Manual package generation
- [x] Package creation through CI
  - Packages that require a sign during the build phase must implement this functionality (for example Windows and macOS)
- [ ] ~Add CI testing~
- [x] Upload packages to S3 through CI. This must be done after the testing phase

**Comment by jotacarma90** [comment]
## Update 05/03/2024

- Testing WPK generated.
- Problems encountered with WPK signature during testing.
- Request for macOS machine to verify the package: https://github.com/wazuh/internal-devel-requests/issues/829
  - macOS agent:
```
[root@ip-x ec2-user]# /var/ossec/bin/agent_upgrade -l
ID    Name                                Version
001   ip-x.ec2.internal        Wazuh v4.7.2

Total outdated agents: 1
[root@x ec2-user]# /var/ossec/bin/agent_upgrade -a 001 -f /home/ec2-user/macOSAgent.wpk

Upgrading...

Failed upgrades:
        Agent 001 status: Send upgrade command error
```
  - Manager logs:

```
2024/03/05 16:56:30 wazuh-modulesd:agent-upgrade: ERROR: (8139): At unsign(): Could not unsign package file 'var/incoming/macOSAgent.wpk'
2024/03/05 16:56:30 wazuh-modulesd:agent-upgrade: ERROR: (8131): At upgrade: 'Could not verify signature'
```

- WPKs generation of aarch64 architecture.
- Pending testing aarch64 architecture.

**Comment by jotacarma90** [comment]
# Update 06/03/2024

## Testing Linux

- Generated WPK:


- Manager logs:
```

```
- Agent upgrade.log: 
```

```

## Testing MacOS

- Generated WPK:
[macOSAgent.zip](https://github.com/wazuh/wazuh/files/14509141/macOSAgent.zip)

- Manager logs:
```
[root@ip-172-31-45-230 ec2-user]# /var/ossec/bin/agent_upgrade -a 002 -f /home/ec2-user/macOSAgent.wpk

Upgrading...

Upgraded agents:
        Agent 002 upgraded: Wazuh v4.7.2 -> Wazuh v4.7.2
```
- Agent upgrade.log: 
```
2024/03/06 11:20:47 - Backup generated in /Library/Ossec/backup/backup_[03-06-2024_11-20-46].tar.gz
2024/03/06 11:20:47 - Upgrade started.
installer: Package name is Wazuh Agent
installer: Upgrading at base path /
installer: The upgrade was successful.
2024/03/06 11:21:00 - Installation result = 0
2024/03/06 11:21:00 - Waiting connection... Remaining attempts: 30.
2024/03/06 11:21:01 - Status = connected.
2024/03/06 11:21:01 - Connected to manager.
2024/03/06 11:21:01 - Upgrade finished successfully.
```


## Testing Windows

- Generated WPK:
[WindowsAgent.zip](https://github.com/wazuh/wazuh/files/14509154/WindowsAgent.zip)


- Manager logs:
```
root@ubuntu23:/home/vagrant# /var/ossec/bin/agent_upgrade -a 001 -f /vagrant/wpk/WindowsAgent.wpk

Upgrading...

Upgraded agents:
        Agent 001 upgraded: Wazuh v4.7.2 -> Wazuh v4.7.2
```
- Agent upgrade.log: 
```
2024-03-06 11:39:17Z - Sysnative Powershell will be used to access the registry.
2024-03-06 11:39:17Z - Current version: v4.7.2.
2024-03-06 11:39:17Z - Generating backup.
2024-03-06 11:39:17Z - Backing up Wazuh home files.
2024-03-06 11:39:21Z - Searching Wazuh-Agent cached MSI through the registry.
2024-03-06 11:39:21Z - Backing up Wazuh-Agent cached MSI: "C:\Windows\Installer\10c15b.msi".
2024-03-06 11:39:21Z - Trying to stop Wazuh service.
2024-03-06 11:39:23Z - Starting upgrade processs.
2024-03-06 11:39:25Z - Waiting for the Wazuh-Agent installation to end.
2024-03-06 11:39:27Z - Waiting for the Wazuh-Agent installation to end.
2024-03-06 11:39:29Z - Waiting for the Wazuh-Agent installation to end.
2024-03-06 11:39:31Z - Waiting for the Wazuh-Agent installation to end.
2024-03-06 11:39:33Z - Waiting for the Wazuh-Agent installation to end.
2024-03-06 11:39:35Z - Restarting Wazuh-Agent service.
2024-03-06 11:39:35Z - Installation finished.
2024-03-06 11:39:35Z - Process ID: 7000.
2024-03-06 11:39:45Z - Reading status file: status='connected'.
2024-03-06 11:39:45Z - Upgrade finished successfully.
2024-03-06 11:39:45Z - New version: v4.7.2.
```

**Comment by jotacarma90** [comment]
## Update 07/03/2024

- I have tried to generate WPK packages for aarch64 and armv7hl architectures, but the scripts are outdated. Related issue: https://github.com/wazuh/wazuh/issues/22400
- PR related to this issue: https://github.com/wazuh/wazuh/pull/22401
- I have been working and researching the format and syntax of the GitHub actions, creating a workflow to generate WPK.
- I have been investigating some bugs in the process. Currently debugging a problem in the wpkpack.py script:
```
+ wpkpack /var/local/wazuh/windowsAgent.22321-migrate-wpk-tools.wpk /etc/wazuh/wpkcert.pem /etc/wazuh/wpkcert.key wazuh-agent-4.7.3-1.msi upgrade.bat do_upgrade.ps1
Traceback (most recent call last):
  File "/usr/local/bin/wpkpack", line 102, in <module>
    raise error
  File "/usr/local/bin/wpkpack", line 99, in <module>
    mergeappend(merged, argv[4:])
  File "/usr/local/bin/wpkpack", line 38, in mergeappend
    _mergeappend(f, s)
  File "/usr/local/bin/wpkpack", line 52, in _mergeappend
    raise Exception
Exception
```

**Comment by jotacarma90** [comment]
Issue blocked by https://github.com/wazuh/internal-devel-requests/issues/964
Extending ETA waiting for AWS secrets permissions.

**Comment by jotacarma90** [comment]
## Update 08/03/2024

- I have continued to work on the necessary workflows. 
- I have uploaded commits adding the existing actions in wazuh-packages to pull and push the docker images.
- Created new workflow to update the images to generate WPK packages.
- Working and debugging on both workflows.
- Found block because I need WPK certificates: https://github.com/wazuh/wazuh-jenkins/issues/6344

**Comment by jotacarma90** [comment]
## Update 11/03/2024

- Working with workflows.
- I have been troubleshooting multiple issues to correctly capture WPK certificates from eAWS.
- Currently workflows are working: https://github.com/wazuh/wazuh/actions/runs/8238751969/job/22530408937?pr=22401
- Pending to modify the packet upload step to the artifacts, so that they are uploaded to S3.

**Comment by rauldpm** [comment]
As discussed in the meeting today, the WPK packages will not be tested in this tier

- https://github.com/wazuh/internal-devel-requests/issues/187#issuecomment-2018579969
