### ISSUE TITLE
Migrate Filebeat templates and adapt the Filebeat module

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#22367]
| Related Issue|
|---|
| [Wazuh packages redesign tier 1 - Stage 2 - Migrate and adapt Wazuh subsystem repositories](https://github.com/wazuh/wazuh/issues/21755) |

# Description

Hello team,

This issue is part of the project to migrate all the package tools from the wazuh-packages repository to the wazuh/wazuh repository.
In this issue, we are going to make all the necessary modifications to move the Filebeat files needed to creation of Filebeat package.

## Tasks

- [x] Research and set ETA for the parent issue (notify @rauldpm)

## Tasks (templates)

- [x] Research changes related to Filebeat templates
- [x] Migrate Filebeat templates from wazuh-packages to wazuh/wazuh
- [x] Adapt changes related to Filebeat templates

## Tasks (module)

- [x] Manual package generation
  - Check the [README](https://github.com/wazuh/wazuh/blob/master/extensions/filebeat/7.x/wazuh-module/README.md) file 
- [x] Package creation through CI
  - Packages that require a sign during the build phase must implement this functionality (for example Windows and macOS)
- [x] Add CI testing
- [x] Upload packages to S3 through CI. This must be done after the testing phase

**Comment by rauldpm** [comment]
After a meeting with the teams involved, it has been decided the following:

- Wazuh Filebeat module will be versioned in a tier 2

**Comment by jotacarma90** [comment]
## Update 15/03/2024
- Research usefulness of filebeat module and all its files.
- Working on the workflow related to the creation of the Filebeat package, steps in this readme: https://github.com/wazuh/wazuh/blob/master/extensions/filebeat/7.x/wazuh-module/README.md
- Thread on some related comments: https://wazuh-team.slack.com/archives/C038AR25C8N/p1710428187030819

**Comment by rauldpm** [comment]
Missing CI test, please update project fields and complete the missing tasks
