### ISSUE TITLE
AWS Integration: Improvements (II)

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh#2241]
#### Fixes
- [ ] Fix bug when Macie logs are too long (https://github.com/wazuh/wazuh/issues/1439).
- [ ] AWS - Reformat arrays of objects and lists to strings (https://github.com/wazuh/wazuh/pull/1699) (https://github.com/wazuh/wazuh/issues/2013)

#### New features
- [ ] Add AWS metadata to agent labels (https://github.com/wazuh/wazuh/issues/684).
- [ ] Add support for relative dates in `start_after` parameter (for example `-1d`) (https://github.com/wazuh/wazuh/issues/1669).
- [ ] AWS Config Checks using Prowler (https://github.com/wazuh/wazuh/pull/1700)
- [ ] Support for AWS CSM
