### ISSUE TITLE
Support new stage Beta 4 for 4.8.0

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#22447]
# Description

This issue attempts to support a new stage Beta 4 for 4.8.0 in the Wazuh system.

# Tasks

Each task must be completed sequentially based on numbering. Tasks within the same subsection might be parallelized.

### wazuh-qa -> @wazuh/qa
- https://github.com/wazuh/wazuh-qa/issues/5093
### wazuh-jenkins -> @wazuh/qa
- https://github.com/wazuh/wazuh-jenkins/issues/6351
### wazuh-automation -> @wazuh/devops
- https://github.com/wazuh/wazuh-automation/issues/1593
### wazuh-packages -> @wazuh/core
- https://github.com/wazuh/wazuh-packages/issues/2877
### wazuh -> @wazuh/core
- https://github.com/wazuh/wazuh/issues/22446
### wazuh-ansible -> @wazuh/devops
- https://github.com/wazuh/wazuh-ansible/issues/1241
### wazuh-docker -> @wazuh/devops
- https://github.com/wazuh/wazuh-docker/issues/1257
### wazuh-puppet -> @wazuh/devops
- https://github.com/wazuh/wazuh-puppet/issues/960
### wazuh-kubernetes -> @wazuh/devops
- https://github.com/wazuh/wazuh-kubernetes/issues/623
### wazuh-dashboard-plugins -> @wazuh/dashboard
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6497
### qa-integration-framework -> @wazuh/framework
- https://github.com/wazuh/qa-integration-framework/issues/120
### wazuh-documentation -> @wazuh/qa
- https://github.com/wazuh/wazuh-documentation/issues/7114

## 2. Create pre-release packages for v4.8.0-beta4 using tags from task 1. -> @wazuh/qa
- [x] https://github.com/wazuh/wazuh-jenkins/issues/6355
- [x] https://github.com/wazuh/wazuh-jenkins/issues/6356

## 3. Create and assign testing issues for 4.8.0 Beta 4. -> @davidjiglesias
- [x] Create issues https://ci.wazuh.info/view/Procedures/job/Procedure_cicd_release_issues/148/

## 4.Set up demo environment for 4.8.0 Beta 4. -> @wazuh/devops

- https://github.com/wazuh/wazuh-automation/issues/1594
