### ISSUE TITLE
wazuh-keystore directories are being created for agents

### ISSUE THREAD

**Issue by ncvicchi** [wazuh/wazuh#22616]
## Description

|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-Beta4 | wazuh-keystore| Manager/Agent | Packages/Sources | Any |

|Related issues|
|--------------|
|[#6363](https://github.com/wazuh/wazuh-jenkins/issues/6363)|
|[#22470](https://github.com/wazuh/wazuh/issues/22470)      |

This issue is a subtask of #6363, to investigate and solve the first error listed:

`Agent: /var/ossec/queue/keystore`

These errors appeared in the #22470 test issue.

A preliminary analysis denotes that the error origins in having created the directory in the common installation in the wazuh/src/init/inst-functions.sh, instead of the server installation.

wazuh-keystore should be only be present in the manager, avoiding any modification for the agent

## Tasks

- [ ] Check the error
- [ ] Find the root cause
- [ ] Prepare a fix

## Validation

- [ ] Launch the `Test_upgrade_tier` pipeline
