### ISSUE TITLE
Scheduled upward merges for numbered branches - Fortnight #7

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#22696]
# Description

The goal of this is to track the completion of the following tasks so the development branches are up to date in every repository, ensuring a clean environment for our development teams.

# Tasks

### wazuh-qa -> @wazuh/qa
- https://github.com/wazuh/wazuh-qa/issues/5167
### wazuh-jenkins -> @wazuh/qa
- https://github.com/wazuh/wazuh-jenkins/issues/6377
### wazuh-automation -> @wazuh/devops
- https://github.com/wazuh/wazuh-automation/issues/1601
### wazuh-packages -> @wazuh/core
- https://github.com/wazuh/wazuh-packages/issues/2894
### wazuh -> @wazuh/core
- https://github.com/wazuh/wazuh/issues/22695
### wazuh-ansible -> @wazuh/devops
- https://github.com/wazuh/wazuh-ansible/issues/1246
### wazuh-docker -> @wazuh/devops
- https://github.com/wazuh/wazuh-docker/issues/1281
### wazuh-puppet -> @wazuh/devops
- https://github.com/wazuh/wazuh-puppet/issues/964
### wazuh-kubernetes -> @wazuh/devops
- https://github.com/wazuh/wazuh-kubernetes/issues/630
### wazuh-dashboard-plugins -> @wazuh/dashboard
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6562
### wazuh-documentation -> @wazuh/qa
- https://github.com/wazuh/wazuh-documentation/issues/7150
### qa-integration-framework -> @wazuh/framework
- https://github.com/wazuh/qa-integration-framework/issues/124
### wazuh-security-dashboards-plugin -> @wazuh/dashboard
- https://github.com/wazuh/wazuh-security-dashboards-plugin/issues/42
### wazuh-indexer -> @wazuh/indexer
- https://github.com/wazuh/wazuh-indexer/issues/195

## 2. Upload installation assistant in packages-dev -> @wazuh/qa

- [x] Upload installation assistant in packages-dev using `Publish_unattended` pipeline. **BE CAREFUL NOT TO UPLOAD IT TO PRODUCTION**
  - [x] 4.8.0: Will be done directly for Beta 5.
  - [x] ~4.8.1~: This is not done because it would overwrite 4.8.0. In addition, there is no tag.
  - [x] ~4.8.2~: This is not done because it would overwrite 4.8.0. In addition, there is no tag.
  - [x] ~4.9.0~: There is no tag.
  - [x] ~5.0.0~: There is no tag.
  
## 3. Create AWS resources  -> @wazuh/qa

- [x] Regenerate AWS resources using the Procedure_ecs_task_tier pipeline on branches that have been modified/bumped.
  - [x] 4.8.0: https://ci.wazuh.info/job/Procedure_ecs_task_tier/136/
  - [x] 4.9.0: https://ci.wazuh.info/job/Procedure_ecs_task_tier/137/
  - [x] 5.0.0: https://ci.wazuh.info/job/Procedure_ecs_task_tier/138

**Comment by davidjiglesias** [comment]
LGTM
