### ISSUE TITLE
Adapt agent package generation workflows with VPN and allocator module

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#22839]
| Related Issue|
|---|
| [Wazuh packages redesign tier 1 - Stage 2 - Migrate and adapt Wazuh subsystem repositories](https://github.com/wazuh/wazuh/issues/21755) |

# Description
This issue is to work on the packet generation workflows that need the Wazuh VPN and the use of the allocator module for special machines (arm and macOS/windows signatures). 
After migrating those workflows, for security reasons, to the private repo in this issue: https://github.com/wazuh/wazuh-agent-packages/issues/1
This issue is going to be used to reference the PRs in the private repo that introduce the necessary steps to have the packages complete.

## Tasks

- [x] Wazuh agent Windows sign tool - https://github.com/wazuh/wazuh-agent-packages/pull/8
- [x] Wazuh agent macOS sign tool arm64 and intel64 - https://github.com/wazuh/wazuh-agent-packages/pull/9
- [x] Wazuh agent ARM architecture - https://github.com/wazuh/wazuh-agent-packages/pull/10

## Blocked by
> Connection problems with the environment.
- https://github.com/wazuh/wazuh-qa/issues/5226
- https://github.com/wazuh/internal-devel-requests/issues/1054
- https://github.com/wazuh/internal-devel-requests/issues/1004

**Comment by jotacarma90** [comment]
# Update 10/04/2024
- I have been reading and analyzing the allocator module documentation:
- Working on the code for package generation workflows that need special machines.
- Added the steps to install and connect the VPN.
- Added the steps to download, install and configure the allocator module (Pending some steps)
- Follow up thread: https://wazuh-team.slack.com/archives/C06Q9QHP0QP/p1712597177934839

**Comment by MarcelKemp** [comment]
### Status
#### In progress
Because we are working on the unlocked parts of both `Linux ARM` and `macOS ARM` (unsigned).

#### Still blocked
Please note that it is still blocked due to lack of provisioning of `Windows machine` (with certificates to sign), `intel64 macOS machine` and `macOS machine` to sign the package:
- https://github.com/wazuh/wazuh-qa/issues/5226
- https://github.com/wazuh/internal-devel-requests/issues/1054
- https://github.com/wazuh/internal-devel-requests/issues/1004

**Comment by jotacarma90** [comment]
# Update 06/05/2024
I continue testing workflows related to Windows and macOS:
- Windows:
  - Tested the machine with the ssh server where we are going to generate and sign the packages. Issue comment: https://github.com/wazuh/internal-devel-requests/issues/1103#issuecomment-2096087823
  - Waiting for the machine to be available in the allocator to launch the generation workflows.
  - Workflows updated with the use of ssh, pending testing.

- macOS:
  - arm64: 
    - Waiting for the machine to be available in the allocator.
    - Multiple problems running workflows, connection problems, macStadium busy, etc. [Example](https://github.com/wazuh/wazuh-agent-packages/actions/runs/8972792356).
    - Fixed problem with secrets needed for signing. Thread: 
    - Continued to debug problems.

  - intel64:
    - Testing compilation on `macos-highsierra-10.13.6-amd64` box, but multiple dependencies need to be installed.
    - Waiting for the `macos-sierragcc9-10.12.6-amd64` box, which has what is needed for compilation.
    - Encountered some unstable connection problems.

**Comment by jotacarma90** [comment]
# Update 07/05/2024
- Solving compiler problems and different machines for macOS intel64 and macOS.
- Investigating connection issues and different options.

**Comment by jotacarma90** [comment]
# Update 08/05/2024
- I'm still debugging and fixing bugs in the package generation scripts.
- The Windows machine is now available for testing.
- There are still some instability problems with the VPN that make testing very difficult.
