### ISSUE TITLE
Fix API integration tests conftest directives

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#22891]
## Description

The API integration tests [conftest.py](https://github.com/wazuh/wazuh/blob/epic/20748-upgrade-to-connexion-3/api/test/integration/conftest.py) file contains some errors that are causing the tests execution to not behave as expected in the [20748-upgrade-to-connexion-3](https://github.com/wazuh/wazuh/blob/epic/20748-upgrade-to-connexion-3) branch.

### Tasks

- [x] When the environment was created using a profile, the [down_env](https://github.com/wazuh/wazuh/blob/c65cec03dc96ae18e000f05a3386242fd01dcf78/api/test/integration/conftest.py#L149) directive is not tearing down the containers successfully. We should include the following changes:

```diff
+ def down_env(env_mode: str):
    """Stop and remove all Docker containers."""
    os.chdir(env_path)
    with open(docker_log_path, mode='a') as f_docker:
+       current_process = subprocess.Popen(["docker", "compose", "--profile", env_mode, "down"], stdout=f_docker,
                                           stderr=subprocess.STDOUT, universal_newlines=True)
        current_process.wait()
    os.chdir(current_path)
```

- [x] Not related to the conftest itself but it could be handy to have a `.env` file next to the docker-compose to specify the values of the variables `ENV_MODE` and `WAZUH_LOCAL_PATH` there instead of doing it on every command.

- [x] Review why the agents depend on the one deployed earlier. They shouldn't depend on each other.

https://github.com/wazuh/wazuh/blob/997f201dd3452c95b662fb0a106874ce8a3fb41c/api/test/integration/env/docker-compose.yml#L94-L96

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

### Test with a branch that is not on remote (no tarball)

The manager image uses the current branch tarball to build Wazuh, if the local branch is not on remote it should fail early.

<details><summary>Logs</summary>

```console
(venv_connexion) gasti@pop-os:~/work/wazuh/api/test/integration$ pytest -vv test_active_response_endpoints.tavern.yaml --disable-warnings
================================================================= test session starts ==================================================================
platform linux -- Python 3.10.12, pytest-7.3.1, pluggy-1.4.0
rootdir: /home/gasti/work/wazuh/api/test/integration
configfile: pytest.ini
plugins: trio-0.8.0, asyncio-0.18.1, tavern-1.23.5, metadata-3.1.1, html-2.1.1, anyio-4.3.0
asyncio: mode=auto
collected 2 items                                                                                                                                      

test_active_response_endpoints.tavern.yaml EEE                                                                                                   [100%]

======================================================================== ERRORS ========================================================================
...
=============================================================== short test summary info ================================================================
ERROR test_active_response_endpoints.tavern.yaml::PUT /active-response/{:agent_id} - Failed: Current branch tarball doesn't exist
ERROR test_active_response_endpoints.tavern.yaml::PUT /active-response - Failed: Current branch tarball doesn't exist
ERROR test_active_response_endpoints.tavern.yaml::PUT /active-response - TypeError: 'NoneType' object is not callable
============================================================= 1 warning, 3 errors in 1.08s =============================================================
```

</details>

### Test after pushing the changes

docker.log: [docker_log.zip](https://github.com/wazuh/wazuh/files/15169102/docker_log.zip)

<details><summary>Logs</summary>

```console
(venv_connexion) gasti@pop-os:~/work/wazuh/api/test/integration$ pytest -vv test_active_response_endpoints.tavern.yaml --disable-warnings
================================================================= test session starts ==================================================================
platform linux -- Python 3.10.12, pytest-7.3.1, pluggy-1.4.0 -- /home/gasti/work/wazuh/venv_connexion/bin/python
cachedir: .pytest_cache
metadata: {'Python': '3.10.12', 'Platform': 'Linux-6.6.10-76060610-generic-x86_64-with-glibc2.35', 'Packages': {'pytest': '7.3.1', 'pluggy': '1.4.0'}, 'Plugins': {'trio': '0.8.0', 'asyncio': '0.18.1', 'tavern': '1.23.5', 'metadata': '3.1.1', 'html': '2.1.1', 'anyio': '4.3.0'}}
rootdir: /home/gasti/work/wazuh/api/test/integration
configfile: pytest.ini
plugins: trio-0.8.0, asyncio-0.18.1, tavern-1.23.5, metadata-3.1.1, html-2.1.1, anyio-4.3.0
asyncio: mode=auto
collected 2 items                                                                                                                                      

test_active_response_endpoints.tavern.yaml::PUT /active-response/{:agent_id} PASSED                                                              [ 50%]
test_active_response_endpoints.tavern.yaml::PUT /active-response PASSED                                                                          [100%]

====================================================== 2 passed, 3 warnings in 520.57s (0:08:40) =======================================================

```

</details>

### Docker images before and after the changes in the docker-compose.yaml

Before the changes we were building one image per node and agent, now we are reusing them.

<details><summary>Before</summary>

```console
gasti@pop-os:~/work/wazuh/api/test/integration$ docker images
REPOSITORY                         TAG       IMAGE ID       CREATED              SIZE
<none>                             <none>    b892328b9b94   About a minute ago   2.28GB
<none>                             <none>    0c861d926de9   About a minute ago   2.28GB
integration_test_wazuh-manager     latest    c4a46c14bda1   About a minute ago   2.28GB
<none>                             <none>    f24083273883   2 minutes ago        1.21GB
<none>                             <none>    73aa0eda5c19   2 minutes ago        1.21GB
<none>                             <none>    075cd8f4d8fe   2 minutes ago        1.21GB
integration_test_wazuh-agent       latest    f30e6ca8f2a9   2 minutes ago        1.21GB
<none>                             <none>    827aeed56891   4 minutes ago        160MB
integration_test_wazuh-agent_old   latest    cab85f426790   4 minutes ago        160MB
<none>                             <none>    4163237b0eff   4 minutes ago        160MB
<none>                             <none>    4affc4c5136f   4 minutes ago        160MB
integration_test_nginx-lb          latest    1cd99f4565c8   5 minutes ago        188MB
```

</details>

<details><summary>After</summary>

```console
gasti@pop-os:~/work/wazuh/api/test/integration/env$ docker images
REPOSITORY                         TAG       IMAGE ID       CREATED          SIZE
integration_test_wazuh-manager     latest    1c3fed9836cc   12 minutes ago   2.28GB
integration_test_wazuh-agent       latest    ee2e738c3fc1   14 minutes ago   1.21GB
integration_test_wazuh-agent_old   latest    e688c0da1885   17 minutes ago   160MB
integration_test_nginx-lb          latest    9847182cbcbb   17 minutes ago   188MB
```

</details>

### Launching the test with the `--nobuild` flag doesn't recreate the images

docker.log: [docker_log.zip](https://github.com/wazuh/wazuh/files/15169168/docker_log.zip)

<details><summary>Logs</summary>

Window 1

```console
(venv_connexion) gasti@pop-os:~/work/wazuh/api/test/integration$ pytest -vv test_active_response_endpoints.tavern.yaml --disable-warnings --nobuild
================================================================= test session starts ==================================================================
platform linux -- Python 3.10.12, pytest-7.3.1, pluggy-1.4.0 -- /home/gasti/work/wazuh/venv_connexion/bin/python
cachedir: .pytest_cache
metadata: {'Python': '3.10.12', 'Platform': 'Linux-6.6.10-76060610-generic-x86_64-with-glibc2.35', 'Packages': {'pytest': '7.3.1', 'pluggy': '1.4.0'}, 'Plugins': {'trio': '0.8.0', 'asyncio': '0.18.1', 'tavern': '1.23.5', 'metadata': '3.1.1', 'html': '2.1.1', 'anyio': '4.3.0'}}
rootdir: /home/gasti/work/wazuh/api/test/integration
configfile: pytest.ini
plugins: trio-0.8.0, asyncio-0.18.1, tavern-1.23.5, metadata-3.1.1, html-2.1.1, anyio-4.3.0
asyncio: mode=auto
collected 2 items                                                                                                                                      

test_active_response_endpoints.tavern.yaml::PUT /active-response/{:agent_id} PASSED                                                              [ 50%]
test_active_response_endpoints.tavern.yaml::PUT /active-response PASSED                                                                          [100%]

====================================================== 2 passed, 3 warnings in 133.44s (0:02:13) =======================================================
```

Window 2

```console
gasti@pop-os:~/work/wazuh/api/test/integration/env$ docker images
REPOSITORY                         TAG       IMAGE ID       CREATED          SIZE
integration_test_wazuh-agent_old   latest    8cd3ea05c80b   13 minutes ago   160MB
integration_test_nginx-lb          latest    5a200b749c23   13 minutes ago   188MB
integration_test_wazuh-manager     latest    1c3fed9836cc   26 minutes ago   2.28GB
integration_test_wazuh-agent       latest    ee2e738c3fc1   28 minutes ago   1.21GB
```

</details>

**Comment by GGP1** [comment]
## Update

Made modifications to the AIT environment to improve its efficiency and reliability.

**Comment by GGP1** [comment]
## Update

Fixed a dependency issue between nginx and the workers and updated a test which was failing because an agent could reconnect before the test ended.

**Comment by GGP1** [comment]
## Update

Modified the conftest to fail when the request is not successful and the code is not 404. Ran all integration tests on jenkins and compared them to 4.9.0.
