### ISSUE TITLE
 Validate Compatibility of Journald Log Collection with Existing Ruleset

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#22964]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0 | Logcollector | Manager/Agent | Packages/Sources | OS version |

### Description

With the successful implementation of the `journald` log collection feature in Wazuh, it is crucial to ensure that this new functionality integrates seamlessly with the existing ruleset. This issue focuses on verifying that the logs collected via the new `journald` method are consistent with those collected by traditional methods in terms of format and content, thereby ensuring that no modifications to the current ruleset are necessary for continued effectiveness.

### Objectives

- **Log Format Consistency**: Ensure that the logs collected from `journald` are formatted identically to those obtained through existing log collection mechanisms, maintaining compatibility with the current ruleset.
- **Content Verification**: Confirm that the content of the logs (e.g., fields and values) collected from `journald` matches those expected by existing rules, ensuring that alerts are triggered as intended.
- **Seamless Integration**: Validate that the integration of `journald` logs into the Wazuh framework does not necessitate any changes to the ruleset, preserving the current operational integrity and detection capabilities.

### Requirements

1. **Consistency Checks**:
   - Compare the logs collected from `journald` with those obtained through traditional log collection methods to spot any discrepancies in format or content.
   - Verify that key log attributes (e.g., timestamp, source, message) adhere to the formats expected by existing rules.

2. **Testing and Validation**:
   - Conduct a series of tests where `journald` logs known to trigger rules are introduced into the system to see if the expected alerts are generated.
   - Utilize a controlled environment to ensure that `journald` log collection interacts correctly with the ruleset across various scenarios and configurations.

3. **Documentation and Reporting**:
   - Document any findings related to format discrepancies or content mismatches.
   - If discrepancies are found, outline potential solutions or recommendations for adjustments to the `journald` log collection process or the ruleset itself.

### Tasks

- [ ] Create a comprehensive test plan to evaluate the compatibility of `journald` logs with the existing ruleset.
- [ ] Implement automated tests that compare the format and content of `journald` logs against traditionally collected logs.
- [ ] Analyze test results to confirm or deny the need for modifications to the ruleset or `journald` log collection methodology.
- [ ] Prepare a detailed report summarizing the testing process, findings, and any recommendations for further action.

### Testing Criteria

- **Format Compatibility**: Ensure that all `journald` logs are in a format that is correctly parsed and processed by existing rules.
- **Alert Generation**: Confirm that alerts are triggered as expected when `journald` logs meet the conditions specified in existing rules.
- **Ruleset Efficacy**: Validate that the existing ruleset maintains its effectiveness and does not require adjustments to accommodate logs collected from `journald`.

### Conclusion

This issue is pivotal for ensuring that the integration of `journald` log collection into Wazuh is truly seamless and does not inadvertently compromise the effectiveness of existing security monitoring setups. By verifying the compatibility of new log formats with the established ruleset, we can maintain confidence in the system's overall security posture.

**Comment by jk-olaoluwa** [comment]
## Testing Output

**Installed the dependencies as documented [here](https://documentation.wazuh.com/current/deployment-options/wazuh-from-sources/wazuh-agent/index.html)**

Cloned the branch to install the agent
``` console
root@agent:/home/vagrant# git clone https://github.com/wazuh/wazuh.git -b 12862-logcollector-journald-support
Cloning into 'wazuh'...
remote: Enumerating objects: 401976, done.
remote: Counting objects: 100% (3222/3222), done.
remote: Compressing objects: 100% (1540/1540), done.
error: RPC failed; curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.
error: 3214 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
root@agent:/home/vagrant# git clone https://github.com/wazuh/wazuh.git -b 12862-logcollector-journald-support
Cloning into 'wazuh'...
remote: Enumerating objects: 401976, done.
remote: Counting objects: 100% (3110/3110), done.
remote: Compressing objects: 100% (1512/1512), done.
remote: Total 401976 (delta 1909), reused 2529 (delta 1507), pack-reused 398866
Receiving objects: 100% (401976/401976), 363.37 MiB | 1.06 MiB/s, done.
Resolving deltas: 100% (299979/299979), done.
Updating files: 100% (5202/5202), done.
```

**Installed the agent with the following options**
![image](https://github.com/wazuh/wazuh/assets/69200476/8cef0a1c-b854-42a1-9241-44210a10e224)

**Comment by jk-olaoluwa** [comment]
## Testing Journald logs
**Collected logs from the Wazuh Agent**
``` console
root@agent:/home/vagrant/wazuh# journalctl --since "1 hour ago"
Apr 23 12:17:01 agent CRON[27453]: pam_unix(cron:session): session opened for user root(uid=0) by (uid=0)
Apr 23 12:17:01 agent CRON[27454]: (root) CMD (cd / && run-parts --report /etc/cron.hourly)
Apr 23 12:17:02 agent CRON[27453]: pam_unix(cron:session): session closed for user root
```

**Logtest on collected logs on Wazuh Manager**
``` console
root@server:/home/vagrant# /var/ossec/bin/wazuh-logtest
Starting wazuh-logtest v4.9.0
Type one log per line

Apr 23 12:17:01 agent CRON[27453]: pam_unix(cron:session): session opened for user root(uid=0) by (uid=0)
Apr 23 12:17:01 agent CRON[27454]: (root) CMD (cd / && run-parts --report /etc/cron.hourly)
Apr 23 12:17:02 agent CRON[27453]: pam_unix(cron:session): session closed for user root

**Phase 1: Completed pre-decoding.
        full event: 'Apr 23 12:17:01 agent CRON[27453]: pam_unix(cron:session): session opened for user root(uid=0) by (uid=0)'
        timestamp: 'Apr 23 12:17:01'
        hostname: 'agent'
        program_name: 'CRON'

**Phase 2: Completed decoding.
        name: 'pam'
        parent: 'pam'
        dstuser: 'root(uid=0)'
        uid: '0'

**Phase 3: Completed filtering (rules).
        id: '5521'
        level: '0'
        description: 'PAM: Ignoring Annoying Ubuntu/debian cron login events.'
        groups: '['pam', 'syslog']'
        firedtimes: '1'
        mail: 'False'


**Phase 1: Completed pre-decoding.
        full event: 'Apr 23 12:17:01 agent CRON[27454]: (root) CMD (cd / && run-parts --report /etc/cron.hourly)'
        timestamp: 'Apr 23 12:17:01'
        hostname: 'agent'
        program_name: 'CRON'

**Phase 2: Completed decoding.
        No decoder matched.


**Phase 1: Completed pre-decoding.
        full event: 'Apr 23 12:17:02 agent CRON[27453]: pam_unix(cron:session): session closed for user root'
        timestamp: 'Apr 23 12:17:02'
        hostname: 'agent'
        program_name: 'CRON'

**Phase 2: Completed decoding.
        name: 'pam'
        parent: 'pam'
        dstuser: 'root'

**Phase 3: Completed filtering (rules).
        id: '5522'
        level: '0'
        description: 'PAM: Ignoring Annoying Ubuntu/debian cron login events.'
        groups: '['pam', 'syslog']'
        firedtimes: '1'
        mail: 'False'
```

**Comment by jk-olaoluwa** [comment]
## Test Plan
- Prepare your environment
- Test the use cases.
- Analyse the results.
- Provide a detailed report and recommendations.


## Confirm that journald supports the same logs as syslog.

## Test case 1: SSH rules

## Test case 2: Generic syslog rules 
 - Access control 
 - cron 
 - su 
 - sudo 
 - adduser

- Generate the logs
   - Compare journald logs with syslog logs
- Test the logs to review output
- Show on dashboard

**Comment by Johnng007** [comment]
### Update: 29/04/2024
#### Environment Setup

- Install a fresh Ubuntu 22.04
- Install make
  `sudo apt install make`
- Install cmake
  `sudo apt install cmake`
- Install curl
  `sudo apt install curl`
- Install build essential
  `sudo apt install build-essential`
- Install git
  `sudo apt install git`

#### Wazuh Manager setup

- git clone https://github.com/wazuh/wazuh.git
- cd wazuh && git checkout 12862-logcollector-journald-support
- ./install.sh

- [ ] Below shows Wazuh manager successful installation following the above steps:

![image](https://github.com/wazuh/wazuh/assets/30580457/90132ad8-072f-4029-a69d-c6d060afadc1)

- [ ] Confirming journald is being monitored in ossec.conf

![image](https://github.com/wazuh/wazuh/assets/30580457/a945ceda-a7b8-4051-8992-827937ac74e1)

#### Wazuh Agent setup

- Follow same steps in manager section to install prerequisites.
- git clone https://github.com/wazuh/wazuh.git
- cd wazuh && git checkout 12862-logcollector-journald-support
- ./install.sh

- [ ] Confirming successful agent installation

![image](https://github.com/wazuh/wazuh/assets/30580457/d97526e7-00d3-44cf-9ada-f636df5babed)

#### Simulating SSH Attack Against the Agent
![image](https://github.com/wazuh/wazuh/assets/30580457/29837037-9dd2-4854-ab65-9611c8370ce7)

- [ ] Confirming alerts where properly generated in alerts.log on the manager through journald

![image](https://github.com/wazuh/wazuh/assets/30580457/4cf3350c-012b-4042-aca6-6ff34f763744)

````
** Alert 1714423036.1523917: - syslog,access_control,authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,gpg13_7.8,gdpr_
IV_35.7.d,gdpr_IV_32.2,hipaa_164.312.b,nist_800_53_AU.14,nist_800_53_AC.7,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2024 Apr 29 22:37:16 (stockholm-ubuntu-agent-random) any->journald
Rule: 2502 (level 10) -> 'syslog: User missed the password more than one time'
Src IP: 192.168.25.1
User: root
Apr 29 20:37:15 stockholm-ubuntu-agent-random sshd[14977]: PAM 5 more authentication failures; logname= uid=0 euid=0 tty
=ssh ruser= rhost=192.168.25.1  user=root
````

- [ ] Confirming alerts where properly generated in alerts.json on the manager through journald

![image](https://github.com/wazuh/wazuh/assets/30580457/2528063e-2c00-4ec2-a1b8-2c1e51beda4b)

````
{"timestamp":"2024-04-29T22:41:54.528+0200","rule":{"level":5,"description":"syslog: User authentication failure.","id":"2501","firedtimes":125,"mail":false,"groups":["syslog","access_control","authentication_failed"],"pci_dss":["10.2.4","10.2.5"],"gpg13":["7.8"],"gdpr":["IV_35.7.d","IV_32.2"],"hipaa":["164.312.b"],"nist_800_53":["AU.14","AC.7"],"tsc":["CC6.1","CC6.8","CC7.2","CC7.3"]},"agent":{"id":"001","name":"stockholm-ubuntu-agent-random","ip":"192.168.25.136"},"manager":{"name":"stockholm-test-wazuh"},"id":"1714423314.2097391","full_log":"Apr 29 20:41:53 stockholm-ubuntu-agent-random sshd[15186]: Disconnecting authenticating user root 192.168.25.1 port 57895: Too many authentication failures [preauth]","predecoder":{"program_name":"sshd","timestamp":"Apr 29 20:41:53","hostname":"stockholm-ubuntu-agent-random"},"decoder":{"name":"sshd"},"location":"journald"}
````

**Comment by ooniagbi** [comment]
This looks good from our end. @JcabreraC is there any other thing you'd like us to confirm in this issue?

**Comment by JcabreraC** [comment]
While the basic cases such as sudo and authentication have indeed been tested, we acknowledge the need for a more comprehensive testing of the ruleset. 

Our ruleset is extensive, encompassing various scenarios across different products. Hence, it's imperative to ensure thorough testing beyond just the fundamental cases. We'll prioritize expanding our testing scope to encompass a wider range of log sources to enhance the robustness of our ruleset.

**Comment by ooniagbi** [comment]
I'll adjust the ETA for the issue and we'll add more checks.

**Comment by Johnng007** [comment]
## Update 02/05/2024

### Triggering Kernel message and Observing Journald & Wazuh decoding
To trigger a kernel message, a USB device was plugged into a system with Wazuh agent.
Journald logs where being read in real time to observe the received messages.
`journalctl -f`

Below messages where received:
````
kvě 03 01:57:58 stockholm-ubuntu-agent-random kernel: usb 2-1: new high-speed USB device number 2 using ehci-pci
kvě 03 01:57:58 stockholm-ubuntu-agent-random kernel: usb 2-1: New USB device found, idVendor=0781, idProduct=5599, bcdDevice= 1.00
````
Checking the Wazuh manager's alerts.log to confirm the kernel message was properly decoded.
`cat /var/ossec/logs/alerts/alerts.log | grep usb`

Below decoded alert was received:
````
** Alert 1714694278.3210: - usb,gpg13_4.8,
May 02 23:57:58 stockholm-ubuntu-agent-random kernel: usb 2-1: New USB device found, idVendor=0781, idProduct=5599, bcdDevice= 1.00
````

### Conclusion
Kernel messages are properly decoded even when collected by `Journald` and not `/var/log/kern.log`

**Comment by JcabreraC** [comment]
LGTM !
