### ISSUE TITLE
Failing GitHub Actions for MacOS Integration Tests and Scan-Build Workflow

### ISSUE THREAD

**Issue by juliancnn** [wazuh/wazuh#23148]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| current | Github Actions | -| - | MacOS |

### Overview

Recently, two GitHub Actions workflows related to MacOS have begun failing without any recent changes to the codebase. The suspected cause is an underlying environment change, possibly due to updates in the MacOS runners provided by GitHub Actions. The affected workflows are specifically for MacOS integration tests (Tier 0 and 1) and the scan-build analysis for MacOS agent.

### Objectives

- **Diagnosis**: Identify the root cause of the failures in both MacOS workflows.
- **Resolution**: Implement necessary changes to restore workflow functionality.
- **Stability**: Ensure long-term stability and reliability of the CI process on MacOS platforms.

### Affected Workflows

1. **Integration Tests for Logcollector on MacOS - Tier 0 and 1**
   - File: `.github/workflows/integration-tests-logcollector-tier-0-1-macos.yml`
   - Symptom: Failing at runtime with no recent changes to the test scripts or Logcollector source code.

2. **Scan-Build MacOS Agent**
   - File: `.github/workflows/scan-build.yml`
   - Symptom: Failing possibly due to changes in the MacOS runner environment used by GitHub Actions.

### Suspected Cause

Both workflows utilize `macos-latest` as their runner, which recently may have been updated to a new MacOS version. Such updates can introduce compatibility issues or changes in the underlying system libraries and tools, impacting the execution of tests and builds.

### Tasks

- [x] **Initial Investigation**:
  - Review the logs from the failing workflows to pinpoint specific errors or changes in the environment.
  - Replicate the workflow runs locally or in a controlled environment to confirm if the issue is reproducible.
  
- [x] **Environment Analysis**:
  - Determine the exact MacOS version being used in the `macos-latest` runner at the time of failures.
  - Assess the impact of the MacOS update on the workflows, particularly looking at system libraries and toolchain versions.

- [x] **Workflow Modifications**:
  - Modify the GitHub Actions workflows to either pin a previously stable MacOS version or adjust the configuration to accommodate the latest MacOS updates.
  - Test changes in a feature branch to validate that the modifications resolve the issues without introducing new problems.

- [ ] **Documentation and Reporting**:
  - Document the changes made, the reasons behind them, and any implications for future workflow maintenance.
  - Update any CI/CD documentation to reflect the new configurations or setup.

### Testing Criteria

- **Workflow Success**: Both workflows should pass successfully in the CI environment after modifications.
- **No Regression**: Ensure that the changes do not introduce regressions or new failures in other parts of the CI pipeline.

### Notes

This issue is critical as it impacts the reliability of our CI processes for MacOS, which in turn affects development velocity and code quality assurance. Resolving this efficiently will help maintain the integrity of our development pipeline and ensure that contributions are validated against a stable and consistent CI setup.

**Comment by vikman90** [comment]
## To do

- [ ] Revert 68ce5972d179f8759333af011f59d268f457aaf3.
- [ ] Fix the new `scan-build` location:
```diff
--- /usr/local/opt/llvm@14/bin/scan-build
+++ /opt/homebrew/opt/llvm@14/bin/scan-build
```
- Upload pre-compiled external dependencies for macOS @ aarch64.

**Comment by jotacarma90** [comment]
# Update 05/06/2024

- Analysis done, indeed the problem is related to the macos-latest runner, which corresponds to:
|Virtual Machine | Processor (CPU) | Memory (RAM) | Storage (SSD) | Workflow label | Notes|
|-- | -- | -- | -- | -- | --|
|macOS | 3 (M1) | 7 GB | 14 GB | macos-latest or macos-14 | The macos-latest label currently uses the macOS 14 runner image.|


- Being ARM, there are several problems with the scan-build and python path:
  - Related issue mentioning this problem: https://github.com/actions/setup-python/issues/865
```
Version 3.10
   was not found in the local cache
  Version 3.10
   is available for downloading
  Download from "https://github.com/actions/python-versions/releases/download/3.10.14-8361245787/python-3.10.14-darwin-x64.tar.gz"
  Extract downloaded archive
  /usr/bin/tar xz -C /Users/runner/work/_temp/6faacca3-c70c-4cb1-aaeb-3[17](https://github.com/wazuh/wazuh/actions/runs/8839153826/job/24271872542#step:3:18)bb3765c5a -f /Users/runner/work/_temp/2f08a505-ba20-44bd-b563-eaa08f5cf69f
  Execute installation script
  Check if Python hostedtoolcache folder exist...
  Create Python 3.10.14 folder
  Copy Python binaries to hostedtoolcache folder
  Create additional symlinks (Required for the UsePythonVersion Azure Pipelines task and the setup-python GitHub Action)
  Upgrading pip...
  Error: dyld[3290]: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
    Referenced from: <09857011-94D0-3FBA-9F9D-9FCE0E7366FF> /Users/
  Error: runner/hostedtoolcache/Python/3.10.14/x64/bin/python3.10
    Reason: tried: '/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/usr/local/lib/libintl.8.dylib' (no such file), '/usr/lib/libintl.8.dylib' (no such file, not in dyld cache)
  ./setup.sh: line 52:  3[29](https://github.com/wazuh/wazuh/actions/runs/8839153826/job/24271872542#step:3:30)0 Abort trap: 6           ./python -m ensurepip
  Error: The process '/bin/bash' failed with exit code 134
```

- Working on the creation of the precompiled external dependencies file.
- Testing with the scan-build workflow using EXTERNAL_SRC_ONLY failed: https://github.com/wazuh/wazuh/actions/runs/9387522361/job/25850636498

**Comment by jotacarma90** [comment]
# Update 06/06/2024

- Current changes in PR
  - Revert to `macos-latest`
  - Solved python installation issues updating python version to 3.11.
  - Solved scan-build issues modifying command path.
  - Created external folder zip with precompiled dependencies.
    - After use the EXTERNAL_SRC_ONLY tag, and try to compile dependencies, the problem was brew not installed in the system, after install it, this error was solved:
```
./autogen.sh: line 14: libtoolize: command not found
./autogen.sh: line 16: aclocal: command not found
./autogen.sh: line 17: autoheader: command not found
./autogen.sh: line 18: automake: command not found
./autogen.sh: line 19: autoconf: command not found
```
  - external precompiled dependencies to test it: https://drive.google.com/file/d/1o1PRyEdjrbr_G5caQX4PsWxNJbGcKBWL/view?usp=sharing

**Comment by MarcelKemp** [comment]
Fixed by https://github.com/wazuh/wazuh/pull/23927 or https://github.com/wazuh/qa-integration-framework/pull/181
