### ISSUE TITLE
Post release tasks for 4.7.4

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#23180]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.7.4.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.7.4-into-4.8.0`.

## Tasks

- https://github.com/wazuh/wazuh/pull/23190
- https://github.com/wazuh/wazuh/pull/23191
- https://github.com/wazuh/wazuh/pull/23212
- [x] Publish GitHub release as latest.
- [x] Delete all stage pre-releases for 4.7.4 (https://github.com/wazuh/wazuh/releases).
- [x] Fast-forward definitive tag v4.7.4 to `4.7.4` branch
- [x] Delete all stage tags for v4.7.4. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.7.4-rc1, 4.7.4-alpha1, etc.
