### ISSUE TITLE
Debian Buster vulnerabilities will no longer be available

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#23235]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| All | Vulnerability Detector | Manager | All | Debian Buster |

### Description

The end of support for Debian 10 Buster will be reached on June 30th.

![image](https://github.com/wazuh/wazuh/assets/37207742/b97b6683-9cd2-4ae6-9569-666cad91e4c7)

Unfortunately, that means that they do not provide affected packages for Debian Buster in the [Security tracker feed](https://security-tracker.debian.org/tracker/data/json), which Vulnerability Detector needs to scan Debian agents for vulnerabilities in the package inventory.

On Wazuh's side, it is necessary to remove Debian Buster support in Vulnerability Detector. We can see the same task done for Debian Stretch two years ago:
- https://github.com/wazuh/wazuh/issues/14354

Reported in:
- https://github.com/wazuh/wazuh/issues/23214

### Tasks in currently code

- [ ] Avoid indexing the Debian Buster OVAL feed, used for the CVE metadata
- [ ] Remove Debian Buster from the Vulnerability Detector configuration templates
- [ ] Avoid scanning Debian Buster agents in Vulnerability Detector
- [ ] Include a warning message when detected a Debian Buster agent is being scanned
- [ ] Remove integration tests related to Debian Buster in Vulnerability Detector 
- [ ] Deprecate Debian Buster in the Wazuh documentation

**Comment by Dwordcito** [comment]
@Damian-Mangold check the impact in vpd of this issue.

**Comment by Damian-Mangold** [comment]
Hello @Dwordcito,

Assuming it happens as in previous cases, where all vulnerability information associated with "Buster" is removed from the feed, the impact on CTI content would be significant.

Currently, in the CTI feed, there are 629,121 affected packages where the "platform" includes "Buster", distributed across 28,009 CVEs.

**Comment by Dwordcito** [comment]
This is unnecessary in versions upper or equal to 4.8.0; we do not deliver a 4.7.x patch.
