### ISSUE TITLE
Scheduled upward merges for numbered branches - Fortnight #10

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#23565]
# Description

The goal of this is to track the completion of the following tasks so the development branches are up to date in every repository, ensuring a clean environment for our development teams.

# Tasks

### wazuh-qa -> @wazuh/qa
- https://github.com/wazuh/wazuh-qa/issues/5418
### wazuh-jenkins -> @wazuh/qa
- https://github.com/wazuh/wazuh-jenkins/issues/6518
### wazuh-automation -> @wazuh/devops
- https://github.com/wazuh/wazuh-automation/issues/1673
### wazuh-packages -> @wazuh/agent
- https://github.com/wazuh/wazuh-packages/issues/2959
### wazuh -> @wazuh/cppserver
- https://github.com/wazuh/wazuh/issues/23564
### wazuh-ansible -> @wazuh/devops
- https://github.com/wazuh/wazuh-ansible/issues/1293
### wazuh-docker -> @wazuh/devops
- https://github.com/wazuh/wazuh-docker/issues/1349
### wazuh-puppet -> @wazuh/devops
- https://github.com/wazuh/wazuh-puppet/issues/1008
### wazuh-kubernetes -> @wazuh/devops
- https://github.com/wazuh/wazuh-kubernetes/issues/681
### wazuh-dashboard-plugins -> @wazuh/dashboard
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6695
### wazuh-documentation -> @wazuh/qa
- https://github.com/wazuh/wazuh-documentation/issues/7324
### qa-integration-framework -> @wazuh/pyserver
- https://github.com/wazuh/qa-integration-framework/issues/166
### wazuh-security-dashboards-plugin -> @wazuh/dashboard
- https://github.com/wazuh/wazuh-security-dashboards-plugin/issues/49
### wazuh-indexer -> @wazuh/indexer
- https://github.com/wazuh/wazuh-indexer/issues/232

## 2. Upload installation assistant in packages-dev -> @wazuh/qa

- [x] Upload installation assistant in packages-dev using `Publish_unattended` pipeline. **BE CAREFUL NOT TO UPLOAD IT TO PRODUCTION** To be done as part of https://github.com/wazuh/wazuh-jenkins/issues/6530

## 3. Create AWS resources  -> @wazuh/qa

- [x] Regenerate AWS resources using the Procedure_ecs_task_tier pipeline on branches that have been modified/bumped.
  - [x] 4.8.0: https://ci.wazuh.info/job/Procedure_ecs_task_tier/150/
