### ISSUE TITLE
Support new stage RC 3 for 4.8.0 in wazuh repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#23613]
## Description

This issue attempts to support a new stage RC 3 for 4.8.0 in the wazuh repository.

## Tasks

- [x] #23615
- [x] Create tag v4.8.0-rc3 from branch 4.8.0 on wazuh repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh/releases/tag/v4.8.0-rc3.

## New tasks

- [x] Merge https://github.com/wazuh/wazuh/issues/23646 into 4.8.0 branch,
- [x] Upload 4.8.0 changelog if needed
- [x] Delete the v4.8.0-rc3 release notes,
- [x] Delete the v4.8.0-rc3 tag,
- [x] Create tag v4.8.0-rc3 from branch 4.8.0 on wazuh repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh/releases/tag/v4.8.0-rc3.

**Comment by vikman90** [comment]
We need to retag RC3.
