### ISSUE TITLE
Support new stage RC 2 for 4.7.5 in wazuh repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#23761]
## Description

This issue attempts to support a new stage RC 2 for 4.7.5 in the wazuh repository.

## Tasks

- [x] Ensure changelog is updated for 4.7.5 (if applicable).
- [x] https://github.com/wazuh/wazuh/pull/23765
- [x] Create tag v4.7.5-rc2 from branch 4.7.5 on wazuh repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh/releases/tag/v4.7.5-rc2.

**Comment by jnasselle** [comment]
Reopening this issue because the REVISION should be 40720
