### ISSUE TITLE
Post release tasks for 4.7.5

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh#23778]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.7.5.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.7.5-into-4.8.0`.

## Tasks

- [ ] Merge branch `4.7.5` into branch `4.8.0`. 
- [ ] Merge branch `4.8.0` into branch `4.9.0`. 
- [ ] Merge branch `4.9.0` into branch `master`. 
- [ ] Publish GitHub release as latest.
- [ ] Delete all stage pre-releases for 4.7.5 (https://github.com/wazuh/wazuh/releases).
- [ ] Fast-forward definitive tag v4.7.5 to `4.7.5` branch
- [ ] Delete all stage tags for v4.7.5. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.7.5-rc1, 4.7.5-alpha1, etc.
