### ISSUE TITLE
Wazuh manager workflow continued when the package build failed

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#23779]
# Description

Testing the QA stage generation script, I have found an error while using a branch with a build error related to the spec file

Workflow run: https://github.com/wazuh/wazuh/actions/runs/9291975231/job/25571767415

```
RPM build errors: 

 File listed twice: /var/ossec/wodles/aws 
 File listed twice: /var/ossec/wodles/aws/__init__.py 
 File listed twice: /var/ossec/wodles/aws/aws-s3 
...

 Installed (but unpackaged) file(s) found: 
 /var/ossec/framework/wazuh/core/cluster/hap_helper/__init__.py 
 /var/ossec/framework/wazuh/core/cluster/hap_helper/hap_helper.py 
 /var/ossec/framework/wazuh/core/cluster/hap_helper/proxy.py 
 /var/ossec/framework/wazuh/core/cluster/hap_helper/wazuh.py
```

As the workflow log shows, the RPM name was not set and the sha512sum step was stuck in a loop

https://github.com/wazuh/wazuh/actions/runs/9291975231/job/25571767415

![image](https://github.com/wazuh/wazuh/assets/14913942/fd0d9785-8411-4105-84dd-a3eafbfa1fcd)

We need to review this, the build process failed but the process continued when it should have been stopped

We also need to set a workflow timeout in case we find another run like this

## Related

- Branch used: https://github.com/wazuh/wazuh/pull/23513/commits
- Commit: efb7bc307cc08a2f9a2a1d89fc11f0950fc21a36

# Tasks

- [x] Research: Identify why the build didn't return code 1
- [x] Fix error handling and workflow stage to stop the run if an error is found
- [x] Add a workflow timeout (it should be at least, twice the actual run time)
- [x] Check the agent workflows in case this behavior also occurs

**Comment by lchico** [comment]
# Update
I'm doing some research and looking for a solution.

**Comment by lchico** [comment]
# Update
All the changes have been made and tested locally. They are just pending a test using the workflow.

**Comment by lchico** [comment]
# Update
The PR has been tested and everything looks good. We already have one approval.
