### ISSUE TITLE
Ignore option for Syscheck makes global ignores on the manager

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#2378]
## Bug report

**Install type**
_manager_

**Config sample**

```
<syscheck>
    ...
    <!-- Files/directories to ignore -->
    <ignore>/etc/mtab</ignore>
    <ignore>/etc/hosts.deny</ignore>
    <ignore>/etc/mail/statistics</ignore>
    <ignore>/etc/random-seed</ignore>
    <ignore>/etc/random.seed</ignore>
    <ignore>/etc/adjtime</ignore>
    <ignore>/etc/httpd/logs</ignore>
    <ignore>/etc/utmpx</ignore>
    <ignore>/etc/wtmpx</ignore>
    <ignore>/etc/cups/certs</ignore>
    <ignore>/etc/dumpdates</ignore>
    <ignore>/etc/svc/volatile</ignore>
    <ignore>/sys/kernel/security</ignore>
    <ignore>/sys/kernel/debug</ignore>
    ...
</syscheck>
```

Bug description
----------------
The `ignore` tag of Syscheck works in a different way for agents and manager. In agents, it works at FIM level by ignoring specified files when monitoring them. 

However, when setting the same configuration on the manager side, it affects all the events coming from agents ignoring every event related to those files globally by the Analysis engine.

This is an inconsistency we have to face by adding a global ignore option for Analysisd.

**Update:**

To solve all inconsistencies with the FIM configuration. Apart from make the ignore option applies only to the Syscheck module, we will move the FIM options at decoder level to the global section of the configuration. It would look like:

```
<global>
  ...
  <fim>
    <ignore>...</ignore>
    <auto_ignore frequency="X" timeframe="Y">...</auto_ignore>
    <alert_new_files>...</alert_new_files>
  </fim>
</global>
```

Here is the list of subtasks to reach the main goal:

## Tasks

- [x] Makes the ignore option does not apply to the Syscheck decoder.
- [x] New FIM structure at the global section working as before.
- [x] Adapt templates of the configuration file (ossec.conf).
- [x] Warning messages about deprecated options of Syscheck.
- [x] Adapt the functions to query the configuration remotely to the new structure. Related issue: https://github.com/wazuh/wazuh/issues/2373

**Comment by juan70** [comment]
# Status
2019-01-30 
--
  - Implementation of the reading of the new `<fim>...</fim>` block within the `<global>` section.
  - Syscheck options `alert_new_files` and `auto_ignore` throw a `deprecated` warning. But they are still working.
  - Syscheck `<ignore>` options not taken into account in syscheck decoder. The ones taken into account are now those existing in the new `<fim>...</fim>` block.
  - Some on the fly quick testing.

**Comment by chemamartinez** [comment]
It is important to explain in the documentation reference that the `ignore` option for Syscheck accepts directories and SRegex as attributes. However, the one for Analysisd (`<global><fim><ignore>`) just matches with filenames stores in the manager DB (it doesn't support directories or any regex expression).

**Comment by Lopuiz** [comment]
Hello team,

Good news! New FIM solves it, so I am going to close this issue.

Regards,
Eva
