### ISSUE TITLE
Support new OSs - AlmaLinux 8.10 - Check agent output in Dashboard

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#23871]
# Description
| Related issue | Epic issue |
|---|---|
| https://github.com/wazuh/wazuh/issues/23838 | https://github.com/wazuh/wazuh/issues/23868 |

| Agent support | Agent tier | Central components support | OS type |
|-|-|-|-|
|Yes | 2 | No | Minor |

# Plan

- [ ] If we need to add support for the agent, we need to test functionality for all stateful modules according to the OS's tier.
- [ ] If we need to add support for the agent, we need to make sure that the agent-related information in the agent list is correct.
- [ ] If we need to add support for the agent, we need to test the deployment one-liner for the new OS.

**Comment by lucianogorza** [comment]
# Testing

## :green_circle: Make sure that the agent-related information is correct.

<details>
<summary>Agent list</summary>

![image](https://github.com/wazuh/wazuh/assets/103193307/ff4d2c93-730b-493c-ae1e-8e82bdac591b)

</details>

<details>
<summary>Agent summary</summary>

![image](https://github.com/wazuh/wazuh/assets/103193307/e95db06d-a28e-4eac-b0ae-4d7b1792ee6e)

</details>

<details>
<summary>Security events</summary>

![image](https://github.com/wazuh/wazuh/assets/103193307/ae627e7c-f204-46c9-b3f2-0f31af84008a)
![image](https://github.com/wazuh/wazuh/assets/103193307/440d1284-875f-4a11-9339-7dd77060dac4)

</details>

**Comment by Tostti** [comment]
LGTM
