### ISSUE TITLE
Engine Indexer communication.

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#23894]
# Description
This epic focuses on integrating a developed module with a simplified interface that receives alerts from JSON data to Wazuh-Indexer. This module is designed to be a direct replacement for the existing functionality provided by Filebeat.

Previously, the module was developed under the epic https://github.com/wazuh/wazuh/issues/17894 which aimed to create a straightforward interface for event handling and state synchronization with Wazuh-Indexer. The module has been tested to ensure it meets the functional, performance, and compatibility requirements.

## Functional Requirements
- **Alert Indexing**: Must index the generated alerts in Wazuh-Indexer.
- **Common Configuration Usage**: Should utilize the common/global configuration of the Indexer Connector.
- **Persistence and Recovery**: Should be persistent and capable of recovering from failures.

## Implementation Restrictions
- **Compatibility**: The module must be compatible with the current Wazuh-Indexer infrastructure and any future updates.
- **Minimal Disruption**: The integration process should minimize disruption to the existing system and operations.

## Plan
0. **Filebeat vs indexer connector featuring**
    - #24098

1. **Preparation for Integration**: -> @wazuh/devel-cppserver-div1 
    - [x] #24353
    - [x] https://github.com/wazuh/wazuh/issues/24351
    - [x] https://github.com/wazuh/wazuh/issues/24099
    - [x] https://github.com/wazuh/wazuh/issues/24352
    - [x] #25119
    - [x] #25325

2. **Integration Process**: @wazuh/devel-cppserver-div3 
    - [x] #24354

3. **Discovered issues during the integration process**: -> @wazuh/devel-cppserver-div1 
    - [x] #25547
    - [x] #25542
    - [x] #25541
    - [x] #25540

4. **Issue from 4.x to 5.0**: -> @wazuh/devel-cppserver-div1 
    - [x] #25717

**Comment by Dwordcito** [comment]
Step 1 for the plan - Assigned to @wazuh/devel-cppserver-div1 , moved to backlog.

**Comment by sebasfalcone** [comment]
## Updated ETA
Stages 3 and 4 were delayed due to issues related to 4.9.1 and 4.10.0 release being pushed to completion

**Comment by sebasfalcone** [comment]
## ETA update
Due to delays in https://github.com/wazuh/wazuh/issues/25542

**Comment by Dwordcito** [comment]
All related development for this epic is finished.
