### ISSUE TITLE
Review versions references in package generation files

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#23999]
# Description

Testing the 4.9.0 Wazuh agent and Wazuh manager package generation I observed the following things:

- The Wazuh manager SPEC file defines a VD filename referencing to 4.8.0
- Changelogs have references to the old 4.8.1 and 4.8.2 versions 

We need to validate if the 4.8.0 references are valid or should be changed, the tasks defined in this issue should contemplate the following:

- Wazuh manager
- Wazuh agent

## Related

- https://github.com/wazuh/wazuh/pull/22741
- https://github.com/wazuh/wazuh-jenkins/issues/6371
- https://github.com/wazuh/internal-devel-requests/issues/187

# Tasks

- [x] Review all 4.8.0, 4.8.1, and 4.8.2 references in the package generation files 4.9.0 branch
- [x] Validate the VD filename version
- [x] Remove/modify all version references that should not exist or should be updated
