### ISSUE TITLE
Engine - Update Design Document for Engine

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#24027]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0.0 | Engine | Manager | Packages | OS version |

|Epic|
|---|
|https://github.com/wazuh/wazuh/issues/23968|

## Description:
We need to review and update the current design document for the Engine. This includes:

- Reviewing the existing content.
- Updating sections that describe the architecture, components, and workflows of the Engine.
- Documenting any recent changes or improvements to the Engine.

## Tasks:

- [x] Review the current design document.
- [ ] Update the architecture description.
- [ ] Update the components and workflows sections.
- [ ] Ensure all recent changes and improvements are documented.

References:

[Design document](https://docs.google.com/document/d/125d8tpj192MNdggLcNjk_R0tQWEuhjBEmtjONHbUkHo/edit#)

**Comment by JcabreraC** [comment]
## Update
Reviewed and completed sections:
- Common Schema
  - Configuration Schema
  - Data Schema
- Router, Environment and Policy
- The Policy
  - Decoding Process
  - Security Enrichment Process
  - Archiving and Alerting Process

**Comment by JcabreraC** [comment]
## Update
Reviewed and completed sections:
- Syntax elements
  - Schema
    - Variable expression
    - Helper function expression
    - Definitions
    - Databases
    - Services
- Components
  - Classes of components
  - Atributte
  - Stage

**Comment by JcabreraC** [comment]
Key sections of the document have been updated.

As this is a living document, it will continue to evolve with future developments.

Therefore, I am closing this issue.
