### ISSUE TITLE
Engine - Revise User Manual

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#24028]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0.0 | Engine | Manager | Packages | OS version |

|Epic|
|---|
|https://github.com/wazuh/wazuh/issues/23968|

## Description:
We need to revise the user manual to reflect the latest features and functionalities of the Engine. This includes:

- Including new usage examples.
- Updating configuration options.
- Adding troubleshooting tips.

## Tasks:
- [x] Review the current user manual.
- [x] Update with the latest features and functionalities.
- [x] Add new usage examples.
- [x] Update configuration options.
- [x] Add troubleshooting tips.

References:

[User manual](https://docs.google.com/document/d/1N0p7pd7XszQwFU9HBjpB7txIw2DCcAsV-BKfEZSLixw/edit)

**Comment by juliancnn** [comment]
# Daily update

Started to modify the parser section, update documentation and add parser documentation. The parsers are not documented or the documentation is scarce. Updated the parsers of:
- Bool
- Long
- Double
- float
- scaled_float
- byte
- text
- ip

**Comment by juliancnn** [comment]
## Daily update
- Complete the schema parser seccion
- In an analysis of source code to create functionality documentation, it was detected that numerical parsers with scientific notation work when a symbol is expressed after the letter e, it will be fixed tomorrow
- Isses with event indexing, when there are custom fields that can take different types, they generate a problem when indexing

Next step: High level parser, and fix numeric parsers

**Comment by JavierBejMen** [comment]
## Update

Reviewed sections up to the Reference section and documented changes to be done

**Comment by juliancnn** [comment]
## Daily update
Update High level parsers: 
 - Literal
 - Quoted
 - DSV
 - CSV
 - JSON
 
Next step: Continue with High level parser

**Comment by JavierBejMen** [comment]
## Update
Migrated basic command line reference to a subpage
Migrated and improved:
- Introduction section
- How it works section
- Getting started section
- Operations guide section

Working on:
- Development guide section
- Moving diagram images to draw files in the drive

**Comment by JavierBejMen** [comment]
## Update
Migrated some development figures to drawings and tables to sheets
Migrated and improved:
- Developing a new integration
- Event acquisition
- Default policy (made it its own section before operations guide)

**Comment by JavierBejMen** [comment]
## Update
Migrated some development figures to drawings and tables to sheets
Migrated and improve:
- Common Schema
- Adding integration decoders
- Testing a policy
- Router, environment and policy

Working on giving structure to the document to guide the reader in an orderly manner without duplicating too much information.

**Comment by juliancnn** [comment]
## Update

Review, fix and document the following parsers:
- xml
- kv
- uri
- fqdn
- file
- ignore
- between
- alphanumeric
- Useragent

**Comment by JavierBejMen** [comment]
## Update
Accommodated migrated sections following the new structure.
Added Assets sub-section in under the hood
Added The Policy section
Added Integrations section
Working on how to add a decoder in development guide (migrated some sections and working on new ones)

**Comment by juliancnn** [comment]
## Update
- Review of site docuemnt with suggest of changes
- Created and completed the message and queue protocol sections in the google document

**Comment by JavierBejMen** [comment]
## Update
- Review comments
- Working on how to add a decoder in development guide

**Comment by juliancnn** [comment]
## Update

- Migrating/Sync google site and doc
- Working on develop Asset / stages

**Comment by JavierBejMen** [comment]
## Update
Finished develop a new asset subsection
Added definitions section

**Comment by JavierBejMen** [comment]
## Update
Restructured stage sections inside the standard library
Added Attributes section in the standard library
Working on developing rules section
Completed and general QoL in the whole document

**Comment by JavierBejMen** [comment]
## Update
In developing asset section:
- Added aset types
- Added Operations
- Added Execution Graph Summary (with drawings)
- Added Helper functions

Added various comments with reminders to update and general QoL (style and structure) on the document

**Comment by juliancnn** [comment]
## Update

Create new tool seccion:
- Start and finish the `evtx2xml` manual
- Start and finish the `engine-test` manual

**Comment by juliancnn** [comment]
## Update

Working on parser:
- How it works/introduccion
- EndTokens and parser combinations
- Specifc parsers (All schema parsers and start winth specific parsers.

**Comment by JavierBejMen** [comment]
## Update
User manual:
- Cleaned old comments
- Added how to update engine schema section
- QoL

Added markdown for engine-schema script and updated readme of engine-suite

**Comment by juliancnn** [comment]
## Update

Working and finish with all specific parsers (xml, kv,,uri,fqdn,file,ignore,between,alphanumeric)

**Comment by JavierBejMen** [comment]
## Update
Fixed headers in Parsers and helpers sections

**Comment by juliancnn** [comment]
## Update
-  Created new readme.md files with descriptions and configurations for the tests

**Comment by juliancnn** [comment]
## Update

- Add new documentation (Setup, descripton, quick guide, structure and more) for:
  - Test in general
  - Integration Test
  - Healt Test
  - Acceptance Test
 - Fixed IT Configuration
