### ISSUE TITLE
Engine - Create Quick Start Guide

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#24040]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0.0 | Engine | Manager | Packages | OS version |

|Epic|
|---|
|https://github.com/wazuh/wazuh/issues/23968|

## Description:
We need to create a quick start guide for the Engine. This guide should help users get started quickly without having to read the entire user manual. It should explain the basic operation of the Engine.

## Tasks:
- [x] Draft a quick start guide.
- [x] Include basic operations of the Engine.
- [x] Ensure the guide is concise and easy to follow.

**Comment by juliancnn** [comment]
## Daily update

- Catalog section started and completed
- Created the google guide site and moved the content to a new location

**Comment by JcabreraC** [comment]
## Update
- Thoroughly revised the documentation
- Applied consistent formatting throughout the document
