### ISSUE TITLE
Engine - Create Decoder Issue Template

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#24042]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0.0 | Engine | Manager | Packages | OS version |

|Epic|
|---|
|https://github.com/wazuh/wazuh/issues/23968|

## Description:
We need to create a template for creating decoder issues in our repository. This template should include a checklist of tasks that need to be followed for a decoder integration to be considered valid.

## Tasks:
- [ ] Draft a decoder issue template.
- [ ] Include a checklist of necessary tasks.
- [ ] Ensure the template is clear and comprehensive.

**Comment by JcabreraC** [comment]
## Update:
- Added detailed steps to guide users through the process.
- Included non-visible comments to provide additional context and facilitate understanding of the template.

**Comment by JavierBejMen** [comment]
## Update
Added steps based on the documentation, ordered following the working flow.

**Comment by JcabreraC** [comment]
## Update
- Revised the template and added steps and comments.

**Comment by juliancnn** [comment]
## Daily update
- Create the issue, PR and template
-  W / @JavierBejMen on several improvements
