### ISSUE TITLE
Post release tasks for 4.8.0

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#24057]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.8.0.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.8.0-into-4.8.1`.

## Tasks

- [x] [Merge branch `4.8.0` into branch `4.8.1`.](https://github.com/wazuh/wazuh/pull/24070)
- [x] [Merge branch `4.8.1` into branch `4.9.0`.](https://github.com/wazuh/wazuh/pull/24075)
- [ ] [Merge branch `4.9.0` into branch `master`.](https://github.com/wazuh/wazuh/pull/24083)
- [ ] Publish GitHub release as latest.
- [ ] Delete all stage pre-releases for 4.8.0 (https://github.com/wazuh/wazuh/releases).
- [ ] Delete all stage tags for v4.8.0. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.8.0-rc1, 4.8.0-alpha1, etc.
