### ISSUE TITLE
API: Flask PoC

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh#2413]
We have to review the following points to perform the API migration to Python 3.7:
### 4th week sprint
- [x] API installation -> API should be installed by default when wazuh-manager, without any manual pre or post installation configuration. To achieve this, I have modified several Makefiles and implemented a daemonized flask app (in a similar way to wazuh-clusterd)
- [x] Cluster and API connection: currently we have 3 endpoints implemented (local_master and distributed_master types) and working. I have simplified the format used between nodes for sending and receiving commands. It will allow us removing the request_list.py file, which is redundant.
- [x] OpenAPI spec. We have a detailed specification for 3 endpoints:
   * GET /agents
   * DELETE /agents
   * PUT /agents/restart

### Tasks
- [x] (#2564) Authentication
- [ ] ~~(https://github.com/wazuh/wazuh-api/issues/114, https://github.com/wazuh/wazuh-api/pull/140) RBAC~~
- [x] (#2566) Research how to generate documentation automatically taking the openapi specification as input 
- [x] (#2567) Migration: Care must be taken when an user upgrades from the nodeJS to python API, specially regarding config.js. This task should be done in the installation script.
- [x] (#2568) Path naming. We should convey the most convenient folder structure for the API, python interpreter and its libraries, framework and cluster. I have followed this structure on my own, subject to discussion:
    * /var/ossec/python/ -> Python installation, packages, ...
    * /var/ossec/api -> Python API
    * /var/ossec/bin/wazuh-apid -> API launcher in daemon mode

- [x] (#2569) Logging
- [x] (#2570) Configuring API, ideally with a YAML file
- [x] (#2571) Parameter validation. Currently, `connexion` package performs basic validation. Pending to review if more validation is required

**Comment by crd1985** [comment]
We have to review the following points to perform the API migration to Python 3.7:
- [ ] Authentication
   - [ ] RBAC
- [x] API installation -> API should be installed by default when wazuh-manager, without any manual pre or post installation configuration. To achieve this, I have modified several Makefiles and implemented a daemonized flask app (in a similar way to wazuh-clusterd)
   - [ ] Care must be taken when an user upgrades from the nodeJS to python API, specially regarding config.js. This task should be done in the installation script.
- [ ] Path naming. We should convey the most convenient folder structure for the API, python interpreter and its libraries, framework and cluster. I have followed this structure on my own, subject to discussion:
    * /var/ossec/python/ -> Python installation, packages, ...
    * /var/ossec/api -> Python API
    * /var/ossec/bin/wazuh-apid -> API launcher in daemon mode
- [x] Cluster and API connection: currently we have 3 endpoints implemented (local_master and distributed_master types) and working. I have simplified the format used between nodes for sending and receiving commands. It will allow us removing the request_list.py file, which is redundant.
- [ ] Logging
- [ ] Configuring API, ideally with a YAML file
- [x] OpenAPI spec. We have a detailed specification for 3 endpoints:
   * GET /agents
   * DELETE /agents
   * PUT /agents/restart
- [ ] Research how to generate documentation automatically taking the openapi specification as input
- [ ] Parameter validation. Currently, `connexion` package performs basic validation. Pending to review if more validation is required

**Comment by crd1985** [comment]
Closing this issue since the minimum requirement for the PoC have been met.

The current development is being held on https://github.com/wazuh/wazuh/tree/dev-flask-poc branch.
