### ISSUE TITLE
Support new OSs - macOS Sequoia 15 - Add support in QA procedures

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#24157]
# Description
| Related issue | Epic issue |
|---|---|
| https://github.com/wazuh/wazuh/issues/25665 | https://github.com/wazuh/wazuh/issues/24146 |

| Agent tier | Central components support | OS type |
|-|-|-|
| 1 | No | Major |

# Plan

**QA**
## Considerations

- Testing environment: Deploy the new OS taking into account the following notes:
  - If the Wazuh central components are supported: 1 VM
  - If the Wazuh agent is supported: 1 VM for each architecture supported.
  - If the Wazuh central components or the Wazuh agent is not supported, deploy a Debian 12 VM for the non-supported component.
- All testing tasks must be completed for each OS architecture supported.
- The following tasks should be completed in order.

## Tasks

- [x] Test the Wazuh dashboard one-liner deployment. https://github.com/wazuh/wazuh/issues/24157#issuecomment-2377159156
  - [x] Deploy a Wazuh agent using the Wazuh dashboard one-liner feature provided in the Wazuh user interface with the following cases.
    - [x] Only IP address.
    - [x] Only FQDN.
    - [x] IP address, agent name, and group.
- [x] Add/Update/Check CI https://github.com/wazuh/wazuh/issues/24157#issuecomment-2378630850
  - [x] Test the JobFlow testing tool for that specific system.
  - [x] Add the OS and each architecture to the JobFlow testing tool.
  - [x] Add the OS and each architecture to the GitHub Deployability and Upgrade release templates.
- [x] Add the OS and its supported architectures to the E2E UX Tests spreadsheet (OS sheet).
- [x] Add the OS as supported in the compatibility system spreadsheet.
- [x] ~We need to add proper documentation, including adding the new OS version if it belongs to an OS family already added to these tables:~ All the documentation is related to Wazuh Central Components while macOs support is only for the Wazuh-Agent
  - [x]  ~https://documentation.wazuh.com/current/quickstart.html#operating-system~
  - [x]  ~https://documentation.wazuh.com/current/installation-guide/wazuh-server/index.html#recommended-operating-systems~
  - [x]  ~https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/index.html#recommended-operating-systems~
  - [x]  ~https://documentation.wazuh.com/current/installation-guide/wazuh-dashboard/index.html#recommended-operating-systems~

I have checked the macOS Agents section to see if there is any reference to versions but I have not found anything [here](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-linux.html).

**Comment by MarcelKemp** [comment]
Due to the change in the process, I am closing this issue as not planned because it is a pre-release version.

**Comment by jotacarma90** [comment]
Reopened due to release date for macOS 15 Sequoia is here:
https://9to5mac.com/2024/09/09/macos-sequoia-release-date/

**Comment by pro-akim** [comment]
## ## Test the Wazuh dashboard one-liner deployment :construction:

**Comment by pro-akim** [comment]
## Add/Update/Check CI :construction: 
### Test the JobFlow testing tool for that specific system.
<details><summary>YAML</summary>

```
version: 0.1
description: This workflow is used to test agents deployment for DDT
variables:

  macos-agent-os:
    - macos-sequoia-15-amd64
    - macos-sequoia-15-arm64

  manager-os: linux-ubuntu-22.04-amd64
  infra-provider: aws
  macos-infra-provider: vagrant
  working-dir: /tmp/dtt1-poc

tasks:
  # Unique manager allocate task
  - task: "allocate-manager-{manager-os}"
    description: "Allocate resources for the manager."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: create
          - provider: "{infra-provider}"
          - size: large
          - composite-name: "{manager-os}"
          - inventory-output: "{working-dir}/manager-{manager-os}/inventory.yaml"
          - track-output: "{working-dir}/manager-{manager-os}/track.yaml"
          - label-termination-date: "1d"
          - label-team: "qa"
          - label-issue: "https://github.com/wazuh/wazuh/issues/24157"
    on-error: "abort-all"
    cleanup:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: delete
          - track-output: "{working-dir}/manager-{manager-os}/track.yaml"

  # Unique manager provision task
  - task: "provision-manager-{manager-os}"
    description: "Provision the manager."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/provision/main.py
          - inventory: "{working-dir}/manager-{manager-os}/inventory.yaml"
          - install:
            - component: wazuh-manager
              type: assistant
              version: <major.minor.patch>
              live: False
    depends-on:
      - "allocate-manager-{manager-os}"
    on-error: "abort-all"

  # Unique agent allocate task
  - task: "allocate-macos-agent-{agent}"
    description: "Allocate resources for the agent."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: create
          - provider: "{macos-infra-provider}"
          - size: small
          - composite-name: "{agent}"
          - inventory-output: "{working-dir}/agent-{agent}/inventory.yaml"
          - track-output: "{working-dir}/agent-{agent}/track.yaml"
          - label-termination-date: "1d"
          - label-team: "qa"
          - label-issue: "https://github.com/wazuh/wazuh/issues/24157"
    on-error: "abort-all"
    foreach:
      - variable: macos-agent-os
        as: agent
    depends-on:
      - "provision-manager-{manager-os}"
    cleanup:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: delete
          - track-output: "{working-dir}/agent-{agent}/track.yaml"

  # Generic agent test task
  - task: "run-macos-agent-{agent}-tests"
    description: "Run tests install for the agent {agent}."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/testing/main.py
          - targets:
            - wazuh-1: "{working-dir}/manager-{manager-os}/inventory.yaml"
            - agent: "{working-dir}/agent-{agent}/inventory.yaml"
          - tests: "install,registration,connection,basic_info,restart,stop,uninstall"
          - component: "agent"
          - wazuh-version: "4.9.0"
          - wazuh-revision: ""
          - live: True
    foreach:
      - variable: macos-agent-os
        as: agent
    depends-on:
      - "allocate-macos-agent-{agent}"

```
</details>

**Comment by pro-akim** [comment]
On hold due to https://github.com/wazuh/wazuh-qa/issues/5778

**Comment by pro-akim** [comment]
On hold due to 4.9.1-RC2 release testing

**Comment by rauldpm** [comment]
Based on https://github.com/wazuh/wazuh/issues/25993#issuecomment-2384954910 let's change the https://github.com/wazuh/wazuh-qa/blob/9eba4fb752e2d4b8862e9a96c7db9c0afbc8d9c5/deployability/modules/testing/tests/helpers/generic.py#L875C75-L875C115 test to use wazuh-control status instead of ps, as macOS systems do not have systemctl or service

Test the `launchctl` too, in case we can use it https://apple.stackexchange.com/questions/364094/how-to-view-status-of-service-e-g-whether-its-running-in-a-format-similar-to

**Comment by pro-akim** [comment]
Testing with `launchctl` I could not find the agent between the processes

<details> 
```
sh-3.2# /Library/Ossec/bin/wazuh-control status
wazuh-modulesd is running...
wazuh-logcollector is running...
wazuh-syscheckd is running...
wazuh-agentd is running...
wazuh-execd is running...
sh-3.2# launchctl list 
PID	Status	Label
-	0	com.apple.mobile.obliteration
255	0	com.apple.security.cryptexd
313	0	com.apple.CoreAuthentication.daemon
154	0	com.apple.coreservicesd
273	0	com.apple.modelcatalogd
-	0	com.apple.touchbarserver
1153	0	com.apple.deleted_helper
-	0	com.apple.avbdeviced
-	0	com.apple.cvmsServ
-	0	com.apple.applessdstatistics
-	0	com.apple.corercd
-	0	com.apple.hdiejectd
-	0	com.apple.corestorage.corestoraged
236	0	com.apple.storagekitd
209	0	com.apple.biomed
1073	0	com.apple.ospredictiond
-	0	com.apple.storereceiptinstaller
1072	0	com.apple.mobileactivationd
205	0	com.parallels.vm.prl_fsd
-	0	com.apple.seld
285	0	com.apple.PerfPowerTelemetryClientRegistrationService
-	0	com.apple.security.agent.login.00000000-0000-0000-0000-0000000186A2
476	0	com.apple.iconservices.iconservicesagent
-	0	com.apple.asr
-	0	com.apple.audiomxd
-	0	com.apple.logkextloadsd
113	0	com.apple.syslogd
311	0	com.apple.symptomsd-diag
282	-11	com.apple.WindowServer
-	0	com.apple.idleassetsd
-	0	com.apple.NetworkSharing
-	0	com.apple.afpfs_checkafp
1145	0	com.apple.systemstats.microstackshot_periodic
-	0	com.apple.AppSSOAgent.login
123	0	com.apple.securityd
-	0	com.apple.attentionawarenessd
126	0	com.apple.nesessionmanager
-	0	com.apple.cfnetwork.cfnetworkagent
-	0	com.apple.ocspd
173	0	com.apple.symptomsd
128	0	com.apple.autofsd
80	0	com.apple.UserEventAgent-System
-	0	com.apple.Kerberos.kadmind
-	0	com.apple.griddatad
354	0	com.apple.coresymbolicationd
-	0	com.apple.PerfPowerServicesExtended
290	0	com.apple.suhelperd
-	0	com.apple.RFBEventHelper
-	0	com.apple.racoon
-	0	com.apple.bosreporter
-	0	com.apple.MobileSoftwareUpdate.CryptegraftService
-	0	com.apple.metadata.mds.scan
145	0	com.apple.AirPlayXPCHelper
-	0	com.apple.trustd.agent
-	0	com.apple.quicklook
-	0	com.apple.appkit.xpc.ColorSampler
-	0	com.apple.screensharing.agent
-	0	com.apple.commerce
-	0	com.apple.familynotificationd
-	0	com.apple.TrustedPeersHelper
84	0	com.apple.mediaremoted
-	0	com.apple.mbusertrampoline
-	0	com.apple.RemoteDesktop.PrivilegeProxy
-	0	com.apple.diskimagesiod
-	0	com.apple.accessoryupdaterd
-	0	com.apple.sysdiagnose
638	0	com.apple.installd
-	0	com.apple.system_installd
-	0	com.apple.DASDelegateService
-	0	com.apple.AppStoreDaemon.StorePrivilegedODRService
-	0	com.apple.dvdplayback.setregion
-	0	com.apple.SafeEjectGPUStartupDaemon
169	0	com.apple.nehelper
-	0	com.apple.boswatcher
78	0	com.apple.logd
297	0	com.apple.loginwindow.19621813-77EE-4EFA-BA60-D7BF18F4CD88
265	0	com.apple.IOUserDockChannelSerial-0x10000031c
147	0	com.apple.tccd.system
-	0	com.apple.accessoryd
-	0	com.apple.appleseed.fbahelperd
1083	0	com.apple.memory-maintenance
-	0	com.apple.IFCStart
-	0	com.apple.applekeystored
108	0	com.apple.kernelmanagerd
-	0	com.apple.mdmclient.daemon
267	0	com.apple.icloud.searchpartyd
-	0	com.apple.retimerd
-	0	com.apple.Virtualization.AppleVirtualPlatformHIDBridge
277	0	com.apple.cameracaptured
-	0	com.apple.xpc.roleaccountd
216	0	com.apple.nsurlsessiond_privileged
-	0	com.apple.awdd
160	0	com.apple.contextstored
202	0	com.apple.mDNSResponderHelper.reloaded
253	0	com.apple.countryd
-	0	com.apple.dt.RemotePairingDataVaultHelper
-	78	com.apple.appleh13camerad
1068	0	com.apple.online-auth-agent.xpc
-	0	com.apple.nearbyd
-	0	com.apple.CSCSupportd
-	0	com.apple.cloudd
185	0	com.apple.secinitd
186	0	com.apple.fskit.fskit_helper
-	0	com.apple.kuncd
-	0	com.apple.corecaptured
-	0	com.apple.scsid
-	0	com.apple.IOAccelMemoryInfoCollector
-	0	com.apple.msrpc.lsarpc
-	0	com.apple.diskimagesiod.spb
-	0	com.apple.nand_task_scheduler
-	0	com.apple.filesystems.userfs_helper
138	0	com.apple.KernelEventAgent
153	0	com.apple.aslmanager
-	0	com.apple.taskgated-helper
269	0	com.apple.hidd
-	0	com.apple.RemotePairTool
146	0	com.apple.cmio.registerassistantservice
-	0	com.apple.accessibility.AXVisualSupportAgent
-	0	com.apple.coreservices.UASharedPasteboardProgressUI
343	0	com.apple.ctkd
-	0	com.apple.screensharing.menuextra
-	0	com.apple.universalaccesscontrol
-	0	com.apple.findmymacmessenger
-	0	com.apple.package-script-service
1107	0	com.apple.noticeboard.agent
-	0	com.apple.speech.speechsynthesisd.x86_64
-	0	com.apple.LocalAuthentication.UIAgent
-	0	com.apple.kernelmanager_helper
152	0	com.apple.runningboardd
-	0	com.apple.tzlinkd
-	0	com.apple.tmp_cleaner
570	0	com.apple.XprotectFramework.PluginService
-	0	com.apple.filesystems.fskitd
307	0	com.apple.security.agent.login.00000000-0000-0000-0000-0000000186AB
-	0	com.apple.XProtect.daemon.scan.startup
287	0	com.apple.coreservices.appleevents
87	0	com.apple.systemstats.analysis
-	78	com.apple.iomfb_fdr_loader
-	0	com.apple.diagnosticd
587	0	com.apple.AssetCacheTetheratorService
-	0	com.apple.mobilegestalt.xpc
92	0	com.apple.powerd
203	0	com.apple.authd
-	78	com.apple.iomfb_bics_daemon
161	0	com.apple.PowerUIAgent
-	0	com.apple.corekdld
-	0	com.apple.filesystems.doubleagentd
-	0	com.apple.oahd-root-helper
-	0	com.apple.DumpPanic
-	0	com.apple.vsdbutil
-	0	com.apple.mobile.NRDUpdated
-	0	com.apple.nfsd
168	0	com.apple.airportd
195	0	com.apple.audio.coreaudiod
-	0	com.apple.akd
-	0	com.apple.watchdogd
-	0	com.apple.pfd
107	0	com.apple.iconservices.iconservicesd
-	0	com.apple.testmanagerd.remote
284	0	com.apple.securityd.system
151	0	com.apple.containermanagerd.system
-	0	com.apple.InstallerProgress
-	0	com.apple.AXMediaUtilitiesService
-	0	com.apple.nlcd
-	0	com.apple.systemkeychain
-	0	com.apple.filesystems.userfsd
204	0	com.parallels.TimeSync
-	0	com.apple.appleh16camerad
561	-1	com.apple.netbiosd
-	0	com.apple.SCHelper
-	0	com.apple.softwareupdate_firstrun_tasks
-	0	com.apple.aonsensed
-	0	com.apple.preferences.timezone.admintool
-	0	com.apple.statd.notify
-	0	org.cups.cupsd
-	0	com.apple.appinstalld
1109	0	com.apple.noticeboard.state
155	0	com.apple.lsd
-	0	com.apple.threadradiod
358	0	com.apple.metadata.mds.index
121	0	com.apple.timed
122	0	com.apple.usbmuxd
1158	0	com.apple.CrashReporterSupportHelper
302	0	com.apple.MobileSoftwareUpdate.CleanupPreparePathService
-	0	com.apple.DumpGPURestart
129	0	com.apple.displaypolicyd
-	0	com.apple.powerlogHelperd
-	0	com.apple.wifip2pd
278	0	com.apple.timesync.audioclocksyncd
621	0	com.apple.PerfPowerServices
249	0	com.apple.alf
-	0	com.openssh.sshd
-	0	com.apple.dspluginhelperd
136	0	com.apple.logind
141	0	com.apple.bluetoothd
-	0	com.apple.msrpc.netlogon
-	0	com.apple.replayd
306	0	com.apple.ViewBridgeAuxiliary
-	0	com.apple.storeaccountd
299	0	com.apple.UserEventAgent-LoginWindow
-	0	com.apple.previewshellmacapp
-	0	com.apple.storeuid
305	0	com.apple.pluginkit.pkd
337	0	com.apple.CryptoTokenKit.ahp.agent
-	0	com.apple.security.XPCTimeStampingService
-	0	com.apple.coreservices.useractivityd
-	0	com.apple.diagnosticextensions.osx.spotlight.helper
330	0	com.apple.logd_helper
-	0	com.apple.TrustEvaluationAgent.system
-	0	com.apple.newsyslog
-	0	com.apple.MRTd
-	0	com.apple.taskgated
560	0	com.apple.GSSCred
342	0	com.apple.audio.systemsoundserverd
1085	0	com.apple.modelmanagerd
90	0	com.apple.configd
-	0	com.apple.captiveagent
294	0	com.apple.AccountPolicyHelper
-	0	com.apple.fontmover
-	0	com.apple.ManagedClient.mechanism
-	78	com.apple.oahd
-	0	com.apple.UserNotificationCenter
166	0	com.apple.trustdFileHelper
-	0	com.apple.aneuserd
-	0	com.apple.BlueTool
172	0	com.apple.icloud.findmydeviced
-	0	com.apple.MobileInstallationHelperService
-	1	com.apple.AppleQEMUGuestAgent
-	0	com.apple.security.authtrampoline
-	0	com.apple.DumpPanic.Accessory
-	0	com.apple.rpcbind
112	0	com.apple.coreduetd
-	0	com.apple.fairplayd
-	0	com.apple.DesktopServicesHelper
-	0	com.apple.ucupdate.plist
-	0	com.apple.sysdiagnose_helper
-	0	com.apple.diskimagesiod.ram
-	0	com.apple.ManagedClient.enroll
-	0	com.apple.recoveryos-lockout-service
1165	0	com.apple.timezoneupdates.tzd
573	0	com.apple.AssetCache.builtin
-	0	com.apple.powerdatad
-	0	com.apple.multiversed
-	0	com.apple.siri.acousticsignature
125	0	com.apple.locationd
-	0	com.apple.loginwindow.59BEBE6C-B7B5-41DF-9EFD-80627A4793AC
562	0	com.apple.rtcreportingd
-	0	com.apple.MobileAsset.ManifestStorageService
-	0	com.apple.Kerberos.kcm
1108	0	com.apple.coreservices.sharedfilelistd
-	0	com.apple.dt.fetchsymbolsd
-	0	com.apple.BluetoothUIService
-	0	com.apple.efilogin-helper
-	0	com.apple.loginwindow
-	0	com.apple.ReportMemoryException
245	0	com.apple.sysextd
-	0	com.apple.cmio.iOSScreenCaptureAssistant
-	0	com.apple.rapportd
142	0	com.apple.notifyd
-	0	com.apple.DistributionKit.DistributionHelper
-	0	com.apple.DictionaryServiceHelper
-	0	com.apple.DwellControl
-	0	com.apple.storedownloadd
-	0	com.apple.nowplayingtouchui
-	0	com.apple.AskPermissionUI
-	0	com.apple.SoftwareUpdateNotificationManager
-	0	com.apple.AppleVirtualPlatform.SystemService
-	0	com.apple.wifiFirmwareLoader
-	0	com.apple.ReportSystemMemory
83	0	com.apple.fseventsd
-	0	com.apple.devicemanagementclient.managedeventsd
-	0	com.apple.Kerberos.digest-service
-	0	com.apple.systempreferences.cacheAssistant
-	0	com.apple.automountd
-	0	com.apple.wifianalyticsd
-	0	com.vix.cron
-	1	com.apple.thermald
-	0	com.apple.FileCoordination
-	0	com.apple.eapolcfg_auth
201	0	com.apple.audio.AudioComponentRegistrar
-	0	com.apple.srp-mdns-proxy
-	0	com.apple.audioanalyticsd
571	0	com.apple.AssetCacheLocatorService
97	0	com.apple.remoted
-	0	com.apple.InstallerDiagnostics.installerdiagd
263	0	com.apple.softwareupdated
-	0	com.apple.systemadministration.writeconfig
-	0	com.apple.diskmanagementstartup
1151	0	com.apple.signpost.signpost_reporter
-	0	com.apple.postfix.master
-	0	com.apple.usbaudiod
-	0	com.apple.SubmitDiagInfo
-	0	com.apple.ContainerMigrationService
-	0	com.apple.AppSSODaemon
288	0	com.apple.bootinstalld
-	0	com.apple.mbsystemadministration
-	0	com.apple.msrpc.mdssvc
-	0	com.apple.corestorage.corestoragehelperd
-	0	com.apple.devicemanagementclient.teslad
281	0	com.apple.ReportCrash.Root
568	0	com.apple.trustd
-	0	com.apple.cmio.IIDCVideoAssistant
174	0	com.apple.security.syspolicy
-	0	com.apple.ioupsd
-	0	com.apple.biometrickitd
247	0	com.apple.usbd
-	0	com.apple.logd_reporter
132	0	com.apple.distnoted.xpc.daemon
171	0	com.apple.mDNSResponder.reloaded
-	0	com.apple.bridgeOSUpdateProxy
135	0	com.apple.bsd.dirhelper
137	0	com.apple.revisiond
139	0	com.apple.mobile.usermanagerd
-	0	com.apple.smb.preferences
312	0	com.apple.findmymacd
149	0	com.apple.cfprefsd.xpc.daemon
-	0	com.apple.xartstorageremoted
-	0	com.apple.unmountassistant.sysagent
-	0	com.apple.mobile.notification_proxy
-	0	com.apple.relatived
-	0	com.apple.preference.displays.MirrorDisplays
-	0	com.apple.previewshellapp
-	0	com.apple.KeyboardAccessAgent
-	0	com.apple.storelegacy
-	0	com.apple.OSDUIHelper
304	0	com.parallels.DynresHelper
298	0	com.apple.imklaunchagent
-	0	com.apple.btsa
-	0	com.apple.hiservices-xpcservice
-	0	com.apple.powerchime
-	0	com.apple.iCloudUserNotificationsd
-	0	com.apple.storeassetd
-	0	com.apple.familycircled
-	0	com.apple.RemoteDesktop.agent
-	0	com.apple.VoiceOver
-	0	com.apple.AssistiveControl
361	0	com.parallels.vm.prl_tg_virtio
-	0	com.apple.lskdd
-	0	com.apple.uninstalld
321	0	com.apple.colorsync.displayservices
79	0	com.apple.xpc.smd
-	0	com.apple.gkreport
91	0	com.apple.endpointsecurity.endpointsecurityd
324	0	com.apple.colorsyncd
223	0	com.apple.backupd
-	0	com.apple.eoshostd
-	0	com.apple.airport.wps
-	0	com.apple.dt.automationmode-writer
95	0	com.apple.MobileFileIntegrity
-	0	com.apple.netauth.sys.auth
-	0	com.apple.nfsconf
99	0	com.apple.mobile.keybagd
-	0	com.apple.configureLocalKDC
100	0	com.apple.mobile.softwareupdated
-	0	com.apple.spindump
-	0	com.apple.lockd
106	0	com.apple.metadata.mds
-	0	com.apple.cmio.VDCAssistant
-	0	com.apple.printtool.daemon
-	0	com.apple.pfctl
-	0	com.apple.security.authhost
-	0	com.apple.misagent
-	0	com.apple.security.agent.login
-	0	com.apple.ecosystemanalyticsd
-	0	com.apple.ionodecache
116	0	com.apple.thermalmonitord
-	0	com.apple.gssd
999	0	com.apple.remotemanagementd
333	0	com.apple.CryptoTokenKit.ahp
-	0	com.apple.afpfs_afpLoad
120	0	com.apple.coreservices.launchservicesd
-	0	com.apple.dynamic_pager
-	0	com.apple.usbsmartcardreaderd
-	0	com.apple.deviceinterfaced
-	0	com.apple.csrutil.report
-	0	com.apple.iokit.ioserviceauthorized
-	0	com.apple.Kerberos.kdc
-	0	com.apple.aned
133	0	com.apple.AppleCredentialManagerDaemon
-	0	com.apple.msrpc.srvsvc
-	0	com.apple.tracd
572	0	com.apple.osanalytics.osanalyticshelper
-	0	com.apple.mobile.storage_mounter
266	0	com.apple.driverkit.AppleUserHIDDrivers-0x10000031d
-	0	com.apple.familycontrols
-	0	com.apple.FollowUpUI
-	0	com.apple.uikitsystemapp
-	0	com.apple.controlstrip
-	0	com.apple.iCloudHelper
-	0	com.apple.testmanagerd
-	0	com.apple.dt.AutomationModeUI
-	0	com.apple.menuextra.battery.helper
-	0	com.apple.security.XPCKeychainSandboxCheck
-	0	com.apple.wifi.WiFiAgent
-	0	com.apple.CoreAuthentication.agent
-	0	com.apple.DictationIM
-	0	com.apple.installcoordination_proxy
-	0	com.apple.diagnosticextensions.osx.timemachine.helper
-	0	com.apple.kcproxy
1067	0	com.apple.XProtect.daemon.scan
-	0	com.apple.adid
569	0	com.apple.AmbientDisplayAgent
-	0	com.apple.wifivelocityd
-	0	com.apple.installandsetup.systemmigrationd
-	0	com.apple.BTServer.le
-	0	com.apple.metadata.mds.spindump
-	0	com.apple.Kerberos.kpasswdd
272	0	com.apple.WirelessRadioManager
167	0	com.apple.mobileassetd
1078	0	com.apple.nand.aspcarry
-	0	com.apple.InstallerDiagnostics.installerdiagwatcher
-	0	com.apple.UpdateSettings
-	0	com.apple.msrpc.wkssvc
-	0	com.apple.erasecontentsettingshelperd
-	0	com.apple.mobile.storage_mounter_proxy
1077	0	com.apple.liquiddetectiond
1069	0	com.apple.nfcd
105	0	com.apple.warmd
-	0	com.apple.powerd.swd
-	0	com.apple.ManagedClient
-	0	com.apple.xpc.uscwoap
109	0	com.apple.diskarbitrationd
279	0	com.apple.cmio.uvcassistantextension
1144	0	com.apple.dprivacyd
347	0	com.apple.backupd-helper
-	0	com.apple.installcoordinationd
-	0	com.apple.netauth.sys.gui
-	0	com.apple.postfix.newaliases
268	0	com.apple.eligibilityd
-	0	com.apple.fairplaydeviceidentityd
-	0	com.apple.systemstats.daily
626	0	com.openssh.sshd.B113B31E-0350-4630-816A-95B0FA686CE9
-	0	com.apple.startupdiskhelper
280	0	com.apple.findmy.findmybeaconingd
217	0	com.apple.ifdreader
117	0	com.apple.opendirectoryd
-	0	com.apple.appstored
-	0	com.apple.DataDetectorsSourceAccess
119	0	com.apple.apsd
-	0	com.apple.internal.aupbregistrarservice
-	0	com.apple.ManagedClient.cloudconfigurationd
206	0	com.parallels.vm.prltoolsd
-	0	com.apple.GameController.gamecontrollerd
-	0	com.apple.wallpaper.export
-	0	com.apple.AppStoreDaemon.StorePrivilegedTaskService
-	0	com.apple.powerexperienced
218	0	com.apple.apfsd
178	0	com.apple.backgroundtaskmanagementd
130	0	com.apple.dasd
-	0	com.apple.sessionlogoutd
-	0	com.apple.triald.system
-	0	com.apple.AssetCacheManagerService
246	0	com.apple.systemstatusd
-	0	com.apple.handwritingd
-	0	com.apple.cmio.AVCAssistant
182	0	com.apple.analyticsd
259	0	com.apple.CodeSigningHelper
143	0	com.apple.sandboxd
583	0	com.apple.sysmond
144	0	com.apple.corebrightnessd
-	0	com.apple.tailspind
-	0	com.apple.accessibility.mediaaccessibilityd
-	0	com.apple.scrod
-	0	com.apple.SpeechRecognitionCore.brokerd
-	0	com.apple.iokit.IOServiceAuthorizeAgent
300	0	com.apple.universalaccessd
-	0	com.apple.carboncore.csnameddata
-	0	com.apple.UserNotificationCenterAgent-LoginWindow
-	0	com.apple.ScreenReaderUIServer
-	0	com.apple.speech.speechsynthesisd.arm64
-	0	com.apple.netauth.user.gui
-	0	com.apple.SetStoreUpdateService
-	0	com.apple.geod
sh-3.2# launchctl list | grep agent
-	0	com.apple.security.agent.login.00000000-0000-0000-0000-0000000186A2
476	0	com.apple.iconservices.iconservicesagent
-	0	com.apple.cfnetwork.cfnetworkagent
-	0	com.apple.trustd.agent
-	0	com.apple.screensharing.agent
1068	0	com.apple.online-auth-agent.xpc
1107	0	com.apple.noticeboard.agent
307	0	com.apple.security.agent.login.00000000-0000-0000-0000-0000000186AB
-	0	com.apple.filesystems.doubleagentd
337	0	com.apple.CryptoTokenKit.ahp.agent
-	0	com.apple.captiveagent
-	0	com.apple.unmountassistant.sysagent
298	0	com.apple.imklaunchagent
-	0	com.apple.RemoteDesktop.agent
-	0	com.apple.misagent
-	0	com.apple.security.agent.login
-	0	com.apple.CoreAuthentication.agent


```
</details>

I will change the Service testing by using wazuh-control as it was suggested by @vikman90

**Comment by pro-akim** [comment]
## Add the OS and its supported architectures to the E2E UX Tests spreadsheet (OS sheet).
![image](https://github.com/user-attachments/assets/08fc5cb1-4236-4f33-8706-4a9d28b29c76)

**Comment by rauldpm** [comment]
Blocking this issue temporarily as we need confirmation that the Wazuh agent should not appear in the `launchctl list` output

**Comment by pro-akim** [comment]
Testing the `launchctl` list output in other macOs before reporting it officially.

**Comment by pro-akim** [comment]
## Testing


### Sonoma AMD64

```
sh-3.2# uname -a
Darwin macos-14 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:11:05 PDT 2024; root:xnu-10063.101.17~1/RELEASE_X86_64 x86_64
sh-3.2# /Library/Ossec/bin/wazuh-control status
wazuh-modulesd is running...
wazuh-logcollector is running...
wazuh-syscheckd is running...
wazuh-agentd is running...
wazuh-execd is running...
sh-3.2# launchctl list | grep agent
284	0	com.apple.security.agent.login.00000000-0000-0000-0000-0000000186A2
364	0	com.apple.iconservices.iconservicesagent
-	0	com.apple.cfnetwork.cfnetworkagent
-	0	com.apple.trustd.agent
-	0	com.apple.screensharing.agent
4527	0	com.apple.online-auth-agent.xpc
-	0	com.apple.noticeboard.agent
310	0	com.apple.CryptoTokenKit.ahp.agent
-	0	com.apple.captiveagent
-	0	com.apple.unmountassistant.sysagent
195	0	com.apple.imklaunchagent
-	0	com.apple.RemoteDesktop.agent
-	0	com.apple.misagent
-	0	com.apple.security.agent.login
-	0	com.apple.CoreAuthentication.agent
```


### Ventura AMD64

```
sh-3.2# uname -a
Darwin macos-13 22.6.0 Darwin Kernel Version 22.6.0: Mon Feb 19 19:48:53 PST 2024; root:xnu-8796.141.3.704.6~1/RELEASE_X86_64 x86_64
sh-3.2# /Library/Ossec/bin/wazuh-control status
wazuh-modulesd is running...
wazuh-logcollector is running...
wazuh-syscheckd is running...
wazuh-agentd is running...
wazuh-execd is running...
sh-3.2# launchctl list | grep agent
337	0	com.apple.iconservices.iconservicesagent
-	0	com.apple.cfnetwork.cfnetworkagent
-	0	com.apple.trustd.agent
-	0	com.apple.screensharing.agent
-	0	com.apple.noticeboard.agent
283	0	com.apple.security.agent.login.00000000-0000-0000-0000-0000000186A4
324	0	com.apple.CryptoTokenKit.ahp.agent
-	0	com.apple.captiveagent
-	0	com.apple.unmountassistant.sysagent
176	0	com.apple.imklaunchagent
-	0	com.apple.RemoteDesktop.agent
-	0	com.apple.misagent
-	0	com.apple.security.agent.login
-	0	com.apple.CoreAuthentication.agent
```

Checking the presence of Wazuh-Agent activity using Launchtcl, its presence could not be observed in other versions of macOS. @rauldpm  will be consulted for its definition.

**Comment by rauldpm** [comment]
Still waiting for confirmation as the `launchtcl` command is used in:

https://github.com/wazuh/wazuh/blob/dceb92714fc777f9041d33af96720230b7274253/src/init/darwin-init.sh#L15
https://github.com/wazuh/wazuh/blob/dceb92714fc777f9041d33af96720230b7274253/.github/actions/test_deploy_macos.sh#L36

**Comment by pro-akim** [comment]
## Update
Moved to 4.10.0

**Comment by pro-akim** [comment]
## Update
Moved to 4.10.0

**Comment by rauldpm** [comment]
Based on https://github.com/wazuh/wazuh/issues/21636, we will not use `launchctl`

**Comment by pro-akim** [comment]
Pull requests heading to 4.9.1 were restablished.
