### ISSUE TITLE
Support new stage Alpha 1 for 4.9.0 in wazuh repository

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#24183]
## Description

This issue attempts to support a new stage Alpha 1 for 4.9.0 in the wazuh repository.

## Tasks

- [ ] Ensure changelog is updated for 4.9.0 (if applicable).
- [ ] Bump revision for branch 4.9.0 on wazuh repository.
- [ ] Create tag v4.9.0-alpha1 from branch 4.9.0 on wazuh repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh/releases/tag/v4.9.0-alpha1.
