### ISSUE TITLE
Develop Comms API

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#24305]
|Objective|
|---|
| #22677 |

# Description
This issue is intended to implement the **Comms API** proposed and initially developed as part of https://github.com/wazuh/wazuh/issues/23395 and https://github.com/wazuh/wazuh/issues/23396. This API server will replace the old `remoted` service, receiving events from the agents and sending those events to the [Engine](https://github.com/wazuh/wazuh/issues/11334) and the wazuh indexer.  

## Layout
Initially we will go ahead with the proposal made [here](https://github.com/wazuh/wazuh/issues/23395#issuecomment-2176438280):
<details>
<summary>Layout</summary>

```
├── apis
│   ├── server_management_api
│   │   ├── ...
│   │   ├── setup.py
│   │   └── tests
|   ├── comms_api
|   │   ├── __init__.py
│   │   ├── setup.py
|   │   ├── api.py
|   │   ├── configuration
|   │   │   └── ...
|   │   ├── dependencies
|   |   │   ├── __init__.py
|   |   │   ├── auth.py 
|   |   │   ├── indexer.py  
|   |   │   └── ...
|   │   ├── middlewares
|   |   │   ├── __init__.py
|   |   │   └── ...
|   │   ├── models
|   |   │   ├── __init__.py
|   |   │   ├── command.py
|   |   │   ├── event.py
|   |   │   ├── stateless_event.py
|   |   │   └── ...
|   │   ├── routers
|   |   │   ├── __init__.py
|   |   │   ├── commands.py
|   |   │   ├── events.py
|   |   │   ├── management.py
|   |   │   └── login.py
|   │   └── tests
│   ├── test
│   ├── Makefile
│   ├── scripts
│   └── wrappers
└── framework
    ├── examples
    ├── __init__.py
    ├── Makefile
    ├── pytest.ini
    ├── requirements-dev.txt
    ├── requirements.txt
    ├── scripts
    ├── setup.py
    ├── wazuh
    └── wrappers
```

</details>

Both Python APIs will be located under `apis` folder. There will be no versioning at a directory level. 

# Requirements
## Functional requirements
1. The API must use HTTPS for communication. 
2. The API will respond to stateless requests as soon as the events are sent to the engine.
3. The API will respond to stateful requests after indexing the data in wazuh indexer.
4. The API will direct each stateful request to a batching service that will send the events to the indexer every certain time interval or determined batch size.
5. The API must support long polling requests initiated by clients to send commands when necessary.
6. The API must be able to scale horizontally within each server by increasing the number of Uvicorn workers/processes.
7. The API must use standard [HTTP response status codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes).
8. The API must support JSON with the [brotli](https://www.ietf.org/rfc/rfc7932.txt) compression algorithm for data transmission.

## Non-functional requirements

1. The new API process and subprocesses will be named with the same format as the current `wazuh-apid` process. The proposed name is `wazuh-comms-apid`.
2. The new API process and subprocesses should be located in the `/var/ossec/var/run`.
3. The new API process and subprocesses should be able to be managed with the `wazuh-control` script.

## Implementation restrictions
1. The framework will be FastAPI, using Uvicorn as the engine.
5. Gunicorn must be used to handle Uvicorn worker processes.
6. The response format must be consistent along all Comms API endpoints both for error and success cases. The proposal made [here](https://github.com/wazuh/wazuh/issues/23395#issuecomment-2178737901) must be followed.
7. The Python server-engine communication component must be located in the framework folder since it will be used for both Comms API and Server management API. Unix sockets must be used to communicate with the Engine. 
9. The [opensearch-py](https://pypi.org/project/opensearch-py/) must be used for API-Indexer communication.
10. The Python server-indexer communication component must be located in the framework folder since it will be used for both Comms API and Server management API.
11. The Comms API must start with the rest of the wazuh server services. 
12. Stateful events must be batched to reduce the number of requests to the indexer. 
   1. Batching must be common to all Comms API workers/processes within a server.
   2. Event batching should accumulate up to a specific size or duration, both of which should be configurable.
   3. Batching will be grouped by module/origin of events.
   4. While a batch of events is being sent, there should be other batches under construction.
13. Endpoint timeouts will be parametrizable and specific.

# Plan
- [x] https://github.com/wazuh/wazuh/issues/24616
- [x] https://github.com/wazuh/wazuh/issues/24617
- [x] Endpoints:
  - [x] https://github.com/wazuh/wazuh/issues/24618
  - [x] https://github.com/wazuh/wazuh/issues/24619
  - [x] https://github.com/wazuh/wazuh/issues/24647
  - [x] https://github.com/wazuh/wazuh/issues/24691
  - [x] https://github.com/wazuh/wazuh/issues/24692
  - [x] https://github.com/wazuh/wazuh/issues/24693
- [ ] ~Remoted replacement with the server daemon~ (To be done in the feature complete implementation)

**Comment by GGP1** [comment]
## Update 

Created multiple issues for tasks that will be part of this API's development and modified the implementation restrictions to include endpoint-specific timeouts

**Comment by GGP1** [comment]
## Update

Created two more issues: #24646 and #24647. I'm leaving this one on hold to focus on the 4.9.0 alpha 2 release testing.

**Comment by GGP1** [comment]
## Update

Created the issues #24691, #24692, #24693 and #24695.

**Comment by GGP1** [comment]
## Update

The only task remaining is `Remoted replacement with the server daemon`, but doing this is not possible yet because there's still many things to define regarding the cluster initialization and configuration. The task will be left for the feature complete implementation.

With that said, this issue is ready to be reviewed.
