### ISSUE TITLE
Engine - Migration of Agent and Manager Event Processing from wazuh-analysisd to wazuh-engine

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#24312]
| Wazuh version |  Integration name  | Integration type | Integration version |
|---------------|--------------------|------------------|---------------------|
|   5.0.0   | <integration_name> | new       | 1.0.0         |

## Overview

This issue aims to enhance the processing capabilities of Wazuh-Engine by migrating the handling of specific agent and manager events from wazuh-analysisd to wazuh-engine. The focus will be on adding new decoders that are compliant with the Elastic Common Schema (ECS) to process events currently managed under rules 501 to 506.

### Objective

- **ECS Compliant Decoders**: Develop decoders within Wazuh-Engine that normalize and process agent and manager events in accordance with the ECS standards.

### Requirements

- **ECS Compliance**: Ensure all new decoders adhere to the ECS.
- **Event Coverage**: Cover the following events with new decoders:
  - Agent started
  - Agent disconnected
  - Agent removed
  - Agent stopped
  - Manager started

### Tasks

- [ ] Review the current implementation of rules 501 to 506 in the [Wazuh ruleset](https://github.com/wazuh/wazuh/blob/a5f51ad61af5abcf49186cd72d4d73c0c3927021/ruleset/rules/0015-ossec_rules.xml#L16-L67) to understand the logic and fields involved in event processing.
- [ ] Design and document the schema for the new ECS-compliant decoders, detailing how each event type will be normalized and processed.
- [ ] Develop the new decoders in wazuh-engine, ensuring they capture and normalize all relevant data from the events.
- [ ] Conduct a phased rollout of the new decoders, initially in a test environment

## Checklist before reviewing an integration

- [ ] Create a new integration under `engine/ruleset/integrations`

- [ ] Add and test the agent configuration inside the `<integration_name>/agent/ossec.conf`.
- Events
    - [ ] Identify all events this integration must process.
    - [ ] Create `engine-test` configuration to test the events.
    - [ ] All test events are obfuscated. (i.e. IP, dates)
- Develop neccesary decoders, for each decoder ensure:
    - [ ] Regex was used only when strictly necessary.
    - [ ] The decoder does not depend on the evaluation of sibling decoders (It does not have to be run with another decoder in a specific order since the check stage is exhaustive).
    - [ ] All fields mapped are documented in the integration's sheet.
    
    - [ ] Is in the `wazuh` namespace.
    - Added test for all events:
        - [ ] `input` added
        - [ ] `expected` added
        - [ ] `engine-test.conf` added
- Testing
    - [ ] `./test/health_test/run.py` runs without errors.
    - [ ] The events in the dashbord are displayed correctly.
    - [ ] There are no warnings or errors on Filebeta logs when indexing events.
        
- Documentation
    - [ ] Title, Overview, Compatibility, Configuration, event module/dataset added in `documentation.yml`
    - [ ] Add entry to the `changelog.yml`
    - [ ] The `engine-integration generate-doc` tool generated the `readme.MD` correctly
