### ISSUE TITLE
A flag wazuh_command.remote_commands in local_internal_options.conf is ignored

### ISSUE THREAD

**Issue by lchico** [wazuh/wazuh#24330]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|4.8.0-1 | Wodle | Agent| Packages | Windows 11 24H2 | 

While testing [Windows 11 24H2](https://github.com/wazuh/wazuh/issues/23861), I noticed that the `wazuh_command.remote_commands` flag was being ignored. Upon reviewing my configurations in `local_internal_options.conf`, I found that the `wazuh_command.remote_commands=0` flag was set, and `internal_options.conf` is empty. However, a remote command had still been executed.

Upon further investigation, I discovered that `local_internal_options.conf` is partially deprecated as mentioned in [issue 3150](https://github.com/wazuh/wazuh/issues/3150), and should be replaced with something like the following [XML snippet:](https://github.com/wazuh/wazuh/issues/3150#:~:text=%3Cwodle%20name%3D%E2%80%9Dcommand%E2%80%9D%3E%0A%20%20%20%20%3Cremote_commands%3E0%3C/remote_commands%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%23%23%23%20%2D%2D%2D%20wazuh_command.remote_commands%0A%20%20%3C/wodle%3E):

```xml
  <wodle name=”command”>
    <remote_commands>0</remote_commands>                ### --- wazuh_command.remote_commands
  </wodle>
```
However, testing this configuration did not resolve the issue:

```log
2024/06/26 10:34:12 wazuh-agent: ERROR: No such tag 'remote_commands' at module 'command'.
2024/06/26 10:34:12 wazuh-agent: ERROR: (1202): Configuration error at 'ossec.conf'.
```
Finally, I came across [issue 3248](https://github.com/wazuh/wazuh-documentation/pull/3248/files) from the API, which might explain this behavior. It appears that remote commands using Wodle are enabled by default, contrary to the documentation stating they are disabled for security reasons [documentation reference](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-command.html#:~:text=Remote%20commands%20may%20be%20specified%20in%20the%20centralized%20configuration%2C%20however%2C%20they%20are%20disabled%20by%20default%20due%20to%20security%20reasons.).

# Task

- [ ]  Verify if this issue occurs on other operating systems.
- [ ]  Confirm if remote_commands has been deprecated from internal_options.
- [ ]  Update the documentation accordingly.

**Comment by vikman90** [comment]
@lchico As I see, this module works correctly on Windows.

If I configure a command remotely _(/var/ossec/etc/shared/default/agent.conf_):

The Windows agent fails because it has remote commands disabled:

> 2024/06/28 11:53:33 wazuh-modulesd:command: WARNING: Remote commands are disabled. Ignoring 'test'.

However, if I change the settings in the agent (_local_internal_options.conf_):

```python
wazuh_command.remote_commands=0
```

Then the agent does execute the command:

> 2024/06/28 11:54:30 wazuh-modulesd:command: INFO: Starting command 'test'.

The internal options system is broken in the sense that we don't add new options, but it still works. Any changes to this setting could come from 5.0.

Let me close this issue.
Thanks and regards.

**Comment by lchico** [comment]
@vikman90  thanks. Yes, I messed up that. Tested and works as expected.

```
ossec.log:236182:2024/06/28 14:51:42 wazuh-modulesd:command: WARNING: Remote commands are disabled. Ignoring 'test'.
```
