### ISSUE TITLE
Extend WPK upgrade support to Windows XP

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#2437]
|Type|Platform|Development branch|
|---|---|---|
|Agent|Windows XP|[3.9-wpk-win-xp](https://github.com/wazuh/wazuh/compare/3.9...3.9-wpk-win-xp)|

Currently, WPK upgrades are not supported on Windows XP because they require Windows Powershell to run the upgrade script (_do_upgrade.ps1_). `agent_upgrade` rejects to upgrade an agent if it's running on a Windows version under Vista.

We require supporting remote upgrades on Windows XP so we're translating the Powershell script into a legacy MS-DOS batch script.

## Subtasks

- [X] Implement agent upgrade batch script. 2208625
- [X] Make the upgrade launcher (_upgrade.bat_) run this script if Powershell is not installed.
- [x] Update the agent platform version constraint at the Framework. f8f8645
- [X] Let the update procedure rollback Registry key on failure. 987301b

## Test matrix

||Windows XP SP2|Windows XP SP3|Windows Server 2003|Windows 7|Windows Server 2019|
|---|---|---|---|---|---|
|Successful upgrade from v3.7.2|OK|Upgrade OK, incorrect logs.||||
|Successful upgrade from v3.6.0|OK|Upgrade OK, incorrect logs.||||
|Successful upgrade from v3.5.0||||||
|Upgrade failure/rollback from v3.7.2|OK|Rollback OK, incorrect logs.||||
|Upgrade failure/rollback from v3.6.0|OK|Rollback OK, incorrect logs.||||
|Upgrade failure/rollback from v3.5.0||||||

**Comment by vikman90** [comment]
## Problems detected and fixed

### Log output redirection issue

After the first log line (_upgrade\upgrade.log_), the output from the callee commands are dumped into the log and we can't see the `echo`s to that file. 

This error happened after the `echo` that follows this instruction:

```shell
SET /P curversion=<VERSION
```

*Fix:* Replace that sentence with a `FOR` loop that achieves the same effect. (ac73563)

### Find utility crash

Calling `FIND` with an input file instead of _stdin_:
```
FIND "status='connected'" ossec-agent.state
```
It produced a crash in `FIND`:
> Find String (grep) utility has encountered a problem and needs to close.

*Fix:* Use _stdin_ as program call input. (c2f25d2)
