### ISSUE TITLE
Scheduled upward merges for numbered branches - Fortnight #11

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh#24416]
# Description

The goal of this is to track the completion of the following tasks so the development branches are up to date in every repository, ensuring a clean environment for our development teams.

# Tasks

### wazuh-qa -> @wazuh/qa
- https://github.com/wazuh/wazuh-qa/issues/5549
### wazuh-jenkins -> @wazuh/qa
- https://github.com/wazuh/wazuh-jenkins/issues/6708
### wazuh-automation -> @wazuh/devops
- https://github.com/wazuh/wazuh-automation/issues/1727
### wazuh-packages -> @wazuh/agent
- https://github.com/wazuh/wazuh-packages/issues/3027
### wazuh -> @wazuh/cppserver
- https://github.com/wazuh/wazuh/issues/24415
### wazuh-ansible -> @wazuh/devops
- https://github.com/wazuh/wazuh-ansible/issues/1333
### wazuh-docker -> @wazuh/devops
- https://github.com/wazuh/wazuh-docker/issues/1418
### wazuh-puppet -> @wazuh/devops
- https://github.com/wazuh/wazuh-puppet/issues/1050
### wazuh-kubernetes -> @wazuh/devops
- https://github.com/wazuh/wazuh-kubernetes/issues/740
### wazuh-dashboard-plugins -> @wazuh/dashboard
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6812
### wazuh-documentation -> @wazuh/qa
- https://github.com/wazuh/wazuh-documentation/issues/7503
### qa-integration-framework -> @wazuh/pyserver
- https://github.com/wazuh/qa-integration-framework/issues/198
### wazuh-security-dashboards-plugin -> @wazuh/dashboard
- https://github.com/wazuh/wazuh-security-dashboards-plugin/issues/61
### wazuh-indexer -> @wazuh/indexer
- https://github.com/wazuh/wazuh-indexer/issues/295
### wazuh-dashboard -> @wazuh/devel-dashboard 
- https://github.com/wazuh/wazuh-dashboard/issues/230

## 2. Upload installation assistant in packages-dev -> @wazuh/qa

- [x] Upload installation assistant in packages-dev using `Publish_unattended` pipeline. **BE CAREFUL NOT TO UPLOAD IT TO PRODUCTION**  https://ci.wazuh.info/job/publish_unattended/296/console

## 3. Create AWS resources  -> @wazuh/qa

- [x] Regenerate AWS resources using the Procedure_ecs_task_tier pipeline on branches that have been modified/bumped.
  - [x] 4.9.0: https://ci.wazuh.info/job/Procedure_ecs_task_tier/163/
    - https://github.com/wazuh/wazuh-jenkins/issues/3961

**Comment by pro-akim** [comment]
## Review Notes
LGTM
