### ISSUE TITLE
Support new OSs - CentOS Stream 10 - Add support in QA procedures

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#24491]
# Description
| Related issue | Epic issue |
|---|---|
| https://github.com/wazuh/wazuh/issues/24128 | https://github.com/wazuh/wazuh/issues/24490 |

| Agent tier | Central components support | OS type |
|-|-|-|
| 1 | No | Major |

# Plan

**QA**
## Considerations

- Testing environment: Deploy the new OS taking into account the following notes:
  - If the Wazuh central components are supported: 1 VM
  - If the Wazuh agent is supported: 1 VM for each architecture supported.
  - If the Wazuh central components or the Wazuh agent is not supported, deploy a Debian 12 VM for the non-supported component.
- All testing tasks must be completed for each OS architecture supported.
- The following tasks should be completed in order.

## Tasks

- [ ] Test the Wazuh dashboard one-liner deployment.
  - [ ] Deploy a Wazuh agent using the Wazuh dashboard one-liner feature provided in the Wazuh user interface with the following cases.
    - [ ] Only IP address.
    - [ ] Only FQDN.
    - [ ] IP address, agent name, and group.
- [ ] Add/Update/Check CI 
  - [ ] Test the JobFlow testing tool for that specific system.
  - [ ] Add the OS and each architecture to the JobFlow testing tool.
  - [ ] Add the OS and each architecture to the GitHub Deployability and Upgrade release templates.
- [ ] Add the OS and its supported architectures to the E2E UX Tests spreadsheet (OS sheet).
- [ ] Add the OS as supported in the compatibility system spreadsheet.
- [ ] We need to add proper documentation, including adding the new OS version if it belongs to an OS family already added to these tables: 
  - [ ]  https://documentation.wazuh.com/current/quickstart.html#operating-system
  - [ ]  https://documentation.wazuh.com/current/installation-guide/wazuh-server/index.html#recommended-operating-systems
  - [ ]  https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/index.html#recommended-operating-systems
  - [ ]  https://documentation.wazuh.com/current/installation-guide/wazuh-dashboard/index.html#recommended-operating-systems

**Comment by pro-akim** [comment]
## To do list:

- [ ] Check DTT functionality with the new system
- [ ] Update the E2E UX Tests spreadsheet to include the new system
- [ ] Include new system in CI overhaul systems (Packages/Update)
- [ ] Add system to the Wazuh documentation supported systems (5.0)

**Comment by pro-akim** [comment]
## DTT

I opened this issue requesting presence of CentOS 10 in the allocator module:

https://github.com/wazuh/wazuh-jenkins/issues/6926

**Comment by pro-akim** [comment]
On hold due to: https://github.com/wazuh/wazuh-qa/issues/5721

**Comment by pro-akim** [comment]
## CI overhaul systems
In order to support CentOS 10 in Upgrade test, CentOS 10 should be available in DockerHub, however, centOS 10 is not available in the official DockerHun repository.
Support of CentOS in Upgrade tests will remain unsupported until further notice

**Comment by pro-akim** [comment]
Moved to on hold due to https://github.com/wazuh/wazuh-jenkins/issues/6921

**Comment by MarcelKemp** [comment]
I am temporarily closing the issue until an official release date appears.

**Comment by mjcr99** [comment]
Official Release available, reopening the issue.

**Comment by antoniorr02** [comment]
## Update report CentOS Stream 10 amd
- DTT execution finished successfully 🟢
    - YAML: 
    - LOG: 

## Test the Wazuh dashboard one-liner deployment. 🟢
<details><summary>Only IP address.</summary>
</details>

<details><summary>Only FQDN.</summary>
</details>

<details><summary>IP address, agent name, and group.</summary>
</details>

**Comment by antoniorr02** [comment]
# Update report CentOS Stream 10 aarch64
## Test the Wazuh dashboard one-liner deployment. 🟢
```
[ec2-user@ip-172-31-27-5 ~]$ cat /etc/os-release 
NAME="CentOS Stream"
VERSION="10 (Coughlan)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="10"
PLATFORM_ID="platform:el10"
PRETTY_NAME="CentOS Stream 10 (Coughlan)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:10"
HOME_URL="https://centos.org/"
VENDOR_NAME="CentOS"
VENDOR_URL="https://centos.org/"
BUG_REPORT_URL="https://issues.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 10"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"

[ec2-user@ip-172-31-27-5 ~]$ uname -m
aarch64
```
<details><summary>Only IP address.</summary>
</details>

<details><summary>Only FQDN.</summary>
</details>

<details><summary>IP address, agent name, and group.</summary>
</details>

**Comment by antoniorr02** [comment]
I have opened [this issue](https://github.com/wazuh/wazuh-documentation/issues/8438) in the Wazuh documentation repository to request adding CentOS 10 to the list of supported operating system

**Comment by rauldpm** [comment]
Lets test the DTT tool using the 4.11.2 branch, modify the agent JobFlow template to use only the new targets and use the 4.13.0 branch for the Allocator module

Also check the PR review: https://github.com/wazuh/wazuh-qa-automation/pull/1608#pullrequestreview-2786947163

The CC components were installed in a CentOS Stream 10 instance instead of a Debian 12, as the CC are not supported officially in that system, we need to test it in the specified Debian system

**Comment by antoniorr02** [comment]
I have opened [this issue](https://github.com/wazuh/internal-devel-requests/issues/2336) to request a debian 12 vm to continue with the testing.

**Comment by antoniorr02** [comment]
I have installed wazuh cc in debian 12 and I have updated the testing in this enviroment with the centOS 10 agents in the previous comments.

```
admin@ip-172-31-34-232:~$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
admin@ip-172-31-34-232:~$ sudo systemctl status wazuh-manager.service 
● wazuh-manager.service - Wazuh manager
     Loaded: loaded (/lib/systemd/system/wazuh-manager.service; enabled; preset: enabled)
     Active: active (running) since Thu 2025-04-24 09:50:07 UTC; 17min ago
      Tasks: 174 (limit: 9395)
     Memory: 2.9G
        CPU: 52.735s
     CGroup: /system.slice/wazuh-manager.service
             ├─57600 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh_apid.py
             ├─57601 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh_apid.py
             ├─57602 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh_apid.py
             ├─57605 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh_apid.py
             ├─57608 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh_apid.py
             ├─57649 /var/ossec/bin/wazuh-authd
             ├─57662 /var/ossec/bin/wazuh-db
             ├─57687 /var/ossec/bin/wazuh-execd
             ├─57698 /var/ossec/bin/wazuh-analysisd
             ├─57707 /var/ossec/bin/wazuh-syscheckd
             ├─57774 /var/ossec/bin/wazuh-remoted
             ├─57812 /var/ossec/bin/wazuh-logcollector
             ├─57828 /var/ossec/bin/wazuh-monitord
             └─57874 /var/ossec/bin/wazuh-modulesd

Apr 24 09:50:01 ip-172-31-34-232 env[57538]: Started wazuh-analysisd...
Apr 24 09:50:02 ip-172-31-34-232 env[57538]: Started wazuh-syscheckd...
Apr 24 09:50:03 ip-172-31-34-232 env[57538]: Started wazuh-remoted...
Apr 24 09:50:03 ip-172-31-34-232 env[57538]: Started wazuh-logcollector...
Apr 24 09:50:04 ip-172-31-34-232 env[57538]: Started wazuh-monitord...
Apr 24 09:50:04 ip-172-31-34-232 env[57872]: 2025/04/24 09:50:04 wazuh-modulesd:router: INFO: Loaded router module.
Apr 24 09:50:04 ip-172-31-34-232 env[57872]: 2025/04/24 09:50:04 wazuh-modulesd:content_manager: INFO: Loaded content_manager module.
Apr 24 09:50:05 ip-172-31-34-232 env[57538]: Started wazuh-modulesd...
Apr 24 09:50:07 ip-172-31-34-232 env[57538]: Completed.
Apr 24 09:50:07 ip-172-31-34-232 systemd[1]: Started wazuh-manager.service - Wazuh manager.
admin@ip-172-31-34-232:~$ sudo systemctl status wazuh-indexer
● wazuh-indexer.service - wazuh-indexer
     Loaded: loaded (/lib/systemd/system/wazuh-indexer.service; enabled; preset: enabled)
     Active: active (running) since Thu 2025-04-24 09:45:42 UTC; 21min ago
       Docs: https://documentation.wazuh.com
   Main PID: 5897 (java)
      Tasks: 86 (limit: 9395)
     Memory: 1.4G
        CPU: 1min 1.533s
     CGroup: /system.slice/wazuh-indexer.service
             └─5897 /usr/share/wazuh-indexer/jdk/bin/java -Xshare:auto -Dopensearch.networkaddress.cache.ttl=60 -Dopensearch.networkaddress.cache.negative>

Apr 24 09:45:32 ip-172-31-34-232 systemd-entrypoint[5897]: WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.OpenSearch (fil>
Apr 24 09:45:32 ip-172-31-34-232 systemd-entrypoint[5897]: WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.OpenSear>
Apr 24 09:45:32 ip-172-31-34-232 systemd-entrypoint[5897]: WARNING: System::setSecurityManager will be removed in a future release
Apr 24 09:45:32 ip-172-31-34-232 systemd-entrypoint[5897]: Apr 24, 2025 9:45:32 AM sun.util.locale.provider.LocaleProviderAdapter <clinit>
Apr 24 09:45:32 ip-172-31-34-232 systemd-entrypoint[5897]: WARNING: COMPAT locale provider will be removed in a future release
Apr 24 09:45:33 ip-172-31-34-232 systemd-entrypoint[5897]: WARNING: A terminally deprecated method in java.lang.System has been called
Apr 24 09:45:33 ip-172-31-34-232 systemd-entrypoint[5897]: WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.Security (file:>
Apr 24 09:45:33 ip-172-31-34-232 systemd-entrypoint[5897]: WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.Security
Apr 24 09:45:33 ip-172-31-34-232 systemd-entrypoint[5897]: WARNING: System::setSecurityManager will be removed in a future release
Apr 24 09:45:42 ip-172-31-34-232 systemd[1]: Started wazuh-indexer.service - wazuh-indexer.
admin@ip-172-31-34-232:~$ sudo systemctl status wazuh-dashboard.service 
● wazuh-dashboard.service - wazuh-dashboard
     Loaded: loaded (/etc/systemd/system/wazuh-dashboard.service; enabled; preset: enabled)
     Active: active (running) since Thu 2025-04-24 09:50:09 UTC; 17min ago
   Main PID: 58849 (node)
      Tasks: 11 (limit: 9395)
     Memory: 204.2M
        CPU: 10.881s
     CGroup: /system.slice/wazuh-dashboard.service
             └─58849 /usr/share/wazuh-dashboard/node/bin/node --no-warnings --max-http-header-size=65536 --unhandled-rejections=warn /usr/share/wazuh-dash>

Apr 24 10:03:16 ip-172-31-34-232 opensearch-dashboards[58849]: {"type":"response","@timestamp":"2025-04-24T10:03:16Z","tags":[],"pid":58849,"method":"get">
Apr 24 10:03:16 ip-172-31-34-232 opensearch-dashboards[58849]: {"type":"response","@timestamp":"2025-04-24T10:03:16Z","tags":[],"pid":58849,"method":"get">
Apr 24 10:03:16 ip-172-31-34-232 opensearch-dashboards[58849]: {"type":"response","@timestamp":"2025-04-24T10:03:16Z","tags":[],"pid":58849,"method":"post>
Apr 24 10:03:16 ip-172-31-34-232 opensearch-dashboards[58849]: {"type":"response","@timestamp":"2025-04-24T10:03:16Z","tags":[],"pid":58849,"method":"get">
Apr 24 10:03:16 ip-172-31-34-232 opensearch-dashboards[58849]: {"type":"response","@timestamp":"2025-04-24T10:03:16Z","tags":[],"pid":58849,"method":"post>
Apr 24 10:03:16 ip-172-31-34-232 opensearch-dashboards[58849]: {"type":"response","@timestamp":"2025-04-24T10:03:16Z","tags":[],"pid":58849,"method":"post>
Apr 24 10:03:16 ip-172-31-34-232 opensearch-dashboards[58849]: {"type":"response","@timestamp":"2025-04-24T10:03:16Z","tags":[],"pid":58849,"method":"get">
Apr 24 10:03:17 ip-172-31-34-232 opensearch-dashboards[58849]: {"type":"response","@timestamp":"2025-04-24T10:03:16Z","tags":[],"pid":58849,"method":"post>
Apr 24 10:03:17 ip-172-31-34-232 opensearch-dashboards[58849]: {"type":"response","@timestamp":"2025-04-24T10:03:16Z","tags":[],"pid":58849,"method":"post>
Apr 24 10:03:17 ip-172-31-34-232 opensearch-dashboards[58849]: {"type":"response","@timestamp":"2025-04-24T10:03:17Z","tags":[],"pid":58849,"method":"get">
admin@ip-172-31-34-232:~$ sudo systemctl status filebeat.service 
● filebeat.service - Filebeat sends log files to Logstash or directly to Elasticsearch.
     Loaded: loaded (/lib/systemd/system/filebeat.service; enabled; preset: enabled)
     Active: active (running) since Thu 2025-04-24 09:49:52 UTC; 17min ago
       Docs: https://www.elastic.co/products/beats/filebeat
   Main PID: 57328 (filebeat)
      Tasks: 10 (limit: 9395)
     Memory: 20.5M
        CPU: 185ms
     CGroup: /system.slice/filebeat.service
             └─57328 /usr/share/filebeat/bin/filebeat --environment systemd -c /etc/filebeat/filebeat.yml --path.home /usr/share/filebeat --path.config /e>

Apr 24 09:49:52 ip-172-31-34-232 systemd[1]: Started filebeat.service - Filebeat sends log files to Logstash or directly to Elasticsearch..
```

**Comment by antoniorr02** [comment]
Blocked: Missing changes from version 4.12.0. Cannot proceed with this issue as neither DTT nor package signing is working.

**Comment by antoniorr02** [comment]
# DDT Report CentOS 10 aarch64 / amd 🟢

As the changes from 4.12.0 has been added to 4.13.0, I tried to execute DDT again.

The Test-agent-complete.yaml used was: 

And it finished correctly.

**Comment by antoniorr02** [comment]
# Support to the upgrade test pipeline 🟢

## Generate 4.13.0 packages

Template:  [targets_template.yaml](https://github.com/user-attachments/files/20119043/targets_template.txt)

```

```

## Sign 4.13.0 packages

## Move packages to staging from pre-release

## Using packages to test the upgrade pipeline

**Comment by antoniorr02** [comment]
Issue on hold while I get the needed permissions https://github.com/wazuh/internal-devel-requests/issues/2391

**Comment by antoniorr02** [comment]
On hold because I'm working on https://github.com/wazuh/wazuh/issues/29720, which has highest priority issue

**Comment by antoniorr02** [comment]
# Using packages to test the upgrade pipeline 🔴

Firstly, I had to generate images in EC2 for wazuh manager and agent 4.12.0.

With the packages and images generated, I was able to run the upgrade test.

The problem was that CentOS 10 installs Python version 3.12.2 by default, while the executor node uses Python 3.11.2. This creates an incompatibility with Ansible that cannot be resolved by any method.

The following have been tried, among other things:
- Installing a compatible version of Python in a testing folder, but it took the default version.
- Installing a compatible version of Python in the testing folder and marking it as default with symbolic links.
- Overriding the default Python and installing a lower version, which breaks the system because Python is critical to the system.
- Downgrading, the same thing happens as before.

**Comment by antoniorr02** [comment]
# Update

It was decided that the upgrade, the docker image, and the upgrade_tier are removed and will be resumed in DTT2.
All related changes are reverted.
