### ISSUE TITLE
Support new stage Alpha 2 for 4.9.0

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#24559]
# Description

This issue attempts to support a new stage Alpha 2 for 4.9.0 in the Wazuh system.

# Tasks

Each task must be completed sequentially based on numbering. Tasks within the same subsection might be parallelized.

### wazuh-qa -> @wazuh/qa
- https://github.com/wazuh/wazuh-qa/issues/5570
### wazuh-jenkins -> @wazuh/qa
- https://github.com/wazuh/wazuh-jenkins/issues/6724
### wazuh-automation -> @wazuh/devops
- https://github.com/wazuh/wazuh-automation/issues/1734
### wazuh-packages -> @wazuh/agent
- https://github.com/wazuh/wazuh-packages/issues/3036
### wazuh -> @wazuh/cppserver
- https://github.com/wazuh/wazuh/issues/24558
### wazuh-ansible -> @wazuh/devops
- https://github.com/wazuh/wazuh-ansible/issues/1341
### wazuh-docker -> @wazuh/devops
- https://github.com/wazuh/wazuh-docker/issues/1430
### wazuh-puppet -> @wazuh/devops
- https://github.com/wazuh/wazuh-puppet/issues/1055
### wazuh-kubernetes -> @wazuh/devops
- https://github.com/wazuh/wazuh-kubernetes/issues/748
### wazuh-dashboard-plugins -> @wazuh/dashboard
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6819
### qa-integration-framework -> @wazuh/pyserver
- https://github.com/wazuh/qa-integration-framework/issues/200
### wazuh-security-dashboards-plugin -> @wazuh/dashboard
- https://github.com/wazuh/wazuh-security-dashboards-plugin/issues/63
### wazuh-indexer -> @wazuh/indexer
- https://github.com/wazuh/wazuh-indexer/issues/305
### wazuh-agent -> @wazuh/agent
- https://github.com/wazuh/wazuh-agent/issues/35
### wazuh-indexer-plugins -> @wazuh/indexer
- https://github.com/wazuh/wazuh-indexer-plugins/issues/15
### wazuh-agent-packages -> @wazuh/agent
- https://github.com/wazuh/wazuh-agent-packages/issues/53
### wazuh-dashboard -> @wazuh/dashboard
- https://github.com/wazuh/wazuh-dashboard/issues/235
### wazuh-virtual-machines -> @wazuh/devops
- https://github.com/wazuh/wazuh-virtual-machines/issues/7
### wazuh-installation-assistant -> @wazuh/devops
- https://github.com/wazuh/wazuh-installation-assistant/issues/8
### wazuh-documentation -> @wazuh/qa
- https://github.com/wazuh/wazuh-documentation/issues/7516

## 2. Create pre-release packages for v4.9.0-alpha2 using tags from task 1. -> @wazuh/qa
- [ ] ~Upload updated filebeat module~ No changes
- [x] Create packages https://github.com/wazuh/wazuh-jenkins/issues/6710

## 3. Create and assign testing issues for 4.9.0 Alpha 2. -> @davidjiglesias
- [x] Create issues https://ci.wazuh.info/job/Procedure_cicd_release_issues/163/

## 4.Set up demo environment for 4.9.0 Alpha 2. -> @wazuh/devops

- https://github.com/wazuh/wazuh-automation/issues/1735
