### ISSUE TITLE
Benchmarking tests: Monitoring class for process data collection

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#24683]
# Description 

Develop a monitoring class to collect process data within the Wazuh environment. This class should track various aspects of process performance, such as CPU usage, memory consumption, etc. The data collected will be used to analyze and optimize the performance of the Wazuh agent.

# Overview

We are considering using existing tools for this task, specifically the [QA Monitor class](https://github.com/wazuh/wazuh-qa/blob/master/deps/wazuh_testing/wazuh_testing/tools/performance/binary.py). This issue involves checking the current status of the monitor class, fixing any pending bugs, and adding any new capabilities needed to fulfill the requirements.

# Functional requirements
- The Python module should monitor all Wazuh component processes, generating a CSV with the collected values for each timestamp.
- The Python module should track the disk usage of the Wazuh installation over time.
- A Python script should be capable of launching process monitoring.
- A Python script should be capable of launching disk partition monitoring.

# Tasks
- [x] Research the current issues of the monitoring class in the Wazuh-qa repository and fix them if necessary to meet the requirements.
- [x] Research which metrics should be included in the desired monitoring modules.
- [x] Create a new module capable of tracking disk usage.
- [x] Create a Python script to use these modules on an endpoint easily

# Validation
- [ ] Proof of concept (PoC) of monitoring capabilities in a real environment for the agent, server, indexer, and dashboard.

**Comment by jseg380** [comment]
In a meeting with @Rebits some questions about the issue were clarified. These inquiries were the following:
- Add the missing key metrics seems to not specify which are the key metrics that already exist
- Research metrics to monitor the mentioned resources (_such as CPU usage, memory consumption, and runtime duration_). There are numerous metrics for tracking the aforementioned resources, therefore I find highly difficult to make a good choice all by myself on what metrics should be chosen.
- It is mentioned that bugs of the current [QA Monitor class](https://github.com/wazuh/wazuh-qa/blob/master/deps/wazuh_testing/wazuh_testing/tools/performance/binary.py) should be fixed, but no links to those bugs are provided and after searching the issues in the repo nothing was found but I am unsure if I was using the wrong keywords.
- When talking about the disk usage of the installation over time it wasn't specified whether logs should be taken into account but as Víctor said it makes sense to exclude them.
- Also one task includes creating a new module for monitoring disk usage and it is alluded several times about having multiple modules instead of one. It has been decided that it will be up to the assignee.

**Comment by jseg380** [comment]
Refactored current script to make use of "advanced" type hinting (making use of the typing module).
Started modularization of Monitor and different logging classes.
Researched references made to the Monitor class, only found [`wazuh_metrics.py`](https://github.com/wazuh/wazuh-qa/blob/master/deps/wazuh_testing/wazuh_testing/scripts/wazuh_metrics.py).
Extensive research about `PEP 8 – Style Guide for Python Code`.

**Comment by jseg380** [comment]
Continued modularization of Monitor and Logging classes and addded type hinting for those last ones.

**Comment by jseg380** [comment]
Continued modularization of Monitor class. Increased functionality of Monitor class to track disk usage instead of creating another module because it seems appropiate in this situation since it already monitors memory size, swap, file descriptors, read and write operations and bytes read and written. As discussed with @Rebits some of the logic of some methods has to be modified not to depend on hardcoded values, or at least specify the available values that can be used.

**Comment by Rebits** [comment]
Moved ETA to 21/09/2024 to allow final review

**Comment by jseg380** [comment]
On hold due to #25203

**Comment by jseg380** [comment]
On hold due to #25270

**Comment by jseg380** [comment]
## Update
Refactoring the existing script that makes use of the module for resource monitoring (the script that is called).

**Comment by jseg380** [comment]
On hold due to  [4.9.0 RC 2 Footprint](https://github.com/wazuh/wazuh/issues/25488)

**Comment by jseg380** [comment]
## Update

Worked on the creation of unit tests for the partition usage module.

**Comment by jseg380** [comment]
On hold due to https://github.com/wazuh/wazuh-jenkins/issues/6919 
Even though the aforementioned issue has lower priority it's planned for the next release so it has precedence over this one.

**Comment by jseg380** [comment]
## Update
Created branch: `enhancement/24683-process-resource-monitoring`
Associated PR: https://github.com/wazuh/wazuh-qa/pull/5747

**Comment by rafabailon** [comment]
### LGTM

**Comment by jseg380** [comment]
Working on the changes requested in the PR (https://github.com/wazuh/wazuh-qa/pull/5747#discussion_r1775635279)
