### ISSUE TITLE
Support new stage Alpha 3 for 4.9.0

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#24702]
# Description

This issue attempts to support a new stage Alpha 3 for 4.9.0 in the Wazuh system.

# Tasks

Each task must be completed sequentially based on numbering. Tasks within the same subsection might be parallelized.

### wazuh-qa -> @wazuh/qa
- https://github.com/wazuh/wazuh-qa/issues/5585
### wazuh-jenkins -> @wazuh/qa
- https://github.com/wazuh/wazuh-jenkins/issues/6777
### wazuh-automation -> @wazuh/devops
- https://github.com/wazuh/wazuh-automation/issues/1746
### wazuh-packages -> @wazuh/agent
- https://github.com/wazuh/wazuh-packages/issues/3049
### wazuh -> @wazuh/cppserver
- https://github.com/wazuh/wazuh/issues/24701
### wazuh-ansible -> @wazuh/devops
- https://github.com/wazuh/wazuh-ansible/issues/1354
### wazuh-docker -> @wazuh/devops
- https://github.com/wazuh/wazuh-docker/issues/1452
### wazuh-puppet -> @wazuh/devops
- https://github.com/wazuh/wazuh-puppet/issues/1065
### wazuh-kubernetes -> @wazuh/devops
- https://github.com/wazuh/wazuh-kubernetes/issues/765
### wazuh-dashboard-plugins -> @wazuh/dashboard
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6849
### qa-integration-framework -> @wazuh/pyserver
- https://github.com/wazuh/qa-integration-framework/issues/208
### wazuh-security-dashboards-plugin -> @wazuh/dashboard
- https://github.com/wazuh/wazuh-security-dashboards-plugin/issues/71
### wazuh-indexer -> @wazuh/indexer
- https://github.com/wazuh/wazuh-indexer/issues/320
### wazuh-agent -> @wazuh/agent
- https://github.com/wazuh/wazuh-agent/issues/47
### wazuh-indexer-plugins -> @wazuh/indexer
- https://github.com/wazuh/wazuh-indexer-plugins/issues/22
### wazuh-agent-packages -> @wazuh/agent
- https://github.com/wazuh/wazuh-agent-packages/issues/61
### wazuh-dashboard -> @wazuh/dashboard
- https://github.com/wazuh/wazuh-dashboard/issues/251
### wazuh-virtual-machines -> @wazuh/devops
- https://github.com/wazuh/wazuh-virtual-machines/issues/14
### wazuh-installation-assistant -> @wazuh/devops
- https://github.com/wazuh/wazuh-installation-assistant/issues/14
### wazuh-qa-automation -> @wazuh/qa
- https://github.com/wazuh/wazuh-qa-automation/issues/5
### wazuh-documentation -> @wazuh/qa
- https://github.com/wazuh/wazuh-documentation/issues/7547

## 2. Create pre-release packages for v4.9.0-alpha3 using tags from task 1. -> @wazuh/qa
- [x] ~Upload updated filebeat module~ Without changes
- [x] Create packages https://github.com/wazuh/wazuh-jenkins/issues/6788

## 3. Create and assign testing issues for 4.9.0 Alpha 3. -> @davidjiglesias
- [x] Create issues 
  - [x] Main https://ci.wazuh.info/job/Procedure_cicd_release_issues/165/
  - [x] E2E

## 4.Set up demo environment for 4.9.0 Alpha 3. -> @wazuh/devops

- https://github.com/wazuh/wazuh-automation/issues/1747
