### ISSUE TITLE
Syscollector cannot get the CPU frequency on Raspberry Pi

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#2488]
When running Syscollector on Raspberry Pi, we have this error:

```log
2019/01/29 21:08:18 wazuh-db[27115] wdb_parser.c:75 at wdb_parse(): DEBUG: Agent 000 query: hardware save 959844733|2019/01/29 21:08:18|unknown|ARMv7 Processor rev 4 (v7l)|4|0.000000|949448.000000|166392.000000|83
2019/01/29 21:11:27 wazuh-db[28373] wdb_syscollector.c:588 at wdb_hardware_insert(): ERROR: at wdb_hardware_insert(): sqlite3_step(): CHECK constraint failed: sys_hwinfo
2019/01/29 21:11:27 wazuh-db[28373] wdb_parser.c:1282 at wdb_parse_hardware(): DEBUG: wdb_parse_hardware(): Cannot save HW information.
2019/01/29 21:11:27 wazuh-db[28373] wdb_parser.c:152 at wdb_parse(): ERROR: Unable to update 'sys_hwinfo' table for agent '000'
```

The problem is that Syscollector isn't picking the CPU frequency and it reports the default value: `0`. On the other hand, the Wazuh DB schema constraints the CPU frequency to a positive number:
```sql
cpu_mhz REAL CHECK (cpu_mhz > 0)
```

## Subtasks
- [ ] Fix Syscollector's hardware reader to get the CPU frequency. Hint: can we read _/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq_?
- [x] Relax constraints at DB table `sys_hwinfo`. Indeed, agents below v3.8 will also fail to get the number of CPU cores.
- [x] Update the Wazuh DB upgrade.

**Comment by vikman90** [comment]
Related issue: https://github.com/wazuh/wazuh/issues/2716
