### ISSUE TITLE
Antitampering functionality implementation 

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#24908]
Parent issue:
- https://github.com/wazuh/wazuh/issues/23466

# Description

Hello team,

This issue is to finish the complete implementation of the new anti-tampering functionality of the agent, in charge of preventing the uninstallation of the agent until the validation by the manager for that user, in case it has been configured previously.

## To-do list
- [x] We must adapt the latest changes related to the new API endpoint.
- [x] Perform the necessary tests of the complete flow, using the API request with real credentials.
- [x] Check the getConfig functionality for the new anti_tampering config block.

**Comment by jotacarma90** [comment]
# Update 25/07/2024
- I have created the working branch:
- I have implemented the new page of the ossec.conf section with the necessary info of the new anti_tampering block.
- Rethinking if it is necessary an entry in capabilities for this functionality. Pending open thread.

**Comment by jotacarma90** [comment]
# Update 19/08/2024
- Changes in endpoint name modification
- Going through all the code and trying to make it work locally. I have set up an environment for it.
- Testing all the code to verify the functionality.
