### ISSUE TITLE
Preparation for Merging `11334-dev-new-wazuh-engine` into Master

### ISSUE THREAD

**Issue by juliancnn** [wazuh/wazuh#24922]
### Background
As we prepare to merge the `11334-dev-new-wazuh-engine` branch into the master branch, it is crucial to revert certain modifications made outside the `src/engine` directory to maintain the integrity and functionality of the master branch. This issue outlines the necessary reversions and updates required for a smooth transition.

#### Revert Specific Configurations
- **Windows Configuration Reversion:** 
  - From commit [e79b7df](https://github.com/wazuh/wazuh/commit/e79b7df04517e37f80ddbbd2effd0b626b9d54f7#diff-5405f4d73e62edf9c24bd46ff201c92d977c6a025e6c3dfbf683ce034d81474c), remove the following block from `src/win32/ossec.conf`:
    ```xml
    <localfile>
      <location>Microsoft-Windows-Sysmon/Operational</location>
      <log_format>eventchannel</log_format>
    </localfile>
    ```
- **Revert Changes in `read_json`:**
  - Revert changes made in the `read_json` function as introduced in commit [a70012e](https://github.com/wazuh/wazuh/commit/a70012e77b5ad5a7c0e5d3a429af249541521d03), which was an approach later deemed unnecessary.

- **Revert Wazuh-Logcollector Event Channel Changes:**
  - Revert changes made to the Wazuh-Logcollector regarding the event channel to ensure that collected events are sent as JSON. This reversion aligns with the original behavior before the `11334-dev-new-wazuh-engine` modifications.

#### Update GitHub Actions
- **Modify GitHub Actions:**
  - Update the following GitHub Actions to trigger on merges or pushes to the master branch, ensuring they do not run exclusively against `11334-dev-new-wazuh-engine`:
    - Engine Health Test
    - Engine Helper Functions Test
    - Engine Integration Test
    - Engine Unit Test

### Tasks
- [x] Revert specific configurations as outlined.
- [x] Update GitHub Actions to correctly trigger against the master branch.
- [x] Confirm reversion of the Logcollector event channel change.

### Justification
These reversions are critical to ensure that the `11334-dev-new-wazuh-engine` branch integrates seamlessly into the master without introducing configurations or changes that were specific to earlier development phases or that are incompatible with the project's current direction.

### Additional Notes
- Ensure thorough testing post-reversion to verify that no unintended behaviors have been introduced.
- Document any changes and their impacts to keep the team informed and maintain transparency in development processes.

**Comment by juliancnn** [comment]
## Update

Created the required PR with all changes, ready for review

**Comment by juliancnn** [comment]
## Update

Created the required PR with all changes, ready for review

**Comment by juliancnn** [comment]
## Update

- Fixes GHA, are now executed regardless of the banch they point to.
