### ISSUE TITLE
Create unit tests using TAP

### ISSUE THREAD

**Issue by Cerv1** [wazuh/wazuh#2507]
## Task summary 
We currently use `Check` as our unit testing framework. Since it is outdated and has no support for some operating systems, we will no longer use it.

Now we're going to use **Test Anything Protocol (TAP)** which  is a protocol to allow communication between _unit tests_ and a _test harness_. We're going to design our custom test suite using the guidelines defined in **TAP**.

For further information about this protocol please refer to the [TAP specification](https://testanything.org/tap-specification.html).
Best regards,
Cerv1.

**Comment by Cerv1** [comment]
## Current status 

### 1. Migrate current tests to TAP 

- [x] Migrate `os_crypto` tests (https://github.com/wazuh/wazuh/commit/7f15d2a4b4e8200aa68cf186d7152c0829eaa7ba)
- [ ] Migrate `os_net` tests
- [ ] Migrate `os_regex` tests
- [ ] Migrate `shared` tests
- [ ] Migrate `os_zlib` tests
- [ ] Migrate `os_xml` tests

## Examples

Output of the new `os_crypto` bellow
```

   STARTING TEST - OS_CRYPTO   

    ok  1 - Blowfish encryption test.
    ok  2 - MD5 encryption test.
    ok  3 - MD5 file reading encryption test.
not ok  4 - MD5 non-existing file to read from. # TODO
    ok  5 - SHA1 encryption test.
    ok  6 - SHA1 file reading encryption test.
not ok  7 - SHA1 non-existing file to read from. # TODO
    ok  8 - MD5+SHA1 file reading encryption test.
    ok  9 - MD5+SHA1 reading from file using command encryption test.
not ok 10 - MD5+SHA1 non-existing file to read from using command. # TODO
1..10

      [ ALL TESTS PASSED ]

    ENDING TEST  - OS_CRYPTO   
```

**Comment by albertomn86** [comment]
Merged
