### ISSUE TITLE
Prepare demo for 5th week

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#2509]
## Summary

Demo to show and test all changes achieved during the last week.
Create a new branch from the latest version of 3.9 and merge the following branches (if not already merged in 3.9):
* Framework
- [x] https://github.com/wazuh/wazuh/tree/3.9-new-framework
- [x] https://github.com/wazuh/wazuh/tree/dev-rootcheck-pm
* API
- [x] https://github.com/wazuh/wazuh-api/tree/dev-rootcheck-pm
- [x] https://github.com/wazuh/wazuh-api/tree/dev-3.9-edit-ruleset-api
* Environment
- [x] Create an environment with a cluster of 3 manager and 3 agents. For example, with docker-compose

**Comment by crd1985** [comment]
# Status update
## Summary
After @snaow request, I have configured a docker-based environment including Elastic stack and Wazuh Kibana plugin.
Unfortunately, the demo will not be complete until the restarting managers functionality is working, so as to let users changing wazuh configuration safely.

## Tasks
* [2.5h] Configure elasticsearch, kibana, filebeat and logstash within my docker environment

## Stoppers
* https://github.com/wazuh/wazuh-api/issues/297

## Difficulties
* First time configuring the demo environment, but already automated and working
* Error when executing chown within folder of kibana plugin. It took too much to complete because of the high number of files inside node_modules. Fixed bypassing this folder which is not necessary.

## Pending
* Merging https://github.com/wazuh/wazuh-api/issues/297
* Live demo with @snaow

**Comment by crd1985** [comment]
Everything needed for demo has been uploaded to branch 3.9-alpha (both api and wazuh repos).
