### ISSUE TITLE
Framework unittests review

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#2511]
## Description
Review carefully if unit tests really cover the new code developed the week before. Think about extreme and limit cases and try to automate them.

The main goal is to guarantee our code is robust and free of bugs before passing to integration and service testing.

## Subtasks
- [x] Check unittests for policy monitoring
- [x] Check unittests for cdb lists
- [x] Check unittests for updating manager files (rulesets, decoders, lists, ossec.conf)

**Comment by crd1985** [comment]
We have been reviewing all unit tests for this week. Unit tests results are pasted on each PR for 3.9 release. 
For me they are OK to go ahead with merging the code and integrated testing.
