### ISSUE TITLE
Policy monitoring module - 6th week

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#2518]
|Main issue|Branch|
|---|---|
|[#1983](https://github.com/wazuh/wazuh/issues/1983)|3.9-sql-rootcheck ([Compare](https://github.com/wazuh/wazuh/compare/3.9...3.9-sql-rootcheck))|

This is the planning for continuing the development of a new module to perform policy monitoring scans.

- [x] Collect passed checks and send them as events.
- [x] Create a hash table in the agent to calculate differences between scans.
_The hash table will contain the `check id` + `result` of every check._
- [x] Implement a precheck to evaluate the requirements of a PM file.
- [x] Wazuh DB store the last state of scans sent by the agents.
- [x] Create rules to alert about state changes of checks.
- [x] Design a mechanism to ensure the integrity of the PM database. (_in progress_) https://github.com/wazuh/wazuh/issues/2556

**Comment by TJOSERAFAEL** [comment]
### Status

- Rules added for throwing alerts to the log.
- Hash table implemented to send only the differences.
- Fixed some crashes
- Adjusted mandatory fields

### What remains

- [ ] Implement a precheck to evaluate the requirements of a PM file.
- [ ] Design a mechanism to ensure the integrity of the PM database.

**Comment by cristgl** [comment]
Ruleset status
------------------
Rules have been added to the ruleset folder, but they aren't matching yet. I think the problem comes from the way the event gets decoded, as it needs to be parsed by the JSON decoder (`JSON_Decoder_Exec`). Also, it is needed to write the event at the `lf` variable that is returned to `analysisd` to match the new rules.

Windows testing
---------------------
The compilation for Windows has been fixed, as there were some functions that weren't available at this SO. Also the default directory that was not being taken into account as it was running on _/var/ossec_.

**Comment by cristgl** [comment]
- Fix matching rules
- Added rules for checks that change their value
- Add `requirements` field check. For now, it only works if the `requirements` block is at the end of the file, if not, it will take the whole file from `requirements` to the last `check`.

**Comment by TJOSERAFAEL** [comment]
### Next steps

- [ ] Transform every cis file to yaml format
- [ ] Add `file` field to policy on yaml
- [ ] Make the `policy-monitoring` hash table store the following data:
  - [ ] Store the check `id` as key
  - [ ] Store `result, json` as value
- [ ] Alert summary only when something has changed
- [ ] Send summary with `start_time`,`end_time`

The new database is:

```sql
CREATE TABLE IF NOT EXISTS pm_policy (
    name TEXT,
    file TEXT,
    policy_id TEXT,
    description TEXT,
    `references` TEXT
);

CREATE TABLE IF NOT EXISTS pm_scan_info (
    scan_id INTEGER PRIMARY KEY,
    start_scan INTEGER,
    end_scan INTEGER,
    policy_id TEXT REFERENCES pm_policy (policy_id),
    pass INTEGER,
    fail INTEGER,
    score INTEGER
);

CREATE TABLE IF NOT EXISTS pm_check (
    scan_id TEXT REFERENCES pm_scan_info (scan_id),
    id INTEGER PRIMARY KEY,
    title TEXT,
    cis_control TEXT,
    description TEXT,
    rationale TEXT,
    remediation TEXT,
    file TEXT,
    process TEXT,
    directory TEXT,
    registry TEXT,
    `references` TEXT,
    result TEXT NOT NULL
);
```

**Comment by cristgl** [comment]
- Fixed setting the requirements check at the beginning of file.
- Fixed 'enabled' option. The module was running when `enabled` was set to "no".
- Add documentation. Explained the way this module works. It remains describing an use case and configuration options. Working at branch `3.9-add-policy-monitoring-doc`.

**Comment by TJOSERAFAEL** [comment]
### Status

- Completed database integration and data filling
- Every scan with its own ID
- Summary with all fields required for the table `pm_policy`

### Next steps tomorrow

- [ ] Hash table unique for each policy
- [ ] Calculate hash
- [ ] Send summary only when something changed

**Comment by TJOSERAFAEL** [comment]
### Status

- Policy monitoring renamed to `configuration_assessment`
- Now each policy file has it's own hash table for managing differences
- A  MD5 hash is calculated for each hash table, sending the hash along with the summary
- The JSON event it's also stored on the hash table, allowing a future retrieving of data when the integrity protocol is completed

The DB tables have been updated to the following schema:

```sql
CREATE TABLE IF NOT EXISTS configuration_assessment_policy (
   name TEXT,
   file TEXT,
   id TEXT,
   description TEXT,
   `references` TEXT
);

CREATE TABLE IF NOT EXISTS configuration_assessment_scan_info (
   id INTEGER PRIMARY KEY,
   start_scan INTEGER,
   end_scan INTEGER,
   policy_id TEXT REFERENCES configuration_assessment_policy (id),
   pass INTEGER,
   fail INTEGER,
   score INTEGER,
   hash TEXT
);

CREATE TABLE IF NOT EXISTS configuration_assessment_check (
   scan_id INTEGER REFERENCES configuration_assessment_scan_info (id),
   id INTEGER PRIMARY KEY,
   title TEXT,
   description TEXT,
   rationale TEXT,
   remediation TEXT,
   file TEXT,
   process TEXT,
   directory TEXT,
   registry TEXT,
   `references` TEXT,
   result TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS configuration_assessment_check_compliance (
   id_check INTEGER REFERENCES configuration_assessment_check (id),
  `key` TEXT,
  `value` TEXT
);
```
### Next steps

- [ ] Alert summary only if the HASH has changed
- [ ] Change the `<profile>` to  `<policies>` 
- [ ] Implement the integrity protocol

**Comment by TJOSERAFAEL** [comment]
### Status

- Completed hash integrity comparison with DB
- Summary is only alerted when the hash differs
- Memory leaks fixed for decoder and module
- Completed `<policies>` tag with `enabled` attribute

An example of the configuration:

```xml
<configuration_assessment>
    <enabled>yes</enabled>
    <scan_on_start>yes</scan_on_start>
    <interval>1m</interval>
    <skip_nfs>yes</skip_nfs>

    <policies>
      <policy enabled="yes">cis_debian_linux_rcl.yml</policy>
    </policies>
</configuration_assessment>

```

### Next steps

- [ ] Implement integrity protocol with chunk sending
