### ISSUE TITLE
Post release tasks for 4.8.2

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#25278]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.8.2.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.8.2-into-4.9.0`.

## Tasks

- [x] Merge branch `4.8.2` into branch `4.9.0`. #25299
- [x] Merge branch `4.9.0` into branch `4.9.1`. #25302
- [x] Merge branch `4.9.1` into branch `4.10.0`. #25309
- [x] ~Merge branch `4.10.0` into branch `master`. #25313~
- [x] Publish GitHub release as latest.
- [x] Delete all stage pre-releases for 4.8.2 (https://github.com/wazuh/wazuh/releases).
- [x] Delete all stage tags for v4.8.2. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.8.2-rc1, 4.8.2-alpha1, etc.

**Comment by sebasfalcone** [comment]
## Issue blocked
We need a definition of how to proceed with the merge into master. Given the huge refactor taking place, changes will be removed anyway

**Comment by JcabreraC** [comment]
> ## Issue blocked
> 
> We need a definition of how to proceed with the merge into master. Given the huge refactor taking place, changes will be removed anyway

No merge from 4.10.0 to master will take place due to the upcoming changes in version 5.0.0, which separates the agent from the manager and includes significant module refactoring.
