### ISSUE TITLE
SPIKE - Review and adapt configuration for Wazuh-Engine cluster compatibility

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#25472]
### Description:
As part of the ongoing development to integrate Wazuh-Engine into a cluster environment, this issue focuses on reviewing and adapting the current configuration module of Wazuh-Engine. The goal is to ensure that Wazuh-Engine can effectively receive and process configurations necessary for operation within a cluster, without orchestrating configurations itself.

### Objectives:
- **Review Current Configuration Module**: Assess the existing configuration module used by Wazuh-Engine to determine its capabilities and limitations in a clustered environment.
- **Define Necessary Changes**: Identify modifications needed to enable Wazuh-Engine to receive and apply configurations from the cluster master node effectively.

### Tasks:
- [x] **Assessment of Current Configuration System**: Analyze the current configuration handling mechanism within Wazuh-Engine to understand how it processes and applies configuration data.
- [x] **Identify Required Configurations for Cluster Operation**: Determine the specific configurations that Wazuh-Engine needs to function as part of a cluster.
- [x] **Propose Modifications**: Outline changes required in the configuration module to handle cluster-specific settings without affecting the standalone functionality of Wazuh-Engine.
- [x] **Collaboration and Documentation**: Work closely with the cluster development team to align the configuration module adaptations with overall cluster functionality. Document the changes needed and propose a plan for implementation.

### Expected Outcome:
The configuration module of Wazuh-Engine will be capable of seamlessly integrating into the cluster environment, receiving and applying configurations as dictated by the cluster master node. This integration will enhance the modularity and scalability of Wazuh-Engine within the new cluster framework.

### Notes:
This task is critical for ensuring that Wazuh-Engine can operate efficiently within a cluster without taking on the role of configuration orchestration, thereby simplifying its integration and maintenance in large-scale deployments.

**Comment by JcabreraC** [comment]
## Update

Actual configuration:
```
# Sets the logging level.
server.log_level="error"
# Sets the logging output. Default: stdout.
server.log_output="/home/bee/Project/wazuh/src/engine/____test/integration/logs/engine_tmp.log"
# Allows whether or not to delete the log file at each start of the engine
server.log_truncate=true
# Sets the number of threads for server worker pool.
server.server_threads=2
# Sets the events server socket address.
server.event_socket="/home/bee/Project/wazuh/src/engine/____test/integration/queue/sockets/queue"
# Sets the size of the event task queue of the server (0 = disable, process asynchonously).
server.event_queue_tasks=1000000
# Sets the API server socket address.
server.api_socket="/home/bee/Project/wazuh/src/engine/____test/integration/queue/sockets/engine-api"
# Sets the size of the API task queue of the server. (0 = disable, process asynchonously).
server.api_queue_tasks=300
# Sets the timeout for the API socket in miliseconds.
server.api_timeout=10000
# Sets the path to the folder where the assets are located (store).
server.store_path="/home/bee/Project/wazuh/src/engine/____test/integration/engine/store"
# Sets the path to the KVDB folder.
server.kvdb_path="/home/bee/Project/wazuh/src/engine/____test/integration/engine/etc/kvdb/"
# Sets the install path to the time zone database.
server.tzdb_path="/home/bee/Project/wazuh/src/engine/____test/integration/engine/tzdb"
# Sets the number of threads to be used by the router.
server.router_threads=2
# Sets the number of events that can be queued to be processed.
server.queue_size=1000000
# Sets the path to the file where the flood events will be stored.
server.queue_flood_file="/home/bee/Project/wazuh/src/engine/____test/integration/logs/engine-flood.log"
# Sets the number of attempts to try to push an event to the queue.
server.queue_flood_attempts=3
# Sets the number of microseconds to sleep between attempts to push an event to the queue.
server.queue_flood_sleep=100
```

**Comment by JcabreraC** [comment]
## Update
After the latest changes, the current configuration is:
```
# ./build/main config get                                                                                                                                                                          130 ↵

# Sets the logging level.
server.log_level="debug"

# Sets the number of threads for server worker pool.
server.server_threads=1

# Sets the events server socket address.
server.event_socket="/var/ossec/queue/sockets/queue"

# Sets the size of the event task queue of the server (0 = disable, process asynchonously).
server.event_queue_tasks=0

# Sets the API server socket address.
server.api_socket="/var/ossec/queue/sockets/engine-api"

# Sets the size of the API task queue of the server. (0 = disable, process asynchonously).
server.api_queue_tasks=0

# Sets the timeout for the API socket in miliseconds.
server.api_timeout=3600000

# Sets the path to the folder where the assets are located (store).
server.store_path="/workspaces/repos/engine-installed/store"

# Sets the path to the KVDB folder.
server.kvdb_path="/workspaces/repos/engine-installed/kvdb/"

# Sets the install path to the time zone database.
server.tzdb_path="/workspaces/repos/engine-installed/tzdb"

# Enable automatic updates of the time zone database.
server.tzdb_automatic_update=false

# Sets the number of threads to be used by the router.
server.router_threads=2

# Sets the number of events that can be queued to be processed.
server.queue_size=1000000

# Sets the path to the file where the flood events will be stored.
server.queue_flood_file=""

# Sets the number of attempts to try to push an event to the queue.
server.queue_flood_attempts=3

# Sets the number of microseconds to sleep between attempts to push an event to the queue.
server.queue_flood_sleep=100

# If enabled, the queue will drop the flood events instead of storing them in the file.
server.queue_drop_flood=false
```

**Comment by JcabreraC** [comment]
Analysis:
```
# Sets the logging level.
server.log_level="debug"
```
Remains in the configuration.

```
# Sets the number of threads for server worker pool.
server.server_threads=1
```

Change with `http-lib` implementation.

```
# Sets the events server socket address.
server.event_socket="/var/ossec/queue/sockets/queue"
```
Removed.

```
# Sets the size of the event task queue of the server (0 = disable, process asynchonously).
server.event_queue_tasks=0
```

Change with `http-lib` implementation.

```
# Sets the API server socket address.
server.api_socket="/var/ossec/queue/sockets/engine-api"
```

Removed with package creation.

```
# Sets the size of the API task queue of the server. (0 = disable, process asynchonously).
server.api_queue_tasks=0
```

Change with `http-lib` implementation (queue for requests configurable ?).

```
# Sets the timeout for the API socket in miliseconds.
server.api_timeout=3600000
```

Change with `http-lib` implementation.

```
# Sets the path to the folder where the assets are located (store).
server.store_path="/workspaces/repos/engine-installed/store"
```

Removed with package build.

```
# Sets the path to the KVDB folder.
server.kvdb_path="/workspaces/repos/engine-installed/kvdb/"
```

Removed with package creation.

```
# Sets the install path to the time zone database.
server.tzdb_path="/workspaces/repos/engine-installed/tzdb"
```

Removed with package build.

```
# Enable automatic updates of the time zone database.
server.tzdb_automatic_update=false
```

Remains in configuration (check at startup).

```
# Sets the number of threads to be used by the router.
server.router_threads=2
```

Remains in the configuration

```
# Sets the number of events that can be queued to be processed.
server.queue_size=1000000
```

Remains in the configuration: non-persistent router queue. It queues and the router is pulling events.

```
# Sets the path to the file where the flood events will be stored.
server.queue_flood_file=""
```

Removed with the packet. This feature can be permanently removed.

```
# Sets the number of attempts to try to push an event to the queue.
server.queue_flood_attempts=3
```

Deleted (internal)

```
# Sets the number of microseconds to sleep between attempts to push an event to the queue.
server.queue_flood_sleep=100
```

Deleted (internal)

```
# If enabled, the queue will drop the flood events instead of storing them in the file.
server.queue_drop_flood=false
```

This will be configurable ? the event float was decided the last time.

**Comment by JcabreraC** [comment]
## Summary

Engine configuration:
```
# Sets the logging level.
server.log_level="debug"

# Enable automatic updates of the time zone database.
server.tzdb_automatic_update=false

# Sets the number of threads to be used by the router.
server.router_threads=2

# Sets the number of events that can be queued to be processed.
server.queue_size=1000000
```

Change with `http-lib` implementation:
```
# Sets the number of threads for server worker pool.
server.server_threads=1

# Sets the size of the event task queue of the server (0 = disable, process asynchonously).
server.event_queue_tasks=0

# Sets the size of the API task queue of the server. (0 = disable, process asynchonously).
server.api_queue_tasks=0

# Sets the timeout for the API socket in miliseconds.
server.api_timeout=3600000
```

Deleted (internal):
```
# Sets the number of attempts to try to push an event to the queue.
server.queue_flood_attempts=3

# Sets the number of microseconds to sleep between attempts to push an event to the queue.
server.queue_flood_sleep=100
```

Removed with package build:
```
# Sets the events server socket address.
server.event_socket="/var/ossec/queue/sockets/queue"

# Sets the API server socket address.
server.api_socket="/var/ossec/queue/sockets/engine-api"

# Sets the path to the folder where the assets are located (store).
server.store_path="/workspaces/repos/engine-installed/store"

# Sets the path to the KVDB folder.
server.kvdb_path="/workspaces/repos/engine-installed/kvdb/"

# Sets the install path to the time zone database.
server.tzdb_path="/workspaces/repos/engine-installed/tzdb"

# Sets the path to the file where the flood events will be stored.
server.queue_flood_file=""
```

Configurable or default flooding ?
```
# If enabled, the queue will drop the flood events instead of storing them in the file.
server.queue_drop_flood=false
```

**Comment by JcabreraC** [comment]
Finally, the configuration that is maintained for the engine is:
```xml
# Sets the logging level.
server.log_level="debug"

# Enable automatic updates of the time zone database.
server.tzdb_automatic_update=false
```

**Comment by Dwordcito** [comment]
LGTM, as an additional note, engine uses the credentials and certificate configuration to index alerts through the indexer connector.

The indexer connector needs a configuration similar to:

```json
{
     "name": "wazuh-alerts-5.x",
     "host": ["localhost:9200"],
     "user": "admin",
     "password": "admin",
     "ssl": {
         "certificate_authorities": "/etc/ssl/certs/ca.pem",
         "certificate": "/etc/ssl/certs/cert.pem",
         "key": "/etc/ssl/certs/key.pem"
     }
}
```
