### ISSUE TITLE
Enrich and adapt current benchmarks for the Configuration Assessment module

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#2553]
|Main issue|Branch|
|---|---|
|[#1983](https://github.com/wazuh/wazuh/issues/1983)|3.9-sql-rootcheck ([Compare](https://github.com/wazuh/wazuh/compare/3.9...3.9-sql-rootcheck))|

This task consists of adapt the current policies for Rootcheck in _txt_ format to _YAML_ policies files being enriched with the oldest CIS benchmarks available.

### List of benchmarks

- [x] cis_apache_2224_rcl.yml [apache file](https://github.com/wazuh/wazuh/blob/3ec0de82ccb7f68eb07af330a23c4adf338dbf4b/etc/configuration_assessment/cis_apache2224_rcl.yml)
- [x] cis_debian_linux_rcl.yml [debian file](https://github.com/wazuh/wazuh/blob/3ec0de82ccb7f68eb07af330a23c4adf338dbf4b/etc/configuration_assessment/cis_debian_linux_rcl.yml)
- [x] cis_mysql5-6_community_rcl.yml [mysql5.6 community file](https://github.com/wazuh/wazuh/blob/3ec0de82ccb7f68eb07af330a23c4adf338dbf4b/etc/configuration_assessment/cis_mysql5-6_community_rcl.yml)
- [x] cis_mysql5-6_enterprise_rcl.yml [mysql5.6 enterprise file](https://github.com/wazuh/wazuh/blob/3ec0de82ccb7f68eb07af330a23c4adf338dbf4b/etc/configuration_assessment/cis_mysql5-6_enterprise_rcl.yml)
- [ ] cis_rhel_linux_rcl.yml _invalid_
- [x] cis_rhel5_linux_rcl.yml [rhel5 file](https://github.com/wazuh/wazuh/blob/bbc61c9d1da332a8355f0a9cfd0ab87395fe4988/etc/configuration_assessment/cis_rhel5_linux_rcl.yml)
- [x] cis_rhel6_linux_rcl.yml [rhel6 file](https://github.com/wazuh/wazuh/blob/bbc61c9d1da332a8355f0a9cfd0ab87395fe4988/etc/configuration_assessment/cis_rhel6_linux_rcl.yml)
- [x] cis_rhel7_linux_rcl.yml [rhel7 file](https://github.com/wazuh/wazuh/blob/74656b53e67103687d3429b47ffd464fdd473a81/etc/configuration_assessment/rhel/7/cis_rhel7_linux_rcl.yml)
- [x] cis_sles11_linux_rcl.yml [sles11 file](https://github.com/wazuh/wazuh/blob/2f596eecfc1883c84ea714391a2daff40f17f96a/etc/configuration_assessment/suse/11/cis_sles11_linux_rcl.yml)
- [x] cis_sles12_linux_rcl.yml [sles12 file](https://github.com/wazuh/wazuh/blob/2f596eecfc1883c84ea714391a2daff40f17f96a/etc/configuration_assessment/suse/12/cis_sles12_linux_rcl.yml)
- [x] cis_win2012r2_domainL1_rcl.yml [win2012r2domainL1 file](https://github.com/wazuh/wazuh/blob/93988732ee71e222defe39e3fa005bd8999cca3a/etc/configuration_assessment/windows/cis_win2012r2_domainL1_rcl.yml)
- [x] cis_win2012r2_domainL2_rcl.yml [win2012r2domainL2 file](https://github.com/wazuh/wazuh/blob/d075a5dff476dccc195e64cd9079a205c5b513c3/etc/configuration_assessment/windows/cis_win2012r2_domainL2_rcl.yml)
- [x] cis_win2012r2_memberL1_rcl.yml [win2012r2memberL1 file](https://github.com/wazuh/wazuh/blob/72b0809faa3a7f0487666a55848b73f715d3f00a/etc/configuration_assessment/windows/cis_win2012r2_memberL1_rcl.yml)
- [ ] cis_win2012r2_memberL2_rcl.yml _ToDo_
- [x] system_audit_rcl.yml
- [x] system_audit_ssh.yml
- [x] win_applications_rcl.yml
- [x] win_audit_rcl.yml
- [x] win_malware_rcl.yml

**Comment by juan70** [comment]
# Status
2019-02-12
----------
  - `cis_windows_2012r2_domainL1_rcl.yml`. In progress, not finished yet.
  - Very small fixes in `cis_mysql5-6_enterprise_rcl.yml` and `cis_mysql5-6_community.yml`.

2019-02-11
----------
  - `cis_mysql5-6_enterprise_rcl.yml`
  - `cis_mysql5-6_community.yml`

**Comment by chemamartinez** [comment]
GJ @cristgl @juan70!
