### ISSUE TITLE
Configuration Assessment module - 7th week

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#2556]
|Main issue|Branch|
|---|---|
|[#1983](https://github.com/wazuh/wazuh/issues/1983)|3.9-sql-rootcheck ([Compare](https://github.com/wazuh/wazuh/compare/3.9...3.9-sql-rootcheck))|

This is the remaining tasks for the development of the Configuration Assessment module.

### Integrity tasks

- [x] Compare the hashes when a new scan arrives at the manager. No alert when a resend has been received.

- [x] If the checksum fails, create a protocol between manager and agent to resend the scan.

- [x] Program the resend of the scan result for a random interval.

- [x] Purge the database when a Policy is disabled.

### Other tasks

- [x] Add the `policy_id` field to the check table.

- [x] Add indices to DB tables.

- [x] Add warning on log if the requirement is not satisfied.

- [x] Add tags to configuration on demand.

- [x] Refactor code from `policy monitoring` to `configuration assessment`.

- [x] Configuration templates with dynamic policies depending on the agent OS.

- [x] Agent databases migration to 3.9.0.

- [x] Fix configuration on demand.

- [x] Add policy installation on Windows

```
2019/02/10 19:53:42 wazuh-modulesd: ERROR: socketerr (not available).
2019/02/10 19:53:42 wazuh-modulesd: ERROR: (1224): Error sending message to queue.
2019/02/10 19:53:42 wazuh-db: ERROR: DB(000) sqlite3_prepare_v2() stmt(42): no such table: configuration_assessment_check
2019/02/10 19:53:42 wazuh-db: ERROR: Unable to update 'pm_check' table for agent '000'
2019/02/10 19:53:42 ossec-analysisd: ERROR: received: 'err Cannot query policy monitoring'
2019/02/10 19:53:42 ossec-analysisd: ERROR: Error querying policy monitoring database for agent 000
(...Many times...)
2019/02/10 19:53:42 wazuh-db: ERROR: DB(000) sqlite3_prepare_v2() stmt(42): no such table: configuration_assessment_check
2019/02/10 19:53:42 wazuh-db: ERROR: Unable to update 'pm_check' table for agent '000'
2019/02/10 19:53:42 ossec-analysisd: ERROR: received: 'err Cannot query policy monitoring'
2019/02/10 19:53:42 ossec-analysisd: ERROR: Error querying policy monitoring database for agent 000
2019/02/10 19:53:42 wazuh-modulesd:configuration_assessment: INFO: Evaluation finished for policy 'cis_debian_linux_rcl.yml'.
```

- [x] Tag for log messages `WM_CONFIGURATION_ASSESSMENT_MONITORING_LOGTAG`

- [x] Attempts to connect to the socket before sending any data to avoid timing issues.

- [x] Use `wm_sendmsg()` to control the EPS of the module.

- [x] Allow to include policies with absolute paths in the configuration.

- [x] Add configurable `time`interval for DB dump requests

- [x] Decide witch fields of the yaml configuration are string or numeric

- [x] Write a testing template

- [x] Test on all operating systems, valgrind check

**Comment by TJOSERAFAEL** [comment]
## Status

- The integrity check is done on the manager side, if the hash from the DB does not match, it will send a `dump request` to the `configuration_assessment` module (manager only)

**Comment by cristgl** [comment]
Status
=====

Configuration assessment directories structures
-------------------------------------------------------------
Commit: https://github.com/wazuh/wazuh/commit/a75d25b6b114a9bdc1de7d76650c337d1df2df92

It remains the install-files function and fix some typos from the templates. Also, it is necessary to update the ruleset upgrade script to copy the new YAML files.

**Comment by TJOSERAFAEL** [comment]
### Status

- Completed DB integrity check on Windows and Linux agents, the DB dumping requests is handled by the module in the same way on both platforms.

**Comment by TJOSERAFAEL** [comment]
### Completed implementation

- The implementation is now completed, we need heavy testing for this module. Tests must be made for all operating systems that Wazuh supports.
