### ISSUE TITLE
Implement server orders distribution

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#25599]
|Epic|
|---|
| https://github.com/wazuh/wazuh-indexer/issues/349 |

## Description
As part of the Command Manager development, a new endpoint in the current Management API is required to accept `orders` and then distribute them to the other nodes of the cluster so that they can make them available to the agents or make the relevant modifications to the server at the cluster level (i.e., changes related to the engine). This endpoint will require a new role in the RBAC mechanism with the necessary permissions to distribute said orders.

### Orders 
<details><summary>Orders schema</summary>

> [!NOTE]
> This schema may change.
> Referenced from https://github.com/wazuh/wazuh-indexer-plugins/issues/69#issuecomment-2376740320

```json
{
    "source": "Users/Services (via Management API) | Engine (via Management API)",
    "user": "User that originated the request",
    "target": "Cluster name destination",
    "type": "Agent groups | Agent | Server cluster",
    "action": {
        "type": "Agent groups | Agent | Server cluster",
        "params": "Additional parameters for the action",
        "version": "Version of the action",
    },
    "timeout": "Number of seconds to wait for the command to be executed"
}
```

</details>

Nevertheless, the `order` to be received by the endpoint will contain only those fields required to be sent to the corresponding target.

### Flow 
 
<details><summary>Flow</summary>

```mermaid
flowchart TD
    subgraph Master["Server Master"]
        MAPI["Management API"]
        CAPI["Comms API"]
        Cluster["Cluster"]
    end

    subgraph Node_N["Server Node_N"]
        MAPI_N["Management API"]
        CAPI_N["Comms API"]
        Cluster_N["Cluster"]
    end

    subgraph Indexer["Indexer"]


    end

    subgraph lb["Load Balancer"]
        lb_node["Per request"]
    end

    Agent_1 -- GET /commands --> lb
    Agent_N -- GET /commands --> lb
    lb -- GET /commands --> CAPI
    lb -- GET /commands --> CAPI_N
    Indexer -- 1.POST /orders --> MAPI
    MAPI -- 2./distribute_orders --> Cluster
    Cluster -- 3.a.Distribute order to node N --> Cluster_N
    Cluster -- 3.b.Make order available --> CAPI
    Cluster_N -- 4.Make order available --> CAPI_N

    style Indexer fill:#abc2eb
```

</details>

## Requirements

- The Management API of the master node must be able to receive a single order and process it according to the target to which it must be sent.
- The Management API of the master node must be able to redirect the order to the rest of the `wazuh-server` nodes via the cluster. 
- In case the target is an agent or a group of agents:
    - If any agent is not available, the endpoint must return an error response with the corresponding status code (for example, a [`503` status code](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503))
    - If the order is sent to every agent, the response to the indexer must be successful with a `200` status code.

## Tasks

- [x] Develop the new Management API `POST /orders` endpoint to be able to process a single order.
- [x] Develop the RBAC action to send orders to the Management API.
- [x] Apply the necessary changes to the cluster to distribute the orders and communicate with the Comms API to make the orders available to the corresponding agents.
- [x] Develop corresponding Unit Tests.
- [x] Propose AIT test cases to be developed in later phases.

**Comment by GGP1** [comment]
## Update

- Added the endpoint to the spec 
- Created a new RBAC action to send orders
- Added the orders data models
- Implemented the endpoint logic and orders distribution via the local server
- Started creating the unix server for the Comms API

**Comment by GGP1** [comment]
## Update

- Implementation of endpoint to receive commands in the Comms API
- Implementation of class to handle and share commands between processes
- Corrections in the initialization of the local server of the Comms API
- Tests of the changes

I have to make some corrections to the orders request the local server sends to the comms API and add unit tests.

**Comment by GGP1** [comment]
## Update

- Implementated the endpoint that receives commands in the Comms API
- Implementated a class to handle and share commands between processes
- Corrected the initialization of the Comms API local server
- Tested the changes

I have to make some corrections to the orders request the local server sends to the comms API and add unit tests.

**Comment by GGP1** [comment]
## Update

Finished developing the orders distribution, testing the changes and adding unit tests.

### Integration tests cases

1. (OK) Post multiple orders
2. (OK) Post a single order
3. (KO) Try to post an invalid order
4. (KO) Try to post orders without permissions
5. (KO) Try to post orders with an invalid content type

**Comment by GGP1** [comment]
## Update

Applied suggested changes.
