### ISSUE TITLE
Post release tasks for 4.9.0

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#25590]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.9.0.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.9.0-into-4.9.1`.

## Tasks
- [x] Publish GitHub release as latest.
- [x] https://github.com/wazuh/wazuh/pull/25600
- [x] https://github.com/wazuh/wazuh/pull/25601
- [x] Delete all stage pre-releases for 4.9.0 (https://github.com/wazuh/wazuh/releases).
- [x] Delete all stage tags for v4.9.0. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.9.0-rc1, 4.9.0-alpha1, etc.

**Comment by sebasfalcone** [comment]
## Task re-order
Due to a [request from the QA team](https://wazuh-team.slack.com/archives/C02A737S5MJ/p1725547617815139?thread_ts=1725525969.728269&cid=C02A737S5MJ) we are going to publish the release before making the upward merges

**Comment by sebasfalcone** [comment]
## Update
Task completed
