### ISSUE TITLE
Update PyServer test workflows

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#25646]
## Description

During an internal investigation, I noticed that the [Integration tests for API - Tier 2](https://github.com/wazuh/wazuh/actions/workflows/integration-tests-api-tier-2.yml) do not have paths in its workflow condition, causing it to never trigger unless it's executed manually.

Lastly, the [Integration tests for API - Tier 0 and 1](https://github.com/wazuh/wazuh/actions/workflows/integration-tests-api-tier-0-1.yml) include [RBAC](https://github.com/wazuh/wazuh/actions/workflows/integration-tests-rbac-tier-0-1.yml) tests as well, we might want to update the condition to avoid executing them.

This issue aims to resolve these issues.

## Tasks

- [x] ~Add a workflow for the external integrations module unit tests~.
- [x] Validate that the module is executed on changes performed in `integrations/**`.
- [x] Validate that the workflow can be executed manually.
- [x] Add paths to the API tier 2 integration tests.
- [x] Exclude RBAC integration tests path from API tier 0/1 and 2

**Comment by GGP1** [comment]
## Update

Updated the AIT tier 0 and 1 paths and bumped the versions of the github actions used.
