### ISSUE TITLE
Update cluster tasks and threads

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#25648]
## Description

Currently, the nodes from the cluster synchronize files, agent and groups data using periodic tasks and communicating via TCP. In 5.0, the data persistence is now delegated to a set of indexing nodes and these operations are no longer necessary.

As a consequence, the tasks that were in charge of sharing wazuh-db data between nodes will be removed, leaving only keep alive signals and the synchronization of group files.

This issue aims to apply these changes to the cluster code, leaving it operational even after their removal.

### Cluster tasks

| Task | Description | Status |
| --- | --- | --- |
| Integrity-check | Calculates the hash of all the files to be synchronized | ✏️  |
| Integrity-sync | Synchronizes agent, groups, rules, decoders, CDB lists and other files | ✏️ |
| Agent-info sync | Synchronizes the agents' last keepalives and operating system information | ❌ |
| Agent-groups send | Synchronizes new wazuh-db agent groups | ❌ |
| Agent-groups send full | Synchronizes all wazuh-db agents groups information | ❌ |

### Cluster threads

| Name | Node | Description | Status |
| --- | --- | --- |  --- |
| Keep alive - send to master | Worker | Used to consider a node as disconnected from the cluster | ✔️ |
| Integrity sync | Worker | Integrity information synchronization between master and worker nodes | ✏️ |
| Agent info sync | Worker | Synchronize agent last keepalives and operating system information | ❌ |
| Keep alive - check workers | Master | Used to consider a node as disconnected from the cluster | ✔️ |
| Agent groups send | Master | Synchronize agent groups information | ❌  |
| Local agent-groups | Master | Periodically asks information about the agent groups to wazuh-db | ❌ |
| Local integrity | Master | Periodically reads all its integrity files and calculates their checksums |  ✏️ |
| Sendsync | Master | Allows redirection of messages coming from worker nodes to master services | ❌ |
| DAPI | Both | It's used to receive API requests and forward them to the most suitable node to process the request | ✔️ |

#### Legend

|Symbol|Meaning|
|:-:|--|
| ✔️ | Keep |
| ❌ | Remove |
| ✏️ | Needs modifications |
| | Currently N/A |

### Tasks

- [x] Remove legacy tasks and threads.
- [x] Update `Integrity check` and `Integrity sync` to work with group files only.
- [x] Remove the `cluster_control` binary.
- [x] Validate that the cluster is still operational and performing the remaining tasks successfully.

**Comment by GGP1** [comment]
## Update

- Removed the 'agent-info sync' task
- Removed the 'agent-groups send' task
- Removed the 'agent-groups send full' task
- Removed references to wazuh-db in the cluster
- Removed the sendsync command
- Updated the 'Integrity-sync' task to synchronize group files only

**Comment by GGP1** [comment]
## Update

Validated that the cluster behaved as expected after the changes.

**Comment by GGP1** [comment]
## Update

Applied suggested changes.
