### ISSUE TITLE
Synchronize JWT tokens signing key between cluster nodes

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#25651]
## Description

Wazuh 5.0 will introduce a new API for the communication between server nodes and agents.

This API uses JWT tokens as an authentication mechanism and requires all nodes to share the same key for a request to be handled by any node. Otherwise, the token signed by node A would be rejected on validation by the node B.

Similarly, the management API will be exposed behind a load balancer, and we currently don't support distributed calls since each node has a different key.

This issue aims to implement the synchronization of the JWT signing key between the nodes in a cluster.

## Tasks

- [x] On the master node start, check if the signing key is present and generate it if it's not.
- [x] On worker nodes start, calculate signing key hash and compare the results with the master node.
- [x] If there is any difference, synchronize the JWT signing key.
- [x] Validate that all nodes in the cluster have the same key.

**Comment by GGP1** [comment]
## Update

Unified the keys used to sign JWT tokens in both APIs, moved the key pair functions to the framework, made the changes to create a key pair on the master node startup and synchronize it with the workers in the Integrity sync task.

**Comment by GGP1** [comment]
## Update

Applied suggested changes.

**Comment by GGP1** [comment]
## Update

Applied suggested changes.
