### ISSUE TITLE
Replace cluster nodes communications pre-shared key with TLS

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#25650]
## Description

The current cluster communication security scheme has many [caveats](https://github.com/wazuh/wazuh/issues/25228#issuecomment-2310859042). In the new implementation, we should remove the Fernet key and use TLS by default (preferrably >=1.3), moving the encryption from the cluster logic to between the transport and application layers.

We should generate new certificates for each node signed by the root CA during the [deployment](https://documentation.wazuh.com/current/user-manual/wazuh-indexer/certificates.html).

Certificate/key pairs used by all nodes must be signed by the same root CA, this will be validated during every connection initialization, if the validation fails, the node will reject the connection.

This way, the nodes will use the counterpart public key to securely exchange the session key that will be used to encrypt the rest of the communication, offering us data encryption, data integrity and authentication.

> [!Note]
> Related investigation and comparison with the previous scheme: https://github.com/wazuh/wazuh/issues/25228#issuecomment-2310859042

### Private key pair

For the private key pair, it may be appropiate to change the key length used to 3072 or 4096, or even using the [Elliptic Curve Digital Signature Algorithm](https://en.wikipedia.org/wiki/Elliptic_Curve_Digital_Signature_Algorithm). Currently, the generation is done with 2048-bit RSA keys, which provide an acceptable security until 2030, as per NIST.

> [!Important]
> Users should be able to specify a password to encrypt the key file, as well as options to specify the cipher suites, whether to match the peer [cert’s hostname](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.check_hostname), etc.

### TLS version

TLS 1.3 is preferred over any of its previous versions as it only supports the more efficient and secure authenticated ciphers. 

It also removes optional data compression, a feature that enabled the [CRIME attack](https://en.wikipedia.org/wiki/CRIME) on version 1.2.

Furthermore, it brings new features that make the connections more secure and efficient: downgrade protection, single round-trip handshakes and session resumption.

## Tasks

- [x] Remove all references to `ssl_enabled` and `fernet_key`.
- [x] Remove the code used to encrypt the communication between the nodes.
- [x] Add parameters to specify an alternative certificates path.
- [x] Implement SSL on all TCP connections, using a configured set of keys and certificates.
- [x] Validate that the communication between the nodes is completely encrypted and does not leak any details.
- [x] Validate that trying to connect a node with a certificate signed by a different authority is not allowed.

**Comment by GGP1** [comment]
## Update

- Made changes to use SSL by default in cluster communications
- Removed of the fernet key, used to encrypt messages
- Added SSL configurations for custom certificates, keys and key file password
- Updated unit tests

**Comment by GGP1** [comment]
## Update

- Removed deprecated exceptions
- Added the path to the CA file
- Created certificates and keys to test the communication locally
- Validated that the nodes' communications is completely encrypted using TLS v1.3

**Comment by GGP1** [comment]
## Update

Applied suggested changes.
