### ISSUE TITLE
Migrate the `Packages_builder_solaris` and  `Packages_builder_special` pipeline to GHA

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh#25683]
| Objective |
|---|
| https://github.com/wazuh/wazuh-packages/issues/2904 | 

## Description
Because of the `Wazuh packages redesign tier 2` objective we need to migrate the `Packages_builder_solaris` and 
`Packages_builder_special` pipeline to a GHA.

## Tasks
- [x] Replicate the `Packages_builder_solaris`  from the Jenkins pipeline to GHA.
  - [x] Solaris Intel: https://github.com/wazuh/wazuh/issues/26197
- [x] Replicate the `Packages_builder_special`  from the Jenkins pipeline to GHA.
  - [x] HP-UX: https://github.com/wazuh/wazuh/issues/25795
  - [x] AIX: https://github.com/wazuh/wazuh/issues/26096
  - [x] Solaris SPARC: https://github.com/wazuh/wazuh/issues/26220
- [x] Test the pipeline migrated and provide evidence.
- [x] Backport every commit to 4.10.0
  - https://github.com/wazuh/wazuh-agent-packages/pull/125
  - https://github.com/wazuh/wazuh/pull/26482

# Test

# Tested Solaris SPARC workflow 
- Solaris 10 
  - `is_stage`: https://github.com/wazuh/wazuh-agent-packages/actions/runs/11454705290 🟢
  - `checksum`: https://github.com/wazuh/wazuh-agent-packages/actions/runs/11445677249 🟢 
- Solaris 11 
  - `is_stage`: https://github.com/wazuh/wazuh-agent-packages/actions/runs/11400047178 🟢  
  - `checksum`: https://github.com/wazuh/wazuh-agent-packages/actions/runs/11404745987 🟢 

# Tested Solaris i386 workflow 
- Solaris 10  
  - `is_stage`: https://github.com/wazuh/wazuh-agent-packages/actions/runs/11405321564 🟢 
  - `checksum`: https://github.com/wazuh/wazuh-agent-packages/actions/runs/11405327561 🟢 
- Solaris 11 
  - `is_stage`: https://github.com/wazuh/wazuh-agent-packages/actions/runs/11405320919 🟢 
  - `checksum`: https://github.com/wazuh/wazuh-agent-packages/actions/runs/11405328314 🟢 

# Tested AIX workflow 
- `is_stage`: https://github.com/wazuh/wazuh-agent-packages/actions/runs/11400044901 🟢 
- `checksum`: https://github.com/wazuh/wazuh-agent-packages/actions/runs/11404744270 🟢 

# Tested HP-UX workflow 
- `is_stage`: https://github.com/wazuh/wazuh-agent-packages/actions/runs/11400043824 🟢 
- `checksum`: (Not needed, changes with this parameters is no difference with other systems)

**Comment by jnasselle** [comment]
# Update

After a meeting with @jotacarma90 , we agreed to attempt to follow the next steps regarding to workflow segmentations and inputs

- HP-UX
  - workflow:  packages-build-hp-ux-agent.yml
  - parameters:
     - common ones: is_stage, checksum, source_reference, id
     - ssh: port, host, pass 
- AIX
  - workflow:  packages-build-aix-agent.yml
  - parameters:
     - common ones: is_stage, checksum, source_reference, id
     - ssh: port, host, pass 
 - Solaris 10 and 11 with SPARC arch
   - workflow:  packages-build-solaris-agent-sparc.yml
   - parameters:
     - common ones: is_stage, checksum, source_reference, id
     - os selector: os _version
     - ssh: port, host, pass    
- Solaris 10 and 11 with i386 arch
   - workflow:  packages-build-solaris-agent-i386.yml
   - parameters:
     - common ones: is_stage, checksum, source_reference, id
     - os selector: os _version
