### ISSUE TITLE
Engine - Error when using definitions as target field in helper function

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#25706]
### Description:

There is a bug when using `definitions` as the target field in a helper function, leading to a validation failure. The following example demonstrates the issue:
```yml
definitions:
  excluded_parents_name: ["some_name"]

check: >-
    array_contains($excluded_parents_name, any_name)
```

During the validation process, this code fails. After debugging, the problem was traced to the `checkExpressionBuilder` method, where the following logic is used:
```cpp
try
{
    // Apply definitions
    auto replacedExpr = buildCtx->definitions().replace(logicExpr);
    // TODO: make a factory and inject this dependency
    evaluator = logicexpr::buildDijstraEvaluator<base::Event, parsers::HelperToken>(
        replacedExpr, getTermBuilder(buildCtx), parsers::getTermParser());
}
catch (const std::exception& e)
{
    throw std::runtime_error(fmt::format("Stage 'check' failed to build expression '{}': {}", logicExpr, e.what()));
}
```
hen the `definitions` are replaced, the expression becomes:
```
array_not_contains(["some_name"], any_name)
```

This replacement is passed to the `termParser()` method within the Tokenizer class, where the parser evaluates:
```cpp
auto res = m_termParser(sv, pos);
```
At this point, `sv` holds the string:
```
"array_contains([\"some_name\"], any_name)"
```

The relevant parser is:
```cpp
inline parsec::Parser<HelperToken> assertTargetMonadic(const HelperToken& helperToken)
{
    return [helperToken](auto sv, auto pos) -> parsec::Result<HelperToken>
    {
        if (helperToken.args.size() < 1)
        {
            return parsec::makeError<HelperToken>("At least one argument with target field expected", pos);
        }

        if (!helperToken.args[0]->isReference())
        {
            return parsec::makeError<HelperToken>("First argument must be a reference to target field", pos);
        }

        HelperToken next;
        next.name = helperToken.name;
        next.targetField = builders::Reference(*std::static_pointer_cast<builders::Reference>(helperToken.args[0]));
        next.args = std::vector<builders::OpArg>(helperToken.args.begin() + 1, helperToken.args.end());

        return parsec::makeSuccess<HelperToken>(std::move(next), pos);
    };
}
```

The issue occurs at the following check:
```cpp
if (!helperToken.args[0]->isReference())
```

Since the `definitions` have been substituted with a value (i.e., `["some_name"]`), this condition evaluates to `true`, causing the expression to fail validation, and the error `"Unexpected token"` is returned.

### Impact:
This bug prevents the use of `definitions` as target fields in helper functions like `array_contains` and `array_not_contains`, impacting the ability to validate such expressions.

### Steps to Reproduce:
1. Define a `definitions` block with a value.
2. Use the `definitions` value in a helper function (e.g., `array_contains` or `array_not_contains`) within a `check` expression.
3. Attempt validation.
4. Observe the validation failure with an "Unexpected token" error.

### Expected Behavior:
Helper functions should correctly handle `definitions` as target fields without validation errors.

### Tasks:
- [ ] Investigate and resolve the issue with `definitions` substitution in helper functions.
- [ ] Ensure `definitions` are correctly handled as target fields in helper functions like `array_contains` and `array_not_contains`.
- [ ] Add unit tests for helper functions in the filter category, particularly for `array_contains` and `array_not_contains` when using `definitions`.
