### ISSUE TITLE
Migrate HP-UX generation script and workflow to GHA

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#25795]
# Description

Epic issue: https://github.com/wazuh/wazuh/issues/25683

This issue is for the specific migration of the HP-UX workflow and package generation script.

## Tasks
- [x] Migrate and adapt script generation `generate_wazuh_packages.sh` from wazuh-packages to wazuh/wazuh.
  - https://github.com/wazuh/wazuh/pull/25794  
- [x] Migrate pipeline to generate HP-UX package from wazuh-jenkins to wazuh-agent-packages.
  - https://github.com/wazuh/wazuh-agent-packages/pull/94
- [x] Test the full flow for HP-UX generation.

## Tested workflow 🟢 
https://github.com/wazuh/wazuh-agent-packages/actions/runs/10992801184/job/30517925619

**Comment by jotacarma90** [comment]
# Update 19/09/2024
- Analyzing the compilation error. The problem was the compilation of the antitampering.
- Created issue/PR for the urgent upgrade to 4.10.0 for AIX HP-UX package generation.
  - https://github.com/wazuh/wazuh/issues/25789
  - https://github.com/wazuh/wazuh/pull/25791
- Last modifications to the HP-UX generation workflow.
- Converted the migration issue to epica, and created this same issue to specifically work on HP-UX.
