### ISSUE TITLE
Use a cluster by default

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#25895]
## Description

From v5.0 onwards, every Wazuh installation will run a cluster, regardless of whether there is a single node or many.

In addition to that, the default `bind_addr` will be `localhost` instead of `0.0.0.0` for security reasons.

This issue aims to make the modifications necessary to the cluster source code to fulfill these requirements.

## Tasks

- [x] Remove the `cluster.disabled` and `cluster.name` configuration options.
- [x] Remove all references to the cluster status and name.
- [x] Change the bind address from `0.0.0.0` to `localhost`.
- [x] Validate that the nodes operate as if they were in a cluster by default.

**Comment by GGP1** [comment]
## Update

Made the modifications to use a cluster and bind the address to `localhost` by default, and removed all references to the cluster name and status.

**Comment by GGP1** [comment]
## Update

Validated that the cluster is enabled by default and that not specifying a `bind_addr` makes the server listen on localhost.

**Comment by GGP1** [comment]
## Update

Applied suggested changes.

**Comment by GGP1** [comment]
## Update

Applied suggested changes.

**Comment by GGP1** [comment]
## Update

Rebased the branch to master and solved conflicts

**Comment by GGP1** [comment]
## Update

Rebased the branch to master and solved conflicts.
