### ISSUE TITLE
Develop a WPK Package for Wazuh Agent on macOS with Apple Silicon

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#25976]
## Description

Wazuh supports a remote agent upgrade system through the manager, utilizing a custom package format called WPK. While the Wazuh agent for macOS has been supported on both Intel and Apple Silicon (arm64) architectures for several versions, a WPK package for macOS on Apple Silicon is still missing.

## Definition of Done

- Ability to generate WPK packages for macOS (arm64).
- Upgrade module supports macOS agents on arm64.
- WPK packages for macOS (arm64) are uploaded to the repository alongside other packages.
- Documentation is updated to reflect the changes.

## Tasks

- [x] https://github.com/wazuh/wazuh/issues/25977
- [x] https://github.com/wazuh/wazuh/issues/18541
- [x] https://github.com/wazuh/wazuh-documentation/issues/7813
- [x] Test remote upgrades for macOS agents on arm64.
- [x] Test upgrades for Apple Silicon agents that previously had Intel versions installed.

**Comment by y0d4a** [comment]
any ETA for this?
tnx.

**Comment by mjcr99** [comment]
## Update
**(28/10/2024)** Making a test to fully ensure the manager can locate the new WPK file when required.
