### ISSUE TITLE
Implement commands sending to Indexer

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#26077]
|Epic|
|---|
| https://github.com/wazuh/wazuh-indexer/issues/349 |

## Description

In https://github.com/wazuh/wazuh/issues/24711, the Management API structure was modified for the necessary changes related to the command creation for agent restart. The current issue aims to develop the rest of the logic related to sending commands to the Command Manager API for it to be able to continue with the commands workflow, taking the use case mentioned before as an example to test.

## Tasks
- [x] Develop the command sending logic so it is reusable, modular, and extensible. This involves the command generation in the indexer for the agents' group assignment use case initially carried out in https://github.com/wazuh/wazuh/issues/25122.
- [x] Apply the necessary changes to the `PUT /agents/<agent_uuid>/restart` related code to use the command sending logic and send the restart command to the Command Manager API.
- [x] Develop the necessary unit tests.
- [x] Define the test cases for future integration tests.

**Comment by GGP1** [comment]
## Update

- Reviewed the Indexer team REST API development
- Updated command models
- Added the create method to the indexer commands module
- Renamed the commands index to commands manager
- Created and updated unit tests
- Changed the agent restart endpoint logic

I have yet to install the plugin in the environment, test that everything works as expected and define the test cases for future integration tests.

**Comment by GGP1** [comment]
## Update

Configured the environment to include the `setup` and `command-manager` Wazuh plugins. However, when I tried to create commands using the URL `/_plugins/_commandmanager'` I get an error saying that there's no handler for that endpoint

```console
[opensearch@wazuh-indexer ~]$ curl -X POST -H "Content-Type: application/json" -ku admin:SecretPassword1% http://localhost:9200/_plugins/_commandmanager
{"error":"no handler found for uri [/_plugins/_commandmanager] and method [POST]"}
```

I will contact the Indexer team to validate why isn't the plugin working.

**Comment by GGP1** [comment]
## Update

I was able to test the endpoint after [building](https://github.com/wazuh/wazuh-indexer/actions/runs/11365652178) the packages with the command manager plugin latest branch. I changed some things from the logic to adapt to the changes from the Indexer team.

### Integration test cases

1. Restart one agent
2. Restart multiple agents
3. Restart all agents
4. Try to restart an agent with an invalid ID
