### ISSUE TITLE
Migrate AIX generation script and workflow to GHA from Jenkins

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#26096]
# Description

Epic issue: https://github.com/wazuh/wazuh/issues/25683
Specific resources issue: https://github.com/wazuh/wazuh-automation/issues/1838

This issue is for the specific migration of the AIX workflow and package generation script.

## Tasks

- [x] Migrate and adapt AIX script generation `generate_wazuh_packages.sh` from wazuh-packages to wazuh/wazuh.
- [x] Migrate pipeline to generate AIX package from wazuh-jenkins to wazuh-agent-packages.
- [x] Test the full flow for AIX generation.

# Tested workflow 🟢 
- is_stage: https://github.com/wazuh/wazuh-agent-packages/actions/runs/11179779744/job/31080127651
- checksum: https://github.com/wazuh/wazuh-agent-packages/actions/runs/11180541735/job/31082501742
- Precompiled cmake uploaded: https://github.com/wazuh/wazuh-agent-packages/actions/runs/11230033171/job/31216621601
- HP-UX workflow after merge workflows AIX and HP-UX: https://github.com/wazuh/wazuh-agent-packages/actions/runs/11230733124/job/31218657452

## Test manual installation Package AIX 6.1 🟢 
- Install and start: 
```
bash-4.4# WAZUH_MANAGER="10.0.0.2" rpm -i wazuh-agent-4.10.1-1.aix6.1.ppc.rpm
bash-4.4# /var/ossec/bin/wazuh-control start
Starting Wazuh v4.10.1...
Started wazuh-execd...
Started wazuh-agentd...
Started wazuh-syscheckd...
Started wazuh-logcollector...
Started wazuh-modulesd...
Completed.
```

## Test manual installation Package AIX 7.3 🟢 

- Install Wazuh:
```
bash-5.2# WAZUH_MANAGER="10.0.0.2" rpm -ivh wazuh-agent-4.10.1-1.aix6.1.ppc.rpm
warning: RPM v3 packages are deprecated: wazuh-agent-4.10.1-1.ppc
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
warning: RPM v3 packages are deprecated: wazuh-agent-4.10.1-1.ppc
Updating / installing...
   1:wazuh-agent-4.10.1-1             ################################# [100%]
```

- Start error:
```
bash-5.2# /var/ossec/bin/wazuh-control restart
exec(): 0509-036 Cannot load program /var/ossec/bin/wazuh-execd because of the following errors:
        0509-022 Cannot load module /var/ossec/lib/libwazuhext.so.
        0509-150   Dependent module /var/ossec/lib/libatomic.a(libatomic.so.1) could not be loaded.
        0509-103   The module has an invalid magic number.
```
- Download libgcc 12 oficial from here: 
https://public.dhe.ibm.com/aix/freeSoftware/aixtoolbox/RPMS/ppc-7.3/gcc12/libgcc12-12.3.0-1.aix7.3.ppc.rpm
- Install:
```
bash-5.2# rpm -i libgcc12-12.3.0-1.aix7.3.ppc.rpm
```
- Copy to `/var/ossec/lib`:
```
bash-5.2# cp /opt/freeware/lib/gcc/powerpc-ibm-aix7.3.0.0/12/libatomic.a /var/ossec/lib/
```
- Restart Wazuh:
```
bash-5.2# /var/ossec/bin/wazuh-control restart
wazuh-modulesd not running...
wazuh-logcollector not running...
wazuh-syscheckd not running...
wazuh-agentd not running...
wazuh-execd not running...
Wazuh v4.10.1 Stopped
Starting Wazuh v4.10.1...
Started wazuh-execd...
Started wazuh-agentd...
Started wazuh-syscheckd...
Started wazuh-logcollector...
Started wazuh-modulesd...
Completed.
```

**Comment by jotacarma90** [comment]
# Update 02/10/2024
- VM AIX requested: https://github.com/wazuh/wazuh-automation/issues/1838
- Tests on AIX 7.3, could not compile correctly, we switch to AIX 6.1.
- Dependencies correctly installed.
- Compilation successful and package correctly generated.
- Testing if it is possible to upload already compiled gmake to packages-dev.wazuh to save time in the process.
- Working branch for both repositories: `enhancement/26096-migrate-aix-package-generation`
