### ISSUE TITLE
Change the instantiation of Thread Dispatch Queue and update logs

### ISSUE THREAD

**Issue by NahuFigueroa97** [wazuh/wazuh#26126]
## Description

Currently, the thread count value is used to set the maximum queue size, which causes issues when sending events. This change was made in this PR https://github.com/wazuh/wazuh/pull/25267

Specifically when instantiating the dispatcher 
https://github.com/wazuh/wazuh/blob/340e45c5017fc5e137e61f1a1681cc2f65954982/src/engine/source/indexerconnector/src/indexerConnector.cpp#L136-L195 the error occurred when setting the number of threads in the position of the maximum queue size. This causes issues when pushing events to the queue.

The TThreadEventDispatcher constructor expects this order:
https://github.com/wazuh/wazuh/blob/340e45c5017fc5e137e61f1a1681cc2f65954982/src/engine/source/base/include/base/utils/threadEventDispatcher.hpp#L73-L83

In this section of code https://github.com/wazuh/wazuh/blob/b4696f5fae2fa5ad01e9cfc4c4297625c3616784/src/engine/source/base/include/base/utils/threadEventDispatcher.hpp#L104-L110 at the beginning the condition `UNLIMITED_QUEUE_SIZE == m_maxQueueSize` is not met since m_maxQueueSize saves the number of threads but the condition `m_queue->size(prefix) < m_maxQueueSize` is met therefore the event is pushed. The problem appears when pushing a second event since neither the first nor the second condition are met since **m_queue->size(prefix) is not less than m_maxQueueSize** resulting in lost events

There are also logs within the dispatcher initialization that are wrong: https://github.com/wazuh/wazuh/blob/340e45c5017fc5e137e61f1a1681cc2f65954982/src/engine/source/indexerconnector/src/indexerConnector.cpp#L183-L189 

## Task

- [x] Make the required change
- [x] Add tests to verify that multiple events can be pushed to the queue
- [x] Fix badly formatted logs

**Comment by MiguelazoDS** [comment]
I did the changes, although I'm not sure about some of the items in the DoD. 

- The required changes are applied.
- The test are already implemented, the issue was in the production code, not in the tests.
- I use named parameters approach for the conditional "bulkData.empty()".
