### ISSUE TITLE
Migrate Solaris 10/11 (i386) generation script and workflow from Jenkins to GHA

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#26197]
# Description

Epic issue: https://github.com/wazuh/wazuh/issues/25683

This issue is for the specific migration of the Solaris 10/11 (i386) workflow and package generation script.

## Tasks

- [x] Migrate and adapt Solaris 10/11 (i386) script generation `generate_wazuh_packages.sh` from wazuh-packages to wazuh/wazuh.
- [x] Migrate pipeline to generate Solaris 10/11 (i386) package from wazuh-jenkins to wazuh-agent-packages.
- [x] Test the full flow for Solaris 10/11 (i386) generation.

# Tested workflow  
- Solaris 10 
  - `is_stage`: https://github.com/wazuh/wazuh-agent-packages/actions/runs/11454705290 🟢
  - `checksum`: https://github.com/wazuh/wazuh-agent-packages/actions/runs/11445677249 🟢 
- Solaris 11 
  - `is_stage`: https://github.com/wazuh/wazuh-agent-packages/actions/runs/11405320919 🟢
  - `checksum`: https://github.com/wazuh/wazuh-agent-packages/actions/runs/11405328314 🟢
