### ISSUE TITLE
Migrate Solaris 10/11 (SPARC) generation script and workflow from Jenkins to GHA

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#26220]
# Description

Epic issue: https://github.com/wazuh/wazuh/issues/25683

This issue is for the specific migration of the Solaris 10/11 (SPARC) workflow and package generation script.

## Tasks

- [ ] Migrate and adapt Solaris 10/11 (SPARC) script generation `generate_wazuh_packages.sh` from wazuh-packages to wazuh/wazuh.
- [ ] Migrate pipeline to generate Solaris 10/11 (SPARC) package from wazuh-jenkins to wazuh-agent-packages.
- [ ] Test the full flow for Solaris 10/11 (SPARC) generation.

# Tested workflow 🟡 
-

**Comment by jotacarma90** [comment]
# Update 08/10/2024
- Analyzing the package generation format for SPARC.
- Preparing branches.
