### ISSUE TITLE
Post release tasks for 4.9.1

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#26361]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.9.1.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.9.1-into-4.10.0`.

## Tasks

- [x] https://github.com/wazuh/wazuh/pull/26369
- [x] https://github.com/wazuh/wazuh/pull/26375
- [x] https://github.com/wazuh/wazuh/pull/26381
- [x] Publish GitHub release as latest.
- [x] Delete all stage pre-releases for 4.9.1 (https://github.com/wazuh/wazuh/releases).
- [x] Delete all stage tags for v4.9.1. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.9.1-rc1, 4.9.1-alpha1, etc.
