### ISSUE TITLE
Make new API in Python ready for production use

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#2640]
Reimplementation of every old nodejs-based endpoints to the new framework.

Sections to reimplement in this issue:
- [x] Default (root endpoint to get API info) #2967 
- [x] Active Response #2836
- [x] Agents #2835 
- [x] Cache. Finally, cache endpoints will not be considered. However cache will be kept, as explained in #2924 
- [x] CIS-CAT #2840
- [x] Cluster #2845
- [x] Cluster config on demand #3121 
- [x] Decoders #2848
- [x] Experimental #2957
- [x] Lists #3255
- [x] Manager #2858
- [x] ~Rootcheck (Deprecated in 4.0, #3308)~
- [x] Rules #2868
- [x] Security #3280 
- [x] Summary #3879 
- [x] Syscheck #2906
- [x] Syscollector #2907
- [x] SCA #3243

**Comment by vicferpoy** [comment]
For testing purposes, we have a really long `auth_token_exp_timeout` (authentication token expiration timeout). As soon as this is ready for production, we need to change it to **900** seconds. This parameter can be found in:

- api/api/**configuration.py**
- api/api/configuration/**api.yaml**
- api/api/spec/**spec.yaml** _(x3)_
- api/scripts/**migration.py**
- api/test/integration/env/configurations/base/manager/**api.yaml**
- api/test/integration/**test_cluster_endpoints.tavern.yaml**
