### ISSUE TITLE
Engine - Enhance error handling in Indexer-Connector module

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#26560]
### Description:
The current implementation of the indexer-connector module in Wazuh-Engine fails to accurately identify and log individual document indexing errors when using the bulk operation in OpenSearch. While the server may respond with a general HTTP 201 status, individual entries within the bulk request may fail without being properly reported. This issue aims to refine the error handling process to ensure that any indexing errors are clearly logged, including warnings with detailed information about the documents that failed to index.

### Objectives:
- Improve error detection in the bulk indexing process of the indexer-connector module.
- Ensure detailed error messages are logged, including specific document data that failed during the indexing process.

### Tasks:
1. **Assess Current Bulk Handling**: Review the current bulk request handling mechanism to understand how responses are processed.
2. **Implement Error Parsing**: Enhance the response parsing logic to iterate through the response array and identify any errors in individual document submissions.
3. **Log Detailed Warnings**: Implement logging that includes detailed warnings for each failed document, ensuring that the document content or identifier is part of the warning message.
4. **Testing and Validation**: Conduct thorough testing to ensure that the new error handling mechanism accurately captures and logs all indexing errors.
5. **Documentation**: Update the documentation to reflect the changes in error handling and logging for the indexer-connector module.

### Expected Outcome:
- A more robust indexer-connector module that can identify and log detailed errors for each document in a bulk indexing operation, enhancing troubleshooting and monitoring of indexing processes.

### DoD (Definition of Done):
- [ ] The indexer-connector's bulk indexing response handling is capable of detecting and logging individual document errors.
- [ ] Detailed warning logs are implemented and show precise information about the documents that failed to index.
- [ ] All modifications are thoroughly tested with various indexing scenarios.
- [ ] The module's documentation is updated to include information on the new error handling capabilities.

This enhancement will significantly improve the operational transparency of the indexing process in Wazuh-Engine, aiding in quicker identification and resolution of issues related to document indexing in OpenSearch.

**Comment by JcabreraC** [comment]
### Log examples:
- Event 1:
```json
{
  "timestamp": "2018-10-03T14:42:44.836744+0000",
  "flow_id": 2191386088856669,
  "in_iface": "enp0s3",
  "event_type": "alert",
  "src_ip": "192.168.1.146",
  "src_port": 32858,
  "dest_ip": "89.160.20.112",
  "dest_port": 80,
  "proto": "TCP",
  "tx_id": 0,
  "alert": {
    "action": "allowed",
    "gid": 1,
    "signature_id": 2013028,
    "rev": 4,
    "signature": "ET POLICY curl User-Agent Outbound",
    "category": "Attempted Information Leak",
    "severity": 2
  },
  "http": {
    "hostname": "example.net",
    "url": "/",
    "http_user_agent": "curl/7.58.0",
    "http_content_type": "text/html",
    "http_method": "GET",
    "protocol": "HTTP/1.1",
    "status": 200,
    "length": 1121
  },
  "app_proto": "http",
  "flow": {
    "pkts_toserver": 4,
    "pkts_toclient": 3,
    "bytes_toserver": 347,
    "bytes_toclient": 1654,
    "start": "2018-10-03T14:42:44.613469+0000"
  }
}
```

- Event 2:
```json
{
  "timestamp": "2018-10-03T16:16:26.711841+0000",
  "flow_id": 678269478904081,
  "in_iface": "enp0s3",
  "event_type": "alert",
  "src_ip": "192.168.1.146",
  "src_port": 32864,
  "dest_ip": "89.160.20.112",
  "dest_port": 80,
  "proto": "TCP",
  "tx_id": 0,
  "alert": {
    "action": "allowed",
    "gid": 1,
    "signature_id": 2013028,
    "rev": 4,
    "signature": "ET POLICY curl User-Agent Outbound",
    "category": "Attempted Information Leak",
    "severity": 2
  },
  "http": {
    "hostname": "example.net",
    "url": "/",
    "http_user_agent": "curl/7.58.0",
    "http_content_type": "text/html",
    "http_method": "GET",
    "protocol": "HTTP/1.1",
    "status": 200,
    "length": 1121
  },
  "app_proto": "http",
  "flow": {
    "pkts_toserver": 4,
    "pkts_toclient": 3,
    "bytes_toserver": 347,
    "bytes_toclient": "non-integer",
    "start": "2018-10-03T16:16:26.467217+0000"
  }
}
```

### Actual log:
```
2024-10-15 17:34:54.345 59173:59563 indexerConnector.cpp:164 at operator()::<lambda>handleSuccessfulPostResponse(): debug: Response: {"took":5055,"errors":true,"items":[{"index":{"_index":"test-basic-index","_id":"1bQ_kZIBmzjx6FV-K3nH","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":36,"_primary_term":1,"status":201}},{"index":{"_index":"test-basic-index","_id":"1rQ_kZIBmzjx6FV-K3nH","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse field [suricata.flow.bytes_toclient] of type [long] in document with id '1rQ_kZIBmzjx6FV-K3nH'. Preview of field's value: 'non-integer'","caused_by":{"type":"illegal_argument_exception","reason":"For input string: \"non-integer\""}}}}]
``` 

Since you are currently logging in, we cannot determine whether an indexing error occurred or identify the specific event that caused it. The 201 status should be logged at the trace level, while the 400 status should be logged as a warning.

The goal is to maintain a log of events that led to the indexing error.

**Comment by GabrielEValenzuela** [comment]
# Update

- Logic implemented. Pending add UTs and check with IT. 
- We align with div3 and store the events in a file
- We log the id of the document and errorReason

**Comment by GabrielEValenzuela** [comment]
# Update

- UT and development done. PR is in draft and open to any suggestions.
- Pending test with Opensearch

**Comment by GabrielEValenzuela** [comment]
# Update

- Refactoring based on the requested changes done. 
- I made a rebase with the last commits of the target branch
- Change UTs and fix them if it was necessary
- Pending review

**Comment by GabrielEValenzuela** [comment]
# Update

- Change order headers
- Remove unused variable
- Add UT for querybuilder

**Comment by sebasfalcone** [comment]
## ETA update
Issue awaiting review

**Comment by sebasfalcone** [comment]
## ETA update
Updated to accommodate for reviews

**Comment by GabrielEValenzuela** [comment]
# Update

- Improve code and UTs
- Fix some bugs

**Comment by GabrielEValenzuela** [comment]
# Update

- Minor changes related to the logic
- In review

**Comment by GabrielEValenzuela** [comment]
# Update

- Rebase and package generation

**Comment by GabrielEValenzuela** [comment]
# Update

- Improve constness and fix typo

**Comment by sebasfalcone** [comment]
## ETA update
@GabrielEValenzuela is out of office, we are going to retake this task with @pereyra-m

**Comment by pereyra-m** [comment]
## Update

I apply review changes.

**Comment by pereyra-m** [comment]
## Update

Extra changes in the PR related to the review

**Comment by GabrielEValenzuela** [comment]
#Update 

- Rebase branch
- Testing

**Comment by pereyra-m** [comment]
@Dwordcito 

If you consider that this implementation should be re-designed, you could move it to backlog again so we can find a different approach.

**Comment by royy92** [comment]
Hi,

I was reviewing this issue and took a closer look at the current codebase. 
I found that `validateBulkResponse()` in:

`src/shared_modules/indexer_connector/src/indexerConnectorSyncImpl.hpp`

already handles individual document-level errors from bulk responses. It:
- Iterates over the `items` array in the OpenSearch bulk response
- Logs detailed errors per document including operation type, status 
  code, and error reason
- Distinguishes between real failures and acceptable version conflicts

However, there is no documentation explaining what these new warning logs 
look like or how operators should use them for troubleshooting.

I would like to contribute by adding documentation that covers:
- What the new per-document warning logs look like
- How to interpret them during troubleshooting
- Where they appear in the Wazuh logs

Would this be a useful contribution toward closing this issue?

Thanks!
