### ISSUE TITLE
Support new stage RC 1 for 4.9.2 in wazuh repository

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#26576]
## Description

This issue attempts to support a new stage RC 1 for 4.9.2 in the wazuh repository.

## Tasks

- [x] Delete previous Alpha 2 release: https://github.com/wazuh/wazuh/releases/tag/v4.10.0-alpha2.
- [x] Delete previous v4.10.0-alpha2 tag.
- [x] Ensure changelog is updated for 4.9.2 (if applicable).
- [x] Bump revision for branch 4.9.2 on wazuh repository.
- [x] Create tag v4.9.2-rc1 from branch 4.9.2 on wazuh repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh/releases/tag/v4.9.2-rc1.
