### ISSUE TITLE
Post release tasks for 4.9.2

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#26690]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.9.2.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.9.2-into-4.10.0`.

## Tasks

- [ ] Merge branch `4.9.2` into branch `4.10.0`.
- [ ] Merge branch `4.10.0` into branch `4.10.1`.
- [ ] Merge branch `4.10.1` into branch `4.10.2`.
- [ ] Publish GitHub release as latest.
- [ ] Delete all stage pre-releases for 4.9.2 (https://github.com/wazuh/wazuh/releases).
- [ ] Delete all stage tags for v4.9.2. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.9.2-rc1, 4.9.2-alpha1, etc.

**Comment by sebasfalcone** [comment]
## Issue blocked
Due to not signed commits, we cannot continue. We need someone with elevated privileges
