### ISSUE TITLE
Upload Wazuh embedded CPython interpreter - ARM64

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#26714]
### Description
This issue focuses on ensuring the ARM64 architecture is fully supported by uploading the ARM64-compatible CPython interpreter and any related dependencies to our package repository. This will facilitate seamless installations and runtime operations on ARM64 systems, enhancing Wazuh's compatibility and performance on these platforms.

### Objectives
- **CPython Interpreter for ARM64**: Secure that the CPython interpreter and all its required libraries are compiled, tested, and ready for ARM64 architecture.
- **Dependency Upload**: Ensure all ARM64-specific dependencies necessary for Wazuh's operation are available in the package repository.
- **Documentation and Integration**: Update documentation to reflect the availability of these resources and ensure seamless integration with existing processes without modifying installation scripts.

### Tasks
- [x] **Compilation and Testing**: Compile the CPython interpreter and essential dependencies for ARM64, ensuring functionality and optimization for the architecture.
- [x] **Resource Upload**: Upload the compiled resources to the appropriate package repositories or CDN paths.
- [x] **Documentation Update**: Update the documentation to include information on the availability of ARM64 resources and any relevant instructions.

### Expected Challenges
- **Compatibility Issues**: Address any compatibility issues that may arise during the compilation or integration of the CPython interpreter and dependencies for ARM64.
- **Testing Coverage**: Conduct extensive testing across various ARM64 environments to ensure reliability and optimal performance.

### Acceptance Criteria
- The CPython interpreter and all related dependencies must be available and operational for ARM64 platforms within the Wazuh package repositories.
- Documentation must clearly outline any steps or considerations specific to ARM64 installations, ensuring users can deploy Wazuh on this architecture effortlessly.

This issue is critical for expanding Wazuh's support to ARM64 architectures, ensuring users can leverage the full functionality of the platform across a broader range of devices and operating systems.

**Comment by RamosFe** [comment]
## Update - Tests

## Test report

[archive.zip](https://github.com/user-attachments/files/18440146/archive.zip)

## Test results

---
| **Test name** | **Pass** | **XPass** | **Skip** | **XFail** | **Fail** | **Issues Ref.** | **Status** |
|--|--|--|--|--|--|--|--|
| test_active_response_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_agent_GET_endpoints.tavern.yaml | 94 | 0 | 0 | 0 | 1 | - | 🟡  |
| test_cdb_list_endpoints.tavern.yaml | 5 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_cluster_endpoints.tavern.yaml | 49 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_decoder_endpoints.tavern.yaml | 25 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_default_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_logtest_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_mitre_endpoints.tavern.yaml | 7 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_overview_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_active_response_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_cdb_list_endpoints.tavern.yaml | 5 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_decoder_endpoints.tavern.yaml | 6 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_experimental_endpoints.tavern.yaml | 12 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_logtest_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_manager_endpoints.tavern.yaml | 16 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_mitre_endpoints.tavern.yaml | 7 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_overview_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_rootcheck_endpoints.tavern.yaml | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_sca_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_security_endpoints.tavern.yaml | 25 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_syscheck_endpoints.tavern.yaml | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_task_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_active_response_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_agent_endpoints.tavern.yaml | 42 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_all_endpoints.tavern.yaml | 162 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_cluster_endpoints.tavern.yaml | 19 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_logtest_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_overview_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_rule_endpoints.tavern.yaml | 8 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_sca_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rule_endpoints.tavern.yaml | 15 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_security_DELETE_endpoints.tavern.yaml | 15 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_task_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |

### `test_agent_GET_endpoints.tavern.yaml` failed test case



All tests passed locally:

```console
========================================================================================================== test session starts ==========================================================================================================
platform linux -- Python 3.10.12, pytest-7.3.1, pluggy-1.5.0
rootdir: /home/federamos/Documents/Wazuh/Repositories/wazuh/api/test/integration
configfile: pytest.ini
plugins: asyncio-0.18.1, html-2.1.1, metadata-3.1.1, cov-4.1.0, tavern-1.23.5, anyio-4.1.0, trio-0.8.0
asyncio: mode=auto
collected 95 items                                                                                                                                                                                                                      

test_agent_GET_endpoints.tavern.yaml ...............................................................................................                                                                                              [100%]

=========================================================================================================== warnings summary ============================================================================================================
../../../env/lib/python3.10/site-packages/_pytest/nodes.py:642
  /home/federamos/Documents/Wazuh/Repositories/wazuh/env/lib/python3.10/site-packages/_pytest/nodes.py:642: PytestRemovedIn8Warning: The (fspath: py.path.local) argument to YamlFile is deprecated. Please use the (path: pathlib.Path) argument instead.
  See https://docs.pytest.org/en/latest/deprecations.html#fspath-argument-for-node-constructors-replaced-with-pathlib-path
    return super().from_parent(parent=parent, fspath=fspath, path=path, **kw)

test_agent_GET_endpoints.tavern.yaml: 95 warnings
  <frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================================================================== 95 passed, 96 warnings in 784.00s (0:13:03) ==============================================================================================
```

**Comment by javiersanchz** [comment]
## Review

- The tests show that the installation is performed correctly.
- All tests passed successfully, the only test that failed, `test_agent_GET_endpoints.tavern.yaml`, was run locally and also passed successfully.

LGTM!

**Comment by fdalmaup** [comment]
# Review

The issue's goal has not been achieved since it aims to upload the pre-compiled files to a location not yet defined and verify that the Wazuh Manager can be installed for this architecture completely from sources.

**Comment by RamosFe** [comment]
## Update - Makefile Analysis

To obtain the architecture of the system, we could use the following environmental variable. This will allow us to create a condition based on the architecture of the system when installing the `cpython` package.

https://github.com/wazuh/wazuh/blob/2898cb763dfa950523d6a4683ddf6c802c727772/src/Makefile#L1377-L1398

As we can see, there is already a `aarch64` option:

```make
 ifneq (,$(filter ${cpu_arch},aarch64 arm64)) 
 	PRECOMPILED_ARCH := /aarch64 
```


Finally, with this variable, we can create an `if` condition for different operating systems, adding it to the following code segment:

https://github.com/wazuh/wazuh/blob/2898cb763dfa950523d6a4683ddf6c802c727772/src/Makefile#L1463-L1469


To avoid changing the structure where the packages are saved, we can use a different suffix for `aarch64`. This is an example of the implementation:



```make
ifeq (,$(filter ${PYTHON_SOURCE},YES yes y Y 1)) 
ifneq (,$(PRECOMPILED_RES)) 
external/$(CPYTHON).tar.gz: 
ifeq ($(PRECOMPILED_ARCH),/aarch64)
    suffix := arm64
else
    suffix := x86_64
endif
	test -e $(patsubst %.gz,%,$@) ||\ 
	($(CURL) $@ $(RESOURCES_URL)/libraries/sources/$(patsubst external/%,%,$@)_$(suffix).tar.gz &&\ 
	cd external && $(GUNZIP) $(patsubst external/%,%,$@)_$(suffix).tar.gz && $(TAR) $(patsubst external/%.gz,%,$@)_$(suffix).tar && rm $(patsubst external/%.gz,%,$@)_$(suffix).tar) 
	test -d $(patsubst %.tar.gz,%,$@) || (cd external && $(GZIP) $(patsubst external/%.gz,%,$@)_$(suffix).tar))  
```

**Comment by RamosFe** [comment]
## Update - 21/1

I continue fixing errors when trying to install the dependencies on an ARM64 machine.

**Comment by RamosFe** [comment]
## Update - 23/1

### `make deps`

```console
make deps TERGET=server
…
(curl -so external/cpython_arm64.tar.gz https://packages.wazuh.com/deps/40/libraries/sources/cpython_arm64.tar.gz &&\
cd external && gunzip cpython_arm64.tar.gz && tar -xf cpython_arm64.tar && rm cpython_arm64.tar)
curl -so external/jemalloc.tar.gz https://packages.wazuh.com/deps/40/libraries/linux/aarch64/jemalloc.tar.gz || true
cd external && test -e jemalloc.tar.gz && gunzip jemalloc.tar.gz || true
cd external && test -e jemalloc.tar && tar -xf jemalloc.tar || true
test -e external/jemalloc.tar && rm external/jemalloc.tar || true
test -d external/jemalloc ||\
(curl -so external/jemalloc.tar.gz https://packages.wazuh.com/deps/40/libraries/sources/jemalloc.tar.gz &&\
cd external && gunzip jemalloc.tar.gz && tar -xf jemalloc.tar && rm jemalloc.tar)
curl -so external/flatbuffers.tar.gz https://packages.wazuh.com/deps/40/libraries/linux/aarch64/flatbuffers.tar.gz || true
cd external && test -e flatbuffers.tar.gz && gunzip flatbuffers.tar.gz || true
cd external && test -e flatbuffers.tar && tar -xf flatbuffers.tar || true
test -e external/flatbuffers.tar && rm external/flatbuffers.tar || true
test -d external/flatbuffers ||\
(curl -so external/flatbuffers.tar.gz https://packages.wazuh.com/deps/40/libraries/sources/flatbuffers.tar.gz &&\
cd external && gunzip flatbuffers.tar.gz && tar -xf flatbuffers.tar && rm flatbuffers.tar)
find shared_modules/http-request -type f -exec false {} + &&\
((test -e shared_modules/http-request.tar || curl -so shared_modules/http-request.tar.gz -L https://github.com/wazuh/wazuh-http-request/tarball/8a302e514de6ef4df86717027682922f705330f4) &&\
(gunzip shared_modules/http-request.tar.gz || (rm -f shared_modules/http-request.tar.gz && echo "Error decompressing shared_modules/http-request.tar.gz maybe wrong branch was supplied!" && false)) &&\
tar -xf shared_modules/http-request.tar --strip-components=1 -C shared_modules/http-request &&\
rm shared_modules/http-request.tar) || true

```

### Installation

```console
Successfully built api
Installing collected packages: api
Successfully installed api-4.12.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
cd ../tools/mitre && /var/ossec/framework/python/bin/python3 mitredb.py -d /var/ossec/var/db/mitre.db
Generating self-signed certificate for wazuh-authd...


 - System is Redhat Linux.
 - Init script modified to start Wazuh during boot.
Starting Wazuh...
server
2025/01/23 17:39:40 wazuh-modulesd:router: INFO: Loaded router module.
2025/01/23 17:39:40 wazuh-modulesd:content_manager: INFO: Loaded content_manager module.
Starting Wazuh v4.12.0...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
2025/01/23 17:39:41 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
Started wazuh-integratord...
Started wazuh-agentlessd...
Started wazuh-authd...
Started wazuh-db...
Started wazuh-execd...
Started wazuh-analysisd...
Started wazuh-syscheckd...
Started wazuh-remoted...
Started wazuh-logcollector...
Started wazuh-monitord...
wazuh-modulesd: Process 9285 not used by Wazuh, removing...
2025/01/23 17:39:44 wazuh-modulesd:router: INFO: Loaded router module.
2025/01/23 17:39:44 wazuh-modulesd:content_manager: INFO: Loaded content_manager module.
Started wazuh-modulesd...
Completed.

 - Configuration finished properly.

 - To start Wazuh:
      /var/ossec/bin/wazuh-control start

 - To stop Wazuh:
      /var/ossec/bin/wazuh-control stop

 - The configuration can be viewed or modified at /var/ossec/etc/ossec.conf


   Thanks for using Wazuh.
   Please don't hesitate to contact us if you need help or find
   any bugs.

   Use our public Mailing List at:
          https://groups.google.com/forum/#!forum/wazuh

   More information can be found at:
          - http://www.wazuh.com

    ---  Press ENTER to finish (maybe more information below). ---

```

### Service status

```console
[root@74ba89990359 bin]# ./wazuh-control status
wazuh-clusterd not running...
wazuh-modulesd is running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd is running...
wazuh-maild not running...
wazuh-execd is running...
wazuh-db is running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid is running...
```

### API execution

```console
[root@74ba89990359 bin]# ./wazuh-apid -r -f
wazuh-apid: Orphan child process 9369 was terminated.
wazuh-apid: Orphan child process 9363 was terminated.
wazuh-apid: Orphan child process 9366 was terminated.
wazuh-apid: Orphan child process 9316 was terminated.
2025/01/23 17:41:26 INFO: Starting API in foreground
2025/01/23 17:41:26 INFO: Starting API as root
2025/01/23 17:41:26 INFO: Checking RBAC database integrity...
2025/01/23 17:41:26 INFO: /var/ossec/api/configuration/security/rbac.db file was detected
2025/01/23 17:41:26 INFO: RBAC database integrity check finished successfully
2025/01/23 17:41:28 INFO: Listening on ['0.0.0.0', '::']:55000.
2025/01/23 17:41:28 INFO: Getting installation UID...
2025/01/23 17:41:28 INFO: Getting updates information...
```

> The same tests were made for `x86`.

## Documentation

The user doesn't have to take any new steps to install the server in `x86` or `aarch64`.
