### ISSUE TITLE
Update agent groups queries and scripts

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#26847]
## Description

During the initial development, agent groups were stored and managed as a string with a list of names separated by commas. 

However, after [confirming](https://github.com/wazuh/wazuh-indexer/issues/506) that the document-level security allows the use of array values, from now on we are going to use a list of names to manage them.

As such, we need to update the agent pool queries and scripts to accommodate the new type.

### Tasks

Update:

- [x] Index query
- [x] Delete group query
- [x] Delete group script
- [x] Get group agents query
- [x] Add group script
- [x] Remove group script

**Comment by GGP1** [comment]
## Update

Updated the groups queries and scripts and validated that everything worked as expected.
