### ISSUE TITLE
Review the wazuh-tools repository for relevant code to migrate by PyServer

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh#26850]
## Description

Analyze the content of the repository `wazuh-tools`, detect and document the code pertinent to migrate to the corresponding repository.

## Tasks

- [x] Review the `wazuh-tools` repository.
- [x] Detect and identify relevant code to migrate.
- [x] Migrate code.
- [x] Enhancement and 5.0 development environment: https://github.com/wazuh/wazuh/issues/26820

**Comment by GGP1** [comment]
## Update

I've reviewed the code from our team in wazuh-tools and analyzed which resources should be migrated to this repository.
 
| Resource | Migrate | Notes |
| -- | -- | -- |
| framework/environments/dev | ✔ | The 4.x environment has been added to the repository in https://github.com/wazuh/wazuh/issues/26820 |
| framework/scripts/daemon_stats | ❌ | Agent statistics will no longer be stored in the server |
| framework/scripts/pytest_coverage | ❌ | We already have a script in qa-integration-framework and a GitHub action for this |
| framework/scripts/pytest_results | ❌ | Used to parse unit and integration test results. Still relevant, but should be included in the [qa-integration-framework](https://github.com/wazuh/qa-integration-framework) repository to generate reports automatically |
| framework/scripts/diagnostic_tool | ❌ | Uses 4.x resources, no longer needed in 5.0 |

I've opened the issue https://github.com/wazuh/wazuh/issues/27443 to integrate the pytest_results script with our tests workflows.

**Comment by GGP1** [comment]
## Update

Applied suggested changes.
