### ISSUE TITLE
Engine - Align testing tools and ruleset with updated communication protocol

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#26870]
### Description:
In response to recent modifications to the communication protocol in Wazuh-Engine, it is essential to update the testing tools and ruleset configurations to maintain test accuracy and relevance. This task involves updating `engine-test` to accommodate new protocol changes and adjusting the ruleset tests to ensure they reflect the current operational environment of the engine.

### Objective:
To ensure that `engine-test` and ruleset testing configurations are fully aligned with the revised communication protocol of Wazuh-Engine, thereby enabling accurate testing and validation of engine functionalities.

### Tasks:
1. **Update `engine-test`**:
   - Modify the `engine-test` tool to handle the new communication protocol changes, ensuring it can simulate and validate interactions as per the latest engine specifications.
   - Implement changes that allow `engine-test` to test both the transmission and reception of messages in accordance with the updated protocol.

2. **Revise Ruleset Testing Configurations**:
   - Adjust the ruleset testing configurations to match the updated ruleset used by Wazuh-Engine.
   - Ensure that the test setups accurately mirror the new engine behavior, especially in terms of event processing and handling.

3. **Validate and Integrate Changes**:
   - Conduct thorough testing to validate the functionality of the updated `engine-test` and the revised ruleset configurations.
   - Integrate the updated testing tools into the regular testing cycles to ensure continuous validation throughout development.

### Expected Outcome:
The successful update of `engine-test` and ruleset testing configurations will ensure that the tools are capable of accurately assessing and validating the functionality of Wazuh-Engine under the revised communication protocol. This alignment is crucial for detecting potential issues and maintaining the high reliability of the engine.

### DoD (Definition of Done):
- [ ] `engine-test` is updated to fully support the new communication protocol.
- [ ] Ruleset testing configurations are revised to align with the current engine settings.
- [ ] Successful integration of the updated tools into the development and testing pipeline.

### Impact:
By aligning the testing tools and ruleset with the updated communication protocol, we ensure that Wazuh-Engine continues to operate effectively and efficiently, with robust testing mechanisms in place to uphold system integrity and performance.

**Comment by JcabreraC** [comment]
### Analysis Summary

The `engine-health-test` uses both `engine-test` and `engine-test-utils`, which internally depend on the `api_communication` package. The `api_communication` communicates with the socket, sending requests in the following format:

```python
request = {
    'version': 1,
    'command': command,
    'origin': {'name': 'engine-integration-test', 'module': 'engine-integration-test'},
    'parameters': params
}
```
The key change required is the way `command `and `params `are obtained. This means that while `engine-health-test` relies on tools dependent on` api_communication`, **there's no need to modify anything in these tests**. Similarly, there's no need to modify the engine-test or engine-test-utils packages. The changes should focus solely on the api_communication package.

From API PR, it's evident that the server accepts requests from both `httplib` and `protobuf`, so this compatibility eliminates concerns about the format.

### Specific Cases:
- helper-test:
    Similar to `engine-health-test`, it relies on `engine-test`, which depends on `api_communication`. No modifications are needed in these tests either.
-  integration-test:
    These tests directly use `api_communication` and send `protobuf `requests. Since the server supports protobuf requests (as established above), there should be no issues here.

**Comment by juliancnn** [comment]
## Update

### Wazuh-Engine
- New protocol for test was implemented
- TODO: 
   - Fix orchestrator, router, api, tester unit test and component test
   - Fix IT


### Engine-test
- Ready for develop new ruleset
- TODO:
   - Wait CLI rebase for rebase big changes
   - Py Docuentation / Readmes / User manual doc.
   - Add multiline document format (For dynamic multiline)

**Comment by juliancnn** [comment]
## Update

- Adapted unit test and compont test to new protocol
- Fix and adapt Integration test
- Adapted engine-helper test tool to new protocol
- Add a new method to recollect data in engine-test, support for dynamic multiline collection.

**Comment by JcabreraC** [comment]
## Update
- Removed base decoders no longer required by the new protocol.
- Updated `Wazuh-core` decoders for compatibility.
- Modified `Apache` decoders to align with new requirements.
- Adjusted `Apache` tests to reflect changes in decoders.
- Adapting `Syslog` decoders.

**Comment by juliancnn** [comment]
## Update

- Rebase and adapt after remove CLI
- Update devContainer
- Cleanup of all legacy code with old prototype, removal of old endpoint, ut, it, ct, benchmark and more.
- Fixed `template base-tags` -> `tags`

_Waiting for ruleset to upload to S3 and adapt the installation script._

**Comment by juliancnn** [comment]
## Update

- Update documentation of aip
- Discovered bug in npm module to generate the API documentation (`swagger.json`), the npm module `apidoc-openapi-3-1`, does not generate the documentation of all params, it can be seen in debug mode that does not analyze `@apiDescription`, `@apiParamExample`, `@apiSampleRequest` so it is not possible to add an example payload in the documentation of `engine.html`. But the apidoc tool that generates the index.html does generate correctly the example with the `@apiDescription` param.

**Comment by JcabreraC** [comment]
## Update
- Changes made to Suricata decoders
- Fixes applied to Windows decoders
- Suricata tests adapted

**Comment by JcabreraC** [comment]
ETA extended for priority in MVP issues.

**Comment by JcabreraC** [comment]
## Update
- Adapting windows decoders
- Adapting windows test
- Reorganizing ruleset files

**Comment by NahuFigueroa97** [comment]
## Update

- Fix engine-schema generator for efficiency merge
- Generate all schames
- Fix health-test static

**Comment by JcabreraC** [comment]
## Update
- Adapting sysmon decoders
- Adapting sysmon test
- Fixed expected
