### ISSUE TITLE
Modify installation scripts for ARM architecture.

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#26946]
### Description
As Wazuh expands its support to include ARM architectures, it's essential to adapt the existing installation scripts to accommodate these platforms. The primary focus of this issue is to ensure that the `install.sh` script can detect the operating system's architecture and adjust its operations accordingly, particularly regarding dependency management and package installation.

### Objectives
- **Architecture Detection**: Enhance the `install.sh` script to automatically detect the architecture of the Linux system where it's being executed. This includes distinguishing between x86_64 and ARM architectures.
- **Conditional Logic Implementation**: Implement conditional logic within the script to handle different scenarios based on the detected architecture. This includes fetching the correct binaries and dependencies tailored to ARM environments.
- **Test and Validation**: Thoroughly test the modified script on various ARM platforms to ensure it performs the installation process smoothly and efficiently.

### Tasks
- [x] **Script Modification**: Update the `install.sh` script to include checks for ARM architecture and apply conditional operations based on the outcome.
- [x] **Dependency Management**: Adjust the dependency download and installation processes within the script to support ARM-specific packages.
- [x] **Testing on ARM Devices**: Perform comprehensive testing on multiple ARM-based devices or emulators to ensure compatibility and functionality.
- [ ] **Documentation Update**: Revise the installation documentation to include instructions and notes specific to ARM architecture setups.

### Expected Challenges
- **Dependency Compatibility**: Ensuring that all required dependencies are available and functional on ARM platforms.
- **Testing Scope**: Extensively testing the script across different ARM distributions and versions to guarantee robustness.

### Acceptance Criteria
- The `install.sh` script must successfully detect the architecture and install Wazuh-Server on ARM platforms without manual intervention.
- All changes should be backward compatible, not affecting the existing installation process on x86_64 architectures.
- The script should handle errors gracefully, providing clear guidance or fallback mechanisms when issues arise.

This issue is a critical step towards broadening the support of Wazuh to ARM architectures, ensuring that the installation process is as seamless on ARM as it is on traditional x86_64 systems.

**Comment by gecube** [comment]
Waiting with impatience to get fully working wazuh installation on ARM....

**Comment by fcaffieri** [comment]
### Documentation Update


File: source/quickstart.rst
Line: 48

Actual:

```
Operating system

The Wazuh central components require a 64-bit Intel or AMD Linux processor (x86_64/AMD64 architecture) to run. Wazuh recommends any of the following operating system versions:

```

Suggested:

```
Operating system

The Wazuh central components require a 64-bit Intel or AMD or ARM Linux processor (x86_64/AMD64/AARCH64/ARMM64 architecture) to run. Wazuh recommends any of the following operating system versions:

```

---

File: source/installation-guide/wazuh-dashboard/index.rst
Line: 77

Actual:

```
Recommended operating systems

The Wazuh dashboard requires a 64-bit Intel or AMD Linux processor (x86_64/AMD64 architecture) to run. Wazuh supports the following operating system versions:

```

Suggested:

```
Recommended operating systems

The Wazuh dashboard requires a 64-bit Intel or AMD or ARM Linux processor (x86_64/AMD64/AARCH64/ARMM64 architecture) to run. Wazuh supports the following operating system versions:

```

---

File: source/installation-guide/wazuh-dashboard/installation-assistant.rst
Line: 9

Actual:

```
Install and configure the Wazuh dashboard on a 64-bit (x86_64/AMD64) architecture using the assisted installation method. Wazuh dashboard is a flexible and intuitive web interface for mining and visualizing security events and archives.
```

Suggested:

```
Install and configure the Wazuh dashboard on a 64-bit (x86_64/AMD64/AARCH64/ARM64) architecture using the assisted installation method. Wazuh dashboard is a flexible and intuitive web interface for mining and visualizing security events and archives.
```


---

File: source/installation-guide/wazuh-indexer/index.rst
Line: 76

Actual:

```
Recommended operating systems

The Wazuh indexer requires a 64-bit Intel or AMD Linux processor (x86_64/AMD64 architecture) to run. Wazuh supports the following operating system versions:
```

Suggested:

```
Recommended operating systems

The Wazuh indexer requires a 64-bit Intel or AMD or ARM Linux processor (x86_64/AMD64/AARCH64/ARMM64 architecture) to run. Wazuh supports the following operating system versions:
```


---

File: source/installation-guide/wazuh-indexer/installation-assistant.rst
Line: 9

Actual:

```
Install and configure the Wazuh indexer as a single-node or multi-node cluster on a 64-bit (x86_64/AMD64) architecture using the assisted installation method. The Wazuh indexer is a highly scalable full-text search engine. It offers advanced security, alerting, index management, deep performance analysis, and several other features.
```

Suggested:

```
Install and configure the Wazuh indexer as a single-node or multi-node cluster on a 64-bit (x86_64/AMD64/AARCH64/ARM64) architecture using the assisted installation method. The Wazuh indexer is a highly scalable full-text search engine. It offers advanced security, alerting, index management, deep performance analysis, and several other features.
```

---

File: source/installation-guide/wazuh-server/index.rst
Line: 77

Actual:

```
Recommended operating systems

The Wazuh server requires a 64-bit Intel or AMD Linux processor (x86_64/AMD64 architecture) to run. Wazuh supports the following operating system versions:

```

Suggested:

```
Recommended operating systems

The Wazuh server requires a 64-bit Intel or AMD or ARM Linux processor (x86_64/AMD64/AARCH64/ARMM64 architecture) to run. Wazuh supports the following operating system versions:

```

---

File: source/installation-guide/wazuh-server/installation-assistant.rst
Line: 9

Actual:

```
Install the Wazuh server as a single-node or multi-node cluster on a 64-bit (x86_64/AMD64) architecture using the assisted installation method. The Wazuh server analyzes the data received from the agents triggering alerts when it detects threats and anomalies. This central component includes the Wazuh manager and Filebeat.
```

Suggested:

```
Install the Wazuh server as a single-node or multi-node cluster on a 64-bit (x86_64/AMD64/AARCH64/ARM64) architecture using the assisted installation method. The Wazuh server analyzes the data received from the agents triggering alerts when it detects threats and anomalies. This central component includes the Wazuh manager and Filebeat.

```

---

File: source/user-manual/agent/agent-management/remote-upgrading/upgrading-agent.rst
Line: 135

Actual:

```
This recommendation is based on testing with a Wazuh manager on a server with a 2.5 GHz AMD EPYC 7000 series processor and 4 GiB memory. Using an agent list with 3000 agents or fewer on a system with similar or better specifications guarantees a response before the API timeout occurs.
```

Suggested:

```
This recommendation is based on testing with a Wazuh manager on a server with a 2.5 GHz AMD OR ARM EPYC 7000 series processor and 4 GiB memory. Using an agent list with 3000 agents or fewer on a system with similar or better specifications guarantees a response before the API timeout occurs.
```

---

File: source/deployment-options/docker/docker-installation.rst
Line: 56

Actual:

```
For Linux/Unix machines, Docker requires an amd64 architecture system running kernel version 3.10 or later.
```

Suggested:

```
For Linux/Unix machines, Docker requires an amd64 or arm64 architecture system running kernel version 3.10 or later.
```

---

File: source/deployment-options/offline-installation/index.rst
Line: 9

Actual:

```
You can install Wazuh even when there is no connection to the Internet. Installing the solution offline involves downloading the Wazuh central components to later install them on a system with no Internet connection. The Wazuh server, the Wazuh indexer, and the Wazuh dashboard can be installed and configured on the same host in an all-in-one deployment, or each component can be installed on a separate host as a distributed deployment, depending on your environment needs. The supported architecture is 64-bit (x86_64/AMD64).
```

Suggested:

```
You can install Wazuh even when there is no connection to the Internet. Installing the solution offline involves downloading the Wazuh central components to later install them on a system with no Internet connection. The Wazuh server, the Wazuh indexer, and the Wazuh dashboard can be installed and configured on the same host in an all-in-one deployment, or each component can be installed on a separate host as a distributed deployment, depending on your environment needs. The supported architecture is 64-bit (x86_64/AMD64/AARCH64/ARM64).
```

---

File: source/deployment-options/offline-installation/index.rst
Line: 27 to 43

Actual:

```
#. Run the following commands from any Linux system with Internet connection. This action executes a script that downloads all required files for the offline installation on x86_64 architectures. Select the package format to download.
   .. tabs::

        .. group-tab:: RPM

            .. code-block:: console
        
               # curl -sO https://packages.wazuh.com/|WAZUH_CURRENT_MINOR|/wazuh-install.sh
               # chmod 744 wazuh-install.sh
               # ./wazuh-install.sh -dw rpm

        .. group-tab:: DEB

            .. code-block:: console
        
               # curl -sO https://packages.wazuh.com/|WAZUH_CURRENT_MINOR|/wazuh-install.sh
               # chmod 744 wazuh-install.sh
               # ./wazuh-install.sh -dw deb
```

Suggested:

```
#. Run the following commands from any Linux system with Internet connection. This action executes a script that downloads all required files for the offline installation (on x86_64/AMD&$/ARM64/AARCH64 architectures). Select the package format to download.
     .. tabs::

        .. group-tab:: RPM

            .. code-block:: console
        
               # curl -sO https://packages.wazuh.com/|WAZUH_CURRENT_MINOR|/wazuh-install.sh
               # chmod 744 wazuh-install.sh
               # ./wazuh-install.sh -dw rpm -da x86_64

            .. code-block:: console
        
               # curl -sO https://packages.wazuh.com/|WAZUH_CURRENT_MINOR|/wazuh-install.sh
               # chmod 744 wazuh-install.sh
               # ./wazuh-install.sh -dw rpm -da aarch64

        .. group-tab:: DEB

            .. code-block:: console
        
               # curl -sO https://packages.wazuh.com/|WAZUH_CURRENT_MINOR|/wazuh-install.sh
               # chmod 744 wazuh-install.sh
               # ./wazuh-install.sh -dw deb -da arm64

            .. code-block:: console
        
               # curl -sO https://packages.wazuh.com/|WAZUH_CURRENT_MINOR|/wazuh-install.sh
               # chmod 744 wazuh-install.sh
               # ./wazuh-install.sh -dw deb -da amd64
```

---

File: source/deployment-options/offline-installation/installation-assistant.rst
Line: 4

Actual:

```
l and configure the different Wazuh components on a 64-bit (x86_64/AMD64) architecture with the aid of the Wazuh installation assistant.
```

Suggested:

```
l and configure the different Wazuh components on a 64-bit (x86_64/AMD64/AARCH64/ARM64) architecture with the aid of the Wazuh installation assistant.
```

---

File: source/deployment-options/virtual-machine/virtual-machine.rst
Line: 11

Actual:

```
Wazuh provides a pre-built virtual machine image in Open Virtual Appliance (OVA) format. This can be directly imported to VirtualBox or other OVA compatible virtualization systems. Take into account that this VM only runs on 64-bit systems with x86_64/AMD64 architecture. It does not provide high availability and scalability out of the box. However, these can be implemented by using :doc:`distributed deployment </installation-guide/index>`.
```

Suggested:

```
Wazuh provides a pre-built virtual machine image in Open Virtual Appliance (OVA) format. This can be directly imported to VirtualBox or other OVA compatible virtualization systems. Take into account that this VM only runs on 64-bit systems with x86_64/AMD64/AARCH64/ARM64 architecture. It does not provide high availability and scalability out of the box. However, these can be implemented by using :doc:`distributed deployment </installation-guide/index>`.
```

---

File: source/deployment-options/virtual-machine/virtual-machine.rst
Line: 31

Actual:

```
+----------------+-----------------------------------+--------------+----------------------+------------------+
|  Distribution  | Architecture                      | VM Format    | Version              | Package          |
+================+===================================+==============+======================+==================+
| Amazon Linux 2 | 64-bit x86_64/AMD64 architecture  |      OVA     | |WAZUH_OVA_VERSION|  | |VM_AL2_64_OVA|  |
+----------------+-----------------------------------+--------------+----------------------+------------------+
```

Suggested:

```+----------------+-----------------------------------+--------------+----------------------+------------------+
|  Distribution  | Architecture                      | VM Format    | Version              | Package          |
+================+===================================+==============+======================+==================+
| Amazon Linux 2 | 64-bit x86_64/AMD64 architecture  |      OVA     | |WAZUH_OVA_VERSION|  | |VM_AL2_64_OVA|  |
+----------------+-----------------------------------+--------------+----------------------+------------------+
| Amazon Linux 2 | 64-bit AARCH64/ARM64 architecture |      OVA     | |WAZUH_OVA_VERSION|  | |VM_AL2_64_OVA|  |
+----------------+-----------------------------------+--------------+----------------------+------------------+

```

---

File: source/deployment-options/virtual-machine/virtual-machine.rst
Line: 39

Actual:

```
- The host operating system has to be a 64-bit system with x86_64/AMD64 architecture.
```

Suggested:

```
- The host operating system has to be a 64-bit system with x86_64/AMD64/AARCH64/ARM64 architecture.
```

---

**Comment by teddytpc1** [comment]
The content team was notified about the documentation changes.

**Comment by Ifex370** [comment]
Hi @fcaffieri 

Does this expansion include coverage for installing Wazuh on Apple Silicon ARM64 (AArch64) architecture?
I have tried several versions of the Wazuh OVA on an Apple M4, and I always get the "Platform not supported" error message.
