### ISSUE TITLE
Framework indexer client refinement

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#27048]
## Description

During the testing of the MVP we have encountered some issues while connecting the wazuh server and indexer.

This issue aims to fix them and to improve the error handling on the server to facilitate debugging.

### Tasks

- [x] Add a `verify_certificates` field to the `indexer.ssl` configuration instead of using always `True`. This will let users disable the hostname verification in testing environments
  ```console
  ConnectionError(Cannot connect to host wazuh-indexer:9200 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'wazuh-indexer'. (_ssl.c:1007)")])
  ```
- [x] We should enhance the message returned when the connection fails, adding the connection error message from the client. We are currently returning just
  ```console
  wazuh.core.exception.WazuhIndexerError: Error 2200 - Could not connect to the indexer
  ```
  where we should return
  ```console
  wazuh.core.exception.WazuhIndexerError: Error 2200 - Could not connect to the indexer: AuthenticationException(401, 'Unauthorized')
  ```
- [x] Make certificates paths required if `indexer.ssl.use_ssl` is true.
- [x] Validate certificates paths if `indexer.ssl.use_ssl` is true.

**Comment by GGP1** [comment]
## Update

Improved the indexer client usability and validated the changes in a testing environment.
