### ISSUE TITLE
Change `wazuh-packages` reference in Solaris package generation

### ISSUE THREAD

**Issue by hossam1522** [wazuh/wazuh#27059]
Following the development carried out in [Wazuh packages redesign tier 2](https://github.com/wazuh/wazuh-packages/issues/2904), considering that the `wazuh-packages` repository is going to be deprecated, it is necessary to remove any existing reference to this repository and update the documentation of the [Solaris package generation](https://github.com/wazuh/wazuh/blob/4.10.0/packages/solaris/package_generation/README.md) to take these changes into account.

In addition, there are also those for documentation:

- https://github.com/wazuh/wazuh-documentation/blob/4.10.0/source/user-manual/agent/agent-management/remote-upgrading/wpk-files/create-custom-wpk.rst
- https://github.com/wazuh/wazuh-documentation/blob/4.10.0/source/development/packaging/generate-osx-package.rst
- https://github.com/wazuh/wazuh-documentation/blob/4.10.0/source/development/packaging/generate-hpux-package.rst
- https://github.com/wazuh/wazuh-documentation/blob/4.10.0/source/development/packaging/generate-sol-package.rst
- https://github.com/wazuh/wazuh-documentation/blob/4.10.0/source/development/packaging/generate-aix-package.rst
- https://github.com/wazuh/wazuh-documentation/blob/4.10.0/source/deployment-options/wazuh-from-sources/wazuh-agent/index.rst

<details><summary>References</summary>

```
source/user-manual/agent/agent-management/remote-upgrading/wpk-files/create-custom-wpk.rst:#. Download the ``wazuh-packages`` repository from GitHub and navigate to the WPK directory:
source/user-manual/agent/agent-management/remote-upgrading/wpk-files/create-custom-wpk.rst:      $ git clone https://github.com/wazuh/wazuh-packages && cd wazuh-packages/wpk && git checkout v|WAZUH_CURRENT|
source/development/packaging/generate-osx-package.rst:Download our wazuh-packages repository from GitHub and go to the macos directory.
source/development/packaging/generate-osx-package.rst:The result of the notarization will be stored in wazuh-packages/macos/request_result.txt.
source/development/packaging/generate-hpux-package.rst:Download our wazuh-packages repository from GitHub and go to the ``hpux`` directory.
source/development/packaging/generate-hpux-package.rst: $ curl -L https://github.com/wazuh/wazuh-packages/tarball/v|WAZUH_CURRENT| | tar zx
source/development/packaging/generate-hpux-package.rst: $ cd wazuh-wazuh-packages-*
source/development/packaging/generate-sol-package.rst:Download our wazuh-packages repository from GitHub and go to the ``solaris`` directory.
source/development/packaging/generate-sol-package.rst:  $ git clone https://github.com/wazuh/wazuh-packages && cd wazuh-packages/solaris && git checkout v|WAZUH_CURRENT_SOLARIS|
source/development/packaging/generate-sol-package.rst:Clone our wazuh-packages repository from GitHub and switch to your target branch. Copy the source files for your Solaris 10 or Solaris 11 target system into ``wazuh-packages/solaris/package_generation/src``. Change to the ``wazuh-packages/solaris/package_generation`` directory before building the package.
source/development/packaging/generate-sol-package.rst:      $ git clone https://github.com/wazuh/wazuh-packages && cd wazuh-packages/solaris && git checkout v|WAZUH_CURRENT_SOLARIS10|
source/development/packaging/generate-sol-package.rst:      $ git clone https://github.com/wazuh/wazuh-packages && cd wazuh-packages/solaris && git checkout v|WAZUH_CURRENT_SOLARIS11|
source/development/packaging/generate-aix-package.rst:Download our wazuh-packages repository from GitHub and go to the aix directory.
source/development/packaging/generate-aix-package.rst: $ curl -L https://github.com/wazuh/wazuh-packages/tarball/v|WAZUH_CURRENT| | tar zx
source/development/packaging/generate-aix-package.rst: $ cd wazuh-wazuh-packages-*
source/deployment-options/wazuh-from-sources/wazuh-agent/index.rst:                    # wget https://raw.githubusercontent.com/wazuh/wazuh-packages/|WAZUH_CURRENT_MINOR_FROM_SOURCES|/aix/generate_wazuh_packages.sh --no-check-certificate
source/deployment-options/wazuh-from-sources/wazuh-agent/index.rst:                    # /usr/local/bin/wget https://github.com/wazuh/wazuh-packages/raw/master/hp-ux/depothelper-2.10-hppa_32-11.31.depot --no-check-certificate
source/deployment-options/wazuh-from-sources/wazuh-agent/index.rst:                    # /usr/local/bin/wget https://raw.githubusercontent.com/wazuh/wazuh-packages/master/hp-ux/generate_wazuh_packages.sh --no-check-certificate
```

</details>

## Tasks

- [ ] Check all references to `wazuh-packages`.
- [ ] Change the references and adapt them to not use that repository.
- [ ] Check that everything is working properly.
