### ISSUE TITLE
Comms API - Stateful endpoint with ECS compliant models 

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#27079]
# Description

As part of the 5.0 MVP refinement, we need to make adjustments to the `POST /events/stateful` endpoint, specifically to the expected fields in the request body. In https://github.com/wazuh/wazuh-indexer/issues/270, the Indexer team has defined the index data model (template) for the following `stateful` indices that can already be checked in the [ecs/docs](https://github.com/wazuh/wazuh-indexer/tree/master/ecs/docs) folder:
  - [System Inventory](https://github.com/wazuh/wazuh-indexer/blob/master/ecs/docs/inventory-system.md)
  -  [Processes Inventory](https://github.com/wazuh/wazuh-indexer/blob/master/ecs/docs/inventory-processes.md)
  -  [Packages Inventory](https://github.com/wazuh/wazuh-indexer/blob/master/ecs/docs/inventory-packages.md)
  -  [Network Inventory](https://github.com/wazuh/wazuh-indexer/blob/master/ecs/docs/inventory-networks.md)
  -  [Ports Inventory](https://github.com/wazuh/wazuh-indexer/blob/master/ecs/docs/inventory-ports.md)
  -  [Hardware Inventory](https://github.com/wazuh/wazuh-indexer/blob/master/ecs/docs/inventory-hardware.md)
  -  [Hotfixes Inventory](https://github.com/wazuh/wazuh-indexer/blob/master/ecs/docs/inventory-hotfixes.md)
  -  [Vulnerabilities](https://github.com/wazuh/wazuh-indexer/blob/master/ecs/docs/states-vulnerability.md)
  -  [FIM](https://github.com/wazuh/wazuh-indexer/blob/master/ecs/docs/states-fim.md)

Taking into account the streaming protocol we have established for the stateful events in https://github.com/wazuh/wazuh/issues/26709#issuecomment-2457898608, which has the following structure: 

```json
{
# Agent Metadata
}
{
# Module information
}
{
# Event
}
{
# Module information
}
{
# Event
}
```
> [!NOTE]
> For the `"operation": "delete"` type we do not expect an `Event`.

The requirement is to only validate the information related to the `Agent Metadata` and the `Module information` since it is required for the query to the indexer and pass the `Event` without validating its fields.

## Tasks

- [x] Make the necessary modifications to the `StatefulEvent` model.
- [x] Check that every module is mapped to its correspondent index name.
- [x] Test against a deployed indexer that the received bulk is correctly sent and indexed.

**Comment by GGP1** [comment]
## Update

Fixed various bugs in the batcher when sending and receiving multiple events and removed the events classes, moving the validation layer to the indexer.
