### ISSUE TITLE
Comms API - Review and fix requests logging

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#27098]
# Description 

During the 5.0 MVP tests, it was found that the Comms API is not printing every request that is being received. Therefore, the complete behavior of the Wazuh Server related to the requests it processes cannot be checked as expected.

The issue might be related to the processes being launched by the Comms API. Currently, the Comms API deploys a `gunicorn` server which then runs workers that process the incoming requests. These workers log via the same logger, without any mechanism to order the messages to print, so we suspect that a possible race condition between them is taking place and blocking the logging.

A possible alternative would be to log everything to `stdout` as described in https://github.com/wazuh/wazuh/issues/25231 and then depending on the environment where it is deployed, delegate the processing of it.

## Tasks

- [x] Determine the root cause of the error.
- [x] Implement the necessary changes to be able to log every processed request.
- [x] Test the implementation to verify that multiple requests are logged as expected.

**Comment by fdalmaup** [comment]
# Update

The error was expected since multiple processes are logging into the same `comms_api.log` file. It was decided that every process must log to `stdout`, therefore we will delete any related logging file configuration, such as rotation handlers, and remove the log file creation.

The initial changes have been pushed to the `bug/27098-fix-server-logging` branch, giving the following result:
```log
root@cca3f3cbfdb1:/# /usr/share/wazuh-server/bin/wazuh-server start -r 
Starting cluster in foreground (pid: 916)
2024/12/02 18:34:15 INFO: [Local Server] [Main] Starting wazuh-engined
2024-12-02 18:34:15.073 922:922 info: Logging initialized.
2024-12-02 18:34:15.075 922:922 info: Store initialized.
2024-12-02 18:34:15.075 922:922 info: RBAC initialized.
2024-12-02 18:34:15.075 922:922 info: MetricsManager: Created new scope: (KVDB)
2024/12/02 18:34:15 INFO: [Master] [Config Server] Started server process [916]
2024/12/02 18:34:15 INFO: [Master] [Config Server] Waiting for application startup.
2024/12/02 18:34:15 INFO: [Master] [Config Server] Application startup complete.
2024/12/02 18:34:15 INFO: [Master] [Config Server] Uvicorn running on unix socket /run/wazuh-server/config-server.sock (Press CTRL+C to quit)
2024-12-02 18:34:15.114 922:922 info: KVDB initialized.
2024-12-02 18:34:15.114 922:922 info: Geo initialized.
2024-12-02 18:34:15.130 922:922 info: Schema initialized.
2024-12-02 18:34:15.141 922:922 info: Loaded timezone database version: '2024a'
2024-12-02 18:34:15.145 922:922 info: HLP initialized.
2024-12-02 18:34:15.166 922:922 info: Indexer Connector initialized.
2024-12-02 18:34:15.166 922:922 info: Builder initialized.
2024-12-02 18:34:15.166 922:922 info: Catalog initialized.
2024-12-02 18:34:15.166 922:922 info: Policy manager initialized.
2024-12-02 18:34:15.166 922:922 info: MetricsManager: Created new scope: (EventQueue)
2024-12-02 18:34:15.166 922:922 info: MetricsManager: Created new scope: (EventQueueDelta)
2024-12-02 18:34:15.167 922:922 info: No flooding file provided, the queue will not be flooded.
2024-12-02 18:34:15.167 922:922 info: MetricsManager: Created new scope: (TestQueue)
2024-12-02 18:34:15.168 922:922 info: MetricsManager: Created new scope: (TestQueueDelta)
2024-12-02 18:34:15.174 922:922 info: No flooding file provided, the queue will not be flooded.
2024-12-02 18:34:15.175 922:922 warning: Router: router/tester/0 table is empty
2024-12-02 18:34:15.263 922:922 info: Router initialized.
2024-12-02 18:34:15.263 922:922 info: Starting database file decompression.
2024/12/02 18:34:17 INFO: [Local Server] [Main] Started wazuh-engined (pid: 922)
2024/12/02 18:34:17 INFO: [Local Server] [Main] Starting wazuh-comms-apid
2024/12/02 18:34:17 INFO: Starting API in foreground
2024/12/02 18:34:17 INFO: Starting API as root
2024/12/02 18:34:17 INFO: Listening on localhost:27000
2024/12/02 18:34:18 INFO: Generated private key file in /etc/wazuh-server/api/configuration/ssl/server.key
2024/12/02 18:34:18 INFO: Generated certificate file in /etc/wazuh-server/api/configuration/ssl/server.crt
2024/12/02 18:34:18 INFO: Starting gunicorn 22.0.0
2024/12/02 18:34:18 INFO: Listening at: https://127.0.0.1:27000 (1322)
2024/12/02 18:34:18 INFO: Using worker: uvicorn.workers.UvicornWorker
2024/12/02 18:34:18 INFO: Booting worker with pid: 1368
2024/12/02 18:34:18 INFO: Started server process [1368]
2024/12/02 18:34:18 INFO: Waiting for application startup.
2024/12/02 18:34:18 INFO: Application startup complete.
2024/12/02 18:34:18 INFO: Booting worker with pid: 1369
2024/12/02 18:34:18 INFO: Started server process [1369]
2024/12/02 18:34:18 INFO: Waiting for application startup.
2024/12/02 18:34:18 INFO: Application startup complete.
2024/12/02 18:34:18 INFO: Booting worker with pid: 1370
2024/12/02 18:34:18 INFO: Started server process [1370]
2024/12/02 18:34:18 INFO: Waiting for application startup.
2024/12/02 18:34:18 INFO: Application startup complete.
2024/12/02 18:34:18 INFO: Booting worker with pid: 1371
2024/12/02 18:34:18 INFO: Started server process [1371]
2024/12/02 18:34:18 INFO: Waiting for application startup.
2024/12/02 18:34:18 INFO: Application startup complete.
2024/12/02 18:34:19 INFO: [Local Server] [Main] Started wazuh-comms-apid (pid: 1322)
2024/12/02 18:34:19 INFO: [Local Server] [Main] Starting wazuh-apid
2024/12/02 18:34:19 INFO: Starting API in foreground
2024/12/02 18:34:19 INFO: Starting API as root
2024/12/02 18:34:19 INFO: Checking RBAC database integrity...
2024/12/02 18:34:19 INFO: RBAC database not found. Initializing
2024/12/02 18:34:21 INFO: [Local Server] [Main] Started wazuh-apid (pid: 1372)
2024/12/02 18:34:21 INFO: [Local Server] [Main] Serving on /run/wazuh-server/socket/local-server.sock
2024/12/02 18:34:21 INFO: [Master] [Main] Serving on ('127.0.0.1', 1516)
2024/12/02 18:34:21 INFO: [Master] [Local integrity] Starting.
2024/12/02 18:34:21 INFO: [Master] [Local integrity] Finished in 0.001s. Calculated metadata of 0 files.
2024/12/02 18:34:29 INFO: [Master] [Local integrity] Starting.
2024/12/02 18:34:29 INFO: [Master] [Local integrity] Finished in 0.001s. Calculated metadata of 0 files.
2024/12/02 18:34:29 INFO: /var/lib/wazuh-server/rbac.db database created successfully
2024/12/02 18:34:29 INFO: RBAC database integrity check finished successfully
2024/12/02 18:34:30 INFO: Listening on ['localhost', '::1']:55000.
2024/12/02 18:34:30 INFO: Populating installation UID...
2024/12/02 18:34:30 INFO: Getting updates information...
2024/12/02 18:34:37 INFO: [Master] [Local integrity] Starting.
2024/12/02 18:34:37 INFO: [Master] [Local integrity] Finished in 0.002s. Calculated metadata of 0 files.
2024/12/02 18:34:45 INFO: [Master] [Local integrity] Starting.
2024/12/02 18:34:45 INFO: [Master] [Local integrity] Finished in 0.002s. Calculated metadata of 0 files.
```

Further tests will be carried out and the unit tests must be updated.

**Comment by fdalmaup** [comment]
# Manual tests

## Two simultaneous requests
Sent requests to the `POST /security/user/authenticate` Management API endpoint and the `GET /commands` endpoint simultaneously. Both requests were logged:

```
2024/12/03 12:27:09 INFO: [Master] [Local integrity] Starting.
2024/12/03 12:27:09 INFO: [Master] [Local integrity] Finished in 0.002s. Calculated metadata of 0 files.
2024/12/03 12:27:13 DEBUG: Request headers: {'host': 'localhost:27000', 'user-agent': 'curl/7.68.0', 'accept': '*/*', 'content-type': 'application/json'}
2024/12/03 12:27:13 INFO: "GET /api/v1/commands" with parameters {} and body {} done in 0.002s: 403
2024/12/03 12:27:13 INFO: wazuh 172.18.0.1 "POST /security/user/authenticate" with parameters {} and body {} done in 0.158s: 200
```

## Multiple simultaneous requests

(WIP)
