### ISSUE TITLE
Bug in URL validation for the Maltiverse integration

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#27090]
# Description

The `maltiverse.py` script contains a bug that exposes it to the [CVE-2024-11168](https://nvd.nist.gov/vuln/detail/CVE-2024-11168) vulnerability, expected to be fixed for Python `v3.10` in https://github.com/python/cpython/pull/126975. Nevertheless, until the PR is merged and a new patch version is released, we need to modify the script to reduce the risk of unwanted behavior in the script.

https://github.com/wazuh/wazuh/blob/6cf1a07a225a44a999dc6175777553049ed9e767/integrations/maltiverse.py#L204-L218

## Tasks

- [x] Modify the `is_valid_url` function implementation to check the URL taking into account [URL parsing security](https://docs.python.org/3.10/library/urllib.parse.html#url-parsing-security).
- [x] Update unit tests if needed.
- [x] Test the Maltiverse integration and verify it works as expected.
