### ISSUE TITLE
Allow empty fields in Syscollector

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#2716]
The `sys_hwinfo` table in Wazuh DB is defined this way:
```sql
CREATE TABLE IF NOT EXISTS sys_hwinfo (
    scan_id INTEGER,
    scan_time TEXT,
    board_serial TEXT,
    cpu_name TEXT,
    cpu_cores INTEGER CHECK (cpu_cores > 0),
    cpu_mhz REAL CHECK (cpu_mhz > 0),
    ram_total INTEGER CHECK (ram_total > 0),
    ram_free INTEGER CHECK (ram_free > 0),
    ram_usage INTEGER CHECK (ram_usage >= 0 AND ram_usage <= 100),
    PRIMARY KEY (scan_id, board_serial)
);
```
(https://github.com/wazuh/wazuh/blob/v3.8.2/src/wazuh_db/schema_agents.sql#L103-L114)

On the other hand, Syscollector zeroes this structure before getting hardware data:
```c
typedef struct hw_info {
    char *cpu_name;
    int cpu_cores;
    double cpu_MHz;
    uint64_t ram_total;  // kB
    uint64_t ram_free;   // kB
    int ram_usage;  // Percentage
} hw_info;
```
(https://github.com/wazuh/wazuh/blob/v3.8.2/src/wazuh_modules/syscollector/syscollector.h#L98-L105)

Nevertheless, Syscollector always sends all these fields, no matter if the data was successfully obtained.

If Syscollector loses any of the fields, for instance, the CPU frequency, the agent will send the value `0` in the payload, producing an error like this in the manager:
> 2019/02/28 16:00:58 ossec-analysisd: ERROR: at sc_send_db(): received: 'err Cannot save HW information.'

## Subtasks
- [ ] Let Syscollector send only the data it read.
- [ ] Disable the value integrity checks in the database.
- [x] Implement those value checks in the Syscollector decoder.
- [ ] Add the changes to the database migration procedure.

**Comment by juan70** [comment]
2019-03-01
----------
- Find a way to reproduce the error.
- Error reproduced (see below).

**Comment by juan70** [comment]
Error reproduced
--
The problem seems to happen only when `cpu_mhz` is `0`.
With every empty or 0:
```
echo 'd:syscollector:{"type":"hardware","ID":0,"timestamp":"","inventory":{"board_serial":"","cpu_name":"","cpu_cores":0,"cpu_MHz":1,"ram_total":0,"ram_free":0,"ram_usage":0}}' | nc -Uu /var/ossec/queue/ossec/queue
```

In `ossec.log`:
```
2019/03/01 12:06:23 wazuh-db: ERROR: at wdb_hardware_insert(): sqlite3_step(): CHECK constraint failed: sys_hwinfo
2019/03/01 12:06:23 wazuh-db: ERROR: Unable to update 'sys_hwinfo' table for agent '000'
2019/03/01 12:06:23 ossec-analysisd: ERROR: at sc_send_db(): received: 'err Cannot save HW information.'
```

With a little more than 0 for the Mhz:
```
echo 'd:syscollector:{"type":"hardware","ID":0,"timestamp":"","inventory":{"board_serial":"","cpu_name":"","cpu_cores":0,"cpu_MHz":0.000001,"ram_total":0,"ram_free":0,"ram_usage":0}}' | nc -Uu /var/ossec/queue/ossec/queue
```
No errors in `ossec.log`.
```
# sqlite3 /var/ossec/queue/db/000.db '.headers on' 'select * from sys_hwinfo'
scan_id|scan_time|board_serial|cpu_name|cpu_cores|cpu_mhz|ram_total|ram_free|ram_usage
0|||||1.0e-06|||
```
(With a bit less, 0.0000001, 1.0e-07, the error occurs.)

**Comment by juan70** [comment]
Note
--
Related to the issue https://github.com/wazuh/wazuh/issues/2488: it turns out that on virtual machines running Linux through vagrant/VirtualBox, the file `/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq` does **not** exist.
For example, on a Debian 9 box:
```
root@deb9man:/sys/devices/system/cpu/cpu0#  ll
total 0
drwxr-xr-x 7 root root    0 Mar  1 15:03 cache
-r-------- 1 root root 4096 Mar  1 15:03 crash_notes
-r-------- 1 root root 4096 Mar  1 15:03 crash_notes_size
lrwxrwxrwx 1 root root    0 Mar  1 15:03 driver -> ../../../../bus/cpu/drivers/processor
lrwxrwxrwx 1 root root    0 Mar  1 15:03 firmware_node -> ../../../LNXSYSTM:00/LNXCPU:00
drwxr-xr-x 2 root root    0 Mar  1 15:03 hotplug
lrwxrwxrwx 1 root root    0 Mar  1 15:03 node0 -> ../../node/node0
drwxr-xr-x 2 root root    0 Mar  1 15:03 power
lrwxrwxrwx 1 root root    0 Mar  1 15:02 subsystem -> ../../../../bus/cpu
drwxr-xr-x 2 root root    0 Mar  1 15:03 topology
-rw-r--r-- 1 root root 4096 Mar  1 15:02 uevent
```
No `cpufreq`.
The same applies to CentOS 7 and Ubuntu 18 VMs.

**Comment by chemamartinez** [comment]
Hi @vikman90 ,

PR #2740 has been merged. The solution it applies is to check if the MHz value is zero when inserting the data by Wazuh DB.

I think this is the simplest way to avoid the error in case the value is zero, without changing schemas and migrating tables.

On the other side, the frequency information cannot be read from `/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq` because that file is missing in most OS.

Please, let us know if that solution works for you and close both issues if you consider. Otherwise, we can discuss another solution for solving the issue.

Regards.
