### ISSUE TITLE
Post release tasks for 4.10.0

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#27381]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.10.0.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.10.1-into-4.10.2`.

## Tasks

- [ ] Merge branch `4.10.1` into branch `4.10.2`.
- [ ] Merge branch `4.10.2` into branch `4.10.3`.
- [ ] Publish GitHub release as latest.
- [ ] Delete all stage pre-releases for 4.10.1 (https://github.com/wazuh/wazuh/releases).
- [ ] Delete all stage tags for v4.10.1. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.10.1-rc1, 4.10.1-alpha1, etc.
