### ISSUE TITLE
Support new Wazuh version 4.12.0

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#27402]
# Description

This issue attempts to support a new version 4.12.0 in the Wazuh system. It includes tracking the generation of issues, projects, and numbered branches across all repositories.

# Tasks
Each task must be completed sequentially based on numbering. Tasks within the same subsection might be parallelized.

## 1. Open release tracking project  -> @juliamagan
- [x] Release 4.12.0

### wazuh-qa -> @wazuh/devel-qa
- https://github.com/wazuh/wazuh-qa/issues/5860
### wazuh-jenkins -> @wazuh/devel-qa
- https://github.com/wazuh/wazuh-jenkins/issues/7102
### wazuh-automation -> @wazuh/devel-devops
- https://github.com/wazuh/wazuh-automation/issues/2015
### wazuh -> @wazuh/devel-cppserver
- https://github.com/wazuh/wazuh/issues/27401
### wazuh-ansible -> @wazuh/devel-devops
- https://github.com/wazuh/wazuh-ansible/issues/1484
### wazuh-docker -> @wazuh/devel-devops
- https://github.com/wazuh/wazuh-docker/issues/1657
### wazuh-puppet -> @wazuh/devel-devops
- https://github.com/wazuh/wazuh-puppet/issues/1198
### wazuh-kubernetes -> @wazuh/devel-devops
- https://github.com/wazuh/wazuh-kubernetes/issues/929
### wazuh-dashboard-plugins -> @wazuh/devel-dashboard
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/7216
### wazuh-documentation -> @wazuh/devel-qa
- https://github.com/wazuh/wazuh-documentation/issues/8062
### qa-integration-framework -> @wazuh/devel-pyserver
- https://github.com/wazuh/qa-integration-framework/issues/278
### wazuh-security-dashboards-plugin -> @wazuh/devel-dashboard
- https://github.com/wazuh/wazuh-security-dashboards-plugin/issues/155
### wazuh-indexer -> @wazuh/devel-indexer
- https://github.com/wazuh/wazuh-indexer/issues/612
### wazuh-agent -> @wazuh/devel-agent
- https://github.com/wazuh/wazuh-agent/issues/458
### wazuh-indexer-plugins -> @wazuh/devel-indexer
- https://github.com/wazuh/wazuh-indexer-plugins/issues/199
### wazuh-agent-packages -> @wazuh/devel-agent
- https://github.com/wazuh/wazuh-agent-packages/issues/173
### wazuh-dashboard -> @wazuh/devel-dashboard
- https://github.com/wazuh/wazuh-dashboard/issues/462
### wazuh-virtual-machines -> @wazuh/devel-devops
- https://github.com/wazuh/wazuh-virtual-machines/issues/139
### wazuh-installation-assistant -> @wazuh/devel-devops
- https://github.com/wazuh/wazuh-installation-assistant/issues/179
### wazuh-qa-automation -> @wazuh/devel-qa
- https://github.com/wazuh/wazuh-qa-automation/issues/607

## 3. Create AWS resources  -> @wazuh/devel-qa

- [x] All AWS resources should be regenerated using the Procedure_ecs_task_tier pipeline on branches that have been modified/bumped.
  - [x] 4.12.0 https://jenkins-staging.qa.wazuh.info/job/procedure_ecs_task_tier/13/

## 4. Create unattended resources  -> @wazuh/devel-devops
- [x] ~~Create repositories for 4.12.0 in packages-dev to support unattended installer. [Reference](https://github.com/wazuh/wazuh-jenkins/issues/5417#issuecomment-1648346363)~~ https://github.com/wazuh/wazuh/issues/27402#issuecomment-2559894620

**Comment by c-bordon** [comment]
Since version 4.9.0, manual copying of the wizard files is no longer being performed, the workflow that publishes the scripts should be responsible for creating the necessary subdirectories.

**Comment by hossam1522** [comment]
LGTM!
