### ISSUE TITLE
Support new Wazuh version 4.11.0

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#27400]
# Description

This issue attempts to support a new version 4.11.0 in the Wazuh system. It includes tracking the generation of issues, projects, and numbered branches across all repositories.

# Tasks
Each task must be completed sequentially based on numbering. Tasks within the same subsection might be parallelized.

## 1. Open release tracking project  -> @juliamagan
- [x] Release 4.11.0

### wazuh-qa -> @wazuh/devel-qa
- https://github.com/wazuh/wazuh-qa/issues/5859
### wazuh-jenkins -> @wazuh/devel-qa
- https://github.com/wazuh/wazuh-jenkins/issues/7101
### wazuh-automation -> @wazuh/devel-devops
- https://github.com/wazuh/wazuh-automation/issues/2014
### wazuh -> @wazuh/devel-cppserver
- https://github.com/wazuh/wazuh/issues/27399
### wazuh-ansible -> @wazuh/devel-devops
- https://github.com/wazuh/wazuh-ansible/issues/1483
### wazuh-docker -> @wazuh/devel-devops
- https://github.com/wazuh/wazuh-docker/issues/1656
### wazuh-puppet -> @wazuh/devel-devops
- https://github.com/wazuh/wazuh-puppet/issues/1197
### wazuh-kubernetes -> @wazuh/devel-devops
- https://github.com/wazuh/wazuh-kubernetes/issues/928
### wazuh-dashboard-plugins -> @wazuh/devel-dashboard
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/7215
### wazuh-documentation -> @wazuh/devel-qa
- https://github.com/wazuh/wazuh-documentation/issues/8061
### qa-integration-framework -> @wazuh/devel-pyserver
- https://github.com/wazuh/qa-integration-framework/issues/277
### wazuh-security-dashboards-plugin -> @wazuh/devel-dashboard
- https://github.com/wazuh/wazuh-security-dashboards-plugin/issues/154
### wazuh-indexer -> @wazuh/devel-indexer
- https://github.com/wazuh/wazuh-indexer/issues/611
### wazuh-agent -> @wazuh/devel-agent
- https://github.com/wazuh/wazuh-agent/issues/457
### wazuh-indexer-plugins -> @wazuh/devel-indexer
- https://github.com/wazuh/wazuh-indexer-plugins/issues/198
### wazuh-agent-packages -> @wazuh/devel-agent
- https://github.com/wazuh/wazuh-agent-packages/issues/172
### wazuh-dashboard -> @wazuh/devel-dashboard
- https://github.com/wazuh/wazuh-dashboard/issues/461
### wazuh-virtual-machines -> @wazuh/devel-devops
- https://github.com/wazuh/wazuh-virtual-machines/issues/138
### wazuh-installation-assistant -> @wazuh/devel-devops
- https://github.com/wazuh/wazuh-installation-assistant/issues/178
### wazuh-qa-automation -> @wazuh/devel-qa
- https://github.com/wazuh/wazuh-qa-automation/issues/606

## 3. Create AWS resources  -> @wazuh/devel-qa

- [x] All AWS resources should be regenerated using the Procedure_ecs_task_tier pipeline on branches that have been modified/bumped.
  - [x] 4.11.0 https://jenkins-staging.qa.wazuh.info/job/procedure_ecs_task_tier/12/

## 4. Create unattended resources  -> @wazuh/devel-devops
- [x] ~~Create repositories for 4.11.0 in packages-dev to support unattended installer. [Reference](https://github.com/wazuh/wazuh-jenkins/issues/5417#issuecomment-1648346363)~~ https://github.com/wazuh/wazuh/issues/27400#issuecomment-2559893780

**Comment by c-bordon** [comment]
Since version 4.9.0, manual copying of the wizard files is no longer being performed, the workflow that publishes the scripts should be responsible for creating the necessary subdirectories.
