### ISSUE TITLE
API Flask: Generate packages

### ISSUE THREAD

**Issue by druizz90** [wazuh/wazuh#2817]
Hi team,

It is necessary to generate packages for the new API (new API is included into `wazuh-manager` package).

#### Tasks

- Generate `RPM` package:
    - [x] Clean install.
    - [x] Upgrade without `wazuh-api` installed.
    - [ ] Upgrade with `wazuh-api` installed:
        - [ ] Check that `config.js` is migrated properly.
        - [ ] Check that `SSL` certificates are migrated properly.

- Generate `DEB` package:
    - [ ] Clean install.
    - [ ] Upgrade without `wazuh-api` installed.
    - [ ] Upgrade with `wazuh-api` installed:
        - [ ] Check that `config.js` is migrated properly.
        - [ ] Check that `SSL` certificates are migrated properly.

**Comment by crd1985** [comment]
Deprecated
