### ISSUE TITLE
Fluent forwarder for agents

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#2828]
|Branch|
|---|
|[4.0-fluent](https://github.com/wazuh/wazuh/compare/4.0...4.0-fluent)|

Implement a feature that shall forward logs from a socket to a Fluentd server.

## Supported Fluent plugins

- [forward](https://docs.fluentd.org/v0.12/articles/in_forward)
- [secure_forward](https://docs.fluentd.org/v0.12/articles/in_secure_forward)

## Option set

|Option|Value|Default|Required|Description|
|---|---|---|---|---|
|**enabled**|`yes`, `no`|`yes`|No|Enable or disable this feature.|
|**tag**|String|None|Yes|Tag name associated to all logs.|
|**socket_path**|Path (string)|None|Yes|Path to the listening socket.|
|**address**|IP or domain|`localhost`|No|Address of the Fluentd server.|
|**port**|Integer [0..65535]|`24224`|No|Listening port of the Fluentd server.|
|**shared_key**|String|None|No *|A shared key known by the Fluentd server for authentication.|
|**ca_file**|Path (string)|None|No|Path to a CA certificate file to validate the server (secure mode only).|
|**user**|String|None|No|User name for authentication (secure mode only).|
|**password**|String|None|No **|User password for authentication (secure mode only).|
|**timeout**|Integer [1..9000]|0|No|Timeout in seconds for sending and receiving from fluentd|

(*) Defining _shared_key_ enables the secure (TLS) mode.
(**) A *password* is required if *user* is defined.

### Example

```xml
<fluent_forward>
  <enabled>yes</enabled>
  <socket_path>/var/run/fluent.sock</socket_path>
  <address>fluent.server.com</address>
  <port>24224</port>
  <shared_key>secret_string</shared_key>
  <ca_file>/root/certs/fluent.crt</ca_file>
  <user>foo</user>
  <password>bar</password>
</fluent_forward>
```

## References

- [Forward Protocol specification](https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v1)
- [msgpack C version user guide](https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v1)

## Subtasks

- [X] Implement a PoC of the Fluent Protocol in Python for plain forwarding mode.
- [X] Implement a PoC of the Fluent Protocol in Python for TLS mode.
- [X] Implement the socket listener.
- [X] Add _msgpack-c_ to the external library.
- [X] Implement the Fluent forwarder for plain forwarding mode.
- [x] Implement the Fluent forwarder for TLS mode.
- [x] Install the C code as a module in _wazuh-modulesd_.
- [x] Implement the option parser.
- [x] Implement the setting dumper.
- [x] Fill documentation.
- [x] Unit tests.

**Comment by vikman90** [comment]
## Follow up

The implementation of the forwarder and authentication algorithm has been completed.

### Next step 
Test option combinations and create a Wazuh module to handle this feature.

**Comment by TJOSERAFAEL** [comment]
Hi @vikman90 ,

the development of the module continues on this branch: https://github.com/wazuh/wazuh/tree/4.0-fluent-modulesd

Regards.

**Comment by snaow** [comment]
Testing phase, issue: https://github.com/wazuh/wazuh/issues/2992

**Comment by TJOSERAFAEL** [comment]
Merged at https://github.com/wazuh/wazuh/pull/2929
