### ISSUE TITLE
Flask API: Implement Decoders endpoints

### ISSUE THREAD

**Issue by mgmacias95** [wazuh/wazuh#2848]
This issue is part of #2640.

Pending Decoders endpoints to implement:
- [x] GET/decoders https://github.com/wazuh/wazuh/commit/66343f5b90a580b66148b0f36078cda1f56e1afb
- [x] GET/decoders/{decoder_name} 2e5999ee121237f17a0a913de1e19327159b089a
- [x] GET/decoders/files a4f08df2f6fb6e7fcc66756705bf2128e2420240
- [x] GET/decoders/parents c2493efefcf06ded83144c812fca9a13924a6bf0

**Comment by mgmacias95** [comment]
## Update summary
All endpoints have already been implemented. A new endpoint `/decoders/download` has been added to remove `download` parameter from `/decoders/files` endpoint.

### Stoppers
* `search` and `sort` aren't correctly parsed. I'm waiting for #2846 to be merged so I can add the parsers in these endpoints too.
* `/decoders/download` always returns an `application/json`  object despite it must return an `application/xml`. This is a known bug in Connexion (https://github.com/zalando/connexion/issues/840).

**Comment by davidjiglesias** [comment]
Status update
## Summary
Today I've finished the implementation of the decoders_controller and the integration tests for the decoders endpoints.

## Tasks
* [3h] Implement and check decoders controllers and framework behaviour
* [6h] Implement and run integration tests for decoders endpoints
* [2h] Solve difficulties

## Difficulties
* Problems with `regex` key in the responses. The spec had it defined as a `string`, however, sometimes two regexes lines were beind read from the xml and thus added as an `array`. We solved this by always returning the regex field inside an array.
* `accumulate` field in the response keys is always a None. This field only appears in one decoder.
## Tests performed
```
============================= test session starts ==============================
platform linux -- Python 3.7.2, pytest-4.4.1, py-1.8.0, pluggy-0.9.0
rootdir: /var/ossec/framework/python/bin
plugins: tavern-0.26.3
collected 15 items                                                             

test/test_syscheck_endpoints.tavern.yml ...............                  [100%]

=============================== warnings summary ===============================
/var/ossec/framework/python/lib/python3.7/site-packages/PyYAML-3.13-py3.7-linux-x86_64.egg/yaml/constructor.py:126
  /var/ossec/framework/python/lib/python3.7/site-packages/PyYAML-3.13-py3.7-linux-x86_64.egg/yaml/constructor.py:126: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

test/test_syscheck_endpoints.tavern.yml::GET /syscheck/{agent_id}
  /var/ossec/framework/python/lib/python3.7/site-packages/jwt/api_jwt.py:81: DeprecationWarning: It is strongly recommended that you pass in a value for the "algorithms" argument when calling decode(). This argument will be mandatory in a future version.
    DeprecationWarning

-- Docs: https://docs.pytest.org/en/latest/warnings.html
==================== 15 passed, 2 warnings in 0.98 seconds =====================
```
## Pending
Implement cache if endpoint requires it
Implement and run integration test for remaining endpoints

**Comment by davidjiglesias** [comment]
Status update
## Summary
Today I've finished the refactoring and implementation of GET /decoders/download endpoint.

## Tasks
* [3h] Refactor and implement new GET /decoders/download endpoint
* [0.5h] Refactor exception handling
* [0.5h] Update and run integration tests for decoders endpoints

## Difficulties
* Adapting old GET /decoders/files?download endpoint to GET /decoders/download with python and maintaining content-type:application/xml for response
## Tests performed
* API request:
```
root@320fec22e2a1:/# curl "http://localhost:55000/decoders/files?download=local_decoder.xml"
<!-- Local Decoders -->

<!-- Modify it at your will. -->
<!-- Copyright (C) 2015-2019, Wazuh Inc. -->

<!--
  - Allowed static fields:
  - location   - where the log came from (only on FTS)
  - srcuser    - extracts the source username
  - dstuser    - extracts the destination (target) username
  - user       - an alias to dstuser (only one of the two can be used)
  - srcip      - source ip
  - dstip      - dst ip
  - srcport    - source port
  - dstport    - destination port
  - protocol   - protocol
  - id         - event id
  - url        - url of the event
  - action     - event action (deny, drop, accept, etc)
  - status     - event status (success, failure, etc)
  - extra_data - Any extra data
-->

<decoder name="local_decoder_example">
    <program_name>local_decoder_example</program_name>
</decoder>
```
* API request with wrong file:
```
root@320fec22e2a1:/# curl "http://localhost:55000/decoders/download?file=local_decoder.xmls"
{
  "code": 1503,
  "dapi_errors": {
    "master-node": {
      "error": "Decoders file not found",
      "logfile": "WAZUH_HOME/logs/api.log"
    }
  },
  "detail": "Decoders file not found",
  "remediation": "Please, use GET /decoders/files to list all available decoders",
  "status": 400,
  "title": "Wazuh Error",
  "type": "about:blank"
}
```
* API request with wrong permissions on file:
```
root@320fec22e2a1:/# curl "http://localhost:55000/decoders/download?file=local_decoder.xml"
{
  "code": 1502,
  "dapi_errors": {
    "master-node": {
      "error": "Error reading decoders file: WAZUH_HOME/etc/decoders/local_decoder.xml",
      "logfile": "WAZUH_HOME/logs/api.log"
    }
  },
  "detail": "Error reading decoders file: WAZUH_HOME/etc/decoders/local_decoder.xml",
  "remediation": "Please, make sure you have read permissions on the file",
  "status": 400,
  "title": "Wazuh Error",
  "type": "about:blank"
}
```
* Integration tests
```
========================================== test session starts ===========================================
platform linux -- Python 3.7.2, pytest-4.4.2, py-1.8.0, pluggy-0.11.0 -- /var/ossec/framework/python/bin/python3.7
cachedir: .pytest_cache
rootdir: /var/ossec/framework/python/bin
plugins: tavern-0.26.3
collected 23 items                                                                                       

test/test_decoders_endpoints.tavern.yaml::GET /decoders PASSED                                     [  4%]
test/test_decoders_endpoints.tavern.yaml::GET /decoders[file] PASSED                               [  8%]
test/test_decoders_endpoints.tavern.yaml::GET /decoders[path] PASSED                               [ 13%]
test/test_decoders_endpoints.tavern.yaml::GET /decoders[name] PASSED                               [ 17%]
test/test_decoders_endpoints.tavern.yaml::GET /decoders[position] PASSED                           [ 21%]
test/test_decoders_endpoints.tavern.yaml::GET /decoders[status] PASSED                             [ 26%]
test/test_decoders_endpoints.tavern.yaml::GET /decoders/{decoder_name} PASSED                      [ 30%]
test/test_decoders_endpoints.tavern.yaml::GET /decoders/{decoder_name}[file] PASSED                [ 34%]
test/test_decoders_endpoints.tavern.yaml::GET /decoders/{decoder_name}[path] PASSED                [ 39%]
test/test_decoders_endpoints.tavern.yaml::GET /decoders/{decoder_name}[name] PASSED                [ 43%]
test/test_decoders_endpoints.tavern.yaml::GET /decoders/{decoder_name}[position] PASSED            [ 47%]
test/test_decoders_endpoints.tavern.yaml::GET /decoders/{decoder_name}[status] PASSED              [ 52%]
test/test_decoders_endpoints.tavern.yaml::GET /decoders/files PASSED                               [ 56%]
test/test_decoders_endpoints.tavern.yaml::GET /decoders/files[file] PASSED                         [ 60%]
test/test_decoders_endpoints.tavern.yaml::GET /decoders/files[path] PASSED                         [ 65%]
test/test_decoders_endpoints.tavern.yaml::GET /decoders/files[status] PASSED                       [ 69%]
test/test_decoders_endpoints.tavern.yaml::GET /decoders/parents PASSED                             [ 73%]
test/test_decoders_endpoints.tavern.yaml::GET /decoders/parents[file] PASSED                       [ 78%]
test/test_decoders_endpoints.tavern.yaml::GET /decoders/parents[name] PASSED                       [ 82%]
test/test_decoders_endpoints.tavern.yaml::GET /decoders/parents[path] PASSED                       [ 86%]
test/test_decoders_endpoints.tavern.yaml::GET /decoders/parents[position] PASSED                   [ 91%]
test/test_decoders_endpoints.tavern.yaml::GET /decoders/parents[status] PASSED                     [ 95%]
test/test_decoders_endpoints.tavern.yaml::GET /decoders/download PASSED                            [100%]

============================================ warnings summary ============================================
/var/ossec/framework/python/lib/python3.7/site-packages/yaml/constructor.py:126
  /var/ossec/framework/python/lib/python3.7/site-packages/yaml/constructor.py:126: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    if not isinstance(key, collections.Hashable):

test/test_decoders_endpoints.tavern.yaml::GET /decoders
  /var/ossec/framework/python/lib/python3.7/site-packages/jwt/api_jwt.py:81: DeprecationWarning: It is strongly recommended that you pass in a value for the "algorithms" argument when calling decode(). This argument will be mandatory in a future version.
    DeprecationWarning

-- Docs: https://docs.pytest.org/en/latest/warnings.html
================================= 23 passed, 2 warnings in 3.78 seconds ==================================
```
## Pending
