### ISSUE TITLE
syscheck hangs analyzing /dev/core

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#3007]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.7.2 | Agent| Packages | CentOS 7 |

Hello team,
syscheck scan stops when analyzing `/dev/core` and the link that it follows: `/proc/kcore`.
For these two files syscheck completely hangs at 100% CPU.

For `/proc/kmsg` syscheck stops analyzing files, but rootcheck keeps working and no abnormal use of CPU can be seen. In one of my tests I saw syscheck daemon wasn't running anymore, but I haven't been able to reproduce it again.

### Tasks
- [x] Ignore by default conflictive filesystems: `/proc`, `/sys` and `/dev` (3e081d3da6ece18c19a4a4a48b7b4c704c0ff36a and 26c854466d9009630f3ca2ee853066770442e2b9)
- [x] Don't calculate the hash of empty files (e1b04c4e9eeb6a6fe06a2a834b469925ca6a7fc1)
- [x] Don't calculate the hash of files bigger than `syscheck.file_max_size` (e1b04c4e9eeb6a6fe06a2a834b469925ca6a7fc1)
- [x] Set a _timeout_ when reading files to calculate its hash (acf3aea5b3d70b19949a63e922adbb09f984744c)
- [x] Prevent alerts when performing the system call `stat` to check file properties in conflictive filesystems because its `atime`, `mtime` and `ctime` are modified (f98754154e00d372ec1213da8d58096bb790acb0)
- [x] Solve the `size` conflict of files in conflictive filesystems. The number of bytes read, sometimes, isn't equal to the size returned by the `stat` system call (e1b04c4e9eeb6a6fe06a2a834b469925ca6a7fc1)

Development branch: [`fix-syscheck-block`](https://github.com/wazuh/wazuh/tree/fix-syscheck-block).

**Comment by chemamartinez** [comment]
Working on it right now.

Investigating the issue deeper, I have realized those files are considered regular files for the Syscheck module. The `stat` command used to check the file type returns correct information from the files `/proc/kmsg` and `/proc/kcores`:

```
# stat /proc/kmsg
  File: /proc/kmsg
  Size: 0         	Blocks: 0          IO Block: 1024   regular empty file
Device: 4h/4d	Inode: 4026532032  Links: 1
Access: (0400/-r--------)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-03-26 11:02:18.039981249 -0700
Modify: 2019-03-26 11:02:18.039981249 -0700
Change: 2019-03-26 11:02:18.039981249 -0700
 Birth: -
# stat /proc/kcore
  File: /proc/kcore
  Size: 140737477881856	Blocks: 0          IO Block: 1024   regular file
Device: 4h/4d	Inode: 4026532031  Links: 1
Access: (0400/-r--------)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-04-03 09:58:03.160406252 -0700
Modify: 2019-04-03 09:58:03.160406252 -0700
Change: 2019-04-03 09:58:03.160406252 -0700
 Birth: -
```

The next step for Syscheck in the first scan for those files is to calculate their checksums (MD5, SHA1, and SHA256). This step is failing with two different behaviors for both files.

For `/proc/kmsg` it fails due to the `fread` function never returns. Just here: https://github.com/wazuh/wazuh/blob/399ee9631c5e28a20bd93c045619aec17e083683/src/os_crypto/md5_sha1_sha256/md5_sha1_sha256_op.c#L64

We have to determine the cause of this behavior and control this situation.

For the rest of tested files of `/proc`, the `fread` function always returns an empty buffer and Syscheck keeps hold into an infinite loop. Here we can see some debug logs to understand it better.

```
2019/04/03 10:11:36 ossec-syscheckd: INFO: ~~~ fread returned: buf = , length = 2048
2019/04/03 10:11:36 ossec-syscheckd: INFO: ~~~ fread returned: buf = , length = 2048
2019/04/03 10:11:36 ossec-syscheckd: INFO: ~~~ fread returned: buf = , length = 2048
2019/04/03 10:11:36 ossec-syscheckd: INFO: ~~~ fread returned: buf = , length = 2048
2019/04/03 10:11:36 ossec-syscheckd: INFO: ~~~ fread returned: buf = , length = 2048
2019/04/03 10:11:36 ossec-syscheckd: INFO: ~~~ fread returned: buf = , length = 2048
``` 

We are working on a fix to detect the issued files and ignore them when performing the scans.

Regards.

**Comment by chemamartinez** [comment]
After deeper research, this is the plan to solve this issue as well as avoid the same cases in the future:

- [ ] Implement an internal option for ignoring files by size. This way, we avoid trying to calculate the checksums of large files by error.

- [ ] Implement a timeout when reading files with `fread()`. This way we avoid blocking cases when reading kernel buffers.

- [ ] Ignore issued files by default in the configuration templates. In addition, these specific files will be ignored by default, even though when is missing from the configuration. To monitor critical system files like these ones, it will have to be enabled explicitly `<ignore enabled="no">/proc/kmsg</ignore>`.

The combination of the three approaches should avoid the scan blocking the scan while improving the performance of Syscheck.

Regards.

**Comment by chemamartinez** [comment]
Working on branch: [fix-issue-3007](https://github.com/wazuh/wazuh/tree/fix-issue-3007)

- Ignore files by size -> _Done_ (7b3704cac39b575b1ea45e2c7593648e5a7b526b)

- Timeout when fread() is blocked -> _In progress_ (05ee7aa0882d6ac1f1262fcf6a884070adde2194)

This last task is being debugged because it doesn't work when the timeout expires for more than one file in the same scan. For one file, it works fine by throwing the following error:

```
2019/04/08 12:04:27 ossec-syscheckd: ERROR: Timeout when calling fread() expired for file '/proc/kmsg'
```

But the next failed call to fread() blocks the module. Other options are being thought in parallel.

**Comment by chemamartinez** [comment]
Merged: #3059

**Comment by Cerv1** [comment]
Hi,

We've found a bug in the timeout signal handler that produced a _general protection fault (GPF)_ in the `ossec-syscheckd` daemon after merging #3059.

#### `valgrind` output
```
==26028== Warning: client switching stacks?  SP change: 0x6dcbdd8 --> 0x38df2a7759371825
==26028==          to suppress, use: --max-stackframe=4098040877901568589 or greater
==26028== Thread 2:
==26028== Jump to the invalid address stated on the next line
==26028==    at 0x38DF2A7759371825: ???
==26028==  Address 0x38df2a7759371825 is not stack'd, malloc'd or (recently) free'd
==26028==
==26028==
==26028== Process terminating with default action of signal 11 (SIGSEGV)
==26028==  Bad permissions for mapped region at address 0x38DF2A7759371825
==26028==    at 0x38DF2A7759371825: ???
==26028== Invalid write of size 8
==26028==    at 0x4A246B0: _vgnU_freeres (vg_preloaded.c:59)
==26028==  Address 0x38df2a775937181d is not stack'd, malloc'd or (recently) free'd
==26028==
==26028==
==26028== Process terminating with default action of signal 11 (SIGSEGV)
==26028==  General Protection Fault
==26028==    at 0x4A246B0: _vgnU_freeres (vg_preloaded.c:59)
==26028==
==26028== HEAP SUMMARY:
...
==26028== LEAK SUMMARY:
...
```

#### `gdb` trace
```
(gdb) info thread
  Id   Target Id         Frame
  4    Thread 0x7f26e7bbe800 (LWP 18762) 0x00007f26e695ef8d in read () from /lib64/libc.so.6
  3    Thread 0x7f26e5e5b700 (LWP 18891) 0x00007f26e68a60f0 in __longjmp () from /lib64/libc.so.6
  2    Thread 0x7f26e665c700 (LWP 18763) 0x00007f26e6964f73 in select () from /lib64/libc.so.6
• 1    Thread 0x7f26e565a700 (LWP 32397) 0x00007f26e6934e2d in nanosleep () from /lib64/libc.so.6
```
The 4th thread is in `w_fread_timeout` 
```
(gdb) f    4
#4  0x00000000004543f7 in w_fread_timeout (ptr=0x7ffe9e62f0c0, size=1, nitems=2048, stream=0xb65e50, timeout=5)    at shared/file_op.c:2959
```
and the 3rd thread jumps out of its memory map using `longjmp`
```
[Switching to thread 3 (Thread 0x7f26e5e5b700 (LWP 18891))]
#0  0x00007f26e68a60f0 in __longjmp () from /lib64/libc.so.6
(gdb) f    0
#0  0x00007f26e68a60f0 in __longjmp () from /lib64/libc.so.6
(gdb) f    1
#1  0xe88cf15ea094860f in ?? ()
(gdb) f    2
Cannot access memory at address 0xe88cf15ea094860f
```

----
The problem was that the `alarm()` function sends a signal to `ossec-syscheckd` and this doesn't guarantee that the thread which will attend this signal is the one that produced the timeout, so another thread could replace its heap location and provoke the _GPF_ failure.

Credits to @snaow, @vikman90 and @chemamartinez for the research.

Regards,
Cerv1.

**Comment by Cerv1** [comment]
Hi all,

I will detail the changes that will be implemented to fix this issue in the following task list.

- [ ] Ignore by default conflictive filesystems: `/proc`, `/sys` and `/dev`.
- [ ] Don't calculate the hash of empty files.
- [ ] Don't calculate the hash of files bigger than `syscheck.file_max_size`
- [ ] Set a _timeout_ when reading files to calculate its hash.
- [ ] Prevent alerts when performing the system call `stat` to check file properties in conflictive filesystems because its `atime`, `mtime` and `ctime` are modified.
- [ ] Solve the `size` conflict of files in conflictive filesystems. The number of bytes read, sometimes, isn't equal to the size returned by the `stat` system call.

Best regards,
Cerv1.

**Comment by Cerv1** [comment]
### Some attributes will be ignored for files under `/proc`
Hi all,

After doing some research, we've decided to ignore the `atime`, `mtime` and `ctime` of the files located under the `/proc` directory.

#### Why?
We've noticed that using `stat` on these files modifies the `atime`, `mtime` and `ctime` attributes. This behavior isn't reproducible every time. We've tested on multiple operating systems and sometimes the ' stat` function modifies these attributes and sometimes not. The problem is that _FIM_ needs to `stat` these files to check these times and if they change constantly, FIM will generate modification alerts.

#### Conclusion
After reading [this post](https://bugzilla.redhat.com/show_bug.cgi?id=155658) of Stephen Tweedie, we've decided to ignore these attributes under the `procfs` filesystem because they aren't relevant. 

>_The files in /proc have no existence of their own.  They are ephemera, invented_
>_on the spur of the moment when you look at them, forgotten once you look away._
>_The only time that has any meaning for those files is "right now"._

Regards,
Cerv1.

**Comment by Cerv1** [comment]
Hi team,

This issue has been blocked because of #3319. 

The algorithm has been redesigned and therefore this problem has been solved from a different approach. The implementation of this fix it's valid only for the current FIM algorithm.

Best regards,
Cerv1.

**Comment by vikman90** [comment]
Implemented in #3319.
