### ISSUE TITLE
SCA: report non-applicable checks

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#3029]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9.0 | Manager/Agent | Packages/Sources | All |

Currently, the SCA scanner reports all the checks with passed or failed results only. This may derivate in falses positives when any rule has been unable to be scanned for any reason:

- The file to scan is not present.
- Permissions to read a file or registry.
- Command execution timeout.
- Any other cause.

In these cases, we cannot mark that check as passed, instead, we are going to create a new state called `not applicable` supported by a reason when possible of that status. Here we can see an event example of this situation:

```
{
  "id": 1575131405,
  "type": "check",
  "policy": "CIS benchmark for Debian/Linux",
  "policy_id": "cis_debian",
  "check": {
    "id": 5038,
    "title": "Ensure SSH PermitEmptyPasswords is disabled",
    "description": "The PermitEmptyPasswords parameter specifies if the SSH server allows login to accounts with empty password strings.",
    "rationale": "Disallowing remote shell access to accounts that have an empty password reduces the probability of unauthorized access to the system",
    "remediation": "Edit the /etc/ssh/sshd_config file to set the parameter as follows: PermitEmptyPasswords no",
    "compliance": {
      "cis_csc": "16.3",
      "cis": "5.2.11",
      "pci_dss": "4.1"
    },
    "file": "/etc/ssh/sshd_config",
    "status": "not applicable",
    "reason": "File not found"
  }
}
```

As we can see, the `result` field is missing in favor of `status` and `reason`.

Procedure
-------------

At the module side:
* Check when a file, directory or registry don't exist or when timeout is returned from running a command. 
* These cases will return a different error code, which will result in two new different fields, `status`, that will have the value 'Not applicable' and `reason`, which states the reason why the check couldn't be run. 
* When these two fields exist, the `result` field won't, as it does not have any sense if the check couldn't be executed.

At the manager side:
* If the check couldn't be run, the `result` field will come empty. 
* The integrity is calculated only with the `result` field. If if comes empty, for example `passed::passed:passed`, it means that the empty value check couldn't be run.
* If `result` is empty, store at the database the fields `status` and `reason`.
* When the check changes from empty `result` to `failed` or `passed`, store this new value at the database and remove `status` and `reason`, and vice versa.

Here is the list of requirements to accomplish this development:

### Tasks

- [x] Caught the error when checking a rule.

- [x] Store the status and reason when an error occurred.

- [x] Don't add this check to the pass/fail list. It doesn't apply to the integrity check based on the check result (which will be missing in this case). That check doesn't count for calculating the score.

- [x] Store new fields into the SCA database.

- [x] Create rules for these new cases.

**Comment by cristgl** [comment]
Working on branch [3.9-sca-status](https://github.com/wazuh/wazuh/tree/3.9-sca-status).

* Check for 'File not found'. [5a855ac](https://github.com/wazuh/wazuh/commit/5a855ac6a103498e43185560a12f89bd5fcc6821)
* Check for 'Error executing command'. [5a855ac](https://github.com/wazuh/wazuh/commit/5a855ac6a103498e43185560a12f89bd5fcc6821)
* Check for 'Insufficient permissions for executing command or invalid path'. [5a855ac](https://github.com/wazuh/wazuh/commit/5a855ac6a103498e43185560a12f89bd5fcc6821)

To do:

* Add a `reason` array to store each invalid check's reason.
* Fix memory leaks.
* Add the `reason` field to the JSON block.

Below is an example of an invalid check event with the current development:

```
{
   "type":"check",
   "id":1740632425,
   "policy":"CIS benchmark for Debian/Linux",
   "policy_id":"cis_debian",
   "check":{
      "id":5000,
      "title":"Check Debian version",
      "description":"Requirements for running the SCA scan against Debian/Ubuntu.",
      "rationale":"-",
      "remediation":"-",
      "compliance":{
         "cis_csc":"5.1",
         "cis":"1.1.2"
      },
      "references":"https://tldp.org/HOWTO/LVM-HOWTO/,https://www.freedesktop.org/wiki/Software/systemd/APIFileSystems/",
      "file":"",
      "status":"Not applicable",
      "reason":"error"
   }
}
```

Its rule check is the next one: 
```
  rules:
    - 'f:/proc/sys/kernel/osstype;'
```

**Comment by cristgl** [comment]
* Add  a `reason` array to store each invalid check's reason. [ef5a469](https://github.com/wazuh/wazuh/commit/ef5a4695d07ca63a4ddf3a535f7fc05cef645a3e).
* Fix memory leaks. [55af7a0](https://github.com/wazuh/wazuh/commit/55af7a0a838251c76d815339a38c5f4d30539424)

**Comment by cristgl** [comment]
* Add directories check. DONE -> [d54478f](https://github.com/wazuh/wazuh/commit/d54478fb4bee198da180d514ebbd8f1897352197)

**Comment by chemamartinez** [comment]
Merged: #3122. Thanks @cristgl !
