### ISSUE TITLE
Improve log rotation

### ISSUE THREAD

**Issue by Cerv1** [wazuh/wazuh#3072]
## Main goal
This issue aims to gather all the problems and feature requests related to log rotation. 

The development of these features will be done in this branch: [`fix-log-compression`](https://github.com/wazuh/wazuh/tree/fix-log-compression)

## Related issues
*  _Wazuh manager is not compressing alerts.json_ (https://github.com/wazuh/wazuh/issues/1302) by @havidarou 
* _log rotation issues_ (https://github.com/wazuh/wazuh/issues/2290) by @rossengeorgiev
* _Allow size-based rotation of ossec.log_ (https://github.com/wazuh/wazuh/issues/2502) by @vikman90 
* lots of errors when log rotation is impossible (https://github.com/wazuh/wazuh/issues/2899) by @okynos 
* _alerts.json should be compressed when is rotated by rotate_interval setting_ (https://github.com/wazuh/wazuh/issues/2919) by @toniMR  
* _Save old alerts.json data for a specific amount of time_ (https://github.com/wazuh/wazuh/issues/2964) by @havidarou 
* _Wazuh manager only compress alerts when it is running_ (https://github.com/wazuh/wazuh/issues/3047) by @Phandora
* #11196
* #12050

## Problems and feature requests
- The option `max_output_size` is not working as expected.
- Prevent `ossec-analysisd` from restarting the counter when deleting old files.
- Prevent `ossec-monitord` from restarting the counter when deleting old files.
- `wazuh-manager` should compress `alerts.log`, `alerts.json`, `archives.log` and `archives.json`.
- Uncompressed files should be removed from the system to save disk space after the compressed file is created.
- Add an option to delete old logs like [logrotate](https://linux.die.net/man/8/logrotate).
- `ossec-agent` throws a lot of errors when restoring a virtual machine a few days later.
- Add an option to choose the compression algorithm (gzip or bzip2).
- The manager should rotate _integrations.log_.
- The file _active_responses.log_ should also get rotated.

Best regards,
Cerv1.

**Comment by Cerv1** [comment]
## Solution overview

- The option `max_output_size` is fixed [here](https://github.com/wazuh/wazuh/commit/3f6b1795941aa88241cfb98e78147763a3d8c42f#diff-22bf29506ec7d1e01a7a1d51a8e2e121R190). The problem was that we didn't update the file position pointer.
- Now we compress every log after it is rotated as it can be seen [here](https://github.com/wazuh/wazuh/blob/3f6b1795941aa88241cfb98e78147763a3d8c42f/src/analysisd/alerts/getloglocation.c#L168).
- The uncompressed logs are removed [here](https://github.com/wazuh/wazuh/commit/997b2d02b1f0748c453c758a67d3d012fcf02aa1#diff-22bf29506ec7d1e01a7a1d51a8e2e121R171).
- The new `internal_option` for `ossec-monitord` will be named `keep_rotated_files`. This option will allow the user to choose to save the rotated logs in a time interval or delete them.

## Examples of configuration
* Rotates each log if it's bigger than 120MB.
```xml
  <global>
    <max_output_size>120M</max_output_size>
  </global>
```
* Rotates each log if it's older than 10h
```xml
  <global>
    <rotate_interval>10h</rotate_interval>
  </global>
```

* Rotates each log if it's bigger than 400MB or older than 12h
```xml
  <global>
    <max_output_size>400M</max_output_size>
    <rotate_interval>1h</rotate_interval>
  </global>
```

* Rotates each log if it's bigger than 50MB or older than 1h. It keeps only the last day's logs.
```
# internal_options.conf
monitord.keep_rotated_files=1440
```
```xml
# ossec.conf
  <global>
    <max_output_size>400M</max_output_size>
    <rotate_interval>12h</rotate_interval>
  </global>
```

**Comment by rossengeorgiev** [comment]
Hi @Cerv1, nice work. Couple of questions:

1. Will `monitord.keep_rotated_files` only apply to alerts.json?  Or archives.json too?
2. Will `monitord.keep_rotated_files` apply to service logs (e.g. `ossec.log`) ?
3. Does it also remove empty directories, and `.sum` files? What about left over `.log` or `.json` files from when the service is down?

**Comment by Cerv1** [comment]
Hello @rossengeorgiev,

> 1. Will monitord.keep_rotated_files only apply to alerts.json? Or archives.json too?
> 2. Will monitord.keep_rotated_files apply to service logs (e.g. ossec.log) ?

It'll be applied to `alerts.json`, `alerts.log`, `archives.json`, `archives.log`,  `ossec.json` and `ossec.log`.

> 3. Does it also remove empty directories, and .sum files? What about left over .log or .json files from when the service is down?

We're still figuring out, but I think it should remove empty directories and all the files older than `keep_rotated_files`. 

Regarding the left over uncompressed logs, I think that when it starts it has to look for all uncompressed files and compress them in order to save disk space if the option `monitord.compress` is enabled. What do you think?

Thank you for your interest, it helps us a lot to know the doubts and needs of our community. Please, do not hesitate to contact us again if you have any questions or suggestions.

Best regards,
Cerv1.

**Comment by rossengeorgiev** [comment]
@Cerv1 thanks for the information. 

> We're still figuring out, but I think it should remove empty directories and all the files older than keep_rotated_files.

I don't think you even have to check the date. 

> Regarding the left over uncompressed logs, I think that when it starts it has to look for all uncompressed files and compress them in order to save disk space if the option monitord.compress is enabled.

That sounds great. Remember to consider the case where there might be many uncompressed files.

**Comment by Cerv1** [comment]
## Solution overview (II)
* The following **internal_options** are going to be deprecated from `ossec-monitord`:
  - `monitord.day_wait` 
  - `monitord.compress` 
  - `monitord.sign`
  - `monitord.rotate_log`
  - `monitord.keep_log_days`
  - `monitord.size_rotate`
  - `monitord.daily_rotations`

[Reference for `internal_options`](https://documentation.wazuh.com/current/user-manual/reference/internal-options.html#monitord).
* We've added two new options to the new `rotation` block:
  - `compress`: Decide whether to compress the logs when rotating or not.
  - `enabled`: Decides whether log rotation is active or not.

This new options **will be enabled by default**.
## New configuration (II)
```xml
<logging>
  <log>
    <enabled>[ yes | no ]</enabled>
    <format>[ json | plain | both ]</format>
    <rotation>
      <enabled>[ yes | no ]</enabled>
      <max_size>[ 0-9 ]* [ M|K|G ]</max_size>
      <interval>[ 0-9 ]* [ h|d|w|m ]</interval>
      <rotate>[ 0-9 ]*</rotate>
      <compress>[ yes | no ]</compress>
    </rotation>
  </log>
  <alerts>
    <enabled>[ yes | no ]</enabled>
    <format>[ json | plain | both ]</format>
    <rotation>
      <enabled>[ yes | no ]</enabled>
      <max_size>[ 0-9 ]* [ M|K|G ]</max_size>
      <interval>[ 0-9 ]* [ h|d|w|m ]</interval>
      <rotate>[ 0-9 ]*</rotate>
      <compress>[ yes | no ]</compress>
    </rotation>
  </alerts>
  <archives>
    <enabled>[ yes | no ]</enabled>
    <format>[ json | plain | both ]</format>
    <rotation>
      <enabled>[ yes | no ]</enabled>
      <max_size>[ 0-9 ]* [ M|K|G ]</max_size>
      <interval>[ 0-9 ]* [ h|d|w|m ]</interval>
      <rotate>[ 0-9 ]*</rotate>
      <compress>[ yes | no ]</compress>
    </rotation>
  </archives>
</logging>
```

**Comment by DaveVG1** [comment]
## Issues checks

These checks keep track of the current resolved issues in the list above (in the related branch of this issue):
- [ ] Wazuh manager is not compressing `alerts.json` (https://github.com/wazuh/wazuh/issues/1302)
- [ ] Log rotation issues (https://github.com/wazuh/wazuh/issues/2290)
- [ ] Allow size-based rotation of ossec.log (https://github.com/wazuh/wazuh/issues/2502)
- [ ] lots of errors when log rotation is impossible (https://github.com/wazuh/wazuh/issues/2899)
- [ ] alerts.json should be compressed when is rotated by rotate_interval setting (https://github.com/wazuh/wazuh/issues/2919)
- [ ] Save old alerts.json data for a specific amount of time (https://github.com/wazuh/wazuh/issues/2964)
- [ ] Wazuh manager only compress alerts when it is running (https://github.com/wazuh/wazuh/issues/3047)

**Comment by DaveVG1** [comment]
## Requirements (Updated 16 September 2019)

As the development seems to be changing I think a deeper requirements specification is need. I propose the following requirements for this issue:

Id. | Name | Description | Priority
-- | -- | -- | --
1 | Rotation coherence | All log (`ossec.log`, `archives.log` and `alerts.log`) should have the same rotation behavior. | 1
2 | Rotation options | There should be different options to rotate logs (rotation by size, interval, etc.). | 1
2.1. | Enable rotation | An option (`enable`) should toogle the log rotation for every log (`ossec.log`, `archives.log` and `alerts.log`). | 1
2.2 | Rotation by `size` | The logs should be able to be rotated by `size`. This option should accept the following values: bytes, kilobytes, megabytes and gigabytes (`B`, `K`, `M` and `G`). The minimum size to rotate should be `1 MB`. The upper limit will be delimited by the **INT_MAX** variable. (#2502) | 1
2.3 | Rotation by `interval` | The logs should be able to be rotated by `interval`. This option should accept the following values: minutes, hours and days (`m`, `h` and `d`). This option will work as indicated in the _**interval example**_*.  | 1
2.4 | Rotation by `maxsize` | The logs should be able to be rotated either by `maxsize` or `interval` (what happens first). Depends on `2.3`. | 1
2.5 | Rotation by `minsize` | The logs should be able to be rotated either by size and interval. The log will be rotated only if it has reached both `minsize` and `interval`. Depends on `2.3`. | 1
2.6 | Maximum rotated logs | An option to indicate the maximum number of rotated logs to keep should exist. Option called `rotate`. | 1
2.7 | Exclusive size options | Only one size rotation option is permitted to be used. This means that if more than one is indicated a configuration error will be prompted. Depends on `2.2`, `2.4` and `2.5`. | 1
2.8 | Log rotation compression | An option should exist to permit the compression (`compress`) of the rotated logs. This compression will be performed right after the log is rotated (#2919). | 1
2.9 | Time to maintain rotated logs | An option (`maxage`) should exist to indicate the specific time (in days) that a rotated log should be maintained (#2964) . | 1
3 | Rotation format | The rotation format will be the following `ossec-TAG-DAY[-COUNTER].FORMAT[.gz]`. For example: `ossec-archive-16-004.json.gz` | 1
3.1 | Rotation format: tag | Each log will have its own TAG (`logs` for `ossec.log`, `archive` for `archives.log` and `alerts` for `alerts.log`. | 1
3.2 | Rotation format: day | The day indicated in the name of the rotated log will be the current day. This first rotation of the next day will still indicate the day before as it has logs from the day before. | 1
3.3 | Rotation format: counter | The counter will indicate if its the first rotation of the day (no counter) or not (the number of rotation in the indicated day). The first rotation of the next day will have the applicable counter. | 1
4 | Documentation | The new options should be added to the documentation to a new section if needed. | 1

**Comment by DaveVG1** [comment]
### Interval rotation (2)

After another iteration of the development of the rotation by `interval` option we've came to the conclusion that the aforementioned behavior could be confusing for the user (having the first rotation outside the specified range).

Another proposed option is the following:

- Accept only divisors of `24h` as the minimum acceptable value (1, 2, 3, 4, 6, 12 hours and daily rotations).
- Adding an option like `start_rotation` that would meant that a rotation is always performed when Wazuh is started (this way we ensure that a rotation is performed, no matter if Wazuh is restarted several times). On the bad side, if, for example, an agent is restarted several times due to a change in centralized configuration we would have several rotated logs.
- Also could accept weekly values, by indicating the day of the week when the rotated will be performed.
- The `minsize` option could be supressed.

Example:

- An interval of `3h` is set. Wazuh is started at `Apr 20 2019 13:45:19`:

Nº | Date | Files
-- | -- | --
1 | Apr 20 2019 15:00:00 | ossec-logs-20.json.gz
2 | Apr 20 2019 18:00:00 | ossec-logs-20-001.json.gz
3 | Apr 20 2019 21:00:00 | ossec-logs-20-002.json.gz
4 | Apr 21 2019 00:00:00 | ossec-logs-20-003.json.gz

**Comment by JPLachance** [comment]
Hello!

I know I'm a little bit out of scope, but is it possible that the Windows agent (3.10.2) on does not support the following configuration:
```XML
  <logging>
    <log_format>plain,json</log_format>
  </logging>
```

On my Windows instance, I see the `ossec.log` file aside the `ossec-agent.exe` file, but the `ossec.json` file never gets created.

Will this refactoring fix the issue?

Thanks!

**Comment by rswestmoreland** [comment]
Did the new logging options ever make it into a release?  The site's documentation does not mention it.

**Comment by vikman90** [comment]
@rswestmoreland we've recently rescued this issue from the icebox. Unfortunately, after such a long time, we will need to re-implement various parts of the code and do a lot of testing.

We've targeted this task to 4.5.0, although we will advance it to 4.4 if possible.

Best regards.

**Comment by zbalkan** [comment]
Generally, the logging and retention is handled in two phases in most enterprises, especially the ones who have to comply with PCI-DSS and such:

- Log anything you can.
- Set a retention period (_RP1_) for the usable/queryable logs that regulations require, generally 30 days.
- Compress the logs older than _RP1_ and move to an archive location. It is generally a file server, SAN, mounted as `/archive` etc.
- Set a retention period (_RP2_) for the minimum period that regulations require, generally 6 months or a year.
- Remove all compressed logs after _RP2_.
- Log the compression and removal processes too.

In Wazuh, `.log` files can be handled this way by improving the `ossec.conf` and the feature that is in the roadmap. But handling the Elasticsearch indexed logs also needs to obey _RP1_ and _RP2_. 

This feature is important to prove the data retention. Yet, it needs the configuration files to prove that periods are set. Then there must be audit logs for the daily running tasks, if they succeeded or failed. finally, there must be a way to query that there is no log file under `/var/ossec/logs/alert` before `today - RP1`, no compressed/archived log file in `/archive` before `today - RP2`. for the last one we add `find /var/ossec/logs/alert -mtime +30 -print` and `find /archive -mtime +30 -print` to the end of our scripts to ensure they succeeded. For all of these, we generally use bash, perl or python scripts. It is generally a one time thing but it needs to be maintained per each server.

**Comment by sara-hann** [comment]
Is there any data retention policy currently? Did this ever get implemented? If not, would it be possible to list here all the directories to which wazuh manager would generate files, so that I can set up a cronjob or something to delete files older than x days in each directory?

**Comment by zbalkan** [comment]
I wanted to add another point here. In order to make Wazuh servers stateless, I mounted an NFS drive to `/var/ossec/logs/archives` and `/var/ossec/logs/alerts` paths. But we were afraid of concurrency issues, like multiple node trying to create new directory, compares and sign files in the midnight. They may be non-issues since we did not even try. But with new features, it is possible to present new conditions. 

So the "multiple nodes one file share" scenario worth a test for edge cases like race conditions.

**Comment by vikman90** [comment]
@sara-hann data retention is currently implemented for the product's log only (_logs/wazuh_). One of the subtasks (https://github.com/wazuh/wazuh/issues/2964) is to address just this matter.

**Comment by vikman90** [comment]
@zbalkan currently, the manager assumes that all subfolders in _logs_are in the same mount point and are written exclusively by one manager. Here is an important difference between _ossec.log_ event logs.

### Product's log (ossec.log)

- For each log, the product opens _ossec.log_, adds a new line and closes it.
- On rotation, _ossec.log_ is moved to the corresponding file inside _logs/wazuh_.

### Event logs (alerts, archives, and firewall)

- Analysisd creates the corresponding files inside _logs/alerts_, _logs/archives_, and _logs/firewall_.
  - It holds them open until the next rotation.
  - _logs/archives.json_, _logs/archives.log_, _logs/alerts.json_, _logs/alerts.log_,, and _logs/firewall.log_ are **hard links** to the original files. That is why they must be in the same partition.
- On rotation, new files get created. Then Analysisd updates the hard links.

Due to this, multiple managers can't access the same _logs_ folder. Otherwise, files will be overwritten, and only one of the files by each manager will persist. We expect that there is one instance of Filebeat in each manager, this way they will forward all the events (alerts/archives) to Wazuh Indexer.

**Comment by zbalkan** [comment]
Currently, even if we have only plaintext files, log rotation process assumes JSON logs exists and tries to generate a checksum. Eventually, we end up one with `*.json.sum` file per Wazuh server per day. 

So for each day we will have:
- *.log.gz (correct compressed plaintext log)
- *.log.sum (correct checksum)
- *.json.sum (incorrectly generated checksum)


![image](https://github.com/wazuh/wazuh/assets/39981909/70f77cc6-0c3e-45ab-8d63-17b96507284b)

This is a simple problem which can be solved without waiting for a new major release.

**Comment by vikman90** [comment]
Closing this issue as it will be superseded by version 5.0.
