### ISSUE TITLE
Add 'hash_file' field to SCA endpoints

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#3154]
A new field `hash_file` has been created in table `sca_policy` for SCA module (#3099), so we need to review and readapt the framework code in order to show its value in API endpoint (GET/sca/:agent_id).

I suggest changing the dictionary in https://github.com/wazuh/wazuh/blob/219b69e3e1f316dfc1ca818d8adff212d3a6338a/framework/wazuh/security_configuration_assessment.py#L19 to include the new field.

Tasks:
* [x] Modify framework code [Solved: #3157 ]
* [x] Readapt unit tests if necessary
* [x] Test API
* [x] Review API doc [Solved:  wazuh/wazuh-api/pull/375 ]

**Comment by AdriiiPRodri** [comment]
# Status update
## Summary
Added hash_file field in GET /sca/:agent_id
It has been tested, unit tests have been passed and the documentation has been updated.

## Tasks
* [1.0h] Add and test after the  modification

## Difficulties
* Understanding api in node

## Tests performed
### Unittests
```bash
root@b2225824f222:/wazuh/framework/wazuh/tests# /var/ossec/framework/python/bin/pytest test_security_configuration_assessment.py 
============================================================= test session starts ==============================================================
platform linux -- Python 3.7.2, pytest-4.4.1, py-1.8.0, pluggy-0.9.0
rootdir: /wazuh/framework
collected 5 items                                                                                                                              

test_security_configuration_assessment.py .....                                                                                          [100%]

=========================================================== 5 passed in 0.25 seconds ===========================================================
```
### Test
```bash
curl -u foo:bar -X GET "http://localhost:55000/sca/000?pretty"
...
{
            "score": 100,
            "policy_id": "system_audit",
            "fail": 0,
            "pass": 16,
            "end_scan": "2019-04-23 08:27:43",
            "start_scan": "2019-04-23 08:27:43",
            "description": "Guidance for establishing a secure configuration for web-related vulnerabilities.",
            "name": "System audit for web-related vulnerabilities",
            "hash_file": "f2323962b52c2cc1aa0c53a34871aabe242d571af423a33f831bd77336822f58"
}
...
```
