### ISSUE TITLE
Refactor the SCA internal logic engine

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#3249]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v3.9.0 | SCA | Agent | All | All |

Currently, the logic to determine if a check is `passed` or `failed` in the SCA module is inverted. Let's see it with an example:

```
- id: 10577
   title: "Set SSH Protocol to 2"
   description: "SSH supports two different and incompatible protocols: SSH1 and SSH2. SSH1 was the original protocol and was subject to security issues. SSH2 is more advanced and secure."
   rationale: "SSH v1 suffers from insecurities that do not affect SSH v2."
   remediation: "Edit the /etc/ssh/sshd_config file to set the parameter as follows: Protocol 2"
   compliance:
    - cis: "9.3.1"
   condition: any
   rules:
     - 'f:/etc/ssh/sshd_config -> IN !r:^# && r:Protocol 1;'
     - 'f:/etc/ssh/sshd_config -> !r:^Protocol 2$;'
```

We want to ensure the SSH protocol is set to 2 instead of 1. The rule to mark this check to `pass` is to look for the lack of the desired output `protocol 2`. In other words, when the rule matches, the result of the check is fail.

The correct syntax to write this check should be the following one:

```
- id: 5035
   title: "Ensure SSH Protocol is set to 2"
   description: "Older versions of SSH support two different and incompatible protocols: SSH1 and SSH2. SSH1 was the original protocol and was subject to security issues. SSH2 is more advanced and secure."
   rationale: "SSH v1 suffers from insecurities that do not affect SSH v2."
   remediation: "Edit the /etc/ssh/sshd_config file to set the parameter as follows: Protocol 2"
   compliance:
    - cis_csc: "14.4"
    - cis: "5.2.4"
    - pci_dss: "4.1"
   condition: any
   rules:
     - 'f:/etc/ssh/sshd_config -> IN !r:^# && r:Protocol\.+2;'
```

Here, if we found a line which matches with `!r:^# && r:Protocol\.+2`, the check is passed.

On the other side, the use of `IN/NIN` (included or not included) to negate a whole rule makes the rules more complexes to be understood. It will be replaced by `not` to negate a complete rule:

This rule looks for a non-commented line (`!r:^#`) which contains `Protocol\.+2`.
```
- 'f:/etc/ssh/sshd_config -> !r:^# && r:Protocol\.+2;'
```

However, the next rule looks for the opposite (not to find any rule that matches that regex):
```
- 'f:/etc/ssh/sshd_config -> not !r:^# && r:Protocol\.+2;'
```

By default, the `not` operator should be lowercase, but NOT should be supported as well.

The last change for this issue is to remove the final semicolon of every rule, which is unuseful.

### Task summary

- [x] Invert the check logic for the SCA rules

- [x] Replace the `IN/NIN` for `not`

- [x] Remove the semicolon `;` of every rule

- [x] Improve the debug logging

**Comment by JuantAldea** [comment]
Requirements conditions `all/any/none required` are redundant  to `all/any/none` as they are **required** by definition, hence I will be deprecating the "required" modifier, defaulting requirements using them to their equivalent.

**Comment by JuantAldea** [comment]
Tests
For Requirements
- [ ] ALL/ANY/NONE with several checks. With checks returning 0/1/2.
- [ ] ALL/ANY/NONE with a single check. With check returning 0/1/2.

**Comment by JuantAldea** [comment]
We have been discussing about the where to place the `not` operator and we have concluded that the best location is at the beginning of the rule. For example:
```yaml
 - id: 99302
   title: FAIL Test to check if value data is not found
   condition: any
   rules:
     - not r:HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion -> SoftwareType -> System
```

**Comment by JuantAldea** [comment]
- Windows registry rules tested with a testing ruleset [1]
- Tested using Dr Memory on Windows

[1] https://github.com/wazuh/wazuh-qa/blob/master/sca-tests/sca_win_registry_test_suite.yml

**Comment by JuantAldea** [comment]
When checking directory or file lists for existence, the elements are aggregated by an OR

**Comment by JuantAldea** [comment]
- Tested file rules with testing suite [1]
- Valgrind tests on Linux.


[1] https://github.com/wazuh/wazuh-qa/blob/51115cf8742b97e2868f0a45f7fd574954f8a7ff/sca-tests/3.10/sca_files_test_suite.yml

**Comment by JuantAldea** [comment]
Commands
```
DEBUG: Result for check id: 300100 'PASS -- Yield ABC and match it' -> 1
DEBUG: Result for check id: 300101 'FAIL -- Negate yield ABC and match it' -> 0
DEBUG: Result for check id: 300102 'FAIL -- Yield ABC and try to find CBA' -> 0
DEBUG: Result for check id: 300103 'PASS -- Negate yield ABC and try to find CBA' -> 1
DEBUG: Result for check id: 300104 'INVALID -- Command does not exist (will trigger leak reports due to execvp failing)' -> 2
DEBUG: Result for check id: 300105 'INVALID -- Not executable file (will trigger leak reports due to execvp failing)' -> 2
```

**Comment by JuantAldea** [comment]
Whenever a command cannot be executed wm_exec (execvp), several memory leaks will be reported by Valgrind. This leaks are inherited from the parent process and, given that the child dies, the leaked memory is recalled by the operating system.
A POC to reproduce the afore explained behaviour:
```C
#include <unistd.h>
#include <stdlib.h>
#include <sys/wait.h>

/*
 ./leak /bin/cat 
 ./leak /bin/cat123
*/

int main(int argc, char *argv[])
{
    char *leak = calloc(8192, sizeof(char));

    int pid = fork(); 
    
    if (pid == 0) {
        char *args[] ={ "", 0};
       
        /* 
            if exec fails, the process image is not replaced
            so leak is kept and reported by valgrind when the 
            child dies 
        */

        execvp(argv[1], args);
        //free(leak);
        return 0;
    }

    //wait(NULL);
    while (1) { ; }
    free(leak);
    return 0;
}```

**Comment by JuantAldea** [comment]
- Testing the return code of processes is not supported.
- Piped commands are not supported.
Open questions for commands:
- Command rules without a pattern return FOUND directly without executing anything
- Command rules yielding empty output return NOT_FOUND.
Open questions for processes:
- If p_list is null NOT_FOUND is returned. Shouldn't it be INVALID?
- If no value is specified, i.e, a rule such as "p:", NOT_FOUND is returned. Is this correct?

**Comment by JuantAldea** [comment]
Fixed check_process so that it returns INVALID whenever the process list is not available.

**Comment by JuantAldea** [comment]
Fixed rule validation so that systems other than Windows reject registry rules.

**Comment by JuantAldea** [comment]
Added condition and negation validation suites

**Output for aggregation conditions**
```
Result for check id: 800100 'PASS -- ANY on a list [TRUE, TRUE, TRUE]' -> 1
Result for check id: 800101 'PASS -- ANY on a list [TRUE, FALSE, FALSE]' -> 1
Result for check id: 800102 'PASS -- ANY on a list [FALSE, TRUE, FALSE]' -> 1
Result for check id: 800103 'PASS -- ANY on a list [FALSE, FALSE, TRUE]' -> 1
Result for check id: 800104 'FAIL -- ANY on a list [FALSE, FALSE, FALSE]' -> 0
Result for check id: 800105 'INVALID -- ANY on a list [INVALID, INVALID, INVALID]' -> 2
Result for check id: 800106 'INVALID -- ANY on a list [FALSE, INVALID, FALSE]' -> 2
Result for check id: 800107 'PASS -- ANY on a list [FALSE, INVALID, TRUE]' -> 1
Result for check id: 800200 'PASS -- ALL on a list [TRUE, TRUE, TRUE]' -> 1
Result for check id: 800201 'FAIL -- ALL on a list [TRUE, TRUE, FALSE]' -> 0
Result for check id: 800202 'FAIL -- ALL on a list [TRUE, FALSE, TRUE]' -> 0
Result for check id: 800203 'FAIL -- ALL on a list [FALSE, TRUE, TRUE]' -> 0
Result for check id: 800204 'FAIL -- ALL on a list [FALSE, FALSE, FALSE]' -> 0
Result for check id: 800205 'INVALID -- ALL on a list [INVALID, INVALID, INVALID]' -> 2
Result for check id: 800206 'INVALID -- ALL on a list [TRUE, INVALID, TRUE]' -> 2
Result for check id: 800207 'FAIL -- ALL on a list [INVALID, TRUE, FALSE]' -> 0
Result for check id: 800300 'FAIL -- NONE on a list [TRUE, TRUE, TRUE]' -> 0
Result for check id: 800301 'FAIL -- NONE on a list [TRUE, FALSE, FALSE]' -> 0
Result for check id: 800302 'FAIL -- NONE on a list [FALSE, TRUE, FALSE]' -> 0
Result for check id: 800303 'FAIL -- NONE on a list [FALSE, FALSE, TRUE]' -> 0
Result for check id: 800304 'PASS -- NONE on a list [FALSE, FALSE, FALSE]' -> 1
Result for check id: 800305 'INVALID -- NONE on a list [INVALID, INVALID, INVALID]' -> 2
Result for check id: 800306 'INVALID -- NONE on a list [INVALID, FALSE, FALSE]' -> 2
Result for check id: 800307 'FAIL -- NONE on a list [INVALID, FALSE, TRUE]' -> 0
```
**Output for negation**
```
Result for check id: 700100 'PASS -- TRUE' -> 1
Result for check id: 700101 'FAIL -- FALSE' -> 0
Result for check id: 700102 'INVALID -- INVALID' -> 2
Result for check id: 700103 'FAIL -- not TRUE' -> 0
Result for check id: 700104 'PASS -- not FALSE' -> 1
Result for check id: 700105 'INVALID -- not INVALID' -> 2
```

**Comment by JuantAldea** [comment]
```
Starting evaluation of policy: 'sca_negation_test_suite.yml'
Result for check id: 700100 'PASS -- TRUE' -> 1
Result for check id: 700104 'PASS -- not FALSE' -> 1
Starting evaluation of policy: 'sca_condition_test_suite.yml'
Result for check id: 800100 'PASS -- ANY on a list [TRUE, TRUE, TRUE]' -> 1
Result for check id: 800101 'PASS -- ANY on a list [TRUE, FALSE, FALSE]' -> 1
Result for check id: 800102 'PASS -- ANY on a list [FALSE, TRUE, FALSE]' -> 1
Result for check id: 800103 'PASS -- ANY on a list [FALSE, FALSE, TRUE]' -> 1
Result for check id: 800107 'PASS -- ANY on a list [FALSE, INVALID, TRUE]' -> 1
Result for check id: 800200 'PASS -- ALL on a list [TRUE, TRUE, TRUE]' -> 1
Result for check id: 800304 'PASS -- NONE on a list [FALSE, FALSE, FALSE]' -> 1
Starting evaluation of policy: 'sca_processes_test_suite.yml'
Result for check id: 400100 'PASS -- Look for systemd' -> 1
Result for check id: 400103 'PASS -- Negate look for systemd_FAKE' -> 1
Result for check id: 400104 'PASS -- Look for systemd using regex' -> 1
Starting evaluation of policy: 'sca_commands_test_suite.yml'
Result for check id: 300100 'PASS -- Yield ABC and match it' -> 1
Result for check id: 300103 'PASS -- Negate yield ABC and try to find CBA' -> 1
Starting evaluation of policy: 'sca_files_test_suite.yml'
Result for check id: 200100 'PASS -- existing file exists' -> 1
Result for check id: 200102 'PASS -- a non-existing file does not exist' -> 1
Result for check id: 200200 'PASS -- Last file exists' -> 1
Result for check id: 200203 'PASS -- Negated non-existing list' -> 1
Result for check id: 200300 'PASS -- Full rule regex match' -> 1
Result for check id: 200303 'PASS -- negated full rule regex does not match' -> 1
Result for check id: 200304 'PASS -- negated regex matches (because !r:^FAIL matches everything but ^FAIL)' -> 1
Result for check id: 200307 'PASS -- Negated contradictory match -> Tautology' -> 1
Starting evaluation of policy: 'sca_directories_test_suite.yml'
Result for check id: 100100 'PASS -- Directory exists' -> 1
Result for check id: 100102 'PASS -- Directory does not exist' -> 1
Result for check id: 100201 'PASS -- The last directory exists' -> 1
Result for check id: 100202 'PASS -- Negated directories that do not exist' -> 1
Result for check id: 100300 'PASS -- Full rule regex match' -> 1
Result for check id: 100400 'PASS -- The file exists' -> 1
Result for check id: 100401 'PASS -- There exist other files in /var/ossec which !ossec.conf -> TRUE' -> 1
Result for check id: 100403 'PASS -- There exist other files in /var/ossec which !fakefile -> TRUE' -> 1
```
```
Starting evaluation of policy: 'sca_negation_test_suite.yml'
Result for check id: 700101 'FAIL -- FALSE' -> 0
Result for check id: 700103 'FAIL -- not TRUE' -> 0
Starting evaluation of policy: 'sca_condition_test_suite.yml'
Result for check id: 800104 'FAIL -- ANY on a list [FALSE, FALSE, FALSE]' -> 0
Result for check id: 800201 'FAIL -- ALL on a list [TRUE, TRUE, FALSE]' -> 0
Result for check id: 800202 'FAIL -- ALL on a list [TRUE, FALSE, TRUE]' -> 0
Result for check id: 800203 'FAIL -- ALL on a list [FALSE, TRUE, TRUE]' -> 0
Result for check id: 800204 'FAIL -- ALL on a list [FALSE, FALSE, FALSE]' -> 0
Result for check id: 800207 'FAIL -- ALL on a list [INVALID, TRUE, FALSE]' -> 0
Result for check id: 800300 'FAIL -- NONE on a list [TRUE, TRUE, TRUE]' -> 0
Result for check id: 800301 'FAIL -- NONE on a list [TRUE, FALSE, FALSE]' -> 0
Result for check id: 800302 'FAIL -- NONE on a list [FALSE, TRUE, FALSE]' -> 0
Result for check id: 800303 'FAIL -- NONE on a list [FALSE, FALSE, TRUE]' -> 0
Result for check id: 800307 'FAIL -- NONE on a list [INVALID, FALSE, TRUE]' -> 0
Starting evaluation of policy: 'sca_processes_test_suite.yml'
Result for check id: 400101 'FAIL -- Negate look for systemd' -> 0
Result for check id: 400102 'FAIL -- Look for systemd_FAKE' -> 0
Starting evaluation of policy: 'sca_commands_test_suite.yml'
Result for check id: 300101 'FAIL -- Negate yield ABC and match it' -> 0
Result for check id: 300102 'FAIL -- Yield ABC and try to find CBA' -> 0
Starting evaluation of policy: 'sca_files_test_suite.yml'
Result for check id: 200101 'FAIL -- a non-existing file file should exist' -> 0
Result for check id: 200103 'FAIL -- existing file file should not exist' -> 0
Result for check id: 200201 'FAIL -- Files do not exist' -> 0
Result for check id: 200202 'FAIL -- Negated last file exists' -> 0
Result for check id: 200301 'FAIL -- negated full rule regex match' -> 0
Result for check id: 200302 'FAIL -- Full rule regex does not match' -> 0
Result for check id: 200306 'FAIL -- Contradictory match' -> 0
Starting evaluation of policy: 'sca_directories_test_suite.yml'
Result for check id: 100101 'FAIL -- Directory does not exist' -> 0
Result for check id: 100103 'FAIL -- Directory exists' -> 0
Result for check id: 100200 'FAIL -- Directories do not exist' -> 0
Result for check id: 100203 'FAIL -- Negated existing directories' -> 0
Result for check id: 100301 'FAIL -- Full rule regex does not match' -> 0
Result for check id: 100303 'FAIL -- File does not exist' -> 0
Result for check id: 100402 'FAIL -- There not exists the file ossec.conf' -> 0
Result for check id: 100404 'FAIL -- The file does not exist' -> 0
```
```
Starting evaluation of policy: 'sca_negation_test_suite.yml'
Result for check id: 700102 'INVALID -- INVALID' -> 2
Result for check id: 700105 'INVALID -- not INVALID' -> 2
Starting evaluation of policy: 'sca_condition_test_suite.yml'
Result for check id: 800105 'INVALID -- ANY on a list [INVALID, INVALID, INVALID]' -> 2
Result for check id: 800106 'INVALID -- ANY on a list [FALSE, INVALID, FALSE]' -> 2
Result for check id: 800205 'INVALID -- ALL on a list [INVALID, INVALID, INVALID]' -> 2
Result for check id: 800206 'INVALID -- ALL on a list [TRUE, INVALID, TRUE]' -> 2
Result for check id: 800305 'INVALID -- NONE on a list [INVALID, INVALID, INVALID]' -> 2
Result for check id: 800306 'INVALID -- NONE on a list [INVALID, FALSE, FALSE]' -> 2
Starting evaluation of policy: 'sca_processes_test_suite.yml'
Starting evaluation of policy: 'sca_commands_test_suite.yml'
Result for check id: 300104 'INVALID -- Command does not exist (will trigger leak reports due to execvp failing)' -> 2
Result for check id: 300105 'INVALID -- negated Command does not exist (will trigger leak reports due to execvp failing)' -> 2
Result for check id: 300106 'INVALID -- Not executable file (will trigger leak reports due to execvp failing)' -> 2
Starting evaluation of policy: 'sca_files_test_suite.yml'
Result for check id: 200305 'INVALID -- File does not exist' -> 2
Starting evaluation of policy: 'sca_directories_test_suite.yml'
Result for check id: 100302 'INVALID -- Directory does not exist' -> 2
Result for check id: 100405 'INVALID -- The directory does not exist' -> 2
Starting evaluation of policy: 'sca_negation_test_suite.yml'
Result for check id: 700102 'INVALID -- INVALID' -> 2
Result for check id: 700105 'INVALID -- not INVALID' -> 2
Starting evaluation of policy: 'sca_condition_test_suite.yml'
Result for check id: 800105 'INVALID -- ANY on a list [INVALID, INVALID, INVALID]' -> 2
Result for check id: 800106 'INVALID -- ANY on a list [FALSE, INVALID, FALSE]' -> 2
Result for check id: 800205 'INVALID -- ALL on a list [INVALID, INVALID, INVALID]' -> 2
Result for check id: 800206 'INVALID -- ALL on a list [TRUE, INVALID, TRUE]' -> 2
```

**Comment by JuantAldea** [comment]
Added Symlink resolution.

**Comment by JuantAldea** [comment]
Added symlink processing.

**Comment by chemamartinez** [comment]
#3228 and #3374 are subtasks of this one.

**Comment by chemamartinez** [comment]
#3623 and #3595 are also including in the development for this issue.

**Comment by chemamartinez** [comment]
Another subtask is needed after discussing it with the team:

Since #3595, policies located at `/ruleset/sca` are scanned by default (it is no needed to specify each policy file in the configuration).

The manager stores in `/ruleset/sca` every available policy to be able to push them to group of agents by the remote configuration. So, to avoid the loaded of unsupported policies on the manager side. The next change is required:

- When installing the manager, all the policies are installed in its `/ruleset/sca` folder. The supported policy for that manager should be loaded for scanning it by SCA, the rest of policies should be added with the extension `.disabled` (e.g. `cis_apache_24.yml.disabled`) to be ignored when starting the SCA module.

This change has to work in the same way when installing by sources and packages. _Ping @wazuh/cicd_

**Comment by chemamartinez** [comment]
Merged at https://github.com/wazuh/wazuh/pull/3286.

Pending documentation (https://github.com/wazuh/wazuh-documentation/issues/1333) to close the issue.
