### ISSUE TITLE
Flask API: Implement Lists endpoints

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#3255]
Reimplementation of every Lists endpoint implemented on nodejs-based to python for the new API.

Principal roadmap #2640.

Goals:
- [x] Review actual API endpoints (functionality, paremeters, tests)
- [x] Review and update API spec for Lists endpoints
- [x] Implement GET /lists controller
- [x] Implement GET /lists/files controller
- [x] Implement GET /list controller
- [x] Update controller and framework WazuhExceptions to new methodology
- [x] Update and run cdb-list framework unit tests
- [x] Implement integration tests
- [x] Run complete integration tests
- [x] Run manual API tests
- [x] Review and update changes.md for Lists endpoints

**Comment by davidjiglesias** [comment]
Status update
## Summary
Today I have worked in the implemention of the lists endpoints.

## Tasks
* [2h] Review actual API endpoints (functionality, paremeters, tests). While reviewing old API lists I found a bug in `GET /lists` docstring --> https://github.com/wazuh/wazuh-api/issues/383. I fixed the issue --> https://github.com/wazuh/wazuh-api/pull/384/. I also opened a documentation issue derived from the same issue --> XXXXX
* [1h] Review and update API spec for Lists endpoints. Added `CDBListFile` schema to Lists models to match response from `GET /lists/files`. Refactored `GET /lists/files` spec definition.
* [0.75h] Implement `GET /lists controller`
* [0.75h] Implement `GET /lists/files controller`
* [1h] Update controller and framework `WazuhExceptions` to `WazuhError(400)` and `WazuhInternalError(500)`. Adjusted message, codes and remediations for them. Exceptions manual tests provided in Test performed section below.
* [0.5h] Review, update or implement cdb-list framework unit test
* [2h] Work on implementing `GET /list` endpoint and controller

## Difficulties

## Tests performed
* Manual exceptions test:
```
root@e0d510049324:/# curl "http://localhost:55000/lists?path=etc/lists/amazon/aws-eventnames.cdb"
{
  "code": 1800,
  "dapi_errors": {
    "master-node": {
      "error": "Bad format in CDB list WAZUH_HOME/etc/lists/amazon/aws-eventnames.cdb",
      "logfile": "WAZUH_HOME/logs/api.log"
    }
  },
  "detail": "Bad format in CDB list WAZUH_HOME/etc/lists/amazon/aws-eventnames.cdb",
  "status": 400,
  "title": "Wazuh Error",
  "type": "about:blank"
}
```
```
root@e0d510049324:/# curl "http://localhost:55000/lists?path=etc/lists/amazon./aws-eventnamess"
{
  "code": 1801,
  "dapi_errors": {
    "master-node": {
      "error": "Wrong 'path' parameter",
      "logfile": "WAZUH_HOME/logs/api.log"
    }
  },
  "detail": "Wrong 'path' parameter",
  "remediation": "Please, provide a correct path",
  "status": 400,
  "title": "Wazuh Error",
  "type": "about:blank"
}
```
```
root@e0d510049324:/# curl "http://localhost:55000/lists?path=etc/lists/amazon/aws-eventnamess"
{
  "code": 1802,
  "dapi_errors": {
    "master-node": {
      "error": "Lists file not found",
      "logfile": "WAZUH_HOME/logs/api.log"
    }
  },
  "detail": "Lists file not found",
  "remediation": "Please, use GET /lists/files to list all available lists",
  "status": 400,
  "title": "Wazuh Error",
  "type": "about:blank"
}
```
```
root@e0d510049324:/# curl "http://localhost:55000/lists?path=etc/lists/audit-keys.cdb"
{
  "code": 1803,
  "dapi_errors": {
    "master-node": {
      "error": "Error reading lists file",
      "logfile": "WAZUH_HOME/logs/api.log"
    }
  },
  "detail": "Error reading lists file",
  "remediation": "Please, make sure you have read permissions on the file",
  "status": 400,
  "title": "Wazuh Error",
  "type": "about:blank"
}
```
```
root@e0d510049324:/# curl "http://localhost:55000/lists?path=etc/lists/amazon"
{
  "code": 1804,
  "dapi_errors": {
    "master-node": {
      "error": "Error reading lists file: WAZUH_HOME/etc/lists/amazon is a directory",
      "logfile": "WAZUH_HOME/logs/api.log"
    }
  },
  "detail": "Error reading lists file: WAZUH_HOME/etc/lists/amazon is a directory",
  "remediation": "Please, make sure you provide a correct filepath",
  "status": 400,
  "title": "Wazuh Error",
  "type": "about:blank"
}
```
* Unit tests for `cdb_list.py` framework module:
```
============================= test session starts ==============================
platform linux -- Python 3.7.2, pytest-4.4.2, py-1.8.0, pluggy-0.11.0
rootdir: /opt/project/framework
plugins: tavern-0.26.3collected 9 items

test_cdb_list.py                                                [100%]

=========================== 9 passed in 0.36 seconds ===========================
```
## Pending
- Implement new GET/list controller
- Implement integration tests
- Run complete integration tests
- Run manual API tests
- Review and update changes.md for Lists endpoints

**Comment by davidjiglesias** [comment]
Status update
## Summary
Today I have completed the remaining goals to achieve the implemention of the lists endpoints.

## Tasks
* [1h] Implemented new `GET/list controller`. We have added a new endpoint to replicate the behaviour of old `GET /lists?path` request. `GET /lists?path` is now a filter parameter.
* [0.25h] Updated and run `test_cdb_list.py` unittest to include new cdb framework function `get_list(filepath)`
* [0.5h] Completed and run the implementation of integration tests
* [0.1h] Run manual API tests
* [0.1h] Updated `changes.md` with mentioned changes on `GET /lists?path` and the addition of `GET /list?path`
* [0.1h] Opened documentation issue: https://github.com/wazuh/wazuh-documentation/issues/1207

## Difficulties
## Tests performed
* Unit tests:
```
============================= test session starts ==============================
platform linux -- Python 3.7.2, pytest-4.4.2, py-1.8.0, pluggy-0.11.0
rootdir: /opt/project/framework
plugins: tavern-0.26.3collected 10 items

test_cdb_list.py ..........                                              [100%]

========================== 10 passed in 0.05 seconds ===========================
```
* Integration tests:
```
============================== test session starts ===============================
platform linux -- Python 3.7.2, pytest-4.4.2, py-1.8.0, pluggy-0.11.0 -- /var/ossec/framework/python/bin/python3.7
cachedir: .pytest_cache
rootdir: /var/ossec/framework/python/bin
plugins: tavern-0.26.3
collected 3 items                                                                

test/test_lists_endpoints.tavern.yaml::GET /lists PASSED                   [ 33%]
test/test_lists_endpoints.tavern.yaml::GET /list?path=list_filepath PASSED [ 66%]
test/test_lists_endpoints.tavern.yaml::GET /lists/files PASSED             [100%]

================================ warnings summary ================================
/var/ossec/framework/python/lib/python3.7/site-packages/yaml/constructor.py:126
  /var/ossec/framework/python/lib/python3.7/site-packages/yaml/constructor.py:126: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    if not isinstance(key, collections.Hashable):

test/test_lists_endpoints.tavern.yaml::GET /lists
  /var/ossec/framework/python/lib/python3.7/site-packages/jwt/api_jwt.py:81: DeprecationWarning: It is strongly recommended that you pass in a value for the "algorithms" argument when calling decode(). This argument will be mandatory in a future version.
    DeprecationWarning

-- Docs: https://docs.pytest.org/en/latest/warnings.html
====================== 3 passed, 2 warnings in 0.83 seconds ======================
```
## Pending

**Comment by davidjiglesias** [comment]
Status update
## Summary
Today I have added folder and path changes in the response of GET /lists/files

## Tasks
* Changes to GET /lists/files

## Difficulties
## Tests performed
* API test:
```json
curl -X GET "http://localhost:55000/lists/files?pretty=false&wait_for_complete=false" -H  "accept: application/json" -H  "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YXp1aCIsImlhdCI6MTU1OTIwNzYyMiwiZXhwIjoxNTU5MjA4MjIyLCJzdWIiOiJmb28ifQ.Az_JiurVE6sLwy-fEw4PayMNUznr9bGl9OLNvopAkZU"
{
  "data": {
    "items": [
      {
        "folder": "etc/lists",
        "name": "audit-keys",
        "path": "etc/lists/audit-keys"
      },
      {
        "folder": "etc/lists",
        "name": "security-eventchannel",
        "path": "etc/lists/security-eventchannel"
      },
      {
        "folder": "etc/lists/amazon",
        "name": "aws-sources",
        "path": "etc/lists/amazon/aws-sources"
      },
      {
        "folder": "etc/lists/amazon",
        "name": "aws-eventnames",
        "path": "etc/lists/amazon/aws-eventnames"
      }
    ],
    "totalItems": 4
  }
```
* Unit tests:
```python
============================== test session starts ===============================
platform linux -- Python 3.7.2, pytest-4.5.0, py-1.8.0, pluggy-0.12.0 -- /var/ossec/framework/python/bin/python3.7
cachedir: .pytest_cache
rootdir: /var/ossec/framework/python/bin
plugins: cov-2.7.1, tavern-0.26.3
collected 10 items                                                               

unit/test_cdb_list.py::TestCDBList::test_get_list PASSED                   [ 10%]
unit/test_cdb_list.py::TestCDBList::test_get_lists PASSED                  [ 20%]
unit/test_cdb_list.py::TestCDBList::test_get_lists_offset PASSED           [ 30%]
unit/test_cdb_list.py::TestCDBList::test_get_lists_path PASSED             [ 40%]
unit/test_cdb_list.py::TestCDBList::test_get_lists_search PASSED           [ 50%]
unit/test_cdb_list.py::TestCDBList::test_get_lists_sort PASSED             [ 60%]
unit/test_cdb_list.py::TestCDBList::test_get_path_lists PASSED             [ 70%]
unit/test_cdb_list.py::TestCDBList::test_get_path_lists_offset PASSED      [ 80%]
unit/test_cdb_list.py::TestCDBList::test_get_path_lists_search PASSED      [ 90%]
unit/test_cdb_list.py::TestCDBList::test_get_path_lists_sort PASSED        [100%]

=========================== 10 passed in 0.09 seconds ============================
```
* Integration tests:
```python
============================== test session starts ===============================
platform linux -- Python 3.7.2, pytest-4.5.0, py-1.8.0, pluggy-0.12.0 -- /var/ossec/framework/python/bin/python3.7
cachedir: .pytest_cache
rootdir: /var/ossec/framework/python/bin
plugins: cov-2.7.1, tavern-0.26.3
collected 3 items                                                                

test/test_lists_endpoints.tavern.yaml::GET /lists PASSED                   [ 33%]
test/test_lists_endpoints.tavern.yaml::GET /list?path=list_filepath PASSED [ 66%]
test/test_lists_endpoints.tavern.yaml::GET /lists/files PASSED             [100%]

================================ warnings summary ================================
/var/ossec/framework/python/lib/python3.7/site-packages/yaml/constructor.py:126
  /var/ossec/framework/python/lib/python3.7/site-packages/yaml/constructor.py:126: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    if not isinstance(key, collections.Hashable):

test/test_lists_endpoints.tavern.yaml::GET /lists
  /var/ossec/framework/python/lib/python3.7/site-packages/jwt/api_jwt.py:81: DeprecationWarning: It is strongly recommended that you pass in a value for the "algorithms" argument when calling decode(). This argument will be mandatory in a future version.
    DeprecationWarning

-- Docs: https://docs.pytest.org/en/latest/warnings.html
====================== 3 passed, 2 warnings in 1.23 seconds ======================
```
## Pending
