### ISSUE TITLE
Add RBAC support to Wazuh API and Framework

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#3287]
This issue describes the design of RBAC to be implemented in Wazuh API and Wazuh framework.

## Introduction
The main goal of RBAC is adding to Wazuh the capability to control access to different endpoints and resources through API based on privileges to users. The main concepts that give support to RBAC are:
- User
- Role
- Permission

A full explanation of the standard RBAC definition may be found [here](https://en.wikipedia.org/wiki/Role-based_access_control).

## Restrictions
- API must provide endpoints to allow setting up RBAC (configuring users, roles and permissions)
- In order to use RBAC with the API, a user must be logged in to get a mapped role and therefore, the permissions associated.
- Implications using Wazuh App for Kibana:
  - A security plugin must be installed in Kibana so as to have user authentication, such as SearchGuard or X-Pack. Otherwise, RBAC would not make sense for obvious reasons.
  - Although API does provide an user registration and authentication functionality, it must be capable of mapping roles to users logged in through the previous mentioned security plugin. The main reason is preventing users from double authenticating when accessing Wazuh App.
  - The only way to use RBAC in a non secure Kibana installation is setting a default user statically in its configuration.
- Must have two modes for configuring permissions:
  - White list mode: everything is forbidden. The administrator configure roles to give permissions.
  - Black list mode: everything is allowed. The administrator configure roles to restrict permissions.
- Permissions must be exposed at least with the following level of granularity:
  - #### Active-Response
    - Execute active-response
      - Agent id
      - Agent group
  - #### Agents
    - Agents overall query agents (GET)
      - Agent id
      - Agent group
    - GET Agents
      - Agent id
      - Agent group
    - GET Agents config
      - Agent id
      - Agent group
    - GET Agents key
      - Agent id
      - Agent group
    - GET Upgrade result
      - Agent id
      - Agent group
    - GET Agents without group
    - GET Agents outdated
    - GET Agents stats distinct
    - GET Agents summary
    - GET Agents OS summary
    - Groups of agents overall GET endpoints
      - Group id
    - GET Agents in a group
      - Group id
    - GET Group configuration
      - Group id
    - GET Group files
      - Group id
    - GET Group file
      - Group id
      - File id
    - Agents overall operate with agents (PUT, POST)
      - Agent id
      - Agent group
    - POST agent addition 
    - POST agent addition to group
      - Group id
    - POST Upload config to group
      - Group id
    - POST Upload file to group
      - Group id
    - POST Insert an agent
      - Agent id
      - Agent group
    - POST Restart agents
      - Agent id
      - Agent group
    - PUT Add agent to group
      - Agent id
      - Agent group
    - PUT Restart an agent
      - Agent id
      - Agent group
    - PUT Upgrade an agent
      - Agent id
      - Agent group
    - PUT Upgrade an agent with custom file
      - Agent id
      - Agent group
    - PUT Add agent with name
    - PUT Create group
    - PUT Restart all agents
  - #### CIS-CAT
    - GET CIS-CAT results
      - Agent id
      - Agent group
  - #### Cluster/manager
    - Overall cluster read-only commands (GET)
      - Node id
    - GET List nodes
    - GET local node info
      - Node id
    - GET node info
      - Node id
    - GET cluster config
    - GET cluster healthcheck
    - GET cluster status
    - GET node config
      - Node id
    - GET node logs and logs summary
      - Node id
    - GET node stats
      - Node id
    - GET node id status
      - Node id
  - #### Decoders
    - Overall decoders read-only commands (GET)
    - Overall decoders write commands (PUT/POST)
      - Decoder id
    - PUT/POST create new decoder
    - PUT/POST modify existing decoder
      - Decoder id
    - DELETE delete decoder
      - Decoder id
  - #### Rules
    - Overall rules read-only commands (GET)
    - Overall rules write commands (PUT/POST)
      - Rule id
    - PUT/POST create new rule
    - PUT/POST modify existing rule
      - Rule id
    - DELETE delete rule
      - Rule id
  - #### Rootcheck
    - Overall rootcheck read-only commands (GET)
      - Agent id
      - Agent group
    - GET rootcheck scan data
      - Agent id
      - Agent group
    - PUT Rootcheck run commands
      - Agent id
      - Agent group
    - DELETE Clear rootcheck db
      - Agent id
      - Agent group
  - #### Syscheck
    - Overall syscheck read-only commands (GET)
      - Agent id
      - Agent group
    - PUT Syscheck run commands
      - Agent id
      - Agent group
    - DELETE Clear rootcheck db
      - Agent id
      - Agent group
   - #### SCA
     - Overall sca read-only commands (GET)
       - Agent id
       - Agent group
    
### Concepts
- User: an entity representing a person or a system that may access API using basic authentication (with password)
- Role: A set of `policies` that must be matched in order to get access to a `resource`. It can be applied using a `rule` or associated to a `user`.
- Policy: a structure relating a list of `actions`, `resources` and an `effect` that translates into a permission.
- Action: a string matching the pattern "\w+|\*(\:\w+|\*)\*" representing a hierarchy of actions that an `user` may perform.
  The set of `actions` is closed and static. A '\*' character may be used as a wildcard.
- Resource: any entity that can be subject to an action. The set of `resources` is dynamic, but the types are static.
  Some examples of resources are "agent 001", "agents in group default" or "node of a cluster".
- Effect: only can be "allow" or "deny", depending on the effective permission to be applied.
- Rule: a condition that the `authorization context` has to match to apply a `role`
- Authorization context: a set of data generated by the authorization layer granting access to API (X-Pack, SearchGuard, ...)

### Database
An sqlite database will be created in order to store instances of the previous concepts. It will contain the following tables:
- #### roles
  |Field name|Type|Description|
  |---|---|---|
  |id|long|Primary key|
  |name|text|Human readable string to identify the role|
  |rule|text|JSON formatted rule to be matched against the `authorization context`|
- #### policies
  |Field name|Type|Description|
  |---|---|---|
  |id|long|Primary key|
  |name|text|Human readable string to identify the policy|
  |policy|text|JSON formatted object in the form: {"actions": "...", "resources":"...", "effect": "allow/deny"}|
- #### roles_policies
  |Field name|Type|Description|
  |---|---|---|
  |role_id|long|Primary key. Foreign key to `roles.id`|
  |policy_id|long|Primary key. Foreign key to `policies.id`|

The recommended approach to implement this data model is using the ORM of SQLAlchemy.

### Cluster considerations
All data stored in RBAC database must be synchronized in every node in the cluster, since the API will be running everywhere.
To achieve this, we have two alternatives:
1. Modify the synchronization task already implemented in current cluster, in charge of sending client.keys and other data to workers.
2. Implement a cluster-based solution to share information across nodes in cluster like [rqlite](https://github.com/rqlite/rqlite)

### Coding
To enable RBAC capabilities in current framework a new `rbac.py` module will be created under `framework/wazuh` folder.
It will provide the following utils:
- Decorators to generate the strings to be matched by the policy fields `action` and `resources`:
    - `exposes_actions`: decorator to expose the `actions` to be executed when calling a function. It must create  a new variable with the list of actions that a policy must address to allow the execution of the function. Furthermore, the decorator must be able to be applied more than once over the same function, indicating optionality in the different sets of actions.
    - `requires_resources`: decorator to expose the `resources` ids to be accessed to perform an `action`. Ideally, the resources should have identified based on the parameters passed to the decorated function.
- `matches_privileges`: a function to check if some of the policies linked to a role matches the pair `action-resource` required by some function.

An example of decorated API controller:
```python
@exposes_actions(['agent:delete'])
@requires_resources('agent:id:{ids}')
def delete_agents(pretty=False, wait_for_complete=False, ids=None, purge=None, status=None, older_than=None):
    ...
```

In this example the function delete_agents will perform the action `'agent:delete'` over the resources `'agent:id:001', 'agent:id:002', 'agent:id:003'` supposing `ids` is set with the value `['001', '002', '003']`. There must exist also the possibility to use a wildcard in the form:
```python
@exposes_actions(['agent:delete'])
@requires_resources('agent:id:*')
def delete_all_agents():
    ...
```
It should be interpreted as the function accessing all possible agents in that environment.

Let's consider an environment with 5 agents (001, 002, 003, 004 and 005) and a policy in the form:
```json
{
  "actions": ["agent:delete"],
  "resources": ["agent:id:001", "agent:id:002", "agent:id:003"],
  "effect": "allow"
}
```
In this case, this policy is enough to execute the first function, but not the second one.

Let's consider another policy with the same 5 agents:
```json
{
  "actions": ["agent:delete"],
  "resources": ["agent:id:*"],
  "effect": "allow"
}
```
Using this policy, both functions could be executed since it grants access for deleting all existing agents.

Once a user is logged in, an authorization context is received to be matched against all rules in `roles` table. A user may have several roles assigned at the same time. A function `match_auth_context` must be provided in order to load all `roles` and its related `policies` using the previously defined ORM. Once all `policies` are loaded, they should be JSON encoded together within the JWT authorization token it is already being used in `authentication` module, specifically in `generate_token` function. This function could be refactored in order to include a new key in the JSON encoded called `rbac` with all the `policies` applied through `roles`.

### Roles and policies management
Customizing RBAC must be as simple as possible, so a catalog of new API endpoints will be provided to operate the CRUD cycle of roles and policies:
- `PUT /security/role`: creates a new `role` given a name, a `rule` and optionally the ids of `policies` related to it.
- `GET /security/roles`: lists all existing `roles` and their details.
- `GET /security/role/:role_id`: gets the full definition of a `role` given its id (including `policies` related to it)
- `POST /security/role/:role_id`: updates an existing `role`. It allows changing the `rule`, name or relating `policies`.
- `DELETE /security/role/:role_id`: deletes an existing `role`. It should also remove all the relationships to any `policies`.
- `PUT /security/policy`: creates a new `policy` given a name and a definition.
- `GET /security/policies`: lists all existing `policies` and their details.
- `GET /security/policy/:policy_id`: gets the full definition of a `policy` given its id (including name and definition)
- `POST /security/policy/:policy_id`: updates an existing `policy` given its id.
- `DELETE /security/policy/:policy_id`: deletes an existing `policy`. It should also remove all 
the relationships to any `roles`.
- `POST /security/role/:role_id/policy/:policy_id`: attaches a `role` and a `policy`.
- `DELETE /security/role/:role_id/policy/:policy_id`: detaches a `role` and a `policy`.

### Documentation
Documentation issue is tracked here: https://github.com/wazuh/wazuh-documentation/issues/1197

### Main Subtasks:
- [x] Implement RBAC application code and decorators #3373 
- [x] Implementation of the database structure to enable RBAC in the API #3375
- [x] Implementation of endpoints to manage RBAC through API #3410 
- [x] Implementation of login system #3507 
- [x] Policies preprocessing #3955

In order to adapt current framework for RBAC support some of the modules need heavy refactoring. It is necessary to granularly divide functions to better expose accessed actions:resources.

### Module Subtasks:
- [x] Active Response #3917 
- [x] Agents #3959
- [x] CIS-CAT #4118 
- [x] Cluster #4126 
- [x] Decoders #4119 
- [x] Experimental #4258 
- [x] Lists #4120 
- [x] Manager (done at the same time as cluster endpoints)
- [x] Rules #4122 
- [x] Security #3410 #3928
- [x] Syscheck #4124 
- [x] Syscollector #4125
- [x] SCA #4123

**Comment by AdriiiPRodri** [comment]
## Status update

Hi team,

In the development of RBAC we have reached a point where we have decided to make a policy processing engine for users. This engine is motivated by the intention that **'*' permissions**, that is, all permissions on a resource (e.g. agent : id : *) **are local to the user and not global**.

This way if for example we have 50 agents numbered 000-049 and a certain user has permissions to see 10 of the agents (012-021), when the user makes the call to see all the agents the call must show **exclusively** its **10 agents**.

In the previous behavior, this call would be forbidden because it does not have permissions to see all agents (**globally**, in this case the 50).

With this engine we introduce a greater **flexibility** and above all **comfort** for our users. In addition we have improved the number of requests to the database so that in this way with the inclusion of RBAC we have an **improvement of performance** in this aspect.

## First working version
In this version the agents are covered individually, at the moment the groups are not supported.

![RBACinAR](https://user-images.githubusercontent.com/15522808/64688231-30c15f80-d48c-11e9-973c-f3c56ec42835.png)
