### ISSUE TITLE
Flask API: Implement Rootcheck endpoints

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#3308]
Reimplementation of every Rootcheck endpoint implemented on nodejs-based to python for the new API.

Principal roadmap #2640.

Goals:
- [x] Review actual API endpoints (functionality, paremeters, tests)
- [x] Review and update API spec for Rootcheck endpoints
- [x] Implement PUT /rootcheck
- [x] Implement DELETE /rootcheck
- [x] Implement GET /rootcheck/{agent_id}
- [x] Implement PUT /rootcheck/{agent_id}
- [x] Implement DELETE /rootcheck/{agent_id}
- [x] Implement GET /rootcheck/{agent_id}/pci
- [x] Implement GET /rootcheck/{agent_id}/cis
- [x] Implement GET/rootcheck/{agent_id}/last_scan
- [x] Update controller and framework WazuhExceptions to new methodology
- [x] Update/Implement and run rootcheck framework unit tests
- [x] Implement and run integration tests
- [x] Run manual API tests
- [x] Review and update changes.md for Rootcheck endpoints

**Comment by davidjiglesias** [comment]
Status update
## Summary
I have completed the following goals:
- [x] Implement PUT /rootcheck
- [x] Implement DELETE /rootcheck
- [x] Implement GET /rootcheck/{agent_id}/pci
- [x] Implement GET /rootcheck/{agent_id}/cis
- [x] Implement GET/rootcheck/{agent_id}/last_scan
- [x] Update controller and framework WazuhExceptions to new methodology

## Tasks
* [2.5h] Implement rootcheck endpoints

## Difficulties
## Tests performed
```
root@b19beb17f0c9:/# curl -X PUT "http://localhost:55000/rootcheck/000"
{
  "message": "Restarting Syscheck/Rootcheck locally"
}
```
```
root@b19beb17f0c9:/# curl -X PUT "http://localhost:55000/rootcheck/002"
{
  "message": "Restarting Syscheck/Rootcheck on agent"
}
```
```
root@b19beb17f0c9:/# curl -X DELETE  "http://localhost:55000/rootcheck/000"
{
  "message": "Rootcheck database deleted"
}
```
```
root@b19beb17f0c9:/# curl -X DELETE  "http://localhost:55000/rootcheck/002"
{
  "message": "Rootcheck database deleted"
}
```
## Pending
- Implement PUT /rootcheck/{agent_id}
- Implement DELETE /rootcheck/{agent_id}
- Update/Implement and run rootcheck framework unit tests
- Implement and run integration tests
- Run manual API tests
- Review and update changes.md for Rootcheck end

**Comment by davidjiglesias** [comment]
This issue is blocked by #2911

**Comment by davidjiglesias** [comment]
Rootcheck endpoints are being deprecated in the new API.
