### ISSUE TITLE
Syscheck rework

### ISSUE THREAD

**Issue by bah07** [wazuh/wazuh#3319]
|Wazuh version|Component|Platform|Branch|
|---|---|---|---|
| 3.9.0-1 | Syscheck | All | [3319-fim-rework](https://github.com/wazuh/wazuh/compare/3.12...3319-fim-rework) |

This work will be done in parallel to #2404 because both implementations are codependent.

### Problem.

We must re-design to resolve some problems and simplify tasks.

- Race conditions between Whodata and Frequency/Realtime events. The data structure used is shared and some operations like deletion can cause errors.

- Due to multiple changes and new features added we have a complex and unmaintainable algorithm.

### Proposed solution.

- Simplify the recursive directory analysis algorithm.
- Create a unified data structure.
- Create a thread to manage events come from Realtime mode.

 ### Implementation.

- Until now, the recursive algorithm that analyzes directories and generates the database consists of two functions `read_dir` and `read_file` in a very complex and not maintainable way. The designed algorithm has a structure more divided by more concrete processes.

![chart_fim_scan](https://user-images.githubusercontent.com/6572618/57700776-eb666000-765a-11e9-955d-315488e22f1d.jpg)

- Let's change the content of the hash tables. Changing the checksum for a data structure with each of the fields that have a file

```
typedef struct fim_data {
    // Checksum attributes
    unsigned int size;
    unsigned int perm;
    unsigned int uid;
    unsigned int gid;
    char * user_name;
    char * group_name;
    unsigned int mtime;
    long unsigned int inode;
    os_md5 hash_md5;
    os_sha1 hash_sha1;
    os_sha256 hash_sha256;
    // Options mask
    int options;
} fim_data;
```

- Separate the hash table entries into three, one for each mode (Real-time, Whdoata and Scheduled scans). This way we avoid race conditions between the different threads when they access the same element. As well as their respective inode tables. These are necessary to handle certain events produced in real time.

```
syscheck.fim_entry[FIM_SCHEDULED]
syscheck.fim_entry[FIM_REALTIME]
syscheck.fim_entry[FIM_WHODATA]

KEY: Path name
DATA: struct fim_data

syscheck.fim_inode[FIM_REALTIME]
syscheck.fim_inode[FIM_WHODATA]

KEY: Inode
DATA: Path name
```

- Reassign sizes of hash tables to avoid nesting that generates slower processing before searching and insertions.

- Add an option that offers the possibility to configure the execution priority of the syscheck process by the operating system.

- Avoid processing Real-time events when the configured directory has the Whodata option and vice versa. We have to check the paths with which the events are generated to discard those that come from a contrary configuration (If the option is RT and the configuration was WD it is discarded and vice versa).

- Avoid processing paths in the programmed scan when that path exists in the configuration with the option Real-time or Whodata.

**Comment by Cerv1** [comment]
## Development update - 1
After doing some research, we will add the following behaviors to **FIM**.

### Precise configuration
The deeper the directory, the more priority its configuration has. We will be able to override the configuration of parent directories if we have a child directory entry with a more specific configuration. 

#### Configuration example
```xml
<syscheck>
  ...
  <directories check_all="yes" whodata="yes">/etc</directories>
  <directories check_all="yes" whodata="no" >/etc/chrony</directories>
  ...
</syscheck>
```

With the following configuration, we will have the whole `/etc` directory monitored with `whodata` **except for** `/etc/chrony`, which will be monitored only with the scheduled scans. This has been reported by @chemamartinez  in #3425.


### Improve the centralized configuration
We will be able to disable FIM using the centralized configuration (`agent.conf`). Besides being able to disable the FIM module completely, we will also be able to disable specific `<directories>` in order to suppress unnecessary configuration of the agents without having to directly access them one by one. 
This is especially useful for large environments with a high amount of agents as it can be distributed through the groups.

These are two of the possible alternatives to develop this functionality:
* Add a new option for the `<directories>` entry called `enabled` which _enables / disables_ the directory.
* Use the `check_all="no` configuration for `<directories>`.This will prevent the agent from monitoring this directory.

From these two options, we keep the one above because it allows us to achieve a greater specificity when creating configurations. For example, we will be able to monitor `C:\`  complete using `report_changes` but exclude `C:\User\wazuh\dont_scan_me` because it is problematic due to a large number of changing files.

Best regards,
Cerv1.

**Comment by Cerv1** [comment]
## Development update - 2
We have updated the new data structures: 
-  `fim_data` has been renamed to `fim_entry_data`
- We've added a new data structure used to store the number of paths related to an inode named `fim_inode_data`.
- We've added `mode` to `fim_entry_data` to unify the previous hash tables into one as it is explained [here](https://github.com/wazuh/wazuh/issues/2404#issuecomment-497356642).
- We've added the `scanned` flag used to check if the file has been found during the _scheduled_ scan.

### Updated data structures

```c
typedef struct fim_entry_data {
    // Checksum attributes
    unsigned int size;        # size
    unsigned int perm;        # permissions
    unsigned int uid;         # uid
    unsigned int gid;         # gid
    char * user_name;         # user name
    char * group_name;        # group name
    unsigned int mtime;       # mtime
    long unsigned int inode;  # inode 
    os_md5 hash_md5;          # md5 sum
    os_sha1 hash_sha1;        # sha1 sum
    os_sha256 hash_sha256;    # sha256 sum
    // Options
    int mode;                 # FIM mode
    int options;              # FIM options
    unsigned int scanned;     # scanned flag
} fim_entry_data;

typedef struct fim_inode_data {
    // Checksum attributes
    int items;             # number of items in path
    char ** paths;         # array of paths
} fim_inode_data;

```

Best regards,
Cerv1.

**Comment by Cerv1** [comment]
## Development update - 3

In this update, we've introduced the following changes:

- **Improved the code:** We have improved the reliability of the scheduled scan by enhancing the use of memory and creating more secure access to the hash tables.
- **Memory checks:** We have verified the behavior of these new changes using `valgrind` to prevent possible memory leaks and invalid reads.
- **We have included the `realtime` scan support:** Now, we are testing the integration of the `realtime` scan with the `scheduled` scan to prevent false positives and verify that everything is working on both scans.

Best regards,
Cerv1.

**Comment by Cerv1** [comment]
## Development update - 4

In this update, we've improved the _realtime_ monitoring for **FIM**. In the previous version, we weren't able to get the _move_ events (e. g: `mv dirA dirB`). This problem was caused because the `syscheck.dirtb` hash table wasn't being updated correctly. If we move a folder into another, _inotify_ doesn't change the internal watcher and as we can see in the following code snippet, if the _inotify watch_ of the folder was already used, we don't update the directory in any case.

https://github.com/wazuh/wazuh/blob/6441f5bfa69496be25e3f07ddd638af7c734c9a5/src/syscheckd/run_realtime.c#L309-L322

This caused that the new folder wasn't added to the _realtime_ engine of FIM and therefore, we didn't have any alerts related to this new directory when files are created, modified or deleted.

To solve this problem, we update the hash table if the _inotify watcher_ was already used because that means that the folder has been moved into another. Because of this, now we can alert of `mv` operations without restriction and without needing to use the `whodata` mode.

Best regards,
Cerv1.

**Comment by Lopuiz** [comment]
**Testing FIM in Windows Agent**
We have tested Syscheck: 
+ Frequency: works. The following example is a generated alert
```json
{"data":{"path":"c:\\testing\\testing.txt","options":1023,"alert":"Added"},"attributes":{"new_size":0,"new_perm":33206,"new_uid":0,"new_gid":0,"new_user_name":"Admi","new_mtime":1562076471,"new_inode":0,"new_hash_md5":"","new_hash_sha1":"","new_hash_sha256":""}}
```
+ Whodata:
We should declare the whodata thread in `start_daemon()`
```c
#ifdef WIN_WHODATA
    // Scan
    if (syscheck.wdata.whodata_setup && !run_whodata_scan()) {
        if (t_hdle = CreateThread(NULL, 0, state_checker, NULL, 0, &t_id), !t_hdle) {
            merror(FIM_ERROR_CHECK_THREAD);
        }
    }
#endif
```

**Comment by Lopuiz** [comment]
## The saved directory path is not correct

Directories configured in syscheck configuration block are been saved with extra slash character at the path end, independetly if it ends with this character.

This character is included in this line:

https://github.com/wazuh/wazuh/blob/b36bfd71f0adcd87f8f3e0c026a99bb85e8c9b46/src/config/syscheck-config.c#L61

Previously this character was not added:

https://github.com/wazuh/wazuh/blob/81d866cdab1502a4c940bc49bdd5e2040d86b7f3/src/config/syscheck-config.c#L72

You can see how the path is saved in the following log:
>2019/07/12 06:29:24 ossec-agent: INFO: (6003): Monitoring directory: 'c:\testing\', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | attributes | whodata'.

And the configuration is:
```xml
<directories check_all="yes" whodata="yes">C:\testing</directories>
```

**Comment by vikman90** [comment]
## File discarding in real-time

We've detected this issue in the current version:

### Configuration
```xml
<directories check_all="yes" realtime="yes">/root/test</directories>
<ignore>noalert</ignore>
```

### Alert

```
** Alert 1566491834.26136: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,
2019 Aug 22 18:37:14 disco->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File '/root/test/noalert' was added.
```

FIM is not ignoring files in real-time mode. This is because `realtime_process()` calls `realtime_checksumfile()`, that does not check for `<ignore>` or `<restrict>`

### Fix

This issue has already been fixed in this branch as every engine (scheduled, real-time, and who-data) call `fim_process_event()` (https://github.com/wazuh/wazuh/blob/fix-syscheck-integritydb/src/syscheckd/create_db.c#L243-L259), that does perform file filtering.

**Comment by vikman90** [comment]
## Message format

### File entry event

The agent produces these events when it detects that a file has been either created, modified or removed.

```
{
  type:                     "event"
  data: {
    path:                   string
    mode:                   "scheduled" | "real-time" | "whodata"
    type:                   "added" | "deleted" | "modified"
    timestamp:              number
    changed_attributes: [
      "size"
      "permission"
      "uid"
      "user_name"
      "gid"
      "group_name"
      "mtime"
      "inode"
      "md5"
      "sha1"
      "sha256"
    ]
    tags:                   string
    content_changes:        string
    old_attributes: {
      type:                 "file" | "registry"
      size:                 number
      perm:                 string
      user_name:            string
      group_name:           string
      uid:                  string
      gid:                  string
      inode:                number
      mtime:                number
      hash_md5:             string
      hash_sha1:            string
      hash_sha256:          string
      win_attributes:       string
      symlink_path:         string
      checksum:             string
    }
    attributes: {
      type:                 "file" | "registry"
      size:                 number
      perm:                 string
      user_name:            string
      group_name:           string
      uid:                  string
      gid:                  string
      inode:                number
      mtime:                number
      hash_md5:             string
      hash_sha1:            string
      hash_sha256:          string
      win_attributes:       string
      symlink_path:         string
      checksum:             string
    }
    audit: {
      user_id:              string
      user_name:            string
      group_id:             string
      group_name:           string
      process_name:         string
      audit_uid:            string
      audit_name:           string
      effective_uid:        string
      effective_name:       string
      ppid:                 number
      process_id:           number
    }
  }
}
```

### Scan info event

These events are produced everytime a scheduled scan starts and ends.

```
{
  type:         "scan_start" | "scan_end"
  data: {
    timestamp:  number
  }
}
```

### Integrity check control message

The agent sends an integrity verification message periodically to check that the manager's database is a mirror of the agent's data set.

```
{
  component:    "syscheck"
  type:         "integrity_check_global"
  data: {
    id:         number
    begin:      string
    end:        string
    checksum:   string
  }
}
```

#### Response (checksum failed)

If the manager's database contains some data in the range defined, but the checksum does not match, it responds the following message:

```
syscheck dbsync checksum_fail { "begin": "string", "end": "string" }
```

When the agent receives this message, it splits the range into two subsets and sends two messages `integrity_check_left` and `integrity_check_right` (explained below).

#### Response (no data)

Instead, if the are no content in the range specified, the manager answers this message:

```
syscheck dbsync no_data { "begin": "string", "end": "string" }
```

This message makes the agent report the entire data set.

#### Integrity check division control message

When the agent receives a `checksum_fail` message, it splits the data between `begin` and `end`, and answers these two messages:

```
{
  component:    "syscheck"
  type:         "integrity_check_left"
  data: {
    id:         number
    begin:      string
    end:        string
    tail:       string
    checksum:   string
  }
}

{
  component:    "syscheck"
  type:         "integrity_check_right" | "integrity_check_global"
  data: {
    id:         number
    begin:      string
    end:        string
    checksum:   string
  }
}
```

### Integrity clear control message

In the particular case when the agent has no data, it delivers a database clear message. This makes the manager erase its database.

```
{
  component: string
  type:      "integrity_clear"
}
```

### File state message

When either the agent receives a `no_data` message for a data range or a `checksum_fail` message with `begin=end` (data range size = 1), it sends one or multiple state messages, one per each file that must synchronize:

```
{
  component:            "syscheck"
  type:                 "state"
  data: {
    path:               string
    timestamp:          number
    attributes: {
      type:             "file" | "registry"
      size:             number
      perm:             string
      user_name:        string
      group_name:       string
      uid:              string
      gid:              string
      inode:            number
      mtime:            number
      hash_md5:         string
      hash_sha1:        string
      hash_sha256:      string
      win_attributes:   string
      symlink_path:     string
      checksum:         string
    }
  }
}
```

**Comment by vikman90** [comment]
## Configuration options changes

### New Syscheck options

```xml
<syscheck>
  <inventory>
    <sync_interval />
    <response_timeout />
  </inventory>
  <max_eps />
</syscheck>
```

|Option|Range|Default|Description|
|---|---|---|---|
|`sync_interval`|`1` .. _LONG_MAX_|`10m`|Synchronization interval, in seconds. `smhdw` suffixes allowed.|
|`response_timeout`|`0` .. _LONG_MAX_|`1m`|Minimum time since the last synchronization message received before starting a new synchronization stage, in seconds. `smhdw` suffixes allowed.|
|`max_eps`|`1` .. `1000000`|`200`|Maximum output throughput, in messages per second. This setting applies to events and synchronization control messages.|

### New Wazuh DB options

Described at https://github.com/wazuh/wazuh/issues/3803#issuecomment-519630569.

### Deprecated Syscheck options:

```xml
<syscheck>
  <auto_ignore>
  <alert_new_files>
</syscheck>
```

**Comment by vikman90** [comment]
## Pending subtasks

### Development

- [X] Do not scan _ossec.conf_ or _internal_options.conf_ on start.
- [X] Merge Wazuh DB commit time limit branch.
- [X] Read inode though `<check_inode=no>`.
- [X] Send and store synchronization time (attempt and reached).
- [X] Decoder: build attribute change description string.
- [X] Refactor save control message with state.
- [X] Fix leaky bucket output timing (accurate EPS).
- [X] Find out why Wazuh DB got stuck.
- [X] Agentd: fix broken pipe error.
- [X] Fix double _type=check_ member at integrity control messages.
- [ ] Merge perm and win_perm . Discuss format on Windows.
- [ ] Discuss definitely option <inventory> name.
- [ ] Research file read timeout.
- [X] Ignore proc, sys, and dev file systems by default. Add user options to set up them.
- [ ] Fix <directories>///</directories> .
- [X] Windows agent: scan Registry.
- [ ] Windows agent: send win_attributes.
- [ ] Send different audit (whodata) fields depending on the platform.
- [X] Check issue #3990.
- [ ] Possible issue calling `fim_update()` when a file is replaced (inode changes). Inode hash table may not be updated.
- [ ] Implement an RT notify cache (like database module).
- [ ] Monitor symbolic links, including directories. Implement a thread to reload links. (*)
- [ ] Replace char matrix at inode hash table with a `W_Vector` instance.
- [ ] Whodata: parse paths when they come defined in hexadecimal format.
- [ ] Deprecate `<alert_new_files>`.
- [ ] Enable all `check-*` options but `check_md5` and `check_sha1` by default.
- [ ] Check files inodes on Windows.

(*)

- _linka_ -> _/home/usera_.
- Remove entries from _/home/usera_.
- Add entries to _/home/userb_.
- On RT or whodata, remove current watch and add the new directory.

### Documentation

- [ ] Doxygen for integrity message dispatcher (Analysisd).
- [ ] Doxygen for Syscheckd.
- [ ] `commit_time_max` and `commit_time_min` for Wazuh DB.
- [ ] `<inventory>`, and `<max_eps>` for Syscheckd.
- [ ] `<skip_proc>`, `<skip_dev>`, and `<skip_sys>`.
- [ ] `process_priority`.
- [ ] `rt_delay` default value changed from `10` to `1`.

### Testing

- [ ] Functional tests (Python).
- [ ] Unit tests (C).
- [ ] Compile agent on Raspberry Pi.
- [ ] Compile agent on HP-UX
- [ ] Compile agent on AIX.
- [ ] Compile agent on Solaris.
- [ ] Test who-data on SLES 12.
- [ ] Check behavior on macOS. Are there links to _/private_?
- [ ] Check issue #3007 (_/dev/kcore_) related to read timeout.
- [ ] Check alerts and events with files and directories including strange characters.
- [ ] Check fields in alerts, with old and new agents.
- [ ] Check `fim_configuration_directory()` when a file name starts like another subfolder in the same directory.
- [ ] Check the behavior monitoring _/root/file.txt_ with real-time and who-data.
- [ ] Test old agents (older than 3.7 and older than 3.10).
- [ ] Measure file scan time with 1GB files.

**Comment by vikman90** [comment]
## Basic test on HP-UX

### Compilation

We need GCC 4.2.3.

```shell
/usr/local/bin/depothelper -f gcc

gmake -C src TARGET=agent DISABLE_SHARED=yes
USER_BINARYINSTALL=y /usr/local/bin/bash install.sh
```

### Shared configuration

```xml
<agent_config>

  <client_buffer>
    <events_per_second>100</events_per_second>
  </client_buffer>


  <syscheck>
    <frequency>30</frequency>
    <directories check_all="yes" check_md5sum="no" check_sha1sum="no">///</directories>
    <ignore>/opt</ignore>

    <max_eps>100</max_eps>

    <inventory>
      <sync_interval>1m</sync_interval>
      <response_timeout>10s</response_timeout>
    </inventory>
  </syscheck>

  <rootcheck>
    <disabled>yes</disabled>
  </rootcheck>

</agent_config>
```

### Notable issues

1. Syscheck logs a warning if a file's UID does not match any user. 
```
2019/10/01 08:24:59 ossec-syscheckd: WARNING: ~~~ User with uid `1000` not found
```
This should not be a warning.

2. Syscheck prints a warning about _real-time_ and _who-data_ are not available on this system.
```
2019/10/01 08:29:53 ossec-syscheckd: WARNING: (6905): The realtime monitoring request on unsupported system.
```
This should either be an information message, or appear only if any directory is setup to be monitored in _who-data_ or _real-time_ mode.

3. Agentd is not able to connect to Syscheck after 1:30 h running.
```
2019/10/01 08:30:16 ossec-agentd: ERROR: dbsync: cannot connect to syscheck: Connection refused (239)
```
This is due to a bug in Syscheck that made the main thread close wherever _who-data_ is not available. This has been already fixed.

**Comment by vikman90** [comment]
## Basic test on AIX

### Compilation

```shell
gmake -C src deps RESOURCES_URL=http://packages.wazuh.com/deps/3.11
gmake -C src TARGET=agent DISABLE_SHARED=yes
USER_BINARYINSTALL=y bash install.sh
```

### Shared configuration

(Same as HP-UX agent)

### Notable issues

Syscheck logs an error if a file's UID does not match any user.

```
2019/10/02 08:13:22 ossec-syscheckd: ERROR: Failed getting user_name (-1):'Error -1 occurred.'
```

I think this issue is similar to HP-UX's issue point 1.

## Synchronization performance

|Platform|Files|Time to synchronize|Avg. throughput|
|---|---|---|---|
|**HP_UX**|91.864|70 min.|50 EPS|
|**AIX**|157.366|38 min.|100 EPS|

**Comment by vikman90** [comment]
## Basic test on Solaris 10

### Compilation issues

1. `getpwuid_r` has a different syntax than other UNIX platforms.

```
shared/syscheck_op.c:597:9: error: too many arguments to function 'getpwuid_r'
     s = getpwuid_r(uid, &pwd, buf, bufsize, &result);
         ^
In file included from ./headers/syscheck_op.h:19:0,
                 from shared/syscheck_op.c:11:
/usr/include/pwd.h:173:23: note: declared here
 extern struct passwd *getpwuid_r(uid_t, struct passwd *, char *, int);
                       ^
shared/syscheck_op.c:597:7: warning: assignment makes integer from pointer without a cast
     s = getpwuid_r(uid, &pwd, buf, bufsize, &result);
       ^
```

This is being fixed in #3474.

2. Solaris 11 needs option `-z relax=secadj` but Solaris 10 does not support it:

```
ld: fatal: option -z has illegal argument 'relax=secadj'
ld: fatal: flags processing errors
```

### Notable issues

1. Syscheck logs that it does not support _real-time_ (as HP-UX's issue point 2.

```
2019/10/03 16:57:27 ossec-syscheckd: WARNING: (6905): The realtime monitoring request on unsupported system.
```

**Comment by fabinou** [comment]
Hi,

After talking with @5albrecs , we are planing to implement Wazuh for our company, but we have a feature on our actual product wich compare files changes vs a "frozen repository".

What about to implement an option telling not to upgrade central database with the new hash on each change ? I think it's could be an "easy way" to implement such feature (since it's really usefull for us because we have binaries and configuration file that's must stay the same for years sometimes !)

Or may be do you suggest another approach to achieve this ?

Thanks for this great product anyway !

**Comment by vikman90** [comment]
Hi @fabinou,

Thank you for your comment. This request is close to a feature that is already in our roadmap: support for file baselines. After a little talk with the team, we think that the best way to achieve this is having two datasets in the database:

- The current state of every file (sent by the agent).
- The baseline (initial or desired state) of the files.

This way, the manager can report which files have differences (don't belong to the baseline) and which ones are identical (match the baseline). We could visualize this in the Kibana App. In addition, alerts may include baseline data:

- When a file ceased to belong to the baseline.
- Whether a file went back to the baseline.

One of the main goals of this issue is having a consistent copy of the agent's files state, so this will make things easier.

Regarding the baseline construction, I think that we could build a baseline for a group of agents from a particular agent's file list. Then we would assign that baseline to every agent of that group. We should allow manual baseline definition and modification also.

What do you think about this? How would you set a baseline or "immutable file list" for an agent or a group of agents?

All feedback is welcome!

**Comment by bah07** [comment]
We have detected a bug in agents using Audit version 2.8.5. In operations performed with the command `mv` Whodata does not report alerts because Audit does not generate any event.

>root@centos7:/$ auditctl -v
>auditctl version 2.8.5

>root@centos7:/$ auditctl -l
>-w /test -p wa -k wazuh_fim

>root@centos7:/$ echo "aaa" >> /test/aa
audit.log ouput:
```log
type=SYSCALL msg=audit(1570810321.840:1232): arch=c000003e syscall=2 success=yes exit=3 a0=224c720 a1=441 a2=1b6 a3=fffffff0 items=2 ppid=20329 pid=20355 auid=1000 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts2 ses=11 comm="bash" exe="/usr/bin/bash" subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key="wazuh_fim"
type=CWD msg=audit(1570810321.840:1232):  cwd="/"
type=PATH msg=audit(1570810321.840:1232): item=0 name="/test/" inode=2228225 dev=08:01 mode=040755 ouid=0 ogid=0 rdev=00:00 obj=unconfined_u:object_r:default_t:s0 objtype=PARENT cap_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0
type=PATH msg=audit(1570810321.840:1232): item=1 name="/test/aa" inode=2228227 dev=08:01 mode=0100644 ouid=0 ogid=0 rdev=00:00 obj=unconfined_u:object_r:default_t:s0 objtype=CREATE cap_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0
type=PROCTITLE msg=audit(1570810321.840:1232): proctitle="bash"
```

**Comment by vikman90** [comment]
## FIM Alpha 1

### Environment

|System|Version|Platform|
|---|---|---|
|Manager|FIM branch|Debian 10|
|Agent|FIM branch|Windows Server 2019|
|Agent|FIM branch|CentOS 8|
|Agent|3.6.2|CentOS 7|
|Agent|3.10.2|CentOS 7|
|Manager|FIM branch|Raspbian 10|

### Successful tests

- Agent upgrade from v3.11 to v3.12 (sources/NSIS).
- Database upgrade from v3.11 (DB v3) to v3.12 (DB v4).
- No wrong fields detected in alerts coming from agents v3.6+.
- File inventory data seems correct.
- (Raspbian) No noticeable memory usage increase after 3 days running.

### Notes

- Every Windows Registry key has a leading architecture mark: `[x32]` or `[x64]`.
- The new agent reports file permissions with a slightly different syntax (compatible):
![Screen Shot 2019-10-18 at 17 41 21 (2)](https://user-images.githubusercontent.com/10536251/67185457-2af15f00-f3e6-11e9-867c-f42ac9330b01.png)
- Windows's files permissions field is not very readable in Kibana:
<img width="1680" alt="Screen Shot 2019-10-17 at 19 04 01" src="https://user-images.githubusercontent.com/10536251/67185516-4c524b00-f3e6-11e9-8ea6-c2ab0e605c3f.png">

- Alerts about file deleted include the last known attributes of the file.

```json
2019/10/18 18:39:36 ossec-syscheckd[4295] run_check.c:63 at send_syscheck_msg(): DEBUG: (6321): Sending event: {"type":"event","data":{"path":"/root/test-rt/file-02","mode":"real-time","type":"deleted","timestamp":1571416746,"attributes":{"type":"file","size":0,"perm":"rw-r--r--","uid":"0","gid":"0","user_name":"root","group_name":"root","inode":18297036,"mtime":1571412040,"hash_md5":"d41d8cd98f00b204e9800998ecf8427e","hash_sha1":"da39a3ee5e6b4b0d3255bfef95601890afd80709","hash_sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","checksum":"02b1c1bd08bcfd8bb8bbc2c5a896b1b976edc5da"}}}
```

### Issues detected

- Unit test: `fim_insert()` does not return `-1` if `fim_update_inode()` fails.
- Unit test: `fim_update()` does not return even if `file == NULL`.
- 8 unit tests failed due to the last changes in the branch, that were not applied in the tests.
- NSIS installer for Windows left both versions (v3.11 and v3.12) in the Applications panel.
- (Raspbian) two alerts (file truncated + modified) were triggered for the same change:
```sh
head -c106 /dev/urandom > file-01
```
- Syscheckd logs a lot of errors again and again when trying to monitor more than 256 directories in who-data mode:
<img width="834" alt="Screen Shot 2019-10-18 at 17 59 33" src="https://user-images.githubusercontent.com/10536251/67185955-46a93500-f3e7-11e9-8c27-84da3ceac255.png">

- (Windows) Warning message 6920 because Registry key _HKLM\System\CurrentControlSet\Services\MpsSvc_ does not exist. Should we silence this log or remove that stanza from the configuration template?
<img width="1680" alt="Screen Shot 2019-10-18 at 17 41 21" src="https://user-images.githubusercontent.com/10536251/67186062-84a65900-f3e7-11e9-89d1-2b9d9e28da02.png">

- (Raspbian) These logs appear again and again:
```
2019/10/21 08:31:15 ossec-syscheckd: ERROR: Couldn't get attributes for file: '/home/pi/test/file-10'
2019/10/21 08:31:15 ossec-syscheckd: WARNING: (6923): Unable to process file '/home/pi/test/file-10'
2019/10/21 08:31:25 ossec-syscheckd: INFO: Data not found for file /home/pi/test/file-08
```
