### ISSUE TITLE
Implement RBAC security endpoints 

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#3410]
## Introduction
Once we have made a functional first implementation of our database management system RBAC #3375, we will proceed to make the endpoints for the administration of this.

## Endpoints definition
We must make the following endpoints in order to cover the functionalities as indicated in #3287 :

### Roles and policies management
Customizing RBAC must be as simple as possible, so a catalog of new API endpoints will be provided to operate the CRUD cycle of roles and policies:
- `PUT /security/role`: creates a new `role` given a name, a `rule` and optionally the ids of `policies` related to it.
- `GET /security/roles`: lists all existing `roles` and their details.
- `GET /security/role/:role_id`: gets the full definition of a `role` given its id (including `policies` related to it)
- `POST /security/role/:role_id`: updates an existing `role`. It allows changing the `rule`, name or relating `policies`.
- `DELETE /security/role/:role_id`: deletes an existing `role`. It should also remove all the relationships to any `policies`.
- `PUT /security/policy`: creates a new `policy` given a name and a definition.
- `GET /security/policies`: lists all existing `policies` and their details.
- `GET /security/policy/:policy_id`: gets the full definition of a `policy` given its id (including name and definition)
- `POST /security/policy/:policy_id`: updates an existing `policy` given its id.
- `DELETE /security/policy/:policy_id`: deletes an existing `policy`. It should also remove all 
the relationships to any `roles`.
- `POST /security/role/:role_id/policy/:policy_id`: attaches a `role` and a `policy`.
- `DELETE /security/role/:role_id/policy/:policy_id`: detaches a `role` and a `policy`.

## Pending
- [x] PUT /security/role
- [x] GET /security/roles
- [x] GET /security/role/:role_id
- [x] POST /security/role/:role_id
- [x] DELETE /security/role/:role_id
- [x] PUT /security/policy
- [x] GET /security/policies
- [x] GET /security/policy/:policy_id
- [x] POST /security/policy/:policy_id
- [x] DELETE /security/policy/:policy_id
- [x] POST /security/role/:role_id/policy/:policy_id
- [x] DELETE /security/role/:role_id/policy/:policy_id

**Comment by AdriiiPRodri** [comment]
## Status update

We've been debating the functions and uses of these endpoints and the RBAC database, now I'm going to comment on the changes with respect to the first definition and the current state of development.

We will start by commenting that currently we are not following some **good practices** for the spec of our RESTful API, as we can see in the following link [PUT-POST in RESTful API](https://restfulapi.net/rest-put-vs-post/) .
As we can see the PUT method is **idempotent**, which means that if the request is executed multiple times the result must be **the same** as if we execute it only once, this means that the PUT method must be used to modify existing entities in the system or to create a specific entity which we create with a identifier in the URL, the POST however does **not have the feature of being idempotent** which causes that if we execute the request N times, in the end we should have **N different entities**. Therefore it is necessary to modify all our spec to adjust it to the use of good practices.
From here I will comment the endpoints in the same order that in the first definition but placing the correct method as we have indicated:

- `POST /security/role`: The method has been modified to POST, for this endpoint initially the definition said that a new role would be created giving its name, rule and optionally a list of associated policies. We decided to remove the option to add a list of associated policies due to problems with concurrency. The problem is that SQLAlchemy in combination with SQLite3 uses sessions for possible users who are in the system so that one user can be adding a role while another is deleting it, causing a **race condition**. We have decided to leave the functionality of adding policies to a role to the endpoint created for this: `PUT /security/role/:role_id/policy/:policy_id`, this method has also seen its method altered.

- `GET /security/roles`: At first this endpoint indicated that all roles should be listed with their details, which was interpreted as all their information, this has been redefined and it has been decided to show only the name and rule of each role.

- `GET /security/role/:role_id`: This endpoint is working correctly, we must change the database definition of the policy element of the Policies object (varchar to text).

- `PUT /security/role/:role_id`: This endpoint has seen modified its method, initially in that method could modify the policies as well as the name and rule, we have chosen to remove this feature and leave the union of role-policy to the endpoint created for this: `PUT /security/role/:role_id/policy/:policy_id`

- `DELETE /security/role/:role_id`: This endpoint has not been modified.

- The policy endpoints have not been modified.

- `PUT /security/role/:role_id/policy/:policy_id`: The method of this endpoint has been changed, this endpoint is **exclusively responsible** for creating relationships between roles and policies, if a role or policy does not exist should cancel the operation.

- `DELETE /security/role/:role_id/policy/:policy_id`: This endpoint has not seen its original definition modified.

**Comment by AdriiiPRodri** [comment]
## Status update

The endpoints are ready, we have to create integrated tests for them and improve the docstring and error messages.

Currently the behavior when you delete a role is that it is deleted but the policies it had assigned are not affected.
If we remove a policy, it is removed from all roles.

## ToDo

- [ ] Do the integrated tests
- [ ] Improve docstring
- [ ] Improve error messages

**Comment by AdriiiPRodri** [comment]
## Status update

We are currently working on the implementation of integrated tests for these endpoints.

Right now our endpoints work correctly with the tests we have done manually, performing the integrated tests we have decided to add to the parameters we currently have, limit and offset, the parameters sort and search so that we can sort both roles and policies and search for a specific role or policy.

The sort parameter will allow you to sort roles and policies by name in ascending or descending order, this will be the only field by which you can sort, this may change in the future.

The search parameter will allow to search the roles and policies by name, we will not need to enter the full name to perform the search, that is, if for example we have the roles admin1, admin2 and admin3, if we search by admin will appear the three, and if we search by admin1 will appear only this if it exists, this way we increase the possibilities of this parameter and we do not do so strict and still maintain the exact search.

## ToDo
- [ ] Implement sort parameter
- [ ] Implement search parameter

**Comment by AdriiiPRodri** [comment]
## Status update

The tests for the GET, POST, PUT methods have been added, the tests for the DELETE method are in progress, the last one are more complex, it will be as soon as possible.

The tests are not definitive and check the functionalities as far as they are defined.

## Outputs
#### GET
```bash
root@56ea5661b614:/# /var/ossec/framework/python/bin/pytest -vv /var/ossec/framework/python/bin/test/test_rbac_GET_endpoint.tavern.yaml 
================================ test session starts ================================
platform linux -- Python 3.7.2, pytest-4.6.2, py-1.8.0, pluggy-0.12.0 -- /var/ossec/framework/python/bin/python3.7
cachedir: .pytest_cache
rootdir: /var/ossec/framework/python/bin/test
plugins: tavern-0.26.4
collected 2 items                                                                   

var/ossec/framework/python/bin/test/test_rbac_GET_endpoint.tavern.yaml::GET /security/roles PASSED [ 50%]
var/ossec/framework/python/bin/test/test_rbac_GET_endpoint.tavern.yaml::GET /security/policies PASSED [100%]

================================= warnings summary ==================================
var/ossec/framework/python/lib/python3.7/site-packages/yaml/constructor.py:126
  /var/ossec/framework/python/lib/python3.7/site-packages/yaml/constructor.py:126: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    if not isinstance(key, collections.Hashable):

test_rbac_GET_endpoint.tavern.yaml::GET /security/roles
test_rbac_GET_endpoint.tavern.yaml::GET /security/policies
  /var/ossec/framework/python/lib/python3.7/site-packages/jwt/api_jwt.py:81: DeprecationWarning: It is strongly recommended that you pass in a value for the "algorithms" argument when calling decode(). This argument will be mandatory in a future version.
    DeprecationWarning

-- Docs: https://docs.pytest.org/en/latest/warnings.html
======================= 2 passed, 3 warnings in 0.92 seconds ========================
```
#### POST
```bash
root@56ea5661b614:/# /var/ossec/framework/python/bin/pytest -vv /var/ossec/framework/python/bin/test/test_rbac_POST_endpoint.tavern.yaml 
================================ test session starts ================================
platform linux -- Python 3.7.2, pytest-4.6.2, py-1.8.0, pluggy-0.12.0 -- /var/ossec/framework/python/bin/python3.7
cachedir: .pytest_cache
rootdir: /var/ossec/framework/python/bin/test
plugins: tavern-0.26.4
collected 2 items                                                                   

var/ossec/framework/python/bin/test/test_rbac_POST_endpoint.tavern.yaml::POST /security/roles PASSED [ 50%]
var/ossec/framework/python/bin/test/test_rbac_POST_endpoint.tavern.yaml::POST /security/policies PASSED [100%]

================================= warnings summary ==================================
var/ossec/framework/python/lib/python3.7/site-packages/yaml/constructor.py:126
  /var/ossec/framework/python/lib/python3.7/site-packages/yaml/constructor.py:126: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    if not isinstance(key, collections.Hashable):

test_rbac_POST_endpoint.tavern.yaml::POST /security/roles
test_rbac_POST_endpoint.tavern.yaml::POST /security/policies
  /var/ossec/framework/python/lib/python3.7/site-packages/jwt/api_jwt.py:81: DeprecationWarning: It is strongly recommended that you pass in a value for the "algorithms" argument when calling decode(). This argument will be mandatory in a future version.
    DeprecationWarning

-- Docs: https://docs.pytest.org/en/latest/warnings.html
======================= 2 passed, 3 warnings in 0.63 seconds ========================
```
#### PUT
```bash
root@56ea5661b614:/# /var/ossec/framework/python/bin/pytest -vv /var/ossec/framework/python/bin/test/test_rbac_PUT_endpoint.tavern.yaml 
================================ test session starts ================================
platform linux -- Python 3.7.2, pytest-4.6.2, py-1.8.0, pluggy-0.12.0 -- /var/ossec/framework/python/bin/python3.7
cachedir: .pytest_cache
rootdir: /var/ossec/framework/python/bin/test
plugins: tavern-0.26.4
collected 3 items                                                                   

var/ossec/framework/python/bin/test/test_rbac_PUT_endpoint.tavern.yaml::PUT /security/roles PASSED [ 33%]
var/ossec/framework/python/bin/test/test_rbac_PUT_endpoint.tavern.yaml::PUT /security/roles/{role_id}/policies/{policy_id} PASSED [ 66%]
var/ossec/framework/python/bin/test/test_rbac_PUT_endpoint.tavern.yaml::PUT /security/policies PASSED [100%]

================================= warnings summary ==================================
var/ossec/framework/python/lib/python3.7/site-packages/yaml/constructor.py:126
  /var/ossec/framework/python/lib/python3.7/site-packages/yaml/constructor.py:126: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    if not isinstance(key, collections.Hashable):

test_rbac_PUT_endpoint.tavern.yaml::PUT /security/roles
test_rbac_PUT_endpoint.tavern.yaml::PUT /security/roles/{role_id}/policies/{policy_id}
test_rbac_PUT_endpoint.tavern.yaml::PUT /security/policies
  /var/ossec/framework/python/lib/python3.7/site-packages/jwt/api_jwt.py:81: DeprecationWarning: It is strongly recommended that you pass in a value for the "algorithms" argument when calling decode(). This argument will be mandatory in a future version.
    DeprecationWarning

-- Docs: https://docs.pytest.org/en/latest/warnings.html
======================= 3 passed, 4 warnings in 1.01 seconds ========================
```

**Comment by AdriiiPRodri** [comment]
## Status update
Added integrated tests for DELETE method

## Output
```bash
root@039d05c078c1:/# /var/ossec/framework/python/bin/pytest -vv /var/ossec/framework/python/bin/test/test_rbac_DELETE_endpoint.tavern.yaml 
========================= test session starts ==========================
platform linux -- Python 3.7.2, pytest-4.6.2, py-1.8.0, pluggy-0.12.0 -- /var/ossec/framework/python/bin/python3.7
cachedir: .pytest_cache
rootdir: /var/ossec/framework/python/bin/test
plugins: tavern-0.26.4
collected 5 items                                                      

var/ossec/framework/python/bin/test/test_rbac_DELETE_endpoint.tavern.yaml::DELETE /security/roles/{role_id} PASSED [ 20%]
var/ossec/framework/python/bin/test/test_rbac_DELETE_endpoint.tavern.yaml::DELETE /security/policies/{policy_id} PASSED [ 40%]
var/ossec/framework/python/bin/test/test_rbac_DELETE_endpoint.tavern.yaml::DELETE /security/roles/{role_id}/policies/{policy_id} PASSED [ 60%]
var/ossec/framework/python/bin/test/test_rbac_DELETE_endpoint.tavern.yaml::DELETE /security/roles PASSED [ 80%]
var/ossec/framework/python/bin/test/test_rbac_DELETE_endpoint.tavern.yaml::DELETE /security/policies PASSED [100%]

=========================== warnings summary ===========================
var/ossec/framework/python/lib/python3.7/site-packages/yaml/constructor.py:126
  /var/ossec/framework/python/lib/python3.7/site-packages/yaml/constructor.py:126: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    if not isinstance(key, collections.Hashable):

test_rbac_DELETE_endpoint.tavern.yaml::DELETE /security/roles/{role_id}
test_rbac_DELETE_endpoint.tavern.yaml::DELETE /security/policies/{policy_id}
test_rbac_DELETE_endpoint.tavern.yaml::DELETE /security/roles/{role_id}/policies/{policy_id}
test_rbac_DELETE_endpoint.tavern.yaml::DELETE /security/roles
test_rbac_DELETE_endpoint.tavern.yaml::DELETE /security/policies
  /var/ossec/framework/python/lib/python3.7/site-packages/jwt/api_jwt.py:81: DeprecationWarning: It is strongly recommended that you pass in a value for the "algorithms" argument when calling decode(). This argument will be mandatory in a future version.
    DeprecationWarning

-- Docs: https://docs.pytest.org/en/latest/warnings.html
================= 5 passed, 6 warnings in 1.13 seconds =================
```

**Comment by AdriiiPRodri** [comment]
## Status update

The policies are now created in the same way as indicated in the issue https://github.com/wazuh/wazuh/issues/3287:

```json
{
  "actions": ["agent:delete"],
  "resources": ["agent:id:001", "agent:id:002", "agent:id:003"],
  "effect": "allow"
}
```

In order to do this, all the necessary fields have been added to the spec, however we cannot control in the spec that the policy that is sent to the API has the fields in the correct format, to solve this a regular expression has been added. 

```regex
r'^[a-z*]+:[a-z0-9*]+(:[a-z0-9*]+)*$'
```

This regular expression will allow to introduce values in the policies as long as they are separated by : and each : must be between two elements.
With this regular expression only valid policies can be created, these will have the format:

- For example: ```agent:id:001``` or ```agent:*```, etc. Policies will not be accepted with a format other than this one, the following: ```agent.id.001``` or ```agent:id:001:``` will not be accepted.

Now we can create links between a role and several policies, before this was done one by one, now we can put a list.

The behavior at the time of detecting an error when we try to create or delete a link, will be to cancel the operation and not make any changes. This implies that if we send a list of policies to remove in a particular role and one of them does not exist or has no relationship with the role, the operation will be canceled even if the other relationships exist and it won't change anything.

We have decided to do so for security reasons and that the user knows perfectly what changes have originated the operation.
