### ISSUE TITLE
[Filebeat-3.9.3]Custom module for Filebeat and Wazuh

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh#3566]
### Overview
From the [Beats docs](https://www.elastic.co/guide/en/beats/devguide/current/filebeat-modules-devguide.html):

> Each Filebeat module is composed of one or more "_filesets_". We usually create a module for each service that we support (_nginx_ for Nginx, _mysql_ for Mysql, and so on) and a _fileset_ for each type of log that the service creates. For example, the Nginx module has access and error _filesets_. You can contribute a new module (with at least one _fileset_), or a new _fileset_ for an existing module.

### Why does Wazuh need a Filebeat module?

Here is a list of issues we are working on it but may be solved using a custom Filebeat module:

- Problems indexing rotated events or Filebeat is stopped more than one day https://github.com/wazuh/wazuh-documentation/issues/1269
- Workarounds about the GeoIP features, renaming fields, ingest pipelines https://github.com/wazuh/wazuh/issues/3512
- Problems with the `full_log` field, JSON formats, mapping conflicts https://github.com/wazuh/wazuh/issues/3513

In addition, most of the logic we are doing in configuration files, pipelines and some other files can be achieved using a custom module for Filebeat.

### Creating the module

1. The first step is to learn about Filebeat modules, the reference docs are https://www.elastic.co/guide/en/beats/devguide/current/filebeat-modules-devguide.html, where we can find useful information on how to create a simple module.
2. Once we know how to create the module, we can start to migrate all the Wazuh related logic to this module.

**Tasks**
- [x] Researching about Filebeat modules.
- [x] Implement a simple module to apply acquired knowledge.
- [x] Design and decide what our module should do for us.
- [x] Implement the module, test the module against different use cases.
- [x] Create/update the proper documentation.
- [ ] Should we try to publish it as an official Filebeat module (their website)?

**Comment by jesusgn90** [comment]
**Getting started with Filebeat modules**

Following the how-to docs from the Elastic docs, I've created the very first Filebeat module for testing purposes.

Since it needs "Go" to be installed, I've installed it as follow (using 1.11.5 because is the version for beats v7.1.1):

```sh
GO_VERSION="1.11.5"
curl -so go.tar.gz "https://dl.google.com/go/go$GO_VERSION.linux-amd64.tar.gz"
tar -xzf go.tar.gz 
mv go /usr/local/
rm -f go.tar.gz
```

Setup Go environment:

```sh
export GOROOT=/usr/local/go
export GOPATH=/home/vagrant/filebeat-wazuh-module
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
go version
// go version go1.11.5 linux/amd64
```

Prepare Filebeat:

```sh
go get github.com/elastic/beats
cd src/github.com/elastic/beats/filebeat/
git checkout v7.1.1
go get
make
```

Create an empty module:

```sh
make create-module MODULE=wazuh
// New module was generated, now you can start creating filesets by create-fileset command.
```

Verify the generated empty module:

```
tree module/wazuh/
module/wazuh/
├── _meta
│   ├── config.yml
│   ├── docs.asciidoc
│   └── fields.yml
└── module.yml
```

Now, create the _fileset_ for the module:

```
make create-fileset MODULE=wazuh FILESET=wazuh-fileset
New fileset was generated, please check that module.yml file have proper fileset dashboard settings. After setting up Grok pattern in pipeline.json, please generate fields.yml
```

Verify the generated _fileset_ for the Wazuh module:

```
├── _meta
│   ├── config.yml
│   ├── docs.asciidoc
│   └── fields.yml
├── module.yml
└── wazuh-fileset
    ├── config
    │   └── wazuh-fileset.yml
    ├── ingest
    │   └── pipeline.json
    ├── manifest.yml
    ├── _meta
    └── test
```

After doing a tiny modification in the manifest.yml, I've tried to build the module, then I've noticed `virtualenv` is also needed.

```
yum install python-virtualenv -y
```

Now, and following their docs:

```
make update
mage update
Generated fields.yml for filebeat to /home/vagrant/filebeat-wazuh-module/src/github.com/elastic/beats/filebeat/fields.yml
No fields files for module apache2
Generated fields.yml for filebeat to /home/vagrant/filebeat-wazuh-module/src/github.com/elastic/beats/filebeat/fields.yml
>> Building filebeat.yml for linux/amd64
>> Building filebeat.reference.yml for linux/amd64
>> Building filebeat.docker.yml for linux/amd64
Generated fields.yml for filebeat to /home/vagrant/filebeat-wazuh-module/src/github.com/elastic/beats/filebeat/build/fields/fields.all.yml
```

Load the fake module into Filebeat:

1. First step is to stop Filebeat and to modify its current configuration.

```sh
systemctl stop filebeat
vi /etc/filebeat/filebeat.yml 
```

Here is the testing config I've used:

```yaml
filebeat.modules:
- module: wazuh

output.elasticsearch.hosts: ['http://172.16.1.4:9200']
output.elasticsearch.indices:
  - index: 'testing-module'
```

Copy our module to Filebeat:

```sh
cp modules.d/wazuh.yml.disabled /etc/filebeat/modules.d/
cp module/wazuh/ /usr/share/filebeat/module/ -R
stat -c "%a %n" /usr/share/filebeat/module/zeek # Not needed, just looking for the right perms (755)
chmod 755 /usr/share/filebeat/module/wazuh -R
```

Run Filebeat in debug mode:

```
/usr/share/filebeat/bin/filebeat -e -c /etc/filebeat/filebeat.yml -path.home /usr/share/filebeat -path.config /etc/filebeat -path.data /var/lib/filebeat -path.logs /var/log/filebeat -d '*'
```

Add an alert to the `alerts.json`:

```
cat myalert.json >> /var/ossec/logs/alerts/alerts.json
```

And here is the Filebeat output (reduced because the debug messages are too long):

```
[root@master filebeat]# cat /tmp/output.txt | grep wazuh
    "pipeline": "filebeat-7.1.0-wazuh-wazuh-fileset-pipeline"
    "type": "wazuh"
  "message": "{\"timestamp\":\"2019-06-11T08:29:26.125+0000\",\"rule\":{\"level\":3,\"description\":\"Service startup type was changed\",\"id\":\"61104\",\"info\":\"This does not appear to be logged on Windows 2000\",\"firedtimes\":2,\"mail\":false,\"groups\":[\"windows\",\" windows_systempolicy_changed\"],\"pci_dss\":[\"10.6\"],\"gdpr\":[\"IV_35.7.d\"]},\"agent\":{\"id\":\"010\",\"name\":\"windows-ag\",\"ip\":\"10.0.2.15\"},\"manager\":{\"name\":\"master\"},\"id\":\"1560241766.129973\",\"cluster\":{\"name\":\"wazuh\",\"node\":\"node01\"},\"decoder\":{\"name\":\"windows_eventchannel\"},\"data\":{\"foo\":\"bar\"},\"location\":\"EventChannel\"}",
    "module": "wazuh",
    "dataset": "wazuh.wazuh-fileset"
    "name": "wazuh-fileset"
2019-06-24T15:36:27.186Z	DEBUG	[elasticsearch]	elasticsearch/client.go:752	GET http://172.16.1.4:9200/_ingest/pipeline/filebeat-7.1.0-wazuh-wazuh-fileset-pipeline  <nil>
2019-06-24T15:36:27.187Z	DEBUG	[modules]	fileset/pipelines.go:120	Pipeline filebeat-7.1.0-wazuh-wazuh-fileset-pipeline already loaded
```

As we can see our pipeline is doing the basic job, the event is not _wazuh-comptaible_ yet of course, but it's a first step that I think is useful.

It's in Elasticsearch, and we can see it was indexed in the right index (`testing-module`):

![image](https://user-images.githubusercontent.com/8860227/60032650-5027c800-96a7-11e9-8c3f-7c17a060dcdd.png)

**Comment by jesusgn90** [comment]
## Module definition

Branch: https://github.com/wazuh/wazuh/tree/filebeat-module

### New Filebeat configuration

https://github.com/wazuh/wazuh/blob/ed7aeddb47ae43ce9406aee98de21515b964d935/extensions/filebeat/7.x/filebeat.yml#L1-L13

### New directory tree for _extensions/filebeat/7.x/_

```
├── filebeat.yml
└── wazuh-module
    ├── fields.go
    ├── _meta
    │   ├── config.yml
    │   ├── docs.asciidoc
    │   └── fields.yml
    ├── module.yml
    └── wazuh-fileset
        ├── config
        │   └── wazuh-fileset.yml
        ├── ingest
        │   └── pipeline.json
        ├── manifest.yml
        ├── _meta
        └── test
```

### Wazuh module

**wazuh-module/wazuh-fileset/manifest.yml**

- The manifest file defines the main settings for the module such as variables and some paths.
- Variables under `var:` can be overwritten in `filebeat.yml`.
- The `ingest_pipeline` is a relative path to our ingest pipeline where we put all the processors and logic for parsing and enrich our event.
- The `input` is a relative path to our input configuration where our defined variables will be expanded.

```yaml
module_version: 1.0

var:
  - name: paths
    default:
      - /var/ossec/logs/alerts/alerts.json
  - name: index_prefix
    default:
      - wazuh-alerts-3.x-

ingest_pipeline: ingest/pipeline.json

input: config/wazuh-fileset.yml
```

The user doesn't need to touch any file from this module. All the customizations can be done using _filebeat.yml_.

**wazuh-module/wazuh-fileset/config/wazuh-fileset.yml**

Template file for our input configuration, all is dynamic so you should not modify this file unless you know what you are doing. 

```yaml
fields:
  index_prefix: {{ .index_prefix }}
type: log
paths:
{{ range $i, $path := .paths }}
 - {{$path}}
{{ end }}
```

**wazuh-module/wazuh-fileset/ingest/pipeline.json**

This is our ingest pipeline for Elasticsearch.

- Description
https://github.com/wazuh/wazuh/blob/ed7aeddb47ae43ce9406aee98de21515b964d935/extensions/filebeat/7.x/wazuh-module/wazuh-fileset/ingest/pipeline.json#L2

- Decode events as JSON
  - **Note:** this way to parse events respect the `full_log` escaped as a String.
https://github.com/wazuh/wazuh/blob/ed7aeddb47ae43ce9406aee98de21515b964d935/extensions/filebeat/7.x/wazuh-module/wazuh-fileset/ingest/pipeline.json#L4

- GeoIP
  - We can add as many fields as we want if future releases need it.
https://github.com/wazuh/wazuh/blob/ed7aeddb47ae43ce9406aee98de21515b964d935/extensions/filebeat/7.x/wazuh-module/wazuh-fileset/ingest/pipeline.json#L5-L31

- Ensure the event is going to be indexed in the right index depending on the event timestamp.
https://github.com/wazuh/wazuh/blob/ed7aeddb47ae43ce9406aee98de21515b964d935/extensions/filebeat/7.x/wazuh-module/wazuh-fileset/ingest/pipeline.json#L32-L48

- Remove extra fields, temporary fields, Elastic stack added fields...
https://github.com/wazuh/wazuh/blob/ed7aeddb47ae43ce9406aee98de21515b964d935/extensions/filebeat/7.x/wazuh-module/wazuh-fileset/ingest/pipeline.json#L49-L63

- Add an extra field if an error is thrown but it was not handled properly (pretty weird situation but possible situation)
https://github.com/wazuh/wazuh/blob/ed7aeddb47ae43ce9406aee98de21515b964d935/extensions/filebeat/7.x/wazuh-module/wazuh-fileset/ingest/pipeline.json#L65-L70

### Using the module

**Note:** this is not the final way we are going to use, just for testing purposes. We must explorer different ways to create distributable Filebeat modules.

1. Install Filebeat.

```sh
yum install filebeat-7.1.1 -y
```

2. Download the Filebeat configuration file.

```sh
curl -so /etc/filebeat/filebeat.yml https://raw.githubusercontent.com/wazuh/wazuh/filebeat-module/extensions/filebeat/7.x/filebeat.yml
chmod go+r /etc/filebeat/filebeat.yml
```

3. Set your Elasticsearch address.

```sh
sed -i 's:YOUR_ELASTIC_SERVER_IP:172.16.1.4:g' /etc/filebeat/filebeat.yml
```

4. Download the Elasticsearch template (which includes `full_log` as text).

```sh
curl -so /etc/filebeat/wazuh-template.json https://raw.githubusercontent.com/wazuh/wazuh/filebeat-module/extensions/elasticsearch/7.x/wazuh-template.json
chmod go+r /etc/filebeat/wazuh-template.json
```

5. Download and extract the Wazuh module for Filebeat.

```sh
curl -so /tmp/wazuh-module.zip https://packages-dev.wazuh.com/utils/wazuh-module.zip
unzip /tmp/wazuh-module.zip -d /usr/share/filebeat/module/wazuh
chmod 755 -R /usr/share/filebeat/module/wazuh
```

6. Enable and restart the service.

```sh
systemctl enable filebeat
systemctl daemon-reload
systemctl restart filebeat
```

Now it should be working as expected.

### Some screenshots

The pipeline was inserted properly:

![image](https://user-images.githubusercontent.com/8860227/60103938-c89e8f80-9760-11e9-8229-0ef4eeec11c3.png)

The template was inserted properly:

![image](https://user-images.githubusercontent.com/8860227/60103994-df44e680-9760-11e9-8c6a-f77ae5ae004e.png)

The `full_log` for an AWS event is being indexed as string:

![image](https://user-images.githubusercontent.com/8860227/60104146-2501af00-9761-11e9-8127-d48b92951583.png)

The `GeoIP` is working as expected:

![image](https://user-images.githubusercontent.com/8860227/60104403-aeb17c80-9761-11e9-9413-5efccf9eb187.png)

Every event is being indexed in the right index depending on the event timestamp:

![image](https://user-images.githubusercontent.com/8860227/60104454-cdb00e80-9761-11e9-8b3d-065586b55b36.png)

**Comment by jesusgn90** [comment]
**Update 27/06/2019**

The module is working as expected however, we need to test it in a more **complex environment** using multiple Filebeat instances and having more than one Elasticsearch nodes. It's also needed to test it against a large dataset so we can benchmark the **performance** for our **ingest pipeline**.

**Latest changes**

- https://github.com/wazuh/wazuh/commit/a1a25bb521a2a5c60027e203a52e9fc09dfaba30 here I've removed a redundant line, however, it should be included/explained in the Wazuh documentation for those users that may want to use a different index name.
- https://github.com/wazuh/wazuh/commit/abf863f7e1c88e3578a52c9fba8ee14643f17e27 here I've just corrected a variable type, after https://github.com/wazuh/wazuh/commit/a1a25bb521a2a5c60027e203a52e9fc09dfaba30 I've realized it was declared in a wrong way (array instead of concrete value)

This is how the `filebeat.yml` looks now:

```yaml
# Wazuh - Filebeat configuration file
filebeat.modules:
  - module: wazuh

setup.template.json.enabled: true
setup.template.json.path: '/etc/filebeat/wazuh-template.json'
setup.template.json.name: 'wazuh'
setup.template.overwrite: true

output.elasticsearch.hosts: ['http://YOUR_ELASTIC_SERVER_IP:9200']
#output.logstash.hosts: ["YOUR_LOGSTASH_SERVER_IP:5000"]
```

And this is how the `manifest.yml` from the module looks now:

```yaml
module_version: 1.0

var:
  - name: paths
    default:
      - /var/ossec/logs/alerts/alerts.json
  - name: index_prefix
    default: wazuh-alerts-3.x-

input: config/wazuh-fileset.yml

ingest_pipeline: ingest/pipeline.json
```

**Insert the template from the module**

Right now I didn't found a solution for this, I've been trying to include it in different files and using different syntax multiple times with no luck. 

On the other hand, I've been talking with the Elastic team with no reply yet, and I've also opened a [discuss](https://discuss.elastic.co/t/load-index-template-from-filebeat-module/187780) in their forums (still waiting for a reply)

**Cleaning opened tickets**

Since this change enhances the way we parse and send the events, some other tickets are now outdated and I've closed them:

- Problems indexing rotated events -> ~~https://github.com/wazuh/wazuh-documentation/issues/1269~~ is fixed with this change :heavy_check_mark: 
- Do not remove fields when renaming -> ~~https://github.com/wazuh/wazuh/issues/3512~~ it's solved here in a better way :heavy_check_mark:.
- Problems with `full_log` mapping -> ~~https://github.com/wazuh/wazuh/issues/3513~~ The mapping has been changed in https://github.com/wazuh/wazuh/pull/3541/commits/e109147d96278b16d190c1eafea5b7cac5699bcd and already merged in 3.9, also with this module, escaped JSON(s) are kept as a string because we are decoding at pipeline level instead of Filebeat level :heavy_check_mark:.

**Next steps (intended to be done 28/06/2019)**

- Check the **performance** against complex environments and with large datasets.
- Update Wazuh **documentation** to be consistent with these changes.
- Update some **variable names**, **file names** for the module.
- Decide the way of **distribution** for this module (one-line command, S3, zip|tar.gz, etc...)

All those points will be finished **tomorrow**.

**Comment by jesusgn90** [comment]
**Testing**
- [x] The next command should be enough for make the module working:
```
curl -s https://packages-dev.wazuh.com/utils/wazuh-filebeat-parent.tar.gz | tar -xvz --no-same-owner -C /usr/share/filebeat/module --owner=0
```
- [x] Alerts from yesterday should be indexed in yesterday's index.
- [x] Alerts from today should be indexed in today's index.
- [x] Alerts with a `full_log` fields being an escaped object should be indexed and they should have the `full_log` as a large string.
- [x] Alerts including a valid IP address in `data.srcip` should generate `GeoLocation.location`.
- [x] Alerts including a invalid IP address in `data.srcip` should not generate `GeoLocation.location` but should be indexed.
- [x] Alerts including a valid IP address in `data.win.eventdata.ipAddress` should generate `GeoLocation.location`.
- [x] Alerts including a invalid IP address in `data.win.eventdata.ipAddress` should not generate `GeoLocation.location` but should be indexed.
- [x] Alerts including a valid IP address in `data.aws.sourceIPAddress` should generate `GeoLocation.location`.
- [x] Alerts including a invalid IP address in `data.aws.sourceIPAddress` should not generate `GeoLocation.location` but should be indexed.

**Performance**

After some researching about _Beats logic vs Elasticsearch logic_ I've concluded that our use case is even faster if using Elasticsearch, in the worst case I think the performance it's almost the same.

Here are some tests I've made to verify these questions:

- [x] Single node - low load should work - **1GB heap x 1**
  - __CentOS 7, 4 core, 4GB + Kibana + Wazuh manager + Filebeat + Elasticsearch__
- [x] Single node - high load should work - **1GB heap x 1**
  - __CentOS 7, 4 core, 4GB + Kibana + Wazuh manager + Filebeat + Elasticsearch__
- [x] Multiple nodes (3 nodes for example) - low load should work - **1GB heap x 3**
  - __CentOS 7, 4 core, 4GB + Kibana + Wazuh manager + Filebeat + Elasticsearch__
  - __CentOS 7, 1 core, 2GB + Elasticsearch__
  - __CentOS 7, 1 core, 2GB + Elasticsearch__
- [x] Multiple nodes (3 nodes for example) - high load should work - **1GB heap x 3**
  - __CentOS 7, 4 core, 4GB + Kibana + Wazuh manager + Filebeat + Elasticsearch__
  - __CentOS 7, 1 core, 2GB + Elasticsearch__
  - __CentOS 7, 1 core, 2GB + Elasticsearch__

All the above tests about the performance were just fine, nothing weird or unexpected occurred. From my view, the module is working just fine.

Here is a script I've used to simulate a real environment:

```
for i in {1..10}; do cat /tmp/alerts.json >> /var/ossec/logs/alerts/alerts.json && sleep 5; done
```

The above script is using a 500K events dataset (`/tmp/alerts.json`) and then it's appending the content to the JSON file Filebeat is reading (`/var/ossec/logs/alerts/alerts.json`). It includes alerts expected to generate a GeoLocation, alerts with escaped-object `full_log`, alerts from yesterday, etc...

At some point, I've reached the _watermark_ in one node. But I've been using two more nodes, so that node started to relegate shards to other nodes, nothing weird.

After some performance testing, I've added a second __Filebeat instance__ in some of the secondary Elasticsearch nodes, then I've started to push more 500K events blocks from this instance too.

**Comment by jesusgn90** [comment]
### Wazuh alerts, Wazuh archives

The module is composed of two sub-modules, the first one is named `alerts` and the second one is named `archives`. Each one has its own configuration file and its own ingest pipeline.

By default, we'll use just the `alerts` sub-module, however, activate the `archives` is as simple as set to `true` a variable.

https://github.com/wazuh/wazuh/blob/4ad23580dfd2f5f27ccd624c029706fb0fd69a2b/extensions/filebeat/7.x/filebeat.yml#L2-L7

For the `archives`, I've added it to our template, so the user will be ready for use it:

https://github.com/wazuh/wazuh/blob/4ad23580dfd2f5f27ccd624c029706fb0fd69a2b/extensions/elasticsearch/7.x/wazuh-template.json#L3

### Ingest pipelines

Both `alerts` and `archives` sub-modules have its own ingest pipeline, however, each one just uses its pipeline, there is no double logic in Elasticsearch.

_Alerts_

https://github.com/wazuh/wazuh/blob/4ad23580dfd2f5f27ccd624c029706fb0fd69a2b/extensions/filebeat/7.x/wazuh-module/alerts/manifest.yml#L10

_Archives_

https://github.com/wazuh/wazuh/blob/4ad23580dfd2f5f27ccd624c029706fb0fd69a2b/extensions/filebeat/7.x/wazuh-module/archives/manifest.yml#L10

### When is a pipeline inserted?

The very first time an event for that sub-module comes to Filebeat, if the pipeline doesn't exist Filebeat tells Elasticsearch it should create it. This means that if you never activate the `archives` for example, you'll never have an ingest pipeline for it.

Here we can see both ingest pipelines inserted:

![image](https://user-images.githubusercontent.com/8860227/61310386-7d721c80-a7f4-11e9-8a99-fb760b13629b.png)

__Note__: I would like to change the ingest pipeline names, but I don't know how to do it yet.

### About the module files

This module has source files, those files are expected to be maintained in our core repository as part of the Filebeat files. However, those files are not the files we are going to distribute for production, instead, we'll build a `.tar.gz` with the generated files by Filebeat as other Filebeat modules are doing.

*Source files*
```
├── alerts
│   ├── config
│   │   └── alerts.yml
│   ├── ingest
│   │   └── pipeline.json
│   ├── manifest.yml
│   ├── _meta
│   └── test
├── archives
│   ├── config
│   │   └── archives.yml
│   ├── ingest
│   │   └── pipeline.json
│   ├── manifest.yml
│   ├── _meta
│   └── test
├── _meta
│   ├── config.yml
│   ├── docs.asciidoc
│   └── fields.yml
└── module.yml
```

*Production files*

```
├── alerts
 │   ├── config
 │   │   └── alerts.yml
 │   ├── ingest
 │   │   └── pipeline.json
 │   └── manifest.yml
 ├── archives
 │   ├── config
 │   │   └── archives.yml
 │   ├── ingest
 │   │   └── pipeline.json
 │   └── manifest.yml
 └── module.yml
```

### Building module

The module will be distributed as a `.tar.gz` file, for building it we must follow some steps using the Beats repository of the Elastic stack. Here is a *draft* pull request for the @wazuh/cicd team, https://github.com/wazuh/wazuh-packages/pull/233, that pull request adds a simple script which generates the `.tar.gz`. It's still a draft because we'll probably need to do some adjustments for our internal packaging instances.

```
./build-wazuh-module.sh 
```

### Version 0.1
As I said, the module has two sub-modules. Each one has a version on its `manifest`.

_Alerts_

https://github.com/wazuh/wazuh/blob/4ad23580dfd2f5f27ccd624c029706fb0fd69a2b/extensions/filebeat/7.x/wazuh-module/alerts/manifest.yml#L1

_Archives_

https://github.com/wazuh/wazuh/blob/4ad23580dfd2f5f27ccd624c029706fb0fd69a2b/extensions/filebeat/7.x/wazuh-module/archives/manifest.yml#L1

### Module docs

Since we are planning to include it in the Filebeat standard modules, the _readme_ file for the module is https://github.com/wazuh/wazuh/blob/filebeat-module/extensions/filebeat/7.x/wazuh-module/_meta/docs.asciidoc and it uses the same syntax as the Elastic guys are using. It's a bit poor so far so we may want to enrich that document.

### Testing

Here are the needed files for giving a try to this module:

- Dev package `tar.gz` -> [wazuh-filebeat.1563290146.tar.gz](https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/utils/wazuh-filebeat.1563290146.tar.gz)
- Elasticsearch template including `archives` -> [wazuh-template.json](https://raw.githubusercontent.com/wazuh/wazuh/filebeat-module/extensions/elasticsearch/7.x/wazuh-template.json)
- Filebeat configuration -> [filebeat.yml](https://raw.githubusercontent.com/wazuh/wazuh/filebeat-module/extensions/filebeat/7.x/filebeat.yml)

The installation just adds an extra step for installing the Wazuh module for Filebeat, you can install it from S3 as follow (being a superuser, before starting Filebeat):

```
curl -s https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/utils/wazuh-filebeat.1563290146.tar.gz | tar -xvz --no-same-owner -C /usr/share/filebeat/module --owner=0
```

**Comment by aggrosparrow** [comment]
Hello there. 
I am having problems using the wazuh module in the context of working with ILM. When I make the appropriate settings in filebeat:
```
setup.ilm.enabled: true
setup.ilm.rollover_alias: "wazuh-alerts-4.x"
setup.ilm.policy_name: "wazuh-ilm"
```
I expect that the filebeat will write events to the `wazuh-alerts-4.x-date-000001` index. And such an index is created automatically, with the setting `is_write_index=true` and the correct alias. 
But instead, events continue to come to the daily index with the name `wazuh-alerts-4.x-date`.
Please tell me what I'm missing.

Sincerely, Vitaly
