### ISSUE TITLE
Fix LGTM reported errors

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#3679]
Hi team,

we recently added LGTM to the Wazuh repository. LGTM is a code analysis tool which detects code improvements to follow good practices as well as vulnerabilities.

In the report detailed by the tool we see that 28 errors are listed to day 2019-07-17 which we will group by file. The branch on which we will apply the changes is dev-flask-poc.

Best regards,
Adri

### Extended report
To view the report in detail: [LGTM](https://lgtm.com/projects/g/wazuh/wazuh/alerts/?mode=list&severity=error)

### ToDo
- [x] framework/wazuh/manager.py:
  - [x] Line 251: Error in move function - Changed in version 3.5: Added the copy_function keyword argument.
  - [x] Line 293: Error in move function - Changed in version 3.5: Added the copy_function keyword argument.
- [x] framework/wazuh/configuration.py:
  - [x] Line 676: Error in move function - Changed in version 3.5: Added the copy_function keyword argument.
- [x] framework/scripts/agent_groups.py:
  - [x] Line 23: Unsafe input in Python 2. Fixed, first we try to make a raw_input in case we are in Python2
- [x] framework/scripts/update_ruleset.py:
  - [x] Line 137: Unsafe input in Python 2. Fixed, first we try to make a raw_input in case we are in Python2

**All the problems related to old-style classes are solved, all our functions are in new-style**
- [x] framework/wazuh/cluster/master.py:
  - [x] Line 37: Access to inherited methods with super is only available at [new-style classes](https://docs.python.org/3/glossary.html#term-new-style-class)
  - [x] Line 52: new-style classes
  - [x] Line 70: new-style classes
  - [x] Line 85: new-style classes
  - [x] Line 103: new-style classes
  - [x] Line 118: new-style classes
  - [x] Line 131: new-style classes
  - [x] Line 192: new-style classes
  - [x] Line 240: new-style classes
  - [x] Line 334: new-style classes
  - [x] Line 350: new-style classes
  - [x] Line 358: new-style classes
  - [x] Line 653: new-style classes
  - [x] Line 665: new-style classes
- [x] framework/wazuh/cluster/worker.py:
  - [x] Line 550: new-style classes
  - [x] Line 564: new-style classes
- [x] framework/wazuh/cluster/local_client.py:
  - [x] Line 22: new-style classes
  - [x] Line 62: new-style classes
  - [x] Line 84: new-style classes
- [x] framework/wazuh/cluster/local_server.py:
  - [x] Line 51: new-style classes
  - [x] Line 119: new-style classes
  - [x] Line 178: new-style classes
  - [x] Line 218: new-style classes
  - [x] Line 243: new-style classes
  - [x] Line 308: new-style classes
- [x] framework/wazuh/agent.py:
  - [x] Line 160: Missing call to __init__ during object initialization - 1f64f90c04fada30d578cdf859bb8abaab330e58
