### ISSUE TITLE
Support for MITRE ATT&CK knowledge base

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#3709]
## Goal

Let Wazuh support the [ATT&CK Matrix for Enterprise](https://attack.mitre.org).

The MITRE attack technique taxonomy has the following attributes:

- ID
- Tactic
- Platform
- Permissions required
- Effective permissions
- Data sources
- Contributors
- Version

1. Ruleset shall include references to the attack technique (id).
2. Alerts will include such reference.
3. Wazuh DB should support the MITRE attack technique taxonomy.
4. Ruleset will include the ATT&CK matrix in JSON format so Wazuh DB will update it.
5. Wazuh API shall add an endpoint to query the ATT&CK matrix to Wazuh DB so that Wazuh App will show the corresponding data for the alerts.

## Subtasks

- [x] Implement parsing of MITRE attack technique ID on rules. #3711 
- [x] Add a table in Wazuh DB to save the MITRE ATT&CK Matrix.
- [x] Insert the MITRE ATT&CK Matrix into Wazuh DB. Discuss about updating.
- [x] Add a query in Wazuh DB to query an attack technique by ID.
- [x] Add an endpoint to the API to query an attack tecnhique by ID.  #4036
- [ ] Extend ruleset with MITRE attack technique ID data, including documentation.
