### ISSUE TITLE
Increase the maximum EPS for the agent bucket

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#3766]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.3 | Agentd | Agent | All | All |

Hi team,

Since the agent queue appeared, the agent EPS by default is set to 500 (https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client_buffer.html?highlight=events_per_second#events-per-second) and the maximum EPS available is 1000.

That limit is too short, it has to be extended to 100000.

The current implementation should be changed, currently, we use the `Sleep()` function of the Windows API (https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-sleep). https://github.com/wazuh/wazuh/blob/91de7ca0118f96027805be613937b37a3bb41a83/src/client-agent/buffer.c#L224

Which has a granularity of milliseconds. So, that solution doesn't work for us. A possible solution could be to use the `select()` function (https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-select) but its documentation says is not supported on Windows older than Vista, in addition, it seems that cannot be used without creating a socket like the Unix version (https://blogs.msdn.microsoft.com/cellfish/2008/09/17/sleep-less-than-one-millisecond/).

Further investigation is needed to find the optimal solution.

Regards.

## Subtasks

- [ ] ~https://github.com/wazuh/wazuh-qa/issues/4016~
- [ ] https://github.com/wazuh/wazuh-documentation/issues/5967
- [ ] https://github.com/wazuh/qa-integration-framework/pull/26

**Comment by myanaros** [comment]
I'm curious, why was the EPS maximum set to something so low? 

1000 EPS is barely enough to handle average production web server loads.

**Comment by jotacarma90** [comment]
## Update
Hello team, 
We have decided to implement a new EPS control mechanism for the client buffer. We are going to use the existing library in analysisd, `limits.c`, which makes use of semaphores to put the thread on hold when the maximum number of events per second is reached.
For this it is necessary to generalize this library to a common directory. In addition to the configuration setting for events per second (currently in the client buffer we have `events_per_second`), we are going to add a `timeframe`, which indicates how often the remaining event count will be updated before blocking the thread (credits).

## List of issue tasks

- [ ] Move the library to a common directory.
- [ ] Generalize the internal limits_t structure to contain all the necessary variables.
- [ ] Update structure initializer, remove info and warning messages (move them to configuration files).
- [ ] Correct the necessary to make the code work in Windows (now it will be part of the agent).
- [ ] Implement the functions in the client buffer.
- [ ] Testing

**Comment by vikman90** [comment]
Reopening this issue because we're going to move it forward to a next release.

**Comment by vikman90** [comment]
## Reverting subtasks

- https://github.com/wazuh/wazuh/issues/20168
- https://github.com/wazuh/wazuh-documentation/issues/6744
- https://github.com/wazuh/qa-integration-framework/issues/50
- https://github.com/wazuh/wazuh-qa/issues/4687

**Comment by jotacarma90** [comment]
# Back to backlog after revert

- [ ] wazuh/wazuh:
  - This same issue: https://github.com/wazuh/wazuh/issues/3766
  - Branch: [3766-client-buffer-eps](https://github.com/wazuh/wazuh/tree/3766-client-buffer-eps)
- [ ] wazuh-documentation:
  - Issue: https://github.com/wazuh/wazuh-documentation/issues/5967
  - Branch: [5967-eps-timeframe](https://github.com/wazuh/wazuh-documentation/tree/5967-eps-timeframe)
- [ ] qa-framework:
  - Issue: https://github.com/wazuh/qa-integration-framework/issues/30
  - Branch: [3766-client-buffer-eps](https://github.com/wazuh/qa-integration-framework/tree/3766-client-buffer-eps)
- [ ] wazuh-qa:
  - No issue, no branch. Pending to create.

**Comment by vikman90** [comment]
We're closing this issue as we will be working on a new communication mechanism: 
- https://github.com/wazuh/wazuh/issues/22677

Best regards.
