### ISSUE TITLE
Remoted fails to accept TCP connections

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#3816]
|Wazuh version|Component|Install type|Platform|
|---|---|---|---|
| 3.9.0 | Remoted | Manager | Linux |

Remoted died suddenly. The following error appeared in the log:

```
2019/08/08 20:00:22 ossec-remoted: CRITICAL: (1242): Couldn't accept TCP connections
```

Unfortunately, the log did not include a description of the error.

## Subtasks

- [X] Include a description of the error: #3662
- [x] Investigate the possible causes of this error.
- [x] Design a mitigation plan.

**Comment by vikman90** [comment]
## Error message

This is the error that now includes a description:
> 2019/12/14 17:04:08 ossec-remoted: CRITICAL: (1242): Couldn't accept TCP connections: Software caused connection abort (103)

The error 103 might happen when a client closes a connection before the server (Remoted) accepts it. That's a non-critical issue that should be ignored.

## Plan

Switch the error type from critical to:
- Debug, if the code is 103.
- Non-critical error, otherwise.
