### ISSUE TITLE
Add RBAC support to Active response module

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#3917]
Hi team,

this issue is related with #3287, after adding everything required to run our RBAC module as detailed in issue 3287 and in all that refer to it. Now we have to adapt the different endpoints of the Wazuh API to be able to add the RBAC support. In this case we will adapt the **Active response** module.

The first thing we will do is to adapt the functions of the framework. To do this we will add the necessary decorators to the functions and define for each module a list of actions-resources that are used. An example of these **actions-resources** is:
```json
{
  "actions": ["agent:delete"],
  "resources": ["agent:id:001", "agent:id:002", "agent:id:003"],
  "effect": "allow"
}
```

Once we define the necessary list for **Active response** we will start to make a refactor of the whole module, eliminating unnecessary code and improving the existing one.

Regards,
Adri

## ToDo
- [x] Create list of actions-resources
- [x] Add RBAC module to controllers
- [x] Refactor the Active response module
- [x] New system to expand *

**Comment by AdriiiPRodri** [comment]
## Status update

After reviewing the controller, we have determined **the list of actions and resources** for this endpoint:

### Active response
#### run_command:
```bash
{
    "actions": ["command:active_response"],
    "resources": ["agent:id:001", "agent:id:002"],
    "effect": "allow"
}
```

#### run_command_all:
```bash
{
    "actions": ["command:active_response"],
    "resources": ["agent:id:*"],
    "effect": "allow"
}
```

**Comment by AdriiiPRodri** [comment]
## Status update

Current RBAC code is running after the refactor on Active response

## Tests
### Current user have permissions over active response of agent 001
```bash
adriiiprodri@Wazuh:/# curl -X PUT "http://localhost:55000/active-response/001?pretty=false&wait_for_complete=false" -H "accept: application/json" -H "Authorization: Bearer {token}" -H "Content-Type: application/json" -d "{\"arguments\":[\"restart-ossec0\"],\"command\":\"restart-ossec0\",\"custom\":false}"
{
  "message": "Command sent."
}
```

### For Agent 2 he doesn't have
```bash
adriiiprodri@Wazuh:/# curl -X PUT "http://localhost:55000/active-response/002?pretty=false&wait_for_complete=false" -H "accept: application/json" -H "Authorization: Bearer {token}" -H "Content-Type: application/json" -d "{\"arguments\":[\"restart-ossec0\"],\"command\":\"restart-ossec0\",\"custom\":false}"
{
  "code": 4000,
  "dapi_errors": {
    "worker1": {
      "error": "Permission denied"
    }
  },
  "detail": "Permission denied",
  "remediation": "Please, make sure you have permissions to execute current request, for more information on setting up permissions please visit XXXX",
  "status": 400,
  "title": "Wazuh Error",
  "type": "about:blank"
}
```

**Comment by AdriiiPRodri** [comment]
## Status update

Hi team,

**RBAC** is correctly added to active response module. We have problems with distributed calls and the output of this, for the moment the status of this issue is completed. When dapy errors are corrected, active response should work properly.
