### ISSUE TITLE
Add RBAC support to Security module

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#3928]
Hi team,

this issue is related with #3287. In this case we will adapt the **Security** module.

The first thing we will do is to adapt the functions of the framework. To do this we will add the necessary decorators to the functions and define for each module a list of actions-resources that are used. An example of these **actions-resources** is:
```json
{
  "actions": ["agent:delete"],
  "resources": ["agent:id:001", "agent:id:002", "agent:id:003"],
  "effect": "allow"
}
```

Once we define the necessary list for **Security** we will start to make a refactor of the whole module, eliminating unnecessary code and improving the existing one.

Regards,
Adri

## ToDo
- [x] Create list of actions-resources
- [x] Add RBAC module to security framework
- [x] Refactor the security module

**Comment by AdriiiPRodri** [comment]
## Status update

The security module has been refactored to support RBAC. In the refactoring we have separated the parts of the framework (SDK) and the most internal parts of the operation (framework core).

## Integrated tests
### GET
```bash
adriiiprodri@Wazuh python -m pytest test_security_GET_endpoint.tavern.yaml   
================================================================================ test session starts =================================================================================
platform linux -- Python 3.5.3, pytest-4.5.0, py-1.8.0, pluggy-0.12.0
rootdir: /home/adriiiprodri/Desktop/git/wazuh/api
plugins: tavern-0.28.0
collected 4 items                                                                                                                                                                    

../../git/wazuh/api/test/integration/test_security_GET_endpoint.tavern.yaml ....                                                                                               [100%]

======================================================================= 4 passed, 3 warnings in 1.5 seconds =======================================================================
```

### POST
```bash
adriiiprodri@Wazuh python -m pytest test_security_POST_endpoint.tavern.yaml
============================================ test session starts =============================================
platform linux -- Python 3.5.3, pytest-4.5.0, py-1.8.0, pluggy-0.12.0
rootdir: /home/adriiiprodri/Desktop/git/wazuh/api
plugins: tavern-0.28.0
collected 2 items                                                                                            

../../git/wazuh/api/test/integration/test_security_POST_endpoint.tavern.yaml ..                                                                                                [100%]

======================================================================= 2 passed, 1 warnings in 1.88 seconds =======================================================================
```

### PUT
```bash
adriiiprodri@Wazuh python -m pytest test_security_PUT_endpoint.tavern.yaml
================================================================================ test session starts =================================================================================
platform linux -- Python 3.5.3, pytest-4.5.0, py-1.8.0, pluggy-0.12.0
rootdir: /home/adriiiprodri/Desktop/git/wazuh/api
plugins: tavern-0.28.0
collected 3 items                                                                                                                                                                    

../../git/wazuh/api/test/integration/test_security_PUT_endpoint.tavern.yaml ...                                                                                                [100%]

======================================================================= 3 passed, 1 warnings in 1.42 seconds =======================================================================
```

### DELETE
```bash
adriiiprodri@Wazuh python -m pytest test_security_DELETE_endpoint.tavern.yaml
================================================================================ test session starts =================================================================================
platform linux -- Python 3.5.3, pytest-4.5.0, py-1.8.0, pluggy-0.12.0
rootdir: /home/adriiiprodri/Desktop/git/wazuh/api
plugins: tavern-0.28.0
collected 5 items                                                                                                                                                                    

../../git/wazuh/api/test/integration/test_security_DELETE_endpoint.tavern.yaml .....                                                                                           [100%]

======================================================================= 5 passed, 2 warnings in 1.55 seconds =======================================================================
```

**Comment by AdriiiPRodri** [comment]
## Status update

Hi team,

We have added RBAC support to security module (roles, policies, users administration).
In the process, we improved the module's code and fixed some minor bugs.

### Integrated tests (RBAC in BLACK mode)
#### POST
```json
adriiiprodri@Wazuh python -m pytest -vv ~/Desktop/git/wazuh/api/test/integration/test_security_POST_endpoint.tavern.yaml  
========================================================================= test session starts ==========================================================================
platform linux -- Python 3.5.3, pytest-4.5.0, py-1.8.0, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/adriiiprodri/Desktop/git/wazuh/api
plugins: tavern-0.28.0
collected 2 items                                                                                                                                                      

Desktop/git/wazuh/api/test/integration/test_security_POST_endpoint.tavern.yaml::POST /security/roles PASSED                                                      [ 50%]
Desktop/git/wazuh/api/test/integration/test_security_POST_endpoint.tavern.yaml::POST /security/policies PASSED                                                   [100%]

================================================================= 2 passed, 1 warnings in 1.02 seconds =================================================================
```
#### PUT
```json
adriiiprodri@Wazuh python -m pytest -vv ~/Desktop/git/wazuh/api/test/integration/test_security_PUT_endpoint.tavern.yaml   
========================================================================= test session starts ==========================================================================
platform linux -- Python 3.5.3, pytest-4.5.0, py-1.8.0, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/adriiiprodri/Desktop/git/wazuh/api
plugins: tavern-0.28.0
collected 3 items                                                                                                                                                      

Desktop/git/wazuh/api/test/integration/test_security_PUT_endpoint.tavern.yaml::PUT /security/roles PASSED                                                        [ 33%]
Desktop/git/wazuh/api/test/integration/test_security_PUT_endpoint.tavern.yaml::PUT /security/policies PASSED                                                     [ 66%]
Desktop/git/wazuh/api/test/integration/test_security_PUT_endpoint.tavern.yaml::PUT /security/roles/{role_id}/policies/{policy_id} PASSED                         [100%]

================================================================= 3 passed, 1 warnings in 1.33 seconds =================================================================
```
#### GET
```json
adriiiprodri@Wazuh python -m pytest -vv ~/Desktop/git/wazuh/api/test/integration/test_security_GET_endpoint.tavern.yaml 
========================================================================= test session starts ==========================================================================
platform linux -- Python 3.5.3, pytest-4.5.0, py-1.8.0, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/adriiiprodri/Desktop/git/wazuh/api
plugins: tavern-0.28.0
collected 4 items                                                                                                                                                      

Desktop/git/wazuh/api/test/integration/test_security_GET_endpoint.tavern.yaml::GET /security/roles PASSED                                                        [ 25%]
Desktop/git/wazuh/api/test/integration/test_security_GET_endpoint.tavern.yaml::GET /security/policies PASSED                                                     [ 50%]
Desktop/git/wazuh/api/test/integration/test_security_GET_endpoint.tavern.yaml::GET /security/roles PASSED                                                        [ 50%]
Desktop/git/wazuh/api/test/integration/test_security_GET_endpoint.tavern.yaml::GET /security/policies/{policy_id} PASSED                                         [ 75%]

================================================================= 4 passed, 3 warnings in 4.54 seconds =================================================================
```
#### DELETE
```json
adriiiprodri@Wazuh python -m pytest -vv ~/Desktop/git/wazuh/api/test/integration/test_security_DELETE_endpoint.tavern.yaml 
========================================================================= test session starts ==========================================================================
platform linux -- Python 3.5.3, pytest-4.5.0, py-1.8.0, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/adriiiprodri/Desktop/git/wazuh/api
plugins: tavern-0.28.0
collected 5 items                                                                                                                                                      

Desktop/git/wazuh/api/test/integration/test_security_DELETE_endpoint.tavern.yaml::DELETE /security/roles/{role_id} PASSED                                        [ 20%]
Desktop/git/wazuh/api/test/integration/test_security_DELETE_endpoint.tavern.yaml::DELETE /security/policies/{policy_id} PASSED                                   [ 40%]
Desktop/git/wazuh/api/test/integration/test_security_DELETE_endpoint.tavern.yaml::DELETE /security/roles/{role_id}/policies/{policy_id} PASSED                   [ 60%]
Desktop/git/wazuh/api/test/integration/test_security_DELETE_endpoint.tavern.yaml::DELETE /security/roles PASSED                                                  [ 80%]
Desktop/git/wazuh/api/test/integration/test_security_DELETE_endpoint.tavern.yaml::DELETE /security/policies PASSED                                               [100%]

================================================================= 5 passed, 2 warnings in 1.69 seconds =================================================================
```

**Comment by AdriiiPRodri** [comment]
### **API security endpoints RBAC catalog:**
| Http Method | API endpoint  | Actions | Resources |
| ------------- | ------------- | ------------- | ------------ |
| GET | /security/roles | security:read | role:id | 
| GET | /security/policies | security:read | policy:id | 
| GET | /security/users | security:read | user:id | 
| POST | /security/roles  | security:create | * |
| POST | /security/policies  | security:create | * | 
| POST | /security/users  | security:create_user | * |
| PUT | /security/roles/{role_id} | security:update | role:id |
| PUT | /security/policies/{policy_id} | security:update | policy:id |
| PUT | /security/users/{username} | security:update | user:id |
| PUT | /security/roles/{role_id}/policies | security:update | role:id policy:id | 
| DELETE | /security/roles | security:delete | role:id |
| DELETE | /security/policies | security:delete | policy:id |
| DELETE | /security/users | security:delete | user:id |
| DELETE | /security/roles/{role_id}/policies | security:delete | role:id policy:id |
