### ISSUE TITLE
Calculate differences between inventory scans

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#3940]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| N/A | Syscollector | All | All | All |

As previously stated in https://github.com/wazuh/wazuh/issues/742, it is needed to adapt the Syscollector module to calculate differences between successive scans. That differences should be calculated on the agent and sent them to store in the manager DB, avoiding the flooding of repeated events every scan.

Working as described above lead the following advantages:

- Only new information is reported to the manager, decongesting the network.
- We ensure the reliability of the inventory database content by an integrity mechanism.
- The manager can fire alerts when changes appear. For example, a new port is listening or a new package has been installed.

This development includes the following subtasks:

- [ ] Store the last scan in the agent, updating it each iteration.

- [ ] Send differences to the manager triggering alerts.

- [ ] Create a synchronization mechanism that ensure the integrity of the data between manager and agent. It is currently in development for FIM (https://github.com/wazuh/wazuh/issues/2404#issuecomment-520966297). 

- [ ] Basic rules to catch new events.

- [ ] Automatic tests for the new feature.

- [ ] Adapt documentation.

**Comment by TomasTurina** [comment]
### Update 1:

- [x] Store the last scan in the agent, updating it each iteration.

The data stores  for the different scan types are already implemented in the client side.

Each time a scan is performed, the information retrieved is stored for each type of scan as follows:

- **Hardware:** The information from the last scan is stored in the `hw_entry` structure. When a new scan is performed, the new information is compared with that stored in this structure. If the information changes, the structure is updated. The structure is as follows:
```C
typedef struct hw_entry {
    char * board_serial;                    // Motherboard serial number
    char * cpu_name;                        // CPU name
    int cpu_cores;                          // Number of cores of the CPU
    double cpu_MHz;                         // Current processor frequency
    long ram_total;                         // Total RAM (KB)
    long ram_free;                          // Free RAM (KB)
    int ram_usage;                          // Percentage of RAM in use
} hw_entry;
```

- **Software:** The information from the last scan is stored in the `os_entry` structure. When a new scan is performed, the new information is compared with that stored in this structure. If the information changes, the structure is updated. The structure is as follows:
```C
typedef struct os_entry {
    char * hostname;                        // Hostname of the machine
    char * architecture;                    // OS architecture
    char * os_name;                         // OS name
    char * os_release;                      // OS release
    char * os_version;                      // OS version
    char * os_codename;                     // OS version codename
    char * os_major;                        // Major release version
    char * os_minor;                        // Minor release version
    char * os_build;                        // Optional build-specific
    char * os_platform;                     // OS platform
    char * sysname;                         // System name
    char * release;                         // Release name
    char * version;                         // Release version
} os_entry;
```

- **Network interfaces:** The information from the last scan is stored in a `rb_tree`. Each entry of this tree is an instance of the `interface_entry_data` structure. The PK for each entry is the _**name**_ of the interface. When a new scan is performed, the information of each interface is compared with that of the same PK in the tree. If it doesn't exist or changes, the tree is updated. After iterating all the interfaces, those that no longer exist are removed from the tree. The structure is as follows:
```C
typedef struct interface_entry_data {
    char * name;                            // Interface name
    char * adapter;                         // Physical adapter name
    char * type;                            // Network adapter
    char * state;                           // State of the interface
    char * mac;                             // MAC Address
    int mtu;                                // Maximum Transmission Unit

    int tx_packets;                         // Transmitted packets
    int rx_packets;                         // Received packets
    int tx_bytes;                           // Transmitted bytes
    int rx_bytes;                           // Received bytes
    int tx_errors;                          // Transmission errors
    int rx_errors;                          // Reception errors
    int tx_dropped;                         // Dropped transmission packets
    int rx_dropped;                         // Dropped reception packets

    struct net_addr * ipv4;
    struct net_addr * ipv6;

    int enabled;
} interface_entry_data;
```
```C
typedef struct net_addr {
    char ** address;                        // IPv4/IPv6 address
    char ** netmask;                        // Netmask address
    char ** broadcast;                      // Broadcast address
    int metric;                             // Metric
    char * gateway;                         // Default gateway
    char * dhcp;                            // DHCP status
} net_addr;
```

- **Programs/Packages:** The information from the last scan is stored in a `rb_tree`. Each entry of this tree is an instance of the `program_entry_data` structure. The PK for each entry is the _**name**_, the _**version**_ and the _**architecture**_ of the program/package. When a new scan is performed, the information of each program/package is compared with that of the same PK in the tree. If it doesn't exist or changes, the tree is updated. After iterating all the programs/packages, those that no longer exist are removed from the tree. The structure is as follows:
```C
typedef struct program_entry_data {
    char * format;                          // Format of the package
    char * name;                            // Name of the package

    char * priority;                        // Priority of the package
    char * group;                           // Section of the package
    long size;                              // Size of the installed package in bytes
    char * vendor;                          // Vendor name
    char * install_time;                    // Date when the package was installed
    char * version;                         // Version of the package
    char * architecture;                    // Architecture of the package
    char * multi_arch;                      // Multiarchitecture support
    char * source;                          // Source of the package
    char * description;                     // Description of the package
    char * location;                        // Location of the package

    int installed;
} program_entry_data;
```

- **Hotfixes (only Windows):** The information from the last scan is stored in a `rb_tree`. Each entry of this tree is an instance of the `hotfix_entry_data` structure. The PK for each entry is the _**hotfix**_ name of the hotfix. When a new scan is performed, the information of each hotfix is compared with that of the same PK in the tree. If it doesn't exist or changes, the tree is updated. After iterating all the hotfixes, those that no longer exist are removed from the tree. The structure is as follows:
```C
typedef struct hotfix_entry_data {
    char * hotfix;                          // Hotfix name

    int installed;
} hotfix_entry_data;
```

- **Ports:** The information from the last scan is stored in a `rb_tree`. Each entry of this tree is an instance of the `port_entry_data` structure. The PK for each entry is the _**protocol**_, the _**local_ip**_, the _**local_port**_ and the _**pid**_ of the port. When a new scan is performed, the information of each port is compared with that of the same PK in the tree. If it doesn't exist or changes, the tree is updated. After iterating all the ports, those that no longer exist are removed from the tree. The structure is as follows:
```C
typedef struct port_entry_data {
    char * protocol;                        // Protocol of the port

    char * local_ip;                        // Local IP
    int local_port;                         // Local port
    char * remote_ip;                       // Remote IP
    int remote_port;                        // Remote port

    int tx_queue;                           // Packets pending to be transmitted
    int rx_queue;                           // Packets at the receiver queue
    int inode;                              // Inode of the port

    char * state;                           // State of the port

    int pid;                                // PID owner of the opened port
    char * process;                         // Name of the PID

    int opened;
} port_entry_data;
```

- **Processes:** The information from the last scan is stored in a `rb_tree`. Each entry of this tree is an instance of the `process_entry_data` structure. The PK for each entry is the _**pid**_ and the _**name**_ of the process. When a new scan is performed, the information of each process is compared with that of the same PK in the tree. If it doesn't exist or changes, the tree is updated. After iterating all the processes, those that no longer exist are removed from the tree. The structure is as follows:
```C
typedef struct process_entry_data {
    int pid;                                // PID of the process
    int ppid;                               // PPID of the process
    char * name;                            // Name of the process
    char * cmd;                             // Command executed
    char ** argvs;                          // Arguments of the process
    char * state;                           // State of the process

    char * euser;                           // Effective user
    char * ruser;                           // Real user
    char * suser;                           // Saved-set user
    char * egroup;                          // Effective group
    char * rgroup;                          // Real group
    char * sgroup;                          // Saved-set group
    char * fgroup;                          // Filesystem group name

    int priority;                           // Kernel scheduling priority
    int nice;                               // Nice value of the process

    long size;                              // Size of the process
    long vm_size;                           // Total VM size (KB)
    long resident;                          // Residen size of the process in bytes
    long share;                             // Shared memory

    long long start_time;                   // Time when the process started
    long long utime;                        // Time spent executing user code
    long long stime;                        // Time spent executing system code

    int pgrp;                               // Process group
    int session;                            // Session of the process
    int nlwp;                               // Number of light weight processes
    int tgid;                               // Thread Group ID
    int tty;                                // Number of TTY of the process
    int processor;                          // Number of the processor

    int running;
} process_entry_data;
```
