### ISSUE TITLE
Google Cloud: Pub/Sub integration

### ISSUE THREAD

**Issue by snaow** [wazuh/wazuh#4015]
It is time Wazuh has a native capability to pull logs from Google Cloud Pub/Sub.
The new module will be _wodle based_ similar to what it already has with AWS.

**Requirements**
- It should work on both manager and agents
- The only dependency must be the Python module [google-cloud-pubsub](https://pypi.org/project/google-cloud-pubsub/)
- Python 3.6 compatible (since 2.7 will be deprecated by Google Pub/Sub in January 2020)
- The module will assume there is already a sink, topic, and a subscription created in GCP.
- No temporal files are needed. It must write directly into _agentd/analysisd_ socket.

**Configuration settings**

- `project_id`: _String_. Google Cloud Project ID (name, not number). Required.
- `subscription_name`: _String_. Name of the subscription to read from. Required.
- `credentials_file`: _String_. The path to the Google Cloud credentials file. JWT Tokens. It must allow both relative (to $HOME_INSTALLATION) and absolute paths. Required.
- `interval`: _String_. The amount of time between each pull. Default: 1h. (It must allow the format: 1h, 1d, 20m, 1405s). 
- `max_messages`: _Integer_. The number of maximum messages pulled in each iteration. Default: 100.
- `enabled`: _String_. Enable or disabled the module. Values: yes/no.
- `pull_on_start`: _String_. Trigger the pulling in case of an agent start or restart. Values: yes/no. Default: yes.
- `logging`: _String_. Toggle between the different logging levels. Values: disabled/info/debug/trace. Default: info.

**Directory structure**
_source_
- `wodles/gcp-pubsub/gcp-pubsub`: Main. Core script.
- `wodles/gcp-pubsub/tests:` Tests mocha/pytest folder.

_installation_
- `wodles/gcp-pubsub/gcp-pubsub.py`: Main. Core script.
- `wodles/gcp-pubsub/gcp-pubsub:` Wrapper to detect Manager/agent installation and use Wazuh embedded Python.

**Considerations**
- All errors logs must be sent as an event (auth errors, timeouts..)
- Each Pub/Sub event will contain and send only one event to Wazuh Manager.
- No SQLite DBs are required for this integration

**Documentation**

The documentation must contain all the process involved in creating the following resources in Google Cloud console:

- Sink
- Pub/Sub Topic
- Pub/Sub subscription

As well as the following use cases:

- DNS Logs
- Admin Activity audit logs
- Data Access audit logs
- System Event audit logs

Moreover, it should have the instructions to configure the module in both Manager and Agent installations.

**Configuration example**

```
<gcp_pubsub>
  <project_id>wazuh-dev</project_id>
  <subscription_name>wazuh-dns</subscription_name>
  <credentials_file>wazuh-dev-211c44f005a.json</credentials_file>
</gcp_pubsub>
```

**JSON Alert sample**
_TBD_

**Tasks**

- [x] Python main core script (framework) https://github.com/wazuh/wazuh/pull/4110
- [x] Wazuh module (_core_) (_wodle_) https://github.com/wazuh/wazuh/pull/4078
- [x] Configuration on demand settings (_syscom_)
- [x] Ruleset https://github.com/wazuh/wazuh-ruleset/pull/509
- [x] Packages https://github.com/wazuh/wazuh-packages/issues/364
- [ ] Wazuh App dashboards (extension) https://github.com/wazuh/wazuh-kibana-app/issues/1873
- [x] Documentation tech https://github.com/wazuh/wazuh-documentation/pull/1947
- [x] Documentation user https://github.com/wazuh/wazuh-documentation/issues/2046

**Comment by cristgl** [comment]
Working at branch [4015-gcp-integration](https://github.com/wazuh/wazuh/tree/4015-gcp-integration).

#### Some configuration limitations

- Setting `project_id` as a number.

```
2019/10/09 16:22:30 wazuh-modulesd: ERROR: Tag 'project_id' from the 'gcp-pubsub' module should not be a number.
2019/10/09 16:22:30 wazuh-modulesd: ERROR: (1202): Configuration error at '/var/ossec/etc/ossec.conf'.
```

- Setting a non-existing file in tag `credentials-file`.
```
2019/10/09 16:20:39 wazuh-modulesd: WARNING: File 'wazuh-dev-211c44f005a.json' from tag 'credentials_file' not found.
2019/10/09 16:20:39 wazuh-modulesd: ERROR: (1202): Configuration error at '/var/ossec/etc/ossec.conf'.
```

**Comment by cristgl** [comment]
Currently the python script sends the logs directly to the `analysisd` socket. This doesn't give us the possibility to detect if it is a manager or an agent, and in this last case, send them to the correspondent manager. The code [here](https://github.com/wazuh/wazuh/blob/f82e063251a6ba92fdf1e152467a3890f3ce2651/wodles/gcloud/tools.py#L61) searches at the _/etc/ossec-init.conf_ for the Wazuh path and version, and giving that, finds the `analysisd` socket and forwards the JSON events.

In addition, we have got an inconsistency, as I understood by reading this issue, the `logging` tag can be set as info, debug, trace or be disabled, but the python script ([in this function](https://github.com/wazuh/wazuh/blob/f82e063251a6ba92fdf1e152467a3890f3ce2651/wodles/gcloud/tools.py#L43)) has different log levels, debug, info, warning, error and critical.
