### ISSUE TITLE
Create unit tests using cmocka

### ISSUE THREAD

**Issue by albertomn86** [wazuh/wazuh#4033]
| Working branch |
| --- |
| [unit-tests](https://github.com/wazuh/wazuh/tree/unit-tests) |

This issue is intended to create the unit tests for the current C code using the testing framework [cmocka](https://cmocka.org/).

Step 1: Configure environment.
-------
- [x] Installation/compilation of `cmocka`.

   The `libcmocka-dev` package is available to install from repositories.

- [x] Update Makefile to compile and execute the new tests.

   Generated a `Cmakefile` to compile tests allowing wrapping of functions. 

Step 2: Create unit tests.
-------
The following libraries will be documented and the corresponding unit tests will be created:

- [ ] agent_op
- [ ] audit_op
- [ ] auth_client
- [ ] cluster_utils
- [ ] custom_output_search_replace
- [ ] debug_op
- [ ] dirtree_op
- [ ] exec_op
- [x] file_op
- [ ] file-queue
- [ ] fs_op
- [ ] hash_op
- [ ] help
- [x] integrity_op 3272745055a7676372ff72cb623aeb9196e5c1fd
- [ ] json_op
- [ ] json-queue
- [ ] labels_op
- [ ] list_op
- [ ] math_op
- [ ] mem_op
- [ ] mq_op
- [ ] notify_op
- [ ] os_utils
- [ ] privsep_op
- [ ] pthreads_op
- [ ] queue_op
- [ ] randombytes
- [x] rbtree_op f41ae5b7bfeb3bb1a057351848d54b6a1c582fce
- [ ] read-agents
- [ ] read-alert
- [ ] regex_op
- [ ] report_op
- [ ] request_op
- [ ] rootcheck_op
- [ ] rules_op
- [ ] sig_op
- [ ] store_op
- [ ] string_op
- [ ] syscheck_op
- [ ] time_op
- [ ] url
- [ ] utf8_op
- [ ] validate_op
- [ ] vector_op
- [x] version_op
- [ ] wait_op
- [ ] wazuhdb_op
- [ ] yaml2json

#### Syscheck files:
- [x] create_db.c
