### ISSUE TITLE
Integration tests for agents endpoints and RBAC

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#4115]
## Description
We need to write additional integration tests for all endpoints involving agents in order to guarantee that permissions are taken into account.

These tests should include:
- Allow/deny access for white list mode (everything is forbidden except those permissions explicitly allowed)
- Allow/deny access for black list mode (everything is allowed except those permissions explicitly denied)

## Tasks

- [x] Update integration tests :
  - [x] DELETE
  - [x] GET
    - There are 3 stages at lines 600, 712 and 2270 of `test_agentsGET_endpoints.tavern.yaml` failing due to a problem with `status` filter using several separated by comma and `older_than` filter.
  - [x] POST
  - [x] PUT

**Add WHITE RBAC integration tests:**
- [x] DELETE
    - [x] DELETE /agents
    - [x] DELETE /agents/group/{group_id}
    - [x] DELETE /agents/groups
    - [x] DELETE /agents/groups/{group_id}
    - [x] DELETE /agents/{agent_id}/group
    - [x] DELETE /agents/{agent_id}/group/{group_id}
    - [x] DELETE /agents/{agent_id}

- [x] GET
    - [x] GET /agents
    - [x] GET /agents/groups
    - [x] GET /agents/groups/{group_id}
    - [x] GET /agents/groups/{group_id}/configuration
    - [x] GET /agents/groups/{group_id}/files
    - [x] GET /agents/groups/{group_id}/files/{file_name}/json
    - [x] GET /agents/groups/{group_id}/files/{file_name}/xml
    - [x] GET /agents/name/{agent_name}
    - [x] GET /agents/no_group
    - [x] GET /agents/outdated
    - [x] GET /agents/stats/distinct
    - [x] GET /agents/summary/status
    - [x] GET /agents/summary/os
    - [x] GET /agents/{agent_id}
    - [x] GET /agents/{agent_id}/config/{component}/{configuration}
    - [x] GET /agents/{agent_id}/group/is_sync
    - [x] GET /agents/{agent_id}/key
    - [x] GET /agents/{agent_id}/upgrade_result

- [x] POST
    - [x] POST /agents
    - [x] POST /agents/groups/{group_id}
    - [x] POST /agents/insert
    - [x] POST /agents/{agent_name}

- [x] PUT
    - [x] PUT /agents/group/{group_id}
    - [x] PUT /agents/groups/{group_id}/configuration
    - [x] PUT /agents/restart
    - [x] PUT /agents/{agent_id}/group/{group_id}
    - [x] PUT /agents/{agent_id}/restart
    - [x] PUT /agents/{agent_id}/upgrade
    - [x] PUT /agents/{agent_id}/upgrade_custom

**Add BLACK RBAC integration tests:**
- [x] DELETE
    - [x] DELETE /agents
    - [x] DELETE /agents/group/{group_id}
    - [x] DELETE /agents/groups
    - [x] DELETE /agents/groups/{group_id}
    - [x] DELETE /agents/{agent_id}/group
    - [x] DELETE /agents/{agent_id}/group/{group_id}
    - [x] DELETE /agents/{agent_id}

- [x] GET
    - [x] GET /agents
    - [x] GET /agents/groups
    - [x] GET /agents/groups/{group_id}
    - [x] GET /agents/groups/{group_id}/configuration
    - [x] GET /agents/groups/{group_id}/files
    - [x] GET /agents/groups/{group_id}/files/{file_name}/json
    - [x] GET /agents/groups/{group_id}/files/{file_name}/xml
    - [x] GET /agents/name/{agent_name}
    - [x] GET /agents/no_group
    - [x] GET /agents/outdated
    - [x] GET /agents/stats/distinct
    - [x] GET /agents/summary/status
    - [x] GET /agents/summary/os
    - [x] GET /agents/{agent_id}
    - [x] GET /agents/{agent_id}/config/{component}/{configuration}
    - [x] GET /agents/{agent_id}/group/is_sync
    - [x] GET /agents/{agent_id}/key
    - [x] GET /agents/{agent_id}/upgrade_result

- [x] POST
    - [x] POST /agents
    - [x] POST /agents/groups/{group_id}
    - [x] POST /agents/insert
    - [x] POST /agents/{agent_name}

- [x] PUT
    - [x] PUT /agents/group/{group_id}
    - [x] PUT /agents/groups/{group_id}/configuration
    - [x] PUT /agents/restart
    - [x] PUT /agents/{agent_id}/group/{group_id}
    - [x] PUT /agents/{agent_id}/restart
    - [x] PUT /agents/{agent_id}/upgrade
    - [x] PUT /agents/{agent_id}/upgrade_custom

**Comment by davidjiglesias** [comment]
### **Update integration tests results :**
**DELETE**
```

**Comment by davidjiglesias** [comment]
**DELETE WHITE**
```
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-4.4.0, py-1.8.0, pluggy-0.12.0 -- /usr/bin/python3.6
cachedir: .pytest_cache
rootdir: /home/davidjiglesias/git/wazuh/api
plugins: cov-2.7.1, tavern-0.26.4
collecting ... collected 7 items

test_rbac_white_agentsDELETE_endpoints.tavern.yaml::DELETE /agents/{agent_id}/group/{group_id} PASSED [ 14%]
test_rbac_white_agentsDELETE_endpoints.tavern.yaml::DELETE /agents/{agent_id}/group PASSED [ 28%]
test_rbac_white_agentsDELETE_endpoints.tavern.yaml::DELETE /agents/group/{group_id} PASSED [ 42%]
test_rbac_white_agentsDELETE_endpoints.tavern.yaml::DELETE /agents/groups/{group_id} PASSED [ 57%]
test_rbac_white_agentsDELETE_endpoints.tavern.yaml::DELETE /agents/groups PASSED [ 71%]
test_rbac_white_agentsDELETE_endpoints.tavern.yaml::DELETE /agents/{agent_id} PASSED [ 85%]
test_rbac_white_agentsDELETE_endpoints.tavern.yaml::DELETE /agents PASSED [100%]

=============================== warnings summary ===============================
test/integration/test_rbac_white_agentsDELETE_endpoints.tavern.yaml::DELETE /agents/{agent_id}/group/{group_id}
  /home/davidjiglesias/.local/lib/python3.6/site-packages/jwt/api_jwt.py:81: DeprecationWarning: It is strongly recommended that you pass in a value for the "algorithms" argument when calling decode(). This argument will be mandatory in a future version.
    DeprecationWarning

-- Docs: https://docs.pytest.org/en/latest/warnings.html
==================== 7 passed, 1 warnings in 12.10 seconds =====================
```

**Comment by davidjiglesias** [comment]
**BLACK RBAC**
```
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-4.4.0, py-1.8.0, pluggy-0.12.0 -- /usr/bin/python3.6
cachedir: .pytest_cache
rootdir: /home/davidjiglesias/git/wazuh/api
plugins: cov-2.7.1, tavern-0.26.4
collecting ... collected 36 items

test_rbac_black_agents_endpoints.tavern.yaml::GET /agents PASSED         [  2%]
test_rbac_black_agents_endpoints.tavern.yaml::GET /agents/{agent_id} PASSED [  5%]
test_rbac_black_agents_endpoints.tavern.yaml::GET /agents/{agent_id}/config/{component}/{configuration} PASSED [  8%]
test_rbac_black_agents_endpoints.tavern.yaml::GET /agents/{agent_id}/group/is_sync PASSED [ 11%]
test_rbac_black_agents_endpoints.tavern.yaml::GET /agents/{agent_id}/key PASSED [ 13%]
test_rbac_black_agents_endpoints.tavern.yaml::GET /agents/groups PASSED  [ 16%]
test_rbac_black_agents_endpoints.tavern.yaml::GET /agents/groups/{group_id} PASSED [ 19%]
test_rbac_black_agents_endpoints.tavern.yaml::GET /agents/groups/{group_id}/configuration PASSED [ 22%]
test_rbac_black_agents_endpoints.tavern.yaml::GET /agents/groups/{group_id}/files PASSED [ 25%]
test_rbac_black_agents_endpoints.tavern.yaml::GET /agents/groups/{group_id}/files/{filename}/json PASSED [ 27%]
test_rbac_black_agents_endpoints.tavern.yaml::GET /agents/groups/{group_id}/files/{filename}/xml PASSED [ 30%]
test_rbac_black_agents_endpoints.tavern.yaml::GET /agents/name/{agent_name} PASSED [ 33%]
test_rbac_black_agents_endpoints.tavern.yaml::GET /agents/no_group PASSED [ 36%]
test_rbac_black_agents_endpoints.tavern.yaml::GET /agents/outdated PASSED [ 38%]
test_rbac_black_agents_endpoints.tavern.yaml::GET /agents/stats/distinct PASSED [ 41%]
test_rbac_black_agents_endpoints.tavern.yaml::GET /agents/summary/status PASSED [ 44%]
test_rbac_black_agents_endpoints.tavern.yaml::GET /agents/summary/os PASSED [ 47%]
test_rbac_black_agents_endpoints.tavern.yaml::GET /agents/{agent_id}/upgrade_result PASSED [ 50%]
test_rbac_black_agents_endpoints.tavern.yaml::DELETE /agents/{agent_id}/group/{group_id} PASSED [ 52%]
test_rbac_black_agents_endpoints.tavern.yaml::DELETE /agents/{agent_id}/group PASSED [ 55%]
test_rbac_black_agents_endpoints.tavern.yaml::DELETE /agents/group/{group_id} PASSED [ 58%]
test_rbac_black_agents_endpoints.tavern.yaml::DELETE /agents/groups/{group_id} PASSED [ 61%]
test_rbac_black_agents_endpoints.tavern.yaml::DELETE /agents/groups PASSED [ 63%]
test_rbac_black_agents_endpoints.tavern.yaml::DELETE /agents/{agent_id} PASSED [ 66%]
test_rbac_black_agents_endpoints.tavern.yaml::DELETE /agents PASSED      [ 69%]
test_rbac_black_agents_endpoints.tavern.yaml::POST /agents PASSED        [ 72%]
test_rbac_black_agents_endpoints.tavern.yaml::POST /agents/insert PASSED [ 75%]
test_rbac_black_agents_endpoints.tavern.yaml::POST /agents/{agent_name} PASSED [ 77%]
test_rbac_black_agents_endpoints.tavern.yaml::POST /agents/groups/{group_id} PASSED [ 80%]
test_rbac_black_agents_endpoints.tavern.yaml::PUT /agents/group/{group_id} PASSED [ 83%]
test_rbac_black_agents_endpoints.tavern.yaml::PUT /agents/groups/{group_id}/configuration PASSED [ 86%]
test_rbac_black_agents_endpoints.tavern.yaml::PUT /agents/restart PASSED [ 88%]
test_rbac_black_agents_endpoints.tavern.yaml::PUT /agents/{agent_id}/group/{group_id} PASSED [ 91%]
test_rbac_black_agents_endpoints.tavern.yaml::PUT /agents/{agent_id}/restart PASSED [ 94%]
test_rbac_black_agents_endpoints.tavern.yaml::PUT /agents/{agent_id}/upgrade PASSED [ 97%]
test_rbac_black_agents_endpoints.tavern.yaml::PUT /agents/{agent_id}/upgrade_custom PASSED [100%]

=============================== warnings summary ===============================
test/integration/test_rbac_black_agents_endpoints.tavern.yaml::GET /agents
  /home/davidjiglesias/.local/lib/python3.6/site-packages/jwt/api_jwt.py:81: DeprecationWarning: It is strongly recommended that you pass in a value for the "algorithms" argument when calling decode(). This argument will be mandatory in a future version.
    DeprecationWarning

-- Docs: https://docs.pytest.org/en/latest/warnings.html
==================== 36 passed, 1 warnings in 56.72 seconds ====================
```
