### ISSUE TITLE
Integration tests for RBAC in security endpoints

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#4117]
## Description
We need to write additional integration tests for all endpoints involving security in order to guarantee that permissions are taken into account.

These tests should include:
- Allow/deny access for white list mode (everything is forbidden except those permissions explicitly allowed)
- Allow/deny access for black list mode (everything is allowed except those permissions explicitly denied)

## Tasks
- [x] DELETE /security/policies
- [x] GET /security/policies
- [x] POST /security/policies
- [x] PUT /security/policies/{policy_id}
- [x] DELETE /security/roles
- [x] GET /security/roles
- [x] POST /security/roles
- [x] PUT /security/roles/{role_id}
- [x] DELETE /security/roles/{role_id}/policies
- [x] POST /security/roles/{role_id}/policies
- [x] GET /security/user/authenticate
- [x] DELETE /security/users
- [x] GET /security/users
- [x] POST /security/users
- [x] PUT /security/users/{username}

**Comment by AdriiiPRodri** [comment]
## Status update

Hi team,

Currently the tests for the security module in white mode are finished. We cover all endpoints with several use cases tested. **Each mode will have its own environment** which will be configured before running the tests. This way we can fully **automate** them.

Best regards,
Adri

### Environment configuration
| Resource    | List                                                         |
|-------------|--------------------------------------------------------------|
| user:id     | wazuh,wazuh-app,administrator,normal,ossec,python,rbac,guest |
| role:id     | 1,2,3,4,5,6                                                  |
| policy:id   | 1,2,3,4,5,6,7,8,9,10                                         |
| role:policy | (1:1),(2:1),(3:1,2,5,8),(4:4,5),(5:2,3,10),(6:*)             |


| Actions              | Resources | Allow                             | Deny |
|----------------------|-----------|-----------------------------------|------|
| security:read        | user:id   | administrator,normal,python,guest |      |
| security:read        | role:id   | *                                 |      |
| security:read        | policy:id |                                   | *    |
| security:update      | user:id   |                                   | *    |
| security:update      | role:id   | 3,4,6                             |      |
| security:update      | policy:id | 5                                 |      |
| security:delete      | user:id   | guest,normal,wazuh-app            |      |
| security:delete      | role:id   |                                   | *    |
| security:delete      | policy:id |                                   | *    |
| security:create      | *         | *                                 |      |
| security:create_user | *         |                                   | *    |

### Tests result
```bash
adriiiprodri@Wazuh python -m pytest -vv ~/Desktop/git/wazuh/api/test/integration/test_rbac_white_security_endpoint.tavern.yaml
====================================== test session starts ======================================
platform linux -- Python 3.5.3, pytest-4.5.0, py-1.8.0, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/adriiiprodri/Desktop/git/wazuh/api
plugins: tavern-0.28.0
collected 11 items                                                                              

../test_rbac_white_security_endpoint.tavern.yaml::GET USERS RBAC PASSED                   [  9%]
../test_rbac_white_security_endpoint.tavern.yaml::GET ROLES RBAC PASSED                   [ 18%]
../test_rbac_white_security_endpoint.tavern.yaml::GET POLICIES RBAC PASSED                [ 27%]
../test_rbac_white_security_endpoint.tavern.yaml::UPDATE USERS RBAC PASSED                [ 36%]
../test_rbac_white_security_endpoint.tavern.yaml::UPDATE ROLES RBAC PASSED                [ 45%]
../test_rbac_white_security_endpoint.tavern.yaml::UPDATE POLICIES RBAC PASSED             [ 54%]
../test_rbac_white_security_endpoint.tavern.yaml::DELETE USERS RBAC PASSED                [ 63%]
../test_rbac_white_security_endpoint.tavern.yaml::DELETE ROLES RBAC PASSED                [ 72%]
../test_rbac_white_security_endpoint.tavern.yaml::DELETE POLICIES RBAC PASSED             [ 81%]
../test_rbac_white_security_endpoint.tavern.yaml::CREATE USERS RBAC PASSED                [ 90%]
../test_rbac_white_security_endpoint.tavern.yaml::CREATE ROLES AND POLICIES RBAC PASSED   [100%]

============================ 11 passed, 1 warnings in 156.79 seconds ============================
```

**Comment by AdriiiPRodri** [comment]
## Status update

Hi team,

We have added the remaining tests for **black** mode. In the process we **fixed** a bug that affected roles and policies.

Best regards,
Adri

### Environment configuration
| Resource    | List                                                         |
|-------------|--------------------------------------------------------------|
| user:id     | wazuh,wazuh-app,administrator,normal,ossec,python,rbac,guest |
| role:id     | 1,2,3,4,5,6                                                  |
| policy:id   | 1,2,3,4,5,6,7,8,9,10                                         |
| role:policy | (1:1),(2:1),(3:1,2,5,8),(4:4,5),(5:2,3,10),(6:*)             |


| Actions              | Resources | Allow | Deny                              |
|----------------------|-----------|-------|-----------------------------------|
| security:read        | user:id   |       | administrator,normal,python,guest |
| security:read        | role:id   |       | *                                 |
| security:read        | policy:id | *     |                                   |
| security:update      | user:id   | *     |                                   |
| security:update      | role:id   |       | 3,4,6                             |
| security:update      | policy:id |       | 5                                 |
| security:delete      | user:id   |       | guest,normal,wazuh-app            |
| security:delete      | role:id   | *     |                                   |
| security:delete      | policy:id | *     |                                   |
| security:create      | *         |       | *                                 |
| security:create_user | *         | *     |                                   |

### Tests result
```bash
adriiiprodri@Wazuh python -m pytest -vv ~/Desktop/git/wazuh/api/test/integration/test_rbac_black_security_endpoint.tavern.yaml
======================================================================================= test session starts ========================================================================================
platform linux -- Python 3.5.3, pytest-4.5.0, py-1.8.0, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/adriiiprodri/Desktop/git/wazuh/api
plugins: tavern-0.28.0
collected 13 items                                                                                                                                                                                 

../test_rbac_black_security_endpoint.tavern.yaml::GET USERS RBAC PASSED                                                                                                                      [  7%]
../test_rbac_black_security_endpoint.tavern.yaml::GET ROLES RBAC PASSED                                                                                                                      [ 15%]
../test_rbac_black_security_endpoint.tavern.yaml::GET POLICIES RBAC PASSED                                                                                                                   [ 23%]
../test_rbac_black_security_endpoint.tavern.yaml::UPDATE USERS RBAC PASSED                                                                                                                   [ 30%]
../test_rbac_black_security_endpoint.tavern.yaml::UPDATE ROLES RBAC PASSED                                                                                                                   [ 38%]
../test_rbac_black_security_endpoint.tavern.yaml::UPDATE POLICIES RBAC PASSED                                                                                                                [ 46%]
../test_rbac_black_security_endpoint.tavern.yaml::CREATE LINK ROLE-POLICIES RBAC PASSED                                                                                                      [ 53%]
../test_rbac_black_security_endpoint.tavern.yaml::DELETE LINK ROLE-POLICIES RBAC PASSED                                                                                                      [ 61%]
../test_rbac_black_security_endpoint.tavern.yaml::DELETE USERS RBAC PASSED                                                                                                                   [ 69%]
../test_rbac_black_security_endpoint.tavern.yaml::DELETE ROLES RBAC PASSED                                                                                                                   [ 76%]
../test_rbac_black_security_endpoint.tavern.yaml::DELETE POLICIES RBAC PASSED                                                                                                                [ 84%]
../test_rbac_black_security_endpoint.tavern.yaml::CREATE USERS RBAC PASSED                                                                                                                   [ 92%]
../test_rbac_black_security_endpoint.tavern.yaml::CREATE ROLES AND POLICIES RBAC PASSED                                                                                                      [100%]

============================================================================== 13 passed, 1 warnings in 152.63 seconds ==============================================================================
```
