### ISSUE TITLE
Add integration tests for RBAC in cluster endpoints

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#4127]
## Description
We need to write additional integration tests for all endpoints involving cluster in order to guarantee that permissions are taken into account.

These tests should include:
- Allow/deny access for white list mode (everything is forbidden except those permissions explicitly allowed)
- Allow/deny access for black list mode (everything is allowed except those permissions explicitly denied)

## Tasks
- [x] GET /cluster/config
- [x] GET /cluster/configuration/validation
- [x] GET /cluster/healthcheck
- [x] GET /cluster/healthcheck/{node_id}
- [x] GET /cluster/node
- [x] GET /cluster/nodes
- [x] GET /cluster/nodes/{node_id}
- [x] PUT /cluster/restart
- [x] GET /cluster/status
- [x] GET /cluster/{node_id}/configuration
- [x] GET /cluster/{node_id}/configuration/validation
- [x] GET /cluster/{node_id}/configuration/{component}/{configuration}
- [x] DELETE /cluster/{node_id}/files
- [x] GET /cluster/{node_id}/files
- [x] PUT /cluster/{node_id}/files
- [x] GET /cluster/{node_id}/info
- [x] GET /cluster/{node_id}/logs
- [x] GET /cluster/{node_id}/logs/summary
- [x] PUT /cluster/{node_id}/restart
- [x] GET /cluster/{node_id}/stats
- [x] GET /cluster/{node_id}/stats/analysisd
- [x] GET /cluster/{node_id}/stats/hourly
- [x] GET /cluster/{node_id}/stats/remoted
- [x] GET /cluster/{node_id}/stats/weekly
- [x] GET /cluster/{node_id}/status

**Comment by AdriiiPRodri** [comment]
## Status update

Hi team,

We have added the integration tests for cluster endpoints as well as RBAC integration tests.
Some tests are marked as xfail because we expect them to fail due to #4280.

### Tests results
#### RBAC disabled
```bash
adriiiprodri@wazuh python -m pytest -vv --tavern-beta-new-traceback ../test_cluster_endpoints.tavern.yaml

============================================================================================================================== test session starts ===============================================================================================================================
platform linux -- Python 3.6.9, pytest-4.5.0, py-1.8.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/adriiiprodri/Desktop/git/wazuh/api
plugins: tavern-0.33.0
collected 53 items                                                                                                                                                                                                                                                               

../test_cluster_endpoints.tavern.yaml::GET /cluster/local/config PASSED                                                                                                                                                                                                    [  1%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/healthcheck PASSED                                                                                                                                                                                                     [  3%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/local/info PASSED                                                                                                                                                                                                      [  5%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/nodes PASSED                                                                                                                                                                                                           [  7%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/nodes[master-node] PASSED                                                                                                                                                                                              [  9%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/nodes[worker1] PASSED                                                                                                                                                                                                  [ 11%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/nodes[worker2] PASSED                                                                                                                                                                                                  [ 13%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/nodes select[ip] PASSED                                                                                                                                                                                                [ 15%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/nodes select[name] PASSED                                                                                                                                                                                              [ 16%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/nodes select[type] PASSED                                                                                                                                                                                              [ 18%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/nodes select[version] PASSED                                                                                                                                                                                           [ 20%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/status PASSED                                                                                                                                                                                                          [ 22%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/configuration PASSED                                                                                                                                                                                         [ 24%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/configuration/validation PASSED                                                                                                                                                                                        [ 26%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/configuration/{component}/{configuration} PASSED                                                                                                                                                             [ 28%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/files[master-node] PASSED                                                                                                                                                                                    [ 30%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/files[worker1] PASSED                                                                                                                                                                                        [ 32%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/files[worker2] PASSED                                                                                                                                                                                        [ 33%]
../test_cluster_endpoints.tavern.yaml::DELETE /cluster/{node_id}/files[master-node] PASSED                                                                                                                                                                                 [ 35%]
../test_cluster_endpoints.tavern.yaml::DELETE /cluster/{node_id}/files[worker1] PASSED                                                                                                                                                                                     [ 37%]
../test_cluster_endpoints.tavern.yaml::DELETE /cluster/{node_id}/files[worker2] PASSED                                                                                                                                                                                     [ 39%]
../test_cluster_endpoints.tavern.yaml::PUT /cluster/{node_id}/files[master-node] PASSED                                                                                                                                                                                    [ 41%]
../test_cluster_endpoints.tavern.yaml::PUT /cluster/{node_id}/files[worker1] PASSED                                                                                                                                                                                        [ 43%]
../test_cluster_endpoints.tavern.yaml::PUT /cluster/{node_id}/files[worker2] PASSED                                                                                                                                                                                        [ 45%]
../test_cluster_endpoints.tavern.yaml::PUT /cluster/wrong_node/files PASSED                                                                                                                                                                                                [ 47%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/info[master-node] PASSED                                                                                                                                                                                     [ 49%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/info[worker1] PASSED                                                                                                                                                                                         [ 50%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/info[worker2] PASSED                                                                                                                                                                                         [ 52%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs[master-node] PASSED                                                                                                                                                                                     [ 54%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs[worker1] PASSED                                                                                                                                                                                         [ 56%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs[worker2] PASSED                                                                                                                                                                                         [ 58%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs/summary[worker1] PASSED                                                                                                                                                                                 [ 60%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs/summary[worker2] PASSED                                                                                                                                                                                 [ 62%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats[master-node] PASSED                                                                                                                                                                                    [ 64%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats[worker1] PASSED                                                                                                                                                                                        [ 66%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats[worker2] PASSED                                                                                                                                                                                        [ 67%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/wrong_node/stats PASSED                                                                                                                                                                                                [ 69%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/analysisd[master-node] PASSED                                                                                                                                                                          [ 71%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/analysisd[worker1] PASSED                                                                                                                                                                              [ 73%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/analysisd[worker2] PASSED                                                                                                                                                                              [ 75%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/hourly[master-node] PASSED                                                                                                                                                                             [ 77%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/hourly[worker1] PASSED                                                                                                                                                                                 [ 79%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/hourly[worker2] PASSED                                                                                                                                                                                 [ 81%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/remoted[master-node] PASSED                                                                                                                                                                            [ 83%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/remoted[worker1] PASSED                                                                                                                                                                                [ 84%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/remoted[worker2] PASSED                                                                                                                                                                                [ 86%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/weekly[master-node] PASSED                                                                                                                                                                             [ 88%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/weekly[worker1] PASSED                                                                                                                                                                                 [ 90%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/weekly[worker2] PASSED                                                                                                                                                                                 [ 92%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/status[master-node] PASSED                                                                                                                                                                                   [ 94%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/status[worker1] PASSED                                                                                                                                                                                       [ 96%]
../test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/status[worker2] PASSED                                                                                                                                                                                       [ 98%]
../test_cluster_endpoints.tavern.yaml::PUT /cluster/restart PASSED                                                                                                                                                                                                         [100%]

==================================================================================================================== 53 passed, 1 warnings in 122.81 seconds =====================================================================================================================
```

#### Black RBAC tests
```bash
adriiiprodri@wazuh python -m pytest -vv --tavern-beta-new-traceback ../test_rbac_black_cluster_endpoints.tavern.yaml
============================================================================================================================== test session starts ===============================================================================================================================
platform linux -- Python 3.6.9, pytest-4.5.0, py-1.8.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/adriiiprodri/Desktop/git/wazuh/api
plugins: tavern-0.33.0
collected 18 items                                                                                                                                                                                                                                                               

../test_rbac_black_cluster_endpoints.tavern.yaml::/cluster/local/config PASSED                                                                                                                                                                                             [  5%]
../test_rbac_black_cluster_endpoints.tavern.yaml::GET /cluster/healthcheck PASSED                                                                                                                                                                                          [ 11%]
../test_rbac_black_cluster_endpoints.tavern.yaml::GET /cluster/local/info PASSED                                                                                                                                                                                           [ 16%]
../test_rbac_black_cluster_endpoints.tavern.yaml::GET /cluster/nodes PASSED                                                                                                                                                                                                [ 22%]
../test_rbac_black_cluster_endpoints.tavern.yaml::GET /cluster/nodes/{node_id} PASSED                                                                                                                                                                                      [ 27%]
../test_rbac_black_cluster_endpoints.tavern.yaml::GET /cluster/status PASSED                                                                                                                                                                                               [ 33%]
../test_rbac_black_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/configuration PASSED                                                                                                                                                                              [ 38%]
../test_rbac_black_cluster_endpoints.tavern.yaml::GET /cluster/configuration/validation PASSED                                                                                                                                                                             [ 44%]
../test_rbac_black_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/configuration/{component}/{configuration} PASSED                                                                                                                                                  [ 50%]
../test_rbac_black_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/files XPASS                                                                                                                                                                                       [ 55%]
../test_rbac_black_cluster_endpoints.tavern.yaml::DELETE /cluster/{node_id}/files XFAIL                                                                                                                                                                                    [ 61%]
../test_rbac_black_cluster_endpoints.tavern.yaml::PUT /cluster/{node_id}/files XFAIL                                                                                                                                                                                       [ 66%]
../test_rbac_black_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/info PASSED                                                                                                                                                                                       [ 72%]
../test_rbac_black_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs PASSED                                                                                                                                                                                       [ 77%]
../test_rbac_black_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs/summary PASSED                                                                                                                                                                               [ 83%]
../test_rbac_black_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats PASSED                                                                                                                                                                                      [ 88%]
../test_rbac_black_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/status PASSED                                                                                                                                                                                     [ 94%]
../test_rbac_black_cluster_endpoints.tavern.yaml::PUT /cluster/restart PASSED                                                                                                                                                                                              [100%]

========================================================================================================= 15 passed, 2 xfailed, 1 xpassed, 1 warnings in 114.41 seconds ==========================================================================================================
```

#### White RBAC tests
```bash
adriiiprodri@wazuh python -m pytest -vv --tavern-beta-new-traceback ../test_rbac_white_cluster_endpoints.tavern.yaml
============================================================================================================================== test session starts ===============================================================================================================================
platform linux -- Python 3.6.9, pytest-4.5.0, py-1.8.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/adriiiprodri/Desktop/git/wazuh/api
plugins: tavern-0.33.0
collected 18 items                                                                                                                                                                                                                                                               

../test_rbac_white_cluster_endpoints.tavern.yaml::/cluster/local/config PASSED                                                                                                                                                                                             [  5%]
../test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/healthcheck PASSED                                                                                                                                                                                          [ 11%]
../test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/local/info PASSED                                                                                                                                                                                           [ 16%]
../test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/nodes PASSED                                                                                                                                                                                                [ 22%]
../test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/nodes/{node_id} PASSED                                                                                                                                                                                      [ 27%]
../test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/status PASSED                                                                                                                                                                                               [ 33%]
../test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/configuration PASSED                                                                                                                                                                              [ 38%]
../test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/configuration/validation PASSED                                                                                                                                                                             [ 44%]
../test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/configuration/{component}/{configuration} PASSED                                                                                                                                                  [ 50%]
../test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/files XPASS                                                                                                                                                                                       [ 55%]
../test_rbac_white_cluster_endpoints.tavern.yaml::DELETE /cluster/{node_id}/files XFAIL                                                                                                                                                                                    [ 61%]
../test_rbac_white_cluster_endpoints.tavern.yaml::PUT /cluster/{node_id}/files XFAIL                                                                                                                                                                                       [ 66%]
../test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/info PASSED                                                                                                                                                                                       [ 72%]
../test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs PASSED                                                                                                                                                                                       [ 77%]
../test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs/summary PASSED                                                                                                                                                                               [ 83%]
../test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats PASSED                                                                                                                                                                                      [ 88%]
../test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/status PASSED                                                                                                                                                                                     [ 94%]
../test_rbac_white_cluster_endpoints.tavern.yaml::PUT /cluster/restart PASSED                                                                                                                                                                                              [100%]

========================================================================================================= 15 passed, 2 xfailed, 1 xpassed, 1 warnings in 114.60 seconds ==========================================================================================================
```
