### ISSUE TITLE
Add integration tests for RBAC manager endpoints

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#4129]
## Description
We need to write additional integration tests for all endpoints involving manager in order to guarantee that permissions are taken into account.

These tests should include:
- Allow/deny access for white list mode (everything is forbidden except those permissions explicitly allowed)
- Allow/deny access for black list mode (everything is allowed except those permissions explicitly denied)

## Tasks
- [x] GET /manager/configuration
- [x] GET /manager/configuration/validation
- [x] GET /manager/configuration/{component}/{configuration}
- [x] DELETE /manager/files
- [x] GET /manager/files
- [x] PUT /manager/files
- [x] GET /manager/info
- [x] GET /manager/logs
- [x] GET /manager/logs/summary
- [x] PUT /manager/restart
- [x] GET /manager/stats
- [x] GET /manager/stats/analysisd
- [x] GET /manager/stats/hourly
- [x] GET /manager/stats/remoted
- [x] GET /manager/stats/weekly
- [x] GET /manager/status

**Comment by davidjiglesias** [comment]
### **Adapt manager integration tests:**
```

**Comment by davidjiglesias** [comment]
### *BLACK RBAC integration tests:**
```
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-4.4.0, py-1.8.0, pluggy-0.12.0 -- /usr/bin/python3.6
cachedir: .pytest_cache
rootdir: /home/davidjiglesias/git/wazuh/api
plugins: cov-2.7.1, tavern-0.26.4
collecting ... collected 16 items

test_rbac_black_manager_endpoints.tavern.yaml::GET /manager/configuration PASSED [  6%]
test_rbac_black_manager_endpoints.tavern.yaml::GET /manager/configuration/validation PASSED [ 12%]
test_rbac_black_manager_endpoints.tavern.yaml::GET /manager/configuration/{component}/{configuration} PASSED [ 18%]
test_rbac_black_manager_endpoints.tavern.yaml::DELETE /manager/files XFAIL [ 25%]
test_rbac_black_manager_endpoints.tavern.yaml::GET /manager/files XFAIL  [ 31%]
test_rbac_black_manager_endpoints.tavern.yaml::PUT /manager/files XFAIL  [ 37%]
test_rbac_black_manager_endpoints.tavern.yaml::GET /manager/info PASSED  [ 43%]
test_rbac_black_manager_endpoints.tavern.yaml::GET /manager/logs PASSED  [ 50%]
test_rbac_black_manager_endpoints.tavern.yaml::GET /manager/logs/summary PASSED [ 56%]
test_rbac_black_manager_endpoints.tavern.yaml::PUT /manager/restart PASSED [ 62%]
test_rbac_black_manager_endpoints.tavern.yaml::GET /manager/stats PASSED [ 68%]
test_rbac_black_manager_endpoints.tavern.yaml::GET /manager/stats/analysisd PASSED [ 75%]
test_rbac_black_manager_endpoints.tavern.yaml::GET /manager/stats/hourly PASSED [ 81%]
test_rbac_black_manager_endpoints.tavern.yaml::GET /manager/stats/remoted PASSED [ 87%]
test_rbac_black_manager_endpoints.tavern.yaml::GET /manager/stats/weekly PASSED [ 93%]
test_rbac_black_manager_endpoints.tavern.yaml::GET /manager/status PASSED [100%]

=============================== warnings summary ===============================
test/integration/test_rbac_black_manager_endpoints.tavern.yaml::GET /manager/configuration
  /home/davidjiglesias/.local/lib/python3.6/site-packages/jwt/api_jwt.py:81: DeprecationWarning: It is strongly recommended that you pass in a value for the "algorithms" argument when calling decode(). This argument will be mandatory in a future version.
    DeprecationWarning

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=============== 13 passed, 3 xfailed, 1 warnings in 0.63 seconds ===============
```

**Comment by davidjiglesias** [comment]
### **WHITE RBAC integration tests:**
```
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-4.4.0, py-1.8.0, pluggy-0.12.0 -- /usr/bin/python3.6
cachedir: .pytest_cache
rootdir: /home/davidjiglesias/git/wazuh/api
plugins: cov-2.7.1, tavern-0.26.4
collecting ... collected 16 items

test_rbac_white_manager_endpoints.tavern.yaml::GET /manager/configuration PASSED [  6%]
test_rbac_white_manager_endpoints.tavern.yaml::GET /manager/configuration/validation PASSED [ 12%]
test_rbac_white_manager_endpoints.tavern.yaml::GET /manager/configuration/{component}/{configuration} PASSED [ 18%]
test_rbac_white_manager_endpoints.tavern.yaml::DELETE /manager/files XFAIL [ 25%]
test_rbac_white_manager_endpoints.tavern.yaml::GET /manager/files XFAIL  [ 31%]
test_rbac_white_manager_endpoints.tavern.yaml::PUT /manager/files XPASS  [ 37%]
test_rbac_white_manager_endpoints.tavern.yaml::GET /manager/info PASSED  [ 43%]
test_rbac_white_manager_endpoints.tavern.yaml::GET /manager/logs PASSED  [ 50%]
test_rbac_white_manager_endpoints.tavern.yaml::GET /manager/logs/summary PASSED [ 56%]
test_rbac_white_manager_endpoints.tavern.yaml::PUT /manager/restart PASSED [ 62%]
test_rbac_white_manager_endpoints.tavern.yaml::GET /manager/stats PASSED [ 68%]
test_rbac_white_manager_endpoints.tavern.yaml::GET /manager/stats/analysisd PASSED [ 75%]
test_rbac_white_manager_endpoints.tavern.yaml::GET /manager/stats/hourly PASSED [ 81%]
test_rbac_white_manager_endpoints.tavern.yaml::GET /manager/stats/remoted PASSED [ 87%]
test_rbac_white_manager_endpoints.tavern.yaml::GET /manager/stats/weekly PASSED [ 93%]
test_rbac_white_manager_endpoints.tavern.yaml::GET /manager/status PASSED [100%]

=============================== warnings summary ===============================
test/integration/test_rbac_white_manager_endpoints.tavern.yaml::GET /manager/configuration
  /home/davidjiglesias/.local/lib/python3.6/site-packages/jwt/api_jwt.py:81: DeprecationWarning: It is strongly recommended that you pass in a value for the "algorithms" argument when calling decode(). This argument will be mandatory in a future version.
    DeprecationWarning

-- Docs: https://docs.pytest.org/en/latest/warnings.html
========= 13 passed, 2 xfailed, 1 xpassed, 1 warnings in 1.97 seconds ==========
```
