### ISSUE TITLE
Implement the ability to remove positive threats reported by VirusTotal

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh#4172]
Hello team,

We currently have a [VirusTotal integration](https://documentation.wazuh.com/3.10/user-manual/capabilities/virustotal-scan/index.html) which is working pretty good. But thinking further on this feature, it could be interesting to trigger an active response that automatically removes such a positive threat or moving it into quarantine.

#### Proposal

To implement this, we should keep in mind the following flow:

![active response (1)](https://user-images.githubusercontent.com/10210567/67875264-64d50a80-fb36-11e9-8288-30326df94249.png)

1. On the agent side, we have several resources being monitored. When a new file is created or modified, a new `syscheck` alert is created.

2. We have the `VirusTotal` integration already configured so in case the file is a positive threat, a new alert with ID `87105` will be triggered.

3. Then, we have to set up a new `integration` to be triggered when that specific ID is launched.

4. This integration will be in charge of reading the alert and extracting the required fields, such:
    - Agent ID.
    - Path of detected file.

5. Write messages to the `AR socket` so each agent will be noticed to execute the script of removing positive threats.

6. In order to generate alerts of each removed threat, the local script should write into the `active-response.log` file, also this file has to be monitored as `localfile`.

#### Tasks to do:

- [x] Implement the `integration script`.
- [x] Implement the local script that removes a positive threat.
   - [x] Linux
   - [ ] Windows
   - [ ] Other operating systems
- [x] Write the proper `rules` and `decoders` so an alert can be triggered when a threat is removed.
- [x] Tests
   - [x] Single host
   - [x] Cluster environment

The details of this development will be tracked on this issue.

Cheers

**Comment by manuasir** [comment]
Hi, just pasting here the results I got for making this work:

Before starting, it's required to set up the [VirusTotal integration](https://documentation.wazuh.com/3.10/user-manual/capabilities/virustotal-scan/index.html).


#### Manager side

- Append the following decoder to `/var/ossec/etc/decoders/local_decoder.xml`
```xml
<decoder name="ar_log_fields">
    <parent>ar_log</parent>
    <regex offset="after_parent">^(\S+) Removed positive threat located in (\S+)</regex>
    <order>script_name, path</order>
</decoder>
```

- Append the following rule to `/var/ossec/etc/rules/local_rules.xml`
```xml
<group name="syscheck,virustotal,">
  <rule id="100092" level="12">
    <if_sid>607</if_sid>
    <match>Removed positive</match>
    <description>$(script_name) Removed positive threat located in $(path)</description>
  </rule>
</group>
```

- Place this `custom-remove-threat` script in `/var/ossec/etc/integrations`

```python
#!/usr/bin/env python
# Copyright (C) 2017 Wazuh Inc.
# October 29, 2019.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.
# Wazuh, Inc <support@wazuh.com>
import json
import sys
import time
import os
from socket import socket, AF_UNIX, SOCK_DGRAM
# ossec.conf configuration:
#  <command>
#    <name>remove-threat</name>
#    <executable>remove-threat.sh</executable>
#    <expect>filename</expect>
#    <timeout_allowed>no</timeout_allowed>
#  </command>
#  <active-response>
#   <disabled>no</disabled>
#   <command>remove-threat</command>
#   <location>local</location>
# </active-response>
#  <integration>
#      <name>custom-remove-threat</name>
#      <rule_id>87105</rule_id>
#       <alert_format>json</alert_format>
#  </integration>
# Global vars
debug_enabled = True
pwd = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
json_alert = {}
now = time.strftime("%a %b %d %H:%M:%S %Z %Y")
# Set paths
log_file = '{0}/logs/integrations.log'.format(pwd)
socket_addr = '{0}/queue/alerts/ar'.format(pwd)
def main(args):
    debug("# Starting")
    # Read args
    alert_file_location = args[1]
    debug("# File location")
    debug(alert_file_location)
    # Load alert. Parse JSON object.
    with open(alert_file_location) as alert_file:    
        json_alert = json.load(alert_file)
    debug("# Processing alert")
    debug(json_alert)
    # Send event to AR socket
    msg = "(msg_to_agent) [] NNS {0} remove-threat0 - {1}".format(json_alert["agent"]["id"], json_alert["data"]["virustotal"]["source"]["file"])
    send_event(msg)
def debug(msg):
    if debug_enabled:
        msg = "{0}: {1}\n".format(now, msg)
        print(msg)
        f = open(log_file,"a")
        f.write(msg)
        f.close()
def send_event(msg):
    sock = socket(AF_UNIX, SOCK_DGRAM)
    sock.connect(socket_addr)
    sock.send(msg.encode())
    sock.close()
if __name__ == "__main__":
    try:
        # Read arguments
        bad_arguments = False
        if len(sys.argv) >= 2:
            alertfile=sys.argv[1]
            msg = '{0} {1} {2} {3}'.format(now, sys.argv[1], sys.argv[2], sys.argv[3])
        else:
            msg = '{0} Wrong arguments'.format(now)
            bad_arguments = True
        # Logging the call
        f = open(log_file, 'a')
        f.write(msg +'\n')
        f.close()
        if bad_arguments:
            debug("# Exiting: Bad arguments.")
            sys.exit(0)
        # Main function
        main(sys.argv)
    except Exception as e:
        debug('Error:' + str(e))
        raise
```

- Set permissions to the `custom-remove-threat`

```cmd
chgrp ossec /var/ossec/integrations/custom-remove-threat
chmod 750 /var/ossec/integrations/custom-remove-threat
```

- Manager `ossec.conf`

```xml
<command>
    <name>remove-threat</name>
    <executable>remove-threat.sh</executable>
    <expect>filename</expect>
    <timeout_allowed>no</timeout_allowed>
</command>

<active-response>
    <disabled>no</disabled>
    <command>remove-threat</command>
    <location>local</location>
</active-response>

<integration>
    <name>custom-remove-threat</name>
    <rule_id>87105</rule_id>
    <alert_format>json</alert_format>
</integration>
```

#### Agents side

- Place this `remove-threat.sh` script in `/var/ossec/active-response/bin/`

```bash
#!/bin/bash

# Checking user arguments
if [ "x$1" == "xdelete" ]; then
    exit 0;
fi

LOCAL=`dirname $0`;
cd $LOCAL
cd ../

PWD=`pwd`

# Removing file
rm -f $3
if [ $? -eq 0 ]; then
    echo "`date` $0 Removed positive threat located in $3" >> ${PWD}/../logs/active-responses.log
else
    echo "`date` $0 Error removing positive threat located in $3" >> ${PWD}/../logs/active-responses.log
fi

exit 0;
```

- Set permissions to the `remove-threat.sh`

```cmd
chgrp ossec /var/ossec/active-response/bin/remove-threat.sh
chmod 750 /var/ossec/active-response/bin/remove-threat.sh
```
