### ISSUE TITLE
Add endpoint /rules/mitre to new API

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#4213]
## Description

A new endpoint was added according to issue #4212. This new one must implemented in new API also.

## Subtasks
- [x] Modify OpenAPI spec
- [x] Add framework support
- [x] Add RBAC decorator
- [x] Add this use case to integration tests

**Comment by davidjiglesias** [comment]
Hi team,

I have added `mitre` filter to `GET /rules` endpoint. I have also added `GET /rules/requirement/mitre` and updated integration tests for new endpoint and filter.

**Comment by davidjiglesias** [comment]
### **Integration test results:**
```
============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-4.4.0, py-1.8.0, pluggy-0.12.0 -- /usr/bin/python3.6
cachedir: .pytest_cache
rootdir: /home/davidjiglesias/git/wazuh/api
plugins: cov-2.7.1, tavern-0.34.0
collecting ... collected 11 items

test_rules_endpoints.tavern.yaml::GET /rules PASSED                      [  9%]
test_rules_endpoints.tavern.yaml::GET /rules filters XFAIL               [ 18%]
test_rules_endpoints.tavern.yaml::GET /rules/requirement/pci PASSED      [ 27%]
test_rules_endpoints.tavern.yaml::GET /rules/requirement/gdpr PASSED     [ 36%]
test_rules_endpoints.tavern.yaml::GET /rules/requirement/gpg13 PASSED    [ 45%]
test_rules_endpoints.tavern.yaml::GET /rules/requirement/hipaa PASSED    [ 54%]
test_rules_endpoints.tavern.yaml::GET /rules/requirement/nist-800-53 PASSED [ 63%]
test_rules_endpoints.tavern.yaml::GET /rules/requirement/mitre XPASS     [ 72%]
test_rules_endpoints.tavern.yaml::GET /rules/groups PASSED               [ 81%]
test_rules_endpoints.tavern.yaml::GET /rules/files PASSED                [ 90%]
test_rules_endpoints.tavern.yaml::GET /rules/{rule_ids} PASSED           [100%]

=============================== warnings summary ===============================
test/integration/test_rules_endpoints.tavern.yaml::GET /rules
  /home/davidjiglesias/.local/lib/python3.6/site-packages/jwt/api_jwt.py:81: DeprecationWarning: It is strongly recommended that you pass in a value for the "algorithms" argument when calling decode(). This argument will be mandatory in a future version.
    DeprecationWarning

test/integration/test_rules_endpoints.tavern.yaml::GET /rules
test/integration/test_rules_endpoints.tavern.yaml::GET /rules filters
  /home/davidjiglesias/.local/lib/python3.6/site-packages/tavern/util/dict_util.py:189: FutureWarning: In a future version of Tavern, selecting for values to save in nested objects will have to be done as a JMES path query - see http://jmespath.org/ for more information
    warnings.warn(msg, FutureWarning)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
========= 9 passed, 1 xfailed, 1 xpassed, 3 warnings in 43.43 seconds ==========
```
