### ISSUE TITLE
Add RBAC support to new endpoint GET /syscollector/hotfixes

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#4219]
## Description
A new endpoint was added according to issue #3800. Now we should ensure that it is considered in our RBAC roadmap.

## Subtasks
- [x] Include RBAC permissions in the controller
- [x] Check the decorator in the framework function
- [x] Create new tests for black-list and white-list modes

**Comment by vicferpoy** [comment]
## Status update

Hi team,

We have added RBAC support to the new endpoint `GET /syscollector/hotfixes`. We have also added tests for **white** and **black** mode, but they are being skipped right now.

We have done this to prevent them from giving false negatives, since they use agent databases that are not implemented until `3.11`. Once we upgrade to 3.11, we could test both modes properly simply by removing the `x-fail` mark in both of them.  

### RBAC *white* mode
```
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.7.5rc1, pytest-4.5.0, py-1.8.0, pluggy-0.13.0 -- /usr/bin/python3.7
cachedir: .pytest_cache
rootdir: /home/vicferpoy/Desktop/Git/wazuh/api
plugins: tavern-0.30.3
collected 9 items                                                                                                                                                                                                 

test_rbac_white_syscollector_endpoints.tavern.yaml::GET OS SYSCOLLECTOR RBAC PASSED                                                                                                                         [ 11%]
test_rbac_white_syscollector_endpoints.tavern.yaml::GET HARDWARE SYSCOLLECTOR RBAC PASSED                                                                                                                   [ 22%]
test_rbac_white_syscollector_endpoints.tavern.yaml::GET NETADDR SYSCOLLECTOR RBAC PASSED                                                                                                                    [ 33%]
test_rbac_white_syscollector_endpoints.tavern.yaml::GET NETIFACE SYSCOLLECTOR RBAC PASSED                                                                                                                   [ 44%]
test_rbac_white_syscollector_endpoints.tavern.yaml::GET NETPROTO SYSCOLLECTOR RBAC PASSED                                                                                                                   [ 55%]
test_rbac_white_syscollector_endpoints.tavern.yaml::GET PACKAGES SYSCOLLECTOR RBAC PASSED                                                                                                                   [ 66%]
test_rbac_white_syscollector_endpoints.tavern.yaml::GET PORTS SYSCOLLECTOR RBAC PASSED                                                                                                                      [ 77%]
test_rbac_white_syscollector_endpoints.tavern.yaml::GET PROCESSES SYSCOLLECTOR RBAC PASSED                                                                                                                  [ 88%]
test_rbac_white_syscollector_endpoints.tavern.yaml::GET HOTFIXES SYSCOLLECTOR RBAC XFAIL                                                                                                                    [100%]

================================================================================================ warnings summary =================================================================================================
test/integration/test_rbac_white_syscollector_endpoints.tavern.yaml::GET OS SYSCOLLECTOR RBAC
  /usr/lib/python3/dist-packages/jwt/api_jwt.py:81: DeprecationWarning: It is strongly recommended that you pass in a value for the "algorithms" argument when calling decode(). This argument will be mandatory in a future version.
    DeprecationWarning

-- Docs: https://docs.pytest.org/en/latest/warnings.html
================================================================================ 8 passed, 1 xfailed, 1 warnings in 73.65 seconds =================================================================================
```

### RBAC *black* mode
```
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.7.5rc1, pytest-4.5.0, py-1.8.0, pluggy-0.13.0 -- /usr/bin/python3.7
cachedir: .pytest_cache
rootdir: /home/vicferpoy/Desktop/Git/wazuh/api
plugins: tavern-0.30.3
collected 9 items                                                                                                                                                                                                 

test_rbac_black_syscollector_endpoints.tavern.yaml::GET OS SYSCOLLECTOR RBAC PASSED                                                                                                                         [ 11%]
test_rbac_black_syscollector_endpoints.tavern.yaml::GET HARDWARE SYSCOLLECTOR RBAC PASSED                                                                                                                   [ 22%]
test_rbac_black_syscollector_endpoints.tavern.yaml::GET NETADDR SYSCOLLECTOR RBAC PASSED                                                                                                                    [ 33%]
test_rbac_black_syscollector_endpoints.tavern.yaml::GET NETIFACE SYSCOLLECTOR RBAC PASSED                                                                                                                   [ 44%]
test_rbac_black_syscollector_endpoints.tavern.yaml::GET NETPROTO SYSCOLLECTOR RBAC PASSED                                                                                                                   [ 55%]
test_rbac_black_syscollector_endpoints.tavern.yaml::GET PACKAGES SYSCOLLECTOR RBAC PASSED                                                                                                                   [ 66%]
test_rbac_black_syscollector_endpoints.tavern.yaml::GET PORTS SYSCOLLECTOR RBAC PASSED                                                                                                                      [ 77%]
test_rbac_black_syscollector_endpoints.tavern.yaml::GET PROCESSES SYSCOLLECTOR RBAC PASSED                                                                                                                  [ 88%]
test_rbac_black_syscollector_endpoints.tavern.yaml::GET HOTFIXES SYSCOLLECTOR RBAC XFAIL                                                                                                                    [100%]

================================================================================================ warnings summary =================================================================================================
```
