### ISSUE TITLE
Add RBAC support to experimental endpoints

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#4258]
## Description

Currently, the following experimental endpoints must be supported in the new API:
- [x] GET /experimental/ciscat/results
- [x] DELETE /experimental/syscheck
- [x] GET /experimental/syscollector/hardware
- [x] GET /experimental/syscollector/netaddr
- [x] GET /experimental/syscollector/netiface
- [x] GET /experimental/syscollector/netproto
- [x] GET /experimental/syscollector/os
- [x] GET /experimental/syscollector/packages
- [x] GET /experimental/syscollector/ports
- [x] GET /experimental/syscollector/processes
- [x] GET /experimental/syscollector/hotfixes

All these endpoints must have their integrated tests implemented and working. After that, RBAC support must be extended to all of them, with integration tests also.

*NOTE*: care must be taken when testing sort and select params since all these endpoints are kind of broadcast calls.

## Tasks
- [x] Ensure all integrated tests are working
- [x] Add RBAC support to all framework functions
- [x] Write and pass integrated tests for black-list and white-list mode

**Comment by davidjiglesias** [comment]
### **Adapted integration tests results:**
```

**Comment by davidjiglesias** [comment]
### **Adapted integration test results:**
```
### **Adapted integration tests results:**
```
============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-4.4.0, py-1.8.0, pluggy-0.12.0 -- /usr/bin/python3.6
cachedir: .pytest_cache
rootdir: /home/davidjiglesias/git/wazuh/api
plugins: cov-2.7.1, tavern-0.26.4
collecting ... collected 10 items

test_experimental_endpoints.tavern.yaml::DELETE /experimental/syscheck PASSED [ 10%]
test_experimental_endpoints.tavern.yaml::GET /experimental/ciscat/results PASSED [ 20%]
test_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/hardware PASSED [ 30%]
test_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/netaddr PASSED [ 40%]
test_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/netiface PASSED [ 50%]
test_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/netproto PASSED [ 60%]
test_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/os PASSED [ 70%]
test_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/packages PASSED [ 80%]
test_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/ports PASSED [ 90%]
test_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/processes PASSED [100%]

=============================== warnings summary ===============================
test/integration/test_experimental_endpoints.tavern.yaml::DELETE /experimental/syscheck
  /home/davidjiglesias/.local/lib/python3.6/site-packages/jwt/api_jwt.py:81: DeprecationWarning: It is strongly recommended that you pass in a value for the "algorithms" argument when calling decode(). This argument will be mandatory in a future version.
    DeprecationWarning

-- Docs: https://docs.pytest.org/en/latest/warnings.html
==================== 10 passed, 1 warnings in 6.22 seconds =====================
```

**Comment by davidjiglesias** [comment]
### **Black RBAC test results:**
```
============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-4.4.0, py-1.8.0, pluggy-0.12.0 -- /usr/bin/python3.6
cachedir: .pytest_cache
rootdir: /home/davidjiglesias/git/wazuh/api
plugins: cov-2.7.1, tavern-0.26.4
collecting ... collected 11 items

test_rbac_black_experimental_endpoints.tavern.yaml::DELETE /experimental/syscheck PASSED [  9%]
test_rbac_black_experimental_endpoints.tavern.yaml::GET /experimental/ciscat/results XFAIL [ 18%]
test_rbac_black_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/hardware PASSED [ 27%]
test_rbac_black_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/netaddr PASSED [ 36%]
test_rbac_black_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/netiface PASSED [ 45%]
test_rbac_black_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/netproto PASSED [ 54%]
test_rbac_black_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/os PASSED [ 63%]
test_rbac_black_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/packages PASSED [ 72%]
test_rbac_black_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/ports PASSED [ 81%]
test_rbac_black_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/processes PASSED [ 90%]
test_rbac_black_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/hotfixes XFAIL [100%]

=============================== warnings summary ===============================
test/integration/test_rbac_black_experimental_endpoints.tavern.yaml::DELETE /experimental/syscheck
  /home/davidjiglesias/.local/lib/python3.6/site-packages/jwt/api_jwt.py:81: DeprecationWarning: It is strongly recommended that you pass in a value for the "algorithms" argument when calling decode(). This argument will be mandatory in a future version.
    DeprecationWarning

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=============== 9 passed, 2 xfailed, 1 warnings in 95.27 seconds ===============
```

**Comment by davidjiglesias** [comment]
### **White RBAC test results:**
```
============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-4.4.0, py-1.8.0, pluggy-0.12.0 -- /usr/bin/python3.6
cachedir: .pytest_cache
rootdir: /home/davidjiglesias/git/wazuh/api
plugins: cov-2.7.1, tavern-0.26.4
collecting ... collected 11 items

test_rbac_white_experimental_endpoints.tavern.yaml::DELETE /experimental/syscheck PASSED [  9%]
test_rbac_white_experimental_endpoints.tavern.yaml::GET /experimental/ciscat/results XFAIL [ 18%]
test_rbac_white_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/hardware PASSED [ 27%]
test_rbac_white_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/netaddr PASSED [ 36%]
test_rbac_white_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/netiface PASSED [ 45%]
test_rbac_white_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/netproto PASSED [ 54%]
test_rbac_white_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/os PASSED [ 63%]
test_rbac_white_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/packages PASSED [ 72%]
test_rbac_white_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/ports PASSED [ 81%]
test_rbac_white_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/processes PASSED [ 90%]
test_rbac_white_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/hotfixes XFAIL [100%]

=============================== warnings summary ===============================
test/integration/test_rbac_white_experimental_endpoints.tavern.yaml::DELETE /experimental/syscheck
  /home/davidjiglesias/.local/lib/python3.6/site-packages/jwt/api_jwt.py:81: DeprecationWarning: It is strongly recommended that you pass in a value for the "algorithms" argument when calling decode(). This argument will be mandatory in a future version.
    DeprecationWarning

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=============== 9 passed, 2 xfailed, 1 warnings in 96.14 seconds ===============
```

**Comment by davidjiglesias** [comment]
### **API experimental endpoints RBAC catalog:**
| Http Method | API endpoint  | Actions | Resources |
| ------------- | ------------- | ------------- | ------------ |
| GET | /experimental/ciscat/results | ciscat:read | agent:id | 
| DELETE | /experimental/syscheck | syscheck:clear | agent:id | 
| GET | /experimental/syscollector/hardware | syscollector:read | agent:id | 
| GET | /experimental/syscollector/netaddr  | syscollector:read | agent:id | 
| GET | /experimental/syscollector/netiface | syscollector:read | agent:id | 
| GET | /experimental/syscollector/netproto | syscollector:read | agent:id | 
| GET | /experimental/syscollector/os | agent:id | 
| GET | /experimental/syscollector/packages | syscollector:read | agent:id | 
| GET | /experimental/syscollector/ports | syscollector:read | agent:id | 
| GET | /experimental/syscollector/processes | syscollector:read  | agent:id | 
| GET | /experimental/syscollector/hotfixes/configuration | syscollector:read | agent:id |
