### ISSUE TITLE
Rewrite unit tests for cluster module

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#4300]
## Description
Unit tests must be adapted to new RBAC and API implementation.

## Tasks
- [x] wazuh/tests/test_cluster.py
- [x] wazuh/core/cluster/tests/test_client.py
- [x] wazuh/core/cluster/tests/test_cluster.py (Already fixed, 35% coverage)
- [x] wazuh/core/cluster/tests/test_common.py (Already fixed, 31% coverage)
- [x] wazuh/core/cluster/tests/test_control.py
- [x] wazuh/core/cluster/tests/test_local_client.py (Already fixed, 39% coverage)
- [x] wazuh/core/cluster/tests/test_local_server.py
- [x] wazuh/core/cluster/tests/test_master.py
- [x] wazuh/core/cluster/tests/test_server.py
- [x] wazuh/core/cluster/tests/test_utils.py
- [x] wazuh/core/cluster/tests/test_worker.py (Already fixed, 53% coverage)
- [x] wazuh/core/cluster/dapi/tests/test_dapi.py (88%, The asynchronous function is missing)

**Comment by vicferpoy** [comment]
# Status update
Development has begun. 
**Branch**: [feature/4300-dev-flask-rework-cluster-unittests](https://github.com/wazuh/wazuh/tree/feature/4300-dev-flask-rework-cluster-unittests)

**Comment by vicferpoy** [comment]
# Status update

Development has been stopped. We are currently reworking the new API and making some cluster changes. It will resume afterwards.

**Comment by AdriiiPRodri** [comment]
# Status update

```bash
adriiiprodri@wazuh python3 -m coverage run --source=wazuh.core.cluster.dapi.dapi -m pytest test_dapi.py
=========================================================================== test session starts ===========================================================================
platform linux -- Python 3.7.5, pytest-5.4.1, py-1.7.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/Desktop/git/wazuh/framework
plugins: html-2.0.1, mock-1.10.0, cov-2.8.1, testinfra-5.0.0, tavern-1.0.0, metadata-1.8.0
collected 20 items

test_dapi.py ....................                                                                                                                                   [100%]

===================================================================== 20 passed, 2 warnings in 0.75s ======================================================================
```

```bash
adriiiprodri@wazuh coverage report -m
Name                                                                             Stmts   Miss  Cover   Missing
--------------------------------------------------------------------------------------------------------------
wazuh/framework/wazuh/core/cluster/dapi/dapi.py     255     28    89%   266, 278, 399, 449-452, 488, 506-538
```

**Comment by AdriiiPRodri** [comment]
# Status update

## New cluster integrated test
```bash
adriiiprodri@wazuh python3 -m coverage run --source=wazuh.cluster -m pytest -x test_cluster.py
=========================================================================== test session starts ===========================================================================
platform linux -- Python 3.7.5, pytest-5.4.1, py-1.7.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/Desktop/git/wazuh/framework
plugins: html-2.0.1, mock-1.10.0, asyncio-0.12.0, aiohttp-0.3.0, cov-2.8.1, testinfra-5.0.0, tavern-1.0.0, metadata-1.8.0
collected 7 items                                                                                                                                                         

test_cluster.py .......                                                                                                                                             [100%]

====================================================================== 7 passed, 2 warnings in 0.11s ======================================================================
```
```bash
adriiiprodri@wazuh coverage report -m
Name                                             Stmts   Miss  Cover   Missing
-----------------------------------------------------------------------------------------------
wazuh/framework/wazuh/cluster.py      43      0   100%
```

**Comment by AdriiiPRodri** [comment]
# Status update

## New control integrated test
```bash
adriiiprodri@wazuh python3 -m coverage run --source=wazuh.core.cluster.control -m pytest -x test_control.py
=========================================================================== test session starts ===========================================================================
platform linux -- Python 3.7.5, pytest-5.4.1, py-1.7.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/Desktop/git/wazuh/framework
plugins: html-2.0.1, mock-1.10.0, asyncio-0.12.0, aiohttp-0.3.0, cov-2.8.1, testinfra-5.0.0, tavern-1.0.0, metadata-1.8.0
collected 5 items                                                                                                                                                         

test_control.py .....                                                                                                                                               [100%]

====================================================================== 5 passed, 2 warnings in 0.11s ======================================================================
```
```bash
adriiiprodri@wazuh coverage report -m
Name                                                              Stmts   Miss  Cover   Missing
------------------------------------------------------------------------------------------------------------
wazuh/framework/wazuh/core/cluster/control.py      49      0   100%
```

**Comment by AdriiiPRodri** [comment]
# Status update

## New core/cluster/utils.py integrated test
```bash
adriiiprodri@wazuh python3 -m coverage run --source=wazuh.core.cluster.utils -m pytest -x test_utils.py
=========================================================================== test session starts ===========================================================================
platform linux -- Python 3.7.5, pytest-5.4.1, py-1.7.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/Desktop/git/wazuh/framework
plugins: html-2.0.1, mock-1.10.0, asyncio-0.12.0, aiohttp-0.3.0, cov-2.8.1, testinfra-5.0.0, tavern-1.0.0, metadata-1.8.0
collected 7 items                                                                                                                                                         

test_utils.py .......                                                                                                                                               [100%]

====================================================================== 7 passed, 1 warning in 0.08s =======================================================================
```
```bash
adriiiprodri@wazuh coverage report -m
Name                                          Stmts   Miss  Cover   Missing
----------------------------------------------------------------------------------------------------------
wazuh/framework/wazuh/core/cluster/utils.py     117      3    97%   113, 115, 117
```

**Comment by AdriiiPRodri** [comment]
## RBAC tests
### Black RBAC
```bash
adriiiprodri@wazuh pytest -vv test_rbac_black_cluster_endpoints.tavern.yaml
================================ test session starts ================================
platform linux -- Python 3.7.5, pytest-5.4.1, py-1.7.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.7.5', 'Platform': 'Linux-5.3.0-7648-generic-x86_64-with-Ubuntu-19.10-eoan', 'Packages': {'pytest': '5.4.1', 'py': '1.7.0', 'pluggy': '0.13.1'}, 'Plugins': {'html': '2.0.1', 'mock': '1.10.0', 'asyncio': '0.12.0', 'aiohttp': '0.3.0', 'cov': '2.8.1', 'testinfra': '5.0.0', 'tavern': '1.0.0', 'metadata': '1.8.0'}}
rootdir: /home/adriiiprodri/Desktop/git/wazuh/api/test/integration, inifile: pytest.ini
plugins: html-2.0.1, mock-1.10.0, asyncio-0.12.0, aiohttp-0.3.0, cov-2.8.1, testinfra-5.0.0, tavern-1.0.0, metadata-1.8.0
collected 21 items

test_rbac_black_cluster_endpoints.tavern.yaml::/cluster/local/config PASSED   [  4%]
test_rbac_black_cluster_endpoints.tavern.yaml::GET /cluster/healthcheck PASSED [  9%]
test_rbac_black_cluster_endpoints.tavern.yaml::GET /cluster/local/info PASSED [ 14%]
test_rbac_black_cluster_endpoints.tavern.yaml::GET /cluster/nodes PASSED      [ 19%]
test_rbac_black_cluster_endpoints.tavern.yaml::GET /cluster/nodes/{node_id} PASSED [ 23%]
test_rbac_black_cluster_endpoints.tavern.yaml::GET /cluster/status PASSED     [ 28%]
test_rbac_black_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/configuration PASSED [ 33%]
test_rbac_black_cluster_endpoints.tavern.yaml::GET /cluster/configuration/validation PASSED [ 38%]
test_rbac_black_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/configuration/{component}/{configuration} PASSED [ 42%]
test_rbac_black_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/info PASSED [ 47%]
test_rbac_black_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs PASSED [ 52%]
test_rbac_black_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs/summary PASSED [ 57%]
test_rbac_black_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats PASSED [ 61%]
test_rbac_black_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/status PASSED [ 66%]
test_rbac_black_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/files PASSED [ 71%]
test_rbac_black_cluster_endpoints.tavern.yaml::PUT /cluster/{node_id}/files PASSED [ 76%]
test_rbac_black_cluster_endpoints.tavern.yaml::DELETE /cluster/{node_id}/files PASSED [ 80%]
test_rbac_black_cluster_endpoints.tavern.yaml::GET /cluster/api/config PASSED [ 85%]
test_rbac_black_cluster_endpoints.tavern.yaml::PUT /cluster/api/config PASSED [ 90%]
test_rbac_black_cluster_endpoints.tavern.yaml::DELETE /cluster/api/config PASSED [ 95%]
test_rbac_black_cluster_endpoints.tavern.yaml::PUT /cluster/restart PASSED    [100%]

==================== 21 passed, 88 warnings in 156.19s (0:02:36) ====================
```
### White RBAC
```bash
adriiiprodri@wazuh  ~/Desktop/git/wazuh/api/test/integration   feature/5109-JWT_invalidation ●  pytest -vv test_rbac_white_cluster_endpoints.tavern.yaml
================================ test session starts ================================
platform linux -- Python 3.7.5, pytest-5.4.1, py-1.7.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.7.5', 'Platform': 'Linux-5.3.0-7648-generic-x86_64-with-Ubuntu-19.10-eoan', 'Packages': {'pytest': '5.4.1', 'py': '1.7.0', 'pluggy': '0.13.1'}, 'Plugins': {'html': '2.0.1', 'mock': '1.10.0', 'asyncio': '0.12.0', 'aiohttp': '0.3.0', 'cov': '2.8.1', 'testinfra': '5.0.0', 'tavern': '1.0.0', 'metadata': '1.8.0'}}
rootdir: /home/adriiiprodri/Desktop/git/wazuh/api/test/integration, inifile: pytest.ini
plugins: html-2.0.1, mock-1.10.0, asyncio-0.12.0, aiohttp-0.3.0, cov-2.8.1, testinfra-5.0.0, tavern-1.0.0, metadata-1.8.0
collected 21 items

test_rbac_white_cluster_endpoints.tavern.yaml::/cluster/local/config PASSED   [  4%]
test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/healthcheck PASSED [  9%]
test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/local/info PASSED [ 14%]
test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/nodes PASSED      [ 19%]
test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/nodes/{node_id} PASSED [ 23%]
test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/status PASSED     [ 28%]
test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/configuration PASSED [ 33%]
test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/configuration/validation PASSED [ 38%]
test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/configuration/{component}/{configuration} PASSED [ 42%]
test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/info PASSED [ 47%]
test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs PASSED [ 52%]
test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs/summary PASSED [ 57%]
test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats PASSED [ 61%]
test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/status PASSED [ 66%]
test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/api/config PASSED [ 71%]
test_rbac_white_cluster_endpoints.tavern.yaml::PUT /cluster/api/config PASSED [ 76%]
test_rbac_white_cluster_endpoints.tavern.yaml::PUT /cluster/restart PASSED    [ 80%]
test_rbac_white_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/files PASSED [ 85%]
test_rbac_white_cluster_endpoints.tavern.yaml::PUT /cluster/{node_id}/files PASSED [ 90%]
test_rbac_white_cluster_endpoints.tavern.yaml::DELETE /cluster/{node_id}/files PASSED [ 95%]
test_rbac_white_cluster_endpoints.tavern.yaml::DELETE /cluster/api/config PASSED [100%]

==================== 21 passed, 90 warnings in 155.70s (0:02:35) ====================
```
