### ISSUE TITLE
FIM v2: Save DB into disk storage

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#4347]
|Related issue|
|---|
|#3319|

|Working branch|
|---|
|[3319-fim-rework-sqlite](https://github.com/wazuh/wazuh/tree/3319-fim-rework-sqlite)|

## Introduction

We know that Syscheck stores the filesystem's state into memory so that it can compare file checksums and determine was either just added, changed or deleted. All this data is handled by `syscheck.fim_entry` (a red-black tree).

In addition, Syscheck needs to handle the relationship between file paths and inodes in order to locate a file by its device-inode pair, and get the known hard links to a file. The `syscheck.fim_inode` hash table saves this data.

Handling all this information takes a cost of O(n) with respect to the number of monitored files. There are two matters here:
1. We've made many improvements to FIM that have increased the amount of memory used per file.
2. We expect FIM to be able to monitor a large number of files.

## Proposal

We aim to replace the data structures mentioned above with an SQLite database in the agent. This database should behave just like the current data structures, and be recreated on every agent startup.

### Functional requirements

The design should keep the same functional requirements that FIM currently meets.

1. Store all files in a database on disk.
2. Insert a file.
3. Retrieve a file by the path and by device-inode pair.
4. Mark all files as "old".
5. Mark one file as "new".
6. Retrieve and delete old files.
7. Retrieve a list of file checksum ordered by path, within a range (`rbtree_range()`).
8. Retrieve a list of files within a range.
9. Commit the database every few seconds.
10. Delete the database when the agent stops.
11. Delete and recreate the database when the agent starts.

Here are possible requirements for future versions (just keep them in mind):

- Switch the database on disk with an in-memory database.
- Let the database be persistent if Syscheck is stopped less time than `<interval>`.

### Non-functional requirements

1. FIM shall not increase the memory usage with the number of files (pay attention to functional requirements 6, 7 and 8).
2. Syscheck shall use as much disk space as it's currently taking in RAM (FIMv2). Optimize disk usage as much as possible.
3. The insertion or retrieval efficiency shall not impact the scan performance. In other words, we expect that insertion and retrieval operations to be faster than scanning files.
4. This feature must support every platform that FIM already supports.

### Tests

1. Unit tests to cover all new code
2. Integration tests to cover all new code (File change must end into local DB)

### PoC metrics gathering

All metrics must be gathered in a controlled environment: AWS t2.xlarge.

- How much disk space consume [1,1k,100k,500k,1M] file(s) scan
- Disk usage (bandwidth) to complete and save one scan [1,1k,100k,500k,1M]
- Disk usage (bandwidth) to read and sync (integrity) the full DB [1,1k,100k,500k,1M]
- CPU usage to complete and save one scan [1,1k,100k,500k,1M]
- CPU usage to read and sync (integrity) the full DB [1,1k,100k,500k,1M]
- Files per second (read) cap ratio within an AWS-EBS disk
- Files per second (write) cap ratio within an AWS-EBS disk
- Network usage (bandwidth) to complete and save one scan [1,1k,100k,500k,1M]
- Network usage (bandwidth) to read and sync (integrity) the full DB [1,1k,100k,500k,1M]
- Sync spent time [1,1k,100k,500k,1M]

**Comment by 0xN3utr0n** [comment]
### Update 1: fim_db integration into FIM
The sqlite implementation has been successfully completed and what's only left are the following goals:

- [ ] Replace `rbtree` functions for the new sqlite ones.
- [ ] Replace` hash_table` operations for the sqlite equivalents.
- [ ] Write new Unit and integration tests and repair the older ones.
- [ ] Lastly, run a few performance tests to verify the improvements over the `rbtree` implementation.
