### ISSUE TITLE
Develop clusterd agent key polling 

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#4392]
## Description

This is related to issue #4387.

This issue is about integrating the agent key polling feature in `wazuh-clusterd` so it could work also in agents reporting a worker node. As explained in #4387, the external script in charge of getting valid keys is running only in the master node, so we need to distribute the request from workers to master. As a result, the client.keys in the master node should be updated and synchronized back to the workers via Integrity thread.

## Design

There are two communication points with other Wazuh daemons that need to be developed:

- ### Request from `remoted` to trigger the key polling process
Each worker node is running a `LocalServer` inside the `wazuh-clusterd` process. This server is intended to answer internal cluster requests such an API request being forwarded to the node that has some specific data. It listens to a unix socket placed in `/var/ossec/queue/cluster/c-internal.sock`. The binary structure of messages sent through sockets is the following one:
  - A header with three fields:
    - Counter: big endian unsigned int (4 bytes)
    - Size of the payload: big endian unsigned int (4 bytes)
    - Command: 12 bytes. It is made up of a command name, a blank space and as much '-' character as needed to complete the 12 bytes in total. Example: 'control_res ', 'short ------'
  - Payload

According to this format, we will enable a new message type with command `run_keypoll` to trigger the agent key polling module in the master node. An example of this message could be: `\x00\x00\x00\x03\x00\x00\x00\x15run_keypoll {"message": "id:001"}`. 

In order to receive and process this message, a new abstract method `run_agent_key_polling` must be declared in the `LocalServerHandler` class. Furthermore, the method `process_request` must include a new case to process the `run_keypoll` command. A full example of the pattern to be applied here is the method `get_nodes` which is implemented differently in `LocalServerHandlerWorker` and `LocalServerHandlerMaster` classes.

- ### Request from `clusterd` to `modulesd`

A new method must be implemented in `AbstractServer` class in `server.py`. It will be in charge of writing the message field in the previous step into the socket `/var/ossec/queue/ossec/krequest`. It must control any errors in case the socket is not available.

## Testing

This implementation should be tested at unit level at least using mocks to ensure error and response handling.

## Tasks
- [ ] Accept message from `remoted` to trigger the key polling process
- [ ] Send request from `clusterd` to `modulesd`
- [ ] Write unit tests and documentation
- [ ] Test in a real environment with at least one master and two workers.
- [ ] Write a small script to stress the cluster socket and run the agent key polling intensively. Check that cluster and distributed API does not collapse.

**Comment by JcabreraC** [comment]
When trying to use the `c-internal.sock` socket, it returns the `permission denied` error.

#ls -l /var/ossec/queue/cluster/
```
srwxr-xr-x 1 ossec ossec    0 Jan 16 14:17 c-internal.sock
```
Socket permissions are 755.

If we check the permissions of the other sockets:
```
srw-rw---- 1 ossec  ossec 0 Jan 16 14:17 analysis
srw-rw---- 1 root   ossec 0 Jan 16 09:29 auth
srw-rw---- 1 root   ossec 0 Jan 16 14:17 com
srw-rw---- 1 root   ossec 0 Jan 16 14:17 control
srw-rw---- 1 root   ossec 0 Jan 16 14:17 download
srw-rw---- 1 root   ossec 0 Jan 16 14:17 krequest
srw-rw---- 1 root   ossec 0 Jan 16 14:17 logcollector
srw-rw---- 1 ossec  ossec 0 Jan 16 14:17 monitor
srw-rw---- 1 ossec  ossec 0 Jan 16 14:17 queue
srw-rw---- 1 ossecr ossec 0 Jan 16 14:17 request
srw-rw---- 1 root   ossec 0 Jan 16 14:17 syscheck
srw-rw---- 1 root   ossec 0 Jan 16 14:17 wmodules
```

The sockets permissions are 660.

Even if we change the permissions of the socket with "chmod 660 /var/ossec/queue/cluster/c-internal.sock", every time the manager starts, he puts back to 660 the permissions.

**Comment by davidjiglesias** [comment]
Fixed socket permissions so they are properly set to 660. Also fixed `Send request from clusterd to modulesd` so it connects to the socket using UDP.

Added 2 exceptions to error log for the cluster:
```
2020/01/20 08:19:40 wazuh-clusterd: ERROR: [Worker worker1] [Main] Error processing request 'b'run_keypoll'': Error 3025 - Permission denied, ensure krequest socket has right permissions
2020/01/20 08:20:24 wazuh-clusterd: ERROR: [Worker worker1] [Main] Error processing request 'b'run_keypoll'': Error 3024 - krequest socket is not present, ensure agent-key-polling wodle is running in the master node```
