### ISSUE TITLE
FIM's database implementation using sqlite3

### ISSUE THREAD

**Issue by 0xN3utr0n** [wazuh/wazuh#4417]
|Wazuh version|Component|Install type|Platform|Branch
|---|---|---|---|---|
| 3119-fim-rework | Syscheck | Agent | ALL | [3319-fim-rework-sqlite3](https://github.com/wazuh/wazuh/tree/3319-fim-rework-sqlite)

**Problem**
The rework of FIM uses a **red-black tree** with the purpuse of storing the information of all scanned files. Said implementation consumes too much memory on certain escenarios; therefore, an alternative one which wastes less resources is required.

**Proposed solution**
A simple sqlite3 database stored on disc can be used instead of the **RB Tree**. For that goal, we'll use as base [this PoC](https://github.com/albertomn86/FIM-DB-POC).

**Todo**

- [ ] Replace all the RB Tree references with the sqlite's ones.

- [ ] Check there aren't race conditions nor data races.

- [ ] Test it works correctly in all modes (realtime, whodata and scheduled).

- [ ] Check the new implementation is indeed more memory efficient.
