### ISSUE TITLE
Remoted option to switch agent key request

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#4442]
When an agent fails to connect due to missing or invalid key, it tries to request a key to the Agent Key Polling module, if it's running (#1859).

However, this does not work in a cluster environment.

## Goal

Meet steps 1 and 2 of #4387.

1. Implement new options in `<remote>`.
2. Let Remoted connect either to the _agent key polling_ module, or Clusterd.

### New configuration

```xml
<ossec_conf>
  <remote>
    <connection>secure</connection>
    <key_polling enabled="yes">
      <mode>local</mode>
    </key_polling>
  </remote>
</ossec_conf>
```

|Option|Range|Default|Description|
|---|---|---|---|
|`enabled`|`yes` or `no`|`yes`|Enable or disable key query.|
|`mode`|`local` or `master`|`local`|Select the agent polling target: locally or cluster.|

## Subtasks

- [x] Implement the option parser.
- [x] Develop a key polling selector.
- [x] Unit test for newly implemented functions.
- [x] Get metrics about request throughput.
- [x] Documentation.

**Comment by chemamartinez** [comment]
This issue is outdated so I am closing it in favor of https://github.com/wazuh/wazuh/issues/9092.

Best regards!
