### ISSUE TITLE
Review configuration module

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#4478]
## Description

Check that every configuration setting in `api.yml` is applied at runtime. Fix those not working.

## Tasks
- [x] Check `host`
- [x] Check `port`
- [x] Delete `basic_auth`
- [x] Check `behind_proxy_server`
- [x] Check `rbac.mode`
- [x] Check `https`
- [x] Check logs
- [x] Check `cors`
- [x] Check `cache`. Delete `debug`
- [x] Check `use_only_authd`
- [x] Check `drop_privileges`
- [x] Check `experimental_features`
- [x] Add `auth_token_exp_timeout` option to set the time in seconds a JWT will expire.
- [ ] Write integration tests to check configuration

**Comment by Selutario** [comment]
Hello team,

I just want to note that I checked `use_only_authd` even though it is not working on the main branch `dev-flask-poc`. The reason is that I already fixed it (and tested it) in this PR https://github.com/wazuh/wazuh/pull/4721, but it won't work until it is merged. 

Kind regards,
Jose Luis.
