### ISSUE TITLE
Remove option -D in Agentd

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#4508]
|Branch|Component|Install type|
|---|---|---|
| 3319-fim-rework | Agentd | Agent |

PR #4241 removed `chroot` jailing from Agentd. In addition, #3319 will remove the explicit agent's configuration integrity check from Agentd. Due to these two things, option `-D` (select the _chroot_ directory) will not apply anymore.

## Subtasks

- [x] Remove variable `dir` in Agentd's `main()` and `AgentdStart()`.
- [x] Replace the option `-D` feature with a message printing that the option is deprecated.
- [x] Mark this option as deprecated in the documentation.

## Acceptance criteria

Since option `-D` makes nothing in Agentd, we should only test:

- `ossec-agentd -D X` does not make Agentd fail. Instead, it should print a warning.
