### ISSUE TITLE
Slow down reporting throughput in FIM to prevent overflow

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#4622]
The reporting throughput proposed for FIM v3.12 is:

```xml
<syscheck>
  <max_eps>200</max_eps>
</syscheck>
```

This value is twice the current throughput (v3.11). On the other hand, the new synchronization protocol includes heavy queries which should have a low priority since it does not affect alert generation.

We need:

1. Decrease the event reporting to 100 EPS.
2. Decrease the inventory synchronization message throughput to 10 EPS.

## New configuration

```xml
<syscheck>
  <max_eps>100</max_eps>
  <synchronization>
    <max_eps>10</max_eps>
  </synchronization>
</syscheck>
```

### New options

|Option|Description|Range|Default|
|---|---|---|---|
|**inventory.max_eps**|Throughput limit for synchronization messges|0 .. 1000000|10|

## Subtasks

- [X] Add option to configuration parser.
- [X] Add the option value to the remote configuration generator.
- [X] Allow setting `max_eps` to 0, meaning unlimited throughput.
- [X] Set the default value for `max_eps` to 100.
- [X] Update unit tests.
- [X] Update documentation.
