### ISSUE TITLE
API 4.0 - Standardize endpoints output

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#4871]
Hello team,

Currently we are working on the implementation of a new API 4.0. In this new API we have restructured the output of almost all endpoints. In most of them we have applied a basic general schema:
```bash
{
  "data": {
    "affected_items": [
      {
        ...
      },
      {
        ...
      },
      ...
    ],
    "failed_items": [],
    "total_affected_items": X,
    "total_failed_items": Y
  },
  "message": "Message"
}
```

However, several endpoints do not follow this format. Two cases can be distinguished between these. On the one hand we have endpoints where this format does not make sense, for example GET /groups/{group_id}/files/{file_name}/xml. These will still keep the original format, without following the general schema. On the other hand, there are endpoints to which the standard format can be applied, in order to homogenize the API outputs. This way, a standard output is achieved that is easy to analyze and automatically extract information from it.

This is the list of endpoints that would be affected by this change:
- [x] GET /agents/summary/os
- [x] GET ​/groups​/{group_id}​/files
- [x] GET /agents/stats/distinct (SPEC example)
- [x] GET /cluster/nodes (SPEC example)
- [x] GET /cluster/{node_id}/logs (SPEC example)
- [x] GET /decoders (SPEC example)
- [x] GET /decoders/files (SPEC example)
- [x] GET /decoders/parents (SPEC example)
- [x] GET ​/manager​/logs (SPEC example)
- [x] GET /experimental/syscollector/netproto (SPEC example)
- [x] GET /experimental/syscollector/os (SPEC example)
- [x] GET /experimental/syscollector/packages (SPEC example)
- [x] GET /experimental/syscollector/ports (SPEC example)
- [x] GET /experimental/syscollector/processes (SPEC example)
- [x] GET /syscollector/{agent_id}/netiface (SPEC example)
- [x] GET /syscollector/{agent_id}/netproto (SPEC example)
- [x] GET /syscollector/{agent_id}/os (SPEC example)
- [x] GET /syscollector/{agent_id}/packages (SPEC example)
- [x] GET /syscollector/{agent_id}/ports (SPEC example)
- [x] GET /syscollector/{agent_id}/processes (SPEC example)
- [x] GET /rootcheck (SPEC example) [NOT IMPLEMENTED YET]
- [x] GET /rootcheck/{agent_id}/pci (SPEC example) [NOT IMPLEMENTED YET]
- [x] GET /rootcheck/{agent_id}/cis (SPEC example) [NOT IMPLEMENTED YET]
* The current development branch https://github.com/wazuh/wazuh/tree/dev-aiohttp-poc has been taken as a reference

It is possible that more endpoints can be added to this list, if necessary and discussed in advance. Suggestions are welcome

### ToDo list
- [x] Change SPEC
- [x] Update API's controllers
- [x] Update Framework's modules
- [x] Update unittests
- [x] Update integrated tests

Best regards,
Adrián Peña

**Comment by AdriiiPRodri** [comment]
## Status update

### GET /agents/summary/os - New output
```json
{
  "data": {
    "affected_items": [
      "ubuntu"
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Showing the operative system of all specified agents"
}
```

### GET ​/groups​/{group_id}​/files - New output
```json
{
  "data": {
    "affected_items": [
      {
        "filename": "agent.conf",
        "hash": "ab73af41699f13fdd81903b5f23d8d00"
      },
      {
        "filename": "ar.conf",
        "hash": "76d8be9b97d8eae4c239e530ee7e71c8"
      },
      {
        "filename": "merged.mg",
        "hash": "f5e0305e248bd00e05445f329bd1dd5e"
      }
    ],
    "total_affected_items": 3,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected groups files are shown"
}
```
