### ISSUE TITLE
Add TSC requirement to rules endpoints in API 4.0

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#4892]
## Description

`SOC/TSC` requirement has been recently added to Wazuh rules requirement specifications. We should adapt new API 4.0 for these changes.

## Related

- [API](https://github.com/wazuh/wazuh-api/commit/719563a6e18581a2c062ba0f6a950730ac74222d)
- [Ruleset](https://github.com/wazuh/wazuh-ruleset/pull/613)
- [Framework](https://github.com/wazuh/wazuh/pull/4882) 

## Tasks

- [x] Changes in `spec.yaml` to endpoints `GET /rules/requirement/{requirement}` and `tsc` filter for `GET /rules`
- [x] Rules controllers changes
- [x] Framework changes in `rules.py` and/or `core/rules.py`
- [x] Add/update API integration tests for `tsc` requirement (standard and rbac black & white)
- [x] Add/update unit tests for `rules.py` and `core/rules.py`
