### ISSUE TITLE
Extend agent service configuration to support enrollment

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#4899]
The `<client>` configuration block shall include all `agent-auth`'s parameters in a new block `<enrollment>`.

## New options

```xml
<client>
  <auto_enrollment>
    <enabled>
    <manager_address>
    <groups>
    <agent_address>
    <ssl_cipher>
    <server_ca_path>
    <agent_certificate_path>
    <agent_key_path>
    <authorization_pass>
    <auto_method>
  </auto_enrollment>
</client>
```

## Subtasks

- [x] Design a data structure to support these options.
- [x] Implement the XML parser for this configuration.
- [x] Extend the configuration JSON reporter.

**Comment by nicolaspapp** [comment]
## New configurations

### Autoenrollment

|Option|Values|Required|Default Value|Description|
|---|---|---|---|--|
|`enabled`|`yes` or `no`|`yes`|-|Enables/Disables agent auto-enrollment|
|`manager_address`| `string` - Should be valid IP/Hostname |`yes`|-|Hostname or IP of the manager where the agent will be enrolled|
|`port`| `0`...`65535`|`no`|1515|Manager port|
|`agent_name`| `string` - Registration name for the agent|`no`| Hostname of the machine | Agent name that will be used for enrollment|
|`groups`| `string` - Name of one or many valid groups |`no`| NULL | Agent name that will be used for enrollment|
|`agent_address`| `string` - Valid IP | `no` | `src` | Force IP adress from agent. If this is not set manager will extract source IP from enrollment message |
|`ssl_cipher`|`valid ssl ciphers`|`no`| DEFAULT_CIPHERS | Override SSL used ciphers |
|`server_ca_path`| Path to a valid CA certificate | `no` | NULL | Used for manager verification. If no CA certificate is set server will not be verified |
|`agent_certificate_path`| Path to a valid agent certificate file | `no` | NULL | Required when agent verification is enabled in manager | 
|`agent_key_path`| Path to a valid agent key file | `no` |  NULL | Required when agent verification is enabled in manager |
|`authorization_pass`| Password string | `no` | NULL | Required when enrollment is using password verification |
|`auto_method`| `yes`, `no` | `no` | `no` | `no` for TLS v1.2 only, `yes` for Auto negotiate the most secure common SSL/TLS method with the manager. |
