### ISSUE TITLE
Wrap agent-auth tool capabilities into a shared library

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#4900]
Since the Agent service will auto-enroll with the manager, both the `agent-auth` tool and the agent service will share the key request code. We need to encapsulate this code into a library.

## Subtasks

- [x] Design the library interface (headers).
- [x] Port the `agent-auth` tool code into the library.
- [x] Document the library with Doxygen.
- [x] Make `agent-auth` use the library to request a key to the manager. It shall keep the same functionality.
- [x] Add unit tests for the newly implemented functions.
