### ISSUE TITLE
4.0 - Testing environments optimization

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#4955]
## Description

Currently we have multiple testing environments to be able to test every change in the API code and the Framework. This variety of environments makes the task of running integration tests and keeping them up to date and running cumbersome.

Therefore, the goal of this issue is to improve the testing infrastructure for our integration tests.

## Design

On the one hand, the first idea of improvement is to replace all bash files of permissions configuration by SQL schemas that replace the RBAC database. This way we can eliminate the testing code implemented in the RBAC decorator.

On the other hand, we can optimize the number of images created for our tests by re-implementing the inheritance system and dividing the images into different Dockerfiles which will inherit from a parent Dockerfile.

Finally, we will consider the possibility of replacing the current docker-compose-based system with an Ansible-based system. This change can benefit us in maintaining the code and managing the different images created for each test.

## Tasks

To achieve this goal we must undertake the following tasks
- [x] Modify the current permissions injection method.
- [x] Optimize docker images.
- [x] Consider using Ansible instead of the current docker-compose.

Best regards,
Adrián Peña

**Comment by AdriiiPRodri** [comment]
# Status update

We have improved the implementation of the environment system for the integrated tests of the API 4.0. Now each test builds its own environment **without** the necessity of having a specific function in the **conftest.py**. This reduces the complexity of the code. 

On the other hand we have optimized the time it takes for each test to run (**about 50%**).  Also, we have eliminated the marks of each test, now the type of test will be automatically detected according to the **name of the file**.

Finally, we have improved the RBAC permissions system, now the permissions will be defined in **YAML** files that will be loaded at the beginning of each test.

Right now we are updating all the tests to this new system.

**Comment by AdriiiPRodri** [comment]
## Status update

In this list we will list the tests that are already adapted to the new environment based testing system.

### Integrated tests
- [x] test_active-response_endpoints.tavern.yaml
- [x] test_agents_DELETE_endpoints.tavern.yaml
- [x] test_agents_GET_endpoints.tavern.yaml
- [x] test_agents_POST_endpoints.tavern.yaml
- [x] test_agents_PUT_endpoints.tavern.yaml
- [ ] test_ciscat_endpoints.tavern.yaml
- [ ] test_cluster_endpoints.tavern.yaml
- [ ] test_decoders_endpoints.tavern.yaml
- [ ] test_default_endpoints.tavern.yaml
- [ ] test_experimental_endpoints.tavern.yaml
- [ ] test_lists_endpoints.tavern.yaml
- [ ] test_manager_endpoints.tavern.yaml
- [x] test_overview_endpoints.tavern.yaml
- [x] test_rbac_black_active-response_endpoints.tavern.yaml
- [x] test_rbac_black_agents_endpoints.tavern.yaml
- [x] test_rbac_black_ciscat_endpoints.tavern.yaml
- [ ] test_rbac_black_cluster_endpoints.tavern.yaml
- [ ] test_rbac_black_decoders_endpoints.tavern.yaml
- [ ] test_rbac_black_experimental_endpoints.tavern.yaml
- [ ] test_rbac_black_lists_endpoints.tavern.yaml
- [ ] test_rbac_black_manager_endpoints.tavern.yaml
- [x] test_rbac_black_overview_endpoints.tavern.yaml
- [x] test_rbac_black_rules_endpoints.tavern.yaml
- [x] test_rbac_black_sca_endpoints.tavern.yaml
- [x] test_rbac_black_security_endpoints.tavern.yaml
- [x] test_rbac_black_syscheck_endpoints.tavern.yaml
- [x] test_rbac_black_syscollector_endpoints.tavern.yaml
- [x] test_rbac_white_active-response_endpoints.tavern.yaml
- [x] test_rbac_white_agents_endpoints.tavern.yaml
- [ ] test_rbac_white_ciscat_endpoints.tavern.yaml
- [ ] test_rbac_white_cluster_endpoints.tavern.yaml
- [ ] test_rbac_white_decoders_endpoints.tavern.yaml
- [ ] test_rbac_white_experimental_endpoints.tavern.yaml
- [ ] test_rbac_white_lists_endpoints.tavern.yaml
- [ ] test_rbac_white_manager_endpoints.tavern.yaml
- [x] test_rbac_white_overview_endpoints.tavern.yaml
- [x] test_rbac_white_rules_endpoints.tavern.yaml
- [x] test_rbac_white_sca_endpoints.tavern.yaml
- [x] test_rbac_white_security_endpoints.tavern.yaml
- [x] test_rbac_white_syscheck_endpoints.tavern.yaml
- [x] test_rbac_white_syscollector_endpoints.tavern.yaml
- [x] test_rules_endpoints.tavern.yaml
- [x] test_sca_endpoints.tavern.yaml
- [x] test_security_DELETE_endpoints.tavern.yaml
- [x] test_security_GET_endpoints.tavern.yaml
- [x] test_security_POST_endpoints.tavern.yaml
- [x] test_security_PUT_endpoints.tavern.yaml
- [x] test_syscheck_endpoints.tavern.yaml
- [x] test_syscollector_endpoints.tavern.yaml

**Comment by AdriiiPRodri** [comment]
## Guide for new environments system
In this guide we will describe the most important changes for the maintenance of the API 4.0 integration tests.
- The Dockerfiles have been redesigned and now they only have the logic to mount the base images, for both managers and agents nodes. This means an improvement in the maintenance. It is no longer necessary to modify them when adding or removing integration tests for the API 4.0.
- The same goes for the conftest.py file. There is no longer any need to add or remove functions from it. All the specific functions of the tests have been removed. All that static logic becomes dynamic in this new version. It uses the name of the test files. Basing on this name, it gets the module we are going to test and if RBAC is going to be used and in which mode. Therefore, when adding new tests, we will need to follow the nomenclature of the existing ones.
- All the logic of configuration of the environments goes to the entrypoints now. We have added several functions that will configure the environments based on its files. All the tests that require special configuration files will have a folder whose name will be the one of the module to test. Inside this one, they will have an agent or manager folder (or both), depending on the type of node the files will be loaded to.
- Within these folders are located all the files we want to run: bash files, python scripts and SQL files are accepted.
- As for the healthchecks, these should be located in a folder called healthcheck and within this its corresponding type of node folder. Agent or manager depending on where we want to run the healthcheck.
- Now the RBAC permissions are defined in YAML files. We have deleted all the testing code as it must not be in production. With this, we leave the RBAC code ready for production.

**Comment by AdriiiPRodri** [comment]
## Status update

RBAC permissions are now defined as follows:

```yaml
---
- actions:
  - agent:read
  - agent:delete
  - agent:restart
  - agent:upgrade
  - agent:modify_group
  resources:
  - agent:id:*
  effect: deny

- actions:
  - agent:read
  resources:
  - agent:id:001
  - agent:id:003
  - agent:id:005
  - agent:id:007
  - agent:id:009
  - agent:id:011
  effect: allow

- actions:
  - agent:delete
  resources:
  - agent:id:000
  - agent:id:002
  - agent:id:004
  - agent:id:006
  - agent:id:008
  - agent:id:010
  - agent:id:012
  effect: allow
```

Each element is now a policy, and all policies defined in the test RBAC files will be related to the new user 'testing' of the API. This user only exists in the tests and is the one we will use if we need to make any requests to the environment.
