### ISSUE TITLE
Move auth_token_exp_timeout out of RBAC configuration.

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#5044]
## Description

Currently, the auth_token_exp_timeout configuration option is located inside the RBAC section in api.yaml, as you can see here:

```YAML
# RBAC configuration
 rbac:
   mode: white
   auth_token_exp_timeout: 36000
```
However, the `jwt` token does not belong to RBAC, so it is better to move it out like any other configuration.

```YAML
# JWT token expiration time (in seconds)
 auth_token_exp_timeout: 36000

# RBAC configuration
 rbac:
   mode: white
```
It may be used in more places than mentioned in the task list. Make sure to change it everywhere.

## Tasks

- [x] api.yaml
- [x] api/api/configuration.py
- [x] api/api/authentication.py
- [x] api/api/spec/spec.yaml
- [x] api/scripts/migration.py
- [x] tavern tests
- [x] API configuration integration tests inside Wazuh-QA ([685](https://github.com/wazuh/wazuh-qa/pull/685))

Kind regards,
Selu.
