### ISSUE TITLE
Add support for AWS Cloudwatch Logs in AWS module

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#5187]
|Branch|
|---|
| [dev-5187-cloudwatch-logs](https://github.com/wazuh/wazuh/tree/dev-5187-cloudwatch-logs) |

# Description
`Cloudwatch Logs` is an AWS service used to store and access logs files from Amazon instances (EC2 and Fargate), AWS CloudTrail, Route 53, and other, regardless of their source, as a single and consistent flow of events ordered by time. 

`AWS Cloudwatch Logs` are stored using `log groups` and `log streams`. Our AWS module needs to be able to access those log groups, extract their contents and finally send them to `analysd`.

# Design
We need to add a new `AWSCloudwatchLogs` class which inherits from `AWSService` in the `AWS-S3.py` module. This will work in a similar way to the current `AWSInspector`.

The new class must be able to connect to AWS Cloudwatch Logs, get the required `log group` provided by parameter and fetch all logs for each `log stream` in that `log group`. Once we have collected the logs the new Class must be able to send them to the `Analysisd` daemon so they will be analyzed and alerts will be raised if applicable.

To avoid getting the same logs every time a fetch is performed we will used the `aws_service.db` database to store the token received from the boto3 client the last time a fetch was performed.

Finally, the AWS parser must be also updated to allow the usage of the new tags for this service.

# Testing

A `TaskDefinition` with an Apache httpd image will be created and launched using Fargate. This task definition must forward its logs to a Cloudwatch log group. Once we have those logs we will retreive them using the new module and ensure everything is working as expected. 

# Tasks
- [x] Create `AWSCloudwatchLogs` that extends from `AWSService` in `AWS-S3.py` module.
- [x] Define which tags will be available for the new Service in the `ossec.conf` file.
- [x] Update the AWS parser to allow the usage of those new tags.
- [x] Test in a real environment with data from an AWS account.
- [x] Update Wazuh Documentation to add relevant information about usage and parameters. Update existing pages and tables to add the new supported AWS Service.

**Comment by CarlosRS9** [comment]
# Status Update

- The `AWSCloudwatchLogs` class was created. The functions to obtain the log groups, log streams and the logs itselfs are finished and they are working fine.
- All the logic related to the DB (saving and retreiving the token) its done and tested. 
- All the AWS Console related steps (TaskDefinition creation, execution, etc) has been done and the logs are available for testing.
- The function for sending the logs to `analysisd` is implemented but need some tweaks to fix a known bug. I'm currently working on this.
- I started to apply some of the changes needed to read and parse the tags for this new service in the ossec.conf file. Need further development.

**Comment by CarlosRS9** [comment]
# Status Update

* The bug related to sending logs to `analisysd` has been fixed. Several test were performed to ensure it works properly now.

* The definition of the parameters that our CloudwatchLogs service will have available is finished. Here is the list of the final parameters:
```
<wodle name="aws-s3"> 
  <disabled> no </disabled> 
  <interval> 5m </interval> 
  <run_on_start> yes </run_on_start> 
  <service type="cloudwatchlogs"> 
    <aws_account_id> account </aws_account_id> 
    <aws_account_alias> alias </aws_account_alias> 
    <access_key> access </access_key> 
    <secret_key> secret </secret_key> 
    <aws_profile> profile </aws_profile> 
    <iam_role_arn> role </iam_role_arn> 
    <aws_log_groups> log_group1,log_group2 </aws_log_groups> 
    <only_logs_after> only_logs_after </only_logs_after> 
    <regions> region1,region2 </regions> 
    <remove_log_streams> no </remove_log_streams> 
   </service> 
 </wodle> 
```

* The parsing logic in Core has been updated to recognize those new parameters available for the service. The parameters can now be specified in the `ossec.conf` file.

* The function for removing log streams from a log group is the user wants was added. A few improvements over `AWSCloudwatchLogs` have been applied, too.

* The following parameters have been tested and they are working fine: `aws_account_id`, `aws_account_alias`, `access_key`, `secret_key`, `aws_profile`, `aws_log_groups`, `regions` and `remove_log_streams`.


# Pending Tasks

* Finish the logic for the `only_logs_after` parameter and test it.
* Test the `iam_role_arn` parameter.
* Perform additional tests to ensure everything is working as expected.
* Create the documentation page.

**Comment by CarlosRS9** [comment]
# Status Update

* The development is finished.
* The rework to avoid duplicate events has been completed. Several manual tests were performed using real data to ensure everything behaves as expected.
* Minor modifications were applied, too.

**Comment by CarlosRS9** [comment]
## Status Update

After some testing with Fargate and EC2 instances execution we saw in both cases the logstream name format is the following one:

```
TaskDefinitionName/ContainerName/TaskID
```

We are going to work in a parser to add this information to the event json and this way be able to identify the source of each raised alert.

**Comment by CarlosRS9** [comment]
# Status Update

We have introduced some changes to add the `TaskDefinitionName`, `ContainerName` and `TaskID` to the CloudWatchLogs events sent to `Analysisd`. Previously, the events only contained their logs. For example:
```
[Wed Jun 10 07:39:29.284097 2020] [mpm_event:notice] [pid 1:tid 139761339495552] AH00492: caught SIGWINCH, shutting down gracefully
```

The new message format with the additional fields is:
```
{
    'log': '[Wed Jun 10 07:39:29.284097 2020] [mpm_event:notice] [pid 1:tid 139761339495552] AH00492: caught SIGWINCH, shutting down gracefully',
    'task_definition_name': 'awslogs-example',
    'container_name': 'apache',
    'task_id': 'e20a0365-1c31-45eb-864e-7c586a344901'
}
```

We need to study the changes needed for the pre-decoding analysisd step to be able to understand and expect those new fields. If we don't modify it the events won't be decoded as they should and they won't match any of the required rules.
 
Here is an example of `ossec-logtest` using the old message format:
```
**Phase 1: Completed pre-decoding.
       full event: '[Wed Jun 10 07:39:15.069382 2020] [core:notice] [pid 1:tid 139761339495552] AH00094: Command line: 'httpd -D FOREGROUND''
       timestamp: '(null)'
       hostname: 'wazuh-manager'
       program_name: '(null)'
       log: '[Wed Jun 10 07:39:15.069382 2020] [core:notice] [pid 1:tid 139761339495552] AH00094: Command line: 'httpd -D FOREGROUND''

**Phase 2: Completed decoding.
       decoder: 'apache-errorlog'

**Phase 3: Completed filtering (rules).
       Rule id: '30303'
       Level: '2'
       Description: 'Apache notice messages grouped.'
```

The message was correctly decoded and it matched the expected rule. However, with the new format the predecoder does not extract the new fields and the decoding phase will fail:
```
**Phase 1: Completed pre-decoding.
       full event: '{'log': '[Wed Jun 10 07:39:29.284097 2020] [mpm_event:notice] [pid 1:tid 139761339495552] AH00492: caught SIGWINCH, shutting down gracefully', 'task_definition_name': 'awslogs-example', 'container_name': 'apache', 'task_id': 'e20a0365-1c31-45eb-864e-7c586a344901'}'
       timestamp: '(null)'
       hostname: 'wazuh-manager'
       program_name: '(null)'
       log: '{'log': '[Wed Jun 10 07:39:29.284097 2020] [mpm_event:notice] [pid 1:tid 139761339495552] AH00492: caught SIGWINCH, shutting down gracefully', 'task_definition_name': 'awslogs-example', 'container_name': 'apache', 'task_id': 'e20a0365-1c31-45eb-864e-7c586a344901'}'

**Phase 2: Completed decoding.
       No decoder matched.
```

## Pending
Study the required changes to ensure pre-decoding phase allows and accept the new fields.

**Comment by CarlosRS9** [comment]
## Status Update

Development branch has changed from [dev-5187-cloudwatch-logs](https://github.com/wazuh/wazuh/tree/dev-5187-cloudwatch-logs) to [feature/5187-cloudwatchlogs](https://github.com/wazuh/wazuh/tree/feature/5187-cloudwatchlogs) as this development was designed for 3.13 but will finally be added in 4.0.

AWS CloudWatchLogs support will be added without the parser in charge of identifying the source of the events as that needs some additional changes related to Core Team. This will be added in a future issue.
