### ISSUE TITLE
Improve the default policies structure of RBAC

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#5224]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| WIP_4.0 | RBAC | Manager | Packages/Sources | x86_64 |

Hi team,

To make our RBAC easier to use, we added default roles and policies in our system. These policies are loaded into the database from a `.yaml` file. To reduce the complexity and size of this file we initially thought to create policies with multiple actions and as resources add a set of all the resources involved in those actions. The problem with this approach is that some of these combinations are not useful. Let's take an example:

The action agent:read has as possible resources agent:id and agent:group, on the other hand the action agent:create is of resourceless type (resource "\*:\*:\*") so if we add these two actions in a single policy the result would be the following:

```yaml
agent:read:
    agent:id:*: allow
    agent:group:*: allow
    *:*:*: allow
agent:create:
    agent:id:*: allow
    agent:group:*: allow
    *:*:*: allow
```

As we can see, we have obtained a result that is complicated to understand. For example, in the action agent:create the only resource that works with it is "\*:\*:\*", the other resources will be ignored.

We are going to modify the file that defines the default policies to make it more consistent. This will also help us to identify possible resources or forgotten actions. One of these forgotten actions is **syscheck:read**. To avoid these problems and be sure of our set of default policies, we are going to run the integration tests with the administrator user ('wazuh') which has several default policies, in white mode (all denied by default).

## ToDo
- [x] Redefine default policies to make them more consistent.
- [x] Group policies together as much as possible to avoid an overload of default policies.
- [ ] Run the integrated tests (without RBAC, changing the mode to white) to check the integrity of the default policies.

**Comment by AdriiiPRodri** [comment]
## Status update

### Security integrated tests without RBAC and white mode
```
adriiiprodri@wazuh python3 run_tests.py -rbac no -k security         
Collected tests [4]:
test_security_DELETE_endpoints.tavern.yaml, test_security_GET_endpoints.tavern.yaml, test_security_POST_endpoints.tavern.yaml, test_security_PUT_endpoints.tavern.yaml


test_security_DELETE_endpoints.tavern.yaml 
	 11 passed, 54 warnings

test_security_GET_endpoints.tavern.yaml 
	 13 passed, 84 warnings

test_security_POST_endpoints.tavern.yaml 
	 4 passed, 44 warnings

test_security_PUT_endpoints.tavern.yaml 
	 6 passed, 34 warnings
```

**Comment by AdriiiPRodri** [comment]
## Status update
### Security integrated tests with RBAC
```yaml
adriiiprodri@wazuh python3 run_tests.py -rbac yes -k security
Collected tests [2]:
test_rbac_black_security_endpoints.tavern.yaml, test_rbac_white_security_endpoints.tavern.yaml


test_rbac_black_security_endpoints.tavern.yaml 
	 18 passed, 77 warnings

test_rbac_white_security_endpoints.tavern.yaml 
	 19 passed, 81 warnings
```
