### ISSUE TITLE
Expose free method for deallocations managed by hosted process.

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#5293]
## Description

This aims to release allocations made by this shared library, This function ensures that the deallocation primitive is the correct one.

## Testing

This implementation should be tested at the unit and integration level to ensure error and response handling.
integration tests must be done with dbsync_test_tool

## Tasks
- [X] Expose an interface to deallocate results.
- [X] Add doxygen declaration in header.
- [X] Implement result deallocation method and unit tests for it
- [x] Add to dbsync_test_tool the capabilities to test it. (Not dbsync tool yet)
- [X] Run local Valgrind execution using this partial feature.
