### ISSUE TITLE
Change locking mechanism in handle lookup.

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#5294]
## Description

This aims to change the current implementation with plain mutex to shared_mutex, in order to allow the read lookup by several threads.

## Testing

This implementation should be tested at the unit and integration level to ensure error and response handling.
integration tests must be done with dbsync_test_tool

## Tasks
- [x] Update doxygen declaration in header.
- [x] Change implementation.
- [ ] Update/add unit tests for it.
- [ ] Add to dbsync_test_tool the capabilities to test it.
- [x] Run local Valgrind execution using this partial feature.
