### ISSUE TITLE
Change raw pointers to smart pointers + deleters

### ISSUE THREAD

**Issue by konangc87** [wazuh/wazuh#5303]
## Description

This aims to change the current implementation with raw pointers to smart pointers + deleters, in order ensure the correct managing of resources life cycles and be code style compliant.

## Testing

This implementation should be tested at the unit and integration level to ensure error and response handling.
integration tests must be done with dbsync_test_tool

## Tasks
- [x] Change implementation and unit tests for it
- [x] Add to dbsync_test_tool the capabilities to test it.(No dbsync tool yet.)
- [x] Run local Valgrind execution using this partial feature.
