### ISSUE TITLE
Move all the SQLite files to its own folder in dbsync/src

### ISSUE THREAD

**Issue by konangc87** [wazuh/wazuh#5327]
## Description

This aims to move all the the file containing sqlite implementation details to a new folder called sqlite, in order to separate abstract/factory files from implementation details/concrete classes.

## Testing

This implementation should be tested at the unit and integration level to ensure error and response handling.
integration tests must be done with dbsync_test_tool

## Tasks
- [ ] Move all the files.
- [ ] Fix CMake/Make files.
- [ ] Check compilation and tests.
