### ISSUE TITLE
CPPCHECK baseline issues

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#5475]
## Description

This aims to solve style and performance issues in the dbsync library baseline.

## DoD
0 Issues.

Current status:
![image (2)](https://user-images.githubusercontent.com/14300208/87470117-b228d780-c5f2-11ea-8a04-b04b880d18a3.png)

## Tasks
- [ ] Fix CPPCHECK issues.
- [ ] Run unit test and post results
- [ ] Run test tool and post results
- [ ] Run local Valgrind execution using this partial feature.
- [ ] PR
