### ISSUE TITLE
[WPK][API] Add new endpoints to upgrade and get upgrade results of multiple agents

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#5536]
Hello team,

This issue is based on https://github.com/wazuh/wazuh/issues/5387. 

## Description

With the refactor and changes to the upgrade process, the new Wazuh upgrade module allows to receive a petition to upgrade multiple agents at once. We should add new API endpoints to allow receiving a list of agents to ugprade, or all of them. We should  add the same endpoint with custom upgrade and upgrade results.

## Design

The endpoints should have the following structure:

Path: 

- `PUT /agents/upgrade`

Query parameters: 
- `pretty`
- `wait_for_complete`
- `list_agents`
- `wpk_repo`
- `upgrade_version`
- `use_http`
- `force`

Path: 

- `PUT /agents/upgrade_custom`

Query parameters: 
- `pretty`
- `wait_for_complete`
- `list_agents`
- `file_path`
- `installer`

Path: 

- `GET /agents/upgrade_result`

Query parameters: 
- `pretty`
- `wait_for_complete`
- `list_agents`

## Testing

We should add new endpoint test integration cases for the 3 new endpoints to:
-  [test_agents_PUT_endpoints.tavern.yaml](https://github.com/wazuh/wazuh/blob/develop/api/test/integration/test_agents_PUT_endpoints.tavern.yaml)
-  [test_rbac_black_agents_endpoints.tavern.yaml](https://github.com/wazuh/wazuh/blob/develop/api/test/integration/test_rbac_black_agents_endpoints.tavern.yaml)
- [test_rbac_white_agents_endpoints.tavern.yaml](https://github.com/wazuh/wazuh/blob/develop/api/test/integration/test_rbac_white_agents_endpoints.tavern.yaml)

## Tasks

- [x] Update spec.yaml
- [x] Update/Add agents controllers
- [x] Add and run new test integration cases
- [x] Update changes.md

**Comment by mcarmona99** [comment]
Functions put_upgrade_multiple_agents, put_upgrade_multiple_custom_agents and get_agent_upgrade_multiple added to the agent controller. Changed spec.yaml and updated changes.md with the new endpoints. Branch: feature/5536-upgrade-multiple-agents-endpoints
