### ISSUE TITLE
Improve monitoring of Windows registers

### ISSUE THREAD

**Issue by Molter73** [wazuh/wazuh#5576]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.0 | Wazuh FIM | Agent | Packages/Sources | Windows |

## Description

Monitoring of Windows registers is in need of some improvements. Each register is being treated as a file by FIM, which causes it to trigger alerts but prevents it from reporting detailed information on the event (was a value in the registry changed? Which entry and what is its new value? Was some entry deleted or added? etc.).

Since registers work in a manner similar to files and directories, we will need to find a proper way to store its values in a separate table inside the FIM database. A first approach adding a separate `win_reg_data` table is shown next:

![imagen](https://user-images.githubusercontent.com/20206636/88660213-9a635000-d0d6-11ea-9d84-6a60af479791.png)

- path: Holds the path relative to the configured entry.
- type: An integer describing the type of value contained in the register, as described [here](https://docs.microsoft.com/en-us/windows/win32/sysinfo/registry-value-types)
- value: The value held in the registry entry, converted into a string representing it.
- parent_id: An integer linking the current entry to its configured parent.

Having the data stored in this manner will allow us to sweep through the registry entries and `SELECT` the corresponding data for comparison by filtering with id and the remaining path. Additionally, a general checksum will be kept, this should save some space in the DB and processing time when scanning if no changes where made.

A way of integrating this new information into the alerts needs to be designed too, some things to take into account:
- Will multiple changes under the same configured registry be reported in the same alert or over multiple alerts?
- Does it make sense to use an existing field such as `content_changes` or will we use a new one?
- Do all types of registry entries make sense to be reported? (Specifically binary data)
- Do we need to limit how much information is sent in these alerts? Or should we use something similar to a diff with large enough entries? (Multi string entries could be quite large)

We should also look into using the information provided by the `Security` eventchannel on modified registries, specifically the events listed [here](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-registry) and integrate this information in, maybe as a `whodata` option for registries.

Last but not least, a way of disabling changes being reported must be put in place in the configuration, (maybe use an attribute like `report_changes` in files), and we need to determine if this will be on or off by default. It could also prove useful to add a global way to disable this new feature.

## Checks
- [x] Implement the new database schema and related operations in the code.
- [x] Modify the registry scan algorithm so it generates separate information for each value.
- [x] The content of each registry value changed is properly notified in alerts.
- [x] Adapt the synchronization mechanism.
- [x] Develop unit tests for the new functionalities.
- [x] Develop integration tests for the new functionalities.
- [x] Update documentation.

**Comment by Molter73** [comment]
We've decided to make some changes to the previous design, to begin with, we will have separate tables for files and registers, the final design looks like this:

![FIM registry2](https://user-images.githubusercontent.com/20206636/91716331-bce20080-eb8f-11ea-8a12-1a2927801704.png)
