### ISSUE TITLE
Set the default manager-agent connection protocol to TCP

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#5579]
When deploying a Wazuh environment, agents try to connect to the manager using UDP by default. We want to change this to TCP as it is more reliable than UDP.

## Subtasks

- [x] Replace the `<protocol>` option value to `tcp` in the `<client>` configuration template for UNIX.
- [x] Replace the `<protocol>` option value to `tcp` in the `<client>` configuration template for Windows.
- [x] Replace the `<protocol>` option value to `tcp` in the `<remote>` configuration template.
- [x] Set the default protocol option value to TCP in the ossec-agentd configuration parser.
- [x] Set the default protocol option value to TCP in the ossec-remoted configuration parser.
- [x] Check if we need to set this option default in the Windows installer.
- [x] Update the reference documentation of `<remote>`.
- [x] Update the reference documentation of `<client>`.

## Goal

1. Every agent installation method (including from sources) shall set the `<protocol>` to `tcp` in the configuration.
1. Every manager installation method (including from sources) shall set the `<protocol>` to `tcp` in the configuration.
2. The agent shall try to connect in TCP mode if the `<protocol>` option is not defined.
2. The manager shall listen to a TCP port if the `<protocol>` option is not defined.

**Comment by chemamartinez** [comment]
Done at #5696
