### ISSUE TITLE
Add restriction on endpoints with DELETE method

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#5583]
Hi team,

Currently, for the 4.0 version we decided that all API endpoints accessing resources in any way should have as input a list of specified resources. This way if we want to get all the agents in the system we just need to make a request to the endpoint without the **list_agents** argument. However, this behavior can be dangerous for endpoints whose method is **DELETE**:

```
curl -X DELETE "https://localhost:55040/v4/agents?older_than=1s" -H  "accept: application/json" -H  "Authorization: Bearer TOKEN"

{
  "data": {
    "affected_items": [
      "001",
      "002",
      "003",
      "004",
      "005",
      "006",
      "007",
      "008",
      "009",
      "010",
      "011",
      "012",
    ],
    "total_affected_items": 12,
    "total_failed_items": 0,
    "failed_items": [],
    "older_than": "1s"
  },
  "message": "All selected agents were deleted"
}
```

We are going to change that behavior so that in these cases, if nothing is specified, nothing is removed. If the user wants to remove all of the resources, they can specify the "**all**" keyword.

## ToDo

- [x] Change the behavior of DELETE /agents
- [x] Change the behavior of DELETE /agents/group
- [x] Change the behavior of DELETE /groups
- [x] Change the behavior of DELETE /experimental/syscheck
- [x] Change the behavior of DELETE /security/roles
- [x] Change the behavior of DELETE /security/policies
- [x] Change the behavior of DELETE /security/users
- [x] Change the behavior of DELETE /security/users/{user_id}/roles
- [x] Change the behavior of DELETE /security/roles/{role_id}/policies
- [x] Add/Update integrated tests

**Comment by AdriiiPRodri** [comment]
## Status update

Hi team,

These are the results of the updated integrated tests:

```
test_agents_DELETE_endpoints.tavern.yaml 
	 7 passed, 63 warnings

test_agents_GET_endpoints.tavern.yaml 
	 90 passed, 523 warnings

test_agents_POST_endpoints.tavern.yaml 
	 4 passed, 40 warnings

test_agents_PUT_endpoints.tavern.yaml 
	 9 passed, 71 warnings

test_rbac_black_agents_endpoints.tavern.yaml 
	 39 passed, 162 warnings

test_rbac_white_agents_endpoints.tavern.yaml 
	 39 passed, 169 warnings

test_experimental_endpoints.tavern.yaml 
	 11 passed, 47 warnings

test_rbac_black_experimental_endpoints.tavern.yaml 
	 11 passed, 47 warnings

test_rbac_white_experimental_endpoints.tavern.yaml 
	 11 passed, 47 warnings

test_security_DELETE_endpoints.tavern.yaml 
	 12 passed, 60 warnings

test_security_GET_endpoints.tavern.yaml 
	 14 passed, 87 warnings

test_security_POST_endpoints.tavern.yaml 
	 4 passed, 44 warnings

test_security_PUT_endpoints.tavern.yaml 
	 7 passed, 37 warnings

test_rbac_black_security_endpoints.tavern.yaml 
	 18 passed, 78 warnings

test_rbac_white_security_endpoints.tavern.yaml 
	 19 passed, 81 warnings
```
