### ISSUE TITLE
Let the auto-enrollment configuration block be <enrollment>

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#5631]
The auto-enrollment feature groups its options into the block `<auto_enrollment>`. We desire to rename it `<enrollment>`.

## Subtasks

- [x] Refactor the configuration parser.
- [x] Change the configuration JSON report function.
- [x] Modify the unit tests (if needed) (Not needed).
- [x] Adapt the integration tests.
- [x] Update the documentation.
