### ISSUE TITLE
Adapt framework to new WPK repository path changed in 4.x

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#5661]
Hello team,

The WPK package repository path is going to change starting with Wazuh major version 4. Until now, the wpk packages were located in path `packages.wazuh.com/wpk/`, but now, they will be insided a folder for that major version:  `packages.wazuh.com/4.x/wpk/`.

We should adapt our framework upgrade modules to load the wpk packages from one path or the other depending on the targeted upgrade version. We should also adapt and update related unit and API integration tests.

### Tasks:
- [x] Update agent.py framework SDK and core modules to support upgrading to 3.X or 4.X versions 
- [x] Update/add and run unit tests
- [x] Update/add and run API integration tests
