### ISSUE TITLE
Add new security endpoints to complete CRUD cycle for new API mapping rules

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#5691]
Hello team,

With the changes to the new API and the addition of RBAC, we added several endpoints that allow to Create, Modify or Delete security roles:

`POST /security/roles` -> Add a new role to the system
`DELETE /security/roles` -> Delete a list of roles or all roles in the system
`PUT  /security/roles/{role_id}` -> Modify a specified role

However, we have found it difficult to reliably modify the rules of a role using actual design. Therefore, we should add 5 new endpoints (CRUD cycle + relationship) to work with role_mapping rules in the new security section of the API.

`GET /security/mapping_rules` -> Get a list of mapping_rules from the system or all of them
`POST /security/mapping_rules` -> Add a new mapping_rule to the system
`DELETE /security/mapping_rules` -> Delete a list of mapping_rules from the system or all of them
`PUT /security/mapping_rules/{rule_id}` -> Modify a specified mapping rule
`POST /security/roles/{role_id}/mapping_rules` -> Add a relationship between one role and one or more mapping rules
`DELETE  /security/roles/{role_id}/mapping_rules` -> Delete the relationship between one role and one or more  mapping rules

We should also add new RBAC permissions to operate with the mapping rules resources.

### Tasks:

- [ ] Update spec.yaml with new endpoints and schemas
- [ ] Add new API controllers
- [ ] Add new mapping rule body validators
- [ ] Add new SDK functions
- [ ] Add necessary ORM functions to operate with database for mapping rules
- [ ] Adapt roles endpoints (no rule field)
- [ ] Modify default roles
- [ ] Add/Update and run API integration tests
- [ ] Add/Update unit tests for all affected modules
- [ ] Update RBAC catalog
- [ ] Update RBAC documentation
- [ ] Update changes.md

**Comment by vicferpoy** [comment]
# Status update
Development is not finished yet, but the ORM has been reworked and basic endpoints are working. A new resource has been added for every `security` action (`rule:id:*`). This is the structure of the RBAC database now:

## Roles table
```sql
1|administrator|2020-08-13 06:08:15.077746
2|readonly|2020-08-13 06:08:15.091380
3|users_admin|2020-08-13 06:08:15.107635
4|agents_readonly|2020-08-13 06:08:15.121522
5|agents_admin|2020-08-13 06:08:15.135141
6|cluster_readonly|2020-08-13 06:08:15.148416
7|cluster_admin|2020-08-13 06:08:15.171130
```

## Rules table
```sql
1|{"FIND": {"r'^auth[a-zA-Z]+$'": ["full_admin"]}}|2020-08-13 06:08:15.226012
2|{"FIND": {"r'^auth[a-zA-Z]+$'": ["readonly"]}}|2020-08-13 06:08:15.239419
3|{"FIND": {"r'^auth[a-zA-Z]+$'": ["users_admin"]}}|2020-08-13 06:08:15.250558
4|{"FIND": {"r'^auth[a-zA-Z]+$'": ["agents_readonly"]}}|2020-08-13 06:08:15.261934
5|{"FIND": {"r'^auth[a-zA-Z]+$'": ["agents_admin"]}}|2020-08-13 06:08:15.271044
6|{"FIND": {"r'^auth[a-zA-Z]+$'": ["cluster_readonly"]}}|2020-08-13 06:08:15.282594
7|{"FIND": {"r'^auth[a-zA-Z]+$'": ["cluster_admin"]}}|2020-08-13 06:08:15.301108
```

## Endpoints status

### GET /security/roles (limit=1)
```json
{
  "data": {
    "affected_items": [
      {
        "id": 1,
        "name": "administrator",
        "policies": [
          1,
          2,
          3,
          6,
          7,
          8,
          11,
          12,
          13,
          14,
          15,
          16,
          18,
          19,
          20,
          21,
          22,
          23
        ],
        "users": [
          1
        ],
        "rules": [
          1
        ]
      }
    ],
    "total_affected_items": 7,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All specified roles were shown"
}
```

### GET /security/rules (limit=1)
```json
{
  "data": {
    "affected_items": [
      {
        "id": 1,
        "rule": {
          "FIND": {
            "r'^auth[a-zA-Z]+$'": [
              "full_admin"
            ]
          }
        },
        "roles": [
          1
        ]
      }
    ],
    "total_affected_items": 7,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All specified rules were shown"
}
```

## Difficulties
- The ORM module has a lot of dependencies and I needed to rework it to introduce new classes that interact with the previous ones.

## Pending
- SDK functions to manage associations between rules and roles (DELETE and PUT)
- Unit and integration tests.
- Update documentation.

**Comment by vicferpoy** [comment]
# Status update
| Working branch |
|-|
| [develop-5691-mapping-rules](https://github.com/wazuh/wazuh/tree/develop-5691-mapping-rules) |

Development is finished. There are a few TODOs but it's only docstrings and response examples.

## RBAC tables

### New SQL schemas
```sql
CREATE TABLE roles (
	id INTEGER NOT NULL, 
	name VARCHAR(20), 
	created_at DATETIME, 
	PRIMARY KEY (id), 
	CONSTRAINT name_role UNIQUE (name)
);

CREATE TABLE rules (
	id INTEGER NOT NULL, 
	rule TEXT, 
	created_at DATETIME, 
	PRIMARY KEY (id), 
	CONSTRAINT rule_definition UNIQUE (rule)
);

CREATE TABLE roles_rules (
	id INTEGER NOT NULL, 
	role_id INTEGER, 
	rule_id INTEGER, 
	created_at DATETIME, 
	PRIMARY KEY (id), 
	CONSTRAINT role_rule UNIQUE (role_id, rule_id), 
	FOREIGN KEY(role_id) REFERENCES roles (id) ON DELETE CASCADE, 
	FOREIGN KEY(rule_id) REFERENCES rules (id) ON DELETE CASCADE
);


```

### Roles table
```sql
1|administrator|2020-08-13 12:21:35.887511
2|readonly|2020-08-13 12:21:35.900456
3|users_admin|2020-08-13 12:21:35.911619
4|agents_readonly|2020-08-13 12:21:35.922772
5|agents_admin|2020-08-13 12:21:35.933630
6|cluster_readonly|2020-08-13 12:21:35.943557
7|cluster_admin|2020-08-13 12:21:35.954887

```

### Rules table
```sql
1|{"FIND$": {"elastic": ["administrator"]}}|2020-08-13 12:21:35.982227
2|{"FIND$": {"admin": ["administrator"]}}|2020-08-13 12:21:35.998801

```

### Roles-Rules table
```sql
1|1|1|2020-08-13 12:21:35.557026
2|1|2|2020-08-13 12:21:35.557026

```

## Endpoints status

### GET /security/roles (limit=2)
```json
{
  "data": {
    "affected_items": [
      {
        "id": 1,
        "name": "administrator",
        "policies": [
          1,
          2,
          3,
          6,
          7,
          8,
          11,
          12,
          13,
          14,
          15,
          16,
          18,
          19,
          20,
          21,
          22,
          23
        ],
        "users": [
          1
        ],
        "rules": [
          1,
          2
        ]
      },
      {
        "id": 2,
        "name": "readonly",
        "policies": [
          4,
          5,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          19
        ],
        "users": [
          2
        ],
        "rules": []
      }
    ],
    "total_affected_items": 7,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All specified roles were shown"
}
```

### GET /security/rules
```json
{
  "data": {
    "affected_items": [
      {
        "id": 1,
        "rule": {
          "MATCH$": {
            "elastic": [
              "administrator"
            ]
          }
        },
        "roles": [
          1
        ]
      },
      {
        "id": 2,
        "rule": {
          "MATCH$": {
            "admin": [
              "administrator"
            ]
          }
        },
        "roles": [
          1
        ]
      }
    ],
    "total_affected_items": 2,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All specified rules were shown"
}
```

### PUT /security/rules
```json
{
  "data": {
    "affected_items": [
      {
        "id": 3,
        "rule": {
          "MATCH": {
            "definition": "example_rule"
          }
        }
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Rule created correctly"
}
```

### DELETE /security/rules (delete all rules. Default admin rules cannot be deleted)
```
{
  "data": {
    "affected_items": [
      {
        "id": 3,
        "rule": {
          "MATCH": {
            "definition": "example_rule"
          }
        },
        "roles": []
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All specified rules were deleted"
}
```

### PUT /security/rules/{rule_id} (you cannot update default admin rules)
```json
{
  "data": {
    "affected_items": [
      {
        "id": 3,
        "rule": {
          "MATCH": {
            "definition": "updated"
          }
        },
        "roles": []
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Rule updated correctly"
}
```

### POST /security/roles/{role_id}/rules 
```json
{
  "data": {
    "affected_items": [
      {
        "id": 2,
        "name": "readonly",
        "policies": [
          4,
          5,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          19
        ],
        "users": [
          2
        ],
        "rules": [
          1,
          2
        ]
      }
    ],
    "total_affected_items": 2,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All rules were linked to role 2"
}
```

### DELETE /security/roles/{role_id}/rules (delete all rules from role_id=1)

This role has rules 1, 2 and 3. Admin rules are set as: Rule 1 and 2 must be assigned to role 1.

```json
{
  "data": {
    "affected_items": [
      {
        "id": 1,
        "name": "administrator",
        "policies": [
          1,
          2,
          3,
          6,
          7,
          8,
          11,
          12,
          13,
          14,
          15,
          16,
          18,
          19,
          20,
          21,
          22,
          23
        ],
        "users": [
          1
        ],
        "rules": [
          1,
          2
        ]
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All rules were unlinked from role 1"
}
```

Rules 1 and 2 remains. This would not happen if this was role 2.


## Pending
- Unit and integration tests.
- Update documentation.
- Docstrings.

**Comment by vicferpoy** [comment]
# Status update
For clarity, we decided to add the `name` field to every rule. The current structure is the following:

```sql
1|elastic_admin|{"FIND$": {"elastic": ["administrator"]}}|2020-08-14 08:05:18.255067
2|opendistro_admin|{"FIND$": {"admin": ["administrator"]}}|2020-08-14 08:05:18.270748
```

```json
{
  "data": {
    "affected_items": [
      {
        "id": 1,
        "name": "elastic_admin",
        "rule": {
          "FIND$": {
            "elastic": [
              "administrator"
            ]
          }
        },
        "roles": [
          1
        ]
      },
      {
        "id": 2,
        "name": "opendistro_admin",
        "rule": {
          "FIND$": {
            "admin": [
              "administrator"
            ]
          }
        },
        "roles": [
          1
        ]
      }
    ],
    "total_affected_items": 2,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All specified rules were shown"
}
```

**Comment by vicferpoy** [comment]
# Status update
Although this was not required in this issue, I have added a new endpoint for the `authorization context` login:
`POST /security/user/authenticate/run_as`

This way we will avoid the use of an empty JSON with the standard login.

Testing environment has been changed as well in order to adapt to the new changes in the RBAC database.

## Pending
- RBAC white integration tests.
- Documentation.
