### ISSUE TITLE
Add option to get JWT token in raw format for login endpoint

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#5708]
Hello team,

We should add a new parameter option to `GET /security/user/authenticate` in order to respond with the token information in raw format. This parameter would ease the use of JWT token authorization in human-driven environments, such as curl commands.

The JWT token can be quite long depending on the user permissions and therefore we require to add this new functionality.

### Tasks:

- [x] Add parameter `raw` to endpoint in login controller and API spec
- [x] Allow schema to receive `application/json` and `text/plain` in the responses for the endpoint
- [x] Add integration test case for the new parameter to API security tests
