### ISSUE TITLE
Adapt stats framework module to use AffectedItemsWazuhResult

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#5733]
Hello team,

With the changes to the new API, the majority of endpoints use the framework SDK to obtain information about several resources.
For that reason, the actual response uses an affected_items and failed_items type of response to deal with multi-resource queries.

We should adapt the stats endpoints and framework to use such format for the response.

### Tasks:
- [x] Update spec.yaml for stats endpoints
- [x] Update stats framework modules to use AffectedItemsWazuhResult structure
- [x] Update unit tests accordingly
- [x] Update api integration tests accordingly
- [x] Update changes.md
- [x] Update equivalences table in documentation

**Comment by CarlosRS9** [comment]
# Status Update

Several minor changes  were applied by @vicferpoy. Spec.yaml and unit test were updated accordingly. We are currently updating integrity tests as they need a few changes to expect the new message format.

## Pending tasks

- Finish the integrity tests
- Update examples in the Spec.yaml
- Update message contents with proper ones for each endpoint.
