### ISSUE TITLE
Add token revocation to auth_context logged users when mapping rules change

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#5736]
Hello team,

We should improve our current token blacklist system to revoke those tokens from users logged through an authorization_context whose permissions may have changed due to changes in the security mapping rules.

Currently, when a policy, role, or user is modified, a list of affected users is calculated and all of their tokens are revoked. However, when an user is logged through an authorization_context, its permissions may also change when a new mapping rule is added or deleted from a role.

We should ensure the tokens are revoked correctly in this situation.

### Tasks:

- [x] Update [check_relationships()](https://github.com/wazuh/wazuh/blob/develop/framework/wazuh/core/security.py#L50) function to correctly interpret affected users logged through `auth_context` when a rule changes
- [x] Add `auth_context` logging test cases to [jwt_invalidation](https://github.com/wazuh/wazuh-qa/tree/master/tests/system/test_jwt_invalidation) ansible tests (https://github.com/wazuh/wazuh-qa/issues/840)
- [x] Add `auth_context` integration tests

**Comment by AdriiiPRodri** [comment]
## Integration tests

- [ ] Check that the authorization context endpoint returns a valid JWT token with the correct roles.

- [ ] Check that the default rules can only be used by the `wazuh-wui` user.

- [ ] Check that the authorization context endpoint handles invalid JSON bodies.

- [ ] Check that the authorization context endpoint does not return any permission when the body does not match any rule.

**Comment by AdriiiPRodri** [comment]
## Test result
```
adriiiprodri@wazuh python3 -m pytest -x test_authorization_contexts_login_method.tavern.yaml 
===================================================================================== test session starts =====================================================================================
platform linux -- Python 3.7.5, pytest-5.4.1, py-1.7.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/Desktop/git/wazuh/api/test/integration, inifile: pytest.ini
plugins: html-2.0.1, mock-1.10.0, asyncio-0.12.0, aiohttp-0.3.0, cov-2.8.1, testinfra-5.0.0, tavern-1.0.0, metadata-1.8.0
collected 1 item                                                                                                                                                                              

test_authorization_contexts_login_method.tavern.yaml .                                                                                                                                  [100%]

========================================================================= 1 passed, 10 warnings in 406.17s (0:06:46) ==========================================================================

```
