### ISSUE TITLE
Organize the util folder as common util for different modules.

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#5804]
## Description
This issue aims to organize the util folder, as common util for different modules.

## Expected
- Expose as common utils, the content into utils folder.
- Compile Utils unit tests as part of the preexistent CMakeList on `wazuh/src/unit_tests`

## Tasks
- [x] Move utils folder / Fix inclusions in DBSync project.
- [x] Move and modify unit tests to `wazuh/src/unit_tests`
- [x] Modify the CMakeList.txt in `wazuh/src/unit_tests`
- [x] PR
