### ISSUE TITLE
Adapt API, framework and documentation to the merge of API and manager services

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#5824]
Hello team,

The wazuh-api service has been merged together with wazuh-manager service here: https://github.com/wazuh/wazuh/pull/5721

We need to ensure the API is working correctly after these changes. Run and update any test if neccesary and also update new documentation to reflect these changes.

### Questions:

- What is the appropriate way to only restart the API now?
  - Control binary?
- If the manager is restarted via API endpoint, is the API also restarted? Should it be?
- How can a user disable the API?
- Should we remove reading and caching of ossec.conf from the API starting code? How much overhead does it add to every restart?

### Tasks:

- [x] Solve lingering questions
- [x] Update documentation to remove service wazuh-api where applicable
- [x] Fix and update necessary code in wazuh-apid.py, not a service anymore
- [x] Check if the merge affect ansible QA, integration QA or API integration test environments
- [x] Test and check the merge does not affect upgrade/migrations from 3.x to 4.0 or 4.0 to 4.x

**Comment by CarlosRS9** [comment]
# Status Update

Our team has discussed the questions related to this issue. These are the conclusions:
* The API will be a Daemon and therefore it will restart along with Wazuh using the Wazuh service or the `ossec-control` binary.
* There won't be an endpoint to restart the API.
* The API cannot be disabled by the user.
* Wazuh-apid binary won't have control functions such as Start, Stop or Status because those will be handled by `ossec-control` and the Wazuh service.
* We will study the possibility of creating a binary to control the API daemon (start, Stop, Restart, Status)

**Comment by CarlosRS9** [comment]
# Status update

We are working in the removal of the start, stop and status functions of `wazuh-apid` binary. Now it works as a daemon. Further tests must be performed as we are currently facing an issue regarding this.

The Wazuh apid daemon is now included in the daemon list so it will be triggered when Wazuh service starts.

**Comment by CarlosRS9** [comment]
# Status update

Further changes have been applied to `wazuh-apid` to integrate it as a daemon in `ossec-control`. Now it creates its own pid file and works as expected within the `ossec-control`. Additionally, Wazuh-apid daemon has been added to the optional daemon list  for `ossec-server.sh`.

**Comment by CarlosRS9** [comment]
# Status update

Several checks and tests were performed to ensure migration from 3.x to 4.0 or 4.0 to 4.x still works. A few changes were made to restore this functionality. Additional minor changes were applied to adapt it to the new service. Now it is working as expected.

To ensure the API integration tests were not impacted by these changes we have run the agent tests. Here are the results:
```
test_agents_DELETE_endpoints.tavern.yaml 
         7 passed, 9 warnings

test_agents_GET_endpoints.tavern.yaml 
         90 passed, 97 warnings

test_agents_POST_endpoints.tavern.yaml 
         4 passed, 6 warnings

test_agents_PUT_endpoints.tavern.yaml 
         9 passed, 11 warnings
```

Ansible QA testing started but is not yet finished. Integration QA tests are still pending.

Several modification were applied to the wazuh documentation to remove the use of the old wazuh-api service. Additional changes are required. We are working on it.

## Pending tasks

- Finish Ansible QA and Integration QA testing.
- Apply the remaining changes to Wazuh documentation.

**Comment by CarlosRS9** [comment]
# Status update

The development is finished. Documentation and tests have been updated accordingly.
