### ISSUE TITLE
[Agent-info][Framework] Adapt and update framework acess to global.db

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#5935]
## Description

Due to changes in https://github.com/wazuh/wazuh/issues/5367, `global.db` information has been migrated to `wazuh-db` as part of the process to improve disk access performance, and it is now part of the pool of databases handled by `wazuh-db`. We should ensure the appropriate changes are performed in the framework to access the information from `global.db`.

## Design

We have to change `WazuhDbQueryAgent` and related classes to use `WazuhDBBackend` instead of `SQLiteBackend`. Also, we have to provide a solution from the framework or request a mechanism to `wazuh-db` to be able to access data with a size bigger than 64kb, the maximum `wazuh-db` can respond in a single query due to socket limitations. 

## Testing

We should update and run related unit tests as well as to run the API integration tests for Agents.

## Tasks

- [x] Update access to global.db
- [x] Investigate and provide a design solution to receive more than 64kb of data from wazuh-db (chunks)
- [x] Update/add and run new framework unit tests
- [ ] Run agents API integration tests
- [ ] Update changelog.md

**Comment by Selutario** [comment]
## Issue update

Hi team!

The easy part of the modifications is already done. It was enough to replace the backend that was used until now (SQLiteBackend) with WazuhDBBackend. However, there was a problem calling the _substitute_params function. When trying to replace the placeholders in a query like this:
```
OR (id = :id$9 COLLATE NOCASE) OR (id = :id$10 COLLATE NOCASE) OR (id = :id$11 COLLATE NOCASE)
```
it ended like this incorrectly:
```
(id = '000' COLLATE NOCASE) OR (id = '011'0 COLLATE NOCASE) OR (id = '011'1 COLLATE NOCASE)
```

It is fixed by replacing the `query.replace()` of line 873 with a regex that only replaces the whole word.
https://github.com/wazuh/wazuh/blob/528fc300468b429f767784250933233bf6c121ad/framework/wazuh/core/utils.py#L867-L874

It remains to solve the problem of the wazuh-db socket saturation when a lot of information is returned.

Kind regards,
Selu.

**Comment by vicferpoy** [comment]
# Issue update

We studied the possibility of adding a compressor for the `agent_info` payload with the `zlib` python lib. 

We would compress the payload in the module `local_server` :
```python
        elif command == b'sendsync':
            if self.server.node.client is None:
                raise WazuhClusterError(3023)
            asyncio.create_task(self.server.node.client.send_request(b'sendsync', zlib.compress(self.name.encode() + b' ' + data)))
            return None, None
        elif command == b'sendasync':
            if self.server.node.client is None:
                raise WazuhClusterError(3023)
            asyncio.create_task(self.server.node.client.send_request(b'sendsync', zlib.compress(self.name.encode() + b' ' + data)))
            return b'ok', b'Added request to sendsync requests queue'
```

And decompress it once received in the module `master.py`:
```python
        elif command == b'sendsync':
            self.server.sendsync.add_request(self.name.encode() + b'*' + zlib.decompress(data))
            return b'ok', b'Added request to SendSync requests queue'
```

**Without compression**, changing the `agent_info` of **5000 agents**:
```
2020/09/18 10:45:57 DEBUG2: [Client worker1] [Main] Time synchronizing agent statuses: 0.45822858810424805 s
2020/09/18 10:46:08 DEBUG2: [Client worker1] [Main] Time synchronizing agent statuses: 0.45055508613586426 s
```

**With compression**, changing the `agent_info` of **5000 agents**:
```
2020/09/18 10:48:04 DEBUG2: [Client worker1] [Main] Time synchronizing agent statuses: 0.5320742130279541 s
2020/09/18 10:48:14 DEBUG2: [Client worker1] [Main] Time synchronizing agent statuses: 0.5255429744720459 s
```

**Comment by vicferpoy** [comment]
# Issue update

Hello team. I have been working on a hybrid solution to solve the `wazuh-db` buffer limitation (64KB). This caused two problems:
- Wazuh-db cannot handle queries larger than 64KB.
- The framework cannot do queries which imply responses larger than 64KB (the response will be cut off).

## Query responses larger than 64KB

To solve this issue, we consume the `wazuh-db` response and check its size. If it is equal or greater than 64KB, we paginate the query in chunks and then merge the result. It is as efficient as it could be with large environments since we are using chunks of 500 results at max.

I tested this on an environment with 30000 agents and 1000 long named groups and it worked fine.

## Framework queries larger than 64KB

This issue is harder to solve than the latter. When using RBAC, we get a list of permitted agents first and then filter the final query with that list. The query build was very inefficient and it was adding an `OR` clause for every agent in the list. The solution for this was to check the number of permitted agents and compare it with the number of total agents in the system. Using the smaller group (permitted or not permitted), we can build a dynamic query using `IN` or `NOT IN` + `(id1,id2,i3)` instead of `id = '001' OR id = '002' OR ...`.

This solution is called hybrid because this only covers a maximum group of resources. On large environments with no difference between the permitted and non permitted agents (or groups, it is the same use case) the query will surpass the 64KB restriction anyway. We need to add another mechanism (even if it is less efficient) for this case.

## Test results

I have tested this implementation on an environment with **30000** registered agents. The `wazuh` user has permission to read them all and a normal user has only permission to read **10000** (almost critical use case).

I used this script to get the average time for every case:

```python
import time
import requests
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

user_token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjAwOTU4MzQ0LCJleHAiOjE2MDA5NjE5NDQsInN1YiI6ImFnZW50ZXMiLCJyYmFjX3JvbGVzIjpbMTAwXSwicmJhY19wb2xpY2llcyI6eyJhZ2VudDpyZWFkIjp7ImFnZW50Omdyb3VwOmRlbmllZCI6ImFsbG93In0sInJiYWNfbW9kZSI6IndoaXRlIn19.U8meuko2EMULrTDQl4T_Owhl914lukKYcycYZRiSroY"
admin_token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjAwOTU4ODI4LCJleHAiOjE2MDA5NjI0MjgsInN1YiI6IndhenVoIiwicmJhY19yb2xlcyI6WzFdLCJyYmFjX3BvbGljaWVzIjp7ImFnZW50OmNyZWF0ZSI6eyIqOio6KiI6ImFsbG93In0sImdyb3VwOmNyZWF0ZSI6eyIqOio6KiI6ImFsbG93In0sImFnZW50OnJlYWQiOnsiYWdlbnQ6aWQ6KiI6ImFsbG93IiwiYWdlbnQ6Z3JvdXA6KiI6ImFsbG93In0sImFnZW50OmRlbGV0ZSI6eyJhZ2VudDppZDoqIjoiYWxsb3ciLCJhZ2VudDpncm91cDoqIjoiYWxsb3cifSwiYWdlbnQ6bW9kaWZ5X2dyb3VwIjp7ImFnZW50OmlkOioiOiJhbGxvdyIsImFnZW50Omdyb3VwOioiOiJhbGxvdyJ9LCJhZ2VudDpyZXN0YXJ0Ijp7ImFnZW50OmlkOioiOiJhbGxvdyIsImFnZW50Omdyb3VwOioiOiJhbGxvdyJ9LCJhZ2VudDp1cGdyYWRlIjp7ImFnZW50OmlkOioiOiJhbGxvdyIsImFnZW50Omdyb3VwOioiOiJhbGxvdyJ9LCJncm91cDpyZWFkIjp7Imdyb3VwOmlkOioiOiJhbGxvdyJ9LCJncm91cDpkZWxldGUiOnsiZ3JvdXA6aWQ6KiI6ImFsbG93In0sImdyb3VwOnVwZGF0ZV9jb25maWciOnsiZ3JvdXA6aWQ6KiI6ImFsbG93In0sImdyb3VwOm1vZGlmeV9hc3NpZ25tZW50cyI6eyJncm91cDppZDoqIjoiYWxsb3cifSwiYWN0aXZlLXJlc3BvbnNlOmNvbW1hbmQiOnsiYWdlbnQ6aWQ6KiI6ImFsbG93In0sInNlY3VyaXR5OmNyZWF0ZSI6eyIqOio6KiI6ImFsbG93In0sInNlY3VyaXR5OmNyZWF0ZV91c2VyIjp7Iio6KjoqIjoiYWxsb3cifSwic2VjdXJpdHk6cmVhZF9jb25maWciOnsiKjoqOioiOiJhbGxvdyJ9LCJzZWN1cml0eTp1cGRhdGVfY29uZmlnIjp7Iio6KjoqIjoiYWxsb3cifSwic2VjdXJpdHk6cmV2b2tlIjp7Iio6KjoqIjoiYWxsb3cifSwic2VjdXJpdHk6cmVhZCI6eyJyb2xlOmlkOioiOiJhbGxvdyIsInBvbGljeTppZDoqIjoiYWxsb3ciLCJ1c2VyOmlkOioiOiJhbGxvdyIsInJ1bGU6aWQ6KiI6ImFsbG93In0sInNlY3VyaXR5OnVwZGF0ZSI6eyJyb2xlOmlkOioiOiJhbGxvdyIsInBvbGljeTppZDoqIjoiYWxsb3ciLCJ1c2VyOmlkOioiOiJhbGxvdyIsInJ1bGU6aWQ6KiI6ImFsbG93In0sInNlY3VyaXR5OmRlbGV0ZSI6eyJyb2xlOmlkOioiOiJhbGxvdyIsInBvbGljeTppZDoqIjoiYWxsb3ciLCJ1c2VyOmlkOioiOiJhbGxvdyIsInJ1bGU6aWQ6KiI6ImFsbG93In0sImNsdXN0ZXI6c3RhdHVzIjp7Iio6KjoqIjoiYWxsb3cifSwibWFuYWdlcjpyZWFkIjp7Iio6KjoqIjoiYWxsb3cifSwibWFuYWdlcjpyZWFkX2FwaV9jb25maWciOnsiKjoqOioiOiJhbGxvdyJ9LCJtYW5hZ2VyOnVwZGF0ZV9hcGlfY29uZmlnIjp7Iio6KjoqIjoiYWxsb3cifSwibWFuYWdlcjp1cGxvYWRfZmlsZSI6eyIqOio6KiI6ImFsbG93In0sIm1hbmFnZXI6cmVzdGFydCI6eyIqOio6KiI6ImFsbG93In0sIm1hbmFnZXI6ZGVsZXRlX2ZpbGUiOnsiKjoqOioiOiJhbGxvdyIsImZpbGU6cGF0aDoqIjoiYWxsb3cifSwibWFuYWdlcjpyZWFkX2ZpbGUiOnsiZmlsZTpwYXRoOioiOiJhbGxvdyJ9LCJjbHVzdGVyOmRlbGV0ZV9maWxlIjp7Im5vZGU6aWQ6KiI6ImFsbG93Iiwibm9kZTppZDoqJmZpbGU6cGF0aDoqIjoiYWxsb3cifSwiY2x1c3RlcjpyZWFkX2FwaV9jb25maWciOnsibm9kZTppZDoqIjoiYWxsb3cifSwiY2x1c3RlcjpyZWFkIjp7Im5vZGU6aWQ6KiI6ImFsbG93In0sImNsdXN0ZXI6dXBkYXRlX2FwaV9jb25maWciOnsibm9kZTppZDoqIjoiYWxsb3cifSwiY2x1c3RlcjpyZXN0YXJ0Ijp7Im5vZGU6aWQ6KiI6ImFsbG93In0sImNsdXN0ZXI6dXBsb2FkX2ZpbGUiOnsibm9kZTppZDoqIjoiYWxsb3cifSwiY2x1c3RlcjpyZWFkX2ZpbGUiOnsibm9kZTppZDoqJmZpbGU6cGF0aDoqIjoiYWxsb3cifSwiY2lzY2F0OnJlYWQiOnsiYWdlbnQ6aWQ6KiI6ImFsbG93In0sImRlY29kZXJzOnJlYWQiOnsiZGVjb2RlcjpmaWxlOioiOiJhbGxvdyJ9LCJsaXN0czpyZWFkIjp7Imxpc3Q6cGF0aDoqIjoiYWxsb3cifSwicnVsZXM6cmVhZCI6eyJydWxlOmZpbGU6KiI6ImFsbG93In0sIm1pdHJlOnJlYWQiOnsiKjoqOioiOiJhbGxvdyJ9LCJzY2E6cmVhZCI6eyJhZ2VudDppZDoqIjoiYWxsb3cifSwic3lzY2hlY2s6Y2xlYXIiOnsiYWdlbnQ6aWQ6KiI6ImFsbG93In0sInN5c2NoZWNrOnJlYWQiOnsiYWdlbnQ6aWQ6KiI6ImFsbG93In0sInN5c2NoZWNrOnJ1biI6eyJhZ2VudDppZDoqIjoiYWxsb3cifSwic3lzY29sbGVjdG9yOnJlYWQiOnsiYWdlbnQ6aWQ6KiI6ImFsbG93In0sInJiYWNfbW9kZSI6IndoaXRlIn19.heHTHF6heO3wu51n9dWTtO9fsjs94MIVRNzFat9bkf4"

def make_api_call(token=None):
    headers = {'Authorization': f'Bearer {token}'}
    before = time.time()
    requests.get('https://localhost:55000/agents', headers=headers, verify=False)
    after = time.time() - before
    return after


def print_results(user=None, token=None):
    results = list()

    for i in range(50):
        results.append(make_api_call(token=token))

    print(f"{user} - {sum(results) / len(results)}")

print_results('admin', admin_token)
print_results('user', user_token)

```


These were the results:

```
admin - 1.0187586069107055
user - 0.5216933250427246
```

Although the average time has increased with this implementation, I believe we cannot short it preventing any error without increasing the wazuh-db max buffer size.

**Comment by AdriiiPRodri** [comment]
# Issue update

Hi team,

We have been working on the hybrid solution, as we know, **above 10000 agents** (**approximate value**), the first part of the solution does not work properly. Because of this we have developed a solution for these situations.

## Framework queries larger than 64KB

For this solution we have decided that when the "**where in**" parameter of the query to the database is equal or higher than 10000 elements, this parameter will be excluded and will be processed once we have the data from the database. In this way, we avoid consuming the socket buffer size and also speed up the process.

The main problem with this solution is that **we don't know in advance how many elements will be removed after applying the "where in" filter**. Let's take an example of this. If in our system we have 30000 agents, we have permissions for 15000 of them, the query to the database must have a "where in" with 15000 which exceeds **the limit of 64KB**. In this case we remove this list of 15000 elements and make the request without it, this way we will get 500 agents from the database, this is because the limit to query the database is 500. Now of those 500 we only have permissions for 200, 300 will be removed when we process the list removed before. We will return 200 elements to the user **instead of the 500 requested**. If we knew this information before executing the query, we could raise the limit of 500 in order to return 500, although we cannot be sure that these new elements are included in the allowed ones until we reach the post-processing part.

To solve this problem we can apply some kind of **heuristics** to the limit of the queries. In our tests we have verified that making **a query with 10,000 elements can take up to 10 seconds**. Our heuristics in the worst case and given that **the complexity in time is linear (O(n))**, for a case of 30000 agents could take about 30 seconds to give the answer, with the guarantee that it will have all the correct elements.

The changes have to be applied in the `core/utils.py` framework file, currently we have been testing increasing the limit to the size of the allowed elements plus 500 extra elements. This heuristic is simple and can be improved, so we will do more tests:

```
def run(self):
    """Builds the query and runs it on the database"""
    rbac_ids = self.legacy_filters.pop('rbac_ids', None)

    self._add_select_to_query()
    self._add_filters_to_query()
    self._add_search_to_query()
    if self.count:
        self._get_total_items()
        if not self.data:
            return {'totalItems': self.total_items}
    self._add_sort_to_query()
    self._add_limit_to_query()
    if self.data:
        if len(rbac_ids) > 10000:
            self.limit = len(rbac_ids) + 500

        self._execute_data_query()

        if self.limit > 500 and rbac_ids:
            key = 'id' if 'id' in self._data[0].keys() else 'name'
            for element in list(self._data):
                str(element[key]).zfill(3) not in rbac_ids and self._data.remove(element)

            self._get_total_items()

        return self._format_data_into_dictionary()
```
