### ISSUE TITLE
Make Analysisd accept the negate attribute

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#5961]
As explained in #141, the rule match engine shall accept a new attribute `negate` in the options mentioned in the "Requirements" section.

## How to do

The affected options are represented in the [code](https://github.com/wazuh/wazuh/blob/v3.13.1/src/analysisd/rules.h#L148) as
```c
OSMatch *
OSRegex *
char *
```

I propose to declare three new pair structures:

```c
typedef struct {
    OSMatch *match;
    bool negated;
} w_deniable_osmatch_t;

typedef struct {
    OSRegex *regex;
    bool negated;
} w_deniable_osregex_t;

typedef struct {
    char *string;
    bool negated;
} w_deniable_string_t;
```

And replace the affected options with such structures.

On the other hand, we must make the XML rule parser accept the new `negate` attribute.

|Attribute|Mandatory|Value range|Default value|
|---|---|---|---|
|`negate`|No|`yes` or `no`|`no`|

## Subtasks

- [ ] Extend the data structure at _analysisd/rules.h_.
- [ ] Accept the `negate` attribute in _analysisd/rules.c_.
- [ ] Support, but do not apply, the `negate` attribute in _shared/rules_op.c_.
