### ISSUE TITLE
Import the PCRE2 library into the external dependencies

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#5967]
We are introducing Perl-compatible expressions in rules and decoders. That's why we need the PCRE2 library in the external dependencies.

## Subtasks

- [x] Compile the PCRE2 library for Linux (32-bit and 64-bit).
- [x] Compress the library sources (`pcre2.tar.gz`), and add this file to the external dependencies repository.
- [x] Modify the `Makefile` to download and compile the PCRE2 library into `libwazuhext.so`, for the `server` target (so far).
- [x] Check how much the external library build time increases after adding PCRE2.
- [x] Update the README file with the PCRE2 library.
