### ISSUE TITLE
Extend the rule parser to accept PCRE2 expressions

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#5970]
Support PCRE2 in rules through a new attribute in the fields that currently accept a regex.

## Affected options

- `<regex>`
- `<field>`

## New attribute

|Attribute|Mandatory|Value range|Default value|
|---|---|---|---|
|`type`|No|`osregex` or `pcre2`|`osregex`|

## Example

```xml
<rule>
  <regex type="pcre2">^Hello</regex>
  <field name="id" type="osregex" negate="yes">Joe$</field>
</rule>
```

## Data structure

Use the data structure described in #5968.

## Subtasks

- [ ] Extend the data structure at _analysisd/rules.h_.
- [ ] Accept the `type` attribute in _analysisd/rules.c_.
- [ ] Support, but do not apply, the `type` attribute in _shared/rules_op.c_.
