### ISSUE TITLE
[Task] Add new endpoint to check status of tasks

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#6029]
Hi team,

This issue is related with #5537 and #5387. With the new agent upgrade system, a new task module has been added.

This module is in charge of performing different types of tasks, currently only the new upgrade module takes advantage of it.

In this issue we are looking to create a new endpoint to check the status of the tasks.

## Design

The endpoint should have the following structure:

Path: 

- `GET /tasks/status`

Query parameters: 
- `pretty`
- `wait_for_complete`
- `list_tasks`

## Tasks

- [x] Update spec.yaml
- [x] Add tasks controller
- [x] Add tasks functions at framework side
- [x] Add and run new integration tests
- [x] Add and run new unit tests
- [x] Update changelog

**Comment by AdriiiPRodri** [comment]
## Integration tests
```
adriiiprodri@wazuh pytest -x test_tasks_endpoints.tavern.yaml 
================================ test session starts ================================
platform linux -- Python 3.7.5, pytest-5.4.1, py-1.7.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/Desktop/git/wazuh/api/test/integration, inifile: pytest.ini
plugins: html-2.0.1, mock-1.10.0, asyncio-0.12.0, aiohttp-0.3.0, cov-2.8.1, testinfra-5.0.0, tavern-1.0.0, metadata-1.8.0
collected 2 items                                                                   

test_tasks_endpoints.tavern.yaml ..                                           [100%]

==================== 2 passed, 13 warnings in 109.30s (0:01:49) =====================

```

**Comment by AdriiiPRodri** [comment]
## Status update

### Example output
```
{
  "data": {
    "affected_items": [
      {
        "create_time": 1606897796,
        "task_id": 2,
        "module": "upgrade_module",
        "status": "In progress",
        "node": "master-node",
        "last_update_time": 1606897796,
        "command": "upgrade",
        "agent_id": "004"
      }
    ],
    "total_affected_items": 5,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All specified task's status were returned",
  "error": 0
}
```

### Integration tests
```
adriiiprodri@wazuh pytest -x test_tasks_endpoints.tavern.yaml 
=========================================================================== test session starts ===========================================================================
platform linux -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/Desktop/git/wazuh/api/test/integration, configfile: pytest.ini
plugins: metadata-1.10.0, html-2.1.1, tavern-1.7.0
collected 4 items                                                                                                                                                         

test_tasks_endpoints.tavern.yaml ....

================================================================ 4 passed, 5 warnings in 155.67s (0:02:35) ================================================================
```

### Unittests
```
adriiiprodri@wazuh pytest -x wazuh/tests/test_tasks.py
=========================================================================== test session starts ===========================================================================
platform linux -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/Desktop/git/wazuh/framework
plugins: metadata-1.10.0, html-2.1.1, tavern-1.7.0
collected 28 items                                                                                                                                                        

wazuh/tests/test_tasks.py ............................

=========================================================================== 28 passed in 0.25s ============================================================================
```
