### ISSUE TITLE
[AWS Integration] Add support for load balancer logs in AWS module

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#6034]
Hello team,

As part of Wazuh's continuous effort towards improvement, we should include support for AWS load balancer logs in our AWS module. 

### **Description:**
This development should include support for the following logs:

Application Load Balancer (ALB): https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html#access-log-entry-format
Classic Load Balancer (CLB): https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html#access-log-entry-format
Network Load Balancer (NLB): https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-access-logs.html#access-log-entry-format

### **Design:**

As part of the development we should update [Wazuh's AWS module](https://github.com/wazuh/wazuh/blob/master/wodles/aws/aws_s3.py) to support the processing of the new logs. We should investigate and decide whether we need three different classes to process logs coming from the different load balancer types or if one is enough for the three of them.

Also, we should update the [Monitoring AWS based services](https://github.com/wazuh/wazuh-documentation/tree/develop/source/amazon/services/supported-services) documentation to add the new supported services, their configuration, and use case examples.

Lastly, we should update [Wazuh's AWS ruleset](https://github.com/wazuh/wazuh-ruleset/blob/master/rules/0350-amazon_rules.xml) to support the added services and generate new alerts for these logs.

### **Tasks:**

- [x] Investigate access logs for the 3 type of load balancers to design module changes
- [x] Add support for new logs in AWS module python script
- [x] Add configuration support changes to ossec.conf
- [x] Test use cases in real setup using AWS
- [x] Add new rules for aws ruleset
- [x] Update/Add new documentation for ossec.conf and services
- [x] Update changelog.md
