### ISSUE TITLE
[API] Review and update API endpoint responses

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#6196]
Hello team,

After reviewing all the Wazuh API endpoints we discovered there are a few of them that are not following our response standard standard. Here is an example of one of those endpoints
```
{
    "active-response:command": {},
    "description": "Allow to execute active response commands in the agents",
    "resources": [],
    "example": {},
    "related_endpoints": []
  },
    "agent:create": {},
    "description": "Create new agents",
    "resources": [],
    "example": {},
    "related_endpoints": []
  }
}
```

And here is an example of the same endpoint but applying the "data" standard:
```
{
  "data": {
      "active-response:command": {},
      "description": "Allow to execute active response commands in the agents",
      "resources": [],
      "example": {},
      "related_endpoints": []
    },
      "agent:create": {},
      "description": "Create new agents",
      "resources": [],
      "example": {},
      "related_endpoints": []
    }
  }
}
```
The endpoints affected by this are the following ones:
```
GET /security/user/authenticate
POST /security/user/authenticate/run_as
GET /security/actions
GET /security/config
GET /security/resources
GET /
```

Additionally, some endpoints are missing a `200` response example. We should add an example for the following ones:
```
GET /decoders/files/{filename}/download
GET /groups/{group_id}/files/{file_name}/xml
GET /rules/files/{filename}/download
PUT /security/user/revoke
PUT /security/config
DELETE /security/config
```
## Tasks
- [x] Update the listed endpoints to use the "data" response format.
- [x] Add examples of `200` responses for the specified endpoints.
- [x] Update `spec.yaml` file and `changes.md`
- [x] Review integration tests for the affected endpoints

**Comment by CarlosRS9** [comment]
# Status Update

The endpoints have been updated and now their responses contains the expected `data` field. Here is an example for each of these endpoints:

`GET /security/user/authenticate`
```
{
  "data": {
    "token": "{TOKEN_STRING}"
  }
}
```

`POST /security/user/authenticate/run_as`
```
{
  "data": {
    "token": "{TOKEN_STRING}"
  }
}
```

`GET /security/actions`
```
{
  "data": {
    "active-response:command": {
      "description": "Allow to execute active response commands in the agents",
      "resources": [
        "agent:id"
      ],
      "example": {
        "actions": [
          "active-response:command"
        ],
        "resources": [
          "agent:id:001"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "PUT /active-response"
      ]
    },

    · · ·

    "security:update_config": {
      "description": "Update current security configuration",
      "resources": [
        "*:*"
      ],
      "example": {
        "actions": [
          "security:update_config"
        ],
        "resources": [
          "*:*:*"
        ],
        "effect": "allow"
      },
      "related_endpoints": [
        "PUT /security/config",
        "DELETE /security/config"
      ]
    }
  }
}
```

`GET /security/resources`
```
{
  "data": {
    "*:*": {
      "description": "Resource applied in functions which take part in the creation of a specific resource. We call these functions, resourceless functions. Example: agent:create"
    },
    "agent:id": {
      "description": "Reference agents via agent ID (i.e. agent:id:001)"
    },
    "group:id": {
      "description": "Reference agent groups via group ID (i.e. group:id:default)"
    },
    "node:id": {
      "description": "Reference cluster nodes via node ID (i.e. node:id:worker1)"
    },
    "file:path": {
      "description": "Reference files via its path (i.e. file:path:etc/rules/new_rule.xml)"
    },
    "decoder:file": {
      "description": "Reference decoder files via its path (i.e. decoder:file:0005-wazuh_decoders.xml)"
    },
    "list:path": {
      "description": "Reference list files via its path (i.e. list:path:etc/lists/audit-keys)"
    },
    "rule:file": {
      "description": "Reference rule files via its path (i.e. rule:file:0610-win-ms_logs_rules.xml)"
    },
    "policy:id": {
      "description": "Reference security policies via its id (i.e. policy:id:1)"
    },
    "role:id": {
      "description": "Reference security roles via its id (i.e. role:id:1)"
    },
    "user:id": {
      "description": "Reference security users via its id (i.e. user:id:1)"
    },
    "rule:id": {
      "description": "Reference security rules via its id (i.e. rule:id:1)"
    }
  }
}
```

`GET /`
```
{
  "data": {
    "title": "Wazuh API REST",
    "api_version": "4.0.0",
    "revision": 4000,
    "license_name": "GPL 2.0",
    "license_url": "https://github.com/wazuh/wazuh/blob/master/LICENSE",
    "hostname": "wazuh-master",
    "timestamp": "2020-10-05T15:43:56+0000"
  }
}
```

Regarding the endpoints that didn't have examples for their `200` responses, the problem was that they actually have those examples, but as they are `xml` responses REDOC is not able to show them properly.

**Comment by CarlosRS9** [comment]
# Status Update

The development is finished. The examples for the endpoints with responses in XML format have been updated so REDOC is able to show them properly. `Spec.yaml` has been updated accordingly.

Integration (tavern) tests were updated to support the responses with the new `data` field.
