### ISSUE TITLE
[API] rules and decoders endpoint: add support to negate and type regex attribute

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#6318]
|Wazuh version|Component|Install type|Install method|
|---|---|---|---|
| 4.1.0 | API | Manager | Packages/Sources |

# Description
Hi team!

As explained [here](https://github.com/wazuh/wazuh/issues/141) and [here](https://github.com/wazuh/wazuh/issues/205), API should show:

- [x] `/decoders`: add `type` attribute for `regex` option .  Value range: `osregex`,`pcre2` . Related to https://github.com/wazuh/wazuh/issues/5968
- [x] `/rules` : add `type` attribute for `regex` and `field` option.  Value range: `osregex`,`pcre2` . Related to https://github.com/wazuh/wazuh/issues/5970
- [x] `/rules` : add  `negate` attribute for any [regex option available](https://github.com/wazuh/wazuh-documentation/pull/2990) .  Value range: `no`,`yes` . Related to https://github.com/wazuh/wazuh/issues/5961

Because, from now, regex options might have this optional attributes, is desirable that those are grouped in a JSON object using `pattern`, `type` and `negate` for regex pattern, regex type and negate value respectively.

## Example

`curl -u foo:bar -k -X GET "https://127.0.0.1:55000/decoders?pretty&offset=0&limit=1&sort=+file,position"`
```json
{
  "error":0,
  "data":{
    "items":[
      {
        "file":"0005-wazuh_decoders.xml",
        "path":"ruleset/decoders",
        "name":"wazuh",
        "position":0,
        "status":"enabled",
        "details":{
          "prematch":{
            "pattern":"^wazuh: ",
            "type":"osregex"
          }
        }
      }
    ],
    "totalItems":880
  }
}
```
`curl -u foo:bar -k -X GET "https://127.0.0.1:55000/rules/1002?pretty"`
```json
{
  "error":0,
  "data":{
    "items":[
      {
        "file":"0020-syslog_rules.xml",
        "path":"ruleset/rules",
        "id":1002,
        "description":"Unknown problem somewhere in the system.",
        "level":2,
        "status":"enabled",
        "groups":[
          "syslog",
          "errors"
        ],
        "pci":[
          
        ],
        "gdpr":[
          
        ],
        "hipaa":[
          
        ],
        "nist-800-53":[
          
        ],
        "gpg13":[
          "4.3"
        ],
        "details":{
          "match":{
            "pattern":"core_dumped|failure|error|attack| bad |illegal |denied|refused|unauthorized|fatal|failed|Segmentation Fault|Corrupted",
            "type":"osregex",
            "negate":"no"
          }
        }
      }
    ],
    "totalItems":1
  }
}
```

Regards,
Nico
