### ISSUE TITLE
Segment and multithread Analysis daemon engine

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#637]
Once PR https://github.com/wazuh/wazuh/pull/649 is completed, Analysisd will be the main data stream bottleneck due to two main reasons:

1. Analysisd performs hard CPU processing in a single thread that may use 100% of one core, leaving the rest of cores idle.
2. Currently the FIM data processing is the heaviest task in Analysisd, and it blocks the processing of the rest of —lighter— events.

## Subtasks

- [X] Input event buffer. (https://github.com/wazuh/wazuh/commit/13a8bb539f3dff935da4eb547cda5c18e1118b09)
- [x] Segment Analysis pipeline: 
  - Message receiving.
  - Event pre-decoding.
  - Event decoding.
  - Rule matching.
  - Rule postprocessing.
  - Event storage on disk.
  - Output file rotation.
- [x] Assign a queue and a thread to each task.
- [x] Get rid of critical sections, mainly for the alert cache.

### To be decided

We have to discuss whether the rule postprocessing should work in the same process or in a subprocess. 

## Dependencies

This issue depends on issue https://github.com/wazuh/wazuh/issues/611 related to Syscheck performance.

Working on branch [dev-analysisd-parallelization](https://github.com/wazuh/wazuh/tree/dev-analysisd-parallelization).

**Comment by vikman90** [comment]
Implementing task 1 (input event buffer) for PR https://github.com/wazuh/wazuh/pull/649.

**Comment by vikman90** [comment]
Input event queue implemented: https://github.com/wazuh/wazuh/commit/13a8bb539f3dff935da4eb547cda5c18e1118b09

**Comment by TJOSERAFAEL** [comment]
This PR https://github.com/wazuh/wazuh/pull/1039 solves the issue

**Comment by vikman90** [comment]
## Data flow and thread design diagram
![image1](https://github.com/wazuh/wazuh/assets/10536251/6de50dc7-e801-4a2b-827e-22c1d30c4fe2)
