### ISSUE TITLE
[use cases] IP Reputation

### ISSUE THREAD

**Issue by Zenidd** [wazuh/wazuh#6654]
Hi team,

### Description

IP Reputation use case shows Wazuh capabilities on blocking and alerting interactions with addresses on a blacklist. This use case requires integrating a CDB list, a related config line on `ossec.conf` and a minimum of one rule.

### Tasks

- [ ] Integrate Alienvault CDB list file.

- [ ] Edit `ossec.conf` to add AlienVault blacklist.

- [ ] add IP-reputation rule.

- [ ] Add documentation explaining the use case.

Greetings,
JP

**Comment by Zenidd** [comment]
## Use case requirements

### Rules and decoders
```xml
<group name="attack,">
  <rule id="100100" level="10">
  <if_group>web|attack|attacks</if_group>
  <list field="srcip" lookup="address_match_key">etc/lists/blacklist-alienvault</list>
  <description>IP address found in AlienVault reputation database.</description>
  </rule>
</group>
```
### Additional ossec.conf configuration
```xml
<ruleset>
  <list>etc/lists/ip-reputation</list>
</ruleset>

<command>
  <name>firewall-drop</name>
  <executable>firewall-drop.sh</executable>
  <expect>srcip</expect>
  <timeout_allowed>yes</timeout_allowed>
</command>

<active-response>
  <command>firewall-drop</command>
  <location>local</location>
  <rules_id>100100</rules_id>
  <timeout>60</timeout>
</active-response>
```
### Third party software/files

- IP set file from Alienvault.
- Script to convert IP-set to CDB list format.

## Possible approaches and implementation
- The only rule for this use case could be appended to an existing rules file.
- The IP-set file should be downloaded and converted to CDB list format internally.
- The related 

### New ossec.conf configuration section related to IP reputation feed 
```xml
<ip_reputation>
  <ipset_url>https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/alienvault_reputation.ipset</ipset_url>
  <frequency>6h</frequency>
</ip_reputation>
```
