### ISSUE TITLE
[use cases] Yara

### ISSUE THREAD

**Issue by neonmei** [wazuh/wazuh#6667]
### Detecting and removing malware - VirusTotal integration

Yara is a tool which can identify and classify malware artifacts. Wazuh can receive feedback from Yara to scan new and modified files and check for malware.

### Tasks

- [ ] Custom rules and decoders in the Wazuh manager

- [ ] Configuration Items in Wazuh Manager config, commented out (i.e: command, active-response).

- [ ] Script to be distributed on monitored endpoint side to aid with invocation and parsing

- [ ] Add documentation on how to bootstrap and enable yara on a monitored endpoint.

**Comment by neonmei** [comment]
## Use case requirements

- Wazuh Manager: Custom rules and decoders.
- Monitored endpoint: [Yara](https://github.com/VirusTotal/yara) Installed
- Monitored endpoint: custom script to wrap yara and fit output for processing.
- Documentation showing how to enable syscheck+active-response to monitor folders on both Manager and Monitored Endpoint.

### Rules and decoders

Something like the following would go into `etc/decoders/0600-use_cases_decoders.xml` (/var/ossec/ruleset/decoders/0600-use_cases_decoders.xml)

```xml
<decoder name="yara_decoder">
    <prematch>wazuh-yara:</prematch>
</decoder>

<decoder name="yara_decoder1">
    <parent>yara_decoder</parent>
    <regex>wazuh-yara: (\S+) - Scan result: (\S+) (\S+)</regex>
    <order>log_type, yara_rule, yara_scanned_file</order>
</decoder>
```

This would go into `etc/uses_cases-rules.xml`  (/var/ossec/etc/rules/uses_cases-rules.xml)

```xml
<group name="yara,">
    <rule id="108000" level="0">
        <decoded_as>yara_decoder</decoded_as>
        <description>Yara grouping rule</description>
    </rule>
    <rule id="108001" level="12">
        <if_sid>108000</if_sid>
        <match>wazuh-yara: INFO - Scan result: </match>
        <description>File "$(yara_scanned_file)" is a positive match. Yara rule: $(yara_rule)</description>
    </rule>
</group>
```
### User-dependant configuration: Monitored endpoint

On the endpoint side, we need to declare monitored folders in `/var/ossec/etc/ossec.conf`, like the following example:

```
  <syscheck>
    <directories whodata="yes">/tmp</directories>
  </syscheck>
```

### User-dependant configuration: Manager

User should declare which monitored directories manager should react to, by adding rules to later trigger an active response.
Like the following example:

```xml
<group name="syscheck,">
    <rule id="100300" level="7">
        <if_sid>550</if_sid>
        <field name="file">/tmp</field>
        <description>File modified in /tmp directory.</description>
    </rule>
    <rule id="100301" level="7">
        <if_sid>554</if_sid>
        <field name="file">/tmp</field>
        <description>File added to /tmpdirectory.</description>
    </rule>
</group>
```

Also, the file `/var/ossec/etc/ossec.conf` should be updated to refer to those syscheck events and fire a yara scan accordingly.

```xml
<ossec_config>
    <command>
        <name>yara</name>
        <executable>yara.sh</executable>
        <extra_args>-yara_path /usr/local/bin -yara_rules /tmp/yara_rules.yar</extra_args>
        <expect>filename</expect>
        <timeout_allowed>no</timeout_allowed>
    </command>
    <active-response>
        <command>yara</command>
        <location>local</location>
        <rules_id>100300,100301</rules_id>
        <timeout>600</timeout>
    </active-response>
</ossec_config>
```

### Third party software/files

- [Yara](https://github.com/VirusTotal/yara)
- Yara Rules ([an example](https://github.com/VirusTotal/yara-rules) and [another example](https://github.com/Yara-Rules/rules)  )
- Custom wrapper script yara.sh in `/var/ossec/active-response/bin/yara.sh` with owner/group root:ossec/0750

## Possible approaches and implementation

- `syscheck` rules would be disabled by default on `rules/use_cases.xml`. Documentation will instruct the user how to customize the **desired paths** to be monitored by Yara on both Windows and Linux.
- Similarly, `command` and `active-response` declarations would be disabled by default, and the user will have to enable the relevant configs on `ossec.conf` with desired paths.
- In both cases, it's up to the user to provide with a working Yara installation. Documentation should point to a guide on how to do so.

**Comment by Zenidd** [comment]
The core team previously worked on this use case https://github.com/wazuh/wazuh/issues/3357

**Comment by neonmei** [comment]
closed to un-assign myself, feel free to re-open
