### ISSUE TITLE
Change Wazuh daemons name to Wazuh standard

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#6741]
As part of the initiative of moving from the current project architecture to the Wazuh stack, one of the things that should be done is finally stop using the `ossec` word in the code and instead, make use of `wazuh`.

Considering this, the main goal of this epic is to change the Wazuh daemons names from `ossec-*` to `wazuh-*`. In these changes, the next items should be taken into account:

- Processes to be renamed:

  - `ossec-agentd` -> `wazuh-agentd`
  - `ossec-agentlessd` -> `wazuh-agentlessd`
  - `ossec-analysisd` -> `wazuh-analysisd`
  - `ossec-authd` -> `wazuh-authd`
  - `ossec-csyslogd` -> `wazuh-csyslogd`
  - `ossec-dbd` -> `wazuh-dbd`
  - `ossec-execd` -> `wazuh-execd`
  - `ossec-integratord` -> `wazuh-integratord`
  - `ossec-logcollector` -> `wazuh-logcollector`
  - `ossec-maild` -> `wazuh-maild`
  - `ossec-monitord` -> `wazuh-monitord`
  - `ossec-remoted` -> `wazuh-remoted`
  - `ossec-reportd` -> `wazuh-reportd`
  - `ossec-syscheckd` -> `wazuh-syscheckd`

- Windows:

  - `ossec-agent.exe` -> `wazuh-agent.exe`
  - `ossec-agent-eventchannel.exe` -> `wazuh-agent-eventchannel.exe`
  - `ossec-rootcheck.exe` -> deprecated

### Tasks

- [x]  Modify makefile.

- [x] Modify installer script and upgrade script.

- [x]  Rename state files.

- [x]  Modify all uses of renamed daemons.

- [x]  Modify Wazuh packages to remove old executables.

- [x]  Review all repositories that may use renamed daemons.

- [x]  Change tests (UT / IT) to use new names of processes.

- [x]  Modify documentation talking about renamed daemons.
