### ISSUE TITLE
Change Wazuh tools name to Wazuh standard

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#6766]
The goal of this issue is to standardize the name of the tools placed in a Wazuh installation. Removing those which have been deprecated in older releases.

More particularly, by changing the names of the Wazuh tools from ossec-* to wazuh-*. In these changes, the next items should be taken into account:

- `ossec-control` -> `wazuh-control`
- `ossec-server.sh` -> `wazuh-server.sh`
- `ossec-client.sh` -> `wazuh-client.sh`
- `ossec-local.sh` -> `wazuh-local.sh`
- `ossec-regex` -> `wazuh-regex`

- `rootcheck_control` -> Deprecated
- `syscheck_control` -> Deprecated
- `syscheck_update` -> Deprecated

- `ossec-logtest` -> Deprecated
- `ossec-makelists` -> Deprecated

- `util.sh` -> Deprecated

The next items should be reviewed in order to apply the desired changes:

- [x]  Modify makefile, and installer script to install new tools

- [x] Modify upgrade scripts to install new tools on upgrade and remove old tools

- [x] Review other repositories that may use renamed tools.

- [x] Modify all uses of the renamed tools in this repository.

- [x] Change tests (UT / IT) to use new names of the tools.

- [x] Test every OS (clean install and upgrade).

- [x] Modify documentation talking about renamed tools.

- [x] Modify API and framework references to Wazuh tools.

- [x] Modify Wazuh packages to remove old executables.

https://documentation.wazuh.com/4.0/user-manual/reference/tools/index.html

**Comment by chemamartinez** [comment]
Branch https://github.com/wazuh/wazuh/tree/6766-change-wazuh-tools-name
