### ISSUE TITLE
Remove ossec-logtest from Wazuh

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#6787]
### Description

`ossec-logtest` is deprecated since https://github.com/wazuh/wazuh/issues/5337 which introduces a new tool called `wazuh-logtest`.

According to the new Wazuh naming standard, this deprecated tool should be removed from the code and Wazuh installations.

### Tasks

- [x] Modify the Makefile and installation scripts to avoid its building and installation

- [x] On upgrades it must be uninstalled

- [x] The code exclusive for this tool should be removed

- [x] Check UT and test everything works fine

- [x] Review uses of this tool in this repository and others

**Comment by chemamartinez** [comment]
Merged #6827
