### ISSUE TITLE
Remove ossec-makelists from Wazuh

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#6788]
### Description

The binary `ossec-makelists` is deprecated since https://github.com/wazuh/wazuh/pull/3488 was introduced in 3.11.0. It makes Analysisd building CDB lists on start-up.

According to the new Wazuh naming standard, this deprecated tool should be removed from the code and Wazuh installations.

### Tasks

- [x] Modify the Makefile and installation scripts to avoid its building and installation

- [x] On upgrades it must be uninstalled

- [x] The code exclusive for this tool should be removed

- [x] Check UT and test everything works fine

- [ ] Review uses of this tool in this repository and others

**Comment by chemamartinez** [comment]
Done at #6788
