### ISSUE TITLE
Remove util.sh from the installed binaries

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#6805]
### Description

The script `util.sh` will no longer be installed along with the rest of the Wazuh binaries.

According to the new Wazuh naming standard, this deprecated tool should be removed from the  Wazuh installations.

### Tasks

- [x] Modify the installation scripts to avoid its building and installation

- [x] On upgrades it must be uninstalled

- [x] Review uses of this tool in this repository and others

**Comment by chemamartinez** [comment]
Merged #6809
