### ISSUE TITLE
Rename rotated logs directory according to the new Wazuh naming standard

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#6901]
### Description

The aim of this issue is to rename the directory `logs/ossec` to `logs/wazuh` in this repository. This folder stores the rotated logs and alerts.

### Tasks

- [x] Change all the occurrences of this folder in the source code

- [x] Change all the occurrences of this folder in the UT

- [x] Change the occurrences of this folder in the framework code

- [x] In clean installs, the folder must be installed with the new name

- [x] In upgrades, the folder should be renamed and the content of the folder in the upgrade time must be kept.

**Comment by chemamartinez** [comment]
Merged https://github.com/wazuh/wazuh/pull/6920
