### ISSUE TITLE
[API] Remove behind_proxy_server API option

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#7006]
|Wazuh version|Component|
|---|---|
| 4.2 | Wazuh API |

## Description
Hi team!

After removing, in the following block of code of `POST /agents/insert` endpoint in https://github.com/wazuh/wazuh/issues/7015, the tests and documentation related need to be deleted too.

https://github.com/wazuh/wazuh/blob/eeec711edd16e82c176af5419be732f16119b22f/api/api/controllers/agent_controller.py#L905-L915

## To-do
- [x] Remove `behind_proxy_server` option in the `api.configuration` module (and everywhere it is used -> spec.yaml, etc).
- [x] Update API tavern tests for manager and cluster in case they fail.
- [x] Search and update mentions in the documentation (https://documentation.wazuh.com/4.0/user-manual/api/configuration.html#behind-proxy-server)

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

Kind regards,
Selu.
