### ISSUE TITLE
[API] Missing security headers

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#7024]
|Wazuh version|Component|
|---|---|
| 4.1.x | Wazuh API |

Hi team,

We have reviewed the recommended security headers on the API side. In order to do so, we have followed the next OWASP guide: https://cheatsheetseries.owasp.org/cheatsheets/REST_Security_Cheat_Sheet.html#security-headers. In our case the headers in 4.0.x are the following:
```
adriiiprodri@wazuh curl -k -u wazuh:wazuh -s -D- https://localhost:55040/security/user/authenticate
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Content-Length: 300
Date: Wed, 23 Dec 2020 15:04:16 GMT
Server: Python/3.8 aiohttp/3.6.2

{"data": {"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjA4NzM1ODU2LCJleHAiOjE2MDg3Mzk0NTYsInN1YiI6IndhenVoIiwicnVuX2FzIjpmYWxzZSwicmJhY19yb2xlcyI6WzFdLCJyYmFjX21vZGUiOiJ3aGl0ZSJ9.azsSDosovuhO3uRe9GVfqnD7uyqk0EcuKeIz0092rN0"}, "error": 0}
```
As we can see, we do not fulfill the recommended standard. Therefore, we will implement these safety measures on the API side. To affect performance as least as possible, these headers will be incorporated into the response at the last moment, just before it is sent to the user.

## ToDo
- [x] Implement security headers
- [x] Remove the line with backend information

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by AdriiiPRodri** [comment]
## Status update

Implemented secure headers:

```
adriiiprodri@wazuh curl -k -u wazuh:wazuh -D- https://localhost:55040/security/user/authenticate
HTTP/1.1 200 OK
Server: Secure
Strict-Transport-Security: max-age=63072000; includeSubdomains
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Security-Policy: none
Referrer-Policy: no-referrer, strict-origin-when-cross-origin
Pragma: no-cache
Expires: 0
Cache-control: no-cache, no-store, must-revalidate, max-age=0
Content-Length: 300
Content-Type: application/octet-stream
Date: Thu, 24 Dec 2020 08:57:21 GMT

{"data": {"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjA4ODAwMjQxLCJleHAiOjE2MDg4MDM4NDEsInN1YiI6IndhenVoIiwicnVuX2FzIjpmYWxzZSwicmJhY19yb2xlcyI6WzFdLCJyYmFjX21vZGUiOiJ3aGl0ZSJ9.FPPPZr0HVdH1H5M0ADidTWskxaGsX8-XlloYyU5rroU"}, "error": 0}
```
