### ISSUE TITLE
Refactor ciscat and experimental API integration tests

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#7142]
Hello team,

We should re-evaluate and do some refactor for our current ciscat and experimental API integration test configuration:

https://github.com/wazuh/wazuh/blob/master/api/test/integration/test_ciscat_endpoints.tavern.yaml
https://github.com/wazuh/wazuh/blob/master/api/test/integration/test_experimental_endpoints.tavern.yaml

The current testing environment is generating some results using the ciscat scan module. Such results take sometimes too long to finish on the agents thus causing problems with the automation of the tests. Also, the software needed to run the CIS-CAT scan is heavy loaded to integrate with Jenkins.

We should make API integration tests independent of such software, and just ensure the high level API endpoints are behaving correctly. At the same time, we should improve our current unit tests to manage real ciscat results using an sql schema similar to others like syscheck or syscollector.

## Tasks
- [x] Adapt ciscat and experimental API integration tests to remove the ciscat installation (also related rbac tests)
- [x] Update ciscat unit tests with real data using an sql schema
- [x] Adopt Jenkins integration related measures for automated tests

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)
