### ISSUE TITLE
Change pidfile management in wazuh-clusterd and wazuh-apid to have a generic behavior

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#7190]
Hi team,

When fixing #5011, new bugs were found that need to be fixed.

This issue details one of them:

**Problems:**
1.-`Wazuh-apid` does not create any pidfile when running in foreground, `wazuh-clusterd` does. The pidfile created by a foreground `wazuh-clusterd` daemon is used in the `cluster-control`. If we had no pidfile in this case, we wouldn't be able to see the cluster information with `cluster-control`. In order to have the same behavior when creating pidfiles, `cluster-control` or `wazuh-clusterd` (or both) must be changed.

2.-If you create more than one `wazuh-apid` or `wazuh-clusterd` tasks and kill them, the pidfiles will remain in `/var/ossec/var/run`, but the pids in `/proc` won't. When killing the tasks, the pidfile and pid in both `/var/ossec/var/run` and `/proc` are supposed to be deleted.

**Solution:**
Change the pidfile management in order to have a similar behavior to the rest of daemons (the scripts must remove old pidfiles, kill must kill the process and remove its corresponding pidfile, etc.).

Regards,
Manuel.

**Comment by AdriiiPRodri** [comment]
Hi team,

As my teammate indicates, there are several inconsistencies in the `wazuh-apid` and `wazuh-clusterd` daemons. We will expose these issues along with the test performed:

We start from a totally clean environment with the `master` branch changes as of `06/21/21`:

#### Processes
```
root@wazuh-master:/# ps -edf ww
UID          PID    PPID  C STIME TTY      STAT   TIME CMD
root           1       0  0 07:10 ?        Ss     0:00 bash /scripts/entrypoint.sh wazuh-master master-node master
root        1147       1  0 07:10 ?        S      0:00 /usr/bin/python3 /usr/bin/supervisord
root        1195    1147  0 07:10 ?        S      0:00 sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups
root        1554       0  0 07:23 pts/0    Ss     0:00 bash
root        1566       0  0 07:23 pts/1    Ss+    0:00 bash
wazuh       1771       1  2 07:24 ?        Sl     0:06 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
root        1810       1  0 07:24 ?        Sl     0:00 /var/ossec/bin/wazuh-authd
wazuh       1826       1  0 07:24 ?        Sl     0:00 /var/ossec/bin/wazuh-db
root        1849       1  0 07:24 ?        Sl     0:00 /var/ossec/bin/wazuh-execd
wazuh       1860       1  0 07:24 ?        Sl     0:00 /var/ossec/bin/wazuh-analysisd
root        1869       1  1 07:24 ?        SNl    0:03 /var/ossec/bin/wazuh-syscheckd
wazuh       2047       1  0 07:24 ?        Sl     0:00 /var/ossec/bin/wazuh-remoted
root        2114       1  0 07:24 ?        Sl     0:00 /var/ossec/bin/wazuh-logcollector
wazuh       2130       1  0 07:24 ?        Sl     0:00 /var/ossec/bin/wazuh-monitord
root        2139       1  0 07:24 ?        Sl     0:00 /var/ossec/bin/wazuh-modulesd
wazuh       2481       1  0 07:24 ?        S      0:02 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
root        3238    1554  0 07:29 pts/0    R+     0:00 ps -edf ww
```

#### /proc
```
root@wazuh-master:/# ls /proc/ | grep -Eo '[0-9]{1,4}'
1 1147  1195  1554  1566  1771  1810  1826  1849  1860  1869  2047  2114  2130  2139  2481  3268  3269
```

#### /var/ossec/var/run
```
root@wazuh-master:/# ls /var/ossec/var/run/
wazuh-analysisd-1860.pid  wazuh-apid-1771.pid   wazuh-clusterd-2481.pid  wazuh-execd-1849.pid         wazuh-logcollector.state  wazuh-monitord-2130.pid  wazuh-remoted.state
wazuh-analysisd.state     wazuh-authd-1810.pid  wazuh-db-1826.pid        wazuh-logcollector-2114.pid  wazuh-modulesd-2139.pid   wazuh-remoted-2047.pid   wazuh-syscheckd-1869.pid
```

#### Status
```
root@wazuh-master:/# service wazuh-manager status
wazuh-clusterd is running...
wazuh-modulesd is running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd is running...
wazuh-maild not running...
wazuh-execd is running...
wazuh-db is running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid is running...
```

As we can see, everything is correct, both the API and the cluster are working correctly and both have a PID file in `/var/ossec/var/run`.

### 1st test
Kill the API process using the `kill` command:
```
root@wazuh-master:/# kill 1771
root@wazuh-master:/# ps -edf ww
UID          PID    PPID  C STIME TTY      STAT   TIME CMD
root           1       0  0 07:10 ?        Ss     0:00 bash /scripts/entrypoint.sh wazuh-master master-node master
root        1147       1  0 07:10 ?        S      0:00 /usr/bin/python3 /usr/bin/supervisord
root        1195    1147  0 07:10 ?        S      0:00 sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups
root        1554       0  0 07:23 pts/0    Ss     0:00 bash
root        1566       0  0 07:23 pts/1    Ss+    0:00 bash
root        1810       1  0 07:24 ?        Sl     0:01 /var/ossec/bin/wazuh-authd
wazuh       1826       1  0 07:24 ?        Sl     0:03 /var/ossec/bin/wazuh-db
root        1849       1  0 07:24 ?        Sl     0:00 /var/ossec/bin/wazuh-execd
wazuh       1860       1  0 07:24 ?        Sl     0:00 /var/ossec/bin/wazuh-analysisd
root        1869       1  0 07:24 ?        SNl    0:03 /var/ossec/bin/wazuh-syscheckd
wazuh       2047       1  0 07:24 ?        Sl     0:03 /var/ossec/bin/wazuh-remoted
root        2114       1  0 07:24 ?        Sl     0:00 /var/ossec/bin/wazuh-logcollector
wazuh       2130       1  0 07:24 ?        Sl     0:00 /var/ossec/bin/wazuh-monitord
root        2139       1  0 07:24 ?        Sl     0:00 /var/ossec/bin/wazuh-modulesd
wazuh       2481       1  0 07:24 ?        S      0:10 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
root        3336    1554  0 08:10 pts/0    R+     0:00 ps -edf ww
```

The file `1771` no longer exists in the `/proc` folder, but it does in the `/var/ossec/var/run` folder:
```
root@wazuh-master:/# ls /proc/ | grep 1771
root@wazuh-master:/# ls /var/ossec/var/run/
wazuh-analysisd-1860.pid  wazuh-apid-1771.pid   wazuh-clusterd-2481.pid  wazuh-execd-1849.pid         wazuh-logcollector.state  wazuh-monitord-2130.pid  wazuh-remoted.state
wazuh-analysisd.state     wazuh-authd-1810.pid  wazuh-db-1826.pid        wazuh-logcollector-2114.pid  wazuh-modulesd-2139.pid   wazuh-remoted-2047.pid   wazuh-syscheckd-1869.pid
```

As a comparison let's use the behavior of `wazuh-modulesd`, we do the same process:
```
root@wazuh-master:/# ps -edf ww
UID          PID    PPID  C STIME TTY      STAT   TIME CMD
root           1       0  0 07:10 ?        Ss     0:00 bash /scripts/entrypoint.sh wazuh-master master-node master
root        1147       1  0 07:10 ?        S      0:00 /usr/bin/python3 /usr/bin/supervisord
root        1195    1147  0 07:10 ?        S      0:00 sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups
root        1554       0  0 07:23 pts/0    Ss     0:00 bash
root        1566       0  0 07:23 pts/1    Ss+    0:00 bash
root        1810       1  0 07:24 ?        Sl     0:01 /var/ossec/bin/wazuh-authd
wazuh       1826       1  0 07:24 ?        Sl     0:04 /var/ossec/bin/wazuh-db
root        1849       1  0 07:24 ?        Sl     0:00 /var/ossec/bin/wazuh-execd
wazuh       1860       1  0 07:24 ?        Sl     0:00 /var/ossec/bin/wazuh-analysisd
root        1869       1  0 07:24 ?        SNl    0:03 /var/ossec/bin/wazuh-syscheckd
wazuh       2047       1  0 07:24 ?        Sl     0:04 /var/ossec/bin/wazuh-remoted
root        2114       1  0 07:24 ?        Sl     0:00 /var/ossec/bin/wazuh-logcollector
wazuh       2130       1  0 07:24 ?        Sl     0:00 /var/ossec/bin/wazuh-monitord
root        2139       1  0 07:24 ?        Sl     0:00 /var/ossec/bin/wazuh-modulesd
wazuh       2481       1  0 07:24 ?        S      0:12 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
root        3369    1554  0 08:19 pts/0    R+     0:00 ps -edf ww
root@wazuh-master:/# kill 2139
root@wazuh-master:/# ls /var/ossec/var/run/
wazuh-analysisd-1860.pid  wazuh-authd-1810.pid     wazuh-db-1826.pid     wazuh-logcollector-2114.pid  wazuh-monitord-2130.pid  wazuh-remoted.state
wazuh-analysisd.state     wazuh-clusterd-2481.pid  wazuh-execd-1849.pid  wazuh-logcollector.state     wazuh-remoted-2047.pid   wazuh-syscheckd-1869.pid
```

Here can be seen how `wazuh-modulesd` has no pidfile in `/var/ossec/var/run`. This is the right behavior.

Once we have the API stopped and its file is in `/var/ossec/var/run`, if we launch a status, we can see how the error is solved:

```
root@wazuh-master:/# service wazuh-manager status
wazuh-clusterd is running...
wazuh-modulesd is running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd is running...
wazuh-maild not running...
wazuh-execd is running...
wazuh-db is running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid: Process 1771 not used by Wazuh, removing...
wazuh-apid not running...
```
### 2nd test
Unlike other daemons, when the API is started in foreground mode, the user is not notified of its PID:

```
root@wazuh-master:/# /var/ossec/bin/wazuh-apid -f
Starting API in foreground
2021/06/21 08:20:37 INFO: Listening on 0.0.0.0:55000..
======== Running on https://0.0.0.0:55000 ========
(Press CTRL+C to quit)
```

However, in the case of `wazuh-modulesd` it does appear:
```
root@wazuh-master:/# /var/ossec/bin/wazuh-modulesd -f
2021/06/21 08:21:15 wazuh-modulesd: INFO: Started (pid: 3441).
2021/06/21 08:21:35 wazuh-modulesd:agent-upgrade: INFO: (8153): Module Agent Upgrade started.
```

We consider that it could be useful for the user to be notified of the PID of the API in foreground mode.

### 3rd test
When we launch the API in foreground mode, its PID file is not created, which causes that wazuh does not know that it is working:

```
root@wazuh-master:/# /var/ossec/bin/wazuh-apid -f
Starting API in foreground
2021/06/21 08:20:37 INFO: Listening on 0.0.0.0:55000..
======== Running on https://0.0.0.0:55000 ========
(Press CTRL+C to quit)
```

```
root@wazuh-master:/# ls /var/ossec/var/run/
wazuh-analysisd-1860.pid  wazuh-authd-1810.pid     wazuh-db-1826.pid     wazuh-logcollector-2114.pid  wazuh-monitord-2130.pid  wazuh-remoted.state
wazuh-analysisd.state     wazuh-clusterd-2481.pid  wazuh-execd-1849.pid  wazuh-logcollector.state     wazuh-remoted-2047.pid   wazuh-syscheckd-1869.pid
```

We can also see that two processes appear:

```
root@wazuh-master:/# ps -edf ww | grep apid
root        3371    1566  0 08:20 pts/1    S+     0:00 /bin/sh /var/ossec/bin/wazuh-apid -f
wazuh       3376    3371 11 08:20 pts/1    Sl+    0:10 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py -f
root        3387    1554  0 08:22 pts/0    S+     0:00 grep --color=auto apid
```

One of them is a child of the other, the parent is the API binary itself and the child is the python process. One of the things we could modify is this, ideally, only one process should be present. Note: This also happens with `wazuh-clusterd`.

On the other hand, as it does not have a PID file we have that when doing a status, it is not detected as active:

```
root@wazuh-master:/# service wazuh-manager status
wazuh-clusterd is running...
wazuh-modulesd not running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd is running...
wazuh-maild not running...
wazuh-execd is running...
wazuh-db is running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid not running...
```

This same case with `modulesd` does not occur:

```
root@wazuh-master:/# /var/ossec/bin/wazuh-modulesd -f
2021/06/21 08:23:57 wazuh-modulesd: INFO: Started (pid: 3441).
2021/06/21 08:23:57 wazuh-modulesd:agent-upgrade: INFO: (8153): Module Agent Upgrade started.
```

```
root@wazuh-master:/# service wazuh-manager status
wazuh-clusterd is running...
wazuh-modulesd is running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd is running...
wazuh-maild not running...
wazuh-execd is running...
wazuh-db is running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid not running...
```

```
root@wazuh-master:/# ps -edf ww
UID          PID    PPID  C STIME TTY      STAT   TIME CMD
root           1       0  0 07:10 ?        Ss     0:00 bash /scripts/entrypoint.sh wazuh-master master-node master
root        1147       1  0 07:10 ?        S      0:00 /usr/bin/python3 /usr/bin/supervisord
root        1195    1147  0 07:10 ?        S      0:00 sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups
root        1554       0  0 07:23 pts/0    Ss     0:00 bash
root        1566       0  0 07:23 pts/1    Ss     0:00 bash
root        1810       1  0 07:24 ?        Sl     0:01 /var/ossec/bin/wazuh-authd
wazuh       1826       1  0 07:24 ?        Sl     0:04 /var/ossec/bin/wazuh-db
root        1849       1  0 07:24 ?        Sl     0:00 /var/ossec/bin/wazuh-execd
wazuh       1860       1  0 07:24 ?        Sl     0:00 /var/ossec/bin/wazuh-analysisd
root        1869       1  0 07:24 ?        SNl    0:03 /var/ossec/bin/wazuh-syscheckd
wazuh       2047       1  0 07:24 ?        Sl     0:04 /var/ossec/bin/wazuh-remoted
root        2114       1  0 07:24 ?        Sl     0:00 /var/ossec/bin/wazuh-logcollector
wazuh       2130       1  0 07:24 ?        Sl     0:00 /var/ossec/bin/wazuh-monitord
wazuh       2481       1  0 07:24 ?        S      0:13 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
root        3441    1566  4 08:23 pts/1    Sl+    0:00 /var/ossec/bin/wazuh-modulesd -f
root        3995    1554  0 08:24 pts/0    R+     0:00 ps -edf ww
root@wazuh-master:/# ls /var/ossec/var/run/
wazuh-analysisd-1860.pid  wazuh-authd-1810.pid     wazuh-db-1826.pid     wazuh-logcollector-2114.pid  wazuh-modulesd-3441.pid  wazuh-remoted-2047.pid  wazuh-syscheckd-1869.pid
wazuh-analysisd.state     wazuh-clusterd-2481.pid  wazuh-execd-1849.pid  wazuh-logcollector.state     wazuh-monitord-2130.pid  wazuh-remoted.state
```

As for `clusterd`, as Manuel says, we have that if its PID file is created and therefore, its status is detected:

```
root@wazuh-master:/# /var/ossec/bin/wazuh-clusterd -f
2021/06/21 08:54:30 INFO: [Local Server] [Main] Serving on /var/ossec/queue/cluster/c-internal.sock
2021/06/21 08:54:30 INFO: [Master] [Main] Serving on ('0.0.0.0', 1516)
2021/06/21 08:54:30 INFO: [Master] [Local integrity] Starting.
2021/06/21 08:54:30 INFO: [Master] [Local integrity] Finished in 0.003s. Calculated metadata of 21 files.
```

```
root@wazuh-master:/# ps -edf ww
UID          PID    PPID  C STIME TTY      STAT   TIME CMD
root           1       0  0 07:10 ?        Ss     0:00 bash /scripts/entrypoint.sh wazuh-master master-node master
root        1147       1  0 07:10 ?        S      0:01 /usr/bin/python3 /usr/bin/supervisord
root        1195    1147  0 07:10 ?        S      0:00 sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups
root        1554       0  0 07:23 pts/0    Ss     0:00 bash
root        1566       0  0 07:23 pts/1    Ss     0:00 bash
wazuh       7581       1  1 08:47 ?        Sl     0:07 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
root        7620       1  0 08:47 ?        Sl     0:00 /var/ossec/bin/wazuh-authd
wazuh       7636       1  0 08:47 ?        Sl     0:00 /var/ossec/bin/wazuh-db
root        7659       1  0 08:47 ?        Sl     0:00 /var/ossec/bin/wazuh-execd
wazuh       7670       1  0 08:47 ?        Sl     0:00 /var/ossec/bin/wazuh-analysisd
root        7679       1  0 08:47 ?        SNl    0:03 /var/ossec/bin/wazuh-syscheckd
wazuh       7855       1  0 08:47 ?        Sl     0:00 /var/ossec/bin/wazuh-remoted
root        7916       1  0 08:47 ?        Sl     0:00 /var/ossec/bin/wazuh-logcollector
wazuh       7932       1  0 08:47 ?        Sl     0:00 /var/ossec/bin/wazuh-monitord
root        7982       1  0 08:47 ?        Sl     0:00 /var/ossec/bin/wazuh-modulesd
root        9063    1566  0 08:54 pts/1    S+     0:00 /bin/sh /var/ossec/bin/wazuh-clusterd -f
wazuh       9068    9063  8 08:54 pts/1    S+     0:02 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py -f
root        9070    1554  0 08:54 pts/0    R+     0:00 ps -edf ww
root@wazuh-master:/# ls /var/ossec/var/run/
wazuh-analysisd-7670.pid  wazuh-apid-7581.pid   wazuh-clusterd-8335.pid  wazuh-db-7636.pid     wazuh-logcollector-7916.pid  wazuh-modulesd-7982.pid  wazuh-remoted-7855.pid  wazuh-syscheckd-7679.pid
wazuh-analysisd.state     wazuh-authd-7620.pid  wazuh-clusterd-9068.pid  wazuh-execd-7659.pid  wazuh-logcollector.state     wazuh-monitord-7932.pid  wazuh-remoted.state
```

```
root@wazuh-master:/# service wazuh-manager status
wazuh-clusterd: Process 8335 not used by Wazuh, removing...
wazuh-clusterd is running...
wazuh-modulesd is running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd is running...
wazuh-maild not running...
wazuh-execd is running...
wazuh-db is running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid is running...
```

### ToDo

- [ ] Investigate the behavior of `wazuh-control status`.
- [ ] Print the PID when starting in foreground mode both the API and the cluster.
- [ ] Handle the kill signal so that both the API and the cluster delete the file inside `/var/ossec/var/run`.
- [ ] Check why the API does not create the PID file when starting in foreground mode.

**Comment by AdriiiPRodri** [comment]
## Status update

### New startup message and cleaning orphan files
#### API
```
root@wazuh-master:/# ps -edf ww
UID          PID    PPID  C STIME TTY      STAT   TIME CMD
root           1       0  0 08:30 ?        Ss     0:00 bash /scripts/entrypoint.sh wazuh-master master-node master
wazuh         70       1 37 08:30 ?        Sl     0:07 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
root         109       1  0 08:30 ?        Sl     0:00 /var/ossec/bin/wazuh-authd
wazuh        125       1  3 08:31 ?        Sl     0:00 /var/ossec/bin/wazuh-db
root         148       1  0 08:31 ?        Sl     0:00 /var/ossec/bin/wazuh-execd
wazuh        159       1  2 08:31 ?        Sl     0:00 /var/ossec/bin/wazuh-analysisd
root         168       1 18 08:31 ?        SNl    0:03 /var/ossec/bin/wazuh-syscheckd
wazuh        343       1  0 08:31 ?        Sl     0:00 /var/ossec/bin/wazuh-remoted
root         401       1  0 08:31 ?        Sl     0:00 /var/ossec/bin/wazuh-logcollector
wazuh        417       1  0 08:31 ?        Sl     0:00 /var/ossec/bin/wazuh-monitord
root         426       1  2 08:31 ?        Sl     0:00 /var/ossec/bin/wazuh-modulesd
wazuh        628       1 13 08:31 ?        S      0:02 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
root        1004       1  1 08:31 ?        S      0:00 /usr/bin/python3 /usr/bin/supervisord
root        1050    1004  0 08:31 ?        S      0:00 sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups
root        1284       0  0 08:31 pts/0    Ss     0:00 bash
root        1371    1284  0 08:31 pts/0    R+     0:00 ps -edf ww
root@wazuh-master:/# kill -9 70
root@wazuh-master:/# /var/ossec/bin/wazuh-apid -f
wazuh-apid: Process 70 not used by Wazuh, removing...
Starting API in foreground (pid: 1378)
2021/06/22 08:31:52 INFO: Listening on 0.0.0.0:55000..
======== Running on https://0.0.0.0:55000 ========
(Press CTRL+C to quit)
```

#### Cluster
```
root@wazuh-master:/# ps -edf ww
UID          PID    PPID  C STIME TTY      STAT   TIME CMD
root           1       0  0 08:30 ?        Ss     0:00 bash /scripts/entrypoint.sh wazuh-master master-node master
root         109       1  0 08:30 ?        Sl     0:00 /var/ossec/bin/wazuh-authd
wazuh        125       1  3 08:31 ?        Sl     0:03 /var/ossec/bin/wazuh-db
root         148       1  0 08:31 ?        Sl     0:00 /var/ossec/bin/wazuh-execd
wazuh        159       1  2 08:31 ?        Sl     0:02 /var/ossec/bin/wazuh-analysisd
root         168       1  4 08:31 ?        SNl    0:03 /var/ossec/bin/wazuh-syscheckd
wazuh        343       1  1 08:31 ?        Sl     0:01 /var/ossec/bin/wazuh-remoted
root         401       1  0 08:31 ?        Sl     0:00 /var/ossec/bin/wazuh-logcollector
wazuh        417       1  0 08:31 ?        Sl     0:00 /var/ossec/bin/wazuh-monitord
root         426       1  0 08:31 ?        Sl     0:00 /var/ossec/bin/wazuh-modulesd
wazuh        628       1  2 08:31 ?        S      0:02 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
root        1004       1  0 08:31 ?        S      0:00 /usr/bin/python3 /usr/bin/supervisord
root        1050    1004  0 08:31 ?        S      0:00 sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups
root        1284       0  0 08:31 pts/0    Ss     0:00 bash
root        1384    1284  0 08:32 pts/0    R+     0:00 ps -edf ww
root@wazuh-master:/# kill -9 628
root@wazuh-master:/# /var/ossec/bin/wazuh-clusterd -f
wazuh-clusterd: Process 628 not used by Wazuh, removing...
Starting cluster in foreground (pid: 1390)
2021/06/22 08:32:40 INFO: [Local Server] [Main] Serving on /var/ossec/queue/cluster/c-internal.sock
2021/06/22 08:32:40 INFO: [Master] [Main] Serving on ('0.0.0.0', 1516)
2021/06/22 08:32:40 INFO: [Master] [Local integrity] Starting.
2021/06/22 08:32:40 INFO: [Master] [Local integrity] Finished in 0.004s. Calculated metadata of 21 files.
2021/06/22 08:32:42 INFO: [Worker] [Main] Connection from ('172.27.0.4', 57320)

```
