### ISSUE TITLE
Develop a maintenance plan for Python

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#7224]
Hello team,

As part of the migration to the new versions of Python, we need to check that none of our libraries, as well as the new version of Python, have vulnerabilities.

Tasks:
- [x] Automate as much as possible the change of Python version.
- [x] Investigate the different static code analyzers for Python and create a list of trusted resources (websites, scanners, etc) to check against the versions used by Wazuh.
- [x] Integrate a static code analyzer into the development process.
- [x] Fix the current flaws in the code.
- [ ] Add an analysis tool to the Wazuh repository testing process.

Regards,
Adrián Peña
