### ISSUE TITLE
Investigate API and cluster performance in loaded environments

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#7366]
Hello team,

As part of the investigation for https://github.com/wazuh/wazuh/issues/6744 we discovered several performance issues with the API and the cluster in very big environments (30k+ agents, 4+ worker nodes). Some of these problems lead to API timeouts or a very slow loading page from Wazuh WUI.

We should use AWS available tools to deploy environments as realistic as possible to do further testing for every API endpoint and to measure several performance metrics for the API and the cluster.

### **Tasks:**

  - [x] Investigate and define the most appropriate way to deploy and replicate as realistically as possible a very big Wazuh clustered environment.
  - [x] Design and develop the necessary tools to deploy such environment (python scripts, images for AWS, packages, etc)
  - [x] Investigate and define performance metrics (Wazuh API requests time, cluster synchronization time, wazuh-db access time, processes cpu, processes memory, etc)
  - [x] Design scripts for API and cluster load
  - [x] Design and develop API tests in loaded environment
  - [x] Fix the encountered issues (API, cluster, etc)
   
Best regards,

David J. Iglesias
