### ISSUE TITLE
Adapt the binaries to work under the install directory

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#7430]
### Description

Once the binaries know where Wazuh is installed. Use `chdir()` to change the current working directory for that process to the Wazuh installation directory.

That way, we avoid the need of working with absolute paths when accessing queues and files.

### Subtasks

- [x] Remove the `BUILDDIR` and `HOMEDIR` MACROs
- [x] `w_homedir()` should check the directory is valid, as it was done in `HOMEDIR`
- [x] The main of each binary has to move to the new current working directory
- [x] Adapt references to absolute directories
- [x] Adapt unit tests

### Affected components

- [x] Shared files

- [x] Analysisd

- [x] Agentd

- [x] Remoted

- [x] Wazuh modulesd

- [x] Agentless

- [x] Integratord 

- [x] Rootcheck

- [x] Syscheck

- [x] Logcollector

- [x] Authd

- [x] Wazuh DB

- [x] DB output (os_dbd)

- [x] Maild

- [x] Monitord

- [x] Reportd

- [x] Execd

- [x] Csyslogd

- [x] Addagent

- [x] Utils (agent_control, verify_agent_conf, ...)
