### ISSUE TITLE
Refactor security checks for the orm module

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#7542]
|Wazuh version|Component|
|---|---|
| 4.2.0 | Wazuh Framework |

Hello team,

As part of the epic issue #6652 , we need to apply the following changes:
- Remove `force_admin` parameter from the `orm`. This was previosly used as a way to ensure no default resources could be removed or updated by the user. This is no longer needed as we have a better way to manage this using  `resource_type`. 
- Remove `check_default` parameter from the `orm`. Same reasoning as above.
- Remove any `max_id_reserved` check from the `orm`. This check is still needed, but it should be performed outside the `orm`. The idea is to perform no security checks when the ORM is applying any change to the database. Those checks and restrictions should be applied outside the `orm` module, in the `security` module or in any other intermediate layer. This way, it will be possible to import and use the `orm` module within the framework, skipping any security restriction such as `resource_type` or `reserved_range` protection, allowing us to use this module to manually add new default resources or modify the existing ones, such as changing the password of a default user

## Tasks
- [ ] Apply necessary changes to remove the `force_admin` parameter.
- [ ] Apply the required changes to remove the `check_default` parameter.
- [ ] Remove from the `orm` any security check such as `reserved_range` protection and implement them in `security.py` or any other appropiate layer.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Changelog (`CHANGELOG.md`)
