### ISSUE TITLE
Classify MITRE information in the DB

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#7607]
### Description

MITRE information is retrieved from the JSON file `enterprise-attack.json`. This file is used to create and populate the MITRE DB, which is located in the path `/var/ossec/var/db/mitre.db`.

The information from the JSON file is stored in the DB but it is not classified, so each DB entry has only a MITRE technique ID and the full JSON related to that technique.

The idea of this epic is to classify this information in the DB, so it becomes simpler and more organized to query.

The following tasks should be done:

- [x] Replace MITRE JSON file with the [latest version](https://github.com/mitre/cti/blob/master/enterprise-attack/enterprise-attack.json).
- [x] Analyze and classify the information from the JSON file into DB tables.
- [x] Modify the script that creates the MITRE DB with the new structure.
- [x] Adapt all the components that consume information from this DB.
