### ISSUE TITLE
Split SecurityError.ALREADY_EXIST error code into two different error codes

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#7804]
Hello team,

We need to expand the `orm.py` functionality to be able to determine when `PoliciesManager.add_policy` returns a `SecurityError.ALREADY_EXIST` error because there is already a policy with the same name and when this error is returned because there is a policy with a different name but the same policy body.

## Tasks
- [x] Add a new SecurityError code for that particular case
- [x] Update the add_policy function to ensure the right error code is returned in any case

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

**Comment by CarlosRS9** [comment]
# Status update

The development is finished. Here is the list of changed introduced:
- New `SecurityError` error code added (`POLICY_BODY_ALREADY_EXIST`)
- `add_policy` function in `orm` module updated to use the new `SecurityError`
- New exception (4027) has been added.
- `security` module updated to use the new exception.
- `test_orm` unit test updated accordingly.
- API security integration tests updated accordingly

**Comment by CarlosRS9** [comment]
# Status update

The `POLICY_BODY_ALREADY_EXIST` error code has been renamed to `CONSTRAINT_ERROR` so we can use it in other places. Few changes have been applied to made use of this new error code.
