### ISSUE TITLE
[AWS Integration] Add support for s3 access logs in AWS module

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh#7811]
Hello team,

As part of Wazuh's continuous effort towards improvement, we should include support for AWSs3 access logs in our AWS module.

**Description:**
This development should include support for the following logs:

- Amazon S3 server access: https://docs.aws.amazon.com/AmazonS3/latest/userguide/LogFormat.html

**Design:**
As part of the development, we should update the Wazuh AWS module to support the processing of the new logs. 

Also, we should update the Monitoring AWS-based services documentation to add the new supported services, their configuration, and use case examples.

Lastly, we should update the Wazuh AWS ruleset to support the added services and generate new alerts for these logs.

**Tasks:**
 - [x] Investigate access logs 
 - [x] Add support for new logs in AWS module python script
 - [x] Add configuration support changes to ossec.conf
 - [x] Test use cases in a real setup using AWS
 - [ ] Add new rules for AWS ruleset
 - [x] Update/Add new documentation for ossec.conf and services
 - [x] Update changelog.md

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by fhielpos** [comment]
Possible rules for this kind of events:

```
<group name="amazon, aws, s3">

  <rule id="200000" level="0">
    <if_sid>80200</if_sid>
    <field name="aws.source">s3_access_logs</field>
    <description>AWS S3 Access Log events group</description>
  </rule>

  <rule id="200001" level="5">
    <if_sid>200000</if_sid>
    <field name="aws.operation">DELETE</field>
    <description>AWS S3: DELETE operation: $(aws.request_uri)</description>
  </rule>

  <rule id="200010" level="3">
    <if_sid>200000</if_sid>
    <field name="aws.operation">GET</field>
    <description>AWS S3: GET operation: $(aws.request_uri)</description>
  </rule>

  <!-- Silence general REST.GET.OBJECT with status code 200 -->
  <rule id="200011" level="0">
    <if_sid>200010</if_sid>
    <field name="aws.operation">^REST.GET.OBJECT$</field>
    <field name="aws.htt_status">200</field>
    <description>AWS S3: GET with 200 status code</description>
  </rule>

  <rule id="200020" level="3">
    <if_sid>200000</if_sid>
    <field name="aws.operation">PUT</field>
    <description>AWS S3: PUT operation: $(aws.request_uri)</description>
  </rule>

  <!-- Silence events when S3 puts a file into the bucket -->
  <rule id="200021" level="0">
    <if_sid>200020</if_sid>
    <field name="aws.requester">^svc:s3.amazonaws.com$</field>
    <description>AWS S3: PUT operation: $(aws.request_uri) from S3 service</description>
  </rule>

  <rule id="200030" level="3">
    <if_sid>200000</if_sid>
    <field name="aws.operation">POST</field>
    <description>AWS S3: POST operation: $(aws.request_uri)</description>
  </rule>

</group>
```

**Comment by CarlosRS9** [comment]
## Issue update

I have been researching how the S3 service access logging works and how it should be integrated into our AWS module. The logging is performed by indicating which bucket you want to monitor and in which bucket you want to store the resulting logs.

`Boto3` does not have its own functionality for such service, but in theory it will be enough to download the logs from that bucket (in a similar way as a custom integration) and process those logs.

**Comment by CarlosRS9** [comment]
## Issue update
I have started with the implementation for this new type of buckets. This will not be a new service, but a new type of supported bucket, just like `WAF`, `CLB`, `ALB` or `NLB`, since the information is accessible in AWS within a bucket, not through a service.

It is almost done. I'm an currently working on an issue with the `time` field format.

**Comment by CarlosRS9** [comment]
## Issue update

The `s3_server_access` support has been added to the `aws-s3` module and core. It has been necessary to implement custom solution to avoid the usage of the `csv.DictReader`, which is used in the other custom bucket implementations, to be able to deal with the`time` field format issue, as it contains a empty space (`[%d/%b/%Y:%H:%M:%S %z]`)

Here is an example of an event before applying the fix:

```
{
    "integration": "aws",
    "aws": {
        "log_info": {
            "aws_account_alias": "",
            "log_file": "s3_server_access/2020-10-28-11-20-19-3608821FC36364A4",
            "s3bucket": "wazuh-aws-wodle-access-logs"
        },
        "bucket_owner": "3ab1235e25ea9e94ff9b7e4e379ba6b0c872cd36c096e1ac8cce7df433b47101",
        "bucket": "wazuh-aws-wodle",
        "time": "[28/Oct/2020:10:58:10",
        "remote_ip": "+0000]",
        "requester": "IP",
        "request_id": "arn:aws:iam::123123123123:user/name",
        "operation": "439E89589139B20F",
        "key": "REST.GET.OBJECT",
        "request_uri": "AWSLogs/123123123123/CloudTrail/us-west-1/2020/10/28/123123123123_CloudTrail_us-west-1_20201028T1040Z_g35t2mAJyTpGTTzU.json.gz",
        "http_status": "GET /AWSLogs/123123123123/CloudTrail/us-west-1/2020/10/28/123123123123_CloudTrail_us-west-1_20201028T1040Z_g35t2mAJyTpGTTzU.json.gz HTTP/1.1",
        "error_code": "200",
        "bytes_sent": "-",
        "object_sent": "2261",
        "total_time": "2261",
        "turn_around_time": "32",
        "referer": "31",
        "user_agent": "-",
        "host_id": "Boto3/1.13.1 Python/3.8.2 Linux/4.14.114-105.126.amzn2.x86_64 Botocore/1.16.1",
        "signature_version": "-",
        "cipher_suite": "pX/E8R4mWoR1T0iF5aRSKyweDX3EbxxpLJ1PwmKFfUdM7it113PIMYh+urKIQJOCu2k5DPdKGmw=",
        "authentication_type": "SigV4",
        "host_header": "ECDHE-RSA-AES128-GCM-SHA256",
        "tls_version": "AuthHeader",
        "null": ["wazuh-aws-wodle.s3.amazonaws.com", "TLSv1.2"],
        "source": "access_log"
    }
}
```

As we can see, the `time` field, is wrongly splitted into two fields because of the offset value, making the rest of the values of the alert not to match with their corresponding fields. Because of this, we decided to implement a customised solution instead of the aforementioned `csv.dictReader`. To determine the feasibility of such a custom solution, we have performed some performance tests.


### Performance Tests


For this performance test we have created a log file with `10000000` real logs and processed it using the `csv.dictReader` solution (hence having the mentioned issue regading the `time` field value) and the custom solution proposed. Here are the results:

| Implementation | Elapdsed Time |
|-|-|
| csv.dictReader | 24,17 s |
| Custom solution | 20,99 s |


As we can see, the proposed solution is faster than the `csv.dictReader` functionality while fixing the aforementioned `time` field issue at the same time.




### Usage example


As specified at the beginning of the development, we have added support for `S3 Server Access logging` as a new bucket type using our custom bucket integration, since it is not a service like `CloudWatchLogs` or `Inspector`. It works in a similar way to the `WAF` integration.

Here is an example of configuration:

```
<wodle name="aws-s3">
  <disabled>no</disabled>
  <interval>5m</interval>
  <run_on_start>yes</run_on_start>
  <skip_on_error>no</skip_on_error>
  <remove_from_bucket>no</remove_from_bucket>
  <bucket type="server_access">
    <name>wazuh-aws-wodle-access-logs</name>
    <aws_profile>default</aws_profile>
  </bucket>
</wodle>
```

This new bucket only requires the name of the bucket and no additional parameters.


Here is an example of how to test it manually:
```
root@wazuh-master:/var/ossec/wodles/aws/performance# /var/ossec/wodles/aws/aws-s3 -t server_access -b wazuh-aws-wodle-access-logs -a $ACCESS -k $KEY -d 2
```

Example output:
```
DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Table does not exist; create
DEBUG: +++ Marker: 2021/04/28
DEBUG: ++ Found new log: s3_server_access/
DEBUG: ++ Found new log: s3_server_access/2020-10-28-11-19-11-6F1508DAB5754BAC
DEBUG: ++ Found new log: s3_server_access/2020-10-28-11-19-24-BCCBB76650EF1720
DEBUG: ++ Found new log: s3_server_access/2020-10-28-11-19-25-7A1CC48BB572E8BD
DEBUG: ++ Found new log: s3_server_access/2020-10-28-11-19-34-9BE3B01526CD52D2
DEBUG: ++ Found new log: s3_server_access/2020-10-28-11-19-36-94E793EEBC55FA97
```

Example event:
```
{
    "integration": "aws",
    "aws": {
        "log_info": {
            "aws_account_alias": "",
            "log_file": "s3_server_access/2020-10-28-11-20-00-4A830EF7F088E06E",
            "s3bucket": "wazuh-aws-wodle-access-logs"
        },
        "bucket_owner": "3ab1235e25ea9e94ff9b7e4e379ba6b0c872cd36c096e1ac8cce7df433b47101",
        "bucket": "wazuh-aws-wodle",
        "time": "28/Oct/2020:10:54:25 +000",
        "remote_ip": "IP",
        "requester": "arn:aws:iam::123123123123:user/name",
        "request_id": "69A7D09FE762DE99",
        "operation": "REST.GET.OBJECT",
        "key": "config/AWSLogs/123123123123/Config/us-east-1/2019/2/5/ConfigSnapshot/123123123123_Config_us-east-1_ConfigSnapshot_20190205T105551Z_6b9d26dc-21c5-46b1-9e75-86cef21b7b30.json.gz",
        "request_uri": "\"GET /config/AWSLogs/123123123123/Config/us-east-1/2019/2/5/ConfigSnapshot/123123123123_Config_us-east-1_ConfigSnapshot_20190205T105551Z_6b9d26dc-21c5-46b1-9e75-86cef21b7b30.json.gz HTTP/1.1\"",
        "http_status": "200",
        "error_code": "-",
        "bytes_sent": "79591",
        "object_sent": "79591",
        "total_time": "69",
        "turn_around_time": "68",
        "referer": "\"-\"",
        "user_agent": "\"Boto3/1.9.82 Python/3.7.2 Linux/5.4.0-48-generic Botocore/1.12.240\"",
        "version_id": "-",
        "host_id": "gkh4BpsJSdnHPYEyHvXIbtMJuVX+5aJf4PB8AD9QPlvak7LL28NTOiTLQIUIRo8k++Tv2ss/Y4E=",
        "signature_version": "SigV4",
        "cipher_suite": "ECDHE-RSA-AES128-GCM-SHA256",
        "authentication_type": "AuthHeader",
        "host_header": "wazuh-aws-wodle.s3.amazonaws.com",
        "tls_version": "TLSv1.2\n",
        "source": "s3_server_access"
    }
}
```

**Comment by CarlosRS9** [comment]
# Issue update

Minor changes have been applied to the `load_information_from_file` function. One of the improvements is that now quotes and doble quotes wrapping a string will be removed to clean up the resulting event. As a result, the performance is now a bit slower than the previous version, but still reasonable:

Using a log file with `1000000` logs inside:
| Implementation | Elapdsed Time |
|-|-|
| csv.dictReader | 23,70 s |
| Custom solution | 25,08 s |


## How to test the integration

In order to ensure everything is working as intented manual testing has been performed. Here are the details about how to replicate this testing:

### Available data

We have real S3 Server Access logs available both in `wazuh-aws-wodle-access-logs` and `wazuh-aws-wodle` buckets. The former bucket has logs available in the root path while the latter has the logs inside the `access_logs` directory, to be able to test the `path` option.

### Example configuration

The following configuration can be used to test this integration:

```
<wodle name="aws-s3">
  <disabled>no</disabled>
  <interval>5m</interval>
  <bucket type="server_access">
    <name>wazuh-aws-wodle</name>
    <aws_profile>default</aws_profile>
    <path>access_logs</path>
    <only_logs_after>2021-JAN-01</only_logs_after>
  </bucket>
</wodle>
```

The aws module can be also executed manually using the following command:
```
/var/ossec/wodles/aws/aws-s3 -t server_access -b wazuh-aws-wodle-access-logs -a $ACCESS -k $KEY -d 2 -s 2021-JAN-01
```

### Test results

Once the integration runs several alerts will be raised using the available data and the custom rules provided in the first comment of this issue. The events can be found in the `Security Information Management` > `Amazon AWS` section in Kibana. Here is an event example:

![image](https://user-images.githubusercontent.com/54286452/116559060-52d95100-a900-11eb-999b-1ddf7c4f9a64.png)

As we can see, the `time` field is parsed as expected and quotes wrapping some values have been removed too.

**Comment by CarlosRS9** [comment]
## Issue update

An issue related to the usage of the `only_logs_after` was found and addressed accordingly. Everything works as expected now.
