### ISSUE TITLE
Migrate rules and decoders to yml language

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh#7914]
Migrate rules and decoders to a clean and readable format based on yml language and use common schema to normalize field names

### Language migration.
  - [x] define current decoders representation from xml to yml. #8010
    - [x] Elements and attributes - modify the current syntax and structure to a more legible yml format.
    - [x] Elements and attributes - re-naming for a better user experience.
    - [x] Use common schema to name current fields from decoders.
      - [x] Map current decoders used field names to wazuh common schema. 

  - [x] define current rules representation from xml to yml. #8011
    - [x] Elements and attributes - modify the current syntax and structure to a more legible yml format.
    - [x] Elements and attributes - re-naming and grouping for a better user experience.

  - [ ] Review and approval 

### Team sync
 
- [ ] Sync with other related wazuh areas.
  - [ ] Core. 
  - [ ] Framework.
  - [ ] Wazuh plugin.

**Comment by 72nomada** [comment]
Will open a new issue when new syntax is full defined and migration plan is in place.
