### ISSUE TITLE
Design and develop script to increase cluster load using the API

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#7937]
Hello team,

As the cluster is used to forward the requests to another node, we need to develop a script that makes distributed API calls to increase the cluster load. The script must be able to emulate the normal Kibana behaviour (there are some cronjobs making API requests) and must be running during the whole testing session.

In addition, we should keep track of the number of requests and their status to see if they get slower or fail at some point.

## Tasks
- [x] Design the script behaviour and parametrization
- [x] Investigate which endpoints are the most used by Kibana (preferably distributed ones)
- [x] Investigate which are the most interesting distributed API endpoints to increase the cluster load
- [x] Add functionality to keep track of interesting API metrics 
- [x] Develop API request script

Regards,
Víctor Fernández

**Comment by vicferpoy** [comment]
## Issue update

Hello team,

The script has been defined like this:

![image](https://user-images.githubusercontent.com/37274979/111800266-127fbf80-88cc-11eb-8a79-af9218f8b30f.png)

We will have this script running on a different AWS instance, connected to the master node of the cluster. It will read a YAML file containing parametrization values:

```yaml
remote:
    host: <HOST_IP>
    port: <PORT>

kibana:
    enabled: True/False

extra_load:
    enabled: True/False
    api_requests_percentage: 0-100

```

### Kibana
If `kibana` is enabled, the script will have a thread simulating the API requests that Kibana usually makes on standby in addition to some other requests such as see agents in the system.

### Extra load
If `extra_load` is enabled, the script will have another thread making distributed API requests depending on the `api_requests_percentage` parameter. This will make as many API requests as the the given percentage of the `max_requests_per_minute` parameter from the API to avoid the DOS preventing mechanism.

Regards,
Víctor Fernández

**Comment by vicferpoy** [comment]
## Issue update 

Hello team,

Development is finished. We now have a python script to send requests periodically to a manager host. Its configuration is as it is described above and each module has its own request template. The script is divided in multiple classes, allowing external integration in case we need it. For this case, the templates are the following:

- Kibana template

```yaml
requests:
  -
    endpoint: /cluster/status
    method: get
    parameters: {}
    body: {}
  -
    endpoint: /agents
    method: get
    parameters:
      limit: 1
      q: "id!=000"
    body: {}
  -
    endpoint: /manager/info
    method: get
    parameters: {}
    body: {}
  -
    endpoint: /security/users/me/policies
    method: get
    parameters: {}
    body: {}
  -
    endpoint: /agents/summary/status
    method: get
    parameters: {}
    body: {}
  -
    endpoint: /manager/stats/remoted
    method: get
    parameters:
      pretty: True
    body: {}
  -
    endpoint: /manager/stats/analysisd
    method: get
    parameters:
      pretty: True
    body: {}

```

- Extra Load template

```yaml
requests:
  -
    endpoint: /agents
    method: get
    parameters: {}
    body: {}
  -
    endpoint: /cluster/healthcheck
    method: get
    parameters: {}
    body: {}
  -
    endpoint: /cluster/configuration/validation
    method: get
    parameters: {}
    body: {}
  -
    endpoint: /groups/default/agents
    method: get
    parameters: {}
    body: {}
  -
    endpoint: /syscheck
    method: put
    parameters: {}
    body: {}

```

It accepts the following parameters:

```
Wazuh API load simulator

optional arguments:
  -h, --help            show this help message and exit
  -f, --foreground      Enable logging in foreground mode
  -fr FREQUENCY, --frequency FREQUENCY
                        Insert Kibana API requests interval
  -t TIMEOUT, --timeout TIMEOUT
                        Insert API timeout

```

For the `Kibana` thread, it will make all the request in the template every `FREQUENCY` seconds, resulting in a constant load. The `Extra Load` thread will make all the requests until it reaches the maximum request number per minute, waiting until completing the minute left to begin a new iteration. It will ask for the API maximum request number per minute and then apply the percentage introduced in the configuration. This limit is restricted between **5% and 90%** to prevent activating the DOS preventing mechanism.

### Wazuh API simulator

<details>

<summary>wazuh_api_simulator.py</summary>

```python
#!/usr/bin/python3
import argparse
import json
import logging
import time
from base64 import b64encode

import requests
import urllib3
import yaml

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

from os.path import join, dirname, abspath
from threading import Thread, Event
from time import sleep, time

KIBANA_TEMPLATE = join(dirname(abspath(__file__)), 'data', 'kibana_requests.yaml')
EXTRA_TEMPLATE = join(dirname(abspath(__file__)), 'data', 'extra_requests.yaml')


class ThreadFilter(logging.Filter):
    def __init__(self, thread_name):
        super().__init__()
        self.thread_name = thread_name

    def filter(self, record):
        record.thread_name = self.thread_name
        return True


class CustomLogger:
    def __init__(self, name, filename='wazuh_api_simulator.log', foreground=False, tag='Main'):
        logger = logging.getLogger(name)
        logger.addFilter(ThreadFilter(tag))
        logger_formatter = logging.Formatter('{asctime} {levelname}: [{thread_name}] {message}', style='{',
                                             datefmt='%Y/%m/%d %H:%M:%S')
        logging.basicConfig(filename=join(dirname(abspath(__file__)), filename), filemode='a', level=logging.INFO,
                            format='%(asctime)s %(levelname)s: [%(thread_name)s] %(message)s',
                            datefmt='%Y/%m/%d %H:%M:%S')

        if foreground:
            ch = logging.StreamHandler()
            ch.setFormatter(logger_formatter)
            logger.addHandler(ch)

        self.logger = logger

    def get_logger(self):
        return self.logger


class WazuhAPIRequester:
    def __init__(self, host, port, protocol='https', frequency=60, user='wazuh', password='wazuh', timeout=60,
                 external_logger=None, request_percentage=0, request_template=None):
        self.host = host
        self.port = port
        self.protocol = protocol
        self.frequency = frequency
        self.timeout = timeout
        self.logger = external_logger if external_logger else logging.getLogger('wazuh-api-requester')
        self.user = user
        self.password = password
        self.token = None
        self.requests = None
        self.request_percentage = request_percentage

        self.thread = None
        self.event = None

        self.base_url = f'{self.protocol}://{self.host}:{self.port}'
        self.load_template(request_template)
        self.validate_percentage()

    def load_template(self, template_file):
        try:
            self.requests = yaml.safe_load(open(template_file))['requests']
            self.logger.info(f'Loaded template in {template_file}')
        except OSError as file_error:
            self.logger.error(f'Could not load request template: {file_error}')
            exit(1)
        except yaml.YAMLError as yaml_error:
            self.logger.error(f'Failed to load request template: {yaml_error}')
            exit(1)

    def validate_percentage(self):
        if self.request_percentage == 0:
            return

        elif 5 > self.request_percentage > 90:
            self.logger.error('Invalid request percentage. It must be between 5 and 90. Current '
                              f'{self.request_percentage}')
            exit(1)


    def get_token(self):
        authenticate_url = '/security/user/authenticate'
        basic_auth = {'Content-Type': 'application/json',
                      'Authorization': f"Basic {b64encode(f'{self.user}:{self.password}'.encode()).decode()}"}

        for _ in range(10):
            try:
                self.logger.info('Trying to obtain API token')
                response = requests.get(f'{self.base_url}{authenticate_url}', headers=basic_auth, verify=False)
                if response.status_code != 200:
                    self.logger.error(f'Failed to obtain API token: {response.json()}')
                    self.logger.error('Retrying in 1s...')
                    sleep(1)
                else:
                    self.token = json.loads(response.content.decode())['data']['token']
                    return

            except Exception as token_exception:
                self.logger.error(f'An exception occurred trying to obtain API token: {token_exception}')
                self.logger.error('Retrying in 1s...')
                sleep(1)
        else:
            raise RuntimeError('Could not obtain an API token after 10 tries')

    def make_request(self, request, result=False):
        endpoint = f"{self.base_url}{request['endpoint']}"
        headers = {'Authorization': f'Bearer {self.token}'}
        if request['body']:
            headers['Content-Type'] = 'application/json'

        try:
            response = getattr(requests, request['method'])(endpoint, headers=headers, params=request['parameters'],
                                                 data=request['body'], verify=False, timeout=self.timeout)
            if result:
                return response
        except requests.exceptions.Timeout:
            self.logger.error(f"API request timed out: {request['endpoint']}")
            return

        if response.status_code == 401:
            self.logger.warning('API token expired')
            self.get_token()
            try:
                response = getattr(requests, request['method'])(endpoint, headers=headers, params=request['parameters'],
                                                                data=request['body'], verify=False,
                                                                timeout=self.timeout)
                if result:
                    return response

            except requests.exceptions.Timeout:
                self.logger.error(f'API request timed out. Current timeout: {self.timeout}s')
                return

        self.logger.info(f"API request {request['endpoint']} | {response.status_code}")

    def _calculate_mrpm(self):
        data = {'endpoint': '/manager/api/config',
                'method': 'get',
                'parameters': {},
                'body': {}}

        try:
            self.logger.info('Attempting to obtain max API requests per minute')
            response = self.make_request(data, result=True)
            max_request = json.loads(response.content.decode())['data']['affected_items'][0]['node_api_config']['access']['max_request_per_minute']
            self.logger.info(f'Current max requests per minute: {max_request}')
            return int(max_request * self.request_percentage / 100)
        except Exception as max_request_error:
            self.logger.error(f'Could not obtain max API requests per minute: {max_request_error}')
            exit(1)


    def _request_loop(self):
        if not self.requests:
            self.logger.info('There are no requests to do. Process aborted')
            exit(0)
        self.logger.info(f'{len(self.requests)} requests per loop')
        self.logger.info(f'Frequency: {self.frequency} - Timeout: {self.timeout}')
        self.get_token()

        time_per_request = self.frequency / len(self.requests)
        max_rpm = self._calculate_mrpm() if self.request_percentage else 0
        minute_timer = time()
        request_per_minute = 0 if not max_rpm else 1

        while not self.event.is_set():
            for request in self.requests:
                if self.event.is_set():
                    break
                tic = time()
                self.make_request(request)
                request_per_minute += 1

                if not max_rpm:
                    time_left = time_per_request - (time() - tic)
                    if time_left > 0:
                        sleep(time_left)
                elif time() - minute_timer < 60 and request_per_minute > max_rpm:
                    waiting_time = 60 - (time() - minute_timer)
                    self.logger.info(f'Max requests per minute limit exceeded. Waiting {int(waiting_time)}s')
                    sleep(waiting_time)
                    minute_timer = time()
                    request_per_minute = 0
                elif time() - minute_timer >= 60:
                    minute_timer = time()
                    request_per_minute = 0


    def start(self):
        self.logger.info('Initializing process')
        self.event = Event()
        self.thread = Thread(target=self._request_loop)
        self.thread.start()

    def shutdown(self):
        self.logger.info('Attempting to finish process')
        self.event.set()
        self.thread.join()
        self.logger.info('Process finished')


def get_arguments():
    parser = argparse.ArgumentParser(usage="%(prog)s [options]",
                                     description="Wazuh API load simulator",
                                     formatter_class=argparse.RawTextHelpFormatter)
    parser.add_argument('-f', '--foreground', dest='foreground', action='store_true', default=False,
                        help='Enable logging in foreground mode')
    parser.add_argument('-fr', '--frequency', dest='frequency', action='store', default=60, type=int,
                        help='Insert Kibana API requests interval')
    parser.add_argument('-t', '--timeout', dest='timeout', action='store', default=15, type=int,
                        help='Insert API timeout')

    return parser.parse_args()


def main():
    options = get_arguments()

    main_logger = CustomLogger('wazuh_api_simulator', foreground=options.foreground).get_logger()

    try:
        configuration_file = join(dirname(abspath(__file__)), 'config.yaml')
        configuration = yaml.safe_load(open(configuration_file))
        main_logger.info(f'Loaded configuration file: {configuration}')
    except OSError as e:
        main_logger.error(f'Could not load configuration file. Error: {e}')
        exit(1)

    HOST = configuration['remote']['host']
    PORT = configuration['remote']['port']

    if configuration['kibana']['enabled']:
        kibana_logger = CustomLogger('kibana_thread', foreground=options.foreground, tag='Kibana').get_logger()
        try:
            kibana_thread = WazuhAPIRequester(HOST, PORT, request_template=KIBANA_TEMPLATE, frequency=options.frequency,
                                              timeout=options.timeout, external_logger=kibana_logger)
            kibana_thread.start()
        except Exception as kibana_exception:
            kibana_logger.error(f'Unhandled exception: {kibana_exception}')

    if configuration['extra_load']['enabled']:
        extra_logger = CustomLogger('extra_thread', foreground=options.foreground, tag='ExtraLoad').get_logger()
        try:
            request_percentage = configuration['extra_load']['api_requests_percentage']
            extra_load_thread = WazuhAPIRequester(HOST, PORT, request_template=EXTRA_TEMPLATE,
                                                  request_percentage=request_percentage, timeout=options.timeout,
                                                  external_logger=extra_logger,)
            extra_load_thread.start()
        except Exception as extra_exception:
            extra_logger.error(f'Unhandled exception: {extra_exception}')


if __name__ == '__main__':
    main()

```

</details>

#### Files structure

```
|-- wazuh_api_simulator.py
|-- config.yaml
|-- data
|   |-- extra_requests.yaml
|   `-- kibana_requests.yaml
`-- wazuh_api_simulator.log
```

#### Log example

- Both modules enabled
- Frequency: 20s
- API request percentage: 5%

```log

root@wazuh-worker1:/# python3 wazuh_api_simulator.py -f -fr 20
2021/03/24 10:23:05 INFO: [Main] Loaded configuration file: {'remote': {'host': 'wazuh-master', 'port': 55000}, 'kibana': {'enabled': True}, 'extra_load': {'enabled': True, 'api_requests_percentage': 5}}
2021/03/24 10:23:05 INFO: [Kibana] Loaded template in /scratches/api_load/data/kibana_requests.yaml
2021/03/24 10:23:05 INFO: [Kibana] Initializing process
2021/03/24 10:23:05 INFO: [Kibana] 7 requests per loop
2021/03/24 10:23:05 INFO: [Kibana] Frequency: 20 - Timeout: 15
2021/03/24 10:23:05 INFO: [ExtraLoad] Loaded template in /scratches/api_load/data/extra_requests.yaml
2021/03/24 10:23:05 INFO: [Kibana] Trying to obtain API token
2021/03/24 10:23:05 INFO: [ExtraLoad] Initializing process
2021/03/24 10:23:05 INFO: [ExtraLoad] 5 requests per loop
2021/03/24 10:23:05 INFO: [ExtraLoad] Frequency: 60 - Timeout: 15
2021/03/24 10:23:05 INFO: [ExtraLoad] Trying to obtain API token
2021/03/24 10:23:05 INFO: [ExtraLoad] Attempting to obtain max API requests per minute
2021/03/24 10:23:05 INFO: [Kibana] API request /cluster/status | 200
2021/03/24 10:23:05 INFO: [ExtraLoad] Current max requests per minute: 300
2021/03/24 10:23:05 INFO: [ExtraLoad] API request /agents | 200
2021/03/24 10:23:05 INFO: [ExtraLoad] API request /cluster/healthcheck | 200
2021/03/24 10:23:06 INFO: [ExtraLoad] API request /cluster/configuration/validation | 200
2021/03/24 10:23:06 INFO: [ExtraLoad] API request /groups/default/agents | 200
2021/03/24 10:23:06 INFO: [ExtraLoad] API request /syscheck | 200
2021/03/24 10:23:06 INFO: [ExtraLoad] API request /agents | 200
2021/03/24 10:23:06 INFO: [ExtraLoad] API request /cluster/healthcheck | 200
2021/03/24 10:23:07 INFO: [ExtraLoad] API request /cluster/configuration/validation | 200
2021/03/24 10:23:07 INFO: [ExtraLoad] API request /groups/default/agents | 200
2021/03/24 10:23:07 INFO: [ExtraLoad] API request /syscheck | 200
2021/03/24 10:23:07 INFO: [ExtraLoad] API request /agents | 200
2021/03/24 10:23:07 INFO: [ExtraLoad] API request /cluster/healthcheck | 200
2021/03/24 10:23:08 INFO: [ExtraLoad] API request /cluster/configuration/validation | 200
2021/03/24 10:23:08 INFO: [ExtraLoad] API request /groups/default/agents | 200
2021/03/24 10:23:08 INFO: [ExtraLoad] API request /syscheck | 200
2021/03/24 10:23:08 INFO: [ExtraLoad] Max requests per minute limit exceeded. Waiting 57s
2021/03/24 10:23:08 INFO: [Kibana] API request /agents | 200
2021/03/24 10:23:11 INFO: [Kibana] API request /manager/info | 200
2021/03/24 10:23:14 INFO: [Kibana] API request /security/users/me/policies | 200
2021/03/24 10:23:17 INFO: [Kibana] API request /agents/summary/status | 200
2021/03/24 10:23:19 INFO: [Kibana] API request /manager/stats/remoted | 200
2021/03/24 10:23:22 INFO: [Kibana] API request /manager/stats/analysisd | 200
2021/03/24 10:23:25 INFO: [Kibana] API request /cluster/status | 200
2021/03/24 10:23:28 INFO: [Kibana] API request /agents | 200
2021/03/24 10:23:31 INFO: [Kibana] API request /manager/info | 200
2021/03/24 10:23:34 INFO: [Kibana] API request /security/users/me/policies | 200

```

**NOTE**: This script has been running at 50% request percentage for one hour without any errors.

Regards,
Víctor Fernández
