### ISSUE TITLE
Design and develop API integration tests for loaded environments

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#7940]
Hello team,

We need to develop new API tests that will be executed in a loaded environment. The main goal of these tests is to see what endpoints do not scale properly when the environment is under a heavy load. This means that we need to analyze response times in addition to status codes and consider custom timeouts.

## Tasks
- [x] Investigate what is the best approach for these tests (tavern or requests module)
- [x] Define API endpoints to test
- [x] Develop the framework for the tests
- [x] Develop the tests

Regards,
Víctor Fernández

**Comment by vicferpoy** [comment]
## Issue update

Hello team,

After some investigation, we decided to use `requests` for this task as it is more flexible. As for the endpoints, we will divide them in two big groups and then sort them by request method:

1. Service endpoints (restart, status...)
  1.1. GET
  1.2. PUT
  1.3. DELETE

2. Resource endpoints (resource management such as agents, groups, security resources...)
  2.1. POST
  2.2. GET
  2.3. PUT
  2.4. DELETE

This way, we will avoid any issues with unexisting resources, stopped daemons, etc. In addition, we need to define which endpoints are really problematic since we know for a fact that a big part of them will scale smoothly on larger environments (creating a new security role, for instance, will not have any issue).

As soon as the endpoints are defined, we will begin the development.

Regards,
Víctor Fernández

**Comment by vicferpoy** [comment]
## Issue update
Test development is finished. We just need to add more test cases to the template. The template has this structure:

```yaml
configuration:
  host: 'localhost'
  port: 55000

test_cases:
  - endpoint: /active-response
    method: put
    parameters: {}
    body:
      command: custom
      custom: True

  - endpoint: /agents
    method: get
    parameters: {}
    body: {}
```

These tests are designed to use the `--html` parameter in order to generate a report with useful data. Tests only pass when the status code is `200`. This is an example of the report with the template from above:

![image](https://user-images.githubusercontent.com/37274979/113847246-90323f00-9797-11eb-9116-aa2bd6bfadbd.png)

Regards,
Víctor Fernández

**Comment by vicferpoy** [comment]
## Issue update

Issue is finished. More test cases has been added to the template in addition to more useful information about each endpoint, such as the possibility of waiting for a restart. This option is only considered on certain `PUT` endpoints and the restart delay must be added in the configuration section of the template:

```yaml
configuration:
  host: 'localhost'
  port: 55000
  restart_delay: 30

test_cases:

(...)

```

This is an example of the final report:

![image](https://user-images.githubusercontent.com/37274979/114146992-84ba5180-9918-11eb-8a5c-a976c33e7745.png)


Regards,
Víctor Fernández
