### ISSUE TITLE
Run Bandit scan and analyze and the results

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#7998]
- Objective scan branch: https://github.com/wazuh/wazuh/tree/master
- Last commit before scan: https://github.com/wazuh/wazuh/commit/ecc19c3a5735509370c96b1b818c0c5d67658cd0
- Scan date: 04/22/21

Hi team,

After the research done in the issue https://github.com/wazuh/wazuh/issues/7971, it is necessary to run the Bandit tool on the API, Framework and Wodles code in order to fix as far as possible all the alerts that this tool gives us.

As for the possible alerts that require a refactor, it will be determined if it is necessary to suppress the Bandit test that causes the alert or if consequently it will be proceeded to the refactoring of the code.

The current status of the API/Framework/Wodles code is as follows:

### API
```
{
    "totals": {
      "CONFIDENCE.HIGH": 0.0,
      "CONFIDENCE.LOW": 0.0,
      "CONFIDENCE.MEDIUM": 2.0,
      "CONFIDENCE.UNDEFINED": 0.0,
      "SEVERITY.HIGH": 0.0,
      "SEVERITY.LOW": 1.0,
      "SEVERITY.MEDIUM": 1.0,
      "SEVERITY.UNDEFINED": 0.0,
      "loc": 7493,
      "nosec": 0
    }
}
```

### Framework:
```
{
    "totals": {
      "CONFIDENCE.HIGH": 30.0,
      "CONFIDENCE.LOW": 7.0,
      "CONFIDENCE.MEDIUM": 7.0,
      "CONFIDENCE.UNDEFINED": 0.0,
      "SEVERITY.HIGH": 0.0,
      "SEVERITY.LOW": 21.0,
      "SEVERITY.MEDIUM": 23.0,
      "SEVERITY.UNDEFINED": 0.0,
      "loc": 18755,
      "nosec": 0
    }
}
```

### Wodles:
```
{
    "totals": {
      "CONFIDENCE.HIGH": 11.0,
      "CONFIDENCE.LOW": 0.0,
      "CONFIDENCE.MEDIUM": 0.0,
      "CONFIDENCE.UNDEFINED": 0.0,
      "SEVERITY.HIGH": 1.0,
      "SEVERITY.LOW": 5.0,
      "SEVERITY.MEDIUM": 5.0,
      "SEVERITY.UNDEFINED": 0.0,
      "loc": 3562,
      "nosec": 0
    }
}
```
## ToDo:

- [x] Analyze API flaws.
- [x] Analyze Framework flaws.
- [x] Analyze Wodles flaws.

Best regards,

Adrián Peña

**Comment by AdriiiPRodri** [comment]
## API Report
Hi team,

According to Bandit, we have 2 possible security flaws in the API code. 

![api_flaws_chart](https://user-images.githubusercontent.com/15522808/115693420-310c2700-a360-11eb-85c5-ef6b2cfe803e.png)

One of them has a low severity and the other one has a medium severity. Next, we will investigate them:

- We start with the low severity report:

```
>> Issue: [B106:hardcoded_password_funcarg] Possible hardcoded password: 'request'
   Severity: Low   Confidence: Medium
   Location: ./api/scripts/wazuh-apid.py:137
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b106_hardcoded_password_funcarg.html
136	                               )
137	    app.add_api('spec.yaml',
138	                arguments={'title': 'Wazuh API',
139	                           'protocol': 'https' if api_conf['https']['enabled'] else 'http',
140	                           'host': api_conf['host'],
141	                           'port': api_conf['port']
142	                           },
143	                strict_validation=True,
144	                validate_responses=False,
145	                pass_context_arg_name='request',
146	                options={"middlewares": [response_postprocessing, set_user_name, security_middleware, request_logging,
147	                                         set_secure_headers]})
148	
```

In this case we notice that it is possible that there is a hardcoded password, however, in the code we can see that this is not the case and it is a false positive.

- The following report has a medium severity:

```
>> Issue: [B104:hardcoded_bind_all_interfaces] Possible binding to all interfaces.
   Severity: Medium   Confidence: Medium
   Location: ./api/api/configuration.py:30
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b104_hardcoded_bind_all_interfaces.html
29	default_api_configuration = {
30	    "host": "0.0.0.0",
31	    "port": 55000,
32	    "use_only_authd": False,
33	    "drop_privileges": True,
34	    "experimental_features": False,
35	    "https": {
36	        "enabled": True,
37	        "key": "api/configuration/ssl/server.key",
38	        "cert": "api/configuration/ssl/server.crt",
39	        "use_ca": False,
40	        "ca": "api/configuration/ssl/ca.crt",
41	        "ssl_cipher": "TLSv1.2"
42	    },
43	    "logs": {
44	        "level": "info",
45	        "path": "logs/api.log"
46	    },
47	    "cors": {
48	        "enabled": False,
49	        "source_route": "*",
50	        "expose_headers": "*",
51	        "allow_headers": "*",
52	        "allow_credentials": False,
53	    },
54	    "cache": {
55	        "enabled": True,
56	        "time": 0.750
57	    },
58	    "access": {
59	        "max_login_attempts": 50,
60	        "block_time": 300,
61	        "max_request_per_minute": 300
62	    },
63	    "remote_commands": {
64	        "localfile": {
65	            "enabled": True,
66	            "exceptions": []
67	        },
68	        "wodle_command": {
69	            "enabled": True,
70	            "exceptions": []
71	        }
72	    }
```

We are told that we are exposing the API from all network interfaces. This is due to the design of the API, by default, the API accepts all connections unless otherwise indicated in its configuration. This is because the API can be configured from the API itself.

Therefore, we conclude that there is no security problem in the API code.

**Comment by AdriiiPRodri** [comment]
# Framework Report

Hi team,

According to Bandit, we have 46 possible security flaws in the Framework/Cluster code.

![framework_flaws_chart](https://user-images.githubusercontent.com/15522808/115713426-48560f00-a376-11eb-8a20-4ee83c9d285f.png)


We will start with the flag whose confidence is "Medium" and severity "low":

```
>> Issue: [B105:hardcoded_password_string] Possible hardcoded password: ''
   Severity: Low   Confidence: Medium
   Location: ./framework/scripts/wazuh-logtest.py:89
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b105_hardcoded_password_string.html
88	    # Main processing loop
89	    session_token = ''
90	    while True:
```

As we can see, we are facing a false positive, we are told that it is possible that a password is hardcoded, although this is a false positive because the session_token variable has been declared as ''. This flaw could be solved by replacing this declaration by `session_token = str()`, however it is not necessary.

We continue with the flaws with "low" severity and "high" confidence. There are 22 of these flaws, which can be classified into three different types. 

## Pseudo-Random

The first type is related to the use of random numbers, we have 7 of this flaw. Three of them are false positives since these are used to generate temporary files but these also use the `time()` function, so since these functions are synchronous, we can guarantee that the files will never be overwritten. The other 4 flaws, can cause possible problems in the future, next we are going to analyze them:

### core/cluster/common.py

```
>> Issue: [B311:blacklist] Standard pseudo-random generators are not suitable for security/cryptographic purposes.
   Severity: Low   Confidence: High
   Location: ./framework/wazuh/core/cluster/common.py:192
   More Info: https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b311-random
191	        self.coro = self.set_up_coro()
192	        self.task_id = task_id.decode() if task_id else str(random.randint(0, 2 ** 32))
193	        self.received_information = asyncio.Event()
```

In this case, there is a possibility that two or more tasks have the same id, which would cause that only the last of the tasks would be taken into account because the ids must be unique since the tasks are identified by them.

### core/cluster/dapi/dapi.py

```
>> Issue: [B311:blacklist] Standard pseudo-random generators are not suitable for security/cryptographic purposes.
   Severity: Low   Confidence: High
   Location: ./framework/wazuh/core/cluster/dapi/dapi.py:87
   More Info: https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b311-random
86	        self.node_info = wazuh.core.cluster.cluster.get_node() if node is None else node.get_node()
87	        self.request_id = str(random.randint(0, 2 ** 10 - 1))
88	        self.request_type = request_type
```

In this case, the same thing happens but with a higher probability because the range of numbers is smaller. In addition this line in particular is not used in the rest of the DistributedAPI class so we can suppress it.

### core/cluster/master.py

```
>> Issue: [B311:blacklist] Standard pseudo-random generators are not suitable for security/cryptographic purposes.
   Severity: Low   Confidence: High
   Location: ./framework/wazuh/core/cluster/master.py:255
   More Info: https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b311-random
254	        """
255	        request_id = str(random.randint(0, 2**10 - 1))
256	        # Create an event to wait for the response.
```

Same case, it is possible that there are two equal request_id which would cause the first one to be lost due to the fact that at the end they are placed in a dictionary:

```
request_id = str(random.randint(0, 2**10 - 1))
# Create an event to wait for the response.
self.server.pending_api_requests[request_id] = {'Event': asyncio.Event(), 'Response': ''}
```

### core/cluster/server.py

```
>> Issue: [B311:blacklist] Standard pseudo-random generators are not suitable for security/cryptographic purposes.
   Severity: Low   Confidence: High
   Location: ./framework/wazuh/core/cluster/server.py:44
   More Info: https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b311-random
43	        """
44	        super().__init__(fernet_key=fernet_key, logger=logger, tag=f"{tag} {random.randint(0, 1000)}",
45	                         cluster_items=cluster_items)
```

Finally, if a tag is repeated what would happen would be that we would lose information in the logger, this is the least risky of the four cases.

## Subprocess

For this type we have a total of 11 flaws, which are all false positives because the subprocess module is used but we never set an external input as a parameter. In other words, all the invoked subprocesses have the parameters hardcoded. Here we can see an example:

```
>> Issue: [B603:subprocess_without_shell_equals_true] subprocess call - check for execution of untrusted input.
   Severity: Low   Confidence: High
   Location: ./framework/scripts/wazuh-logtest.py:420
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b603_subprocess_without_shell_equals_true.html
419	        try:
420	            proc = subprocess.Popen([wazuh_control, "info"], stdout=subprocess.PIPE)
421	            (stdout, stderr) = proc.communicate()
```

## XML

Of this type of flaws we have 4. As bandit indicates, in this case it is always convenient to use defusedxml because it does not reduce functionality and increases security. This requirement was added to the requirements.txt file but was never applied, only in the `api/api/validator.py` file.

```
>> Issue: [B408:blacklist] Using parseString to parse untrusted XML data is known to be vulnerable to XML attacks. Replace parseString with the equivalent defusedxml package, or make sure defusedxml.defuse_stdlib() is called.
   Severity: Low   Confidence: High
   Location: ./framework/wazuh/core/configuration.py:17
   More Info: https://bandit.readthedocs.io/en/latest/blacklists/blacklist_imports.html#b408-import-xml-minidom
16	
17	from xml.dom.minidom import parseString
18	
19	from wazuh.core import common
```

**Comment by AdriiiPRodri** [comment]
# Wodle Report

Hi team,

According to Bandit, we have 11 possible security flaws in the Wodles code.

![wodles_flaws_chart](https://user-images.githubusercontent.com/15522808/115743052-962c4080-a391-11eb-89ff-4f97202cec9a.png)


We will start with the flag whose severity is "low", we have 5 flaws:

```
>> Issue: [B311:blacklist] Standard pseudo-random generators are not suitable for security/cryptographic purposes.
   Severity: Low   Confidence: High
   Location: ./wodles/oscap/oscap.py:164
   More Info: https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b311-random
163	        except:
164	            agent_id = randrange(1, 9999)
165
```

In this case a random is being used as agent_id, it does not seem very secure and we should investigate more the operation of this wodle since it does not seem clear that this is being used.

On the other hand we have that the other errors are due to the use of the subprocess library. After reviewing the possible flaws, it does not seem to be possible to do an injection, the parameters are hardcoded in the code. Here we can see an example:

```
>> Issue: [B603:subprocess_without_shell_equals_true] subprocess call - check for execution of untrusted input.
   Severity: Low   Confidence: High
   Location: ./wodles/oscap/oscap.py:170
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b603_subprocess_without_shell_equals_true.html
169	
170	            ps_xsltproc = Popen([XSLT_BIN, TEMPLATE_XCCDF, FIFO_PATH], stdin=None, stdout=PIPE, stderr=STDOUT)
171	            ps.wait()
```

The following are those classified as severity "medium", these are 5. Within these we have two types, the first indicates that we use an insecure hash function (MD5):

```
>> Issue: [B303:blacklist] Use of insecure MD2, MD4, MD5, or SHA1 hash function.
   Severity: Medium   Confidence: High
   Location: ./wodles/azure/azure-logs.py:384
   More Info: https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b303-md5
383			try:
384				graph_md5 = hashlib.md5(graph_format_query.encode()).hexdigest()
385				# first time for this query

```

In this case it is not a problem since the data handled are not critical and are only used internally by the wodle, so there is no decoding possibility.

The next flaw has to do with the use of the "eval" function:

```
>> Issue: [B307:blacklist] Use of possibly insecure function - consider using safer ast.literal_eval.
   Severity: Medium   Confidence: High
   Location: ./wodles/oscap/oscap.py:111
   More Info: https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b307-eval
110	    try:
111	        perm = eval('0666')
112	    except SyntaxError:
```

Similar to subprocess, eval is dangerous because if code is injected into its parameters, they will be executed. However, as with subprocess, the parameters are hardcoded in the code.

Finally, let's go with the flaw with severity "high":

```
>> Issue: [B602:subprocess_popen_with_shell_equals_true] subprocess call with shell=True identified, security issue.
   Severity: High   Confidence: High
   Location: ./wodles/oscap/oscap.py:36
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b602_subprocess_popen_with_shell_equals_true.html
35	
36	    ps = Popen(arguments,shell=shell, stdin=None, stdout=PIPE, stderr=STDOUT)
37	    cmd_output = ps.communicate()[0]
```

In this case, we have that the function "check_installed" can receive parameters and these are inserted directly into a Popen. This can suppose some risk, this function is called in three different points and in all of them the parameters are hardcoded, for example:

```
output_installed = check_installed([OSCAP_BIN, "-V"], stderr=STDOUT)
```

However, there are better ways to check this and it can be improved. At the moment it does not represent a major risk, but we should improve this part.

**Comment by AdriiiPRodri** [comment]
## Reports

- API report: 
[api_flaws.txt](https://github.com/wazuh/wazuh/files/6364333/api_flaws.txt)

- Framework/Cluster report: 
[framework_flaws.txt](https://github.com/wazuh/wazuh/files/6364337/framework_flaws.txt)

- Wodles report: 
[wodles_flaws.txt](https://github.com/wazuh/wazuh/files/6364339/wodles_flaws.txt)
