### ISSUE TITLE
Integrating Snyk with the Wazuh repo

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#8000]
Hi team,

In this PR we will analyze how we can integrate Snyk with the Wazuh repository. Ideally it would be necessary that Snyk analyze the code of the PRs related to the API/Framework/Wodles. So we will investigate how to achieve this.

## ToDo:

- [ ] Integrate Snyk with the Wazuh repo
- [ ] Investigate selective analysis of PRs
- [ ] Test and investigate the functionality of creating automatic PRs, as well as comments on PRs.

Best regards,

Adrián Peña
