### ISSUE TITLE
Provide the tools to be able to test decoders and rules

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh#8006]
## Description
With the YML migration process on going the need to implement a suitable and efficient way of testing the ruleset has arose, as currently we lack coverage and automation, making the whole process of testing rules and decoders inefficient, thus the ability to deliver and update new rules and decoders with confidence and to guaranty integrity between versions increases in difficulty.

## Problems
- Our ruleset is composed of approximately 3100 rules and 900 decoders, and only about a 10% are covered by our current testing tools.
- Not automated, not integrated with Jenkins
- Limited traceability
- Inability to test decoders and rules independently
- Inability to test some decoder/rules out of the box

## Objectives
- [ ] Be able to test and verify rules and decoders. 
  - [ ] Improve current tests: add tests and additional sample logs.
  - [ ] Get base line for future reference.
  - [ ] Test after migration from current version to new version.
  - [ ] Be able to run test automatically after ruleset modification.
 
## Metrics
| total rules                                  | 3245 |
| -------------------------------------------- | ---- |
| rules with test in .ini                      | 255  |
| rules with example logs (to be added in ini) | 227  |
| rules not covered                            | 2763 |
![image.png](https://images.zenhubusercontent.com/602cf858864bfc5b71b3cbc8/43fc3c2b-ecb9-4074-ba81-4771afd20ad5)

**Comment by JavierBejMen** [comment]
## Taking a look

Current decoders/rule testing consist of .ini files (log inputs and test definition), runtests.py (script wich reads inputs, calls wazuh-logtest and process the latest output to verify test results). 
### Current Problems

1. Poor decoder/rule coverage -> .ini files
2. Inability to test some decoder/rules out of the box, precisely Windows Sysmon, possibly FIM and SCA -> wazuh-logtest, runtests.py
3. Not automatized, not integrated with Jenkins -> runtests.py
4. Limited traceability, can't trace exact decoder tree and output doesn't specify what caused the test to fail -> wazuh-logtest, runtests.py

### Action Proposal

1. Gather logs to increase coverage, possibly in conjunction with #7556, as rule reviewing is taking in place.
2. Further review inputs needed to test such events and incorporate them.
3. Coordinate with Jenkins managers, CI/CD, to define a more functional testing output.
4. Coordinate with wazuh-logtest managers, devel-core, to:
    - Study improvements viability.
    - Define future of wazuh-logtest, as possible rollback to ossec-logtest is in the air.

### Future Insights to keep in mind

- End to End testing, from agent to ELK.
- YML support.

**Comment by juanrricci** [comment]
## Related issues (research)
### From [wazuh/wazuh](https://github.com/wazuh/wazuh)
- Wazuh logtest does not load newly created files until manager is restarted #7781
- Verbose mode is missing in wazuh-logtest #7779
- Create a test tool for SCA rules #7623
- Parent decoder name used in ossec-logtest instead the child decoder name #4937
### From wazuh/wazuh-jenkins
- Add check-run log results on test ruleset (2352)

**Comment by juanrricci** [comment]
## WIP - Rule coverage report / Rule coverage improvement
As part of the general testing improvement of our ruleset, it is necessary to know the current state of it. For this purpose, a new Python script is being currently developed in order to get a report with relevant information.
This is a new project. We were able to achieve the following goals so far:
- Parse the rule files (with .xml extension) in order to get the IDs of the whole ruleset
- Parse the testing files (with .ini extension) in order to get the description, example log(s), matching rule ID, alert level and decoder name of each test.

The following tasks are still in progress:
- Join the information obtained both from rule files and testing files for creating a dictionary that relates each rule ID with their respective tests.
- Get some general results from this infomation. For example, the rule coverage percentage.
- Create a reliable structure for add new tests massively in order to increment the coverage in a fast and organized way.
- Know which rules keep excluded from this testing mechanism in orden to define an action plan for extending the capacities of our pipeline.

**Comment by JavierBejMen** [comment]
Related to #7914

**Comment by juanrricci** [comment]
## Partial results
- Percentage of rules covered by current tests: 10%

**Comment by JavierBejMen** [comment]
## Research

Wazuh-logtest and ossec-logtest failed to show extracted fields by decoder, but extraction occurs as shown below:
```bash
**Phase 1: Completed pre-decoding.
       full event: '%FTD-1-105008: (Primary) Testing interface interface_name.'
       timestamp: '(null)'
       hostname: 'localhost'
       program_name: '(null)'
       log: '%FTD-1-105008: (Primary) Testing interface interface_name.'
**Phase 2: Completed decoding.
       decoder: 'cisco-ios'
       id: '%FTD-1-105008'
**Phase 3: Completed filtering (rules).
       Rule id: '4711'
       Level: '5'
       Description: 'Cisco IOS alert message.'
**Alert to be generated.
```
In order for rule 4711 to be triggered the field **cisco.severity** has to be successfully extracted :
```xml
<rule id="4711" level="7">
    <if_sid>4700</if_sid>
    <field name="cisco.severity">1</field>
    <description>Cisco IOS alert message - $(cisco.mnemonic)</description>
    <group>gpg13_4.1,</group>
  </rule>
```

**Comment by JavierBejMen** [comment]
## Research
Unable to find runtests.py documentation

**Comment by JavierBejMen** [comment]
# Update
After finishing reviewing .inis and logs inside xml files as comments we are covering a 7% of current rules with testing, and another 7% of extracted logs to be added to test files.

| total rules                                  | 3245 |
| -------------------------------------------- | ---- |
| rules with test in .ini                      | 255  |
| rules with example logs (to be added in ini) | 227  |
| rules not covered                            | 2763 |

![image.png](https://images.zenhubusercontent.com/602cf858864bfc5b71b3cbc8/07e6933e-31bf-4c0d-8400-5dec00b74fd8)
