### ISSUE TITLE
Add resource_type filter to security endpoints

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#8057]
Hello team,

We need to add a new  filter to the Wazuh API security endpoints to be able to filter resources by its `resource_type`.

## Tasks
- [x] Add the new filter to each security endpoint.
- [x] Create new integration tests for this feature.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [ ] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by CarlosRS9** [comment]
## Issue update

The changes were applied. The security endpoints now accepts `resource_type` parameter. It is limited to `default`, `protected` and `user` values. It is working as expected.

The unit tests have been updated and expanded to test this new parameter. Integration tests are currently being executed to grant everythin still works as expected.

**Comment by CarlosRS9** [comment]
## Issue update

The development is finished. Unit and integration tests have been updated accordingly.
