### ISSUE TITLE
Update security_resources CLI to protect existing resources

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#8078]
Hello team,

It will be interesting to have a function in our `security_resources` CLI to allow the users to protect their custom resources by changing their resource_type from resource_type `user` to `protected`. For example: a user could protect their custom Policies by running the `security_resources` CLI with the list of the IDs for those Policies to protect.

## Tasks

- [ ] Review and implement the required changes in the `security` module to ensure this functionality is supported.
- [ ] Update the `security_resources` CLI to add the new parameters.
- [ ] Update the `security_resources` documentation page.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

Regards

**Comment by vicferpoy** [comment]
After analyzing this issue we are closing it. This functionality can be done using the `update` option and using the same resource data as input. It will switch to `protected` if the resource was `user`.

We will consider adding an independent option for this in the future if the feature is requested.

Regards,
Víctor Fernández
