### ISSUE TITLE
Define an output format for a single target in localfiles

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#830]
The option `<output_format>` in `<localfile>` stanzas builds a custom message for monitored files and commands. This option affects every target.

Make this option capable of formatting a log for a single target.

## Proposed configuration change

```xml
<localfile>
  <log_format>syslog</log_format>
  <location>/var/log/syslog</location>
  <target>agent,socket</target>
  <out_format target="socket">$(timestamp %Y-%m-%dT%H:%M:%S): $(log)</out_format>
</localfile>
```

### `struct outformat`
A temporary structure for configuration parsing time. It will save the output format string and the name of the target.

### `struct logtarget`
An intermediate structure between the `logreader` and `logsocket`: it will point to a global target (with a socket) and will include a custom format string.

## Subtasks

- [X] Extend data structure.
- [x] Modify configuration parser.
- [x] Update post-configuration function (to fill `logtarget`).
- [x] Modify `SendMSGtoSCK()` to use build output format strings for each target.

**Comment by vikman90** [comment]
Working on branch: [3.4-outformat](https://github.com/wazuh/wazuh/tree/3.4-outformat)
