### ISSUE TITLE
Fix findings found after the analysis of the Framework/Cluster code

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#8343]
|Wazuh version|Component|
|---|---|
| master | Wazuh Framework - Cluster |

Hi team,

As we have commented in issue #7998, there are several functions in the framework and cluster code where a random number is calculated and used to identify a certain task or log.

This can cause that at a certain moment, even if the probability is low, a random number will be calculated for a task and this number was previously assigned to another task. This would cause the loss of the first task.

On the other hand, in several parts of the Framework code we handle XML files. These files are not sanitized, so these parts of the code are vulnerable to possible attacks such as https://en.wikipedia.org/wiki/Billion_laughs_attack. To solve this problem we must use the `defusedxml` library. Introduced in the Framework requirements.

More information here: https://github.com/wazuh/wazuh/issues/7998#issuecomment-824792766

### ToDo

- [x] Refactor pseudo-random generators
- [x] Sanitize XML files

Regards,

Adrián Peña

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by AdriiiPRodri** [comment]
## Status update

### Core unittests
```
adriiiprodri@wazuh PYTHONPATH=/home/adriiiprodri/git/wazuh/api:/home/adriiiprodri/git/wazuh/framework pytest -x framework/wazuh/core/tests --disable-warnings
================================================================================================ test session starts =================================================================================================
platform linux -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/git/wazuh/framework
plugins: tavern-1.14.0, metadata-1.11.0, html-3.1.1
collected 654 items                                                                                                                                                                                                  

framework/wazuh/core/tests/test_active_response.py ..............                                                                                                                                              [  2%]
framework/wazuh/core/tests/test_agent.py .............................................................................................................................................................         [ 26%]
framework/wazuh/core/tests/test_cdb_list.py ......................................                                                                                                                             [ 31%]
framework/wazuh/core/tests/test_common.py .......                                                                                                                                                              [ 33%]
framework/wazuh/core/tests/test_configuration.py ....................................                                                                                                                          [ 38%]
framework/wazuh/core/tests/test_decoder.py ................                                                                                                                                                    [ 40%]
framework/wazuh/core/tests/test_input_validator.py ...                                                                                                                                                         [ 41%]
framework/wazuh/core/tests/test_logtest.py ..                                                                                                                                                                  [ 41%]
framework/wazuh/core/tests/test_manager.py .................                                                                                                                                                   [ 44%]
framework/wazuh/core/tests/test_pyDaemonModule.py ......                                                                                                                                                       [ 45%]
framework/wazuh/core/tests/test_results.py ........................................                                                                                                                            [ 51%]
framework/wazuh/core/tests/test_rootcheck.py ..........                                                                                                                                                        [ 52%]
framework/wazuh/core/tests/test_rule.py ......................                                                                                                                                                 [ 56%]
framework/wazuh/core/tests/test_stats.py ....                                                                                                                                                                  [ 56%]
framework/wazuh/core/tests/test_syscollector.py ...                                                                                                                                                            [ 57%]
framework/wazuh/core/tests/test_utils.py ..................................................................................................................................................................... [ 82%]
......................................................                                                                                                                                                         [ 90%]
framework/wazuh/core/tests/test_vulnerability.py .                                                                                                                                                             [ 90%]
framework/wazuh/core/tests/test_wazuh_queue.py ..................                                                                                                                                              [ 93%]
framework/wazuh/core/tests/test_wazuh_socket.py ....................                                                                                                                                           [ 96%]
framework/wazuh/core/tests/test_wdb.py .....................                                                                                                                                                   [100%]

========================================================================================== 654 passed, 12 warnings in 2.42s ==========================================================================================
```

### Framework unittests
```
adriiiprodri@wazuh PYTHONPATH=/home/adriiiprodri/git/wazuh/api:/home/adriiiprodri/git/wazuh/framework pytest -x framework/wazuh/tests --disable-warnings 
================================================================================================ test session starts =================================================================================================
platform linux -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/git/wazuh/framework
plugins: tavern-1.14.0, metadata-1.11.0, html-3.1.1
collected 760 items                                                                                                                                                                                                  

framework/wazuh/tests/test_active_response.py ............                                                                                                                                                     [  1%]
framework/wazuh/tests/test_agent.py ...................................................................................................                                                                        [ 14%]
framework/wazuh/tests/test_cdb_list.py .....................................................                                                                                                                   [ 21%]
framework/wazuh/tests/test_ciscat.py .................................                                                                                                                                         [ 25%]
framework/wazuh/tests/test_cluster.py .....ss                                                                                                                                                                  [ 26%]
framework/wazuh/tests/test_decoder.py ...................................                                                                                                                                      [ 31%]
framework/wazuh/tests/test_group.py ........                                                                                                                                                                   [ 32%]
framework/wazuh/tests/test_logtest.py ......                                                                                                                                                                   [ 33%]
framework/wazuh/tests/test_manager.py .................................                                                                                                                                        [ 37%]
framework/wazuh/tests/test_mitre.py .......................................................................................................................................................................... [ 60%]
..........                                                                                                                                                                                                     [ 61%]
framework/wazuh/tests/test_rootcheck.py .................................................                                                                                                                      [ 67%]
framework/wazuh/tests/test_rule.py ........................................................                                                                                                                    [ 75%]
framework/wazuh/tests/test_sca.py .......                                                                                                                                                                      [ 76%]
framework/wazuh/tests/test_security.py ............................................................................                                                                                            [ 86%]
framework/wazuh/tests/test_stats.py ................                                                                                                                                                           [ 88%]
framework/wazuh/tests/test_syscheck.py ........................                                                                                                                                                [ 91%]
framework/wazuh/tests/test_syscollector.py ............                                                                                                                                                        [ 92%]
framework/wazuh/tests/test_task.py ............................                                                                                                                                                [ 96%]
framework/wazuh/tests/test_vulnerability.py ..........................                                                                                                                                         [100%]

============================================================================== 758 passed, 2 skipped, 930 warnings in 68.10s (0:01:08) ===============================================================================
```

### API unittests
```
adriiiprodri@wazuh PYTHONPATH=/home/adriiiprodri/git/wazuh/api:/home/adriiiprodri/git/wazuh/framework pytest -x api/api/test --disable-warnings 
================================================================================================ test session starts =================================================================================================
platform linux -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/git/wazuh/api
plugins: tavern-1.14.0, metadata-1.11.0, html-3.1.1
collected 225 items                                                                                                                                                                                                  

api/api/test/test_alogging.py ..........                                                                                                                                                                       [  4%]
api/api/test/test_authentication.py ..........                                                                                                                                                                 [  8%]
api/api/test/test_configuration.py .........................................                                                                                                                                   [ 27%]
api/api/test/test_util.py ...................................                                                                                                                                                  [ 42%]
api/api/test/test_validator.py .................................................................................................................................                                               [100%]

========================================================================================== 225 passed, 16 warnings in 1.21s ==========================================================================================
```

### Cluster unittests
```
adriiiprodri@wazuh PYTHONPATH=/home/adriiiprodri/git/wazuh/api:/home/adriiiprodri/git/wazuh/framework pytest -x framework/wazuh/core/cluster/tests --disable-warnings 
================================================================================================ test session starts =================================================================================================
platform linux -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/git/wazuh/framework
plugins: tavern-1.14.0, metadata-1.11.0, html-3.1.1
collected 56 items                                                                                                                                                                                                   

framework/wazuh/core/cluster/tests/test_cluster.py ...................                                                                                                                                         [ 33%]
framework/wazuh/core/cluster/tests/test_common.py .......                                                                                                                                                      [ 46%]
framework/wazuh/core/cluster/tests/test_control.py sssss                                                                                                                                                       [ 55%]
framework/wazuh/core/cluster/tests/test_local_client.py .                                                                                                                                                      [ 57%]
framework/wazuh/core/cluster/tests/test_utils.py .......                                                                                                                                                       [ 69%]
framework/wazuh/core/cluster/tests/test_worker.py ............sss.s                                                                                                                                            [100%]

===================================================================================== 47 passed, 9 skipped, 22 warnings in 0.50s =====================================================================================
```

**Comment by AdriiiPRodri** [comment]
## Status update

### Integration tests
```
adriiiprodri@wazuh python3 run_tests.py -rbac both -k manager
Collected tests [3]:
test_manager_endpoints.tavern.yaml, test_rbac_black_manager_endpoints.tavern.yaml, test_rbac_white_manager_endpoints.tavern.yaml


test_manager_endpoints.tavern.yaml 
	 31 passed, 33 warnings

test_rbac_black_manager_endpoints.tavern.yaml 
	 15 passed, 17 warnings

test_rbac_white_manager_endpoints.tavern.yaml 
	 15 passed, 17 warnings

adriiiprodri@wazuh python3 run_tests.py -rbac both -k rule   
Collected tests [3]:
test_rbac_black_rule_endpoints.tavern.yaml, test_rbac_white_rule_endpoints.tavern.yaml, test_rule_endpoints.tavern.yaml


test_rbac_black_rule_endpoints.tavern.yaml 
	 8 passed, 10 warnings

test_rbac_white_rule_endpoints.tavern.yaml 
	 8 passed, 10 warnings

test_rule_endpoints.tavern.yaml 
	 15 passed, 17 warnings

adriiiprodri@wazuh python3 run_tests.py -rbac both -k agent
Collected tests [6]:
test_agent_DELETE_endpoints.tavern.yaml, test_agent_GET_endpoints.tavern.yaml, test_agent_POST_endpoints.tavern.yaml, test_agent_PUT_endpoints.tavern.yaml, test_rbac_black_agent_endpoints.tavern.yaml, test_rbac_white_agent_endpoints.tavern.yaml


test_agent_DELETE_endpoints.tavern.yaml 
	 6 passed, 8 warnings

test_agent_GET_endpoints.tavern.yaml 
	 91 passed, 93 warnings

test_agent_POST_endpoints.tavern.yaml 
	 5 passed, 7 warnings

test_agent_PUT_endpoints.tavern.yaml 
	 10 passed, 12 warnings

test_rbac_black_agent_endpoints.tavern.yaml 
	 41 passed, 43 warnings

test_rbac_white_agent_endpoints.tavern.yaml 
	 41 passed, 43 warnings
```
