### ISSUE TITLE
Improve error handling when wazuh-control start with an error in ossec.conf

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#8361]
|Wazuh version|Component|
|---|---|
| master | Wazuh API |

Hi team,

Recently we have detected an unexpected error in the API. When we have an invalid `ossec.conf` for any reason and we try to restart Wazuh, the API throws an error that warns of a broken `ossec.conf` file.

```
root@wazuh-master:/# service wazuh-manager restart
wazuh-clusterd not running...
wazuh-modulesd not running...
wazuh-monitord not running...
wazuh-logcollector not running...
wazuh-remoted not running...
wazuh-syscheckd not running...
wazuh-analysisd not running...
wazuh-maild not running...
wazuh-execd not running...
wazuh-db not running...
wazuh-authd not running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid not running...
Wazuh v4.3.0 Stopped
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/xml/etree/ElementTree.py", line 1720, in feed
    self.parser.Parse(data, False)
xml.parsers.expat.ExpatError: mismatched tag: line 19, column 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/configuration.py", line 480, in get_ossec_conf
    xml_data = load_wazuh_xml(conf_file)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/utils.py", line 756, in load_wazuh_xml
    return ElementTree.fromstring(entities + '<root_tag>' + data + '</root_tag>')
  File "/var/ossec/framework/python/lib/python3.9/xml/etree/ElementTree.py", line 1347, in XML
    parser.feed(text)
  File "/var/ossec/framework/python/lib/python3.9/xml/etree/ElementTree.py", line 1722, in feed
    self._raiseerror(v)
  File "/var/ossec/framework/python/lib/python3.9/xml/etree/ElementTree.py", line 1629, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: mismatched tag: line 19, column 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/cluster/utils.py", line 58, in read_cluster_config
    config_cluster = get_ossec_conf(section='cluster', conf_file=config_file)['cluster']
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/configuration.py", line 485, in get_ossec_conf
    raise WazuhError(1101, extra_message=str(e))
wazuh.core.exception.WazuhError: Error 1101 - Requested component does not exist: mismatched tag: line 19, column 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/api/scripts/wazuh-apid.py", line 10, in <module>
    from api import alogging, configuration
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.3.0-py3.9.egg/api/alogging.py", line 11, in <module>
    from api.authentication import decode_token
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.3.0-py3.9.egg/api/authentication.py", line 22, in <module>
    from wazuh.core.cluster.dapi.dapi import DistributedAPI
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 26, in <module>
    from wazuh import agent
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/agent.py", line 23, in <module>
    cluster_enabled = not read_cluster_config()['disabled']
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/cluster/utils.py", line 65, in read_cluster_config
    raise WazuhError(3006, extra_message=e.message)
wazuh.core.exception.WazuhError: Error 3006 - Error reading cluster configuration: Requested component does not exist: mismatched tag: line 19, column 4
wazuh-apid: Configuration error. Exiting
```

We consider that it is more convenient that this message appears in the API/Wazuh log instead of in the terminal, in this way we let the other Wazuh daemons continue to run and we do not interrupt the execution of the command. In addition, we can better control this message so that it does not appear so much information, we can be more concrete.

## ToDo

- [x] Investigate the Wazuh API error when the ossec.conf file have an error.
- [x] Improve exception handling.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

Best regards,
Adrián Peña

**Comment by AdriiiPRodri** [comment]
## Status update

Hi team,

We have improved the handling of the exception thrown when the API loads the ossec.conf file and it has an error. Now we report the error and do not stop the command execution.

```
root@wazuh-master:/# service wazuh-manager restart
Killing wazuh-clusterd...
Killing wazuh-modulesd...
Killing wazuh-monitord...
Killing wazuh-logcollector...
Killing wazuh-remoted...
Killing wazuh-syscheckd...
Killing wazuh-analysisd...
wazuh-maild not running...
Killing wazuh-execd...
Killing wazuh-db...
Killing wazuh-authd...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
Killing wazuh-apid...
Wazuh v4.3.0 Stopped
wazuh-apid: There is an error in the ossec.conf file: mismatched tag: line 19, column 4
2021/04/26 11:52:52 wazuh-csyslogd: CRITICAL: (1226): Error reading XML file 'etc/ossec.conf':  (line 0).
wazuh-csyslogd: Configuration error. Exiting
```

**Comment by AdriiiPRodri** [comment]
## Unittests

### framework/wazuh/core/cluster/tests

```
adriiiprodri@wazuh pytest -x framework/wazuh/core/cluster/tests --disable-warnings
================================================================================================ test session starts =================================================================================================
platform linux -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/git/wazuh/framework
plugins: tavern-1.14.0, metadata-1.11.0, html-3.1.1
collected 56 items                                                                                                                                                                                                   

framework/wazuh/core/cluster/tests/test_cluster.py ...................                                                                                                                                         [ 33%]
framework/wazuh/core/cluster/tests/test_common.py .......                                                                                                                                                      [ 46%]
framework/wazuh/core/cluster/tests/test_control.py sssss                                                                                                                                                       [ 55%]
framework/wazuh/core/cluster/tests/test_local_client.py .                                                                                                                                                      [ 57%]
framework/wazuh/core/cluster/tests/test_utils.py .......                                                                                                                                                       [ 69%]
framework/wazuh/core/cluster/tests/test_worker.py ............sss.s                                                                                                                                            [100%]

===================================================================================== 47 passed, 9 skipped, 22 warnings in 0.55s =====================================================================================
```

### framework/wazuh/core/cluster/dapi/tests

```
adriiiprodri@wazuh pytest -x framework/wazuh/core/cluster/dapi/tests --disable-warnings
================================================================================================ test session starts =================================================================================================
platform linux -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/git/wazuh/framework
plugins: tavern-1.14.0, metadata-1.11.0, html-3.1.1
collected 23 items                                                                                                                                                                                                   

framework/wazuh/core/cluster/dapi/tests/test_dapi.py .......................                                                                                                                                   [100%]

========================================================================================== 23 passed, 12 warnings in 0.69s ===========================================================================================
```

### framework/wazuh/core/tests

```
adriiiprodri@wazuh pytest -x framework/wazuh/core/tests --disable-warnings
================================================================================================ test session starts =================================================================================================
platform linux -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/git/wazuh/framework
plugins: tavern-1.14.0, metadata-1.11.0, html-3.1.1
collected 654 items                                                                                                                                                                                                  

framework/wazuh/core/tests/test_active_response.py ..............                                                                                                                                              [  2%]
framework/wazuh/core/tests/test_agent.py .............................................................................................................................................................         [ 26%]
framework/wazuh/core/tests/test_cdb_list.py ......................................                                                                                                                             [ 31%]
framework/wazuh/core/tests/test_common.py .......                                                                                                                                                              [ 33%]
framework/wazuh/core/tests/test_configuration.py ....................................                                                                                                                          [ 38%]
framework/wazuh/core/tests/test_decoder.py ................                                                                                                                                                    [ 40%]
framework/wazuh/core/tests/test_input_validator.py ...                                                                                                                                                         [ 41%]
framework/wazuh/core/tests/test_logtest.py ..                                                                                                                                                                  [ 41%]
framework/wazuh/core/tests/test_manager.py .................                                                                                                                                                   [ 44%]
framework/wazuh/core/tests/test_pyDaemonModule.py ......                                                                                                                                                       [ 45%]
framework/wazuh/core/tests/test_results.py ........................................                                                                                                                            [ 51%]
framework/wazuh/core/tests/test_rootcheck.py ..........                                                                                                                                                        [ 52%]
framework/wazuh/core/tests/test_rule.py ......................                                                                                                                                                 [ 56%]
framework/wazuh/core/tests/test_stats.py ....                                                                                                                                                                  [ 56%]
framework/wazuh/core/tests/test_syscollector.py ...                                                                                                                                                            [ 57%]
framework/wazuh/core/tests/test_utils.py ..................................................................................................................................................................... [ 82%]
......................................................                                                                                                                                                         [ 90%]
framework/wazuh/core/tests/test_vulnerability.py .                                                                                                                                                             [ 90%]
framework/wazuh/core/tests/test_wazuh_queue.py ..................                                                                                                                                              [ 93%]
framework/wazuh/core/tests/test_wazuh_socket.py ....................                                                                                                                                           [ 96%]
framework/wazuh/core/tests/test_wdb.py .....................                                                                                                                                                   [100%]

========================================================================================== 654 passed, 12 warnings in 2.17s ==========================================================================================
```

### framework/wazuh/tests

```
adriiiprodri@wazuh pytest -x framework/wazuh/tests --disable-warnings 
================================================================================================ test session starts =================================================================================================
platform linux -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/git/wazuh/framework
plugins: tavern-1.14.0, metadata-1.11.0, html-3.1.1
collected 760 items                                                                                                                                                                                                  

framework/wazuh/tests/test_active_response.py ............                                                                                                                                                     [  1%]
framework/wazuh/tests/test_agent.py ...................................................................................................                                                                        [ 14%]
framework/wazuh/tests/test_cdb_list.py .....................................................                                                                                                                   [ 21%]
framework/wazuh/tests/test_ciscat.py .................................                                                                                                                                         [ 25%]
framework/wazuh/tests/test_cluster.py .....ss                                                                                                                                                                  [ 26%]
framework/wazuh/tests/test_decoder.py ...................................                                                                                                                                      [ 31%]
framework/wazuh/tests/test_group.py ........                                                                                                                                                                   [ 32%]
framework/wazuh/tests/test_logtest.py ......                                                                                                                                                                   [ 33%]
framework/wazuh/tests/test_manager.py .................................                                                                                                                                        [ 37%]
framework/wazuh/tests/test_mitre.py .......................................................................................................................................................................... [ 60%]
..........                                                                                                                                                                                                     [ 61%]
framework/wazuh/tests/test_rootcheck.py .................................................                                                                                                                      [ 67%]
framework/wazuh/tests/test_rule.py ........................................................                                                                                                                    [ 75%]
framework/wazuh/tests/test_sca.py .......                                                                                                                                                                      [ 76%]
framework/wazuh/tests/test_security.py ............................................................................                                                                                            [ 86%]
framework/wazuh/tests/test_stats.py ................                                                                                                                                                           [ 88%]
framework/wazuh/tests/test_syscheck.py ........................                                                                                                                                                [ 91%]
framework/wazuh/tests/test_syscollector.py ............                                                                                                                                                        [ 92%]
framework/wazuh/tests/test_task.py ............................                                                                                                                                                [ 96%]
framework/wazuh/tests/test_vulnerability.py ..........................                                                                                                                                         [100%]

=================================================================================== 758 passed, 2 skipped, 930 warnings in 54.37s ====================================================================================
```

### framework/wazuh/rbac/tests

```
adriiiprodri@wazuh pytest -x framework/wazuh/rbac/tests --disable-warnings 
================================================================================================ test session starts =================================================================================================
platform linux -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/git/wazuh/framework
plugins: tavern-1.14.0, metadata-1.11.0, html-3.1.1
collected 227 items                                                                                                                                                                                                  

framework/wazuh/rbac/tests/test_auth_context.py ..                                                                                                                                                             [  0%]
framework/wazuh/rbac/tests/test_decorators.py .........................................................................................................                                                        [ 47%]
framework/wazuh/rbac/tests/test_default_configuration.py .......................................................                                                                                               [ 71%]
framework/wazuh/rbac/tests/test_orm.py ......................................................                                                                                                                  [ 95%]
framework/wazuh/rbac/tests/test_preprocessor.py ...........                                                                                                                                                    [100%]

=================================================================================== 227 passed, 2728 warnings in 139.12s (0:02:19) ===================================================================================
```

### api/api/test

```
adriiiprodri@wazuh pytest -x api/api/test --disable-warnings 
================================================================================================ test session starts =================================================================================================
platform linux -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/git/wazuh/api
plugins: tavern-1.14.0, metadata-1.11.0, html-3.1.1
collected 225 items                                                                                                                                                                                                  

api/api/test/test_alogging.py ..........                                                                                                                                                                       [  4%]
api/api/test/test_authentication.py ..........                                                                                                                                                                 [  8%]
api/api/test/test_configuration.py .........................................                                                                                                                                   [ 27%]
api/api/test/test_util.py ...................................                                                                                                                                                  [ 42%]
api/api/test/test_validator.py .................................................................................................................................                                               [100%]

========================================================================================== 225 passed, 16 warnings in 1.19s ==========================================================================================
```
