### ISSUE TITLE
Amazon Linux support: Add configuration for the new provider

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#8367]
### Description

Adding support for Amazon Linux in Vulnerability Detector involves the module to fetch feeds from a new provider for those platforms:

- Amazon Linux: https://alas.aws.amazon.com/alas.rss
- Amazon Linux 2: https://alas.aws.amazon.com/AL2/alas.rss

They won't be directly pulled from the official repositories but from feed.wazuh.com.

The Vulnerability Detector configuration has to include a new block to configure the gathering of these feeds:

```xml
<provider name="alas">
  <enabled>no</enabled>
  <os>amazon-linux</os>
  <os>amazon-linux-2</os>
  <update_interval>1h</update_interval>
</provider>
```

In addition, both feeds have to support the offline update from custom locations:

```xml
<os path="/custom/path/amazon-linux.json">amazon-linux</os>
<os url="https://localhost/amazon-linux.json">amazon-linux</os>
```

### Tasks

- [x] Create the configuration template
- [x] Create the configuration reader for the new provider
- [x] Create the functions to fetch the feeds when they are found in the configuration
- [x] Create UT for the added functions

**Comment by chemamartinez** [comment]
Main devel branch: https://github.com/wazuh/wazuh/tree/6734-alas-support

**Comment by alromeros** [comment]
**Devel branch:** https://github.com/wazuh/wazuh/tree/8367-alas-provider-config
**Pull Request:** https://github.com/wazuh/wazuh/pull/8425
