### ISSUE TITLE
Merge macos-sshd ruleset into sshd ruleset

### ISSUE THREAD

**Issue by JavierBejMen** [wazuh/wazuh#8501]
## Description
With the forecomming predecoder update to take macos-sshd timestamps, current ruleset for said service will be absorved by sshd ruleset, so we need to merge macos-sshd ruleset into sshd ruleset.

### Related issue
#8427

## Tasks
- [x] Add required decoders from macos-sshd to sshd
- [x] Add required rules from macos-sshd to sshd
- [ ] Delete macos-sshd rules/decoders/.ini
- [x] Adjust test file .ini to the new sshd ruleset
- [ ] Test solution

**Comment by JavierBejMen** [comment]
# Github branch
Branch to track changes: https://github.com/wazuh/wazuh/tree/8501_merge_macos_sshd_ruleset

**Comment by JavierBejMen** [comment]
# Update
Merged decoders, changes:

- macos-sshd-success --> sshd-success (added srcport decoding)
- macos-sshd-error --> ssh-scan2 (added "Broken pipe" prematch and changed after_prematch to after_parent, fixed space)
- macos-sshd-rmap --> sshd-rmap (new)
- macos-sshd-rmap-2 --> ssh-reverse-mapping
- macos-sshd-reset --> sshd-reset (new)
- macos-sshd-disconnect --> sshd-disconnect (new)
- macos-sshd-insecure-connection --> ssh-scan2
- macos-sshd-closed --> ssh-closed (added srcport decoding)
- macos-sshd-from --> sshd-from (new)(removed prematch user (\S+) from (\S+))
                                --> ssh-denied
- macos-sshd-from --> (removed)

**Comment by JavierBejMen** [comment]
# Update
Merged rules, changes:
- 64251 --> 5710
- 64252 --> 5712
- 64253 --> 5760 (new)
- 64254 --> 5758
- 64255 --> 5722 (Connection closed)
--> 5761(new) (Disconnected from user)
- 64256 --> 5715
- 64257 --> 5706
- 64258 --> 5735
- 64259 --> 5762 (new)
- 64260 --> 5763 (new)
- 64261 --> 5764 (new)
- 64262 --> 5702
--> 5757
- 64263 --> 5703
- 64264 --> 5701

**Comment by JavierBejMen** [comment]
# Update
Merged .inis, changes:

- [SSHD Attempt to login using a non-existent user] -> [invalid user]
- [SSHD Authentication error] --> [SSHD Authentication error]
- [SSHD Maximum authentication attempts exceeded] --> [max auth attempts]
- [SSHD Disconnect] --> [SSHD Connection close]
--> [SSHD Disconnected from]
- [SSHD Authentication success] --> [SSHD Authentication success]
- [SSHD insecure connection attempt] --> [SSHD insecure connection attempt]
- [SSHD: Failed write] --> [SSHD: Failed write]
- [SSHD: connection reset] --> [SSHD: connection reset]
- [SSHD: denied user] --> [SSHD: denied user]
- [SSHD: Reverse lookup error] --> [SSHD: Reverse lookup error]
--> [bad dns]
- [SSHD: possible attack] --> [SSHD: possible attack]

**Comment by JavierBejMen** [comment]
# Blocked
Only is left testing solution, until changes to predecoder are done this issue is blocked.
