### ISSUE TITLE
Optimize the flow followed for each API request

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#8594]
Hi team,

Currently, each request sent to the API (except for authentication calls) goes through. The process is as follows:

1. We request a token from the API
```
TOKEN=$(curl -u wazuh:wazuh -k -X GET "https://localhost:55000/security/user/authenticate?raw=true")
```

2. We send the request to the API:
```
curl -k -X GET "https://localhost:55000/agents?pretty=true" -H "Authorization: Bearer $TOKEN"
```

3. First, we execute the [decode_token](https://github.com/wazuh/wazuh/blob/46921975a22719e1f6c6dda0e6a6faa6b7358f4d/api/api/authentication.py#L200) function, this function is in charge of decoding the token of the user.

- Then, the function check_token which checks the validity of the token based on time checks that the user exists and if necessary checks if you have enabled the `run_as` option. Finally, when all this is checked and everything is correct the policies are processed from the database to obtain a data structure easier and faster to handle.

- Once obtained an optimal data structure and checked the validity of the token, the jwt data is checked with the current settings of the API, this way if the RBAC mode or the expiration time is greater than the subtraction of the key `exp` and `nbf` of the token, a warning will be sent to the user indicating that the provided token is not authorized.

4. The Framework function needed to obtain the data is executed.

5. The output is post-processed, in this step, the errors thrown by the Framework are formatted and unnecessary fields are eliminated.

Our goal is to optimize step 3.1, to do this we have an initial idea. We know the lifetime of each of the tokens given by the API. This information is self-contained in the token itself. In addition to this, we have the API configuration itself, where we can specify the lifetime of these.

Having this information, we can save the [check_token](https://github.com/wazuh/wazuh/blob/46921975a22719e1f6c6dda0e6a6faa6b7358f4d/api/api/authentication.py#L160) function in cache indicating that this saved value is valid for the same amount of time that the API tokens are valid. This approach would be valid in case the token would be used at the same time the token is generated, however, it is possible that the token is not used as soon as it is issued. Because of this, it is necessary to check before reaching the cached function (`check_token`) that the token is still valid. To do this we subtract the key 'nbf' from the key 'exp' of the token itself.

## ToDo

 - [x] Apply cache based on token expiration time to the function check_token
 - [x] Modify the decode_token function to check in advance the validity of the token.
 - [x] Update unittests

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by AdriiiPRodri** [comment]
## Status update

### QA integration test
```
root@wazuh-master:/wazuh-qa# /var/ossec/framework/python/bin/python3 -m pytest tests/integration/test_api/
/var/ossec/framework/python/lib/python3.9/site-packages/_testinfra_renamed.py:5: DeprecationWarning: testinfra package has been renamed to pytest-testinfra. Please `pip install pytest-testinfra` and `pip uninstall testinfra` and update your package requirements to avoid this message
  warnings.warn((
=========================================== test session starts ===========================================
platform linux -- Python 3.9.2, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /wazuh-qa/tests/integration, configfile: pytest.ini
plugins: testinfra-6.3.0, testinfra-6.0.0, metadata-1.11.0, html-3.1.1
collected 78 items                                                                                        

tests/integration/test_api/test_config/test_DOS_blocking_system/test_DOS_blocking_system.py .ss.    [  5%]
tests/integration/test_api/test_config/test_bruteforce_blocking_system/test_bruteforce_blocking_system.py . [  6%]
ss.                                                                                                 [ 10%]
tests/integration/test_api/test_config/test_cache/test_cache.py .ss.                                [ 15%]
tests/integration/test_api/test_config/test_cors/test_cors.py xX                                    [ 17%]
tests/integration/test_api/test_config/test_drop_privileges/test_drop_privileges.py .ss.            [ 23%]
tests/integration/test_api/test_config/test_experimental_features/test_experimental_features.py .ss [ 26%]
.                                                                                                   [ 28%]
tests/integration/test_api/test_config/test_host_port/test_host_port.py .s.ss.s.                    [ 38%]
tests/integration/test_api/test_config/test_https/test_https.py .ss.                                [ 43%]
tests/integration/test_api/test_config/test_jwt_token_exp_timeout/test_jwt_token_exp_timeout.py .ss [ 47%]
.                                                                                                   [ 48%]
tests/integration/test_api/test_config/test_logs/test_logs.py .ss.                                  [ 53%]
tests/integration/test_api/test_config/test_rbac/test_rbac_mode.py .ss.                             [ 58%]
tests/integration/test_api/test_config/test_use_only_authd/test_use_only_authd.py .s.s.s.ss.s.s.s.  [ 79%]
tests/integration/test_api/test_rbac/test_add_old_resource.py ....                                  [ 84%]
tests/integration/test_api/test_rbac/test_admin_resources.py ....                                   [ 89%]
tests/integration/test_api/test_rbac/test_policy_position.py .                                      [ 91%]
tests/integration/test_api/test_rbac/test_remove_relationship.py ...                                [ 94%]
tests/integration/test_api/test_rbac/test_remove_resource.py ....                                   [100%]

============== 46 passed, 30 skipped, 1 xfailed, 1 xpassed, 43 warnings in 766.19s (0:12:46) ==============
```

### System tests
```
adriiiprodri@wazuh pytest -xs test_jwt_invalidation 

================================================================================================ test session starts =================================================================================================
platform linux -- Python 3.9.2, pytest-5.4.3, py-1.10.0, pluggy-0.13.1
rootdir: /home/adriiiprodri/git/wazuh-qa/tests/system
plugins: metadata-1.11.0, html-2.1.1, cov-2.10.1, asyncio-0.12.0, tavern-1.0.0, testinfra-6.3.0, testinfra-6.0.0
collected 19 items                                                                                                                                                                                                   

test_jwt_invalidation/test_change_rbac_mode.py ....
test_jwt_invalidation/test_change_security_resources.py ....
test_jwt_invalidation/test_disconnected_nodes.py .
test_jwt_invalidation/test_revoke_endpoint.py ......
test_jwt_invalidation/test_update_password.py ....

=========================================================================================== 19 passed in 955.53s (0:15:55) ===========================================================================================
```
