### ISSUE TITLE
Cluster: Improve performance

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh#861]
The data transfer speed of the cluster is not enough.

We will move to *Python 3.7.1* and *asyncio*.

- [x] Embebed Python in Wazuh (https://github.com/wazuh/wazuh/issues/2400).
- [x] Adapt cluster to asyncio (https://github.com/wazuh/wazuh/pull/2493):
  - [x] Communication layer (https://github.com/wazuh/wazuh/issues/1903).
  - [x] Wazuh layer (https://github.com/wazuh/wazuh/issues/1975).
  - [x] Internal socket (https://github.com/wazuh/wazuh/issues/1976).
  - [x] Distributed API (https://github.com/wazuh/wazuh/issues/2017).
  - [x] SSL (included in Communication layer, but not enabled).
- [x] Performance analysis and define cluster specifications (https://github.com/wazuh/wazuh/issues/2061)
- [x] Testing asyncio (https://github.com/wazuh/wazuh/issues/2063)
- [x] Global test (https://github.com/wazuh/wazuh/issues/2520)
- [x] Documentation (https://github.com/wazuh/wazuh-documentation/pull/924)

**Comment by jesuslinares** [comment]
Great job @mgmacias95 and @BraulioV. Finally, we have Python 3 embedded + _asyncio_ and the cluster performance is much better.
