### ISSUE TITLE
Gather logs to cover all rules and decoders testing through .inis (Set 1)

### ISSUE THREAD

**Issue by JavierBejMen** [wazuh/wazuh#8647]
# Description
Gather logs examples to be able to test all rules and decoders.

# Tasks

- [ ]  0010-rules_config.xml
- [ ]  0015-ossec_rules.xml
- [ ]  0016-wazuh_rules.xml
- [ ]  0020-syslog_rules.xml
- [ ]  0025-sendmail_rules.xml
- [ ]  0030-postfix_rules.xml
- [ ]  0035-spamd_rules.xml
- [ ]  0040-imapd_rules.xml
- [ ]  0045-mailscanner_rules.xml
- [ ]  0050-ms-exchange_rules.xml
- [ ]  0055-courier_rules.xml
- [ ]  0065-pix_rules.xml
- [ ]  0070-netscreenfw_rules.xml
- [ ]  0075-cisco-ios_rules.xml
- [ ]  0080-sonicwall_rules.xml
- [ ]  0085-pam_rules.xml
- [ ]  0090-telnetd_rules.xml
- [ ]  0095-sshd_rules.xml
- [ ]  0100-solaris_bsm_rules.xml
