### ISSUE TITLE
Gather logs to cover all rules and decoders testing through .inis (Set 2)

### ISSUE THREAD

**Issue by JavierBejMen** [wazuh/wazuh#8649]
# Description
Gather logs examples to be able to test all rules and decoders.

# Tasks
- [ ]  0105-asterisk_rules.xml
- [ ]  0110-ms_dhcp_rules.xml
- [ ]  0115-arpwatch_rules.xml
- [ ]  0120-symantec-av_rules.xml
- [ ]  0125-symantec-ws_rules.xml
- [ ]  0130-trend-osce_rules.xml
- [ ]  0135-hordeimp_rules.xml
- [ ]  0140-roundcube_rules.xml
- [ ]  0145-wordpress_rules.xml
- [ ]  0150-cimserver_rules.xml
- [ ]  0155-dovecot_rules.xml
- [ ]  0160-vmpop3d_rules.xml
- [ ]  0165-vpopmail_rules.xml
- [ ]  0170-ftpd_rules.xml
- [ ]  0175-proftpd_rules.xml
- [ ]  0180-pure-ftpd_rules.xml
- [ ]  0185-vsftpd_rules.xml
- [ ]  0190-ms_ftpd_rules.xml
- [ ]  0195-named_rules.xml
- [ ]  0200-smbd_rules.xml
