### ISSUE TITLE
Gather logs to cover all rules and decoders testing through .inis (Set 3)

### ISSUE THREAD

**Issue by JavierBejMen** [wazuh/wazuh#8650]
# Description
Gather logs examples to be able to test all rules and decoders.

# Tasks
- [ ]  0205-racoon_rules.xml
- [ ]  0210-vpn_concentrator_rules.xml
- [ ]  0215-policy_rules.xml
- [ ]  0220-msauth_rules.xml
- [ ]  0225-mcafee_av_rules.xml
- [ ]  0230-ms-se_rules.xml
- [ ]  0235-vmware_rules.xml
- [ ]  0240-ids_rules.xml
- [ ]  0245-web_rules.xml
- [ ]  0250-apache_rules.xml
- [ ]  0255-zeus_rules.xml
- [ ]  0260-nginx_rules.xml
- [ ]  0265-php_rules.xml
- [ ]  0270-web_appsec_rules.xml
- [ ]  0275-squid_rules.xml
- [ ]  0280-attack_rules.xml
- [ ]  0285-systemd_rules.xml
- [ ]  0290-firewalld_rules.xml
- [ ]  0295-mysql_rules.xml
- [ ]  0300-postgresql_rules.xml
