### ISSUE TITLE
Gather logs to cover all rules and decoders testing through .inis (Set 4)

### ISSUE THREAD

**Issue by JavierBejMen** [wazuh/wazuh#8651]
# Description
Gather logs examples to be able to test all rules and decoders.

# Tasks
- [ ]  0305-dropbear_rules.xml
- [ ]  0310-openbsd_rules.xml
- [ ]  0315-apparmor_rules.xml
- [ ]  0320-clam_av_rules.xml
- [ ]  0325-opensmtpd_rules.xml
- [ ]  0330-sysmon_rules.xml
- [ ]  0335-unbound_rules.xml
- [ ]  0340-puppet_rules.xml
- [ ]  0345-netscaler_rules.xml
- [ ]  0350-amazon_rules.xml
- [ ]  0360-serv-u_rules.xml
- [ ]  0365-auditd_rules.xml
- [ ]  0375-usb_rules.xml
- [ ]  0380-redis_rules.xml
- [ ]  0385-oscap_rules.xml
- [ ]  0390-fortigate_rules.xml
- [ ]  0395-hp_rules.xml
- [ ]  0400-openvpn_rules.xml
- [ ]  0405-rsa-auth-manager_rules.xml
- [ ]  0410-imperva_rules.xml
