### ISSUE TITLE
Gather logs to cover all rules and decoders testing through .inis (Set 5)

### ISSUE THREAD

**Issue by JavierBejMen** [wazuh/wazuh#8652]
# Description
Gather logs examples to be able to test all rules and decoders.

# Tasks
- [ ]  0415-sophos_rules.xml
- [ ]  0420-freeipa_rules.xml
- [ ]  0425-cisco-estreamer_rules.xml
- [ ]  0430-ms_wdefender_rules.xml
- [ ]  0435-ms_logs_rules.xml
- [ ]  0440-ms_sqlserver_rules.xml
- [ ]  0445-identity_guard_rules.xml
- [ ]  0450-mongodb_rules.xml
- [ ]  0455-docker_rules.xml
- [ ]  0460-jenkins_rules.xml
- [ ]  0470-vshell_rules.xml
- [ ]  0475-suricata_rules.xml
- [ ]  0480-qualysguard_rules.xml
- [ ]  0485-cylance_rules.xml
- [ ]  0490-virustotal_rules.xml
- [ ]  0495-proxmox-ve_rules.xml
- [ ]  0500-owncloud_rules.xml
- [ ]  0505-vuls_rules.xml
- [ ]  0510-ciscat_rules.xml
- [ ]  0515-exim_rules.xml
