### ISSUE TITLE
Gather logs to cover all rules and decoders testing through .inis (Set 6)

### ISSUE THREAD

**Issue by JavierBejMen** [wazuh/wazuh#8653]
# Description
Gather logs examples to be able to test all rules and decoders.

# Tasks
- [ ] 0520-vulnerability-detector_rules.xml
- [ ]  0525-openvas_rules.xml
- [ ]  0530-mysql_audit_rules.xml
- [ ]  0535-mariadb_rules.xml
- [ ]  0540-pfsense_rules.xml
- [ ]  0545-osquery_rules.xml
- [ ]  0550-kaspersky_rules.xml
- [ ]  0555-azure_rules.xml
- [ ]  0560-docker_integration_rules.xml
- [ ]  0565-ms_ipsec_rules.xml
- [ ]  0570-sca_rules.xml
- [ ]  0575-win-base_rules.xml
- [ ]  0580-win-security_rules.xml
- [ ]  0585-win-application_rules.xml
- [ ]  0590-win-system_rules.xml
- [ ]  0595-win-sysmon_rules.xml
- [ ]  0600-win-wdefender_rules.xml
- [ ]  0601-win-vipre_rules.xml
- [ ]  0602-win-wfirewall_rules.xml
- [ ]  0605-win-mcafee_rules.xml
