### ISSUE TITLE
Gather logs to cover all rules and decoders testing through .inis (Set 7)

### ISSUE THREAD

**Issue by JavierBejMen** [wazuh/wazuh#8654]
# Description
Gather logs examples to be able to test all rules and decoders.

# Tasks
- [ ]  0610-win-ms_logs_rules.xml
- [ ]  0615-win-ms-se_rules.xml
- [ ]  0620-win-generic_rules.xml
- [ ]  0625-cisco-asa_rules.xml
- [ ]  0625-mcafee_epo_rules.xml
- [ ]  0630-nextcloud_rules.xml
- [ ]  0635-owlh-zeek_rules.xml
- [ ]  0640-junos_rules.xml
- [ ]  0675-panda-paps_rules.xml
- [ ]  0680-checkpoint-smart1_rules.xml
- [ ]  0685-macos-sshd_rules.xml
- [ ]  0690-gcp_rules.xml
- [ ]  0700-paloalto_rules.xml
- [ ]  0705-sophos_fw_rules.xml
- [ ]  0710-wazuh-api-rules.xml
- [ ]  0900-firewall_rules.xml
