### ISSUE TITLE
Gather logs to cover all rules and decoders testing through .inis (Set 8)

### ISSUE THREAD

**Issue by JavierBejMen** [wazuh/wazuh#8655]
# Description
Gather logs examples to be able to test all rules and decoders.

# Tasks
- [ ]  0005-wazuh_decoders.xml
- [ ]  0006-json_decoders.xml
- [ ]  0010-active-response_decoders.xml
- [ ]  0015-aix-ipsec_decoders.xml
- [ ]  0025-apache_decoders.xml
- [ ]  0030-arpwatch_decoders.xml
- [ ]  0035-asterisk_decoders.xml
- [ ]  0040-auditd_decoders.xml
- [ ]  0045-barracuda_decoders.xml
- [ ]  0050-checkpoint_decoders.xml
- [ ]  0051-checkpoint-smart1_decoders.xml
- [ ]  0055-cimserver_decoders.xml
- [ ]  0060-cisco-estreamer_decoders.xml
- [ ]  0063-pix_decoders.xml
- [ ]  0064-cisco-asa_decoders.xml
- [ ]  0065-cisco-ios_decoders.xml
- [ ]  0070-cisco-vpn_decoders.xml
- [ ]  0075-clamav_decoders.xml
- [ ]  0080-courier_decoders.xml
- [ ]  0085-dovecot_decoders.xml
