### ISSUE TITLE
Gather logs to cover all rules and decoders testing through .inis (Set 9)

### ISSUE THREAD

**Issue by JavierBejMen** [wazuh/wazuh#8656]
# Description
Gather logs examples to be able to test all rules and decoders.

# Tasks
- [ ]  0090-dragon-nids_decoders.xml
- [ ]  0095-dropbear_decoders.xml
- [ ]  0100-fortigate_decoders.xml
- [ ]  0105-freeipa_decoders.xml
- [ ]  0110-ftpd_decoders.xml
- [ ]  0115-grandstream_decoders.xml
- [ ]  0120-horde_decoders.xml
- [ ]  0125-hp_decoders.xml
- [ ]  0130-imapd_decoders.xml
- [ ]  0135-imperva_decoders.xml
- [ ]  0140-kernel_decoders.xml
- [ ]  0145-mailscanner_decoders.xml
- [ ]  0150-mysql_decoders.xml
- [ ]  0155-named_decoders.xml
- [ ]  0160-netscaler_decoders.xml
- [ ]  0165-netscreen_decoders.xml
- [ ]  0170-nginx_decoders.xml
- [ ]  0175-ntpd_decoders.xml
- [ ]  0180-openbsd_decoders.xml
- [ ]  0185-openldap_decoders.xml
