### ISSUE TITLE
Gather logs to cover all rules and decoders testing through .inis (Set 10)

### ISSUE THREAD

**Issue by JavierBejMen** [wazuh/wazuh#8657]
# Description
Gather logs examples to be able to test all rules and decoders.

# Tasks
- [ ]  0190-openvpn_decoders.xml
- [ ]  0195-oscap_decoders.xml
- [ ]  0200-ossec_decoders.xml
- [ ]  0205-pam_decoders.xml
- [ ]  0215-portsentry_decoders.xml
- [ ]  0220-postfix_decoders.xml
- [ ]  0225-postgresql_decoders.xml
- [ ]  0230-proftpd_decoders.xml
- [ ]  0235-puppet_decoders.xml
- [ ]  0240-pure-ftpd_decoders.xml
- [ ]  0245-racoon_decoders.xml
- [ ]  0250-redis_decoders.xml
- [ ]  0255-roundcube_decoders.xml
- [ ]  0260-rsa-auth-manager_decoders.xml
- [ ]  0265-rshd_decoders.xml
- [ ]  0270-samba_decoders.xml
- [ ]  0275-sendmail_decoders.xml
- [ ]  0280-serv-u_decoders.xml
- [ ]  0285-snort_decoders.xml
- [ ]  0290-solaris_decoders.xml
