### ISSUE TITLE
Gather logs to cover all rules and decoders testing through .inis (Set 11)

### ISSUE THREAD

**Issue by JavierBejMen** [wazuh/wazuh#8658]
# Description
Gather logs examples to be able to test all rules and decoders.

# Tasks
- [ ] 0295-sonicwall_decoders.xml
- [ ]  0300-sophos_decoders.xml
- [ ]  0305-squid_decoders.xml
- [ ]  0310-ssh_decoders.xml
- [ ]  0315-su_decoders.xml
- [ ]  0320-sudo_decoders.xml
- [ ]  0325-suhosin_decoders.xml
- [ ]  0330-symantec_decoders.xml
- [ ]  0335-telnet_decoders.xml
- [ ]  0340-trend-osce_decoders.xml
- [ ]  0345-unbound_decoders.xml
- [ ]  0350-unix_decoders.xml
- [ ]  0355-vm-pop3_decoders.xml
- [ ]  0360-vmware_decoders.xml
- [ ]  0365-vpopmail_decoders.xml
- [ ]  0370-vsftpd_decoders.xml
- [ ]  0375-web-accesslog_decoders.xml
- [ ]  0378-mariadb_decoders.xml
- [ ]  0379-dpkg_decoders.xml
- [ ]  0380-windows_decoders.xml
