### ISSUE TITLE
Gather logs to cover all rules and decoders testing through .inis (Set 12)

### ISSUE THREAD

**Issue by JavierBejMen** [wazuh/wazuh#8659]
# Description
Gather logs examples to be able to test all rules and decoders.

# Tasks
- [ ] 0385-wordpress_decoders.xml
- [ ]  0390-zeus_decoders.xml
- [ ]  0395-sqlserver_decoders.xml
- [ ]  0400-identity_guard_decoders.xml
- [ ]  0405-mongodb_decoders.xml
- [ ]  0410-docker_decoders.xml
- [ ]  0415-jenkins_decoders.xml
- [ ]  0420-vshell_decoders.xml
- [ ]  0425-qualysguard_decoders.xml
- [ ]  0430-cylance_decoders.xml
- [ ]  0435-owncloud_decoders.xml
- [ ]  0440-proxmox-ve_decoders.xml
- [ ]  0445-exim_decoders.xml
- [ ]  0450-openvas_decoders.xml
- [ ]  0455-pfsense_decoders.xml
- [ ]  0460-kaspersky_decoders.xml
- [ ]  0465-azure_decoders.xml
- [ ]  0470-panda-paps_decoders.xml
- [ ]  0475-mcafee_decoders.xml
- [ ]  0480-perdition_decoders.xml
- [ ]  0485-nextcloud_decoders.xml
- [ ]  0490-junos_decoders.xml
- [ ]  0500-macos-sshd_decoders.xml
- [ ]  0505-paloalto_decoders.xml
- [ ]  0510-sophos_fw_decoders.xml
- [ ]  0515-wazuh-api-decoders.xml
