### ISSUE TITLE
Overreaching sibling decoders for Sophos

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh#8675]
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.2.0-40203 | Decoders | Error |

## Description
The new Sophos decoders which use sibling decoders to extract information are not correctly declared in many cases.
Many use an `OR` logic that looks for the field either and its value followed by spaces or just the full line.
The consequence is that if the field is not present in the log the whole log is parsed in its stead.

## Reason
All decoders declared like this:
```
<decoder name="sophos-fw">
  <parent>sophos-fw</parent>
  <regex>device_id=(\w*)\s+|(\.*)$</regex>
  <order>device_id</order>
</decoder>
```
Should be declared like this:
```
<decoder name="sophos-fw">
  <parent>sophos-fw</parent>
  <regex>device_id=(\w*)\s+|device_id=(\w*)$</regex>
  <order>device_id</order>
</decoder>
```

### Current results
```
echo 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0' | /var/ossec/bin/wazuh-logtest
Starting wazuh-logtest v4.2.0
Type one log per line


**Phase 1: Completed pre-decoding.
        full event: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'

**Phase 2: Completed decoding.
        name: 'sophos-fw'
        appfilter_policy_id: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        application: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        application_category: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        application_risk: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        application_technology: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        appresolvedby: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        connevent: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        connid: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        date: '2021-06-05'
        device: 'SFW'
        device_id: 'C0A0B0D0E0F0G66'
        device_name: 'XG86'
        dir_disp: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        dst_country_code: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        dst_ip: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        dst_port: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        dstzone: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        dstzonetype: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        duration: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        fw_rule_id: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        hb_health: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        iap: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        in_interface: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        ips_policy_id: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        log_component: 'Wireless Protection'
        log_id: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        log_subtype: 'Information'
        log_type: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        message: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        out_interface: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        policy_type: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        priority: 'Information'
        protocol: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        recv_bytes: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        recv_pkts: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        sent_bytes: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        sent_pkts: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        sophos_fw_status_msg: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        src_country_code: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        src_ip: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        src_mac: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        src_port: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        srczone: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        srczonetype: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        th: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        time: '12:00:10'
        timezone: '-02'
        tran_dst_ip: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        tran_src_ip: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        tran_src_port: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        user_group: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        user_name: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'
        vconnid: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'

**Phase 3: Completed filtering (rules).
        id: '70020'
        level: '0'
        description: 'Sophos XG210 Firewall event'
        groups: '['sophos-fw']'
        firedtimes: '1'
        mail: 'False'
```

### Expected results
```
echo 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0' | /var/ossec/bin/wazuh-logtest
Starting wazuh-logtest v4.2.0
Type one log per line


**Phase 1: Completed pre-decoding.
        full event: 'device="SFW" date=2021-06-05 time=12:00:10 timezone="-02" device_name="XG86" device_id=C0A0B0D0E0F0G66 log_id=123456789101 log_type="Wireless Protection" log_component="Wireless Protection" log_subtype="Information" priority=Information ap=P12345CV678VQDD ssid="WiFi_WPA_Enterprise clients_conn_SSID=0'

**Phase 2: Completed decoding.
        name: 'sophos-fw'
        device: SFW
        date: 2021-06-05 
        time: 12:00:10 
        timezone: -02
        device_name: XG86
        device_id: C0A0B0D0E0F0G66 
        log_id: 123456789101 
        log_type: Wireless Protection
        log_component: Wireless Protection
        log_subtype: Information
        priority: Information 
        ap: P12345CV678VQDD 
        ssid: WiFi_WPA_Enterprise clients_conn_SSID=0


**Phase 3: Completed filtering (rules).
        id: '70020'
        level: '0'
        description: 'Sophos XG210 Firewall event'
        groups: '['sophos-fw']'
        firedtimes: '1'
        mail: 'False'
```

## Tests

- [ ] Added .ini test file for covering related rules
- [ ] Executed unit tests (runtests.py) for checking ruleset integrity
- [ ] Verified mitre.db integrity
- [ ] Verified compliance mapping 
- [ ] Verified no errors/warnings related in ossec.log
- [ ] Kibana shows alerts

**Comment by jctello** [comment]
It's worth noting that the two log samples present in the decoders file present the same issue (although less dramatic):
```echo 'device="SFW" date=2019-10-09 time=17:19:06 timezone="+08" device_name="XG210" device_id=AAAAAAAA1234567 log_id=010101010101 log_type="Firewall" log_component="Firewall Rule" log_subtype="Denied" status="Deny" priority=Information duration=0 fw_rule_id=14 policy_type=1 user_name="" user_gp="" iap=2 ips_policy_id=0 appfilter_policy_id=0 application="" application_risk=0 application_technology="" application_category="" in_interface="Port3" out_interface="Port2" src_mac=11:22:aa:bb:22:11 src_ip=11.22.33.44 src_country_code= dst_ip=44.33.22.11 dst_country_code= protocol="TCP" src_port=52667 dst_port=10051 sent_pkts=0  recv_pkts=0 sent_bytes=0 recv_bytes=0 tran_src_ip= tran_src_port=0 tran_dst_ip= tran_dst_port=0 srczonetype="" srczone="" dstzonetype="" dstzone="" dir_disp="" connid="" vconnid="" hb_health="No Heartbeat" message="" appresolvedby="Signature"th="No Heartbeat' | /var/ossec/bin/wazuh-logtest
Starting wazuh-logtest v4.2.0
Type one log per line


**Phase 1: Completed pre-decoding.
        full event: 'device="SFW" date=2019-10-09 time=17:19:06 timezone="+08" device_name="XG210" device_id=AAAAAAAA1234567 log_id=010101010101 log_type="Firewall" log_component="Firewall Rule" log_subtype="Denied" status="Deny" priority=Information duration=0 fw_rule_id=14 policy_type=1 user_name="" user_gp="" iap=2 ips_policy_id=0 appfilter_policy_id=0 application="" application_risk=0 application_technology="" application_category="" in_interface="Port3" out_interface="Port2" src_mac=11:22:aa:bb:22:11 src_ip=11.22.33.44 src_country_code= dst_ip=44.33.22.11 dst_country_code= protocol="TCP" src_port=52667 dst_port=10051 sent_pkts=0  recv_pkts=0 sent_bytes=0 recv_bytes=0 tran_src_ip= tran_src_port=0 tran_dst_ip= tran_dst_port=0 srczonetype="" srczone="" dstzonetype="" dstzone="" dir_disp="" connid="" vconnid="" hb_health="No Heartbeat" message="" appresolvedby="Signature"th="No Heartbeat'

**Phase 2: Completed decoding.
        name: 'sophos-fw'
        appfilter_policy_id: '0'
        application_risk: '0'
        appresolvedby: 'Signature'
        connevent: 'device="SFW" date=2019-10-09 time=17:19:06 timezone="+08" device_name="XG210" device_id=AAAAAAAA1234567 log_id=010101010101 log_type="Firewall" log_component="Firewall Rule" log_subtype="Denied" status="Deny" priority=Information duration=0 fw_rule_id=14 policy_type=1 user_name="" user_gp="" iap=2 ips_policy_id=0 appfilter_policy_id=0 application="" application_risk=0 application_technology="" application_category="" in_interface="Port3" out_interface="Port2" src_mac=11:22:aa:bb:22:11 src_ip=11.22.33.44 src_country_code= dst_ip=44.33.22.11 dst_country_code= protocol="TCP" src_port=52667 dst_port=10051 sent_pkts=0  recv_pkts=0 sent_bytes=0 recv_bytes=0 tran_src_ip= tran_src_port=0 tran_dst_ip= tran_dst_port=0 srczonetype="" srczone="" dstzonetype="" dstzone="" dir_disp="" connid="" vconnid="" hb_health="No Heartbeat" message="" appresolvedby="Signature"th="No Heartbeat'
        date: '2019-10-09'
        device: 'SFW'
        device_id: 'AAAAAAAA1234567'
        device_name: 'XG210'
        dst_ip: '44.33.22.11'
        dst_port: '10051'
        duration: '0'
        fw_rule_id: '14'
        hb_health: 'No Heartbeat'
        iap: '2'
        in_interface: 'Port3'
        ips_policy_id: '0'
        log_component: 'Firewall Rule'
        log_id: 'device="SFW" date=2019-10-09 time=17:19:06 timezone="+08" device_name="XG210" device_id=AAAAAAAA1234567 log_id=010101010101 log_type="Firewall" log_component="Firewall Rule" log_subtype="Denied" status="Deny" priority=Information duration=0 fw_rule_id=14 policy_type=1 user_name="" user_gp="" iap=2 ips_policy_id=0 appfilter_policy_id=0 application="" application_risk=0 application_technology="" application_category="" in_interface="Port3" out_interface="Port2" src_mac=11:22:aa:bb:22:11 src_ip=11.22.33.44 src_country_code= dst_ip=44.33.22.11 dst_country_code= protocol="TCP" src_port=52667 dst_port=10051 sent_pkts=0  recv_pkts=0 sent_bytes=0 recv_bytes=0 tran_src_ip= tran_src_port=0 tran_dst_ip= tran_dst_port=0 srczonetype="" srczone="" dstzonetype="" dstzone="" dir_disp="" connid="" vconnid="" hb_health="No Heartbeat" message="" appresolvedby="Signature"th="No Heartbeat'
        log_subtype: 'Denied'
        log_type: 'Firewall'
        out_interface: 'Port2'
        policy_type: '1'
        priority: 'Information'
        protocol: 'TCP'
        recv_bytes: '0'
        recv_pkts: '0'
        sent_bytes: '0'
        sent_pkts: '0'
        sophos_fw_status_msg: 'Deny'
        src_ip: '11.22.33.44'
        src_mac: '11:22:aa:bb:22:11'
        src_port: '52667'
        th: 'No Heartbeat'
        time: '17:19:06'
        timezone: '+08'
        tran_src_port: '0'

**Phase 3: Completed filtering (rules).
        id: '70021'
        level: '5'
        description: 'Traffic Denied: from 11.22.33.44 to 44.33.22.11'
        groups: '['sophos-fw']'
        firedtimes: '1'
        mail: 'False'
**Alert to be generated.
```

```
echo 'device="SFW" date=2019-10-09 time=17:19:06 timezone="+08" device_name="XG210" device_id=AAAAAAAA1234567 log_id=010101010101 log_type="Firewall" log_component="Firewall Rule" log_subtype="Allowed" status="Allow" priority=Information duration=0 fw_rule_id=22 policy_type=1 user_name="" user_gp="" iap=0 ips_policy_id=9 appfilter_policy_id=0 application="DNS" application_risk=1 application_technology="Network Protocol" application_category="Infrastructure" in_interface="Port3" out_interface="Port2" src_mac=11:22:aa:bb:22:11 src_ip=11.22.33.44 src_country_code=R1 dst_ip=8.8.8.8 dst_country_code=USA protocol="UDP" src_port=60778 dst_port=53 sent_pkts=0  recv_pkts=0 sent_bytes=0 recv_bytes=0 tran_src_ip=11.22.33.44 tran_src_port=0 tran_dst_ip= tran_dst_port=0 srczonetype="DMZ" srczone="DMZ" dstzonetype="WAN" dstzone="WAN" dir_disp="" connevent="Start" connid="17709984" vconnid="" hb_health="No Heartbeat" message="" appresolvedby="Signature"' | /var/ossec/bin/wazuh-logtest
Starting wazuh-logtest v4.2.0
Type one log per line


**Phase 1: Completed pre-decoding.
        full event: 'device="SFW" date=2019-10-09 time=17:19:06 timezone="+08" device_name="XG210" device_id=AAAAAAAA1234567 log_id=010101010101 log_type="Firewall" log_component="Firewall Rule" log_subtype="Allowed" status="Allow" priority=Information duration=0 fw_rule_id=22 policy_type=1 user_name="" user_gp="" iap=0 ips_policy_id=9 appfilter_policy_id=0 application="DNS" application_risk=1 application_technology="Network Protocol" application_category="Infrastructure" in_interface="Port3" out_interface="Port2" src_mac=11:22:aa:bb:22:11 src_ip=11.22.33.44 src_country_code=R1 dst_ip=8.8.8.8 dst_country_code=USA protocol="UDP" src_port=60778 dst_port=53 sent_pkts=0  recv_pkts=0 sent_bytes=0 recv_bytes=0 tran_src_ip=11.22.33.44 tran_src_port=0 tran_dst_ip= tran_dst_port=0 srczonetype="DMZ" srczone="DMZ" dstzonetype="WAN" dstzone="WAN" dir_disp="" connevent="Start" connid="17709984" vconnid="" hb_health="No Heartbeat" message="" appresolvedby="Signature"'

**Phase 2: Completed decoding.
        name: 'sophos-fw'
        appfilter_policy_id: '0'
        application: 'DNS'
        application_category: 'Infrastructure'
        application_risk: '1'
        application_technology: 'device="SFW" date=2019-10-09 time=17:19:06 timezone="+08" device_name="XG210" device_id=AAAAAAAA1234567 log_id=010101010101 log_type="Firewall" log_component="Firewall Rule" log_subtype="Allowed" status="Allow" priority=Information duration=0 fw_rule_id=22 policy_type=1 user_name="" user_gp="" iap=0 ips_policy_id=9 appfilter_policy_id=0 application="DNS" application_risk=1 application_technology="Network Protocol" application_category="Infrastructure" in_interface="Port3" out_interface="Port2" src_mac=11:22:aa:bb:22:11 src_ip=11.22.33.44 src_country_code=R1 dst_ip=8.8.8.8 dst_country_code=USA protocol="UDP" src_port=60778 dst_port=53 sent_pkts=0  recv_pkts=0 sent_bytes=0 recv_bytes=0 tran_src_ip=11.22.33.44 tran_src_port=0 tran_dst_ip= tran_dst_port=0 srczonetype="DMZ" srczone="DMZ" dstzonetype="WAN" dstzone="WAN" dir_disp="" connevent="Start" connid="17709984" vconnid="" hb_health="No Heartbeat" message="" appresolvedby="Signature"'
        appresolvedby: 'Signature'
        connevent: 'Start'
        connid: '17709984'
        date: '2019-10-09'
        device: 'SFW'
        device_id: 'AAAAAAAA1234567'
        device_name: 'XG210'
        dst_country_code: 'USA'
        dst_ip: '8.8.8.8'
        dst_port: '53'
        dstzone: 'WAN'
        dstzonetype: 'WAN'
        duration: '0'
        fw_rule_id: '22'
        hb_health: 'No Heartbeat'
        iap: '0'
        in_interface: 'Port3'
        ips_policy_id: '9'
        log_component: 'Firewall Rule'
        log_id: 'device="SFW" date=2019-10-09 time=17:19:06 timezone="+08" device_name="XG210" device_id=AAAAAAAA1234567 log_id=010101010101 log_type="Firewall" log_component="Firewall Rule" log_subtype="Allowed" status="Allow" priority=Information duration=0 fw_rule_id=22 policy_type=1 user_name="" user_gp="" iap=0 ips_policy_id=9 appfilter_policy_id=0 application="DNS" application_risk=1 application_technology="Network Protocol" application_category="Infrastructure" in_interface="Port3" out_interface="Port2" src_mac=11:22:aa:bb:22:11 src_ip=11.22.33.44 src_country_code=R1 dst_ip=8.8.8.8 dst_country_code=USA protocol="UDP" src_port=60778 dst_port=53 sent_pkts=0  recv_pkts=0 sent_bytes=0 recv_bytes=0 tran_src_ip=11.22.33.44 tran_src_port=0 tran_dst_ip= tran_dst_port=0 srczonetype="DMZ" srczone="DMZ" dstzonetype="WAN" dstzone="WAN" dir_disp="" connevent="Start" connid="17709984" vconnid="" hb_health="No Heartbeat" message="" appresolvedby="Signature"'
        log_subtype: 'Allowed'
        log_type: 'Firewall'
        out_interface: 'Port2'
        policy_type: '1'
        priority: 'Information'
        protocol: 'UDP'
        recv_bytes: '0'
        recv_pkts: '0'
        sent_bytes: '0'
        sent_pkts: '0'
        sophos_fw_status_msg: 'Allow'
        src_country_code: 'R1'
        src_ip: '11.22.33.44'
        src_mac: '11:22:aa:bb:22:11'
        src_port: '60778'
        srczone: 'DMZ'
        srczonetype: 'DMZ'
        th: 'No Heartbeat'
        time: '17:19:06'
        timezone: '+08'
        tran_src_ip: '11.22.33.44'
        tran_src_port: '0'

**Phase 3: Completed filtering (rules).
        id: '70022'
        level: '3'
        description: 'Traffic Allowed: from 11.22.33.44 to 8.8.8.8'
        groups: '['sophos-fw']'
        firedtimes: '1'
        mail: 'False'
**Alert to be generated.
```

**Comment by jctello** [comment]
Just noticed that this issue is present in three files:
```
# grep -lF '|(\.*)$' /var/ossec/ruleset/decoders/*
/var/ossec/ruleset/decoders/0051-checkpoint-smart1_decoders.xml
/var/ossec/ruleset/decoders/0470-panda-paps_decoders.xml
/var/ossec/ruleset/decoders/0510-sophos_fw_decoders.xml
```
