### ISSUE TITLE
Add support for VPC Flow logs in our GCP module

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#8713]
|Wazuh version|Component|
|---|---|
| 4.3 | GCP Module |

Hello team,

As stated in #8244 we want to add support for additional GCP services for our GCP integration. In this case, we want to add support for [VPC Flow logs](https://cloud.google.com/vpc/docs/flow-logs). 

## Design
Research on this new service was carried out in #8690. We concluded that VPC Flow service can be easily integrated into the current version of our GCP module as this service is able to use `pub/sub` we currently support. The end user must configure VPC Flow to send the logs to a topic and our module will fetch these logs by using a subscription.

Once VPC Flow logging is enabled its logs can be found in the `Cloud Logging` section.

## Billing

To test the new integration we need to generate some VPC Flow logs which requires enabling billing for the project. Standard pricing for Logging, BigQuery, or Pub/Sub apply in this case. The details are [here](https://cloud.google.com/vpc/docs/flow-logs#pricing) and [here](https://cloud.google.com/vpc/network-pricing#network-telemetry).
 
## Tasks

- [x] Enable VPC Flow in a test project to generate some logs.
- [x] Update the Core parser to be able to read the parameters for the new GCP services.
- [x] Configure VPC to send the logs to pub/sub and check our module is able to access it.
- [x] Create a documentation page for the new service explaining how to use it.

**Comment by CarlosRS9** [comment]
## Status update

This development started once billing was successfully enabled.

We have created a VM instance associated to a VPC network and we have managed to generate VPC flow logs that will be used to test this integration. We still need to finish configuring the export of VPC flow logs to pubsub, as we have experienced a permissions issue. Our team is working on it. Once this problem is solved we will be able to start with the Core and Wodle code.

**Comment by CarlosRS9** [comment]
## Status Update

VPC Flow is fully compatible with the current version of our GCP module as long as the user configure Cloud Logging to export VPC Flow logs to Pub/sub using a sink.

No changes to core or wodle code were necessary. The documentation has been updated to explain to the users how to set up VPC flow and the  required exporter. No further changes are required except for the creation of the new rules for this service.

**Comment by CarlosRS9** [comment]
Here is an example of a VPC Flow log extracted from GCP by our gcloud integration:
```
{
    "integration": "gcp",
    "gcp": {
        "insertId": "g3n55zfjeyg2i",
        "jsonPayload": {
            "bytes_sent": "8",
            "connection": {
                "dest_ip": "ff02::2",
                "protocol": 58,
                "src_ip": "XXXXXXXXXXXXXX"
            },
            "dest_location": {},
            "end_time": "2021-06-04T11:18:46.770486824Z",
            "packets_sent": "1",
            "reporter": "SRC",
            "src_instance": {
                "project_id": "wazuh-dev-XXXXXX",
                "region": "us-east1",
                "vm_name": "framework-vpc-flow-test-instance",
                "zone": "us-east1-b"
            },
            "src_vpc": {
                "project_id": "wazuh-dev-XXXXXX",
                "subnetwork_name": "default",
                "vpc_name": "default"
            },
            "start_time": "2021-06-04T11:18:46.770486824Z"
        },
        "logName": "projects/wazuh-dev-XXXXXX/logs/compute.googleapis.com%2Fvpc_flows",
        "receiveTimestamp": "2021-06-04T11:19:10.440812789Z",
        "resource": {
            "labels": {
                "location": "us-east1-b",
                "project_id": "wazuh-dev-XXXXXX",
                "subnetwork_id": "6133410668509430049",
                "subnetwork_name": "default"
            },
            "type": "gce_subnetwork"
        },
        "timestamp": "2021-06-04T11:19:10.440812789Z"
    }
}
```

The module can be manually executed using the following command:
```
/var/ossec/wodles/gcloud/gcloud -p wazuh-dev-XXXXXX -s framework-vpc-flow-topic-sub -c /var/ossec/wodles/gcloud/credentials.json
```

**Comment by JavierBejMen** [comment]
# Update
Added generic rule to group VPC flow events:
```json
<rule id="65050" level="2">
        <if_sid>65000</if_sid>
        <field name="gcp.jsonPayload.reporter" type="pcre2">^(?!^$).*</field>
        <description>GCP VPC Flow rules grouped</description>
        <options>no_full_log</options>
    </rule>
```
Merged changes to primary branch: https://github.com/wazuh/wazuh/tree/8244_gcp_vpc_ruleset
