### ISSUE TITLE
Add support for Firewall logs in our GCP module

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#8714]
|Wazuh version|Component|
|---|---|
| 4.3 | GCP Module |

Hello team,

As stated in #8244 we want to add support for additional GCP services for our GCP integration. In this case, we want to add support for [Firewall](https://cloud.google.com/vpc/docs/firewall-rules-logging) logs. 

## Design

Research on this new service was carried out in #8690. We concluded that Firewall service can be easily integrated into the current version of our GCP module as this service is able to use `pub/sub` we currently support. The end user must configure Firewall to send the logs to a topic and our module will fetch these logs by using a subscription.

How to enable Firewall logs is explained [here](https://cloud.google.com/vpc/docs/using-firewall-rules-logging#console). Once Firewall logging is enabled its logs can be found in the `Cloud Logging` section.

## Billing

To test the new integration we need to generate some Firewall logs which requires enabling `Compute Engine API` and thus the project owner must enable billing for the project.

## Tasks

- [x] Enable Firewall in a test project to generate some logs.
- [x] Update the Core parser to be able to read the parameters for the new GCP services.
- [x] Configure Firewall to send the logs to pub/sub and check our module is able to access it.
- [x] Create a documentation page for the new service explaining how to use it.

**Comment by CarlosRS9** [comment]
## Status Update

Firewall Route Logging is fully compatible with the current version of our GCP module as long as the user configure Cloud Logging to export the logs to Pub/sub using a sink.

No changes to core or wodle code were necessary. The documentation has been updated to explain to the users how to set up Firewall Route Logging and the required exporter. No further changes are required except for the creation of the new rules for this service.

This service was successfully tested after generating some Firewall Route Logging logs and running the following command:
```
/var/ossec/wodles/gcloud/gcloud -p wazuh-dev-258815 -s framework-firewall-sub -c /var/ossec/wodles/gcloud/credentials.json
```


Here is a example Firewall Route Logging log obtained using our gcloud integration:
```
{
    "integration": "gcp",
    "gcp": {
        "insertId": "6dxcl6g15v9cee",
        "jsonPayload": {
            "connection": {
                "dest_ip": "10.142.0.2",
                "dest_port": 22,
                "protocol": 6,
                "src_ip": "XX.XX.XX.XX",
                "src_port": 43710
            },
            "disposition": "ALLOWED",
            "instance": {
                "project_id": "wazuh-dev-XXXXXX",
                "region": "us-east1",
                "vm_name": "framework-vpc-flow-test-instance",
                "zone": "us-east1-b"
            },
            "rule_details": {
                "action": "ALLOW",
                "direction": "INGRESS",
                "ip_port_info": [{
                    "ip_protocol": "TCP",
                    "port_range": ["22"]
                }],
                "priority": 65534,
                "reference": "network:default/firewall:default-allow-ssh",
                "source_range": ["0.0.0.0/0"]
            },
            "vpc": {
                "project_id": "wazuh-dev-XXXXXX",
                "subnetwork_name": "default",
                "vpc_name": "default"
            }
        },
        "logName": "projects/wazuh-dev-XXXXXX/logs/compute.googleapis.com%2Ffirewall",
        "receiveTimestamp": "2021-06-04T13:27:43.45097863Z",
        "resource": {
            "labels": {
                "location": "us-east1-b",
                "project_id": "wazuh-dev-XXXXXX",
                "subnetwork_id": "6133410668509430049",
                "subnetwork_name": "default"
            },
            "type": "gce_subnetwork"
        },
        "timestamp": "2021-06-04T13:27:35.794717819Z"
    }
}
```
