### ISSUE TITLE
Add support for Load Balancing Logging in our GCP module

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#8715]
|Wazuh version|Component|
|---|---|
| 4.3 | GCP Module |

Hello team,

As stated in #8244 we want to add support for additional GCP services for our GCP integration. In this case, we want to add support for [Load Balancing Logging](https://cloud.google.com/load-balancing/docs/https/https-logging-monitoring). 

## Design

Research on this new service was carried out in #8690. We concluded that Load Balancing Logging service  can be easily integrated into the current version of our GCP module as this service is able to use `pub/sub` we currently support. The end user must create a sink to send the logs to a `pubsub` topic and our module will fetch these logs by using a subscription.

How to enable Load Balancing Logging is explained [here](https://cloud.google.com/load-balancing/docs/https/https-logging-monitoring#enabling_logging_on_a_new_backend_service). Once Load Balancing Logging is enabled its logs can be found in the `Logs Explorer`.

## Billing

To test the new integration we need to generate some Load Balancing logs which requires enabling `Compute Engine API` and thus the project owner must enable billing for the project.

## Tasks

- [x] Enable Load Balancing Logging in a test project to generate some logs.
- [x] Update the Core parser to be able to read the parameters for the new GCP services.
- [x] Create a sink to send the Load Balancing logs to pub/sub and check our module is able to access it.
- [x] Create a documentation page for the new service explaining how to use it.

**Comment by CarlosRS9** [comment]
## Status Update

HTTP(S) Load Balancing Logging is fully compatible with the current version of our GCP module as long as the user configure Cloud Logging to export the logs to Pub/sub using a sink.

No changes to core or wodle code were necessary. The documentation has been updated to explain to the users how to set up HTTP(S) Load Balancing Logging and the required exporter. No further changes are required except for the creation of the new rules for this service.

This service was successfully tested after generating some HTTP(S) Load Balancing Logging logs and running the following command:
```
/var/ossec/wodles/gcloud/gcloud -p wazuh-dev-xxxxxx -s framework-load-balancer-sub -c /var/ossec/wodles/gcloud/credentials.json
```


Here is a example HTTP(S) Load Balancing Logging log obtained using our gcloud integration:
```
{
    "integration": "gcp",
    "gcp": {
        "httpRequest": {
            "latency": "0.000864s",
            "remoteIp": "YY.YY.YY.YY",
            "requestMethod": "GET",
            "requestSize": "385",
            "requestUrl": "http://XX.XX.XX.XX/favicon.ico",
            "responseSize": "488",
            "status": 502,
            "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
        },
        "insertId": "1mtxf1hf2c4idk",
        "jsonPayload": {
            "@type": "type.googleapis.com/google.cloud.loadbalancing.type.LoadBalancerLogEntry",
            "statusDetails": "failed_to_pick_backend"
        },
        "logName": "projects/wazuh-dev-xxxxxx/logs/requests",
        "receiveTimestamp": "2021-06-09T15:17:25.473538144Z",
        "resource": {
            "labels": {
                "backend_service_name": "framework-load-balancer-backend-test",
                "forwarding_rule_name": "framework-load-balancer-backend-test",
                "project_id": "wazuh-dev-xxxxxx",
                "target_proxy_name": "framework-load-balancer-test-target-proxy",
                "url_map_name": "framework-load-balancer-test",
                "zone": "global"
            },
            "type": "http_load_balancer"
        },
        "severity": "WARNING",
        "spanId": "ab6c36e7fc60f24e",
        "timestamp": "2021-06-09T15:17:24.408864Z",
        "trace": "projects/wazuh-dev-xxxxxx/traces/68183a7cda548ce0e79207099a1fea58"
    }
}
```
