### ISSUE TITLE
Add support for GCS access logs in our GCP module

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#8716]
|Wazuh version|Component|
|---|---|
| 4.3 | GCP Module |

Hello team,

As stated in #8244 we want to add support for additional GCP services for our GCP integration. In this case, we want to add support for [GCS access logs](https://cloud.google.com/storage/docs/access-logs). 

## Design

Research on this new service was carried out in #8690. We concluded that GCS Access logs service requires some modifications to our GCP module as this service is **not** able to use `pub/sub`. It store its logs in a bucket instead. It is not possible to move data from a bucket to a pubsub subscription. Because of that, to add support for this service we need to add to our GCP module the ability to read data from GCP buckets in a similar way to our current AWS module. To achieve this we can use the [official GCS api](https://cloud.google.com/appengine/docs/standard/python/googlecloudstorageclient/read-write-to-cloud-storage).

GCS Access logs must be enabled using the `gsutil`, the `XML API` or the `JSON API` availables in Cloud Storage. The details are [here](https://cloud.google.com/storage/docs/access-logs#json-api).

## Billing

To test the new integration we need to generate some GCS Access logs which requires `Cloud Storage` and thus the project owner must enable billing for the project.

## Tasks

- [x] Expand the GCP module to be able to read data from GCS buckets.
- [x] Update the Core parser to be able to read the parameters for the new GCP services.
- [x] Enable GCS Access logs in a test project to generate some logs.
- [x] Test the new integration fetching data from a real GCP bucket.
- [x] Create a documentation page for the new service explaining how to use it.

**Comment by CarlosRS9** [comment]
## Status update


We created a GCS bucket and applied the necessary configurations to be able to generate GCS access logs for testing. We can confirm it is possible to export the logs contained in this bucket to Pub/Sub using a DataFlow Job. However, this solution is not feasible due to the CSV format of Access Logs. This format consists of a first line with the header and a second line with the values. Exporting the data via DataFlow and then ingesting these logs from Pub/Sub would result in 2 different events: the first one with the header and the second one with the values only. Therefore, it is still necessary to implement the logic to be able to consume the logs directly from the Bucket, processing them as CSV in a similar way to how the AWS module currently works, so that we can correctly generate a well-formed event.

This would be an example of an Access Logs log as found in the bucket:


```
"time_micros","c_ip","c_ip_type","c_ip_region","cs_method","cs_uri","sc_status","cs_bytes","sc_bytes","time_taken_micros","cs_host","cs_referer","cs_user_agent","s_request_id","cs_operation","cs_bucket","cs_object"
"1623412011750099","XX.XX.XX.XX","1","","PATCH","/storage/v1/b/framework-test-bucket?alt=json&fields=id&projection=noAcl","200","84","36","692000","storage.googleapis.com","","apitools Python/3.7.3 gsutil/4.62 (linux) analytics/disabled interactive/True command/logging google-cloud-sdk/344.0.0,gzip(gfe)","ABg5-UyjUSYKcUyQgJHkwV8T8q8mBGWVfTQ0AEx_GLBTmTtBmtBUdFKMf1wJ8xxkUKwuLjbPgcwbh8zN6p6BDDv8-XZFGyqzxg","","framework-test-bucket",""
```

**Comment by CarlosRS9** [comment]
## Status update

We ere working on the necessary changes to adapt our GCP module and make it compatible with GCS buckets. Several changes to the current structure of the module were required to make it compatible with GCS buckets in a flexible way, allowing us to add support for new bucket types in the future while maintaining compatibility with pubsub.


The GCS bucket implementation is currently working and is able to process the access logs of a bucket without issues. However, we still need to implement the logic related to certain tags, such as the `only_logs_after`. The changes in the core part of the module are also pending.


For GCP bucket we will make use of a new tag in the ossec.conf configuration: `gcp-bucket`


Here is the proposal for the gcp bucket configuration options:

```
 <gcp-bucket>
    <run_on_start>no</run_on_start>
    <interval>1m</interval>
    <project_id>wazuh-dev</project_id>
    <logging>debug</logging>
    <remove_from_bucket> no </remove_from_bucket>

    <bucket type="access_logs">
        <name>framework-test-bucket</name>
        <credentials_file>wodles/gcp/credentials.json</credentials_file>
        <only_logs_after>2021-JUN-01</only_logs_after>
        <path>access_logs/</path>
    </bucket>
</gcp-bucket>
```

**Comment by CarlosRS9** [comment]
## Status Update

The necessary changes in the GCP module have been applied. The new parameters listed in the previous update are working correctly. The module can now be run manually without any issues. We are currently working on updating the core parser logic in order to be able to correctly read the new ossec.conf configuration proposed above.

**Comment by CarlosRS9** [comment]
## Status Update

The parser have been updated to be able to read and process the configuration for `gcp-bucket`. The module is working as expected.

Core and wodle unit tests needs to be updated with the new changes. We are currently working on this.

**Comment by noise-kngdm** [comment]
## Issue update
After the refactor made to the GCP integration module in [this PR](https://github.com/wazuh/wazuh/pull/9927) to increase the number of EPS it can handle, it is necessary to refactor part of the code developed for this issue to solve the conflicts with the master branch. We're currently working on that.

**Comment by noise-kngdm** [comment]
## Issue update
We've finished with rebasing `dev-8244-gcp` branch to master and solving all conflicts. We're currently testing that the changes made to the code are working as expected.
### Tests performed
#### Pubsub module
So far we've tested that the pubsub module is working both executing it in the command line and configuring it using the `ossec.conf` file.
##### Command line
To test it we've executed the module multiple times to check if all parameters are working fine.
```
root@bc81c4381b16:/var/ossec# /var/ossec/wodles/gcloud/gcloud -p wazuh-project -s test_subscription -c /var/ossec/wodles/gcloud/credentials.json -l 2 -T pubsub   
gcloud_wodle: INFO: Received and acknowledged 100 messages
```  

```
root@bc81c4381b16:/var/ossec/wodles/gcloud# /var/ossec/wodles/gcloud/gcloud -p wazuh-project -s test_subscription -c /var/ossec/wodles/gcloud/credentials.json -l 2 -T pubsub  -t 10
gcloud_wodle: INFO: Received and acknowledged 100 messages
```  
 
```
root@bc81c4381b16:/var/ossec# /var/ossec/wodles/gcloud/gcloud -p wazuh-project -s test_subscription -c /var/ossec/wodles/gcloud/credentials.json -l 2 -T pubsub -m 150
gcloud_wodle: INFO: Received and acknowledged 150 messages
```  

```
root@bc81c4381b16:/var/ossec# /var/ossec/wodles/gcloud/gcloud -p wazuh-project -s test_subscription -c /var/ossec/wodles/gcloud/credentials.json -l 2 -T pubsub -m 250 -t 12
gcloud_wodle: INFO: Received and acknowledged 250 messages
```  

##### ossec.conf file
To check that all the affected parameters were adequately parsed, we added the following code snippet to the `ossec.conf` file.
```
<gcp-pubsub>
    <pull_on_start>yes</pull_on_start>
    <interval>1d</interval>
    <project_id>wazuh-project</project_id>
    <subscription_name>test_subscription</subscription_name>
    <num_threads>4</num_threads>
    <logging>debug</logging>
    <max_messages>500</max_messages>
    <credentials_file>/var/ossec/wodles/gcloud/credentials.json</credentials_file>
</gcp-pubsub>
```  
Then, to check that the parameters are being passed to the module, we temporarily added the subsequent code to it to write them into a file.
```
with open('/tmp/pubsub_test.txt,'w') as f:
    f.write(f'messages: {max_messages}\nn_threads: {n_threads}\nproject: {project}\nsubscription id: {subscription_id}\n')
```  
After restarting the wazuh manager, we checked the test file and got the expected output.
```
root@bc81c4381b16:/# cat /tmp/pubsub_test.txt
messages: 500
n_threads: 4
project: wazuh-project
subscription id: test_subscription
```  

#### Access logs
To test the module, we uploaded the following file to a bucket:
```
WAZUH TEST LOG FILE
Test log 0 - 1632781210655
Test log 1 - 1632781270655
Test log 2 - 1632781330655
Test log 3 - 1632781390655
Test log 4 - 1632781450655
Test log 5 - 1632781510655
Test log 6 - 1632781570655
Test log 7 - 1632781630655
Test log 8 - 1632781690655
Test log 9 - 1632781750655
```
##### Command line
After executing the module in debug mode, we got the following output:
```
root@bc81c4381b16:/var/ossec/wodles/gcloud# ./gcloud  -T access_logs -c ./credentials.json  -b  test-bucket -l 1
gcloud_wodle: INFO: The creation time of Copy of testfile is older than 2021-10-01 00:00:00+00:00. Skipping it...
gcloud_wodle: INFO: Processing test_file.txt
gcloud_wodle: DEBUG: Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"WAZUH TEST LOG FILE": "Test log 0 - 1632781210655", "source": "gcp_bucket"}}'"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"WAZUH TEST LOG FILE": "Test log 1 - 1632781270655", "source": "gcp_bucket"}}'"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"WAZUH TEST LOG FILE": "Test log 2 - 1632781330655", "source": "gcp_bucket"}}'"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"WAZUH TEST LOG FILE": "Test log 3 - 1632781390655", "source": "gcp_bucket"}}'"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"WAZUH TEST LOG FILE": "Test log 4 - 1632781450655", "source": "gcp_bucket"}}'"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"WAZUH TEST LOG FILE": "Test log 5 - 1632781510655", "source": "gcp_bucket"}}'"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"WAZUH TEST LOG FILE": "Test log 6 - 1632781570655", "source": "gcp_bucket"}}'"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"WAZUH TEST LOG FILE": "Test log 7 - 1632781630655", "source": "gcp_bucket"}}'"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"WAZUH TEST LOG FILE": "Test log 8 - 1632781690655", "source": "gcp_bucket"}}'"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"WAZUH TEST LOG FILE": "Test log 9 - 1632781750655", "source": "gcp_bucket"}}'"
gcloud_wodle: INFO: Updating previously processed files.
gcloud_wodle: INFO: Received and acknowledged 1 messages
```
From that output, it looks like the module is not considering the total amount of lines sent to analysisd to compute the number of messages, but the number of files examined. If we upload a file similar to the first one, we get this output:
```
root@bc81c4381b16:/var/ossec/wodles/gcloud# ./gcloud  -T access_logs -c ./credentials.json  -b  framework-test-bucket -l 1
gcloud_wodle: INFO: Processing test_file.txt
gcloud_wodle: DEBUG: Sending msg to analysisd: "b1:Wazuh-GCloud:{integration: gcp, gcp: {WAZUH TEST LOG FILE: Test log 0 - 1632781210655, source: gcp_bucket}}"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b1:Wazuh-GCloud:{integration: gcp, gcp: {WAZUH TEST LOG FILE: Test log 1 - 1632781270655, source: gcp_bucket}}"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b1:Wazuh-GCloud:{integration: gcp, gcp: {WAZUH TEST LOG FILE: Test log 2 - 1632781330655, source: gcp_bucket}}"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b1:Wazuh-GCloud:{integration: gcp, gcp: {WAZUH TEST LOG FILE: Test log 3 - 1632781390655, source: gcp_bucket}}"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b1:Wazuh-GCloud:{integration: gcp, gcp: {WAZUH TEST LOG FILE: Test log 4 - 1632781450655, source: gcp_bucket}}"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b1:Wazuh-GCloud:{integration: gcp, gcp: {WAZUH TEST LOG FILE: Test log 5 - 1632781510655, source: gcp_bucket}}"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b1:Wazuh-GCloud:{integration: gcp, gcp: {WAZUH TEST LOG FILE: Test log 6 - 1632781570655, source: gcp_bucket}}"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b1:Wazuh-GCloud:{integration: gcp, gcp: {WAZUH TEST LOG FILE: Test log 7 - 1632781630655, source: gcp_bucket}}"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b1:Wazuh-GCloud:{integration: gcp, gcp: {WAZUH TEST LOG FILE: Test log 8 - 1632781690655, source: gcp_bucket}}"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b1:Wazuh-GCloud:{integration: gcp, gcp: {WAZUH TEST LOG FILE: Test log 9 - 1632781750655, source: gcp_bucket}}"
gcloud_wodle: INFO: Processing test_file_2.txt
gcloud_wodle: DEBUG: Sending msg to analysisd: "b1:Wazuh-GCloud:{integration: gcp, gcp: {WAZUH TEST LOG FILE 2: Test log 0 - 1632781210655, source: gcp_bucket}}"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b1:Wazuh-GCloud:{integration: gcp, gcp: {WAZUH TEST LOG FILE 2: Test log 1 - 1632781270655, source: gcp_bucket}}"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b1:Wazuh-GCloud:{integration: gcp, gcp: {WAZUH TEST LOG FILE 2: Test log 2 - 1632781330655, source: gcp_bucket}}"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b1:Wazuh-GCloud:{integration: gcp, gcp: {WAZUH TEST LOG FILE 2: Test log 3 - 1632781390655, source: gcp_bucket}}"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b1:Wazuh-GCloud:{integration: gcp, gcp: {WAZUH TEST LOG FILE 2: Test log 4 - 1632781450655, source: gcp_bucket}}"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b1:Wazuh-GCloud:{integration: gcp, gcp: {WAZUH TEST LOG FILE 2: Test log 5 - 1632781510655, source: gcp_bucket}}"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b1:Wazuh-GCloud:{integration: gcp, gcp: {WAZUH TEST LOG FILE 2: Test log 6 - 1632781570655, source: gcp_bucket}}"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b1:Wazuh-GCloud:{integration: gcp, gcp: {WAZUH TEST LOG FILE 2: Test log 7 - 1632781630655, source: gcp_bucket}}"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b1:Wazuh-GCloud:{integration: gcp, gcp: {WAZUH TEST LOG FILE 2: Test log 8 - 1632781690655, source: gcp_bucket}}"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b1:Wazuh-GCloud:{integration: gcp, gcp: {WAZUH TEST LOG FILE 2: Test log 9 - 1632781750655, source: gcp_bucket}}"
gcloud_wodle: INFO: Updating previously processed files.
gcloud_wodle: INFO: Received and acknowledged 2 messages
```
That is a bug I think we should fix before continuing with the testing, and I will work on that until further notice.

**Comment by noise-kngdm** [comment]
## Issue update
We fixed the bug that made the `access_logs` module print a wrong number of processed messages after finishing its execution. Now executing the module will return the expected output:

```
root@be54301d06ba:/var/ossec/wodles/gcloud# /var/ossec/wodles/gcloud/gcloud -T access_logs -b test-bucket -c credentials.json -l 1 
gcloud_wodle: INFO: Processing test_file.txt
gcloud_wodle: DEBUG: Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GCloud test bucket logs": "Test log 0 - 1633042692324", "source": "gcp_bucket"}}'"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GCloud test bucket logs": "Test log 1 - 1633042752324", "source": "gcp_bucket"}}'"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GCloud test bucket logs": "Test log 2 - 1633042812324", "source": "gcp_bucket"}}'"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GCloud test bucket logs": "Test log 3 - 1633042872324", "source": "gcp_bucket"}}'"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GCloud test bucket logs": "Test log 4 - 1633042932324", "source": "gcp_bucket"}}'"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GCloud test bucket logs": "Test log 5 - 1633042992324", "source": "gcp_bucket"}}'"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GCloud test bucket logs": "Test log 6 - 1633043052324", "source": "gcp_bucket"}}'"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GCloud test bucket logs": "Test log 7 - 1633043112324", "source": "gcp_bucket"}}'"
gcloud_wodle: DEBUG: Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GCloud test bucket logs": "Test log 8 - 1633043172324", "source": "gcp_bucket"}}'"
gcloud_wodle: INFO: Updating previously processed files.
gcloud_wodle: INFO: Received 9 messages
```  

We also changed the message from `Received and acknowledge X messages` to `Received X messages` for the `acces_logs` module since it won't send any ACK to the google cloud, that's exclusive for the `Pub/Sub` module.  

### Tests performed
#### Manual tests
We checked that the `access_logs` module was working when configured via the `ossec.conf` file. In order to do that, we used the following configuration:
```
 <gcp-bucket>
    <run_on_start>yes</run_on_start>
    <interval>1m</interval>
    <logging>debug</logging>
    <bucket type="access_logs">
        <name>test-bucket</name>
        <credentials_file>/var/ossec/wodles/gcloud/credentials.json</credentials_file>
        <only_logs_after>2021-Sep-01</only_logs_after>
        <remove_from_bucket>no</remove_from_bucket>
    </bucket>
 </gcp-bucket>
```  
When we tried to check that this was working fine, we realized that the database wasn't been created in `{WAZUH_PATH}/wodles/gcloud/gcloud.db` but in `{WAZUH_PATH}/gcloud.db` when configuring it using the `ossec.conf` file. That's because `WazuhGCloudBucket` was using this as the database path:
https://github.com/wazuh/wazuh/blob/3e67db056e87eeb264d302c25f577b918bb21fa0/wodles/gcloud/buckets/bucket.py#L60  

And then, the module would use the following code to connect to the DB:
https://github.com/wazuh/wazuh/blob/3e67db056e87eeb264d302c25f577b918bb21fa0/wodles/gcloud/buckets/bucket.py#L127-L138  

When executing the module using the CLI, the module would take the working directory and would append the `gcloud.db` to connect to the DB; but since the working directory is the wazuh path when configuring a module using the `ossec.conf` file, doing so would mean that the database would get created in `{WAZUH_PATH}/gcloud.db`. We fixed that and then we checked again the use of the module both configuring it via the `ossec.conf` file and executing it manually.

When executing it via the `ossec.conf` file, after waiting for 1 minute we can check that the database has been created and it contains information regarding the test file:
```
root@1ceeee265657:/var/ossec/wodles/gcloud# sqlite3 gcloud.db 
SQLite version 3.31.1 2020-01-27 19:55:54
Enter ".help" for usage hints.
sqlite> select * from access_logs;
wazuh-dev-258815|test-bucket||test_file.txt|2021-10-04 09:59:25.336000+00:00
```  

#### C tests
After changing some aspects of the code, we made sure that the C unit tests written for this development kept working.
```
root@ubuntu20:/wazuh/src/unit_tests/build/wazuh_modules/gcp# valgrind --track-origins=yes --leak-check=full --keep-stacktraces=alloc-and-free --track-fds=yes --num-callers=20 --show-leak-kinds=definite,indirect --log-file=/UTValgrind.log --show-reachable=yes ./test_wmodules_gcp 
[==========] Running 23 test(s).
[ RUN      ] test_wm_gcp_pubsub_read_full_configuration
[       OK ] test_wm_gcp_pubsub_read_full_configuration
[ RUN      ] test_wm_gcp_pubsub_read_enabled_tag_invalid
[       OK ] test_wm_gcp_pubsub_read_enabled_tag_invalid
[ RUN      ] test_wm_gcp_pubsub_read_project_id_tag_invalid
[       OK ] test_wm_gcp_pubsub_read_project_id_tag_invalid
[ RUN      ] test_wm_gcp_pubsub_read_no_project_id_tag
[       OK ] test_wm_gcp_pubsub_read_no_project_id_tag
[ RUN      ] test_wm_gcp_pubsub_read_subscription_name_tag_invalid
[       OK ] test_wm_gcp_pubsub_read_subscription_name_tag_invalid
[ RUN      ] test_wm_gcp_pubsub_read_no_subscription_name_tag
[       OK ] test_wm_gcp_pubsub_read_no_subscription_name_tag
[ RUN      ] test_wm_gcp_pubsub_read_credentials_file_full_path
[       OK ] test_wm_gcp_pubsub_read_credentials_file_full_path
[ RUN      ] test_wm_gcp_pubsub_read_credentials_file_tag_empty
[       OK ] test_wm_gcp_pubsub_read_credentials_file_tag_empty
[ RUN      ] test_wm_gcp_pubsub_read_credentials_file_tag_too_long
[       OK ] test_wm_gcp_pubsub_read_credentials_file_tag_too_long
[ RUN      ] test_wm_gcp_pubsub_read_credentials_file_tag_realpath_error
[       OK ] test_wm_gcp_pubsub_read_credentials_file_tag_realpath_error
[ RUN      ] test_wm_gcp_pubsub_read_credentials_file_tag_file_not_found
[       OK ] test_wm_gcp_pubsub_read_credentials_file_tag_file_not_found
[ RUN      ] test_wm_gcp_pubsub_read_no_credentials_file_tag
[       OK ] test_wm_gcp_pubsub_read_no_credentials_file_tag
[ RUN      ] test_wm_gcp_pubsub_read_max_messages_tag_empty
[       OK ] test_wm_gcp_pubsub_read_max_messages_tag_empty
[ RUN      ] test_wm_gcp_pubsub_read_max_messages_tag_not_digit
[       OK ] test_wm_gcp_pubsub_read_max_messages_tag_not_digit
[ RUN      ] test_wm_gcp_pubsub_read_pull_on_start_tag_invalid
[       OK ] test_wm_gcp_pubsub_read_pull_on_start_tag_invalid
[ RUN      ] test_wm_gcp_pubsub_read_logging_tag_debug
[       OK ] test_wm_gcp_pubsub_read_logging_tag_debug
[ RUN      ] test_wm_gcp_pubsub_read_logging_tag_info
[       OK ] test_wm_gcp_pubsub_read_logging_tag_info
[ RUN      ] test_wm_gcp_pubsub_read_logging_tag_warning
[       OK ] test_wm_gcp_pubsub_read_logging_tag_warning
[ RUN      ] test_wm_gcp_pubsub_read_logging_tag_error
[       OK ] test_wm_gcp_pubsub_read_logging_tag_error
[ RUN      ] test_wm_gcp_pubsub_read_logging_tag_critical
[       OK ] test_wm_gcp_pubsub_read_logging_tag_critical
[ RUN      ] test_wm_gcp_pubsub_read_logging_tag_invalid
[       OK ] test_wm_gcp_pubsub_read_logging_tag_invalid
[ RUN      ] test_wm_gcp_pubsub_read_invalid_tag
[       OK ] test_wm_gcp_pubsub_read_invalid_tag
[ RUN      ] test_wm_gcp_pubsub_read_invalid_element
[       OK ] test_wm_gcp_pubsub_read_invalid_element
[==========] 23 test(s) run.
[  PASSED  ] 23 test(s).
```
```
root@ubuntu20:/# cat UTValgrind.log 
==40082== Memcheck, a memory error detector
==40082== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==40082== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==40082== Command: ./test_wmodules_gcp
==40082== Parent PID: 40045
==40082== 
==40082== 
==40082== FILE DESCRIPTORS: 4 open at exit.
==40082== Open file descriptor 3: /UTValgrind.log
==40082==    <inherited from parent>
==40082== 
==40082== Open file descriptor 2: /dev/pts/0
==40082==    <inherited from parent>
==40082== 
==40082== Open file descriptor 1: /dev/pts/0
==40082==    <inherited from parent>
==40082== 
==40082== Open file descriptor 0: /dev/pts/0
==40082==    <inherited from parent>
==40082== 
==40082== 
==40082== HEAP SUMMARY:
==40082==     in use at exit: 0 bytes in 0 blocks
==40082==   total heap usage: 3,186 allocs, 3,186 frees, 1,637,358 bytes allocated
==40082== 
==40082== All heap blocks were freed -- no leaks are possible
==40082== 
==40082== For lists of detected and suppressed errors, rerun with: -s
==40082== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

#### Python unit tests
We had to change some of the tests to make them suitable for the state of the module after the changes introduced in this development.
```
(wazuh-unit)   gcloud [dev-8244-gcp]   pytest .
==================================== test session starts ====================================
platform linux -- Python 3.9.7, pytest-5.4.3, py-1.10.0, pluggy-0.13.1
rootdir: /home/gonzz/git/wazuh/wodles/gcloud
plugins: asyncio-0.15.1, cov-2.12.0
collected 7 items                                                                           

tests/test_access_logs.py .                                                           [ 14%]
tests/test_bucket.py .                                                                [ 28%]
tests/test_integration.py ...                                                         [ 71%]
tests/test_subscriber.py .                                                            [ 85%]
tests/test_tools.py .                                                                 [100%]

===================================== 7 passed in 0.17s =====================================
```
