### ISSUE TITLE
Merge `file_entry` and `file_data` into a single table

### ISSUE THREAD

**Issue by Molter73** [wazuh/wazuh#8855]
|Wazuh version|Component|
|---|---|
| 4.2.0+ | Wazuh FIM |

This issue aims at unifying both file tables in the FIM DB into a single one.

### Tasks
- [x] Change the FIM DB schema.
- [x] Modify affected queries, remove obsolete ones.
- [x] Fix any `fim_db` functions broken by changes on queries.
