### ISSUE TITLE
Investigate resource usage after unifying FIM DB

### ISSUE THREAD

**Issue by Molter73** [wazuh/wazuh#8857]
|Wazuh version|Component|
|---|---|
| 4.2.0+ | Wazuh FIM |

This issue aims at investigating and documenting resource usage by FIM before and after the file tables are unified. All tests must be done on as many platforms as possible and run with the DB in memory and disk modes.

### Tasks
- [x] Compare CPU usage before and after the change.
- [x] Compare memory usage before and after the change.
- [x] Compare disk usage before and after the change.

**Comment by jotacarma90** [comment]
Here are the results of the performance analysis before and after the database related changes:
https://docs.google.com/spreadsheets/d/1jSxQzB11y6eKEwrrQerd3e0df1tWnUzU19qiSxgGvFE/edit?usp=sharing

![image](https://user-images.githubusercontent.com/60003131/123127192-5691db80-d44a-11eb-9a41-edd8bc29cc1d.png)

**Comment by jotacarma90** [comment]
## Summary of the analysis

The tests have all been done on a vabrant virtual machine, bento/ubuntu-18.04, with 4 cores and 4096MB of RAM.
The configuration used in most cases has been:
```
  <syscheck>
    <frequency>10</frequency>
    <disabled>no</disabled>
    <directories check_all="yes">/monitored</directories>
    <max_eps>5000</max_eps>
    <database>memory</database>
    <synchronization>
      <enabled>no</enabled>
    </synchronization>
  </syscheck>
```

For the test of modifying the inodes I used the command:
`rm -rf /monitored/* && shuf -z -e /testdir/* | xargs -0 cp -t /monitored/`

To generate the normal modifications (mtime only): 
`for i in {1..5000}; do touch /monitored/test$i; done`

For the hardlinks test:
`for i in {1..1000}; do ln /monitored/file /monitored/hardlink$i; done`

Los resultados muestra claras mejoras en tiempo de CPU y escritura en disco. El tamaño de la DB crece mas si existen multiples hardlinks.
![image](https://user-images.githubusercontent.com/60003131/123258483-b2fd0580-d4f3-11eb-907c-bd5a46d510a7.png)
![image](https://user-images.githubusercontent.com/60003131/123259314-a0370080-d4f4-11eb-8ea1-4b43082b77c8.png)
![image](https://user-images.githubusercontent.com/60003131/123259341-a5944b00-d4f4-11eb-8758-affd83b28cfd.png)
![image](https://user-images.githubusercontent.com/60003131/123259366-ab8a2c00-d4f4-11eb-949d-f1e0978dd671.png)
![image](https://user-images.githubusercontent.com/60003131/123259392-b2b13a00-d4f4-11eb-8faa-99ebd452046c.png)
![image](https://user-images.githubusercontent.com/60003131/123259509-d2486280-d4f4-11eb-8a34-6c2a51dd9df5.png)

**Comment by Molter73** [comment]
Thank you @jotacarma90 for the extensive testing done.

All the values look according to what we would expect from the changes implemented. It's great to know that on DBs with a small number of hardlinks we are actually using less disk space than before and the performance increase when having inode collisions on a scan looks substantial.

Since no further actions are required, I'm closing this issue so we can move on with the epic issue.
