### ISSUE TITLE
Add generic load balancers rules for GCP

### ISSUE THREAD

**Issue by JavierBejMen** [wazuh/wazuh#9000]
# Description
Generic rules needed in order to monitor LB logs from GCP integration

## Reference
- https://cloud.google.com/load-balancing/docs/https/https-logging-monitoring

## Logs
```json
{
    "integration": "gcp",
    "gcp": {
        "httpRequest": {
            "latency": "0.000864s",
            "remoteIp": "YY.YY.YY.YY",
            "requestMethod": "GET",
            "requestSize": "385",
            "requestUrl": "http://XX.XX.XX.XX/favicon.ico",
            "responseSize": "488",
            "status": 502,
            "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
        },
        "insertId": "1mtxf1hf2c4idk",
        "jsonPayload": {
            "@type": "type.googleapis.com/google.cloud.loadbalancing.type.LoadBalancerLogEntry",
            "statusDetails": "failed_to_pick_backend"
        },
        "logName": "projects/wazuh-dev-xxxxxx/logs/requests",
        "receiveTimestamp": "2021-06-09T15:17:25.473538144Z",
        "resource": {
            "labels": {
                "backend_service_name": "framework-load-balancer-backend-test",
                "forwarding_rule_name": "framework-load-balancer-backend-test",
                "project_id": "wazuh-dev-xxxxxx",
                "target_proxy_name": "framework-load-balancer-test-target-proxy",
                "url_map_name": "framework-load-balancer-test",
                "zone": "global"
            },
            "type": "http_load_balancer"
        },
        "severity": "WARNING",
        "spanId": "ab6c36e7fc60f24e",
        "timestamp": "2021-06-09T15:17:24.408864Z",
        "trace": "projects/wazuh-dev-xxxxxx/traces/68183a7cda548ce0e79207099a1fea58"
    }
}
```
# Tasks
- [x] Research LB formats
- [x] Add generic rules
- [x] Add tests (.ini)

## Branch
https://github.com/wazuh/wazuh/tree/8244_gcp_vpc_ruleset

**Comment by JavierBejMen** [comment]
# Update
HTTPS internal/external Load Balancers are identified by the `httpRequest` field, a valid generic rule would be:
```xml
<!-- LB https internal/external -->
    <rule id="65051" level="2">
        <if_sid>65000</if_sid>
        <field name="gcp.httpRequest.status" type="pcre2">^(?!^$).*</field>
        <description>GCP HTTP Load Balancer event</description>
        <options>no_full_log</options>
    </rule>
```

**Comment by JavierBejMen** [comment]
# Closed

After reviewing GCP documentation about [Internal TCP/UDP LB](https://cloud.google.com/load-balancing/docs/internal/internal-logging-monitoring), [external TCP/UDP LB](https://cloud.google.com/load-balancing/docs/network/networklb-monitoring) and [external SSL/TCP Proxies LB](https://cloud.google.com/load-balancing/docs/tcp/tcp-ssl-proxy-logging-monitoring) there seems to be available only metrics with no security relevance without traffic analysis techniques, thus integration has not been tested and therefore rules won't be implemented.
