### ISSUE TITLE
Automatic decoders for Windows events

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#905]
|Depends on|
|---|
|#2105|

Our windows decoders cause a lot of issues and they don't extract all the information. There are programs like NxLog (open source) or Winlogbeat (https://www.elastic.co/downloads/beats/winlogbeat) that convert from Windows log to JSON.

We have two options:

- Send the raw log and parse the log to dynamic fields using plugin decoders.
- Define a new logformat: `<logformat>windows_event</logformat>`. It sends the Windows event as JSON.

```json
{
  "EventTime": "2017-04-10 23:03:52",
  "Hostname": "Desktop",
  "Keywords": -9214364837600035000,
  "EventType": "AUDIT_SUCCESS",
  "SeverityValue": 2,
  "Severity": "INFO",
  "EventID": 4688,
  "SourceName": "Microsoft-Windows-Security-Auditing",
  "ProviderGuid": "{54849625-5478-4994-A5BA-3E3B0328C30D}",
  "Version": 2,
  "Task": 13312,
  "OpcodeValue": 0,
  "RecordNumber": 27093267,
  "ProcessID": 4,
  "ThreadID": 10112,
  "Channel": "Security",
  "Message": "A new process has been created.\r\n\r\nCreator Subject:\r\n\tSecurity ID:\t\tS-1-5-21-xxxxxxxxxx-xxxxxxxxxx-xxxxxxxxxx-xxxx\r\n\tAccount Name:\t\txxxxxx\r\n\tAccount Domain:\t\tXXXXXXX\r\n\tLogon ID:\t\t0x131E6806\r\n\r\nTarget Subject:\r\n\tSecurity ID:\t\tS-1-0-0\r\n\tAccount Name:\t\t-\r\n\tAccount Domain:\t\t-\r\n\tLogon ID:\t\t0x0\r\n\r\nProcess Information:\r\n\tNew Process ID:\t\t0xe5c\r\n\tNew Process Name:\tC:\\Program Files (x86)\\Windows\\Resource Kits\\Tools\\tail.exe\r\n\tToken Elevation Type:\t%%1937\r\n\tMandatory Label:\t\tS-1-16-12288\r\n\tCreator Process ID:\t0x91c\r\n\tCreator Process Name:\tC:\\Windows\\System32\\cmd.exe\r\n\tProcess Command Line:\ttail -1 win_sec_process_tracking.log\r\n\r\nToken Elevation Type indicates the type of token that was assigned to the new process in accordance with User Account Control policy.\r\n\r\nType 1 is a full token with no privileges removed or groups disabled. A full token is only used if User Account Control is disabled or if the user is the built-in Administrator account or a service account.\r\n\r\nType 2 is an elevated token with no privileges removed or groups disabled. An elevated token is used when User Account Control is enabled and the user chooses to start the program using Run as administrator. An elevated token is also used when an application is configured to always require administrative privilege or to always require maximum privilege, and the user is a member of the Administrators group.\r\n\r\nType 3 is a limited token with administrative privileges removed and administrative groups disabled. The limited token is used when User Account Control is enabled, the application does not require administrative privilege, and the user does not choose to start the program using Run as administrator.",
  "Category": "Process Creation",
  "Opcode": "Info",
  "SubjectUserSid": "S-1-5-21-xxxxxxxxxx-xxxxxxxxxx-xxxxxxxxxx-xxxx",
  "SubjectUserName": "xxxxxxxx",
  "SubjectDomainName": "xxxxxxxx",
  "SubjectLogonId": "0x131e6806",
  "NewProcessId": "0xe5c",
  "NewProcessName": "C:\\Program Files (x86)\\Windows\\Resource Kits\\Tools\\tail.exe",
  "TokenElevationType": "%%1937",
  "CommandLine": "tail -1 win_sec_process_tracking.log",
  "TargetUserSid": "S-1-0-0",
  "TargetUserName": "-",
  "TargetDomainName": "-",
  "TargetLogonId": "0x0",
  "ParentProcessName": "C:\\Windows\\System32\\cmd.exe",
  "MandatoryLabel": "S-1-16-12288",
  "EventReceivedTime": 1491854633,
  "SourceModuleName": "win_sec_process_tracking",
  "SourceModuleType": "im_msvistalog"
}
```

## Requirements

- This new event format must be compatible with the same versions of Windows that the Eventchannel format supports.
- This collector must extract all the possible data from the event.
- The keys must be independent from the language of the operating system.

## Subtasks

- [x] Render the content of the Windows event log in XML.
- [x] Extend the OSSEC XML parser to accept strings, in addition to files.
- [x] Cut the `message` field in order to avoid duplicate data (already given in the XML content).
- Test the new XML content:
  - [x] It must work with every language of Windows.
  - [x] The key data —name of the fields— must not change across languages.
  - [x] The parser must extract all the possible fields.
- [x] Compose the collected data into a JSON string.
- [x] Test that the JSON parser correctly accepts the full event from the agent.
- [x] Extend the ruleset to produce alerts.
- [x] [Documentation](https://github.com/wazuh/wazuh-documentation/pull/660)
- [x] Unify the start functions
## Post conditions

- The new alerts will have a different rule ID.

## Testing
See the logs at archives.log and the alerts matched at alerts.log.

- [x] Installing/uninstalling a program.
- [x] Sysmon
- [x] Sign out/sign in.
- [x] Custom event (for example: eventcreate /T INFORMATION /ID 88 /L Application /SO MozillaFirefox /D "Firefox has started successfully".
- [x] Installing Chrome Remote Desktop and seeing the logs generated at the archives.json file.
- [x] Add a new user with Admin privileges or Child.
- [x] Windows Defender
- [x] Windows Security Essentials

Windows versions:
- [x] Check all the Windows lower than Vista show the message that says that the eventchannel is not supported.
- [x] Windows 7
- [x] Windows 8.1
- [x] Windows 10
- [x] Windows Server 2019
- [x] Test the newer versions of Windows in every language (english, spanish, french, chinese, japanese, russian, korean).
- [x] Test with a Wazuh app (https://github.com/wazuh/wazuh/issues/1997).

## Data obtained
This module will get two main fields, `System` and `EventData`. `System` is generally static and shows information about the environment, and `EventData` is totally dynamic, it gets some extra fields about the event.

- System: There are some fields inside this one that are not shown everytime:
    - EventSourceName
    - Opcode
    - ProcessID
    - ThreadID

   This are the static ones:
    - ProviderName
    - ProviderGuid
    - EventID
    - Version
    - Level
    - Task
    - Keywords
    - SystemTime
    - EventRecordID
    - Channel
    - Computer

They all can be obtained from the XML string except for `Message` and `SeverityValue`. The `SeverityValue` field can be calculated with the `keywords` and the `level` values. For the `Message` field, there is a function at the read_win_event_channel.c named `get_message` that gets this string with the `ProviderName` as an input.

- EventData: This field can be empty, its parameters can have names that doesn't show any information about the value, for example: `"Data":"10.0.0.3"`, but they all can be obtained by the XML.

In conclusion, every field is contemplated at the XML string but the `Message` and the `SeverityValue`, that can be obtained with other fields at the XML.

## Message sent to the manager
As there are some fields that can't be found at the XML string, to make adding some more fields easier, the event will be sent to the manager as an XML inside a JSON, where the new fields that can't be obtained by the XML and must be obtained at the agent will be added as key:value, as shown below:

```
{
"Message":"Successfully scheduled Software Protection service for re-start at 2018-11-28T10:06:42Z. Reason: RulesEngine.",
"Event":"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-SPP' Guid='{E23B33B0-C8C9-472C-A5F9-F2BDFEA0F156}' EventSourceName='Software Protection Platform Service'/><EventID Qualifiers='16384'>902</EventID><Version>0</Version><Level>0</Level><Task>0</Task><Opcode>0</Opcode><Keywords>0x80000000000000</Keywords><TimeCreated SystemTime='2018-12-07T14:38:26.000000000Z'/><EventRecordID>1519</EventRecordID><Correlation/><Execution ProcessID='0' ThreadID='0'/><Channel>Application</Channel><Computer>dsaf</Computer><Security/></System><EventData><Data>6.3.9600.16497</Data></EventData></Event>"
}
```

## Important information
There are some events that are not being processed yet because they have some fields that our XML parser cannot read. This fields are ended with a backslash (`\`), for example: 
`<Data Name='CurrentDirectory'>C:\\Users\\user1\\</Data>`. 
There are two backslashes at the end of the value, meant to be skipped and just process one of them, but our parser translate it as an end of field tag, and it crashes as it is not an end.

**Comment by V1D1AN** [comment]
Yes it's a good idea..
With this idea, we have all the fields scattered in the archive.json
After, when you use logstash with the plugin json, you can send all the logs in elasticsearch

**Comment by cristgl** [comment]
It is possible to get all the parameters with the EvtRender function, but for now, I can't get all the events. I've been searching some information about this, and I have seen that the ReadEventLog function can do this, but can't get all the parameters because it returns an [_EVENTLOGRECORD](https://docs.microsoft.com/es-es/windows/desktop/api/winnt/ns-winnt-_eventlogrecord). I have seen that it is possible to get all the events with the EvtSubscribe function. I am trying it with this one.

This is a sample of log that I have achieved to obtain with the System and Security channels:
```
2018 Nov 22 08:48:08 (win) any->WinEvtLog {"System":{"ProviderName":"Microsoft-Windows-Security-Auditing","ProviderGuid":"{54849625-5478-4994-A5BA-3E3B0328C30D}","EventID":"4985","Version":"0","Level":"0","Task":"12800","Opcode":"0","Keywords":"0x8020000000000000","SystemTime":"2018-11-22T07:48:05.605974400Z","EventRecordID":"1441892","Correlation":"","ProcessID":"4","ThreadID":"1776","Channel":"Security","Computer":"hffg","Security":"","SeverityValue":"Unknown"},"EventData":{"SubjectUserSid":"S-1-5-18","SubjectUserName":"HFFG$","SubjectDomainName":"WORKGROUP","SubjectLogonId":"0x3e7","TransactionId":"{D1360FB4-EDA5-11E8-82B3-08002750D7C5}","NewState":"52","ResourceManager":"{7D5F0E1F-ABCB-11E8-A2E2-D5514FE2B72B}","ProcessId":"0x3e8","ProcessName":"C:\\Windows\\System32\\svchost.exe"}}

2018 Nov 21 17:02:31 (win) any->WinEvtLog {"System":{"ProviderName":"Microsoft-Windows-Winlogon","ProviderGuid":"{DBE9B383-7CF3-4331-91CC-A3CB16A3B538}","EventID":"7002","Version":"0","Level":"4","Task":"1102","Opcode":"0","Keywords":"0x2000000000000000","SystemTime":"2018-11-21T16:02:30.352212600Z","EventRecordID":"7800","Correlation":"","ProcessID":"2740","ThreadID":"4860","Channel":"System","Computer":"hffg","Security":"","SeverityValue":"Unknown"},"EventData":{"TSId":"19","UserSid":"S-1-5-21-2679284592-1135774982-2343772463-1001"}}
```

**Comment by cristgl** [comment]
All the events are being sent from channels Security, System and Application. The message is not working yet.

**Comment by V1D1AN** [comment]
It's a very good news :)

**Comment by cristgl** [comment]
@V1D1AN yes it will work with Windows Sysmon!

**Comment by V1D1AN** [comment]
Hello,

Hello how to activate the feature ??
I put <logformat>windows_event</logformat> in the ossec.conf of client Windows ??
I must recompile the win agent wazuh ?

Thanks :)

**Comment by cristgl** [comment]
Hello @V1D1AN, for activating it you have to download the [fix-windows-dec](https://github.com/wazuh/wazuh/tree/fix-windows-dec) branch and compile it for a Windows agent. Then, you'll have to configure the ossec.conf with the `<log_format>eventchannel-json</log_format>` option at the agent and restart it.
The 0380-windows_decoders.xml file is maintained for the old `eventchannel`, but not used for the new.
This feature is not finished yet, we are testing and trying to make some generic rules for making the addition of rules easier, but you can test it if you want!

Kind regards

**Comment by V1D1AN** [comment]
Thanks for your reponse :)
It's a very great job

**Comment by V1D1AN** [comment]
You must put this feature in the production.. 
Wazuh does the same as WinlogBeat... Now,  I must recreate all Windows rules with the tag \<decoded_as\>json\</decoded_as\> and recreate all my sysmon rules ..

**Comment by cristgl** [comment]
Hi @V1D1AN,
This branch is in development, it will be released for Wazuh v3.8.0. We are adapting the ruleset for this new feature so that you don't have to do it and it can be easier for the users.

Best regards

**Comment by V1D1AN** [comment]
I have errors in my ossec.log

2018/12/04 18:51:29 ossec-agent: INFO: (1951): Analyzing event log: 'Application'.
2018/12/04 18:51:29 ossec-agent: INFO: (1951): Analyzing event log: 'Security'.
2018/12/04 18:51:29 ossec-agent: INFO: (1951): Analyzing event log: 'System'.
2018/12/04 18:51:29 ossec-agent: ERROR: Could not EvtFormatMessage() to determine buffer size with flags (1) which returned (15027)
2018/12/04 18:51:29 ossec-agent: ERROR: Could not get message for (Application)

**Comment by cristgl** [comment]
Hello @V1D1AN,

This error comes when it is not possible to get the event message. Can you paste your ossec.conf here? Also I would like to know the Windows version and the language of it.

Best regards

**Comment by V1D1AN** [comment]
Hello @cristgl,

For my test,  I have a Microsoft Server 2008 R2 64bits with this conf : 



<ossec_config>

  <client>
    <server>
      <address>192.168.40.200</address>
      <port>1514</port>
      <protocol>udp</protocol>
    </server>
    <crypto_method>aes</crypto_method>
    <notify_time>10</notify_time>
    <time-reconnect>60</time-reconnect>
    <auto_restart>yes</auto_restart>
  </client>

  
  <client_buffer>
    <disabled>no</disabled>
    <queue_size>5000</queue_size>
    <events_per_second>500</events_per_second>
  </client_buffer>

  
  <localfile>
    <location>Application</location>
    <log_format>eventchannel-json</log_format>
  </localfile>

  <localfile>
    <location>Security</location>
    <log_format>eventchannel-json</log_format>
  </localfile>

  <localfile>
    <location>System</location>
    <log_format>eventchannel-json</log_format>
  </localfile>

  <localfile>
    <location>active-response\active-responses.log</location>
    <log_format>syslog</log_format>
  </localfile>
  
  <localfile>
      <location>Windows PowerShell</location>
      <log_format>eventchannel-json</log_format>
  </localfile>
    
  <localfile>
      <location>Microsoft-Windows-Application-Experience/Program-Inventory</location>
      <log_format>eventchannel-json</log_format>
  </localfile>
  
  <localfile>
      <location>Microsoft-Windows-DNS-Client/Operational</location>
      <log_format>eventchannel-json</log_format>
  </localfile>
  
  <localfile>
      <location>Microsoft-Windows-DriverFrameworks-UserMode/Operational</location>
      <log_format>eventchannel-json</log_format>
  </localfile>
  
  <localfile>
      <location>Microsoft-Windows-Sysmon/Operational</location>
      <log_format>eventchannel-json</log_format>
  </localfile>
    
  <localfile>
      <location>Microsoft-Windows-TaskScheduler/Operational</location>
      <log_format>eventchannel-json</log_format>
  </localfile>
    
  <localfile>
      <location>Microsoft-Windows-TerminalServices-RemoteConnectionManager/Operational</location>
      <log_format>eventchannel-json</log_format>
  </localfile>
  
  <localfile>
      <location>Microsoft-Windows-Windows Firewall With Advanced Security/Firewall</location>
      <log_format>eventchannel-json</log_format>
  </localfile>

  
  <rootcheck>
    <disabled>no</disabled>
    <windows_audit>./shared/win_audit_rcl.txt</windows_audit>
    <windows_apps>./shared/win_applications_rcl.txt</windows_apps>
    <windows_malware>./shared/win_malware_rcl.txt</windows_malware>
  </rootcheck>

  
  <syscheck>
    
    <disabled>no</disabled>

    
    <frequency>43200</frequency>

    
    <directories check_all="yes">%WINDIR%\regedit.exe</directories>
    <directories check_all="yes">%WINDIR%\system.ini</directories>
    <directories check_all="yes">%WINDIR%\win.ini</directories>

    <directories check_all="yes">%WINDIR%\SysNative\at.exe</directories>
    <directories check_all="yes">%WINDIR%\SysNative\attrib.exe</directories>
    <directories check_all="yes">%WINDIR%\SysNative\cacls.exe</directories>
    <directories check_all="yes">%WINDIR%\SysNative\cmd.exe</directories>
    <directories check_all="yes">%WINDIR%\SysNative\drivers\etc</directories>
    <directories check_all="yes">%WINDIR%\SysNative\eventcreate.exe</directories>
    <directories check_all="yes">%WINDIR%\SysNative\ftp.exe</directories>
    <directories check_all="yes">%WINDIR%\SysNative\lsass.exe</directories>
    <directories check_all="yes">%WINDIR%\SysNative\net.exe</directories>
    <directories check_all="yes">%WINDIR%\SysNative\net1.exe</directories>
    <directories check_all="yes">%WINDIR%\SysNative\netsh.exe</directories>
    <directories check_all="yes">%WINDIR%\SysNative\reg.exe</directories>
    <directories check_all="yes">%WINDIR%\SysNative\regedt32.exe</directories>
    <directories check_all="yes">%WINDIR%\SysNative\regsvr32.exe</directories>
    <directories check_all="yes">%WINDIR%\SysNative\runas.exe</directories>
    <directories check_all="yes">%WINDIR%\SysNative\sc.exe</directories>
    <directories check_all="yes">%WINDIR%\SysNative\schtasks.exe</directories>
    <directories check_all="yes">%WINDIR%\SysNative\sethc.exe</directories>
    <directories check_all="yes">%WINDIR%\SysNative\subst.exe</directories>
    <directories check_all="yes">%WINDIR%\SysNative\wbem\WMIC.exe</directories>
    <directories check_all="yes">%WINDIR%\SysNative\WindowsPowerShell\v1.0\powershell.exe</directories>
    <directories check_all="yes">%WINDIR%\SysNative\winrm.vbs</directories>

    
    <directories check_all="yes">%WINDIR%\System32\at.exe</directories>
    <directories check_all="yes">%WINDIR%\System32\attrib.exe</directories>
    <directories check_all="yes">%WINDIR%\System32\cacls.exe</directories>
    <directories check_all="yes">%WINDIR%\System32\cmd.exe</directories>
    <directories check_all="yes">%WINDIR%\System32\drivers\etc</directories>
    <directories check_all="yes">%WINDIR%\System32\eventcreate.exe</directories>
    <directories check_all="yes">%WINDIR%\System32\ftp.exe</directories>
    <directories check_all="yes">%WINDIR%\System32\net.exe</directories>
    <directories check_all="yes">%WINDIR%\System32\net1.exe</directories>
    <directories check_all="yes">%WINDIR%\System32\netsh.exe</directories>
    <directories check_all="yes">%WINDIR%\System32\reg.exe</directories>
    <directories check_all="yes">%WINDIR%\System32\regedit.exe</directories>
    <directories check_all="yes">%WINDIR%\System32\regedt32.exe</directories>
    <directories check_all="yes">%WINDIR%\System32\regsvr32.exe</directories>
    <directories check_all="yes">%WINDIR%\System32\runas.exe</directories>
    <directories check_all="yes">%WINDIR%\System32\sc.exe</directories>
    <directories check_all="yes">%WINDIR%\System32\schtasks.exe</directories>
    <directories check_all="yes">%WINDIR%\System32\sethc.exe</directories>
    <directories check_all="yes">%WINDIR%\System32\subst.exe</directories>
    <directories check_all="yes">%WINDIR%\System32\wbem\WMIC.exe</directories>
    <directories check_all="yes">%WINDIR%\System32\WindowsPowerShell\v1.0\powershell.exe</directories>
    <directories check_all="yes">%WINDIR%\System32\winrm.vbs</directories>

    <directories check_all="yes" realtime="yes">%PROGRAMDATA%\Microsoft\Windows\Start Menu\Programs\Startup</directories>

    <ignore type="sregex">.log$|.htm$|.jpg$|.png$|.chm$|.pnf$|.evtx$</ignore>

    
    <windows_registry>HKEY_LOCAL_MACHINE\Software\Classes\batfile</windows_registry>
    <windows_registry>HKEY_LOCAL_MACHINE\Software\Classes\cmdfile</windows_registry>
    <windows_registry>HKEY_LOCAL_MACHINE\Software\Classes\comfile</windows_registry>
    <windows_registry>HKEY_LOCAL_MACHINE\Software\Classes\exefile</windows_registry>
    <windows_registry>HKEY_LOCAL_MACHINE\Software\Classes\piffile</windows_registry>
    <windows_registry>HKEY_LOCAL_MACHINE\Software\Classes\AllFilesystemObjects</windows_registry>
    <windows_registry>HKEY_LOCAL_MACHINE\Software\Classes\Directory</windows_registry>
    <windows_registry>HKEY_LOCAL_MACHINE\Software\Classes\Folder</windows_registry>
    <windows_registry arch="both">HKEY_LOCAL_MACHINE\Software\Classes\Protocols</windows_registry>
    <windows_registry arch="both">HKEY_LOCAL_MACHINE\Software\Policies</windows_registry>
    <windows_registry>HKEY_LOCAL_MACHINE\Security</windows_registry>
    <windows_registry arch="both">HKEY_LOCAL_MACHINE\Software\Microsoft\Internet Explorer</windows_registry>

    <windows_registry>HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services</windows_registry>
    <windows_registry>HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\KnownDLLs</windows_registry>
    <windows_registry>HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\SecurePipeServers\winreg</windows_registry>

    <windows_registry arch="both">HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run</windows_registry>
    <windows_registry arch="both">HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\RunOnce</windows_registry>
    <windows_registry>HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\RunOnceEx</windows_registry>
    <windows_registry arch="both">HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\URL</windows_registry>
    <windows_registry arch="both">HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies</windows_registry>
    <windows_registry arch="both">HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Windows</windows_registry>
    <windows_registry arch="both">HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Winlogon</windows_registry>

    <windows_registry arch="both">HKEY_LOCAL_MACHINE\Software\Microsoft\Active Setup\Installed Components</windows_registry>

    
    <registry_ignore>HKEY_LOCAL_MACHINE\Security\Policy\Secrets</registry_ignore>
    <registry_ignore>HKEY_LOCAL_MACHINE\Security\SAM\Domains\Account\Users</registry_ignore>
    <registry_ignore type="sregex">\Enum$</registry_ignore>

    
    <remove_old_diff>yes</remove_old_diff>

    
    <windows_audit_interval>300</windows_audit_interval>
  </syscheck>

  
  <wodle name="syscollector">
    <disabled>no</disabled>
    <interval>1h</interval>
    <scan_on_start>yes</scan_on_start>
    <hardware>yes</hardware>
    <os>yes</os>
    <network>yes</network>
    <packages>yes</packages>
    <ports all="no">yes</ports>
    <processes>yes</processes>
  </wodle>

  
  <wodle name="cis-cat">
    <disabled>yes</disabled>
    <timeout>1800</timeout>
    <interval>1d</interval>
    <scan-on-start>yes</scan-on-start>

    <java_path>\\server\jre\bin\java.exe</java_path>
    <ciscat_path>C:\cis-cat</ciscat_path>
  </wodle>

  
  <wodle name="osquery">
    <disabled>yes</disabled>
    <run_daemon>yes</run_daemon>
    <bin_path>C:\ProgramData\osquery\osqueryd</bin_path>
    <log_path>C:\ProgramData\osquery\log\osqueryd.results.log</log_path>
    <config_path>C:\ProgramData\osquery\osquery.conf</config_path>
    <add_labels>yes</add_labels>
  </wodle>

  
  <active-response>
    <disabled>no</disabled>
    <ca_store>wpk_root.pem</ca_store>
    <ca_verification>yes</ca_verification>
  </active-response>
  <command>
    <name>restart-ossec</name>
    <executable>restart-ossec.cmd</executable>
    <expect></expect>
  </command>

  
  <logging>
    <log_format>plain</log_format>
  </logging>

</ossec_config>




And I have the same error with Microsoft Windows 7 X86 FRE :

**Comment by cristgl** [comment]
Hello @V1D1AN,
I will search for the `ERROR_EVT_MESSAGE_NOT_FOUND` error and tell you if I find anything.
Can you tell me if the event is being sent anyways?

Best regards

**Comment by V1D1AN** [comment]
I have an other error in my ossec.log ..
2018/12/05 11:19:29 ossec-agent: ERROR: error xml file not read 
2018/12/05 11:19:29 ossec-agent: ERROR: error xml file not read
2018/12/05 11:19:29 ossec-agent: ERROR: error xml file not read
...

**Comment by V1D1AN** [comment]
I have an other error with my Windows 2008 R2, my Wazuh agent crash  : 
```
Faulting application name: ossec-agent.exe, version: 0.0.0.0, time stamp: 0x5c0124d1
Faulting module name: msvcrt.dll, version: 7.0.7600.16385, time stamp: 0x4a5bda6f
Exception code: 0xc0000005
Fault offset: 0x0000dc12
Faulting process id: 0x1118
Faulting application start time: 0x01d48cea1286fffc
Faulting application path: C:\Program Files (x86)\ossec-agent\ossec-agent.exe
Faulting module path: C:\Windows\syswow64\msvcrt.dll
Report Id: 51920584-f8dd-11e8-8eb2-000c290fe2e5
```

**Comment by V1D1AN** [comment]
I have a crash with the Wazuh Agent..

This is the extract of Application Event Viewer
```
Faulting application name: ossec-agent.exe, version: 0.0.0.0, time stamp: 0x5c0124d1
Faulting module name: msvcrt.dll, version: 7.0.7600.16385, time stamp: 0x4a5bda6f
Exception code: 0xc0000005
Fault offset: 0x0000dc12
Faulting process id: 0xae4
Faulting application start time: 0x01d48f74b16e1808
Faulting application path: C:\Program Files (x86)\ossec-agent\ossec-agent.exe
Faulting module path: C:\Windows\syswow64\msvcrt.dll
Report Id: efcb11e6-fb67-11e8-aaf8-000c290fe2e5
```

If a I modify my ossec.conf like this: 
``` 
  <!-- Log analysis
  <localfile>
    <location>Application</location>
    <log_format>eventchannel-json</log_format>
  </localfile>
  --> 
```

My Wazuh Agent start correctly

**Comment by cristgl** [comment]
Hello @V1D1AN,

This is still in development, but maybe your issues get solved with the new commit changes, this one modifies the event processing, now it is done at the manager; also it solves some other bugs. If you want to, you can try it and tell me if you keep having these problems, thank you for reporting them!

Best regards!

**Comment by V1D1AN** [comment]
Hello @cristgl 

Can you put your features with the version 3.7.2 of wazuh.. I have problem with the logcollector ..
https://github.com/wazuh/wazuh/issues/2088

Thanks for your jobs

**Comment by cristgl** [comment]
Hello @V1D1AN, it is not finished yet, it needs to be tested and it won't be released until Wazuh v3.8.0.
Thank you for understanding,

Best regards

**Comment by chemamartinez** [comment]
Hi @V1D1AN,

This development has been finished and it is already merged into the 3.8 branch. It will be released with the new Wazuh version, so let me close this issue.

If you have any other questions or comments, do not hesitate to let us know.

Thanks to @cristgl for the hard work!

Regards,
Chema.

**Comment by Testonesaid** [comment]
Hi Team

I am trying to implement the same in Wazuh version App version: App version: 4.7.0 and 4.8.0.
However, i do not receive the log in wazuh.
Is this recorded in Wazuh documentation.

Thanks
