### ISSUE TITLE
Add OracleDB 12c cluster ruleset

### ISSUE THREAD

**Issue by NicoGuini** [wazuh/wazuh#9056]
# Description
Ruleset for Oracle DB needs to be added.

Questionnaire summary:
```
What product is? Oracle DB - cluster
Any particular version? 12C
Is it paid? Yes - license is needed
  How we proceed to get that product installed for us? They will send us logs of 6 month
  What are the environment requirements to install the product? -
What are you needs? See security alerts, healthcheck, initdb logs provided by oracle (no additional information is needed)
What do you expect to see on Wazuh? -
Did you have any security issue that you expect to see? No
Exists documentation about the product? -
Do we need core team integration? Yes, maybe, we need to confirm
Expected date? 2/3 weeks
Expected Wazuh version? They want to install 4.2
Compliance or Mitre information? - 
```
## Logs
We have 2 types of logs, `.log` and `.aud` files.

Audit files contains logs of database operations and queries, they are multi-line, some examples:
```aud
Sat Dec 21 22:13:41 2019 +05:30
LENGTH : '4582'
ACTION :[4430] 'select /*+  no_parallel(t) no_parallel_index(t) dbms_stats cursor_sharing_exact use_weak_name_resl dynamic_sampling(0) no_monitoring xmlindex_sel_idx_tbl no_substrb_pad  */ substrb(dump("USER#",16,0,64),1,240) val, 
                      rowidtochar(rowid) rwid from "SYS"."USER$" t where rowid in (chartorowid('AAAAAKAABAAAADRAAA'),chartorowid('AAAAAKAABAAAADRAAB'),...) order by "USER#"'
DATABASE USER:[3] 'SYS'
PRIVILEGE :[4] 'NONE'
CLIENT USER:[0] ''
CLIENT TERMINAL:[7] 'UNKNOWN'
STATUS:[1] '0'
DBID:[10] '3320902093'

Sat Dec 21 22:13:41 2019 +05:30
LENGTH : '4582'
ACTION :[4430] 'select /*+  no_parallel(t) no_parallel_index(t) dbms_stats cursor_sharing_exact use_weak_name_resl dynamic_sampling(0) no_monitoring xmlindex_sel_idx_tbl no_substrb_pad  */ substrb(dump("USER#",16,0,64),1,240) val, 
                      rowidtochar(rowid) rwid from "SYS"."USER$" t where rowid in (chartorowid('AAAAAKAABAAAADRAAA'),chartorowid('AAAAAKAABAAAADRAAB'),chartorowid('AAAAAKAABAAAADRAAC'),chartorowid('AAAAAKAABAAAADRAAD'),chartorowid('AAAAAKAABAAAADRAAE'), ...) order by "USER#"'
DATABASE USER:[3] 'SYS'
PRIVILEGE :[4] 'NONE'
CLIENT USER:[0] ''
CLIENT TERMINAL:[7] 'UNKNOWN'
STATUS:[1] '0'
DBID:[10] '3320902093'
```

Log files are also multi-line and they contain general logging, some examples:
```log
Thu Feb 11 13:14:56 2021
Thread 1 advanced to log sequence 13060 (LGWR switch)
  Current log# 2 seq# 13060 mem# 0: +NPCDBDG/CDBTST93/ONLINELOG/group_2.384.1017127695
  Current log# 2 seq# 13060 mem# 1: +FLASHDG/CDBTST93/ONLINELOG/group_2.263.1017127695
Thu Feb 11 13:14:56 2021
Archived Log entry 13813 added for thread 1 sequence 13059 ID 0xc5f18acd dest 1:
Thu Feb 11 13:32:07 2021
skgxpvfynet: mtype: 61 process 38909 failed because of a resource problem in the OS. The OS has most likely run out of buffers (rval: 4)
Errors in file /opt/oracle/app/oracle/diag/rdbms/cdbtst93/CDBTST931/trace/CDBTST931_ora_38909.trc  (incident=346160):
ORA-00603: ORACLE server session terminated by fatal error
ORA-27504: IPC error creating OSD context
ORA-27300: OS system dependent operation:sendmsg failed with status: 105
ORA-27301: OS failure message: No buffer space available
ORA-27302: failure occurred at: sskgxpsnd2
Incident details in: /opt/oracle/app/oracle/diag/rdbms/cdbtst93/CDBTST931/incident/incdir_346160/CDBTST931_ora_38909_i346160.trc
opiodr aborting process unknown ospid (38909) as a result of ORA-603
Thu Feb 11 13:32:08 2021
Dumping diagnostic data in directory=[cdmp_20210211133208], requested by (instance=1, osid=38909), summary=[incident=346160].
```

## Tasks
- [x] Test multi-line functionality on Wazuh 4.2
- [x] Develop decoders
  - [x] Audit decoders
  - [x] General logging decoders
- [x] Develop generic rules
  - [x] Generic Audit rules
  - [x] Generic general logging rules
  - [x] Map applicable compliance 

## Branch to track changes
https://github.com/wazuh/wazuh/tree/9056_add_oracledb_12c_ruleset

**Comment by jcruzlp** [comment]
Used this field to catch the multi-line log.
```
  <localfile>
   <log_format>syslog</log_format>
   <location>/home/vagrant/test.log</location>
   <multiline_regex replace="wspace">\w{3}\s\w{3}\s{2}\d\s\d{2}:\d{2}:\d{2}\s\d{4}\s\+\d{2}:\d{2}</multiline_regex>
  </localfile>
```
But seems to don't get it right, asked Core team about this.

**Comment by JavierBejMen** [comment]
# Update 
In order to ingest multiline logs we need to add the following to wazuh configuration:
```conf
  <localfile>
   <log_format>multi-line-regex</log_format>
   <location>/vagrant/test.log</location>
   <multiline_regex replace="wspace" >^\w{3}\s\w{3}\s\d{2}\s\d{2}:\d{2}:\d{2}\s\d{4}$|\w{3}\s\w{3}\s{2}\d\s\d{2}:\d{2}:\d{2}\s\d{4}\s\+\d{2}:\d{2}</multiline_regex>
  </localfile>

```

**Comment by NicoGuini** [comment]
# Update
Suggested ossec.conf configuration

```
  <localfile>
    <log_format>multi-line-regex</log_format>
    <location>/tmp/oracle/CDBTST931_j000_31115_20191221221341590818143795.aud</location>
    <multiline_regex match="end">\n\n</multiline_regex>
    <out_format>$(timestamp) $(hostname) oracledb: $(log)</out_format>
  </localfile>
```

Suggested decoder: (0550-oracledb_decoders.xml)

```
<decoder name="oracledb_log">
    <program_name>^oracledb$</program_name>
</decoder>
```

**Comment by NicoGuini** [comment]
PR opened. And ready for review
