### ISSUE TITLE
AWS WAF V2 default rules decoding issue 

### ISSUE THREAD

**Issue by imtaji** [wazuh/wazuh#9101]
|Wazuh version| Component | Action type |
|---| --- | --- |
| wazuh/wazuh-odfe:4.1.5 | Rules/Decoders | Error |

## Description

I am already referring this https://github.com/wazuh/wazuh/blob/180bcc348b7e224d83a7bd752bead513f3f72cba/ruleset/rules/0350-amazon_rules.xml#L269

But somehow I am unable to decode the logs of AWS Waf V2. Wazuh setup is on AWS EKS as per your recommendations. 

### Reason
It completes phase 2 of decoding and then getting stuck. 

### Current results

```
[root@wazuh-manager-master-0 bin]# ./wazuh-logtest
Starting wazuh-logtest v4.1.5
Type one log per line

{"timestamp":1624525209272,"formatVersion":1,"webaclId":"arn:aws:wafv2:us-east-1:xxxxxxxxxxx:global/webacl/xxxxxxxxxxxx/f5ce530a-7320-5aac-c86c-d320157llaf6","terminatingRuleId":"Default_Action","terminatingRuleType":"REGULAR","action":"ALLOW","terminatingRuleMatchDetails":[],"httpSourceName":"CF","httpSourceId":"E2FAJHV15D60F3","ruleGroupList":[{"ruleGroupId":"AWS#AWSManagedRulesCommonRuleSet","terminatingRule":null,"nonTerminatingMatchingRules":[],"excludedRules":null},{"ruleGroupId":"AWS#AWSManagedRulesSQLiRuleSet","terminatingRule":null,"nonTerminatingMatchingRules":[],"excludedRules":null},{"ruleGroupId":"AWS#AWSManagedRulesAmazonIpReputationList","terminatingRule":null,"nonTerminatingMatchingRules":[],"excludedRules":null},{"ruleGroupId":"AWS#AWSManagedRulesAnonymousIpList","terminatingRule":null,"nonTerminatingMatchingRules":[],"excludedRules":null},{"ruleGroupId":"AWS#AWSManagedRulesKnownBadInputsRuleSet","terminatingRule":null,"nonTerminatingMatchingRules":[],"excludedRules":null},{"ruleGroupId":"AWS#AWSManagedRulesPHPRuleSet","terminatingRule":null,"nonTerminatingMatchingRules":[],"excludedRules":null}],"rateBasedRuleList":[{"rateBasedRuleId":"arn:aws:wafv2:us-east-1:XXXXXXXXXXXX_MANAGED:global/ipset/xxxxxxxxx-7420-4xxx-bxxc-exxxxx7ffaf6_0xxxxx04-7385-4e4e-a94d-abcb12xxxxx_IPV4/xxxxxxx-7385-xxxx-axx-abcb12xxxxxxxx","rateBasedRuleName":"Ratelimiting","limitKey":"IP","maxRateAllowed":200,"limitValue":"xxx.112.2xx.1xx"}],"nonTerminatingMatchingRules":[],"requestHeadersInserted":null,"responseCodeSent":null,"httpRequest":{"clientIp":"xxx.xxx.2xx.1xx","country":"RU","headers":[{"name":"host","value":"xxxxxxx.xxxxx.com"},{"name":"content-type","value":"application/json"},{"name":"accept","value":"*/*"},{"name":"authorization","value":"Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"},{"name":"accept-language","value":"ru"},{"name":"accept-encoding","value":"gzip, deflate, br"},{"name":"origin","value":"https://xxxxxx.xxxxxx.com"},{"name":"user-agent","value":"REDACTED"},{"name":"referer","value":"https://xxxxxxx.xxxxxxx.com/new/user/auth/login"},{"name":"content-length","value":"355"},{"name":"cookie","value":"LIVE_SESSION=xxxxxxxxxxxxxxxxx; wt_rla=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; lid=xxxxxxxxAgA="}],"uri":"REDACTED","args":"REDACTED","httpVersion":"HTTP/2.0","httpMethod":"REDACTED","requestId":"xxxxxxxxxxxxxxxw9WloxxxxxxxxxxcoGvxxxxxfsTtw=="}}

**Phase 1: Completed pre-decoding.
	full event: '{"timestamp":1624525209272,"formatVersion":1,"webaclId":"arn:aws:wafv2:us-east-1:xxxxxxxxxx:global/webacl/Lamoda1_Live/xxxxxxxxxx-xxxxxxxxxx-","terminatingRuleId":"Default_Action","terminatingRuleType":"REGULAR","action":"ALLOW","terminatingRuleMatchDetails":[],"httpSourceName":"CF","httpSourceId":"xxxxxxxxxx","ruleGroupList":[{"ruleGroupId":"AWS#AWSManagedRulesCommonRuleSet","terminatingRule":null,"nonTerminatingMatchingRules":[],"excludedRules":null},{"ruleGroupId":"AWS#AWSManagedRulesSQLiRuleSet","terminatingRule":null,"nonTerminatingMatchingRules":[],"excludedRules":null},{"ruleGroupId":"AWS#AWSManagedRulesAmazonIpReputationList","terminatingRule":null,"nonTerminatingMatchingRules":[],"excludedRules":null},{"ruleGroupId":"AWS#AWSManagedRulesAnonymousIpList","terminatingRule":null,"nonTerminatingMatchingRules":[],"excludedRules":null},{"ruleGroupId":"AWS#AWSManagedRulesKnownBadInputsRuleSet","terminatingRule":null,"nonTerminatingMatchingRules":[],"excludedRules":null},{"ruleGroupId":"AWS#AWSManagedRulesPHPRuleSet","terminatingRule":null,"nonTerminatingMatchingRules":[],"excludedRules":null}],"rateBasedRuleList":[{"rateBasedRuleId":"arn:aws:wafv2:us-east-1:xxxxxxxxxx_MANAGED:global/ipset/xxxxxxxxxx_IPV4/xxxxxxxxxx-abcb1290462c","rateBasedRuleName":"Ratelimiting","limitKey":"IP","maxRateAllowed":200,"limitValue":"1xx.1xx.2xx.1xx"}],"nonTerminatingMatchingRules":[],"requestHeadersInserted":null,"responseCodeSent":null,"httpRequest":{"clientIp":"1xx.1xx.2xx.1xx","country":"RU","headers":[{"name":"host","value":"xx.xxxxx.com"},{"name":"content-type","value":"application/json"},{"name":"accept","value":"*/*"},{"name":"authorization","value":"Bearer xxxxxxxxxx"},{"name":"accept-language","value":"ru"},{"name":"accept-encoding","value":"gzip, deflate, br"},{"name":"origin","value":"https://xxxx.xxxxxxxxxx.com"},{"name":"user-agent","value":"REDACTED"},{"name":"referer","value":"https://xxxx.xxxx.com/login"},{"name":"content-length","value":"355"},{"name":"cookie","value":"LIVE_SESSION=xxxxxxxxxx; wt_rla=xxxxxxxxxx; _hjid=xxxxxxxxxx; lid=xxxxxxxxxxd6zmAgA="}],"uri":"REDACTED","args":"REDACTED","httpVersion":"HTTP/2.0","httpMethod":"REDACTED","requestId":"xxxxxxxxxxPK8m9EfsTtw=="}}'

**Phase 2: Completed decoding.
	name: 'json'
	action: 'ALLOW'
	formatVersion: '1'
	httpRequest.args: 'REDACTED'
	httpRequest.clientIp: '1xx.1xx.2xx.1xx'
	httpRequest.country: 'RU'
	httpRequest.headers: '[{'name': 'host', 'value': 'xxx.xxx.com'}, {'name': 'content-type', 'value': 'application/json'}, {'name': 'accept', 'value': '*/*'}, {'name': 'authorization', 'value': 'Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}, {'name': 'accept-language', 'value': 'ru'}, {'name': 'accept-encoding', 'value': 'gzip, deflate, br'}, {'name': 'origin', 'value': 'https://xxx.xxx.com'}, {'name': 'user-agent', 'value': 'REDACTED'}, {'name': 'referer', 'value': 'https://xxx.xxx.com/login'}, {'name': 'content-length', 'value': '355'}, {'name': 'cookie', 'value': 'LIVE_SESSION=xxxxxxxxxxxxxxxxxx; wt_rla=xxxxxxxxxxxx; wt3_sid=xxxxxx; wt_geid=xxxxxx; lid=xxxIdxxx='}]'
	httpRequest.httpMethod: 'REDACTED'
	httpRequest.httpVersion: 'HTTP/2.0'
	httpRequest.requestId: 'xxxK8m9EfsTtw=='
	httpRequest.uri: 'REDACTED'
	httpSourceId: 'XXXXXXXXXXXX'
	httpSourceName: 'CF'
	nonTerminatingMatchingRules: '[]'
	rateBasedRuleList: '[{'rateBasedRuleId': 'arn:aws:wafv2:us-east-1:XXXXXXX_MANAGED:global/ipset/fxxxx_IPV4/09e55e04-7385-4e4e-a94d-abcb1290462c', 'rateBasedRuleName': 'Ratelimiting', 'limitKey': 'IP', 'maxRateAllowed': 200, 'limitValue': '1xx.1xx.2xx.1xx'}]'
	requestHeadersInserted: 'null'
	responseCodeSent: 'null'
	ruleGroupList: '[{'ruleGroupId': 'AWS#AWSManagedRulesCommonRuleSet', 'terminatingRule': None, 'nonTerminatingMatchingRules': [], 'excludedRules': None}, {'ruleGroupId': 'AWS#AWSManagedRulesSQLiRuleSet', 'terminatingRule': None, 'nonTerminatingMatchingRules': [], 'excludedRules': None}, {'ruleGroupId': 'AWS#AWSManagedRulesAmazonIpReputationList', 'terminatingRule': None, 'nonTerminatingMatchingRules': [], 'excludedRules': None}, {'ruleGroupId': 'AWS#AWSManagedRulesAnonymousIpList', 'terminatingRule': None, 'nonTerminatingMatchingRules': [], 'excludedRules': None}, {'ruleGroupId': 'AWS#AWSManagedRulesKnownBadInputsRuleSet', 'terminatingRule': None, 'nonTerminatingMatchingRules': [], 'excludedRules': None}, {'ruleGroupId': 'AWS#AWSManagedRulesPHPRuleSet', 'terminatingRule': None, 'nonTerminatingMatchingRules': [], 'excludedRules': None}]'
	terminatingRuleId: 'Default_Action'
	terminatingRuleMatchDetails: '[]'
	terminatingRuleType: 'REGULAR'
	timestamp: '1624525209272.000000'
	webaclId: 'arn:aws:wafv2:us-east-1:xxxxxxxx:global/webacl/xxxxxx/f4xxxxx-74xx-4xxx-bxxx-e32xxxxaf6'

```

### Expected results

Along with above mentioned `current results`, there should be phase 3 i.e.

```
**Phase 3: Completed filtering (rules).
	id: 'xxxxx'
	level: '3'
	description: 'warning message.'
	groups: '['amazonwaf']'
	firedtimes: '1'
	mail: 'False'
**Alert to be generated.
```

### Log format reference 
https://github.com/wazuh/wazuh/issues/7947

## Tests

- [x] Added .ini test file for covering related rules :x:
- [x] Executed unit tests (runtests.py) for checking ruleset integrity :x:
- [x] Verified mitre.db integrity :x:
- [x] Verified compliance mapping :x: 
- [x] Verified no errors/warnings related in ossec.log :x:
- [x] Kibana shows alerts :x:

**Comment by imtaji** [comment]
please try with log samples: https://docs.aws.amazon.com/waf/latest/developerguide/logging.html

**Comment by imtaji** [comment]
## Update:

After spending almost this week, I have learned that `{"source": "waf","integration": "aws", "aws":` should be appended in front of logs. I am assuming that wazuh do itself, but I don't know how to confirm this. 

Here are logs from `ossec.log`:

```
2021/06/25 17:12:29 wazuh-modulesd:aws-s3: INFO: Starting fetching of logs.
2021/06/25 17:12:29 wazuh-modulesd:aws-s3: INFO: Executing Bucket Analysis: (Bucket: wazuh-xxx, Path: firehose2021, Type: waf, Account ID: 810543902243, Account Alias: XXXX)
2021/06/25 17:12:31 wazuh-modulesd:aws-s3: INFO: Executing Service Analysis: (Service: cloudwatchlogs)
2021/06/25 17:12:32 wazuh-modulesd:aws-s3: INFO: Fetching logs finished.
```
which means `wazuh-master` is able to fetch the logs. Can you please tell me where are these logs now stored locally? I cannot find it anywhere.

After appending `{"source": "waf","integration": "aws", "aws":`, decoder is working:

```
**Phase 3: Completed filtering (rules).
	id: '80200'
	level: '0'
	description: 'AWS alert.'
	groups: '['amazon', 'aws']'
	firedtimes: '1'
	mail: 'False'
```

Now again I am stuck because I cannot see logs reflecting on UI:

![image](https://user-images.githubusercontent.com/13151141/123462019-16695f00-d5ea-11eb-9cf6-f3414023da6f.png)

**Comment by fabamatic** [comment]
Hello @imtaji , I am very sorry about the delay helping you with this issue.
As the saying goes, better late than never.
Let's start with the rules not triggering, the WAF rules located in wazuh/ruleset/rules/0350-amazon_rules.xml are not exactly for WAF raw logs but for cloudtrail logs of WAF. Cloudtrail is AWS auditing service. As you correctly discovered the logs need to have the aws integration data appended in front, and as you correctly guessed this is done automatically by Wazuh.

A guide on how to achieve CloudTrail integration with Wazuh [is available here](https://wazuh.com/blog/integrating-aws-cloudtrail-in-wazuh/)
The user manual describing how to integrate CloudTrail service [is also available](https://documentation.wazuh.com/current/amazon/services/supported-services/cloudtrail.html)

Let me know if this was helpful for you

**Comment by fabamatic** [comment]
Closing issue by lack of updates
