### ISSUE TITLE
Delete the modification of `agent-groups` files in the `DELETE /groups` endpoint

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#9141]
Hi team,

After analyzing the API performance test results (https://github.com/wazuh/wazuh/issues/8325), we have seen that despite the improvements made in the `DELETE /groups` endpoint (https://github.com/wazuh/wazuh/issues/9014), the endpoint does not scale as it should.

In our tests, the group to be deleted had 10000 agents, before the enhancement, about 1500 agents were unassigned from the group in about 10 seconds, after the enhancement about 6000 agents were deleted.

Looking into the Framework code, we have identified the bottleneck inside this endpoint. As we can see in lines 606-612, for each of the agents in the group, its agents are extracted and the group is removed from its agent-groups file. This is done so that we can return in the endpoint response the agents affected by this change. However, this is very inefficient because we perform two IO operations in addition to applying two decorators for each of the agents, as can be seen in lines 733-765.

https://github.com/wazuh/wazuh/blob/e1b9d1673abd5e0bc443e3d7b184454149588757/framework/wazuh/agent.py#L586-L622
https://github.com/wazuh/wazuh/blob/e1b9d1673abd5e0bc443e3d7b184454149588757/framework/wazuh/agent.py#L733-L768

Therefore, we propose to eliminate the call to `remove_agents_from_group`, in this way we will increase the speed of the endpoint substantially at the cost of losing the information of the affected agents. This loss of information is not relevant to us because the purpose of the endpoint is to indicate whether or not it has been possible to delete the agent. Furthermore, this change implies that until now, to delete an agent it was necessary to have permissions on the resource `group:delete`, `group:modify_assignments` and `agent:modify_group`, after the change, the only permission that the user needs to have is `group:delete`.

Finally, the proposed change implies that we stop modifying the `agent-groups` files from the Framework, so it would be necessary to investigate if by simply deleting the group, Wazuh internally modifies those files removing the deleted group from the agents.

## ToDo

- [ ] Investigate the possible implications of removing the triple decorator for group deletion.
- [ ] Apply the changes and test the internal behavior of Wazuh with agent-groups files.
- [ ] Run a performance test after applying the changes (more than 10000 agents).
- [ ] Update the documentation related to the permissions of this endpoint.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by davidjiglesias** [comment]
I am missing information and details on how much the different problems found affect the behavior and performance of these endpoints.

Before we move on with different solutions, we need to understand the weight of RBAC permissions collision and files management in the total execution time. We can apply a deep code profiling to obtain some metrics.

**Comment by davidjiglesias** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core-5b4dd684c93e4717b2160eea/issues/wazuh/wazuh/9141?planning-poker) with ZenHub @vicferpoy @mcarmona99 @Kondent
