### ISSUE TITLE
Agent ability to get the configuration files of different groups

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#917]
Currently, the managers will push a configuration file to a specific agent, depending on the group the agent belongs to. This means that the agent will inherit and apply the FIM settings for that specific group.

An agent can only apply get the FIM rules defined in its group, meaning that when a server is running multiple applications, the FIM rules to monitor all the applications need to be part of the group the agent belongs too.

Ideally, in order to avoid having to include all FIM settings in all groups, an agent should be able to belong to multiple groups. This way configuration groups (profiles) can be created on per application basis. 

The group configuration is transparent to agents: this feature is compatible with old versions of Wazuh and classic OSSEC.

## Subtasks

- [x] Extend agent metadata attributes to support multiple groups per agent.
- [x] Extend agent group TUI tool to manage multiple groups per agent.
- [x] Extend global agent database to support multiple groups per agent.
- [x] Extend the RESTful API to support multiple groups per agent.
- [x] Modify Remote daemon to gather multiple shared configuration files before sending to agents.
- [x] Detect the group of an agent using the MD5 sum of the shared file.

**Comment by vikman90** [comment]
## Behaviour design

- Every active agent must belong to one group at less. This assignation may be manual (by the user) or automatic (classification based on the agent's configuration MD5, or the group _default_).
- A corollary of the first sentence: an agent in _pending_  or _never connected_ status may not belong to any group.
- An agent may belong to more than one group.
-  The agents are not aware of the group (or groups) to which they belong.
- If an agent belongs to multiple groups, it will receive a shared file set containing the files of all the groups.
- The order matters:
 - The file _agent.conf_ is an amalgam of the _agent.conf_ files of every group, in the order they were assigned.
- If two groups contain a file with the same name (except `agent.conf`) only the latter will be sent.
- The UI (API & CLI) will list the groups for an agent and the agents belonging to a group. In the latter case, each agent that belongs to more than one group will include a mark (like `*`).

## Implementation

The user will define the shared configuration for shared groups in `etc/shared/(group)`, as usual. The agent group definition files at `queue/agent-groups/(id)` will contain one line with the dash-separated list of groups the agent belongs to. For instance:

```
default
WebServers-Databases
GroupA-GroupB-GroupC
```

There are two different options for agent group management:
- *Add* an agent to a group. This means keeping the existing group assignation.
- *Set* an agent to a group. This will overwrite the previous assignation.

When the manager creates a new multigroup combination (like `WebServers-Databases`), it will create the corresponding folder at `var/groups`, in this case, `var/groups/WebServers-Databases`.

Remoted is the component responsible for merging shared files for agents. From now on, it will scan `var/groups` to detect single-group and multi-group combinations, and it will create the corresponding file `merged.mg` based on the behavior above.

When Remoted has to deliver a shared file to an agent, it will send the file at `var/groups/(multigroup)/merged.mg`.

### Database

Two new tables will appear:
- `group` to enumerate each agent group.
- `belongs` to declare assignations between agents and groups.

On the other hand, since tables don't save the order, the column `agent.group` will include the multigroup assignation (e.g. `"WebServer-Database"`) to preserve order and find all the multi-group combinations.

**Comment by vikman90** [comment]
Working on branch [dev-multiple-groups](https://github.com/wazuh/wazuh/tree/dev-multiple-groups).

**Comment by TJOSERAFAEL** [comment]
This PR https://github.com/wazuh/wazuh/pull/1135 solves the issue

**Comment by TJOSERAFAEL** [comment]
Hi @vikman90 ,

### New options

For `agent_groups.py`
- **Add group to agent** -e -i agent_id -g group_id [-q]       

For `RESTful API`
- curl -u foo:bar -X PUT "http://localhost:55000/agents/004/add_group/webserver?pretty"

This is already documented here https://github.com/wazuh/wazuh-documentation/commits/dev-36-multigroups

**Comment by vikman90** [comment]
GJ @TJOSERAFAEL !!
Let's continue this discussion in the PR.
Thx!
