### ISSUE TITLE
Reportd and Log Rotation exploratory charter definition.

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#9202]
Branch
|--|
[9202-gen-reports-and-log-rotation-charter](https://github.com/wazuh/wazuh/tree/9202-gen-reports-and-log-rotation-charter)

## Description
The purpose of this issue is to identify the flow of functional tests to verify that nothing has been broken in the correct functioning of the monitord features.
Take into account the open issues of monitord.
https://github.com/wazuh/wazuh/labels/core%2Fmonitord

## Task
- [x] Identify and understand the flow of reportd and translate it into diagrams (if they exist, reuse them), based on the flow design manual tests, for the current use cases.
- [x] Identify and understand the flow of logrotation and translate it into diagrams (if they exist, reuse them), based on the flow design manual tests, for the current use cases.
- [x] Identify the common issues around this in the Wazuh community.
- [x] Post diagrams and briefly explanation in src/diagrams folder.
- [x] Set team meeting to explain the results.

Post the design test result in https://github.com/wazuh/wazuh/issues/8413
