### ISSUE TITLE
Agent disconnection handling and alerting charter definition.

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#9203]
## Description
The purpose of this issue is to identify the flow of functional tests to verify that nothing has been broken in the correct functioning of the monitord features.
Take into account the open issues of monitord.
https://github.com/wazuh/wazuh/labels/core%2Fmonitord

## Task
- [x] Identify the flow and translate it into diagrams, based on the flow design manual tests, for the current use cases.
- [x] Identify modifications in this branch, to locate flow to test. https://github.com/wazuh/wazuh/issues/5887
- [x] Identify the common issues around this in the Wazuh community.
- [x] Post diagrams and briefly explanation in src/diagrams folder.
- [ ] Set team meeting to explain the results.

Post the design test result in https://github.com/wazuh/wazuh/issues/8413
