### ISSUE TITLE
Improve the Vulnerability Detector and Syscollector modules to allow a manual scan executions

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#9220]
# Description

Currently, the Vulnerability Detector and Syscollector modules work scanning at intervals of time, and it isn't possible to perform a scan request to these modules.

The aim of this epic is to design and implement a mechanism that allows the users to manually trigger scans of both modules. This will enable the possibility of having quick knowledge of the vulnerabilities that affect an agent without waiting for the next scan.

The analysis of this issue began in #9219.

# High-Level Requirements

- [ ] The Wazuh UI should expose buttons in the individual agent views to trigger the scans.
- [ ] The scans should be capable of being triggered also using the Wazuh API.
- [ ] For the Vulnerability Detector module, we should also allow the user to trigger a feeds update.
- [ ] The Wazuh UI should expose information about the scans executed.
- [ ] In case of triggering both, Syscollector and Vulnerability Detector scans at the same time, the Vulnerability Detector scan should start after the Syscollector scan finalized the data synchronization.
- [ ] The Task Manager should be used to register and track the progress of all the scanning tasks.

# Design

## Syscollector scans

For the case of the Syscollector scans, we leverage the capabilities of the **AR forwarder**. This component already implements the capability of sending actions to be taken to the agents. With this, the implementation involves:

- The Wazuh API will register the tasks in the Task Manager and then, it will send a message to the agents by using the **AR forwarder** to trigger the scans.
- Modification of the **receiver** component to handle the new message that instructs the agent to start a Syscollector scan.
- Implement the trigger of the Syscollector scan when the message is handled by the **receiver** component.

**TO BE DEFINED:** After the Syscollector scan, when the synchronization of the data finalizes, the task registered in the task manager should be set as **DONE**. For doing this, there are two options that should be evaluated:

1. When a global integrity checksum is received and it matches with the one calculated by the manager, the Syscollector tasks in the Task Manager for this particular agent should be set as DONE.
2. When analysisd determines that he shouldn't trigger a data synchronization with the agent, the Syscollector tasks in the Task Manager for this particular agent should be set as DONE.

## Vulnerability Detector scans

For the Vulnerability Detector module, we decided to implement two threads:

- **Scheduler thread**: This thread is actually the main thread of the vulnerability detector module. It will be responsible of monitoring the intervals of feed updates and scans, and will implement the interaction with the task manager as well. For details on the design of this thread, check the next issue:
  - https://github.com/wazuh/wazuh/issues/12803
- **Worker thread**: This thread is the one responsible of executing all the feed updates and scanning tasks scheduled by the scheduler thread. For details on the design of this thread, check the next issue:
  - https://github.com/wazuh/wazuh/issues/12802

**Comment by davidjiglesias** [comment]
Partially done in https://github.com/wazuh/wazuh/issues/15002
