### ISSUE TITLE
Provision AWS wazuh-dev environment

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#9233]
Hello team,

We need to provision our AWS `Wazuh-dev` environment with buckets and logs for each of the buckets and services supported by our aws module, so they can be used by the team for future development and for automated testing. The data should be migrated from the wazuh prod environment. Configurations of services such as Cloudtrail or CloudwatchLogs should be taken into account.

## Tasks
- [x] Migrate data from S3 for each supported bucket type and services.
- [x] Review configurations for CloudTrail, CloudWatchLogs, VPC, Macie, EC2 and Elastic Container Service.
- [ ] Create a developer documentation explaining anything remarkable about the Wazuh-dev environment and its structure.

Regards,
Carlos

**Comment by CarlosRS9** [comment]
# Status update

We are currently migrating data from production environment to WAZUH-DEV.

The following buckets will be created in WAZUH-DEV:

```
wazuh-aws-wodle-cloudtrail
wazuh-aws-wodle-vpcflow
wazuh-aws-wodle-config
wazuh-aws-wodle-alb
wazuh-aws-wodle-clb
wazuh-aws-wodle-nlb
wazuh-aws-wodle-kms
wazuh-aws-wodle-macie
wazuh-aws-wodle-trusted_advisor
wazuh-aws-wodle-guardduty
wazuh-aws-wodle-waf
```

Each bucket will contain logs in their root folder as well as two different folders named `test_prefix/` and `test_empty/` that will be used by the automated tests. `test_prefix/` will contain additional logs.

Here is an example of a proposed bucket structure:

```
wazuh-aws-wodle-alb
    ÀWSLogs/
        ...
    test_prefix/
        AWSLogs/
            ...
    test_empty/
```

**Comment by CarlosRS9** [comment]
# Status update

Here is the progress of the log migration:

- [ ] wazuh-aws-wodle-cloudtrail
- [ ] wazuh-aws-wodle-vpcflow
- [ ] wazuh-aws-wodle-config
- [ ] wazuh-aws-wodle-alb
    351 files (158 kb)
- [ ] wazuh-aws-wodle-clb
- [ ] wazuh-aws-wodle-nlb
- [ ] wazuh-aws-wodle-kms
- [ ] wazuh-aws-wodle-macie
- [ ] wazuh-aws-wodle-trusted_advisor
- [ ] wazuh-aws-wodle-guardduty
- [ ] wazuh-aws-wodle-waf

**Comment by CarlosRS9** [comment]
# Status update

We have review the configuration of our supported services in production environment to determine if something needed to be migrated to. Here are the conclusions:

**CloudwatchLogs:**
A log group was created along with 4 log streams and some logs:
```
framework-test-apache
|-- test-logstream-1
|-- test-logstream-2
|-- awslogs-example-alt/apache/86564f94930149f0a54309cfa49ef735
|-- awslogs-multi-line/apache/86564f94930149f0a00000cfa49ef000
```

**Cloudtrail:**
We don't currently have to enable any trail as we already have enough logs to be able to test current and future developments related with CloudTrail. Trails will be enabled in the future if necessary.

**VPC**
Any configuration related to VPC and VPC endpoints this will be performed in #8761 as we are working on this new feature. There is nothing of note in the production environment that needs to be migrated

**Other services and configurations**
We have not found anything remarkable that we should export from the production environment in terms of EC2, ECS, Macie or Trusted advisor.

## Next steps

The only task remaining is to write the development documentation explaining the structure and relevant elements of wazuh-dev environment
