### ISSUE TITLE
Analyze and test how much memory Execd occupies

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#9255]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.0-RC10 | Execd | Agent | Sources | ALL |

## Goal

Find out how much memory the component might take.

## Summary

The main task of the execd daemon is to receive execution commands. The requests are of 2 types:
- with timeout
- without timeout

Requests are always executed as a new process (`fork()` + `execvp()`).
No historical information is stored for a command without timeout. (Stateless)
For commands with timeout only information is stored for re-execution after the time has expired.

#### Description
1 command is sent every 2 seconds, 5 times.
Wait 10 seconds and 10 commands are sent.
#### Purpose
Verify memory retrieval and memory management

### Massif report: 

![execd_wo_test1](https://user-images.githubusercontent.com/1891958/126833001-1bb52833-125b-4395-b156-54ceb71ceff3.png)
[massif.out.wo_to.zip](https://github.com/wazuh/wazuh/files/6870977/massif.out.wo_to.zip)

The results, in addition to being as expected, are acceptable.
- 1: The peak is due to the loading of the XML for the module configuration read.
- 2-3-4-5: Processing of the commands requested to execute (Separated every 2 seconds). Memory is restored quickly.
- 6: Sleep time
- 7: Processing and execution of burst sent commands.

After the tests are finished, the memory returns to the initial state.

#### Description
A command with timeout is sent and wait unit the timeout expires.
Then a command with timeout is sent again and the sending is repeated before the timeout expires. Finally we wait for the timeout

#### Purpose
Verify memory retrieval and memory management

### Massif report: 

![execd_w_test2](https://user-images.githubusercontent.com/1891958/126836320-b4813862-c3ea-4c61-aa14-a0b89d714922.png)
[massif.out.w_to.zip](https://github.com/wazuh/wazuh/files/6871014/massif.out.w_to.zip)

The results, in addition to being as expected, are acceptable.

- 1: The peak is due to the loading of the XML for the module configuration read.
- 2: Processing of the command requested to execute
- 3: Timeout time.
- 4: Processing of the command to execute due to timeout
- 5: Sleep time
- 6: Time between the execution of a command and its timeout
- 7: Attempt to execute 2 commands that have already been executed and cannot be executed. These update the time of the timeout, so `*6` is greater than `*3`.

After the tests are finished, the memory returns to its initial state.

# Tasks

Explain with diagrams and descriptions in markdown files, and put it in the wazuh / architecture directory an explanation of the operation and calculations of how much the peak(stressed) and post-peak consumption would be left in memory in standby.

- [x] [Create functionality diagrams](https://github.com/wazuh/wazuh/issues/9255#issuecomment-892401893)
- [x] [Create feature description](https://github.com/wazuh/wazuh/issues/9255#issue-942133087)
- [x] [Analyze resources consumption](https://github.com/wazuh/wazuh/issues/9255#issuecomment-891328278)
- [x] [Performance conclusions of comparing Wazuh 4.2.0 with 4.1.5](https://github.com/wazuh/wazuh/issues/9255#issuecomment-886322027)
- [x] [Further tests to develop](https://github.com/wazuh/wazuh/issues/9255#issuecomment-886323901)

**Comment by nmkoremblum** [comment]
Hi Team!

Here is a brief of the evaluation we have done so far:

 ## Manager CentOS
  |Measure|Status|Comment|
  |---|---|---|
  | CPU average use (%) | 🟢 | 4.2.0 uses a little more CPU (~3% relative increase) |
  | Disk average use (%) | 🟢 | 4.2.0 uses almost no disk (results throw 0%) |
  | Disk_Read | 🟢 | 4.2.0 does not read from disk (results throw 0%) |
  | Disk_Written | 🟡 | 4.2.0 writes ~14% more data to disk than 4.1.5 (from 56 to 64 MB) |
  | Write_Ops | 🟡 | 4.2.0 writes ~50% more times to disk than 4.1.5 (from 2000 to 3000 times) |
  | Read_Ops | 🟢 |  Similar usage in 4.1.5 and 4.2.0 |
  | FD | 🟢 | 4.2.0 uses 4 more FDs |
  | RSS | 🟢 | 4.2.0 uses ~13% more RSS than 4.1.5 (from 1500 to 1650 KB) |
  | SWAP | 🟡 | Empty graph. Is the test broken? |
  | USS | 🟢 | 4.2.0 uses ~10% less USS than 4.1.5 |
  | PSS | 🟢 | 4.2.0 uses ~6% less PSS than 4.1.5 |
  | VMS | 🟢 | Similar usage in 4.1.5 and 4.2.0 |
  
   ## Windows Agent
  |Measure|Status|Comment|
  |---|---|---|
  | CPU average use (%) | :red_circle: | 4.2.0 uses ~600% more CPU than 4.1.5 (from 1 to 7%) |
  | Disk average use (%) | 🟢 | 4.2.0 uses ~43% more disk than 4.1.5 (from 0.7 to 1%) |
  | Disk_Read | 🟢 | 4.2.0 reads a bit more from disk than 4.1.5 (from 27 to 28 MB) |
  | Disk_Written | :red_circle: | 4.2.0 writes ~20.000% more data to disk than 4.1.5 (from 0.16 to 29.33 MB) |
  | Write_Ops | :red_circle: | 4.2.0 writes ~14.000% more times to disk than 4.1.5 (from 900 to 130.000 times) |
  | Read_Ops | 🟢 | Similar usage in 4.1.5 and 4.2.0 |
  | FD | 🟢 | Similar usage in 4.1.5 and 4.2.0 |
  | RSS | 🟢 | Similar usage in 4.1.5 and 4.2.0 |
  | SWAP | 🟡 | Empty graph. Is the test broken? |
  | USS | 🟢 | Similar usage in 4.1.5 and 4.2.0 |
  | PSS | 🟡 | No data |
  | VMS | 🟢 | 4.2.0 uses ~18% more VMS than 4.1.5 (from 5500 to 6500 KB) |
  
   ## Ubuntu agent
  |Measure|Status|Comment|
  |---|---|---|
  | CPU average use (%) | 🟢 | Similar results in 4.1.5 and 4.2.0 |
  | Disk average use (%) | 🟢 | Similar results in 4.1.5 and 4.2.0 |
  | Disk_Read | 🟢 | Similar results in 4.1.5 and 4.2.0 |
  | Disk_Written | 🟡 | 4.2.0 writes ~12% more data to disk than 4.1.5 (from 50 to 60 MB) |
  | Write_Ops | 🟡 | 4.2.0 writes ~50% more times to disk than 4.1.5 (from 1900 to 2900 times) |
  | Read_Ops | 🟢 | Similar results in 4.1.5 and 4.2.0 |
  | FD | 🟢 | 4.2.0 uses 2 more FDs than 4.1.5 |
  | RSS | 🟡 | 4.2.0 uses ~25% more RSS than 4.1.5 (from 2900 to 3700 KB) |
  | SWAP | 🟡 | Empty graph. Is the test broken? |
  | USS | 🟡 | 4.2.0 uses ~8% more USS than 4.1.5 (from 1200 to 1300 KB) |
  | PSS | 🟡 | 4.2.0 uses ~20% more PSS than 4.1.5 (from 1300 to 1550 KB) |
  | VMS | 🟢 | Similar results in 4.1.5 and 4.2.0 |
  
 Best Regards,
 
 Mariano Koremblum

**Comment by nmkoremblum** [comment]
# Manager (CentOS) 4.2 VS 4.1.5

Wazuh Version |4.2 | 4.1.5 | ( [4.2] / [4.1.5] - 1 ) * 100
-- | -- | --  | --
CPU Average (%) | 0.46 | 0.44 | 2.81%
CPU Median (%)  | 0.00 | 0.00 | ---
CPU Max (%) | 19.70 | 19.50 | 1.03%
RSS Average (KB) | 1649.76 | 1487.38 | 10.92%
RSS Median (KB) | 1680.00 | 1492.00 | 12.60%
RSS Max (KB) | 1680.00 | 1492.00 | 12.60%
VMS Average (KB) | 33057.81 | 33144.00 | -0.26%
VMS Median (KB) |  33064.00 | 33144.00 | -0.24%
VMS Max (KB) | 33068.00 | 33144.00 | -0.23%
FD Average | 7.00 | 5.00 | 40.01%
FD Median | 7.00 | 5.00 | 40.01%
FD Max | 9.00 | 5.00 | 80.00%
Read_Ops Average | 24722.34 | 24660.65 | 0.25%
Read_Ops Median | 27175.00 | 27175.00 | 0%
Read_Ops Max | 27391.00 | 27283.00 | 0.40%
Write_Ops Average | 2753.94 | 1830.52 | 50.45%
Write_Ops Median | 3027.00 | 2017.00 | 50.07%
Write_Ops Max | 3051.00 | 2025.00 | 50.67%
Disk_Read (MB) Average |  0.00 | 22.03 | ---
Disk_Read (MB) Median | 0.00 | 24.00 | ---
Disk_Read (MB) Max |  0.00 | 24.00 | ---
Disk_Written (MB) Average | 48.68 | 44.33 | 9.80%
Disk_Written (MB) Median | 52.00 | 48.00 | 8.33%
Disk_Written (MB) Max | 64.00 | 56.00 | 14.29%
Disk (%) Average | 0.00 | 0.01 | ---
Disk (%) Median |  0.00 | 0.01 | ---
Disk (%) Max | 0.00 | 0.01 | ---
USS (KB) Average | 884.82 | 978.42 | -9.57%
USS (KB) Median | 888.00 | 980.00 | -9.39%
USS (KB) Max | 888.00 | 980.00 | -9.39%
PSS (KB) Average | 932.86 | 996.33 | -6.37%
PSS (KB) Median | 939.00 | 998.00 | -5.91%
PSS (KB) Max | 939.00 | 998.00 | -5.91%

**Comment by nmkoremblum** [comment]
# Ubuntu Agent 4.2 VS 4.1.5

Wazuh Version |4.2 | 4.1.5 | ( [4.2] / [4.1.5] - 1 ) * 100
-- | -- | --  | --
CPU Average (%) | 0.62 | 0.64 | -3.23%
CPU Median (%)  | 0.00 | 0.00 | ---
CPU Max (%) | 19.80 | 19.30 | 2.59%
RSS Average (KB) | 3688.20 | 2934.27 | 25.69%
RSS Median (KB) | 3776.00 | 2952.00 | 27.91%
RSS Max (KB) | 3776.00 | 2952.00 | 27.91%
VMS Average (KB) | 22297.14 | 21996.00 | 1.37%
VMS Median (KB) |  22304.00 | 21996.00 | 1.40%
VMS Max (KB) |  22304.00 | 21996.00 | 1.40%
FD Average | 7.00 | 7.00 | 0%
FD Median | 7.00 | 7.00 | 0%
FD Max | 9.00 | 7.00 | 28.57%
Read_Ops Average | 35743.24 | 35657.50 | 0.24%
Read_Ops Median | 39456.00 | 38696.00 | 1.96%
Read_Ops Max | 40672.00 | 40672.00 | 0%
Write_Ops Average | 2829.31 | 1883.58 | 50.21%
Write_Ops Median | 3123.00 | 2044.00 | 52.79%
Write_Ops Max | 3219.00 | 2148.00 | 49.86%
Disk_Read (MB) Average |  0.00 | 0.00 | ---
Disk_Read (MB) Median | 0.00 | 00.00 | ---
Disk_Read (MB) Max |  0.00 | 00.00 | ---
Disk_Written (MB) Average | 58.29 | 49.87 | 16.87%
Disk_Written (MB) Median | 64.00 | 48.00 | 33.33%
Disk_Written (MB) Max | 76.00 | 68.00 | 11.76%
Disk (%) Average | 0.01 | 0.00 | ---
Disk (%) Median |  0.01 | 0.00 | ---
Disk (%) Max | 0.01 | 0.00 | ---
USS (KB) Average | 1311.87 | 1217.62 | 7.74%
USS (KB) Median | 1316.00 | 1220.00 | 7.87%
USS (KB) Max | 1316.00 | 1220.00 | 7.87%
PSS (KB) Average | 1546.80 | 1290.27 | 19.88%
PSS (KB) Median | 1565.00 | 1292.00 | 21.13%
PSS (KB) Max | 1565.00 | 1292.00 | 21.13%

**Comment by nmkoremblum** [comment]
# Windows Agent 4.2 VS 4.1.5

Wazuh Version |4.2 | 4.1.5 | ( [4.2] / [4.1.5] - 1 ) * 100
-- | -- | --  | --
CPU Average (%) | 6.72 | 1.00 | 571.21%
CPU Median (%)  | 0.00 | 0.00 | ---
CPU Max (%) | 87.50 | 28.70 | 204.88%
RSS Average (KB) | 12333.32 | 11922.60 | 3.44%
RSS Median (KB) | 12012.00 | 11960.00 | 0.43%
RSS Max (KB) | 13180.00 | 12032.00 | 9.54%
VMS Average (KB) | 6474.30 | 5475.60 | 18.24%
VMS Median (KB) |  6668.00 | 5488.00 | 21.50%
VMS Max (KB) |  6716.00 | 5604.00 | 19.84%
FD Average | 248.57 | 236.87 | 4.94%
FD Median | 249.00 | 238.00 | 4.62%
FD Max | 252.00 | 240.00 | 5.00%
Read_Ops Average | 7703.01 | 7330.21 | 5.09%
Read_Ops Median | 7772.00 | 7030.00 | 10.55%
Read_Ops Max | 14702.00 | 14884.000 | -1.22%
Write_Ops Average | 66634.73 | 515.54 | 12825.14%
Write_Ops Median | 67342.00 | 521.00 | 12825.53%
Write_Ops Max | 128302.00 | 935.00 | 13622.14%
Disk_Read (MB) Average |  28.29 | 27.07 | 4.50%
Disk_Read (MB) Median | 28.55 | 25.94 | 10.06%
Disk_Read (MB) Max |  54.69 | 55.56 | -1.57%
Disk_Written (MB) Average | 29.33 | 0.16 | 18369.29%
Disk_Written (MB) Median | 29.66 | 0.16 | 18715.41%
Disk_Written (MB) Max | 56.21 | 0.20 | 28611.07%
Disk (%) Average | 1.00 | 0.70 | 43.16%
Disk (%) Median |  1.03 | 0.70 | 46.87%
Disk (%) Max | 1.81 | 1.28 | 41.63%
USS (KB) Average | 7195.40 | 6932.44 | 3.79%
USS (KB) Median | 6800.00 | 6968.00 | -2.41%
USS (KB) Max | 8144.00 | 7040.00 | 15.68%

**Comment by nmkoremblum** [comment]
# Windows Agent 4.2 VS 4.1.5 UPDATED

Wazuh Version |4.2 | 4.1.5 | ( [4.2] / [4.1.5] - 1 ) * 100
-- | -- | --  | --
CPU Average (%) | 1.65 | 0.87 | 90.03%
CPU Median (%)  | 0.00 | 0.00 | ---
CPU Max (%) | 57.30 | 57.30 | 16.06%
RSS Average (KB) | 12798.24 | 11511.61 | 11.18%
RSS Median (KB) | 12896.00 | 11848.00 | 8.85%
RSS Max (KB) | 12908.00 | 11928.00 | 8.22%
VMS Average (KB) | 6276.52 | 5479.56 | 14.54%
VMS Median (KB) |  6436.00 | 5516.00 | 16.68%
VMS Max (KB) |  6524.00 | 5576.00 | 17.00%
FD Average | 250.52 | 237.68 | 5.40%
FD Median | 252.00 | 239.00 | 5.44%
FD Max | 254.00 | 243.00 | 4.53%
Read_Ops Average | 7778.71 | 7588.06 | 2.51%
Read_Ops Median | 7778.00 | 7492.00 | 3.82%
Read_Ops Max | 14477.00 | 14884.00 | -2.73%
Write_Ops Average | 1000.89 | 517.77 | 93.31%
Write_Ops Median | 1039.50 | 527.00 | 97.25%
Write_Ops Max | 1528.00 | 937.00 | 63.07%
Disk_Read (MB) Average |  28.56 | 28.04 | 1.85%
Disk_Read (MB) Median | 28.56 | 27.68 | 3.18%
Disk_Read (MB) Max |  53.83 | 55.56 | -3.12%
Disk_Written (MB) Average | 0.38 | 0.16 | 135.46%
Disk_Written (MB) Median | 0.39 | 0.16 | 148.05%
Disk_Written (MB) Max | 0.45 | 0.20 | 129.59%
Disk (%) Average | 1.92 | 1.64 | 17.26%
Disk (%) Median |  1.92 | 1.62 | 18.68%
Disk (%) Max | 3.57 | 3.20 | 11.46%
USS (KB) Average | 7834.22 | 6527.73 | 20.01%
USS (KB) Median | 7928.00 | 6900.00 | 14.90%
USS (KB) Max | 7940.00 | 6988.00 | 13.62%

**Comment by JcabreraC** [comment]
There is a problem whereby Active Responses are not correctly stored in the timeout list on the agents. 

All this is detailed in the following issue: https://github.com/wazuh/wazuh/issues/9370

**Comment by nmkoremblum** [comment]
## Performance conclusions of comparing Wazuh 4.2.0 with 4.1.5

As part of Wazuh's modernization and improvement process, this module has had a lot of code rework. In general terms, the increase of use of resources is not worrisome and, as said before, comes hand in hand with the module's enhancements.

**Comment by nmkoremblum** [comment]
## Further tests to develop

Only short-time two-AR triggering, one with timeout and one without it, stress tests were performed. It would be nice to have long-time stress tests with many different ARs, mixing options such as timeout and repeated offenders with multiple and different triggering events. Other aspects of the module should be also tested, as for example client upgrading.

**Comment by nmkoremblum** [comment]
## New measurements,  after the [fix of the ARs](https://github.com/wazuh/wazuh/pull/9407/files) was merged to 4.2

### Manager CentOS
  |Measure|Status|Comment|
  |---|---|---|
  | CPU average use (%) | 🟢 | 4.2.0 uses a little less CPU (~6% relative decrease) |
  | Disk average use (%) | 🟢 | 4.2.0 uses almost no disk (results throw 0%) |
  | Disk_Read | 🟢 | 4.2.0 does not read from disk (results throw 0%) |
  | Disk_Written | 🟢 | Similar usage in 4.1.5 and 4.2.0 |
  | Write_Ops | 🟢 | 4.2.0 writes ~50% more times to disk than 4.1.5 (from 2000 to 3000 times) |
  | Read_Ops | 🟢 |  Similar usage in 4.1.5 and 4.2.0 |
  | FD | 🟢 | 4.2.0 uses 4 more FDs |
  | RSS | 🟢 | 4.2.0 uses ~10% more RSS than 4.1.5 (from 1500 to 1650 KB) |
  | SWAP | 🟡 | Empty graph. Is the test broken? |
  | USS | 🟢 | 4.2.0 uses ~8% less USS than 4.1.5 |
  | PSS | 🟢 | 4.2.0 uses ~4% less PSS than 4.1.5 |
  | VMS | 🟢 | Similar usage in 4.1.5 and 4.2.0 |
  
### Windows Agent
  |Measure|Status|Comment|
  |---|---|---|
  | CPU average use (%) | 🟢 | 4.2.0 uses, on average, ~300% more CPU than 4.1.5 (from 1 to 4%), but the median is about 0% |
  | Disk average use (%) | 🟢 | 4.2.0 uses ~73% more disk than 4.1.5 (from 1.6 to 3%) |
  | Disk_Read | 🟢 | 4.2.0 reads a bit more data from disk than 4.1.5 (from 28 to 29 MB) |
  | Disk_Written | 🟢 | 4.2.0 writes ~110% more data to disk than 4.1.5 (from 0.16 to 0.34 MB) |
  | Write_Ops | 🟢 | 4.2.0 writes ~54% more times to disk than 4.1.5 (from 900 to 1400 times) |
  | Read_Ops | 🟢 | Similar usage in 4.1.5 and 4.2.0 |
  | FD | 🟢 | Similar usage in 4.1.5 and 4.2.0 |
  | RSS | 🟢 | 4.2.0 uses a bit more RSS than 4.1.5 (from 11.5 to 13 MB) |
  | SWAP | 🟡 | Empty graph. Is the test broken? |
  | USS | 🟢 | 4.2.0 uses ~22% more USS than 4.1.5 (from 6.5 to 8 MB) |
  | PSS | 🟡 | No data |
  | VMS | 🟢 | 4.2.0 uses ~18% more VMS than 4.1.5 (from 5.5 to 6.5 MB) |
  
### Ubuntu agent
  |Measure|Status|Comment|
  |---|---|---|
  | CPU average use (%) | 🟢 | 4.2.0 uses, on average, ~300% more CPU than 4.1.5 (from 0.6 to 2.5%), but the median is about 0% |
  | Disk average use (%) | 🟢 | Similar results in 4.1.5 and 4.2.0 (0%) |
  | Disk_Read | 🟢 | Similar results in 4.1.5 and 4.2.0 (0%) |
  | Disk_Written | 🟢 | 4.2.0 writes ~80% less data to disk than 4.1.5 |
  | Write_Ops | 🟡 | 4.2.0 writes ~1800% more times to disk than 4.1.5 (from 2.200 to 42.000 times) |
  | Read_Ops | 🟢 | 4.2.0 reads ~40% less times to disk than 4.1.5 |
  | FD | 🟢 | 4.2.0 uses 4 more FDs than 4.1.5 |
  | RSS | 🟢 | 4.2.0 uses ~21% more RSS than 4.1.5 (from 2.9 to 3.5 MB) |
  | SWAP | 🟡 | Empty graph. Is the test broken? |
  | USS | 🟢 | Similar results in 4.1.5 and 4.2.0 (0%) |
  | PSS | 🟡 | 4.2.0 uses ~13% more PSS than 4.1.5 (from 1.3 to 1.5 MB) |
  | VMS | 🟢 | 4.2.0 uses ~15% less RSS than 4.1.5 |

**Comment by nmkoremblum** [comment]
# Manager (CentOS) 4.2 (AFTER ARs FIX) VS 4.1.5

Wazuh Version | 4.2 | 4.1.5 | ( [4.2] / [4.1.5] - 1 ) * 100
-- | -- | --  | --
CPU Average (%) | 0.42 | 0.44 | -6.14%
CPU Median (%)  | 0.00 | 0.00 | ---
CPU Max (%) | 19.60 | 19.50 | 0.51%
RSS Average (KB) | 1628.77 | 1487.38 | 9.47%
RSS Median (KB) | 1656.00 | 1492.00 | 10.99%
RSS Max (KB) | 1656.00 | 1492.00 | 10.99%
VMS Average (KB) | 32602.27 | 33144.00 | -1.63%
VMS Median (KB) |  32608.00 | 33144.00 | -1.62%
VMS Max (KB) | 32612.00 | 33144.00 | -1.61%
FD Average | 7.00 | 5.00 | 40.01%
FD Median | 7.00 | 5.00 | 40.01%
FD Max | 9.00 | 5.00 | 80.00%
Read_Ops Average | 24971.18 | 24660.65 | 0.35%
Read_Ops Median | 27227.00 | 27175.00 | 0.19%
Read_Ops Max | 27335.00 | 27283.00 | 0.19%
Write_Ops Average | 2781.88 | 1830.52 | 50.61%
Write_Ops Median | 3033.00 | 2017.00 | 50.37%
Write_Ops Max | 3045.00 | 2025.00 | 50.37%
Disk_Read (MB) Average |  0.00 | 22.03 | ---
Disk_Read (MB) Median | 0.00 | 24.00 | ---
Disk_Read (MB) Max |  0.00 | 24.00 | ---
Disk_Written (MB) Average | 45.14 | 44.33 | 1.01%
Disk_Written (MB) Median | 48.00 | 48.00 | 0%
Disk_Written (MB) Max | 56.00 | 56.00 | 0%
Disk (%) Average | 0.00 | 0.01 | ---
Disk (%) Median |  0.00 | 0.01 | ---
Disk (%) Max | 0.00 | 0.01 | ---
USS (KB) Average | 907.66 | 978.42 | -7.24%
USS (KB) Median | 912.00 | 980.00 | -6.94%
USS (KB) Max | 912.00 | 980.00 | -6.94%
PSS (KB) Average | 955.32 | 996.33 | -4.13%
PSS (KB) Median | 962.00 | 998.00 | -3.61%
PSS (KB) Max | 962.00 | 998.00 | -3.61%

![chart(11)](https://user-images.githubusercontent.com/75255206/127928412-d18f278d-2fda-4988-996e-48120891ce43.png)
![chart(10)](https://user-images.githubusercontent.com/75255206/127928438-56d72cb8-4c04-42dc-a435-d5098e371723.png)
![chart(9)](https://user-images.githubusercontent.com/75255206/127928443-933bce45-4201-4bc1-bcc3-46e261bfaaa7.png)
![chart(8)](https://user-images.githubusercontent.com/75255206/127928447-a4504818-a8d1-4feb-bb41-83f8ebd59903.png)
![chart(7)](https://user-images.githubusercontent.com/75255206/127928450-9471fcb9-110e-433b-8ced-cf664e23b650.png)
![chart(6)](https://user-images.githubusercontent.com/75255206/127928453-52320480-f4ac-4d1b-a8ea-4d84f49782ec.png)
![chart(5)](https://user-images.githubusercontent.com/75255206/127928460-76181674-ccc9-4915-9607-25a1000a2cbc.png)
![chart(4)](https://user-images.githubusercontent.com/75255206/127928465-a3508627-5596-4666-a627-5fc1d4c4d964.png)
![chart(3)](https://user-images.githubusercontent.com/75255206/127928470-e228ca0c-c782-4741-beae-c670902cec84.png)
![chart(2)](https://user-images.githubusercontent.com/75255206/127928472-e618aa08-8b0b-4286-bf7b-840a082aba74.png)
![chart(1)](https://user-images.githubusercontent.com/75255206/127928473-41f78448-7a42-44c6-ba3f-dc8e6a5fd9a8.png)
![chart](https://user-images.githubusercontent.com/75255206/127928476-edb4e523-1723-4f2d-8ba9-e1a6e067b8f3.png)

**Comment by nmkoremblum** [comment]
# Ubuntu Agent 4.2 (AFTER ARs FIX) VS 4.1.5

Wazuh Version |4.2 | 4.1.5 | ( [4.2] / [4.1.5] - 1 ) * 100
-- | -- | --  | --
CPU Average (%) | 2.48 | 0.64 | 288.83%
CPU Median (%)  | 0.00 | 0.00 | ---
CPU Max (%) | 19.80 | 19.30 | 2.59%
RSS Average (KB) | 3535.23 | 2934.27 | 20.48%
RSS Median (KB) | 3624.00 | 2952.00 | 22.76%
RSS Max (KB) | 3624.00 | 2952.00 | 22.76%
VMS Average (KB) | 18712.52 | 21996.00 | -14.93%
VMS Median (KB) |  18720.00 | 21996.00 | -14.89%
VMS Max (KB) |  18720.00 | 21996.00 | -14.89%
FD Average | 7.07 | 7.00 | 1.03%
FD Median | 7.00 | 7.00 | 0%
FD Max | 11.00 | 7.00 | 57.14%
Read_Ops Average | 21912.03 | 35657.50 | -38.55%
Read_Ops Median | 22007.00 | 38696.00 | -43.13%
Read_Ops Max | 41990.00 | 40672.00 | 3.24%
Write_Ops Average | 21909.61 | 1883.58 | 1063.19%
Write_Ops Median | 22005.00 | 2044.00 | 976.57%
Write_Ops Max | 41988.00 | 2148.00 | 1854.75%
Disk_Read (MB) Average |  0.00 | 0.00 | ---
Disk_Read (MB) Median | 0.00 | 00.00 | ---
Disk_Read (MB) Max |  0.00 | 00.00 | ---
Disk_Written (MB) Average | 11.66 | 49.87 | -76.62%
Disk_Written (MB) Median | 12.00 | 48.00 | -75.00%
Disk_Written (MB) Max | 12.00 | 68.00 | -82.35%
Disk (%) Average | 0.01 | 0.00 | ---
Disk (%) Median |  0.01 | 0.00 | ---
Disk (%) Max | 0.01 | 0.00 | ---
USS (KB) Average | 1213.02 | 1217.62 | -0.38%
USS (KB) Median | 1244.00 | 1220.00 | 1.97%
USS (KB) Max | 1244.00 | 1220.00 | 1.97%
PSS (KB) Average | 1463.00 | 1290.27 | 13.39%
PSS (KB) Median | 1501.00 | 1292.00 | 16.18%
PSS (KB) Max | 1501.00 | 1292.00 | 16.18%

![chart(11)](https://user-images.githubusercontent.com/75255206/127929317-cd064986-c700-4982-a620-88be291aedca.png)
![chart(10)](https://user-images.githubusercontent.com/75255206/127929320-58d8517d-2404-4541-8fb1-f2b261e0347f.png)
![chart(9)](https://user-images.githubusercontent.com/75255206/127929322-bd422619-ee45-4f32-9f74-911ec1e42422.png)
![chart(8)](https://user-images.githubusercontent.com/75255206/127929324-ce37a6f3-0800-4d09-99d3-4ed3e121411c.png)
![chart(7)](https://user-images.githubusercontent.com/75255206/127929327-5360c81d-b0c1-4b3c-b093-7d8a2cdfed39.png)
![chart(6)](https://user-images.githubusercontent.com/75255206/127929328-5fd9ae6d-f1e8-4b65-8840-16c03a04ce88.png)
![chart(5)](https://user-images.githubusercontent.com/75255206/127929329-9a1e4902-c04d-493f-bbee-03d3c88da60e.png)
![chart(4)](https://user-images.githubusercontent.com/75255206/127929330-5edb9cc3-1031-43d6-9973-865274e38c95.png)
![chart(3)](https://user-images.githubusercontent.com/75255206/127929332-c12c06d6-2c69-49fa-b9cc-34eb0ab868b1.png)
![chart(2)](https://user-images.githubusercontent.com/75255206/127929334-2c3a2821-9378-48ac-baf8-90f4fb03542d.png)
![chart(1)](https://user-images.githubusercontent.com/75255206/127929336-0fe40c85-e4b9-4c4d-8645-75c94c5ca013.png)
![chart](https://user-images.githubusercontent.com/75255206/127929339-a1638eb4-686a-42cf-9dec-1e0618fafcf2.png)

**Comment by nmkoremblum** [comment]
# Windows Agent 4.2 (AFTER ARs FIX) VS 4.1.5

Wazuh Version |4.2 | 4.1.5 | ( [4.2] / [4.1.5] - 1 ) * 100
-- | -- | --  | --
CPU Average (%) | 3.68 | 0.87 | 323.18%
CPU Median (%)  | 0.00 | 0.00 | ---
CPU Max (%) | 86.00 | 57.30 | 50.09%
RSS Average (KB) | 12945.04 | 11511.61 | 12.45%
RSS Median (KB) | 13132.00 | 11848.00 | 10.84%
RSS Max (KB) | 13264.00 | 11928.00 | 11.20%
VMS Average (KB) | 6499.80 | 5479.56 | 18.62%
VMS Median (KB) |  6496.00 | 5516.00 | 17.77%
VMS Max (KB) |  6808.00 | 5576.00 | 22.09%
FD Average | 250.52 | 237.68 | 5.40%
FD Median | 252.00 | 239.00 | 5.44%
FD Max | 256.00 | 243.00 | 5.35%
Read_Ops Average | 7993.68 | 7588.06 | 5.35%
Read_Ops Median | 8075.00 | 7492.00 | 7.78%
Read_Ops Max | 15065.00 | 14884.00 | 1.22%
Write_Ops Average | 924.00 | 517.77 | 78.46%
Write_Ops Median | 953.00 | 527.00 | 80.83%
Write_Ops Max | 1444.00 | 937.00 | 54.11%
Disk_Read (MB) Average |  29.13 | 28.04 | 3.86%
Disk_Read (MB) Median | 29.43 | 27.68 | 6.31%
Disk_Read (MB) Max |  55.56 | 55.56 | 0.00%
Disk_Written (MB) Average | 0.34 | 0.16 | 112.33%
Disk_Written (MB) Median | 0.36 | 0.16 | 123.32%
Disk_Written (MB) Max | 0.41 | 0.20 | 109.70%
Disk (%) Average | 2.83 | 1.64 | 73.11%
Disk (%) Median |  2.87 | 1.62 | 77.33%
Disk (%) Max | 5.31 | 3.20 | 65.83%
USS (KB) Average | 7967.71 | 6527.73 | 22.06%
USS (KB) Median | 8164.00 | 6900.00 | 18.32%
USS (KB) Max | 8296.00 | 6988.00 | 18.72%

![CPU(%)](https://user-images.githubusercontent.com/75255206/127930234-1a0f8f2c-6ff3-4ab3-ad4a-8f7627c61c3d.png)
![chart(9)](https://user-images.githubusercontent.com/75255206/127930236-68818961-ad25-42b6-84ca-a6db5a876ca5.png)
![chart(8)](https://user-images.githubusercontent.com/75255206/127930237-dad933d2-9f0f-41de-846c-e6e8ce7a44ce.png)
![chart(7)](https://user-images.githubusercontent.com/75255206/127930238-f653e347-ad53-4543-b532-e384ecbce313.png)
![chart(6)](https://user-images.githubusercontent.com/75255206/127930239-309026a4-c299-4f09-bda3-4d7af18fa299.png)
![chart(5)](https://user-images.githubusercontent.com/75255206/127930240-377b3da2-7f63-4996-a463-6438f9ba5f6c.png)
![chart(4)](https://user-images.githubusercontent.com/75255206/127930242-d6e2e9c2-79a7-47e6-ba09-6c5b2c4e7123.png)
![chart(3)](https://user-images.githubusercontent.com/75255206/127930245-ea779a49-c9f2-4f36-8e12-fa3da3907bf4.png)
![chart(2)](https://user-images.githubusercontent.com/75255206/127930246-f235314a-a686-43fe-a319-bbfdf8a617f3.png)
![chart(1)](https://user-images.githubusercontent.com/75255206/127930248-38919c7b-04c8-4eae-9848-318b28738bd5.png)
![chart](https://user-images.githubusercontent.com/75255206/127930250-4a48ec32-d667-42f4-999a-ee3a3ca4da85.png)

**Comment by nmkoremblum** [comment]
## Execd Flow diagram

The following diagram briefly describes how the module handles the ARs requests

![execd_diagram](https://user-images.githubusercontent.com/75255206/128132630-51de6648-d3b7-41b8-8a79-4640136733dd.png)
