### ISSUE TITLE
Analyze and test how much memory FIM occupies

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#9256]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.0-RC10 | FIM | Agent | Sources | ALL |

## Goal

Find out how much memory the component might take.

## Components that take a variable amount of memory

- File Internals buffers.
- Cache
- Peak in internals queues.

## Test conditions

- The agent shall be connected to a manager (real or fake).
- Use a buffer with a default value (5.000 events).
- Decrease the out throughput if necessary.
- Modify 200 files with 64kb lines quickly.
- After the stressing stage, leave the agent idle for 10 minutes (at less).
- 
# Tasks

Explain with diagrams and descriptions in markdown files, and put it in the wazuh / architecture directory an explanation of the operation and calculations of how much the peak(stressed) and post-peak consumption would be left in memory in standby.

- [x] [Create feature description](https://github.com/wazuh/wazuh/issues/9256#issuecomment-885714405)
- [x] [Create functionality diagrams](https://github.com/wazuh/wazuh/issues/9256#issuecomment-889033260)
- [x] Analyze resources consumption: [massif](https://github.com/wazuh/wazuh/issues/9256#issuecomment-885714405), [24hs test](https://github.com/wazuh/wazuh/issues/9256#issuecomment-891977853)
- [x] [Performance conclusions of comparing Wazuh 4.2.0 with 4.1.5](https://github.com/wazuh/wazuh/issues/9256#issuecomment-885877169)
- [x] [Further tests to develop](https://github.com/wazuh/wazuh/issues/9256#issuecomment-885888408)

**Comment by juliancnn** [comment]
MASSIF
In progress...

**Comment by JcabreraC** [comment]
# Manager CentOS
  |Measure|Status|Comment|
  |---|---|---|
  | CPU average use (%) | 🟡 | Relative increase of ~30% (from 11 to 14%) |
  | Disk average use (%) | 🟡 | Relative increase of ~30% (from 0.5 to 0.65%). It might be due to the verification of inodes: https://github.com/wazuh/wazuh/pull/7990 |
  | Disk_Read | 🟡 | Relative increase of ~900% (from 0.03 to 0.28 MB). It might be due to the verification of inodes: https://github.com/wazuh/wazuh/pull/7990 |
  | Disk_Written | 🟡 | Relative increase of ~36% (from 631 to 861 MB). It might be due to the verification of inodes: https://github.com/wazuh/wazuh/pull/7990 |
  | Write_Ops | 🟡 | Relative increase of ~10% (Related to disk usage)|
  | Read_Ops | 🟢 | A bit more usage in 4.2.0 (~3% increase)  |
  | FD | 🟢 | +2 FDs in 4.2 |
  | RSS_MAXMIN | 🟢 | A bit less usage in 4.2.0 |
  | RSS | 🟢 | A bit less usage in 4.2.0 (~4% average use decrease) |
  | SWAP | 🟡 | Empty graph. Is the test broken? |
  | USS | 🟢 | A bit less usage in 4.2.0 (~5% decrease) |
  | PSS | 🟢 | A bit less usage in 4.2.0 (~6% decrease) |
  | VMS | 🟢 | Similar usage in 4.1.5 and 4.2.0 |
  
  # Manager (CentOS) 4.2 VS 4.1.5

Wazuh Version |4.2 | 4.1.5 | ( [4.2] / [4.1.5] - 1 ) * 100
-- | -- | --  | --
CPU Average (%) | 13.95 | 10.98 | 27.11%
CPU Median (%)  0.00 | 0.00 | #DIV/0!
CPU Max (%) | 115.00 | 117.70 | -2.29%
RSS Average (KB) | 6319.22 | 6596.82 | -4.21%
RSS Median (KB) | 6428.00 | 6992.00 | -8.07%
RSS Max (KB) |  6996.00 | 7212.00 | -3.00%
VMS Average (KB) | 266676.37 | 268812.28 | -0.79%
VMS Median (KB) |  266832.00 | 268892.00 | -0.77%
VMS Max (KB) | 267056.00 | 269144.00 | -0.78%
FD Average | 11.20 | 9.16 | 22.38%
FD Median | 11.00 | 9.00 | 22.22%
FD Max | 19.00 | 17.00 | 11.76%
Read_Ops Average | 25160527.24 | 24354721.07 | 3.31%
Read_Ops Median | 25005109.50 | 24317432.00 | 2.83%
Read_Ops Max | 49200331.00 | 47342270.00 | 3.92%
Write_Ops Average | 409725.60 | 373867.51 | 9.59%
Write_Ops Median | 421680.00 | 384366.00 | 9.71%
Write_Ops Max | 759178.00 | 690151.00 | 10.00%
Disk_Read (MB) Average |  0.28 | 0.03 | 885.76%
Disk_Read (MB) Median | 0.02 | 0.00 | #DIV/0!
Disk_Read (MB) Max |  1.98 | 0.14 | 1267.57%
Disk_Written (MB) Average | 861.39 | 631.71 | 36.36%
Disk_Written (MB) Median | 887.08 | 650.21 | 36.43%
Disk_Written (MB) Max | 1590.57 | 1163.29 | 36.73%
Disk (%) Average | 0.65 | 0.50 | 29.68%
Disk (%) Median |  0.60 | 0.51 | 17.10%
Disk (%) Max | 1.34 | 0.80 | 66.83%
USS (KB) Average | 4541.90 | 4821.09 | -5.79%
USS (KB) Median | 4760.00 | 5020.00 | -5.18%
USS (KB) Max | 5028.00 | 5244.00 | -4.12%
PSS (KB) Average | 4855.54 | 5136.49 | -5.47%
PSS (KB) Median | 4996.00 | 5378.00 | -7.10%
PSS (KB) Max | 5382.00 | 5602.00 | -3.93%

## CPU (%)
![image](https://user-images.githubusercontent.com/39765143/125974092-8095728c-39b6-4dca-aebe-3cebdbf9338a.png)

## CPU
![image](https://user-images.githubusercontent.com/39765143/125974738-0b3a5531-fd9c-4b84-98ce-bd8e509042d2.png)

## RSS (KB)
![image](https://user-images.githubusercontent.com/39765143/125974829-2de4f5c2-5a7b-4167-a11c-a5a01dfe03c9.png)

## VMS (KB)
![image](https://user-images.githubusercontent.com/39765143/125974927-cab7f66b-764e-4cc3-a69a-155ecc69269a.png)

## FDs
![image](https://user-images.githubusercontent.com/39765143/125975062-d171156b-d908-4de3-ba25-2e29a8f7e510.png)

## Read_ops
![image](https://user-images.githubusercontent.com/39765143/125975146-21770e53-34bb-4428-b60e-86c958b750c1.png)

## Write_ops
![image](https://user-images.githubusercontent.com/39765143/125975202-a9dcb7e9-01e7-4b5d-a262-82b1c81cae77.png)

## Disk_read (MB)
![image](https://user-images.githubusercontent.com/39765143/125975279-2690d871-6347-492b-beea-101a1276c420.png)

## Disk_write (MB)
![image](https://user-images.githubusercontent.com/39765143/125975357-e4db4601-c38f-40b8-9947-f41f63cd2327.png)

## Disk (%)
![image](https://user-images.githubusercontent.com/39765143/125975421-d9dffaac-3284-485b-befc-d9e54bbb6aa0.png)

## USS (KB)
![image](https://user-images.githubusercontent.com/39765143/125975473-338b53fb-7de6-4294-93b0-5e298d56fe3c.png)

## PSS (KB)
![image](https://user-images.githubusercontent.com/39765143/125975529-9c7b8da2-a7bc-4911-80b3-979bcf2def5c.png)

**Comment by JcabreraC** [comment]
# CentOS agent 
  |Measure|Status|Comment|
  |---|---|---|
  | CPU average use (%) | 🟡 | Relative increase of 30% (from 11 to 14%) |
  | Disk average use (%) | 🟢 | A bit less usage in 4.2.0 (-13% decrease) |
  | Disk_Read | 🟢 | A bit more usage in 4.2.0 (~6% increase). It might be due to the verification of inodes: https://github.com/wazuh/wazuh/pull/7990 |
  | Disk_Written | 🟡 | Relative increase of 46% (from 632 to 924 MB). It might be due to the verification of inodes: https://github.com/wazuh/wazuh/pull/7990 |
  | Read_Ops | 🟢 | A bit more usage in 4.2.0 (~5% increase) |
  | Write_Ops | 🟡 | A more usage in 4.2.0 (~22% increase). It might be due to the verification of inodes: https://github.com/wazuh/wazuh/pull/7990 |
  | FD | 🟢 | +1 FD in 4.2 |
  | RSS_MAXMIN | 🟢 | A bit less usage in 4.2.0 (~3% decrease) |
  | RSS | 🟢 | A bit less usage in 4.2.0 (~3% decrease) |
  | SWAP | 🟡 | Empty graph. Is the test broken? |
  | USS | 🟢 | Less usage in 4.2.0 (~8% decrease) |
  | PSS | 🟢 | A bit less usage in 4.2.0 (~6% decrease) |
  | VMS | 🟢 | Similar results in 4.1.5 and 4.2.0 |
  
  # CentOS Agent 4.2 VS 4.1.5

Wazuh Version | 4.2 | 4.1.5 | ( [4.2] / [4.1.5] - 1 ) * 100
-- | -- | -- | --
CPU Average (%) | 13.71 | 10.56 | 29.78%
CPU Median (%) | 0.00 | 0.00 | #DIV/0!
CPU Max (%) | 118.10 | 117.20 | 0.77%
RSS Average (KB) | 6405.28 | 6642.19 | -3.57%
RSS Median (KB) | 6612.00 | 6820.00 | -3.05%
RSS Max (KB) | 6820.00 | 7008.00 | -2.68%
VMS Average (KB) | 265850.81 | 265787.09 | 0.02%
VMS Median (KB) | 265964.00 | 265868.00 | 0.04%
VMS Max (KB) | 266152.00 | 266056.00 | 0.04%
FD Average | 11.20 | 10.16 | 10.30%
FD Median | 11.00 | 10.00 | 10.00%
FD Max | 19.00 | 18.00 | 5.56%
Read_Ops Average | 26506337.53 | 25249022.70 | 4.98%
Read_Ops Median | 26595786.00 | 25295303.50 | 5.14%
Read_Ops Max | 50210601.00 | 48491827.00 | 3.54%
Write_Ops Average | 457837.30 | 374683.59 | 22.19%
Write_Ops Median | 480410.00 | 388021.50 | 23.81%
Write_Ops Max | 820645.00 | 684779.00 | 19.84%
Disk_Read (MB) Average | 143.76 | 135.38 | 6.19%
Disk_Read (MB) Median | 143.76 | 135.38 | 6.19%
Disk_Read (MB) Max | 143.76 | 135.38 | 6.19%
Disk_Written (MB) Average | 924.87 | 632.78 | 46.16%
Disk_Written (MB) Median | 963.73 | 655.07 | 47.12%
Disk_Written (MB) Max | 1675.49 | 1159.73 | 44.47%
Disk (%) Average | 2.61 | 2.99 | -12.87%
Disk (%) Median | 2.46 | 2.00 | 23.44%
Disk (%) Max | 5.99 | 8.01 | -25.24%
USS (KB) Average | 5072.22 | 5512.14 | -7.98%
USS (KB) Median | 5276.00 | 5688.00 | -7.24%
USS (KB) Max | 5488.00 | 5880.00 | -6.67%
PSS (KB) Average | 5394.34 | 5745.44 | -6.11%
PSS (KB) Median | 5598.00 | 5921.00 | -5.46%
PSS (KB) Max | 5810.00 | 6113.00 | -4.96%

## CPU (%)
![imagen](https://user-images.githubusercontent.com/39765143/126131127-ddaa5283-99a9-4257-8f9c-adf824bb49bf.png)

## CPU
![imagen](https://user-images.githubusercontent.com/39765143/126131187-d19bb669-ed6c-4841-aa70-48c8ae1c5d62.png)

## RSS (KB)
![imagen](https://user-images.githubusercontent.com/39765143/126131233-b1cd0a9d-fa66-47ac-8e17-f3d6c3af819d.png)

## VMS (KB)
![imagen](https://user-images.githubusercontent.com/39765143/126131308-3723200a-6c7d-4a39-b473-1d66d1ecc5d7.png)

## FDs
![imagen](https://user-images.githubusercontent.com/39765143/126131395-000adcab-3f1f-4d71-88b9-9d400cadbad2.png)

## Read_ops
![imagen](https://user-images.githubusercontent.com/39765143/126131776-eaf9ccc9-1229-4951-a653-e5392edd8172.png)

## Write_ops
![imagen](https://user-images.githubusercontent.com/39765143/126132475-3ea3a760-7e61-4631-b74d-080b02462889.png)

## Disk_read (MB)
![imagen](https://user-images.githubusercontent.com/39765143/126132525-df8888ca-6801-4e7f-a629-462bafefd0cf.png)

## Disk_write (MB)
![imagen](https://user-images.githubusercontent.com/39765143/126132563-e0360347-4670-4101-b7ab-dd004ba37e48.png)

## Disk (%)
![imagen](https://user-images.githubusercontent.com/39765143/126132633-d8ec7481-c2ad-46a6-96fb-659beb5c6f4a.png)

## USS (KB)
![imagen](https://user-images.githubusercontent.com/39765143/126132679-5b13abd3-fe5f-4fce-be36-ed0a23d73088.png)

## PSS (KB)
![imagen](https://user-images.githubusercontent.com/39765143/126132719-3465ead9-bf12-47fd-962c-5c6e1b24328b.png)

**Comment by JcabreraC** [comment]
# Ubuntu agent
  |Measure|Status|Comment|
  |---|---|---|
  | CPU average use (%) | 🟡 | Relative increase of 34% (from 9 to 12%) |
  | Disk average use (%) | 🟢 | A bit less usage in 4.2.0 (-19% decrease) |
  | Disk_Read | 🟢 | Similar results in 4.1.5 and 4.2.0 |
  | Disk_Written | 🟡 | Relative increase of 65% (from 625 to 1031 MB). It might be due to the verification of inodes: https://github.com/wazuh/wazuh/pull/7990 |
  | Write_Ops | 🟡 | More usage in 4.2.0 (~27% increase). It might be due to the verification of inodes: https://github.com/wazuh/wazuh/pull/7990 |
  | Read_Ops | 🟢 | A bit more usage in 4.2.0 (~5% increase)  |
  | FD | 🟢 | -2 FDs in 4.2.0 |
  | RSS_MAXMIN | 🟢 | A bit less usage in 4.2.0 (~4% decrease) |
  | RSS | 🟢 | A bit less usage in 4.2.0 (~3% decrease) |
  | SWAP | 🟡 | Empty graph. Is the test broken? |
  | USS | 🟢 | A bit less usage in 4.2.0 (~7% decrease) |
  | PSS | 🟢 | A bit less usage in 4.2.0 (~6% decrease) |
  | VMS | 🟢 | Similar results in 4.1.5 and 4.2.0 |
  
  # Ubuntu Agent 4.2 VS 4.1.5


Wazuh Version | 4.2 | 4.1.5 | ( [4.2] / [4.1.5] - 1 ) * 100
-- | -- | -- | --
CPU Average (%) | 11.67 | 8.69 | 34.33%
CPU Median (%) | 0.00 | 0.00 | #DIV/0!
CPU Max (%) | 117.30 | 109.80 | 6.83%
RSS Average (KB) | 9260.65 | 9490.28 | -2.42%
RSS Median (KB) | 9456.00 | 9660.00 | -2.11%
RSS Max (KB) | 9640.00 | 10024.00 | -3.83%
VMS Average (KB) | 273069.07 | 273032.65 | 0.01%
VMS Median (KB) | 273092.00 | 273024.00 | 0.02%
VMS Max (KB) | 273300.00 | 273204.00 | 0.04%
FD Average | 11.17 | 14.12 | -20.92%
FD Median | 11.00 | 14.00 | -21.43%
FD Max | 16.00 | 18.00 | -11.11%
Read_Ops Average | 20194584.03 | 19249635.65 | 4.91%
Read_Ops Median | 20179818.50 | 19265626.00 | 4.75%
Read_Ops Max | 39396117.00 | 37796487.00 | 4.23%
Write_Ops Average | 493606.88 | 388376.10 | 27.10%
Write_Ops Median | 508694.00 | 404757.00 | 25.68%
Write_Ops Max | 904968.00 | 708778.00 | 27.68%
Disk_Read (MB) Average | 195.24 | 195.69 | -0.23%
Disk_Read (MB) Median | 193.28 | 195.46 | -1.12%
Disk_Read (MB) Max | 200.49 | 202.03 | -0.76%
Disk_Written (MB) Average | 1031.26 | 625.15 | 64.96%
Disk_Written (MB) Median | 1064.63 | 649.47 | 63.92%
Disk_Written (MB) Max | 1899.83 | 1146.11 | 65.76%
Disk (%) Average | 0.28 | 0.35 | -19.10%
Disk (%) Median | 0.23 | 0.17 | 32.50%
Disk (%) Max | 4.12 | 4.07 | 1.23%
USS (KB) Average | 6188.63 | 6630.45 | -6.66%
USS (KB) Median | 6372.00 | 6800.00 | -6.29%
USS (KB) Max | 6552.00 | 6984.00 | -6.19%
PSS (KB) Average | 6805.51 | 7203.78 | -5.53%
PSS (KB) Median | 6985.00 | 7371.00 | -5.24%
PSS (KB) Max | 7172.00 | 7558.00 | -5.11%

## CPU (%)
![imagen](https://user-images.githubusercontent.com/39765143/126132955-0892992d-e2dc-4621-b797-05e55362cc7d.png)

## CPU
![imagen](https://user-images.githubusercontent.com/39765143/126132991-743e27b5-ec46-4403-8771-f0817788fad5.png)

## RSS (KB)
![imagen](https://user-images.githubusercontent.com/39765143/126133015-6ad23b96-8a97-4301-8dd6-87bade505ac4.png)

## VMS (KB)
![imagen](https://user-images.githubusercontent.com/39765143/126133045-380fe2e7-3fb5-467d-a646-b19292d6a018.png)

## FDs
![imagen](https://user-images.githubusercontent.com/39765143/126133259-9d290f25-4944-41f9-af27-d4f474ca5a21.png)

## Read_ops
![imagen](https://user-images.githubusercontent.com/39765143/126133315-4b233a7a-435e-4705-aab1-5951561c9fbe.png)

## Write_ops
![imagen](https://user-images.githubusercontent.com/39765143/126133344-65add836-34d3-4a8e-89b3-c0dcf2d9b112.png)

## Disk_read (MB)
![imagen](https://user-images.githubusercontent.com/39765143/126133405-0640bb5a-c18c-4456-a6c3-39bbaea4cfc3.png)

## Disk_write (MB)
![imagen](https://user-images.githubusercontent.com/39765143/126133437-3abd9a4d-4610-4037-b4d5-585eaca2fcb9.png)

## Disk (%)
![imagen](https://user-images.githubusercontent.com/39765143/126133481-3e78db2a-8791-4267-886f-f66566d6af4d.png)

## USS (KB)
![imagen](https://user-images.githubusercontent.com/39765143/126133519-3269f878-d341-4f1e-85af-5bc0e6f752c1.png)

## PSS (KB)
![imagen](https://user-images.githubusercontent.com/39765143/126133568-5e6c89b5-44aa-422c-a060-ce8521325c81.png)

**Comment by JcabreraC** [comment]
# Windows Agent
  |Measure|Status|Comment|
  |---|---|---|
  | CPU average use (%) | 🟢 | Less usage in 4.2.0 (~22% decrease) |
  | Disk average use (%) | 🟢 | Less usage in 4.2.0 (~68% decrease) |
  | Disk_Read | 🟢 | Less usage in 4.2.0 (~70% decrease) |
  | Disk_Written | 🟢 | Less usage in 4.2.0 (~9% decrease) |
  | Write_Ops | 🟢 | Less usage in 4.2.0 (~56% decrease) |
  | Read_Ops | 🟢 | Less usage in 4.2.0 (~70% decrease) | 
  | FD | 🟢 | More FD used in 4.2.0 (~6% increase) |
  | RSS | 🟢 | A bit less in 4.2.0 (~4% decrease) |
  | SWAP | 🟡 | Empty graph. Is the test broken? |
  | USS | 🟢 | A bit less usage in 4.2.0 (~5% decrease) |
  | PSS | 🟡 | No data |
  | VMS | 🟢 | Less usage in 4.2.0 (~7% decrease) |

# Windows Agent 4.2 VS 4.1.5

Wazuh Version | 4.2 | 4.1.5 | ( [4.2] / [4.1.5] - 1 ) * 100
-- | -- | -- | --
CPU Average (%) | 20.44 | 26.32 | -22.34%
CPU Median (%) | 56.80 | 0.00 | #DIV/0!
CPU Max (%) | 157.70 | 200.70 | -21.43%
RSS Average (KB) | 17618.15 | 18274.94 | -3.60%
RSS Median (KB) | 17864.00 | 18432.00 | -3.12%
RSS Max (KB) | 18584.00 | 23428.00 | -20.68%
VMS Average (KB) | 11376.94 | 12212.21 | -6.84%
VMS Median (KB) | 11624.00 | 12260.00 | -5.70%
VMS Max (KB) | 12556.00 | 14560.00 | -13.76%
FD Average | 286.00 | 269.43 | 6.16%
FD Median | 286.00 | 269.00 | 6.32%
FD Max | 294.00 | 279.00 | 5.38%
Read_Ops Average | 41473788.53 | 145285791.44 | -71.29%
Read_Ops Median | 46493681.00 | 147121062.00 | -68.19%
Read_Ops Max | 67350954.00 | 281918505.00 | -76.10%
Write_Ops Average | 2553800.99 | 5904267.63 | -56.38%
Write_Ops Median | 2562923.50 | 5573834.00 | -53.19%
Write_Ops Max | 5008878.00 | 14190985.00 | -64.38%
Disk_Read (MB) Average | 161927.97 | 567453.47 | -71.30%
Disk_Read (MB) Median | 181536.13 | 574628.29 | -68.20%
Disk_Read (MB) Max | 262934.68 | 1101060.19 | -76.11%
Disk_Written (MB) Average | 4470.96 | 4939.68 | -8.90%
Disk_Written (MB) Median | 4468.75 | 4933.72 | -8.40%
Disk_Written (MB) Max | 8897.55 | 10273.45 | -12.69%
Disk (%) Average | 882.85 | 2717.74 | -67.43%
Disk (%) Median | 975.89 | 3377.88 | -71.07%
Disk (%) Max | 1328.81 | 4108.98 | -67.66%
USS (KB) Average | 13344.75 | 13854.90 | -5.05%
USS (KB) Median | 13656.00 | 14008.00 | -4.39%
USS (KB) Max | 14224.00 | 19004.00 | -25.70%

## CPU (%)
![chart(10)](https://user-images.githubusercontent.com/75255206/126393288-5476a0a7-7bfc-4110-b5ba-e735560fe745.png)

## CPU
![chart(9)](https://user-images.githubusercontent.com/75255206/126393292-b27da9a5-e75d-48a4-b840-fb8c7623f8ca.png)

## RSS (KB)
![chart(8)](https://user-images.githubusercontent.com/75255206/126393297-060d31a6-9acd-413c-ace4-e61f4bb55add.png)

## VMS (KB)
![chart(7)](https://user-images.githubusercontent.com/75255206/126393299-276b67ba-4cd8-47ab-a213-62616f50662c.png)

## FDs
![chart(6)](https://user-images.githubusercontent.com/75255206/126393302-cdfa3d76-c3c1-442f-9104-713ca55f7045.png)

## Read_ops
![chart(5)](https://user-images.githubusercontent.com/75255206/126393309-b6edc4bc-c8e3-47d5-8268-b25ceb167923.png)

## Write_ops
![chart(4)](https://user-images.githubusercontent.com/75255206/126393311-aa055194-06e9-46c2-ac14-cb2291c6501c.png)

## Disk_read (MB)
![chart(3)](https://user-images.githubusercontent.com/75255206/126393313-855aa820-62c6-453a-be61-b7b52d31c01a.png)

## Disk_write (MB)
![chart(2)](https://user-images.githubusercontent.com/75255206/126393315-dfc4c273-ab62-4d97-ba20-bf0afdc3fb37.png)

## Disk (%)
![chart(1)](https://user-images.githubusercontent.com/75255206/126393318-0a367be8-e48e-42d4-a36b-d48f9657bb83.png)

## USS (KB)
![chart](https://user-images.githubusercontent.com/75255206/126393321-457c0ab7-430d-470c-9ff7-6b6de75f57ba.png)

**Comment by nmkoremblum** [comment]
## Performance conclusions of comparing 4.2.0 with 4.1.5

As it can be seen in the previously provided data, the `Syscheckd` module uses less RAM in general. The use of the disk increases, which leads to raising the average use of the CPU. As we could verify with the development team that worked with this module, this is mainly produced by the changes introduced on the following PR: [Verify inodes saved on FIM DB before updating file data](https://github.com/wazuh/wazuh/pull/7990), which prevents files that have had their inodes changed from overwriting metadata that belongs to other files. We consider that the increase in the use of resources observable in the tests is justified given the improvements provided in the previously mentioned PR.

**Comment by nmkoremblum** [comment]
## Further tests to implement

In the process of testing the performance of this module, we have found that there was an excessive use of the CPU. This was caused by a bug in the code that prevented the databases to correctly synchronize. Given this situation, and taking into account future modifications that might be done on this module, we would recommend developing tests to check if the databases of managers and agents are synchronizing well.

**Comment by JcabreraC** [comment]
## FIM DB
The FIM database is structured as follows:

![imagen](https://user-images.githubusercontent.com/39765143/127473055-94c1cdc0-799f-4e12-92a7-657db7caa045.png)
- path: Holds the path relative to the configured entry.
- type: An integer describing the type of value contained in the register, as described [here](https://docs.microsoft.com/en-us/windows/win32/sysinfo/registry-value-types)
- value: The value held in the registry entry, converted into a string representing it.
- parent_id: An integer linking the current entry to its configured parent.

Entries in `reg_entry` table will correspond with a subkey and values will be stored over multiple entries in the `reg_data` table.

**Comment by JcabreraC** [comment]
## Flow diagram
The following flowchart shows how the scanning and sending of events is performed in FIM:

![imagen](https://user-images.githubusercontent.com/39765143/127482998-426fdb13-9b8e-4627-9f89-0d38c1851054.png)

**Comment by nmkoremblum** [comment]
## New measurements of 24hs tests, after the fix of the synchronization that was merged to 4.2.0

### Manager CentOS 4.2.0 (after the fix) vs 4.1.5
  |Measure|Status|Comment|
  |---|---|---|
  | CPU average use (%) | 🟢 | Similar usage in 4.1.5 and 4.2.0 |
  | Disk average use (%) | 🟢 | A bit more usage in 4.2.0 (~6% increase)  |
  | Disk_Read | 🟡 | Relative increase of ~300% (from 900 to 3800 MB). It might be due to the verification of inodes: https://github.com/wazuh/wazuh/pull/7990 |
  | Disk_Written | 🟢 | Relative increase of ~26% (from 7000 to 8800 MB). It might be due to the verification of inodes: https://github.com/wazuh/wazuh/pull/7990 |
  | Write_Ops | 🟢 | Similar usage in 4.1.5 and 4.2.0 |
  | Read_Ops | 🟢 | A bit more usage in 4.2.0 (~6% increase)  |
  | FD | 🟢 | +3 FDs in 4.2 |
  | RSS | 🟡 | Relative increase of ~20% (from 6 to 7.5 MB) |
  | SWAP | 🟡 | Empty graph. Is the test broken? |
  | USS | 🟢 | A bit more usage in 4.2.0 (~8% increase) |
  | PSS | 🟢 | A bit more usage in 4.2.0 (~13% increase) |
  | VMS | 🟢 | A bit more usage in 4.2.0 (~6% increase) |
  
### Manager (CentOS) 4.2 VS 4.1.5

Wazuh Version |4.2 | 4.1.5 | ( [4.2] / [4.1.5] - 1 ) * 100
-- | -- | --  | --
CPU Average (%) | 11.79 | 11.77 | 0.15%
CPU Median (%)  | 0.00 | 0.00 | ---
CPU Max (%) | 115.50 | 115.10 | 0.35%
RSS Average (KB) | 7515.02 | 6291.16 | 19.45%
RSS Median (KB) | 7004.00 | 6368.00 | 9.99%
RSS Max (KB) |  9988.00 | 7228.00 | 38.18%
VMS Average (KB) | 284805.13 | 268781.45 | 5.96%
VMS Median (KB) |  284852.00 | 268916.00 | 5.93%
VMS Max (KB) | 285108.00 | 269112.00 | 5.94%
FD Average | 14.15 | 9.14 | 54.86%
FD Median | 14.00 | 9.00 | 55.56%
FD Max | 20.00 | 17.00 | 17.65%
Read_Ops Average | 149784284.47 | 140339862.60 | 6.73%
Read_Ops Median | 150764220.00 | 140638017.50 | 7.20%
Read_Ops Max | 294677636.00 | 278151899.00 | 5.94%
Write_Ops Average | 2347683.60 | 2219429.48 | 5.78%
Write_Ops Median | 2421052.00 | 2284760.00 | 5.97%
Write_Ops Max | 4293230.00 | 4123872.00 | 4.11%
Disk_Read (MB) Average |  1400.89 | 716.12 | 95.62%
Disk_Read (MB) Median | 1456.77 | 918.32 | 58.63%
Disk_Read (MB) Max | 3802.15 | 963.63 | 294.56%
Disk_Written (MB) Average | 4766.36 | 3741.70 | 27.38%
Disk_Written (MB) Median | 4928.23 | 3860.77 | 27.65%
Disk_Written (MB) Max | 8756.53 | 6926.86 | 26.41%
Disk (%) Average | 0.17 | 0.16 | 6.25%
Disk (%) Median |  0.15| 0.12 | 27.27%
Disk (%) Max | 0.55 | 0.45 | 23.21%
USS (KB) Average | 5181.90 | 4795.58 | 8.06%
USS (KB) Median | 5232.00 | 4992.00 | 4.81%
USS (KB) Max | 5936.00 | 5248.00 | 13.11%
PSS (KB) Average | 5708.73 | 5042.13 | 13.22%
PSS (KB) Median | 5631.00 | 5210.00 | 8.08%
PSS (KB) Max | 6796.00 | 5605.00 | 21.25%

![chart(11)](https://user-images.githubusercontent.com/75255206/128049757-67790582-819e-41ae-90b3-02f1456d8700.png)
![chart(10)](https://user-images.githubusercontent.com/75255206/128049760-20d864b2-388a-467e-8cdd-08af21ae6693.png)
![chart(9)](https://user-images.githubusercontent.com/75255206/128049766-d6465eef-69e1-4f7e-ae7e-cfafdba91a16.png)
![chart(8)](https://user-images.githubusercontent.com/75255206/128049768-868de494-d646-44bf-9501-b95cf1f95793.png)
![chart(7)](https://user-images.githubusercontent.com/75255206/128049770-cbae7def-8f26-4bfe-9023-a8b51c0453bd.png)
![chart(6)](https://user-images.githubusercontent.com/75255206/128049777-306421cb-a85e-4b7e-b4e5-40627a8845d8.png)
![chart(5)](https://user-images.githubusercontent.com/75255206/128049781-7c2ccd6f-b228-4ffd-8d1d-2e32a2ebd846.png)
![chart(4)](https://user-images.githubusercontent.com/75255206/128049787-8f00fa67-b7f7-4db5-a947-e8ef1718913b.png)
![chart(3)](https://user-images.githubusercontent.com/75255206/128049789-759fc738-9530-44c7-a3ca-547b47fdf84c.png)
![chart(2)](https://user-images.githubusercontent.com/75255206/128049792-c1256ce6-553d-4c16-a700-bd98bc4e3703.png)
![chart(1)](https://user-images.githubusercontent.com/75255206/128049796-ff97d3bf-ddcc-48e0-83c9-7ae4da4f9b70.png)
![chart](https://user-images.githubusercontent.com/75255206/128049798-f70cad77-ff14-445d-b403-aa06c87abb5c.png)
