### ISSUE TITLE
Analyze and test how much memory AWS occupies

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#9257]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.0-RC10 | Wazuh-Modulesd [AWS] | Manager | Any | ALL |

## Goal

Find out how much memory the component might take.

## Summary

The AWS wodle (inside Wazuh-Modulesd) makes use of a python script, so the footprint of the binary is small.

### How it works

![AWS_S3](https://user-images.githubusercontent.com/1891958/127228722-7964dac9-1912-493f-ab43-8d2bcc069036.png)

#### Test A: config

```xml
  <wodle name="aws-s3">
     <disabled>no</disabled>
     <remove_from_bucket>no</remove_from_bucket>
     <interval>100s</interval>
     <run_on_start>yes</run_on_start>
     <skip_on_error>no</skip_on_error>
     <bucket type="vpcflow">
       <name>ZZZZZZZZZ</name>
       <access_key>XXXXXXXXXXXXXXXXX</access_key>
       <secret_key>YYYYYYYYYYYYYYYYYYYY</secret_key>
       <path>vpc/</path>
     </bucket>
  </wodle>
```
#### Test A: Massif 

![2021-07-22_15-09](https://user-images.githubusercontent.com/1891958/126688230-3ec02a1f-8284-4bda-8d0e-d765aed901fd.png)
[massif.out.couldtrail.zip](https://github.com/wazuh/wazuh/files/6864313/massif.out.zip)

#### Test B: config

With 2 wodles, the result is still as expected

```xml
  <wodle name="aws-s3">
     <disabled>no</disabled>
     <remove_from_bucket>no</remove_from_bucket>
     <interval>100s</interval>
     <run_on_start>yes</run_on_start>
     <skip_on_error>no</skip_on_error>
     <bucket type="vpcflow">
       <name>XXXXXXXXXXX</name>
       <access_key>XXXXXXXXXXX</access_key>
       <secret_key>XXXXXXXXXXX</secret_key>
       <path>vpc/</path>
     </bucket>
  </wodle>

  <wodle name="aws-s3">
     <disabled>no</disabled>
     <remove_from_bucket>no</remove_from_bucket>
     <interval>100s</interval>
     <run_on_start>yes</run_on_start>
     <skip_on_error>no</skip_on_error>
     <bucket type="cloudtrail">
       <name>XXXXXXXXXXX</name>
       <access_key>XXXXXXXXXXX</access_key>
       <secret_key>XXXXXXXXXXX</secret_key>
       <only_logs_after>2021-JUL-22</only_logs_after>
     </bucket>
```

#### Test B: Massif 

![image](https://user-images.githubusercontent.com/1891958/126697616-29a2f4be-ec81-45ec-9121-435bf4d0798d.png)
[massif.out.zip](https://github.com/wazuh/wazuh/files/6864755/massif.out.zip)

The theoretical memory usage (stack + heap) of modulesd is low and constant (300kb). The only activated woodle is AWS.
The startup peak is explained by the configuration load.
The successive spikes every 100 seconds are due to the update interval. The module generates the command to call the script and then waits for it to finish to release it.
Memory usage is very low and recovers quickly

# Tasks

Explain with diagrams and descriptions in markdown files, and put it in the wazuh / architecture directory an explanation of the operation and calculations of how much the peak(stressed) and post-peak consumption would be left in memory in standby.

- [x] [Create functionality diagrams](https://github.com/wazuh/wazuh/issues/9257#issue-942134979)
- [x] [Create feature description](https://github.com/wazuh/wazuh/issues/9257#issue-942134979)
- [x] Analyze resources consumption (Linux): [vpcflow](https://github.com/wazuh/wazuh/issues/9257#issuecomment-885244015), [cloudtrail](https://github.com/wazuh/wazuh/issues/9257#issuecomment-885246844), [iddle](https://github.com/wazuh/wazuh/issues/9257#issuecomment-885632814)
- [x] [Performance conclusions of comparing Wazuh 4.2.0 with 4.1.5](https://github.com/wazuh/wazuh/issues/9257#issuecomment-886367279)
- [x] [Further tests to develop](https://github.com/wazuh/wazuh/issues/9257#issuecomment-886370474)

**Comment by nmkoremblum** [comment]
Results for Test A (aws-s3 process):
![CPU](https://user-images.githubusercontent.com/75255206/126711168-1882aead-b2f4-4e54-818b-65964dfd3a54.png)
![Disk](https://user-images.githubusercontent.com/75255206/126711171-2f486427-21d7-48d2-b74c-e9397a0bf674.png)
![Disk_Read](https://user-images.githubusercontent.com/75255206/126711175-32df5512-b50d-4905-b216-8f68d5481fbe.png)
![Disk_Read_Speed](https://user-images.githubusercontent.com/75255206/126711178-811535ad-d736-4dcc-b4fe-f3fd14c974cf.png)
![Disk_Write_Speed](https://user-images.githubusercontent.com/75255206/126711184-6f8b0555-b38d-4f15-8e56-ddd9d73b97fc.png)
![Disk_Written](https://user-images.githubusercontent.com/75255206/126711185-95b2d676-f845-4b6f-9447-3480a6d0cb96.png)
![FD](https://user-images.githubusercontent.com/75255206/126711194-b177ff5f-faca-48b5-ae3c-a572b8886e41.png)
![PSS](https://user-images.githubusercontent.com/75255206/126711200-bdeddb6f-9734-4ca0-883e-7f6bacdf590f.png)
![Read_Ops](https://user-images.githubusercontent.com/75255206/126711206-b7ec0f2c-4d9c-47c1-bfc2-a5e998887f38.png)
![RSS](https://user-images.githubusercontent.com/75255206/126711209-7d977c95-0c01-471b-9a45-f08c15660b59.png)
![SWAP](https://user-images.githubusercontent.com/75255206/126711214-1eb044d3-24fe-4d65-b641-74958b424199.png)
![USS](https://user-images.githubusercontent.com/75255206/126711216-be9a2ed0-cbc9-4815-8dcb-503b7afcc59a.png)
![VMS](https://user-images.githubusercontent.com/75255206/126711217-c76c0faa-0597-4ac5-8658-a562f54fa807.png)
![Write_Ops](https://user-images.githubusercontent.com/75255206/126711222-f008bacd-643a-4637-a11e-80d9ef578255.png)

**Comment by nmkoremblum** [comment]
Results for Test II (aws-s3 process):

Config:
```xml
<wodle name="aws-s3">
  <disabled>no</disabled>
  <remove_from_bucket>no</remove_from_bucket>
  <interval>100s</interval>
  <run_on_start>yes</run_on_start>
  <skip_on_error>no</skip_on_error>
  <bucket type="cloudtrail">
    <name>XXXXXXXXXXX</name>
    <access_key>XXXXXXXXXXX</access_key>
    <secret_key>XXXXXXXXXXX</secret_key>
    <only_logs_after>2021-JUL-22</only_logs_after>
  </bucket>
</wodle>
```

![CPU](https://user-images.githubusercontent.com/75255206/126711755-3404111e-c286-4b83-b414-452ce90c0cb4.png)
![Disk](https://user-images.githubusercontent.com/75255206/126711760-781fbe64-a485-48bc-9635-b409f1dd4d66.png)
![Disk_Read](https://user-images.githubusercontent.com/75255206/126711762-784c35af-0d8c-4f2d-aaf4-8735373829b4.png)
![Disk_Read_Speed](https://user-images.githubusercontent.com/75255206/126711769-e6781bd3-e7f3-45bf-946d-9a904d05096b.png)
![Disk_Write_Speed](https://user-images.githubusercontent.com/75255206/126711771-d1aeb1c8-0a1b-423e-a696-8b0c9af45421.png)
![Disk_Written](https://user-images.githubusercontent.com/75255206/126711774-9f77eeea-1899-4dbb-929e-f011b67cbb8e.png)
![FD](https://user-images.githubusercontent.com/75255206/126711777-8e004ca7-0e28-411d-ae4c-40b5c514cb45.png)
![PSS](https://user-images.githubusercontent.com/75255206/126711779-6429b4f2-104f-4b2c-bc4c-b0812e5812a5.png)
![Read_Ops](https://user-images.githubusercontent.com/75255206/126711781-bf1a581f-c3a5-4f6e-a958-a198f63e8493.png)
![RSS](https://user-images.githubusercontent.com/75255206/126711783-1d24e646-ca06-4f1e-8e0e-5461192d3782.png)
![SWAP](https://user-images.githubusercontent.com/75255206/126711787-ecdf037c-8487-4aab-859e-209bcc0fb53c.png)
![USS](https://user-images.githubusercontent.com/75255206/126711790-233a0154-87df-4080-9b85-e3692ac99e20.png)
![VMS](https://user-images.githubusercontent.com/75255206/126711793-40c91ce6-a7e6-46b6-89f8-f0efc1a395bf.png)
![Write_Ops](https://user-images.githubusercontent.com/75255206/126711800-35808662-f479-497c-af2d-fa3b0ec9da8d.png)

**Comment by nmkoremblum** [comment]
# Results for Test III (Iddle - 10 minutes)

## Config

No AWS wodle added

## Graphics of wazuh-modulesd process

![CPU](https://user-images.githubusercontent.com/75255206/126787196-76333dd3-aa2d-4c2e-8f62-0e75601d3519.png)
![Disk](https://user-images.githubusercontent.com/75255206/126787206-44dc2d28-f8c0-4104-8175-06cadafb1dd0.png)
![Disk_Read](https://user-images.githubusercontent.com/75255206/126787211-ce899a5a-0de8-4303-91a1-3db738c9adc6.png)
![Disk_Read_Speed](https://user-images.githubusercontent.com/75255206/126787218-4d06f710-ea47-4956-81b7-33fe6ff7325a.png)
![Disk_Write_Speed](https://user-images.githubusercontent.com/75255206/126787223-3ef0ba06-c7c2-4cdd-b5fe-c5ccc9fcf2f0.png)
![Disk_Written](https://user-images.githubusercontent.com/75255206/126787229-0a0d3a7c-9dc8-40e7-ad65-fa01ef8edc61.png)
![FD](https://user-images.githubusercontent.com/75255206/126787233-08761cb2-113c-435b-a92d-6695fc2d1c38.png)
![PSS](https://user-images.githubusercontent.com/75255206/126787237-36ea4ef0-e501-4370-a3f5-f7d9ddeed5c6.png)
![Read_Ops](https://user-images.githubusercontent.com/75255206/126787242-99e74c14-c168-48ba-8e44-bbad4b75740e.png)
![RSS](https://user-images.githubusercontent.com/75255206/126787246-11f7babf-4382-461a-a69b-a260a1b55e37.png)
![SWAP](https://user-images.githubusercontent.com/75255206/126787252-2b154880-1085-4202-9970-589687f9aa9e.png)
![USS](https://user-images.githubusercontent.com/75255206/126787255-de34a793-57a8-47c0-9c92-295a78fcdd0e.png)
![VMS](https://user-images.githubusercontent.com/75255206/126787258-09e370c6-b1c5-4eea-bac1-f91f4633308b.png)
![Write_Ops](https://user-images.githubusercontent.com/75255206/126787260-ce791ea6-a4a9-4e8f-808f-bd6c5670281a.png)

**Comment by nmkoremblum** [comment]
## Performance conclusions of comparing Wazuh 4.2.0 with 4.1.5

After inspecting the code related to the AWS feature, no relevant changes were introduced since version 4.1.5. The memory tests (massif) show that resources are well handled and, as for the stress tests, no strange behavior occurs while stressing the module through the AWS feature.
On tests II and III memory usage raises after about 8 minutes. As test III is completely free from AWS configurations we infer that this memory behavior is not related to AWS but modulesd itself, further analysis related to this should be performed.

**Comment by nmkoremblum** [comment]
## Further tests to develop

The AWS feature does not count, at the time, with integration tests nor stress tests. All the tests were run by hand and they might not have been long nor intensive enough. On these tests, only `"vpcflow"` and `"cloudtrail"` services were used to retrieve logs from the AWS buckets, future tests should cover all the available services.
