### ISSUE TITLE
Decoders for Cisco-IOS don't work properly

### ISSUE THREAD

**Issue by maumrsms** [wazuh/wazuh#9269]
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.1.5 | Decoders| Error/Improve |

## Description
Tested Cisco Firepower 2110 (IOS version 6.4.0.7) log samples with `ossec-logtest` and `wazuh-logtest`. Although they trigger alerts, not all of the event information is properly decoded. Checked that Wazuh currently has decoders for Cisco-IOS.

### Reason
To get current decoders fixed.

### Current results
**Log sample:** `2021-07-07T18:00:02.011094-03:00 XXX.XXX.XXX.XXX %FTD-4-106023: Deny udp src AS_BGP:XXX.XXX.XXX.XXX/39701 dst 3.73-p7:XXX.XXX.XXX.XXX/49261 by access-group "CSM_FW_ACL" [0x97aa021a, 0x0]`

**Test results with `logtest`:**
```
**Phase 1: Completed pre-decoding.
       full event: '2021-07-07T18:00:02.011094-03:00 XXX.XXX.XXX.XXX %FTD-4-106023: Deny udp src AS_BGP:XXX.XXX.XXX.XXX/39701 dst 3.73-p7:XXX.XXX.XXX.XXX/49261 by access-group "CSM_FW_ACL" [0x97aa021a, 0x0]'
       timestamp: '2021-07-07T18:00:02.011094-03:00'
       hostname: 'XXX.XXX.XXX.XXX'
       program_name: '(null)'
       log: '%FTD-4-106023: Deny udp src AS_BGP:XXX.XXX.XXX.XXX/39701 dst 3.73-p7:XXX.XXX.XXX.XXX/49261 by access-group "CSM_FW_ACL" [0x97aa021a, 0x0]'

**Phase 2: Completed decoding.
       decoder: 'cisco-ios'
       id: '%FTD-4-106023'

**Phase 3: Completed filtering (rules).
       Rule id: '4714'
       Level: '4'
       Description: 'Cisco IOS warning message.'
**Alert to be generated.
```

### Expected results
Get all the information decoded into fields.

### Log / Alert examples
```
2021-07-07T18:00:01.980133-03:00 XXX.XXX.XXX.XXX %FTD-4-106023: Deny udp src 3.73-p7:XXX.XXX.XXX.XXX/49261 dst AS_BGP:XXX.XXX.XXX.XXX/20479 by access-group "CSM_FW_ACL_" [0x97aa021a, 0x0]
2021-07-07T18:00:02.002141-03:00 XXX.XXX.XXX.XXX %FTD-4-106023: Deny icmp src AS_BGP:XXX.XXX.XXX.XXX dst 3.73-p7:XXX.XXX.XXX.XXX (type 3, code 3) by access-group "CSM_FW_ACL_" [0x97aa021a, 0x0]
2021-07-07T18:00:02.012591-03:00 XXX.XXX.XXX.XXX %FTD-7-609001: Built local-host inside:XXX.XXX.XXX.XXX
2021-07-07T18:00:02.012591-03:00 XXX.XXX.XXX.XXX %FTD-6-305011: Built dynamic TCP translation from inside:XXX.XXX.XXX.XXX/51932 to 3.174-p8:XXX.XXX.XXX.XXX/51932
2021-07-07T18:00:02.012591-03:00 XXX.XXX.XXX.XXX %FTD-7-609001: Built local-host 3.174-p8:XXX.XXX.XXX.XXX
2021-07-07T18:00:02.034804-03:00 XXX.XXX.XXX.XXX %FTD-7-609002: Teardown local-host inside:XXX.XXX.XXX.XXX duration 0:00:00
2021-07-07T18:00:02.035916-03:00 XXX.XXX.XXX.XXX %FTD-6-305012: Teardown dynamic TCP translation from 5.1105-proxy_out:XXX.XXX.XXX.XXX/6380 to 3.172-p6:XXX.XXX.XXX.XXX/6380 duration 0:00:00
2021-07-07T18:00:02.216740-03:00 XXX.XXX.XXX.XXX %FTD-4-733100: [ Scanning] drop rate-1 exceeded. Current burst rate is 135 per second, max configured rate is 10; Current average rate is 276 per second, max configured rate is 5; Cumulative total count is 166017
2021-07-07T18:00:02.480098-03:00 XXX.XXX.XXX.XXX %FTD-4-106023: Deny udp src 3.73-p7:XXX.XXX.XXX.XXX/49261 dst 3.198-p2:XXX.XXX.XXX.XXX/59442 by access-group "CSM_FW_ACL_" [0x97aa021a, 0x0]
```
Ping me in case you need more samples.

### Log format reference 
https://www.cisco.com/c/en/us/td/docs/security/firepower/Syslogs/b_fptd_syslog_guide/security-event-syslog-messages.html
https://www.cisco.com/c/en/us/td/docs/security/firepower/Syslogs/b_fptd_syslog_guide.html
https://www.cisco.com/c/en/us/td/docs/security/firepower/Syslogs/b_fptd_syslog_guide/syslogs1.html
https://www.cisco.com/c/en/us/td/docs/security/firepower/Syslogs/b_fptd_syslog_guide/syslogs2.html
https://www.cisco.com/c/en/us/td/docs/security/firepower/Syslogs/b_fptd_syslog_guide/syslogs3.html
https://www.cisco.com/c/en/us/td/docs/security/firepower/Syslogs/b_fptd_syslog_guide/syslogs4.html
https://www.cisco.com/c/en/us/td/docs/security/firepower/Syslogs/b_fptd_syslog_guide/syslogs5.html
https://www.cisco.com/c/en/us/td/docs/security/firepower/Syslogs/b_fptd_syslog_guide/syslogs6.html
https://www.cisco.com/c/en/us/td/docs/security/firepower/Syslogs/b_fptd_syslog_guide/syslogs7.html
https://www.cisco.com/c/en/us/td/docs/security/firepower/Syslogs/b_fptd_syslog_guide/syslogs8.html
https://www.cisco.com/c/en/us/td/docs/security/firepower/Syslogs/b_fptd_syslog_guide/syslogs9.html
https://www.cisco.com/c/en/us/td/docs/security/firepower/Syslogs/b_fptd_syslog_guide/syslogs10.html

## Tests

- [ ] Added .ini test file for covering related rules
- [ ] Executed unit tests (runtests.py) for checking ruleset integrity
- [ ] Verified mitre.db integrity
- [ ] Verified compliance mapping 
- [ ] Verified no errors/warnings related in ossec.log
- [ ] Kibana shows alerts

Tested this with `ossec-logtest` and `wazuh-logtest`

**Comment by maumrsms** [comment]
Hello team!

I managed to create some additional decoders:
```
<!-- Cisco IOS custom -->
<!-- Created this one to capture all "Deny" events: -->
<decoder name="cisco-ios-default">
  <parent>cisco-ios</parent>
  <regex>(Deny)\s(\S+)\ssrc\s(\.*):(\d+.\d+.\d+.\d+)/(\d+)\sdst\s(\.*):(\d+.\d+.\d+.\d+)/(\d+)</regex>
  <order>action,protocol,srcinterface,srcip,srcport,dstinterface,dstip,dstport</order>
</decoder>

<!-- Created this other one to capture all icmp events since they don't include port number -->
<decoder name="cisco-ios-default">
  <parent>cisco-ios</parent>
  <regex>\.(\w+)\s(\S+)\ssrc\s(\.*):(\d+.\d+.\d+.\d+)\sdst\s(\.*):(\d+.\d+.\d+.\d+)</regex>
  <order>action,protocol,srcinterface,srcip,dstinterface,dstip</order>
</decoder>

<!-- Created 2 decoders to capture all "Built" events. They have 2 different formats -->
<decoder name="cisco-ios-default">
  <parent>cisco-ios</parent>
  <regex>(Built\s\.*):(\d+.\d+.\d+.\d+)$</regex>
  <order>description,srcip</order>
</decoder>

<decoder name="cisco-ios-default">
  <parent>cisco-ios</parent>
  <regex>(Built\s\.*):(\d+.\d+.\d+.\d+)/(\d+)\sto\s(\.*):(\d+.\d+.\d+.\d+)/(\d+)</regex>
  <order>description,srcip,srcport,dstinterface,dstip,dstport</order>
</decoder>

<!-- Same as "Built", "Teardown" events present 2 different formats -->
<decoder name="cisco-ios-default">
  <parent>cisco-ios</parent>
  <regex>(Teardown\s\.*):(\d+.\d+.\d+.\d+)\sduration\s(\.+)</regex>
  <order>description,srcip,duration</order>
</decoder>

<decoder name="cisco-ios-default">
  <parent>cisco-ios</parent>
  <regex>(Teardown\s\.*):(\d+.\d+.\d+.\d+)/(\d+)\sto\s(\.*):(\d+.\d+.\d+.\d+)/(\d+)\sduration\s(\.+)</regex>
  <order>description,srcip,srcport,dstinterface,dstip,dstport,duration</order>
</decoder>

```
With them I was able to decode almost every field in the previously presented samples. Anyways I noticed there are many event types that I haven't tested (I haven't received samples of every possible event).

Additionally, the related ruleset seem to trigger correctly.

**Comment by JavierBejMen** [comment]
This issue will be handled on https://github.com/wazuh/feed, a rework of cisco decoders and rules will be done.
