### ISSUE TITLE
Analyze and test how much memory SCA occupies

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#9281]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.0-RC10 | SCA | Agent | Sources | ALL |

## Goal

Find out how much memory the SCA module might take with the following purposes:
- Enrich stress tests with these results, providing the needed steps and parameters to maximize the memory consumption
- Learn how the module works under different conditions (idle/stressed)

## Components that take a variable amount of memory

- SCA policies in JSON objects
- Checks results
- Synchronization thread

## Test conditions

- The agent shall be connected to a manager (real or fake)
- Disable the agent leaky bucket
- Limits should be kept in the default values
- Load different amount of policies and checks for every test monitoring the resources usage
- Force different check results for every test
- After the stressing stage, leave the agent idle for 10 minutes (at less)
- Test on Linux and Windows agents

## Tasks

Explain with diagrams and descriptions in markdown files, and put it in the Wazuh / architecture directory an explanation of the operation and calculations of how much the peak(stressed) and post-peak consumption would be left in memory in standby.

- [x] Create [functionality diagrams](https://github.com/wazuh/wazuh/issues/9281#issuecomment-882718327).
- [x] Create [features description](https://github.com/wazuh/wazuh/issues/9281#issuecomment-881582627).
- [x] [Analyze memory consumption peak and post peak (standby) - Linux](https://github.com/wazuh/wazuh/issues/9281#issuecomment-883529271)
- [ ] Analyze memory consumption peak and post peak (standby) - Windows

**Comment by alromeros** [comment]
#9281 **update**:

## SCA's workflow and memory management

### **Workflow**

The _security configuration assessment module_ ([SCA](https://documentation.wazuh.com/4.0/user-manual/capabilities/sec-config-assessment/index.html)) performs hardening and configuration scans based on custom policies, created and maintained by **Wazuh**'s team based on **CIS** benchmarks.

This module is composed of a main thread, from which two other secondary threads diverge. These threads are:

- The **main thread**: In charge of parsing and converting to `JSON` the `YML` policies. These policies are then stored and executed accordingly. This thread contains high amounts of memory management and should be looked at closely.

- **wm_sca_dump_db_thread**: In charge of dumping the scan results into the manager's **SCA** database. This thread should be looked at closely, as it seems to be related to the suspicious memory peaks displayed in graphics from https://github.com/wazuh/wazuh-jenkins/issues/2727

- **wm_sca_request_thread**: In charge of requesting information if missing data is detected. Non-suspicious memory management.

### **Memory consumption and process monitoring**

After closely testing the memory increments and decreases in **Unix** and **Windows** systems, the two main elements that involve memory consumption in **SCA** seem to be:

- **Number of policies**: The total number of policies has a strong influence on the overall memory consumption of the module.
- **Length of each individual policy**: The number of checks seems to be especially relevant memory-wise.

Some other elements like **scan results** or **policy integrity** apparently increase memory consumption during small periods of time. However, after the memory allocated for their original values is freed, the total consumption ends up being the same as with the original files and results.

### **Memory-demanding functions and operations in SCA's source code**

Investigating `SCA`'s memory usage with **gdb** and **Valgrind**'s **massif** has led us to identify certain operations as particularly demanding. Though these two operations and functions are not the only ones to be taken into account, they appear to have a significant impact on overall memory consumption.

1. **libyaml**-related functions, specially `yaml_parse_file` and `yaml2json`.
2. The creation of a _Hash_ table for each policy in `wm_sca_main()` and checklist in `wm_sca_read_files()`.

And, though not as demanding as the first two operations, the `OSStore_create`-related functions and some **cjson** functions like `cJSON_Duplicate` seem to be always causing decent increments in memory.

That said, we will continue to investigate memory consumption in the module and keep updating this issue with any relevant information.

Best regards,
Álvaro Romero.

**Comment by alromeros** [comment]
#9281 **temporary update**:

### Possible explanation for the  unusual memory consumption displayed in  https://github.com/wazuh/wazuh-jenkins/issues/2727

**Windows**

![image](https://user-images.githubusercontent.com/52510206/125982876-67da2f38-0acd-42fe-a468-bf4d45897836.png)

Similar behavior has been replicated after manually changing scan results, which leads us to propose the following conjecture:
- Each change in the integrity of the results loaded in **SCA** causes a stall of several seconds in `wm_sca_dump_db_thread` that heavily interferes with the timing of the scan.
- This causes memory to never accumulate in particularly high peaks.
- However, by leaving the policies intact after the stress test, the scan runs properly at a much higher speed and without stalls, resulting in higher peaks at the end of the graph.

**Linux**

![image](https://user-images.githubusercontent.com/52510206/125983444-a41e5254-a696-4765-bbcc-6f560ff08ad1.png)

As with the case above, similar behavior has been replicated locally, which leads us to propose the following:

- Memory management is exactly the same as in **Windows**, but the freed memory is not reflected in the graph due to fragmentation issues.
- That's why the value is constant, with a level very similar to the peaks seen at the right part of the graph for **Windows**.

That said, we will continue to investigate memory consumption in the module and keep updating this issue with any relevant information.

**Comment by alromeros** [comment]
#9281 **update**:

## Functionality diagram example:

![Branching with opt and alt vpd](https://user-images.githubusercontent.com/52510206/126200087-b9d34207-2a43-4209-b734-775e0f36583a.png)

**Comment by alromeros** [comment]
#9281 **update:**

# Memory consumption diagrams

These next diagrams have been obtained with **Valgrind**'s [massif](https://www.valgrind.org/docs/manual/ms-manual.html), a tool that measures the total amount of heap memory used by a program.

## SCA without policies

**Diagram:**

![no_policy](https://user-images.githubusercontent.com/52510206/126357099-d0c1bf47-2a96-4292-a296-fe8a09bc8cae.png)

**Main memory allocations:**

Not relevant.

## SCA with a single policy with 3 checks

**Diagram:**

![small_policy_3_checks](https://user-images.githubusercontent.com/52510206/126358255-0293b70b-1750-44d4-88c7-a9457901dfdf.png)

**Main memory allocations:**

![allocators_3_checks](https://user-images.githubusercontent.com/52510206/126358336-1ee89815-a760-4a2b-ad29-8d36662a7851.png)


## SCA with a single policy with 21 checks

**Diagram:**

![small_policy](https://user-images.githubusercontent.com/52510206/126358442-cf2b8ff8-b815-4bd6-b430-cc6fc3eeba85.png)

**Main memory allocations:**

![small_policy_allocators](https://user-images.githubusercontent.com/52510206/126358496-cdcb35b1-60e6-4573-9150-ec6cf6c9fd07.png)

## SCA with two small policies

**Diagram:**

![two](https://user-images.githubusercontent.com/52510206/126360914-cc8aa6d4-6c41-4ac1-95c6-ebf7f6e187c6.png)

**Main memory allocations:**

![two_allocators](https://user-images.githubusercontent.com/52510206/126360955-1431081a-c26d-44b5-93ee-a54bcdddce61.png)


## SCA with a single policy with 1000+ checks

**Diagram:**
![highest_peak](https://user-images.githubusercontent.com/52510206/126358755-33e62e10-1646-4a91-a041-55c2198cdb3a.png)

**Main memory allocations:**

![highest_allocators](https://user-images.githubusercontent.com/52510206/126358979-b6d0632a-42be-49a3-b3d8-a89a7f37f01b.png)

## Conclusions

_In progress_

**Comment by alromeros** [comment]
# Conclusions

After checking both the previous graphs and the general memory analysis in https://github.com/wazuh/wazuh/issues/9281#issuecomment-881582627, we've come to reach the following conclusions:

- The overall memory consumption in **SCA** is heavily determined by the total number of checks that are stored in `cis_db_for_hash`. Other factors, like the length of said checks, descriptions in checks, number of policies, etc. influence the total storage, but significantly less than the number of checks. **In short, the best way to stress the memory consumption of the module is to scan policies with a considerably high number of checks.**

- The memory management is practically the same in both **Windows** and **Unix**-like **OS**. We consider https://github.com/wazuh/wazuh/issues/9281#issuecomment-882456232 to provide a valid explanation for the differences shown in the graphs.

- There are still some unknown factors that determine memory consumption in **peaks**, as they seem to vary drastically between equal scans. However, the memory outside the peaks seems to remain constant between scans.

- These peaks are principally caused by **yaml-related** functions, while the constant memory storage is mainly filled by many **cJSON** objects that contain each one of the checks and information from the policy.

- The memory consumption related to these **cJSON** objects mainly depends on three main functions: `cJSON_New_item` (the object constructor), `cJSON_strdup` (the **strdup**-like function used to fill the **cJSON** object), and `cJSON_Duplicate` (used to duplicate objects, but also to call the constructor and fill a new object). However, these functions end up fulfilling the same goal of keeping the relevant policy information saved in memory, so their memory consumption should be seen as a whole. 

- Though the increase in memory is directly related to the length and number of policies, we are currently unable to establish a 100% accurate constant ratio between the two values. However, we can establish an approximate consumption considering the following charts:

**Memory usage after SCA scan:**
|Number of checks | Process whole memory  | Policy in memory* |
--- | --- | --- 
|10|~190kib|~13,4kib|
|100|~290kib|~118,6kib|
|1000|~1,4Mib|~1182,6kib|
|1000|~12,5Mib|~11,5Mib|
|10000|~123Mib|~116,2Mib|

We see an approximate correlation of **1,1Kb/check** that remains constant during the whole process, even when the module is sleeping after the scan. 

A similar chart can be made for memory consumption during the scan, when the memory is stabilized after the **yaml**-related peaks. The last column shows the overall memory consumption during these peaks.

**Memory usage during scan:**
|Number of checks | Process whole memory when the scan is stabilized | Policy in memory when the scan is stabilized* | Process whole memory during peak |
--- | --- | --- | --- 
|10|~190kib|~13,4kib|~259kib|
|100|~350kib|~165,7kib|~414,8kib|
|1000|~1,9Mib|~1,607Mib|~2,7Mib|
|1000|~17,8Mib|~16,3Mib|~22,9Mib|
|10000|~176Mib|~163,3Mib|~204,5Mib|

Giving us an approximate correlation of **1,6Kb/check**. This memory is filled during the first scan but keeps constant in subsequent scans, and only reaches lower values when the module is sleeping. For more information about memory management between scans, check this [graph](https://user-images.githubusercontent.com/52510206/126984960-25de711b-2edb-45fa-ba83-127c1d040485.png).

**\* Sum of `cJSON_strdup`, `cJSON_New_item` and `cJSON_Duplicate` memory consumption.**

Best regards, 
Álvaro Romero.

**Comment by chemamartinez** [comment]
Thanks @alromeros! GJ
