### ISSUE TITLE
Analyze and test how much memory CIS-CAT occupies

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#9282]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.0-RC10 | CIS-CAT | Agent | Sources | ALL |

## Goal

Find out how much memory the CIS-CAT module might take with the following purposes:
- Enrich stress tests with these results, providing the needed steps and parameters to maximize the memory consumption
- Learn how the module works under different conditions (idle/stressed)

## Components that take a variable amount of memory

- CIS-CAT reports which are parsed and sent to the manager

## Test conditions

- The agent shall be connected to a manager (real or fake)
- Disable the agent leaky bucket
- Limits should be kept in the default values
- Load different amount of policies and checks for every test monitoring the resources usage
- After the stressing stage, leave the agent idle for 10 minutes (at less)
- Test on Linux and Windows agents

## Tasks

Explain with diagrams and descriptions in markdown files, and put it in the Wazuh / architecture directory an explanation of the operation and calculations of how much the peak(stressed) and post-peak consumption would be left in memory in standby.

- [x] [Create functionality diagrams.](https://github.com/wazuh/wazuh/issues/9282#issuecomment-883242116)
- [x] [Create features description.](https://github.com/wazuh/wazuh/issues/9282#issuecomment-883213589)
- [x] [Analyze memory consumption peak and post peak (standby) - Linux](https://github.com/wazuh/wazuh/issues/9282#issuecomment-885601578)
- [x] [Analyze memory consumption peak and post peak (standby) - Windows](https://github.com/wazuh/wazuh/issues/9282#issuecomment-885753199)

**Comment by MarcelKemp** [comment]
## CIS-CAT workflow and memory management

### CIS-CAT workflow:

At the beginning, all the necessary checks are carried out for the module to function correctly (check configuration, CIS-CAT, java...).

Once verified, we have an infinite loop in which the following actions are performed:

- We check the timestamp set in the configuration and apply them through the `sleep()` function.

- Once the sleep time is over, the CIS-CAT script will be executed first, scanning the system and reporting the results in different files (_txt_ and _xml_). These files are then parsed. 

- It starts first with the _txt file_, which contains the results of the tests in a generic way and keeps saving the relevant information that has been parsed in memory (mostly `scan_info`).

- Then, it starts preparsing the xml file, obtaining a temporary file in which the information formatted in different nodes is stored with the specific information of each rule, and after that the temporary file is opened in another function to parse and obtain the different nodes and store them in memory (`rule_info`).

- Once we have all the information (both generic and specific), we convert the data to a _JSON_ structure to send the stored information to the manager.

- At the end, the memory that has already been sent is eliminated, thus ending an iteration with the loop and starting again with the sleep.


### Memory management:

When parsing the results obtained by the CIS-CAT script, we open the different files generated (we even generate a temporary xml file in the preparser that is divided into nodes and contains all the specific results of each rule) and we store the data in memory relevant that we are going to send to the manager later.

This data is mainly stored in the `wm_scan_data` and `wm_rule_data` structures, which are released as the data is sent and will no longer be used.

And the structure that is stored until the process is stopped is `wm_ciscat`, which contains information about the configuration, the various paths and the evaluations.

**Comment by MarcelKemp** [comment]
## CIS-CAT functionality diagram
![cis-cat_diagram](https://user-images.githubusercontent.com/37207742/126296639-9d6bff26-d054-42c3-a59f-f171b33fcfa4.png)

**Comment by MarcelKemp** [comment]
## Analyze memory consumption - Linux (4.2)

In the following plots we can visualize the memory consumption for the `wazuh-modulesd` daemon, according to the different configurations with which they have been tested.

Among the different configurations, the following have been modified: the _interval_, the _timeout_ or try to execute the different _benchmarks_ (both valid and invalid), to cause the failure and verify that it continues to work correctly.

As a common factor, almost all of them have been run connected to a manager (since it is mandatory for the integration to work) and all other components are disabled.


<details><summary>CIS-CAT manager disconnected</summary>

+ <summary>Description</summary>

  This test is the only one in which it has been verified what happens in the CIS-CAT module when the agent does not establish the connection with the manager correctly. 
  And we can see that CIS-CAT is running but without executing any benchmark.


+ <details><summary>Plot</summary>

  ![no_connect](https://user-images.githubusercontent.com/37207742/126757270-d8b6c9e7-92b1-4598-a0a2-3e37b2a3f7d9.png)


   </details>
+ <details><summary>Configuration</summary>

  ```
  <!-- Manager disconnected -->
  <wodle name="cis-cat">
    <disabled>no</disabled>
    <timeout>1800</timeout>
    <interval>600s</interval>
    <scan-on-start>yes</scan-on-start>

    <java_path>/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin</java_path>
    <ciscat_path>wodles/ciscat</ciscat_path>

    <content type="xccdf" path="benchmarks/CIS_CentOS_Linux_7_Benchmark_v2.1.1-xccdf.xml">
      <profile>xccdf_org.cisecurity.benchmarks_profile_Level_2_-_Server</profile>
    </content>

  </wodle>
  ```


   </details>
   
</details>

<details><summary>CIS-CAT interval 1m</summary>

+ <summary>Description</summary>

 The behavior has been tested with a single benchmark and a 1 minute interval.
 Everything has worked well, but it may be the case that it took a little longer to analyze the results obtained from the script, which would mean the following _Warning: "Interval overtaken"_, causing the next scan to start instantly.


+ <details><summary>Plots</summary>

  ![1min](https://user-images.githubusercontent.com/37207742/126759725-1ddbe090-7295-4ec3-9782-6a7324c3f7ba.png)

   </details>
+ <details><summary>Configuration</summary>

  ```
  <wodle name="cis-cat">
    <disabled>no</disabled>
    <timeout>1800</timeout>
    <interval>60s</interval>
    <scan-on-start>yes</scan-on-start>

    <java_path>/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin</java_path>
    <ciscat_path>wodles/ciscat</ciscat_path>

    <content type="xccdf" path="benchmarks/CIS_CentOS_Linux_7_Benchmark_v2.1.1-xccdf.xml">
      <profile>xccdf_org.cisecurity.benchmarks_profile_Level_2_-_Server</profile>
    </content>

  </wodle>
  ```


   </details>
   
</details>

<details><summary>CIS-CAT interval 10min</summary>

+ <summary>Description</summary>

 In this test, only 1 benchmark is tested but modifying the interval to 10min, to see if there is any difference with the previous test.

 But as we can see, the only difference is between the time from one execution to the next, where it is observed that it does not perform any action in memory, remaining stable.

+ <details><summary>Plot</summary>

  ![10min](https://user-images.githubusercontent.com/37207742/126762761-cab3e0dd-9d1c-4bfb-879c-f306ee169b08.png)


   </details>
+ <details><summary>Configuration</summary>

  ```
  <wodle name="cis-cat">
    <disabled>no</disabled>
    <timeout>1800</timeout>
    <interval>600s</interval>
    <scan-on-start>yes</scan-on-start>

    <java_path>/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin</java_path>
    <ciscat_path>wodles/ciscat</ciscat_path>

    <content type="xccdf" path="benchmarks/CIS_CentOS_Linux_7_Benchmark_v2.1.1-xccdf.xml">
      <profile>xccdf_org.cisecurity.benchmarks_profile_Level_2_-_Server</profile>
    </content>

  </wodle>
  ```


   </details>
   
</details>

<details><summary>CIS-CAT benchmarks</summary>

+ <summary>Description</summary>

 For this test, the 10min interval has been maintained to be able to easily differentiate the plots and several benchmarks (both functional and invalid) have been added to the config to check the operation in memory.

 We can clearly observe 2 memory peaks in each analysis, which correspond to the 2 benchmarks that are executed correctly (`CIS_Apache_Tomcat_5.5-6.0_Benchmark_v1.0.0.xml` and `CIS_Oracle_Linux_7_Benchmark_v2.0.0-xccdf.xml`), since the other 5 show an error because they cannot be executed.

+ <details><summary>Plot</summary>

  ![2bench_10min](https://user-images.githubusercontent.com/37207742/126765285-da0b67df-ad8d-4c95-87e3-55e3409ae2f0.png)

   </details>
+ <details><summary>Configuration</summary>

  ```
  <wodle name="cis-cat">
    <disabled>no</disabled>
    <timeout>1800</timeout>
    <interval>600s</interval>
    <scan-on-start>yes</scan-on-start>

    <java_path>/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin</java_path>
    <ciscat_path>wodles/ciscat</ciscat_path>

    <content path="benchmarks/CIS_Google_Chrome_Benchmark_v1.2.0-xccdf.xml" type="xccdf">
    </content>

    <content path="benchmarks/CIS_Oracle_Linux_7_Benchmark_v2.0.0-xccdf.xml" type="xccdf">
    </content>

    <content path="benchmarks/CIS_Red_Hat_Enterprise_Linux_7_Benchmark_v2.1.1-xccdf.xml" type="xccdf">
    </content>

    <content path="benchmarks/CIS_Apache_Tomcat_5.5-6.0_Benchmark_v1.0.0.xml" type="xccdf">
    </content>

    <content type="xccdf" path="benchmarks/CIS_CentOS_Linux_7_Benchmark_v2.1.1-xccdf.xml">
      <profile>xccdf_org.cisecurity.benchmarks_profile_Level_2_-_Server</profile>
    </content>

    <content path="benchmarks/CIS_Mozilla_Firefox_24_ESR_Benchmark_v1.0.0-xccdf.xml" type="xccdf">
    </content>

    <content path="benchmarks/CIS_Mozilla_Firefox_38_ESR_Benchmark_v1.0.0-xccdf.xml" type="xccdf">
    </content>

  </wodle>
  ```


   </details>
   
</details>

### Conclusions

After running various tests and checking the results against the memory, I have obtained the following information:

- At startup, it always saves generic information about the configuration (`wm_ciscat_setup()`) in memory and if that information is correct, the infinite loop will be executed and that memory will be occupied until the daemon stops. This case can be easily observed in the plot of **_CISCAT manager disconnected_**, where it is in the loop but does not get to execute any benchmark, thus visualizing that reserved memory in `wm_ciscat_main()`.

- According to the interval, to prevent the _Warning_ from showing, it is necessary to set a value slightly higher than the analysis time of all the benchmarks that you run. Although in the case of stressing the module, you can set a very short interval so that it runs instantly once the analysis that is running is finished (taking into account that this Warning should be displayed).

- However, for the timeout, it is mandatory that the established time is greater than the execution of the benchmarks for the module to be executed correctly.

- According to the number of benchmarks executed, only those from which the report is obtained when executing the script will affect the memory, because those that do not have any report will fail showing in the log, a message similar to the following: _"Failed reading scan results for policy 'benchmark' "_. In addition, those from which reports are obtained will be executed according to the order established in the configuration, saving the information in memory and finally freeing that memory to execute the next benchmark.


Finally, according to the memory peak existing in all the plots, they always reserve the same size _1.4mb_. And it always appears in the first execution of the policy analysis (in this case for the benchmark: `CIS_CentOS_Linux_7_Benchmark_v2.1.1-xccdf.xml`), at the moment of finishing the `wm_ciscat_xml_parser()` and creating the cJSON structure. Since we see that once it reaches the highest point, then the memory is completely released.

Therefore, the memory loading pattern goes step by step through the following functions: `wm_ciscat_txt_parser` -> `wm_ciscat_preparser` -> `wm_ciscat_xml_parser` -> `wm_ciscat_send_scan` -> Free memory after sending the scan

This pattern can best be observed in the plot of the **_CIS-CAT interval 10min_**. And it can also be observed in **_CIS-CAT benchmarks_** analyzing two benchmarks in a row.

**Comment by MarcelKemp** [comment]
## Analyze memory consumption - Windows (4.2)

For Windows the analysis is practically similar, since the only difference with Linux are the paths and the execution of the script (instead of `.sh` it is a `.bat`).

But the rest of the structure remains intact, thus performing  the same flow of actions: `wm_ciscat_txt_parser` -> `wm_ciscat_preparser` -> `wm_ciscat_xml_parser` -> `wm_ciscat_send_scan` -> Free memory after sending the scan

I have been able to verify that the linux graphs are very similar to the graph that **`Perfmon`** shows me when I monitor memory (specifically, _"`% commited bytes in use`"_, although it is the whole system but the only one that is committing data in memory is **_wazuh-agent_** every minute).

<details><summary>Performance monitor</summary>

+ <details><summary>Plot</summary>

   ![ciscat-memory](https://user-images.githubusercontent.com/37207742/126811878-d2c4290c-e21d-4979-87b2-2cd8627eb313.gif)

   </details>

+ <details><summary>Configuration</summary>
   Everything disabled except the ciscat wodle.

   ```
  <!-- CIS policies evaluation -->
  <wodle name="cis-cat">
    <disabled>no</disabled>
    <timeout>1800</timeout>
    <interval>60s</interval>
    <scan-on-start>yes</scan-on-start>

    <java_path>\\server\jre\bin\java.exe</java_path>
    <ciscat_path>wodles\cis-cat</ciscat_path>

    <content type="xccdf" path="benchmarks\CIS_Microsoft_Windows_10_Enterprise_Release_1607_Benchmark_v1.2.0-xccdf.xml">
    </content>
  </wodle>
   ```

   </details>
</details>

**Comment by MarcelKemp** [comment]
## Improve stress tests

The most optimal way to stress the _CIS-CAT_ module based on memory consumption is to execute the benchmark that contains the largest number of checks possible, since it is what will consume the most memory, where the peak will be found at the moment it is save parsed reports in the structures.

> _Note_: The number of benchmarks is indifferent, because they are executed sequentially, so at the moment of parsing one, its memory will be freed and the next one will be executed.

For time settings: Ideally, a very short `interval` for the next analysis to be executed just after the current one ends and a `timeout` much longer than the execution time, so that the usual flow ends correctly.

**Comment by chemamartinez** [comment]
Thanks @MarcelKemp! GJ
