### ISSUE TITLE
Analyze and test how much memory Google Cloud occupies

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#9283]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.0-RC10 | Google Cloud | Agent | Sources | ALL |

## Goal

Find out how much memory the GCP module might take with the following purposes:
- Enrich stress tests with these results, providing the needed steps and parameters to maximize the memory consumption
- Learn how the module works under different conditions (idle/stressed)

## Components that take a variable amount of memory

- The GCP python script which handles the pull and processing of the events

## Test conditions

- The agent shall be connected to a manager (real or fake)
- Disable the agent leaky bucket
- Limits should be kept in the default values
- Load different amount of policies and checks for every test monitoring the resources usage
- After the stressing stage, leave the agent idle for 10 minutes (at less)
- Test on Linux and Windows agents

## Tasks

Explain with diagrams and descriptions in markdown files, and put it in the Wazuh / architecture directory an explanation of the operation and calculations of how much the peak(stressed) and post-peak consumption would be left in memory in standby.

- [x] [Create feature description.](https://github.com/wazuh/wazuh/issues/9283#issuecomment-881397436)
- [x] [Create functionality diagrams. ](https://github.com/wazuh/wazuh/issues/9283#issuecomment-882495112)
- [x] [Analyze memory consumption peak and post peak (standby) - Linux](https://github.com/wazuh/wazuh/issues/9283#issuecomment-885596892)
- [x] [Analyze memory consumption peak and post peak (standby) - Windows](https://github.com/wazuh/wazuh/issues/9283#issuecomment-885596892)

**Comment by juanmanuelug** [comment]
Hi team,

I have been analyzing the Google Cloud Module and, I will explain the behaviour of the memory.
The main point in the Google Cloud Module is the python script that is in charge of the pull and processing of the messages that we get from the Google Cloud API.  

At a first sight and having in mind the memory analysis, we can differentiate the code into two parts. The first one, which is more insignificant in memory impact and the second one, which contains the majority of the memory impact in the script.

Said this, I will get into more details about the workflow.  

At first instance, we have the part of the code that impacts the least in the memory. It is formed by: 
- Getting the arguments for the script(subscription id, credentials, max messages...).
- Creating the logger that will return the messages.
- The checking of the permissions. 
- The instantiation of the object with the Google Cloud credentials.

Once we finish with the part of the code shown above, we could find the main functionality of the script:
- Request a number of messages from Google Cloud
- Receive the messages from Google Cloud
- Give format to every message received
- Provides the events to Wazuh
- Repeat the process until we reach the maximum number of messages that we want to process

Finally and turning our attention to the analysis of the memory, this last process will be responsible for most of the impact on the memory. That´s because it will send to store every processed message that we get from the Google Cloud API.

Regards,
Juan Manuel.

**Comment by juanmanuelug** [comment]
Hi team,

Here I leave you the functionality diagram of the Google Cloud Module.

![gcloudSecuencia](https://user-images.githubusercontent.com/74183704/126157443-b7589cec-9096-425d-a815-c196a9ae7caa.jpg)

Regards,
Juan Manuel.

**Comment by juanmanuelug** [comment]
# Memory consumption diagrams
The diagrams shown below represent the peaks of memory consumed during the execution of the Google Cloud Module, these diagrams also include the functions involved. 

We represent two different use-cases, it is important to note that in both cases, we receive 100 events from Google Cloud:

## Script execution
In this case, we only monitor the script that is executed to receive, format and send the events. We can consider that we reach the peak once we get all the events, then after it gives the format for every event, it will send then to the agents that it is represented as the final descent of the diagram.

Diagram:
![diagramitajuanma](https://user-images.githubusercontent.com/74183704/126773243-8f60a8ee-d7bc-489a-bbb8-1dbdd167c58e.png)

Main memory allocations:
![allocatorsjuanma](https://user-images.githubusercontent.com/74183704/126773457-4f094e13-df2f-473d-b997-ab709529e451.png)

## Google cloud module
In progress

## Conclusions
In progress

**Comment by chemamartinez** [comment]
Thanks @juanmanuelug! GJ
