### ISSUE TITLE
Analyze and test how much memory GitHub integration occupies

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#9317]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.0 | GitHub module | Agent | Sources | All |

## Goal

Find out how much memory the component might take.

# Tasks

Explain with diagrams and descriptions in markdown files, and put it in the wazuh / architecture directory an explanation of the operation and calculations of how much the peak(stressed) and post-peak consumption would be left in memory in standby.

- [x] Create functionality diagrams.
- [x] Create features description.
- [x] Analyze memory consumption peak and post peak (standby) - Linux
- [x] Analyze memory consumption peak and post peak (standby) - Windows

Help yourself with tools like `massif`.

## Components that take a variable amount of memory

- Configuration structure (including `auth` blocks).
- Organization fails structure.
- Message payload sent to manager.
- Next page URL.
- Error message.
- HTTP request.
- HTTP response.

## Test conditions

- The agent shall be connected to a manager (real or fake).
- Configure at less 10 organizations.
- Mock the response of the GitHub API.
- Simulate successful cases with responses near to 1MB (maximum allowed by default).
- Simulate error cases with responses over 1MB (maximum allowed by default).
- Simulate other error cases.
- Simulate responses with many next pages.
- After the stressing stage, leave the agent idle for 10 minutes (at less).

**Comment by cborla** [comment]
Test # 1
1 Organization
928 KB data json
Collection interval 30 seconds

ossec.conf
```
  <github>
    <enabled>yes</enabled>
    <interval>30s</interval>
    <time_delay>1s</time_delay>
    <curl_max_size>1M</curl_max_size>
    <only_future_events>yes</only_future_events>
    <api_auth>
        <org_name>test3</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_parameters>
        <event_type>git</event_type>
    </api_parameters>
  </github>
```

![image](https://user-images.githubusercontent.com/41765669/126645578-e0613d9a-13d4-41b5-9522-98d353bca95d.png)
[sample1MB.txt](https://github.com/wazuh/wazuh/files/6862486/sample1MB.txt)

**Comment by cborla** [comment]
Test # 2
2 Organization
928 KB data json
Collection interval 30 seconds

ossec.conf

```
  <github>
    <enabled>yes</enabled>
    <interval>30s</interval>
    <time_delay>1s</time_delay>
    <curl_max_size>1M</curl_max_size>
    <only_future_events>yes</only_future_events>
    <api_auth>
        <org_name>test2</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test3</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_parameters>
        <event_type>git</event_type>
    </api_parameters>
  </github>
```
![image](https://user-images.githubusercontent.com/41765669/126651445-34b6c4bd-ef9e-470a-a802-276d4acd35ed.png)

**Comment by cborla** [comment]
Test # 3
10 Organization
928 KB data json
Collection interval 1 minute

ossec.conf
```
 <github>
    <enabled>yes</enabled>
    <interval>1m</interval>
    <time_delay>1s</time_delay>
    <curl_max_size>1M</curl_max_size>
    <only_future_events>yes</only_future_events>
    <api_auth>
        <org_name>test2</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test3</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test4</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test5</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test6</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test7</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test8</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test9</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test10</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test11</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_parameters>
        <event_type>git</event_type>
    </api_parameters>
  </github>
```
![image](https://user-images.githubusercontent.com/41765669/126655414-a7715b97-e3b8-4be2-9915-a027d9d020c5.png)

**Comment by cborla** [comment]
Test # 4
10 Organization
928 KB data json
Collection interval 5 minute

ossec.conf

 ```
<github>
    <enabled>yes</enabled>
    <interval>1m</interval>
    <time_delay>1s</time_delay>
    <curl_max_size>1M</curl_max_size>
    <only_future_events>yes</only_future_events>
    <api_auth>
        <org_name>test2</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test3</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test4</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test5</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test6</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test7</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test8</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test9</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test10</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test11</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_parameters>
        <event_type>git</event_type>
    </api_parameters>
  </github>
```
![image](https://user-images.githubusercontent.com/41765669/126668972-ea59347a-28cb-4d88-bf25-048c9b0a9941.png)

**Comment by cborla** [comment]
Test # 5
10 Organization
928 KB data json
Collection interval 10 minutes

ossec.conf

```
<github>
   <enabled>yes</enabled>
   <interval>10m</interval>
   <time_delay>1s</time_delay>
   <curl_max_size>1M</curl_max_size>
   <only_future_events>yes</only_future_events>
   <api_auth>
       <org_name>test2</org_name>
       <api_token>insert_personal_access_token</api_token>
   </api_auth>
   <api_auth>
       <org_name>test3</org_name>
       <api_token>insert_personal_access_token</api_token>
   </api_auth>
   <api_auth>
       <org_name>test4</org_name>
       <api_token>insert_personal_access_token</api_token>
   </api_auth>
   <api_auth>
       <org_name>test5</org_name>
       <api_token>insert_personal_access_token</api_token>
   </api_auth>
   <api_auth>
       <org_name>test6</org_name>
       <api_token>insert_personal_access_token</api_token>
   </api_auth>
   <api_auth>
       <org_name>test7</org_name>
       <api_token>insert_personal_access_token</api_token>
   </api_auth>
   <api_auth>
       <org_name>test8</org_name>
       <api_token>insert_personal_access_token</api_token>
   </api_auth>
   <api_auth>
       <org_name>test9</org_name>
       <api_token>insert_personal_access_token</api_token>
   </api_auth>
   <api_auth>
       <org_name>test10</org_name>
       <api_token>insert_personal_access_token</api_token>
   </api_auth>
   <api_auth>
       <org_name>test11</org_name>
       <api_token>insert_personal_access_token</api_token>
   </api_auth>
   <api_parameters>
       <event_type>git</event_type>
   </api_parameters>
 </github>
```

![image](https://user-images.githubusercontent.com/41765669/126683010-06e14c1b-5ec2-4012-85be-db8b78f33b42.png)

**Comment by cborla** [comment]
Test # 6
10 Organization
900 json events per request (view attached sample json)
Collection interval 1 minute

ossec.conf

```
<github>
   <enabled>yes</enabled>
   <interval>1m</interval>
   <time_delay>1s</time_delay>
   <curl_max_size>1M</curl_max_size>
   <only_future_events>yes</only_future_events>
   <api_auth>
       <org_name>test2</org_name>
       <api_token>insert_personal_access_token</api_token>
   </api_auth>
   <api_auth>
       <org_name>test3</org_name>
       <api_token>insert_personal_access_token</api_token>
   </api_auth>
   <api_auth>
       <org_name>test4</org_name>
       <api_token>insert_personal_access_token</api_token>
   </api_auth>
   <api_auth>
       <org_name>test5</org_name>
       <api_token>insert_personal_access_token</api_token>
   </api_auth>
   <api_auth>
       <org_name>test6</org_name>
       <api_token>insert_personal_access_token</api_token>
   </api_auth>
   <api_auth>
       <org_name>test7</org_name>
       <api_token>insert_personal_access_token</api_token>
   </api_auth>
   <api_auth>
       <org_name>test8</org_name>
       <api_token>insert_personal_access_token</api_token>
   </api_auth>
   <api_auth>
       <org_name>test9</org_name>
       <api_token>insert_personal_access_token</api_token>
   </api_auth>
   <api_auth>
       <org_name>test10</org_name>
       <api_token>insert_personal_access_token</api_token>
   </api_auth>
   <api_auth>
       <org_name>test11</org_name>
       <api_token>insert_personal_access_token</api_token>
   </api_auth>
   <api_parameters>
       <event_type>git</event_type>
   </api_parameters>
 </github>
```
![image](https://user-images.githubusercontent.com/41765669/126686479-f3f0fe35-efe5-4649-93fd-a2481ab5c221.png)

[sample.txt](https://github.com/wazuh/wazuh/files/6864301/sample.txt)

**Comment by cborla** [comment]
Test # 7 
2MB file refused
Sample time span: 7 minutes aprox.
1 Organization.
2 MB data json.
Collection interval 30 seconds.

ossec.conf

<github>
   <enabled>yes</enabled>
   <interval>30s</interval>
   <time_delay>1s</time_delay>
   <curl_max_size>1M</curl_max_size>
   <only_future_events>yes</only_future_events>
   <api_auth>
       <org_name>test2</org_name>
       <api_token>insert_personal_access_token</api_token>
   <api_parameters>
       <event_type>git</event_type>
   </api_parameters>
 </github>
 
 Case 1: Only github configuration
 
![image](https://user-images.githubusercontent.com/41765669/126715658-749940bf-85b9-4551-bebf-b84eb8720662.png)

massif file:
[massif.out.190436.txt](https://github.com/wazuh/wazuh/files/6865463/massif.out.190436.txt)

**Comment by cborla** [comment]
Test # 8
Sample time span: 10 hours aprox.
10 Organization.
1 MB data json.
Collection interval 10 minutes.

ossec.conf

```
<github>
    <enabled>yes</enabled>
    <interval>10m</interval>
    <time_delay>1s</time_delay>
    <curl_max_size>1M</curl_max_size>
    <only_future_events>yes</only_future_events>
    <api_auth>
        <org_name>test2</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test3</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test4</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test5</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test6</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test7</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test8</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test9</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test10</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test12</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_parameters>
        <event_type>git</event_type>
    </api_parameters>
  </github>
```
Case 1: Only github configuration
![image](https://user-images.githubusercontent.com/41765669/126776204-a7e37c68-53f7-45de-b72d-417867a09464.png)

massif flie:
[massif.out.231214.txt](https://github.com/wazuh/wazuh/files/6868411/massif.out.231214.txt)

**Comment by cborla** [comment]
Test # 9
Sample time span: 12 minutes aprox.
2 Organization.
1 MB data json.
Collection interval 30 seconds.

Command to collect:
`iotop -b -p PROCESSID > sample.txt`

ossec.conf
```
 <github>
    <enabled>yes</enabled>
    <interval>30s</interval>
    <time_delay>1s</time_delay>
    <curl_max_size>1M</curl_max_size>
    <only_future_events>yes</only_future_events>
    <api_auth>
        <org_name>test12</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test11</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_parameters>
        <event_type>git</event_type>
    </api_parameters>
  </github>
```

Case 1: Only github configuration

![image](https://user-images.githubusercontent.com/41765669/126839747-22f308ba-3351-4cfd-8fcb-4f4a1252b744.png)

Sample file:
[DiskStatus.xlsx](https://github.com/wazuh/wazuh/files/6871122/DiskStatus.xlsx)

**Comment by cborla** [comment]
Test # 10
Sample time span: 7 minutes aprox.
2 Organization.
100 json events.
Collection interval 1 minute.

Command to collect events:

```
(Using Wpr.exe)
* wpr.exe -HeapTracingConfig wazuh-agent.exe enable
* Stop win-agent
* wpr.exe -start Heap -filemode
* Start win-agent
* Test the scenario.
* wpr.exe -stop C:\Users\workspace\integration-github\wpa\testGithub.etl
* wpr.exe -HeapTracingConfig wazuh-agent.exe disable
```

ossec.conf
```
 <github>
    <enabled>yes</enabled>
    <interval>1m</interval>
    <time_delay>1s</time_delay>
    <curl_max_size>1M</curl_max_size>
    <only_future_events>yes</only_future_events>
    <api_auth>
        <org_name>test12</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_auth>
        <org_name>test11</org_name>
        <api_token>insert_personal_access_token</api_token>
    </api_auth>
    <api_parameters>
        <event_type>git</event_type>
    </api_parameters>
  </github>
 
``` 
Case 1: Only github configuration.
![image](https://user-images.githubusercontent.com/41765669/127166949-e78fa168-4fd1-471e-96d8-80061bf93957.png)

Used Windows Performance Analyzer to visualize it.

As graph showns, every 1 minute, github wazuh module do a request to collect github events, blue peak represent request without a server response, and red peak represent request with server response.

**Comment by cborla** [comment]
```
@startuml wm_github
    
    box "Github Module" #LightBlue
    participant main
    participant wmodules
    participant config
    participant wmodules_github
    participant thread
    participant wm_github
    participant mq_op
    end box

    activate main #Red
    main -> wmodules : wm_config()
    wmodules -> config : ReadConfig()
    config -> config : read_main_elements()
    config -> config : Read_Github()
    config -> wmodules_github : wm_github_read()
    config <-- wmodules_github
    wmodules <-- config
    main <-- wmodules

    main -> thread ++ #Red : CreateThreadJoinable()
    main <-- thread
    thread -> wm_github : wm_github_main (config) 
    wm_github -> mq_op : StartMQ()
    wm_github <-- mq_op


    database github_server
    wm_github -> wm_github : wm_github_execute_scan (initial_scan TRUE)
    rnote over wm_github, github_server: **Scan Block**
    
    loop while (TRUE)
        wm_github -> wm_github : sleep (interval)
        wm_github -> wm_github : wm_github_execute_scan (initial_scan FALSE)
        rnote over wm_github, github_server: **Scan Block**
    end
@enduml
```
![image](https://user-images.githubusercontent.com/41765669/127371527-75073a5d-0689-41d6-b5c6-f43b00668b0c.png)

**Comment by cborla** [comment]
```
@startuml wm_github

    box "Scan Block \n wm_github_execute_scan() Sequence Diagram" #LightBlue
    participant wm_github
    participant wmodules
    participant url
    end box

    loop while (Organization != NULL)
        wm_github -> wmodules : wm_state_io (WM_IO_READ)
        wm_github <-- wmodules
        loop #LightGrey while (!scan_finished)

            wm_github -> url : wurl_http_request (GET_METHOD)
            database github_server
            url -> github_server : API get events
            url <-- github_server
            wm_github <-- url : wurl_http_request 
            loop for (response_lenght)
                wm_github -> wmodules : wm_sendmsg (Save Event)
                wm_github <-- wmodules : wm_sendmsg
            end

            wm_github -> wmodules : wm_read_http_header_element (next_page)
            wm_github <-- wmodules
        end
        wm_github -> url : wurl_free_response
        wm_github <-- url

        alt #LightGrey Scan Fail
            wm_github -> wm_github : wm_github_scan_failure_action (fails, org_name, error_msg, queue_fd)
            alt (Fails >= 3)
                wm_github -> wmodules : wm_sendmsg (fail message)
                wm_github <-- wmodules : wm_sendmsg
            end
        else Scan Success
            wm_github -> wmodules : wm_state_io (WM_IO_WRITE)
            wm_github <-- wmodules
        end
    end
@enduml
```
![image](https://user-images.githubusercontent.com/41765669/127372176-ff64fc16-d0e0-4d82-a097-6fd9354c65ba.png)
