### ISSUE TITLE
Analyze and test how much memory Office365 integration occupies

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#9318]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.0 | Office365 module | Agent | Sources | All |

## Goal

Find out how much memory the component might take.

# Tasks

Explain with diagrams and descriptions in markdown files, and put it in the wazuh / architecture directory an explanation of the operation and calculations of how much the peak(stressed) and post-peak consumption would be left in memory in standby.

- [x] Create functionality diagrams.
- [x] Create features description.
- [x] Analyze memory consumption peak and post peak (standby) - Linux
- [x] Analyze memory consumption peak and post peak (standby) - Windows

Help yourself with tools like `massif`.

## Components that take a variable amount of memory

- Configuration structure (including `auth` and `subscription` blocks).
- Tenant/subscription fails structure.
- Message payload sent to manager.
- Next page URL.
- Access token.
- HTTP request.
- HTTP response.

## Test conditions

- The agent shall be connected to a manager (real or fake).
- Configure at less 10 tenants with all 5 subscriptions.
- Mock the response of the Office365 API.
- Simulate successful cases with responses near to 1MB (maximum allowed by default).
- Simulate error cases with responses over 1MB (maximum allowed by default).
- Simulate other error cases.
- Simulate responses with many next pages.
- After the stressing stage, leave the agent idle for 10 minutes (at less).

**Comment by Nicogp** [comment]
**Tests single tenant**
_Execution time per test case_: 1Hr
_Module configuration_:
```
<office365>
	<enabled>yes</enabled>
	<interval>1m</interval>
	<curl_max_size>1M</curl_max_size>
	<only_future_events>yes</only_future_events>
	<api_auth>
    	<tenant_id>test</tenant_id>
    	<client_id>test</client_id>
    	<client_secret>test</client_secret>
	</api_auth>
	<subscriptions>
    	   <subscription>Audit.AzureActiveDirectory</subscription>
    	   <subscription>Audit.Exchange</subscription>
    	   <subscription>Audit.SharePoint</subscription>
    	   <subscription>Audit.General</subscription>
    	   <subscription>DLP.All</subscription>
	</subscriptions>
</office365>
```

_Error getting token:_
![error-get-token](https://user-images.githubusercontent.com/13004400/126563141-0c633fe1-8c5f-4654-b8ba-fcbd6e4081dc.png)

_Error starting subscription:_
![error-start-subscription](https://user-images.githubusercontent.com/13004400/126563376-f171bb5a-7dd3-4bbc-97bc-94787e70ebb8.png)

_Error getting blobs:_
![error-get-blobs](https://user-images.githubusercontent.com/13004400/126563634-48c04c73-e475-4e54-8e27-1a8819169d58.png)

_Error getting logs, response over 1MB:_
![error-get-logs-res-over-1MB](https://user-images.githubusercontent.com/13004400/126563859-7623f432-10db-484f-a07b-4fcb06e976d3.png)

**Comment by Nicogp** [comment]
**Note:**
Sometimes we can see a graph like the following
![img-ct](https://user-images.githubusercontent.com/13004400/126720189-2d45e516-a4a3-456b-b6ba-07de1b5c76ae.png)

In which the total memory is less than the memory of the components, this is because there is a higher sampling frequency in the total memory, obtaining a more precise value. While the value of each component is maintained until a new value of the component is obtained, producing the slopes in the lines as we see in the graph.

**Comment by Nicogp** [comment]
Sample time span: 12 minutes aprox.
1 Tenant.
880 json events.
Collection interval 1 minute.

Command to collect:
`iotop -b -p PROCESSID > sample.txt`

ossec.conf
```
<office365>
    <enabled>yes</enabled>
    <interval>1m</interval>
    <curl_max_size>1M</curl_max_size>
    <only_future_events>yes</only_future_events>
    <api_auth>
        <tenant_id>test</tenant_id>
        <client_id>test</client_id>
        <client_secret>test</client_secret>
    </api_auth>
    <subscriptions>
    	<subscription>Audit.AzureActiveDirectory</subscription>
    	<subscription>Audit.Exchange</subscription>
    	<subscription>Audit.SharePoint</subscription>
    	<subscription>Audit.General</subscription>
    	<subscription>DLP.All</subscription>
   </subscriptions>
</office365>
```

Case 1: Only office365 configuration
![office365disk](https://user-images.githubusercontent.com/13004400/126918155-e67bc556-10e8-486f-acf0-966d5b417e50.JPG)

Sample file:
[DiskStatusOffice365.xlsx](https://github.com/wazuh/wazuh/files/6874780/DiskStatusOffice365.xlsx)


Office365 module write disk to save bookmarks event collection. Write disk frecuency will depends on time configuration.

**Comment by Nicogp** [comment]
**Test winagent**
Sample time span: 15 minutes aprox.
1 tenant.
5 subscriptions.
880 json events per subscription.
Collection interval 1 minute.

<office365>
    <enabled>yes</enabled>
    <interval>1m</interval>
    <curl_max_size>1M</curl_max_size>
    <only_future_events>yes</only_future_events>
    <api_auth>
        <tenant_id>test</tenant_id>
        <client_id>test</client_id>
        <client_secret>test</client_secret>
    </api_auth>
    <subscriptions>
    	<subscription>Audit.AzureActiveDirectory</subscription>
    	<subscription>Audit.Exchange</subscription>
    	<subscription>Audit.SharePoint</subscription>
    	<subscription>Audit.General</subscription>
    	<subscription>DLP.All</subscription>
   </subscriptions>
</office365>

Command to collect events:
```
(Using Wpr.exe)
* wpr.exe -HeapTracingConfig wazuh-agent.exe enable
* Stop win-agent
* wpr.exe -start Heap -filemode
* Start win-agent
* Test the scenario.
* wpr.exe -stop C:\Users\workspace\integration-github\wpa\testGithub.etl
* wpr.exe -HeapTracingConfig wazuh-agent.exe disable
```

![win-agent](https://user-images.githubusercontent.com/13004400/127257338-e72b235e-1910-496a-a256-587f29e3029e.PNG)

Used Windows Performance Analyzer to visualize it.

**Comment by Nicogp** [comment]
```
@startuml wm_office365
box "Office365 Module" #LightBlue
participant main
participant wmodules
participant config
participant wmodules_office365
participant thread
participant wm_office365
participant mq_op
end box

activate main #Red
main -> wmodules : wm_config()
wmodules -> config : ReadConfig()
config -> config : read_main_elements()
config -> config : Read_Office365()
config -> wmodules_office365 : wm_office365_read()
config <-- wmodules_office365
wmodules <-- config
main <-- wmodules

main -> thread ++ #Red : CreateThreadJoinable()
main <-- thread
thread -> wm_office365 : wm_office365_main (config) 
wm_office365 -> mq_op : StartMQ()
wm_office365 <-- mq_op


database office365_API
wm_office365 -> wm_office365 : wm_office365_execute_scan (initial_scan TRUE)
rnote over wm_office365, office365_API: **Scan Block**
loop
    wm_office365 -> time : sleep(office365_config->interval)
    wm_office365 -> wm_office365 : wm_office365_execute_scan (initial_scan FALSE)
    rnote over wm_office365, office365_API: **Scan Block**
end
@enduml wm_office365
```

![office_365_1](https://user-images.githubusercontent.com/13004400/127397461-b42e7457-884d-4c0f-981b-dc362333d94d.png)

**Comment by Nicogp** [comment]
```
@startuml wm_office365
box "Scan Block \n wm_office365_execute_scan() Sequence Diagram" #LightBlue
participant wm_office365
participant wmodules
participant url
end box

activate wm_office365
loop for every tenant
    alt not initial_scan or not config only_future_events
        wm_office365 -> wm_office365 ++ #red : wm_office365_get_access_token()
        wm_office365 -> url ++ #red : wurl_http_request()
        database office365_API
        url --> office365_API ++ #red : HTTP_REQUEST
        office365_API --> url -- #red : response
        url --> wm_office365 -- #red : response
        deactivate wm_office365
    end

    loop for every subscription
        wm_office365 -> wmodules ++ #red : wm_state_io()
        wm_office365 <- wmodules -- #red

        alt no previous timestamp
            wm_office365 -> wmodules ++ #red: wm_state_io(tenant_state_name, WM_IO_WRITE, tenant_state_struc)
            wm_office365 <- wmodules -- #red
            rnote over wm_office365, wm_office365: **continue**
        end

        wm_office365 -> wm_office365 ++ #red: wm_office365_manage_subscription()
        wm_office365 -> url ++ #red: wurl_http_request()
        url --> office365_API ++ #red : HTTP_REQUEST
        office365_API --> url -- #red : response
        url --> wm_office365 -- #red : subscription_response
        deactivate wm_office365

        loop scan_time 
            rnote over wm_office365, wm_office365: The scan interval can be a maximum of 24 hours \nbut the user can configure a longer interval.\nSuccessive scans are performed
            loop !scan_finished
                wm_office365 -> wm_office365 ++ #red: wm_office365_get_content_blobs()
                wm_office365 -> url ++ #red: wurl_http_request()
                url --> office365_API ++ #red : HTTP_REQUEST
                office365_API --> url -- #red : response
                url --> wm_office365 -- #red : blobs_response
                wm_office365 -> wmodules ++ #red : wm_read_http_header_element()
                wm_office365 <- wmodules -- #red
                deactivate wm_office365
                alt if blobs list
                    loop for every blob
                        wm_office365 -> wm_office365 ++ #red : wm_office365_get_logs_from_blob()
                        wm_office365 -> url ++ #red : wurl_http_request()
                        url --> office365_API ++ #red : HTTP_REQUEST
                        office365_API --> url -- #red : response
                        url --> wm_office365 -- #red : logs_response
                        deactivate wm_office365
                        loop for every log
                            wm_office365 -> wmodules ++ #red : wm_sendmsg(event)
                            wm_office365 <- wmodules -- #red
                        end
                    end
                end
            end

            alt if scan fails
                wm_office365 -> wm_office365 ++ #red: wm_office365_scan_failure_action()
                deactivate wm_office365
            else
                wm_office365 -> wmodules ++ #red : wm_state_io(tenant_state_name, WM_IO_WRITE, tenant_state_struc)
                wm_office365 <- wmodules -- #red
                deactivate wm_office365
            end
        end
    end
end
@enduml wm_office365
```

![office_365_2](https://user-images.githubusercontent.com/13004400/127397644-aed9fed9-4cab-49cd-937b-e8ad59b1104c.png)
