### ISSUE TITLE
Improve AWS ruleset

### ISSUE THREAD

**Issue by JavierBejMen** [wazuh/wazuh#9341]
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.1.5 | Decoders/Rules | Add new |

## Description

We need to improve current Cloudtrial ruleset and compliance coverage, and we need to add ruleset for Eks and vpc flow logs modules logged through Cloudwatch.
## Tasks
- [ ] Add ruleset for AWS Eks:
  - [ ] Audit
  - [ ] Authenticator
- [ ] Add ruleset for AWS vpc-flow-log
- [ ] Expand current Cloudtrail ruleset and revisit compliance mappings

## Related

- [x] #9294

## Resources
- AWS Eks: https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html
