### ISSUE TITLE
Add rules for AWS Eks

### ISSUE THREAD

**Issue by JavierBejMen** [wazuh/wazuh#9367]
## Description
Rules must be develop for AWS Eks Authenticator and Audit modules.

## Tasks

- [ ] Authenticator rules
  - [x] Generic rules
  - [ ] Common security relevant use cases rules
  - [ ] Compliance and ATT&CK mappings
  - [ ] .ini testing files

- [ ] Audit rules
  - [x] Generic rules
  - [x] Common security relevant use cases rules
  - [ ] Compliance and ATT&CK mappings
  - [ ] .ini testing files

## Branch
https://github.com/wazuh/wazuh/tree/9367-add-aws-eks-rules

**Comment by JavierBejMen** [comment]
## Update
Added generic rule to group AWS Eks Audit events, to identify the event we use the json field `apiVersion` as this a mandatory field on every Eks Audit event, explained [here](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/). 
```xml
<rule id="100050" level="0">
    <decoded_as>json</decoded_as>
    <field name="apiVersion" type="pcre2">^audit\.k8s\.io\/v\d$</field>
    <description>AWS Eks Audit event</description>
</rule>
```
Added generic rule to group AWS Eks Authenticator events, we use the decoder `aws-eks-authenticator` to identy them.
```xml
<rule id="100150" level="0">
    <decoded_as>aws-eks-authenticator</decoded_as>
    <description>AWS Eks Authenticator event</desctiption>
</rule>
```

**Comment by JavierBejMen** [comment]
# Research
Audit logs
- https://www.cncf.io/wp-content/uploads/2020/08/Kubernetes-Audit-Log-__-Gold-Mine-For-Security-CNCF-Webinar.pdf
- https://qlinh.com/infosec/2020/09/30/threat-detection-with-kubernetes-audit-logs.html

**Comment by JavierBejMen** [comment]
## Update
Added AWS Eks Audit rules, covering config events, denied and allowed events and error events.
