### ISSUE TITLE
Adapt wpopenv function to receive both stdin and stdout/stderr options

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#9383]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2 | Shared | Manager/Agent | Packages/Sources | All |

### Description

The function `wpopenv` can receive any of the following flags:

- `W_BIND_STDOUT`: This is used to create a pipe so that the parent process is able to read messages that the child writes to `stdout`.
- `W_BIND_STDERR`: This is used to create a pipe so that the parent process is able to read messages that the child writes to `stderr`.
- `W_BIND_STDIN`: This is used to create a pipe so that the parent process is able to write messages that the child reads from`stdin`.

This function has the limitation that **only allows to create one pipe** (in or out).

The purpose of this issue is to extend the functionality of `wpopenv` to be able to create two pipes, in order to allow the communication between parent and child process in both ways.

Take into account that the structure `wfd_t` needs to be modified so now it contains two descriptors, one for input and one for output messages:

```
typedef struct wfd_t {
    FILE * file_in;
    FILE * file_out;
#ifdef WIN32
    PROCESS_INFORMATION pinfo;
#else
    pid_t pid;
#endif
    unsigned int append_pool:1;
} wfd_t;
```

### Subtasks

- [x] Adapt `wpopen` for UNIX.
- [x] Adapt `wpopen` for Windows.
- [x] Update unit tests for UNIX.
- [x] Update unit tests for Windows.
