### ISSUE TITLE
Windows Install and uninstall failure - 

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#9896]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.0-RC14 | Installer | Manager/Agent | Packages/Sources | Windows |

## Description

Steps to reproduce:
1- Install and register/start 4.1.5 agent with default configuration.
2- Wait until the file is created in the `ossec-agent/tmp` folder.
3- try Install 4.2.0

Result: Does not update.
Expected: Does update.

![image](https://user-images.githubusercontent.com/14300208/130741325-a7319f89-4e74-4e02-8365-8a0768491522.png)

### MSI log

```
Action start 2:48:01: InstallValidate.
MSI (s) (7C:40) [02:48:01:270]: Note: 1: 2318 2: C:\Program Files\ossec-agent\tmp\tmp_162987035429324294946307 
MSI (s) (7C:40) [02:48:01:270]: Note: 1: 2205 2:  3: Error 
MSI (s) (7C:40) [02:48:01:270]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 2318 
DEBUG: Error 2318:  File does not exist: C:\Program Files\ossec-agent\tmp\tmp_162987035429324294946307
MSI (s) (7C:40) [02:48:02:643]: Note: 1: 2205 2:  3: Error 
MSI (s) (7C:40) [02:48:02:643]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1709 
MSI (s) (7C:40) [02:48:02:643]: Product: Wazuh Agent -- The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2318. The arguments are: C:\Program Files\ossec-agent\tmp\tmp_162987035429324294946307, , 
```

## Tasks
- [x] RCA
- [x] Apply fix
- [x] Test Clean install
- [x] Test Upgrade (WinXP, Win7, Win8, Win10) when the file exists in the tmp folder.
- [x] Test uninstall (WinXP, Win7, Win8, Win10) when the file exists in the tmp folder.

**Comment by Dwordcito** [comment]
The problem occurs since temporary files are being evaluated before being elevated to administrator, which causes the install to validate to fail prior to the uninstallation of the previous version.

By taking this evaluation for the files contained in the TMP folder this is avoided.

This is since the installation sequence is:

- ValidateInstall
- UAC elevation.
- Remove the prior version.
- Install the new version.


https://docs.microsoft.com/en-us/windows/win32/msi/installvalidate-action
