### ISSUE TITLE
SPIKE - macOS debug symbols generation analysis

### ISSUE THREAD

**Issue by tinachoB** [wazuh/wazuh#9910]
## Description
This issue aims to get a better understanding of what it is needed for generating debug symbols under **macos** platform.

## DoD
- [x] binutils for getting gobjcopy tool: switch to dsymutil
- [x] PoC
- [x] Analysis evidence
- [x] Enable dumps generation on custom folder: cannot be done

### wazuh/wazuh
- [ ] https://github.com/wazuh/wazuh/issues/12622
- [ ] https://github.com/wazuh/wazuh/issues/12621
- [ ] wazuh/wazuh#12710
- [ ] wazuh/wazuh#12711
- [ ] wazuh/wazuh#12712
- [ ] wazuh/wazuh#12624
### wazuh/wazuh-packages
- [ ] wazuh/wazuh-packages#1328
### wazuh/wazuh-documentation
- [ ] wazuh/wazuh-documentation#4925
- [ ] wazuh/wazuh-documentation#4930
- [ ] wazuh/wazuh-documentation#4929
### wazuh/wazuh-jenkins
- [ ] Enable the creation of macos symbols compressed zip file
- [ ] Automatic deploy of macos symbols zip package to S3
- [ ] Enable coredump generation and crash report upload in every macOS CICD pipeline

**Comment by jnasselle** [comment]
# Spike results
## Creating debug symbols files
- Interoperability between lldb and gdb
- lldb as clang debugger
Compared to gdb  symbols files, dSYM files are bundles that contains for example

```
bash-3.2# find /var/ossec/bin/wazuh-logcollector.dSYM/ 
/var/ossec/bin/wazuh-logcollector.dSYM/
/var/ossec/bin/wazuh-logcollector.dSYM//Contents
/var/ossec/bin/wazuh-logcollector.dSYM//Contents/Info.plist
/var/ossec/bin/wazuh-logcollector.dSYM//Contents/Resources
/var/ossec/bin/wazuh-logcollector.dSYM//Contents/Resources/DWARF
/var/ossec/bin/wazuh-logcollector.dSYM//Contents/Resources/DWARF/wazuh-logcollector
```
```
dsymutil /var/ossec/bin/wazuh-logcollector
```
```
bash-3.2# dwarfdump --uuid /var/ossec/bin/wazuh-logcollector.dSYM/Contents/Resources/DWARF/wazuh-logcollector 
UUID: 73B9FC7E-4C2A-3D5C-9F4B-0AD7C918F0F3 (x86_64) /var/ossec/bin/wazuh-logcollector.dSYM/Contents/Resources/DWARF/wazuh-logcollector
bash-3.2# dwarfdump --uuid /var/ossec/bin/wazuh-logcollector                                                  
UUID: 73B9FC7E-4C2A-3D5C-9F4B-0AD7C918F0F3 (x86_64) /var/ossec/bin/wazuh-logcollector
```
References:
[[lldb-dev] Directories to search for separate debugging information
](https://lists.llvm.org/pipermail/lldb-dev/2012-November/001242.html)
## Removing debug symbols from binaries
```
strip -S
```
## Enabling core dump generation
## Deploying debug symbols files
## Postmortem coredump analysis
References:
https://developer.apple.com/documentation/xcode/adding-identifiable-symbol-names-to-a-crash-report#Locate-a-dSYM-Using-Spotlight
