### ISSUE TITLE
Add API controllers unit tests

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#9939]
Our current unit tests do not include any coverage for the API controllers as we can observe from https://github.com/wazuh/wazuh/issues/9877.

This issue aims to add new python unit tests for the API controllers located at [api/controllers](https://github.com/wazuh/wazuh/tree/master/api/api/controllers). The new unit tests should cover as much of the code as possible.

Lastly, the added tests should be included in the Jenkins package so the tests are automatically run in every Pull Request.

### Tasks:
- [x] api/controllers/active_response_controller.py
- [x] api/controllers/agent_controller.py
- [x] api/controllers/cdb_list_controller.py
- [x] api/controllers/ciscat_controller.py 
- [x] api/controllers/cluster_controller.py
- [x] api/controllers/decoder_controller.py
- [x] api/controllers/default_controller.py
- [x] api/controllers/experimental_controller.py
- [x] api/controllers/manager_controller.py
- [x] api/controllers/mitre_controller.py
- [x] api/controllers/overview_controller.py
- [x] api/controllers/rootcheck_controller.py
- [x] api/controllers/rule_controller.py
- [x] api/controllers/sca_controller.py
- [x] api/controllers/security_controller.py
- [x] api/controllers/syscheck_controller.py
- [x] api/controllers/syscollector_controller.py
- [x] api/controllers/task_controller.py
- [x] api/controllers/vulnerability_controller.py

**Comment by Kondent** [comment]
## Update
Started to work with `test_vulnerability_controller.py` but need to do more research about pytest and async. 
Im currently assembling new tests by steps, interleaving with research since there's no related unit test where I could take a look.
Im resuming later on with this.

Regards,
Alexis.

**Comment by Kondent** [comment]
## Update
Got an unit test schema for every controller. I just finished with `api/controllers/task_controller.py` and `api/controllers/vulnerability_controller.py`.
Currently working with `api/controllers/mitre_controller.py`, which is almost done. I'm trying to reuse code to treat it the most generic way I can.
Regards,
Alexis

**Comment by Kondent** [comment]
## Update
- Minor fixes were made on all unit test.
- Added multiple new modules, few still under development.

Regards,
Alexis

**Comment by Kondent** [comment]
## Update
Almost every module got its related unit test.
I'm currently working with `test_security_controller.py` at the moment.

Regards,
Alexis

**Comment by Kondent** [comment]
## Update
`test_security_controller.py` completed.
`test_agent_controller.py` almost done. I'm working with a particular endpoint, which its unit test is still under development, all other endpoints are covered with a related unit test.

Regards,
Alexis

**Comment by Kondent** [comment]
# Update
After opening it's PR (https://github.com/wazuh/wazuh/pull/10041) we discussed a refactor for these unit tests and I'm currently working on them. I left PR on draft.
This test modules are still under development (no refactored):
* `test_security_controller.py`
* `test_test_agent_controller.py`
* `test_mitre_controller.py`

All other tests have been refactored.

Regards,
Alexis

**Comment by Kondent** [comment]
# Update
`test_mitre_controller.py` updated with the discussed refactor.
`test_agents_controller.py` almost done, actual coverage  around 97%.

**Comment by Kondent** [comment]
# Update
I've done every unit test for each controller.
I left PR on draft for the moment, I'll fast-review all modules one more time before I ask for a Cross Review.

Regards,
Alexis
