### ISSUE TITLE
Standardize the behavior of the ``only_logs_after`` parameter in the external integration modules

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#9993]
|Component|
|---|
| External integration modules |

## Description

Currently, the behavior of the modules can become confusing since each one uses the `only_logs` parameter in a different way, for example, the AWS buckets do the following:

When there are no processed logs for a bucket and the module is configured to fetch them starting from a certain date, this works correctly using the [only_logs_after](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-s3.html#bucket-only-logs-after) option. For example, if we add this to the configuration: `<only_logs_after>2021-JUL-08</only_logs_after>`, all logs available as of 08/07/2021 will be parsed.

However, once there are logs processed, the option [only_logs_after](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-s3.html#bucket-only-logs-after) is ignored. In this case, the module always fetches logs from the date of the last parsed log, regardless of whether `<only_logs_after>` date is older or more recent.

## Expected behavior
There is a table with a detailed explanation of the behavior of every module under different use-cases and the desired behavior [down below](https://github.com/wazuh/wazuh/issues/9993#issuecomment-942189409).

## Tasks
- [x] Standardize AWS Buckets
- [x] Standardize AWS CloudWatch Logs
- [x] Standardize Google Cloud Buckets
- [x] Update the documentation
- [x] Changelog (`CHANGELOG.md`)

## Tests
- [x] AWS Cloudtrail Bucket
- [x] AWS Config Bucket
- [x] AWS VPCFlow Bucket
- [x] AWS Custom Bucket (Macie)
- [x] AWS Custom Bucket (NLB, ALB, CLB)
- [x] AWS Custom Bucket (Server Access)
- [x] AWS Server Access
- [x] AWS CloudWatch Logs
- [x] Test AWS Buckets specifying prefixes
- [x] Google Cloud Buckets
- [x] Test in agent

**Comment by noise-kngdm** [comment]
## Issue update
Since we discovered a critical bug on #10601 the development of this issue had to be delayed. After fixing that bug, there were several conflicts in the development branch that needed to be fixed prior to keep working on them. The [branch](https://github.com/wazuh/wazuh/tree/feature/9993-standardize-only-logs-after) has been rebased into master to integrate the latest additions to the module in it, and all the conflicts have been solved.  

As for the status of the development, we decided to change the behavior of the `CloudWatchLogs` module to take advantage of the fact that it can collect events from the past without processing duplicates, unlike the AWS buckets. The following code is the result of that rework, and its testing is almost finished.  

https://github.com/wazuh/wazuh/blob/d1898acab0e384ab3a819516ffbe5087b601a4dd/wodles/aws/aws_s3.py#L2900-L2923  

We will be working on the Google Cloud Buckets next to check if they comply with the desired behavior.

**Comment by noise-kngdm** [comment]
## Issue update
We finished testing that the `CloudWatchLogs` module was working as expected, and we've started working on the Google Cloud Buckets. Since the bucket we used for testing has been deleted, we had to create a new script to upload test log files to a bucket, and we're currently struggling with changing the creation date of a file in a procedural way.  

Once we can do that, we'll be able to write a PR with the changes made to the module.

**Comment by noise-kngdm** [comment]
## Issue update
While reviewing the behavior of the Google Cloud Storage buckets, I discovered a bug and reported it in #10756. After writing the fix, I tested it to check that it was working as expected, which it is.  

This development is only lacking the update of the Azure and the Google Cloud documentation to be ready for merging.

**Comment by noise-kngdm** [comment]
## Issue update
After having finished the documentation and while execution the final tests to check that everything is working fine, we realized that one of the cases wasn't working as expected with the Config bucket. The month and the day of the folder structure have no padding zero, for example we could have a folder like this: `wazuh-aws-wodle-config/AWSLogs/123456789012/Config/us-east-1/2020/7/1/ConfigHistory/`.  

This difference means that the file keys should be treated differently when comparing with the `only_logs_after` value which hasn't been considered until now. The fix is almost ready, and once we push it we will resume the testing and submit a PR.

**Comment by noise-kngdm** [comment]
## Issue update
We have finished standardizing the Config Buckets, and we are now working on the Google Cloud buckets, since we realized that there was a case where they weren't working as expected, that is, when no `only_logs_after` had been passed as a parameter and there was a `last_key` with a value set in at least a day in the past.  

To standardize the Config Buckets, we had to implement two different logics:
- Removing the leading zero of the day and the month of a zero-padded date. This is necessary to create the filters that will be passed to AWS.
- Adding the leading zero to a date stripped of it. This is necessary to be able to parse and compare the dates to choose the best suitable filter for each use-case.

To add these capabilities, we included this regex in the constructor of the `AWSConfigBucket` class:
https://github.com/wazuh/wazuh/blob/9133f895a341382053ed47d3fcfb3858aa55573b/wodles/aws/aws_s3.py#L1094-L1095  

We then overloaded the `marker_only_logs_after` and `marker_custom_date` methods to stripe the dates of the leading zero.

We won't be able to finish with the AWS Custom buckets until the [PR #10718](https://github.com/wazuh/wazuh/pull/10718) gets merged.

**Comment by noise-kngdm** [comment]
## Issue update
We have finished standardizing the Google Cloud Storage and adding almost all the necessary changes to the documentation. Now we must wait for https://github.com/wazuh/wazuh-documentation/pull/4126 to get merged to add a note in the Azure documentation.  

As for the development, we won't be able to test the rest of the AWS Custom Buckets until https://github.com/wazuh/wazuh/pull/10718 is merged.

**Comment by noise-kngdm** [comment]
## Issue update
Since https://github.com/wazuh/wazuh/pull/10718 has been merged, we have continued working on the issue. After rebasing the branch to get the recently added changes and solving all conflicts that appeared, we realized that the module wasn't continuing from the latest log collected if there was a gap of one day between it and the execution time. That's because of how the `AWSCustomBucket` overloads the `iter_regions_and_accounts` method:
https://github.com/wazuh/wazuh/blob/b1baffbd83ee7aa844c982c5027d96061f46b3ce/wodles/aws/aws_s3.py#L1940-L1945  

It will call the `iter_files_in_buckets` method using `None` as both the `aws_region` and `aws_account_id` parameters. Althought the `aws_region` is not needed by this type of buckets, the `aws_account_id` is indeed used by the `build_s3_filter_args` method to collect the key of the last log processed.
https://github.com/wazuh/wazuh/blob/b1baffbd83ee7aa844c982c5027d96061f46b3ce/wodles/aws/aws_s3.py#L717-L721  

Passing `self.account_id` would solve the problem, but we will test the different types of custom buckets to ensure that everything is working fine.

We have also found that the `ALB`, `CLB` and `NLB` buckets have the same flaw, and we're currently investigating why this happens and how to fix it.

**Comment by noise-kngdm** [comment]
## Issue update
We have recently discovered that the `ALB`, `CLB`, and `NLB` buckets weren't working as expected because they are using a wrong account ID to insert the log entries from the database.
That is due to how the `mark_completed` method has been overwritten by the `AWSCustomBucket` class.

https://github.com/wazuh/wazuh/blob/48cf83ccd964aecffd7f75d385088c9949b7b510/wodles/aws/aws_s3.py#L1957-L1973

The only differences between this method and the [original one](https://github.com/wazuh/wazuh/blob/48cf83ccd964aecffd7f75d385088c9949b7b510/wodles/aws/aws_s3.py#L562-L579) are that instead of using the `aws_account_id` passed as parameter it's using `self.aws_account_id`, and that the query doesn't have the `aws_region` parameter. The first difference should have been addressed by passing a different parameter to the parent's method instead of copy-pasting it, the second one is no problem, since in Python, when one of the specified placeholders doesn't exists it continues gracefully.

To correct the values inserted in the database by the  `ALB`, `CLB`, and `NLB` classes, we had to do something similar to what was proposed [here](https://github.com/wazuh/wazuh/issues/10597#issuecomment-957972303), that is, to rely on the parents' parent method instead of the parent one. We tested that and it's working fine.

We are currently waiting for https://github.com/wazuh/wazuh/pull/10811 to be merged in order to be able to finish with the rest of the AWS buckets.

**Comment by noise-kngdm** [comment]
## Issue update
We have decided to include this issue in the `4.3.0` release. While investigating #11183 we detected that the log keys weren't being properly collected from the database due to recent changes, and we fixed that in b8a07cd2f617d1b11f91da81b48e8044705161a6 by defining the following method:

https://github.com/wazuh/wazuh/blob/b8a07cd2f617d1b11f91da81b48e8044705161a6/wodles/aws/aws_s3.py#L564-L579

This method will be used to format the query that will be executed by the DBMS to get the last log processed by the module. Since the parameters that should be used were very class-dependent, we thought it was a better -and less error-prone- solution to call this method instead of copy-pasting the `build_s3_filter_args` method in all the classes that had any difference with how the query was defined in `AWSBucket`; and then overloading this method in the different class to consider its specific parameters.
https://github.com/wazuh/wazuh/blob/b8a07cd2f617d1b11f91da81b48e8044705161a6/wodles/aws/aws_s3.py#L768-L777
